// v3 patches — Form 2 Technical, part 2: Lesson 3 parts 1–5 (desert regions)
// Revised model (Sept 2026): only the points of the progression sheet, short bulleted points (one sentence each),
// definitions apart, pictures beside key points, the situation ends with the character's question, one question per slide.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  S05_L3_P1_Desert_Location_Types: {
    situation: 'In Garoua, Salma watches a film about the Sahara. She is surprised: the desert is not only sand, but also plains of stones and bare rocky mountains. Salma asks: "Where are the deserts of the world, what types are there, and why are they so dry?"',
    sitQA: [['What is the problem in the situation?', 'Salma does not know where deserts are, their types and why they are dry.'],
      ['What did Salma expect to see?', 'Only sand.'],
      ['What else did she see?', 'Plains of stones and bare rocky mountains.']],
    activities: [
      { sec: '1. LOCATION', img: 'deserts_world_big.png', caption: 'The hot deserts of the world.', q: 'Near which lines are most hot deserts found?', a: 'Near the Tropic of Cancer and the Tropic of Capricorn.', noProj: 'draw the tropics on the board.' },
      { sec: '2. TYPES', img: 'f2t_erg.jpg', caption: 'A sandy desert.', q: 'What is a desert of sand dunes called?', a: 'A sandy desert (erg).', noProj: 'describe sand dunes.' },
      { sec: '2. TYPES', img: 'f2t_reg.jpg', caption: 'A desert of stones.', q: 'What is this desert made of?', a: 'Stones: it is a stony desert (reg).', noProj: 'show a handful of gravel.' },
      { sec: '2. TYPES', img: 'f2t_rocky_desert.jpg', caption: 'A desert of bare rock.', q: 'What do we call a desert of bare rock?', a: 'A rocky desert (hamada).', noProj: 'describe bare rock.' },
      { sec: '3. CHARACTERISTICS', img: 'trade_wind_dry.png', caption: 'A wind that blows from the land.', q: 'Why does this wind bring no rain?', a: 'It comes from the land, so it is dry.', noProj: 'describe the Harmattan.' },
    ],
    action: 'Locate the deserts of the world on a map and explain why they are dry.',
    summary: [
      D([['Desert:', 'It is a region that receives less than 250 mm of rain per year.']]),
      { title: '1. Location', intro: 'Hot deserts are found near the tropics:',
        items: [['Africa:', 'The Sahara, the Kalahari and the Namib.', 'deserts_world_big.png', 'the hot deserts of the world'],
          ['Asia:', 'The Arabian and the Thar deserts.'],
          ['America:', 'The Atacama and the Mojave deserts.'],
          ['Australia:', 'The Great Australian Desert.']] },
      { title: '2. Types of Deserts', intro: 'There are the following types of deserts:',
        items: [['Hot deserts:', 'Hot all year, like the Sahara.'],
          ['Cold deserts:', 'Cold and dry, like the Gobi and Antarctica.'],
          ['Sandy desert (erg):', 'It is covered with sand dunes.', 'f2t_erg.jpg', 'a sandy desert'],
          ['Stony desert (reg):', 'It is covered with stones and gravel.', 'f2t_reg.jpg', 'a stony desert'],
          ['Rocky desert (hamada):', 'It is made of bare rock.']] },
      { title: '3. Characteristics and Causes', intro: 'Deserts are dry for the following reasons:',
        items: [['Dry winds:', 'The trade winds blow from the land and bring no rain.', 'trade_wind_dry.png', 'a dry wind from the land'],
          ['High pressure:', 'Dry air sinks near the tropics.'],
          ['Cold currents:', 'Cold sea currents give no rain on some coasts.'],
          ['Distance from the sea:', 'Wet sea winds do not reach the centre of continents.']] },
    ],
    hwAnswer: 'In March the days in Garoua are very hot, often above 40 °C. The nights are cooler, because the heat escapes at night when the sky is clear.',
  },
  S06_L3_P2_Desert_Climate: {
    situation: 'Oumarou, a lorry driver from Garoua, crosses the Sahara. In the day, the metal of his lorry is too hot to touch, but at night he needs a blanket. Oumarou asks: "Why is the desert so hot by day and so cold at night?"',
    sitQA: [['What is the problem in the situation?', 'Oumarou does not understand the great difference between day and night in the desert.'],
      ['How is the day?', 'Very hot.'],
      ['How is the night?', 'Cold.']],
    activities: [
      { sec: '1. RAINFALL', img: 'rain_compare_big.png', caption: 'Rainfall of Aswan and Garoua.', q: 'Which town gets almost no rain: Aswan or Garoua?', a: 'Aswan (about 2 mm per year).', noProj: 'write the numbers on the board.' },
      { sec: '1. RAINFALL', img: 'f2t_wadi_flood.jpg', caption: 'A sudden flood in a dry valley.', q: 'What does this sudden flood show about desert rain?', a: 'The rain is rare and irregular, but can be very heavy.', noProj: 'describe a sudden storm.' },
      { sec: '2. TEMPERATURE', img: 'aswan_temp_big.png', caption: 'Day and night temperatures of Aswan.', q: 'What is the difference between day and night in July?', a: '42 − 26 = 16 °C.', noProj: 'write the temperatures on the board.' },
      { sec: '2. TEMPERATURE', img: 'desert_night.gif', caption: 'Animation: the desert at night.', q: 'Why does the desert become cold at night?', a: 'There are no clouds, so the heat escapes.', noProj: 'compare a clear night and a cloudy night.' },
      { sec: '3. WINDS', img: 'f2t_sandstorm.jpg', caption: 'A sandstorm.', q: 'What is this?', a: 'A sandstorm.', noProj: 'describe a dusty day.' },
    ],
    action: 'Protect yourself from heat and sandstorms in dry areas.',
    summary: [
      D([['Daily range of temperature:', 'It is the difference between the day and the night temperatures.']]),
      { title: '1. Rainfall', intro: 'Desert rainfall has the following characteristics:',
        items: [['Very little rain:', 'Less than 250 mm per year.', 'rain_compare_big.png', 'rainfall of Aswan and Garoua'],
          ['Irregular rain:', 'It may not rain for years.'],
          ['Sudden storms:', 'Rare storms cause floods in dry valleys.']] },
      { title: '2. Temperature', intro: 'Desert temperatures have the following characteristics:',
        items: [['Very hot days:', 'Often more than 40 °C in summer.', 'aswan_temp_big.png', 'temperatures of Aswan'],
          ['Cold nights:', 'The heat escapes because there are no clouds.'],
          ['Large daily range:', 'Often 15 to 20 °C.']] },
      { title: '3. Winds and Humidity', intro: 'The air of the desert has the following characteristics:',
        items: [['Dry air:', 'The humidity is very low.'],
          ['Hot, dry winds:', 'Winds such as the Harmattan.'],
          ['Sandstorms:', 'Strong winds lift sand and dust.', 'f2t_sandstorm.jpg', 'a sandstorm']] },
    ],
    hwAnswer: 'Examples: the cactus stores water in its thick stem; the acacia has small leaves and long roots; the date palm has deep roots that reach underground water.',
  },
  S07_L3_P3_Desert_Soils_Vegetation: {
    situation: 'Fanta planted a mango tree and a small cactus in front of her house in Garoua. She forgot to water them for three months. In March, the mango tree was dead, but the cactus was still green. Fanta asks: "How can desert plants live with so little water?"',
    sitQA: [['What is the problem in the situation?', 'Fanta does not know how desert plants survive without water.'],
      ['Which plant died?', 'The mango tree.'],
      ['Which plant survived?', 'The cactus.']],
    activities: [
      { sec: '1. VEGETATION', img: 'f2t_desert_plants.jpg', caption: 'Desert plants.', q: 'Why are desert plants far apart?', a: 'There is very little water.', noProj: 'describe plants in the Far North.' },
      { sec: '1. VEGETATION', img: 'f2t_cactus.jpg', caption: 'A cactus.', q: 'How does the thick stem help the cactus?', a: 'It stores water.', noProj: 'show a cactus.' },
      { sec: '1. VEGETATION', img: 'desert_roots_big.png', caption: 'The roots of desert plants.', q: 'Why are the roots of desert plants so long?', a: 'To reach water deep underground.', noProj: 'draw long roots.' },
      { sec: '2. SOILS', img: 'f2t_salt_crust.jpg', caption: 'White salt on the ground.', q: 'Is salty soil good for crops?', a: 'No.', noProj: 'taste salty water.' },
      { sec: '2. SOILS', img: 'f2t_nile_fields.jpg', caption: 'Fields along the Nile.', q: 'Why are the fields green here, in the desert?', a: 'Water from the Nile makes the soil fertile.', noProj: 'show the Nile on a map.' },
    ],
    action: 'Use water carefully to help plants grow in dry lands.',
    summary: [
      D([['Xerophyte:', 'It is a plant adapted to very dry conditions.']]),
      { title: '1. Vegetation', intro: 'Desert plants have the following characteristics:',
        items: [['Few and scattered:', 'Plants grow far apart.', 'f2t_desert_plants.jpg', 'desert plants'],
          ['Water storage:', 'Cacti store water in thick stems.', 'f2t_cactus.jpg', 'a cactus'],
          ['Long roots:', 'Roots go deep to find water.', 'desert_roots_big.png', 'long roots'],
          ['Small leaves or spines:', 'They lose little water.'],
          ['Short life cycle:', 'Some plants grow and flower quickly after rain.']] },
      { title: '2. Soils', intro: 'Desert soils have the following characteristics:',
        items: [['Sandy or stony:', 'The soils are made of sand, gravel and rock.'],
          ['Little humus:', 'There are few plants to rot.'],
          ['Salty crusts:', 'The sun dries the soil and leaves salt.', 'f2t_salt_crust.jpg', 'a salt crust'],
          ['Fertile with water:', 'Irrigated soils can be productive.']] },
    ],
    hwAnswer: 'Examples: lack of water (carry water and drink often); heat by day and cold at night (wear loose clothes by day and warm clothes at night); sandstorms (cover the face and shelter).',
  },
  S08_L3_P4_Desert_Problems_Adaptations: {
    situation: 'A Tuareg family lives in the Sahara, in Niger. Their well is dry, and there is no grass for their camels and goats. The father asks: "How can my family survive in this hard place?"',
    sitQA: [['What is the problem in the situation?', 'The family lacks water and grass and must adapt to survive.'],
      ['Where does the family live?', 'In the Sahara, in Niger.'],
      ['What animals do they have?', 'Camels and goats.']],
    activities: [
      { sec: '1. PROBLEMS FACED', img: 'f2t_desert_well.jpg', caption: 'A well in the desert.', q: 'What is the biggest problem in the desert?', a: 'The lack of water.', noProj: 'describe a dry well.' },
      { sec: '1. PROBLEMS FACED', img: 'f2t_moving_sand.jpg', caption: 'Moving sand.', q: 'What can moving sand cover?', a: 'Roads, wells and fields.', noProj: 'describe sand after a windy day.' },
      { sec: '2. ADAPTATIONS', img: 'f2t_camels.jpg', caption: 'Camels.', q: 'Why is the camel called the "ship of the desert"?', a: 'It can walk for days without water and carry heavy loads.', noProj: 'describe a camel.' },
      { sec: '2. ADAPTATIONS', img: 'f2t_tuareg.jpg', caption: 'Tuareg people.', q: 'Why do desert people wear long, loose clothes and a turban?', a: 'To protect the body from the sun and the sand.', noProj: 'describe the clothes of herders in the North.' },
      { sec: '2. ADAPTATIONS', img: 'f2t_desalination.jpg', caption: 'A water plant by the sea.', q: 'How do rich desert countries get drinking water from the sea?', a: 'They remove the salt from sea water.', noProj: 'taste salty water.' },
    ],
    action: 'Learn from desert peoples how to save water and adapt to heat.',
    summary: [
      D([['Adaptation:', 'It is the way people change their way of life to live in an environment.'],
        ['Nomad:', 'It is a person who moves from place to place with his animals.']]),
      { title: '1. Problems Faced', intro: 'People in hot deserts face the following problems:',
        items: [['Lack of water:', 'Wells and rivers are few.', 'f2t_desert_well.jpg', 'a desert well'],
          ['Extreme temperatures:', 'Very hot days and cold nights.'],
          ['Sandstorms and moving sand:', 'They bury roads, wells and fields.', 'f2t_moving_sand.jpg', 'moving sand'],
          ['Poor soils:', 'Few crops can grow.'],
          ['Isolation:', 'Towns are far apart.']] },
      { title: '2. Adaptations', intro: 'People adapt in the following ways:',
        items: [['Nomadism:', 'Nomads move with camels and goats to find water and grass.', 'f2t_camels.jpg', 'camels'],
          ['Clothes:', 'Long, loose clothes and turbans.', 'f2t_tuareg.jpg', 'Tuareg people'],
          ['Houses:', 'Thick mud walls and small windows keep houses cool.'],
          ['Water:', 'Deep wells, boreholes and desalination.'],
          ['Irrigation:', 'Farming in oases and along rivers.']] },
    ],
    hwAnswer: 'Examples: Siwa oasis in Egypt; Tafilalt oasis in Morocco; Kufra oasis in Libya; Bilma oasis in Niger.',
  },
  S09_L3_P5_Desert_Farming_Oases: {
    situation: 'In the middle of the Sahara, travellers see a green place with tall palm trees and gardens, while all around there is only sand. Musa asks: "How can crops grow in the middle of the desert?"',
    sitQA: [['What is the problem in the situation?', 'Musa does not know how farming is possible in the desert.'],
      ['What did the travellers see?', 'Palm trees and gardens.'],
      ['What is around this green place?', 'Only sand.']],
    activities: [
      { sec: '1. OASES', img: 'f2t_oasis.jpg', caption: 'A green place in the desert.', q: 'What do we call this green place in the desert?', a: 'An oasis.', noProj: 'describe a green place in a dry area.' },
      { sec: '1. OASES', img: 'oasis_big.png', caption: 'How an oasis is formed.', q: 'Where does the water of the oasis come from?', a: 'From rain on far hills that moves under the ground.', noProj: 'draw water under the sand.' },
      { sec: '2. OASIS FARMING', img: 'oasis_layers_big.png', caption: 'Layers of crops in an oasis.', q: 'Why do farmers grow crops under the palms?', a: 'The palms give shade and keep the soil wet.', noProj: 'draw three layers.' },
      { sec: '3. IRRIGATION', img: 'f2t_shaduf.jpg', caption: 'Lifting water.', q: 'What does this farmer use to lift water?', a: 'A shaduf.', noProj: 'describe a bucket on a pole.' },
      { sec: '3. IRRIGATION', img: 'f2t_pivot.jpg', caption: 'Modern irrigation.', q: 'Where do modern farmers get water in the desert?', a: 'From deep wells (boreholes).', noProj: 'describe a borehole.' },
    ],
    action: 'Use irrigation water carefully so that it lasts.',
    summary: [
      D([['Oasis:', 'It is a green, fertile place in a desert where water is found.'],
        ['Irrigation:', 'It is bringing water to crops.']]),
      { title: '1. Formation of Oases', intro: 'Oases are formed as follows:',
        items: [['Rain on far hills:', 'Rain sinks into the rocks.', 'oasis_big.png', 'how an oasis forms'],
          ['Underground water:', 'The water moves under the desert.'],
          ['Water at the surface:', 'It comes up in a low place and forms an oasis.']] },
      { title: '2. Farming around Oases', intro: 'Oasis farming has the following characteristics:',
        items: [['Date palms:', 'The top layer gives dates and shade.', 'oasis_layers_big.png', 'crops in an oasis'],
          ['Fruit trees:', 'The middle layer gives oranges, figs and olives.'],
          ['Vegetables and cereals:', 'The lower layer gives wheat, barley and vegetables.'],
          ['Animals:', 'Goats, camels and sheep.']] },
      { title: '3. Irrigation in Deserts', intro: 'Water is brought to crops in the following ways:',
        items: [['Shaduf:', 'A pole with a bucket lifts water.', 'f2t_shaduf.jpg', 'a shaduf'],
          ['Wells and boreholes:', 'Pumps lift underground water.'],
          ['Dams and canals:', 'The Aswan Dam stores Nile water for the fields.'],
          ['Modern sprinklers:', 'Centre-pivot machines water large fields.', 'f2t_pivot.jpg', 'modern irrigation']] },
    ],
    hwAnswer: 'Examples: France, Italy, Germany, the United Kingdom, the USA, Japan and China all lie between 30° and 60° N.',
  },
};
