// v3 patches — Form 2 Technical, part 1: Lesson 1 (equatorial problems), Lesson 2 parts 1–5 (tropical grassland)
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  FORM2TECH_LESSON1_WEEK7_Problems_Solutions: {
    secs: ['1. PROBLEMS FACED BY MAN', '1. PROBLEMS FACED BY MAN', '2. PROBLEMS CAUSED BY MAN', '2. PROBLEMS CAUSED BY MAN', '3. ATTEMPTED SOLUTIONS'],
    action: 'Plant trees and protect the forest and its animals.',
    summary: [
      D([['Deforestation:', 'It is the cutting down of forests.'],
        ['Soil erosion:', 'It is the washing away of soil by rain or wind.'],
        ['Conservation:', 'It is the protection of nature for the future.']]),
      { title: '1. Problems Faced by Man', intro: 'People in the equatorial region face the following problems:',
        items: [['Transport:', 'Heavy rain makes the roads muddy and hard to use.'],
          ['Diseases:', 'Mosquitoes carry malaria in the hot and wet climate.'],
          ['The thick forest:', 'The dense forest is hard to clear for farms and roads.'],
          ['Poor soils:', 'Heavy rain washes the plant food out of the soil.']] },
      { title: '2. Problems Caused by Man', intro: 'People cause the following problems in the equatorial region:',
        items: [['Deforestation:', 'People cut too many trees for timber and farms.'],
          ['Soil erosion:', 'Rain washes away the soil left bare after cutting trees.'],
          ['Loss of animals:', 'Animals such as gorillas and elephants become rare.'],
          ['Water pollution:', 'Mining and waste make the rivers dirty.']] },
      { title: '3. Attempted Solutions', intro: 'The following solutions have been attempted:',
        items: [['Reforestation:', 'People plant new trees where forests were cut.'],
          ['Protected areas:', 'National parks such as the Dja protect plants and animals.'],
          ['Selective logging:', 'Companies cut only some big trees and leave the young ones.'],
          ['Health care:', 'The government gives mosquito nets to fight malaria.']] },
    ],
    hwAnswer: 'Around Garoua there are grasses with trees far apart (savanna), not tall trees growing close together. In the dry season the grass is dry and many trees lose their leaves.',
  },
  FORM2TECH_LESSON2_WEEK8_Tropical_Grassland_Climate: {
    secs: ['1. MEANING AND LOCATION', '1. MEANING AND LOCATION', '2. CLIMATE', '2. CLIMATE', '2. CLIMATE'],
    action: 'Prepare for the dry season and protect yourself from Harmattan dust.',
    summary: [
      { title: '1. Meaning and Location', sub: 'A) Meaning', intro: 'The tropical grassland is defined as follows:',
        items: [['Savanna:', 'It is a region of tall grass with trees far apart, found between the forest and the desert.']] },
      { title: '1. Meaning and Location', sub: 'B) Location', intro: 'The savanna lies between about 5° and 15° north and south of the Equator:',
        items: [['Africa:', 'It covers West Africa including North Cameroon, East Africa and Southern Africa.'],
          ['South America:', 'It is found in the Llanos of Venezuela and the Campos of Brazil.'],
          ['Australia:', 'It is found in the north of Australia.']],
        draw: { img: 'savanna_africa_big.png', caption: 'the savanna in Africa' } },
      { title: '2. Characteristics of the Climate', intro: 'The climate of the savanna has the following characteristics:',
        items: [['Temperature:', 'It is hot all year, between about 20 °C and 33 °C.'],
          ['Seasons:', 'There is a wet season in summer and a dry season in winter.'],
          ['Rainfall:', 'The total rainfall is between 500 mm and 1,500 mm per year.'],
          ['Winds:', 'The dry and dusty Harmattan blows from the Sahara in the dry season.']] },
    ],
    hwAnswer: 'Answers vary. Trees like the mango and the neem keep their leaves, while many trees such as the shea tree and acacias lose them. In the dry season the grass is yellow and dry.',
  },
  S01_L2_P2_Tropical_Grassland_Soils_Vegetation: {
    secs: ['1. VEGETATION', '1. VEGETATION', '1. VEGETATION', '2. SOILS', '2. SOILS'],
    action: 'Avoid bush fires, which destroy plants and the humus of the soil.',
    summary: [
      D([['Deciduous tree:', 'It is a tree that loses its leaves in the dry season.'],
        ['Laterite:', 'It is a hard, red layer in the soil.'],
        ['Leaching:', 'It is the washing of plant food deep into the soil by rain.']]),
      { title: '1. Vegetation', intro: 'The vegetation of the savanna has the following characteristics:',
        items: [['Grass:', 'Tall grass grows up to 3 metres high in the wet season.'],
          ['Trees:', 'Trees such as the baobab, the acacia and the shea tree grow far apart.'],
          ['Deciduous trees:', 'Many trees lose their leaves in the dry season to save water.'],
          ['Thick bark:', 'Thick bark protects trees from bush fires.']] },
      { title: '2. Soils', intro: 'The soils of the savanna have the following characteristics:',
        items: [['Red soils:', 'They are red because of iron and are only fairly fertile.'],
          ['Laterite:', 'It is a hard layer used to make roads and bricks.'],
          ['Black cotton soils:', 'They are fertile clay soils that keep water well.'],
          ['Little humus:', 'The soils have little humus because bush fires burn the dead plants.']] },
    ],
    hwAnswer: 'Examples: food (maize, sorghum, groundnuts, shea butter); wood (firewood, charcoal, poles for building); animals (cattle, goats, meat and milk).',
  },
  S02_L2_P3_Tropical_Grassland_Resources: {
    secs: ['1. PASTURE', '2. FARMLAND', '3. WILDLIFE', '4. WATER', '5. TREES'],
    action: 'Use the resources of the savanna carefully so that they last.',
    summary: [
      D([['Resource:', 'It is anything in nature that people can use.'],
        ['Exploitation:', 'It is the use of a resource to meet our needs or to earn money.']]),
      { title: '1. Resources and Methods of Exploitation', intro: 'The savanna has the following resources:',
        items: [['Pasture:', 'The grass feeds cattle, sheep and goats kept by herders.'],
          ['Farmland:', 'Farmers use the land to grow cotton, maize and sorghum.'],
          ['Wildlife:', 'Animals in national parks such as the Benue attract tourists.'],
          ['Water:', 'Rivers and the Lagdo Dam give water, fish and electricity.'],
          ['Trees:', 'Trees give firewood, charcoal and shea butter.']] },
    ],
    hwAnswer: 'Answers vary. Example: a farmer produces cotton and maize with a hoe and oxen, and sells cotton to SODECOTON; a herder rears cattle, uses a stick and moves with them, and sells them at the cattle market.',
  },
  S03_L2_P4_Tropical_Grassland_Human_Activities: {
    secs: ['1. CROP FARMING', '1. CROP FARMING', '2. LIVESTOCK REARING', '2. LIVESTOCK REARING', '3. OTHER ACTIVITIES'],
    action: 'Respect the work of farmers and herders and help them live in peace.',
    summary: [
      D([['Cash crop:', 'It is a crop grown to be sold.'],
        ['Food crop:', 'It is a crop grown to feed the family.'],
        ['Transhumance:', 'It is the seasonal movement of herders with their animals.']]),
      { title: '1. Crop Farming', intro: 'Crop farming in the savanna takes the following forms:',
        items: [['Food crops:', 'Farmers grow sorghum, millet and maize to feed their families.'],
          ['Cash crops:', 'Farmers grow cotton and sell it to SODECOTON.'],
          ['Irrigated farming:', 'Rice is grown with irrigation at Lagdo and Yagoua.']] },
      { title: '2. Livestock Rearing', intro: 'Herders rear animals in three ways:',
        items: [['Nomadic herding:', 'Herders move from place to place with their animals.'],
          ['Transhumance:', 'Herders move south in the dry season and come back in the wet season.'],
          ['Ranching:', 'Cattle are kept on large farms, as on the Adamawa plateau.']] },
      { title: '3. Other Activities', intro: 'People also carry out the following activities:',
        items: [['Fishing:', 'People fish in the Lagdo lake and the Benue.'],
          ['Tourism:', 'Tourists visit national parks such as the Benue and Waza.'],
          ['Hunting:', 'People hunt in authorised hunting zones.']] },
    ],
    hwAnswer: 'Examples: rains that start late or stop early; bush fires that burn pastures; pests such as locusts and caterpillars; cattle that eat crops, which causes conflicts.',
  },
  S04_L2_P5_Tropical_Grassland_Problems_Solutions: {
    secs: ['1. PROBLEMS FACED', '1. PROBLEMS FACED', '1. PROBLEMS FACED', '1. PROBLEMS FACED', '2. ATTEMPTED SOLUTIONS'],
    action: 'Plant trees, avoid bush fires and respect grazing zones.',
    summary: [
      D([['Drought:', 'It is a long period without enough rain.'],
        ['Overgrazing:', 'It is when too many animals eat the grass of the same land.'],
        ['Desertification:', 'It is the spread of desert conditions into dry lands.']]),
      { title: '1. Problems Faced', intro: 'People in the savanna face the following problems:',
        items: [['Drought:', 'Crops and pastures dry up when the rains fail.'],
          ['Bush fires:', 'Fires destroy plants, animals and the humus of the soil.'],
          ['Soil erosion:', 'Rain and wind remove the bare soil.'],
          ['Farmer–herder conflicts:', 'Cattle eat crops and this causes conflicts between farmers and herders.']] },
      { title: '2. Attempted Solutions', intro: 'The following solutions have been attempted:',
        items: [['Irrigation:', 'Farmers bring water to their crops from rivers and dams.'],
          ['Tree planting:', 'Trees are planted to hold the soil and stop the desert.'],
          ['Firebreaks:', 'Cleared strips of land stop bush fires from spreading.'],
          ['Grazing zones:', 'Special zones for cattle keep them away from farms.']] },
    ],
    hwAnswer: 'The Sahara covers countries such as Algeria, Libya, Egypt, Niger, Mali and Chad.',
  },
};
