// v3 patches — Form 2 Technical, part 3: Lesson 4 parts 1–4 (temperate region)
// Revised model (Sept 2026): only the points of the progression sheet, short bulleted points (one sentence each),
// definitions apart, pictures beside key points, the situation ends with the character's question, one question per slide.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  S10_L4_P1_Temperate_Location_Types_Climate: {
    situation: 'Aïssatou\'s brother is going to study in France in January. He packs only T-shirts and sandals, but his mother says: "You need a thick coat, gloves and closed shoes. It is winter there." He asks: "Why is it cold in France when it is hot in Garoua?"',
    sitQA: [['What is the problem in the situation?', 'The brother does not know the climate of the temperate region.'],
      ['What did he pack?', 'T-shirts and sandals.'],
      ['What season is it in France in January?', 'Winter.']],
    activities: [
      { sec: '1. LOCATION', img: 'temperate_world_big.png', caption: 'The temperate regions of the world.', q: 'Between which latitudes are the temperate regions?', a: 'Between 30° and 60° north and south of the Equator.', noProj: 'draw the lines on the board.' },
      { sec: '2. TYPES', img: 'london_climate_big.png', caption: 'The climate of London.', q: 'Does it rain in every month in London?', a: 'Yes, it rains in every month.', noProj: 'write London\'s rainfall.' },
      { sec: '2. TYPES', img: 'f2t_mediterranean.jpg', caption: 'A sunny coast in summer.', q: 'Which temperate climate has hot, dry summers and mild, wet winters?', a: 'The Mediterranean climate.', noProj: 'name Mediterranean countries.' },
      { sec: '3. CLIMATE', img: 'four_seasons_big.png', caption: 'The seasons.', q: 'How many seasons does the temperate region have?', a: 'Four: spring, summer, autumn and winter.', noProj: 'write the four seasons.' },
      { sec: '3. CLIMATE', img: 'f2t_snow_city.jpg', caption: 'A street in winter.', q: 'What covers the street in winter?', a: 'Snow.', noProj: 'describe ice from a fridge.' },
    ],
    action: 'Compare the climate of temperate lands with the climate of Garoua.',
    summary: [
      D([['Temperate region:', 'It is the region with mild temperatures and four seasons, between 30° and 60° N and S.']]),
      { title: '1. Location', intro: 'The temperate regions are found in the following areas:',
        items: [['Northern Hemisphere:', 'Europe, North America, China and Japan.', 'temperate_world_big.png', 'the temperate regions'],
          ['Southern Hemisphere:', 'South Africa, southern Australia, New Zealand and Argentina.']] },
      { title: '2. Types', intro: 'There are three main types of temperate climate:',
        items: [['Mediterranean:', 'Hot, dry summers and mild, wet winters.', 'f2t_mediterranean.jpg', 'a Mediterranean coast'],
          ['Cool temperate western margin:', 'Mild and rainy all year, like London.', 'london_climate_big.png', 'the climate of London'],
          ['Cool temperate continental:', 'Warm summers and very cold winters, like Moscow.']] },
      { title: '3. Characteristics of the Climate', intro: 'The temperate climate has the following characteristics:',
        items: [['Four seasons:', 'Spring, summer, autumn and winter.', 'four_seasons_big.png', 'the four seasons'],
          ['Mild temperatures:', 'Warm summers and cool or cold winters.'],
          ['Rain:', 'Rain falls in all seasons in most places.'],
          ['Snow:', 'Snow falls in winter in cold areas.']] },
    ],
    hwAnswer: 'In autumn the leaves turn yellow, orange, red and brown; in winter they fall and the trees stand bare until spring.',
  },
  S11_L4_P2_Temperate_Soils_Vegetation: {
    situation: 'On a trip to Europe in November, Samuel sees a forest with yellow and red leaves falling to the ground. In January, the trees have no leaves at all, but some pine trees are still green. Samuel asks: "Why do some trees lose their leaves in winter and others do not?"',
    sitQA: [['What is the problem in the situation?', 'Samuel does not know how temperate plants are adapted to winter.'],
      ['What colour are the leaves in November?', 'Yellow and red.'],
      ['Which trees are still green in January?', 'Pine trees (conifers).']],
    activities: [
      { sec: '1. VEGETATION', img: 'f2t_autumn_forest.jpg', caption: 'A forest in autumn.', q: 'Why do these trees lose their leaves in autumn?', a: 'To survive the cold winter.', noProj: 'describe dry-season trees.' },
      { sec: '1. VEGETATION', img: 'f2t_conifer.jpg', caption: 'Conifers with needle leaves.', q: 'How do needle leaves help conifers in winter?', a: 'They lose little water, and the snow slides off.', noProj: 'draw a needle leaf.' },
      { sec: '1. VEGETATION', img: 'f2t_olive_tree.jpg', caption: 'An olive tree.', q: 'How do small, hard leaves help the olive tree in the dry summer?', a: 'They lose little water.', noProj: 'show olive oil.' },
      { sec: '1. VEGETATION', img: 'f2t_prairie.jpg', caption: 'A grassland.', q: 'Why are there almost no trees here?', a: 'There is too little rain for trees.', noProj: 'describe a grassland.' },
      { sec: '2. SOILS', img: 'f2t_black_soil.jpg', caption: 'A black soil.', q: 'Why is this black soil good for wheat?', a: 'It is full of humus, so it is very fertile.', noProj: 'show dark garden soil.' },
    ],
    action: 'Recognise the products of temperate forests and soils in our markets.',
    summary: [
      D([['Deciduous tree:', 'It is a tree that loses its leaves in one season.'],
        ['Conifer:', 'It is a tree with needle leaves and cones.']]),
      { title: '1. Vegetation', intro: 'The temperate region has the following vegetation:',
        items: [['Deciduous forests:', 'Oak and beech lose their leaves in autumn.', 'f2t_autumn_forest.jpg', 'a forest in autumn'],
          ['Coniferous forests:', 'Pine and fir keep their needle leaves.', 'f2t_conifer.jpg', 'conifers'],
          ['Mediterranean vegetation:', 'Olive trees and shrubs with small, hard leaves.'],
          ['Temperate grasslands:', 'Prairies and steppes with few trees.', 'f2t_prairie.jpg', 'a temperate grassland']] },
      { title: '2. Soils', intro: 'The temperate region has the following soils:',
        items: [['Brown forest soils:', 'Fertile soils under deciduous forests.'],
          ['Podzols:', 'Grey, acid soils under conifers.'],
          ['Black soils (chernozems):', 'Very fertile grassland soils, good for wheat.', 'f2t_black_soil.jpg', 'a black soil'],
          ['Red Mediterranean soils:', 'Soils good for olives and grapes.']] },
    ],
    hwAnswer: 'Examples: wheat flour (from France or Canada), powdered milk (from Europe), apples (from France or South Africa), frozen chicken and onions (from Europe).',
  },
  S12_L4_P3_Temperate_Farming: {
    situation: 'In a shop in Garoua, Blaise sees wheat flour from France, milk powder from the Netherlands and olive oil from Spain. Blaise asks: "How do these countries produce so much food?"',
    sitQA: [['What is the problem in the situation?', 'Blaise does not know the types of farming in the temperate region.'],
      ['Name one product from France.', 'Wheat flour.'],
      ['Name one product from the Netherlands.', 'Milk powder.']],
    activities: [
      { sec: '1. TYPES OF FARMING', img: 'f2t_mixed_farm.jpg', caption: 'Crops and animals on one farm.', q: 'What is this type of farming called?', a: 'Mixed farming.', noProj: 'describe a farm with crops and animals.' },
      { sec: '1. TYPES OF FARMING', img: 'f2t_dairy.jpg', caption: 'Cows reared for milk.', q: 'What is the rearing of cows for milk called?', a: 'Dairy farming.', noProj: 'name milk products.' },
      { sec: '1. TYPES OF FARMING', img: 'f2t_combine.jpg', caption: 'A machine harvests wheat.', q: 'Why can one farmer in Canada grow so much wheat?', a: 'He uses big machines on a huge farm.', noProj: 'compare with a hoe.' },
      { sec: '1. TYPES OF FARMING', img: 'f2t_ranch.jpg', caption: 'Sheep on a huge farm.', q: 'What are huge animal farms called?', a: 'Ranches.', noProj: 'compare with herding in the North.' },
      { sec: '1. TYPES OF FARMING', img: 'f2t_vineyard.jpg', caption: 'A vineyard.', q: 'Name one crop of Mediterranean farming.', a: 'Grapes (also olives and oranges).', noProj: 'name fruits from Europe.' },
    ],
    action: 'Learn from modern farming methods to improve our own farms.',
    summary: [
      D([['Mixed farming:', 'It is growing crops and rearing animals on the same farm.'],
        ['Mechanisation:', 'It is the use of machines on farms.']]),
      { title: 'Farming in the Temperate Region', intro: 'The main types of farming and the reasons for their productivity are the following:',
        items: [['Mixed farming:', 'Crops and animals in Western Europe.', 'f2t_mixed_farm.jpg', 'mixed farming'],
          ['Dairy farming:', 'Milk, butter and cheese in the Netherlands and Denmark.', 'f2t_dairy.jpg', 'dairy farming'],
          ['Wheat farming:', 'Huge wheat farms with machines in Canada and Ukraine.', 'f2t_combine.jpg', 'harvesting wheat'],
          ['Ranching:', 'Cattle and sheep on huge farms in Australia and Argentina.'],
          ['Mediterranean farming:', 'Grapes, olives and oranges in Spain and Italy.', 'f2t_vineyard.jpg', 'a vineyard'],
          ['Why it is productive:', 'Machines, fertilisers and good seeds give high yields.']] },
    ],
    hwAnswer: 'Examples: snow and ice block roads and cause accidents; it is very cold, so people must pay for heating; days are short and dark; water pipes can freeze.',
  },
  S13_L4_P4_Temperate_Problems_Adaptations: {
    situation: 'In January, heavy snow falls on a village in Canada. The roads are blocked, the water pipes freeze and the farmer cannot take his cows out. The farmer asks: "How can we live and farm with such a hard winter?"',
    sitQA: [['What is the problem in the situation?', 'The farmer faces the problems of winter and must adapt.'],
      ['What blocks the roads?', 'Snow.'],
      ['What happens to the water pipes?', 'They freeze.']],
    activities: [
      { sec: '1. PROBLEMS FACED', img: 'f2t_snowplough.jpg', caption: 'A machine on a snowy road.', q: 'How do people clear roads blocked by snow?', a: 'With machines (snowploughs).', noProj: 'describe a blocked road.' },
      { sec: '1. PROBLEMS FACED', img: 'f2t_dust_bowl.jpg', caption: 'A dust storm on farms.', q: 'What did the wind do to the dry soil of these farms?', a: 'It blew it away.', noProj: 'describe dust in the Harmattan.' },
      { sec: '1. PROBLEMS FACED', img: 'f2t_forest_fire.jpg', caption: 'A forest fire.', q: 'Why are there forest fires in Mediterranean summers?', a: 'Summers are hot and dry, so plants burn easily.', noProj: 'compare with bush fires.' },
      { sec: '2. ADAPTATIONS', img: 'f2t_greenhouse.jpg', caption: 'A greenhouse.', q: 'How can farmers grow vegetables when it is too cold outside?', a: 'In greenhouses, where it is warm.', noProj: 'describe a closed car in the sun.' },
      { sec: '2. ADAPTATIONS', img: 'f2t_shelterbelt.jpg', caption: 'Lines of trees around fields.', q: 'Why do farmers plant lines of trees around their fields?', a: 'To stop the wind from blowing the soil away.', noProj: 'describe a hedge.' },
    ],
    action: 'Protect the soil from wind with lines of trees, as temperate farmers do.',
    summary: [
      D([['Greenhouse:', 'It is a glass or plastic house where plants are grown in warm conditions.'],
        ['Shelter belt:', 'It is a line of trees that protects fields from the wind.']]),
      { title: '1. Problems Faced', intro: 'People in the temperate region face the following problems:',
        items: [['Cold winters:', 'Snow and ice block roads and freeze pipes.', 'f2t_snowplough.jpg', 'clearing snow'],
          ['Short growing season:', 'Crops cannot grow in winter.'],
          ['Soil erosion by wind:', 'Dry soil is blown away, as in the Dust Bowl.'],
          ['Summer droughts and fires:', 'Hot, dry summers in Mediterranean lands.', 'f2t_forest_fire.jpg', 'a forest fire']] },
      { title: '2. Adaptations', intro: 'People adapt in the following ways:',
        items: [['Houses:', 'Heated houses with thick walls and double windows.'],
          ['Clothes:', 'Thick coats, gloves and boots in winter.'],
          ['Transport:', 'Snowploughs and salt on the roads.'],
          ['Greenhouses:', 'Vegetables grow in warm glasshouses.', 'f2t_greenhouse.jpg', 'a greenhouse'],
          ['Shelter belts and irrigation:', 'Trees stop the wind, and irrigation helps in summer.', 'f2t_shelterbelt.jpg', 'a shelter belt']] },
    ],
    hwAnswer: 'Examples: farmer, trader, teacher, mechanic, tailor, moto-taxi driver, nurse, carpenter.',
  },
};
