// v3 patches — Form 2 Technical, part 4: Lesson 5 parts 1–6 (sectors of the economy)
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  S14_L5_P1_Sectors_Introduction: {
    secs: ['DEFINITIONS', 'DEFINITIONS', 'DEFINITIONS', '1. THE FOUR SECTORS', '1. THE FOUR SECTORS'],
    action: 'Value every job, because each sector depends on the others.',
    summary: [
      D([['Economy:', 'It is all the work people do to produce, sell and buy goods and services.'],
        ['Goods:', 'They are things we can touch, such as food and clothes.'],
        ['Services:', 'They are work done for other people, such as teaching and transport.'],
        ['Raw material:', 'It is a natural product used to make goods, such as cotton.'],
        ['Sector:', 'It is a group of jobs of the same kind.']]),
      { title: '1. The Four Sectors of the Economy', intro: 'The economy is divided into four sectors:',
        items: [['Primary sector:', 'It takes products from nature, such as cotton from the farm.'],
          ['Secondary sector:', 'It turns raw materials into goods, such as cloth made from cotton.'],
          ['Tertiary sector:', 'It gives services, such as selling and transporting the cloth.'],
          ['Quaternary sector:', 'It creates knowledge, such as research on better cotton seeds.']],
        draw: { img: 'cotton_journey_last.png', caption: 'the journey of cotton through the sectors' } },
    ],
    hwAnswer: 'Example: a SODECOTON worker has a contract, a monthly salary and CNPS insurance, while a moto-taxi driver works alone, earns money daily and has no contract or pension.',
  },
  S15_L5_P2_Formal_Informal_Sectors: {
    secs: ['1. THE FORMAL SECTOR', '1. THE FORMAL SECTOR', '2. THE INFORMAL SECTOR', '2. THE INFORMAL SECTOR', '3. COMPARISON'],
    action: 'Encourage small workers to register their work and join the CNPS.',
    summary: [
      D([['Formal sector:', 'It is work that is registered with the state and pays taxes.'],
        ['Informal sector:', 'It is small work that is not registered with the state.'],
        ['Pension:', 'It is money paid to a worker after retirement.']]),
      { title: '1. The Formal Sector', intro: 'The formal sector has the following characteristics:',
        items: [['Registration:', 'Companies are registered and pay taxes.'],
          ['Contracts:', 'Workers have contracts and receive a monthly salary.'],
          ['Protection:', 'Workers are insured by the CNPS and receive a pension.'],
          ['Examples:', 'SODECOTON, banks, schools and hospitals are in the formal sector.']] },
      { title: '2. The Informal Sector', intro: 'The informal sector is described as follows:',
        items: [['Examples:', 'Moto-taxi drivers, street sellers and roadside mechanics work in the informal sector.'],
          ['Importance:', 'It gives work and income to most people in Cameroon.'],
          ['Problems:', 'Workers have no contract, no insurance and no pension.'],
          ['Solutions:', 'Workers can register their activity and join the CNPS.']],
        draw: { img: 'formal_informal_big.png', caption: 'formal and informal sectors compared' } },
    ],
    hwAnswer: 'Examples: onions and maize (farming, from Garoua and the Far North); fish (fishing, from Lagdo); charcoal and wood (forestry, from the savanna); salt or cement from limestone (mining, from Figuil).',
  },
  S16_L5_P3_Primary_Sector: {
    secs: ['1. AGRICULTURE', '1. LIVESTOCK REARING', '1. FISHING', '1. FORESTRY', '1. MINING'],
    action: 'Respect farmers, herders and fishermen, who feed the nation.',
    summary: [
      D([['Primary sector:', 'It is the sector that takes products directly from nature.']]),
      { title: '1. Examples of the Primary Sector', intro: 'The primary sector in Cameroon includes the following activities:',
        items: [['Agriculture:', 'Farmers grow maize, cassava, cotton and cocoa.'],
          ['Livestock rearing:', 'Herders rear cattle in the North and on the Adamawa plateau.'],
          ['Fishing:', 'People fish in the Lagdo lake and at sea near Kribi and Limbe.'],
          ['Forestry:', 'Timber is cut in the forests of the South and East.'],
          ['Mining:', 'Oil, gold and limestone are taken from the ground.']] },
      { title: '2. Importance of the Primary Sector', intro: 'The primary sector is important for the following reasons:',
        items: [['Food:', 'It feeds the population.'],
          ['Jobs:', 'It employs most people in the villages.'],
          ['Exports:', 'Cameroon earns money by selling cocoa, cotton, timber and oil.']] },
    ],
    hwAnswer: 'Examples: CICAM in Garoua makes cloth from cotton; SABC (Brasseries du Cameroun) makes drinks; Alucam in Edéa makes aluminium; CIMENCAM in Figuil makes cement.',
  },
  S17_L5_P4_Secondary_Sector: {
    secs: ['1. MEANING', '2. EXAMPLES', '2. EXAMPLES', '2. EXAMPLES', '2. EXAMPLES'],
    action: 'Buy goods made in Cameroon to support our industries.',
    summary: [
      { title: '1. Meaning of the Secondary Sector', intro: 'The secondary sector is defined as follows:',
        items: [['Secondary sector:', 'It is the sector that turns raw materials into finished goods.'],
          ['Industry and craft:', 'An industry makes goods in factories, while a craft makes goods by hand.']] },
      { title: '2. Examples of the Secondary Sector', intro: 'The secondary sector in Cameroon includes the following activities:',
        items: [['Agro-industries:', 'CICAM makes cloth from cotton and breweries make drinks.'],
          ['Heavy industries:', 'Alucam in Edéa makes aluminium.'],
          ['Construction:', 'Workers build houses, roads and bridges.'],
          ['Energy:', 'The Lagdo and Edéa dams produce electricity.'],
          ['Crafts:', 'Tailors, blacksmiths and potters make goods by hand.']] },
    ],
    hwAnswer: 'Examples: transport (moto-taxi, bus); school; hospital or health centre; market; mobile money (MTN, Orange).',
  },
  S18_L5_P5_Tertiary_Sector: {
    secs: ['1. TRADE', '1. TRANSPORT', '1. BANKING', '1. SOCIAL SERVICES', '1. TOURISM'],
    action: 'Use services such as mobile money and banks safely.',
    summary: [
      D([['Tertiary sector:', 'It is the sector that gives services to people.']]),
      { title: '1. Examples of the Tertiary Sector', intro: 'The tertiary sector in Cameroon includes the following services:',
        items: [['Trade:', 'Goods are bought and sold in markets, shops and supermarkets.'],
          ['Transport:', 'People and goods move by road, train, plane and boat.'],
          ['Banking:', 'Banks and mobile money keep and transfer money.'],
          ['Social services:', 'Schools and hospitals serve the population.'],
          ['Tourism:', 'Tourists visit the Waza and Benue parks and the beaches of Kribi.']] },
    ],
    hwAnswer: 'IRAD carries out research to produce better seeds and animal breeds and gives advice to farmers; for example it has developed improved maize and sorghum varieties.',
  },
  S19_L5_P6_Quaternary_Sector: {
    secs: ['1. MEANING', '2. EXAMPLES', '2. EXAMPLES', '2. EXAMPLES', '3. IMPORTANCE'],
    action: 'Study hard and use ICT to create new knowledge.',
    summary: [
      { title: '1. Meaning of the Quaternary Sector', intro: 'The quaternary sector is defined as follows:',
        items: [['Quaternary sector:', 'It is the sector of knowledge, research and information.'],
          ['ICT:', 'It is information and communication technology: computers, phones and the internet.']] },
      { title: '2. Examples of the Quaternary Sector', intro: 'The quaternary sector includes the following activities:',
        items: [['Research:', 'IRAD and the universities carry out research.'],
          ['ICT:', 'Specialists create software, websites and phone applications.'],
          ['Advice:', 'Experts give advice to the government and companies.']] },
      { title: '3. Importance of the Quaternary Sector', intro: 'The quaternary sector is important for the following reasons:',
        items: [['Farming:', 'Research produces better seeds and methods.'],
          ['Industry:', 'New machines and techniques improve production.'],
          ['Services:', 'It creates new services such as mobile money and new medicines.']],
        draw: { img: 'quaternary_big.png', caption: 'importance of the quaternary sector' } },
    ],
    hwAnswer: 'Africa is surrounded by the Atlantic Ocean (west), the Indian Ocean (east), the Mediterranean Sea (north) and the Red Sea (north-east).',
  },
};
