// v3 patches — Form 2 Technical, part 5: Lesson 6 parts 1–3 (Africa)
// Revised model (Sept 2026): only the points of the progression sheet, short bulleted points (one sentence each),
// definitions apart, pictures beside key points, the situation ends with the character's question, one question per slide.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  S20_L6_P1_Africa_Location_Physical: {
    situation: 'During a football tournament, a boy from Brazil asks Kevin: "Where exactly is Africa? Is it a country or a continent? Which seas are around it?" Kevin cannot answer well. He asks his teacher: "How can I describe where Africa is and what it looks like?"',
    sitQA: [['What is the problem in the situation?', 'Kevin cannot describe the location and the physical features of Africa.'],
      ['Is Africa a country or a continent?', 'A continent.'],
      ['Name one ocean around Africa.', 'The Atlantic Ocean (or the Indian Ocean).']],
    activities: [
      { sec: '1. LOCATION', img: 'africa_location_big.png', caption: 'Africa and the seas around it.', q: 'Which ocean lies to the west of Africa?', a: 'The Atlantic Ocean.', noProj: 'draw Africa on the board.' },
      { sec: '1. LOCATION', img: 'f2t_suez.jpg', caption: 'A canal between two seas.', q: 'The Suez Canal separates Africa from which continent?', a: 'Asia.', noProj: 'show the Suez Canal on a map.' },
      { sec: '2. PHYSICAL CHARACTERISTICS', img: 'africa_plateau_big.png', caption: 'The high land of Africa.', q: 'What do we call high, flat land like most of Africa?', a: 'A plateau.', noProj: 'describe the Adamawa plateau.' },
      { sec: '2. PHYSICAL CHARACTERISTICS', img: 'f2t_kilimanjaro.jpg', caption: 'The highest mountain of Africa.', q: 'What is the name of the highest mountain of Africa?', a: 'Kilimanjaro (5,895 m).', noProj: 'compare with Mount Cameroon.' },
      { sec: '2. PHYSICAL CHARACTERISTICS', img: 'f2t_nile.jpg', caption: 'The longest river of Africa.', q: 'What is the longest river of Africa?', a: 'The Nile.', noProj: 'show the Nile on a map.' },
    ],
    action: 'Know the map of Africa and the place of Cameroon in it.',
    summary: [
      D([['Continent:', 'It is a very large mass of land.'],
        ['Plateau:', 'It is a large area of high, flat land.']]),
      { title: '1. Location', intro: 'Africa is located as follows:',
        items: [['Latitudes:', 'From about 37° N to 35° S, crossed by the Equator.', 'africa_location_big.png', 'Africa and the seas around it'],
          ['Longitudes:', 'From about 17° W to 51° E.'],
          ['Oceans and seas:', 'Atlantic Ocean, Indian Ocean, Mediterranean Sea and Red Sea.'],
          ['Size:', 'About 30 million km², the second largest continent.'],
          ['Cameroon:', 'In Central Africa, on the Gulf of Guinea.']] },
      { title: '2. Physical Characteristics', intro: 'Africa has the following physical characteristics:',
        items: [['A high plateau:', 'Most of Africa is a high plateau.', 'africa_plateau_big.png', 'the plateau of Africa'],
          ['High mountains:', 'Kilimanjaro (5,895 m) is the highest.', 'f2t_kilimanjaro.jpg', 'Kilimanjaro'],
          ['Rift Valley:', 'A long valley in East Africa.'],
          ['Big rivers and lakes:', 'The Nile, the Congo, the Niger and Lake Victoria.'],
          ['Few coastal plains:', 'The coasts are smooth, with few bays.']] },
    ],
    hwAnswer: 'Douala is the wettest (about 4,000 mm of rain a year); Maroua is the driest (about 800 mm); Garoua is in between (about 1,000 mm).',
  },
  S21_L6_P2_Africa_Climate_Soils_Relief: {
    situation: 'Douala gets about 4,000 mm of rain per year, Garoua about 1,000 mm and Maroua about 800 mm. On the Adamawa plateau, the air is cooler than in Garoua. Nadia asks: "Why do the climate, the relief and the soils change so much across Africa?"',
    sitQA: [['What is the problem in the situation?', 'Nadia does not know the climates, relief and soils of Africa.'],
      ['Which town is the wettest?', 'Douala.'],
      ['Why is the Adamawa cooler?', 'It is high (altitude).']],
    activities: [
      { sec: '1. CLIMATE', img: 'africa_climate_big.png', caption: 'The climates of Africa.', q: 'Which climate is found around the Equator?', a: 'The equatorial climate.', noProj: 'draw climate belts.' },
      { sec: '1. CLIMATE', img: 'f2t_tea_highlands.jpg', caption: 'Tea in the highlands of Kenya.', q: 'Why are highlands near the Equator cool?', a: 'The higher the land, the cooler the air.', noProj: 'compare Garoua and Ngaoundéré.' },
      { sec: '2. RELIEF', img: 'f2t_rift_valley.jpg', caption: 'A long valley in East Africa.', q: 'What is this long valley of East Africa called?', a: 'The Great Rift Valley.', noProj: 'show it on a map.' },
      { sec: '2. RELIEF', img: 'f2t_atlas.jpg', caption: 'Mountains of North Africa.', q: 'Name these fold mountains of North Africa.', a: 'The Atlas Mountains.', noProj: 'show them on a map.' },
      { sec: '3. SOILS', img: 'f2t_mount_cameroon.jpg', caption: 'Mount Cameroon.', q: 'Why are the soils near Mount Cameroon so fertile?', a: 'They come from volcanic rocks.', noProj: 'name crops of the South-West.' },
    ],
    action: 'Use the fertile soils of Africa carefully and protect them.',
    summary: [
      D([['Relief:', 'It is the shape of the land: mountains, plateaux, valleys and plains.']]),
      { title: '1. Climate', intro: 'Africa has the following main climates:',
        items: [['Equatorial:', 'Hot and wet all year, in the Congo Basin.', 'africa_climate_big.png', 'the climates of Africa'],
          ['Tropical (savanna):', 'A wet and a dry season, as in Garoua.'],
          ['Desert:', 'Very dry, in the Sahara and the Kalahari.'],
          ['Mediterranean:', 'Hot, dry summers and wet winters, at the north and south tips.'],
          ['Mountain:', 'Cool, on high land such as the Adamawa and East Africa.']] },
      { title: '2. Relief', intro: 'Africa has the following relief features:',
        items: [['Plateaux:', 'High plateaux cover most of Africa.'],
          ['Fold mountains:', 'The Atlas in the north and the Cape Ranges in the south.', 'f2t_atlas.jpg', 'the Atlas Mountains'],
          ['Volcanic mountains:', 'Kilimanjaro and Mount Cameroon.'],
          ['Rift Valley:', 'A long valley from the Red Sea to Mozambique.', 'f2t_rift_valley.jpg', 'the Rift Valley'],
          ['Basins:', 'The Congo, Chad and Kalahari basins.']] },
      { title: '3. Soils', intro: 'Africa has the following main soils:',
        items: [['Ferrallitic soils:', 'Red, leached soils in the forest.'],
          ['Ferruginous soils:', 'Red soils of the savanna.'],
          ['Desert soils:', 'Sandy, stony and poor soils.'],
          ['Volcanic soils:', 'Very fertile, near Mount Cameroon.', 'f2t_mount_cameroon.jpg', 'Mount Cameroon'],
          ['Alluvial soils:', 'Fertile soils in river valleys, like the Nile.']] },
    ],
    hwAnswer: 'Examples: the Nile flows into the Mediterranean Sea; the Congo flows into the Atlantic Ocean; the Niger flows into the Atlantic Ocean (Gulf of Guinea); the Zambezi flows into the Indian Ocean.',
  },
  S22_L6_P3_Africa_Vegetation_Drainage: {
    situation: 'Lake Chad, north of Cameroon, is much smaller today than sixty years ago, and many fishermen and farmers have lost their work. Mariam asks: "What are the vegetation, the rivers and the lakes of Africa, and why is Lake Chad shrinking?"',
    sitQA: [['What is the problem in the situation?', 'Mariam does not know the vegetation and drainage of Africa and why Lake Chad is shrinking.'],
      ['What happened to Lake Chad?', 'It has become much smaller.'],
      ['Who lost their work?', 'Fishermen and farmers.']],
    activities: [
      { sec: '1. VEGETATION', img: 'africa_vegetation_big.png', caption: 'The vegetation of Africa.', q: 'Which vegetation covers most of Africa?', a: 'The savanna.', noProj: 'draw vegetation belts.' },
      { sec: '1. VEGETATION', img: 'f2t_rainforest.jpg', caption: 'A thick forest.', q: 'Why is the forest so thick near the Equator?', a: 'It is hot and wet all year.', noProj: 'describe the forest of the South.' },
      { sec: '2. DRAINAGE', img: 'africa_drainage_big.png', caption: 'The rivers and lakes of Africa.', q: 'Name two big rivers of Africa.', a: 'The Nile and the Congo (also the Niger and the Zambezi).', noProj: 'draw rivers on a map.' },
      { sec: '2. DRAINAGE', img: 'f2t_benue.jpg', caption: 'The Benue.', q: 'The Benue flows through Garoua. Which big river does it join?', a: 'The Niger.', noProj: 'describe the Benue.' },
      { sec: '2. DRAINAGE', img: 'f2t_lake_chad.jpg', caption: 'Lake Chad.', q: 'Give one reason why Lake Chad is shrinking.', a: 'Less rain (drought) and too much water taken for irrigation.', noProj: 'show Lake Chad on a map.' },
    ],
    action: 'Protect the forests, rivers and lakes of Africa.',
    summary: [
      D([['Vegetation:', 'It is the plants that grow naturally in an area.'],
        ['Drainage:', 'It is the rivers and lakes of an area.']]),
      { title: '1. Vegetation', intro: 'Africa has the following vegetation zones:',
        items: [['Equatorial forest:', 'Thick evergreen forest in the Congo Basin.', 'africa_vegetation_big.png', 'the vegetation of Africa'],
          ['Savanna:', 'Grass and scattered trees, covering most of Africa.'],
          ['Desert vegetation:', 'Few scattered plants in the Sahara and the Kalahari.'],
          ['Mediterranean vegetation:', 'Olive trees and shrubs at the north and south tips.'],
          ['Mountain vegetation:', 'Forests and grass on high mountains.']] },
      { title: '2. Drainage', intro: 'Africa has the following main rivers and lakes:',
        items: [['The Nile:', 'The longest river, flowing into the Mediterranean Sea.', 'africa_drainage_big.png', 'the rivers and lakes of Africa'],
          ['The Congo:', 'It carries the most water, into the Atlantic Ocean.'],
          ['The Niger:', 'It flows into the Gulf of Guinea, and the Benue joins it.'],
          ['The Zambezi:', 'It flows into the Indian Ocean.'],
          ['Lakes:', 'Lake Victoria is the largest, and Lake Chad is shrinking.', 'f2t_lake_chad.jpg', 'Lake Chad'],
          ['Importance:', 'Water, fishing, transport, irrigation and electricity.']] },
    ],
    hwAnswer: 'The map should show the outline of Africa with the Equator across the middle, the Nile flowing north to the Mediterranean, the Congo and the Niger flowing into the Atlantic, Lake Victoria in the east and Cameroon in Central Africa.',
  },
};
