// v3 patches — Form 2 Technical, part 1: Lesson 1 (equatorial problems), Lesson 2 parts 1–5 (tropical grassland)
// Revised model (Sept 2026): only the points of the progression sheet, short bulleted points (one sentence each),
// definitions apart, pictures beside key points, the situation ends with the character's question, one question per slide.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  FORM2TECH_LESSON1_WEEK7_Problems_Solutions: {
    situation: 'Paul visits his uncle in a village of the East Region. A logging company has cut many trees near the village, and after heavy rain muddy water runs into the stream, which now has fewer fish. His uncle also suffers from malaria. Paul asks: "What problems does the forest give to people, what problems do people give to the forest, and what can be done?"',
    sitQA: [['What is the problem in the situation?', 'Paul wants to know the problems of the forest region and their solutions.'],
      ['What did the logging company do?', 'It cut many trees.'],
      ['What happened to the stream?', 'It became muddy and has fewer fish.']],
    activities: [
      { sec: '1. PROBLEMS FACED', img: 'f2t_muddy_road.jpg', caption: 'A muddy road.', q: 'What problem does heavy rain cause for transport?', a: 'The roads become muddy and hard to use.', noProj: 'describe roads in the rainy season.' },
      { sec: '1. PROBLEMS FACED', img: 'f2t_mosquito_net.jpg', caption: 'A mosquito net.', q: 'Which disease does this net prevent?', a: 'Malaria.', noProj: 'show a mosquito net.' },
      { sec: '2. PROBLEMS CAUSED', img: 'f2t_logging_truck.jpg', caption: 'A lorry with logs.', q: 'What happens to the forest when too many trees are cut?', a: 'It disappears: this is deforestation.', noProj: 'count trees cut in the area.' },
      { sec: '2. PROBLEMS CAUSED', img: 'erosion_rain.gif', caption: 'Animation: rain on bare soil and on plants.', q: 'On which side is the soil washed away?', a: 'On the side where the soil is bare.', noProj: 'pour water on bare soil and on grass.' },
      { sec: '3. ATTEMPTED SOLUTIONS', img: 'f2t_tree_planting.jpg', caption: 'Planting a young tree.', q: 'How does planting trees help the forest?', a: 'New trees replace the trees that were cut.', noProj: 'plan a tree-planting day.' },
    ],
    action: 'Plant trees and protect the forest and its animals.',
    summary: [
      D([['Deforestation:', 'It is the cutting down of forests.'],
        ['Soil erosion:', 'It is the washing away of the top soil.']]),
      { title: '1. Problems Faced by Man', intro: 'The equatorial environment causes the following problems:',
        items: [['Diseases:', 'Malaria and sleeping sickness are common.', 'f2t_mosquito_net.jpg', 'a mosquito net'],
          ['Bad roads:', 'Heavy rain makes the roads muddy.', 'f2t_muddy_road.jpg', 'a muddy road'],
          ['Thick forest:', 'Clearing land and building roads is difficult.'],
          ['Poor soils:', 'Soils quickly lose their fertility.']] },
      { title: '2. Problems Caused by Man', intro: 'Human activities cause the following problems:',
        items: [['Deforestation:', 'Logging and farming destroy the forest.', 'f2t_logging_truck.jpg', 'logs from the forest'],
          ['Soil erosion:', 'Rain washes away bare soil.'],
          ['Loss of wildlife:', 'Hunting makes animals rare.'],
          ['Water pollution:', 'Mud and mining make rivers dirty.']] },
      { title: '3. Attempted Solutions', intro: 'The following solutions have been attempted:',
        items: [['Reforestation:', 'Young trees are planted.', 'f2t_tree_planting.jpg', 'planting a tree'],
          ['National parks:', 'Parks such as the Dja protect animals.'],
          ['Health care:', 'Mosquito nets, drugs and vaccines fight diseases.'],
          ['Better roads:', 'Tarred roads are built.'],
          ['Forest laws:', 'The state controls logging and hunting.']] },
    ],
    hwAnswer: 'Around Garoua there are grasses with trees far apart (savanna), not tall trees growing close together. In the dry season the grass is dry and many trees lose their leaves.',
  },
  FORM2TECH_LESSON2_WEEK8_Tropical_Grassland_Climate: {
    situation: 'In March, Moussa\'s father plants maize near Garoua. After a few weeks, the young plants dry up and die, but his neighbour plants in June and his maize grows well. Moussa asks: "Why is June a good time to plant in Garoua, but not March?"',
    sitQA: [['What is the problem in the situation?', 'Moussa does not know when the rainy season comes in Garoua and why.'],
      ['What happened to the maize planted in March?', 'It dried up and died.'],
      ['Why did the maize planted in June grow well?', 'It was planted in the rainy season.']],
    activities: [
      { sec: '1. LOCATION', img: 'f2t_savanna.jpg', caption: 'Grass with scattered trees.', q: 'What do we call this region of tall grass and scattered trees?', a: 'The savanna, or Tropical Grassland.', noProj: 'describe the land around Garoua.' },
      { sec: '1. LOCATION', img: 'savanna_africa_big.png', caption: 'The savanna in Africa.', q: 'Between which latitudes do we find the savanna?', a: 'Between 5° and 15° north and south of the Equator.', noProj: 'draw the Equator and two lines.' },
      { sec: '2. CLIMATE', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'Which months are wet in Garoua?', a: 'From May to October.', noProj: 'write the months on the board.' },
      { sec: '2. CLIMATE', img: 'f2t_harmattan.jpg', caption: 'A dusty sky.', q: 'Which dry, dusty wind blows in the dry season?', a: 'The Harmattan.', noProj: 'describe a Harmattan morning.' },
      { sec: '2. CLIMATE', img: 'f2t_storm.jpg', caption: 'A storm.', q: 'How does rain fall in the savanna in the wet season?', a: 'As heavy storms with thunder.', noProj: 'describe a storm in Garoua.' },
    ],
    action: 'Prepare for the dry season and protect yourself from Harmattan dust.',
    summary: [
      D([['Tropical Grassland (savanna):', 'It is the region of grass and scattered trees with a wet and a dry season.']]),
      { title: '1. Location', intro: 'The savanna lies between 5° and 15° N and S of the Equator:',
        items: [['Africa:', 'North Cameroon, the Sudan savanna and East Africa.', 'savanna_africa_big.png', 'the savanna in Africa'],
          ['South America:', 'The Llanos and the Campos.'],
          ['Australia:', 'The north of Australia.']] },
      { title: '2. Characteristics of the Climate', intro: 'The savanna climate has the following characteristics:',
        items: [['Hot all year:', 'Temperatures are between 25 and 35 °C.', 'garoua_climate_big.png', 'the climate of Garoua'],
          ['Two seasons:', 'A wet season (May–October) and a dry season (November–April).'],
          ['Rainfall:', 'About 750 to 1,500 mm per year.'],
          ['Storms:', 'Rain falls as heavy storms with thunder.'],
          ['Harmattan:', 'A dry, dusty wind blows in the dry season.', 'f2t_harmattan.jpg', 'Harmattan dust']] },
    ],
    hwAnswer: 'Answers vary. Trees like the mango and the neem keep their leaves, while many trees such as the shea tree and acacias lose them. In the dry season the grass is yellow and dry.',
  },
  S01_L2_P2_Tropical_Grassland_Soils_Vegetation: {
    situation: 'In January, Hawa travels from Garoua to Ngaoundéré. The grass is dry and yellow, and many trees have no leaves, but the shea tree still has leaves and its bark is not burnt. Hawa asks: "How do the plants of the savanna survive the long dry season and the bush fires?"',
    sitQA: [['What is the problem in the situation?', 'Hawa does not know how savanna plants survive the dry season and fires.'],
      ['What colour is the grass in January?', 'Yellow (dry).'],
      ['Which tree still has leaves?', 'The shea tree.']],
    activities: [
      { sec: '1. VEGETATION', img: 'f2t_baobab.jpg', caption: 'A baobab.', q: 'How does the big trunk of the baobab help it in the dry season?', a: 'It stores water.', noProj: 'describe a baobab.' },
      { sec: '1. VEGETATION', img: 'f2t_dry_trees.jpg', caption: 'Trees without leaves.', q: 'Why do many savanna trees lose their leaves in the dry season?', a: 'To lose less water.', noProj: 'look at the trees of the school.' },
      { sec: '1. VEGETATION', img: 'f2t_shea_tree.jpg', caption: 'A shea tree.', q: 'How does the thick bark help the shea tree?', a: 'It protects the tree from bush fires.', noProj: 'touch the bark of a tree.' },
      { sec: '2. SOILS', img: 'f2t_laterite.jpg', caption: 'A red, hard soil.', q: 'What is this red soil that becomes hard when it dries?', a: 'Laterite.', noProj: 'show a laterite road.' },
      { sec: '2. SOILS', img: 'f2t_cracked_soil.jpg', caption: 'A black soil that cracks.', q: 'Why do farmers like black cotton soils?', a: 'They are fertile and keep water.', noProj: 'name crops grown on black soils.' },
    ],
    action: 'Avoid bush fires, which destroy plants and the humus of the soil.',
    summary: [
      D([['Savanna:', 'It is a vegetation of tall grass with scattered trees.'],
        ['Laterite:', 'It is a red soil that becomes very hard when it dries.']]),
      { title: '1. Vegetation', intro: 'The savanna vegetation has the following characteristics:',
        items: [['Tall grass:', 'Elephant grass grows up to 3 m high.', 'f2t_savanna.jpg', 'the savanna'],
          ['Scattered trees:', 'Baobab, acacia and shea trees.'],
          ['Deciduous trees:', 'Many trees lose their leaves in the dry season.'],
          ['Water storage:', 'The baobab stores water in its trunk.', 'f2t_baobab.jpg', 'a baobab'],
          ['Protection:', 'Thick bark protects trees from fire.']] },
      { title: '2. Soils', intro: 'The savanna soils have the following characteristics:',
        items: [['Ferruginous soils:', 'Red soils rich in iron.'],
          ['Laterite:', 'A hard red crust used for roads and bricks.', 'f2t_laterite.jpg', 'laterite'],
          ['Black cotton soils:', 'Fertile clay soils that crack when dry.'],
          ['Little humus:', 'Bush fires burn dead plants.']] },
    ],
    hwAnswer: 'Examples: food (maize, sorghum, groundnuts, shea butter); wood (firewood, charcoal, poles for building); animals (cattle, goats, meat and milk).',
  },
  S02_L2_P3_Tropical_Grassland_Resources: {
    situation: 'Ibrahim lives near the Lagdo lake. His uncle fishes in the lake, his father grows cotton, and his cousin guides tourists in the Bénoué National Park. A visitor says: "The savanna is a poor region." Ibrahim asks: "Is the savanna really poor? What resources does it have, and how do we use them?"',
    sitQA: [['What is the problem in the situation?', 'Ibrahim does not agree that the savanna is poor, and wants to know its resources.'],
      ['Name three activities of Ibrahim\'s family.', 'Fishing, cotton farming and tourism.'],
      ['Where is the Bénoué National Park?', 'In the North Region, near Garoua.']],
    activities: [
      { sec: '1. TYPES OF RESOURCES', img: 'f2t_cattle.jpg', caption: 'Cattle.', q: 'What do these animals eat?', a: 'Grass.', noProj: 'describe cattle near Garoua.' },
      { sec: '1. TYPES OF RESOURCES', img: 'f2t_cotton_field.jpg', caption: 'A cotton field.', q: 'Why do farmers grow cotton?', a: 'To sell it and earn money.', noProj: 'name products made of cotton.' },
      { sec: '1. TYPES OF RESOURCES', img: 'f2t_elephants.jpg', caption: 'Elephants.', q: 'In which parks can we see these animals in North Cameroon?', a: 'Bénoué, Bouba Ndjida and Waza.', noProj: 'name the parks.' },
      { sec: '2. METHODS OF EXPLOITATION', img: 'f2t_lagdo.jpg', caption: 'The Lagdo dam.', q: 'Give one way people use the water of the Lagdo lake.', a: 'Fishing (also electricity and irrigation).', noProj: 'describe the lake.' },
      { sec: '2. METHODS OF EXPLOITATION', img: 'f2t_charcoal.jpg', caption: 'Bags of charcoal.', q: 'What do people make from the trees of the savanna?', a: 'Firewood and charcoal (also shea butter).', noProj: 'ask how families cook.' },
    ],
    action: 'Use the resources of the savanna carefully so that they last.',
    summary: [
      D([['Resource:', 'It is anything in nature that people can use.'],
        ['Exploitation:', 'It is the use of a resource to meet our needs or to earn money.']]),
      { title: '1. Types of Resources', intro: 'The savanna has the following resources:',
        items: [['Pasture:', 'Grass for cattle, sheep and goats.', 'f2t_cattle.jpg', 'cattle'],
          ['Farmland:', 'Good for cotton, maize, sorghum and groundnuts.'],
          ['Wildlife:', 'Elephants, lions and antelopes.', 'f2t_elephants.jpg', 'elephants'],
          ['Water:', 'Rivers and lakes such as the Benue and Lagdo.'],
          ['Wood:', 'Firewood, charcoal and shea trees.']] },
      { title: '2. Methods of Exploitation', intro: 'These resources are exploited as follows:',
        items: [['Pasture:', 'Herders graze their animals.'],
          ['Farmland:', 'Farmers use hoes, oxen and tractors.', 'f2t_cotton_field.jpg', 'a cotton field'],
          ['Wildlife:', 'National parks receive tourists.'],
          ['Water:', 'Dams, irrigation and fishing.', 'f2t_lagdo.jpg', 'the Lagdo dam'],
          ['Wood:', 'Trees are cut and burnt into charcoal.']] },
    ],
    hwAnswer: 'Answers vary. Example: a farmer produces cotton and maize with a hoe and oxen, and sells cotton to SODECOTON; a herder rears cattle, uses a stick and moves with them, and sells them at the cattle market.',
  },
  S03_L2_P4_Tropical_Grassland_Human_Activities: {
    situation: 'Every year in November, Adamou, a Fulani herder, leaves his village near Garoua with his cattle. He walks south for weeks and comes back when the rains return. His classmate Paul thinks that Adamou is lost. Paul asks: "Why does Adamou move with his cattle, and what other work do people do in the savanna?"',
    sitQA: [['What is the problem in the situation?', 'Paul does not understand why the herder moves and what activities people do in the savanna.'],
      ['When does Adamou leave?', 'In November, at the start of the dry season.'],
      ['When does he come back?', 'When the rains return.']],
    activities: [
      { sec: '1. FARMING', img: 'f2t_cotton_harvest.jpg', caption: 'Harvesting cotton.', q: 'What do we call a crop that is grown to be sold?', a: 'A cash crop.', noProj: 'name cash crops of the North.' },
      { sec: '1. FARMING', img: 'f2t_rice_field.jpg', caption: 'A rice field.', q: 'How do farmers bring water to their fields in the dry savanna?', a: 'By irrigation from rivers and dams.', noProj: 'describe rice fields near Lagdo.' },
      { sec: '2. LIVESTOCK REARING', img: 'transhumance.gif', caption: 'Animation: herders move with the seasons.', q: 'Where does the herder go in the dry season?', a: 'To the south, where there is grass and water.', noProj: 'draw arrows on a map.' },
      { sec: '2. LIVESTOCK REARING', img: 'f2t_maasai.jpg', caption: 'Herders with cattle.', q: 'Why are cattle important for herders?', a: 'They give milk, meat and money.', noProj: 'ask about cattle markets.' },
      { sec: '3. OTHER ACTIVITIES', img: 'f2t_fishing.jpg', caption: 'Fishermen.', q: 'Give one other activity of the people of the savanna.', a: 'Fishing (also hunting, tourism and cutting wood).', noProj: 'list jobs of the area.' },
    ],
    action: 'Respect the work of farmers and herders and help them live in peace.',
    summary: [
      D([['Cash crop:', 'It is a crop grown to be sold.'],
        ['Transhumance:', 'It is the seasonal movement of herders and their animals.']]),
      { title: '1. Farming', intro: 'Farming in the savanna has the following forms:',
        items: [['Food crops:', 'Maize, sorghum, millet and groundnuts.'],
          ['Cash crops:', 'Cotton, bought by SODECOTON.', 'f2t_cotton_harvest.jpg', 'harvesting cotton'],
          ['Irrigated farming:', 'Rice and onions near rivers and dams.', 'f2t_rice_field.jpg', 'a rice field']] },
      { title: '2. Livestock Rearing', intro: 'Livestock rearing has the following forms:',
        items: [['Nomadic pastoralism:', 'Herders move all the time with their animals.'],
          ['Transhumance:', 'Herders move south in the dry season and return in the rainy season.', 'transhumance_mid.png', 'transhumance'],
          ['Ranching:', 'Animals are reared on large, fenced farms.']] },
      { title: '3. Other Activities', intro: 'People also carry out the following activities:',
        items: [['Hunting:', 'Controlled hunting in hunting zones.'],
          ['Fishing:', 'In the Benue and the Lagdo lake.', 'f2t_fishing.jpg', 'fishing'],
          ['Lumbering:', 'Cutting wood for fuel and building.'],
          ['Tourism:', 'Visits to national parks.']] },
    ],
    hwAnswer: 'Examples: rains that start late or stop early; bush fires that burn pastures; pests such as locusts and caterpillars; cattle that eat crops, which causes conflicts.',
  },
  S04_L2_P5_Tropical_Grassland_Problems_Solutions: {
    situation: 'In a village near Garoua, a herder\'s cattle entered a farmer\'s field at night and ate his maize, and the two men started to fight. The same year, the rains stopped early and a bush fire burnt the pastures. The village chief asks: "What are the problems of our savanna, and how can we solve them?"',
    sitQA: [['What is the problem in the situation?', 'The village faces several problems and the chief looks for solutions.'],
      ['Why did the two men fight?', 'The cattle ate the farmer\'s maize.'],
      ['Name two other problems of the village.', 'Early end of the rains (drought) and bush fires.']],
    activities: [
      { sec: '1. PROBLEMS FACED', img: 'f2t_drought.jpg', caption: 'Dry land.', q: 'What problem do you see in the picture?', a: 'Drought: there is no rain, so crops dry up.', noProj: 'describe a dry year.' },
      { sec: '1. PROBLEMS FACED', img: 'f2t_bushfire.jpg', caption: 'A bush fire.', q: 'What does a bush fire leave behind it?', a: 'Burnt, bare soil.', noProj: 'describe a bush fire.' },
      { sec: '1. PROBLEMS FACED', img: 'erosion_rain.gif', caption: 'Animation: rain on bare soil and on grass.', q: 'Why is the soil washed away on bare land?', a: 'There are no plants to protect it.', noProj: 'pour water on bare soil.' },
      { sec: '1. PROBLEMS FACED', img: 'f2t_cattle_field.jpg', caption: 'Cattle near fields.', q: 'Why do farmers and herders sometimes fight?', a: 'Cattle eat the crops.', noProj: 'discuss conflicts.' },
      { sec: '2. ATTEMPTED SOLUTIONS', img: 'f2t_tree_planting_sahel.jpg', caption: 'Tree planting in a dry area.', q: 'How does planting trees help the savanna?', a: 'Trees protect the soil and stop the desert.', noProj: 'plan a tree-planting day.' },
    ],
    action: 'Plant trees, avoid bush fires and respect grazing zones.',
    summary: [
      D([['Drought:', 'It is a long period without enough rain.'],
        ['Overgrazing:', 'It is keeping too many animals on the same pasture.']]),
      { title: '1. Problems Faced', intro: 'People in the savanna face the following problems:',
        items: [['Drought:', 'The rains start late or stop early.', 'f2t_drought.jpg', 'drought'],
          ['Bush fires:', 'Fires burn pastures, trees and animals.', 'f2t_bushfire.jpg', 'a bush fire'],
          ['Soil erosion:', 'Wind and rain carry away bare soil.'],
          ['Overgrazing:', 'Too many animals destroy the grass.'],
          ['Pests and diseases:', 'Locusts, tsetse flies and animal diseases.'],
          ['Farmer–herder conflicts:', 'Cattle eat crops in the fields.']] },
      { title: '2. Attempted Solutions', intro: 'The following solutions have been attempted:',
        items: [['Tree planting:', 'Operation Sahel Vert and the Great Green Wall.', 'f2t_tree_planting_sahel.jpg', 'tree planting'],
          ['Irrigation:', 'Dams and wells give water in the dry season.'],
          ['Control of bush fires:', 'Fire breaks and laws against burning.'],
          ['Grazing zones:', 'Separate areas for farming and for herding.'],
          ['Veterinary care:', 'Vaccines and treatments for animals.']] },
    ],
    hwAnswer: 'The Sahara covers countries such as Algeria, Libya, Egypt, Niger, Mali and Chad.',
  },
};
