// v3 patches — Form 4, part 1: L1, FS1, L2, L3, PW1, L4, PW2, L5, L6
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  FORM4_LESSON01_Our_Planet_the_Earth: {
    secs: ['2. SHAPE OF THE EARTH', '3. PROOFS OF THE SHAPE', '3. PROOFS OF THE SHAPE'],
    action: 'Use everyday observations to show that the Earth is round.',
    summary: [
      D([['Planet:', 'It is a large body that moves around the Sun.'],
        ['Oblate spheroid:', 'It is a ball that is flat at the poles and wider at the Equator.']]),
      { title: '1. Size of the Earth', intro: 'The main measurements of the Earth are the following:',
        items: [['Equatorial circumference:', 'It is the distance around the Equator, which is about 40,075 km.'],
          ['Polar circumference:', 'It is the distance around the Earth through the poles, which is about 40,008 km.'],
          ['Equatorial diameter:', 'It is the distance through the centre of the Earth at the Equator, which is about 12,756 km.']] },
      { title: '2. Shape of the Earth', intro: 'The true shape of the Earth is described as follows:',
        items: [['Oblate spheroid:', 'The Earth is round, slightly flattened at the poles and bulging at the Equator.']],
        draw: { img: 'earth_shape_big.png', caption: 'the shape of the Earth' } },
      { title: '3. Proofs of the Shape of the Earth', intro: 'The following observations prove that the Earth is round:',
        items: [['The ship at sea:', 'When a ship sails away, its bottom disappears first and its top last.'],
          ['The eclipse of the Moon:', 'The shadow of the Earth on the Moon is always curved.'],
          ['Photos from space:', 'Photos taken from space show that the Earth is round.'],
          ['Travel around the world:', 'A traveller who goes always in one direction comes back to the starting point.']] },
    ],
    hwAnswer: 'The drawings should show the Moon changing shape: for example a thin crescent, then a half Moon, then a nearly full Moon, each with its date.',
  },
  FORM4_FURTHER_STUDY1_Universe_and_Moon: {
    secs: ['1. THE UNIVERSE', '2. THE PHASES OF THE MOON', '3. IMPACTS OF THE MOON'],
    action: 'Observe the sky and the Moon regularly and use the tides and the phases safely.',
    summary: [
      { title: '1. The Universe', sub: 'A) Meaning', intro: 'The universe can be defined as follows:',
        items: [['Universe:', 'It is all of space and everything in it: stars, planets, gases and dust.']] },
      { title: '1. The Universe', sub: 'B) Composition', intro: 'The universe is made up of the following elements:',
        items: [['Galaxies:', 'They are huge groups of stars, and our galaxy is called the Milky Way.'],
          ['The Sun:', 'It is the star of our solar system and it gives light and heat to the Earth.'],
          ['The Moon:', 'It is the natural satellite of the Earth, and it moves around the Earth in about 29½ days.']] },
      { title: '2. The Phases of the Moon', intro: 'The Moon shows the following phases during a month:',
        items: [['New Moon:', 'The lit side of the Moon faces away from the Earth, so we do not see it.'],
          ['First quarter:', 'We see the right half of the Moon lit by the Sun.'],
          ['Full Moon:', 'We see the whole lit face of the Moon.'],
          ['Last quarter:', 'We see the left half of the Moon lit by the Sun.']],
        draw: { img: 'moon_phases_big.png', caption: 'the phases of the Moon' } },
      { title: '3. Impacts of the Moon', intro: 'The Moon affects the environment and human activities as follows:',
        items: [['Tides:', 'The pull of the Moon makes the sea rise and fall twice a day.'],
          ['Fishing and navigation:', 'Fishermen and sailors use the times of the tides to go out and come back.'],
          ['Calendar and culture:', 'Some calendars and feasts, such as Ramadan, follow the phases of the Moon.']] },
    ],
    hwAnswer: 'The numbers on the edges are latitudes (left and right) and longitudes (top and bottom). Near Garoua we read about 9° N and 13° E.',
  },
  FORM4_LESSON02_Latitudes_and_Longitudes: {
    secs: ['1. LATITUDES', '2. LONGITUDES', '3. GEOGRAPHICAL COORDINATES'],
    action: 'Use latitudes and longitudes to locate places correctly on maps.',
    summary: [
      { title: '1. Latitudes', sub: 'A) Meaning and Major Lines', intro: 'Latitudes are defined and named as follows:',
        items: [['Latitude:', 'It is the angular distance of a place north or south of the Equator.'],
          ['Equator:', 'It is the line of latitude 0° that divides the Earth into two hemispheres.'],
          ['Tropics:', 'They are the Tropic of Cancer at 23½° N and the Tropic of Capricorn at 23½° S.'],
          ['Polar circles:', 'They are the Arctic Circle at 66½° N and the Antarctic Circle at 66½° S.']],
        draw: { img: 'latitudes_big.png', caption: 'the major lines of latitude' } },
      { title: '1. Latitudes', sub: 'B) Characteristics', intro: 'Lines of latitude have the following characteristics:',
        items: [['Parallel lines:', 'Lines of latitude are parallel and never meet.'],
          ['Unequal length:', 'They become shorter from the Equator towards the poles.']] },
      { title: '2. Longitudes', intro: 'Longitudes are defined and described as follows:',
        items: [['Longitude:', 'It is the angular distance of a place east or west of the Greenwich Meridian.'],
          ['Greenwich Meridian:', 'It is the line of longitude 0°, and its opposite is the 180° line.'],
          ['Characteristics:', 'Lines of longitude are of equal length and they all meet at the poles.']],
        draw: { img: 'longitudes_big.png', caption: 'lines of longitude' } },
      { title: '3. Geographical Coordinates', intro: 'Geographical coordinates are used as follows:',
        items: [['Coordinates:', 'They are the latitude and the longitude that give the exact position of a place.'],
          ['Example:', 'We write the latitude first, so Garoua is at about 9° N, 13° E.']] },
    ],
    hwAnswer: 'Example: Douala–Paris flies north over the Sahara and the Mediterranean. Aeroplanes follow the curved Earth: the shortest route is a great circle, which looks curved on a flat map.',
  },
  FORM4_LESSON03_Great_Circles_and_IDL: {
    secs: ['1. GREAT CIRCLES', '2. THE INTERNATIONAL DATE LINE', '2. THE INTERNATIONAL DATE LINE'],
    action: 'Use great circles to understand routes and the Date Line to understand the change of date.',
    summary: [
      { title: '1. Great Circles', intro: 'Great circles are explained as follows:',
        items: [['Great circle:', 'It is a circle that cuts the Earth into two equal halves.'],
          ['Small circle:', 'It is a circle, like a tropic, that does not cut the Earth into equal halves.'],
          ['Examples:', 'The Equator and every meridian joined to its opposite meridian are great circles.'],
          ['Importance:', 'A great circle gives the shortest route between two places, so pilots and ships follow it.']],
        draw: { img: 'great_circles_big.png', caption: 'great circles and small circles' } },
      { title: '2. The International Date Line', intro: 'The International Date Line is explained as follows:',
        items: [['Meaning:', 'It is the line where each new calendar day begins.'],
          ['Position:', 'It follows the 180° meridian in the Pacific Ocean but bends to avoid land.'],
          ['Crossing westwards:', 'A traveller who crosses it going west adds one day.'],
          ['Crossing eastwards:', 'A traveller who crosses it going east removes one day.']],
        draw: { img: 'idl_big.png', caption: 'the International Date Line' } },
    ],
    hwAnswer: 'The atlas, ruler and pencil will be used to read the latitude and longitude of towns on the map of Cameroon.',
  },
  FORM4_PRACTICAL_WORK1_Locate_a_Place_on_a_Map: {
    secs: ['1. REVISION', '2. STEPS TO READ COORDINATES', '3. EXERCISE'],
    action: 'Read and write coordinates carefully, latitude first.',
    summary: [
      D([['Coordinates:', 'They are the latitude and the longitude of a place.'],
        ['Grid:', 'It is the set of lines of latitude and longitude drawn on a map.']]),
      { title: '1. Steps to Read Coordinates', intro: 'We locate a place on a map with the following steps:',
        items: [['Step 1:', 'We find the place on the map.'],
          ['Step 2:', 'We follow the line of latitude to the side of the map and read its value and N or S.'],
          ['Step 3:', 'We follow the line of longitude to the top or bottom of the map and read its value and E or W.'],
          ['Step 4:', 'We write the latitude first and the longitude second, for example 9° N, 13° E.']],
        draw: { img: 'coordinates_last.png', caption: 'reading coordinates' } },
      { title: '2. Exercise', intro: 'The coordinates of some towns of Cameroon are the following:',
        items: [['Garoua:', 'It is at about 9° N, 13° E.'],
          ['Maroua:', 'It is at about 11° N, 14° E.'],
          ['Yaoundé:', 'It is at about 4° N, 12° E.']] },
    ],
    hwAnswer: 'Example: Cameroon 12:00, Dubai 15:00 (difference 3 hours ahead); Brazil (Brasília) 08:00 (4 hours behind). Places to the east are ahead in time.',
  },
  FORM4_LESSON04_Local_Time_Standard_Time_Time_Zones: {
    secs: ['1. LOCAL TIME', '2. TIME ZONES', '2. TIME ZONES'],
    action: 'Always check the local time of a place before calling or travelling.',
    summary: [
      D([['Local time:', 'It is the time given by the position of the Sun in a place.'],
        ['Standard time:', 'It is the official time used by a whole country or zone.']]),
      { title: '1. Local and Standard Time', intro: 'Local and standard time follow these rules:',
        items: [['The rule:', 'The Earth turns 15° in one hour, so 1° of longitude equals 4 minutes of time.'],
          ['East and west:', 'Places to the east are ahead in time and places to the west are behind.'],
          ['Cameroon:', 'Cameroon uses West Africa Time, which is GMT + 1.']],
        draw: { img: 'time_line_big.png', caption: 'time and longitude' } },
      { title: '2. Time Zones', intro: 'Time zones are explained as follows:',
        items: [['Time zone:', 'It is an area where people use the same standard time.'],
          ['Number and width:', 'There are 24 main time zones, each about 15° of longitude wide.'],
          ['Reason:', 'Time zones avoid having a different time in every town.'],
          ['Countries with many zones:', 'Wide countries from east to west, like Russia with 11 zones, have many time zones.']] },
    ],
    hwAnswer: 'When it is 12 noon GMT, Garoua (GMT + 1) is at 13:00. A town at 45° E: 45 × 4 min = 180 min = 3 h ahead, so it is 15:00.',
  },
  FORM4_PRACTICAL_WORK2_Calculation_of_Time_and_Date: {
    secs: ['1. THE RULES', '2. CALCULATING SUN TIME', '3. CALCULATING THE DATE'],
    action: 'Follow the rules step by step when calculating time and date.',
    summary: [
      D([['Difference of longitude:', 'It is the number of degrees between two places.'],
        ['Date:', 'It is the day, the month and the year.']]),
      { title: '1. The Rules', intro: 'Time and date are calculated with the following rules:',
        items: [['Rule 1:', 'We find the difference of longitude and multiply it by 4 minutes.'],
          ['Rule 2:', 'We add the time difference for a place to the east and remove it for a place to the west.'],
          ['Rule 3:', 'When the time passes midnight, the date changes.'],
          ['Rule 4:', 'When we cross the International Date Line, the day changes.']] },
      { title: '2. Worked Example', intro: 'The time at 43° E when it is 12:00 in Garoua (13° E) is found as follows:',
        items: [['Difference:', 'The difference of longitude is 43° − 13° = 30°.'],
          ['Time:', 'The time difference is 30 × 4 minutes = 120 minutes, which is 2 hours.'],
          ['Answer:', 'The place is to the east, so the time is 12:00 + 2 hours = 14:00.']],
        draw: { img: 'time_calc_big.png', caption: 'calculating sun time' } },
    ],
    hwAnswer: 'Example: sunrise about 6:00 and sunset about 18:15 in Garoua. The Sun rises in the east because the Earth turns from west to east.',
  },
  FORM4_LESSON05_Rotation_of_the_Earth: {
    secs: ['1. MEANING OF ROTATION', '2. EFFECTS OF ROTATION', '2. EFFECTS OF ROTATION'],
    action: 'Use the rotation of the Earth to explain day, night and time differences.',
    summary: [
      { title: '1. Meaning of Rotation', intro: 'The rotation of the Earth is explained as follows:',
        items: [['Rotation:', 'It is the turning of the Earth on its axis.'],
          ['Axis:', 'It is the imaginary line from the North Pole to the South Pole, tilted at 23½°.'],
          ['Direction and time:', 'The Earth turns from west to east and makes one turn in 24 hours.']],
        draw: { img: 'rotation_mid.png', caption: 'the rotation of the Earth' } },
      { title: '2. Effects of Rotation', intro: 'The rotation of the Earth has the following effects:',
        items: [['Day and night:', 'The side facing the Sun has day while the other side has night.'],
          ['Sunrise in the east:', 'The Sun rises in the east and sets in the west because the Earth turns eastwards.'],
          ['Time difference:', 'Places to the east see the Sun first, so they are ahead in time.'],
          ['Deflection of winds:', 'Winds and ocean currents are bent to the right in the north and to the left in the south.'],
          ['Tides:', 'Rotation, with the pull of the Moon, gives two high tides a day.']] },
    ],
    hwAnswer: 'In Garoua the rainy season starts around April–May and the dry season around October–November.',
  },
  FORM4_LESSON06_Revolution_of_the_Earth: {
    secs: ['1. MEANING OF REVOLUTION', '2. EQUINOXES AND SOLSTICES', '3. EFFECTS OF REVOLUTION'],
    action: 'Plan farm work according to the seasons caused by revolution.',
    summary: [
      { title: '1. Meaning of Revolution', intro: 'The revolution of the Earth is explained as follows:',
        items: [['Revolution:', 'It is the movement of the Earth around the Sun along its orbit.'],
          ['Orbit:', 'It is the oval path of the Earth around the Sun, which takes 365¼ days.']] },
      { title: '2. Equinoxes and Solstices', intro: 'The overhead Sun moves as follows during the year:',
        items: [['Equinoxes:', 'On 21 March and 23 September, the Sun is overhead at the Equator and day and night are equal everywhere.'],
          ['June solstice:', 'On 21 June, the Sun is overhead at the Tropic of Cancer.'],
          ['December solstice:', 'On 22 December, the Sun is overhead at the Tropic of Capricorn.']],
        draw: { img: 'overhead_sun_big.png', caption: 'the overhead Sun during the year' } },
      { title: '3. Effects of Revolution', intro: 'The revolution of the Earth has the following effects:',
        items: [['Seasons:', 'Revolution causes the seasons, such as the rainy and dry seasons in Garoua.'],
          ['Length of day:', 'The length of day and night changes during the year away from the Equator.'],
          ['The year and leap year:', 'A year has 365 days, and every fourth year is a leap year of 366 days.']] },
    ],
    hwAnswer: 'An egg shows a shell, the white and the yolk; an onion shows layers around a centre. The Earth also has layers: crust, mantle and core.',
  },
};
