// v3 patches — Form 3 (FORM4_* sources), part 1: L1, FS1, L2, L3, PW1, L4, PW2, L5, L6
// Revised model (Sept 2026): syllabus points in order, definitions apart, one element per slide with its picture,
// problem visible in the situation (the character asks a question), one question per slide in the activities.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  FORM4_LESSON01_Our_Planet_the_Earth: {
    situation: 'On a long, straight road, Aïcha sees a lorry coming from far away: first she sees only its top, then the whole lorry. Her brother says that the Earth is flat. Aïcha asks: "If the Earth is flat, why did I see the top of the lorry first?"',
    sitQA: [['What is the problem in the situation?', 'Aïcha cannot explain why she saw the top of the lorry first, and her brother thinks that the Earth is flat.'],
      ['Which part of the lorry did she see first?', 'She saw the top of the lorry first.'],
      ['What does this show about the shape of the Earth?', 'It shows that the surface of the Earth is curved: the Earth is round.']],
    activities: [
      { sec: '2. SHAPE OF THE EARTH', img: 'f4_earth_space.jpg', caption: 'The Earth seen from space.', q: 'What is the shape of the Earth on this photo?', a: 'It is round, like a ball.', noProj: 'show a globe or a ball.' },
      { sec: '3. PROOFS OF THE SHAPE', img: 'ship_sailing.gif', caption: 'Animation: a ship sails away from the coast.', q: ['Which part of the ship disappears first?', 'Why does it disappear first?'], a: ['The bottom of the ship.', 'The ship goes down behind the curve of the Earth.'], noProj: 'draw three ships going down behind a curved line.' },
      { sec: '3. PROOFS OF THE SHAPE', img: 'f4_lunar_eclipse.jpg', caption: 'An eclipse of the Moon.', q: 'The shadow of the Earth on the Moon is always curved. What does this prove?', a: 'The Earth is round: only a round object always gives a round shadow.', noProj: 'hold a ball in front of a torch: its shadow on the wall is round.' },
    ],
    action: 'Use everyday observations to show that the Earth is round.',
    summary: [
      D([['Planet:', 'It is a large round body that moves around the Sun.'],
        ['Circumference:', 'It is the distance around a circle or a sphere.'],
        ['Diameter:', 'It is the distance from one side of a sphere to the other, through its centre.'],
        ['Oblate spheroid:', 'It is a ball that is flattened at the poles and bulging at the Equator.']]),
      { title: '1. The Size of the Earth', intro: 'The main measurements of the Earth are the following:',
        items: [['Equatorial circumference:', 'The distance around the Earth at the Equator is about 40,075 km.', 'earth_disc_big.png', 'the Earth'],
          ['Polar circumference:', 'The distance around the Earth through the poles is about 40,008 km.'],
          ['Equatorial diameter:', 'The diameter of the Earth at the Equator is about 12,756 km.'],
          ['Polar diameter:', 'The diameter of the Earth from pole to pole is about 12,714 km.'],
          ['Surface area:', 'The total surface of the Earth is about 510 million km².']] },
      { title: '2. The Shape of the Earth', intro: 'The shape of the Earth is described as follows:',
        items: [['Oblate spheroid:', 'The Earth is round, slightly flattened at the poles and bulging at the Equator.', 'earth_shape_big.png', 'the shape of the Earth'],
          ['Evidence from the measurements:', 'The equatorial diameter is about 42 km longer than the polar diameter.']] },
      { title: '3. Proofs that the Earth Is Spherical', intro: 'The following observations prove that the Earth is round:',
        items: [['The ship at sea:', 'When a ship sails away, its bottom disappears first and its top last.', 'ship_sailing_mid.png', 'the ship at sea'],
          ['The eclipse of the Moon:', 'The shadow of the Earth on the Moon is always curved.', 'eclipse_big.png', 'an eclipse of the Moon'],
          ['Photos from space:', 'Photos taken from satellites and spacecraft show a round Earth.', 'f4_earth_space.jpg', 'the Earth seen from space'],
          ['Travel around the world:', 'A traveller who goes always in one direction comes back to the starting point.'],
          ['The circular horizon:', 'From a high place, the horizon is always a circle, and it widens as we go higher.'],
          ['Sunrise at different times:', 'The Sun rises earlier in the east than in the west, because the surface is curved.']] },
    ],
    hwAnswer: 'The drawings should show the Moon changing shape: for example a thin crescent, then a half Moon, then a nearly full Moon, each with its date.',
  },
  FORM4_FURTHER_STUDY1_Universe_and_Moon: {
    situation: 'One evening, Hawaou sits outside with her grandmother. The full Moon lights up the compound, and grandmother says that some crops are planted according to the shape of the Moon. Hawaou asks: "Why does the Moon change its shape, and how does it affect our lives?"',
    sitQA: [['What is the problem in the situation?', 'Hawaou does not know why the Moon changes its shape or how it affects people.'],
      ['What lights up the compound?', 'The full Moon.'],
      ['Where does the light of the Moon come from?', 'From the Sun: the Moon has no light of its own.']],
    activities: [
      { sec: '1. THE UNIVERSE', img: 'f4_milkyway.jpg', caption: 'The Milky Way at night.', q: 'This band of light is made of billions of stars. What is it called?', a: 'The Milky Way, our galaxy.', noProj: 'ask learners to look at the night sky far from town lights.' },
      { sec: '2. THE PHASES OF THE MOON', img: 'moon_phases.gif', caption: 'Animation: the Moon moves around the Earth.', q: 'Why does the shape of the Moon seem to change?', a: 'The Sun lights half of the Moon, and we see a different part of this lit half as the Moon moves around the Earth.', noProj: 'move a ball around a learner\'s head in front of a torch.' },
      { sec: '3. IMPACTS OF THE MOON', img: 'f4_lowtide.jpg', caption: 'Boats on the sand when the sea is low.', q: ['Why are these boats on the sand?', 'What causes this movement of the sea?'], a: ['The sea has gone down: it is low tide.', 'The pull (gravity) of the Moon.'], noProj: 'describe the beach at Kribi in the morning and in the evening.' },
    ],
    action: 'Observe the sky and the Moon regularly and use the tides and the phases safely.',
    summary: [
      D([['Universe:', 'It is all of space and everything in it: stars, planets, gases and dust.'],
        ['Galaxy:', 'It is a huge group of stars, gas and dust held together by gravity.'],
        ['Satellite:', 'It is a body that moves around a planet.'],
        ['Phases of the Moon:', 'They are the different shapes of the lit part of the Moon that we see during a month.']]),
      { title: '1. The Universe', sub: 'A) Composition of the Universe', intro: 'The universe is made up of the following elements:',
        items: [['Galaxies:', 'There are billions of galaxies, and our galaxy is the Milky Way.', 'f4_milkyway.jpg', 'the Milky Way'],
          ['Stars:', 'Stars are huge balls of burning gas, and the Sun is our nearest star.'],
          ['The solar system:', 'It is the Sun with the eight planets and their satellites that move around it.', 'solar_system_big.png', 'the solar system'],
          ['Other bodies:', 'Asteroids, comets, gases and dust are also found in space.']] },
      { title: '1. The Universe', sub: 'B) Links with the Planet Earth', intro: 'The Earth is linked to the rest of the universe as follows:',
        items: [['Light and heat:', 'The Sun gives the Earth the light and heat that make life possible.'],
          ['Movements:', 'The Earth turns around the Sun, which gives the year and the seasons.'],
          ['Gravity:', 'The Sun and the Moon pull the Earth, and this causes the tides.'],
          ['The place of the Earth:', 'The Earth is the third planet from the Sun and the only one known to have life.']] },
      { title: '2. The Moon, Satellite of the Earth', sub: 'A) The Phases of the Moon', intro: 'The Moon shows the following phases during a month of about 29½ days:',
        items: [['New Moon:', 'The lit side of the Moon faces away from the Earth, so we do not see it.', 'moon_phases_big.png', 'the phases of the Moon'],
          ['First quarter:', 'We see the right half of the Moon lit by the Sun.'],
          ['Full Moon:', 'The whole lit face of the Moon faces the Earth, so we see a full circle.'],
          ['Last quarter:', 'We see the left half of the Moon lit by the Sun.']] },
      { title: '2. The Moon, Satellite of the Earth', sub: 'B) Impacts on the Natural Environment', intro: 'The Moon affects the natural environment as follows:',
        items: [['Tides:', 'The pull of the Moon makes the sea rise and fall twice a day.', 'tides.png', 'how the Moon causes tides'],
          ['Spring and neap tides:', 'At new Moon and full Moon, tides are very high (spring tides), and at the quarters they are low (neap tides).'],
          ['Light at night:', 'The full Moon lights the night, and many animals hunt or move by moonlight.'],
          ['Eclipses:', 'The Moon can hide the Sun (solar eclipse) or enter the shadow of the Earth (lunar eclipse).']] },
      { title: '2. The Moon, Satellite of the Earth', sub: 'C) Impacts on Human Activities', intro: 'The Moon affects human socio-economic activities as follows:',
        items: [['Fishing:', 'Fishermen go out and come back with the tides, and some fish at night with the full Moon.', 'f4_lowtide.jpg', 'boats at low tide'],
          ['Navigation and ports:', 'Big ships enter shallow ports such as Douala at high tide.'],
          ['Calendars and feasts:', 'Some calendars and feasts, such as Ramadan, follow the phases of the Moon.'],
          ['Farming and tradition:', 'In some villages, people plant or harvest according to the phases of the Moon.']] },
    ],
    hwAnswer: 'The numbers on the edges are latitudes (left and right) and longitudes (top and bottom). Near Garoua we read about 9° N and 13° E.',
  },
  FORM4_LESSON02_Latitudes_and_Longitudes: {
    situation: 'Ibrahim\'s cousin in Douala sends a parcel to Japan. On his phone, he shows the position of Tokyo: "35° N, 139° E". Ibrahim asks: "What do these numbers mean, and how can they show exactly where a town is?"',
    sitQA: [['What is the problem in the situation?', 'Ibrahim does not understand the numbers that give the position of a town.'],
      ['What do N and E mean?', 'North and East.'],
      ['What are these two numbers called?', 'The latitude and the longitude: the geographical coordinates.']],
    activities: [
      { sec: '1. LATITUDES', img: 'latitudes_big.png', caption: 'The major lines of latitude.', q: ['Which line is in the middle of the Earth?', 'What is its value?'], a: ['The Equator.', '0°.'], noProj: 'draw a circle with five lines across it on the board.' },
      { sec: '2. LONGITUDES', img: 'longitudes_big.png', caption: 'Lines of longitude.', q: ['Where do the lines of longitude meet?', 'What is the name of the line of 0°?'], a: ['At the poles.', 'The Greenwich Meridian.'], noProj: 'draw lines from the top to the bottom of a circle.' },
      { sec: '3. GEOGRAPHICAL COORDINATES', img: 'cameroon_grid_big.png', caption: 'Cameroon with lines of latitude and longitude.', q: 'Garoua is at about 9° N, 13° E. What does each number tell us?', a: '9° N: 9 degrees north of the Equator; 13° E: 13 degrees east of Greenwich.', noProj: 'draw a grid on the board and place a dot for Garoua.' },
    ],
    action: 'Use latitudes and longitudes to locate places correctly on maps.',
    summary: [
      D([['Latitude:', 'It is the angular distance of a place north or south of the Equator, measured in degrees.'],
        ['Longitude:', 'It is the angular distance of a place east or west of the Greenwich Meridian, measured in degrees.'],
        ['Parallels:', 'They are the lines that join places with the same latitude.'],
        ['Meridians:', 'They are the lines that join places with the same longitude, from pole to pole.'],
        ['Geographical coordinates:', 'They are the latitude and the longitude that give the exact position of a place.']]),
      { title: '1. Latitudes', sub: 'A) Major Lines of Latitude', intro: 'The major lines of latitude are the following:',
        items: [['The Equator (0°):', 'It divides the Earth into the Northern and the Southern Hemispheres.', 'latitudes_big.png', 'the major lines of latitude'],
          ['The Tropic of Cancer (23½° N):', 'It is the most northerly line where the Sun can be overhead.'],
          ['The Tropic of Capricorn (23½° S):', 'It is the most southerly line where the Sun can be overhead.'],
          ['The Arctic Circle (66½° N):', 'It limits the northern polar zone.'],
          ['The Antarctic Circle (66½° S):', 'It limits the southern polar zone.'],
          ['The poles (90° N and 90° S):', 'They are points, not lines, at the ends of the axis of the Earth.']] },
      { title: '1. Latitudes', sub: 'B) Characteristics of Latitudes', intro: 'Lines of latitude have the following characteristics:',
        items: [['Parallel lines:', 'They run from west to east, are parallel and never meet.'],
          ['Unequal length:', 'They become shorter from the Equator towards the poles.'],
          ['Values:', 'They go from 0° at the Equator to 90° at each pole, marked N or S.'],
          ['Equal spacing:', 'One degree of latitude is always about 111 km.']] },
      { title: '2. Longitudes', sub: 'A) Major Lines of Longitude', intro: 'The major lines of longitude are the following:',
        items: [['The Greenwich (Prime) Meridian (0°):', 'It passes through Greenwich in London and divides the Earth into the Eastern and Western Hemispheres.', 'longitudes_big.png', 'lines of longitude'],
          ['The 180° meridian:', 'It is opposite the Greenwich Meridian, and the International Date Line follows it.']] },
      { title: '2. Longitudes', sub: 'B) Characteristics of Longitudes', intro: 'Lines of longitude have the following characteristics:',
        items: [['Semi-circles:', 'They run from the North Pole to the South Pole.'],
          ['Equal length:', 'All meridians have the same length.'],
          ['Meeting at the poles:', 'They are far apart at the Equator and meet at the poles.'],
          ['Values:', 'They go from 0° to 180° east or west of Greenwich.']] },
      { title: '3. Differences between Latitudes and Longitudes', intro: 'Latitudes and longitudes differ in the following ways:',
        items: [['Direction:', 'Latitudes run from west to east, while longitudes run from north to south.'],
          ['Meeting:', 'Latitudes never meet, while longitudes meet at the poles.'],
          ['Length:', 'Latitudes have different lengths, while longitudes have equal lengths.'],
          ['Values:', 'Latitudes go up to 90°, while longitudes go up to 180°.'],
          ['Use:', 'Latitudes help to find climate zones, while longitudes help to calculate time.']] },
      { title: '4. Geographical Coordinates', intro: 'Geographical coordinates are written as follows:',
        items: [['Order:', 'We write the latitude first and the longitude second.', 'cameroon_grid_big.png', 'Cameroon with its grid'],
          ['Directions:', 'We add N or S to the latitude and E or W to the longitude.'],
          ['Example:', 'Garoua is at about 9° N, 13° E.']] },
    ],
    hwAnswer: 'Example: Douala–Paris flies north over the Sahara and the Mediterranean. Aeroplanes follow the curved Earth: the shortest route is a great circle, which looks curved on a flat map.',
  },
  FORM4_LESSON03_Great_Circles_and_IDL: {
    situation: 'On 31 December, Fatimé watches the news: in the afternoon, people in Australia are already celebrating the New Year, but after midnight in Garoua, people in America are still waiting. She asks: "Why does the New Year not start at the same time everywhere, and where does a new day begin?"',
    sitQA: [['What is the problem in the situation?', 'Fatimé does not understand why the New Year comes at different times and where a new day begins.'],
      ['Which country celebrates before Cameroon?', 'Australia (and New Zealand).'],
      ['Which line decides where a new day begins?', 'The International Date Line.']],
    activities: [
      { sec: '1. GREAT CIRCLES', img: 'great_circles_big.png', caption: 'A great circle and a small circle.', q: 'Which circle cuts the Earth into two equal halves?', a: 'The great circle, like the Equator.', noProj: 'cut an orange into two equal halves, then cut a small piece from the top.' },
      { sec: '2. THE INTERNATIONAL DATE LINE', img: 'f4_fireworks.jpg', caption: 'New Year fireworks in Sydney, Australia.', q: 'Why does Australia see the New Year before Cameroon?', a: 'It is far to the east, near the Date Line where each new day begins.', noProj: 'ask learners who has seen the New Year on television.' },
      { sec: '2. THE INTERNATIONAL DATE LINE', img: 'idl_big.png', caption: 'The International Date Line in the Pacific Ocean.', q: 'West of the line it is Monday. What day is it east of the line?', a: 'Sunday: one day behind.', noProj: 'draw a line and write MONDAY on the left and SUNDAY on the right.' },
    ],
    action: 'Use great circles to understand routes and the Date Line to understand the change of date.',
    summary: [
      D([['Great circle:', 'It is a circle on the surface of the Earth whose plane passes through the centre, cutting the Earth into two equal halves.'],
        ['Small circle:', 'It is a circle whose plane does not pass through the centre of the Earth.'],
        ['International Date Line:', 'It is the imaginary line, near the 180° meridian, where each new calendar day begins.']]),
      { title: '1. Great Circles', sub: 'A) Illustrations', intro: 'Great and small circles are illustrated by the following examples:',
        items: [['The Equator:', 'It is the only line of latitude that is a great circle.', 'great_circles_big.png', 'great and small circles'],
          ['Meridians:', 'Every meridian joined to its opposite meridian forms a great circle.'],
          ['Small circles:', 'The tropics, the polar circles and all other parallels are small circles.']] },
      { title: '1. Great Circles', sub: 'B) Importance', intro: 'Great circles are important for the following reasons:',
        items: [['Shortest route:', 'A great circle gives the shortest distance between two places on the Earth.'],
          ['Air transport:', 'Aeroplanes follow great circle routes to save time and fuel.'],
          ['Sea transport:', 'Ships follow great circle routes on long ocean journeys.'],
          ['Day and night:', 'The line between day and night on the Earth is a great circle.']] },
      { title: '2. The International Date Line', sub: 'A) Illustration', intro: 'The International Date Line is placed as follows:',
        items: [['Position:', 'It follows the 180° meridian in the Pacific Ocean.', 'idl_big.png', 'the International Date Line'],
          ['Bends:', 'It bends around islands and countries so that each country keeps one date.'],
          ['Two dates:', 'West of the line the date is one day ahead of the date east of the line.']] },
      { title: '2. The International Date Line', sub: 'B) Importance', intro: 'The International Date Line is important for the following reasons:',
        items: [['Start of the day:', 'It shows where each new calendar day begins on the Earth.'],
          ['Crossing westwards:', 'A traveller who crosses it going west adds one day.'],
          ['Crossing eastwards:', 'A traveller who crosses it going east removes one day.'],
          ['Correct dates:', 'It allows travellers, ships and aeroplanes to keep the correct date.']] },
    ],
    hwAnswer: 'The atlas, ruler and pencil will be used to read the latitude and longitude of towns on the map of Cameroon.',
  },
  FORM4_PRACTICAL_WORK1_Locate_a_Place_on_a_Map: {
    situation: 'A Red Cross team in Garoua must bring medicines to a small village. The office sends only two numbers: "10° N, 14° E". The driver asks: "How can we find this village on our map with only these two numbers?"',
    sitQA: [['What is the problem in the situation?', 'The team must find a village on a map with only its coordinates.'],
      ['What do the two numbers show?', 'The latitude (10° N) and the longitude (14° E).'],
      ['Where are these numbers written on a map?', 'On the sides (latitude) and at the top or bottom (longitude) of the map.']],
    activities: [
      { sec: '1. THEORETICAL BASIS', img: 'cameroon_grid_big.png', caption: 'A map of Cameroon with a grid.', q: ['On which sides of this map are the latitudes written?', 'On which sides are the longitudes written?'], a: ['On the left and right sides.', 'At the top and bottom.'], noProj: 'draw a grid on the board and number its sides.' },
      { sec: '2. PRACTICAL EXERCISE', img: 'coordinates.gif', caption: 'Animation: reading the coordinates of Garoua.', q: 'What are the coordinates of Garoua?', a: 'About 9° N, 13° E.', noProj: 'show the steps with a ruler on the map of the atlas.' },
      { sec: '3. CONTEXTUALISATION', img: 'africa_grid_big.png', caption: 'Africa with a grid of 10°.', q: 'Between which latitudes does Cameroon lie?', a: 'Between about 2° N and 13° N.', noProj: 'give learners the atlas map of Africa.' },
    ],
    action: 'Read and write coordinates carefully, latitude first.',
    summary: [
      D([['Geographical coordinates:', 'They are the latitude and the longitude of a place.'],
        ['Grid:', 'It is the network of lines of latitude and longitude drawn on a map.']]),
      { title: '1. Theoretical Basis', intro: 'We revise the following notions:',
        items: [['Latitude:', 'It is the distance north or south of the Equator, read on the left and right sides of the map.', 'cameroon_grid_big.png', 'a map of Cameroon with a grid'],
          ['Longitude:', 'It is the distance east or west of Greenwich, read at the top and bottom of the map.'],
          ['Order of writing:', 'We write the latitude first and the longitude second, with N, S, E or W.']] },
      { title: '2. Practical Exercise', intro: 'We read the coordinates of a place on a map as follows:',
        items: [['Find the place:', 'We find the town on the map.', 'coordinates_last.png', 'reading the coordinates of Garoua'],
          ['Read the latitude:', 'We follow the parallel to the side of the map and read its value and N or S.'],
          ['Read the longitude:', 'We follow the meridian to the top or bottom of the map and read its value and E or W.'],
          ['Write the coordinates:', 'We write them together, for example 9° N, 13° E.']] },
      { title: '3. Contextualisation', sub: 'A) Cameroon on the Map of Africa', intro: 'Cameroon is located on the map of Africa as follows:',
        items: [['Latitudes:', 'Cameroon lies between about 2° N and 13° N.', 'africa_grid_big.png', 'Africa with a grid'],
          ['Longitudes:', 'Cameroon lies between about 8° E and 16° E.'],
          ['Position:', 'It is in Central Africa, north of the Equator and east of the Greenwich Meridian.']] },
      { title: '3. Contextualisation', sub: 'B) Towns of the Region on the Map of Cameroon', intro: 'Some towns of our region and of Cameroon have the following coordinates:',
        items: [['Garoua:', 'It is at about 9° N, 13° E.'],
          ['Maroua:', 'It is at about 11° N, 14° E.'],
          ['Ngaoundéré:', 'It is at about 7° N, 14° E.'],
          ['Yaoundé:', 'It is at about 4° N, 12° E.']] },
    ],
    hwAnswer: 'Example: Cameroon 12:00, Dubai 15:00 (difference 3 hours ahead); Brazil (Brasília) 08:00 (4 hours behind). Places to the east are ahead in time.',
  },
  FORM4_LESSON04_Local_Time_Standard_Time_Time_Zones: {
    situation: 'The Indomitable Lions play a match in Brazil. The match starts at 3 p.m. in Brazil, but in Garoua we watch it at 7 p.m. Alima asks: "Why is the time not the same in Brazil and in Garoua at the same moment?"',
    sitQA: [['What is the problem in the situation?', 'Alima does not understand why Brazil and Garoua have different times.'],
      ['What is the time difference?', '4 hours.'],
      ['Why is it later in Garoua?', 'Garoua is east of Brazil, so it sees the Sun first.']],
    activities: [
      { sec: '1. LOCAL TIME', img: 'time_line_big.png', caption: '15° of longitude = 1 hour.', q: ['It is 12:00 at 0°. What time is it at 15° E?', 'What time is it at 15° W?'], a: ['13:00.', '11:00.'], noProj: 'draw the time line on the board.' },
      { sec: '2. TIME ZONES', img: 'time_zones_big.png', caption: 'The time zones of the world.', q: 'In which time zone is Cameroon?', a: 'GMT + 1 (West Africa Time).', noProj: 'draw 24 strips on the board.' },
      { sec: '2. TIME ZONES', img: 'f4_worldclocks.jpg', caption: 'Clocks showing the time in different cities.', q: 'Why do these clocks show different times at the same moment?', a: 'Each city is in a different time zone.', noProj: 'compare the time on a phone set to another country.' },
    ],
    action: 'Always check the local time of a place before calling or travelling.',
    summary: [
      D([['Local time (sun time):', 'It is the time given by the position of the Sun in a place: 12 noon when the Sun is highest.'],
        ['Standard time:', 'It is the official time used by a whole country or time zone.'],
        ['Time zone:', 'It is a belt of the Earth, about 15° of longitude wide, where people use the same standard time.']]),
      { title: '1. Local Time', intro: 'Local time is illustrated as follows:',
        items: [['The rule:', 'The Earth turns 360° in 24 hours, so 15° = 1 hour and 1° = 4 minutes.', 'time_line_big.png', 'time and longitude'],
          ['East is ahead:', 'Places to the east see the Sun first, so their local time is ahead.'],
          ['West is behind:', 'Places to the west see the Sun later, so their local time is behind.']] },
      { title: '2. Standard Time and Time Zones', sub: 'A) Illustration', intro: 'Standard time and time zones are organised as follows:',
        items: [['Number of zones:', 'The world is divided into 24 main time zones.', 'time_zones_big.png', 'the time zones of the world'],
          ['Reference:', 'All zones are counted from Greenwich Mean Time (GMT), in hours ahead (+) or behind (−).'],
          ['Cameroon:', 'Cameroon uses West Africa Time, which is GMT + 1.'],
          ['Boundaries:', 'Zone boundaries bend to follow the borders of countries.']] },
      { title: '2. Standard Time and Time Zones', sub: 'B) Reasons for Time Zones', intro: 'Time zones were created for the following reasons:',
        items: [['Avoid confusion:', 'Without zones, every town would have a different local time.'],
          ['Transport:', 'Trains, aeroplanes and ships need common timetables.'],
          ['Communication and trade:', 'Offices, banks, radio and television need the same time over a large area.']] },
      { title: '2. Standard Time and Time Zones', sub: 'C) Why Some Countries Have Many Time Zones', intro: 'The reasons why some countries have many time zones, with examples, are the following:',
        items: [['Great width from east to west:', 'Russia, the USA, Canada and Australia cover many degrees of longitude.'],
          ['Difference in sunrise:', 'The Sun rises hours earlier in the east of these countries than in the west.'],
          ['Examples:', 'Russia has 11 time zones, and the USA has 6.']] },
    ],
    hwAnswer: 'When it is 12 noon GMT, Garoua (GMT + 1) is at 13:00. A town at 45° E: 45 × 4 min = 180 min = 3 h ahead, so it is 15:00.',
  },
  FORM4_PRACTICAL_WORK2_Calculation_of_Time_and_Date: {
    situation: 'A World Cup match in Los Angeles (GMT − 7) starts at 5 p.m. on Sunday, local time. Moussa and his friends in Garoua (GMT + 1) want to watch it live. Moussa asks: "At what time and on what day must we switch on the television?"',
    sitQA: [['What is the problem in the situation?', 'Moussa must calculate the time and the day of the match in Garoua.'],
      ['What is the time difference between Los Angeles and Garoua?', '8 hours (from GMT − 7 to GMT + 1).'],
      ['At what time will they watch?', 'At 1 a.m. on Monday.']],
    activities: [
      { sec: '1. SUN TIME', img: 'time_calc_big.png', caption: 'A worked example.', q: 'It is 12:00 in Garoua (13° E). What is the local time at 43° E?', a: '14:00: the difference is 30°, which is 2 hours, and we add because the place is to the east.', noProj: 'write the steps on the board.' },
      { sec: '2. STANDARD TIME', img: 'time_zones_big.png', caption: 'The time zones of the world.', q: 'It is 22:00 on Friday in Garoua (GMT + 1). What time is it in Tokyo (GMT + 9)?', a: '06:00 on Saturday.', noProj: 'draw the zones on the board.' },
      { sec: '3. THE DATE LINE', img: 'idl_big.png', caption: 'The International Date Line.', q: 'It is 10:00 on Sunday just west of the Date Line. What is the day just east of the line?', a: 'Saturday, at 10:00: we remove one day.', noProj: 'draw the Date Line with the two days.' },
    ],
    action: 'Follow the rules step by step when calculating time and date.',
    summary: [
      D([['Difference of longitude:', 'It is the number of degrees between the meridians of two places.'],
        ['Date:', 'It is the day, the month and the year.']]),
      { title: '1. Sun Time (Local Time)', sub: 'A) Local Time from Longitude', intro: 'Local time is calculated from longitude as follows:',
        items: [['Difference of longitude:', 'If both places are on the same side of Greenwich, we subtract; if not, we add.', 'time_calc_big.png', 'calculating sun time'],
          ['Time difference:', 'We multiply the difference of longitude by 4 minutes.'],
          ['East or west:', 'We add the time difference for a place to the east and remove it for a place to the west.'],
          ['Example:', 'Garoua (13° E) 12:00; at 43° E: 30° × 4 = 120 min = 2 h, so 14:00.']] },
      { title: '1. Sun Time (Local Time)', sub: 'B) Longitude from Local Time', intro: 'Longitude is calculated from local time as follows:',
        items: [['Time difference:', 'We find the difference between the two local times in minutes.'],
          ['Difference of longitude:', 'We divide the time difference by 4 to get the degrees.'],
          ['Direction:', 'If the place is ahead in time it is to the east; if it is behind, it is to the west.'],
          ['Example:', 'It is 12:00 at 0° and 14:00 at place X: 120 ÷ 4 = 30°, so X is at 30° E.']] },
      { title: '2. Standard Time from Standard Time Zones', intro: 'Standard time is calculated with time zones as follows:',
        items: [['Reading the zones:', 'We read the zone of each place in hours ahead of GMT (+) or behind GMT (−).', 'time_zones_big.png', 'the time zones of the world'],
          ['Time difference:', 'We find the difference in hours between the two zones.'],
          ['Example:', 'Garoua GMT + 1 at 22:00 Friday; Tokyo GMT + 9 is 8 hours ahead, so 06:00 Saturday.']] },
      { title: '3. Time and Date across the International Date Line', intro: 'The date is calculated across the Date Line as follows:',
        items: [['Crossing westwards:', 'A traveller going west across the line adds one day.', 'idl_big.png', 'the International Date Line'],
          ['Crossing eastwards:', 'A traveller going east across the line removes one day.'],
          ['Passing midnight:', 'When a calculated time passes midnight, the date also changes.'],
          ['Example:', 'Sunday 10:00 just west of the line is Saturday 10:00 just east of it.']] },
    ],
    hwAnswer: 'Example: sunrise about 6:00 and sunset about 18:15 in Garoua. The Sun rises in the east because the Earth turns from west to east.',
  },
  FORM4_LESSON05_Rotation_of_the_Earth: {
    situation: 'Every morning in Garoua, the first light appears in the east, and in the evening the Sun disappears in the west. Oumarou\'s little sister thinks that the Sun walks around the Earth every day. She asks: "What really moves, and why do we have day and night?"',
    sitQA: [['What is the problem in the situation?', 'The sister does not know what really causes day and night.'],
      ['Where does the Sun rise and set?', 'It rises in the east and sets in the west.'],
      ['What really moves?', 'The Earth turns on itself.']],
    activities: [
      { sec: '1. MEANING OF ROTATION', img: 'rotation.gif', caption: 'Animation: the Earth turns on itself.', q: 'Watch Garoua (red dot). Why does it have day and then night?', a: 'The Earth turns: Garoua faces the Sun (day), then turns away from it (night).', noProj: 'turn a ball with a mark on it in front of a torch.' },
      { sec: '2. EFFECTS OF ROTATION', img: 'f4_sunrise.jpg', caption: 'The Sun low over the savanna.', q: 'Why does the Sun seem to rise in the east?', a: 'The Earth turns from west to east.', noProj: 'ask learners where the Sun rises in Garoua.' },
      { sec: '2. EFFECTS OF ROTATION', img: 'coriolis.gif', caption: 'Animation: winds are bent by the rotation of the Earth.', q: 'In which direction are winds bent in the Northern Hemisphere?', a: 'To the right.', noProj: 'draw a curved arrow on a circle.' },
    ],
    action: 'Use the rotation of the Earth to explain day, night and time differences.',
    summary: [
      D([['Rotation:', 'It is the turning of the Earth on its axis from west to east.'],
        ['Axis:', 'It is the imaginary line through the centre of the Earth from the North Pole to the South Pole.']]),
      { title: '1. Meaning and Illustration of Rotation', intro: 'The rotation of the Earth is described as follows:',
        items: [['Direction:', 'The Earth turns from west to east.', 'rotation_mid.png', 'the rotation of the Earth'],
          ['Duration:', 'One complete turn takes 24 hours, which is one day.'],
          ['Tilt of the axis:', 'The axis is tilted at 23½° from the vertical.'],
          ['Speed:', 'A place on the Equator moves at about 1,670 km per hour.']] },
      { title: '2. Effects of Rotation', intro: 'The rotation of the Earth has the following effects:',
        items: [['Day and night:', 'The side facing the Sun has day, while the other side has night.', 'rotation_mid.png', 'day and night'],
          ['Sunrise in the east:', 'The Sun seems to rise in the east and set in the west because the Earth turns eastwards.', 'f4_sunrise.jpg', 'the Sun low over the savanna'],
          ['Difference in time:', 'Places to the east see the Sun first, so they are ahead in time.'],
          ['Deflection of winds and currents:', 'Winds and ocean currents are bent to the right in the Northern Hemisphere and to the left in the Southern Hemisphere.', 'coriolis_last.png', 'deflection of winds'],
          ['Tides:', 'Rotation, with the pull of the Moon, gives two high tides and two low tides a day.']] },
    ],
    hwAnswer: 'In Garoua the rainy season starts around April–May and the dry season around October–November.',
  },
  FORM4_LESSON06_Revolution_of_the_Earth: {
    situation: 'In September, it is the rainy season in Garoua and the Benue is full. In December and January, the dry Harmattan season comes. Salamatou asks: "What makes the seasons change in the same way every year?"',
    sitQA: [['What is the problem in the situation?', 'Salamatou does not know what causes the change of seasons every year.'],
      ['Name the two seasons of Garoua.', 'The rainy season and the dry season.'],
      ['Which movement of the Earth causes the seasons?', 'The revolution of the Earth around the Sun.']],
    activities: [
      { sec: '1. MEANING OF REVOLUTION', img: 'revolution.gif', caption: 'Animation: the Earth moves around the Sun.', q: 'How long does the Earth take to go once around the Sun?', a: '365¼ days: one year.', noProj: 'walk around a chair (the Sun) with a ball (the Earth).' },
      { sec: '1. MEANING OF REVOLUTION', img: 'overhead_sun_big.png', caption: 'Where the Sun is overhead at midday during the year.', q: ['Where is the Sun overhead on 21 June?', 'Where is it overhead on 22 December?'], a: ['At the Tropic of Cancer.', 'At the Tropic of Capricorn.'], noProj: 'draw the Equator and the two tropics with the dates.' },
      { sec: '2. EFFECTS OF REVOLUTION', img: 'f4_rainyseason.jpg', caption: 'A farmer plants seeds when the rains begin.', q: 'In June, the Sun is overhead north of the Equator. Which season does Garoua have?', a: 'The rainy season.', noProj: 'ask learners which months are rainy in Garoua.' },
    ],
    action: 'Plan farm work according to the seasons caused by revolution.',
    summary: [
      D([['Revolution:', 'It is the movement of the Earth around the Sun.'],
        ['Orbit:', 'It is the oval (elliptical) path of the Earth around the Sun.'],
        ['Equinox:', 'It is the day when the Sun is overhead at the Equator and day and night are equal everywhere.'],
        ['Solstice:', 'It is the day when the Sun is overhead at one of the tropics.'],
        ['Leap year:', 'It is a year of 366 days, which comes every four years.']]),
      { title: '1. Meaning and Illustration of Revolution', intro: 'The revolution of the Earth is described as follows:',
        items: [['Duration:', 'One revolution takes 365¼ days, which is one year.', 'revolution_june.png', 'the Earth on its orbit'],
          ['Tilted axis:', 'During its revolution, the axis of the Earth stays tilted at 23½° in the same direction.'],
          ['March equinox (21 March):', 'The Sun is overhead at the Equator.', 'overhead_sun_big.png', 'the overhead Sun during the year'],
          ['June solstice (21 June):', 'The Sun is overhead at the Tropic of Cancer.'],
          ['September equinox (23 September):', 'The Sun is overhead at the Equator again.'],
          ['December solstice (22 December):', 'The Sun is overhead at the Tropic of Capricorn.']] },
      { title: '2. Effects of Revolution', intro: 'The revolution of the Earth has the following effects:',
        items: [['Seasons:', 'The overhead Sun moves between the tropics, which gives the seasons, such as the rainy and dry seasons of Garoua.', 'f4_rainyseason.jpg', 'planting at the start of the rains'],
          ['Varying length of day and night:', 'Away from the Equator, days are longer in summer and shorter in winter.'],
          ['Midnight Sun and polar night:', 'Beyond the polar circles, the Sun can stay up, or stay down, for 24 hours or more.'],
          ['The year and leap year:', 'A year has 365 days, and the extra quarter day gives a leap year of 366 days every four years.'],
          ['Different heating of the Earth:', 'The tilted axis makes the Sun\'s rays direct near the tropics and slanting near the poles.', 'sun_rays_big.png', 'the Sun\'s rays and latitude']] },
    ],
    hwAnswer: 'An egg shows a shell, the white and the yolk; an onion shows layers around a centre. The Earth also has layers: crust, mantle and core.',
  },
};
