// v3 patches — Form 3 (FORM4_* sources), part 2: L7–L13 (structure of the Earth, rocks, drift, plates, volcanoes, earthquakes)
// Revised model (Sept 2026): syllabus points in order, definitions apart, one element per slide with its picture,
// problem visible in the situation (the character asks a question), one question per slide in the activities.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  FORM4_LESSON07_Internal_Structure_of_the_Earth: {
    situation: 'Workers dig a deep well in Garoua. First they dig through red soil, then they reach very hard rock and must stop. Amadou asks: "What would we find if we could dig down to the centre of the Earth?"',
    sitQA: [['What is the problem in the situation?', 'Amadou does not know what is inside the Earth, under the rock.'],
      ['What did the workers find under the soil?', 'Very hard rock.'],
      ['Can people dig to the centre of the Earth?', 'No: it is about 6,370 km deep and far too hot.']],
    activities: [
      { sec: '1. ILLUSTRATIONS', img: 'earth_layers_big.png', caption: 'The layers of the Earth.', q: ['How many main layers does the Earth have?', 'Which layer is in the centre?'], a: ['Four: crust, mantle, outer core and inner core.', 'The inner core.'], noProj: 'cut a boiled egg or an onion: shell, white, yolk.' },
      { sec: '2. THE MAIN LAYERS', img: 'f2t_laterite.jpg', caption: 'People dig a big pit in the ground.', q: 'When we dig a well, which layer of the Earth do we reach?', a: 'Only the crust, the thin outer layer.', noProj: 'ask learners how deep the wells of their area are.' },
      { sec: '2. THE MAIN LAYERS', img: 'earth_depth.gif', caption: 'Animation: a journey to the centre of the Earth.', q: 'What happens to the temperature as we go deeper into the Earth?', a: 'It rises, to about 6,000 °C at the centre.', noProj: 'write the depth and temperature of each layer on the board.' },
    ],
    action: 'Use models such as an egg or an onion to explain the layers of the Earth.',
    summary: [
      D([['Crust:', 'It is the thin, solid outer layer of the Earth, on which we live.'],
        ['Mantle:', 'It is the thick layer of very hot rock between the crust and the core.'],
        ['Core:', 'It is the central part of the Earth, made mainly of iron and nickel.']]),
      { title: '1. Illustrations of the Structure of the Earth', intro: 'The structure of the Earth is illustrated in two ways:',
        items: [['Circular view:', 'The layers form circles, one inside the other, like the layers of an onion.', 'earth_layers_big.png', 'the layers of the Earth (circular view)'],
          ['Cross-sectional view:', 'A cut through the Earth shows the crust, the mantle, the outer core and the inner core from the surface to the centre.', 'earth_structure.png', 'the internal structure of the Earth (cross-section)']] },
      { title: '2. Brief Description of the Main Layers', intro: 'The main layers of the Earth are described as follows:',
        items: [['The crust:', 'It is 5 to 10 km thick under the oceans and 30 to 70 km thick under the continents. It is made of solid rock.'],
          ['The mantle:', 'It is about 2,900 km thick and made of very hot rock. Its upper part is partly molten and flows very slowly.'],
          ['The outer core:', 'It is about 2,200 km thick and made of liquid iron and nickel.'],
          ['The inner core:', 'It is a solid ball of iron and nickel with a radius of about 1,220 km. Its temperature is about 5,000 to 6,000 °C.', 'earth_depth_last.png', 'the centre of the Earth']] },
    ],
    hwAnswer: 'Examples: granite from a hill or a quarry; a sandstone block from a building site; marble tiles from a shop. Each should be named with where it was found.',
  },
  FORM4_LESSON08_Rocks: {
    situation: 'In Garoua, a new mosque is built on hard grey stones with small crystals, while some walls are made of blocks with thin layers, and the floor is covered with shiny marble. Kadidja asks: "Why are these stones so different, and how were they formed?"',
    sitQA: [['What is the problem in the situation?', 'Kadidja does not know why rocks are different and how they were formed.'],
      ['Describe two kinds of stones in the situation.', 'Hard grey stones with crystals, and blocks with thin layers.'],
      ['How are rocks grouped?', 'By their origin: igneous, sedimentary and metamorphic rocks.']],
    activities: [
      { sec: '1. IGNEOUS ROCKS', img: 'f4_granite.jpg', caption: 'Big granite rocks.', q: 'Granite has crystals. How was it formed?', a: 'Hot magma cooled slowly and became hard: it is an igneous rock.', noProj: 'show a piece of granite from the school yard.' },
      { sec: '1. SEDIMENTARY ROCKS', img: 'f4_sandstone.jpg', caption: 'A rock with layers.', q: 'This rock has layers. How was it formed?', a: 'Layers of sand and mud were pressed together: it is a sedimentary rock.', noProj: 'show layers in a cut road bank.' },
      { sec: '1. METAMORPHIC ROCKS', img: 'f4_marble.jpg', caption: 'A block of marble in a quarry.', q: 'Marble was once limestone. What changed it?', a: 'Great heat and pressure: it is a metamorphic rock.', noProj: 'show a marble tile.' },
    ],
    action: 'Recognise the rocks around us and use them wisely for building.',
    summary: [
      D([['Rock:', 'It is a hard, natural material made of one or more minerals, which forms the crust of the Earth.'],
        ['Magma:', 'It is melted rock found under the ground.'],
        ['Sediments:', 'They are small pieces of rock, sand, mud and remains of living things laid down by water, wind or ice.']]),
      { title: '1. Classification of Rocks according to Origin', sub: 'A) Igneous Rocks', intro: 'Igneous rocks have the following characteristics and examples:',
        items: [['Formation:', 'They are formed when magma or lava cools and hardens.', 'f4_granite.jpg', 'granite, an igneous rock'],
          ['Crystals:', 'They are made of crystals, large when magma cools slowly underground and small when lava cools quickly.'],
          ['Hardness:', 'They are hard, have no layers and contain no fossils.'],
          ['Intrusive examples:', 'Granite and gabbro cooled inside the crust.'],
          ['Extrusive examples:', 'Basalt and pumice cooled on the surface.', 'lsa_basalt.jpg', 'basalt']] },
      { title: '1. Classification of Rocks according to Origin', sub: 'B) Sedimentary Rocks', intro: 'Sedimentary rocks have the following characteristics and examples:',
        items: [['Formation:', 'They are formed from sediments laid down in layers and pressed together over a long time.', 'f4_sandstone.jpg', 'sandstone, a sedimentary rock'],
          ['Layers:', 'They are arranged in layers called strata.'],
          ['Fossils:', 'They often contain fossils of plants and animals.', 'f4_fossil.jpg', 'a fossil in rock'],
          ['Mechanically formed examples:', 'Sandstone, clay and conglomerate are made of rock fragments.'],
          ['Organically and chemically formed examples:', 'Limestone, coal and rock salt come from living things or from chemical deposits.']] },
      { title: '1. Classification of Rocks according to Origin', sub: 'C) Metamorphic Rocks', intro: 'Metamorphic rocks have the following characteristics and examples:',
        items: [['Formation:', 'They are formed when igneous or sedimentary rocks are changed by great heat and pressure.', 'f4_marble.jpg', 'marble, a metamorphic rock'],
          ['Hardness:', 'They are usually harder and more compact than the original rock.'],
          ['Bands:', 'Many of them show bands or thin sheets.'],
          ['Examples:', 'Limestone becomes marble, clay becomes slate, sandstone becomes quartzite and granite becomes gneiss.']] },
      { title: '2. The Rock Cycle', intro: 'The rock cycle is illustrated as follows:',
        items: [['Rock cycle:', 'It is the slow process by which one type of rock changes into another type.', 'rock_cycle_big.png', 'the rock cycle']] },
    ],
    hwAnswer: 'The east coast of South America fits into the west coast of Africa like pieces of a jigsaw puzzle: the two continents were once joined.',
  },
  FORM4_LESSON09_Continental_Drift: {
    situation: 'Djibrilla looks at a world map. The coast of Africa and the coast of South America look like two pieces of a puzzle, although the Atlantic Ocean separates them. He asks: "Were these two continents once joined, and how could they move apart?"',
    sitQA: [['What is the problem in the situation?', 'Djibrilla wonders whether Africa and South America were once joined and how they moved apart.'],
      ['What does he notice?', 'The two coasts fit together like a puzzle.'],
      ['Who first explained this?', 'Alfred Wegener, in 1912.']],
    activities: [
      { sec: '1. MAIN IDEA', img: 'jigsaw.gif', caption: 'Animation: closing the Atlantic Ocean.', q: 'What happens when we bring South America near Africa?', a: 'The two coasts fit together like pieces of a puzzle.', noProj: 'cut a paper map of the two continents and fit them.' },
      { sec: '2. ILLUSTRATION OF DRIFTING', img: 'drift_stages_big.png', caption: 'The break-up of Pangaea.', q: ['What was the name of the single continent of long ago?', 'Into which two parts did it split first?'], a: ['Pangaea.', 'Laurasia in the north and Gondwanaland in the south.'], noProj: 'draw the three stages on the board.' },
      { sec: '3. EVIDENCE', img: 'f4_fossil.jpg', caption: 'A fossil in rock.', q: 'Fossils of the same small reptile, Mesosaurus, are found in Brazil and in southern Africa. What does this prove?', a: 'The two continents were once joined: this small animal could not swim across the ocean.', noProj: 'explain that Mesosaurus lived in fresh water.' },
    ],
    action: 'Use maps and evidence to explain how the continents moved.',
    summary: [
      D([['Continental drift:', 'It is the theory that the continents were once joined and have slowly moved apart.'],
        ['Pangaea:', 'It is the single super-continent that existed about 250 million years ago.'],
        ['Panthalassa:', 'It is the single ocean that surrounded Pangaea.']]),
      { title: '1. Main Idea of the Theory', intro: 'The main idea of the theory of continental drift is the following:',
        items: [['Author:', 'The theory was proposed by the German scientist Alfred Wegener in 1912.'],
          ['One super-continent:', 'All the continents once formed one big land mass, Pangaea, surrounded by one ocean, Panthalassa.'],
          ['Slow drifting:', 'Pangaea broke up, and its pieces slowly drifted to their present positions.']] },
      { title: '2. Illustration of Drifting', intro: 'The continents drifted in the following stages:',
        items: [['About 250 million years ago:', 'All the land formed one continent, Pangaea.', 'drift_stages_big.png', 'the break-up of Pangaea'],
          ['About 200 to 150 million years ago:', 'Pangaea split into Laurasia in the north and Gondwanaland in the south, separated by the Tethys Sea.'],
          ['Later:', 'Laurasia gave North America, Europe and Asia, while Gondwanaland gave South America, Africa, India, Australia and Antarctica.'],
          ['Today:', 'The continents still move a few centimetres each year.']] },
      { title: '3. Evidence of Continental Drift', intro: 'The following evidence supports the theory:',
        items: [['Jigsaw fit:', 'The coasts of Africa and South America fit together like a puzzle.', 'jigsaw_last.png', 'the jigsaw fit of the continents'],
          ['Fossils:', 'The same fossils of plants and animals, such as Mesosaurus, are found on continents now separated by oceans.', 'f4_fossil.jpg', 'a fossil'],
          ['Rocks and mountains:', 'The same types and ages of rocks and mountain chains continue from one continent to another.'],
          ['Ancient ice marks:', 'Marks of old glaciers are found in hot lands such as Africa, India and Australia.'],
          ['Coal in cold lands:', 'Coal, formed from tropical forests, is found in Antarctica.']] },
    ],
    hwAnswer: 'Answers vary. Example: an earthquake in Turkey in 2023 destroyed many buildings and killed thousands of people.',
  },
  FORM4_LESSON10_Plate_Tectonics: {
    situation: 'On television, Mariam sees an earthquake in Japan and a volcano in Italy, while the ground in Garoua feels safe. She knows that Mount Cameroon is also an active volcano. She asks: "Why do earthquakes and volcanoes happen in some places and not in others?"',
    sitQA: [['What is the problem in the situation?', 'Mariam does not know why earthquakes and volcanoes happen only in some places.'],
      ['Name one active volcano in Cameroon.', 'Mount Cameroon.'],
      ['Where do most earthquakes and volcanoes happen?', 'At the edges of the plates.']],
    activities: [
      { sec: '1. MAIN IDEAS', img: 'plates_big.png', caption: 'The main plates of the Earth.', q: 'On which plate is Cameroon?', a: 'On the African Plate.', noProj: 'break a biscuit into pieces: the pieces are like the plates.' },
      { sec: '1. MAIN IDEAS', img: 'mantle_convection.gif', caption: 'Animation: convection currents in the mantle.', q: 'What makes the plates move?', a: 'Convection currents in the hot mantle.', noProj: 'watch rice move in boiling water.' },
      { sec: '3. PLATE MARGINS AND LANDFORMS', img: 'margins.gif', caption: 'Animation: plates move apart (left) and together (right).', q: ['What rises when two plates move apart?', 'What happens to one plate when two plates move together?'], a: ['Magma rises and forms new crust.', 'It sinks under the other plate.'], noProj: 'move two books apart, then push them together.' },
    ],
    action: 'Use the theory of plate tectonics to explain earthquakes and volcanoes.',
    summary: [
      D([['Plate tectonics:', 'It is the theory that the outer shell of the Earth is broken into rigid plates that move slowly.'],
        ['Plate:', 'It is a large, rigid piece of the crust and the upper mantle.'],
        ['Plate margin:', 'It is the edge where two plates meet.']]),
      { title: '1. Main Ideas of the Theory', intro: 'The theory of plate tectonics has two main ideas:',
        items: [['The geometric idea:', 'The outer shell of the Earth is divided into seven major plates and many smaller ones that fit together like a puzzle.', 'plates_big.png', 'the major plates'],
          ['The kinetic idea:', 'The plates move 2 to 10 centimetres a year, pushed by convection currents in the mantle.', 'mantle_convection_mid.png', 'convection currents in the mantle']] },
      { title: '2. The Plates', intro: 'The major plates of the Earth are the following:',
        items: [['The African Plate:', 'It carries Africa, including Cameroon.'],
          ['The Eurasian Plate:', 'It carries Europe and most of Asia.'],
          ['The American Plates:', 'The North American and South American Plates carry the Americas.'],
          ['The Pacific Plate:', 'It is the largest plate and lies under the Pacific Ocean.'],
          ['The Indo-Australian and Antarctic Plates:', 'They carry India, Australia and Antarctica.']] },
      { title: '3. Plate Margins and Main Landforms', intro: 'The margins where plates meet are of three types:',
        items: [['Constructive (divergent) margins:', 'Plates move apart and magma rises to form new crust. Landforms: ocean ridges and rift valleys, such as the East African Rift Valley.', 'plate_margins.png', 'the three types of plate margins'],
          ['Destructive (convergent) margins:', 'Plates move together and one sinks under the other. Landforms: fold mountains, ocean trenches and volcanoes.', 'margins_last.png', 'plates move apart and together'],
          ['Conservative (transform) margins:', 'Plates slide past each other and no crust is made or destroyed. Landforms: faults, with strong earthquakes, such as the San Andreas Fault.']] },
    ],
    hwAnswer: 'Mount Cameroon last erupted in 2012 (and in 1999 and 2000). In 1999 lava flowed towards the sea near Bakingili and destroyed roads and farms.',
  },
  FORM4_LESSON11_Volcanoes: {
    situation: 'Mount Cameroon, near Buea, is a high mountain and an active volcano: in 1999 and 2000, lava flowed down its sides. Yet the dark soils around it are very fertile, and many people live there. Pupils from Buea ask: "What exactly is a volcano, and how is it built?"',
    sitQA: [['What is the problem in the situation?', 'The pupils do not know what a volcano is or how it is built.'],
      ['What came out of Mount Cameroon in 2000?', 'Lava.'],
      ['Is Mount Cameroon active, dormant or extinct?', 'Active: it has erupted recently.']],
    activities: [
      { sec: '1. ORIGIN OF VOLCANOES', img: 'f4_eruption.jpg', caption: 'A volcano erupts.', q: 'What comes out of a volcano during an eruption?', a: 'Lava, gases and ash.', noProj: 'describe the 2000 eruption of Mount Cameroon.' },
      { sec: '2. TYPES OF VOLCANOES', img: 'volcano_types_big.png', caption: 'Types of volcanoes by shape.', q: 'Which type of volcano has gentle slopes made of runny lava?', a: 'The shield volcano.', noProj: 'draw the three shapes on the board.' },
      { sec: '4. GENERAL STRUCTURE', img: 'volcano_big.png', caption: 'The parts of a volcano.', q: ['Where is magma stored under a volcano?', 'Through which part does it rise?'], a: ['In the magma chamber.', 'Through the vent (pipe).'], noProj: 'draw a simple volcano on the board.' },
    ],
    action: 'Know the volcanoes of Cameroon and respect safety rules near them.',
    summary: [
      D([['Volcano:', 'It is an opening in the crust through which magma, gases and ash come out onto the surface.'],
        ['Volcanicity:', 'It is all the processes by which magma rises into the crust or onto the surface.'],
        ['Magma:', 'It is molten rock under the ground.'],
        ['Lava:', 'It is magma that comes out onto the surface.']]),
      { title: '1. Origin of Volcanoes', intro: 'Volcanoes are found in the following places:',
        items: [['Constructive plate margins:', 'Where plates move apart, magma rises through the gap, as in Iceland and the East African Rift.'],
          ['Destructive plate margins:', 'Where one plate sinks and melts, magma rises to the surface, as around the Pacific Ocean.'],
          ['Hot spots:', 'In some places, hot magma rises from deep in the mantle in the middle of a plate, as in Hawaii.'],
          ['Lines of weakness:', 'Magma rises along cracks in the crust, as on the Cameroon Volcanic Line.', 'cameroon_volcanic_line.png', 'volcanoes of Cameroon']] },
      { title: '2. Types of Volcanoes', sub: 'A) According to Activity', intro: 'Volcanoes are classified according to their activity as follows:',
        items: [['Active volcano:', 'It erupts now or has erupted recently, like Mount Cameroon.', 'lsa_mtcameroon.jpg', 'Mount Cameroon'],
          ['Dormant volcano:', 'It has not erupted for a long time but can erupt again.'],
          ['Extinct volcano:', 'It will never erupt again, like Mount Manengouba.']] },
      { title: '2. Types of Volcanoes', sub: 'B) According to Shape', intro: 'Volcanoes are classified according to their shape as follows:',
        items: [['Shield volcano:', 'It has gentle slopes built by runny lava, like Mauna Loa in Hawaii.', 'volcano_types_big.png', 'types of volcanoes by shape'],
          ['Composite cone:', 'It is a high, steep cone built of layers of lava and ash, like Mount Cameroon.'],
          ['Ash and cinder cone:', 'It is a small, steep cone built of ash and cinders.']] },
      { title: '3. Processes of Volcanicity', intro: 'Magma moves by two processes:',
        items: [['Intrusion:', 'Magma cools inside the crust and forms dykes, sills, laccoliths and batholiths.', 'intrusive_extrusive_big.png', 'intrusive and extrusive features'],
          ['Extrusion:', 'Magma comes out as lava, ash and gases and builds cones and lava plateaux.']] },
      { title: '4. General Structure of a Volcano', intro: 'A volcano has the following parts:',
        items: [['Magma chamber:', 'It is the store of molten rock under the volcano.', 'volcano_big.png', 'the structure of a volcano'],
          ['Vent (pipe):', 'It is the channel through which magma rises.'],
          ['Cone:', 'It is the mountain built by layers of lava and ash.'],
          ['Crater:', 'It is the round hollow at the top of the vent.', 'f4_crater.jpg', 'a crater'],
          ['Secondary cone:', 'It is a small cone on the side of the volcano, fed by a side vent.']] },
    ],
    hwAnswer: 'Reasons: very fertile volcanic soils; cool climate and good rainfall for crops. Dangers: lava flows can destroy farms; earthquakes and gases can harm people.',
  },
  FORM4_LESSON12_Impact_of_Volcanicity_on_Man: {
    situation: 'A friend of Aboubakar\'s family wants to start a farm near Buea because the soil is very fertile. Another friend warns him: "It is dangerous! You will live near an active volcano." The farmer asks: "Is a volcano only a danger, or can it also be useful, and how can we live safely near it?"',
    sitQA: [['What is the problem in the situation?', 'The farmer must choose between fertile land and the danger of a volcano, and does not know how to live safely there.'],
      ['Give one danger of the volcano.', 'Lava can burn farms and houses.'],
      ['Give one advantage of the area.', 'The volcanic soil is very fertile.']],
    activities: [
      { sec: '1. VOLCANIC HAZARDS', img: 'f4_lavahouse.jpg', caption: 'Lava has covered a road.', q: 'What does lava do to farms, roads and houses?', a: 'It burns and buries them.', noProj: 'describe the lava of 1999 near Bakingili.' },
      { sec: '1. VOLCANIC HAZARDS', img: 'f4_nyos.jpg', caption: 'Lake Nyos, North-West Region of Cameroon.', q: 'In 1986, gas came out of this lake. What happened?', a: 'The gas killed about 1,700 people and many animals.', noProj: 'tell the story of Lake Nyos (1986).' },
      { sec: '2. IMPORTANCE OF VOLCANOES', img: 'f4_geothermal.jpg', caption: 'A power station that uses the heat of the Earth.', q: 'How can volcanic areas produce electricity?', a: 'Hot steam from the ground turns machines (turbines).', noProj: 'compare with steam from a boiling pot.' },
    ],
    action: 'Respect warnings and safety measures in volcanic areas.',
    summary: [
      D([['Hazard:', 'It is an event that can harm people, property and the environment.'],
        ['Resource:', 'It is anything in nature that people can use.'],
        ['Geothermal energy:', 'It is energy produced from the heat inside the Earth.']]),
      { title: '1. Volcanic Hazards', intro: 'Volcanoes cause the following hazards:',
        items: [['Lava flows:', 'They burn and bury houses, farms and roads.', 'f4_lavahouse.jpg', 'lava over a road'],
          ['Ash falls:', 'Ash covers crops, pollutes water, makes roofs collapse and stops aeroplanes.'],
          ['Poisonous gases:', 'Gases from Lake Nyos killed about 1,700 people and many animals in 1986.', 'f4_nyos.jpg', 'Lake Nyos'],
          ['Mudflows (lahars):', 'Ash mixed with rain flows down the slopes and buries villages.'],
          ['Earthquakes and tsunamis:', 'Eruptions shake the ground and can cause giant sea waves.']] },
      { title: '2. Importance of Volcanoes', intro: 'Volcanoes are useful to man in the following ways:',
        items: [['Fertile soils:', 'Volcanic soils around Mount Cameroon are good for tea, bananas, cocoa and rubber.', 'f2t_tea_highlands.jpg', 'tea on fertile highlands'],
          ['Geothermal energy:', 'Power stations produce electricity from volcanic heat, as in Kenya and Iceland.', 'f4_geothermal.jpg', 'a geothermal power station'],
          ['Tourism:', 'Tourists visit volcanoes, craters and crater lakes, and climb Mount Cameroon during the Race of Hope.'],
          ['Building materials and minerals:', 'Basalt and pozzolana are used for roads and houses, and some minerals come from volcanic rocks.'],
          ['Hot springs:', 'Hot springs are used for bathing and health care.']] },
      { title: '3. Adaptation, Mitigation and Preventive Measures', intro: 'People reduce volcanic dangers with the following measures:',
        items: [['Monitoring:', 'Scientists watch volcanoes with instruments to predict eruptions.', 'lsa_volcmonitor.jpg', 'monitoring a volcano'],
          ['Warning and evacuation:', 'People are warned and leave dangerous areas in time.'],
          ['Land-use planning:', 'Houses and schools are not built in the paths of old lava flows.'],
          ['Degassing:', 'Pipes remove the gas from Lake Nyos to prevent another disaster.'],
          ['Diverting lava:', 'Walls and channels can turn lava away from towns.']] },
    ],
    hwAnswer: 'Answers vary. Example: in Buea, people felt the ground shake for a few seconds during the eruption of 1999; windows rattled and people ran outside.',
  },
  FORM4_LESSON13_Earthquakes: {
    situation: 'On the news, Ismaïla sees that an earthquake in Morocco in September 2023 destroyed many villages and killed thousands of people. He asks: "What makes the ground shake like this, and how can people protect themselves?"',
    sitQA: [['What is the problem in the situation?', 'Ismaïla does not know what causes earthquakes and how people can protect themselves.'],
      ['What did the earthquake destroy?', 'Villages and houses.'],
      ['Why do so many people die?', 'Their houses fall on them.']],
    activities: [
      { sec: 'DEFINITIONS', img: 'quake.gif', caption: 'Animation: the waves of an earthquake.', q: ['Where does the earthquake start?', 'What is the point on the surface just above it?'], a: ['At the focus.', 'The epicentre.'], noProj: 'drop a stone in water: the waves spread in circles.' },
      { sec: '2. MANIFESTATION', img: 'f4_seismograph.jpg', caption: 'A seismograph.', q: 'What does this instrument record?', a: 'The shaking (seismic waves) of the ground.', noProj: 'draw a zigzag line on the board.' },
      { sec: '3. IMPACT ON MAN', img: 'f4_quakedamage.jpg', caption: 'Houses destroyed by an earthquake.', q: 'What is the main cause of death during an earthquake?', a: 'Buildings fall on people.', noProj: 'ask learners how houses could be made stronger.' },
    ],
    action: 'Know what to do during an earthquake: take cover, protect your head and stay away from walls and windows.',
    summary: [
      D([['Earthquake:', 'It is a sudden shaking or vibration of the crust of the Earth.'],
        ['Focus:', 'It is the point under the ground where the earthquake starts.'],
        ['Epicentre:', 'It is the point on the surface directly above the focus, where the shaking is strongest.'],
        ['Seismic waves:', 'They are the shock waves that spread out from the focus.']]),
      { title: '1. Causes of Earthquakes', intro: 'Earthquakes have the following causes:',
        items: [['Plate movements:', 'The sudden movement of plates along faults is the main cause of earthquakes.', 'quake_mid.png', 'focus and epicentre'],
          ['Volcanic eruptions:', 'Rising magma and eruptions shake the ground around volcanoes.'],
          ['Collapse:', 'The collapse of caves or old mines shakes the ground.'],
          ['Human activities:', 'Mining, nuclear tests, explosions and the weight of big dams can cause small earthquakes.']] },
      { title: '2. Manifestation of Earthquakes', intro: 'Earthquakes show themselves and are measured as follows:',
        items: [['Shaking and cracks:', 'The ground shakes, cracks open and buildings sway or fall.'],
          ['Seismograph:', 'It is an instrument that records the seismic waves.', 'f4_seismograph.jpg', 'a seismograph'],
          ['Richter scale:', 'It measures the strength (magnitude) of an earthquake, usually from 1 to 9.'],
          ['Aftershocks:', 'Smaller earthquakes often follow the main shock.']] },
      { title: '3. Impact on Man', intro: 'Earthquakes affect people in the following ways:',
        items: [['Loss of life:', 'Falling buildings kill and injure many people.', 'f4_quakedamage.jpg', 'houses destroyed by an earthquake'],
          ['Destruction of property:', 'Houses, roads, bridges, pipes and power lines are destroyed.'],
          ['Fires and diseases:', 'Broken gas pipes cause fires, and dirty water spreads diseases.'],
          ['Tsunamis and landslides:', 'Earthquakes under the sea cause tsunamis, and on slopes they cause landslides.', 'lsa_tsunami.jpg', 'a tsunami'],
          ['Economic losses:', 'Rebuilding costs a lot of money, and many people lose their jobs and homes.']] },
      { title: '4. Adaptation and Mitigation', intro: 'People reduce the damage of earthquakes with the following measures:',
        items: [['Strong buildings:', 'Buildings designed to resist shaking reduce deaths, as in Japan.'],
          ['Land-use planning:', 'People avoid building on faults and on loose, unstable ground.'],
          ['Monitoring and warning:', 'Seismographs watch active zones, and warning systems alert people.'],
          ['Education and drills:', 'People learn to take cover under a table and protect their heads.'],
          ['Emergency services:', 'Rescue teams, hospitals and emergency supplies are prepared in advance.']] },
    ],
    hwAnswer: 'The running water washed away the soil, made small channels (rills) and carried the soil down to the bottom of the slope or into the gutter.',
  },
};
