// v3 patches — Form 3 (FORM4_* sources), part 3: L14–L17, FS2, L18–L22 (denudation, weathering, rivers)
// Revised model (Sept 2026): syllabus points in order, definitions apart, one element per slide with its picture,
// problem visible in the situation (the character asks a question), one question per slide in the activities.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  FORM4_LESSON14_Denudation: {
    situation: 'After a heavy storm in Garoua, Halima sees a small channel cut in the red soil beside the road. The water has carried sand and stones and dropped them lower down. She asks: "How is the land worn down like this, and what forces do it?"',
    sitQA: [['What is the problem in the situation?', 'Halima does not know how the land is worn down and by which forces.'],
      ['What did the water carry?', 'Sand and stones.'],
      ['Which force wore away the soil here?', 'Running water (rain water).']],
    activities: [
      { sec: '1. PROCESSES OF DENUDATION', img: 'f4_gully.jpg', caption: 'A channel cut by rain water.', q: 'What has the rain water done to the soil?', a: 'It has worn away the soil and carried it away.', noProj: 'describe a road side after a storm.' },
      { sec: '1. PROCESSES OF DENUDATION', img: 'denudation.gif', caption: 'Animation: the processes of denudation.', q: 'What happens to the rock before it can be carried away?', a: 'It is broken down in its place: this is weathering.', noProj: 'write the processes in boxes on the board.' },
      { sec: '2. AGENTS OF DENUDATION', img: 'f4_muddyriver.jpg', caption: 'A muddy river.', q: ['Which agent carries this mud?', 'Name another agent of denudation.'], a: ['Running water.', 'Wind (or waves).'], noProj: 'describe the Benue in the rainy season.' },
    ],
    action: 'Protect the soil from denudation by keeping plant cover.',
    summary: [
      D([['Denudation:', 'It is the general wearing down and lowering of the land surface by natural forces.'],
        ['Agent of denudation:', 'It is a natural force that wears down and carries away rock and soil.']]),
      { title: '1. Major Processes of Denudation', intro: 'Denudation takes place through the following processes:',
        items: [['Weathering:', 'It is the breaking down of rocks in their place by the weather, plants and animals.', 'denudation_last.png', 'the processes of denudation'],
          ['Erosion:', 'It is the wearing away and removal of rock and soil by a moving agent.', 'f4_gully.jpg', 'erosion by rain water'],
          ['Transportation:', 'It is the carrying away of the eroded material by the agent, until the agent loses energy and drops it.']] },
      { title: '2. Main Agents of Denudation', intro: 'The main agents of denudation are the following:',
        items: [['Running water:', 'Rain and rivers wear away and carry soil and rock, and they are the most important agent in wet regions.', 'f4_muddyriver.jpg', 'a muddy river'],
          ['Wind:', 'Wind blows away loose sand and dust and wears rocks, especially in deserts and semi-arid areas such as the Far North.'],
          ['Waves:', 'Sea waves wear away and build up the coast, as at Kribi and Limbe.']] },
    ],
    hwAnswer: 'The old wall has cracks, peeling paint and crumbling or dark patches, while the new wall is smooth and clean. It was damaged by rain, sun and heat, plants and time: this is weathering.',
  },
  FORM4_LESSON15_Weathering: {
    situation: 'In Sadou\'s compound, an old wall is cracked, and its stones break into sandy pieces at the bottom, while a new wall built with the same stones still looks strong. Sadou asks: "What slowly breaks the stones of the old wall, and why faster in some places than in others?"',
    sitQA: [['What is the problem in the situation?', 'Sadou does not know what breaks the stones of the old wall and why.'],
      ['What happens to the stones of the old wall?', 'They crack and break into sandy pieces.'],
      ['Why is the new wall still strong?', 'It has not yet been exposed to the weather for a long time.']],
    activities: [
      { sec: 'DEFINITIONS', img: 'f4_oldwall.jpg', caption: 'An old wall.', q: 'What makes this old wall break slowly?', a: 'Sun, rain, air and plants: this is weathering.', noProj: 'show an old wall of the school.' },
      { sec: '1. TYPES OF WEATHERING', img: 'f4_rust.jpg', caption: 'Rusty iron.', q: 'Rain and air change iron into red, weak rust. Which type of weathering changes rocks in the same way?', a: 'Chemical weathering.', noProj: 'show a rusty nail.' },
      { sec: '2. GENERAL FACTORS OF WEATHERING', img: 'f4_roots.jpg', caption: 'Roots in a rock.', q: 'How can plants break rocks?', a: 'Their roots grow in cracks and open them.', noProj: 'show a tree root lifting a pavement.' },
    ],
    action: 'Observe weathering around you and protect buildings from its effects.',
    summary: [
      D([['Weathering:', 'It is the breaking down or decay of rocks in their place, by the weather, plants and animals, without the rock being carried away.']]),
      { title: '1. Types of Weathering', intro: 'There are two main types of weathering:',
        items: [['Physical (mechanical) weathering:', 'Rocks break into smaller pieces without any change in their minerals. It is common in hot deserts and cold mountains.', 'weathering_types_big.png', 'physical and chemical weathering'],
          ['Chemical weathering:', 'The minerals of the rock are changed by water and air, so the rock rots or dissolves. It is common in hot, wet regions.']] },
      { title: '2. General Factors of Weathering', intro: 'Weathering depends on the following factors:',
        items: [['Climate:', 'Hot and wet climates favour chemical weathering, while hot deserts favour physical weathering.'],
          ['Rock characteristics:', 'Soft rocks and rocks with many joints or soluble minerals break faster.', 'f4_oldwall.jpg', 'an old weathered wall'],
          ['Vegetation:', 'Roots open cracks, and rotting plants produce acids that attack rocks.', 'f4_roots.jpg', 'roots in a rock'],
          ['Time:', 'The longer rocks are exposed, the more they are weathered.'],
          ['Human activities:', 'Roads, quarries, mining and farming expose rocks to weathering.']] },
    ],
    hwAnswer: 'At 1 p.m. the rock is hot, and at 7 p.m. it is cooler. Daily heating makes the outer layer expand and cooling makes it contract; after many years this breaks the rock (thermal shattering).',
  },
  FORM4_LESSON16_Physical_Weathering: {
    situation: 'In the dry season, Yaya walks past a big granite rock. At midday it is too hot to touch, and at night it is cool; its outer surface peels off in thin layers, like an onion. He asks: "How can the Sun alone break such a hard rock?"',
    sitQA: [['What is the problem in the situation?', 'Yaya does not understand how a hard rock breaks without being carried away.'],
      ['What happens to the outer surface of the rock?', 'It peels off in thin layers.'],
      ['What changes between midday and night?', 'The temperature: the rock is hot by day and cool at night.']],
    activities: [
      { sec: '1. THERMAL SHATTERING', img: 'exfoliation.gif', caption: 'Animation: heating by day, cooling by night.', q: 'What happens to the outer layer of the rock after many days and nights?', a: 'It cracks and peels off.', noProj: 'draw a rock with curved layers peeling off.' },
      { sec: '1. THERMAL SHATTERING', img: 'f4_granite.jpg', caption: 'Rounded granite rocks.', q: 'What do we call this peeling of rock in curved layers?', a: 'Exfoliation (onion weathering).', noProj: 'describe the rocks of Mount Tinguelin.' },
      { sec: '5. PHYSICALLY INDUCED BIOLOGICAL WEATHERING', img: 'f4_roots.jpg', caption: 'Roots in a rock.', q: 'How do the roots break the rock?', a: 'They grow bigger in the cracks and push the rock apart.', noProj: 'show a tree root lifting a pavement.' },
    ],
    action: 'Recognise the products of physical weathering around us.',
    summary: [
      D([['Physical weathering:', 'It is the breaking of rocks into smaller pieces without any change in their minerals.'],
        ['Exfoliation:', 'It is the peeling of rock in thin, curved layers, like the layers of an onion.']]),
      { title: '1. Thermal Shattering', intro: 'Thermal shattering works as follows:',
        items: [['Process:', 'By day the Sun heats the outer layer of the rock, which expands, and at night it cools and contracts. After many years, the outer layer cracks and peels off.', 'exfoliation_last.png', 'exfoliation'],
          ['Products:', 'Curved sheets of rock (exfoliation), rounded rocks called exfoliation domes, and angular pieces (block disintegration).', 'f4_granite.jpg', 'rounded granite rocks']] },
      { title: '2. Frost Shattering', intro: 'Frost shattering works as follows:',
        items: [['Process:', 'Water enters cracks and freezes at night; ice takes more space than water, so it widens the cracks until the rock breaks.', 'lsa_frost.jpg', 'frost on rock'],
          ['Products:', 'Sharp, angular pieces of rock that collect at the foot of slopes as scree, in cold mountains.']] },
      { title: '3. Alternate Wetting and Drying (Slaking)', intro: 'Alternate wetting and drying works as follows:',
        items: [['Process:', 'Clay rocks swell when they are wet and shrink when they dry, so they crack.'],
          ['Products:', 'Crumbled clay and deep cracks, as in the black soils of the Far North in the dry season.', 'f2t_cracked_soil.jpg', 'cracked soil']] },
      { title: '4. Pressure Release (Unloading)', intro: 'Pressure release works as follows:',
        items: [['Process:', 'When the rocks above are removed by erosion, the rock below expands and cracks in sheets parallel to the surface.', 'physical_weathering.png', 'processes of physical weathering'],
          ['Products:', 'Sheets of rock and dome-shaped hills such as inselbergs.']] },
      { title: '5. Physically Induced Biological Weathering', intro: 'Living things break rocks physically as follows:',
        items: [['Plant roots:', 'Roots grow in cracks, become thicker and push the rock apart.', 'f4_roots.jpg', 'roots in a rock'],
          ['Burrowing animals:', 'Termites, worms and rodents dig holes and bring broken rock to the surface.'],
          ['Products:', 'Broken blocks of rock and loose, crumbly material.']] },
    ],
    hwAnswer: 'The iron became rusty: it turned reddish-brown and weak, and pieces flake off. This is oxidation, a form of chemical weathering.',
  },
  FORM4_LESSON17_Chemical_Weathering: {
    situation: 'In the rainy season, Kaltouma sees that the old metal gate of her compound is reddish-brown and crumbles, while a new gate still shines. Around Garoua, many soils are also red. She asks: "How do rain and air change the gate and the rocks, and why are our soils red?"',
    sitQA: [['What is the problem in the situation?', 'Kaltouma does not know how water and air change metals and rocks.'],
      ['What colour is the old gate?', 'Reddish-brown (rusty).'],
      ['What do rain and air do to rocks?', 'They change their minerals, so the rocks rot: this is chemical weathering.']],
    activities: [
      { sec: '4. OXIDATION', img: 'f4_rust.jpg', caption: 'Rusty iron.', q: 'Rain and air make iron red and weak. What is this process called?', a: 'Oxidation.', noProj: 'show a rusty nail.' },
      { sec: '4. OXIDATION', img: 'f4_redsoil.jpg', caption: 'A red soil.', q: 'Why are many soils around Garoua red?', a: 'The iron in the rocks and soil has been oxidised (rusted).', noProj: 'show red soil from the school yard.' },
      { sec: '2. CARBONATION', img: 'f4_karst.jpg', caption: 'A limestone cave.', q: 'Rain water slowly dissolves limestone. What forms after a very long time?', a: 'Caves, with stalactites and stalagmites.', noProj: 'drop vinegar on chalk: it fizzes and dissolves.' },
    ],
    action: 'Explain the red soils and caves around us by chemical weathering.',
    summary: [
      D([['Chemical weathering:', 'It is the decay of rocks by a chemical change in their minerals, mainly by water and air.']]),
      { title: '1. Solution', intro: 'Solution works as follows:',
        items: [['Process:', 'Water dissolves soluble minerals such as rock salt and gypsum.', 'chemical_weathering.png', 'processes of chemical weathering'],
          ['Products:', 'The minerals are carried away in the water, and hollows and holes are left in the rock.']] },
      { title: '2. Carbonation', intro: 'Carbonation works as follows:',
        items: [['Process:', 'Rain water absorbs carbon dioxide and becomes a weak acid that dissolves limestone.', 'f4_karst.jpg', 'a limestone cave'],
          ['Products:', 'Caves, stalactites, stalagmites and grooves in limestone areas.']] },
      { title: '3. Hydrolysis', intro: 'Hydrolysis works as follows:',
        items: [['Process:', 'Water reacts with the feldspar of granite and changes it into clay.'],
          ['Products:', 'Clay (kaolin) and loose quartz sand, so granite crumbles.']] },
      { title: '4. Oxidation', intro: 'Oxidation works as follows:',
        items: [['Process:', 'Oxygen in air and water reacts with the iron in rocks, as rust forms on iron.', 'f4_rust.jpg', 'rusty iron'],
          ['Products:', 'Red, yellow or brown crumbly rock and red soils, such as the lateritic soils of Cameroon.', 'f4_redsoil.jpg', 'a red soil']] },
      { title: '5. Hydration', intro: 'Hydration works as follows:',
        items: [['Process:', 'Some minerals take in water, swell and put pressure on the rock.'],
          ['Products:', 'The rock becomes softer, cracks and breaks into pieces.']] },
      { title: '6. Chemically Induced Biological Weathering', intro: 'Living things weather rocks chemically as follows:',
        items: [['Process:', 'Rotting plants, lichens, mosses and bacteria produce acids that attack the minerals of rocks.', 'lsa_lichen.jpg', 'lichens on a rock'],
          ['Products:', 'Rotten, crumbly rock and humus that forms soil.']] },
    ],
    hwAnswer: 'The soil comes from the weathering of the rocks under and around the farm, mixed with rotting plants. After heavy rain, rocks and soil can slide and block roads (landslides).',
  },
  FORM4_FURTHER_STUDY2_Impact_of_Weathering: {
    situation: 'Djaouro\'s uncle says that the rich soil of his farm came from rocks that broke down over thousands of years. But last rainy season, weathered rocks and soil slid from a hill and blocked the road to his farm. Djaouro asks: "Is weathering good or bad for our environment?"',
    sitQA: [['What is the problem in the situation?', 'Djaouro does not know whether weathering is useful or harmful.'],
      ['Give one good effect of weathering in the situation.', 'It formed the rich soil of the farm.'],
      ['Give one bad effect.', 'Rocks and soil slid and blocked the road.']],
    activities: [
      { sec: '1. POSITIVE IMPACTS', img: 'soil_profile_big.png', caption: 'A soil profile.', q: 'How does weathering make soil?', a: 'Rocks break down into small pieces that mix with humus.', noProj: 'dig a small pit in the school garden.' },
      { sec: '2. NEGATIVE IMPACTS', img: 'f4_landslide.jpg', caption: 'A landslide.', q: 'Why do landslides often happen after heavy rain?', a: 'The weathered soil becomes wet and heavy and slides down the slope.', noProj: 'describe a landslide seen on the news.' },
      { sec: '3. MEASURES', img: 'f4_terraces.jpg', caption: 'Terraces on a slope.', q: 'How do these steps protect the slope?', a: 'They slow down the water and hold the soil.', noProj: 'describe the terraces of the Mandara Mountains.' },
    ],
    action: 'Plant trees and grass to hold the soil and build with good drains.',
    summary: [
      D([['Soil:', 'It is the loose top layer of the land, made of weathered rock, humus, air and water, where plants grow.'],
        ['Mass movement:', 'It is the movement of soil and rock down a slope under the force of gravity.'],
        ['Landslide:', 'It is the sudden sliding of soil and rocks down a slope.']]),
      { title: '1. Positive Impacts of Weathering', intro: 'Weathering has the following positive impacts on the environment:',
        items: [['Soil formation:', 'Weathering produces the soils used for farming and for forests.', 'soil_profile_big.png', 'a soil profile'],
          ['Minerals:', 'Weathering concentrates useful minerals, such as the bauxite of Minim-Martap.', 'lsa_bauxite.jpg', 'bauxite'],
          ['Building materials:', 'Weathering produces sand, gravel, clay and laterite used for building.'],
          ['Landforms and tourism:', 'Weathering shapes caves, inselbergs and rock domes that attract tourists.']] },
      { title: '2. Negative Impacts of Weathering', intro: 'Weathering has the following negative impacts on the environment:',
        items: [['Mass movement:', 'Weathered material slides down slopes, blocks roads and destroys houses and farms.', 'f4_landslide.jpg', 'a landslide'],
          ['Damage to buildings and monuments:', 'Weathering cracks walls, bridges, roads, tombs and monuments.', 'f4_oldwall.jpg', 'a damaged wall'],
          ['Loss of soil fertility:', 'In hot, wet areas, heavy rain washes plant food out of deeply weathered soils (leaching).'],
          ['Hard crusts:', 'Oxidation can form hard lateritic crusts that are difficult to farm.']] },
      { title: '3. Measures against the Negative Impacts', intro: 'The negative impacts can be reduced with the following measures:',
        items: [['Plant cover:', 'Trees and grass hold the soil on slopes.'],
          ['Terraces:', 'Terraces slow down running water on slopes.', 'f4_terraces.jpg', 'terraces'],
          ['Good buildings:', 'Durable materials, good foundations and drains protect buildings and tombs.'],
          ['Regular repairs:', 'Walls, tombs and monuments are repaired and painted regularly.']] },
    ],
    hwAnswer: 'Answers vary. Example: the Benue flows slowly and is wide in the dry season; in the rainy season it flows fast, is brown with mud and carries branches and sand.',
  },
  FORM4_LESSON18_Action_of_Rivers: {
    situation: 'The Benue begins on the Adamawa Plateau and flows into Nigeria. Near its source the water is fast, but in Garoua it is wide and slow and carries a lot of brown mud in the rainy season. Aminatou asks: "Why does the river change along its way, and how does it wear away the land?"',
    sitQA: [['What is the problem in the situation?', 'Aminatou does not know why a river changes from its source to its mouth, or how it wears away the land.'],
      ['Where does the Benue begin?', 'On the Adamawa Plateau.'],
      ['What does the brown colour of the water show?', 'The river carries a lot of mud (its load).']],
    activities: [
      { sec: '1. THE LONG PROFILE', img: 'long_profile_big.png', caption: 'The long profile of a river.', q: ['Where is the river steep?', 'Where is it almost flat?'], a: ['Near its source.', 'Near its mouth.'], noProj: 'draw a curve going down from left to right.' },
      { sec: '2. MECHANISMS OF RIVER EROSION', img: 'river_erosion_big.png', caption: 'How a river erodes.', q: 'What happens to stones when they hit each other in the river?', a: 'They become smaller and rounder: this is attrition.', noProj: 'rub two stones together.' },
      { sec: '2. MECHANISMS OF RIVER EROSION', img: 'f4_muddyriver.jpg', caption: 'A muddy river.', q: 'Where does the mud carried by this river come from?', a: 'From the soil and rock worn away from its bed, its banks and its basin.', noProj: 'describe the Benue in the rainy season.' },
    ],
    action: 'Protect river banks from erosion by planting trees.',
    summary: [
      D([['Long profile of a river:', 'It is the slope of a river from its source to its mouth, seen from the side.'],
        ['Source:', 'It is the place where a river begins.'],
        ['Mouth:', 'It is the place where a river ends in a sea, a lake or another river.'],
        ['Load:', 'It is the material carried by a river.']]),
      { title: '1. Illustration of the Long Profile', intro: 'The three courses and the shape of the long profile are the following:',
        items: [['The upper course:', 'The slope is steep, the water is fast, and the river cuts down.', 'long_profile_big.png', 'the long profile of a river'],
          ['The middle course:', 'The slope is gentle, the valley widens, and the river cuts sideways.'],
          ['The lower course:', 'The land is almost flat, the water is slow, and the river drops its load.'],
          ['Shape:', 'The long profile is a concave curve, steep at the source and gentle towards the mouth.']] },
      { title: '2. Mechanisms of River Erosion', intro: 'Rivers erode their bed and banks by the following mechanisms:',
        items: [['Hydraulic action:', 'The force of the moving water breaks and removes rock and soil from the bed and banks.', 'river_erosion_big.png', 'mechanisms of river erosion'],
          ['Abrasion (corrasion):', 'Stones carried by the river scrape and wear the bed and the banks.'],
          ['Attrition:', 'Stones carried by the river hit one another and become smaller and rounder.'],
          ['Solution (corrosion):', 'The river water dissolves some rocks, such as limestone.']] },
    ],
    hwAnswer: 'Example: at the Vina Falls the river falls over a hard rock step into a deep pool. The valley is narrow with steep sides, and the water is fast and noisy.',
  },
  FORM4_LESSON19_Upper_Course: {
    situation: 'Near Ngaoundéré, the Vina River falls over a cliff of hard rock. The water is fast and noisy, and the valley sides are steep, while the Benue at Garoua is wide and slow. Bouba asks: "Why is the valley so different near the source, and how did this waterfall form?"',
    sitQA: [['What is the problem in the situation?', 'Bouba does not know why the upper course of a river looks so different and how waterfalls form.'],
      ['Describe the water of the Vina River.', 'Fast and noisy.'],
      ['Describe the valley sides.', 'They are steep.']],
    activities: [
      { sec: '2. LANDFORMS OF THE UPPER COURSE', img: 'vvalley_big.png', caption: 'A valley in the upper course.', q: ['What is the shape of this valley?', 'Why does it have this shape?'], a: ['A V shape.', 'The river cuts down into its bed.'], noProj: 'draw a V on the board.' },
      { sec: '2. LANDFORMS OF THE UPPER COURSE', img: 'f4_waterfall.jpg', caption: 'A waterfall.', q: 'Why does a waterfall form?', a: 'The river flows from hard rock onto soft rock that is worn away faster.', noProj: 'describe the Vina or Tello Falls.' },
      { sec: '2. LANDFORMS OF THE UPPER COURSE', img: 'waterfall.gif', caption: 'Animation: a waterfall moves back.', q: 'What does the waterfall leave behind as it moves back over many years?', a: 'A gorge.', noProj: 'draw the waterfall at three dates.' },
    ],
    action: 'Use the waterfalls of our region for tourism and energy while respecting safety.',
    summary: [
      D([['Upper course:', 'It is the part of a river near its source, in the highlands.'],
        ['Vertical erosion:', 'It is the downward cutting of a river into its bed.']]),
      { title: '1. Main Characteristics and Processes of the Upper Course', intro: 'The upper course has the following characteristics and processes:',
        items: [['Steep slope:', 'The river is near its source in the highlands, so its slope is steep.'],
          ['Fast water:', 'The water flows fast and is noisy, but the channel is narrow and shallow.'],
          ['Big load:', 'The river carries large stones and boulders, mainly rolled along its bed.'],
          ['Vertical erosion:', 'The river cuts down into its bed by hydraulic action and abrasion.']] },
      { title: '2. Landforms of the Upper Course', intro: 'The upper course has the following landforms:',
        items: [['V-shaped valley:', 'The river cuts down while weathering wears back the sides, giving a narrow, steep-sided valley.', 'vvalley_big.png', 'a V-shaped valley'],
          ['Interlocking spurs:', 'They are ridges of hard rock around which the river winds.', 'interlocking_spurs.png', 'interlocking spurs'],
          ['Waterfall:', 'It forms where a river falls over a band of hard rock lying on soft rock, as at the Vina and Tello Falls.', 'waterfall_last.png', 'formation of a waterfall'],
          ['Gorge:', 'It is a deep, narrow, steep-sided valley left as a waterfall moves back, as at the Kola Gorges near Guider.'],
          ['Rapids (cataracts):', 'They are stretches of fast, rough water where hard and soft rocks alternate on the river bed.'],
          ['Potholes:', 'They are round holes drilled in the river bed by stones swirled by the water.']] },
    ],
    hwAnswer: 'The drawing should show the Benue with bends (meanders) and sandbanks. The water is fastest on the outside of each bend and in the middle of the channel.',
  },
  FORM4_LESSON20_Middle_Course: {
    situation: 'From the Benue Bridge in Garoua, Adama sees that the river makes big bends. On the outside of each bend the bank is steep and falls into the water, while on the inside there is a gentle beach of sand. He asks: "Why is one bank steep and the other gentle?"',
    sitQA: [['What is the problem in the situation?', 'Adama does not understand why the two banks of a bend are different.'],
      ['Describe the outside of the bend.', 'The bank is steep.'],
      ['Describe the inside of the bend.', 'It is a gentle beach of sand.']],
    activities: [
      { sec: '1. CHARACTERISTICS AND PROCESSES', img: 'load.gif', caption: 'Animation: how a river carries its load.', q: 'How does the river carry the big stones along its bed?', a: 'It rolls them: this is traction.', noProj: 'roll a stone along a table.' },
      { sec: '2. LANDFORMS OF THE MIDDLE COURSE', img: 'f4_meander.jpg', caption: 'A river with big bends.', q: 'What do we call these big bends of a river?', a: 'Meanders.', noProj: 'draw a winding river on the board.' },
      { sec: '2. LANDFORMS OF THE MIDDLE COURSE', img: 'meander.gif', caption: 'Animation: erosion and deposition in a meander.', q: ['On which side of the bend does the water erode?', 'On which side does it deposit?'], a: ['On the outside.', 'On the inside.'], noProj: 'mark the fast and slow water on the drawing.' },
    ],
    action: 'Avoid building on the outside of river bends where banks are eroded.',
    summary: [
      D([['Middle course:', 'It is the part of a river between the upper and the lower course, where the slope becomes gentle.'],
        ['Lateral erosion:', 'It is the sideways cutting of a river into its banks.']]),
      { title: '1. Main Characteristics and Processes of the Middle Course', sub: 'A) Characteristics', intro: 'The middle course has the following characteristics:',
        items: [['Gentle slope:', 'The slope becomes gentle, and the water flows more smoothly.'],
          ['Wider valley:', 'The valley is wider and more open, with a flat floor.'],
          ['More water:', 'Tributaries have joined the river, so its volume and load are bigger.'],
          ['Lateral erosion:', 'The river cuts sideways into its banks more than downwards.']] },
      { title: '1. Main Characteristics and Processes of the Middle Course', sub: 'B) Transport of the Load', intro: 'The river carries its load in the following ways:',
        items: [['Traction:', 'Large stones are rolled along the bed.', 'load_mid.png', 'how a river transports its load'],
          ['Saltation:', 'Small stones and sand bounce along the bed.'],
          ['Suspension:', 'Fine mud and clay are carried in the water, which looks brown.'],
          ['Solution:', 'Dissolved minerals are carried invisibly in the water.']] },
      { title: '2. Landforms of the Middle Course', intro: 'The middle course has the following landforms:',
        items: [['Meander:', 'It is a large bend in a river, formed by erosion on the outside and deposition on the inside of the bend.', 'meander_last.png', 'a meander'],
          ['River cliff:', 'It is a steep bank on the outside of a bend, where the fast, deep water erodes.', 'rivercliff_big.png', 'river cliff and slip-off slope'],
          ['Slip-off slope:', 'It is a gentle bank on the inside of a bend, where the slow water deposits sand and gravel.'],
          ['Open V-shaped valley:', 'The valley becomes wider, with gentler sides and a narrow flat floor.']] },
    ],
    hwAnswer: 'A delta is shaped like a triangle or a fan of land with many channels. The Niger Delta reaches the Gulf of Guinea (Atlantic Ocean); the Nile Delta reaches the Mediterranean Sea.',
  },
  FORM4_LESSON21_Lower_Course: {
    situation: 'In the dry season, Oumar sees many sandbanks in the Benue at Garoua, and the water splits into small channels. In the rainy season, the river covers the flat land around it. He asks: "Where does all this sand come from, and what does the river build near its mouth?"',
    sitQA: [['What is the problem in the situation?', 'Oumar does not know where the sand comes from and what landforms the river builds in its lower course.'],
      ['What does he see in the dry season?', 'Sandbanks and small channels.'],
      ['What happens in the rainy season?', 'The river floods the flat land around it.']],
    activities: [
      { sec: '2. LANDFORMS OF THE LOWER COURSE', img: 'f4_floodplain.jpg', caption: 'Flat land beside a river.', q: 'This flat land is covered by the river during floods. What is it called?', a: 'A floodplain.', noProj: 'describe the land along the Benue.' },
      { sec: '2. LANDFORMS OF THE LOWER COURSE', img: 'oxbow.gif', caption: 'Animation: the formation of an ox-bow lake.', q: 'How does an ox-bow lake form?', a: 'The river cuts through the neck of a meander and leaves the old bend as a lake.', noProj: 'draw the three stages on the board.' },
      { sec: '2. LANDFORMS OF THE LOWER COURSE', img: 'f4_delta.jpg', caption: 'A delta seen from space.', q: 'The river drops its load where it enters the sea. What landform does it build?', a: 'A delta.', noProj: 'show the Niger Delta in the atlas.' },
    ],
    action: 'Farm floodplains wisely and prepare for floods.',
    summary: [
      D([['Lower course:', 'It is the part of a river near its mouth, where the land is almost flat.'],
        ['Deposition:', 'It is the dropping of the load when the river loses energy.'],
        ['Alluvium:', 'It is the fine, fertile mud and sand deposited by a river.']]),
      { title: '1. Main Characteristics and Processes of the Lower Course', intro: 'The lower course has the following characteristics and processes:',
        items: [['Almost flat land:', 'The slope is very gentle, so the river flows slowly.'],
          ['Wide, deep channel:', 'The river has its greatest volume of water.'],
          ['Fine load:', 'The river carries mainly fine mud and sand in suspension.'],
          ['Deposition:', 'The slow river drops much of its load, especially during floods and at its mouth.']] },
      { title: '2. Landforms of the Lower Course', intro: 'The lower course has the following landforms:',
        items: [['Floodplain:', 'It is the wide, flat land beside the river, built by layers of alluvium dropped during floods.', 'f4_floodplain.jpg', 'a floodplain'],
          ['Levees:', 'They are raised banks built when the river drops its coarsest load next to the channel during floods.', 'levee_delta.png', 'levees, floodplain and delta'],
          ['Ox-bow lake:', 'It is an old meander cut off from the river when a flood cuts through its neck.', 'oxbow_last.png', 'formation of an ox-bow lake'],
          ['Delta:', 'It is a flat, fan-shaped land built by a river at its mouth, like the deltas of the Nile and the Niger.', 'f4_delta.jpg', 'a delta'],
          ['Braided channels:', 'They form when sandbanks split the river into many small channels, as on the Benue in the dry season.']] },
    ],
    hwAnswer: 'Advantages: fertile soil for rice and onions, water for animals and fishing. Problems: floods destroy houses and crops, and bring diseases like cholera and malaria.',
  },
  FORM4_LESSON22_Man_and_Floodplain_Interactions: {
    situation: 'In September 2012, heavy rain and water released from the Lagdo Dam flooded many villages along the Benue near Garoua, destroying farms and houses. Yet every year farmers come back to plant rice and onions there. A farmer asks: "Why do we stay on the floodplain, and how can we live there safely?"',
    sitQA: [['What is the problem in the situation?', 'People farm and live on the floodplain although floods destroy their farms and houses.'],
      ['What caused the flood of 2012?', 'Heavy rain and water released from the Lagdo Dam.'],
      ['Why do farmers come back?', 'The floodplain soil is fertile and there is water.']],
    activities: [
      { sec: '1. IMPORTANCE', img: 'f4_ricefield.jpg', caption: 'Rice fields on a floodplain.', q: 'Why are floodplains good for farming?', a: 'The soil is fertile (alluvium) and there is water.', noProj: 'name crops grown along the Benue.' },
      { sec: '2. PROBLEMS', img: 'f4_flood.jpg', caption: 'A flooded area.', q: 'What problems do floods cause to people?', a: 'They destroy houses and crops and spread diseases.', noProj: 'describe the flood of 2012.' },
      { sec: '3. SOLUTIONS', img: 'f4_dyke.jpg', caption: 'A raised bank along a river.', q: 'How does this raised bank protect the land?', a: 'It stops the river from flooding the land behind it.', noProj: 'draw a river with a bank on each side.' },
    ],
    action: 'Build away from rivers and follow flood warnings.',
    summary: [
      D([['Floodplain:', 'It is the flat land beside a river that is covered by water during floods.'],
        ['Flood:', 'It is the covering by water of land that is usually dry.'],
        ['Dyke:', 'It is an artificial bank built to stop a river or the sea from flooding the land.']]),
      { title: '1. Importance of Rivers and Floodplains to Man', intro: 'Rivers and floodplains are important to man for the following reasons:',
        items: [['Farming:', 'Floodplains have fertile alluvium for rice, onions, maize and vegetables.', 'f4_ricefield.jpg', 'rice fields on a floodplain'],
          ['Water supply:', 'Rivers supply water for drinking, animals and irrigation.'],
          ['Fishing:', 'Rivers and flooded lands are rich in fish.'],
          ['Energy:', 'Dams on rivers produce electricity, like the Lagdo Dam on the Benue.', 'f2t_lagdo.jpg', 'the Lagdo Dam'],
          ['Transport:', 'Rivers are used to carry people and goods, as on the Benue to Nigeria in the rainy season.'],
          ['Settlement:', 'Flat, fertile land near water attracts villages and towns.']] },
      { title: '2. Problems of Living in Floodplains', intro: 'People in floodplains face the following problems:',
        items: [['Floods:', 'Floods destroy houses, crops, roads and bridges.', 'f4_flood.jpg', 'a flooded area'],
          ['Loss of life:', 'People and animals can drown during floods.'],
          ['Diseases:', 'Stagnant water spreads cholera, malaria and bilharzia.'],
          ['Bank collapse and silting:', 'River banks collapse, and silt fills drains and river beds.'],
          ['Displacement:', 'Families lose their homes and must move.']] },
      { title: '3. Solutions to the Problems of Living in Floodplains', intro: 'The following solutions reduce these problems:',
        items: [['Dykes and raised banks:', 'They hold back the river during floods.', 'f4_dyke.jpg', 'a raised bank'],
          ['Dams:', 'Dams store flood water and release it slowly, with warnings to people downstream.'],
          ['Warnings:', 'Radio and phone messages warn people before floods.'],
          ['Safe building:', 'Houses should be built on higher ground or on raised foundations.'],
          ['Trees and clean channels:', 'Trees along the banks hold the soil, and clearing silt from drains and river beds lets water flow.']] },
    ],
    hwAnswer: 'The wind blows over the water and pushes it into small waves (ripples). The waves move in the direction the wind is blowing; a stronger wind gives bigger waves.',
  },
};
