// Homework of the first cycle (rule of Mr Kamdem, Sept 2026): one very short sentence that prepares the NEXT lesson
// (a small part of it), never "ask your parents". The answer is corrected at the start of the next lesson.
// Keys: 'Lesson 1', 'Practical Work 2'... for F1/F2 (native specs); source names for F3 and F2T.
module.exports = {
  F1: {
    'Lesson 1': ['Name the eight planets of the solar system.', 'Mercury, Venus, the Earth, Mars, Jupiter, Saturn, Uranus and Neptune.'],
    'Lesson 2': ['Name three ways of representing the Earth.', 'The globe, the world map and map projections.'],
    'Practical Work 1': ['Give the latitude of the Equator.', '0°.'],
    'Practical Work 2': ['Name the two movements of the Earth.', 'Rotation and revolution.'],
    'Lesson 3': ['State how many degrees the Earth turns in one hour.', '15° (360° in 24 hours).'],
    'Practical Work 3': ['List four components of the natural environment.', 'Climate, relief, soil and drainage (also flora and fauna).'],
    'Lesson 4': ['Name the two natural regions of Cameroon.', 'The equatorial region in the south and the tropical region in the north.'],
    'Lesson 5': ['Name the two elements shown on a climograph.', 'Temperature and rainfall.'],
    'Practical Work 4': ['Give two causes of the degradation of natural regions.', 'Deforestation and bush fires (also overgrazing and population growth).'],
    'Lesson 6': ['Give two forms of damage to the environment of a school.', 'Waste on the ground and cut trees (also soil erosion).'],
    'Guided Work 1': ['Name the two types of solid waste.', 'Biodegradable and non-biodegradable waste.'],
    'Practical Work 5': ['Name the two main gases of the atmosphere.', 'Nitrogen (about 78 %) and oxygen (about 21 %).'],
    'Lesson 7': ['Name the two types of atmospheric pressure.', 'High pressure and low pressure.'],
    'Lesson 8': ['Name three types of atmospheric disturbances.', 'Thunderstorms, cyclones and dust storms (also torrential rain and drizzle).'],
    'Lesson 9': ['Name two atmospheric disturbances that affect Cameroon.', 'Thunderstorms with torrential rain and dust storms (Harmattan).'],
    'Further Study 1': ['Name the four steps of rain formation.', 'Evaporation, rising and cooling, condensation and precipitation.'],
    'Practical Work 6': ['Give two causes of climate change.', 'Burning fuels and deforestation.'],
    'Lesson 10': ['Name the three layers of the Earth.', 'The crust, the mantle and the core.'],
    'Lesson 11': ['Name the two types of plates.', 'Continental plates and oceanic plates.'],
    'Lesson 12': ['Give one consequence of an earthquake.', 'Buildings collapse (also loss of life, tsunamis and landslides).'],
    'Lesson 13': ['Give one rule to follow during an earthquake.', 'Take cover under a strong table and protect your head (or go outside, away from buildings).'],
    'Further Study 2': ['List three items of an emergency bag.', 'Water, a torch and a first-aid kit (also food, a radio and documents).'],
  },
  F2: {
    'Lesson 1': ['Write the formula of the birth rate.', 'Birth rate = (births ÷ population) × 1,000, in ‰.'],
    'Practical Work 1': ['Write the formula of population density.', 'Density = population ÷ area, in people per km².'],
    'Lesson 2': ['Calculate the density of the Littoral: 3,850,000 people on 20,248 km².', '3,850,000 ÷ 20,248 ≈ 190 people per km².'],
    'Practical Work 2': ['Name the natural zone that covers southern Cameroon.', 'The equatorial zone (the forest zone).'],
    'Lesson 3': ['Give two causes of deforestation in Cameroon.', 'Logging and farming (also firewood and roads).'],
    'Further Study 1': ['Name two resources of the tropical zone of Cameroon.', 'Pasture for cattle and farmland for cotton (also wildlife and the Lagdo lake).'],
    'Lesson 4': ['Give two causes of the firewood crisis.', 'Population growth and over-cutting of trees.'],
    'Further Study 2': ['Name three products gathered from the wild in Cameroon.', 'Eru, njangsa and bush mango (also bitter cola, shea nuts and honey).'],
    'Further Study 3': ['Name two plant resources and two animal resources of Cameroon.', 'Timber trees and oil palms; elephants and fish.'],
    'Practical Work 3': ['Name the largest hot desert of Africa.', 'The Sahara.'],
    'Lesson 5': ['Give two causes of water scarcity.', 'Long dry seasons and population growth (also pollution and waste).'],
    'Further Study 4': ['Name three patterns of rural settlements.', 'Nucleated, dispersed and linear (also regular).'],
    'Lesson 6': ['Name the two largest towns of Cameroon.', 'Douala and Yaoundé.'],
    'Lesson 7': ['List three informal activities in towns.', 'Moto-taxi driving, street selling and tailoring.'],
    'Further Study 5': ['Name the headquarters of the North and Far North Regions.', 'Garoua (North) and Maroua (Far North).'],
    'Practical Work 4': ['Give three urban problems of Cameroonian towns.', 'Slums, floods and unemployment (also traffic jams and waste).'],
    'Further Study 6': ['Give two products that villages send to towns.', 'Food crops and cattle (also firewood).'],
    'Lesson 8': ['Define rural exodus.', 'It is the massive movement of people from villages to towns.'],
    'Further Study 7': ['Give two ways to make villages more attractive.', 'Build roads and health centres, and create jobs in modern farming.'],
  },
  F3: {
    FORM4_LESSON01_Our_Planet_the_Earth: ['Name the four main phases of the Moon.', 'New Moon, first quarter, full Moon and last quarter.'],
    FORM4_FURTHER_STUDY1_Universe_and_Moon: ['Give the value of the Equator and of the Greenwich Meridian.', 'Both are 0°.'],
    FORM4_LESSON02_Latitudes_and_Longitudes: ['Define a great circle.', 'It is a circle that cuts the Earth into two equal halves.'],
    FORM4_LESSON03_Great_Circles_and_IDL: ['Give the coordinates of Garoua.', 'About 9° N, 13° E.'],
    FORM4_PRACTICAL_WORK1_Locate_a_Place_on_a_Map: ['State how many minutes of time equal 1° of longitude.', '4 minutes.'],
    FORM4_LESSON04_Local_Time_Standard_Time_Time_Zones: ['Calculate the local time at 30° E when it is 12:00 at 0°.', '30 × 4 = 120 minutes = 2 hours ahead, so 14:00.'],
    FORM4_PRACTICAL_WORK2_Calculation_of_Time_and_Date: ['Define the rotation of the Earth.', 'It is the turning of the Earth on its axis from west to east.'],
    FORM4_LESSON05_Rotation_of_the_Earth: ['State how long the Earth takes to go around the Sun.', '365¼ days (one year).'],
    FORM4_LESSON06_Revolution_of_the_Earth: ['Name the four main layers of the Earth.', 'The crust, the mantle, the outer core and the inner core.'],
    FORM4_LESSON07_Internal_Structure_of_the_Earth: ['Name the three types of rocks.', 'Igneous, sedimentary and metamorphic rocks.'],
    FORM4_LESSON08_Rocks: ['Name the single continent of long ago.', 'Pangaea.'],
    FORM4_LESSON09_Continental_Drift: ['Name the plate on which Cameroon lies.', 'The African Plate.'],
    FORM4_LESSON10_Plate_Tectonics: ['Name one active volcano of Cameroon.', 'Mount Cameroon.'],
    FORM4_LESSON11_Volcanoes: ['Give one danger and one advantage of volcanoes.', 'Danger: lava flows (or poisonous gases). Advantage: fertile soils.'],
    FORM4_LESSON12_Impact_of_Volcanicity_on_Man: ['Define an earthquake.', 'It is a sudden shaking of the ground.'],
    FORM4_LESSON13_Earthquakes: ['Name the three processes of denudation.', 'Weathering, erosion and transportation.'],
    FORM4_LESSON14_Denudation: ['Name the two types of weathering.', 'Physical weathering and chemical weathering.'],
    FORM4_LESSON15_Weathering: ['Name two processes of physical weathering.', 'Thermal shattering and frost shattering (also wetting and drying, pressure release).'],
    FORM4_LESSON16_Physical_Weathering: ['Name two processes of chemical weathering.', 'Oxidation and carbonation (also solution, hydrolysis and hydration).'],
    FORM4_LESSON17_Chemical_Weathering: ['Give one positive impact of weathering.', 'It forms soils (also minerals and building materials).'],
    FORM4_FURTHER_STUDY2_Impact_of_Weathering: ['Name the three courses of a river.', 'The upper, middle and lower courses.'],
    FORM4_LESSON18_Action_of_Rivers: ['Name two landforms of the upper course of a river.', 'The V-shaped valley and the waterfall (also gorges, rapids and potholes).'],
    FORM4_LESSON19_Upper_Course: ['Define a meander.', 'It is a large bend in a river.'],
    FORM4_LESSON20_Middle_Course: ['Name two landforms of the lower course of a river.', 'The floodplain and the delta (also levees and ox-bow lakes).'],
    FORM4_LESSON21_Lower_Course: ['Give two uses of floodplains.', 'Farming on fertile alluvium and fishing (also water supply and settlement).'],
    FORM4_LESSON22_Man_and_Floodplain_Interactions: ['Name the two types of waves.', 'Constructive waves and destructive waves.'],
    FORM4_LESSON23_Wave_Action_in_Coastal_Areas: ['Name three erosional features of waves.', 'The cliff, the cave and the arch (also the stack and the stump).'],
    FORM4_LESSON24_Erosional_Features_of_Wave_Action: ['Name two depositional features of waves.', 'The beach and the spit (also bars and tombolos).'],
    FORM4_LESSON25_Depositional_Features_of_Wave_Action: ['Name the two main sea ports of Cameroon.', 'Douala and Kribi.'],
    FORM4_LESSON26_Impact_of_Wave_Action_on_Coastal_Development: ['Name the largest hot desert of Africa.', 'The Sahara.'],
    FORM4_LESSON27_SemiArid_Desert_Landscapes: ['Name the two types of sand dunes.', 'Barchans and seif dunes.'],
    FORM4_LESSON28_Depositional_Features_Wind: ['Give two resources of hot deserts.', 'Oil and solar energy (also oases and minerals).'],
    FORM4_LESSON29_Man_in_Hot_Desert: ['Name the four main layers of the atmosphere.', 'The troposphere, the stratosphere, the mesosphere and the thermosphere.'],
    FORM4_LESSON30_The_Atmosphere: ['Distinguish weather from climate.', 'Weather is the state of the atmosphere at a given time; climate is the average weather over about 30 years.'],
    FORM4_LESSON31_Weather_and_Climate: ['Name the instrument that records the maximum and minimum temperatures.', 'Six\'s thermometer.'],
    FORM4_LESSON32_Atmospheric_Temperatures: ['Name the instrument that measures air pressure.', 'The barometer.'],
    FORM4_LESSON33_Other_Weather_Elements: ['Define condensation.', 'It is the change of water vapour into liquid water.'],
    FORM4_LESSON34_Condensation: ['Name the three types of rainfall.', 'Convectional, relief (orographic) and frontal rainfall.'],
    FORM4_LESSON35_Precipitation: ['Name the pressure belt found at the Equator.', 'The Equatorial Low.'],
    FORM4_LESSON36_Pressure_Belts_Planetary_Winds: ['Name the wind that blows from the sea to the land by day.', 'The sea breeze.'],
    FORM4_LESSON37_Local_Winds: ['Give two factors of temperature.', 'Latitude and altitude (also cloud cover, winds, ocean currents and vegetation).'],
    FORM4_LESSON38_Factors_of_Temperature: ['Name the four main stages of the water cycle.', 'Evaporation, condensation, precipitation and runoff.'],
    FORM4_LESSON39_Hydrological_Cycle: ['Name two greenhouse gases.', 'Carbon dioxide and methane.'],
    FORM4_LESSON40_Global_Warming: ['Define desertification.', 'It is the lasting spread of desert conditions into dry lands.'],
    FORM4_LESSON41_Floods_Droughts_Desertification: ['Give two causes of water scarcity.', 'A long dry season and population growth (also pollution and waste).'],
    FORM4_LESSON42_Water_Scarcity: ['Give three ways to conserve water at home.', 'Close taps, repair leaks and collect rainwater.'],
  },
  F2T: {
    F2T_L1_P1_Equatorial_Location_Climate: ['Name the layers of the equatorial forest.', 'Emergents, canopy, under-canopy, shrubs and forest floor.'],
    F2T_L1_P2_Equatorial_Soils_Vegetation: ['Name three resources of the equatorial region.', 'Timber, minerals and water (also farmland and wildlife).'],
    F2T_L1_P3_Equatorial_Resources: ['Define shifting cultivation.', 'It is farming a piece of forest for a few years and moving when the soil is poor.'],
    F2T_L1_P4_Equatorial_Human_Activities: ['Give two problems caused by man in the forest.', 'Deforestation and soil erosion (also loss of wildlife).'],
    FORM2TECH_LESSON1_WEEK7_Problems_Solutions: ['Name the two seasons of Garoua.', 'The wet season and the dry season.'],
    FORM2TECH_LESSON2_WEEK8_Tropical_Grassland_Climate: ['Name two trees of the savanna.', 'The baobab and the shea tree (also the acacia).'],
    S01_L2_P2_Tropical_Grassland_Soils_Vegetation: ['Name three resources of the savanna.', 'Pasture, farmland and wildlife (also water and wood).'],
    S02_L2_P3_Tropical_Grassland_Resources: ['Define transhumance.', 'It is the seasonal movement of herders and their animals.'],
    S03_L2_P4_Tropical_Grassland_Human_Activities: ['Give two problems of the savanna.', 'Drought and bush fires (also overgrazing).'],
    S04_L2_P5_Tropical_Grassland_Problems_Solutions: ['Define a desert.', 'It is a region that receives less than 250 mm of rain per year.'],
    S05_L3_P1_Desert_Location_Types: ['Explain why desert nights are cold.', 'There are no clouds, so the heat escapes.'],
    S06_L3_P2_Desert_Climate: ['Give two ways desert plants save water.', 'Thick stems that store water and small leaves or spines (also long roots).'],
    S07_L3_P3_Desert_Soils_Vegetation: ['Give two problems of people in hot deserts.', 'Lack of water and sandstorms (also extreme temperatures).'],
    S08_L3_P4_Desert_Problems_Adaptations: ['Define an oasis.', 'It is a green, fertile place in a desert where water is found.'],
    S09_L3_P5_Desert_Farming_Oases: ['Name the four seasons of the temperate region.', 'Spring, summer, autumn and winter.'],
    S10_L4_P1_Temperate_Location_Types_Climate: ['Define a deciduous tree.', 'It is a tree that loses its leaves in one season.'],
    S11_L4_P2_Temperate_Soils_Vegetation: ['Define mixed farming.', 'It is growing crops and rearing animals on the same farm.'],
    S12_L4_P3_Temperate_Farming: ['Give two problems of the temperate region.', 'Cold winters with snow and wind erosion of soils.'],
    S13_L4_P4_Temperate_Problems_Adaptations: ['Name the four sectors of the economy.', 'Primary, secondary, tertiary and quaternary.'],
    S14_L5_P1_Sectors_Introduction: ['Name the two sectors of work: registered and not registered.', 'The formal sector and the informal sector.'],
    S15_L5_P2_Formal_Informal_Sectors: ['Give three primary activities.', 'Farming, fishing and mining.'],
    S16_L5_P3_Primary_Sector: ['Name one factory of Garoua and its product.', 'CICAM, which makes cloth.'],
    S17_L5_P4_Secondary_Sector: ['Give three services used every day.', 'Transport, trade and health (also education and mobile money).'],
    S18_L5_P5_Tertiary_Sector: ['Name one research centre in Cameroon.', 'IRAD.'],
    S19_L5_P6_Quaternary_Sector: ['Name the four oceans and seas around Africa.', 'The Atlantic Ocean, the Indian Ocean, the Mediterranean Sea and the Red Sea.'],
    S20_L6_P1_Africa_Location_Physical: ['Name three climates of Africa.', 'Equatorial, tropical (savanna) and desert.'],
    S21_L6_P2_Africa_Climate_Soils_Relief: ['Name three big rivers of Africa.', 'The Nile, the Congo and the Niger (also the Zambezi).'],
    S22_L6_P3_Africa_Vegetation_Drainage: ['Name the three vegetation zones of Africa that we studied.', 'Equatorial forest, savanna and desert vegetation.'],
  },
};
