// v3 patches — LSA Module 2: Geomorphology
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  'Lesson 1': {
    secs: ['1. THE BIG BANG THEORY', '2. THE GEOLOGIC TIME SCALE', '2. A) PRECAMBRIAN', '2. B) PALAEOZOIC', '2. C–D) MESOZOIC AND CENOZOIC'],
    action: 'Understand the long history of the Earth and value fossils and rocks as records of the past.',
    summary: [
      D([['Big Bang:', 'It is the theory that the universe began about 13.8 billion years ago from a very hot, dense point that expanded.'], ['Geologic time scale:', 'It is the division of the history of the Earth into eras, periods and epochs.'], ['Fossil:', 'It is the remains or trace of an ancient plant or animal preserved in rock.']]),
      { title: '1. The Big Bang Theory', intro: 'The theory explains the origin of the Earth as follows:',
        items: [['Origin of the universe:', 'About 13.8 billion years ago, all matter and energy were packed in a tiny hot point that suddenly expanded. As it cooled, atoms, stars and galaxies formed.'],
          ['Origin of the Earth:', 'About 4.6 billion years ago, a cloud of gas and dust around the young sun collapsed into planets. The Earth was first molten and slowly cooled to form a crust, oceans and an atmosphere.']] },
      { title: '2. The Geologic Time Scale', intro: 'The history of the Earth is divided into four eras:',
        items: [['Precambrian (4,600–541 million years ago):', 'It covers almost 90 % of Earth history. The crust, the oceans and the first simple life (bacteria, stromatolites) appeared.'],
          ['Palaeozoic (541–252 million years ago):', 'Life with shells (trilobites), fishes, forests and reptiles appeared. The Caledonian and Hercynian mountains were formed, and it ended with a mass extinction.'],
          ['Mesozoic (252–66 million years ago):', 'It is the age of dinosaurs, when Pangaea broke up and the Atlantic opened. It ended with the extinction of the dinosaurs.'],
          ['Cenozoic (66 million years ago to today):', 'It is the age of mammals and of man. The Alps and Himalayas were formed and the ice ages occurred.']],
        draw: { img: 'geologic_time_big.png', caption: 'the geologic time scale' } },
    ],
    hwAnswer: 'Precambrian: first bacteria and oldest rocks. Palaeozoic: trilobites and first forests. Mesozoic: dinosaurs and break-up of Pangaea. Cenozoic: mammals, man and the Himalayas.',
  },
  'Lesson 2': {
    secs: ['1. LAYERS OF THE EARTH', '1. LAYERS OF THE EARTH', '2. THE ROCK CYCLE', '3. INTERNAL FORCES', '3. EXTERNAL FORCES'],
    action: 'Understand the forces that shape our landscape and the rocks we use.',
    summary: [
      D([['Lithosphere:', 'It is the rigid outer shell of the Earth, made of the crust and the upper mantle.'], ['Rock cycle:', 'It is the continuous change of rocks from one type to another.'], ['Landform:', 'It is a natural shape of the Earth\'s surface, such as a mountain or a valley.']]),
      { title: '1. Layers of the Earth and their Properties', intro: 'The Earth is made up of the following layers:',
        items: [['Crust:', 'It is the thin outer layer, 5–10 km thick under the oceans (sima, basalt) and 30–70 km under continents (sial, granite). It is separated from the mantle by the Moho.'],
          ['Mantle:', 'It is about 2,900 km thick and made of hot, dense rock. Its upper part (asthenosphere) is partly molten and flows slowly, carrying the plates.'],
          ['Core:', 'It is made of iron and nickel. The outer core is liquid and creates the Earth\'s magnetic field, while the inner core is solid.']],
        draw: { img: 'earth_layers_big.png', caption: 'the layers of the Earth' } },
      { title: '2. The Rock Material Cycle', intro: 'Rocks change from one type to another as follows:',
        items: [['Igneous rocks:', 'They form when magma cools, like granite and basalt. Weathering breaks them into sediments.'],
          ['Sedimentary rocks:', 'They form when sediments are deposited, compacted and cemented, like sandstone and limestone. Heat and pressure can change them.'],
          ['Metamorphic rocks:', 'They form when rocks are changed by heat and pressure, like marble and gneiss. If they melt, they become magma again.']],
        draw: { img: 'rock_cycle_big.png', caption: 'the rock cycle' } },
      { title: '3. Forces and Categories of Landforms', intro: 'The landscape is shaped by two groups of forces:',
        items: [['Internal (endogenic) forces:', 'They come from inside the Earth: plate movements, folding, faulting, volcanism and earthquakes. They build up the relief.'],
          ['External (exogenic) forces:', 'They come from the sun and gravity: weathering, mass wasting and erosion by rivers, wind, waves and ice. They wear the relief down.'],
          ['Categories of landforms:', 'Major landforms are continents, ocean basins, mountain ranges and plains. Minor landforms are small features such as valleys, waterfalls and dunes.']] },
    ],
    hwAnswer: 'The coasts of Africa and South America look like pieces of a puzzle because they were once joined in one continent (Gondwana/Pangaea). They later drifted apart as the Atlantic Ocean opened.',
  },
  'Further Study 1': {
    secs: ['1. ISOSTASY', '2. CONTINENTAL DRIFT', '3. EVIDENCE: FOSSILS', '3. EVIDENCE: CLIMATE', '4. STRENGTHS AND WEAKNESSES'],
    action: 'Understand how scientists built theories of the moving Earth from evidence.',
    summary: [
      { title: '1. Isostasy', intro: 'Isostasy can be understood as follows:',
        items: [['Meaning:', 'It is the state of balance of the lighter crust floating on the denser mantle, like wood floating on water. Thick crust sinks deeper, like mountains with deep roots.'],
          ['Isostatic equilibrium:', 'When weight is added (ice sheets) the crust sinks; when it is removed (melting, erosion) the crust rises again. Scandinavia is still rising after the last ice age.']],
        draw: { img: 'isostasy.gif', caption: 'isostasy' } },
      { title: '2. Theory of Continental Drift', intro: 'Wegener\'s theory (1912) states that:',
        items: [['Splitting of landmasses:', 'About 300 million years ago all continents formed one super-continent, Pangaea, surrounded by the ocean Panthalassa. It split into Laurasia in the north and Gondwana in the south.'],
          ['Drifting:', 'The continents slowly drifted to their present positions. The Americas moved west and India moved north towards Asia.']] },
      { title: '3. Evidence, Strengths and Weaknesses', intro: 'The theory is supported and criticised as follows:',
        items: [['Evidence:', 'The coasts of Africa and South America fit, and the same fossils (Mesosaurus, Glossopteris) are found on both. Old glacial striations in India and Africa and similar rocks on both sides of the Atlantic also support it.'],
          ['Strengths:', 'It explained the fit of continents, the spread of fossils and old climates. It prepared the way for plate tectonics.'],
          ['Weaknesses:', 'Wegener could not explain the force that moved the continents. He wrongly thought continents ploughed through the ocean floor.']] },
    ],
    hwAnswer: 'The Mid-Atlantic Ridge is an underwater mountain chain running north–south in the middle of the Atlantic Ocean, from Iceland to the South Atlantic.',
  },
  'Further Study 2': {
    secs: ['1. THE THEORY', '2. MID-OCEANIC ERUPTIONS', '2. MID-OCEANIC ERUPTIONS', '3. EVIDENCE OF SPREADING', '4. EFFECTS ON OCEAN RELIEF'],
    action: 'Understand how the ocean floor is created and how it causes earthquakes and volcanoes.',
    summary: [
      { title: '1. The Theory of Sea-Floor Spreading', intro: 'Harry Hess (1962) explained crustal motion as follows:',
        items: [['Creation of new crust:', 'Magma rises at mid-ocean ridges and forms new oceanic crust. The new crust pushes the older crust away on both sides.'],
          ['Destruction of old crust:', 'The oceanic crust moves like a conveyor belt and sinks back into the mantle at ocean trenches. So the Earth does not grow bigger.']],
        draw: { img: 'seafloor.gif', caption: 'sea-floor spreading' } },
      { title: '2. Mid-Oceanic Volcanic Eruptions', intro: 'Eruptions at the ridges cause spreading:',
        items: [['Gentle eruptions:', 'Runny basalt lava erupts quietly along the ridge and forms pillow lava under water. Iceland is a part of the ridge above sea level.'],
          ['Cause of spreading:', 'Rising magma and convection currents in the mantle pull the plates apart. The Atlantic widens by about 2–5 cm a year.']] },
      { title: '3. Evidence and Effects on Relief', intro: 'Spreading is proved and shapes the ocean floor as follows:',
        items: [['Palaeomagnetic stripes:', 'Rocks record the Earth\'s magnetic field, which reverses from time to time. The stripes are the same on both sides of the ridge, showing symmetrical spreading.'],
          ['Age of rocks and sediments:', 'The youngest rocks are at the ridge and they get older towards the continents. Sediments are thin at the ridge and thick far from it.'],
          ['Effects on relief:', 'Spreading creates mid-ocean ridges, rift valleys, transform faults and volcanic islands. At trenches, deep ocean trenches form.']] },
    ],
    hwAnswer: 'Japan, Indonesia and Chile often have earthquakes and volcanoes. They lie on the Pacific "Ring of Fire" where plates collide.',
  },
  'Lesson 3': {
    secs: ['1. GENESIS: THE PLATES', '4. CAUSES OF PLATE MOTION', '3. PLATE MARGINS', '3. PLATE MARGINS: CONSERVATIVE', '2. MAIN PRINCIPLES'],
    action: 'Understand the distribution of volcanoes and earthquakes to reduce disaster risks.',
    summary: [
      D([['Plate tectonics:', 'It is the theory that the lithosphere is broken into rigid plates that move over the asthenosphere.'], ['Plate margin:', 'It is the boundary where two plates meet.']]),
      { title: '1. Genesis and Main Principles', intro: 'The theory of plate tectonics can be summarised as follows:',
        items: [['Genesis:', 'In the 1960s, continental drift and sea-floor spreading were combined into one theory. It explained where mountains, volcanoes and earthquakes are found.'],
          ['Principles:', 'The lithosphere is divided into about 7 major and many minor plates, such as the African, Eurasian and Pacific plates. They move a few centimetres a year, and most activity happens at their margins.']],
        draw: { img: 'plates_big.png', caption: 'the major plates' } },
      { title: '2. Plate Margins and Processes', intro: 'There are three types of plate margins:',
        items: [['Constructive (divergent) margins:', 'Plates move apart and new crust is formed, as at the Mid-Atlantic Ridge and the East African Rift. Eruptions are gentle and earthquakes shallow.'],
          ['Destructive (convergent) margins:', 'Plates move towards each other and one sinks under the other (subduction), or they collide. Explosive volcanoes, deep earthquakes and fold mountains form.'],
          ['Conservative (transform) margins:', 'Plates slide past each other without creating or destroying crust. Strong earthquakes occur, as on the San Andreas Fault.']],
        draw: { img: 'margins.gif', caption: 'types of plate margins' } },
      { title: '3. Causes of Plate Motions', intro: 'Plates move because of the following forces:',
        items: [['Convection currents:', 'Heat from the core makes the mantle rock rise, spread and sink in slow currents. These currents drag the plates above them.'],
          ['Ridge push and slab pull:', 'New crust at the ridges pushes the plates away. The heavy sinking plate at a trench pulls the rest of the plate behind it.']],
        draw: { img: 'mantle_convection.gif', caption: 'convection currents in the mantle' } },
    ],
    hwAnswer: 'The East African Rift Valley is a long, narrow valley with steep sides (escarpments) and a flat floor. It is formed where the African plate is splitting apart.',
  },
  'Lesson 4': {
    secs: ['1. FAULTING', '2. RIFT VALLEYS', '2. BLOCK MOUNTAINS AND ESCARPMENTS', '3. SHIELD VOLCANOES', '4. ERUPTIONS AND EARTHQUAKES'],
    action: 'Understand landforms at divergent margins such as the East African Rift.',
    summary: [
      D([['Divergent (constructive) margin:', 'It is a boundary where two plates move apart.'], ['Fault:', 'It is a crack in the crust along which rocks have moved.']]),
      { title: '1. Faulting', intro: 'Tension at divergent margins causes faulting:',
        items: [['Normal faults:', 'When the crust is pulled apart, it cracks and blocks slip down along the faults. The exposed side of a fault is a fault scarp.'],
          ['Horst and graben:', 'A block pushed up between two faults is a horst, and a block that sinks is a graben. Many of them together form a basin and range landscape.']],
        draw: { img: 'horst_graben.gif', caption: 'horst and graben' } },
      { title: '2. Landforms at Constructive Margins', intro: 'The main landforms include:',
        items: [['Mid-ocean ridges:', 'They are long underwater mountain chains where plates separate, like the Mid-Atlantic Ridge. They have a central rift valley.'],
          ['Rift valleys:', 'They are long, narrow valleys formed when a block sinks between parallel faults. The East African Rift Valley is over 6,000 km long.'],
          ['Block mountains, plateaux and escarpments:', 'Uplifted blocks form block mountains (Ruwenzori) and plateaux. Their steep fault sides are escarpments.'],
          ['Shield volcanoes:', 'Runny basalt lava spreads far and builds wide volcanoes with gentle slopes. Examples are Mauna Loa and the volcanoes of Iceland.']],
        draw: { img: 'lsa_escarpment.jpg', caption: 'an escarpment' } },
      { title: '3. Eruptions and Earthquakes', intro: 'Activity at constructive margins is characterised by:',
        items: [['Less violent eruptions:', 'Basic, runny lava lets gases escape easily, so eruptions are effusive (Hawaiian or Icelandic types). Lava flows cover large areas.'],
          ['Shallow earthquakes:', 'Earthquakes are frequent but shallow and usually of low magnitude. They occur along faults and transform zones of the ridges.']] },
    ],
    hwAnswer: 'The Himalayas are formed where the Indian plate collides with the Eurasian plate. The Andes are formed where the Nazca plate sinks under the South American plate.',
  },
  'Lesson 5': {
    secs: ['1. FOLDING', '1. FOLDING', '1. FOLD MOUNTAINS', '2. TRENCHES AND BENIOFF ZONES', '3. ISLAND ARCS AND EXPLOSIVE VOLCANOES'],
    action: 'Locate zones of destructive margins and understand their hazards.',
    summary: [
      D([['Convergent (destructive) margin:', 'It is a boundary where two plates move towards each other.'], ['Subduction:', 'It is the sinking of one plate under another into the mantle.'], ['Benioff zone:', 'It is the sloping zone of earthquakes along a subducting plate.']]),
      { title: '1. Fold Mountains and Folding', intro: 'Compression at convergent margins causes folding:',
        items: [['Folding:', 'Layers of sedimentary rock are squeezed into up-folds (anticlines) and down-folds (synclines). Strong pressure creates overfolds and nappes.'],
          ['Formation of fold mountains:', 'Sediments in a sea between two plates are folded and raised when the plates collide. The Himalayas, Alps, Andes and Atlas are young fold mountains.']],
        draw: { img: 'folding_last.png', caption: 'anticlines and synclines' } },
      { title: '2. Trenches, Island Arcs and Volcanoes', intro: 'Subduction produces the following features:',
        items: [['Ocean trenches:', 'Deep trenches form where the oceanic plate sinks, like the Mariana Trench (11,000 m). Earthquakes occur at increasing depth along the Benioff zone.'],
          ['Island arcs:', 'When an oceanic plate sinks under another oceanic plate, a curved chain of volcanic islands forms. Japan and the Aleutians are examples.'],
          ['Explosive volcanoes:', 'Melting of the sinking plate forms thick, acid, gas-rich magma. It erupts violently, as at Mount St Helens and Mount Pinatubo.']],
        draw: { img: 'subduction_big.png', caption: 'subduction at a destructive margin' } },
      { title: '3. Earthquakes, Location and Conservative Margins', intro: 'Other features of these margins are:',
        items: [['Earthquakes:', 'Shallow, intermediate and deep earthquakes occur, often very strong. They are common around the Pacific Ring of Fire.'],
          ['Global location:', 'Destructive margins surround the Pacific Ocean and run from the Alps to the Himalayas. These are the zones of greatest risk.'],
          ['Conservative margins:', 'Two plates by-pass each other along a tear (transform) fault. There are no volcanoes, but strong earthquakes, as in California.']] },
    ],
    hwAnswer: 'Mount Cameroon is about 4,040 m high, the highest mountain in West and Central Africa. Recent eruptions: 1959, 1982, 1999 and 2000.',
  },
  'Lesson 6': {
    secs: ['1. MEANING AND PROCESS', '2. PRODUCTS', '3. LANDFORMS: CONES', '3. LANDFORMS: DEPRESSIONS', '3. LANDFORMS: LAVA PLATEAUX'],
    action: 'Recognise volcanic landforms in Cameroon and understand how they formed.',
    summary: [
      { title: '1. Meaning, Process and Cycle', intro: 'Volcanism can be understood as follows:',
        items: [['Volcanism:', 'It is the process by which magma and gases from inside the Earth reach the surface or the crust.'],
          ['Process:', 'Magma forms in the mantle, rises because it is lighter and collects in a magma chamber. It escapes through a vent when gas pressure is high enough.'],
          ['Life cycle of a volcano:', 'A volcano is active when it erupts often, dormant when it is sleeping, and extinct when it will not erupt again. Mount Cameroon is active, Mount Manengouba is extinct.']],
        draw: { img: 'volcano_big.png', caption: 'structure of a volcano' } },
      { title: '2. Products of Volcanoes', intro: 'Volcanoes produce the following materials:',
        items: [['Lava:', 'It is magma at the surface; basic lava is runny, while acid lava is thick. Pahoehoe and aa are types of lava flows.'],
          ['Pyroclasts:', 'They are solid fragments: ash, lapilli and volcanic bombs. They fall around the volcano and build cones.'],
          ['Gases:', 'Volcanoes release water vapour, carbon dioxide and sulphur gases. These gases can be deadly, as at Lake Nyos.']] },
      { title: '3. Volcanic Landforms', intro: 'The type of landform depends on the lava and the eruption:',
        items: [['Basic lava cones:', 'Runny lava forms wide cones with gentle slopes (shield volcanoes). Mauna Loa is an example.'],
          ['Acid lava cones (cumulo-domes):', 'Thick lava forms steep, dome-shaped cones. The lava does not flow far.'],
          ['Ash and cinder cones:', 'Pyroclasts pile up into small, steep, concave cones. Many exist on Mount Cameroon.'],
          ['Composite (strato) cones:', 'Layers of ash and lava build large, symmetrical cones. Mount Cameroon and Mount Fuji are composite cones.']],
        draw: { img: 'lsa_mayon.jpg', caption: 'a composite cone' } },
      { title: '3. Volcanic Landforms', sub: 'Plateaux and Depressions', intro: 'Other volcanic landforms include:',
        items: [['Lava plateaux:', 'Many flows of runny lava from fissures cover large areas. The Deccan plateau and parts of the Adamawa and Bamenda plateaux are examples.'],
          ['Craters and calderas:', 'A crater is the small hollow at the top of the vent. A caldera is a much larger hollow formed when the top collapses; it may contain a lake like Lake Nyos.']] },
    ],
    hwAnswer: 'Around Buea and Limbe people grow bananas, tea, oil palm, cocoa and food crops. The soils are fertile because they come from weathered volcanic rocks rich in minerals.',
  },
  'Lesson 7': {
    secs: ['1. VOLCANOES AS A RESOURCE', '1. VOLCANOES AS A RESOURCE', '2. VOLCANOES AS A HAZARD', '2. VOLCANOES AS A HAZARD', '3. ADAPTATION AND MITIGATION'],
    action: 'Live safely near volcanoes by using their resources and preparing for eruptions.',
    summary: [
      D([['Volcanic hazard:', 'It is a volcanic event that can cause loss of life and property.'], ['Mitigation:', 'It is the reduction of the effects of a hazard.']]),
      { title: '1. Volcanoes as a Resource', intro: 'Volcanoes are important in the following ways:',
        items: [['Fertile soils:', 'Weathered volcanic rocks give rich soils for farming. Plantations of bananas, tea and rubber cover the slopes of Mount Cameroon.'],
          ['Minerals and building materials:', 'Volcanoes provide sulphur, pumice, basalt and gravel. Basalt is used for roads and buildings.'],
          ['Geothermal energy and tourism:', 'Hot underground water produces electricity in Iceland and Kenya. Volcanoes and crater lakes attract tourists, like the Mount Cameroon Race of Hope.']] },
      { title: '2. Volcanoes as a Hazard', intro: 'Volcanoes can cause the following hazards:',
        items: [['Lava flows and pyroclastic flows:', 'Lava destroys houses, roads and farms, as in 1999 near Bakingili. Pyroclastic flows of hot gas and ash move fast and kill everything.'],
          ['Ash falls and lahars:', 'Ash destroys crops and roofs and harms breathing. Lahars are mudflows of ash and water that bury villages.'],
          ['Toxic gases:', 'Carbon dioxide released from Lake Nyos in 1986 killed about 1,700 people and many animals. Lake Monoun killed 37 people in 1984.']] },
      { title: '3. Adaptation and Mitigation Strategies', intro: 'People reduce volcanic risks through:',
        items: [['Monitoring and warning:', 'Seismographs, tiltmeters and gas sensors detect signs of eruptions. Early warnings allow people to evacuate.'],
          ['Land-use planning and preparedness:', 'Hazard maps show where not to build, and evacuation plans are prepared. Degassing pipes now remove carbon dioxide from Lake Nyos.'],
          ['Protection works:', 'Barriers and channels can divert lava flows. Strong roofs resist ash falls.']] },
    ],
    hwAnswer: 'Earthquakes are felt around Mount Cameroon (Buea, Limbe) and along the Cameroon Volcanic Line. Elders may remember the tremors of 1999 during the eruption.',
  },
  'Lesson 8': {
    secs: ['1. MEANING AND NATURE', '1. MEASUREMENT', '2. DISTRIBUTION AND CAUSES', '4. EFFECTS', '4. EFFECTS: TSUNAMIS'],
    action: 'Reduce the effects of earthquakes through safe buildings and preparedness.',
    summary: [
      { title: '1. Meaning and Nature of Earthquakes', intro: 'An earthquake can be understood as follows:',
        items: [['Earthquake:', 'It is a sudden shaking of the ground caused by the release of energy in the crust.'],
          ['Focus and epicentre:', 'The focus is the point underground where the rocks break. The epicentre is the point on the surface directly above it, where shaking is strongest.'],
          ['Seismic waves and measurement:', 'Primary (P), secondary (S) and surface waves spread from the focus. They are recorded by a seismograph and measured on the Richter or moment magnitude scale.']],
        draw: { img: 'quake.gif', caption: 'focus, epicentre and seismic waves' } },
      { title: '2. Distribution and Causes', intro: 'Earthquakes are distributed and caused as follows:',
        items: [['Global distribution:', 'Most earthquakes occur along plate margins, especially the Pacific Ring of Fire and the Alpine–Himalayan belt. Few occur in the middle of plates.'],
          ['Local distribution:', 'In Cameroon, earthquakes are felt along the Cameroon Volcanic Line, around Mount Cameroon and in Kribi–Lolodorf. They are usually weak.'],
          ['Causes:', 'Plate movements at margins cause most earthquakes. Volcanic eruptions, isostatic recovery, dams and mining can also cause them.']] },
      { title: '3. Earthquakes as a Hazard and Mitigation', intro: 'The effects and mitigation of earthquakes are:',
        items: [['Effects on land and people:', 'Buildings, bridges and roads collapse, killing many people, and fires break out. Landslides and liquefaction occur, and undersea earthquakes cause tsunamis.'],
          ['Measures to mitigate:', 'Build earthquake-resistant houses and avoid building on faults and soft ground. Prepare people with drills, early warnings and emergency services.']] },
    ],
    hwAnswer: 'Elders near Buea may remember tremors during the eruptions of 1982 and 1999. In Garoua, earthquakes are rarely felt because it is far from active margins.',
  },
  'Lesson 9': {
    secs: ['1. MEANING AND CLASSIFICATION OF DENUDATION', '2. SLOPES AND THE SLOPE SYSTEM', '3. PHYSICAL WEATHERING', '3. CHEMICAL WEATHERING', '3. BIOLOGICAL WEATHERING'],
    action: 'Understand how rocks break down to form soils and landforms.',
    summary: [
      { title: '1. Meaning and Classification of Denudation', intro: 'Denudation can be understood as follows:',
        items: [['Denudation:', 'It is the wearing down and lowering of the land surface by external forces.'],
          ['Classification:', 'Denudation includes weathering (breaking rocks in place), mass wasting (movement by gravity), erosion (removal by agents) and transport. Deposition ends the process.']],
        draw: { img: 'denudation.gif', caption: 'processes of denudation' } },
      { title: '2. Slopes', intro: 'Slopes can be studied as follows:',
        items: [['Meaning and types:', 'A slope is an inclined surface of the land. Slopes can be convex, concave, straight (rectilinear) or free faces (cliffs).'],
          ['The slope system:', 'Inputs are rain, sun energy and weathered material from above. Processes are weathering and mass movement, and outputs are material moved downslope and water.']],
        draw: { img: 'slope_system_big.png', caption: 'the slope system' } },
      { title: '3. Weathering and its Types', intro: 'Weathering is the breakdown of rocks in place; it is of three types:',
        items: [['Mechanical (physical) weathering:', 'Rocks break into pieces without chemical change. Processes are exfoliation by heating and cooling, frost shattering and salt crystallisation.'],
          ['Chemical weathering:', 'Rock minerals are changed by water, oxygen and acids. Processes are oxidation (rust), hydrolysis of feldspar, carbonation of limestone and solution.'],
          ['Biological weathering:', 'Plants and animals break rocks. Roots widen cracks, and lichens and termites produce acids and mix the soil.']],
        draw: { img: 'exfoliation.gif', caption: 'exfoliation' } },
    ],
    hwAnswer: 'Rocks in the wet South are more deeply weathered, because heat and water speed up chemical weathering. In the dry North, weathering is mainly physical and shallow.',
  },
  'Lesson 10': {
    secs: ['1. CLIMATE: PELTIER\'S GRAPH', '1. CLIMATE', '2. GEOLOGY', '3. RELIEF AND VEGETATION', '4. HUMAN ACTIVITIES'],
    action: 'Predict where rocks weather deeply and use this in building and farming.',
    summary: [
      D([['Intensity of weathering:', 'It is the speed and depth at which rocks break down.'], ['Regolith:', 'It is the layer of loose weathered material above solid rock.']]),
      { title: '1. Factors of Weathering', sub: 'A) Climate', intro: 'Climate is the main factor of weathering:',
        items: [['Temperature and rainfall:', 'Chemical weathering is strongest where it is hot and wet, as in equatorial regions, where regolith can be 60 m deep. Frost weathering is strongest where temperatures cross 0 °C often.'],
          ['Peltier\'s graph:', 'It shows weathering regions according to mean annual temperature and rainfall. Deserts have weak weathering, and humid tropics strong chemical weathering.']],
        draw: { img: 'peltier_big.png', caption: 'Peltier\'s weathering regions' } },
      { title: '1. Factors of Weathering', sub: 'B) Geology, Relief, Vegetation and Man', intro: 'Other factors of weathering are:',
        items: [['Geology (rock characteristics):', 'Rock type, minerals, joints and permeability control weathering. Limestone dissolves quickly, while quartz resists.'],
          ['Relief:', 'On steep slopes, weathered material is removed quickly, exposing fresh rock. On gentle slopes, thick regolith builds up.'],
          ['Vegetation:', 'Roots and organic acids increase biological and chemical weathering. Plant cover also keeps the soil moist.'],
          ['Human activities:', 'Mining, quarrying and road building expose rocks. Acid rain from industries speeds up the weathering of buildings.']] },
    ],
    hwAnswer: 'Useful materials from weathered rock: sand for building, clay for bricks and pottery, laterite for roads, and bauxite for aluminium.',
  },
  'Lesson 11': {
    secs: ['1. PRODUCTS AS RESOURCES: SOIL', '1. PRODUCTS AS RESOURCES: MINERALS', '1. PRODUCTS AS RESOURCES: BUILDING MATERIALS', '2. EFFECTS ON THE LANDSCAPE', '3. EFFECTS ON MAN'],
    action: 'Use the products of weathering sustainably and protect buildings from weathering.',
    summary: [
      D([['Weathering products:', 'They are the materials produced by the breakdown of rocks, such as regolith, rock fragments and soil.']]),
      { title: '1. Products of Weathering as Resources', intro: 'Weathering products have the following economic importance:',
        items: [['Soil:', 'Weathering produces the mineral part of soil, which supports farming and forests. Deep tropical soils support cocoa, coffee and food crops.'],
          ['Minerals:', 'Deep chemical weathering concentrates bauxite (Minim-Martap, Fongo-Tongo) and iron ore. These are important resources for industry.'],
          ['Building materials:', 'Sand, gravel, clay and laterite are used for roads, bricks and houses. Kaolin is used for pottery and paper.']] },
      { title: '2. Effects of Weathering on the Landscape', intro: 'Weathering shapes the landscape as follows:',
        items: [['Landforms:', 'It forms inselbergs, tors, scree slopes and karst features. In the North, granite domes stand above plains.'],
          ['Slope instability:', 'Deep regolith on steep slopes becomes unstable when wet. This causes landslides, as in the Western Highlands.']] },
      { title: '3. Effects of Weathering on Man', intro: 'Weathering affects man in the following ways:',
        items: [['Positive effects:', 'It provides soils, minerals and building materials. It also creates tourist landscapes such as the Rhumsiki peaks.'],
          ['Negative effects:', 'It damages buildings, monuments and roads, and loosens slopes. Laterite crusts (hardpans) make farming difficult.']] },
    ],
    hwAnswer: 'Signs of soil creep: leaning posts and trees, cracked walls, small soil steps (terracettes) and soil piled behind walls on the slope.',
  },
  'Lesson 12': {
    secs: ['1. MEANING', '1. EVIDENCE', '2. FACTORS', '2. FACTORS', '3. CLASSIFICATION'],
    action: 'Prevent mass movements by protecting slopes and avoiding risky building.',
    summary: [
      { title: '1. Meaning and Evidence of Mass Wasting', intro: 'Mass wasting can be understood as follows:',
        items: [['Mass wasting (movement):', 'It is the downslope movement of soil and rock under the influence of gravity, without an agent such as a river.'],
          ['Evidence:', 'Leaning trees, posts and walls, cracks in roads and soil steps show slow movement. Scars on hillsides and piles of debris show fast movement.']],
        draw: { img: 'creep.gif', caption: 'evidence of soil creep' } },
      { title: '2. Factors of Mass Wasting', intro: 'Mass wasting depends on the following factors:',
        items: [['Slope angle:', 'Steep slopes increase the pull of gravity on material. Most landslides occur on slopes steeper than 30°.'],
          ['Water:', 'Heavy rain adds weight and reduces friction between particles. This is why landslides happen in the rainy season, as at Bafoussam in 2019.'],
          ['Rock, soil and vegetation:', 'Weak, deeply weathered or clay-rich materials move easily. Vegetation roots hold the soil, while deforestation weakens slopes.'],
          ['Human activities and earthquakes:', 'Road cuts, quarrying, farming on slopes and building increase the risk. Earthquakes can trigger sudden slides.']] },
      { title: '3. Classification', intro: 'Carson and Kirkby classify mass movements on a triangular graph:',
        items: [['Basis:', 'Movements are classed by speed (slow or fast) and by water content (dry or wet). The three corners are slides, flows and heaves.'],
          ['Types:', 'Slow movements are creep and solifluction; fast movements are falls, slides, slumps and flows. Wet, fast movements are mudflows.']],
        draw: { img: 'carson_kirkby_big.png', caption: 'Carson and Kirkby\'s classification' } },
    ],
    hwAnswer: 'Example: Bafoussam (Gouache), 28–29 October 2019: after heavy rain a hillside collapsed onto houses; about 40 people died and many homes were destroyed.',
  },
  'Lesson 13': {
    secs: ['1. SLOW MOVEMENTS: CREEP', '1. SLOW MOVEMENTS: SOLIFLUCTION', '2. FAST MOVEMENTS: SLUMPS', '2. FAST MOVEMENTS: FLOWS', '3. IMPACTS AND SOLUTIONS'],
    action: 'Protect people and property from landslides and other mass movements.',
    summary: [
      D([['Slow mass movement:', 'It is a movement so slow that it can be seen only by its effects over time.'], ['Fast mass movement:', 'It is a sudden movement that can be seen as it happens.']]),
      { title: '1. Slow Mass Movements', intro: 'The main slow movements are:',
        items: [['Soil creep:', 'It is the very slow movement of soil downslope by wetting and drying or heating and cooling. It tilts posts and forms terracettes.'],
          ['Solifluction:', 'It is the slow flow of waterlogged soil over frozen ground in cold regions. It forms lobes on slopes.']] },
      { title: '2. Fast Mass Movements', intro: 'The main fast movements are:',
        items: [['Rockfalls:', 'Blocks of rock fall freely from cliffs and form scree at the base. They are common on steep, jointed rocks.'],
          ['Slides and slumps:', 'Material slides on a flat plane (landslide) or rotates on a curved surface (slump). They occur after heavy rain on weak slopes.'],
          ['Flows:', 'Mudflows and debris flows move like liquids, very fast. Lahars are volcanic mudflows.']],
        draw: { img: 'lsa_slump.jpg', caption: 'a slump' } },
      { title: '3. Impacts and Solutions', intro: 'Mass wasting affects man and the environment:',
        items: [['Impacts:', 'Mass movements kill people and destroy houses, roads and farms. They block rivers and bury fertile land.'],
          ['Solutions:', 'Plant trees and grass, build terraces and retaining walls, and improve drainage. Avoid building on steep, unstable slopes and use hazard maps and warnings.']] },
    ],
    hwAnswer: 'After rain, the river carries mud (suspended load), sand and pebbles rolling on the bed (bed load), and dissolved minerals (solution); also leaves and rubbish.',
  },
  'Lesson 14': {
    secs: ['1. EROSIONAL PROCESSES', '2. PROCESSES OF TRANSPORTATION', '2. THE HJULSTRÖM GRAPH', '3. DEPOSITION', '4. THE RIVER AS A SYSTEM'],
    action: 'Understand river processes to manage rivers and prevent erosion and floods.',
    summary: [
      D([['Erosion:', 'It is the wearing away and removal of rock and soil by agents such as rivers, wind, waves and ice.'], ['Competence:', 'It is the size of the largest particle a river can carry.'], ['Capacity:', 'It is the total amount of load a river can carry.']]),
      { title: '1. Erosional Processes', intro: 'Rivers erode by the following processes:',
        items: [['Hydraulic action:', 'The force of water pushes into cracks and breaks rocks. It is strongest at waterfalls and in floods.'],
          ['Abrasion (corrasion):', 'Stones carried by the river scrape the bed and banks. It deepens and widens the channel.'],
          ['Attrition and solution:', 'In attrition, stones hit each other and become smaller and rounder. In solution, water dissolves rocks such as limestone.']],
        draw: { img: 'river_erosion_big.png', caption: 'processes of river erosion' } },
      { title: '2. Transportation', intro: 'The load of a river is transported as follows:',
        items: [['Sources and types of load:', 'Load comes from weathering, mass movement and bank erosion. It is carried as bed load, suspended load and dissolved load.'],
          ['Processes:', 'Large stones roll (traction), smaller ones bounce (saltation), fine clay floats (suspension) and minerals are dissolved (solution). Speed decides which process works.'],
          ['The Hjulström graph:', 'It shows the velocity needed to erode, transport and deposit particles of each size. Clay is hard to erode because it sticks together, but once moving it stays in suspension.']],
        draw: { img: 'hjulstrom_big.png', caption: 'the Hjulström graph' } },
      { title: '3. Deposition and the River as a System', intro: 'Deposition and the fluvial system can be summarised as follows:',
        items: [['Deposition:', 'A river deposits its load when its velocity falls, for example on the inside of bends, in lakes and at its mouth. Heavy materials are dropped first.'],
          ['The river as a system:', 'Inputs are precipitation, load and energy; processes in the channel are erosion, transport and deposition. Outputs are water, sediment and energy to the sea.'],
          ['Functions of rivers:', 'Rivers shape valleys, floodplains and deltas. They also support ecosystems, recharge groundwater and supply fertile silt.']] },
    ],
    hwAnswer: 'The long profile is concave: steep in the upper course near the source, gentler in the middle course, and almost flat in the lower course near the mouth.',
  },
  'Lesson 15': {
    secs: ['1. THE LONG PROFILE', '1. UPPER COURSE', '2. MIDDLE COURSE', '3. LOWER COURSE', '3. LOWER COURSE'],
    action: 'Recognise river landforms and use river valleys wisely.',
    summary: [
      D([['Long profile:', 'It is the change in the height of a river from its source to its mouth.'], ['Base level:', 'It is the lowest level to which a river can erode, usually sea level.']]),
      { title: '1. Upper Course', intro: 'The upper course has the following characteristics and features:',
        items: [['Characteristics:', 'The gradient is steep and the channel is narrow and shallow, with large boulders. Vertical erosion is dominant.'],
          ['Features:', 'V-shaped valleys, interlocking spurs, waterfalls and rapids form here. Waterfalls form where hard rock lies over soft rock, as at Ekom Nkam.']],
        draw: { img: 'long_profile_big.png', caption: 'the long profile' } },
      { title: '2. Middle Course', intro: 'The middle course has the following characteristics and features:',
        items: [['Characteristics:', 'The gradient is gentler, the valley wider and the discharge greater. Lateral erosion becomes important.'],
          ['Features:', 'Meanders form, with river cliffs on the outside of bends and slip-off slopes (point bars) on the inside. The valley floor becomes a narrow floodplain.']],
        draw: { img: 'meander.gif', caption: 'a meander' } },
      { title: '3. Lower Course', intro: 'The lower course has the following characteristics and features:',
        items: [['Characteristics:', 'The gradient is very gentle, the channel wide and deep, and the load fine. Deposition is dominant.'],
          ['Features:', 'Wide floodplains, levées, ox-bow lakes and braided channels form. Ox-bow lakes form when a meander neck is cut through during a flood.'],
          ['Mouth:', 'Deltas form where rivers deposit more than the sea removes, like the Niger delta. Estuaries form where the sea floods the mouth, like the Wouri estuary.']],
        draw: { img: 'oxbow.gif', caption: 'formation of an ox-bow lake' } },
    ],
    hwAnswer: 'At Kribi the coast has sandy beaches, rocks and the Lobé falls reaching the sea. At Limbe there are dark volcanic beaches, rocky headlands and small bays.',
  },
  'Lesson 16': {
    secs: ['1. WAVES AND ENERGY', '1. REFRACTION', '2. EROSION FEATURES', '3. DEPOSITION FEATURES', '4. THREATS TO COASTS'],
    action: 'Protect our coasts from erosion, pollution and rising sea level.',
    summary: [
      D([['Coast:', 'It is the zone where the land meets the sea.'], ['Wave refraction:', 'It is the bending of waves as they approach an irregular coastline.'], ['Longshore drift:', 'It is the movement of material along the coast by waves.']]),
      { title: '1. The Coastal System and Processes', intro: 'The coastal system and its processes are:',
        items: [['Coastal system and factors:', 'Inputs are wave, wind and tidal energy and sediment; outputs are landforms and sediment. Rock type, waves, tides, currents and sea-level change influence coasts.'],
          ['Waves and energy:', 'Waves are made by wind blowing over the sea; their energy depends on wind speed, duration and fetch. Constructive waves build beaches, while destructive waves erode them.'],
          ['Refraction and other processes:', 'Refraction concentrates energy on headlands and spreads it in bays. Tides, storm surges and tsunamis also shape coasts.']],
        draw: { img: 'refraction_big.png', caption: 'wave refraction' } },
      { title: '2. Wave Erosion, Transport and Features', intro: 'Waves erode and transport as follows:',
        items: [['Erosion:', 'Waves erode by hydraulic action, abrasion, attrition and solution. They cut notches, cliffs and wave-cut platforms.'],
          ['Erosional features:', 'Headlands and bays form on alternating hard and soft rocks. A crack in a headland becomes a cave, an arch, a stack and finally a stump.'],
          ['Transport:', 'Swash carries material up the beach at an angle and backwash pulls it straight down. This moves material along the coast by longshore drift.']],
        draw: { img: 'headland.gif', caption: 'cave, arch, stack and stump' } },
      { title: '3. Deposition and Threats', intro: 'Deposition features and threats to coasts are:',
        items: [['Depositional features:', 'Beaches, spits, bars and tombolos form where waves lose energy. A spit grows across a bay by longshore drift.'],
          ['Threats or problems:', 'Coastal erosion, sand mining, pollution, mangrove cutting and sea-level rise threaten coasts. In Cameroon, Limbe and Kribi suffer erosion and pollution.']] },
    ],
    hwAnswer: 'Mount Cameroon is on the south-west coast near Buea; the Adamawa Plateau is in the centre (around Ngaoundéré); the Chad Plain is in the far north near Lake Chad.',
  },
  'Further Study 3': {
    secs: ['1. PHYSIOGRAPHIC REGIONS', '2. MAJOR HIGHLANDS', '2. MAJOR HIGHLANDS', '2. MAJOR HIGHLANDS', '2. MAJOR LOWLANDS'],
    action: 'Know the relief of Cameroon to understand its climate, rivers and human activities.',
    summary: [
      { title: '1. Physiography of Cameroon', intro: 'Cameroon has the following physiographic regions:',
        items: [['Physiographic regions:', 'Cameroon is divided into highlands in the west and centre and lowlands on the coast, in the south and in the north. Relief rises from the coast to the Adamawa and the Western Highlands.'],
          ['Cameroon Volcanic Line:', 'A line of volcanoes runs from the Gulf of Guinea (Bioko) through Mount Cameroon to the Mandara Mountains. It gives Cameroon its highest relief.']],
        draw: { img: 'cameroon_relief_big.png', caption: 'relief regions of Cameroon' } },
      { title: '2. Major Highlands', intro: 'The major highlands and their characteristics are:',
        items: [['Mount Cameroon:', 'It is an active volcano, 4,040 m high, the highest point of Cameroon. Its slopes have fertile volcanic soils and plantations.'],
          ['Western Highlands:', 'They include Manengouba, Bamboutos and the Bamenda plateau (1,000–3,000 m). They have volcanic soils, a cool climate and dense population.'],
          ['Adamawa Plateau:', 'It lies at about 1,000–1,500 m in the centre of the country. It is the "water tower" of Cameroon and a region of cattle rearing.'],
          ['Mandara Mountains:', 'They lie in the Far North along the border with Nigeria, with volcanic peaks such as Rhumsiki. Terraced farming is practised there.']] },
      { title: '3. Major Lowlands', intro: 'The major lowlands and their characteristics are:',
        items: [['Coastal lowlands:', 'They stretch from Rio del Rey to Campo, with the Douala basin, mangroves and estuaries. They are hot, wet and densely populated around Douala.'],
          ['South Cameroon Plateau:', 'It is a low plateau (500–800 m) covered by forest, with inselbergs. Yaoundé lies on it.'],
          ['Northern lowlands:', 'They include the Benue depression around Garoua and the Chad plain in the Far North. They are flat, with seasonal flooding (yaérés) near Lake Chad.']] },
    ],
    hwAnswer: 'The sketch map shows the coastal lowlands, Mount Cameroon, the Western Highlands, the South Cameroon Plateau, the Adamawa Plateau, the Benue depression, the Mandara Mountains and the Chad plain, with a key, title and north arrow.',
  },
};
