// v3 patches — LSA Module 3: Biogeography, part A (soils: Lessons 1–11, PW1, FS1)
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  'Lesson 1': {
    secs: ['1. MEANING', '2. SOIL COMPONENTS', '2. SOIL COMPONENTS', '3. IMPORTANCE OF SOIL', '4. THE SOIL SYSTEM'],
    action: 'Protect and conserve the soils that feed us.',
    summary: [
      { title: '1. Meaning of Soil', intro: 'Soil can be understood as follows:',
        items: [['Soil:', 'It is the thin, loose layer of weathered rock, organic matter, water and air that covers the land surface and supports plant growth.']] },
      { title: '2. Soil Components and Variations with Depth', intro: 'Soil is made up of four main components:',
        items: [['Mineral matter (about 45 %):', 'It comes from the weathering of the parent rock, as sand, silt and clay. It gives the soil its body and many nutrients.'],
          ['Organic matter (about 5 %):', 'It comes from dead plants and animals that decompose into humus. It makes the soil dark, fertile and able to hold water.'],
          ['Water and air (about 25 % each):', 'They fill the pores between particles. Water carries dissolved nutrients to roots, and air supplies oxygen to roots and organisms.'],
          ['Variations with depth:', 'Organic matter, air and organisms decrease with depth, while stones and weathered rock increase. This creates layers called horizons.']],
        draw: { img: 'soil_components_big.png', caption: 'the components of soil' } },
      { title: '3. Importance of Soil to Man and the Biosphere', intro: 'Soil is important in the following ways:',
        items: [['For man:', 'Soil supports farming, which provides food, cash crops and raw materials. It also supplies building materials such as clay and laterite.'],
          ['For the biosphere:', 'Soil anchors plants and supplies them with water and nutrients. It is the home of many organisms and recycles dead matter.']] },
      { title: '4. The Soil System', intro: 'The soil can be studied as an open system:',
        items: [['Inputs:', 'Inputs are weathered rock, organic matter, rain water, air and solar energy. Man adds fertilisers and manure.'],
          ['Processes and state:', 'Processes include weathering, decomposition, leaching and translocation. The state of the soil is its properties at a given time: texture, structure, pH, fertility.'],
          ['Outputs:', 'Outputs are nutrients taken by plants, water lost by evaporation and drainage, and soil lost by erosion. Crops removed by man are also an output.']],
        draw: { img: 'soil_system_big.png', caption: 'the soil system' } },
    ],
    hwAnswer: 'A handful of soil contains mineral particles (sand, clay, small stones), dead leaves and roots (organic matter), small animals (ants, worms), and it may feel damp (water).',
  },
  'Lesson 2': {
    secs: ['1. MEANING: PARTICLE SIZES', '2. TEXTURAL CLASSES', '3. DETERMINATION', '5. FACTORS', '6. SIGNIFICANCE'],
    action: 'Know the texture of our soils to choose the right crops and farming methods.',
    summary: [
      { title: '1. Meaning of Soil Texture', intro: 'Soil texture can be understood as follows:',
        items: [['Soil texture:', 'It is the relative proportion of sand, silt and clay particles in a soil.'],
          ['Particle sizes:', 'Sand particles measure 2–0.05 mm, silt 0.05–0.002 mm and clay less than 0.002 mm. Gravel and stones are larger than 2 mm.']],
        draw: { img: 'particle_sizes_big.png', caption: 'particle sizes' } },
      { title: '2. Textural Classes and Representation', intro: 'Soils are grouped into textural classes:',
        items: [['Main classes:', 'Sandy soils are light and drain fast; clay soils are heavy, sticky and hold water. Loam, a balanced mixture, is the best for farming.'],
          ['Representation:', 'Textural classes are shown on a triangular (ternary) graph with sand, silt and clay percentages. A soil with 40 % sand, 40 % silt and 20 % clay is a loam.']],
        draw: { img: 'texture_triangle_big.png', caption: 'the soil texture triangle' } },
      { title: '3. Determination of Soil Texture', intro: 'Texture can be determined by two methods:',
        items: [['Field methods:', 'A moist sample is rubbed and moulded: sand feels gritty, silt feels smooth and clay feels sticky. Clay makes a long ribbon and a ring, while sand crumbles.'],
          ['Laboratory methods:', 'Dry soil is sieved through meshes of different sizes and each fraction is weighed. The sedimentation method measures fine particles settling in water.']],
        draw: { img: 'ribbon_test_big.png', caption: 'the ribbon test' } },
      { title: '4. Factors and Significance', intro: 'The factors and significance of texture are:',
        items: [['Factors:', 'Parent rock is the main factor: granite gives sandy soils and basalt clayey soils. Weathering, age and deposition by rivers and wind also matter.'],
          ['Significance:', 'Texture controls drainage, aeration, water-holding capacity and ease of ploughing. Rice grows on clay, while groundnuts prefer sandy soils.']] },
    ],
    hwAnswer: 'Example: soil from the garden feels smooth and slightly sticky (loam); soil from the road feels gritty (sandy); soil from the river bank is sticky and forms a ribbon (clay).',
  },
  'Practical Work 1': {
    secs: ['1. SAMPLING', '2. FIELD METHODS', '3. LABORATORY METHOD', '3. LABORATORY METHOD', '4. PLOTTING ON A TERNARY GRAPH'],
    action: 'Determine the texture of school soils to choose the best site for the school garden.',
    summary: [
      D([['Soil sample:', 'It is a small quantity of soil taken to represent the soil of a place.'], ['Ternary graph:', 'It is a triangular graph used to plot three percentages that add up to 100.']]),
      { title: '1. Field Methods', intro: 'In the school locality, texture is determined by feel:',
        items: [['Sampling:', 'Take samples from several places at the same depth, label them and note the site. Several samples give a reliable result.'],
          ['Feeling method:', 'Rub moist soil between the fingers: gritty means sand, smooth means silt and sticky means clay. Record the texture of each sample.'],
          ['Moulding and ringing methods:', 'Roll the moist soil into a ribbon and a ring. Clay makes a long ribbon and a complete ring; sand breaks at once.']] },
      { title: '2. Laboratory Method', intro: 'In the laboratory, texture is measured by sieving:',
        items: [['Preparation:', 'Dry and crush each sample and weigh it (for example 100 g). This separates the particles.'],
          ['Sieving:', 'Pass the soil through a set of sieves (2 mm, 0.05 mm) and weigh the soil left on each. Calculate the percentage of sand, silt and clay.']],
        draw: { img: 'pw_texture_big.png', caption: 'results of three samples' } },
      { title: '3. Plotting and Interpretation', intro: 'The results are plotted and interpreted as follows:',
        items: [['Plotting:', 'Read the sand, silt and clay percentages along the three sides of the triangle. The point where the three lines meet gives the textural class.'],
          ['Interpretation:', 'A loam is best for the school garden because it drains well and holds water. Sandy soils need organic matter and clay soils need drainage.']],
        draw: { img: 'texture_triangle_big.png', caption: 'plotting samples on the texture triangle' } },
    ],
    hwAnswer: 'Sample A (sandy) drains too fast; sample B (loam) is well balanced; sample C (clay, 55 %) holds too much water. The best place for the garden is where sample B was taken.',
  },
  'Lesson 3': {
    secs: ['1. MEANING AND TYPES', '2. FACTORS: ORGANISMS', '2. FACTORS: CLAY AND WEATHER', '2. FACTORS: MAN', '3. SIGNIFICANCE'],
    action: 'Maintain a good soil structure through good farming practices.',
    summary: [
      { title: '1. Meaning and Types of Soil Structure', intro: 'Soil structure can be understood as follows:',
        items: [['Soil structure:', 'It is the way soil particles are grouped together into aggregates (peds).'],
          ['Crumb and granular structure:', 'Small, rounded, porous aggregates are found in topsoils rich in humus. It is the best structure for crops.'],
          ['Blocky, platy and prismatic structure:', 'Blocky peds are found in subsoils, platy peds in compacted layers and prismatic columns in dry clay soils. Single-grain sand has no structure.']],
        draw: { img: 'soil_structure_big.png', caption: 'types of soil structure' } },
      { title: '2. Factors Affecting Soil Structure', intro: 'Soil structure depends on the following factors:',
        items: [['Organic matter and organisms:', 'Humus and earthworm casts glue particles into crumbs. Roots and fungi also bind aggregates.'],
          ['Clay and climate:', 'Clay swells when wet and shrinks when dry, forming cracks and blocks. Wetting, drying and freezing break up large clods.'],
          ['Human activities:', 'Heavy machines and trampling by cattle compact the soil. Burning and continuous cropping destroy organic matter and crumbs.']] },
      { title: '3. Significance of Soil Structure', intro: 'Soil structure is important because:',
        items: [['Water and air:', 'A good structure has many pores that allow infiltration, drainage and aeration. Roots can breathe and grow deep.'],
          ['Erosion and farming:', 'Stable crumbs resist erosion by rain. Well-structured soils are easy to plough and give good yields.']] },
    ],
    hwAnswer: 'Soil from a path is hard, compact and platy because it is trampled. Soil from a garden is loose and crumbly because it contains humus and is dug.',
  },
  'Lesson 4': {
    secs: ['1. SOIL DEPTH: MEANING', '1. SOIL DEPTH: FACTORS', '3. SOIL ORGANIC MATTER (HUMUS)', '2. SOIL ORGANISMS', '2. SOIL ORGANISMS'],
    action: 'Increase soil organic matter through composting and protect soil organisms.',
    summary: [
      { title: '1. Soil Depth (Thickness)', intro: 'Soil depth can be understood as follows:',
        items: [['Meaning:', 'Soil depth is the thickness of the soil from the surface down to the parent rock. It decides how deep roots can grow and how much water the soil can store.'],
          ['Factors:', 'Climate, time and parent rock control depth: hot, wet regions have deep soils, sometimes over 10 m. Steep slopes, erosion and young volcanic rocks give thin soils.']],
        draw: { img: 'soil_profile_big.png', caption: 'soil depth' } },
      { title: '2. Inorganic Matter and Soil Organisms', intro: 'Other important parts of the soil are:',
        items: [['Inorganic matter:', 'It is made of minerals such as quartz, feldspar and clay minerals from weathered rock. It supplies nutrients such as potassium, calcium and iron.'],
          ['Macro-organisms:', 'Earthworms, termites and ants dig channels, mix the soil and bring organic matter down. Termite mounds are common in the savanna.'],
          ['Micro-organisms:', 'Bacteria and fungi decompose dead matter and release nutrients. Some bacteria fix nitrogen from the air.']] },
      { title: '3. Soil Organic Matter (Humus)', intro: 'Soil organic matter can be understood as follows:',
        items: [['Meaning and formation:', 'Humus is the dark, decomposed organic matter of the soil. It forms when decomposers break down litter such as leaves, dung and dead animals.'],
          ['Importance:', 'Humus makes the soil fertile, dark and crumbly and increases its water-holding capacity. It stores nutrients and feeds soil organisms.']] },
    ],
    hwAnswer: 'After two weeks the compost heap becomes warm, smaller and darker; the leaves begin to rot because bacteria, fungi and worms decompose them into humus.',
  },
  'Lesson 5': {
    secs: ['1. SOIL COLOUR', '1. SOIL COLOUR', '3. SOIL pH', '3. SOIL pH', '2. SOIL NUTRIENTS'],
    action: 'Test and correct soil chemistry to improve crop yields.',
    summary: [
      { title: '1. Soil Colour', intro: 'Soil colour can be studied as follows:',
        items: [['Meaning and factors:', 'Soil colour is the shade of the soil, which depends on humus, iron compounds and drainage. Red soils contain oxidised iron, while dark soils are rich in humus.'],
          ['Significance:', 'Grey or mottled colours show poor drainage (waterlogging). Colour helps to identify horizons and soil fertility.']] },
      { title: '2. Soil Nutrients', intro: 'Soil nutrients can be studied as follows:',
        items: [['Meaning:', 'Nutrients are the chemical elements that plants need to grow. Macronutrients are nitrogen (N), phosphorus (P) and potassium (K), plus calcium and magnesium.'],
          ['Factors:', 'Nutrients come from weathered rock, humus and fertilisers. They are lost by leaching, erosion and crop removal.'],
          ['Significance:', 'N helps leaf growth, P helps roots and flowers, and K helps fruits and resistance to disease. Lack of nutrients reduces yields.']] },
      { title: '3. Soil pH', intro: 'Soil pH can be studied as follows:',
        items: [['Meaning:', 'pH measures how acid or alkaline a soil is, on a scale from 0 to 14. A pH of 7 is neutral, below 7 is acid and above 7 is alkaline.'],
          ['Factors:', 'Heavy rain and leaching make soils acid, as in the equatorial forest. Dry climates and limestone make soils alkaline.'],
          ['Significance:', 'Most crops grow best between pH 6 and 7. Farmers add lime to acid soils; pH is measured with a pH meter or indicator paper.']],
        draw: { img: 'ph_scale_big.png', caption: 'the pH scale' } },
    ],
    hwAnswer: 'N (nitrogen) makes leaves grow green; P (phosphorus) helps roots and flowers; K (potassium) helps fruits, seeds and resistance to disease. Example: NPK 20-10-10.',
  },
  'Lesson 6': {
    secs: ['1. MEANING', '2. NATURAL FACTORS', '2. HUMAN FACTORS', '3. MAINTAINING FERTILITY', '3. MAINTAINING FERTILITY'],
    action: 'Keep our soils fertile through sustainable farming practices.',
    summary: [
      { title: '1. Meaning of Soil Fertility', intro: 'Soil fertility can be understood as follows:',
        items: [['Soil fertility:', 'It is the ability of a soil to supply water, air and nutrients to plants in the right amounts to support good yields.'],
          ['Signs of a fertile soil:', 'A fertile soil is deep, rich in humus and nutrients, well drained and well structured. Its pH is close to neutral.']] },
      { title: '2. Factors of Soil Fertility', intro: 'Fertility depends on natural and human factors:',
        items: [['Natural factors:', 'Parent rock, climate, vegetation, relief and organisms determine fertility. Volcanic soils are fertile, while leached rainforest soils are poor.'],
          ['Human factors that reduce fertility:', 'Bush fires, continuous cropping, overgrazing and deforestation remove nutrients and cause erosion. Soils become poor and hard.'],
          ['Human factors that improve fertility:', 'Manure, compost, fertilisers, crop rotation, fallowing and legumes add nutrients. Terraces, zaï pits and mulching reduce losses.']] },
    ],
    hwAnswer: 'Example: the farmer uses cow dung and compost, rotates maize with groundnuts, leaves some land fallow and avoids burning crop residues.',
  },
  'Lesson 7': {
    secs: ['1. STAGES', '2. FACTORS (CLORPT)', '2. A) ACTIVE FACTORS: CLIMATE', '2. B) PASSIVE FACTORS: RELIEF', '2. B) PASSIVE FACTORS: TIME'],
    action: 'Understand how soils form in order to protect them, because they form very slowly.',
    summary: [
      D([['Pedogenesis:', 'It is the process of soil formation.'], ['Parent material:', 'It is the rock or deposit from which a soil is formed.']]),
      { title: '1. Stages of Soil Formation', intro: 'Soil forms in the following stages:',
        items: [['Weathering of the parent rock:', 'The rock breaks down into regolith by physical, chemical and biological weathering. This gives the mineral part of the soil.'],
          ['Colonisation and humus formation:', 'Lichens, mosses and then plants grow on the regolith. Their remains decompose into humus.'],
          ['Horizon development:', 'Water moves materials down and up the profile, forming horizons. A mature soil develops after thousands of years.']],
        draw: { img: 'soil_formation.gif', caption: 'stages of soil formation' } },
      { title: '2. Factors of Soil Formation', intro: 'Jenny\'s equation S = f (CL, O, R, P, T) groups the factors:',
        items: [['Active factor – Climate:', 'Temperature and rainfall control weathering, leaching and decomposition. Hot, wet climates form deep, red, leached soils; dry climates form thin soils.'],
          ['Active factor – Organisms:', 'Plants supply organic matter and animals mix the soil. Man changes soils by farming, burning and fertilising.'],
          ['Passive factor – Parent material:', 'It determines texture, colour and minerals. Basalt gives fertile clay soils, while granite gives sandy soils.'],
          ['Passive factors – Relief and time:', 'Soils are thin on steep slopes and deep and wet in valleys. Older soils are deeper and have clearer horizons.']],
        draw: { img: 'clorpt_big.png', caption: 'factors of soil formation' } },
    ],
    hwAnswer: 'Soils of Mount Cameroon are young volcanic soils, rich in minerals, formed in a very wet climate. Soils of the Far North formed in a dry climate on old rocks and sediments, so they are thinner, sandier and poorer in humus.',
  },
  'Lesson 8': {
    secs: ['1. MEANING', '2. THE IDEAL SOIL PROFILE', '2. HORIZONS', '3. REASONS FOR HORIZONS', '3. REASONS FOR HORIZONS'],
    action: 'Read soil profiles to judge the quality of soils for farming and building.',
    summary: [
      { title: '1. Meaning of the Soil Profile', intro: 'The soil profile can be understood as follows:',
        items: [['Soil profile:', 'It is a vertical section of the soil from the surface down to the parent rock, showing its layers.'],
          ['Horizon:', 'It is a layer of the soil with its own colour, texture and structure. Horizons are named with letters.']] },
      { title: '2. The Ideal Soil Profile', intro: 'An ideal soil profile has the following horizons:',
        items: [['O horizon:', 'It is the surface layer of litter and humus. It is dark and rich in organic matter.'],
          ['A horizon (topsoil):', 'It is dark, fertile and full of roots and organisms. Materials are washed out of it (eluviation).'],
          ['E and B horizons:', 'The E horizon is pale because clay and iron are washed out. The B horizon (subsoil) collects clay, iron and humus (illuviation).'],
          ['C and R horizons:', 'C is the weathered parent material and R is the solid bedrock. They supply the minerals of the soil.']],
        draw: { img: 'ideal_profile_big.png', caption: 'the ideal soil profile' } },
      { title: '3. Reasons for Horizons', intro: 'Soil profiles have horizons for the following reasons:',
        items: [['Movement of water:', 'Water moving down carries clay, iron and nutrients from the top to lower layers. In dry areas, water moving up brings salts to the surface.'],
          ['Organic matter and weathering:', 'Organic matter is added at the surface, so the top is darker. Weathering is strongest near the surface and weaker at depth.'],
          ['Organisms:', 'Worms and roots are concentrated in the topsoil. They mix and enrich the upper horizons.']] },
    ],
    hwAnswer: 'In a road cutting: a thin dark topsoil (A), a thick red or brown subsoil rich in clay (B), weathered rock with stones (C), and sometimes solid rock at the bottom (R).',
  },
  'Lesson 9': {
    secs: ['1. MEANING AND CLASSIFICATION', '2. PODSOLISATION', '3. LATERISATION', '4. CALCIFICATION', '5. SALINISATION'],
    action: 'Understand the main soil-forming regimes to manage soils in different climates.',
    summary: [
      { title: '1. Meaning and Classification', intro: 'Pedogenic regimes can be understood as follows:',
        items: [['Pedogenic regime:', 'It is a major soil-forming process linked to a type of climate and vegetation.'],
          ['Classification:', 'In wet climates, water moves down and leaches the soil (podsolisation, laterisation). In dry climates, water moves up and salts accumulate (calcification, salinisation); gleying occurs in waterlogged soils.']],
        draw: { img: 'pedogenic_big.png', caption: 'major pedogenic regimes' } },
      { title: '2. Leaching Regimes', intro: 'The main leaching regimes are:',
        items: [['Podsolisation:', 'It occurs in cool, wet regions under coniferous forests (taiga). Acid water washes iron, aluminium and humus down, leaving a pale ash-grey E horizon and an iron pan below.'],
          ['Laterisation:', 'It occurs in hot, wet tropical regions such as southern Cameroon. Silica and bases are leached away, while iron and aluminium oxides remain, giving deep red soils and laterite crusts.']] },
      { title: '3. Accumulation Regimes', intro: 'The main accumulation regimes are:',
        items: [['Calcification:', 'It occurs in semi-arid grasslands such as the steppes and prairies. Evaporation draws calcium carbonate up, which collects near the surface and forms fertile chernozems.'],
          ['Salinisation:', 'It occurs in hot, dry regions and in badly irrigated land. Capillary rise brings salts to the surface, forming a white crust that kills crops.'],
          ['Gleying (gleization):', 'It occurs in waterlogged soils without oxygen, such as swamps and floodplains. Iron is reduced, giving grey-blue colours with rusty mottles.']] },
    ],
    hwAnswer: 'Podsolisation: cool, wet taiga. Laterisation: hot, wet equatorial and savanna. Calcification: semi-arid steppe. Salinisation: hot desert. Gleying: swamps and floodplains.',
  },
  'Lesson 10': {
    secs: ['1. THE PROCESSES', '2. WEATHERING', '3. ELUVIATION: LEACHING', '5. ORGANIC SORTING', '6. CAPILLARY ACTION'],
    action: 'Understand small soil processes to manage leaching and salinity.',
    summary: [
      { title: 'Minor Soil-Forming Processes', sub: 'A) Weathering and Eluviation', intro: 'The first minor processes are:',
        items: [['Weathering:', 'It breaks the parent rock into mineral particles and releases nutrients. Oxidation of iron gives red and yellow soils.'],
          ['Leaching:', 'It is the washing down of soluble nutrients (calcium, potassium) by water. It is strong under heavy rain and makes soils acid.'],
          ['Lessivage:', 'It is the washing down of fine clay particles in suspension. It leaves a sandier upper horizon.']],
        draw: { img: 'minor_processes_big.png', caption: 'minor soil processes' } },
      { title: 'Minor Soil-Forming Processes', sub: 'B) Illuviation, Sorting and Translocation', intro: 'Other minor processes are:',
        items: [['Illuviation:', 'It is the deposition in the B horizon of the materials washed down from above. Clay and iron accumulate there.'],
          ['Organic sorting:', 'Earthworms, termites and ants move and mix soil particles and organic matter. They bring fine material to the surface.'],
          ['Capillary action:', 'In dry areas water rises through fine pores and evaporates, leaving salts at the surface. This can form salt crusts.'],
          ['Translocation:', 'It is the general movement of materials within the profile, up or down. It creates the differences between horizons.']] },
    ],
    hwAnswer: 'The water coming out of the bottle is coloured (brown) and cloudy, because it carries dissolved nutrients and fine clay particles washed out of the soil (leaching and lessivage).',
  },
  'Lesson 11': {
    secs: ['1. BASIS OF CLASSIFICATION', '2. ZONAL SOILS', '3. INTRAZONAL SOILS', '4. AZONAL SOILS', '4. AZONAL SOILS'],
    action: 'Identify the soil classes of our area to use them properly.',
    summary: [
      { title: '1. Basis of Soil Classification', intro: 'Soils are classified as follows:',
        items: [['Basis:', 'Soils are classified according to their degree of development and the main factor that formed them. Climate and vegetation are the main basis of the zonal classification.'],
          ['Three classes:', 'Zonal soils reflect climate, intrazonal soils reflect a local factor, and azonal soils are young and immature. This classification is used on the soil maps of Cameroon.']],
        draw: { img: 'soil_classes_big.png', caption: 'classes of soil' } },
      { title: '2. Zonal, Intrazonal and Azonal Soils', intro: 'The meaning and characteristics of each class are:',
        items: [['Zonal soils:', 'They are mature soils with well-developed horizons, formed mainly by climate and vegetation over a long time. Examples are ferrallitic soils, podsols and chernozems.'],
          ['Intrazonal soils:', 'They are soils formed mainly by a local factor such as bad drainage, salt or limestone. Examples are hydromorphic (gley) soils and saline soils.'],
          ['Azonal soils:', 'They are young soils without clear horizons, because they formed recently or are constantly renewed. Examples are alluvial soils, volcanic ash soils and mountain soils.']] },
    ],
    hwAnswer: 'Zonal: ferrallitic soil of the South Cameroon Plateau. Intrazonal: hydromorphic soil of the Logone floodplain. Azonal: alluvial soil of the Benue valley or volcanic soil of Mount Cameroon.',
  },
  'Further Study 1': {
    secs: ['1. DISTRIBUTION', '1. ZONAL SOILS: FERRALLITIC', '1. ZONAL SOILS: BLACK EARTHS', '2. AZONAL SOILS', '3. INTRAZONAL SOILS'],
    action: 'Use the soils of each region of Cameroon according to their qualities.',
    summary: [
      { title: '1. Zonal Soils of Cameroon', intro: 'The zonal soils of Cameroon are:',
        items: [['Ferrallitic soils:', 'They cover the forest zone of the south and east and the Adamawa. They are deep, red and yellow, leached and acid, and need fertilisers for continuous farming.'],
          ['Ferruginous soils:', 'They are found in the savanna of the North region. They are less leached, reddish-brown, sandy and moderately fertile, used for cotton and cereals.'],
          ['Tropical black earths (vertisols):', 'They are found in the Diamaré plain and Far North. They are dark clay soils that crack when dry and are used for sorghum (muskwari) and cotton.']],
        draw: { img: 'cameroon_soils_big.png', caption: 'soils of Cameroon' } },
      { title: '2. Azonal and Intrazonal Soils', intro: 'The other soils of Cameroon are:',
        items: [['Volcanic soils:', 'They are found on Mount Cameroon and in the Western Highlands. They are young, dark and very fertile, supporting plantations and dense populations.'],
          ['Alluvial and mountain soils:', 'Alluvial soils lie along the Benue, Logone and coastal rivers; they are fertile and renewed by floods. Mountain soils are thin and stony on steep slopes.'],
          ['Hydromorphic soils:', 'They are found in swamps, mangroves and the yaérés of the Logone. They are waterlogged and grey, good for rice when drained.']] },
    ],
    hwAnswer: 'Ferrallitic soils – cocoa (South); ferruginous soils – cotton (North); black earths – muskwari sorghum (Far North); volcanic soils – bananas and tea (South West); hydromorphic soils – rice (Logone).',
  },
};
// homework preparing the new next lesson (Further Studies on Cameroon moved to Geography of Cameroon)
module.exports["Lesson 11"] = Object.assign(module.exports["Lesson 11"] || {}, { homework: "Define natural vegetation.", hwAnswer: "Natural vegetation is the plant cover that grows in an area without being planted or changed by people.", homeworkTag: '' });
