// v3 patches — LSA Module 1: Hydrology
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  'Lesson 22': {
    secs: ['1. MEANING AND SCOPE', '2. DISTRIBUTION OF WATER RESOURCES', '2. DISTRIBUTION: ICE CAPS', '2. DISTRIBUTION: UNDERGROUND WATER', '3. USES AND INCREASING DEMAND'],
    action: 'Use water resources wisely and protect water sources in our locality.',
    summary: [
      { title: '1. Meaning and Scope of Hydrology', intro: 'Hydrology can be understood as follows:',
        items: [['Hydrology:', 'It is the scientific study of water on, above and below the Earth\'s surface, its movement and its distribution.'],
          ['Scope:', 'Hydrology studies rainfall, evaporation, rivers, lakes, soil water and underground water. It is used to manage water supply, floods, irrigation and hydro-electricity.']] },
      { title: '2. Distribution of the World\'s Water Resources', intro: 'The water of the Earth is distributed as follows:',
        items: [['Oceans and seas:', 'They contain about 97 % of all water, which is salty. It cannot be drunk or used for farming without desalination.'],
          ['Ice caps and glaciers:', 'They hold about 2 % of all water, or nearly 70 % of fresh water. It is locked up in Antarctica and Greenland, far from people.'],
          ['Underground water:', 'It forms about 0.6 % of all water, or 30 % of fresh water. It is stored in aquifers and reached by wells and boreholes.'],
          ['Lakes, rivers, soil and atmosphere:', 'Together they hold less than 0.1 % of all water. Yet this small part is the water that people use most easily.']],
        draw: { img: 'world_water_big.png', caption: 'distribution of the world\'s water' } },
      { title: '3. Main Uses of Water and Increasing Demand', intro: 'People use water resources in the following ways:',
        items: [['Main uses:', 'Agriculture (irrigation) uses about 70 % of fresh water, industry about 20 % and homes about 10 %. Water is also used for hydro-electricity, transport and fishing.'],
          ['Increasing demand:', 'Demand is rising because of population growth, urbanisation, industrial growth and irrigation. Climate change and pollution reduce the water available.']] },
    ],
    hwAnswer: 'Sources in Garoua: the Benue river, wells, boreholes, streams (mayos) and rain water. Wells and mayos often dry up in the dry season, while boreholes and the Benue remain.',
  },
  'Lesson 23': {
    secs: ['1. MEANING', '2. THE SYSTEMS APPROACH: A CLOSED SYSTEM', '3. FLOWS AND QUANTITIES', '3. STORES: ATMOSPHERE', '3. STORES ON LAND'],
    action: 'Understand the circulation of water on Earth to manage it sustainably.',
    summary: [
      { title: '1. Meaning of the Hydrological Cycle', intro: 'The hydrological cycle can be understood as follows:',
        items: [['Hydrological (water) cycle:', 'It is the continuous movement of water between the oceans, the atmosphere and the land. It is powered by solar energy and gravity.']],
        draw: { img: 'water_cycle.gif', caption: 'the water cycle' } },
      { title: '2. The Systems Approach', intro: 'The hydrological cycle can be studied as a system:',
        items: [['System:', 'A system is a set of stores linked by flows or transfers of matter and energy. It has inputs, stores, flows and outputs.'],
          ['Closed system:', 'At the global scale, the water cycle is a closed system, because no water enters or leaves the Earth. Only energy (sunlight) enters and leaves.']] },
      { title: '3. Components of the Global Cycle', sub: 'A) Stores (Storages)', intro: 'The main stores of the global cycle are:',
        items: [['Oceans:', 'They are by far the largest store, with about 1,338 million km³ of water. Water may stay there for thousands of years.'],
          ['Ice, groundwater, lakes and rivers:', 'Ice caps and groundwater are large stores on land. Lakes, rivers and soil moisture are small but important for people.'],
          ['Atmosphere:', 'It is a very small store (about 13,000 km³). But water passes through it quickly, in about 9 days, so it feeds all rainfall.']] },
      { title: '3. Components of the Global Cycle', sub: 'B) Flows (Linkages) and Quantities', intro: 'Water moves between the stores through the following flows:',
        items: [['Evaporation and transpiration:', 'About 413,000 km³ evaporate from the oceans and 73,000 km³ from the land each year. They move water up into the atmosphere.'],
          ['Precipitation:', 'About 373,000 km³ fall on the oceans and 113,000 km³ on the land. More falls on land than evaporates from it.'],
          ['Runoff:', 'The extra 40,000 km³ that falls on land returns to the sea by rivers and groundwater flow. This keeps the cycle balanced.']],
        draw: { img: 'global_cycle_big.png', caption: 'the global water cycle (thousand km³ per year)' } },
    ],
    hwAnswer: 'Ocean evaporation 413 → rain on oceans 373 and 40 carried to land by winds; land evaporation 73 + 40 = rain on land 113; runoff 40 returns to the oceans.',
  },
  'Lesson 24': {
    secs: ['1. CONCEPT OF DRAINAGE BASIN', '1. CONCEPT OF DRAINAGE BASIN', '2. AN OPEN SYSTEM: INPUTS AND OUTPUTS', '3. STORES AND FLOWS', '3. STORES AND FLOWS'],
    action: 'Protect the drainage basins that supply our water.',
    summary: [
      D([['Drainage basin:', 'It is the area of land drained by a river and its tributaries.'], ['Watershed:', 'It is the high ground that separates two drainage basins.'], ['Open system:', 'It is a system that receives inputs from outside and loses outputs to the outside.']]),
      { title: '1. Concept of the Drainage Basin', intro: 'A drainage basin has the following parts:',
        items: [['Source and mouth:', 'A river begins at its source, often in the hills, and ends at its mouth in a sea, a lake or another river. The Benue rises on the Adamawa Plateau.'],
          ['Tributaries and confluence:', 'Tributaries are smaller rivers that join the main river. The point where they meet is the confluence.']],
        draw: { img: 'drainage_basin_big.png', caption: 'parts of a drainage basin' } },
      { title: '2. The Drainage Basin as an Open System', intro: 'The drainage basin receives and loses water as follows:',
        items: [['Input:', 'The main input is precipitation (rain, snow). Energy from the sun also enters the system.'],
          ['Outputs:', 'Water leaves by evapotranspiration to the atmosphere and by river discharge to the sea. Some may leave as deep groundwater flow.']],
        draw: { img: 'open_system_big.png', caption: 'the drainage basin as an open system' } },
      { title: '3. Stores and Flows', intro: 'Inside the basin, water is stored and transferred:',
        items: [['Stores:', 'Interception (on plants), surface storage (puddles, lakes), soil moisture, groundwater and the river channel. Water stays in each store for different lengths of time.'],
          ['Flows (transfers):', 'Throughfall and stemflow carry water to the ground; infiltration and percolation carry it down. Overland flow, throughflow and groundwater flow carry it to the river.'],
          ['Cascading system:', 'The output of one store is the input of the next. For example, infiltration moves water from the surface to the soil store.']],
        draw: { img: 'basin_system_big.png', caption: 'stores and flows in a drainage basin' } },
    ],
    hwAnswer: 'The sketch shows the stream, its source, tributaries, confluences and mouth, with the watershed drawn around the basin on the surrounding hills.',
  },
  'Lesson 25': {
    secs: ['1. URBANISATION', '1. URBANISATION', '2. AGRICULTURE AND FORESTRY', '3. DAMMING AND IRRIGATION', '4. WATERSHED DEGRADATION AND MANAGEMENT'],
    action: 'Manage our watersheds: plant trees, keep drains clean and avoid building in floodplains.',
    summary: [
      D([['Modified hydrological cycle:', 'It is the water cycle changed by human activities.'], ['Watershed degradation:', 'It is the damage to a drainage basin by deforestation, erosion and pollution.']]),
      { title: '1. Urbanisation', intro: 'Towns affect the hydrological cycle in the following ways:',
        items: [['Impermeable surfaces:', 'Roofs, roads and concrete stop infiltration. More rain becomes fast overland flow.'],
          ['Drains and channels:', 'Gutters carry water quickly to rivers, so lag time is shorter and flood peaks are higher. This is why Douala and Yaoundé flood often.'],
          ['Water use and pollution:', 'Towns take water from rivers and aquifers and return polluted waste water. Groundwater levels fall around big cities.']],
        draw: { img: 'urban_hydro_big.png', caption: 'river flow before and after urbanisation' } },
      { title: '2. Agriculture and Forestry', intro: 'Farming and forestry change the cycle as follows:',
        items: [['Deforestation:', 'Cutting trees reduces interception and transpiration. More water runs off quickly, causing soil erosion and floods.'],
          ['Farming practices:', 'Ploughing, overgrazing and bush fires leave soils bare and compacted. Terraces, cover crops and tree planting increase infiltration.']] },
      { title: '3. Damming and Irrigation', intro: 'Dams and irrigation modify rivers and water stores:',
        items: [['Dams:', 'They store water in reservoirs, control floods and regulate flow, as at Lagdo and Mbakaou. But they increase evaporation, trap silt and change downstream ecosystems.'],
          ['Irrigation:', 'It takes water from rivers and aquifers to fields, increasing evaporation. Over-use has helped to shrink Lake Chad and can cause salty soils.']] },
      { title: '4. Watershed Degradation and Management', intro: 'Degradation and its management strategies are:',
        items: [['Degradation:', 'Deforestation, overgrazing, mining and pollution damage watersheds. Springs dry up, rivers silt up and floods become more frequent.'],
          ['Management strategies:', 'Reforestation, soil conservation, protected catchments and control of building in floodplains. Integrated basin management, such as the Lake Chad Basin Commission, coordinates water use.']] },
    ],
    hwAnswer: 'Example: a low area near the market floods after heavy rain because drains are blocked with rubbish. Solutions: clean and enlarge the drains, and stop building on the floodplain.',
  },
  'Lesson 26': {
    secs: ['1. MEANING AND PROCESS', '5. FACTORS: WEATHER', '4. SPACE-TIME VARIATIONS', '2. TYPES: POTENTIAL AND ACTUAL', '3. MEASUREMENT'],
    action: 'Reduce water losses by evaporation in farming and water storage.',
    summary: [
      { title: '1. Meaning, Types and Process', intro: 'Evapotranspiration can be understood as follows:',
        items: [['Evapotranspiration:', 'It is the total loss of water to the atmosphere by evaporation from surfaces and by transpiration from plants.'],
          ['Types:', 'Potential evapotranspiration (PET) is the amount that would be lost if water were always available. Actual evapotranspiration (AET) is the amount really lost, which is lower when water is short.'],
          ['Process:', 'Evaporation changes liquid water into vapour using the sun\'s energy. Transpiration is water taken by roots and lost through the stomata of leaves.']],
        draw: { img: 'evapotranspiration_big.png', caption: 'evaporation and transpiration' } },
      { title: '2. Measurement and Variations', intro: 'Evapotranspiration is measured and varies as follows:',
        items: [['Measurement:', 'Evaporation is measured with an evaporation pan or a Piche evaporimeter. Evapotranspiration can be measured with a lysimeter or calculated with formulas such as Thornthwaite\'s.'],
          ['Space-time variations:', 'It is high in hot, sunny, windy regions and in the dry season. It is low in cold regions and at night.']] },
      { title: '3. Factors and Significance', intro: 'The main factors and significance of evapotranspiration are:',
        items: [['Climatic factors:', 'High temperature, sunshine, wind and low humidity increase evapotranspiration. This is why clothes dry fast on a hot, windy day.'],
          ['Surface factors:', 'Available water, vegetation type, leaf area and soil colour also matter. Forests transpire much more than bare land.'],
          ['Significance:', 'It is the main output of the drainage basin and returns about two-thirds of rainfall to the air. It recycles moisture that feeds rainfall, as in the Congo forest.']] },
    ],
    hwAnswer: 'The cup in the sun loses more water than the cup in the shade. Higher temperature and sunshine provide more energy for evaporation.',
  },
  'Lesson 27': {
    secs: ['1. MEANING', '4. MEASUREMENT', '2. TYPES AND PROCESS', '5. SPACE VARIATIONS', '5. TIME VARIATIONS'],
    action: 'Measure and record rainfall to plan farming and water supply.',
    summary: [
      { title: '1. Meaning, Types and Process', intro: 'Precipitation as an input can be understood as follows:',
        items: [['Precipitation:', 'It is all the water that falls from the atmosphere to the ground, as rain, snow, hail or drizzle. It is the main input of the drainage basin.'],
          ['Process:', 'Air rises, cools to its dew point and water vapour condenses on nuclei. Droplets grow by collision or around ice crystals until they are heavy enough to fall.'],
          ['Types:', 'Convectional rain comes from heated rising air, relief rain from air forced over mountains, and frontal (cyclonic) rain from warm air rising over cold air.']] ,
        draw: { img: 'rainfall_types_big.png', caption: 'types of rainfall' } },
      { title: '2. Measurement and Variations', intro: 'Precipitation is measured and varies as follows:',
        items: [['Measurement:', 'Rainfall is measured with a rain gauge and recorded in millimetres every day at the same time. Radar and satellites estimate rain over large areas.'],
          ['Space variations:', 'Rainfall decreases from the coast inland and increases on windward slopes. Douala receives about 4,000 mm but Garoua about 1,000 mm.'],
          ['Time variations:', 'Rainfall varies with the seasons, from year to year and even during a day. In Garoua most rain falls from June to September.']],
        draw: { img: 'rain_compare_big.png', caption: 'rainfall in Douala and Garoua' } },
      { title: '3. Factors and Significance', intro: 'The factors and significance of precipitation are:',
        items: [['Factors:', 'Pressure belts, air masses, relief, distance from the sea and ocean currents control precipitation. Intensity, duration and frequency vary with the type of rain.'],
          ['Significance:', 'Precipitation feeds all other stores and flows of the basin. Its intensity decides whether water infiltrates or runs off and causes floods.']] },
    ],
    hwAnswer: 'A bottle rain gauge with a funnel is placed in an open space; each morning the water depth is measured in mm and recorded. The week total is the sum of the daily values.',
  },
  'Lesson 28': {
    secs: ['1. MEANING AND PROCESS', '1. MEANING AND PROCESS', '5. FACTORS: VEGETATION', '5. FACTORS: LAND USE', '6. SIGNIFICANCE'],
    action: 'Protect vegetation cover to reduce floods and soil erosion.',
    summary: [
      { title: '1. Meaning, Types and Process', intro: 'Interception can be understood as follows:',
        items: [['Interception:', 'It is the catching and temporary storage of rain by vegetation and other surfaces before it reaches the ground.'],
          ['Types and process:', 'Rain held on leaves may evaporate (interception loss), drip to the ground (throughfall) or run down the trunk (stemflow). Buildings and litter can also intercept water.']],
        draw: { img: 'interception_big.png', caption: 'interception, throughfall and stemflow' } },
      { title: '2. Measurement and Variations', intro: 'Interception is measured and varies as follows:',
        items: [['Measurement:', 'Rain gauges are placed under and outside the tree canopy, and collars on trunks collect stemflow. Interception = rainfall − (throughfall + stemflow).'],
          ['Space-time variations:', 'Dense forests may intercept 20–30 % of rain, grasslands much less. Interception is higher at the start of a storm and in light rain.']] },
      { title: '3. Factors and Significance', intro: 'The factors and significance of interception are:',
        items: [['Factors:', 'Vegetation type, density, leaf shape and season control interception. Rainfall intensity, duration and wind also matter.'],
          ['Significance:', 'Interception slows water reaching the ground and increases infiltration. It reduces runoff, floods and soil erosion; when forests are cut, gullies appear.']] },
    ],
    hwAnswer: 'The cup under the tree collects less water than the cup in the open, because the leaves intercept part of the rain.',
  },
  'Lesson 29': {
    secs: ['1. MEANING', '2. TYPES: HORTONIAN OVERLAND FLOW', '2. TYPES: SATURATION OVERLAND FLOW', '5. FACTORS', '6. SIGNIFICANCE'],
    action: 'Increase infiltration on farms and in towns to reduce floods and erosion.',
    summary: [
      { title: '1. Meaning and Process', intro: 'Infiltration and overland flow can be understood as follows:',
        items: [['Infiltration:', 'It is the movement of water from the surface into the soil. The maximum rate is the infiltration capacity.'],
          ['Overland flow:', 'It is water that flows over the ground surface when it cannot infiltrate. It moves quickly to rivers.']],
        draw: { img: 'overland.gif', caption: 'infiltration and overland flow' } },
      { title: '2. Types of Overland Flow', intro: 'Overland flow is of two types:',
        items: [['Hortonian (infiltration-excess) flow:', 'It occurs when rain falls faster than the soil can absorb it. It is common in heavy tropical storms on bare or compacted soils.'],
          ['Saturation overland flow:', 'It occurs when the soil is already full of water, so no more can enter. It is common at the foot of slopes and near rivers after long rain.']],
        draw: { img: 'infiltration_big.png', caption: 'types of overland flow' } },
      { title: '3. Measurement, Variations and Factors', intro: 'Infiltration is measured, varies and depends on factors as follows:',
        items: [['Measurement:', 'An infiltrometer (a ring pushed into the soil) measures how fast water sinks in, in mm per hour. Overland flow is measured in small plots with collecting troughs.'],
          ['Space-time variations:', 'Infiltration is high on sandy soils and under forest, low on clay, rock and roads. It falls during a storm as the soil fills with water.'],
          ['Factors:', 'Rain intensity, soil texture, soil moisture, vegetation, slope and land use control infiltration. Compaction and urbanisation reduce it.']] },
      { title: '4. Significance', intro: 'Infiltration and overland flow are important because:',
        items: [['Infiltration:', 'It recharges soil moisture and groundwater and keeps rivers flowing in the dry season. Zaï pits and stone lines increase it on farms.'],
          ['Overland flow:', 'It causes rapid floods and soil erosion (sheet, rill and gully). It carries pollutants and sediment to rivers.']] },
    ],
    hwAnswer: 'The water soaks in faster on the grass than on the bare ground. Grass roots and organic matter keep the soil porous, while bare ground is compacted and crusted.',
  },
  'Lesson 30': {
    secs: ['3. STATES OF SOIL MOISTURE', '2. TYPES OF SOIL WATER', '5. VARIATIONS: DRY SEASON', '5. VARIATIONS: WET SEASON', '7. SIGNIFICANCE'],
    action: 'Conserve soil moisture for crops through mulching and good farming practices.',
    summary: [
      { title: '1. Meaning and Types of Soil Moisture', intro: 'Soil moisture can be understood as follows:',
        items: [['Soil moisture:', 'It is the water held in the pores of the soil between the surface and the water table.'],
          ['Types:', 'Gravitational water drains down through large pores after rain. Capillary water is held in small pores and used by plants, while hygroscopic water is held tightly around particles.']],
        draw: { img: 'soil_profile_big.png', caption: 'soil water in the profile' } },
      { title: '2. States of Soil Moisture', intro: 'Soil moisture exists in the following states:',
        items: [['Saturation:', 'All pores are full of water after heavy rain. Extra water drains or runs off.'],
          ['Field capacity:', 'It is the maximum water the soil can hold after gravitational water has drained away. This is the best state for plant growth.'],
          ['Wilting point:', 'It is the point where the remaining water is held too tightly for roots to take. Plants wilt and die if it continues.']],
        draw: { img: 'soil_states_big.png', caption: 'states of soil moisture' } },
      { title: '3. Measurement, Variations and Factors', intro: 'Soil moisture is measured and varies as follows:',
        items: [['Measurement:', 'A sample is weighed wet, dried in an oven and weighed again; the difference is the water content. Tensiometers and probes measure moisture in the field.'],
          ['Space-time variations:', 'Soils are wet in the rainy season and dry in the dry season. Valley bottoms are wetter than hill tops.'],
          ['Factors:', 'Rainfall, evapotranspiration, soil texture, organic matter and vegetation control soil moisture. Clay holds more water than sand.']] },
      { title: '4. Significance', intro: 'Soil moisture is important because:',
        items: [['For plants and farming:', 'Plants use the water between field capacity and wilting point. It decides the length of the growing season.'],
          ['For the hydrological cycle:', 'It controls infiltration, runoff and groundwater recharge. Dry soils absorb the first rains, while wet soils cause floods.']] },
    ],
    hwAnswer: 'Example: wet soil 200 g, dry soil 160 g. Water lost = 40 g, so moisture content = 40 ÷ 160 × 100 = 25 %.',
  },
  'Lesson 31': {
    secs: ['1. MEANING AND BALANCE', '2. SEASONAL VARIATIONS: RECHARGE', '2. SEASONAL VARIATIONS: DEFICIT', '3. USES FOR FARMING', '3. USES FOR FARMING'],
    action: 'Plan the farming calendar and irrigation using the soil moisture budget.',
    summary: [
      { title: '1. Meaning and Soil Moisture Balance', intro: 'The soil moisture budget can be understood as follows:',
        items: [['Soil moisture budget:', 'It is the balance between the water entering the soil (precipitation) and the water leaving it (evapotranspiration) through the year.'],
          ['Balance:', 'When precipitation is greater than PET, there is a surplus; when it is smaller, the soil store is used and a deficit follows. Budget = P − PET ± change in storage.']],
        draw: { img: 'soil_budget_big.png', caption: 'a soil moisture budget graph' } },
      { title: '2. Seasonal Variations', intro: 'In a tropical station such as Garoua, the budget changes as follows:',
        items: [['Recharge:', 'At the start of the rains, precipitation first refills the dry soil store. There is little runoff.'],
          ['Surplus:', 'When the soil reaches field capacity, extra water runs off or percolates to groundwater. Rivers rise and floods may occur.'],
          ['Utilisation and deficit:', 'When the rains stop, plants use the soil water store. When it is empty, there is a deficit and plants suffer drought.']] },
      { title: '3. Soil Moisture Regimes', intro: 'Soil moisture regimes differ between climates:',
        items: [['Humid regime:', 'In equatorial regions the soil is moist all year, with a surplus most months. Crops can grow at any time.'],
          ['Seasonal and arid regimes:', 'In tropical regions there is a surplus in the rainy season and a deficit in the dry season. In deserts there is a deficit almost all year.']] },
    ],
    hwAnswer: 'Garoua: wet months May–October, dry months November–April. Plant at the start of the rains (May–June) and harvest in October; irrigate or grow dry-season crops (muskwari) on residual moisture.',
  },
  'Lesson 32': {
    secs: ['1. MEANING', '2. TYPES (COMPONENTS)', '4. MEASUREMENT', '5. GENERAL FACTORS', '6. SIGNIFICANCE'],
    action: 'Use river runoff wisely and reduce floods by good land use.',
    summary: [
      { title: '1. Meaning and Types of Runoff', intro: 'Runoff can be understood as follows:',
        items: [['Runoff:', 'It is all the water that flows from a drainage basin into rivers and out of the basin.'],
          ['Components:', 'Quick flow is made of overland flow and fast throughflow after rain. Base flow comes slowly from groundwater and keeps rivers flowing in the dry season.']],
        draw: { img: 'basin_system_big.png', caption: 'quick flow and base flow' } },
      { title: '2. Characteristics and Measurement', intro: 'Runoff is described and measured as follows:',
        items: [['Characteristics:', 'Runoff has a volume (discharge), a speed and a frequency. Discharge is measured in cubic metres per second (m³/s).'],
          ['Measurement:', 'Discharge = cross-section area × velocity. Velocity is measured with a flow meter or a float, and gauging stations record water levels continuously.']] },
      { title: '3. General Factors of Runoff', intro: 'Runoff depends on the following factors:',
        items: [['Climatic characteristics:', 'Rainfall amount, intensity and duration and evapotranspiration control runoff. Heavy storms produce high runoff.'],
          ['Basin and channel characteristics:', 'Size, shape, slope, soil, rock and drainage density affect how fast water reaches the river. Steep, round basins on clay give rapid runoff.'],
          ['Land use:', 'Forests reduce runoff, while farming, overgrazing and urbanisation increase it. Dams regulate it.']] },
      { title: '4. Significance of Runoff', intro: 'Runoff is important because:',
        items: [['In the hydrological cycle:', 'It returns water from the land to the sea and balances the global cycle. It transports sediment and shapes valleys.'],
          ['For man:', 'It supplies water for drinking, irrigation, hydro-electricity and transport. High runoff can cause floods and erosion.']] },
    ],
    hwAnswer: 'Example: width 4 m, mean depth 0.5 m, so area = 2 m²; a float travels 10 m in 20 s, so velocity = 0.5 m/s. Discharge = 2 × 0.5 = 1 m³/s.',
  },
  'Lesson 33': {
    secs: ['1. MEANING AND CHARACTERISTICS', '2. TYPES OF HYDROGRAPHS', '4. STATIC FACTORS', '4. DYNAMIC FACTORS', '3. FLOOD PREDICTION'],
    action: 'Use hydrographs to predict floods and warn people in time.',
    summary: [
      D([['Channel flow:', 'It is the water flowing in a river channel.'], ['Discharge:', 'It is the volume of water passing a point per second, in m³/s.'], ['Storm hydrograph:', 'It is a graph showing how the discharge of a river changes after a storm.']]),
      { title: '1. Characteristics of a Storm Hydrograph', intro: 'A storm hydrograph has the following parts:',
        items: [['Rising limb and peak discharge:', 'The rising limb shows discharge increasing after the rain. The peak is the highest discharge.'],
          ['Lag time:', 'It is the time between peak rainfall and peak discharge. A short lag time means a high flood risk.'],
          ['Falling limb and base flow:', 'The falling limb shows discharge decreasing after the peak. Base flow is the groundwater part that continues between storms.']],
        draw: { img: 'storm_hydrograph_big.png', caption: 'a storm hydrograph' } },
      { title: '2. Types of Hydrographs', intro: 'There are three main types of hydrographs:',
        items: [['Flashy hydrograph:', 'It has a steep rising limb, a high peak and a short lag time. It shows a high risk of flash floods.'],
          ['Subdued hydrograph:', 'It has a gentle rising limb, a low peak and a long lag time. The flood risk is low.'],
          ['Double-peak hydrograph:', 'It has two peaks, from two storms or from quick flow followed by slower throughflow. It can also come from two tributaries.']],
        draw: { img: 'hydrograph_types_big.png', caption: 'flashy and subdued hydrographs' } },
      { title: '3. Factors Affecting the Shape and Lag Time', intro: 'The shape of a hydrograph depends on two groups of factors:',
        items: [['Dynamic factors:', 'Precipitation type, intensity, duration and frequency, and land use, change with time. Intense storms and urbanisation shorten lag time and raise the peak.'],
          ['Static factors:', 'Basin size, shape, relief, soil and rock stay the same. Small, round, steep basins on impermeable rock give flashy hydrographs.'],
          ['Flood prediction:', 'By studying past hydrographs, engineers predict flood peaks and lag times. Warnings allow people to move away and protect property.']],
        draw: { img: 'basin_shapes_big.png', caption: 'basin shape and hydrograph shape' } },
    ],
    hwAnswer: 'Flashy: steep and high, caused by heavy storms, steep slopes, clay or urban surfaces. Subdued: gentle and low, caused by forest cover, permeable soils and large, elongated basins.',
  },
  'Lesson 34': {
    secs: ['1. MEANING', '1. MEANING', '2. TYPES: SIMPLE REGIME', '2. TYPES: COMPLEX REGIME', '3. FACTORS: DAMS'],
    action: 'Plan navigation, irrigation and hydro-electricity according to river regimes.',
    summary: [
      { title: '1. Meaning of River Regimes', intro: 'A river regime can be understood as follows:',
        items: [['River regime:', 'It is the pattern of seasonal variation in the discharge of a river over a year.'],
          ['Example:', 'The Benue at Garoua has high water from August to October and very low water from February to April. Boats can reach Garoua only in the high-water period.']],
        draw: { img: 'regime_big.png', caption: 'regime of the Benue at Garoua' } },
      { title: '2. Types of River Regimes', intro: 'River regimes are of two main types:',
        items: [['Simple regime:', 'It has one high-water period and one low-water period in a year, from one source of water. The Sanaga and the Benue have simple tropical regimes.'],
          ['Complex regime:', 'It has two or more high-water periods, because the river is fed by several climate zones or by rain and snowmelt. The Nile and the Congo have complex regimes.']] },
      { title: '3. Factors of River Regimes', intro: 'River regimes depend on static and dynamic factors:',
        items: [['Climatic (dynamic) factors:', 'The amount and seasonality of rainfall, evaporation and snowmelt are the main factors. Rivers in wet equatorial regions have a regular flow.'],
          ['Basin (static) factors:', 'Rock type, soils, vegetation and the size of the basin affect how water is stored and released. Lakes and permeable rocks regulate flow.'],
          ['Human factors:', 'Dams and reservoirs store water in the wet season and release it in the dry season. The Mbakaou and Lom Pangar dams regulate the Sanaga for Edéa and Song Loulou.']] },
    ],
    hwAnswer: 'The Sanaga is highest from September to November, the best time for hydro-electricity. Dams such as Lom Pangar store water to keep turbines working in the low-water season (February to April).',
  },
  'Further Study 4': {
    secs: ['2. MAIN DRAINAGE BASINS', '2. THE WATERSHED: ADAMAWA', '3. RIVER SYSTEMS: ATLANTIC BASIN', '3. RIVER SYSTEMS: NIGER (BENUE) BASIN', '3. RIVER SYSTEMS: LAKE CHAD BASIN'],
    action: 'Protect and develop the water resources of Cameroon.',
    summary: [
      { title: '1. The Drainage Potentials of Cameroon', intro: 'Cameroon has a large drainage potential:',
        items: [['Abundant water:', 'Cameroon has many rivers fed by heavy rainfall, especially in the south. It has the second hydro-electric potential in Africa after the DR Congo.'],
          ['Uses:', 'Rivers provide hydro-electricity, irrigation, fishing, navigation and drinking water. Examples are Edéa, Lagdo and Nachtigal.']] },
      { title: '2. Main Watersheds and Drainage Basins', intro: 'Cameroon has four main drainage basins:',
        items: [['Atlantic basin:', 'It is the largest basin, with the Sanaga, Wouri, Nyong and Ntem flowing to the Gulf of Guinea. The Sanaga is the longest river of Cameroon (about 920 km).'],
          ['Niger (Benue) basin:', 'The Benue, Faro and Mayo Kebbi flow west to the Niger. The Lagdo dam is on the Benue.'],
          ['Lake Chad basin:', 'The Logone and Chari flow north into Lake Chad. It is an inland basin with no outlet to the sea.'],
          ['Congo basin:', 'The Sangha, Dja and Kadeï flow south-east to the Congo. It drains the East region.']],
        draw: { img: 'cameroon_drainage_big.png', caption: 'drainage basins of Cameroon' } },
      { title: '3. Distribution and Characteristics', intro: 'The drainage networks have the following characteristics:',
        items: [['Watersheds:', 'The Adamawa Plateau is the "water tower" of Cameroon, from which rivers flow in all directions. The Western Highlands are another watershed.'],
          ['Southern rivers:', 'They have large volumes and regular flow but many falls and rapids, good for hydro-electricity but poor for navigation. The Sanaga falls at Edéa and Song Loulou.'],
          ['Northern rivers:', 'They have a seasonal regime, with floods in the rainy season and very low flow in the dry season. Many mayos dry up completely.']] },
    ],
    hwAnswer: 'Atlantic basin: Sanaga, Wouri. Niger basin: Benue, Faro. Lake Chad basin: Logone, Chari. Congo basin: Sangha, Dja.',
  },
  'Practical Work 1': {
    secs: ['1. THE DATA', '2. PLOTTING A STORM HYDROGRAPH', '2. COLLECTING DATA', '3. REGIME GRAPHS', '4. INTERPRETATION AND USES'],
    action: 'Use hydrological data to predict floods and plan water projects.',
    summary: [
      D([['Storm hydrograph:', 'It is a graph of river discharge against time during and after a storm.'], ['River regime graph:', 'It is a graph of the mean monthly discharge of a river over a year.']]),
      { title: '1. Plotting a Storm Hydrograph', intro: 'A storm hydrograph is plotted as follows:',
        items: [['Axes:', 'Time (hours) is placed on the x-axis and discharge (m³/s) on the left y-axis. Rainfall (mm) is shown as bars on a second y-axis at the top or right.'],
          ['Plotting:', 'Plot each discharge value and join the points with a smooth curve. Draw the base flow line under the curve.'],
          ['Reading:', 'Mark the peak rainfall and the peak discharge and measure the lag time between them. Describe the rising and falling limbs.']],
        draw: { img: 'storm_hydrograph_big.png', caption: 'a plotted storm hydrograph' } },
      { title: '2. Plotting and Analysing a River Regime', intro: 'A regime graph is plotted and analysed as follows:',
        items: [['Plotting:', 'Place the months on the x-axis and mean discharge on the y-axis. Draw bars or a line for each month.'],
          ['Analysis:', 'Identify the high-water and low-water periods and calculate the ratio between them. Relate them to rainfall and to the type of regime.'],
          ['Uses:', 'Hydrographs and regimes are used to design dams, bridges and flood warnings. They also help to plan navigation and irrigation.']],
        draw: { img: 'regime_big.png', caption: 'a river regime graph' } },
    ],
    hwAnswer: 'The hydrograph rises from a base flow of about 5 m³/s to a peak of about 27 m³/s. The lag time is about 13 hours; the rising limb is steep and the falling limb is gentle, so the flood risk is fairly high.',
  },
  'Practical Work 2': {
    secs: ['2. AREAL PROPERTIES: STREAM ORDER', '2. AREAL PROPERTIES: BIFURCATION RATIO', '2. AREAL PROPERTIES: DRAINAGE DENSITY', '2. AREAL PROPERTIES: DRAINAGE TEXTURE', '1. LINEAR PROPERTIES'],
    action: 'Measure drainage basins to predict floods and plan land use.',
    summary: [
      { title: '1. Meaning and Classification', intro: 'Basin morphometry can be understood as follows:',
        items: [['Basin morphometry:', 'It is the measurement and analysis of the size, shape and network of a drainage basin.'],
          ['Classification of properties:', 'Linear properties concern the channels (length, width, depth, slope). Areal properties concern the basin (area, density, stream order).']] },
      { title: '2. Linear Properties', intro: 'The linear properties of a channel are calculated as follows:',
        items: [['Channel measurements:', 'Length, slope, width and depth are measured in the field or on maps. Cross-section area = width × mean depth.'],
          ['Wetted perimeter and hydraulic radius:', 'The wetted perimeter is the length of bed and banks in contact with water. Hydraulic radius = cross-section area ÷ wetted perimeter.'],
          ['Efficiency and sinuosity:', 'A high hydraulic radius means an efficient channel with little friction and fast flow. Sinuosity = channel length ÷ straight-line length.']],
        draw: { img: 'morphometry_big.png', caption: 'channel measurements' } },
      { title: '3. Areal Properties', intro: 'The areal properties of a basin are calculated as follows:',
        items: [['Drainage density:', 'Drainage density = total stream length ÷ basin area (km/km²). A high density shows impermeable rock, heavy rain and a high flood risk.'],
          ['Stream frequency:', 'Stream frequency = number of streams ÷ basin area. It shows how finely the basin is dissected.'],
          ['Stream order and bifurcation ratio:', 'With Strahler\'s method, two streams of the same order make the next order. Bifurcation ratio = number of streams of one order ÷ number of the next order; a low ratio means a higher flood risk.']],
        draw: { img: 'strahler_big.png', caption: 'Strahler stream ordering' } },
      { title: '4. Drainage Morphometric Laws', intro: 'Horton\'s laws describe drainage networks:',
        items: [['Law of stream numbers:', 'The number of streams decreases in a regular way as the order increases. The bifurcation ratio is fairly constant, about 3 to 5.'],
          ['Law of stream lengths:', 'The mean length of streams increases with order. Higher-order streams are longer.']] },
    ],
    hwAnswer: 'Example: 12 first-order, 3 second-order and 1 third-order streams. Bifurcation ratios: 12 ÷ 3 = 4 and 3 ÷ 1 = 3; mean ratio = 3.5.',
  },
};
