// v3 patches — LSA Module 3: Biogeography, part B (vegetation and ecosystems: Lessons 12–28, FS2, FS3, PW2)
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  'Lesson 12': {
    secs: ['1. DEFINITION', '1. DEFINITION', '2. PLANT GROUPINGS AND CLASSIFICATION', '3. THE VEGETATION SYSTEM', '4. IMPORTANCE OF VEGETATION'],
    action: 'Protect natural vegetation for its many services to man.',
    summary: [
      { title: '1. Meaning of Natural Vegetation', intro: 'Natural vegetation can be understood as follows:',
        items: [['Natural vegetation:', 'It is the plant cover that grows in an area without human interference, adapted to its climate and soils.'],
          ['Planted vegetation:', 'It is vegetation planted or changed by man, such as plantations and farms. An oil palm estate is not natural vegetation.']] },
      { title: '2. Plant Groupings and Classification', intro: 'Plants are grouped and classified as follows:',
        items: [['Plant groupings:', 'A plant community is a group of plants living together in the same area. A plant formation is a large community with a similar appearance, such as a rainforest.'],
          ['Classification:', 'Vegetation is classified into forests, grasslands and deserts or scrubs. It can also be classified by climate: tropical, temperate and polar.']] },
      { title: '3. The Vegetation System and Importance', intro: 'Vegetation works as a system and is important for man:',
        items: [['Inputs and outputs:', 'Inputs are sunlight, water, carbon dioxide and nutrients from the soil. Outputs are oxygen, water vapour, litter and biomass used by animals and man.'],
          ['Processes:', 'Photosynthesis makes food and stores energy, and respiration releases it. Plants also transpire water and recycle nutrients.'],
          ['Importance:', 'Vegetation provides food, timber, fuelwood, medicines and grazing. It protects soils, regulates climate and water, and shelters wildlife.']],
        draw: { img: 'veg_system_big.png', caption: 'the vegetation system' } },
    ],
    hwAnswer: 'Natural: elephant grass, shea tree, baobab, wild acacia. Planted: mango, maize, cotton, eucalyptus and neem around the house.',
  },
  'Lesson 13': {
    secs: ['1. NOTION OF PLANT SUCCESSION', '2. TYPES AND SITES OF PRISERES', '4. PROCESS OF COLONISATION', '4. PROCESS OF COLONISATION', '5. ARRESTING FACTORS'],
    action: 'Allow vegetation to recover naturally and avoid factors that stop its growth.',
    summary: [
      D([['Plant succession:', 'It is the gradual change of plant communities on a site over time until a stable climax is reached.'], ['Sere:', 'It is the whole series of plant communities in a succession.'], ['Prisere:', 'It is a succession that begins on a bare surface that never had vegetation.']]),
      { title: '1. Types and Sites of Priseres', intro: 'Successions are of different types according to their site:',
        items: [['Primary and secondary succession:', 'Primary succession starts on a new bare surface such as lava. Secondary succession starts where vegetation was removed, such as an abandoned farm.'],
          ['Sites of priseres:', 'A lithosere begins on bare rock, a psammosere on sand dunes and a hydrosere in fresh water. A halosere begins in salt marshes.']],
        draw: { img: 'priseres_big.png', caption: 'types of priseres' } },
      { title: '2. The Process of Plant Colonisation', intro: 'Colonisation follows these stages:',
        items: [['Pioneer stage:', 'Lichens and mosses colonise the bare surface and start weathering it. They add the first organic matter.'],
          ['Intermediate stages:', 'Grasses, herbs and shrubs follow as the soil deepens and improves. Each community changes the site and prepares it for the next.'],
          ['Climax stage:', 'Trees and a stable community are reached, in balance with the climate. The number of species and the biomass are highest.']],
        draw: { img: 'succession.gif', caption: 'stages of a plant succession' } },
      { title: '3. Arresting Factors', intro: 'A succession can be stopped by:',
        items: [['Natural factors:', 'Fire from lightning, floods, landslides and volcanic eruptions can stop or reverse a succession. Grazing by wild animals also keeps grasses.'],
          ['Human factors:', 'Bush fires, farming, grazing, logging and building stop the succession. The vegetation that results is a plagioclimax.']] },
    ],
    hwAnswer: 'On an abandoned field, first weeds and grasses grow, then shrubs and young trees. It is in the intermediate (shrub) stage of a secondary succession.',
  },
  'Lesson 14': {
    secs: ['1. MEANING', '2. TYPES: CLIMATIC CLIMAX', '2. TYPES: PLAGIOCLIMAX', '2. TYPES: PLAGIOCLIMAX', '4. DEBATE ON GRASSLANDS'],
    action: 'Judge the effects of man on vegetation and manage grasslands wisely.',
    summary: [
      { title: '1. Meaning of Climax Vegetation', intro: 'Climax vegetation can be understood as follows:',
        items: [['Climax vegetation:', 'It is the final, stable plant community of a succession, in balance with the environment.'],
          ['Mono-climax view:', 'Clements said that each climatic region has only one true climax, determined by climate. Other communities are only stages towards it.'],
          ['Poly-climax view:', 'Tansley said that several climaxes can exist in one region. Soils, relief, drainage and fire can also produce stable communities.']],
        draw: { img: 'climax_big.png', caption: 'climax vegetation' } },
      { title: '2. Types of Climaxes', intro: 'The main types of climaxes are:',
        items: [['Climatic climax:', 'It is controlled by climate, like the equatorial rainforest. It is the natural vegetation of a region.'],
          ['Edaphic and topographic climax:', 'They are controlled by soil (edaphic) or relief and drainage (topographic). Mangroves and swamp forests are examples.'],
          ['Plagioclimax:', 'It is a stable vegetation maintained by human activity such as fire, grazing or cutting. Many savannas and pastures are plagioclimaxes.']] },
      { title: '3. Debate on the Climax Status of Grasslands', intro: 'Scientists debate whether grasslands are true climaxes:',
        items: [['Grasslands as a plagioclimax:', 'Where fire and grazing stop, trees often return, as in parts of the Guinea savanna. This suggests that man created many savannas.'],
          ['Grasslands as a climatic climax:', 'In dry areas such as the prairies, steppes and Sahel, low rainfall prevents forests. There, grassland is the natural climax.']] },
    ],
    hwAnswer: 'The Guinea savanna of Cameroon is largely a plagioclimax maintained by bush fires and grazing; trees return where fire is controlled. The Sahel grassland is closer to a climatic climax because of low rainfall.',
  },
  'Lesson 15': {
    secs: ['1. PRIMARY SUCCESSION: LITHOSERE', '1. PRIMARY SUCCESSION: LITHOSERE', '1. PRIMARY SUCCESSION: HYDROSERE', '2. SECONDARY SUCCESSION', '2. SECONDARY SUCCESSION'],
    action: 'Help land recover naturally through fallowing and protection.',
    summary: [
      { title: '1. Primary Succession', intro: 'Examples of primary succession are:',
        items: [['Lithosere:', 'On new lava, lichens and mosses colonise first and form the first soil. Ferns, grasses, shrubs and finally forest follow, as on Mount Cameroon lava flows.'],
          ['Hydrosere:', 'In a pond, submerged plants, then floating plants and reeds colonise. Silt and dead plants fill the pond until it becomes a marsh, then dry land with trees.']],
        draw: { img: 'hydrosere_big.png', caption: 'a hydrosere' } },
      { title: '2. Secondary Succession', intro: 'Secondary succession can be illustrated as follows:',
        items: [['Process:', 'On an abandoned farm or after logging, grasses and weeds grow first, then shrubs and fast-growing trees. It is faster than primary succession because the soil and seeds are already there.'],
          ['Result:', 'After many years a secondary forest develops, but it is poorer in species than the original forest. Continuous cutting keeps it at a lower stage.']] },
    ],
    hwAnswer: 'A fallow field has grasses, weeds and small shrubs after one or two years, which shows the early to intermediate stage of secondary succession.',
  },
  'Lesson 16': {
    secs: ['1. HORIZONTAL DISTRIBUTION', '1. HORIZONTAL DISTRIBUTION', '2. FACTORS OF DISTRIBUTION', '3. VERTICAL DISTRIBUTION', '3. VERTICAL DISTRIBUTION'],
    action: 'Explain the distribution of vegetation and protect each formation.',
    summary: [
      { title: '1. Horizontal Distribution', intro: 'Vegetation formations are distributed as follows:',
        items: [['From the Equator to the tropics:', 'The equatorial rainforest gives way to savanna, then to semi-desert and desert. In Africa this order is seen from the Congo basin to the Sahara.'],
          ['In the mid-latitudes and polar regions:', 'Mediterranean scrub, temperate forests and grasslands are followed by the coniferous taiga. The tundra and ice caps are found near the poles.']],
        draw: { img: 'africa_vegetation_big.png', caption: 'vegetation formations of Africa' } },
      { title: '2. Factors of Vegetation Distribution', intro: 'Vegetation distribution depends on the following factors:',
        items: [['Climate:', 'Temperature and rainfall are the main factors: forests need much rain, while grasslands and deserts are drier. Cold limits trees near the poles.'],
          ['Soils and relief:', 'Soil fertility and drainage decide which plants grow; swamps have special vegetation. Relief changes climate with altitude and aspect.'],
          ['Biotic factors and man:', 'Animals graze and spread seeds. Man clears forests, burns savannas and plants crops and trees.']] },
      { title: '3. Vertical Distribution of Vegetation', intro: 'Vegetation changes with altitude on mountains:',
        items: [['Vertical zonation:', 'On Mount Cameroon, lowland rainforest gives way to montane forest, then to montane grassland and bare rock at the top. Each belt reflects falling temperature.'],
          ['Comparison with latitude:', 'Climbing a high mountain is like travelling from the Equator towards the poles. The belts are compressed into a few kilometres.']],
        draw: { img: 'veg_altitude_big.png', caption: 'vegetation belts on a mountain' } },
    ],
    hwAnswer: 'Mount Cameroon: lowland rainforest (0–800 m), submontane forest (800–1,600 m), montane forest (1,600–2,400 m), montane grassland (2,400–3,500 m), bare lava and rock near the summit (4,040 m).',
  },
  'Further Study 2': {
    secs: ['1. DISTRIBUTION', '1. FOREST VEGETATION: MANGROVES', '1. FOREST VEGETATION: RAINFOREST', '2. GRASSLAND VEGETATION', '3. DOMESTICATED LANDSCAPES'],
    action: 'Protect the vegetation of Cameroon through forest reserves and sustainable use.',
    summary: [
      { title: '1. Forest Vegetation of Cameroon', intro: 'The forest types of Cameroon are:',
        items: [['Mangrove forest:', 'It grows on muddy coasts and estuaries (Wouri, Rio del Rey) with stilt-rooted trees. It is a breeding ground for fish but is threatened by cutting and pollution.'],
          ['Rainforest:', 'It covers the south and east with tall evergreen trees such as sapele and iroko. It is exploited for timber and is threatened by logging, farming and mining.'],
          ['Montane and submontane forests:', 'They grow on Mount Cameroon, Mount Oku and the Western Highlands. They are rich in rare species but are cleared for farms and grazing.']],
        draw: { img: 'cameroon_veg_big.png', caption: 'vegetation of Cameroon' } },
      { title: '2. Grassland Vegetation of Cameroon', intro: 'The grassland types from south to north are:',
        items: [['Guinea savanna:', 'It lies in the Centre and Adamawa with tall grasses and scattered trees. It is used for grazing and farming and is burnt every year.'],
          ['Sudan savanna:', 'It covers the North region with shorter grasses and trees such as shea and acacia. It is used for cotton, cereals and cattle.'],
          ['Sahel savanna:', 'It is found near Lake Chad with short grasses and thorny bushes. It is threatened by overgrazing, drought and desertification.']] },
      { title: '3. Domesticated Landscapes and Forest Reserves', intro: 'Man has also created and protected vegetation:',
        items: [['Man-planted vegetation:', 'Plantations of oil palm, rubber, bananas and tea, and trees such as eucalyptus and neem, replace natural vegetation. Farms and fallows form mosaics.'],
          ['Forest reserves:', 'Reserves and parks such as Dja, Korup, Campo-Ma\'an and Waza protect vegetation and wildlife. Measures include forest laws, reforestation and community forests.']] },
    ],
    hwAnswer: 'Mangrove – cutting for fuelwood; rainforest – logging; montane forest – farming; Guinea savanna – bush fires; Sudan savanna – overgrazing; Sahel – desertification.',
  },
  'Lesson 17': {
    secs: ['2. COMPONENTS OF ECOSYSTEMS', '2. BIOTIC COMPONENTS: PRODUCERS', '2. BIOTIC COMPONENTS', '2. BIOTIC COMPONENTS: CONSUMERS', '2. BIOTIC COMPONENTS: DECOMPOSERS'],
    action: 'Protect the balance of ecosystems in our environment.',
    summary: [
      { title: '1. Definition of Ecology and Ecosystems', intro: 'The main terms are defined as follows:',
        items: [['Ecology:', 'It is the study of the relationships between living organisms and their environment.'],
          ['Ecosystem:', 'It is a community of living organisms interacting with each other and with their non-living environment in a given area. It can be as small as a pond or as large as a forest.']] },
      { title: '2. Components of Ecosystems', intro: 'An ecosystem has two groups of components:',
        items: [['Abiotic components:', 'They are the non-living parts: sunlight, temperature, water, air, soil and nutrients. They provide energy and materials.'],
          ['Producers:', 'Green plants make their own food by photosynthesis. They are the base of all food chains.'],
          ['Consumers:', 'Herbivores eat plants, carnivores eat animals and omnivores eat both. The zebra is a herbivore and the lion a carnivore.'],
          ['Decomposers:', 'Bacteria and fungi break down dead matter and return nutrients to the soil. Without them, dead matter would pile up.']],
        draw: { img: 'ecosystem_components_big.png', caption: 'components of an ecosystem' } },
      { title: '3. Characteristics of Ecosystems', intro: 'Ecosystems have the following characteristics:',
        items: [['Open systems:', 'They receive energy and matter and lose them. Energy flows through them, while nutrients are recycled.'],
          ['Dynamic balance:', 'Their components are linked, so a change in one part affects the others. They can change over time and recover after disturbance.']] },
    ],
    hwAnswer: 'Producers: grass, trees, maize. Consumers: goats, chickens, birds, insects and people. Decomposers: fungi, bacteria, termites and earthworms.',
  },
  'Lesson 18': {
    secs: ['1. INPUTS, OUTPUTS AND PROCESSES', '1. PROCESSES: PHOTOSYNTHESIS', '1. PROCESSES: DECOMPOSITION', '2. INTERACTIONS: FEEDING', '2. INTERACTIONS: HUMAN CHANGES'],
    action: 'Manage ecosystems as systems so that inputs and outputs stay balanced.',
    summary: [
      D([['System:', 'It is a set of parts linked by flows of energy and matter.']]),
      { title: '1. Inputs, Outputs and Processes', intro: 'An ecosystem works as a system with:',
        items: [['Inputs:', 'Solar energy, rainfall, carbon dioxide and nutrients from weathering and the air enter the system. Man adds fertilisers and seeds.'],
          ['Processes:', 'Photosynthesis stores energy in plants, feeding transfers it to animals and decomposition returns nutrients to the soil. Respiration releases energy as heat.'],
          ['Outputs:', 'Heat, water vapour, oxygen and nutrients lost by leaching and erosion leave the system. Harvested crops and timber are also outputs.']],
        draw: { img: 'ecosystem_system_big.png', caption: 'the ecosystem as a system' } },
      { title: '2. Interactions between the Parts', intro: 'The parts of the ecosystem interact as follows:',
        items: [['Links between components:', 'Plants depend on soil and climate, animals depend on plants, and decomposers depend on dead matter. A change in one part changes the others.'],
          ['Human interference:', 'Removing vegetation reduces photosynthesis and increases runoff and erosion. Outputs of soil and nutrients then become greater than inputs.']] },
    ],
    hwAnswer: 'Farm system: inputs – sun, rain, seeds, manure and labour; stores – crops, soil and livestock; outputs – harvest, milk, eroded soil and water lost by evaporation.',
  },
  'Lesson 19': {
    secs: ['1. COMPONENTS OF THE POND', '1. COMPONENTS: PRODUCERS', '2. FOOD CHAIN', '3. THE POND AS A SYSTEM', '3. COMPARISON'],
    action: 'Protect ponds and wetlands from pollution and drying.',
    summary: [
      { title: '1. Components and Characteristics of a Pond', intro: 'A pond ecosystem has the following components:',
        items: [['Abiotic components:', 'Water, sunlight, dissolved oxygen, nutrients and bottom mud. Temperature and light change with depth.'],
          ['Producers:', 'Algae, water lilies and reeds make food by photosynthesis. Phytoplankton are tiny floating producers.'],
          ['Consumers and decomposers:', 'Zooplankton, insects, tadpoles and small fish are consumers, and large fish, birds and man are top consumers. Bacteria in the mud decompose dead matter.']],
        draw: { img: 'pond_big.png', caption: 'a pond ecosystem' } },
      { title: '2. The Pond as a System', intro: 'The pond works as a system:',
        items: [['Inputs and outputs:', 'Inputs are sunlight, rain, runoff with nutrients and leaves. Outputs are evaporation, outflow, fish caught and heat.'],
          ['Food chain and characteristics:', 'A typical chain is algae → zooplankton → small fish → large fish → man. The pond is small, clearly limited and sensitive to pollution.']] },
    ],
    hwAnswer: 'In a pond or stream: water plants, algae, frogs and tadpoles, insects (mosquito larvae, water beetles), small fish, snails and birds that feed there.',
  },
  'Lesson 20': {
    secs: ['1. THE FOUR COMPARTMENTS', '2. INTERRELATIONS', '3. EQUILIBRIUM', '4. FACTORS OF DISEQUILIBRIUM', '4. FACTORS OF DISEQUILIBRIUM'],
    action: 'Avoid human actions that upset the balance of ecosystems.',
    summary: [
      { title: '1. Structure of the Ecosystem', intro: 'A four-compartment ecosystem has:',
        items: [['Abiotic compartment:', 'It includes the atmosphere, water, rocks and soil minerals. It supplies energy and materials.'],
          ['Biotic compartments:', 'They are producers (plants), consumers (animals) and decomposers. Each compartment stores energy and nutrients.']],
        draw: { img: 'equilibrium_big.png', caption: 'the four compartments' } },
      { title: '2. Interrelations and Equilibrium', intro: 'The compartments are linked and balanced as follows:',
        items: [['Interrelations:', 'Nutrients move from the soil to plants, from plants to animals, and back to the soil through litter and decomposition. Energy flows in one direction from the sun to decomposers.'],
          ['Equilibrium:', 'When inputs equal outputs, the ecosystem is in balance. The equilibrium is dynamic, because numbers and flows change but stay within limits.']] },
      { title: '3. Factors of Disequilibrium', intro: 'The balance can be upset by:',
        items: [['Natural factors:', 'Droughts, floods, fires, diseases and volcanic eruptions disturb ecosystems. Most ecosystems recover over time.'],
          ['Man:', 'Deforestation, overgrazing, bush fires, pollution and hunting are the main causes of disequilibrium. For example, logging removes the biomass store and exposes the soil to erosion.']] },
    ],
    hwAnswer: 'Example: the savanna near town has been overgrazed and burnt; grass cover has disappeared, soil is eroded and wild animals have left, so the ecosystem has lost its balance.',
  },
  'Lesson 21': {
    secs: ['1. SOURCES OF ENERGY', '1. SOURCES OF ENERGY', '2. ENERGY FLOW', '3. THE FIRST LAW', '3. THE SECOND LAW'],
    action: 'Use energy flows to understand why food production is most efficient at low trophic levels.',
    summary: [
      { title: '1. Sources of Energy in the Ecosystem', intro: 'Energy enters the ecosystem as follows:',
        items: [['Solar energy:', 'The sun is the main source of energy for almost all ecosystems. Only about 1 % of the sunlight reaching plants is used in photosynthesis.'],
          ['Photosynthesis:', 'Plants change light energy into chemical energy stored in food (glucose). This energy is passed on to animals when they feed.']] },
      { title: '2. The Two Energy Laws', intro: 'Energy flow obeys the two laws of thermodynamics:',
        items: [['First law:', 'Energy cannot be created or destroyed; it only changes form. Light becomes chemical energy, then movement and heat.'],
          ['Second law:', 'At each transfer, some energy is lost as heat, so less is available at the next level. Only about 10 % passes from one trophic level to the next.'],
          ['Consequence:', 'Energy flows in one direction and cannot be recycled. This is why there are many zebras but few lions.']],
        draw: { img: 'energy_flow_big.png', caption: 'energy flow through trophic levels' } },
    ],
    hwAnswer: 'With about 10 % passed at each level: grass 50,000 → grasshopper 5,000 → bird 500 → hawk 50 units.',
  },
  'Lesson 22': {
    secs: ['1. MEANING AND ILLUSTRATION', '3. FOOD CHAINS', '3. FOOD WEBS', '3. FOOD WEBS: DECOMPOSERS', '2. LIMITATION OF TROPHIC LEVELS'],
    action: 'Protect all levels of food chains, because each level depends on the others.',
    summary: [
      { title: '1. Meaning and Illustration of Trophic Levels', intro: 'Trophic levels can be understood as follows:',
        items: [['Trophic level:', 'It is the position of an organism in a food chain, according to how it gets its food.'],
          ['Illustration:', 'Level 1 is producers (plants), level 2 primary consumers (herbivores), level 3 secondary consumers and level 4 tertiary consumers. They are shown as a pyramid.']],
        draw: { img: 'trophic_pyramid_big.png', caption: 'a trophic pyramid' } },
      { title: '2. Stepwise Nature and Limitation', intro: 'Trophic levels are limited as follows:',
        items: [['Stepwise nature:', 'Energy passes step by step from one level to the next. Each step has less energy, fewer organisms and less biomass.'],
          ['Limitation:', 'Because about 90 % of energy is lost at each step, there is rarely enough energy for more than four or five levels. Top predators such as lions are few.']] },
      { title: '3. Food Chains and Food Webs', intro: 'Feeding relationships are shown as follows:',
        items: [['Food chain:', 'It is a simple line showing who eats whom. Example: grass → zebra → lion.'],
          ['Food web:', 'It is a network of connected food chains in an ecosystem. It is more stable, because animals have several food sources.'],
          ['Decomposers:', 'They feed on dead matter from all levels. They recycle nutrients back to the producers.']],
        draw: { img: 'food_web_big.png', caption: 'a food web' } },
    ],
    hwAnswer: 'Example web: grass and maize are eaten by grasshoppers, goats and rats; grasshoppers are eaten by birds and lizards; rats and lizards are eaten by snakes and hawks.',
  },
  'Lesson 23': {
    secs: ['2. THE GERSMEHL MODEL', '1. DEFINITION: LITTER', '2. FLOWS: DECOMPOSITION', '2. FLOWS: UPTAKE', '2. INPUTS AND OUTPUTS'],
    action: 'Keep nutrients in our farms and forests by protecting the nutrient cycle.',
    summary: [
      { title: '1. Meaning of Nutrient Cycling', intro: 'Nutrient cycling and its stores are defined as follows:',
        items: [['Nutrient cycling:', 'It is the continuous movement of mineral nutrients between the living and non-living parts of an ecosystem.'],
          ['Biomass:', 'It is the total mass of living organisms, mainly plants, in an area.'],
          ['Litter and soil:', 'Litter is the dead organic matter on the ground, such as fallen leaves. The soil store holds nutrients in humus and minerals.']] },
      { title: '2. The Gersmehl Model', intro: 'Gersmehl\'s model shows nutrient cycling with three stores:',
        items: [['Flows between stores:', 'Fallout moves nutrients from biomass to litter, decomposition from litter to soil, and uptake from soil to biomass. The size of the arrows shows the amount.'],
          ['Inputs:', 'Nutrients enter from weathering of rocks and from rain and dust. Nitrogen is fixed from the air.'],
          ['Outputs:', 'Nutrients leave by leaching, runoff and soil erosion. Harvesting and burning also remove them.']],
        draw: { img: 'gersmehl_big.png', caption: 'the Gersmehl model' } },
    ],
    hwAnswer: 'The diagram shows three circles (biomass, litter, soil) linked by fallout, decomposition and uptake, with inputs from weathering and rain and outputs by leaching and runoff.',
  },
  'Lesson 24': {
    secs: ['1. COMPARISON', '1. THE SELVA', '1. THE SELVA REPLACED', '2. THE STEPPE REPLACED', '3. THE TAIGA'],
    action: 'Manage cleared ecosystems so that their soils do not lose fertility.',
    summary: [
      { title: '1. The Selva and its Replacement', intro: 'Nutrient cycling in the tropical rainforest is as follows:',
        items: [['The selva:', 'Most nutrients are stored in the huge biomass, while the litter and soil stores are small. Hot, wet conditions decompose litter quickly, and roots take nutrients up at once.'],
          ['Man-made replacement:', 'When the forest is cleared for farms or plantations, the biomass store is removed. Heavy rain leaches the poor soil, so fertility falls within a few years.']],
        draw: { img: 'gersmehl_compare_big.png', caption: 'Gersmehl models of three biomes' } },
      { title: '2. The Steppe and its Replacement', intro: 'Nutrient cycling in the temperate grassland is as follows:',
        items: [['The steppe:', 'The soil store is the largest, with deep, dark chernozems rich in humus. The biomass is small, and grass dies back each year.'],
          ['Man-made replacement:', 'Steppes were ploughed for wheat and maize, and the rich soil allowed long farming. But overuse, erosion and the Dust Bowl show that nutrients must be restored.']] },
      { title: '3. The Taiga', intro: 'Nutrient cycling in the coniferous forest is as follows:',
        items: [['Stores:', 'The litter store is the largest, because the cold climate slows decomposition. Needles are acid and decompose slowly.'],
          ['Flows:', 'Uptake and decomposition are slow, and soils are acid podsols. The system is poor in available nutrients.']] },
    ],
    hwAnswer: 'Selva: large biomass circle, small litter and soil circles, big fast flows. Steppe: small biomass, medium litter, large soil circle. The selva stores nutrients in plants, the steppe in the soil.',
  },
  'Lesson 25': {
    secs: ['1. MEANING', '2. RETURNING NUTRIENTS', '2. RETURNING NUTRIENTS', '3. REDUCING LOSSES', '3. COPYING NATURE'],
    action: 'Use knowledge of nutrient cycling to keep our farms productive.',
    summary: [
      { title: '1. Meaning of Ecosystem Management', intro: 'Ecosystem management can be understood as follows:',
        items: [['Ecosystem management:', 'It is the use of ecosystems to obtain resources while keeping their structure, functions and productivity for the future.'],
          ['Link with nutrient cycling:', 'Knowing where nutrients are stored and how they flow helps to use ecosystems without exhausting them. Managers protect the main stores and flows.']] },
      { title: '2. How Man Uses Nutrient Cycling', intro: 'Man can foster ecosystem management in the following ways:',
        items: [['Returning nutrients:', 'Manure, compost, crop residues and fertilisers replace the nutrients removed by harvests. Fertilisers must be used carefully to avoid pollution.'],
          ['Reducing losses:', 'Terraces, cover crops, mulching and contour ploughing reduce erosion and leaching. Avoiding bush fires keeps nutrients in the litter.'],
          ['Copying nature:', 'Agroforestry, crop rotation, fallowing and legumes imitate natural cycling. Trees bring up nutrients from deep and add litter.']] },
    ],
    hwAnswer: 'Plan: use cow dung and compost every year; rotate cereals with legumes; plant trees along the fields; mulch; build contour ridges; leave part of the land fallow; stop burning crop residues.',
  },
  'Lesson 26': {
    secs: ['1. MEANING AND TYPES', '3. PRODUCTIVITY OF DIFFERENT ECOSYSTEMS', '4. REASONS: HIGH PRODUCTIVITY', '4. REASONS: LOW PRODUCTIVITY', '2. MEASUREMENT'],
    action: 'Understand where ecosystems are most productive to use and protect them.',
    summary: [
      { title: '1. Meaning and Types of Productivity', intro: 'Productivity can be understood as follows:',
        items: [['Productivity:', 'It is the rate at which new organic matter (biomass) is produced in an ecosystem, in g/m²/year.'],
          ['Primary productivity:', 'It is the production of organic matter by green plants through photosynthesis.'],
          ['Secondary productivity:', 'It is the production of new biomass by consumers (animals) from the food they eat. It is much smaller than primary productivity.']] },
      { title: '2. Measurement of Productivity', intro: 'Productivity is measured in two ways:',
        items: [['Gross primary productivity (GPP):', 'It is the total energy or matter fixed by plants through photosynthesis. Part of it is used for respiration.'],
          ['Net primary productivity (NPP):', 'NPP = GPP − respiration; it is the matter available to consumers. It is measured by harvesting and weighing dry plant matter in quadrats.']] },
      { title: '3. Productivity of Ecosystems and Factors', intro: 'Productivity varies between ecosystems:',
        items: [['Productivity of different ecosystems:', 'Tropical rainforests (about 2,200 g/m²/year) and swamps are the most productive. Deserts, tundra and the open ocean are the least productive.'],
          ['Reasons and factors:', 'Light, warmth, water and nutrients increase productivity. Cold, drought and poor soils reduce it.']],
        draw: { img: 'productivity_big.png', caption: 'net primary productivity of biomes' } },
    ],
    hwAnswer: 'Rainforest (warm and wet all year) > swamp (water and nutrients) > savanna (dry season) > temperate grassland > desert (lack of water) and tundra (cold).',
  },
  'Practical Work 2': {
    secs: ['1. THE DATA', '2. BAR GRAPH', '3. PRODUCTIVITY PER UNIT AREA', '4. INTERPRETATION', '4. INTERPRETATION'],
    action: 'Calculate and compare the productivity of ecosystems.',
    summary: [
      D([['Gross productivity:', 'It is the total organic matter produced by plants.'], ['Net productivity:', 'It is the gross productivity minus the matter used in respiration.']]),
      { title: '1. Calculations', intro: 'Productivity data are processed as follows:',
        items: [['Net productivity:', 'NPP = gross productivity − respiration. For example, 4,000 − 1,800 = 2,200 g/m²/year for the rainforest.'],
          ['Productivity per unit area:', 'Divide the total production by the surface area to compare ecosystems of different sizes. A 1 m² quadrat giving 900 g of dry matter gives 900 g/m²/year.']],
        draw: { img: 'pw_productivity_big.png', caption: 'productivity data' } },
      { title: '2. Presentation and Interpretation', intro: 'The results are presented and interpreted as follows:',
        items: [['Bar graph:', 'Draw one bar for the NPP of each biome and rank them from highest to lowest. Label the axes and give a title.'],
          ['Classification:', 'The rainforest is high, the savanna medium and the desert low in NPP per unit area. Ecosystems are classed as high, medium or low productivity.'],
          ['Reasons for differences:', 'Rainforests have heat, light and water all year. Savannas have a dry season, and deserts lack water.']],
        draw: { img: 'productivity_big.png', caption: 'bar graph of NPP' } },
    ],
    hwAnswer: 'The bar graph shows the rainforest highest, then savanna, temperate grassland and desert. NPP decreases as water and warmth decrease; the desert is lowest because of lack of water.',
  },
  'Lesson 27': {
    secs: ['1. MEANING', '2. CLASSIFICATION', '2. A) TEMPERATE BIOMES', '2. B) GRASSLAND BIOMES', '2. A) POLAR BIOMES'],
    action: 'Locate and describe the biomes of the world.',
    summary: [
      { title: '1. Meaning of Biomes', intro: 'A biome can be understood as follows:',
        items: [['Biome:', 'It is a very large ecosystem covering a wide area, with similar climate, vegetation, soils and animals.'],
          ['Example:', 'The tropical rainforest biome is found in the Amazon, the Congo basin and South-East Asia. The same biome has similar plants on different continents.']],
        draw: { img: 'biomes_map_big.png', caption: 'biomes of the world' } },
      { title: '2. Classification of Biomes', sub: 'A) By Climatic Characteristics', intro: 'Biomes are classified by climate into:',
        items: [['Tropical biomes:', 'Rainforest, savanna and hot desert are found between the tropics. They are warm all year.'],
          ['Temperate biomes:', 'Deciduous forest, Mediterranean scrub, temperate grassland and taiga are found in the mid-latitudes. They have marked seasons.'],
          ['Polar biomes:', 'Tundra and ice caps are found near the poles. They are cold, with a very short growing season.']] },
      { title: '2. Classification of Biomes', sub: 'B) By Vegetation Characteristics', intro: 'Biomes are also classified by vegetation into:',
        items: [['Forests:', 'Rainforest, deciduous forest and coniferous forest are dominated by trees. They need much water.'],
          ['Grasslands:', 'Savanna, prairie and steppe are dominated by grasses. They occur where rainfall is seasonal or moderate.'],
          ['Scrublands and deserts:', 'Mediterranean scrub, semi-desert and tundra have low, scattered plants. They are limited by drought or cold.']],
        draw: { img: 'biome_classes_big.png', caption: 'classification of biomes' } },
    ],
    hwAnswer: 'Rainforest – hot, wet – tall evergreen trees; savanna – hot, wet and dry seasons – grass with trees; hot desert – very dry – cacti and shrubs; temperate forest – mild, four seasons – deciduous trees; taiga – cold – conifers; tundra – very cold – mosses and lichens.',
  },
  'Lesson 28': {
    secs: ['1. TROPICAL RAINFOREST: VEGETATION', '1. TROPICAL RAINFOREST: CLIMATE', '2. TROPICAL GRASSLAND: VEGETATION', '2. TROPICAL GRASSLAND: CLIMATE', '3. HOT DESERT'],
    action: 'Use tropical biomes sustainably and solve their challenges.',
    summary: [
      { title: '1. Tropical Rainforest (Selva)', intro: 'The tropical rainforest has the following characteristics:',
        items: [['Location and climate:', 'It lies between 5° N and 5° S in the Congo basin, the Amazon and South-East Asia. It is hot (26–28 °C) and wet (over 2,000 mm) all year.'],
          ['Vegetation, soils and fauna:', 'Tall evergreen trees form layers, with lianas and epiphytes; soils are deep, red and leached. It has the greatest variety of animals, and very high productivity.'],
          ['Resources, challenges and solutions:', 'It provides timber, food, medicines and minerals. It is threatened by logging and farming; solutions are reserves, reforestation and sustainable logging.']] },
      { title: '2. Tropical Grassland (Savanna)', intro: 'The savanna has the following characteristics:',
        items: [['Location and climate:', 'It lies between about 5° and 15° N and S, as in northern Cameroon and East Africa. It is hot, with a wet season and a long dry season.'],
          ['Vegetation, soils and fauna:', 'Tall grasses with scattered drought-resistant trees such as baobab and acacia; soils are ferruginous. It has herds of grazing animals and their predators.'],
          ['Human activities and challenges:', 'People practise cattle rearing, cotton and cereal farming and tourism. Bush fires, overgrazing and drought are challenges, managed by controlled grazing and fire control.']] },
      { title: '3. Tropical Hot Deserts', intro: 'Hot deserts have the following characteristics:',
        items: [['Location and climate:', 'They lie near 20–30° of latitude, like the Sahara and the Kalahari. Rainfall is below 250 mm and the daily temperature range is very large.'],
          ['Vegetation, soils and fauna:', 'Plants such as cacti and acacias have long roots, thick skins and small leaves. Soils are thin and sandy, and animals are active at night.'],
          ['Relationship between climate, vegetation and soil:', 'In all three biomes, rainfall controls vegetation, and vegetation controls humus and soil fertility. Where rain decreases, biomass and productivity decrease.']] },
    ],
    hwAnswer: 'Rainforest: hot and wet; tall trees; ferrallitic soils; timber and cocoa. Savanna: wet and dry seasons; grass and trees; ferruginous soils; cattle and cotton. Desert: very dry; cacti and shrubs; thin sandy soils; oases and nomadic herding.',
  },
  'Further Study 3': {
    secs: ['1. TYPES OF SERVICES', '2. PROVISIONING SERVICES', '2. PROVISIONING SERVICES', '5. SUPPORTING SERVICES', '4. CULTURAL SERVICES'],
    action: 'Value and protect the services that ecosystems give us.',
    summary: [
      { title: '1. Meaning of Ecosystem Services', intro: 'Ecosystem services can be understood as follows:',
        items: [['Ecosystem services:', 'They are the benefits that people obtain from ecosystems. They are grouped into provisioning, regulating, cultural and supporting services.']],
        draw: { img: 'services_big.png', caption: 'types of ecosystem services' } },
      { title: '2. Types of Ecosystem Services', intro: 'The four types of services are:',
        items: [['Provisioning services:', 'Ecosystems supply food, fresh water, timber, fuelwood, fibres and medicines. For example, forests give bush mango and medicinal plants, and rivers give fish.'],
          ['Regulating services:', 'Ecosystems regulate climate, store carbon, purify water and control floods and erosion. Mangroves protect coasts from storms.'],
          ['Cultural services:', 'Ecosystems give places for tourism, recreation, education and religious ceremonies. Waza park and sacred forests are examples.'],
          ['Supporting services:', 'They make all other services possible: soil formation, nutrient cycling, photosynthesis and pollination. Bees pollinate crops such as coffee.']] },
    ],
    hwAnswer: 'Near a river: provisioning – fish and water; regulating – flood control and water purification; cultural – bathing, ceremonies; supporting – soil formation on the banks.',
  },
};
// homework preparing the new next lesson (Further Studies on Cameroon moved to Geography of Cameroon)
module.exports["Lesson 16"] = Object.assign(module.exports["Lesson 16"] || {}, { homework: "Define an ecosystem.", hwAnswer: "An ecosystem is a community of living things interacting with each other and with their non-living environment (soil, water, air).", homeworkTag: '' });
