// v3 patches — USA Module 4: Population Geography
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  'Lesson 1': {
    secs: ['1. A) CENSUSES', '1. C) VITAL REGISTRATION', '1. D) MIGRATION RECORDS', '1. A) PROBLEMS OF CENSUSES', '2. CURRENT STATE OF GLOBAL POPULATION'],
    action: 'Register births and deaths and take part in censuses so that planning is based on good data.',
    summary: [
      D([['Population data:', 'They are figures on the number, structure and movement of people.'], ['Census:', 'It is the official count of all the people of a country at a given time.']]),
      { title: '1. Sources of Population Data', intro: 'Population data come from the following sources:',
        items: [['Censuses:', 'A census counts every person and records age, sex, occupation and residence, usually every ten years. Cameroon held censuses in 1976, 1987 and 2005 (BUCREP).'],
          ['Sample surveys:', 'They collect detailed information from a small part of the population, such as the Demographic and Health Surveys. They are cheaper and faster than a census.'],
          ['Vital registration:', 'It records births, deaths and marriages as they happen at the civil status office. It gives birth and death rates between censuses.'],
          ['Migration records:', 'Passports, visas, border and refugee records show people entering and leaving a country. Many movements across African borders are not recorded.']],
        draw: { img: 'data_sources_big.png', caption: 'sources of population data' } },
      { title: '1. Sources of Population Data', sub: 'Problems of Data Collection in LEDCs', intro: 'Data collection faces the following problems:',
        items: [['Practical problems:', 'Poor roads, remote villages, nomads and insecurity make counting difficult. Many births and deaths are never registered.'],
          ['Financial and social problems:', 'Censuses are very expensive, and illiteracy and mistrust lead to wrong answers. Data may be manipulated for political reasons.']] },
      { title: '2. Current State of Global Population', intro: 'The world population today can be described as follows:',
        items: [['World total:', 'The world population passed 8 billion in 2022 and grows by about 70 million a year. Growth is slowing down.'],
          ['Distribution:', 'Asia has about 60 % of the world population, with China and India above 1.4 billion each. Africa has the fastest growth and the youngest population.']],
        draw: { img: 'world_pop_big.png', caption: 'world population by continent' } },
    ],
    hwAnswer: 'Some adults have no birth certificate because they were born at home in a village far from a civil status centre, their parents did not know the importance of the document, or the fees and distance discouraged them.',
  },
  'Lesson 2': {
    secs: ['1. MEANING', '1. MEANING', '2. TYPES AND MEASUREMENT OF DENSITY', '2. TYPES AND MEASUREMENT OF DENSITY', '3. USEFULNESS'],
    action: 'Measure population density to plan services where people live.',
    summary: [
      { title: '1. Meaning of Population Distribution', intro: 'Population distribution can be understood as follows:',
        items: [['Population distribution:', 'It is the way people are spread over the Earth\'s surface. It can be even, clustered or scattered.'],
          ['Population density:', 'It is the average number of people per unit of area, usually per km².']] },
      { title: '2. Types and Measurement of Density', intro: 'Density is measured in different ways:',
        items: [['Arithmetic (crude) density:', 'It is the total population divided by the total area. Cameroon: 28 million ÷ 475,000 km² ≈ 59 people per km².'],
          ['Physiological density:', 'It is the population divided by the area of cultivable land. It shows the pressure of people on farmland.'],
          ['Agricultural density:', 'It is the farming population divided by the area of cultivable land. It shows how many farmers work each km².']],
        draw: { img: 'density_types_big.png', caption: 'types of population density' } },
      { title: '3. Evaluation of Usefulness', intro: 'Density measures have advantages and limits:',
        items: [['Usefulness:', 'Density allows comparison between places of different sizes and helps planning of schools, hospitals and roads. Physiological density shows pressure on land better.'],
          ['Limits:', 'Arithmetic density hides empty and crowded areas inside a region. It says nothing about wealth or resources.']],
        draw: { img: 'choropleth_big.png', caption: 'population density by region of Cameroon' } },
    ],
    hwAnswer: 'North Region (example): population about 2.5 million, area about 66,000 km², density ≈ 2,500,000 ÷ 66,000 ≈ 38 people per km².',
  },
  'Practical Work 1': {
    secs: ['1. DOT MAPS', '1. CHOROPLETH MAPS', '2. THE LORENZ CURVE', '3. POPULATION DENSITY LAPSE RATE', '4. ASSESSMENT'],
    action: 'Map population data to show where people live.',
    summary: [
      D([['Dot map:', 'It is a map where each dot represents a fixed number of people.'], ['Choropleth map:', 'It is a map where areas are shaded according to their density.'], ['Lorenz curve:', 'It is a graph that shows how unevenly a population is distributed.']]),
      { title: '1. Methods of Mapping Population', intro: 'Distribution and density can be mapped as follows:',
        items: [['Dot maps:', 'Choose a value for each dot (e.g. 1 dot = 10,000 people) and place the dots where people live. They show distribution clearly.'],
          ['Choropleth maps:', 'Calculate density for each area, choose classes and shade darker for higher densities. They show density by administrative region.']],
        draw: { img: 'dot_map_big.png', caption: 'a dot map' } },
      { title: '2. The Lorenz Curve and Density Lapse Rate', intro: 'Uneven distribution can be measured as follows:',
        items: [['Lorenz curve:', 'Rank the areas, then plot the cumulative % of area against the cumulative % of population. The further the curve is from the diagonal, the more unequal the distribution.'],
          ['Density lapse rate:', 'In a town, density usually decreases from the centre to the edge. A graph of density against distance shows this lapse.']],
        draw: { img: 'lorenz_big.png', caption: 'a Lorenz curve' } },
      { title: '3. Assessment of these Methods', intro: 'Each method has advantages and disadvantages:',
        items: [['Dot maps:', 'They show real distribution, but dots are hard to count and to place accurately. Very dense areas become black.'],
          ['Choropleth maps:', 'They are easy to read and compare, but they suggest sudden changes at boundaries. They hide differences inside each area.'],
          ['Lorenz curve:', 'It measures inequality precisely, but it does not show where people live. It needs accurate data.']],
        draw: { img: 'mapping_methods_big.png', caption: 'comparison of methods' } },
    ],
    hwAnswer: 'Classes (example): below 25, 25–50, 50–100, over 100 people/km². Littoral, West, North-West and Far North are darkest; East, South and Adamawa are lightest.',
  },
  'Lesson 3': {
    secs: ['1. VARIATIONS AT DIFFERENT SCALES', '2. PHYSICAL FACTORS: CLIMATE', '2. PHYSICAL FACTORS: WATER AND SOILS', '3. ECONOMIC AND SOCIAL FACTORS', '2. RELIEF AND LATITUDE'],
    action: 'Explain the uneven distribution of population and plan balanced development.',
    summary: [
      D([['Habitable space (ecumene):', 'It is the part of the Earth where people live permanently.'], ['Uninhabitable space (anecumene):', 'It is the part where permanent settlement is very difficult, such as ice caps and deserts.']]),
      { title: '1. Variations at Different Spatial Scales', intro: 'Population is unevenly distributed at all scales:',
        items: [['Densely populated regions:', 'South and East Asia, Western Europe, north-eastern USA and the Nile valley are crowded. In Cameroon, the West, Littoral and Far North plains are dense.'],
          ['Sparsely populated regions:', 'Deserts, polar lands, high mountains and dense forests have few people. The Sahara, Siberia and the Amazon are examples; in Cameroon the East is sparse.']],
        draw: { img: 'world_density_big.png', caption: 'world population density' } },
      { title: '2. Physical (Environmental) Factors', intro: 'Physical factors of population distribution include:',
        items: [['Climate:', 'Moderate, well-watered climates attract people, while very cold or dry areas repel them. Yet some extreme areas are dense, such as the Nile valley in the desert.'],
          ['Relief:', 'Lowlands attract people in temperate lands, but in the tropics cool highlands are often crowded. The Western Highlands of Cameroon and the Ethiopian Highlands are examples.'],
          ['Water, soils and resources:', 'Rivers, fertile soils and minerals attract settlement. River plains and deltas such as the Ganges are very dense.']] },
      { title: '3. Economic, Social and Political Factors', intro: 'Human factors of population distribution include:',
        items: [['Economic factors:', 'Industry, mining, ports and services create jobs and attract people. Douala grows because of its port and industries.'],
          ['Historical and political factors:', 'Old kingdoms, colonial plantations and railways concentrated people. Government policies, capital cities and conflicts also change distribution.'],
          ['Social factors:', 'Cultural attachment to ancestral land and family ties keep people in some areas. Access to schools and hospitals attracts others.']] },
    ],
    hwAnswer: 'The Far North plains are crowded because of fertile black soils, flat land, old settlement history and refuge in the Mandara Mountains. The East is sparse because of dense forest, poor soils, disease and poor roads.',
  },
  'Practical Work 2': {
    secs: ['1. READING THE GRAPH', '2. TEMPERATE PATTERN', '3. TROPICAL PATTERN', '3. TROPICAL PATTERN: CAMEROON', '4. EXPLANATION'],
    action: 'Interpret graphs of population and altitude to explain settlement.',
    summary: [
      D([['Altitudinal distribution:', 'It is the distribution of population according to height above sea level.']]),
      { title: '1. Analysis of the Graph', intro: 'The graph of population and altitude shows two patterns:',
        items: [['Temperate pattern:', 'Population decreases quickly with altitude; most people live below 500 m. High mountains such as the Alps are cold and sparsely populated.'],
          ['Tropical pattern:', 'Many people live at medium altitudes (1,000–2,500 m). Cities such as La Paz, Addis Ababa and Bamenda are in highlands.']],
        draw: { img: 'altitude_pop_big.png', caption: 'population and altitude' } },
      { title: '2. Explanation', intro: 'The differences are explained as follows:',
        items: [['Why highlands attract people in the tropics:', 'Highlands are cooler, healthier (less malaria) and have fertile volcanic soils. The lowlands are hot, humid and full of disease.'],
          ['Why highlands repel people in temperate lands:', 'Temperature falls with altitude and highlands become too cold for crops. Lowlands are warmer and easier for farming and transport.']],
        draw: { img: 'altitude_table_big.png', caption: 'altitude and density in Cameroon' } },
    ],
    hwAnswer: 'The bar graph shows few people below 500 m and many between 1,000 and 2,000 m in tropical highlands. This is because highlands are cool, healthy and fertile, while the hot lowlands have diseases.',
  },
  'Lesson 4': {
    secs: ['1. DIFFERENTIAL GROWTH RATES', '1. DIFFERENTIAL GROWTH RATES', '2. MIGRATION', '2. MIGRATION: RURAL–URBAN', '2. MIGRATION: FORCED'],
    action: 'Understand how population distribution changes to plan for future needs.',
    summary: [
      D([['Differential growth:', 'It is the difference in population growth rates between regions or countries.'], ['Redistribution:', 'It is the change in the spatial distribution of population over time.']]),
      { title: '1. Effects of Differential Growth Rates', intro: 'Different growth rates change the world distribution:',
        items: [['Fast-growing regions:', 'Africa grows at about 2.5 % a year, so its share of the world population is rising. It may hold a quarter of humanity by 2050.'],
          ['Slow-growing regions:', 'Europe and Japan grow very slowly or decline. Their share of the world population is falling.']],
        draw: { img: 'pop_share_big.png', caption: 'share of world population by continent' } },
      { title: '2. Migration as a Factor of Redistribution', intro: 'Migration redistributes population as follows:',
        items: [['Rural–urban migration:', 'Young people move from villages to towns for jobs and education. It concentrates population in cities such as Douala and Yaoundé.'],
          ['International migration:', 'People move from poor to rich countries, for example from Africa to Europe. This increases population in destination countries.'],
          ['Forced migration:', 'Conflicts and disasters force people to flee, as in the Far North and the North-West and South-West regions. Refugee camps create new concentrations.']] },
    ],
    hwAnswer: 'Example: an adult came to town to find work and send the children to good schools, after poor harvests in the village.',
  },
  'Lesson 5': {
    secs: ['1. MEANING', '2. A) DEMOGRAPHIC COMPONENTS', '2. B) SOCIO-POLITICAL COMPONENTS', '2. C) ECONOMIC COMPONENTS', '2. C) ECONOMIC COMPONENTS'],
    action: 'Use population structure data to plan education, health and employment.',
    summary: [
      { title: '1. Meaning of Population Structure', intro: 'Population structure can be understood as follows:',
        items: [['Population structure (composition):', 'It is the make-up of a population according to characteristics such as age, sex, education, religion and occupation.']],
        draw: { img: 'structure_components_big.png', caption: 'components of population structure' } },
      { title: '2. Components of Population Structure', intro: 'The components are grouped into three:',
        items: [['Demographic components:', 'They are age, sex, marital status and place of residence (urban or rural). They are shown on pyramids.'],
          ['Socio-political components:', 'They include ethnic group, language, religion, nationality and education level. They affect unity, voting and social services.'],
          ['Economic components:', 'They include occupation, economic sector, income and the active and dependent population. The literacy rate is linked to the skills of the workforce.']] },
    ],
    hwAnswer: 'Table columns: name, age, sex, occupation (e.g. father – 45 – M – farmer; mother – 40 – F – trader; children – students).',
  },
  'Lesson 6': {
    secs: ['2. GLOBAL PATTERNS', '3. YOUTHFUL POPULATION', '3. YOUTHFUL POPULATION', '4. AGEING POPULATION', '4. AGEING POPULATION'],
    action: 'Plan for the needs of both young and old people.',
    summary: [
      { title: '1. Meaning and Global Patterns', intro: 'Age and sex composition can be understood as follows:',
        items: [['Age and sex composition:', 'It is the number or percentage of males and females in each age group of a population. The sex ratio is the number of males per 100 females.'],
          ['Global patterns:', 'LEDCs such as Cameroon and Niger have youthful populations, with over 40 % under 15. MEDCs such as Japan and Italy have ageing populations, with over 20 % over 65.']],
        draw: { img: 'youth_ageing_big.png', caption: 'youthful and ageing populations' } },
      { title: '2. Youthful Population', intro: 'A youthful population has the following consequences:',
        items: [['Problems:', 'It needs many schools, health centres and jobs, and dependency is high. Unemployment of young people can cause social problems.'],
          ['Advantages:', 'It provides a large future workforce and a dynamic market. If educated and employed, youth can give a demographic dividend.']] },
      { title: '3. Ageing Population', intro: 'An ageing population has the following consequences:',
        items: [['Problems:', 'There are fewer workers to pay taxes and pensions, and health costs rise. Schools close and labour shortages appear.'],
          ['Advantages and responses:', 'Old people have experience and savings and do voluntary work. Countries raise the retirement age and encourage immigration.']] },
    ],
    hwAnswer: 'Young people need schools, jobs and leisure facilities; old people need health care, pensions and care homes or family support.',
  },
  'Lesson 7': {
    secs: ['1. MEANING', '2. TYPES OF PYRAMIDS', '2. TYPES OF PYRAMIDS', '3. FACTORS', '4. DEPENDENCY RATIO'],
    action: 'Read population pyramids to plan for the future.',
    summary: [
      { title: '1. Meaning of the Age-Sex Pyramid', intro: 'The pyramid can be understood as follows:',
        items: [['Population pyramid:', 'It is a bar graph that shows the percentage of males and females in each age group of a population. Males are on the left and females on the right.']],
        draw: { img: 'pyramid_cameroon_big.png', caption: 'population pyramid of Cameroon' } },
      { title: '2. Types of Pyramids', intro: 'The main types of pyramids are:',
        items: [['Expansive (progressive) pyramid:', 'It has a wide base and a narrow top, showing high birth and death rates. It is typical of LEDCs such as Cameroon.'],
          ['Stationary pyramid:', 'It has almost straight sides, showing low birth and death rates. It is found in some MEDCs.'],
          ['Constrictive (regressive) pyramid:', 'It has a narrow base and a wide top, showing an ageing, declining population. Japan and Italy are examples.']],
        draw: { img: 'pyramid_types_big.png', caption: 'types of pyramids' } },
      { title: '3. Factors and Indices', intro: 'The shape of pyramids depends on:',
        items: [['Demographic factors:', 'Birth rate shapes the base, death rate and life expectancy shape the top, and migration adds or removes groups. Wars and epidemics create notches.'],
          ['Non-demographic factors:', 'Education of women, family planning, health care and economic development change the shape in the long run. Policies such as China\'s one-child policy change it quickly.'],
          ['Dependency ratio:', 'It is (people aged 0–14 + people over 65) ÷ people aged 15–64 × 100. A ratio of 82 means 82 dependants for every 100 workers.']] },
    ],
    hwAnswer: 'Cameroon: wide base, narrow top, many children, few old people. Japan: narrow base, wide top, few children, many old people, more old women than men.',
  },
  'Practical Work 3': {
    secs: ['1. THE DATA', '2. CONSTRUCTION', '3. DEPENDENCY RATIO', '4. INTERPRETATION', '4. INTERPRETATION'],
    action: 'Draw and interpret population pyramids and dependency ratios.',
    summary: [
      D([['Dependency ratio:', 'It is the number of dependants (under 15 and over 64) for every 100 people of working age (15–64).']]),
      { title: '1. Construction of a Population Pyramid', intro: 'A pyramid is drawn as follows:',
        items: [['Calculations:', 'Calculate each age group as a percentage of the total population. For example, 1,480 boys aged 0–4 out of 9,870 = 15 %.'],
          ['Drawing:', 'Draw a vertical axis with the age groups and a horizontal axis with percentages on both sides. Draw males on the left and females on the right, with a title and key.']],
        draw: { img: 'pw_pyramid_table_big.png', caption: 'data table' } },
      { title: '2. Calculation and Interpretation', intro: 'The results are calculated and interpreted as follows:',
        items: [['Dependency ratio:', 'Add the population under 15 and over 64, divide by the population aged 15–64 and multiply by 100. A high ratio means a heavy burden on workers.'],
          ['Reading the pyramid:', 'Note the width of the base, the shape of the sides and the top, and any notches. They show birth rate, death rate, life expectancy and events such as migration.'],
          ['Distinguishing types:', 'A wide base shows an expansive pyramid (LEDC), straight sides a stationary one, and a narrow base a constrictive one (MEDC). Each type tells us the stage of development of the country.']],
        draw: { img: 'dependency_big.png', caption: 'dependency ratio' } },
    ],
    hwAnswer: 'The town pyramid has a wide base and a narrow top (expansive). The dependency ratio is high (above 80), so many children depend on workers; the town needs schools and jobs.',
  },
  'Lesson 8': {
    secs: ['1. GLOBAL TRENDS', '2. THE INDUSTRIAL REVOLUTION', '2. AFTER THE INDUSTRIAL REVOLUTION', '3. REGIONAL TRENDS', '3. REGIONAL TRENDS'],
    action: 'Understand the history of population growth to prepare for the future.',
    summary: [
      { title: '1. Global Trends before the Industrial Revolution', intro: 'World population grew slowly for a long time:',
        items: [['Slow growth:', 'Until about 1750, high birth and death rates kept growth very slow. Famines, wars and epidemics such as the plague reduced population.'],
          ['Milestones:', 'The world reached 1 billion around 1804 and 2 billion in 1927. Growth then became faster and faster.']],
        draw: { img: 'world_growth_big.png', caption: 'growth of world population' } },
      { title: '2. During and after the Industrial Revolution', intro: 'Growth accelerated for the following reasons:',
        items: [['Industrial Revolution:', 'Better farming, food supply, transport and sanitation reduced death rates in Europe. Population grew quickly in the 19th century.'],
          ['20th century to present:', 'Vaccines, antibiotics and clean water spread worldwide after 1950, so death rates fell everywhere. The world reached 8 billion in 2022.']] },
      { title: '3. Regional Trends', intro: 'Growth differs between regions:',
        items: [['MEDCs:', 'Growth is slow or negative, because birth rates are low. Europe and Japan are ageing.'],
          ['LEDCs:', 'Growth is faster, especially in Africa, where birth rates remain high while death rates have fallen. Asia and Latin America are slowing down.']],
        draw: { img: 'regional_growth_big.png', caption: 'growth of MEDCs and LEDCs' } },
    ],
    hwAnswer: 'Timeline: 1804 – 1 billion; 1927 – 2 billion; 1960 – 3 billion; 1974 – 4 billion; 1987 – 5 billion; 1999 – 6 billion; 2011 – 7 billion; 2022 – 8 billion.',
  },
  'Lesson 9': {
    secs: ['1. MEANING: TYPES OF GROWTH', '2. THE POPULATION CHANGE SYSTEM', '3. DETERMINANTS: FERTILITY', '3. SPATIAL DIFFERENCES', '3. DETERMINANTS: MIGRATION'],
    action: 'Understand the components of population change in our country.',
    summary: [
      { title: '1. Meaning of Population Growth', intro: 'Population growth can be understood as follows:',
        items: [['Population growth:', 'It is the change in the number of people in an area over time.'],
          ['Positive, negative and zero growth:', 'Growth is positive when the population increases, negative when it decreases and zero when it stays the same. Niger grows fast, Japan declines.']],
        draw: { img: 'growth_types_big.png', caption: 'types of growth' } },
      { title: '2. The Population Change System', intro: 'Population change is explained as a system:',
        items: [['Formula:', 'Population change = (births − deaths) + (immigrants − emigrants). Births minus deaths is natural increase.'],
          ['Inputs and outputs:', 'Births and immigration are inputs, deaths and emigration are outputs. The population is the store.']],
        draw: { img: 'change_system_big.png', caption: 'the population change system' } },
      { title: '3. Determinants and their Spatial Differences', intro: 'Population growth is determined by:',
        items: [['Fertility:', 'It is high in Sub-Saharan Africa (about 4–7 children per woman) and low in Europe and East Asia (below 2). It is the main cause of growth differences.'],
          ['Mortality:', 'Death rates are now low in most countries, but infant mortality is still high in poor regions. Life expectancy ranges from about 55 to over 85 years.'],
          ['Migration:', 'Migration adds people to rich countries and cities and removes them from poor regions. It is important in the Gulf states, Europe and North America.']],
        draw: { img: 'birth_death_big.png', caption: 'birth and death rates by region' } },
    ],
    hwAnswer: 'Village system: inputs – births and people coming back from town; outputs – deaths and young people leaving for towns; store – the village population.',
  },
  'Practical Work 4': {
    secs: ['1. FORMULAS', '2. CALCULATIONS', '3. POPULATION PROJECTIONS AND DOUBLING TIME', '4. NET MIGRATION', '5. INTERPRETATION'],
    action: 'Calculate demographic indices to describe population change.',
    summary: [
      D([['Fertility:', 'It is the actual number of children born to women.'], ['Fecundity:', 'It is the biological ability of a woman to have children.']]),
      { title: '1. Formulas of Demographic Indices', intro: 'The main indices are calculated as follows:',
        items: [['Crude birth rate (CBR):', 'CBR = births in a year ÷ total population × 1,000. It is given per 1,000 people to compare countries.'],
          ['Crude death rate (CDR):', 'CDR = deaths in a year ÷ total population × 1,000. Infant mortality rate = deaths under 1 year ÷ live births × 1,000.'],
          ['Growth rate:', 'Natural increase (%) = (CBR − CDR) ÷ 10. For example, (35 − 9) ÷ 10 = 2.6 %.']],
        draw: { img: 'indices_big.png', caption: 'formulas of demographic indices' } },
      { title: '2. Projections, Doubling Time and Migration', intro: 'Other calculations include:',
        items: [['Doubling time:', 'Doubling time ≈ 70 ÷ growth rate (%). At 2.6 %, a population doubles in about 27 years.'],
          ['Population projection:', 'Future population = present population × (1 + r)ⁿ, where r is the growth rate and n the number of years. It helps to plan services.'],
          ['Net migration:', 'Net migration = immigrants − emigrants. A town receiving 5,000 and losing 2,000 has a net gain of 3,000.']],
        draw: { img: 'projection_big.png', caption: 'population projection and doubling time' } },
    ],
    hwAnswer: 'Cameroon (approximate): CBR 35‰, CDR 9‰; natural increase = (35 − 9) ÷ 10 = 2.6 %; doubling time = 70 ÷ 2.6 ≈ 27 years.',
  },
  'Lesson 10': {
    secs: ['1. THE FACTORS', '2. FACTORS OF FERTILITY: EDUCATION', '2. FACTORS OF FERTILITY: ECONOMY', '3. FACTORS OF MORTALITY', '3. FACTORS OF MORTALITY'],
    action: 'Promote education and health to manage population growth.',
    summary: [
      D([['Factors of population growth:', 'They are the social, economic, cultural and political conditions that influence fertility, mortality and migration.']]),
      { title: '1. Factors Influencing Fertility', intro: 'Fertility is influenced by the following factors:',
        items: [['Social and cultural factors:', 'Early marriage, polygamy, religion and the value placed on large families raise fertility. Education of girls delays marriage and lowers fertility.'],
          ['Economic factors:', 'In farming societies children are a source of labour and security in old age. In towns and rich countries, children are costly, so families are smaller.'],
          ['Health and policy factors:', 'Access to contraception and family planning lowers fertility. High infant mortality pushes parents to have more children.']],
        draw: { img: 'growth_factors_big.png', caption: 'factors of population growth' } },
      { title: '2. Factors Influencing Mortality', intro: 'Mortality is influenced by the following factors:',
        items: [['Health and hygiene:', 'Vaccines, clean water, sanitation and hospitals reduce deaths. Diseases such as malaria and HIV still kill many in Africa.'],
          ['Food and income:', 'Good nutrition and higher incomes increase life expectancy. Famine and poverty increase deaths.'],
          ['Wars and disasters:', 'Conflicts, accidents and natural disasters increase mortality. They explain high death rates in some regions.']] },
      { title: '3. Regional Differences', intro: 'These factors explain regional differences:',
        items: [['Africa:', 'High fertility and falling mortality give the fastest growth. Education and urbanisation are slowly lowering fertility.'],
          ['Europe and East Asia:', 'Low fertility and long life expectancy give slow growth and ageing. Some countries depend on immigration.']] },
    ],
    hwAnswer: 'Grandparents often had 8–10 children, parents 4–6. The change is due to education, the cost of schooling and life in town, better health care (fewer child deaths) and family planning.',
  },
  'Lesson 11': {
    secs: ['1. CAUSES', '2. CONSEQUENCES', '3. B) ANTI-NATAL POLICIES', '3. C) MIGRATION LAWS', '3. A) PRO-NATAL POLICIES'],
    action: 'Debate and manage population growth through appropriate policies.',
    summary: [
      D([['Demographic explosion:', 'It is the very rapid growth of world population after 1950.'], ['Population policy:', 'It is a set of measures taken by a government to influence population growth or distribution.']]),
      { title: '1. Causes and Consequences', intro: 'The demographic explosion has the following causes and consequences:',
        items: [['Causes:', 'Death rates fell quickly thanks to vaccines, antibiotics and clean water, while birth rates stayed high. Improved food supply also helped.'],
          ['Consequences:', 'Rapid growth increases pressure on land, food, water, schools and jobs. It can cause unemployment, urban slums and environmental damage.']] },
      { title: '2. Managing Population Growth', intro: 'Countries manage growth with the following policies:',
        items: [['Pro-natal policies:', 'They encourage births with family allowances, tax cuts and parental leave. France and Russia use them because of ageing.'],
          ['Anti-natal policies:', 'They reduce births through family planning and incentives. China\'s one-child policy (1979–2015) slowed growth but caused ageing and a male surplus.'],
          ['Migration laws:', 'The USA has restrictive laws with quotas and border controls. Canada has relaxed laws with a points system to attract skilled migrants.']],
        draw: { img: 'policies_big.png', caption: 'population policies' } },
    ],
    hwAnswer: 'For a policy: rapid growth strains schools, health and jobs; family planning and girls\' education would help. Against a strong anti-natal policy: children are valued, and a young population is a future workforce.',
  },
  'Lesson 12': {
    secs: ['1. MEANING AND STAGES', '2. STAGES TODAY', '2. LINK WITH ROSTOW\'S MODEL', '4. APPLICATION TO CAMEROON', '3. APPRAISAL'],
    action: 'Use the DTM to understand and plan the demographic future of Cameroon.',
    summary: [
      { title: '1. Meaning of the DTM', intro: 'The Demographic Transition Model can be understood as follows:',
        items: [['Demographic transition:', 'It is the change from high birth and death rates to low birth and death rates as a country develops. The model is based on the history of Europe.']],
        draw: { img: 'dtm_big.png', caption: 'the Demographic Transition Model' } },
      { title: '2. Stages of the Model', intro: 'The model has four (or five) stages:',
        items: [['Stage 1 (high stationary):', 'Birth and death rates are both high, so growth is slow. It corresponds to traditional societies (Rostow\'s traditional stage).'],
          ['Stage 2 (early expanding):', 'Death rates fall quickly with better food and health, but birth rates stay high. Growth is very rapid, as in Niger.'],
          ['Stage 3 (late expanding):', 'Birth rates fall with education, urbanisation and family planning. Growth slows; Cameroon and India are in this stage (Rostow\'s take-off and drive to maturity).'],
          ['Stages 4 and 5 (low stationary and declining):', 'Birth and death rates are low and growth is almost zero or negative. MEDCs such as France and Japan are here (Rostow\'s high mass consumption).']] },
      { title: '3. Appraisal and Application to Cameroon', intro: 'The model is evaluated and applied as follows:',
        items: [['Strengths:', 'It is simple, universal and helps to compare countries and predict change. It links population to economic development.'],
          ['Weaknesses:', 'It is based on Europe and does not consider migration or AIDS. LEDCs may not follow the same path or timing.'],
          ['Application to Cameroon:', 'Cameroon is in late stage 2 or early stage 3, with CBR about 35‰ and CDR about 9‰. Growth remains fast, but fertility is slowly falling in towns.']],
        draw: { img: 'cmr_rates_big.png', caption: 'birth and death rates of Cameroon' } },
    ],
    hwAnswer: 'Niger – stage 2 (high births, falling deaths); Cameroon – late stage 2/early stage 3; France – stage 4; Japan – stage 5 (declining).',
  },
  'Lesson 13': {
    secs: ['1. MEANING AND CHARACTERISTICS', '2. ZIPF\'S INVERSE DISTANCE LAW', '2. THE GRAVITY MODEL', '2. STOUFFER\'S MODEL', '3. CALCULATIONS'],
    action: 'Explain migration flows using laws and models.',
    summary: [
      { title: '1. Meaning and Characteristics of Migration', intro: 'Migration can be understood as follows:',
        items: [['Migration:', 'It is the movement of people from one place to another to live there for a long time, usually more than a year. Daily trips to school are circulation, not migration.'],
          ['Migration differentials:', 'Migrants are often young adults, males in the first stages, and more educated than those who stay. The volume of migration varies with distance, opportunities and obstacles.']] },
      { title: '2. Laws and Theories of Migration', intro: 'Migration is explained by the following laws and models:',
        items: [['Zipf\'s inverse distance law:', 'The number of migrants decreases as distance increases. Most people move over short distances.'],
          ['The gravity model:', 'Interaction between two towns is proportional to the product of their populations divided by the square of the distance. Large, close towns interact most.'],
          ['Stouffer\'s intervening opportunities:', 'Migration depends on the opportunities between origin and destination, not only on distance. Migrants may stop at a closer town that offers jobs.']],
        draw: { img: 'gravity_big.png', caption: 'the gravity model' } },
      { title: '3. Calculations Based on Models', intro: 'The gravity model is calculated as follows:',
        items: [['Formula:', 'I = (P1 × P2) ÷ d². P1 and P2 are the populations and d the distance.'],
          ['Example:', 'Town A 100,000, town B 400,000, distance 200 km: I = (100,000 × 400,000) ÷ 40,000 = 1,000,000. The value is compared with other pairs of towns.']] },
    ],
    hwAnswer: 'Douala (3.9 M) – Yaoundé (4.1 M), 240 km: I = (3.9 × 4.1) ÷ 240² ≈ 0.00028; Douala – Garoua (0.9 M), about 1,000 km: I = (3.9 × 0.9) ÷ 1,000² ≈ 0.0000035. Douala–Yaoundé interaction is about 80 times stronger.',
  },
  'Lesson 14': {
    secs: ['1. MEANING', '2. FACTORS: COMPLEMENTARITY', '2. FACTORS: TRANSFERABILITY', '2. FACTORS: INFORMATION', '2. OTHER FACTORS'],
    action: 'Improve links between regions to encourage trade and exchange.',
    summary: [
      { title: '1. Meaning of Spatial Interaction', intro: 'Spatial interaction can be understood as follows:',
        items: [['Spatial interaction:', 'It is the movement of people, goods, money and information between places. Examples are migration, trade, commuting and phone calls.']],
        draw: { img: 'ullman_big.png', caption: 'Ullman\'s bases of interaction' } },
      { title: '2. Factors of Spatial Interaction', intro: 'Ullman identified three main factors:',
        items: [['Complementarity:', 'One place has a surplus of something that another place needs. Cattle from the North are sent to the South, and manufactured goods go North.'],
          ['Transferability:', 'Goods and people can move only if transport costs and time are acceptable. The railway and good roads increase interaction.'],
          ['Intervening opportunity:', 'A closer source of the same good reduces interaction with a distant place. Buyers go to the nearest market that has the product.']] },
      { title: '2. Factors of Spatial Interaction', sub: 'Other Factors', intro: 'Other factors also affect interaction:',
        items: [['Information and communication:', 'Phones, radio and the internet spread information about opportunities. They increase migration and trade.'],
          ['Barriers:', 'Distance, borders, language, insecurity and bad roads reduce interaction. Political decisions such as border closures stop exchanges.']] },
    ],
    hwAnswer: 'Examples: onions and cattle come from the North; plantains, palm oil and kola nuts from the South and West; manufactured goods from Douala. This is due to complementarity between regions.',
  },
  'Lesson 15': {
    secs: ['1. VOLUNTARY AND FORCED MIGRATION', '2. INTERNAL MIGRATION', '3. INTERNATIONAL MIGRATION', '4. FORCED MIGRATION', '5. CONSEQUENCES'],
    action: 'Manage migration so that it benefits both source and destination areas.',
    summary: [
      D([['Push factors:', 'They are the negative conditions that make people leave a place.'], ['Pull factors:', 'They are the attractive conditions that draw people to a place.']]),
      { title: '1. Voluntary Internal Migration', intro: 'The main types of internal migration are:',
        items: [['Rural–urban migration:', 'People move from villages to towns, pushed by poverty and poor services and pulled by jobs and schools. It is the main type in Cameroon (to Douala and Yaoundé).'],
          ['Rural–rural and urban–rural migration:', 'Farmers move to new farmland, as in the Mungo or around Lagdo. Retired people and some workers return to villages.'],
          ['Intra-urban, inter-urban migration and commuting:', 'People move within or between towns for housing and jobs. Commuting is a daily movement between home and work.']] },
      { title: '2. International and Forced Migration', intro: 'Other forms of migration are:',
        items: [['Economic migrants:', 'They move abroad for jobs and higher incomes, for example from Cameroon to Europe or Gabon. They send money (remittances) home.'],
          ['Political migrants and refugees:', 'Refugees flee persecution or war across borders, like those from the Central African Republic in eastern Cameroon. They live in camps such as Gado.'],
          ['Internally displaced persons (IDPs):', 'They flee violence but remain inside their country. The crises in the Far North and the North-West and South-West regions displaced many people.']],
        draw: { img: 'migration_types_big.png', caption: 'types of migration' } },
      { title: '3. Consequences of Migration', intro: 'Migration has consequences for source and destination areas:',
        items: [['At the source:', 'Positive: remittances and less pressure on land. Negative: loss of young workers, ageing villages and brain drain.'],
          ['At the destination:', 'Positive: labour and skills for the economy. Negative: overcrowding, slums, unemployment and pressure on services.']],
        draw: { img: 'cmr_migration_big.png', caption: 'migration flows in Cameroon' } },
    ],
    hwAnswer: 'Push factors (village): poverty, lack of jobs, poor schools and hospitals, small farms. Pull factors (town): jobs, schools, hospitals, electricity, entertainment.',
  },
  'Lesson 16': {
    secs: ['1. MEANING', '1. MEANING', '2. ADJUSTING: TECHNOLOGY', '2. ADJUSTING: OTHER WAYS', '3. POPULATION–RESOURCES REGIMES'],
    action: 'Raise the carrying capacity of our land through sustainable techniques.',
    summary: [
      { title: '1. Meaning of Carrying Capacity', intro: 'Carrying capacity can be understood as follows:',
        items: [['Carrying capacity:', 'It is the maximum number of people (or animals) that an area can support with its resources without damaging the environment.'],
          ['Overshoot:', 'When the population goes beyond the carrying capacity, resources are overused. Overgrazing, soil erosion and famine follow.']],
        draw: { img: 'carrying_big.png', caption: 'carrying capacity' } },
      { title: '2. Ways of Adjusting Resources to Carrying Capacity', intro: 'People adjust to carrying capacity in the following ways:',
        items: [['Raising resources:', 'Irrigation, fertilisers, improved seeds and new technology increase production. Irrigation schemes at Maga and Lagdo raise the capacity of the North.'],
          ['Reducing demand:', 'Family planning, migration and controlled grazing reduce pressure on land. People move to less crowded areas.'],
          ['Trade and conservation:', 'Importing food and protecting resources extend carrying capacity. Soil conservation keeps land productive.']] },
      { title: '3. Population–Resources Regimes', intro: 'Zelinsky identified the following regimes:',
        items: [['U.S. type (technological source area):', 'Few people, rich resources and high technology give high living standards. The USA and Australia are examples.'],
          ['European and Egyptian types:', 'In the European type, many people and limited resources are balanced by technology and trade. In the Egyptian type, many people and limited resources with low technology give poverty.'],
          ['Brazilian and Arctic-desert types:', 'The Brazilian type has few people, rich resources but low technology. The Arctic-desert type has few people and poor resources.']],
        draw: { img: 'regimes_big.png', caption: 'population–resources regimes' } },
    ],
    hwAnswer: 'In our area, carrying capacity could be raised by irrigation from the Benue, using manure and improved seeds, soil conservation, controlled grazing and tree planting.',
  },
  'Lesson 17': {
    secs: ['1. THE CONCEPTS', '2. OVERPOPULATION: INDICATORS', '2. OVERPOPULATION: CONSEQUENCES', '3. UNDERPOPULATION', '4. SOLUTIONS'],
    action: 'Identify population–resource imbalances and propose solutions.',
    summary: [
      { title: '1. Meaning of the Concepts', intro: 'The main concepts can be understood as follows:',
        items: [['Overpopulation:', 'It is a situation where there are too many people for the resources and technology available, so living standards fall.'],
          ['Underpopulation:', 'It is a situation where there are too few people to use the resources fully and efficiently.'],
          ['Optimum population:', 'It is the number of people that gives the highest standard of living with the available resources and technology. It changes when technology changes.']],
        draw: { img: 'optimum_big.png', caption: 'optimum population' } },
      { title: '2. Overpopulation', intro: 'Overpopulation can be studied as follows:',
        items: [['Indicators and measurement:', 'High unemployment, malnutrition, slums, landlessness and very high physiological density indicate overpopulation. It is measured by comparing population with resources and GNI per person.'],
          ['Causes:', 'Rapid population growth and limited resources or technology cause it. Examples are Bangladesh, the Sahel and parts of the Mandara Mountains.'],
          ['Consequences and solutions:', 'It leads to poverty, migration and environmental damage such as soil erosion. Solutions are family planning, intensification of agriculture, industrialisation and migration.']] },
      { title: '3. Underpopulation', intro: 'Underpopulation can be studied as follows:',
        items: [['Indicators and causes:', 'Resources are unused, labour is scarce and markets are small. Causes are low birth rates, emigration or very large territories, as in Australia, Canada and the East Region of Cameroon.'],
          ['Consequences and solutions:', 'Development is slow, and services are expensive for scattered people. Solutions are encouraging immigration, pro-natal policies and better transport.']] },
    ],
    hwAnswer: 'Cameroon as a whole is closer to underpopulation (rich resources, 59 people/km²), but some areas such as the Mandara Mountains and the Western Highlands show signs of overpopulation (land shortage, erosion, migration).',
  },
  'Lesson 18': {
    secs: ['1. MALTHUS\'S THEORY', '1. MALTHUS\'S THEORY', '2. BOSERUP\'S THEORY', '2. BOSERUP\'S THEORY', '3. STRENGTHS AND WEAKNESSES'],
    action: 'Evaluate theories of population and resources and apply them to Cameroon.',
    summary: [
      { title: '1. General Views on Population and Resources', intro: 'There are two main views:',
        items: [['Pessimistic view:', 'Population growth is a threat because resources are limited. Growth leads to famine and poverty.'],
          ['Optimistic view:', 'Population growth stimulates technology and development. People are a resource that creates new solutions.']] },
      { title: '2. Malthus\'s Theory (1798)', intro: 'Thomas Malthus stated that:',
        items: [['Main idea:', 'Population grows geometrically (1, 2, 4, 8…) while food grows arithmetically (1, 2, 3, 4…). Population will therefore outgrow food.'],
          ['Checks:', 'Positive checks (famine, disease, war) raise deaths. Preventive checks (late marriage, abstinence) lower births.'],
          ['Strengths and weaknesses:', 'Famines in the Sahel and Ethiopia seem to support him. But he underestimated technology, trade and the fall in birth rates.']],
        draw: { img: 'malthus_big.png', caption: 'Malthus\'s theory' } },
      { title: '3. Boserup\'s Theory (1965)', intro: 'Ester Boserup stated that:',
        items: [['Main idea:', '"Necessity is the mother of invention": population pressure forces people to intensify farming. Fallow is shortened and new techniques are adopted.'],
          ['Examples:', 'Terraces in the Mandara Mountains and irrigation in Asia increased food production. The Green Revolution supports her view.'],
          ['Strengths and weaknesses:', 'It explains intensification in crowded areas. But it ignores environmental limits and societies that cannot innovate fast enough.']],
        draw: { img: 'boserup_big.png', caption: 'Boserup\'s theory' } },
    ],
    hwAnswer: 'For: rapid growth strains land, schools, jobs and forests (Malthus). Against: a growing population is a larger workforce and market, and pressure encourages innovation such as irrigation and terraces (Boserup).',
  },
  'Further Study 1': {
    secs: ['1. POPULATION GROWTH', '1. POPULATION STRUCTURE', '2. POPULATION DISTRIBUTION', '3. MIGRATION', '3. EFFECTS OF MIGRATION'],
    action: 'Plan the development of Cameroon according to its population trends.',
    summary: [
      { title: '1. Population Growth and Structure', intro: 'The population of Cameroon has changed as follows:',
        items: [['Growth:', 'The population rose from 7.7 million in 1976 to 17.5 million in 2005 and about 28 million today. The growth rate is about 2.6 % per year.'],
          ['Structure:', 'The population is youthful, with about 42 % under 15, and the pyramid is expansive. The dependency ratio is high.']],
        draw: { img: 'cmr_growth_big.png', caption: 'growth of the population of Cameroon' } },
      { title: '2. Population Distribution', intro: 'The population of Cameroon is unevenly distributed:',
        items: [['Densely populated areas:', 'The Littoral, West, North-West and Far North have over 100 people/km². They have fertile soils, towns, industries and old settlements.'],
          ['Sparsely populated areas:', 'The East, South and Adamawa have fewer than 25 people/km². Dense forest, poor soils and poor communications explain this.']],
        draw: { img: 'choropleth_big.png', caption: 'population density of Cameroon' } },
      { title: '3. Migration and its Effects', intro: 'Migration is an important factor of change in Cameroon:',
        items: [['Main flows:', 'Rural–urban migration goes towards Douala and Yaoundé, and migrants from the West go to the Littoral and Centre. Crises have displaced people from the Far North, North-West and South-West.'],
          ['Effects:', 'Towns grow fast, with slums and unemployment. Villages lose young workers, but receive remittances.']],
        draw: { img: 'cmr_migration_big.png', caption: 'migration flows in Cameroon' } },
    ],
    hwAnswer: 'The map shows dense regions (Littoral, West, North-West, Far North) and sparse regions (East, South, Adamawa), with arrows from the West, North and villages to Douala and Yaoundé.',
  },
};
