// v3 patches — USA Module 5: Settlement Geography
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
module.exports = {
  'Lesson 1': {
    secs: ['1. MEANING OF SETTLEMENT', '1. MEANING OF SETTLEMENT', '2. EVOLUTION OF SETTLEMENT', '3. FACTORS OF EARLY LOCATION', '3. FACTORS OF EARLY LOCATION'],
    action: 'Understand why settlements were founded where they are, to plan new ones wisely.',
    summary: [
      { title: '1. Meaning of Settlement', intro: 'A settlement can be understood as follows:',
        items: [['Settlement:', 'It is a place where people live, with houses and the activities linked to them, from a single hut to a large city.'],
          ['Permanent and temporary settlements:', 'Permanent settlements are occupied all year, like villages and towns. Temporary ones are used for a season, like nomad camps and fishing camps.']] },
      { title: '2. Evolution of Settlement', intro: 'Settlements evolved as follows:',
        items: [['Early settlements:', 'Hunters and gatherers lived in temporary camps. The development of farming about 10,000 years ago led to permanent villages.'],
          ['Growth into towns and cities:', 'Surplus food, trade and crafts allowed villages to grow into towns. The Industrial Revolution made cities grow very fast.']],
        draw: { img: 'evolution_big.png', caption: 'from hamlet to city' } },
      { title: '3. Factors Affecting the Location of Early Settlements', intro: 'Early settlements were located according to:',
        items: [['Water supply and drainage:', 'People settled near springs, rivers and wells, but above flood level. Wet-point sites were common in dry areas.'],
          ['Resources and relief:', 'Fertile soils, forests, fish and minerals attracted people. Gentle slopes and flat land were easier to build on.'],
          ['Defence and routes:', 'Hill tops, river bends and islands were easy to defend. Route junctions, fords and bridging points favoured trade.']],
        draw: { img: 'site_types_big.png', caption: 'types of early settlement sites' } },
    ],
    hwAnswer: 'Example: the elder explained that the village was founded near a permanent spring, on a hill that was easy to defend, with fertile land around it.',
  },
  'Lesson 2': {
    secs: ['1. SITE AND SITUATION', '2. TYPES OF SITE', '2. TYPES OF SITE', '3. EXAMPLES OF SITUATION', '3. EXAMPLES OF SITE'],
    action: 'Describe the site and situation of towns to understand their growth.',
    summary: [
      D([['Site:', 'It is the actual land on which a settlement is built, with its relief, soil and water.'], ['Situation:', 'It is the position of a settlement in relation to the surrounding area, routes and other settlements.']]),
      { title: '1. Examples of Sites', intro: 'Common types of sites are:',
        items: [['Wet-point and dry-point sites:', 'Wet-point sites are near water in dry regions, like oasis towns. Dry-point sites are raised above marshes or floods.'],
          ['Defensive sites:', 'They are on hills, in river meanders or on islands, like medieval hill towns. They were easy to protect from enemies.'],
          ['Bridging points and gap towns:', 'Bridging points grow where a river can be crossed. Gap towns grow in valleys through mountains.']],
        draw: { img: 'site_types_big.png', caption: 'types of site' } },
      { title: '2. Examples of Situation', intro: 'A good situation helps a settlement to grow:',
        items: [['Douala:', 'It is on the Wouri estuary, near the sea, at the start of the railway and roads to the interior. This situation made it the economic capital and main port.'],
          ['Bamenda and Yaoundé:', 'Bamenda sits on a plateau below an escarpment at a route centre of the North-West. Yaoundé lies on hills at the centre of the country, a good situation for a capital.']],
        draw: { img: 'site_situation_big.png', caption: 'site and situation' } },
      { title: '3. Factors of Settlement Site', intro: 'The choice of a site depends on:',
        items: [['Physical factors:', 'Water supply, relief, drainage, soils and building materials were the main factors. Flood-free, gentle land was preferred.'],
          ['Human factors:', 'Defence, routes, trade and political decisions also mattered. Modern sites depend more on roads, industries and planning.']] },
    ],
    hwAnswer: 'Example: Garoua – site: on the right bank of the Benue, on flat land near the river; situation: at the crossroads of routes to Ngaoundéré, Maroua and Nigeria, with a river port.',
  },
  'Lesson 3': {
    secs: ['1. MEANING', '2. TYPES', '2. TYPES', '3. SIZE: FACTORS', '3. SIZE: FACTORS'],
    action: 'Plan services according to the size and type of rural settlements.',
    summary: [
      { title: '1. Meaning and Types of Rural Settlement', intro: 'Rural settlement can be understood as follows:',
        items: [['Rural settlement:', 'It is a settlement whose people depend mainly on primary activities such as farming, fishing and herding.'],
          ['Types:', 'Rural settlements are isolated dwellings, hamlets and villages. In Cameroon they include compounds, Grassfields villages with chiefdoms, and herders\' camps.']],
        draw: { img: 'hierarchy_big.png', caption: 'rural settlement types' } },
      { title: '2. Size of Rural Settlements', intro: 'Size and its factors can be explained as follows:',
        items: [['Meaning of size:', 'Size is measured by the number of people, houses or the area covered. A hamlet has a few houses; a village has hundreds of people and some services.'],
          ['Physical factors:', 'Water supply, soil fertility and relief limit how many people can live in one place. Large villages grow near reliable water.'],
          ['Human factors:', 'Farming system, land tenure, security and services affect size. Herders\' settlements are small and scattered, while farming villages with markets are larger.']] },
    ],
    hwAnswer: 'Example: the neighbourhood has about 80 houses and services such as a primary school, a church, a mosque, a borehole and a small market.',
  },
  'Lesson 4': {
    secs: ['1. FORMS: UNSTABLE', '2. SHAPES', '2. SHAPES', '1. FORMS: PLANNED', '1. FORMS: SPONTANEOUS'],
    action: 'Recognise settlement forms and shapes and encourage planned growth.',
    summary: [
      { title: '1. Settlement Forms', intro: 'Settlements have the following forms:',
        items: [['Unstable forms:', 'They are temporary or moving settlements, such as nomad camps and shifting cultivators\' huts. They change place with seasons or resources.'],
          ['Stable spontaneous forms:', 'They grow without a plan, with irregular streets, as in old villages and slums. Houses are added as people arrive.'],
          ['Stable planned forms:', 'They are built according to a plan, with regular streets and plots, like new towns and estates. Services are organised.']] },
      { title: '2. Settlement Shapes', intro: 'The main shapes of settlements are:',
        items: [['Isolated dwellings and compact shapes:', 'An isolated dwelling stands alone on its farm. A compact settlement has houses close together around a centre, like walled towns.'],
          ['Loose-knit and linear shapes:', 'Loose-knit settlements have houses spread out with spaces between them. Linear settlements stretch along a road, river or ridge.'],
          ['T, cross, ring, planned and composite shapes:', 'T and cross shapes grow at road junctions, and ring shapes surround a central space. Composite shapes mix several forms.']],
        draw: { img: 'shapes_big.png', caption: 'settlement shapes' } },
    ],
    hwAnswer: 'Example: our quarter is linear, stretched along the main road, with a small cluster at the junction near the market.',
  },
  'Lesson 5': {
    secs: ['2. SETTLEMENT PATTERN: TYPES', '2. PATTERN: DISPERSED', '2. PATTERN: NUCLEATED', '1. DISTRIBUTION: LINEAR', '3. CHANGES OVER TIME'],
    action: 'Explain settlement patterns and plan rural development.',
    summary: [
      { title: '1. Settlement Distribution', intro: 'Settlement distribution can be studied as follows:',
        items: [['Meaning:', 'It is the way settlements are spread over an area. It shows where people have chosen to live.'],
          ['Types:', 'Distribution can be dense, sparse, clustered, clustered-linear, regular or random. Dense distributions are found on fertile plains.'],
          ['Factors:', 'Relief, water, soils, roads and history affect distribution. Swamps and steep slopes have few settlements.']] },
      { title: '2. Settlement Pattern', intro: 'Settlement pattern can be studied as follows:',
        items: [['Meaning and types:', 'Pattern is the arrangement of houses within an area. It can be nucleated (compact), intercalary, dispersed or planned.'],
          ['Nucleated pattern:', 'Houses are grouped together for defence, water supply, communal farming or social life. It is common in the Far North and in Muslim towns.'],
          ['Dispersed pattern:', 'Houses are scattered on their farms, where water is widespread and land is owned by families. It is typical of the Western Highlands.']],
        draw: { img: 'patterns_big.png', caption: 'settlement patterns' } },
      { title: '3. Changes of Rural Patterns over Time', intro: 'Rural patterns in Cameroon have changed as follows:',
        items: [['Colonial and post-colonial changes:', 'Villages were regrouped along roads for administration and tax collection. Plantations created new camps and linear villages.'],
          ['Recent changes:', 'Roads, markets and services attract houses into linear patterns. Insecurity has regrouped some villages into compact settlements.']] },
    ],
    hwAnswer: 'Example: in the area studied, settlements are nucleated along the river and linear along the main road, while the hills are almost empty.',
  },
  'Practical Work 1': {
    secs: ['1. THE FORMULA', '2. METHOD', '3. CALCULATION', '4. INTERPRETATION', '5. IMPORTANCE AND LIMITATIONS'],
    action: 'Measure settlement patterns objectively with the nearest neighbour index.',
    summary: [
      { title: '1. Meaning and Formula', intro: 'The Nearest Neighbour Index can be understood as follows:',
        items: [['Nearest Neighbour Index (Rn):', 'It is a statistical measure that shows whether a settlement pattern is clustered, random or regular.'],
          ['Formula:', 'Rn = 2 d̄ √(n ÷ A), where d̄ is the mean distance to the nearest neighbour, n the number of settlements and A the area. Distances and area must be in the same units.']] },
      { title: '2. Method and Calculation', intro: 'Rn is calculated as follows:',
        items: [['Method:', 'Number the settlements, measure the distance from each to its nearest neighbour, and find the mean d̄. Count n and measure the area A.'],
          ['Example:', '15 villages in 60 km² with d̄ = 1.0 km: Rn = 2 × 1.0 × √(15 ÷ 60) = 2 × 0.5 = 1.0. The pattern is random.']],
        draw: { img: 'nna_map_big.png', caption: 'measuring nearest neighbours' } },
      { title: '3. Interpretation, Importance and Limitations', intro: 'The result is interpreted and assessed as follows:',
        items: [['Interpretation scale:', 'Rn = 0 is completely clustered, 1.0 random and 2.15 perfectly regular. Values below 1 show clustering and above 1 show dispersal.'],
          ['Importance:', 'It gives an objective, comparable measure of patterns. It helps to test hypotheses about settlement.'],
          ['Limitations:', 'It ignores the size of settlements and the boundary of the area chosen. Two different patterns can give the same value.']],
        draw: { img: 'nna_scale_big.png', caption: 'the Rn scale' } },
    ],
    hwAnswer: 'Example: 10 settlements, area 25 km², mean distance 0.8 km: Rn = 2 × 0.8 × √(10 ÷ 25) = 1.6 × 0.63 ≈ 1.01, a random pattern.',
  },
  'Lesson 6': {
    secs: ['1. FORM', '2. NATURE OF BUILDINGS: MATERIALS', '2. NATURE OF BUILDINGS: STYLES', '2. NATURE OF BUILDINGS: ADAPTATION', '3. OCCUPATION'],
    action: 'Value traditional architecture adapted to the local environment.',
    summary: [
      D([['Immediate physical environment:', 'It is the relief, climate, water, soils and vegetation around a settlement.']]),
      { title: '1. The Physical Environment and Settlement', intro: 'The environment influences rural settlements as follows:',
        items: [['Form:', 'Relief and water decide whether settlements are compact or scattered. Steep slopes give scattered compounds, and flood plains give raised or stilt settlements.'],
          ['Building materials:', 'People use local materials: wood and raffia in the forest, mud and thatch in the savanna, stone in the mountains. Nomads use light tents and mats.'],
          ['Building styles:', 'Steep roofs shed heavy rain in the south, thick mud walls keep houses cool in the north, and stilts protect from floods. Grassfields houses have square walls and conical roofs.'],
          ['Occupation:', 'The environment decides the main activity: farming in fertile areas, herding in grasslands and fishing on coasts and lakes. The settlement is organised around this activity.']] },
    ],
    hwAnswer: 'Example: in the North, traditional houses are round, with thick mud walls and grass thatch; mud keeps them cool, and grass is available locally and easy to replace.',
  },
  'Lesson 7': {
    secs: ['1. CHANGES IN SIZE', '1. CHANGES IN FORM', '1. CHANGES IN FUNCTION', '2. RESULTANT PROBLEMS', '3. PLANNING'],
    action: 'Plan rural development to reduce the problems of changing villages.',
    summary: [
      { title: '1. Changes in Rural Settlements', intro: 'Rural settlements change in the following ways:',
        items: [['Size:', 'Villages near towns and roads grow, while remote villages lose young people. Some become towns, others are abandoned.'],
          ['Form:', 'Modern houses with blocks and iron sheets replace mud and thatch. Settlements stretch along roads.'],
          ['Function:', 'Villages near towns add markets, shops, schools and commuting. Farming becomes commercial and services grow.']] },
      { title: '2. Resultant Problems and Planning', intro: 'These changes cause problems that need planning:',
        items: [['Problems:', 'Rural exodus leaves old people and poor services. Land disputes, poor roads, lack of water and loss of traditions follow.'],
          ['Planning:', 'Governments and communities provide boreholes, schools, health centres, electricity and roads. Rural development projects and land-use plans reduce exodus.']] },
    ],
    hwAnswer: 'Example: 30 years ago the village had mud houses, no road and no school; today it has block houses, a road, a primary school and a borehole, but many young people have left for town.',
  },
  'Lesson 8': {
    secs: ['1. MEANING', '2. CHARACTERISTICS', '2. CHARACTERISTICS', '3. CHALLENGES', '3. CHALLENGES: SOLUTIONS'],
    action: 'Manage the urban fringe to protect farmland and control sprawl.',
    summary: [
      { title: '1. Meaning of the Urban Fringe', intro: 'The urban fringe can be understood as follows:',
        items: [['Urban (rural–urban) fringe:', 'It is the zone at the edge of a town where urban and rural land uses mix. It is a zone of transition and rapid change.']],
        draw: { img: 'cbd_zones_big.png', caption: 'location of the urban fringe' } },
      { title: '2. Characteristics', intro: 'The urban fringe has the following characteristics:',
        items: [['Mixed land use:', 'New housing estates, factories, dumps, cemeteries and airports mix with farms. Large land users move there because land is cheap.'],
          ['Market gardening and commuting:', 'Farmers grow vegetables and keep poultry for the town market. Many residents commute to work in the town.']] },
      { title: '3. Challenges', intro: 'The urban fringe faces the following challenges:',
        items: [['Problems:', 'Farmland is lost to building, land prices rise and illegal settlements grow. Pollution, poor services and land disputes are common.'],
          ['Solutions:', 'Planners create green belts, land-use zoning and planned estates. Services should be extended before settlement.']],
        draw: { img: 'sprawl_control_big.png', caption: 'controlling the fringe' } },
    ],
    hwAnswer: 'Example: at the edge of town there are new houses under construction, maize and vegetable farms, a rubbish dump, a school and a brick factory.',
  },
  'Lesson 9': {
    secs: ['1. CRITERIA', '1. POPULATION NUMBERS', '1. FUNCTIONS', '1. SOCIOLOGICAL CHARACTERISTICS', '2. CRITICAL ANALYSIS'],
    action: 'Distinguish rural and urban areas to plan services appropriately.',
    summary: [
      { title: '1. Criteria for Differentiating Rural and Urban Settlements', intro: 'Settlements are classified using the following criteria:',
        items: [['Population composition and numbers:', 'Towns have many people and high densities; the minimum varies from 2,500 (USA) to 5,000 (Cameroon). Towns have more young adults and migrants.'],
          ['Sociological characteristics:', 'Rural life is based on family ties and tradition, while urban life is more individual and varied. Townspeople have more education and contacts.'],
          ['Land use and morphology:', 'Rural land is mainly farms and scattered houses; urban land is continuously built with streets. Towns have tall buildings and a CBD.'],
          ['Functions:', 'Rural settlements have primary functions (farming, fishing). Towns have secondary and tertiary functions: industry, trade, administration and services.']],
        draw: { img: 'rural_urban_big.png', caption: 'criteria of rural and urban settlements' } },
      { title: '2. Critical Analysis', intro: 'These criteria have limits:',
        items: [['Different definitions:', 'Each country uses a different population threshold, so comparisons are difficult. Some large villages are bigger than small towns.'],
          ['Rural–urban continuum:', 'There is no sharp break but a gradual change from village to city. Many settlements in the fringe have both rural and urban features.']] },
    ],
    hwAnswer: 'Village: few people, farming, family life, no tarred roads. Town: many people, trade and offices, more individual life, tarred roads and electricity.',
  },
  'Lesson 10': {
    secs: ['1. MEANING', '2. CLASSIFICATION INTO TYPES', '2. CLASSIFICATION INTO TYPES', '3. ORIGIN', '3. EVOLUTION'],
    action: 'Understand the origin and functions of towns to plan their development.',
    summary: [
      { title: '1. Meaning of Urban Settlement', intro: 'An urban settlement can be understood as follows:',
        items: [['Urban settlement:', 'It is a large, dense settlement whose people work mainly in industry, trade and services rather than in farming.']] },
      { title: '2. Classification into Types', intro: 'Towns are classified by their main function:',
        items: [['Administrative and commercial towns:', 'Administrative towns are seats of government, like Yaoundé. Commercial towns are centres of trade, like Douala and Kousseri.'],
          ['Industrial, mining and port towns:', 'Industrial towns grow around factories (Edéa), mining towns around mines (Johannesburg). Port towns handle shipping (Douala, Kribi).'],
          ['Other types:', 'There are tourist towns (Limbe), religious towns (Mecca) and university towns (Buea). Most large towns are multi-functional.']] },
      { title: '3. Origin and Evolution of Towns', intro: 'Towns originated and evolved as follows:',
        items: [['Origin:', 'The first towns appeared about 5,000 years ago in Mesopotamia, Egypt and the Indus valley, where farming produced a surplus. They grew around temples, markets and palaces.'],
          ['Evolution:', 'Medieval towns grew around castles and markets; the Industrial Revolution made cities grow very fast. In Africa, many towns grew from colonial posts, ports and railway stations.']],
        draw: { img: 'evolution_big.png', caption: 'evolution of settlements' } },
    ],
    hwAnswer: 'Yaoundé – administrative; Douala – port and commercial; Edéa – industrial (aluminium); Limbe – tourist and industrial (oil refinery); Ngaoundéré – railway and commercial.',
  },
  'Lesson 11': {
    secs: ['1. MEANING AND DIFFERENCES IN RATES', '2. CAUSES', '3. ADVANTAGES', '4. DISADVANTAGES (URBAN PROBLEMS)', '5. SOLUTIONS'],
    action: 'Manage urban growth to reduce urban problems.',
    summary: [
      { title: '1. Meaning, History and Rates of Urbanisation', intro: 'Urbanisation can be understood as follows:',
        items: [['Urbanisation:', 'It is the increase in the proportion of a population living in towns.'],
          ['Brief history:', 'In 1800 only about 3 % of people lived in towns; the world passed 50 % urban in 2007. Europe urbanised first with the Industrial Revolution.'],
          ['Differences between MEDCs and LEDCs:', 'MEDCs are about 80 % urban and grow slowly. LEDCs are less urban (Cameroon about 58 %) but urbanise very fast.']],
        draw: { img: 'urban_pct_big.png', caption: 'urbanisation in MEDCs and LEDCs' } },
      { title: '2. Causes of Urbanisation', intro: 'The causes differ between MEDCs and LEDCs:',
        items: [['In MEDCs:', 'Industrialisation created factory jobs in towns in the 19th century. Mechanisation of farming released rural workers.'],
          ['In LEDCs:', 'Rural–urban migration (push of poverty, pull of jobs, schools and services) and high natural increase in towns cause rapid growth. Insecurity also pushes people to towns.']] },
      { title: '3. Advantages, Problems and Solutions', intro: 'Urbanisation has positive and negative effects:',
        items: [['Advantages:', 'Towns offer jobs, schools, hospitals and markets and drive economic growth. Services are cheaper to provide to concentrated populations.'],
          ['Disadvantages (urban problems):', 'Rapid growth causes slums, unemployment, traffic jams, pollution, crime and floods. Water and electricity supply cannot keep up.'],
          ['Solutions:', 'Urban planning, site-and-service schemes, public transport and rural development reduce problems. Decentralisation develops smaller towns.']] },
    ],
    hwAnswer: 'Examples: traffic jams – build more roads and use buses; flooding – clean and enlarge drains; unemployment – support small businesses and vocational training.',
  },
  'Lesson 12': {
    secs: ['1. STAGES OF URBAN CHANGE', '2. SUBURBANISATION', '3. COUNTER-URBANISATION', '4. RE-URBANISATION', '5. CENTRIPETAL AND CENTRIFUGAL FORCES'],
    action: 'Recognise current urban trends in our towns and plan for them.',
    summary: [
      D([['Centripetal forces:', 'They are forces that attract people and activities to the city centre.'], ['Centrifugal forces:', 'They are forces that push people and activities away from the centre.']]),
      { title: '1. Current Trends in Urbanisation', intro: 'Towns in MEDCs have gone through the following trends:',
        items: [['Suburbanisation:', 'People and activities move from the inner city to the suburbs, helped by cars and cheaper land. It causes urban sprawl and commuting.'],
          ['Counter-urbanisation:', 'People move from cities to small towns and villages in search of a quieter life and cheaper houses. Telecommuting and retirement encourage it.'],
          ['Re-urbanisation:', 'People move back into renewed city centres to be near jobs and entertainment. Gentrification and regeneration schemes such as the London Docklands attract them.']],
        draw: { img: 'urban_cycle_big.png', caption: 'stages of urban change' } },
      { title: '2. Causes and Consequences', intro: 'These trends have causes and consequences:',
        items: [['Centripetal and centrifugal forces:', 'Jobs, services and accessibility attract people to the centre. Congestion, pollution, high rents and crime push them out.'],
          ['Consequences:', 'Suburbanisation empties inner cities and increases traffic. Re-urbanisation renews centres but may push poor residents out.']] },
    ],
    hwAnswer: 'In Garoua, suburbanisation is happening: new quarters grow on the edge of the town (e.g. along the Ngaoundéré road) because land is cheaper and the centre is crowded.',
  },
  'Lesson 13': {
    secs: ['1. MEANING AND TYPES', '2. SPATIAL DISTRIBUTION', '2. PROMINENT EXAMPLES', '3. CAUSES', '3. PROBLEMS'],
    action: 'Understand the growth of large urban regions and their challenges.',
    summary: [
      { title: '1. Meaning of Urban Regions', intro: 'The main urban regions are defined as follows:',
        items: [['Millionaire city:', 'It is a city with more than one million inhabitants. Douala and Yaoundé are millionaire cities.'],
          ['Conurbation:', 'It is a large urban area formed when growing towns merge together. The Ruhr in Germany and Greater Lagos are examples.'],
          ['Megalopolis:', 'It is a very large chain of conurbations linked by transport, with tens of millions of people. BosWash (Boston–Washington) and Tokyo–Osaka are examples.']],
        draw: { img: 'urban_forms_big.png', caption: 'types of urban regions' } },
      { title: '2. Spatial Distribution and Causes', intro: 'Urban regions are distributed and caused as follows:',
        items: [['Distribution:', 'Most megacities (over 10 million) are now in Asia, such as Tokyo, Delhi and Shanghai. Africa has Lagos, Cairo and Kinshasa.'],
          ['Causes:', 'Industrialisation, trade, rural–urban migration and natural increase make cities grow. Good transport links join towns into conurbations.'],
          ['Problems:', 'Megacities suffer from traffic congestion, slums, pollution and water shortages. They are difficult to govern.']],
        draw: { img: 'megacities_big.png', caption: 'megacities of the world' } },
    ],
    hwAnswer: 'Examples: Tokyo (Japan), Delhi (India), Shanghai (China), São Paulo (Brazil), Lagos (Nigeria), marked on a world map.',
  },
  'Lesson 14': {
    secs: ['1. MEANING', '2. SIZES', '2. SHAPES', '3. FACTORS', '3. FACTORS: COMPETITION'],
    action: 'Delimit the zones served by towns to plan services.',
    summary: [
      { title: '1. Meaning of Urban Field', intro: 'An urban field can be understood as follows:',
        items: [['Urban field (sphere of influence):', 'It is the area around a town that is served by it and depends on it for goods, services and jobs.']],
        draw: { img: 'urban_field_big.png', caption: 'an urban field' } },
      { title: '2. Shapes and Sizes', intro: 'Urban fields vary in shape and size:',
        items: [['Sizes:', 'Each service has its own field: high-order services (hospitals, universities) have large fields and low-order services (bakeries) small ones. Large towns have larger fields.'],
          ['Shapes:', 'Fields are rarely circular; they stretch along roads and railways. Relief, rivers and borders cut them.']] },
      { title: '3. Factors of Urban Fields', intro: 'The size and shape of fields depend on:',
        items: [['Size and functions of the town:', 'Towns with more and higher-order services attract people from further away. Yaoundé serves the whole Centre region and beyond.'],
          ['Transport and competition:', 'Good roads extend fields, while nearby competing towns limit them. The breaking point between two towns can be found with Reilly\'s law.'],
          ['Physical and political factors:', 'Mountains, rivers and borders limit fields. Administrative boundaries also influence where people go.']],
        draw: { img: 'reilly_big.png', caption: 'competition between towns' } },
    ],
    hwAnswer: 'Example: for the market people come from 5–10 km, for the bank from 20–30 km and for the regional hospital from over 50 km. The fields are drawn as zones of different sizes around the town.',
  },
  'Practical Work 2': {
    secs: ['1. CRITERIA', '2. DATA COLLECTION', '3. REILLY\'S LAW', '3. REILLY\'S LAW', '4. LIMITS'],
    action: 'Delimit urban fields using data and Reilly\'s law.',
    summary: [
      D([['Breaking point:', 'It is the point between two towns where their influence is equal.']]),
      { title: '1. Methods of Delimiting Urban Fields', intro: 'Urban fields are delimited as follows:',
        items: [['Criteria:', 'Use the areas served by newspapers, buses, schools, hospitals, markets and shops. Each criterion gives a line; together they show the field.'],
          ['Data collection:', 'Questionnaires ask people where they shop, study or seek health care. The answers are mapped with desire lines.']] },
      { title: '2. Reilly\'s Law of Retail Gravitation', intro: 'The breaking point is calculated as follows:',
        items: [['Formula:', 'Distance of the breaking point from the smaller town B = d ÷ (1 + √(PA ÷ PB)). d is the distance between the towns, PA and PB their populations.'],
          ['Example:', 'A = 400,000, B = 100,000, d = 90 km: 90 ÷ (1 + √4) = 90 ÷ 3 = 30 km from B. The field of the larger town is bigger.'],
          ['Limits:', 'The formula assumes equal transport and services and ignores people\'s preferences. Real fields depend also on roads and prices.']],
        draw: { img: 'reilly_big.png', caption: 'Reilly\'s breaking point' } },
    ],
    hwAnswer: 'Example: Garoua (about 900,000) and Guider (about 100,000), 100 km apart: breaking point = 100 ÷ (1 + √9) = 100 ÷ 4 = 25 km from Guider.',
  },
  'Lesson 15': {
    secs: ['1. URBAN HIERARCHY', '2. RANGE AND THRESHOLD', '3. CHRISTALLER\'S MODEL', '3. CHRISTALLER\'S ASSUMPTIONS', '4. APPLICABILITY AND CRITICISMS'],
    action: 'Plan the distribution of services using central place theory.',
    summary: [
      { title: '1. Urban Hierarchy', intro: 'Urban hierarchy can be understood as follows:',
        items: [['Meaning:', 'It is the ranking of settlements according to their size and the services they offer. There are many small settlements and few large cities.'],
          ['Classification:', 'From bottom to top: hamlet, village, small town, town, regional centre and capital city. Higher settlements offer higher-order services.']],
        draw: { img: 'hierarchy_big.png', caption: 'the urban hierarchy' } },
      { title: '2. Central Places, Range and Threshold', intro: 'Central place theory uses the following concepts:',
        items: [['Central place:', 'It is a settlement that provides goods and services to the surrounding area. Its importance is its centrality.'],
          ['Threshold:', 'It is the minimum number of customers needed for a service to survive. A hospital has a higher threshold than a shop.'],
          ['Range:', 'It is the maximum distance people will travel to buy a good or service. High-order goods have a long range.']],
        draw: { img: 'range_threshold_big.png', caption: 'range and threshold' } },
      { title: '3. Christaller\'s Model (1933)', intro: 'Christaller\'s model can be summarised as follows:',
        items: [['Assumptions:', 'He assumed a flat, uniform plain, even population, equal transport in all directions and rational consumers. People buy at the nearest centre.'],
          ['Principles and the three patterns:', 'Market areas are hexagons that cover the plain without gaps. K = 3 is the marketing principle, K = 4 the transport principle and K = 7 the administrative principle.'],
          ['Applicability and criticisms:', 'It fits flat farming areas such as southern Germany and parts of the Chad plain. But relief, rivers, uneven population and modern transport distort the pattern.']],
        draw: { img: 'christaller_big.png', caption: 'Christaller\'s hexagons' } },
    ],
    hwAnswer: 'Example ranking: 1. Garoua (hospital, university, banks); 2. Guider (hospital, market); 3. Pitoa (health centre, market); 4. a village (primary school, weekly market); 5. a hamlet (no services).',
  },
  'Lesson 16': {
    secs: ['1. THE LINEAR RELATIONSHIP', '2. THE CURVILINEAR RELATIONSHIP', '3. EXCEPTIONAL CASES', '3. EXCEPTIONAL CASES', '2. LINK WITH HIERARCHY'],
    action: 'Understand how the number of functions grows with town size.',
    summary: [
      D([['Function:', 'It is an activity or service provided by a settlement, such as a school, a bank or a market.'], ['Functional index:', 'It is a score that measures the number and importance of functions of a settlement.']]),
      { title: '1. Size and Functional Relationship', intro: 'The relationship between size and functions takes the following forms:',
        items: [['Linear relationship:', 'The number of functions increases steadily with population. On a graph the points form a straight line.'],
          ['Curvilinear relationship:', 'In large towns, functions increase more slowly than population. Big towns have more shops of the same type rather than new functions.'],
          ['Exceptional cases:', 'Tourist and resort towns have many functions for their size because of visitors. Mining or dormitory towns may have few functions for their size.']],
        draw: { img: 'size_function_big.png', caption: 'size and functions' } },
    ],
    hwAnswer: 'Example: a village of 2,000 people has 5 functions (school, church, market, borehole, clinic); a town of 50,000 has more than 40 functions (banks, secondary schools, hospital, hotels).',
  },
  'Lesson 17': {
    secs: ['1. MEANING AND FORMULA', '2. APPLICABILITY', '3. DEVIATIONS: PRIMATE', '3. DEVIATIONS: BINARY', '3. REASONS'],
    action: 'Analyse the urban system of Cameroon with the rank-size rule.',
    summary: [
      { title: '1. Meaning and Formula of the Rank-Size Rule', intro: 'The rank-size rule can be understood as follows:',
        items: [['Rank-size rule:', 'It states that the population of a town of rank n equals the population of the largest town divided by n. The second town is half the first, the third one-third, and so on.'],
          ['Formula:', 'Pn = P1 ÷ n. If the largest town has 4 million people, the fourth should have 1 million.']],
        draw: { img: 'rank_size_big.png', caption: 'the rank-size rule' } },
      { title: '2. Applicability and Reasons', intro: 'The rule applies in some countries:',
        items: [['Applicability:', 'It fits large, developed countries with a long urban history and integrated economies, such as the USA. It is shown as a straight line on a log graph.'],
          ['Reasons:', 'A balanced hierarchy develops where economic activities are spread across the country. Many regional centres compete.']] },
      { title: '3. Deviations from the Rule', intro: 'The main deviations are:',
        items: [['Primate pattern:', 'The largest city is much bigger than the second, like Paris, Lagos (formerly) or Bangkok. It results from colonial history, centralisation of power and investment.'],
          ['Binary pattern:', 'Two cities of almost equal size dominate the country. Cameroon has a binary pattern with Douala (economic capital) and Yaoundé (political capital).'],
          ['Stepped pattern:', 'Several towns of similar size form steps in the hierarchy. It is found in federal or regionally balanced countries.']],
        draw: { img: 'primate_big.png', caption: 'deviations from the rule' } },
    ],
    hwAnswer: 'Graph: Yaoundé and Douala about 4 million each, then Garoua, Bamenda and Bafoussam far below. The graph shows a binary pattern, not a regular rank-size line.',
  },
  'Lesson 18': {
    secs: ['2. MAIN FUNCTIONAL ZONES', '2. THE CBD', '1. URBAN MORPHOLOGY: MODELS', '1. URBAN MORPHOLOGY: MODELS', '2. SUBURBS'],
    action: 'Describe the internal structure of cities and compare with our towns.',
    summary: [
      D([['Urban morphology:', 'It is the form, layout and structure of a town.'], ['CBD:', 'It is the Central Business District, the commercial heart of a city.']]),
      { title: '1. Urban Morphology and Structure', intro: 'The structure of cities in MEDCs is explained by models:',
        items: [['Burgess (1925):', 'The city grows in concentric rings: CBD, zone in transition, low-class housing, middle-class housing and commuter zone. It is based on Chicago.'],
          ['Hoyt (1939):', 'Land uses form sectors along transport routes from the centre. High-class housing and industry each form wedges.'],
          ['Harris and Ullman (1945):', 'Large cities have several nuclei (centres) such as the CBD, industrial districts and suburban centres. It fits modern large cities.']],
        draw: { img: 'city_models_big.png', caption: 'models of city structure' } },
      { title: '2. Main Functional Zones', intro: 'The spatial organisation of functions in a city is as follows:',
        items: [['CBD:', 'It has shops, offices, banks and tall buildings at the most accessible point. Land values are highest and few people live there.'],
          ['Inner city and industrial zones:', 'The inner city has old housing and industries near railways and canals. It may suffer from decay.'],
          ['Suburbs and the fringe:', 'Suburbs have lower-density housing with gardens and shopping centres. The fringe mixes housing, farms and large facilities.']] },
    ],
    hwAnswer: 'Example: the town has a central commercial area (market, banks), an old dense quarter, an administrative area, industrial zone near the river and new residential quarters on the edge – close to Hoyt\'s sector model along the main roads.',
  },
  'Lesson 19': {
    secs: ['1. BID RENT THEORY', '1. BID RENT THEORY', '2. SOCIAL SEGREGATION', '2. OTHER FACTORS: RELIEF', '3. CONSEQUENCES'],
    action: 'Understand the urban land market and reduce segregation through planning.',
    summary: [
      D([['Bid rent:', 'It is the amount that a land user is willing to pay for a site at a given distance from the centre.'], ['Functional segregation:', 'It is the separation of different land uses into different zones of a town.']]),
      { title: '1. The Bid Rent Theory', intro: 'The urban land market works as follows:',
        items: [['Land value and accessibility:', 'In a free market, land is most valuable at the most accessible point, the CBD. Locational rent decreases with distance from the CBD.'],
          ['Bid rent curves:', 'Shops and offices bid the highest rents near the centre, industry and flats next, and houses further out. Each land use occupies the zone where it bids highest.'],
          ['Other zones:', 'Secondary peaks of land value occur at road junctions and suburban shopping centres. Lower values are found in the fringe.']],
        draw: { img: 'bid_rent_big.png', caption: 'bid rent curves' } },
      { title: '2. Other Factors of Segregation', intro: 'Segregation also depends on:',
        items: [['Government and planning:', 'Zoning laws separate residential, industrial and commercial areas. Public housing and roads change land values.'],
          ['Micro-relief and social segregation:', 'Hills, flood plains and valleys affect land use; the rich often live on healthy high ground. Income, ethnicity and religion separate social groups.']] },
      { title: '3. Consequences', intro: 'Bid rent and segregation have the following effects:',
        items: [['Housing and density:', 'High land values in the centre lead to tall buildings and high densities of activities. Poor people live in cheap, crowded areas or slums.'],
          ['Location of activities:', 'Commerce concentrates in the CBD, while industries move to the edge where land is cheaper. Population density falls from the inner city outwards.']] },
    ],
    hwAnswer: 'A shop in the centre costs much more (e.g. 100,000 FCFA per month) than one on the outskirts (e.g. 20,000 FCFA) because the centre is more accessible and has more customers.',
  },
  'Lesson 20': {
    secs: ['1. MEANING', '2. REASONS FOR PLANNING', '2. SOCIAL INEQUALITIES AND HOUSING', '2. TRANSPORT PROBLEMS', '2. ENVIRONMENTAL PROBLEMS'],
    action: 'Support urban planning to solve problems in our towns.',
    summary: [
      { title: '1. Meaning of Planning', intro: 'Settlement planning can be understood as follows:',
        items: [['Urban planning:', 'It is the organisation of land use, buildings, transport and services in a settlement to improve living conditions. It is done by councils and ministries.']] },
      { title: '2. Reasons for Urban Planning', intro: 'Planning is needed to solve the following problems:',
        items: [['Economic problems:', 'Unemployment, informal trade and poor infrastructure slow development. Planning creates industrial zones and markets.'],
          ['Social inequalities and housing:', 'Slums lack water, sanitation and security, while the rich live in separate areas. Planning provides serviced plots and low-cost housing.'],
          ['Transport problems:', 'Traffic jams, accidents and poor public transport waste time. Planning builds roads, bus lanes and parking.'],
          ['Environmental problems:', 'Floods, pollution, waste and loss of green spaces harm health. Planning provides drains, waste collection and parks.']],
        draw: { img: 'urban_problems_big.png', caption: 'urban problems' } },
    ],
    hwAnswer: 'Example: our quarter floods every rainy season; plan – clean the drains monthly, build a wider concrete drain, stop building on the stream bed and plant grass on bare land.',
  },
  'Lesson 21': {
    secs: ['1. INNER CITY DECAY', '1. CAUSES OF DECAY', '2. URBAN RENEWAL', '2. EXAMPLE: LONDON DOCKLANDS', '2. RENEWAL IN CAMEROON'],
    action: 'Renew old quarters while protecting their inhabitants.',
    summary: [
      D([['Inner city decay:', 'It is the decline of the old areas near the city centre.'], ['Urban renewal:', 'It is the improvement of decayed urban areas by redevelopment or rehabilitation.']]),
      { title: '1. Inner City Decay', intro: 'Inner city decay can be studied as follows:',
        items: [['Signs:', 'Old, overcrowded houses, empty factories, derelict land, unemployment and crime are signs of decay. Services decline.'],
          ['Causes:', 'Industries closed or moved to the suburbs, and richer people left for better housing. Poor migrants remained in old buildings.']] },
      { title: '2. Urban Renewal in Inner Cities', intro: 'Inner cities are renewed in the following ways:',
        items: [['Redevelopment:', 'Old buildings are demolished and replaced by new housing, offices and roads. It is fast but displaces residents.'],
          ['Rehabilitation:', 'Old houses are repaired and modernised, and services improved. It keeps the community in place.'],
          ['Examples:', 'The London Docklands were transformed into offices, housing and transport links, but some local people could not afford the new houses. In Cameroon, old quarters of Douala and Yaoundé are restructured with new roads and drains.']],
        draw: { img: 'renewal_big.png', caption: 'urban renewal' } },
    ],
    hwAnswer: 'Example: an old quarter near the central market has crowded houses and no drains; it could be renewed by building drains and paved streets, repairing houses and creating a small park, while rehousing families nearby.',
  },
  'Lesson 22': {
    secs: ['1. URBAN SPRAWL', '2. GREEN BELTS', '2. NEW TOWNS', '2. RING ROADS AND DECENTRALISATION', '3. CITIES OF THE FUTURE'],
    action: 'Control the spread of our towns to protect farmland and the environment.',
    summary: [
      D([['Urban sprawl:', 'It is the uncontrolled spread of a town into the surrounding countryside.']]),
      { title: '1. Measures of Checking Town Spread', intro: 'Town spread can be controlled by:',
        items: [['Green belts:', 'A belt of protected countryside around a town where building is forbidden. London has had a green belt since 1947.'],
          ['Ring roads:', 'Roads around the town reduce traffic in the centre and guide growth. They must be combined with planning to avoid new sprawl.'],
          ['Decentralisation and new towns:', 'Activities are moved to smaller towns, and new planned towns absorb growth. Examples are Milton Keynes in England and Abuja in Nigeria.'],
          ['Hypermarkets and other measures:', 'Out-of-town hypermarkets and business parks reduce pressure on the centre. Zoning laws and densification of existing areas also help.']],
        draw: { img: 'sprawl_control_big.png', caption: 'measures against sprawl' } },
      { title: '2. Cities of the Future', intro: 'Future cities aim to be sustainable:',
        items: [['Sustainable features:', 'They use renewable energy, public transport, green spaces and recycling. Compact, mixed-use neighbourhoods reduce car use.'],
          ['Smart cities:', 'Digital technology manages traffic, water and energy. Songdo in South Korea is an example.']] },
    ],
    hwAnswer: 'Measures for Yaoundé or Douala: create a green belt, develop satellite towns (e.g. Soa, Edéa), build ring roads and improve public transport so that people can live further away without sprawl.',
  },
  'Further Study 1': {
    secs: ['1. DISTRIBUTION OF TOWNS', '1. RANKING OF TOWNS', '2. FACTORS OF URBAN GROWTH', '3. CASE STUDY: DOUALA', '3. CASE STUDY: YAOUNDÉ'],
    action: 'Plan the growth of towns in Cameroon to improve living conditions.',
    summary: [
      { title: '1. Urbanisation in Cameroon', intro: 'Urbanisation in Cameroon can be described as follows:',
        items: [['Rate and distribution:', 'About 58 % of Cameroonians live in towns, and the rate is rising fast. Most large towns are in the south and west, with Douala and Yaoundé far ahead.'],
          ['Ranking:', 'Yaoundé and Douala have about 4 million people each, followed by Garoua, Bamenda, Bafoussam and Maroua. The pattern is binary.']],
        draw: { img: 'cmr_towns_big.png', caption: 'main towns of Cameroon' } },
      { title: '2. Factors of Urban Growth', intro: 'Towns in Cameroon grew because of:',
        items: [['Colonial and economic factors:', 'Colonial ports, railways and plantations created towns such as Douala and Nkongsamba. Industries, trade and administration attract migrants.'],
          ['Demographic and political factors:', 'Rural–urban migration and high natural increase add many people. Administrative decisions (regional capitals, universities) also create growth.']] },
      { title: '3. Case Studies: Douala and Yaoundé', intro: 'The two main cities can be described as follows:',
        items: [['Douala:', 'It is sited on low, swampy land on the Wouri estuary, with a situation at the gate of Cameroon and Central Africa. It is the main port, industrial and commercial centre, but suffers from floods, slums and traffic.'],
          ['Yaoundé:', 'It is sited on hills and valleys of the South Cameroon Plateau, at the centre of the country. It is the political capital with ministries, universities and embassies, but faces erosion, floods in valleys and congestion.']] },
    ],
    hwAnswer: 'Douala: low, swampy site on the Wouri estuary. Problems: floods, traffic jams and unplanned quarters (e.g. slums near swamps).',
  },
};
