// FORM 1 — Module 1: The Earth in the Universe (2023 national syllabus): L1, L2, PW1, PW2, L3, PW3
// Revised model (Sept 2026): syllabus points in order, definitions apart, one element per slide with its picture,
// problem visible in the situation, one question per slide in the activities.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F1', code: 'M1', folder: '', module: 'Module 1: The Earth in the Universe', topicDefault: 'The Earth in the Universe', branch: 'The Earth: A Planet of the Solar System',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 1, Module 1: The Earth in the Universe.'] };
const L = [];

L.push({ no: 1, title: 'Geography: Meaning, Branches, Methods and Importance', subtopic: 'Introduction to Geography',
  notions: 'Geography, physical geography, human geography, practical geography, fieldwork.',
  focus: 'Definition of geography; branches and sub-branches; methods; importance.',
  competence: 'Learners are able to explain what geography studies and why it is useful in daily life.',
  objectives: ['Define geography.', 'Identify the branches and sub-branches of geography.', 'Describe the methods and the importance of geography.'],
  recall: ['We live on the Earth, with land, water and air around us.', 'People live in villages and towns and do different jobs.', 'Maps show where places are.'],
  situation: 'On his first day in Form 1, Ibrahim sees "Geography" on his timetable. His elder sister says that it is only about drawing maps, but his father says that it helps farmers, drivers and even the Mayor of Garoua. Ibrahim is confused and asks his teacher: "What does geography really study, and why is it useful?"',
  sitQA: [['What is the problem in the situation?', 'Ibrahim does not know what geography studies and why it is useful.'], ['What does his sister think geography is?', 'She thinks it is only about drawing maps.'], ['Who uses geography, according to his father?', 'Farmers, drivers and the Mayor of Garoua.']],
  justification: 'This lesson helps us to know what geography studies and why it is useful for our lives.',
  action: 'Observe the land, the weather and the activities of people around you like a geographer.',
  activities: [
    { sec: '1. MEANING OF GEOGRAPHY', img: 'f4_earth_space.jpg', caption: 'The Earth seen from space.',
      q: ['The word geography comes from the Greek words "geo" and "graphein". What do these words mean?', 'So, what is geography?'],
      a: ['"Geo" means the Earth, and "graphein" means to describe.', 'Geography is the study and description of the Earth and of the people who live on it.'], noProj: 'write "geo" + "graphein" on the board.' },
    { sec: '2. BRANCHES OF GEOGRAPHY', img: 'lsa_mtcameroon.jpg', caption: 'Mount Cameroon.', q: 'Which branch of geography studies mountains, rivers, climate and soils?', a: 'Physical geography.', noProj: 'name mountains and rivers of Cameroon.' },
    { sec: '2. BRANCHES OF GEOGRAPHY', img: 'f2t_market.jpg', caption: 'A busy market in Cameroon.', q: 'Which branch of geography studies people, markets, towns and farming?', a: 'Human geography.', noProj: 'describe the market of Garoua.' },
    { sec: '3. METHODS OF GEOGRAPHY', img: 'usa_topomap.jpg', caption: 'A geographer using a map in the field.', q: 'How does a geographer collect information about a place?', a: 'By observing and measuring in the field, and by asking people questions.', noProj: 'show a map of Cameroon.' },
    { sec: '4. IMPORTANCE OF GEOGRAPHY', img: 'f2t_cotton_field.jpg', caption: 'A cotton farm in the North.', q: 'How can geography help this farmer?', a: 'It helps him to know the seasons, the rainfall and the soils, so that he chooses the right crops and the right time to plant.', noProj: 'ask learners how their parents choose when to plant.' },
  ],
  summary: [
    D([['Geography:', 'It is the study of the Earth, its physical features and the activities of the people who live on it.'],
      ['Branch of geography:', 'It is a main part of geography that studies one group of subjects.']]),
    { title: '1. Branches and Sub-branches of Geography', intro: 'Geography has three main branches:',
      items: [['Physical geography:', 'It studies natural features such as relief, climate, rivers, soils and vegetation. Its sub-branches include geomorphology, climatology, hydrology, pedology and biogeography.', 'lsa_mtcameroon.jpg', 'Mount Cameroon, a physical feature'],
        ['Human geography:', 'It studies people and their activities. Its sub-branches include population, settlement, economic and political geography.', 'f2t_market.jpg', 'a market, a human activity'],
        ['Practical geography:', 'It studies the tools of the geographer. Its sub-branches include map reading, statistics, fieldwork and remote sensing.', 'usa_topomap.jpg', 'map reading in the field']] },
    { title: '2. Methods of Geography', intro: 'Geographers use the following methods:',
      items: [['Observation and fieldwork:', 'Geographers go to the field to observe, measure and record what they see.', 'fieldwork_steps_big.png', 'the steps of fieldwork'],
        ['Interviews and questionnaires:', 'Geographers ask people questions to collect information on their lives and activities.', 'questionnaire_big.png', 'a questionnaire'],
        ['Maps and photographs:', 'Geographers use maps, photographs and satellite images to show and study places.', 'remote_sensing_big.png', 'a satellite image is taken from space'],
        ['Statistics and graphs:', 'Geographers use numbers, tables and graphs to compare places and changes.', 'graph_choice_big.png', 'types of graphs']] },
    { title: '3. Importance of Geography', intro: 'Geography is important for the following reasons:',
      items: [['Daily life:', 'It helps us to find places, read maps and understand the weather.'],
        ['Farming:', 'It helps farmers to know the seasons, the soils and the right crops.'],
        ['Planning:', 'It helps the government and councils to plan roads, schools and towns.'],
        ['Environment:', 'It teaches us to protect the land, water and forests.']] },
  ],
  evaluation: [['Define geography.', 'It is the study of the Earth, its physical features and the activities of people on it.'], ['Name the three branches of geography.', 'Physical, human and practical geography.']],
  remediation: ['"Geo" means the ______.', 'The study of relief and climate is ______ geography.', 'The study of population and towns is ______ geography.'],
  remediationAnswers: '1. Earth 2. physical 3. human',
  homework: 'Write three physical features and three human activities that you see on your way to school.',
  hwAnswer: 'Physical features: a hill, the River Benue, trees and grass. Human activities: trading in the market, moto-taxi transport, farming.',
  bilingual: [['Geography', 'La géographie'], ['Branch', 'La branche'], ['Map', 'La carte'], ['Fieldwork', 'Le travail de terrain'], ['Relief', 'Le relief'], ['Population', 'La population']],
});

L.push({ no: 2, title: 'Our Planet, the Earth', subtopic: 'The Earth: A Planet of the Solar System',
  notions: 'Universe, solar system, geographical coordinates, latitudes, longitudes.',
  focus: 'The Earth in the solar system; shape, dimensions and locational references; distribution of the landmasses and water bodies.',
  competence: 'Learners are able to situate the Earth in the solar system and describe its shape, size and main land and water areas.',
  objectives: ['Situate the Earth in the solar system.', 'Describe the shape, the dimensions and the locational references of the Earth.', 'Describe the distribution of the landmasses and water bodies.'],
  recall: ['Geography studies the Earth and its people.', 'The Sun gives us light and heat.', 'Maps show land and water.'],
  situation: 'During a clear night in Garoua, Aminatou sees many stars in the sky. She asks her brother: "Is the Earth also a star, and what does it look like from space?" Her brother does not know how to answer her.',
  sitQA: [['What is the problem in the situation?', 'Aminatou does not know what kind of body the Earth is and what it looks like.'], ['Is the Earth a star?', 'No, it is a planet that moves around the Sun.'], ['What covers most of the Earth?', 'Water (oceans and seas).']],
  justification: 'This lesson helps us to know the place of our planet in the universe and its main land and water areas.',
  action: 'Use a globe or a map to locate the continents and oceans of the world.',
  activities: [
    { sec: '1. THE EARTH IN THE SOLAR SYSTEM', img: 'solar_system_big.png', caption: 'The Sun and the planets.',
      q: ['How many planets move around the Sun?', 'What is the position of the Earth from the Sun?'],
      a: ['Eight planets move around the Sun.', 'The Earth is the third planet from the Sun.'], noProj: 'draw the Sun and eight circles on the board.' },
    { sec: '2. SHAPE AND DIMENSIONS', img: 'f4_earth_space.jpg', caption: 'The Earth seen from space.', q: 'What is the shape of the Earth?', a: 'It is round like a ball, slightly flat at the poles.', noProj: 'show a ball or an orange.' },
    { sec: '2. LOCATIONAL REFERENCES', img: 'latitudes_big.png', caption: 'Imaginary lines on the Earth.', q: 'Which imaginary line divides the Earth into a northern half and a southern half?', a: 'The Equator (latitude 0°).', noProj: 'draw a circle with the Equator.' },
    { sec: '3. LANDMASSES AND WATER BODIES', img: 'continents_oceans_big.png', caption: 'The land and water of the Earth.', q: 'Name the continent on which Cameroon is found and two oceans around it.', a: 'Africa; the Atlantic Ocean and the Indian Ocean.', noProj: 'show a world map.' },
    { sec: '3. LANDMASSES AND WATER BODIES', img: 'land_water_big.png', caption: 'Water and land on the Earth.', q: 'Which covers more of the Earth: land or water?', a: 'Water covers about 71 % of the Earth, and land covers only about 29 %.', noProj: 'shade a circle: 7 parts water, 3 parts land.' },
  ],
  summary: [
    D([['Universe:', 'It is all of space and everything in it: stars, planets and galaxies.'],
      ['Solar system:', 'It is the Sun and the planets and other bodies that move around it.'],
      ['Planet:', 'It is a large round body that moves around the Sun.']]),
    { title: '1. The Earth in the Solar System', intro: 'The Earth is situated in the solar system as follows:',
      items: [['The Sun:', 'It is a star at the centre of the solar system. It gives light and heat to the planets.', 'lsa_sun.jpg', 'the Sun'],
        ['The planets:', 'Eight planets move around the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune.', 'solar_system_big.png', 'the solar system'],
        ['The Earth:', 'It is the third planet from the Sun. It is the only planet known to have life, water and air.', 'f4_earth_space.jpg', 'the Earth seen from space']] },
    { title: '2. Shape, Dimensions and Locational References', sub: 'A) Shape and Dimensions',
      items: [['Shape:', 'The Earth is a sphere, wider at the Equator and slightly flattened at the poles.', 'earth_shape_big.png', 'the shape of the Earth'],
        ['Circumference:', 'The distance around the Earth at the Equator is about 40,000 km.'],
        ['Diameter:', 'The distance through the centre of the Earth is about 12,700 km.'],
        ['Surface area:', 'The surface of the Earth is about 510 million km².']] },
    { title: '2. Shape, Dimensions and Locational References', sub: 'B) Locational References',
      items: [['Lines of latitude:', 'They are imaginary circles drawn around the Earth parallel to the Equator. The Equator is latitude 0°.', 'latitudes_big.png', 'lines of latitude'],
        ['Lines of longitude:', 'They are imaginary lines drawn from the North Pole to the South Pole. The Greenwich Meridian is longitude 0°.', 'longitudes_big.png', 'lines of longitude'],
        ['Geographical coordinates:', 'The latitude and the longitude of a place give its exact position on the Earth.', 'coordinates_last.png', 'the coordinates of a place']] },
    { title: '3. Distribution of Landmasses and Water Bodies', intro: 'Land and water are distributed as follows:',
      items: [['Continents:', 'The seven continents are Asia, Africa, North America, South America, Antarctica, Europe and Australia.', 'continents_oceans_big.png', 'the continents and oceans'],
        ['Oceans:', 'The five oceans are the Pacific, the Atlantic, the Indian, the Southern and the Arctic Oceans.'],
        ['Share of land and water:', 'Water covers about 71 % of the Earth, and land covers about 29 %.', 'land_water_big.png', 'water and land on the Earth'],
        ['Hemispheres:', 'Most of the land is in the Northern Hemisphere, and most of the water is in the Southern Hemisphere.']] },
  ],
  evaluation: [['What is the position of the Earth in the solar system?', 'It is the third planet from the Sun.'], ['Name three continents and two oceans.', 'Africa, Asia, Europe; the Atlantic and the Pacific Oceans.']],
  remediation: ['The Earth is the ______ planet from the Sun.', 'The largest ocean is the ______ Ocean.', 'Cameroon is on the continent of ______.'],
  remediationAnswers: '1. third 2. Pacific 3. Africa',
  homework: 'On a map of the world in your atlas, find Cameroon, the Equator and the Greenwich Meridian.',
  hwAnswer: 'Cameroon is in Central Africa, just north of the Equator (between about 2° N and 13° N) and east of the Greenwich Meridian (between about 8° E and 16° E).',
  bilingual: [['Planet', 'La planète'], ['Solar system', 'Le système solaire'], ['Continent', 'Le continent'], ['Ocean', "L'océan"], ['Equator', "L'équateur"], ['Globe', 'Le globe']],
});

L.push({ kind: 'Practical Work', no: 1, title: 'Representation of the Earth\'s Shape and Size', subtopic: 'The Earth: A Planet of the Solar System',
  notions: 'Globe, world map, projection, title, key, scale, cardinal points, grid lines.',
  focus: 'Theoretical basis: forms of representation of the Earth\'s shape (globe, world map, projections). Practical exercise: identification of the marginal information on maps (title, key, scale, cardinal points, grid lines, latitudes and longitudes, orientation). Contextualisation: read the scale of a map and calculate distances between places.',
  competence: 'Learners are able to identify the marginal information of a map and calculate distances with a scale.',
  objectives: ['Identify the forms of representation of the Earth.', 'Identify the marginal information on a map.', 'Calculate real distances using the scale.'],
  recall: ['The Earth is round like a ball.', 'Maps show places on a flat surface.', 'Latitudes and longitudes help us to locate places.'],
  situation: 'Mariam wants to know how far Garoua is from Maroua. On her map, the two towns are 6 cm apart. She asks her father: "How can I change these 6 centimetres into the real distance in kilometres?"',
  sitQA: [['What is the problem in the situation?', 'Mariam does not know how to change a distance on the map into a real distance.'], ['Which part of the map helps her?', 'The scale.'], ['What else is written around a map?', 'The title, the key, the north arrow and the grid lines.']],
  justification: 'This practical work helps us to read maps correctly and to calculate real distances.',
  action: 'Always read the title, the key and the scale before using a map.',
  activities: [
    { sec: '1. FORMS OF REPRESENTATION', img: 'globe_big.png', caption: 'A round model of the Earth.', q: 'What is this round model of the Earth called?', a: 'It is a globe.', noProj: 'show a globe or a ball.' },
    { sec: '1. FORMS OF REPRESENTATION', img: 'map_projections_big.png', caption: 'The Earth drawn on flat surfaces.',
      q: ['Compare these three world maps. Are the shapes of the continents the same?', 'Why are they different?'],
      a: ['No, the shapes and sizes of the continents change from one map to another.', 'Because the round Earth is drawn on a flat surface in different ways, called projections.'], noProj: 'peel an orange and flatten the peel.' },
    { sec: '2. MARGINAL INFORMATION', img: 'map_marginal_big.png', caption: 'A map and the information around it.', q: 'Name the elements written around this map.', a: 'The title, the key, the scale, the north arrow, the frame and the grid lines.', noProj: 'draw a frame with these elements.' },
    { sec: '3. READING THE SCALE', img: 'scale_types_big.png', caption: 'Ways of writing the scale of a map.', q: 'What does the scale "1 cm to 25 km" mean?', a: 'One centimetre on the map represents 25 kilometres on the ground.', noProj: 'write the scale on the board.' },
    { sec: '3. CALCULATING DISTANCES', img: 'cameroon_grid_big.png', caption: 'A map of Cameroon.', q: 'With a scale of 1 cm to 25 km, Garoua and Maroua are 6 cm apart. What is the real distance?', a: '6 × 25 = 150 km.', noProj: 'write the calculation on the board.' },
  ],
  summary: [
    D([['Globe:', 'It is a round model of the Earth.'],
      ['Map:', 'It is a drawing of the Earth or part of it on a flat surface.'],
      ['Projection:', 'It is a method of drawing the round Earth on a flat map.']]),
    { title: '1. Forms of Representation of the Earth', intro: 'The Earth is represented in the following forms:',
      items: [['The globe:', 'It shows the true shape and sizes of the continents. However, it shows only half of the Earth at once and few details.', 'globe_big.png', 'the globe'],
        ['The world map:', 'It shows the whole Earth at once on a flat surface. It is easy to carry and shows many details.', 'continents_oceans_big.png', 'a world map'],
        ['Map projections:', 'Each projection keeps some shapes or sizes and changes others. Examples are cylindrical, equal-area and azimuthal projections.', 'map_projections_big.png', 'three map projections']] },
    { title: '2. Marginal Information on Maps', intro: 'A map has the following marginal information:',
      items: [['Title:', 'It tells what the map shows and where.'],
        ['Key (legend):', 'It explains the signs, lines and colours used on the map.', 'signs_big.png', 'signs explained in a key'],
        ['Scale:', 'It shows the relation between a distance on the map and the real distance on the ground.', 'scale_types_big.png', 'ways of writing a scale'],
        ['Cardinal points and north arrow:', 'They show the directions: north, south, east and west.', 'bearings_big.png', 'the cardinal points'],
        ['Grid lines, latitudes and longitudes:', 'They help us to locate places on the map.', 'cameroon_grid_big.png', 'grid lines on a map of Cameroon']] },
    { title: '3. Reading the Scale and Calculating Distances', intro: 'We calculate a real distance as follows:',
      items: [['Step 1:', 'We measure the distance between the two places on the map with a ruler.'],
        ['Step 2:', 'We multiply the map distance by the value of the scale.'],
        ['Step 3:', 'We write the answer in kilometres.'],
        ['Example:', 'With a scale of 1 cm to 25 km, 6 cm on the map equals 6 × 25 = 150 km.']] },
  ],
  evaluation: [['Name four elements of the marginal information of a map.', 'The title, the key, the scale and the north arrow.'], ['On a map of 1 cm to 10 km, two towns are 4.5 cm apart. Find the real distance.', '4.5 × 10 = 45 km.']],
  remediation: ['A round model of the Earth is a ______.', 'The part of a map that explains the signs is the ______.', 'The part of a map used to calculate distances is the ______.'],
  remediationAnswers: '1. globe 2. key 3. scale',
  homework: 'On the map of Cameroon in your atlas, measure the distance from Garoua to Ngaoundéré and change it into kilometres with the scale.',
  hwAnswer: 'Answers depend on the atlas. Example: 2.8 cm on a map of 1 cm to 75 km gives 2.8 × 75 = 210 km (the road distance is longer because roads are not straight).',
  bilingual: [['Globe', 'Le globe'], ['Map', 'La carte'], ['Title', 'Le titre'], ['Key', 'La légende'], ['Scale', "L'échelle"], ['North arrow', 'La flèche du nord']],
});

L.push({ kind: 'Practical Work', no: 2, title: 'Locate a Place on a Map', subtopic: 'The Earth: A Planet of the Solar System',
  notions: 'Latitude, longitude, geographical coordinates, Equator, Greenwich Meridian.',
  focus: 'Theoretical basis: the Earth in the solar system. Practical exercise: read the coordinates of a place on a map; locate Cameroon on the map of Africa using geographical coordinates. Contextualisation: situate a town in Cameroon using geographical coordinates.',
  competence: 'Learners are able to read and write the geographical coordinates of a place.',
  objectives: ['Read the coordinates of a place on a map.', 'Locate Cameroon on the map of Africa with coordinates.', 'Situate towns of Cameroon with coordinates.'],
  recall: ['The Equator is the line of latitude 0°.', 'The Greenwich Meridian is the line of longitude 0°.', 'Maps have grid lines.'],
  situation: 'A pilot must fly from Douala to Garoua. On the radio, Hassan hears the control tower give the position of Garoua as "9° N, 13° E". He asks his teacher: "What do these numbers mean, and how can I find a town with them?"',
  sitQA: [['What is the problem in the situation?', 'Hassan does not understand the position of Garoua given to the pilot.'], ['What do "9° N" and "13° E" represent?', 'The latitude and the longitude of Garoua.'], ['Why does the pilot need them?', 'To find the exact position of Garoua.']],
  justification: 'This practical work helps us to find the exact position of any place on a map.',
  action: 'Always write the latitude first and the longitude second.',
  activities: [
    { sec: '1. REVISION', img: 'latitudes_big.png', caption: 'Lines of latitude.', q: 'What does the latitude of a place tell us?', a: 'How far north or south of the Equator the place is.', noProj: 'draw the Equator and the tropics.' },
    { sec: '1. REVISION', img: 'longitudes_big.png', caption: 'Lines of longitude.', q: 'What does the longitude of a place tell us?', a: 'How far east or west of the Greenwich Meridian the place is.', noProj: 'draw meridians from pole to pole.' },
    { sec: '1. READING COORDINATES', img: 'coordinates.gif', caption: 'Animation: finding a place on a grid.', q: 'Which do we write first: the latitude or the longitude?', a: 'The latitude first, then the longitude, for example 9° N, 13° E.', noProj: 'show the steps on a grid on the board.' },
    { sec: '2. LOCATING CAMEROON', img: 'africa_grid_big.png', caption: 'Africa with lines of latitude and longitude.', q: 'Between which lines of latitude is Cameroon found?', a: 'Between about 2° N and 13° N.', noProj: 'use the atlas.' },
    { sec: '3. SITUATING TOWNS', img: 'cameroon_grid_big.png', caption: 'Towns of Cameroon on a grid.', q: 'What are the coordinates of Garoua?', a: 'About 9° N, 13° E.', noProj: 'use the atlas.' },
  ],
  summary: [
    D([['Latitude:', 'It is the distance of a place north or south of the Equator, measured in degrees.'],
      ['Longitude:', 'It is the distance of a place east or west of the Greenwich Meridian, measured in degrees.'],
      ['Geographical coordinates:', 'They are the latitude and the longitude of a place.']]),
    { title: '1. Reading the Coordinates of a Place', intro: 'We read the coordinates of a place in the following steps:',
      items: [['Step 1:', 'We find the place on the map.', 'coordinates_last.png', 'reading coordinates on a grid'],
        ['Step 2:', 'We follow the line of latitude to the side of the map and read its value with N or S.'],
        ['Step 3:', 'We follow the line of longitude to the top or bottom of the map and read its value with E or W.'],
        ['Step 4:', 'We write the latitude first and the longitude second, for example 9° N, 13° E.']] },
    { title: '2. Locating Cameroon on the Map of Africa', intro: 'Cameroon is located as follows:',
      items: [['Latitudes:', 'Cameroon lies between about 2° N and 13° N, just north of the Equator.', 'africa_grid_big.png', 'Cameroon on the map of Africa'],
        ['Longitudes:', 'Cameroon lies between about 8° E and 16° E, east of the Greenwich Meridian.']] },
    { title: '3. Situating Towns of Cameroon', intro: 'Some towns of Cameroon have the following coordinates:',
      items: [['Garoua:', 'It is at about 9° N, 13° E.', 'cameroon_grid_big.png', 'towns of Cameroon on a grid'],
        ['Maroua:', 'It is at about 11° N, 14° E.'],
        ['Yaoundé:', 'It is at about 4° N, 12° E.'],
        ['Douala:', 'It is at about 4° N, 10° E.']] },
  ],
  evaluation: [['Write the coordinates of Maroua (about 11° N, 14° E) and explain them.', '11° north of the Equator and 14° east of the Greenwich Meridian.'], ['Which comes first in coordinates?', 'The latitude.']],
  remediation: ['The line of latitude 0° is the ______.', 'The line of longitude 0° is the ______ Meridian.', 'In coordinates, we write the ______ first.'],
  remediationAnswers: '1. Equator 2. Greenwich 3. latitude',
  homework: 'Find the coordinates of Douala, Ngaoundéré and Bertoua in your atlas.',
  hwAnswer: 'Douala: about 4° N, 9.7° E. Ngaoundéré: about 7.3° N, 13.6° E. Bertoua: about 4.6° N, 13.7° E.',
  bilingual: [['Latitude', 'La latitude'], ['Longitude', 'La longitude'], ['Coordinates', 'Les coordonnées'], ['Degree', 'Le degré'], ['North', 'Le nord'], ['East', "L'est"]],
});

L.push({ no: 3, title: 'The Earth: A Planet Moving in Space', subtopic: 'The Earth: A Planet in the Solar System',
  notions: 'Rotation, revolution, time, solstice, equinox, time zones, GMT.',
  focus: 'Rotation and revolution of the Earth and their consequences.',
  competence: 'Learners are able to explain the movements of the Earth and their effects on daily life.',
  objectives: ['Define rotation and revolution.', 'Explain the consequences of rotation.', 'Explain the consequences of revolution.'],
  recall: ['The Earth is a planet that moves around the Sun.', 'The Earth has an axis from the North Pole to the South Pole.', 'Lines of longitude help to locate places.'],
  situation: 'One evening, Aïcha calls her uncle in Canada to wish him a happy birthday. It is already night in Garoua, but her uncle says that it is still the middle of the day there. Aïcha asks her mother: "How can it be night here and day in Canada at the same time?"',
  sitQA: [['What is the problem in the situation?', 'Aïcha does not understand why it is night in Garoua and day in Canada at the same time.'], ['Which movement of the Earth causes day and night?', 'Rotation.'], ['Why is it earlier in Canada?', 'Canada is to the west, so it receives the Sun later.']],
  justification: 'This lesson helps us to understand day and night, the time differences and the seasons.',
  action: 'Plan your activities according to the time of day and the seasons.',
  activities: [
    { sec: '1. ROTATION', img: 'rotation.gif', caption: 'Animation: the Earth turns.',
      q: ['How long does the Earth take to make one full turn on its axis?', 'In which direction does it turn?'],
      a: ['24 hours (one day).', 'From west to east.'], noProj: 'turn a ball in front of a torch.' },
    { sec: '1. CONSEQUENCES OF ROTATION', img: 'rotation_mid.png', caption: 'The Earth facing the Sun.', q: 'Why is it day on one side of the Earth and night on the other?', a: 'Only the side facing the Sun receives light; the other side is in darkness.', noProj: 'use a torch and a ball.' },
    { sec: '1. CONSEQUENCES OF ROTATION', img: 'time_zones_big.png', caption: 'Time zones of the world.', q: 'Why is the time different in different countries?', a: 'Places to the east see the Sun first, so they are ahead in time.', noProj: 'compare the time in Garoua and Paris.' },
    { sec: '2. REVOLUTION', img: 'revolution.gif', caption: 'Animation: the Earth moves around the Sun.', q: 'How long does the Earth take to go once around the Sun?', a: '365¼ days, which is one year.', noProj: 'walk around a chair holding a ball.' },
    { sec: '2. CONSEQUENCES OF REVOLUTION', img: 'overhead_sun_big.png', caption: 'The overhead Sun during the year.', q: 'On which dates is the Sun overhead at the Equator?', a: 'On 21 March and 23 September (the equinoxes).', noProj: 'draw the tropics and the Equator.' },
  ],
  summary: [
    D([['Rotation:', 'It is the turning of the Earth on its axis from west to east in 24 hours.'],
      ['Revolution:', 'It is the movement of the Earth around the Sun in 365¼ days.'],
      ['Axis:', 'It is the imaginary line through the Earth from the North Pole to the South Pole.']]),
    { title: '1. Consequences of Rotation', intro: 'The rotation of the Earth has the following consequences:',
      items: [['Day and night:', 'The side of the Earth facing the Sun has day, and the other side has night.', 'rotation_mid.png', 'day and night'],
        ['Sunrise and sunset:', 'The Sun seems to rise in the east and to set in the west.', 'f4_sunrise.jpg', 'sunrise'],
        ['Time differences:', 'Places to the east are ahead in time: 1 hour for every 15° of longitude.', 'time_zones_big.png', 'time zones of the world'],
        ['Deflection of winds:', 'Winds and ocean currents are turned to the right in the Northern Hemisphere and to the left in the Southern Hemisphere.', 'planetary_winds_big.png', 'planetary winds']] },
    { title: '2. Consequences of Revolution', intro: 'The revolution of the Earth has the following consequences:',
      items: [['Seasons:', 'Revolution and the tilt of the axis cause the seasons of the year.', 'four_seasons_big.png', 'the four seasons of temperate lands'],
        ['Equinoxes:', 'On 21 March and 23 September, the Sun is overhead at the Equator. Day and night are equal everywhere.', 'overhead_sun_big.png', 'the overhead Sun during the year'],
        ['Solstices:', 'On 21 June the Sun is overhead at the Tropic of Cancer. On 22 December it is overhead at the Tropic of Capricorn.'],
        ['Length of day and night:', 'Days are longer in summer and shorter in winter, except at the Equator.'],
        ['Leap year:', 'Every fourth year has 366 days to use the extra quarter days.']] },
  ],
  evaluation: [['Give two consequences of rotation.', 'Day and night; time differences between places.'], ['What is an equinox?', 'A day when the Sun is overhead at the Equator and day and night are equal everywhere.']],
  remediation: ['The turning of the Earth on its axis is ______.', 'One revolution takes ______ days.', 'On 21 June the Sun is overhead at the Tropic of ______.'],
  remediationAnswers: '1. rotation 2. 365¼ 3. Cancer',
  homework: 'It is 12:00 in London (0°). What time is it in Garoua (15° E)? Explain your answer.',
  hwAnswer: 'Garoua is 15° east of London, so it is 1 hour ahead: 12:00 + 1 hour = 13:00.',
  bilingual: [['Rotation', 'La rotation'], ['Revolution', 'La révolution'], ['Axis', "L'axe"], ['Season', 'La saison'], ['Equinox', "L'équinoxe"], ['Solstice', 'Le solstice']],
});

L.push({ kind: 'Practical Work', no: 3, title: 'Calculation of Time', subtopic: 'The Earth: A Planet in the Solar System',
  notions: 'Local time, standard time, GMT, time zone, difference of longitude.',
  focus: 'Theoretical basis: revision of local and standard time. Practical exercise: calculation of local time; calculation of the local time of a place from GMT; basis of carving out time zones. Contextualisation: establish Cameroon\'s standard time compared with other areas.',
  competence: 'Learners are able to calculate the time of places using longitude and time zones.',
  objectives: ['Recall local time, standard time and GMT.', 'Calculate the local time of a place from its longitude or from GMT.', 'Compare the standard time of Cameroon with other countries.'],
  recall: ['The Earth turns 360° in 24 hours.', 'Places to the east are ahead in time.', 'Cameroon uses GMT + 1.'],
  situation: 'A football match starts at 18:00 in London. Moussa wants to watch it on television in Garoua. He asks his friends: "At what time will the match start in Cameroon?" None of them can calculate it.',
  sitQA: [['What is the problem in the situation?', 'Moussa and his friends do not know how to calculate the time of the match in Cameroon.'], ['Which information does he need?', 'The time difference between London and Cameroon.'], ['How can he find it?', 'By using the longitudes or the time zones.']],
  justification: 'This practical work helps us to calculate the time in other places of the world.',
  action: 'Check the time difference before calling or travelling to another country.',
  activities: [
    { sec: '1. REVISION', img: 'time_line_big.png', caption: 'Time and longitude.', q: 'The Earth turns 360° in 24 hours. How many degrees does it turn in one hour?', a: '360 ÷ 24 = 15° per hour, so 1° takes 4 minutes.', noProj: 'write the calculation on the board.' },
    { sec: '2. LOCAL TIME', img: 'time_calc_big.png', caption: 'A worked example.', q: 'It is 12:00 at 0°. What is the local time at 30° E?', a: '30 × 4 min = 120 min = 2 hours; the place is to the east, so 12:00 + 2 h = 14:00.', noProj: 'write the steps on the board.' },
    { sec: '2. LOCAL TIME FROM GMT', img: 'time_line_big.png', caption: 'East is ahead, west is behind.', q: 'It is 10:00 GMT. What is the local time at 45° W?', a: '45 × 4 = 180 min = 3 hours; the place is to the west, so 10:00 − 3 h = 07:00.', noProj: 'draw a line with 0° in the middle.' },
    { sec: '3. TIME ZONES', img: 'time_zones_big.png', caption: 'Time zones of the world.', q: 'Why was the world divided into time zones?', a: 'To avoid a different time in every town: each zone of about 15° uses the same standard time.', noProj: 'show the zones on a world map.' },
    { sec: '4. CAMEROON\'S STANDARD TIME', img: 'f4_worldclocks.jpg', caption: 'Clocks showing the time in different cities.', q: 'When it is 12:00 in Garoua (GMT + 1), what time is it in London (GMT)?', a: '11:00.', noProj: 'draw two clocks on the board.' },
  ],
  summary: [
    D([['Local time:', 'It is the time of a place given by the position of the Sun.'],
      ['Standard time:', 'It is the official time used in a whole country or time zone.'],
      ['GMT:', 'It is Greenwich Mean Time, the local time of the Greenwich Meridian (0°).']]),
    { title: '1. Rules for Calculating Local Time', intro: 'We calculate local time with the following rules:',
      items: [['Rule 1:', 'The Earth turns 15° in one hour, so 1° of longitude equals 4 minutes.', 'time_line_big.png', 'time and longitude'],
        ['Rule 2:', 'We add time for places to the east and remove time for places to the west.'],
        ['Rule 3:', 'We find the difference of longitude, multiply it by 4 minutes and change it into hours.']] },
    { title: '2. Calculating Local Time from GMT', intro: 'We calculate local time from GMT as in the following examples:',
      items: [['Example to the east:', 'It is 12:00 GMT. At 30° E, the difference is 30 × 4 = 120 min = 2 h, so the local time is 14:00.', 'time_calc_big.png', 'calculating local time'],
        ['Example to the west:', 'It is 10:00 GMT. At 45° W, the difference is 45 × 4 = 180 min = 3 h, so the local time is 07:00.']] },
    { title: '3. Basis of Time Zones', intro: 'Time zones are carved out as follows:',
      items: [['24 time zones:', 'The world is divided into 24 time zones of about 15° each, one for each hour.', 'time_zones_big.png', 'time zones of the world'],
        ['Standard time:', 'All places in one zone use the same standard time.'],
        ['Boundaries:', 'The boundaries of the zones often follow the borders of countries.']] },
    { title: '4. Cameroon\'s Standard Time and Other Areas', intro: 'When it is 12:00 in Cameroon (GMT + 1), the time elsewhere is the following:',
      items: [['London (GMT):', 'It is 11:00.', 'f4_worldclocks.jpg', 'clocks in different cities'],
        ['Nigeria and Chad (GMT + 1):', 'It is 12:00, the same time as Cameroon.'],
        ['Dubai (GMT + 4):', 'It is 15:00.'],
        ['New York (GMT − 5):', 'It is 06:00.']] },
  ],
  evaluation: [['It is 08:00 GMT. What is the local time at 60° E?', '60 × 4 = 240 min = 4 h; 08:00 + 4 h = 12:00.'], ['A match starts at 18:00 in London (GMT). What time is it in Cameroon?', '19:00, because Cameroon is GMT + 1.']],
  remediation: ['The Earth turns ______° in one hour.', '1° of longitude equals ______ minutes.', 'Places to the ______ are ahead in time.'],
  remediationAnswers: '1. 15 2. 4 3. east',
  homework: 'When it is 09:00 in Garoua (GMT + 1), what time is it in New York (GMT − 5)?',
  hwAnswer: 'Garoua is 6 hours ahead of New York (+1 − (−5) = 6), so it is 09:00 − 6 h = 03:00 in New York.',
  bilingual: [['Time', "L'heure"], ['Local time', "L'heure locale"], ['Time zone', 'Le fuseau horaire'], ['Clock', "L'horloge"], ['East', "L'est"], ['West', "L'ouest"]],
});

module.exports = { B, L };
