// FORM 1 — Module 3: Protection from the Wrath of Nature (2023 national syllabus): L7, L8, L9, FS1, PW6, L10, L11, L12, L13, FS2
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F1', code: 'M3', folder: '', module: 'Module 3: Protection from the Wrath of Nature', topicDefault: 'Protection against the Wrath of Nature', branch: 'Climatic Disturbances',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 1, Module 3: Protection from the Wrath of Nature.'] };
const L = [];

L.push({ no: 7, title: 'The Atmosphere', subtopic: 'Climatic Disturbances',
  notions: 'Atmosphere, ozone layer, global warming, greenhouse effect.',
  focus: 'Definition, composition and structure of the atmosphere.',
  competence: 'Learners are able to describe the composition and layers of the atmosphere and explain why it must be protected.',
  objectives: ['Define the atmosphere.', 'Give the composition of the atmosphere.', 'Sketch and describe the structure of the atmosphere.'],
  recall: ['The Earth is covered by land, water and air.', 'We breathe oxygen.', 'Clouds and rain form in the sky.'],
  situation: 'During a flight from Garoua to Douala, Salif looks through the window. The plane is above the clouds and the sky is very clear. The pilot says the plane flies at 10 km in the lowest layer of the air.',
  sitQA: [['What is the problem in the situation?', 'Salif wants to know the layers of the air around the Earth.'], ['Where are the clouds?', 'Below the plane, in the lowest layer.'], ['What is the name of the layer of air around the Earth?', 'The atmosphere.']],
  justification: 'This lesson helps us to know the air that protects life on the Earth.',
  action: 'Protect the air: avoid burning plastics and use products without CFCs.',
  activities: [
    { sec: '1. MEANING', img: 'f4_planewindow.jpg', caption: 'The sky seen from an aeroplane.', q: 'What is the atmosphere?', a: 'It is the layer of air that surrounds the Earth.', noProj: 'ask learners to breathe deeply: we breathe the atmosphere.' },
    { sec: '2. COMPOSITION', img: 'gases_pie_big.png', caption: 'The gases of the air.', q: 'Which two gases form most of the air?', a: 'Nitrogen (about 78 %) and oxygen (about 21 %).', noProj: 'draw a pie chart on the board.' },
    { sec: '3. STRUCTURE', img: 'atmosphere_big.png', caption: 'The layers of the atmosphere.', q: 'Name the four layers of the atmosphere from the ground upwards.', a: 'Troposphere, stratosphere, mesosphere and thermosphere.', noProj: 'draw four layers on the board.' },
    { sec: '3. STRUCTURE', img: 'f4_cumulonimbus.jpg', caption: 'A big storm cloud.', q: 'In which layer do clouds, rain and wind occur?', a: 'In the troposphere, the lowest layer.', noProj: 'describe the clouds seen today.' },
    { sec: '3. THE OZONE LAYER', img: 'f4_ozonehole.jpg', caption: 'The ozone hole over the South Pole.', q: 'Why is the ozone layer important?', a: 'It stops the harmful rays of the Sun that cause skin cancer and eye diseases.', noProj: 'explain the hole in the ozone layer.' },
  ],
  summary: [
    { title: '1. Meaning of the Atmosphere', intro: 'The atmosphere is defined as follows:',
      items: [['Atmosphere:', 'It is the layer of air that surrounds the Earth and protects life.']] },
    { title: '2. Composition of the Atmosphere', intro: 'The atmosphere is made up of the following elements:',
      items: [['Nitrogen:', 'It forms about 78 % of the air.'],
        ['Oxygen:', 'It forms about 21 % of the air and people and animals breathe it.'],
        ['Other gases:', 'Carbon dioxide, water vapour and ozone form about 1 % of the air.']],
      draw: { img: 'gases_pie_big.png', caption: 'the gases of the air' } },
    { title: '3. Structure of the Atmosphere', intro: 'The atmosphere has the following layers:',
      items: [['Troposphere:', 'It is the lowest layer, up to about 12 km, where weather occurs.'],
        ['Stratosphere:', 'It lies between 12 and 50 km and contains the ozone layer.'],
        ['Mesosphere:', 'It lies between 50 and 85 km and is very cold.'],
        ['Thermosphere:', 'It is the upper layer, above 85 km.']],
      draw: { img: 'atmosphere_big.png', caption: 'the layers of the atmosphere' } },
  ],
  evaluation: [['What is the atmosphere?', 'The layer of air around the Earth.'], ['In which layer is the ozone layer?', 'In the stratosphere.']],
  remediation: ['The gas that forms 78 % of the air is ______.', 'Weather occurs in the ______.', 'The ozone layer is in the ______.'],
  remediationAnswers: '1. nitrogen 2. troposphere 3. stratosphere',
  homework: 'Draw and label the four layers of the atmosphere.',
  hwAnswer: 'From the ground: troposphere (0–12 km, weather), stratosphere (12–50 km, ozone layer), mesosphere (50–85 km), thermosphere (above 85 km).',
  bilingual: [['Atmosphere', "L'atmosphère"], ['Air', "L'air"], ['Oxygen', "L'oxygène"], ['Layer', 'La couche'], ['Ozone', "L'ozone"], ['Cloud', 'Le nuage']],
});

L.push({ no: 8, title: 'Atmospheric Circulation', subtopic: 'Climatic Disturbances',
  notions: 'Pressure, high pressure, low pressure, wind, pressure belts, planetary winds.',
  focus: 'Pressure; types of pressure (high and low); winds and pressure belts.',
  competence: 'Learners are able to explain how differences in pressure create winds and describe the main pressure belts and winds.',
  objectives: ['Define atmospheric pressure.', 'Distinguish high and low pressure.', 'Describe the pressure belts and the planetary winds.'],
  recall: ['The atmosphere is made of air.', 'The Sun heats the Earth more at the Equator.', 'Hot air rises.'],
  situation: 'In January, the Harmattan blows dust over Garoua from the north-east. In July, a moist wind from the south-west brings rain. Hadiza asks why the wind changes direction with the seasons.',
  sitQA: [['What is the problem in the situation?', 'Hadiza does not know why the wind changes direction.'], ['Which dry wind blows in January?', 'The Harmattan.'], ['What causes winds?', 'Differences in air pressure.']],
  justification: 'This lesson helps us to understand the winds that bring rain and the dry season.',
  action: 'Protect yourself from Harmattan dust: cover your nose and drink water.',
  activities: [
    { sec: '1. PRESSURE', img: 'f4_barometer.jpg', caption: 'A barometer.', q: 'What does a barometer measure?', a: 'Atmospheric pressure, the weight of the air.', noProj: 'describe a barometer.' },
    { sec: '2. HIGH AND LOW PRESSURE', img: 'convection.gif', caption: 'Animation: hot air rises, cool air sinks.', q: 'Where is pressure low: where air rises or where air sinks?', a: 'Pressure is low where hot air rises and high where cool air sinks.', noProj: 'show smoke rising from a fire.' },
    { sec: '3. WINDS', img: 'f4_windsock.jpg', caption: 'A windsock.', q: 'Wind blows from which pressure to which pressure?', a: 'From high pressure to low pressure.', noProj: 'let air out of a balloon.' },
    { sec: '3. PRESSURE BELTS', img: 'pressure_belts_big.png', caption: 'Pressure belts and planetary winds.', q: 'Which winds blow from the tropics towards the Equator?', a: 'The trade winds.', noProj: 'draw the belts on the board.' },
    { sec: '3. WINDS OF CAMEROON', img: 'f2t_harmattan.jpg', caption: 'A dusty sky in the dry season.', q: 'Where does the Harmattan come from, and what does it bring?', a: 'From the Sahara in the north-east; it brings dry, dusty air.', noProj: 'describe the Harmattan season.' },
  ],
  summary: [
    D([['Atmospheric pressure:', 'It is the weight of the air on the surface of the Earth.'],
      ['Wind:', 'It is air moving from high pressure to low pressure.']]),
    { title: '1. Types of Pressure', intro: 'There are two types of pressure:',
      items: [['Low pressure:', 'It forms where hot air rises, as at the Equator.'],
        ['High pressure:', 'It forms where cool air sinks, as at the tropics and the poles.']] },
    { title: '2. Pressure Belts and Winds', intro: 'The main pressure belts and winds are the following:',
      items: [['Pressure belts:', 'The Equatorial Low, the Sub-tropical Highs, the Temperate Lows and the Polar Highs surround the Earth.'],
        ['Trade winds:', 'They blow from the sub-tropical highs towards the Equator.'],
        ['Westerlies:', 'They blow from the sub-tropical highs towards the temperate lows.'],
        ['Winds of Cameroon:', 'The dry Harmattan blows in the dry season and the moist south-west monsoon brings rain.']],
      draw: { img: 'pressure_belts_big.png', caption: 'pressure belts and planetary winds' } },
  ],
  evaluation: [['What is wind?', 'Air moving from high to low pressure.'], ['Name two winds that blow over Cameroon.', 'The Harmattan and the south-west monsoon.']],
  remediation: ['Pressure is measured with a ______.', 'Hot rising air gives ______ pressure.', 'The dry wind from the Sahara is the ______.'],
  remediationAnswers: '1. barometer 2. low 3. Harmattan',
  homework: 'Observe the wind for three days and write its direction and whether it is dry or moist.',
  hwAnswer: 'In the dry season the wind blows from the north-east and is dry and dusty (Harmattan); in the rainy season it blows from the south-west and is moist.',
  bilingual: [['Pressure', 'La pression'], ['Wind', 'Le vent'], ['Barometer', 'Le baromètre'], ['Trade winds', 'Les alizés'], ['Dust', 'La poussière'], ['Monsoon', 'La mousson']],
});

L.push({ no: 9, title: 'Atmospheric Disturbances', subtopic: 'Climatic Disturbances',
  notions: 'Atmospheric disturbance, cloud, thunderstorm, cyclone, dust storm, windward, leeward.',
  focus: 'Definition; types of clouds; types of disturbances (thunderstorms, cyclones, dust storms, torrential rain, drizzle); main areas; consequences.',
  competence: 'Learners are able to identify atmospheric disturbances, locate where they occur and adopt safe behaviour.',
  objectives: ['Define an atmospheric disturbance.', 'Identify the main types of clouds and disturbances.', 'Give their consequences and safety measures.'],
  recall: ['Weather occurs in the troposphere.', 'Winds blow from high to low pressure.', 'Clouds give rain.'],
  situation: 'In June, a violent storm with lightning and strong winds hits Garoua. Roofs are blown off and a tree falls on a house. Some people shelter under a big tree during the storm.',
  sitQA: [['What is the problem in the situation?', 'A violent storm causes damage and danger.'], ['Name two effects of the storm.', 'Roofs are blown off and a tree falls on a house.'], ['Is it safe to shelter under a tree?', 'No, lightning can strike tall trees.']],
  justification: 'This lesson helps us to know dangerous weather and how to protect ourselves.',
  action: 'During a storm, stay inside a building, away from trees and metal objects.',
  activities: [
    { sec: '1. TYPES OF CLOUDS', img: 'cloud_types_big.png', caption: 'The main types of clouds.', q: 'Name three types of clouds.', a: 'Cumulus, stratus and cirrus (also cumulonimbus).', noProj: 'draw the clouds on the board.' },
    { sec: '2. THUNDERSTORMS', img: 'f4_cumulonimbus.jpg', caption: 'A cumulonimbus cloud.', q: 'Which cloud gives thunderstorms?', a: 'The cumulonimbus, a tall dark cloud.', noProj: 'describe a storm cloud.' },
    { sec: '2. CYCLONES', img: 'f4_hurricane.jpg', caption: 'A tropical cyclone seen from space.', q: 'What is a tropical cyclone, and where does it occur?', a: 'A very violent storm with strong winds and heavy rain that forms over warm oceans, such as the Caribbean and the Indian Ocean.', noProj: 'point to the oceans on a map.' },
    { sec: '2. DUST STORMS', img: 'f2t_sandstorm.jpg', caption: 'A dust storm.', q: 'Where do dust storms occur in Cameroon, and when?', a: 'In the North and Far North, in the dry season.', noProj: 'describe a dusty day.' },
    { sec: '3. CONSEQUENCES', img: 'lsa_streetflood.jpg', caption: 'A flooded street after torrential rain.', q: 'Give two consequences of atmospheric disturbances.', a: 'Floods and destroyed houses (also deaths, fallen trees).', noProj: 'list the damage of a storm.' },
  ],
  summary: [
    D([['Atmospheric disturbance:', 'It is a sudden and violent change in the weather.'],
      ['Cloud:', 'It is a mass of tiny water drops or ice floating in the air.']]),
    { title: '1. Types of Clouds', intro: 'The main types of clouds are the following:',
      items: [['Cumulus:', 'They are white, puffy clouds of fine weather.'],
        ['Stratus:', 'They are grey layers of low clouds that give drizzle.'],
        ['Cirrus:', 'They are thin, high clouds made of ice.'],
        ['Cumulonimbus:', 'They are tall, dark clouds that give thunderstorms.']],
      draw: { img: 'cloud_types_big.png', caption: 'types of clouds' } },
    { title: '2. Types of Disturbances', intro: 'The main atmospheric disturbances are the following:',
      items: [['Thunderstorm:', 'It is a storm with lightning, thunder, strong wind and heavy rain.'],
        ['Cyclone:', 'It is a very violent storm that forms over warm tropical oceans.'],
        ['Dust storm:', 'It is a strong wind carrying dust, common in the north in the dry season.'],
        ['Torrential rain and drizzle:', 'Torrential rain is very heavy rain, while drizzle is very light rain.']] },
    { title: '3. Consequences and Safety', intro: 'Disturbances have the following consequences:',
      items: [['Consequences:', 'They cause floods, destroyed houses and crops, and loss of life.'],
        ['Safety:', 'People must shelter in buildings, avoid trees and follow weather warnings.']] },
  ],
  evaluation: [['Name three atmospheric disturbances.', 'Thunderstorm, cyclone and dust storm.'], ['Give one safety rule during a thunderstorm.', 'Stay inside a building, away from trees.']],
  remediation: ['The cloud that gives thunderstorms is the ______.', 'A violent storm over warm oceans is a ______.', 'Very light rain is ______.'],
  remediationAnswers: '1. cumulonimbus 2. cyclone 3. drizzle',
  homework: 'Write three safety rules for your family during a thunderstorm.',
  hwAnswer: 'Stay inside a building; do not shelter under a tree; unplug electrical appliances and stay away from water and metal objects.',
  bilingual: [['Storm', "L'orage"], ['Lightning', "L'éclair"], ['Thunder', 'Le tonnerre'], ['Cyclone', 'Le cyclone'], ['Dust storm', 'La tempête de poussière'], ['Drizzle', 'La bruine']],
});

L.push({ kind: 'Further Study', no: 1, title: 'Atmospheric Disturbances in Cameroon', subtopic: 'Climatic Disturbances',
  notions: 'Thunderstorm, torrential rain, flood, dust storm, heat wave, adaptation, mitigation.',
  focus: 'Identification, manifestations, consequences, adaptation and mitigation strategies of atmospheric disturbances in Cameroon.',
  competence: 'Learners are able to identify the atmospheric disturbances of Cameroon and propose adaptation measures.',
  objectives: ['Identify the atmospheric disturbances of Cameroon.', 'Describe their manifestations and consequences.', 'Propose adaptation and mitigation strategies.'],
  recall: ['Thunderstorms, cyclones and dust storms are disturbances.', 'The Harmattan blows in the dry season.', 'Heavy rain can cause floods.'],
  situation: 'In August, heavy rain floods several quarters of Garoua and Maroua. In March, a heat wave makes the nights very hot and many people fall sick.',
  sitQA: [['What is the problem in the situation?', 'Floods and heat waves affect people in the north.'], ['When do floods occur?', 'In the rainy season, in August.'], ['When do heat waves occur?', 'In the hot dry season, around March.']],
  justification: 'This further study helps us to face the dangerous weather of Cameroon.',
  action: 'Keep gutters clean, drink enough water in the hot season and follow weather warnings.',
  activities: [
    { sec: '1. IDENTIFICATION', img: 'cameroon_climate_big.png', caption: 'The climates of Cameroon.', q: 'Which disturbances are common in the north and which in the south of Cameroon?', a: 'North: dust storms, heat waves and floods after heavy storms. South: torrential rain, thunderstorms and floods.', noProj: 'draw the map of Cameroon.' },
    { sec: '2. MANIFESTATIONS', img: 'f4_heavyrain.jpg', caption: 'Torrential rain in a town.', q: 'How do we recognise torrential rain?', a: 'Very heavy rain in a short time, with water running in the streets.', noProj: 'describe the last heavy rain.' },
    { sec: '2. MANIFESTATIONS', img: 'f2t_harmattan.jpg', caption: 'A dusty sky.', q: 'What are the signs of the Harmattan and dust storms?', a: 'A grey, dusty sky, dry air, cold mornings and poor visibility.', noProj: 'describe a Harmattan morning.' },
    { sec: '3. CONSEQUENCES', img: 'f4_floodvillage.jpg', caption: 'A flooded village.', q: 'Give three consequences of floods in Cameroon.', a: 'Houses and crops are destroyed, people die or lose their homes, and diseases like cholera spread.', noProj: 'recall floods in Garoua or Maroua.' },
    { sec: '4. ADAPTATION AND MITIGATION', img: 'f2t_tree_planting_sahel.jpg', caption: 'Planting trees in the Sahel.', q: 'Give three measures against these disturbances.', a: 'Clean gutters and build drains, plant trees and windbreaks, and build strong houses away from rivers.', noProj: 'list measures for the family.' },
  ],
  summary: [
    { title: '1. Identification and Manifestations', intro: 'Cameroon faces the following atmospheric disturbances:',
      items: [['Thunderstorms and torrential rain:', 'They bring lightning, strong winds and heavy rain in the rainy season.'],
        ['Floods:', 'They follow heavy rain in towns and valleys, as in Garoua, Maroua and Douala.'],
        ['Dust storms and the Harmattan:', 'They bring dust and dry air to the north in the dry season.'],
        ['Heat waves:', 'Very hot days and nights occur in the north around March and April.']] },
    { title: '2. Consequences', intro: 'These disturbances have the following consequences:',
      items: [['Material damage:', 'Houses, roads, bridges and crops are destroyed.'],
        ['Human consequences:', 'People die or fall sick with cholera, meningitis or respiratory diseases.']] },
    { title: '3. Adaptation and Mitigation', intro: 'The following measures reduce the effects of disturbances:',
      items: [['Building:', 'People build strong houses away from rivers and clean the gutters.'],
        ['Environment:', 'People plant trees and windbreaks to reduce wind and dust.'],
        ['Warnings:', 'The weather service warns people before dangerous weather.']] },
  ],
  evaluation: [['Name three atmospheric disturbances of Cameroon.', 'Thunderstorms, floods and dust storms (also heat waves).'], ['Give two measures against floods.', 'Clean gutters and avoid building near rivers.']],
  remediation: ['Very heavy rain is ______ rain.', 'Dust storms occur in the ______ season.', 'Cholera often follows ______.'],
  remediationAnswers: '1. torrential 2. dry 3. floods',
  homework: 'Ask an elder about a flood or a violent storm in your town and write what happened.',
  hwAnswer: 'Answers vary. Example: in 2012 the Benue flooded quarters of Garoua; houses and farms were destroyed and families moved to schools.',
  bilingual: [['Flood', "L'inondation"], ['Heat wave', 'La vague de chaleur'], ['Gutter', 'Le caniveau'], ['Warning', "L'alerte"], ['Damage', 'Les dégâts'], ['Shelter', "L'abri"]],
});

L.push({ kind: 'Practical Work', no: 6, title: 'Mechanisms of Rain Formation', subtopic: 'Climatic Disturbances',
  notions: 'Rainfall, evaporation, condensation, precipitation, relief (orographic) rainfall, windward, leeward.',
  focus: 'Definition of rainfall; drawing step by step the general mechanism of rainfall formation; drawing the mechanism of orographic rainfall (Mount Cameroon area).',
  competence: 'Learners are able to draw and explain step by step how rain forms.',
  objectives: ['Define rainfall.', 'Draw step by step the general mechanism of rain formation.', 'Draw the mechanism of relief rainfall on Mount Cameroon.'],
  recall: ['The Sun heats water.', 'Clouds are made of water drops.', 'Mount Cameroon is very high.'],
  situation: 'Debundscha, at the foot of Mount Cameroon, is one of the wettest places in the world, while places on the other side of the mountain receive much less rain. The class wants to explain this.',
  sitQA: [['What is the problem in the situation?', 'We must explain why one side of the mountain is so wet.'], ['Where does the moist wind come from?', 'From the sea (Atlantic Ocean).'], ['What happens to air that rises up a mountain?', 'It cools and forms clouds and rain.']],
  justification: 'This practical work helps us to understand and draw how rain is formed.',
  action: 'Draw neat labelled diagrams with arrows showing each step.',
  activities: [
    { sec: '1. MEANING', img: 'f4_heavyrain.jpg', caption: 'Rain falling.', q: 'What is rainfall?', a: 'It is water that falls from clouds as drops.', noProj: 'describe rain.' },
    { sec: '2. GENERAL MECHANISM', img: 'water_cycle.gif', caption: 'Animation: evaporation, condensation and rain.', q: 'Give the three main steps of rain formation.', a: 'Evaporation, condensation into clouds, and precipitation.', noProj: 'boil water and hold a cold plate above it.' },
    { sec: '2. GENERAL MECHANISM', img: 'convection.gif', caption: 'Animation: convectional rain.', q: 'Why does rising air form clouds?', a: 'Air cools as it rises, and the water vapour condenses into drops.', noProj: 'draw arrows rising above hot ground.' },
    { sec: '3. RELIEF RAINFALL', img: 'rainfall_types_big.png', caption: 'Types of rainfall.', q: 'Which side of a mountain receives more rain: the windward or the leeward side?', a: 'The windward side, facing the wind; the leeward side is dry (rain shadow).', noProj: 'draw a mountain with the wind.' },
    { sec: '3. MOUNT CAMEROON', img: 'lsa_mtcameroon.jpg', caption: 'Mount Cameroon.', q: 'Explain why Debundscha is very wet.', a: 'Moist sea winds are forced up Mount Cameroon, cool and give heavy rain on the windward side.', noProj: 'show Mount Cameroon on the map.' },
  ],
  summary: [
    D([['Rainfall:', 'It is water that falls from clouds as drops.'],
      ['Condensation:', 'It is the change of water vapour into water drops when air cools.']]),
    { title: '1. General Mechanism of Rain Formation', intro: 'Rain forms in the following steps:',
      items: [['Step 1 – Evaporation:', 'The Sun heats water from seas, rivers and plants and turns it into vapour.'],
        ['Step 2 – Rising and cooling:', 'The warm moist air rises and cools.'],
        ['Step 3 – Condensation:', 'The vapour condenses into tiny drops that form clouds.'],
        ['Step 4 – Precipitation:', 'The drops join, become heavy and fall as rain.']],
      draw: { img: 'water_cycle_last.png', caption: 'the formation of rain' } },
    { title: '2. Relief (Orographic) Rainfall', intro: 'Relief rainfall on Mount Cameroon forms as follows:',
      items: [['Windward side:', 'Moist winds from the sea are forced up the mountain, cool and give heavy rain.'],
        ['Leeward side:', 'The air descends on the other side, warms up and gives little rain (rain shadow).']],
      draw: { img: 'rainfall_types_big.png', caption: 'types of rainfall' } },
  ],
  evaluation: [['Give the four steps of rain formation.', 'Evaporation, rising and cooling, condensation, precipitation.'], ['Why is the windward side of Mount Cameroon wet?', 'Moist air is forced up, cools and gives rain.']],
  remediation: ['Water turning into vapour is ______.', 'Vapour turning into drops is ______.', 'The dry side of a mountain is the ______ side.'],
  remediationAnswers: '1. evaporation 2. condensation 3. leeward',
  homework: 'Draw and label the mechanism of relief rainfall on Mount Cameroon.',
  hwAnswer: 'The drawing shows the sea, moist wind arrows rising up the windward slope, clouds and rain on that slope, and dry descending air on the leeward slope (rain shadow).',
  bilingual: [['Rain', 'La pluie'], ['Evaporation', "L'évaporation"], ['Condensation', 'La condensation'], ['Mountain', 'La montagne'], ['Windward', 'Au vent'], ['Leeward', 'Sous le vent']],
});

L.push({ no: 10, title: 'Climate Change and its Consequences', subtopic: 'Climatic Disturbances',
  notions: 'Climate change, global warming, greenhouse gases, adaptation, mitigation.',
  focus: 'General causes, manifestations, consequences, adaptation and mitigation of climate change.',
  competence: 'Learners are able to explain climate change and adopt behaviour that reduces it.',
  objectives: ['Give the causes of climate change.', 'Describe its manifestations and consequences.', 'Propose adaptation and mitigation measures.'],
  recall: ['The atmosphere contains carbon dioxide.', 'Burning fuel gives smoke.', 'Trees take in carbon dioxide.'],
  situation: 'Grandfather Oumarou says that when he was young, the rains in Garoua started in April and were regular. Today they start late, stop suddenly and the heat is stronger. He wonders what is happening.',
  sitQA: [['What is the problem in the situation?', 'The climate of Garoua is changing.'], ['Give two changes the grandfather notices.', 'The rains start late and the heat is stronger.'], ['What is this phenomenon called?', 'Climate change.']],
  justification: 'This lesson helps us to understand climate change and how to fight it.',
  action: 'Plant trees, save energy and avoid burning waste.',
  activities: [
    { sec: '1. CAUSES', img: 'f4_exhaust.jpg', caption: 'Smoke from factories.', q: 'Give two human causes of climate change.', a: 'Burning fuels in factories and cars, and cutting forests.', noProj: 'list sources of smoke in town.' },
    { sec: '1. CAUSES', img: 'greenhouse_big.png', caption: 'The greenhouse effect.', q: 'How do greenhouse gases warm the Earth?', a: 'They trap the heat of the Sun in the atmosphere, like the glass of a greenhouse.', noProj: 'compare with a closed car in the sun.' },
    { sec: '2. MANIFESTATIONS', img: 'co2_temp_big.png', caption: 'Carbon dioxide and temperature.', q: 'What happens to the temperature of the Earth as carbon dioxide increases?', a: 'The temperature rises (global warming).', noProj: 'draw a rising line on the board.' },
    { sec: '3. CONSEQUENCES', img: 'f2t_drought.jpg', caption: 'Dry, cracked soil.', q: 'Give three consequences of climate change for farmers.', a: 'Irregular rains, droughts and floods, and poor harvests.', noProj: 'ask farmers\' children.' },
    { sec: '4. ADAPTATION AND MITIGATION', img: 'mit_adapt_big.png', caption: 'Mitigation and adaptation.', q: 'Give one mitigation and one adaptation measure.', a: 'Mitigation: plant trees or use solar energy. Adaptation: grow drought-resistant seeds.', noProj: 'list actions for the school.' },
  ],
  summary: [
    D([['Climate change:', 'It is a long-term change in the average climate of a place or of the world.'],
      ['Greenhouse gases:', 'They are gases, such as carbon dioxide, that trap heat in the atmosphere.']]),
    { title: '1. Causes', intro: 'Climate change has the following causes:',
      items: [['Burning fuels:', 'Burning petrol, coal and wood releases carbon dioxide.'],
        ['Deforestation:', 'Cutting trees leaves fewer plants to absorb carbon dioxide.'],
        ['Natural causes:', 'Volcanic eruptions and changes in the Sun also change the climate.']],
      draw: { img: 'greenhouse_big.png', caption: 'the greenhouse effect' } },
    { title: '2. Manifestations and Consequences', intro: 'Climate change shows itself and affects people as follows:',
      items: [['Global warming:', 'The average temperature of the Earth is rising.'],
        ['Irregular rains:', 'Rains start late, stop early and bring droughts and floods.'],
        ['Consequences:', 'Harvests fall, water becomes scarce and diseases increase.']] },
    { title: '3. Adaptation and Mitigation', intro: 'People respond to climate change as follows:',
      items: [['Mitigation:', 'We reduce greenhouse gases by planting trees and using solar energy.'],
        ['Adaptation:', 'We adjust by using drought-resistant seeds, storing water and changing the farming calendar.']] },
  ],
  evaluation: [['Give two causes of climate change.', 'Burning fuels and deforestation.'], ['Distinguish mitigation and adaptation.', 'Mitigation reduces the causes; adaptation adjusts to the effects.']],
  remediation: ['The rise of the Earth\'s temperature is global ______.', 'Carbon dioxide is a ______ gas.', 'Planting trees is a ______ measure.'],
  remediationAnswers: '1. warming 2. greenhouse 3. mitigation',
  homework: 'Propose three actions your family can take against climate change.',
  hwAnswer: 'Plant trees around the house; switch off lights and use solar lamps; stop burning rubbish and use improved stoves that need less wood.',
  bilingual: [['Climate change', 'Le changement climatique'], ['Global warming', 'Le réchauffement climatique'], ['Greenhouse gas', 'Le gaz à effet de serre'], ['Drought', 'La sécheresse'], ['Adaptation', "L'adaptation"], ['Mitigation', "L'atténuation"]],
});

L.push({ no: 11, title: 'The Internal Structure of the Earth', subtopic: 'Movements of the Earth\'s Crust',
  notions: 'Crust, mantle, core, lithosphere.',
  focus: 'The crust, the mantle and the core (identification and illustration only).',
  competence: 'Learners are able to identify and draw the layers of the Earth.',
  objectives: ['Identify the three main layers of the Earth.', 'Describe each layer briefly.', 'Draw the internal structure of the Earth.'],
  recall: ['The Earth is round like a ball.', 'Volcanoes bring hot rock from inside the Earth.', 'An egg has a shell, white and yolk.'],
  situation: 'Moussa cuts a boiled egg in two. He sees a thin shell, the white and a yellow yolk in the centre. His teacher tells him that the Earth also has layers like the egg.',
  sitQA: [['What is the problem in the situation?', 'Moussa wants to know the layers inside the Earth.'], ['Which part of the egg is like the crust?', 'The shell.'], ['Which part is like the core?', 'The yolk.']],
  justification: 'This lesson helps us to know what is inside our planet.',
  action: 'Use simple models such as an egg or an onion to explain the layers of the Earth.',
  activities: [
    { sec: '1. THE CRUST', img: 'f2t_laterite.jpg', caption: 'Rocks and soil of the crust.', q: 'What is the crust?', a: 'It is the thin, solid outer layer of the Earth on which we live.', noProj: 'show a stone.' },
    { sec: '2. THE LAYERS', img: 'earth_layers_big.png', caption: 'The layers of the Earth.', q: 'Name the three main layers of the Earth from the surface to the centre.', a: 'The crust, the mantle and the core.', noProj: 'draw three circles.' },
    { sec: '2. THE MANTLE', img: 'f4_eruption.jpg', caption: 'Lava coming out of a volcano.', q: 'Where does the hot lava of volcanoes come from?', a: 'From the hot mantle under the crust.', noProj: 'describe Mount Cameroon erupting.' },
    { sec: '2. THE CORE', img: 'earth_depth.gif', caption: 'Animation: a journey to the centre of the Earth.', q: 'What is the core made of?', a: 'Mainly iron and nickel, very hot; the outer core is liquid and the inner core is solid.', noProj: 'compare with the yolk of an egg.' },
    { sec: '3. ILLUSTRATION', img: 'earth_disc_big.png', caption: 'Boundaries between the layers.', q: 'Which layer is the thinnest?', a: 'The crust.', noProj: 'draw a cross-section of the Earth.' },
  ],
  summary: [
    D([['Crust:', 'It is the thin, solid outer layer of the Earth.'],
      ['Lithosphere:', 'It is the crust and the top part of the mantle, which form the rigid plates.']]),
    { title: '1. The Main Layers of the Earth', intro: 'The Earth has the following main layers:',
      items: [['Crust:', 'It is the thin, rocky layer on which we live, from about 5 to 70 km thick.'],
        ['Mantle:', 'It is a thick layer of very hot rock, about 2,900 km thick.'],
        ['Outer core:', 'It is a layer of liquid iron and nickel.'],
        ['Inner core:', 'It is the solid, very hot centre of the Earth.']],
      draw: { img: 'earth_layers_big.png', caption: 'the internal structure of the Earth' } },
  ],
  evaluation: [['Name the three main layers of the Earth.', 'Crust, mantle and core.'], ['Which layer do we live on?', 'The crust.']],
  remediation: ['The outer layer of the Earth is the ______.', 'The layer under the crust is the ______.', 'The centre of the Earth is the ______.'],
  remediationAnswers: '1. crust 2. mantle 3. core',
  homework: 'Draw and label the internal structure of the Earth.',
  hwAnswer: 'A circle with, from the outside: crust (thin), mantle (thick), outer core (liquid) and inner core (solid) in the centre.',
  bilingual: [['Crust', "L'écorce terrestre"], ['Mantle', 'Le manteau'], ['Core', 'Le noyau'], ['Layer', 'La couche'], ['Rock', 'La roche'], ['Iron', 'Le fer']],
});

L.push({ no: 12, title: 'Plate Movements', subtopic: 'Movements of the Earth\'s Crust',
  notions: 'Plate, tectonic movement, plate boundary.',
  focus: 'Definition; types of plates; types of plate movements.',
  competence: 'Learners are able to identify the plates on a world map and describe how they move.',
  objectives: ['Define a plate.', 'Identify the major plates on a world map.', 'Describe the types of plate movements.'],
  recall: ['The Earth has a crust, a mantle and a core.', 'The mantle is very hot.', 'Earthquakes shake the ground.'],
  situation: 'Aïssatou sees on a map that the coasts of Africa and South America fit together like pieces of a puzzle. Her teacher says that the crust is broken into pieces that move slowly.',
  sitQA: [['What is the problem in the situation?', 'Aïssatou wants to know why the continents fit together.'], ['What are the pieces of the crust called?', 'Plates.'], ['Do the plates move quickly?', 'No, very slowly, a few centimetres per year.']],
  justification: 'This lesson helps us to understand the movements of the Earth\'s crust.',
  action: 'Locate earthquake and volcano zones on a map of plates.',
  activities: [
    { sec: '1. MEANING', img: 'jigsaw.gif', caption: 'Animation: the continents fit like a puzzle.', q: 'What do the fitting coasts of Africa and South America suggest?', a: 'That the continents were once joined and have moved apart.', noProj: 'cut out a paper map.' },
    { sec: '2. TYPES OF PLATES', img: 'plates_big.png', caption: 'The major plates of the world.', q: 'On which plate is Cameroon?', a: 'On the African Plate.', noProj: 'draw the plates on a world map.' },
    { sec: '2. TYPES OF PLATES', img: 'plates_big.png', caption: 'Oceanic and continental plates.', q: 'Name two other major plates.', a: 'The Pacific Plate and the Eurasian Plate (also North American, South American, Indo-Australian, Antarctic).', noProj: 'use an atlas.' },
    { sec: '3. TYPES OF MOVEMENTS', img: 'margins.gif', caption: 'Animation: plates moving apart, together and side by side.', q: 'Name the three types of plate movements.', a: 'Moving apart (divergent), moving together (convergent) and sliding past (transform).', noProj: 'move two books on the table.' },
    { sec: '3. TYPES OF MOVEMENTS', img: 'f4_sanandreas.jpg', caption: 'The San Andreas Fault.', q: 'Which type of movement forms this fault?', a: 'Plates sliding past each other.', noProj: 'describe a crack in the ground.' },
  ],
  summary: [
    D([['Plate:', 'It is a large piece of the Earth\'s crust that moves slowly on the mantle.'],
      ['Plate boundary:', 'It is the line where two plates meet.']]),
    { title: '1. Types of Plates', intro: 'Plates are classified as follows:',
      items: [['Continental plates:', 'They carry continents, like the African and Eurasian Plates.'],
        ['Oceanic plates:', 'They lie under the oceans, like the Pacific Plate.'],
        ['Cameroon:', 'Cameroon is on the African Plate.']],
      draw: { img: 'plates_big.png', caption: 'the major plates of the world' } },
    { title: '2. Types of Plate Movements', intro: 'Plates move in the following ways:',
      items: [['Divergent movement:', 'Plates move apart and new crust forms.'],
        ['Convergent movement:', 'Plates move towards each other and one may sink under the other.'],
        ['Transform movement:', 'Plates slide past each other.'],
        ['Cause:', 'Heat currents in the mantle move the plates.']] },
  ],
  evaluation: [['What is a plate?', 'A large piece of the crust that moves slowly.'], ['Name the three types of plate movements.', 'Divergent, convergent and transform.']],
  remediation: ['Cameroon is on the ______ Plate.', 'Plates moving apart is a ______ movement.', 'Plates are moved by heat in the ______.'],
  remediationAnswers: '1. African 2. divergent 3. mantle',
  homework: 'On a world map, draw the major plates and write their names.',
  hwAnswer: 'The map shows the African, Eurasian, North American, South American, Pacific, Indo-Australian and Antarctic Plates.',
  bilingual: [['Plate', 'La plaque'], ['Movement', 'Le mouvement'], ['Boundary', 'La limite'], ['Fault', 'La faille'], ['Continent', 'Le continent'], ['Map', 'La carte']],
});

L.push({ no: 13, title: 'Consequences of the Instability of the Earth\'s Crust', subtopic: 'Movements of the Earth\'s Crust',
  notions: 'Crustal instability, volcanism, earthquake, lava, epicentre.',
  focus: 'Earthquakes; volcanism (definition and consequences).',
  competence: 'Learners are able to explain earthquakes and volcanoes and their consequences for people.',
  objectives: ['Define an earthquake and volcanism.', 'Give the consequences of earthquakes.', 'Give the consequences of volcanism.'],
  recall: ['The crust is broken into plates.', 'Plates move slowly.', 'The mantle contains very hot rock.'],
  situation: 'In 1999, Mount Cameroon erupted. Lava flowed towards the sea and cut the road near Bakingili. In 1986, gas from Lake Nyos killed about 1,700 people in their sleep.',
  sitQA: [['What is the problem in the situation?', 'Volcanic activity caused damage and deaths in Cameroon.'], ['What did the lava of Mount Cameroon do?', 'It flowed to the sea and cut the road.'], ['What killed people at Lake Nyos?', 'Poisonous gas from the lake.']],
  justification: 'This lesson helps us to know the dangers of earthquakes and volcanoes.',
  action: 'Learn and follow safety rules for earthquakes and volcanic eruptions.',
  activities: [
    { sec: '1. EARTHQUAKES', img: 'quake.gif', caption: 'Animation: an earthquake.', q: 'What is an earthquake?', a: 'A sudden shaking of the ground caused by the movement of plates.', noProj: 'shake a table with objects on it.' },
    { sec: '1. EARTHQUAKES', img: 'f4_quakedamage.jpg', caption: 'Buildings destroyed by an earthquake.', q: 'Give two consequences of earthquakes.', a: 'Buildings collapse and people die (also roads and bridges are destroyed).', noProj: 'describe earthquake damage.' },
    { sec: '2. VOLCANISM', img: 'volcano_big.png', caption: 'The structure of a volcano.', q: 'What is volcanism?', a: 'The coming out of magma, gases and ash from inside the Earth through the crust.', noProj: 'draw a volcano.' },
    { sec: '2. VOLCANISM', img: 'f4_lavahouse.jpg', caption: 'Lava flow.', q: 'Give two negative consequences of volcanism.', a: 'Lava destroys houses and farms; gases and ash kill people and animals.', noProj: 'describe the 1999 eruption.' },
    { sec: '2. VOLCANISM', img: 'f2t_tea_highlands.jpg', caption: 'Tea on fertile volcanic soil.', q: 'Give one positive consequence of volcanism.', a: 'Volcanic soils are very fertile, as around Mount Cameroon (also tourism).', noProj: 'name crops of Buea.' },
  ],
  summary: [
    D([['Earthquake:', 'It is a sudden shaking of the ground.'],
      ['Volcanism:', 'It is the coming out of magma, gases and ash from inside the Earth.']]),
    { title: '1. Earthquakes', intro: 'Earthquakes are explained as follows:',
      items: [['Cause:', 'Earthquakes are caused mainly by the sudden movement of plates.'],
        ['Consequences:', 'They destroy buildings, roads and bridges and kill people.']] },
    { title: '2. Volcanism', intro: 'Volcanism has the following consequences:',
      items: [['Negative consequences:', 'Lava, ash and gases destroy houses and farms and kill people, as at Lake Nyos in 1986.'],
        ['Positive consequences:', 'Volcanoes give fertile soils, building stones and attract tourists.'],
        ['Cameroon:', 'Mount Cameroon is an active volcano that erupted in 1999 and 2000.']],
      draw: { img: 'volcano_big.png', caption: 'the structure of a volcano' } },
  ],
  evaluation: [['What causes earthquakes?', 'The sudden movement of plates.'], ['Give one negative and one positive consequence of volcanism.', 'Negative: lava destroys farms. Positive: fertile soils.']],
  remediation: ['A sudden shaking of the ground is an ______.', 'Melted rock that comes out of a volcano is ______.', 'The active volcano of Cameroon is Mount ______.'],
  remediationAnswers: '1. earthquake 2. lava 3. Cameroon',
  homework: 'Find out what happened at Lake Nyos in 1986 and write three sentences about it.',
  hwAnswer: 'On 21 August 1986, a cloud of carbon dioxide gas came out of Lake Nyos. It flowed down the valleys and killed about 1,700 people and many animals. Today pipes remove the gas from the lake.',
  bilingual: [['Earthquake', 'Le tremblement de terre'], ['Volcano', 'Le volcan'], ['Lava', 'La lave'], ['Ash', 'La cendre'], ['Gas', 'Le gaz'], ['Eruption', "L'éruption"]],
});

L.push({ kind: 'Further Study', no: 2, title: 'What to Do in Case of an Earthquake or a Volcanic Eruption', subtopic: 'Movements of the Earth\'s Crust',
  notions: 'Safety, evacuation, first aid, adaptation, mitigation, warning.',
  focus: 'What to do in case of an earthquake or a volcanic eruption; adaptation and mitigation measures.',
  competence: 'Learners are able to react safely during an earthquake or volcanic eruption and help others.',
  objectives: ['Give the safety rules during an earthquake.', 'Give the safety rules during a volcanic eruption.', 'Describe adaptation and mitigation measures.'],
  recall: ['Earthquakes shake the ground.', 'Volcanoes give lava, ash and gases.', 'Mount Cameroon is an active volcano.'],
  situation: 'The radio announces that Mount Cameroon may erupt soon. The people of Buea are worried and do not know what to do. Some want to stay, others want to leave immediately.',
  sitQA: [['What is the problem in the situation?', 'The people do not know what to do before an eruption.'], ['What should they listen to?', 'The warnings of the authorities.'], ['Where should they go?', 'To safe places far from the lava paths.']],
  justification: 'This further study helps us to protect our lives during natural disasters.',
  action: 'Know the safe places and the first aid rules; help the weak during an emergency.',
  activities: [
    { sec: '1. DURING AN EARTHQUAKE', img: 'f4_quakedamage.jpg', caption: 'Damage after an earthquake.', q: 'What should you do inside a building during an earthquake?', a: 'Drop, cover your head under a strong table and hold on; stay away from windows.', noProj: 'practise "drop, cover, hold on".' },
    { sec: '1. AFTER AN EARTHQUAKE', img: 'usa_sandbags.jpg', caption: 'Rescue workers.', q: 'What should you do after an earthquake?', a: 'Go out carefully to an open space, help the injured and call the rescue services.', noProj: 'role-play a rescue.' },
    { sec: '2. DURING A VOLCANIC ERUPTION', img: 'f4_eruption.jpg', caption: 'A volcanic eruption.', q: 'What should people do when a volcano erupts?', a: 'Follow warnings, leave the area quickly, move away from lava paths and valleys, and cover the nose and mouth against ash.', noProj: 'list items to take when leaving.' },
    { sec: '3. MITIGATION', img: 'lsa_volcmonitor.jpg', caption: 'A volcano monitoring station.', q: 'How can scientists reduce the danger of volcanoes?', a: 'By watching volcanoes with instruments to predict eruptions and warn people.', noProj: 'explain monitoring.' },
    { sec: '3. ADAPTATION', img: 'f4_nyos.jpg', caption: 'Lake Nyos.', q: 'What was done at Lake Nyos to prevent another disaster?', a: 'Pipes were placed to remove the dangerous gas from the lake.', noProj: 'describe the degassing pipes.' },
  ],
  summary: [
    { title: '1. What to Do During an Earthquake', intro: 'During an earthquake, we follow these rules:',
      items: [['Inside:', 'We drop, cover our head under a strong table and hold on.'],
        ['Outside:', 'We move to an open space away from buildings, trees and electric wires.'],
        ['After:', 'We help the injured, give first aid and call the rescue services.']] },
    { title: '2. What to Do During a Volcanic Eruption', intro: 'During a volcanic eruption, we follow these rules:',
      items: [['Warnings:', 'We listen to the radio and obey the authorities.'],
        ['Evacuation:', 'We leave quickly, away from lava paths and low valleys.'],
        ['Protection:', 'We cover the nose and mouth against ash and gases.']] },
    { title: '3. Adaptation and Mitigation Measures', intro: 'The following measures reduce the dangers:',
      items: [['Monitoring:', 'Scientists watch volcanoes and earthquakes to warn people.'],
        ['Strong buildings:', 'Buildings made to resist shaking save lives.'],
        ['Education:', 'People learn safety drills and first aid, as the Red Cross teaches.']] },
  ],
  evaluation: [['Give two rules during an earthquake.', 'Drop, cover and hold on; stay away from windows.'], ['Give two rules during a volcanic eruption.', 'Obey warnings and leave the area away from lava paths.']],
  remediation: ['During an earthquake, we drop, cover and ______ on.', 'Leaving a dangerous area is ______.', 'Scientists watch volcanoes to give ______.'],
  remediationAnswers: '1. hold 2. evacuation 3. warnings',
  homework: 'Prepare a list of five items to take in an emergency bag.',
  hwAnswer: 'Drinking water, a torch, a first-aid kit, important documents and a radio (also food and a face mask).',
  bilingual: [['Safety', 'La sécurité'], ['Evacuation', "L'évacuation"], ['First aid', 'Les premiers secours'], ['Warning', "L'alerte"], ['Rescue', 'Le sauvetage'], ['Injured', 'Le blessé']],
});

module.exports = { B, L };
