// FORM 2 — Module 1: Man in his Environment (2023 national syllabus): L1, PW1, L2, PW2, L3, FS1, L4, FS2, FS3, PW3, L5, FS4
// Revised model (Sept 2026): syllabus points in order, definitions apart, one element per slide with its picture,
// problem visible in the situation, one question per slide in the activities.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F2', code: 'M1', folder: '', module: 'Module 1: Man in his Environment', topicDefault: 'Man in his Environment', branch: "The World's Population",
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 2, Module 1: Man in his Environment.'] };
const L = [];
const EX = 'Exploitation of Resources in the Natural Environment';

L.push({ no: 1, title: "A Rapid Growth of the World's Population", subtopic: "The World's Population",
  notions: 'Population, natural population growth, resources.',
  focus: "Evolution of the world's population; factors of the population growth; implications of the rapid population growth on natural resources.",
  competence: 'Learners are able to describe the growth of the world population and its effects on natural resources.',
  objectives: ["Describe the evolution of the world's population.", 'Explain the factors of population growth.', 'Give the implications of rapid growth on natural resources.'],
  recall: ['Many people live in towns and villages.', 'Families have children.', 'People use land, water and forests.'],
  situation: 'Grandmother Hawa says that when she was young, her village had only a few compounds and plenty of land. Today the village is crowded, the forest has disappeared and the farms are small. Her grandson asks: "Why are there so many more people today, and what will happen to our land?"',
  sitQA: [['What is the problem in the situation?', 'The grandson does not know why the population has grown so fast and what it means for the land.'], ['What has happened to the forest?', 'It has disappeared.'], ['Why are farms smaller today?', 'More people share the same land.']],
  justification: 'This lesson helps us to understand population growth and its effects on our resources.',
  action: 'Use resources wisely and respect family planning advice.',
  activities: [
    { sec: '1. EVOLUTION OF THE WORLD POPULATION', img: 'world_growth_big.png', caption: 'World population over time.', q: 'About how many people lived on the Earth in 1800?', a: 'About 1 billion.', noProj: 'write the numbers on the board.' },
    { sec: '1. EVOLUTION OF THE WORLD POPULATION', img: 'world_growth_big.png', caption: 'World population over time.', q: 'About how many people live on the Earth today?', a: 'More than 8 billion: the population has grown very fast since 1950.', noProj: 'draw a rising curve.' },
    { sec: '2. FACTORS OF GROWTH', img: 'usa_vaccine.jpg', caption: 'A child is vaccinated.', q: 'How do vaccines and hospitals increase the population?', a: 'They reduce deaths, especially of children, so more people survive.', noProj: 'ask about vaccination campaigns.' },
    { sec: '2. FACTORS OF GROWTH', img: 'birth_death_big.png', caption: 'Births and deaths.', q: 'What happens to the population when births are higher than deaths?', a: 'The population grows: this is natural growth.', noProj: 'draw two lines.' },
    { sec: '3. IMPLICATIONS', img: 'f2t_clearing.jpg', caption: 'Forest cleared for farms.', q: 'Why is the forest cut when the population grows?', a: 'More people need more land for farms and more wood for fuel and houses.', noProj: 'discuss the village of the situation.' },
  ],
  summary: [
    D([['Population:', 'It is the number of people living in a place at a given time.'],
      ['Natural population growth:', 'It is the difference between the number of births and the number of deaths.'],
      ['Resources:', 'They are the useful things that people get from nature, such as land, water and forests.']]),
    { title: "1. Evolution of the World's Population", intro: 'The world population has evolved as follows:',
      items: [['Slow growth:', 'Until about 1800, the world had fewer than 1 billion people because many people died young.'],
        ['Faster growth:', 'The population reached about 2.5 billion in 1950.'],
        ['Rapid growth:', 'It passed 8 billion in 2022, growing fastest in Africa and Asia.', 'world_growth_big.png', 'world population growth']] },
    { title: '2. Factors of the Population Growth', intro: 'The population grows for the following reasons:',
      items: [['High birth rate:', 'Many children are born, especially in poor countries.', 'usa_children.jpg', 'children'],
        ['Falling death rate:', 'Vaccines, hospitals and clean water reduce deaths.', 'usa_vaccine.jpg', 'a vaccination'],
        ['Better food supply:', 'More food allows more people to survive.'],
        ['Early marriages and big families:', 'In many places people marry young and want many children.']] },
    { title: '3. Implications on Natural Resources', intro: 'Rapid growth has the following effects on natural resources:',
      items: [['Land:', 'Farmland becomes scarce, and farms become smaller.'],
        ['Forests:', 'Forests are cut for farms, firewood and building.', 'f2t_clearing.jpg', 'forest cleared for farms'],
        ['Water:', 'Clean water becomes scarce and polluted.'],
        ['Soils:', 'Soils are overused and lose their fertility.']] },
  ],
  evaluation: [['Give two factors of rapid population growth.', 'A high birth rate and a falling death rate.'], ['Give two effects on natural resources.', 'Deforestation and shortage of land.']],
  remediation: ['The world population passed ______ billion in 2022.', 'Births minus deaths is natural ______.', 'Vaccines reduce the ______ rate.'],
  remediationAnswers: '1. 8 2. growth 3. death',
  homework: 'Ask your parents how many brothers and sisters they had and compare with families today.',
  hwAnswer: 'Answers vary. Often parents had many brothers and sisters (6 to 10); many families today have fewer children, but more of them survive.',
  bilingual: [['Population', 'La population'], ['Birth', 'La naissance'], ['Death', 'Le décès'], ['Growth', 'La croissance'], ['Resource', 'La ressource'], ['Family', 'La famille']],
});

L.push({ kind: 'Practical Work', no: 1, title: 'Calculation of the Demographic Indices of Cameroon', subtopic: "The World's Population",
  notions: 'Birth rate, death rate, natural growth rate.',
  focus: 'Theoretical basis: recall of the definitions of birth rate, death rate and natural growth rate. Practical exercise: calculation of the indices (birth rate, death rate and natural increase) with concrete data.',
  competence: 'Learners are able to calculate the birth rate, death rate and natural growth rate of a population.',
  objectives: ['Define birth rate, death rate and natural growth rate.', 'Calculate these rates from data.', 'Interpret the results for Cameroon.'],
  recall: ['Births minus deaths gives natural growth.', 'The population of Cameroon is about 28 million.', 'A rate compares a number with the whole population.'],
  situation: 'In one year, a town of 100,000 people records 3,500 births and 900 deaths. The Mayor asks the class: "How can you tell me, with numbers, how fast our town is growing?"',
  sitQA: [['What is the problem in the situation?', 'The Mayor does not know how to measure the growth of the town with numbers.'], ['What data do we have?', 'The population, the births and the deaths.'], ['What must we calculate?', 'The birth rate, the death rate and the natural growth rate.']],
  justification: 'This practical work helps us to measure how fast a population grows.',
  action: 'Always show the formula, the working and the unit in calculations.',
  activities: [
    { sec: '1. THEORETICAL BASIS', img: 'usa_newborn.jpg', caption: 'A newborn baby.', q: 'How do we compare the births of a big town and a small town fairly?', a: 'We count the births for every 1,000 people: this is the birth rate.', noProj: 'write the definition on the board.' },
    { sec: '2. BIRTH RATE', img: 'pw_indices_big.png', caption: 'Calculating indices.', q: 'A town of 100,000 people has 3,500 births. Calculate the birth rate.', a: '(3,500 ÷ 100,000) × 1,000 = 35 ‰.', noProj: 'work it out on the board.' },
    { sec: '2. DEATH RATE', img: 'pw_indices_big.png', caption: 'Calculating indices.', q: 'The same town has 900 deaths. Calculate the death rate.', a: '(900 ÷ 100,000) × 1,000 = 9 ‰.', noProj: 'work it out on the board.' },
    { sec: '2. NATURAL GROWTH RATE', img: 'pw_indices_big.png', caption: 'Natural increase.', q: 'Calculate the natural growth rate in per cent.', a: '(35 − 9) ÷ 10 = 2.6 %.', noProj: 'work it out on the board.' },
    { sec: '3. CAMEROON', img: 'cmr_rates_big.png', caption: 'Birth and death rates of Cameroon.', q: 'Which rate has fallen faster in Cameroon: the birth rate or the death rate?', a: 'The death rate, so the population grows quickly.', noProj: 'read the values of 2020.' },
  ],
  summary: [
    D([['Birth rate:', 'It is the number of births per 1,000 people in one year.'],
      ['Death rate:', 'It is the number of deaths per 1,000 people in one year.'],
      ['Natural growth rate:', 'It is the difference between the birth rate and the death rate, given in per cent.']]),
    { title: '1. Formulas', intro: 'The demographic indices are calculated with the following formulas:',
      items: [['Birth rate:', 'Birth rate = (births ÷ population) × 1,000, in ‰.', 'pw_indices_big.png', 'formulas and example'],
        ['Death rate:', 'Death rate = (deaths ÷ population) × 1,000, in ‰.'],
        ['Natural growth rate:', 'Natural growth rate = (birth rate − death rate) ÷ 10, in %.']] },
    { title: '2. Worked Example', intro: 'For a town of 100,000 people with 3,500 births and 900 deaths:',
      items: [['Birth rate:', '(3,500 ÷ 100,000) × 1,000 = 35 ‰.'],
        ['Death rate:', '(900 ÷ 100,000) × 1,000 = 9 ‰.'],
        ['Natural growth rate:', '(35 − 9) ÷ 10 = 2.6 % per year.']] },
    { title: '3. The Case of Cameroon', intro: 'The indices of Cameroon are the following (approximate):',
      items: [['Birth rate:', 'It is about 35 ‰.', 'cmr_rates_big.png', 'birth and death rates of Cameroon'],
        ['Death rate:', 'It is about 9 ‰.'],
        ['Natural growth rate:', 'It is about 2.6 %, so the population of Cameroon grows quickly.']] },
  ],
  evaluation: [['A population of 50,000 has 2,000 births. Find the birth rate.', '(2,000 ÷ 50,000) × 1,000 = 40 ‰.'], ['Birth rate 38 ‰, death rate 10 ‰. Find the natural growth rate.', '(38 − 10) ÷ 10 = 2.8 %.']],
  remediation: ['Birth and death rates are given per ______.', 'Natural growth rate is given in ______.', 'Birth rate minus death rate gives the natural ______ rate.'],
  remediationAnswers: '1. thousand (‰) 2. per cent (%) 3. growth',
  homework: 'A village of 5,000 people has 200 births and 50 deaths. Calculate the three indices.',
  hwAnswer: 'Birth rate = (200 ÷ 5,000) × 1,000 = 40 ‰. Death rate = (50 ÷ 5,000) × 1,000 = 10 ‰. Natural growth rate = (40 − 10) ÷ 10 = 3 %.',
  bilingual: [['Birth rate', 'Le taux de natalité'], ['Death rate', 'Le taux de mortalité'], ['Growth rate', "Le taux d'accroissement"], ['Calculation', 'Le calcul'], ['Formula', 'La formule'], ['Per thousand', 'Pour mille']],
});

L.push({ no: 2, title: "The Uneven Distribution of the World's Population", subtopic: "The World's Population",
  notions: 'Population density, population distribution.',
  focus: 'Concept of population density; spatial distribution; factors of uneven distribution.',
  competence: 'Learners are able to identify densely and sparsely populated areas and explain the reasons.',
  objectives: ['Define and calculate population density.', 'Describe the spatial distribution of the world population.', 'Explain the factors of uneven distribution.'],
  recall: ['The world has more than 8 billion people.', 'Some places are crowded, others are empty.', 'Deserts are very dry.'],
  situation: 'On a world map of population, Ali sees many dots in Asia and Europe, but very few in the Sahara and the Amazon forest. He asks his teacher: "Why do people not live everywhere on the Earth?"',
  sitQA: [['What is the problem in the situation?', 'Ali does not know why people are not spread evenly over the Earth.'], ['Name two crowded areas.', 'East Asia and South Asia (also Europe).'], ['Name two nearly empty areas.', 'The Sahara and the Amazon forest.']],
  justification: 'This lesson helps us to understand why people live in some places and not in others.',
  action: 'Read population maps and compare the density of different areas.',
  activities: [
    { sec: '1. POPULATION DENSITY', img: 'density_types_big.png', caption: 'People and area.', q: 'How can we measure how crowded a place is?', a: 'By dividing the population by the area: this is the population density, in people per km².', noProj: 'write the formula.' },
    { sec: '2. SPATIAL DISTRIBUTION', img: 'world_density_big.png', caption: 'Where people live in the world.', q: 'Name three crowded areas of the world.', a: 'East Asia, South Asia and Europe (also West Africa and the north-east of the USA).', noProj: 'use the atlas.' },
    { sec: '2. SPATIAL DISTRIBUTION', img: 'f2t_erg.jpg', caption: 'A sandy desert.', q: 'Why do very few people live here?', a: 'It is too dry and too hot for farming.', noProj: 'describe the Sahara.' },
    { sec: '3. FACTORS', img: 'f2t_rice_field.jpg', caption: 'Rice fields on a plain.', q: 'Why do many people live on fertile plains?', a: 'The soil is good for farming, and there is water.', noProj: 'name fertile areas of Cameroon.' },
    { sec: '3. FACTORS', img: 'lsa_douala.jpg', caption: 'Douala.', q: 'Why do many people move to towns like Douala?', a: 'To find jobs in industries and the port, and services such as schools and hospitals.', noProj: 'ask why people move to Douala.' },
  ],
  summary: [
    D([['Population density:', 'It is the average number of people per km², calculated as population ÷ area.'],
      ['Population distribution:', 'It is the way people are spread over an area.']]),
    { title: '1. Concept of Population Density', intro: 'Population density is understood as follows:',
      items: [['Formula:', 'Density = population ÷ area, in people per km².', 'density_types_big.png', 'population density'],
        ['Example:', 'Cameroon has about 28,000,000 people on 475,000 km², so its density is about 59 people per km².'],
        ['Levels:', 'Areas can have a high, moderate or low density.']] },
    { title: '2. Spatial Distribution', intro: 'The world population is distributed as follows:',
      items: [['Densely populated areas:', 'East Asia, South Asia, Western Europe, West Africa and the north-east of the USA are crowded.', 'world_density_big.png', 'dense and sparse areas of the world'],
        ['Sparsely populated areas:', 'Hot deserts, polar lands, high mountains and thick forests have very few people.', 'f2t_erg.jpg', 'a desert']] },
    { title: '3. Factors of Uneven Distribution', intro: 'The distribution depends on the following factors:',
      items: [['Climate:', 'A mild climate with enough rain attracts people, while very hot, cold or dry places repel them.'],
        ['Relief and soils:', 'Flat land and fertile soils attract people.', 'f2t_rice_field.jpg', 'a fertile plain'],
        ['Water:', 'People settle near rivers, lakes and coasts.'],
        ['Economic factors:', 'Jobs, industries, ports and mines attract people.', 'lsa_douala.jpg', 'Douala, a port and industrial town'],
        ['Social and political factors:', 'Services, security and good government attract people.']] },
  ],
  evaluation: [['A region has 300,000 people and 1,000 km². Find its density.', '300,000 ÷ 1,000 = 300 people per km².'], ['Give two reasons why deserts are sparsely populated.', 'Lack of water and very hot temperatures.']],
  remediation: ['Population ÷ area gives population ______.', 'The Sahara is a ______ populated area.', 'Fertile soils ______ people.'],
  remediationAnswers: '1. density 2. sparsely 3. attract',
  homework: 'Find the population and the area of your region and calculate its density.',
  hwAnswer: 'Example for the North Region: about 2,800,000 people ÷ 66,000 km² ≈ 42 people per km².',
  bilingual: [['Density', 'La densité'], ['Distribution', 'La répartition'], ['Dense', 'Dense'], ['Sparse', 'Clairsemé'], ['Area', 'La superficie'], ['Desert', 'Le désert']],
});

L.push({ kind: 'Practical Work', no: 2, title: 'Population Densities in Cameroon', subtopic: "The World's Population",
  notions: 'Population density; dense, moderate and low density.',
  focus: 'Theoretical basis: recall of the notion of population density. Practical exercise: calculation of the density for different regions of Cameroon. Contextualisation: identify, from a map of population distribution in Cameroon, areas of dense, moderate and low population densities.',
  competence: 'Learners are able to calculate and map the population densities of the regions of Cameroon.',
  objectives: ['Recall the notion of population density.', 'Calculate the density of the regions of Cameroon.', 'Identify areas of dense, moderate and low density on a map.'],
  recall: ['Density = population ÷ area.', 'Cameroon has ten regions.', 'The West is crowded and the East is almost empty.'],
  situation: 'The Ministry wants to build new schools where many people live. It gives the class the population and the area of the regions of Cameroon and asks: "Which regions are the most crowded, and which are almost empty?"',
  sitQA: [['What is the problem in the situation?', 'The class must find the most crowded and the emptiest regions.'], ['Which index shows crowding?', 'Population density.'], ['What data do we need?', 'The population and the area of each region.']],
  justification: 'This practical work helps us to compare the regions of Cameroon.',
  action: 'Use numbers and maps to compare places.',
  activities: [
    { sec: '1. RECALL', img: 'density_types_big.png', caption: 'The formula of density.', q: 'What is the formula of population density?', a: 'Population ÷ area, in people per km².', noProj: 'write the formula.' },
    { sec: '2. CALCULATION', img: 'cmr_popdata_big.png', caption: 'Population and area of the regions (approximate).', q: 'Calculate the density of the Littoral.', a: '3,850,000 ÷ 20,248 ≈ 190 people per km².', noProj: 'work it out on the board.' },
    { sec: '2. CALCULATION', img: 'cmr_popdata_big.png', caption: 'Population and area of the regions (approximate).', q: 'Calculate the density of the East.', a: '1,200,000 ÷ 109,002 ≈ 11 people per km².', noProj: 'work it out on the board.' },
    { sec: '3. MAPPING', img: 'choropleth_big.png', caption: 'Density of the regions of Cameroon.', q: 'Which regions have the darkest colour on this map?', a: 'The Littoral, the West, the Far North and the North-West: they are the most densely populated.', noProj: 'shade a map of the regions.' },
    { sec: '3. EXPLANATION', img: 'usa_bandjoun.jpg', caption: 'A village in the West Region.', q: 'Why is the West densely populated?', a: 'It has fertile volcanic soils, a cool climate and good roads.', noProj: 'discuss the West Region.' },
  ],
  summary: [
    D([['Population density:', 'It is the number of people per km², calculated as population ÷ area.']]),
    { title: '1. Calculation of Densities', intro: 'The densities of the regions of Cameroon are calculated as follows (approximate):',
      items: [['Littoral:', '3,850,000 ÷ 20,248 km² ≈ 190 people per km².', 'cmr_popdata_big.png', 'population and area of the regions'],
        ['West:', '2,080,000 ÷ 13,892 km² ≈ 150 people per km².'],
        ['North:', '2,780,000 ÷ 66,090 km² ≈ 42 people per km².'],
        ['East:', '1,200,000 ÷ 109,002 km² ≈ 11 people per km².']] },
    { title: '2. Areas of Dense, Moderate and Low Density', intro: 'The map of Cameroon shows the following areas:',
      items: [['High density (over 100 per km²):', 'The Littoral, the West, the North-West and the Far North.', 'choropleth_big.png', 'density of the regions of Cameroon'],
        ['Moderate density (20 to 100 per km²):', 'The Centre, the South-West and the North.'],
        ['Low density (under 20 per km²):', 'The East, the South and the Adamawa.']] },
  ],
  evaluation: [['A region has 900,000 people on 30,000 km². Find its density.', '900,000 ÷ 30,000 = 30 people per km².'], ['Name the region with the lowest density.', 'The East.']],
  remediation: ['A crowded region has a ______ density.', 'The East has a ______ density.', 'Density is given in people per ______.'],
  remediationAnswers: '1. high 2. low 3. km²',
  homework: 'Calculate the density of the Far North: about 4,450,000 people on 34,263 km².',
  hwAnswer: '4,450,000 ÷ 34,263 ≈ 130 people per km² (high density).',
  bilingual: [['Region', 'La région'], ['Density', 'La densité'], ['Crowded', 'Surpeuplé'], ['Empty', 'Vide'], ['Map', 'La carte'], ['Calculation', 'Le calcul']],
});

L.push({ no: 3, title: 'Man in the Equatorial Zone', subtopic: EX,
  notions: 'Resources, dense forest, shifting cultivation, bush fallowing.',
  focus: 'Location; climatic characteristics; resources; exploitation of resources; problems faced; proposed solutions.',
  competence: 'Learners are able to describe how people use the resources of the equatorial zone and solve its problems.',
  objectives: ['Locate the equatorial zone and describe its climate.', 'Describe its resources and how they are exploited.', 'Explain the problems faced and propose solutions.'],
  recall: ['The equatorial region is hot and wet all year.', 'It has a thick forest.', 'Southern Cameroon is in the equatorial zone.'],
  situation: 'Near Sangmélima, a farmer clears a piece of forest, burns it and plants cassava. After three years the soil is poor, so he moves to a new place, while a timber company cuts big trees nearby. His son asks: "How can people live well in the forest without destroying it?"',
  sitQA: [['What is the problem in the situation?', 'The son does not know how people can use the forest without destroying it.'], ['What farming method does the farmer use?', 'Shifting cultivation.'], ['Which other activity uses the forest?', 'Lumbering (timber).']],
  justification: 'This lesson helps us to understand how people live in the equatorial forest.',
  action: 'Use the forest wisely and replant trees.',
  activities: [
    { sec: '1. LOCATION', img: 'equatorial_world_big.png', caption: 'Some regions of the world.', q: 'Between which latitudes is the equatorial zone found?', a: 'Between about 5° N and 5° S.', noProj: 'use the atlas.' },
    { sec: '2. CLIMATE', img: 'yaounde_climate_big.png', caption: 'The climate of Yaoundé.', q: 'In how many months does it rain in Yaoundé?', a: 'In almost every month of the year.', noProj: 'write the data of Yaoundé.' },
    { sec: '3. RESOURCES', img: 'f2t_logging_truck.jpg', caption: 'Logs from the forest.', q: 'Which resource of the forest do you see here?', a: 'Timber.', noProj: 'list forest products.' },
    { sec: '4. EXPLOITATION', img: 'f2t_clearing.jpg', caption: 'A cleared and burnt plot.', q: 'Why does the farmer move to a new plot after a few years?', a: 'The soil becomes poor, so he leaves it to rest (fallow) and clears a new plot.', noProj: 'describe the stages.' },
    { sec: '5. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A muddy road.', q: 'Why are roads a problem in the equatorial zone?', a: 'Heavy rain makes earth roads muddy, so it is hard to transport goods.', noProj: 'discuss problems of the South.' },
  ],
  summary: [
    D([['Equatorial zone:', 'It is the hot and wet zone around the Equator, covered by dense forest.'],
      ['Shifting cultivation:', 'It is farming a plot for a few years and moving to a new plot when the soil becomes poor.'],
      ['Bush fallowing:', 'It is leaving farmland to rest for some years so that it becomes fertile again.']]),
    { title: '1. Location', intro: 'The equatorial zone is located as follows:',
      items: [['Latitudes:', 'It lies between about 5° N and 5° S of the Equator.', 'equatorial_world_big.png', 'the equatorial regions of the world'],
        ['Main areas:', 'It covers the Congo Basin, the Amazon Basin, South-East Asia and southern Cameroon.']] },
    { title: '2. Climatic Characteristics', intro: 'The equatorial climate has the following characteristics:',
      items: [['Temperature:', 'It is hot all year, about 25 °C to 27 °C.', 'yaounde_climate_big.png', 'the climate of Yaoundé'],
        ['Rainfall:', 'Rain is heavy, more than 1,500 mm a year, and falls in almost every month.'],
        ['Humidity:', 'The air is always humid.']] },
    { title: '3. Resources', intro: 'The equatorial zone has the following resources:',
      items: [['Forest:', 'It gives timber, fruits, medicines and game.', 'f2t_rainforest.jpg', 'the equatorial forest'],
        ['Farmland:', 'It is used for food crops and cash crops.'],
        ['Minerals:', 'Oil, gold, iron and bauxite are found.'],
        ['Water:', 'Big rivers give fish, transport and hydro-electricity.']] },
    { title: '4. Exploitation of Resources', intro: 'The resources are exploited in the following ways:',
      items: [['Shifting cultivation and bush fallowing:', 'Farmers clear and burn a plot, grow cassava and plantains, then leave it to rest.', 'f2t_clearing.jpg', 'a cleared plot'],
        ['Plantations:', 'Cocoa, coffee, oil palm and rubber are grown for export.', 'usa_cocoa.jpg', 'cocoa'],
        ['Lumbering:', 'Timber companies cut and export valuable trees.', 'f2t_logging_truck.jpg', 'logs'],
        ['Mining and gathering:', 'People extract minerals and gather forest products.']] },
    { title: '5. Problems Faced', intro: 'People face the following problems:',
      items: [['Dense forest:', 'It is difficult to clear and to cross.'],
        ['Heavy rain and bad roads:', 'Earth roads become muddy and cut off villages.', 'f2t_muddy_road.jpg', 'a muddy road'],
        ['Poor soils:', 'Heavy rain washes the minerals out of the soils.'],
        ['Diseases:', 'Malaria and other diseases are common.']] },
    { title: '6. Proposed Solutions', intro: 'The following solutions improve life:',
      items: [['Roads:', 'Tarred roads open up the forest villages.'],
        ['Health:', 'Health centres and mosquito nets fight diseases.', 'f2t_mosquito_net.jpg', 'a mosquito net'],
        ['Better farming:', 'Fertilisers and improved seeds increase harvests.'],
        ['Reforestation:', 'People replant trees where the forest was cut.']] },
  ],
  evaluation: [['Give two resources of the equatorial zone.', 'Timber and farmland (cocoa).'], ['What is bush fallowing?', 'Leaving land to rest for some years so that it becomes fertile again.']],
  remediation: ['The equatorial zone is covered by a dense ______.', 'Moving from one farm to another is ______ cultivation.', 'Leaving land to rest is ______.'],
  remediationAnswers: '1. forest 2. shifting 3. fallowing',
  homework: 'List five products from the equatorial forest sold in your local market.',
  hwAnswer: 'Plantains, cassava, cocoa (chocolate), timber (planks), bush mango or palm oil.',
  bilingual: [['Forest', 'La forêt'], ['Timber', "Le bois d'œuvre"], ['Shifting cultivation', "L'agriculture itinérante"], ['Fallow', 'La jachère'], ['Cocoa', 'Le cacao'], ['Road', 'La route']],
});

L.push({ kind: 'Further Study', no: 1, title: 'Deforestation in Cameroon', subtopic: EX,
  notions: 'Deforestation, logging, reforestation, protected area.',
  focus: 'Causes; manifestations; consequences; solutions.',
  competence: 'Learners are able to explain deforestation in Cameroon and propose solutions.',
  objectives: ['Give the causes of deforestation in Cameroon.', 'Describe its manifestations and consequences.', 'Propose solutions.'],
  recall: ['Southern Cameroon has a dense forest.', 'Timber is exported.', 'Farmers clear forest for farms.'],
  situation: 'Satellite images show that large areas of forest in the East and South of Cameroon have disappeared in the last thirty years, and some animals are becoming rare. A forest guard asks the villagers: "Who is destroying our forest, and how can we stop it?"',
  sitQA: [['What is the problem in the situation?', 'The forests of Cameroon are disappearing, and people do not know how to stop it.'], ['Which regions are affected?', 'The East and the South.'], ['What happens to the animals?', 'They become rare.']],
  justification: 'This further study helps us to understand and fight deforestation.',
  action: 'Plant trees and use improved stoves that need less wood.',
  activities: [
    { sec: '1. CAUSES', img: 'f2t_logging_truck.jpg', caption: 'A logging truck in the East of Cameroon.', q: 'Where are these logs going?', a: 'To sawmills and ports, to be sold as timber: logging is a cause of deforestation.', noProj: 'list uses of wood.' },
    { sec: '2. MANIFESTATIONS', img: 'usa_clearcut.jpg', caption: 'A forest after cutting.', q: 'What do you see where the forest was?', a: 'Bare land, stumps and roads: the forest has been destroyed.', noProj: 'describe a cleared forest.' },
    { sec: '3. CONSEQUENCES', img: 'f4_gully.jpg', caption: 'A gully.', q: 'What happens to the soil when the trees are removed?', a: 'Rain washes it away: this is soil erosion.', noProj: 'discuss effects on villages.' },
    { sec: '4. SOLUTIONS', img: 'cmr_forest_big.png', caption: 'Forests of Cameroon.', q: 'Name one protected area of the forest of Cameroon.', a: 'The Dja reserve (also Lobéké, Korup, Campo-Ma\'an).', noProj: 'use the map.' },
    { sec: '4. SOLUTIONS', img: 'f2t_tree_planting.jpg', caption: 'Planting a young tree.', q: 'How can we replace the trees that were cut?', a: 'By planting new trees: this is reforestation.', noProj: 'plan a tree-planting day.' },
  ],
  summary: [
    D([['Deforestation:', 'It is the destruction of forests by people.'],
      ['Reforestation:', 'It is planting trees where forests have been cut.']]),
    { title: '1. Causes', intro: 'Deforestation in Cameroon has the following causes:',
      items: [['Logging:', 'Companies cut valuable trees for timber and export.', 'f2t_logging_truck.jpg', 'logging'],
        ['Farming:', 'Farmers clear forest for shifting cultivation and plantations.', 'f2t_clearing.jpg', 'a cleared plot'],
        ['Firewood and charcoal:', 'People cut trees for cooking fuel.', 'f2t_charcoal.jpg', 'charcoal'],
        ['Roads, mining and settlements:', 'Forest is cleared to build roads, mines and houses.']] },
    { title: '2. Manifestations', intro: 'Deforestation appears in the following ways:',
      items: [['Bare areas:', 'Large areas of forest disappear.', 'usa_clearcut.jpg', 'a cleared forest'],
        ['Stumps and logging roads:', 'Stumps and new roads appear in the forest.'],
        ['Rare animals:', 'Animals such as gorillas and elephants become rare.']] },
    { title: '3. Consequences', intro: 'Deforestation has the following consequences:',
      items: [['Soil erosion:', 'Bare soils are washed away by rain.', 'f4_gully.jpg', 'soil erosion'],
        ['Loss of biodiversity:', 'Plants and animals disappear.'],
        ['Climate change:', 'Fewer trees mean more carbon dioxide and a warmer climate.'],
        ['Loss for forest peoples:', 'Forest peoples lose food, medicines and income.']] },
    { title: '4. Solutions', intro: 'Deforestation can be reduced by the following solutions:',
      items: [['Reforestation:', 'People plant trees where forests were cut.', 'f2t_tree_planting.jpg', 'planting a tree'],
        ['Protected areas:', 'Parks such as the Dja, Lobéké and Korup protect forests.', 'cmr_forest_big.png', 'forests of Cameroon'],
        ['Laws and control:', 'The Forestry Law controls logging and punishes illegal cutting.'],
        ['Improved stoves and cooking gas:', 'They reduce the use of firewood.']] },
  ],
  evaluation: [['Give two causes of deforestation in Cameroon.', 'Logging and farming.'], ['Give two solutions.', 'Reforestation and protected areas.']],
  remediation: ['The destruction of forests is ______.', 'Planting new trees is ______.', 'The Dja is a ______ area.'],
  remediationAnswers: '1. deforestation 2. reforestation 3. protected',
  homework: 'Write three things your family can do to reduce the use of firewood.',
  hwAnswer: 'Use an improved stove; use cooking gas when possible; plant fast-growing trees for firewood.',
  bilingual: [['Deforestation', 'La déforestation'], ['Logging', "L'exploitation forestière"], ['Reserve', 'La réserve'], ['Tree', "L'arbre"], ['Firewood', 'Le bois de chauffe'], ['Law', 'La loi']],
});

L.push({ no: 4, title: 'Man in the Tropical Zone', subtopic: EX,
  notions: 'Tropical grassland, pastoral nomadism, wildlife, crop rotation, bush fallowing, cereals.',
  focus: 'Location; brief presentation of the climatic characteristics and resources; methods of exploitation of the resources; problems faced; proposed solutions.',
  competence: 'Learners are able to describe how people use the resources of the tropical zone and solve its problems.',
  objectives: ['Locate the tropical zone and describe its climate and resources.', 'Describe the methods of exploitation of its resources.', 'Explain the problems faced and propose solutions.'],
  recall: ['Garoua has a rainy season and a dry season.', 'The savanna has grass and scattered trees.', 'Many cattle are reared in the north.'],
  situation: 'Near Garoua, farmers grow cotton, maize and sorghum in the rainy season. In the dry season, herders move their cattle to find grass and water, and sometimes the cattle enter the farms. A farmer asks the chief: "How can farmers and herders share the land without fighting?"',
  sitQA: [['What is the problem in the situation?', 'Farmers and herders compete for land and water.'], ['Name two crops of the area.', 'Cotton and sorghum (also maize).'], ['Why do herders move in the dry season?', 'To find grass and water.']],
  justification: 'This lesson helps us to understand life and activities in our own tropical zone.',
  action: 'Respect grazing zones and protect wildlife.',
  activities: [
    { sec: '1. LOCATION', img: 'savanna_africa_big.png', caption: 'Savanna regions of Africa.', q: 'Is northern Cameroon in the tropical zone?', a: 'Yes, the tropical zone lies between about 5° and 15° north and south of the Equator.', noProj: 'use the atlas.' },
    { sec: '1. CLIMATE', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'How many seasons does Garoua have?', a: 'Two: a rainy season and a long dry season.', noProj: 'describe the seasons of Garoua.' },
    { sec: '1. RESOURCES', img: 'f2t_elephants.jpg', caption: 'Wildlife in the savanna.', q: 'Which resource of the savanna do these animals represent?', a: 'Wildlife, which attracts tourists to parks such as Waza and Bénoué.', noProj: 'list resources of the North.' },
    { sec: '2. METHODS OF EXPLOITATION', img: 'transhumance.gif', caption: 'Animation: herders move with their cattle.', q: 'Why do these herders move with their cattle?', a: 'To find grass and water in the dry season: this is pastoral nomadism or transhumance.', noProj: 'describe herders of the North.' },
    { sec: '3. PROBLEMS', img: 'f2t_bushfire.jpg', caption: 'A bush fire.', q: 'What damage do bush fires cause in the savanna?', a: 'They burn the grass and trees and leave the soil bare.', noProj: 'discuss problems of the North.' },
  ],
  summary: [
    D([['Tropical zone:', 'It is the hot zone with a rainy season and a dry season, covered by savanna.'],
      ['Pastoral nomadism:', 'It is moving with animals from place to place to find grass and water.'],
      ['Crop rotation:', 'It is growing different crops on the same land from year to year.']]),
    { title: '1. Brief Presentation of the Tropical Zone', intro: 'The tropical zone is presented as follows:',
      items: [['Location:', 'It lies between about 5° and 15° north and south of the Equator, including northern Cameroon.', 'savanna_africa_big.png', 'the savanna regions of Africa'],
        ['Climate:', 'It is hot all year, with a rainy season and a long dry season.', 'garoua_climate_big.png', 'the climate of Garoua'],
        ['Resources:', 'It has grassland for animals, land for cereals and cotton, wildlife and rivers.', 'f2t_savanna.jpg', 'the savanna']] },
    { title: '2. Methods of Exploitation of the Resources', intro: 'The resources are exploited in the following ways:',
      items: [['Crop farming:', 'Farmers grow cereals (sorghum, millet, maize) and cotton using bush fallowing and crop rotation.', 'f2t_cotton_field.jpg', 'a cotton farm'],
        ['Pastoral nomadism and transhumance:', 'Herders move with cattle, sheep and goats to find grass and water.', 'transhumance_mid.png', 'transhumance'],
        ['Tourism:', 'National parks such as Waza and Bénoué attract tourists.', 'f2t_safari.jpg', 'a national park'],
        ['Fishing and irrigation:', 'People fish and grow onions and rice near rivers and lakes.']] },
    { title: '3. Problems Faced', intro: 'People face the following problems:',
      items: [['Drought:', 'The rains are short and irregular.', 'f2t_drought.jpg', 'drought'],
        ['Bush fires:', 'Fires burn the grass and trees.'],
        ['Soil erosion and overgrazing:', 'Too many animals and bare soils damage the land.'],
        ['Farmer–herder conflicts:', 'Cattle enter the farms and destroy crops.']] },
    { title: '4. Proposed Solutions', intro: 'The following solutions are proposed:',
      items: [['Irrigation:', 'Water from rivers and wells is used for farming.', 'f2t_rice_field.jpg', 'irrigated rice'],
        ['Firebreaks:', 'Bare strips stop bush fires.'],
        ['Grazing zones:', 'Separate zones for animals reduce conflicts.'],
        ['Tree planting:', 'Trees protect the soil and give shade.']] },
  ],
  evaluation: [['Give two cereals of the tropical zone.', 'Sorghum and millet (also maize).'], ['Give two problems of the tropical zone.', 'Drought and bush fires.']],
  remediation: ['Moving with animals to find grass is pastoral ______.', 'Changing crops on the same land each year is crop ______.', 'A national park in the North is ______.'],
  remediationAnswers: '1. nomadism 2. rotation 3. Bénoué (or Waza)',
  homework: 'Write the calendar of a farmer near Garoua: what he does in each season.',
  hwAnswer: 'Rainy season (May–October): clearing, sowing, weeding and harvesting cotton, maize and sorghum. Dry season: harvesting late crops, onion gardening near rivers and repairing tools.',
  bilingual: [['Savanna', 'La savane'], ['Cattle', 'Le bétail'], ['Herder', "L'éleveur"], ['Cereal', 'La céréale'], ['Cotton', 'Le coton'], ['Drought', 'La sécheresse']],
});

L.push({ kind: 'Further Study', no: 2, title: 'The Firewood Crisis', subtopic: EX,
  notions: 'Firewood, charcoal, fuel, improved stove, alternative energy.',
  focus: 'Causes; manifestations; consequences; solutions.',
  competence: 'Learners are able to explain the firewood crisis and use energy that saves trees.',
  objectives: ['Give the causes of the firewood crisis.', 'Describe its manifestations and consequences.', 'Propose solutions.'],
  recall: ['Most families cook with firewood or charcoal.', 'Trees are cut around towns.', 'The North is dry.'],
  situation: 'Women in a village near Garoua now walk more than three hours to find firewood, and the price of a bundle of wood in town has doubled in five years. A mother asks: "Why is wood so hard to find now, and how will we cook tomorrow?"',
  sitQA: [['What is the problem in the situation?', 'Firewood is becoming scarce and expensive, and families do not know how to cook tomorrow.'], ['What shows the crisis?', 'Long walks and high prices.'], ['Who suffers most?', 'Women and children who fetch wood.']],
  justification: 'This further study helps us to understand the firewood crisis and save trees.',
  action: 'Use improved stoves and cooking gas, and plant trees for firewood.',
  activities: [
    { sec: '1. CAUSES', img: 'f2t_charcoal.jpg', caption: 'Bags of charcoal for sale.', q: 'Where does the wood for this charcoal come from?', a: 'From trees cut in the bush around the towns.', noProj: 'ask how families cook.' },
    { sec: '2. MANIFESTATIONS', img: 'f4_fetchwater.jpg', caption: 'Women carrying heavy loads.', q: 'Why must women walk farther and farther to find wood?', a: 'The trees near the village have all been cut.', noProj: 'ask about the price of wood.' },
    { sec: '3. CONSEQUENCES', img: 'f2t_clearing.jpg', caption: 'Cut trees.', q: 'What happens to the land when all the trees are cut?', a: 'The soil is eroded and the land becomes like a desert.', noProj: 'discuss effects on women.' },
    { sec: '4. SOLUTIONS', img: 'f4_solar.jpg', caption: 'Solar energy.', q: 'Which energy can replace firewood for cooking?', a: 'Cooking gas, biogas or solar cookers.', noProj: 'list energy sources.' },
    { sec: '4. SOLUTIONS', img: 'f2t_tree_planting_sahel.jpg', caption: 'Planting trees in a dry area.', q: 'How can tree planting solve the crisis?', a: 'Fast-growing trees give firewood without destroying natural forests.', noProj: 'plan a woodlot.' },
  ],
  summary: [
    D([['Firewood crisis:', 'It is the shortage of wood used for cooking and heating.'],
      ['Charcoal:', 'It is wood burnt slowly without much air, used as fuel.']]),
    { title: '1. Causes', intro: 'The firewood crisis has the following causes:',
      items: [['Population growth:', 'More people need more wood for cooking.'],
        ['Over-cutting:', 'Trees are cut faster than they grow.', 'f2t_charcoal.jpg', 'charcoal for sale'],
        ['Dry climate:', 'In the north, trees grow slowly because of the long dry season.'],
        ['Poverty:', 'Many families cannot pay for gas or electricity.']] },
    { title: '2. Manifestations', intro: 'The crisis shows itself in the following ways:',
      items: [['Long distances:', 'Women and children walk far to find wood.', 'f4_fetchwater.jpg', 'carrying heavy loads'],
        ['High prices:', 'The price of firewood and charcoal rises.'],
        ['Bare land:', 'No trees remain around villages and towns.']] },
    { title: '3. Consequences', intro: 'The crisis has the following consequences:',
      items: [['Deforestation and desertification:', 'The land becomes bare and dry.', 'f2t_clearing.jpg', 'cut trees'],
        ['Loss of time:', 'Women and children lose time for school and work.'],
        ['Poverty:', 'Families spend more money on fuel.'],
        ['Health:', 'Smoke from wood fires causes eye and lung diseases.']] },
    { title: '4. Solutions', intro: 'The crisis can be solved by the following measures:',
      items: [['Improved stoves:', 'They use less wood for cooking.'],
        ['Alternative energy:', 'Cooking gas, biogas and solar cookers replace wood.', 'f4_solar.jpg', 'solar energy'],
        ['Tree planting:', 'Woodlots of fast-growing trees provide firewood.', 'f2t_tree_planting_sahel.jpg', 'planting trees'],
        ['Control of cutting:', 'The forest service controls wood cutting.']] },
  ],
  evaluation: [['Give two causes of the firewood crisis.', 'Population growth and over-cutting of trees.'], ['Give two solutions.', 'Improved stoves and cooking gas.']],
  remediation: ['Wood burnt without much air to make fuel is ______.', 'A stove that uses less wood is an ______ stove.', 'Gas from animal waste is ______.'],
  remediationAnswers: '1. charcoal 2. improved 3. biogas',
  homework: 'Ask your family how much they spend on firewood or charcoal each week.',
  hwAnswer: 'Answers vary. Example: about 3,000 to 5,000 FCFA a week for firewood or a bag of charcoal.',
  bilingual: [['Firewood', 'Le bois de chauffe'], ['Charcoal', 'Le charbon de bois'], ['Stove', 'Le foyer'], ['Gas', 'Le gaz'], ['Crisis', 'La crise'], ['Energy', "L'énergie"]],
});

L.push({ kind: 'Further Study', no: 3, title: 'Products Gathered from the Wild in Cameroon', subtopic: EX,
  notions: 'Non-timber forest products, gathering.',
  focus: 'Identification of various products (njangsa, eru, bush mango, bitter cola, etc.); methods of collection and processing; the socio-cultural and economic importance of these products.',
  competence: 'Learners are able to identify wild products of Cameroon and explain their importance.',
  objectives: ['Identify products gathered from the wild in Cameroon.', 'Describe the methods of collection and processing.', 'Explain their socio-cultural and economic importance.'],
  recall: ['The forest gives timber.', 'People gather fruits and leaves.', 'Markets sell many forest products.'],
  situation: 'In the market of Garoua, Aïcha sees eru leaves, njangsa seeds, bush mango, honey and bitter cola. The trader says that she earns her living from these products. Aïcha asks: "Where do these products come from, and why are they so important?"',
  sitQA: [['What is the problem in the situation?', 'Aïcha does not know where these products come from and why they are important.'], ['Name three products she sees.', 'Eru, njangsa and bush mango (also bitter cola and honey).'], ['Why are they important to the trader?', 'They give her an income.']],
  justification: 'This further study helps us to know the value of wild products and protect them.',
  action: 'Harvest wild products without destroying the plants.',
  activities: [
    { sec: '1. IDENTIFICATION', img: 'lsa_herbs.jpg', caption: 'Products in a market.', q: 'Were these products planted by farmers?', a: 'No, they are gathered from the wild: eru, njangsa, bush mango and bitter cola.', noProj: 'bring examples from the market.' },
    { sec: '1. IDENTIFICATION', img: 'f2t_shea_tree.jpg', caption: 'A tree of the northern savanna.', q: 'Which product of the North is made from the nuts of this tree?', a: 'Shea butter.', noProj: 'describe shea butter.' },
    { sec: '2. COLLECTION', img: 'lsa_bee.jpg', caption: 'A bee.', q: 'Where do people find wild honey?', a: 'In hives of wild bees in trees and rocks.', noProj: 'describe harvesting.' },
    { sec: '3. ECONOMIC IMPORTANCE', img: 'f2t_market.jpg', caption: 'A market.', q: 'How do wild products help the families that sell them?', a: 'They give them money to buy food and pay school fees.', noProj: 'list prices in the market.' },
    { sec: '3. SOCIO-CULTURAL IMPORTANCE', img: 'f2t_rainforest.jpg', caption: 'The forest.', q: 'When are cola nuts and bitter cola shared?', a: 'At ceremonies such as weddings and funerals.', noProj: 'ask about cola nuts at ceremonies.' },
  ],
  summary: [
    D([['Wild product:', 'It is a plant or animal product collected from nature without being cultivated.'],
      ['Gathering:', 'It is the collection of wild products.']]),
    { title: '1. Identification of the Products', intro: 'Cameroon has the following wild products:',
      items: [['Eru and njangsa:', 'Eru is a forest leaf eaten as a vegetable, and njangsa seeds are used to make sauces.', 'lsa_herbs.jpg', 'wild products in a market'],
        ['Bush mango and bitter cola:', 'Bush mango seeds thicken sauces, and bitter cola nuts are chewed.'],
        ['Shea nuts:', 'They come from the shea tree of the savanna and give shea butter.', 'f2t_shea_tree.jpg', 'a shea tree'],
        ['Honey and medicinal plants:', 'Honey, mushrooms, barks and roots are also gathered.', 'lsa_bee.jpg', 'a bee']] },
    { title: '2. Methods of Collection and Processing', intro: 'Wild products are collected and processed in the following ways:',
      items: [['Picking:', 'Fruits, nuts and leaves are picked from trees or from the ground.'],
        ['Harvesting honey:', 'Honey is taken from wild hives, often with smoke.'],
        ['Drying and cracking:', 'Seeds and nuts are dried and cracked to remove the kernels.'],
        ['Pressing and boiling:', 'Shea nuts are crushed and boiled to make butter.']] },
    { title: '3. Socio-cultural and Economic Importance', intro: 'Wild products are important in the following ways:',
      items: [['Income:', 'They give money to gatherers and traders.', 'f2t_market.jpg', 'a market'],
        ['Exports:', 'Eru and other products are exported to Nigeria and Europe.'],
        ['Food:', 'They make local dishes rich and nutritious.'],
        ['Ceremonies and medicine:', 'Cola nuts are shared at ceremonies, and many plants are used as traditional medicine.']] },
  ],
  evaluation: [['Name four wild products of Cameroon.', 'Eru, njangsa, bush mango and bitter cola.'], ['Give one economic importance.', 'They give income to families.']],
  remediation: ['Shea butter comes from the ______ tree.', 'A leaf vegetable gathered in the forest is ______.', 'Wild products are used as traditional ______.'],
  remediationAnswers: '1. shea 2. eru 3. medicine',
  homework: 'Visit the market and write the price of three wild products.',
  hwAnswer: 'Answers vary. Example: a bundle of eru 500 FCFA; a cup of njangsa 1,000 FCFA; a bitter cola nut 100 FCFA.',
  bilingual: [['Gathering', 'La cueillette'], ['Honey', 'Le miel'], ['Nut', 'La noix'], ['Leaf', 'La feuille'], ['Market', 'Le marché'], ['Medicine', 'Le médicament']],
});

L.push({ kind: 'Practical Work', no: 3, title: 'Identification of the Biological Resources of Cameroon', subtopic: EX,
  notions: 'Biological resources, biodiversity, flora, fauna, protected species, natural region.',
  focus: 'Theoretical basis: recall of the notion of resources, biodiversity and natural region. Practical exercises: identify natural resources from samples and photographs in their natural region; state their uses. Contextualisation: identify protected species (plants and animals) of the locality or region. NB: debate on the protection of species.',
  competence: 'Learners are able to identify plant and animal resources of Cameroon, state their uses and name protected species.',
  objectives: ['Recall the notions of resource, biodiversity and natural region.', 'Identify plant and animal resources and their uses.', 'Identify protected species of their region.'],
  recall: ['Cameroon has forest and savanna regions.', 'People use plants and animals.', 'National parks protect animals.'],
  situation: 'Cameroon is called "Africa in miniature" because it has many plants and animals. The teacher shows the class photos and samples and asks: "What is each plant or animal, where does it live, how is it used, and which ones must be protected?"',
  sitQA: [['What is the problem in the situation?', 'The class must identify the plants and animals, their uses and the protected species.'], ['Why is Cameroon called "Africa in miniature"?', 'It has almost all the landscapes, plants and animals of Africa.'], ['What must be protected?', 'Rare plants and animals (protected species).']],
  justification: 'This practical work helps us to know and protect the living riches of Cameroon.',
  action: 'Protect rare plants and animals and denounce poaching.',
  activities: [
    { sec: '1. THEORETICAL BASIS', img: 'cameroon_veg_big.png', caption: 'The natural regions of Cameroon.', q: 'Why do Cameroon\'s forest and savanna have different plants and animals?', a: 'They have different climates and soils: each natural region has its own biodiversity.', noProj: 'list plants and animals known.' },
    { sec: '2. PLANT RESOURCES', img: 'f2t_baobab.jpg', caption: 'A big tree of the savanna.', q: 'Which tree is this, and how do people use it?', a: 'The baobab: its leaves and fruits are eaten.', noProj: 'bring leaves or samples.' },
    { sec: '2. PLANT RESOURCES', img: 'lsa_oilpalm.jpg', caption: 'A tree of the forest region.', q: 'What do people get from this tree?', a: 'Palm oil (also palm wine and brooms): it is the oil palm.', noProj: 'list uses of the oil palm.' },
    { sec: '3. PROTECTED SPECIES', img: 'f2t_elephants.jpg', caption: 'Elephants.', q: 'Why is it forbidden to kill elephants?', a: 'They are rare and protected by law, and they attract tourists.', noProj: 'list animals of the parks.' },
    { sec: '4. DEBATE', img: 'lsa_lion.jpg', caption: 'A lion.', q: 'What would happen if all the lions of Waza were killed?', a: 'They would disappear forever, and tourists would no longer come.', noProj: 'hold a short debate.' },
  ],
  summary: [
    D([['Biological resources:', 'They are the plants and animals that people can use.'],
      ['Biodiversity:', 'It is the variety of plants and animals in a place.'],
      ['Natural region:', 'It is an area with the same climate, vegetation and soils.']]),
    { title: '1. Plant Resources and their Uses', intro: 'Cameroon has the following plant resources:',
      items: [['Timber trees:', 'Sapele, iroko and ebony of the forest give wood for furniture and building.', 'f2t_rainforest.jpg', 'the forest'],
        ['Oil palm:', 'It gives palm oil, palm wine and brooms.', 'lsa_oilpalm.jpg', 'an oil palm'],
        ['Baobab:', 'Its leaves and fruits are eaten in the savanna.', 'f2t_baobab.jpg', 'a baobab'],
        ['Shea tree and acacia:', 'They give shea butter and gum arabic.', 'f2t_shea_tree.jpg', 'a shea tree']] },
    { title: '2. Animal Resources and their Uses', intro: 'The animal resources of Cameroon and their uses are the following:',
      items: [['Forest animals:', 'Gorillas, chimpanzees, forest elephants and antelopes live in the forest.'],
        ['Savanna animals:', 'Lions, giraffes, elephants and antelopes live in parks such as Waza and Bénoué.', 'lsa_lion.jpg', 'a lion'],
        ['Fish and bees:', 'Rivers and lakes give fish, and bees give honey.'],
        ['Uses:', 'Animals give meat, skins and income from tourism.']] },
    { title: '3. Protected Species', intro: 'The protected species of the region and the reasons for protecting them are the following:',
      items: [['Protected animals:', 'Elephants, gorillas, lions, giraffes and chimpanzees are protected by law.', 'f2t_elephants.jpg', 'elephants'],
        ['Protected plants:', 'Some trees such as ebony and moabi are protected.'],
        ['Reasons for protection:', 'Protection keeps biodiversity, attracts tourists and preserves our heritage.']] },
  ],
  evaluation: [['Name two plant resources and their uses.', 'Shea tree (butter) and sapele (timber).'], ['Name two protected animals.', 'Elephant and gorilla.']],
  remediation: ['The variety of living things is ______.', 'A protected ape of the forest is the ______.', 'Waza is a national ______.'],
  remediationAnswers: '1. biodiversity 2. gorilla 3. park',
  homework: 'List three plants and three animals of your region and one use of each.',
  hwAnswer: 'Plants: shea tree (butter), baobab (leaves), acacia (gum). Animals: cattle (meat, milk), goats (meat), bees (honey).',
  bilingual: [['Biodiversity', 'La biodiversité'], ['Species', "L'espèce"], ['Protected', 'Protégé'], ['Wildlife', 'La faune sauvage'], ['Tree', "L'arbre"], ['Park', 'Le parc']],
});

L.push({ no: 5, title: 'Man in the Hot Desert Milieu', subtopic: EX,
  notions: 'Oasis, irrigation, pastoral nomadism.',
  focus: 'Location; brief presentation of the climatic characteristics and resources; traditional methods of exploitation of resources; problems faced; proposed solutions.',
  competence: 'Learners are able to describe how people live in hot deserts and solve their problems.',
  objectives: ['Locate the hot deserts and describe their climate and resources.', 'Describe the traditional methods of exploitation.', 'Explain the problems faced and propose solutions.'],
  recall: ['The Sahara is north of Cameroon.', 'Deserts receive very little rain.', 'The Harmattan comes from the Sahara.'],
  situation: 'A Tuareg family moves with its camels across the Sahara from one well to another. At an oasis, farmers grow dates under palm trees with water from a well. A pupil asks: "How can people live and farm in a place with almost no rain?"',
  sitQA: [['What is the problem in the situation?', 'The pupil does not know how people survive and farm in the desert.'], ['Which animal carries the family?', 'The camel.'], ['Where do farmers grow dates?', 'At an oasis.']],
  justification: 'This lesson helps us to understand how people survive in hot deserts.',
  action: 'Save water every day, as desert peoples do.',
  activities: [
    { sec: '1. LOCATION', img: 'deserts_world_big.png', caption: 'Dry regions of the world.', q: 'Which is the largest hot desert of the world?', a: 'The Sahara, north of Cameroon.', noProj: 'use the atlas.' },
    { sec: '1. CLIMATE', img: 'f2t_erg.jpg', caption: 'A sandy desert.', q: 'Why are there no trees here?', a: 'There is very little rain (less than 250 mm a year) and it is very hot.', noProj: 'compare with Garoua.' },
    { sec: '2. OASIS FARMING', img: 'f2t_oasis.jpg', caption: 'A green place in the desert.', q: 'Why can people farm at this place?', a: 'There is water from a spring or a well: it is an oasis.', noProj: 'list desert resources.' },
    { sec: '2. PASTORAL NOMADISM', img: 'f2t_camels.jpg', caption: 'Camels in the desert.', q: 'Why is the camel useful in the desert?', a: 'It can walk for days without water and carries people and goods.', noProj: 'describe nomads of the Far North.' },
    { sec: '3. PROBLEMS', img: 'f2t_sandstorm.jpg', caption: 'A sandstorm.', q: 'What problems do sandstorms cause?', a: 'They bury wells and fields and make breathing difficult.', noProj: 'discuss water problems.' },
  ],
  summary: [
    D([['Hot desert:', 'It is a very dry and hot area that receives less than 250 mm of rain a year.'],
      ['Oasis:', 'It is a green place in the desert with water from a spring or a well.'],
      ['Irrigation:', 'It is bringing water to fields to grow crops.']]),
    { title: '1. Brief Presentation of Hot Deserts', intro: 'Hot deserts are presented as follows:',
      items: [['Location:', 'Hot deserts lie near the tropics, like the Sahara, the Kalahari and the Arabian Desert.', 'deserts_world_big.png', 'hot deserts of the world'],
        ['Climate:', 'They receive less than 250 mm of rain, with very hot days and cold nights.', 'f2t_erg.jpg', 'a sandy desert'],
        ['Resources:', 'They have oases, underground water, oil, gas, minerals and sunshine.']] },
    { title: '2. Traditional Methods of Exploitation', intro: 'People use the desert in the following traditional ways:',
      items: [['Pastoral nomadism:', 'Nomads such as the Tuareg move with camels, goats and sheep from well to well.', 'f2t_camels.jpg', 'camels'],
        ['Oasis farming:', 'Farmers grow dates, vegetables and cereals under palm trees.', 'f2t_oasis.jpg', 'an oasis'],
        ['Traditional irrigation:', 'Farmers lift water from wells with tools such as the shaduf.', 'f2t_shaduf.jpg', 'a shaduf'],
        ['Trade:', 'Camel caravans carry salt and goods across the desert.']] },
    { title: '3. Problems Faced', intro: 'People face the following problems:',
      items: [['Lack of water:', 'Wells dry up and water is scarce.', 'f2t_desert_well.jpg', 'a desert well'],
        ['Heat and cold:', 'Days are very hot and nights are cold.'],
        ['Sandstorms:', 'Wind buries wells, fields and roads.'],
        ['Poor soils:', 'Sand and salt make farming difficult.']] },
    { title: '4. Proposed Solutions', intro: 'The following solutions help people:',
      items: [['Deep wells and boreholes:', 'They bring underground water to the surface.'],
        ['Modern irrigation:', 'Pumps and sprinklers water large fields.', 'f2t_pivot.jpg', 'modern irrigation'],
        ['Tree planting:', 'Trees stop moving sand.'],
        ['Solar energy:', 'Sunshine gives electricity for pumps and homes.']] },
  ],
  evaluation: [['Give two resources of hot deserts.', 'Water at oases and oil.'], ['Give two problems of the desert.', 'Lack of water and sandstorms.']],
  remediation: ['A green place in the desert with water is an ______.', 'The animal of the desert is the ______.', 'Bringing water to fields is ______.'],
  remediationAnswers: '1. oasis 2. camel 3. irrigation',
  homework: 'Write three ways people in the Far North of Cameroon save water.',
  hwAnswer: 'They store rainwater in jars, dig wells and use water carefully for cooking, washing and animals.',
  bilingual: [['Desert', 'Le désert'], ['Oasis', "L'oasis"], ['Camel', 'Le chameau'], ['Well', 'Le puits'], ['Nomad', 'Le nomade'], ['Sand', 'Le sable']],
});

L.push({ kind: 'Further Study', no: 4, title: 'Water Scarcity', subtopic: EX,
  notions: 'Water scarcity, quantity, quality, water management, uses of water.',
  focus: 'Enquiry on the problem of water scarcity (quantity, quality, management and uses).',
  competence: 'Learners are able to investigate water scarcity in their area and propose ways to manage water.',
  objectives: ['Define water scarcity.', 'Describe the problems of quantity and quality of water and its uses.', 'Propose ways to manage water well.'],
  recall: ['People need water every day.', 'The dry season is long in the north.', 'Dirty water causes diseases.'],
  situation: 'In the dry season, the tap in Ali\'s quarter of Garoua runs only two days a week. His family buys water from sellers and sometimes drinks water from a well that is not clean. Ali asks: "Why is there not enough clean water, and what can we do?"',
  sitQA: [['What is the problem in the situation?', 'There is not enough clean water, and Ali does not know what to do.'], ['How does the family get water?', 'From sellers and a well.'], ['What danger does the well water bring?', 'Diseases like cholera and typhoid.']],
  justification: 'This further study helps us to understand water problems and use water wisely.',
  action: 'Close taps, repair leaks, store rainwater and treat drinking water.',
  activities: [
    { sec: '1. MEANING', img: 'f4_fetchwater.jpg', caption: 'Women fetching water.', q: 'Why do these women carry water from far away?', a: 'There is not enough clean water near their homes: this is water scarcity.', noProj: 'ask where families get water.' },
    { sec: '2. QUANTITY', img: 'world_water_big.png', caption: 'Water on the Earth.', q: 'What part of the Earth\'s water is fresh water?', a: 'Only about 2.5 %; most water is salty sea water.', noProj: 'draw a bar of 100 %.' },
    { sec: '3. QUALITY', img: 'f4_borehole.jpg', caption: 'A borehole.', q: 'Why is borehole water safer than water from an open well?', a: 'It comes from deep underground and is protected from dirt.', noProj: 'describe water sources of the quarter.' },
    { sec: '4. USES', img: 'f4_leakingtap.jpg', caption: 'A leaking tap.', q: 'How is water wasted in this picture?', a: 'The tap leaks, so clean water is lost.', noProj: 'list uses at home.' },
    { sec: '5. MANAGEMENT', img: 'rainwater_big.png', caption: 'Collecting rainwater.', q: 'How can a family keep water for the dry season?', a: 'By collecting rainwater from the roof in a tank.', noProj: 'design a water plan for the school.' },
  ],
  summary: [
    D([['Water scarcity:', 'It is a lack of enough clean water to meet people\'s needs.'],
      ['Water management:', 'It is the good use, storage and protection of water.']]),
    { title: '1. Quantity of Water', intro: 'The quantity of water is limited for the following reasons:',
      items: [['Little fresh water:', 'Only about 2.5 % of the water on the Earth is fresh.', 'world_water_big.png', 'water on the Earth'],
        ['Long dry seasons and droughts:', 'Rivers and wells dry up in the north.'],
        ['Population growth:', 'More people need more water.']] },
    { title: '2. Quality of Water', intro: 'The quality of water is explained as follows:',
      items: [['Open wells and rivers:', 'Their water is often dirty and carries germs.'],
        ['Diseases:', 'Dirty water causes cholera, typhoid and diarrhoea.'],
        ['Safe sources:', 'Boreholes and treated tap water are safer.', 'f4_borehole.jpg', 'a borehole']] },
    { title: '3. Uses of Water', intro: 'The uses of water and its waste are the following:',
      items: [['Domestic uses:', 'We use water for drinking, cooking and washing.'],
        ['Farming and livestock:', 'Farmers irrigate crops and herders water their animals.', 'usa_irrigation.jpg', 'irrigation'],
        ['Industry and energy:', 'Factories use water, and dams produce electricity.'],
        ['Waste:', 'Leaking taps and careless use waste water.', 'f4_leakingtap.jpg', 'a leaking tap']] },
    { title: '4. Management of Water', intro: 'Water can be managed with the following measures:',
      items: [['Saving water:', 'We close taps and repair leaks.'],
        ['Storing water:', 'We collect rainwater in tanks and build dams.', 'rainwater_big.png', 'collecting rainwater'],
        ['Clean water:', 'We boil or filter water and build boreholes.'],
        ['Protecting sources:', 'We keep wells covered and do not throw rubbish in rivers.']] },
  ],
  evaluation: [['What is water scarcity?', 'A lack of enough clean water.'], ['Give two ways to manage water.', 'Store rainwater and repair leaks.']],
  remediation: ['Only about ______ % of the Earth\'s water is fresh.', 'A deep well dug with machines is a ______.', 'Dirty water causes ______.'],
  remediationAnswers: '1. 2.5 2. borehole 3. cholera (or typhoid)',
  homework: 'Carry out a small enquiry: ask three families where they get water and what problems they have.',
  hwAnswer: 'Answers vary. Typical results: tap water that runs irregularly, buying water from sellers, wells that dry up in the dry season, and fear of dirty water.',
  bilingual: [['Water', "L'eau"], ['Scarcity', 'La pénurie'], ['Well', 'Le puits'], ['Tap', 'Le robinet'], ['Clean', 'Propre'], ['Enquiry', "L'enquête"]],
});

module.exports = { B, L };
