// FORM 2 — Module 1: Man in his Environment (2023 national syllabus): L1, PW1, L2, PW2, L3, FS1, L4, FS2, FS3, PW3, L5, FS4
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F2', code: 'M1', folder: '', module: 'Module 1: Man in his Environment', topicDefault: 'Man in his Environment', branch: "The World's Population",
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 2, Module 1: Man in his Environment.'] };
const L = [];

L.push({ no: 1, title: "A Rapid Growth of the World's Population", subtopic: "The World's Population",
  notions: 'Population, natural population growth, birth rate, death rate, resources.',
  focus: "Evolution of the world's population; factors of population growth; implications of rapid population growth on natural resources.",
  competence: 'Learners are able to describe the growth of the world population and its effects on natural resources.',
  objectives: ["Describe the evolution of the world's population.", 'Explain the factors of population growth.', 'Give the implications of rapid growth on natural resources.'],
  recall: ['Many people live in towns and villages.', 'Families have children.', 'People use land, water and forests.'],
  situation: 'Grandmother Hawa says that when she was young, her village had only a few compounds and plenty of land. Today the village is crowded, the forest has disappeared and farms are small.',
  sitQA: [['What is the problem in the situation?', 'The population of the village has grown quickly.'], ['What has happened to the forest?', 'It has disappeared.'], ['Why are farms smaller today?', 'There are more people sharing the same land.']],
  justification: 'This lesson helps us to understand population growth and its effects on our resources.',
  action: 'Use resources wisely and respect family planning advice.',
  activities: [
    { sec: '1. EVOLUTION OF THE WORLD POPULATION', img: 'world_growth_big.png', caption: 'World population over time.', q: 'How many people lived on the Earth in 1800 and in 2022?', a: 'About 1 billion in 1800 and 8 billion in 2022.', noProj: 'write the numbers on the board.' },
    { sec: '1. EVOLUTION OF THE WORLD POPULATION', img: 'usa_crowd.jpg', caption: 'A crowded market.', q: 'Is the world population growing slowly or quickly today?', a: 'Quickly: it has grown very fast since about 1950.', noProj: 'describe a crowded place.' },
    { sec: '2. FACTORS OF GROWTH', img: 'usa_vaccine.jpg', caption: 'A child is vaccinated.', q: 'How do vaccines and hospitals increase the population?', a: 'They reduce deaths, especially of children, so more people survive.', noProj: 'ask about vaccination campaigns.' },
    { sec: '2. FACTORS OF GROWTH', img: 'birth_death_big.png', caption: 'Birth rate and death rate.', q: 'What happens to the population when births are higher than deaths?', a: 'The population grows (natural increase).', noProj: 'draw two lines.' },
    { sec: '3. IMPLICATIONS', img: 'f2t_clearing.jpg', caption: 'Forest cleared for farms.', q: 'Give two effects of rapid population growth on natural resources.', a: 'Forests are cut for farms and firewood; land and water become scarce.', noProj: 'discuss the village of the situation.' },
  ],
  summary: [
    D([['Population:', 'It is the number of people living in a place.'],
      ['Natural growth:', 'It is the difference between the number of births and the number of deaths.']]),
    { title: "1. Evolution of the World's Population", intro: 'The world population has grown as follows:',
      items: [['Slow growth:', 'The world had fewer than 1 billion people until about 1800.'],
        ['Rapid growth:', 'The population reached 8 billion in 2022, growing fastest after 1950.']],
      draw: { img: 'world_growth_big.png', caption: 'world population growth' } },
    { title: '2. Factors of Population Growth', intro: 'The population grows for the following reasons:',
      items: [['High birth rate:', 'Many children are born, especially in poor countries.'],
        ['Falling death rate:', 'Vaccines, hospitals and clean water reduce deaths.'],
        ['Better food supply:', 'More food allows more people to survive.']] },
    { title: '3. Implications on Natural Resources', intro: 'Rapid growth has the following effects on resources:',
      items: [['Land:', 'Farmland becomes scarce and farms become smaller.'],
        ['Forests:', 'Forests are cut for farms, firewood and building.'],
        ['Water:', 'Clean water becomes scarce and polluted.']] },
  ],
  evaluation: [['Give two factors of rapid population growth.', 'A high birth rate and a falling death rate.'], ['Give two effects on natural resources.', 'Deforestation and shortage of land.']],
  remediation: ['The world population reached ______ billion in 2022.', 'Births minus deaths is natural ______.', 'Vaccines reduce the ______ rate.'],
  remediationAnswers: '1. 8 2. growth 3. death',
  homework: 'Ask your parents how many brothers and sisters they had and compare with families today.',
  hwAnswer: 'Answers vary. Often parents had many brothers and sisters (6 to 10); many families today have fewer children, but more of them survive.',
  bilingual: [['Population', 'La population'], ['Birth', 'La naissance'], ['Death', 'Le décès'], ['Growth', 'La croissance'], ['Resource', 'La ressource'], ['Family', 'La famille']],
});

L.push({ kind: 'Practical Work', no: 1, title: 'Calculation of the Demographic Indices of Cameroon', subtopic: "The World's Population",
  notions: 'Birth rate, death rate, natural growth rate, per thousand (‰), per cent (%).',
  focus: 'Recall of the definitions of birth rate, death rate and natural growth rate; calculation of these indices with concrete data.',
  competence: 'Learners are able to calculate the birth rate, death rate and natural growth rate of a population.',
  objectives: ['Define birth rate, death rate and natural growth rate.', 'Calculate these rates from data.', 'Interpret the results for Cameroon.'],
  recall: ['Births minus deaths gives natural growth.', 'The population of Cameroon is about 28 million.', 'A rate compares a number with the whole population.'],
  situation: 'In one year, a town of 100,000 people records 3,500 births and 900 deaths. The Mayor wants to know how fast the population of the town is growing.',
  sitQA: [['What is the problem in the situation?', 'The Mayor wants to know the growth of the town.'], ['What data do we have?', 'The population, the births and the deaths.'], ['What must we calculate?', 'The birth rate, the death rate and the natural growth rate.']],
  justification: 'This practical work helps us to measure how fast a population grows.',
  action: 'Always show the formula, the working and the unit in calculations.',
  activities: [
    { sec: '1. THEORETICAL BASIS', img: 'birth_death_big.png', caption: 'Birth and death rates.', q: 'What is the birth rate?', a: 'The number of births per 1,000 people in one year.', noProj: 'write the definition on the board.' },
    { sec: '2. BIRTH RATE', img: 'usa_newborn.jpg', caption: 'A newborn baby.', q: 'A town of 100,000 people has 3,500 births. Calculate the birth rate.', a: '(3,500 ÷ 100,000) × 1,000 = 35 ‰.', noProj: 'work it out on the board.' },
    { sec: '2. DEATH RATE', img: 'pw_indices_big.png', caption: 'Calculating demographic indices.', q: 'The same town has 900 deaths. Calculate the death rate.', a: '(900 ÷ 100,000) × 1,000 = 9 ‰.', noProj: 'work it out on the board.' },
    { sec: '2. NATURAL GROWTH RATE', img: 'pw_indices_big.png', caption: 'Natural increase.', q: 'Calculate the natural growth rate in per cent.', a: '(35 − 9) ÷ 10 = 2.6 %.', noProj: 'work it out on the board.' },
    { sec: '3. CAMEROON', img: 'cmr_rates_big.png', caption: 'Birth and death rates of Cameroon.', q: 'What does the graph show about Cameroon?', a: 'The death rate has fallen faster than the birth rate, so the population grows quickly.', noProj: 'read the values of 2020.' },
  ],
  summary: [
    D([['Birth rate:', 'It is the number of births per 1,000 people in one year.'],
      ['Death rate:', 'It is the number of deaths per 1,000 people in one year.'],
      ['Natural growth rate:', 'It is the difference between the birth rate and the death rate, given in per cent.']]),
    { title: '1. Formulas', intro: 'The demographic indices are calculated as follows:',
      items: [['Birth rate:', 'Birth rate = (births ÷ population) × 1,000, in ‰.'],
        ['Death rate:', 'Death rate = (deaths ÷ population) × 1,000, in ‰.'],
        ['Natural growth rate:', 'Natural growth rate = (birth rate − death rate) ÷ 10, in %.']] },
    { title: '2. Worked Example', intro: 'For a town of 100,000 people with 3,500 births and 900 deaths:',
      items: [['Birth rate:', '(3,500 ÷ 100,000) × 1,000 = 35 ‰.'],
        ['Death rate:', '(900 ÷ 100,000) × 1,000 = 9 ‰.'],
        ['Natural growth rate:', '(35 − 9) ÷ 10 = 2.6 % per year.']],
      draw: { img: 'pw_indices_big.png', caption: 'calculating demographic indices' } },
  ],
  evaluation: [['A population of 50,000 has 2,000 births. Find the birth rate.', '(2,000 ÷ 50,000) × 1,000 = 40 ‰.'], ['Birth rate 38 ‰, death rate 10 ‰. Find the natural growth rate.', '(38 − 10) ÷ 10 = 2.8 %.']],
  remediation: ['Birth and death rates are given per ______.', 'Natural growth rate is given in ______.', 'Birth rate minus death rate gives the natural ______ rate.'],
  remediationAnswers: '1. thousand (‰) 2. per cent (%) 3. growth',
  homework: 'A village of 5,000 people has 200 births and 50 deaths. Calculate the three indices.',
  hwAnswer: 'Birth rate = (200 ÷ 5,000) × 1,000 = 40 ‰. Death rate = (50 ÷ 5,000) × 1,000 = 10 ‰. Natural growth rate = (40 − 10) ÷ 10 = 3 %.',
  bilingual: [['Birth rate', 'Le taux de natalité'], ['Death rate', 'Le taux de mortalité'], ['Growth rate', "Le taux d'accroissement"], ['Calculation', 'Le calcul'], ['Formula', 'La formule'], ['Per thousand', 'Pour mille']],
});

L.push({ no: 2, title: "The Uneven Distribution of the World's Population", subtopic: "The World's Population",
  notions: 'Population density, population distribution, dense, sparse.',
  focus: 'Concept of population density; spatial distribution; factors of uneven distribution.',
  competence: 'Learners are able to identify densely and sparsely populated areas and explain the reasons.',
  objectives: ['Define population density and calculate it.', 'Describe the distribution of the world population.', 'Explain the factors of uneven distribution.'],
  recall: ['The world has 8 billion people.', 'Some places are crowded, others are empty.', 'Deserts are very dry.'],
  situation: 'On a world map of population, Ali sees that many dots cover Asia and Europe, but very few cover the Sahara and the Amazon forest. He asks why people do not live everywhere.',
  sitQA: [['What is the problem in the situation?', 'Ali wants to know why the population is unevenly distributed.'], ['Name two crowded areas.', 'East Asia and South Asia (also Europe).'], ['Name two nearly empty areas.', 'The Sahara and the Amazon forest.']],
  justification: 'This lesson helps us to understand why people live in some places and not in others.',
  action: 'Read population maps and compare the density of different areas.',
  activities: [
    { sec: '1. POPULATION DENSITY', img: 'density_types_big.png', caption: 'Population density.', q: 'How do we calculate population density?', a: 'Population ÷ area, in people per km².', noProj: 'write the formula.' },
    { sec: '2. SPATIAL DISTRIBUTION', img: 'world_density_big.png', caption: 'Dense and sparse areas of the world.', q: 'Name three densely populated areas of the world.', a: 'East Asia, South Asia and Europe (also West Africa, NE USA).', noProj: 'use the atlas.' },
    { sec: '2. SPATIAL DISTRIBUTION', img: 'f2t_erg.jpg', caption: 'A sandy desert.', q: 'Why are deserts sparsely populated?', a: 'They are too dry and too hot for farming.', noProj: 'describe the Sahara.' },
    { sec: '3. FACTORS', img: 'f2t_rice_field.jpg', caption: 'Rice fields on a fertile plain.', q: 'Why do many people live on fertile plains?', a: 'The soil is good for farming and there is water.', noProj: 'name fertile areas of Cameroon.' },
    { sec: '3. FACTORS', img: 'lsa_douala.jpg', caption: 'Douala.', q: 'Give two human factors that attract people to towns like Douala.', a: 'Jobs and industries, and services such as schools and hospitals (also the port).', noProj: 'ask why people move to Douala.' },
  ],
  summary: [
    D([['Population density:', 'It is the average number of people per km², calculated as population ÷ area.'],
      ['Population distribution:', 'It is the way people are spread over an area.']]),
    { title: '1. Spatial Distribution', intro: 'The world population is distributed as follows:',
      items: [['Dense areas:', 'East Asia, South Asia, Europe and West Africa have many people per km².'],
        ['Sparse areas:', 'Deserts, polar lands, high mountains and thick forests have very few people.']],
      draw: { img: 'world_density_big.png', caption: 'dense and sparse areas of the world' } },
    { title: '2. Factors of Uneven Distribution', intro: 'The distribution depends on the following factors:',
      items: [['Physical factors:', 'Fertile soils, a good climate, water and flat land attract people.'],
        ['Unfavourable conditions:', 'Too much cold, heat, dryness or steep slopes keep people away.'],
        ['Human factors:', 'Jobs, industries, towns, roads and security attract people.']] },
  ],
  evaluation: [['A region has 300,000 people and 1,000 km². Find its density.', '300,000 ÷ 1,000 = 300 people per km².'], ['Give two reasons why deserts are sparsely populated.', 'Lack of water and very hot temperatures.']],
  remediation: ['Population ÷ area gives population ______.', 'The Sahara is a ______ populated area.', 'Fertile soils ______ people.'],
  remediationAnswers: '1. density 2. sparsely 3. attract',
  homework: 'Find the population and the area of your region and calculate its density.',
  hwAnswer: 'Example for the North Region: about 3,000,000 people ÷ 66,000 km² ≈ 45 people per km².',
  bilingual: [['Density', 'La densité'], ['Distribution', 'La répartition'], ['Dense', 'Dense'], ['Sparse', 'Clairsemé'], ['Area', 'La superficie'], ['Desert', 'Le désert']],
});

L.push({ kind: 'Practical Work', no: 2, title: 'Population Densities in Cameroon', subtopic: "The World's Population",
  notions: 'Population density, dense, moderate and low density.',
  focus: 'Recall of population density; calculation of density for different regions of Cameroon; identifying areas of dense, moderate and low density on a map.',
  competence: 'Learners are able to calculate and map the population densities of the regions of Cameroon.',
  objectives: ['Recall the notion of population density.', 'Calculate the density of regions of Cameroon.', 'Identify areas of dense, moderate and low density on a map.'],
  recall: ['Density = population ÷ area.', 'Cameroon has ten regions.', 'The West is crowded and the East is almost empty.'],
  situation: 'The Ministry wants to build new schools where many people live. It gives the class the population and area of four regions and asks which region is the most crowded.',
  sitQA: [['What is the problem in the situation?', 'We must find the most crowded region.'], ['Which index shows crowding?', 'Population density.'], ['What data do we need?', 'The population and the area of each region.']],
  justification: 'This practical work helps us to compare the regions of Cameroon.',
  action: 'Use numbers and maps to compare places.',
  activities: [
    { sec: '1. RECALL', img: 'density_types_big.png', caption: 'The formula of density.', q: 'Give the formula of population density and its unit.', a: 'Population ÷ area, in people per km².', noProj: 'write the formula.' },
    { sec: '2. CALCULATION', img: 'cmr_regions_big.png', caption: 'The ten regions of Cameroon.', q: 'The West has about 2,000,000 people on 14,000 km². Calculate its density.', a: '2,000,000 ÷ 14,000 ≈ 143 people per km².', noProj: 'work it out on the board.' },
    { sec: '2. CALCULATION', img: 'cmr_regions_big.png', caption: 'The East Region.', q: 'The East has about 1,100,000 people on 109,000 km². Calculate its density.', a: '1,100,000 ÷ 109,000 ≈ 10 people per km².', noProj: 'work it out on the board.' },
    { sec: '3. MAPPING', img: 'cmr_towns_big.png', caption: 'The main towns of Cameroon.', q: 'Name two regions of high density and two of low density.', a: 'High: West and Littoral (also North-West, Far North). Low: East and South (also Adamawa).', noProj: 'shade a map of the regions.' },
    { sec: '3. EXPLANATION', img: 'usa_bandjoun.jpg', caption: 'A village in the West Region.', q: 'Why is the West densely populated?', a: 'It has fertile volcanic soils, a cool climate and good roads.', noProj: 'discuss the West Region.' },
  ],
  summary: [
    D([['Population density:', 'It is the number of people per km², calculated as population ÷ area.']]),
    { title: '1. Calculation', intro: 'The density of some regions of Cameroon is calculated as follows:',
      items: [['West:', 'About 2,000,000 ÷ 14,000 km² ≈ 143 people per km² (high density).'],
        ['Littoral:', 'About 3,500,000 ÷ 20,000 km² ≈ 175 people per km² (high density).'],
        ['East:', 'About 1,100,000 ÷ 109,000 km² ≈ 10 people per km² (low density).']] },
    { title: '2. Areas of Density in Cameroon', intro: 'Cameroon has the following areas of density:',
      items: [['High density:', 'The West, North-West, Littoral and the Mandara area of the Far North are crowded.'],
        ['Moderate density:', 'The Centre, South-West and North have a moderate density.'],
        ['Low density:', 'The East, South and Adamawa have few people per km².']],
      draw: { img: 'cmr_regions_big.png', caption: 'the regions of Cameroon' } },
  ],
  evaluation: [['A region has 900,000 people on 30,000 km². Find its density.', '900,000 ÷ 30,000 = 30 people per km².'], ['Name the region with the lowest density.', 'The East.']],
  remediation: ['A crowded region has a ______ density.', 'The East has a ______ density.', 'Density is given in people per ______.'],
  remediationAnswers: '1. high 2. low 3. km²',
  homework: 'Calculate the density of the North Region: about 3,000,000 people on 66,000 km².',
  hwAnswer: '3,000,000 ÷ 66,000 ≈ 45 people per km² (moderate density).',
  bilingual: [['Region', 'La région'], ['Density', 'La densité'], ['Crowded', 'Surpeuplé'], ['Empty', 'Vide'], ['Map', 'La carte'], ['Calculation', 'Le calcul']],
});

L.push({ no: 3, title: 'Man in the Equatorial Zone', subtopic: 'Exploitation of Resources in the Natural Environment',
  notions: 'Resources, dense forest, shifting cultivation, bush fallowing.',
  focus: 'Location; climatic characteristics; resources; exploitation of resources; problems faced; proposed solutions.',
  competence: 'Learners are able to describe how people use the resources of the equatorial zone and solve its problems.',
  objectives: ['Locate the equatorial zone and describe its climate.', 'Describe its resources and how they are exploited.', 'Explain the problems faced and propose solutions.'],
  recall: ['The equatorial region is hot and wet all year.', 'It has a thick forest.', 'Southern Cameroon is in the equatorial zone.'],
  situation: 'Near Sangmélima, a farmer clears a piece of forest, burns it and plants cassava. After three years, the soil is poor, so he moves to a new place. A timber company also cuts big trees nearby.',
  sitQA: [['What is the problem in the situation?', 'The soil becomes poor and the forest is being cut.'], ['What farming method does the farmer use?', 'Shifting cultivation.'], ['Which other activity uses the forest?', 'Lumbering (timber).']],
  justification: 'This lesson helps us to understand how people live in the equatorial forest.',
  action: 'Use the forest wisely and replant trees.',
  activities: [
    { sec: '1. LOCATION AND CLIMATE', img: 'equatorial_world_big.png', caption: 'The equatorial regions of the world.', q: 'Between which latitudes is the equatorial zone found?', a: 'Between about 5° N and 5° S.', noProj: 'use the atlas.' },
    { sec: '1. LOCATION AND CLIMATE', img: 'yaounde_climate_big.png', caption: 'The climate of Yaoundé.', q: 'Describe the equatorial climate.', a: 'Hot all year and rain in almost every month.', noProj: 'write the data of Yaoundé.' },
    { sec: '2. RESOURCES', img: 'f2t_logging_truck.jpg', caption: 'Logs from the forest.', q: 'Name three resources of the equatorial zone.', a: 'Timber, farmland for cocoa and cassava, and minerals (also water, wildlife).', noProj: 'list forest products.' },
    { sec: '3. EXPLOITATION', img: 'f2t_clearing.jpg', caption: 'A cleared and burnt plot.', q: 'Describe shifting cultivation and bush fallowing.', a: 'The farmer clears and burns a plot, farms it for a few years, then leaves it to rest (fallow) and moves.', noProj: 'describe the stages.' },
    { sec: '4. PROBLEMS AND SOLUTIONS', img: 'f2t_muddy_road.jpg', caption: 'A muddy road.', q: 'Give two problems and two solutions.', a: 'Problems: bad roads and diseases. Solutions: tarred roads and mosquito nets (also reforestation).', noProj: 'discuss problems of the South.' },
  ],
  summary: [
    { title: '1. Location and Climate', intro: 'The equatorial zone is presented as follows:',
      items: [['Location:', 'It lies between about 5° N and 5° S, in the Congo and Amazon Basins, South-East Asia and southern Cameroon.'],
        ['Climate:', 'It is hot all year with heavy rain in almost every month.']],
      draw: { img: 'equatorial_world_big.png', caption: 'the equatorial regions' } },
    { title: '2. Resources and their Exploitation', intro: 'The resources of the equatorial zone are exploited as follows:',
      items: [['Forest:', 'Timber is cut and exported, and people gather fruits and medicines.'],
        ['Farmland:', 'Farmers practise shifting cultivation and bush fallowing, and plantations grow cocoa, oil palm and rubber.'],
        ['Minerals and water:', 'Oil, gold and hydro-electricity are produced.']] },
    { title: '3. Problems and Solutions', intro: 'People face the following problems and solutions:',
      items: [['Problems:', 'The thick forest, heavy rain, bad roads, poor soils and diseases make life difficult.'],
        ['Solutions:', 'Roads, health care, fertilisers and reforestation improve life.']] },
  ],
  evaluation: [['Give two resources of the equatorial zone.', 'Timber and farmland (cocoa).'], ['What is bush fallowing?', 'Leaving land to rest for some years so that it becomes fertile again.']],
  remediation: ['The equatorial zone is covered by a dense ______.', 'Moving from one farm to another is ______ cultivation.', 'Leaving land to rest is ______.'],
  remediationAnswers: '1. forest 2. shifting 3. fallowing',
  homework: 'List five products from the equatorial forest sold in your local market.',
  hwAnswer: 'Plantains, cassava, cocoa (chocolate), timber (planks), bush mango (ndo\'o) or palm oil.',
  bilingual: [['Forest', 'La forêt'], ['Timber', "Le bois d'œuvre"], ['Shifting cultivation', "L'agriculture itinérante"], ['Fallow', 'La jachère'], ['Cocoa', 'Le cacao'], ['Road', 'La route']],
});

L.push({ kind: 'Further Study', no: 1, title: 'Deforestation in Cameroon', subtopic: 'Exploitation of Resources in the Natural Environment',
  notions: 'Deforestation, logging, reforestation, protected area.',
  focus: 'Causes, manifestations, consequences and solutions of deforestation in Cameroon.',
  competence: 'Learners are able to explain deforestation in Cameroon and propose solutions.',
  objectives: ['Give the causes of deforestation in Cameroon.', 'Describe its manifestations and consequences.', 'Propose solutions.'],
  recall: ['Southern Cameroon has a dense forest.', 'Timber is exported.', 'Farmers clear forest for farms.'],
  situation: 'Satellite images show that large areas of forest in the East and South of Cameroon have disappeared in the last thirty years. Some animals are becoming rare.',
  sitQA: [['What is the problem in the situation?', 'The forests of Cameroon are disappearing.'], ['Which regions are affected?', 'The East and the South.'], ['What happens to the animals?', 'They become rare.']],
  justification: 'This further study helps us to understand and fight deforestation.',
  action: 'Plant trees and use improved stoves that need less wood.',
  activities: [
    { sec: '1. CAUSES', img: 'f2t_logging_truck.jpg', caption: 'A logging truck in the East of Cameroon.', q: 'Give two causes of deforestation in Cameroon.', a: 'Logging for timber and clearing for farms (also firewood, mining, roads).', noProj: 'list uses of wood.' },
    { sec: '2. MANIFESTATIONS', img: 'usa_clearcut.jpg', caption: 'A forest cleared by logging.', q: 'How can we see deforestation?', a: 'Large bare areas, stumps and roads cut through the forest.', noProj: 'describe a cleared forest.' },
    { sec: '3. CONSEQUENCES', img: 'f4_gully.jpg', caption: 'Soil erosion.', q: 'Give two consequences of deforestation.', a: 'Soil erosion and loss of animals and plants (also climate change).', noProj: 'discuss effects on villages.' },
    { sec: '4. SOLUTIONS', img: 'cmr_forest_big.png', caption: 'Protected forests of Cameroon.', q: 'Name two protected areas of the forest of Cameroon.', a: 'The Dja reserve and the Lobéké park (also Korup, Campo-Ma\'an).', noProj: 'use the map.' },
    { sec: '4. SOLUTIONS', img: 'f2t_tree_planting.jpg', caption: 'Planting a young tree.', q: 'Give three solutions to deforestation.', a: 'Reforestation, protected areas and controlled logging (also improved stoves).', noProj: 'plan a tree-planting day.' },
  ],
  summary: [
    D([['Deforestation:', 'It is the destruction of forests by people.']]),
    { title: '1. Causes and Manifestations', intro: 'Deforestation in Cameroon has the following causes:',
      items: [['Logging:', 'Companies cut valuable trees for timber and export.'],
        ['Farming:', 'Farmers clear forest for shifting cultivation and plantations.'],
        ['Firewood and settlements:', 'People cut trees for firewood, charcoal, roads and houses.'],
        ['Manifestations:', 'Bare areas, stumps and new roads appear in the forest.']] },
    { title: '2. Consequences', intro: 'Deforestation has the following consequences:',
      items: [['Environment:', 'Soils are eroded, rivers dry up and animals disappear.'],
        ['Climate:', 'Less forest means more carbon dioxide and a warmer climate.'],
        ['People:', 'Forest peoples lose food, medicines and income.']] },
    { title: '3. Solutions', intro: 'Deforestation can be reduced by the following solutions:',
      items: [['Reforestation:', 'People plant trees where forests were cut.'],
        ['Protected areas:', 'Parks such as the Dja, Lobéké and Korup protect forests.'],
        ['Laws and controls:', 'The Forestry Law of 1994 controls logging.']],
      draw: { img: 'cmr_forest_big.png', caption: 'forests and protected areas of Cameroon' } },
  ],
  evaluation: [['Give two causes of deforestation in Cameroon.', 'Logging and farming.'], ['Give two solutions.', 'Reforestation and protected areas.']],
  remediation: ['The destruction of forests is ______.', 'Planting new trees is ______.', 'The Dja is a ______ area.'],
  remediationAnswers: '1. deforestation 2. reforestation 3. protected',
  homework: 'Write three things your family can do to reduce the use of firewood.',
  hwAnswer: 'Use an improved stove; use cooking gas when possible; plant fast-growing trees for firewood.',
  bilingual: [['Deforestation', 'La déforestation'], ['Logging', "L'exploitation forestière"], ['Reserve', 'La réserve'], ['Tree', "L'arbre"], ['Firewood', 'Le bois de chauffe'], ['Law', 'La loi']],
});

L.push({ no: 4, title: 'Man in the Tropical Zone', subtopic: 'Exploitation of Resources in the Natural Environment',
  notions: 'Tropical grassland, pastoral nomadism, wildlife, crop rotation, bush fallowing, cereals.',
  focus: 'Location; climatic characteristics; resources; methods of exploitation; problems faced; proposed solutions.',
  competence: 'Learners are able to describe how people use the resources of the tropical zone and solve its problems.',
  objectives: ['Locate the tropical zone and describe its climate.', 'Describe its resources and methods of exploitation.', 'Explain the problems faced and propose solutions.'],
  recall: ['Garoua has a rainy and a dry season.', 'The savanna has grass and scattered trees.', 'Many cattle are reared in the north.'],
  situation: 'Near Garoua, farmers grow cotton, maize and sorghum in the rainy season. In the dry season, herders move their cattle to find grass and water, and sometimes the cattle enter the farms.',
  sitQA: [['What is the problem in the situation?', 'Farmers and herders compete for land and water.'], ['Name two crops of the area.', 'Cotton and sorghum (also maize).'], ['Why do herders move in the dry season?', 'To find grass and water.']],
  justification: 'This lesson helps us to understand life and activities in our own tropical zone.',
  action: 'Respect grazing zones and protect wildlife.',
  activities: [
    { sec: '1. LOCATION', img: 'savanna_africa_big.png', caption: 'The savanna regions of Africa.', q: 'Between which latitudes is the tropical zone found?', a: 'Between about 5° and 15° north and south of the Equator.', noProj: 'use the atlas.' },
    { sec: '1. CLIMATE', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'Describe the tropical climate.', a: 'Hot all year, with a rainy season and a dry season.', noProj: 'describe the seasons of Garoua.' },
    { sec: '2. RESOURCES', img: 'f2t_elephants.jpg', caption: 'Wildlife in the savanna.', q: 'Name three resources of the tropical zone.', a: 'Grass for cattle, land for cereals and cotton, and wildlife (also rivers).', noProj: 'list resources of the North.' },
    { sec: '3. METHODS OF EXPLOITATION', img: 'transhumance.gif', caption: 'Animation: herders move with their cattle.', q: 'What is pastoral nomadism?', a: 'Moving with animals from place to place to find grass and water.', noProj: 'describe herders of the North.' },
    { sec: '4. PROBLEMS AND SOLUTIONS', img: 'f2t_bushfire.jpg', caption: 'A bush fire.', q: 'Give two problems and two solutions.', a: 'Problems: drought, bush fires, farmer–herder conflicts. Solutions: irrigation, firebreaks and grazing zones.', noProj: 'discuss problems of the North.' },
  ],
  summary: [
    { title: '1. Location and Climate', intro: 'The tropical zone is presented as follows:',
      items: [['Location:', 'It lies between about 5° and 15° north and south of the Equator, including northern Cameroon.'],
        ['Climate:', 'It is hot all year with a rainy season and a long dry season.']],
      draw: { img: 'savanna_africa_big.png', caption: 'the savanna regions of Africa' } },
    { title: '2. Resources and Methods of Exploitation', intro: 'The resources of the tropical zone are exploited as follows:',
      items: [['Crop farming:', 'Farmers grow cereals (sorghum, millet, maize) and cotton using bush fallowing and crop rotation.'],
        ['Livestock:', 'Herders practise pastoral nomadism and transhumance with cattle, sheep and goats.'],
        ['Wildlife:', 'National parks such as Waza and Bénoué attract tourists.']] },
    { title: '3. Problems and Solutions', intro: 'People face the following problems and solutions:',
      items: [['Problems:', 'Drought, bush fires, soil erosion and farmer–herder conflicts affect the zone.'],
        ['Solutions:', 'Irrigation, firebreaks, tree planting and grazing zones reduce these problems.']] },
  ],
  evaluation: [['Give two cereals of the tropical zone.', 'Sorghum and millet (also maize).'], ['Give two problems of the tropical zone.', 'Drought and bush fires.']],
  remediation: ['Moving with animals to find grass is pastoral ______.', 'Changing crops on the same land each year is crop ______.', 'A park in the North is ______.'],
  remediationAnswers: '1. nomadism 2. rotation 3. Bénoué (or Waza)',
  homework: 'Write the calendar of a farmer near Garoua: what he does in each season.',
  hwAnswer: 'Rainy season (May–October): clearing, sowing, weeding and harvesting cotton, maize and sorghum. Dry season: harvesting late crops, onion gardening near rivers and repairing tools.',
  bilingual: [['Savanna', 'La savane'], ['Cattle', 'Le bétail'], ['Herder', "L'éleveur"], ['Cereal', 'La céréale'], ['Cotton', 'Le coton'], ['Drought', 'La sécheresse']],
});

L.push({ kind: 'Further Study', no: 2, title: 'The Firewood Crisis', subtopic: 'Exploitation of Resources in the Natural Environment',
  notions: 'Firewood, charcoal, fuel, improved stove, alternative energy.',
  focus: 'Causes, manifestations, consequences and solutions of the firewood crisis.',
  competence: 'Learners are able to explain the firewood crisis and use energy that saves trees.',
  objectives: ['Give the causes of the firewood crisis.', 'Describe its manifestations and consequences.', 'Propose solutions.'],
  recall: ['Most families cook with firewood or charcoal.', 'Trees are cut around towns.', 'The North is dry.'],
  situation: 'Women in a village near Garoua now walk more than three hours to find firewood, and the price of a bundle of wood in town has doubled in five years.',
  sitQA: [['What is the problem in the situation?', 'Firewood is becoming scarce and expensive.'], ['What shows the crisis?', 'Long walks and high prices.'], ['Who suffers most?', 'Women and children who fetch wood.']],
  justification: 'This further study helps us to understand the firewood crisis and save trees.',
  action: 'Use improved stoves and cooking gas, and plant trees for firewood.',
  activities: [
    { sec: '1. CAUSES', img: 'f2t_charcoal.jpg', caption: 'Bags of charcoal for sale.', q: 'Why is firewood becoming scarce?', a: 'Many people use wood and charcoal, trees are cut faster than they grow, and there are few trees in dry areas.', noProj: 'ask how families cook.' },
    { sec: '2. MANIFESTATIONS', img: 'f4_fetchwater.jpg', caption: 'Women carrying loads over long distances.', q: 'How do we see the firewood crisis?', a: 'People walk far to find wood and its price rises.', noProj: 'ask about the price of wood.' },
    { sec: '3. CONSEQUENCES', img: 'f2t_clearing.jpg', caption: 'Cut trees.', q: 'Give two consequences of the firewood crisis.', a: 'Deforestation and desertification, and loss of time and money for families.', noProj: 'discuss effects on women.' },
    { sec: '4. SOLUTIONS', img: 'f4_solar.jpg', caption: 'Solar energy.', q: 'Give two alternative sources of energy for cooking.', a: 'Cooking gas and solar cookers (also biogas).', noProj: 'list energy sources.' },
    { sec: '4. SOLUTIONS', img: 'f2t_tree_planting_sahel.jpg', caption: 'Planting trees in a dry area.', q: 'How can tree planting solve the crisis?', a: 'Fast-growing trees give firewood without destroying natural forests.', noProj: 'plan a woodlot.' },
  ],
  summary: [
    D([['Firewood crisis:', 'It is the shortage of wood used for cooking and heating.']]),
    { title: '1. Causes and Manifestations', intro: 'The firewood crisis has the following causes and signs:',
      items: [['Causes:', 'Rapid population growth and cutting trees faster than they grow cause the crisis.'],
        ['Manifestations:', 'People walk long distances to find wood and prices rise.']] },
    { title: '2. Consequences', intro: 'The crisis has the following consequences:',
      items: [['Environment:', 'Deforestation leads to soil erosion and desertification.'],
        ['People:', 'Women and children lose time and families spend more money.']] },
    { title: '3. Solutions', intro: 'The crisis can be solved by the following measures:',
      items: [['Improved stoves:', 'They use less wood for cooking.'],
        ['Alternative energy:', 'Cooking gas, biogas and solar cookers replace wood.'],
        ['Tree planting:', 'Woodlots of fast-growing trees provide firewood.']] },
  ],
  evaluation: [['Give two causes of the firewood crisis.', 'Population growth and over-cutting of trees.'], ['Give two solutions.', 'Improved stoves and cooking gas.']],
  remediation: ['Wood burnt without air to make fuel is ______.', 'A stove that uses less wood is an ______ stove.', 'Gas from animal waste is ______.'],
  remediationAnswers: '1. charcoal 2. improved 3. biogas',
  homework: 'Ask your family how much they spend on firewood or charcoal each week.',
  hwAnswer: 'Answers vary. Example: about 3,000 to 5,000 FCFA a week for firewood or a bag of charcoal.',
  bilingual: [['Firewood', 'Le bois de chauffe'], ['Charcoal', 'Le charbon de bois'], ['Stove', 'Le foyer'], ['Gas', 'Le gaz'], ['Crisis', 'La crise'], ['Energy', "L'énergie"]],
});

L.push({ kind: 'Further Study', no: 3, title: 'Products Gathered from the Wild in Cameroon', subtopic: 'Exploitation of Resources in the Natural Environment',
  notions: 'Non-timber forest products, njangsa, eru, bush mango, bitter cola, gathering.',
  focus: 'Identification of various products (njangsa, eru, bush mango, bitter cola, etc.); methods of collection and processing; socio-cultural and economic importance.',
  competence: 'Learners are able to identify wild products of Cameroon and explain their importance.',
  objectives: ['Identify products gathered from the wild in Cameroon.', 'Describe methods of collection.', 'Explain their socio-cultural and economic importance.'],
  recall: ['The forest gives timber.', 'People gather fruits and leaves.', 'Markets sell many forest products.'],
  situation: 'In the market of Garoua, Aïcha sees eru leaves, njangsa seeds, bush mango, honey and bitter cola that come from the forests of the South. The trader says she earns her living from these products.',
  sitQA: [['What is the problem in the situation?', 'Aïcha wants to know the products gathered from the wild.'], ['Name three products she sees.', 'Eru, njangsa and bush mango (also bitter cola, honey).'], ['Why are they important to the trader?', 'They give her an income.']],
  justification: 'This further study helps us to know the value of wild products and protect them.',
  action: 'Harvest wild products without destroying the plants.',
  activities: [
    { sec: '1. IDENTIFICATION', img: 'lsa_herbs.jpg', caption: 'Wild products in a market.', q: 'Name four products gathered from the wild in Cameroon.', a: 'Eru, njangsa, bush mango and bitter cola (also honey, shea nuts, mushrooms).', noProj: 'bring examples from the market.' },
    { sec: '1. IDENTIFICATION', img: 'f2t_shea_tree.jpg', caption: 'A shea tree.', q: 'Which wild product of the North is made from the shea tree?', a: 'Shea butter.', noProj: 'describe shea butter.' },
    { sec: '2. METHODS OF COLLECTION', img: 'lsa_bee.jpg', caption: 'A bee.', q: 'How are honey and fruits collected from the wild?', a: 'Honey is taken from hives in trees; fruits and nuts are picked from the ground or trees.', noProj: 'describe harvesting.' },
    { sec: '3. ECONOMIC IMPORTANCE', img: 'f2t_market.jpg', caption: 'A market.', q: 'How are wild products economically important?', a: 'They are sold for income and some, like eru, are exported to Nigeria and Europe.', noProj: 'list prices in the market.' },
    { sec: '3. SOCIO-CULTURAL IMPORTANCE', img: 'f2t_rainforest.jpg', caption: 'The forest.', q: 'Give one socio-cultural use of wild products.', a: 'Bitter cola and cola nuts are shared at ceremonies; many plants are used as traditional medicine.', noProj: 'ask about cola nuts at ceremonies.' },
  ],
  summary: [
    D([['Wild product:', 'It is a plant or animal product collected from nature without being cultivated.']]),
    { title: '1. Identification', intro: 'Cameroon has the following wild products:',
      items: [['Leaves and seeds:', 'Eru, njangsa and bush mango are used in cooking.'],
        ['Nuts and fruits:', 'Bitter cola, cola nuts and shea nuts are gathered.'],
        ['Other products:', 'Honey, mushrooms, medicinal plants and rattan are also collected.']] },
    { title: '2. Methods of Collection', intro: 'Wild products are collected in the following ways:',
      items: [['Picking:', 'Fruits, nuts and leaves are picked from trees or the ground.'],
        ['Processing:', 'Products are dried, cracked or pressed, as shea nuts are made into butter.']] },
    { title: '3. Importance', intro: 'Wild products are important in the following ways:',
      items: [['Economic importance:', 'They give income to gatherers and traders and some are exported.'],
        ['Socio-cultural importance:', 'They are used in food, ceremonies and traditional medicine.']] },
  ],
  evaluation: [['Name four wild products of Cameroon.', 'Eru, njangsa, bush mango and bitter cola.'], ['Give one economic importance.', 'They give income to families.']],
  remediation: ['Shea butter comes from the ______ tree.', 'A leaf vegetable gathered in the forest is ______.', 'Wild products are used as traditional ______.'],
  remediationAnswers: '1. shea 2. eru 3. medicine',
  homework: 'Visit the market and write the price of three wild products.',
  hwAnswer: 'Answers vary. Example: a bundle of eru 500 FCFA; a cup of njangsa 1,000 FCFA; a bitter cola nut 100 FCFA.',
  bilingual: [['Gathering', 'La cueillette'], ['Honey', 'Le miel'], ['Nut', 'La noix'], ['Leaf', 'La feuille'], ['Market', 'Le marché'], ['Medicine', 'Le médicament']],
});

L.push({ kind: 'Practical Work', no: 3, title: 'Identification of the Biological Resources of Cameroon', subtopic: 'Exploitation of Resources in the Natural Environment',
  notions: 'Biological resources, biodiversity, flora, fauna, protected species, natural region.',
  focus: 'Recall of resources, biodiversity and natural region; identifying natural resources from samples and photographs; stating their uses; identifying protected species; debate on protection.',
  competence: 'Learners are able to identify plant and animal resources of Cameroon, state their uses and name protected species.',
  objectives: ['Recall the notions of resource, biodiversity and natural region.', 'Identify plant and animal resources and their uses.', 'Identify protected species of their region.'],
  recall: ['Cameroon has forest and savanna regions.', 'People use plants and animals.', 'National parks protect animals.'],
  situation: 'Cameroon is called "Africa in miniature" because it has many plants and animals. The class receives photos and samples and must say what each one is, where it lives and how it is used.',
  sitQA: [['What is the problem in the situation?', 'The class must identify the plants and animals of Cameroon.'], ['Why is Cameroon called "Africa in miniature"?', 'It has almost all the landscapes, plants and animals of Africa.'], ['What must be protected?', 'Rare plants and animals (protected species).']],
  justification: 'This practical work helps us to know and protect the living riches of Cameroon.',
  action: 'Protect rare plants and animals and denounce poaching.',
  activities: [
    { sec: '1. RECALL', img: 'cameroon_veg_big.png', caption: 'The natural regions of Cameroon.', q: 'What is biodiversity?', a: 'The variety of plants and animals in a place.', noProj: 'list plants and animals known.' },
    { sec: '2. PLANT RESOURCES', img: 'f2t_baobab.jpg', caption: 'A baobab tree.', q: 'Identify this tree, its region and one use.', a: 'The baobab of the savanna; its leaves and fruits are eaten.', noProj: 'bring leaves or samples.' },
    { sec: '2. PLANT RESOURCES', img: 'f2t_rainforest.jpg', caption: 'The rainforest.', q: 'Name two useful trees of the forest region and their uses.', a: 'Sapele and iroko for timber; oil palm for oil.', noProj: 'list furniture woods.' },
    { sec: '3. ANIMAL RESOURCES', img: 'f2t_elephants.jpg', caption: 'Elephants.', q: 'Name two protected animals of Cameroon.', a: 'The elephant and the gorilla (also the lion, the giraffe, the chimpanzee).', noProj: 'list animals of the parks.' },
    { sec: '4. PROTECTION', img: 'lsa_lion.jpg', caption: 'A lion.', q: 'Give two arguments for protecting species.', a: 'They are part of our heritage and bring tourists; if killed they disappear forever.', noProj: 'hold a short debate.' },
  ],
  summary: [
    D([['Biological resources:', 'They are the plants and animals that people can use.'],
      ['Biodiversity:', 'It is the variety of plants and animals in a place.']]),
    { title: '1. Plant Resources', intro: 'Cameroon has the following plant resources:',
      items: [['Forest region:', 'Sapele, iroko, ebony and oil palm give timber and oil.'],
        ['Savanna region:', 'Baobab, shea, acacia and grass give food, butter, gum and pasture.']] },
    { title: '2. Animal Resources', intro: 'Cameroon has the following animal resources:',
      items: [['Forest animals:', 'Gorillas, chimpanzees, forest elephants and many birds live in the forest.'],
        ['Savanna animals:', 'Lions, giraffes, elephants and antelopes live in parks such as Waza and Bénoué.']] },
    { title: '3. Protected Species', intro: 'Some species must be protected for the following reasons:',
      items: [['Protected species:', 'Elephants, gorillas, lions and giraffes are protected by law.'],
        ['Reasons:', 'Protection keeps biodiversity, attracts tourists and preserves our heritage.']] },
  ],
  evaluation: [['Name two plant resources and their uses.', 'Shea tree (butter) and sapele (timber).'], ['Name two protected animals.', 'Elephant and gorilla.']],
  remediation: ['The variety of living things is ______.', 'A protected ape of the forest is the ______.', 'Waza is a national ______.'],
  remediationAnswers: '1. biodiversity 2. gorilla 3. park',
  homework: 'List three plants and three animals of your region and one use of each.',
  hwAnswer: 'Plants: shea tree (butter), baobab (leaves), acacia (gum). Animals: cattle (meat, milk), goats (meat), bees (honey).',
  bilingual: [['Biodiversity', 'La biodiversité'], ['Species', "L'espèce"], ['Protected', 'Protégé'], ['Wildlife', 'La faune sauvage'], ['Tree', "L'arbre"], ['Park', 'Le parc']],
});

L.push({ no: 5, title: 'Man in the Hot Desert Milieu', subtopic: 'Exploitation of Resources in the Natural Environment',
  notions: 'Oasis, irrigation, pastoral nomadism, hot desert.',
  focus: 'Location; climatic characteristics; resources; traditional methods of exploitation; problems faced; proposed solutions.',
  competence: 'Learners are able to describe how people live in hot deserts and solve their problems.',
  objectives: ['Locate the hot deserts and describe their climate.', 'Describe their resources and traditional methods of exploitation.', 'Explain the problems faced and propose solutions.'],
  recall: ['The Sahara is north of Cameroon.', 'Deserts receive very little rain.', 'The Harmattan comes from the Sahara.'],
  situation: 'A Tuareg family moves with its camels across the Sahara from one well to another. At an oasis, farmers grow dates under palm trees with water from a well.',
  sitQA: [['What is the problem in the situation?', 'People must find water to live in the desert.'], ['Which animal carries the family?', 'The camel.'], ['Where do farmers grow dates?', 'At an oasis.']],
  justification: 'This lesson helps us to understand how people survive in hot deserts.',
  action: 'Save water every day, as desert peoples do.',
  activities: [
    { sec: '1. LOCATION', img: 'deserts_world_big.png', caption: 'Hot deserts of the world.', q: 'Name three hot deserts.', a: 'The Sahara, the Kalahari and the Arabian Desert.', noProj: 'use the atlas.' },
    { sec: '1. CLIMATE', img: 'f2t_erg.jpg', caption: 'A sandy desert.', q: 'Describe the climate of hot deserts.', a: 'Less than 250 mm of rain, very hot days and cold nights.', noProj: 'compare with Garoua.' },
    { sec: '2. RESOURCES', img: 'f2t_oasis.jpg', caption: 'An oasis.', q: 'Name three resources of hot deserts.', a: 'Water at oases, oil and minerals, and sunshine (also dates).', noProj: 'list desert resources.' },
    { sec: '3. TRADITIONAL EXPLOITATION', img: 'f2t_camels.jpg', caption: 'Camels in the desert.', q: 'How do nomads use the desert?', a: 'They move with camels, goats and sheep from well to well to find water and pasture.', noProj: 'describe nomads of the Far North.' },
    { sec: '4. PROBLEMS AND SOLUTIONS', img: 'f2t_desert_well.jpg', caption: 'People at a desert well.', q: 'Give two problems and two solutions.', a: 'Problems: lack of water, sandstorms. Solutions: wells and irrigation, tree planting.', noProj: 'discuss water problems.' },
  ],
  summary: [
    { title: '1. Location and Climate', intro: 'Hot deserts are presented as follows:',
      items: [['Location:', 'Hot deserts lie near the tropics, like the Sahara, the Kalahari and the Arabian Desert.'],
        ['Climate:', 'They receive less than 250 mm of rain, with very hot days and cold nights.']],
      draw: { img: 'deserts_world_big.png', caption: 'hot deserts of the world' } },
    { title: '2. Resources and Traditional Exploitation', intro: 'People use the desert in the following ways:',
      items: [['Pastoral nomadism:', 'Nomads such as the Tuareg move with camels, goats and sheep.'],
        ['Oasis farming:', 'Farmers grow dates, vegetables and cereals with irrigation from wells.'],
        ['Other resources:', 'Oil, gas, uranium and sunshine are exploited today.']] },
    { title: '3. Problems and Solutions', intro: 'People face the following problems and solutions:',
      items: [['Problems:', 'Lack of water, heat, sandstorms and poor soils make life hard.'],
        ['Solutions:', 'Deep wells, irrigation, tree planting and solar energy help people.']] },
  ],
  evaluation: [['Give two resources of hot deserts.', 'Water at oases and oil.'], ['Give two problems of the desert.', 'Lack of water and sandstorms.']],
  remediation: ['A green place in the desert with water is an ______.', 'The animal of the desert is the ______.', 'Bringing water to fields is ______.'],
  remediationAnswers: '1. oasis 2. camel 3. irrigation',
  homework: 'Write three ways people in the Far North of Cameroon save water.',
  hwAnswer: 'They store rainwater in jars, dig wells and use water carefully for cooking, washing and animals.',
  bilingual: [['Desert', 'Le désert'], ['Oasis', "L'oasis"], ['Camel', 'Le chameau'], ['Well', 'Le puits'], ['Nomad', 'Le nomade'], ['Sand', 'Le sable']],
});

L.push({ kind: 'Further Study', no: 4, title: 'Water Scarcity', subtopic: 'Exploitation of Resources in the Natural Environment',
  notions: 'Water scarcity, quantity, quality, water management, uses of water.',
  focus: 'Enquiry on the problem of water scarcity: quantity, quality, management and uses.',
  competence: 'Learners are able to investigate water scarcity in their area and propose ways to manage water.',
  objectives: ['Define water scarcity.', 'Describe the problems of quantity and quality of water.', 'Propose ways to manage and use water well.'],
  recall: ['People need water every day.', 'The dry season is long in the north.', 'Dirty water causes diseases.'],
  situation: 'In the dry season, the tap in Ali\'s quarter of Garoua runs only two days a week. His family buys water from sellers and sometimes drinks water from a well that is not clean.',
  sitQA: [['What is the problem in the situation?', 'There is not enough clean water.'], ['How does the family get water?', 'From sellers and a well.'], ['What danger does the well water bring?', 'Diseases like cholera and typhoid.']],
  justification: 'This further study helps us to understand water problems and use water wisely.',
  action: 'Close taps, repair leaks, store rainwater and treat drinking water.',
  activities: [
    { sec: '1. MEANING', img: 'f4_fetchwater.jpg', caption: 'Women fetching water.', q: 'What is water scarcity?', a: 'A lack of enough clean water for people\'s needs.', noProj: 'ask where families get water.' },
    { sec: '2. QUANTITY', img: 'world_water_big.png', caption: 'Water on the Earth.', q: 'What part of the Earth\'s water is fresh water?', a: 'Only about 2.5 %; most is salty sea water.', noProj: 'draw a bar of 100 %.' },
    { sec: '3. QUALITY', img: 'f4_borehole.jpg', caption: 'A borehole.', q: 'Why is borehole water safer than water from an open well?', a: 'It comes from deep underground and is protected from dirt.', noProj: 'describe water sources of the quarter.' },
    { sec: '4. USES', img: 'f4_leakingtap.jpg', caption: 'A leaking tap.', q: 'Give three uses of water and one way we waste it.', a: 'Drinking, cooking and washing (also farming); leaking taps waste water.', noProj: 'list uses at home.' },
    { sec: '5. MANAGEMENT', img: 'rainwater_big.png', caption: 'Collecting rainwater.', q: 'Give three ways to manage water well.', a: 'Store rainwater, repair leaks and treat drinking water (also build boreholes).', noProj: 'design a water plan for the school.' },
  ],
  summary: [
    D([['Water scarcity:', 'It is a lack of enough clean water to meet people\'s needs.']]),
    { title: '1. Quantity and Quality', intro: 'Water scarcity is a problem of quantity and quality:',
      items: [['Quantity:', 'Long dry seasons, droughts and population growth reduce the water available.'],
        ['Quality:', 'Dirty water from open wells and rivers causes cholera and typhoid.']] },
    { title: '2. Uses of Water', intro: 'Water has the following uses:',
      items: [['Domestic uses:', 'We use water for drinking, cooking and washing.'],
        ['Economic uses:', 'Farmers, herders and factories need water.']] },
    { title: '3. Management', intro: 'Water can be managed with the following measures:',
      items: [['Saving water:', 'We close taps and repair leaks.'],
        ['Storing water:', 'We collect rainwater in tanks and build dams.'],
        ['Clean water:', 'We boil or filter water and build boreholes.']],
      draw: { img: 'rainwater_big.png', caption: 'collecting rainwater' } },
  ],
  evaluation: [['What is water scarcity?', 'A lack of enough clean water.'], ['Give two ways to manage water.', 'Store rainwater and repair leaks.']],
  remediation: ['Only about ______ % of the Earth\'s water is fresh.', 'A deep well dug with machines is a ______.', 'Dirty water causes ______.'],
  remediationAnswers: '1. 2.5 2. borehole 3. cholera (or typhoid)',
  homework: 'Carry out a small enquiry: ask three families where they get water and what problems they have.',
  hwAnswer: 'Answers vary. Typical results: tap water that runs irregularly, buying water from sellers, wells that dry up in the dry season, and fear of dirty water.',
  bilingual: [['Water', "L'eau"], ['Scarcity', 'La pénurie'], ['Well', 'Le puits'], ['Tap', 'Le robinet'], ['Clean', 'Propre'], ['Enquiry', "L'enquête"]],
});

module.exports = { B, L };
