// FORM 2 — Module 2: Space Occupation (2023 national syllabus): L6, L7, FS5, PW4, FS6, L8, FS7
// Revised model (Sept 2026): syllabus points in order, definitions apart, one element per slide with its picture,
// problem visible in the situation, one question per slide in the activities.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F2', code: 'M2', folder: '', module: 'Module 2: Space Occupation', topicDefault: 'Space Occupation', branch: 'Country Sides and Towns of Africa',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 2, Module 2: Space Occupation.'] };
const L = [];

L.push({ no: 6, title: 'Country Sides in Africa', subtopic: 'Country Sides and Towns of Africa',
  notions: 'Rural landscape, agricultural landscape, rural settlement, land.',
  focus: 'Agricultural landscape; rural settlements; attractive and repulsive aspects of rural areas (emphasis on the attractive aspects).',
  competence: 'Learners are able to describe rural areas of Africa and appreciate their attractive aspects.',
  objectives: ['Describe the agricultural landscape of African country sides.', 'Describe the building materials, types, forms and patterns of rural settlements.', 'Identify the attractive and repulsive aspects of rural areas.'],
  recall: ['Most Africans live in villages.', 'Villagers are mostly farmers.', 'Villages have fewer services than towns.'],
  situation: 'Awa\'s cousin in Yaoundé says that village life is boring and poor. Awa, who lives in a village near Guider, answers that the village has fresh food, clean air and solidarity. Their teacher asks the class: "Who is right: is the country side only a place of problems, or does it also have good sides?"',
  sitQA: [['What is the problem in the situation?', 'The two girls disagree: we must find out whether the country side has only problems or also attractive aspects.'], ['Give one negative view of the village.', 'It is boring and poor.'], ['Give two attractive aspects of the village.', 'Fresh food and solidarity (also clean air).']],
  justification: 'This lesson helps us to know and appreciate the country sides of Africa.',
  action: 'Value village life and contribute to the development of your village.',
  activities: [
    { sec: '1. AGRICULTURAL LANDSCAPE', img: 'f2t_cotton_field.jpg', caption: 'A cotton field near Garoua.', q: 'What covers most of the land in this rural landscape?', a: 'Fields of crops: here, cotton.', noProj: 'describe farms around the village.' },
    { sec: '2. RURAL SETTLEMENTS', img: 'usa_hillvillage.jpg', caption: 'A village of round huts.', q: ['What shape are the houses of this village?', 'With what materials are they built?'], a: ['They are round huts.', 'Mud walls and grass (thatched) roofs.'], noProj: 'describe houses in your village.' },
    { sec: '2. RURAL SETTLEMENTS', img: 'patterns_big.png', caption: 'Patterns of rural settlements.', q: 'In which pattern are the houses grouped closely together?', a: 'The nucleated (grouped) pattern.', noProj: 'draw the patterns on the board.' },
    { sec: '3. ATTRACTIVE ASPECTS', img: 'usa_bandjoun.jpg', caption: 'A chiefdom in the West of Cameroon.', q: 'What can attract a town dweller to a village like this?', a: 'Its traditions and culture, its calm life, fresh food and solidarity.', noProj: 'list what learners like in villages.' },
    { sec: '3. REPULSIVE ASPECTS', img: 'f2t_muddy_road.jpg', caption: 'A bad rural road.', q: 'Why does this road push young people away from the village?', a: 'It makes travel and trade difficult; villages also lack jobs, hospitals and electricity.', noProj: 'discuss problems of villages.' },
  ],
  summary: [
    D([['Country side:', 'It is the rural area outside towns, where most people live from farming, herding or fishing.'],
      ['Rural landscape:', 'It is the appearance of the country side, made of fields, pastures, bush and villages.'],
      ['Rural settlement:', 'It is a group of dwellings in the country side, such as a village or a hamlet.']]),
    { title: '1. The Agricultural Landscape', intro: 'The agricultural landscape of African country sides is made of the following elements:',
      items: [['Food crop fields:', 'Fields of maize, millet, sorghum, cassava and groundnuts surround the villages.', 'f2t_cassava_farm.jpg', 'a cassava farm'],
        ['Cash crop fields and plantations:', 'Cotton, cocoa, coffee and oil palm are grown for sale, on small farms or on large plantations.', 'f2t_cotton_field.jpg', 'a cotton field'],
        ['Pastures:', 'Herders graze cattle, sheep and goats on grassland, especially in the savanna.', 'usa_herders.jpg', 'herders and cattle'],
        ['Fallow land and bush:', 'Some land is left to rest to recover its fertility, and bush and forest remain between the fields.'],
        ['Open and enclosed fields:', 'In the savanna, fields are usually open, while in the Western Highlands they are often enclosed by hedges.']] },
    { title: '2. Rural Settlements', sub: 'A) Building Materials', intro: 'Rural houses are built with the following local materials:',
      items: [['Mud (earth):', 'Mud or mud bricks are used for the walls of most rural houses.', 'usa_hillvillage.jpg', 'mud huts with grass roofs'],
        ['Grass (thatch):', 'Dry grass is used for roofs, especially in the savanna.'],
        ['Wood, bamboo and raffia:', 'They are used for walls and roofs in forest areas.'],
        ['Stone:', 'Stones are used for walls in mountain areas such as the Mandara Mountains.'],
        ['Modern materials:', 'Cement blocks and zinc sheets are more and more used in villages.']] },
    { title: '2. Rural Settlements', sub: 'B) Types of Rural Dwellings', intro: 'The main types of rural dwellings are the following:',
      items: [['Round huts:', 'They have a circular mud wall and a conical grass roof, as in the North of Cameroon.'],
        ['Rectangular houses:', 'They have straight walls and a roof of thatch or zinc, as in the forest South.'],
        ['Compounds (saré):', 'Several huts of one family are grouped inside a fence or wall.'],
        ['Square houses with high roofs:', 'They are typical of the chiefdoms of the Western Highlands.', 'usa_bandjoun.jpg', 'a chiefdom of the West']] },
    { title: '2. Rural Settlements', sub: 'C) Patterns of Rural Settlements', intro: 'Rural settlements are spread over the land in the following patterns:',
      items: [['Nucleated (grouped) pattern:', 'The houses are grouped closely together, often around a chief\'s compound, a water point or a market.', 'patterns_big.png', 'patterns of rural settlements'],
        ['Dispersed (scattered) pattern:', 'The houses are far from one another, each one on its farm.'],
        ['Linear pattern:', 'The houses are built in a line along a road, a river or a valley.'],
        ['Regular (planned) pattern:', 'The houses are placed at equal distances, as in planned villages.']] },
    { title: '2. Rural Settlements', sub: 'D) Forms of Rural Settlements', intro: 'The main forms of rural settlements are the following:',
      items: [['Star form:', 'The houses spread along several roads that meet at one point.', 'rural_forms_big.png', 'forms of rural settlements'],
        ['Linear form:', 'The houses form one line along a single road.'],
        ['Rectangular form:', 'The houses are built around a square or an open space.'],
        ['Cruciform form:', 'The houses are built along two roads that cross each other.']] },
    { title: '3. Attractive and Repulsive Aspects', sub: 'A) Attractive Aspects', intro: 'Rural areas attract people for the following reasons:',
      items: [['Fresh and cheap food:', 'Food comes directly from the farms and costs little.', 'f2t_market.jpg', 'a rural market'],
        ['Clean air and a calm life:', 'There is little noise, pollution and traffic.'],
        ['Solidarity:', 'People know one another and help one another at work, in sickness and at funerals.'],
        ['Traditions and culture:', 'Chiefdoms, festivals, dances and crafts keep culture alive.', 'usa_bandjoun.jpg', 'a traditional chiefdom'],
        ['Available land:', 'Land is available for farming, herding and building a house.']] },
    { title: '3. Attractive and Repulsive Aspects', sub: 'B) Repulsive Aspects', intro: 'Rural areas push people away for the following reasons:',
      items: [['Bad roads:', 'Many roads are muddy in the rainy season, so travel and trade are difficult.', 'f2t_muddy_road.jpg', 'a bad rural road'],
        ['Lack of social amenities:', 'Hospitals, schools, electricity and pipe-borne water are scarce.'],
        ['Unemployment and poverty:', 'There are few paid jobs apart from farming, and incomes are low.'],
        ['Hard work:', 'Farming with hoes and cutlasses is tiring and gives low yields.']] },
  ],
  evaluation: [['Name three patterns of rural settlements.', 'Nucleated, dispersed and linear (also regular).'], ['Give two attractive aspects of rural areas.', 'Fresh food and solidarity.']],
  remediation: ['Houses grouped together form a ______ settlement.', 'Houses along a road form a ______ settlement.', 'The roof of a round hut is often made of ______.'],
  remediationAnswers: '1. nucleated 2. linear 3. grass (thatch)',
  homework: 'Describe your village or a village you know: its fields, its houses and two attractive aspects.',
  hwAnswer: 'Answers vary. Example: fields of maize and cotton around the village; round mud houses with grass roofs grouped around the chief\'s compound; fresh food and solidarity at harvest time.',
  bilingual: [['Village', 'Le village'], ['Countryside', 'La campagne'], ['Farmer', "L'agriculteur"], ['Hut', 'La case'], ['Field', 'Le champ'], ['Solidarity', 'La solidarité']],
});

L.push({ no: 7, title: 'Towns in Africa', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Town, urban landscape, city, informal sector, megalopolis.',
  focus: 'Urban landscapes; informal activities; problems of African towns and cities.',
  competence: 'Learners are able to identify, classify and describe African towns, their activities and their problems.',
  objectives: ['Describe the urban landscape of African towns and classify towns.', 'Identify informal activities in towns.', 'Explain the problems of African towns and cities.'],
  recall: ['Towns have many people and buildings.', 'Douala and Yaoundé are big cities.', 'Many young people move to towns.'],
  situation: 'Ibrahim visits Douala for the first time. He admires the tall buildings and the busy port, but he also sees street sellers everywhere, traffic jams and quarters with poor houses and dirty gutters. He asks his uncle: "Why does such a rich town also have so many problems?"',
  sitQA: [['What is the problem in the situation?', 'Ibrahim does not understand why a big, rich town also has many problems.'], ['Name two things he admires.', 'Tall buildings and the busy port.'], ['Name two problems of the town.', 'Traffic jams and poor quarters with dirty gutters.']],
  justification: 'This lesson helps us to understand life and problems in African towns.',
  action: 'Keep your town clean and respect traffic rules.',
  activities: [
    { sec: '1. URBAN LANDSCAPE', img: 'lsa_yaounde.jpg', caption: 'Yaoundé.', q: 'What shows that this place is a town and not a village?', a: 'Tall buildings, many roads and cars, and dense housing.', noProj: 'describe the centre of Garoua.' },
    { sec: '1. URBAN LANDSCAPE', img: 'cmr_towns_big.png', caption: 'The main towns of Cameroon.', q: ['Which are the two largest towns of Cameroon?', 'Is Garoua bigger or smaller than them?'], a: ['Douala and Yaoundé.', 'Smaller: it is a medium-sized town.'], noProj: 'use the atlas.' },
    { sec: '2. INFORMAL ACTIVITIES', img: 'f2t_street_vendor.jpg', caption: 'A street seller roasting maize.', q: 'Does this seller have a shop, a contract or a registered business?', a: 'No: he works on the street without registration; this is an informal activity.', noProj: 'list small jobs in town.' },
    { sec: '3. PROBLEMS', img: 'usa_traffic.jpg', caption: 'A traffic jam.', q: 'Why are there traffic jams in big African towns?', a: 'There are too many vehicles for narrow and badly maintained roads.', noProj: 'describe rush hour in town.' },
    { sec: '3. PROBLEMS', img: 'usa_slum.jpg', caption: 'A crowded poor quarter.', q: 'What problem of African towns does this picture show?', a: 'Poor housing: a slum, crowded and without services.', noProj: 'discuss poor quarters of Garoua.' },
  ],
  summary: [
    D([['Town:', 'It is a large, dense settlement where most people work in trade, industry and services.'],
      ['City:', 'It is a large and important town.'],
      ['Megalopolis:', 'It is a very large urban region formed when several big cities grow and join together.'],
      ['Informal sector:', 'It is all the small economic activities that are not registered and do not pay taxes regularly.']]),
    { title: '1. Urban Landscapes', sub: 'A) Elements of the Urban Landscape', intro: 'An African town has the following parts:',
      items: [['The centre (Central Business District):', 'It has offices, banks, big shops and tall buildings.', 'lsa_yaounde.jpg', 'the centre of Yaoundé'],
        ['Rich residential quarters:', 'They have large houses, gardens, tarred roads and all services.', 'usa_suburb.jpg', 'a rich residential quarter'],
        ['Poor quarters (slums):', 'They are crowded, with poor houses and few roads, drains or water points.', 'usa_slum.jpg', 'a poor quarter'],
        ['Industrial zones and ports:', 'Factories, warehouses and ports are found near railways, rivers or the sea, as in Douala.'],
        ['Markets and transport areas:', 'Big markets, bus stations and motor parks are crowded at all times.', 'usa_busstation.jpg', 'a bus station']] },
    { title: '1. Urban Landscapes', sub: 'B) Classification of Towns by Size', intro: 'Towns can be classified by their size as follows:',
      items: [['Small towns:', 'They have a few thousand to about 50,000 people, such as Poli and Tcholliré.'],
        ['Medium-sized towns:', 'They have about 50,000 to 1 million people, such as Garoua, Maroua and Bamenda.'],
        ['Millionaire cities:', 'They have more than 1 million people, such as Douala, Yaoundé and Kinshasa.', 'cmr_towns_big.png', 'the main towns of Cameroon'],
        ['Megalopolises:', 'They are chains of big cities joined together, such as the Lagos–Ibadan area in Nigeria.', 'urban_forms_big.png', 'city, conurbation and megalopolis']] },
    { title: '1. Urban Landscapes', sub: 'C) Classification of Towns by Function', intro: 'Towns can also be classified by their main function:',
      items: [['Administrative towns:', 'They are seats of government, such as Yaoundé, the political capital.', 'urban_functions_big.png', 'urban functions'],
        ['Commercial and port towns:', 'They live from trade and ports, such as Douala and Kribi.'],
        ['Industrial towns:', 'They have many factories, such as Edéa with its aluminium plant.'],
        ['Educational and religious towns:', 'They have universities or religious centres, such as Buea, Dschang and Ngaoundéré.']] },
    { title: '2. Informal Activities', intro: 'Many town dwellers work in the following informal activities:',
      items: [['Street trade:', 'Sellers of food, fruits, clothes and phone credit work on the streets and in markets.', 'f2t_street_vendor.jpg', 'a street seller'],
        ['Transport:', 'Moto-taxis and clandestine taxis carry people across the town.', 'f2t_moto_taxi.jpg', 'moto-taxis'],
        ['Crafts:', 'Tailors, carpenters, blacksmiths and hairdressers work in small workshops.', 'f2t_tailor.jpg', 'a tailor'],
        ['Repairs and services:', 'Mechanics, shoe repairers, phone repairers and mobile money agents serve the population.']] },
    { title: '3. Problems of African Towns and Cities', intro: 'African towns and cities face the following problems:',
      items: [['Unemployment:', 'There are not enough jobs for the many young people who arrive from villages.'],
        ['Poor housing (slums):', 'Many people live in crowded quarters without water, drains or electricity.', 'usa_slum.jpg', 'a slum'],
        ['Traffic jams:', 'Roads are too narrow for the growing number of vehicles.', 'usa_traffic.jpg', 'a traffic jam'],
        ['Waste and floods:', 'Rubbish blocks the gutters, and quarters are flooded after heavy rain.', 'lsa_streetflood.jpg', 'a flooded street'],
        ['Insecurity:', 'Poverty and unemployment favour theft and aggression.'],
        ['Lack of social amenities:', 'Schools, hospitals, water and electricity are not enough for everybody.']] },
  ],
  evaluation: [['Give two informal activities.', 'Street selling and moto-taxi driving.'], ['Give three problems of African towns.', 'Traffic jams, unemployment and slums.']],
  remediation: ['Small unregistered jobs form the ______ sector.', 'A crowded poor quarter is a ______.', 'A town of more than one million people is a ______ city.'],
  remediationAnswers: '1. informal 2. slum 3. millionaire',
  homework: 'List five informal activities you see on your way to school.',
  hwAnswer: 'Moto-taxi driving, selling roasted maize, selling fuel in bottles, shoe repairing, hairdressing in the street.',
  bilingual: [['Town', 'La ville'], ['City', 'La grande ville'], ['Traffic jam', "L'embouteillage"], ['Slum', 'Le bidonville'], ['Street seller', 'Le vendeur ambulant'], ['Unemployment', 'Le chômage']],
});

L.push({ kind: 'Further Study', no: 5, title: 'Informal Sector Activities in African Cities', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Informal sector, small trade, self-employment, tax.',
  focus: 'Types, general characteristics, importance and limitations of informal sector activities (small trades) in African cities.',
  competence: 'Learners are able to describe the informal sector and judge its importance and its limits.',
  objectives: ['Identify the types of informal activities.', 'Give their general characteristics.', 'Explain their importance and limitations.'],
  recall: ['Many people in towns have small jobs.', 'Moto-taxis are common in Garoua.', 'The informal sector is not registered.'],
  situation: 'After failing to find an office job, Moussa buys a motorbike and becomes a moto-taxi driver in Garoua. He earns money every day, but after an accident he has no insurance to pay the hospital. He asks: "Is my small job a good solution or a trap?"',
  sitQA: [['What is the problem in the situation?', 'Moussa wonders whether his informal job is good for him, because it gives money but no protection.'], ['What job does Moussa do?', 'He is a moto-taxi driver.'], ['Give one advantage and one limit of his job.', 'He earns money every day; he has no insurance.']],
  justification: 'This further study helps us to understand the small trades that feed many families.',
  action: 'Encourage small traders to register and to save money.',
  activities: [
    { sec: '1. TYPES', img: 'f2t_moto_taxi.jpg', caption: 'Moto-taxis.', q: 'To which type of informal activity do moto-taxis belong?', a: 'Transport.', noProj: 'list small trades.' },
    { sec: '1. TYPES', img: 'f2t_tailor.jpg', caption: 'A tailor at work.', q: 'To which type of informal activity does this tailor belong?', a: 'Crafts (small workshops).', noProj: 'name craftsmen of the quarter.' },
    { sec: '2. CHARACTERISTICS', img: 'f2t_street_vendor.jpg', caption: 'A street seller.', q: 'How much money does this seller need to start his business?', a: 'Very little: informal activities need small capital and little training.', noProj: 'interview a seller.' },
    { sec: '3. IMPORTANCE', img: 'f2t_market.jpg', caption: 'A busy market.', q: 'Why do so many families depend on small trades?', a: 'They give jobs and daily income to people who cannot find other work.', noProj: 'discuss in groups.' },
    { sec: '3. LIMITATIONS', img: 'formal_informal_big.png', caption: 'Formal and informal sectors.', q: 'What does the informal worker lack compared with the formal worker?', a: 'A contract, a regular salary, insurance and a pension (CNPS).', noProj: 'compare with a civil servant.' },
  ],
  summary: [
    D([['Informal sector:', 'It is all the small economic activities that are not registered and do not pay taxes regularly.'],
      ['Small trade:', 'It is a small business run by one person or a family with little money.'],
      ['Self-employment:', 'It is working for oneself instead of working for an employer.']]),
    { title: '1. Types of Informal Activities', intro: 'The main types of informal activities are the following:',
      items: [['Small trade:', 'Street selling of food, fruits, clothes, fuel and phone credit.', 'f2t_street_vendor.jpg', 'a street seller'],
        ['Transport:', 'Moto-taxis, clandestine taxis, push-carts and porters.', 'f2t_moto_taxi.jpg', 'moto-taxis'],
        ['Crafts:', 'Tailoring, carpentry, blacksmithing, pottery and hairdressing.', 'f2t_tailor.jpg', 'a tailor'],
        ['Repairs:', 'Repairing of cars, motorbikes, shoes, phones and radios.'],
        ['Food services:', 'Small restaurants (tourne-dos), roasted fish and maize, and drinks.']] },
    { title: '2. General Characteristics', intro: 'Informal activities have the following characteristics:',
      items: [['Small capital:', 'They need very little money to start.'],
        ['No registration:', 'They are not registered and pay few or no taxes.'],
        ['Little training:', 'They are learnt on the job or by apprenticeship.'],
        ['Family or self-employment:', 'They are run by one person or a family, without a written contract.'],
        ['Irregular income and place:', 'Income changes every day, and many workers have no fixed place of work.']] },
    { title: '3. Importance of the Informal Sector', intro: 'The informal sector is important for the following reasons:',
      items: [['Jobs:', 'It employs most of the workers in African cities, especially young people.', 'f2t_market.jpg', 'a busy market'],
        ['Income:', 'It gives daily income to families and reduces poverty.'],
        ['Cheap goods and services:', 'It provides food, transport and repairs at low prices.'],
        ['Training:', 'Apprentices learn a trade in workshops.'],
        ['Links with the countryside:', 'Traders sell farm products from the villages in the town.']] },
    { title: '4. Limitations of the Informal Sector', intro: 'The informal sector has the following limitations:',
      items: [['No social protection:', 'Workers have no insurance, no pension and no paid leave.', 'formal_informal_big.png', 'formal and informal sectors'],
        ['Low and irregular income:', 'Incomes are small and change from day to day.'],
        ['Loss of taxes:', 'The state and the councils lose money because taxes are not paid.'],
        ['Disorder and pollution:', 'Streets become crowded, dirty and dangerous.'],
        ['Accidents and poor quality:', 'Moto-taxi accidents are frequent, and some goods and services are of poor quality.']] },
  ],
  evaluation: [['Give two characteristics of informal activities.', 'Little capital and no registration.'], ['Give one importance and one limitation.', 'It gives jobs; workers have no pension.']],
  remediation: ['Informal activities are not ______.', 'A moto-taxi driver works in the ______ sector.', 'Informal workers often have no ______.'],
  remediationAnswers: '1. registered 2. informal 3. pension (or insurance)',
  homework: 'Interview one informal worker: his or her job, income and main problem.',
  hwAnswer: 'Answers vary. Example: a shoe repairer earns about 2,000 FCFA a day; the main problem is irregular income and no place to work when it rains.',
  bilingual: [['Informal sector', 'Le secteur informel'], ['Small trade', 'Le petit commerce'], ['Tax', "L'impôt"], ['Income', 'Le revenu'], ['Craftsman', "L'artisan"], ['Pension', 'La retraite']],
});

L.push({ kind: 'Practical Work', no: 4, title: 'Location of the Regional and Divisional Headquarters of Cameroon', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Region, division, regional headquarters, divisional headquarters, base map.',
  focus: 'Theoretical basis: naming the regional and divisional headquarters. Practical exercise: locating them on a base map and naming them.',
  competence: 'Learners are able to name and locate the regional headquarters of Cameroon and the divisional headquarters of their region.',
  objectives: ['Name the ten regions of Cameroon and their headquarters.', 'Name the divisions of the North Region and their headquarters.', 'Locate and name them on a base map.'],
  recall: ['Cameroon has ten regions.', 'Yaoundé is the capital of Cameroon.', 'Garoua is in the North Region.'],
  situation: 'A new student from Bafoussam asks the class the headquarters of the West Region and of the divisions around Garoua. Nobody can show them correctly on the map of Cameroon. He asks: "How can we know and locate the headquarters of our regions and divisions?"',
  sitQA: [['What is the problem in the situation?', 'The class cannot name and locate the headquarters on a map.'], ['What is the headquarters of the North Region?', 'Garoua.'], ['What do we need?', 'A base map of Cameroon with regions and divisions.']],
  justification: 'This practical work helps us to know the administrative map of our country.',
  action: 'Locate places carefully on your maps and name them correctly.',
  activities: [
    { sec: '1. THEORETICAL BASIS', img: 'cmr_regions_big.png', caption: 'The ten regions of Cameroon.', q: 'How many regions does Cameroon have?', a: 'Ten regions.', noProj: 'write them on the board.' },
    { sec: '2. REGIONAL HEADQUARTERS', img: 'cmr_regions_big.png', caption: 'Regional headquarters.', q: 'What is the headquarters of the Far North Region?', a: 'Maroua.', noProj: 'match regions and towns.' },
    { sec: '2. REGIONAL HEADQUARTERS', img: 'cmr_towns_big.png', caption: 'Main towns of Cameroon.', q: 'Which regional headquarters is a sea port?', a: 'Douala, headquarters of the Littoral Region.', noProj: 'use the atlas.' },
    { sec: '3. DIVISIONAL HEADQUARTERS', img: 'cmr_regions_big.png', caption: 'The North Region.', q: ['How many divisions does the North Region have?', 'What is the headquarters of the Mayo-Louti division?'], a: ['Four divisions.', 'Guider.'], noProj: 'draw the North Region.' },
    { sec: '4. PRACTICAL EXERCISE', img: 'map_marginal_big.png', caption: 'Elements of a map.', q: 'How can we show the difference between a regional and a divisional headquarters on the base map?', a: 'With two different symbols explained in the key, for example a star and a dot.', noProj: 'give each learner a base map.' },
  ],
  summary: [
    D([['Region:', 'It is the largest administrative unit of Cameroon, headed by a Governor.'],
      ['Division:', 'It is an administrative unit inside a region, headed by a Senior Divisional Officer (SDO).'],
      ['Regional headquarters:', 'It is the town where the administration of a region is found.'],
      ['Divisional headquarters:', 'It is the town where the administration of a division is found.']]),
    { title: '1. Theoretical Basis', sub: 'A) The Regional Headquarters of Cameroon', intro: 'The ten regions of Cameroon and their headquarters are the following:',
      items: [['Far North:', 'Its headquarters is Maroua.', 'cmr_regions_big.png', 'regions and regional headquarters'],
        ['North:', 'Its headquarters is Garoua.'],
        ['Adamawa:', 'Its headquarters is Ngaoundéré.'],
        ['East:', 'Its headquarters is Bertoua.'],
        ['Centre:', 'Its headquarters is Yaoundé, the political capital.'],
        ['South:', 'Its headquarters is Ebolowa.'],
        ['Littoral:', 'Its headquarters is Douala, the economic capital.'],
        ['South-West:', 'Its headquarters is Buea.'],
        ['West:', 'Its headquarters is Bafoussam.'],
        ['North-West:', 'Its headquarters is Bamenda.']] },
    { title: '1. Theoretical Basis', sub: 'B) The Divisional Headquarters of the North Region', intro: 'The North Region has the following divisions and headquarters:',
      items: [['Bénoué:', 'Its headquarters is Garoua.'],
        ['Faro:', 'Its headquarters is Poli.'],
        ['Mayo-Louti:', 'Its headquarters is Guider.'],
        ['Mayo-Rey:', 'Its headquarters is Tcholliré.']] },
    { title: '2. Practical Exercise', intro: 'On a base map of Cameroon, learners do the following:',
      items: [['Locate the regional headquarters:', 'Place each of the ten towns in its region and write its name.', 'cmr_towns_big.png', 'the main towns of Cameroon'],
        ['Locate the divisional headquarters:', 'On a base map of the North Region, place Garoua, Poli, Guider and Tcholliré and write their names.'],
        ['Complete the map:', 'Give the map a title and a key that explains the symbols used.']] },
  ],
  evaluation: [['Give the headquarters of the West and North-West Regions.', 'Bafoussam and Bamenda.'], ['What is the headquarters of the Faro division?', 'Poli.']],
  remediation: ['The headquarters of the East Region is ______.', 'The headquarters of the South Region is ______.', 'The headquarters of the Mayo-Rey division is ______.'],
  remediationAnswers: '1. Bertoua 2. Ebolowa 3. Tcholliré',
  homework: 'On a base map of Cameroon, locate and name the ten regional headquarters.',
  hwAnswer: 'The map shows Maroua, Garoua, Ngaoundéré, Bertoua, Yaoundé, Ebolowa, Douala, Buea, Bafoussam and Bamenda, each in its region, with a title and a key.',
  bilingual: [['Region', 'La région'], ['Division', 'Le département'], ['Headquarters', 'Le chef-lieu'], ['Capital', 'La capitale'], ['Base map', 'Le fond de carte'], ['Governor', 'Le gouverneur']],
});

L.push({ kind: 'Further Study', no: 6, title: 'Urban Problems in Cameroon', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Urban problems, slum, unemployment, waste, floods, town planning, regulations.',
  focus: 'Types of urban problems; causes; consequences; practical solutions and regulations in force.',
  competence: 'Learners are able to identify urban problems in Cameroon and propose practical solutions.',
  objectives: ['Identify the types of urban problems in Cameroon.', 'Explain their causes and consequences.', 'Propose practical solutions and know the regulations in force.'],
  recall: ['Towns grow quickly.', 'Many people work in the informal sector.', 'Waste pollutes the environment.'],
  situation: 'After a heavy rain in Douala, gutters blocked with rubbish overflow and flood a quarter. Houses built on the riverbank are destroyed, and rescue vehicles cannot enter the narrow streets. A victim asks: "Why does this happen every year, and what can be done to stop it?"',
  sitQA: [['What is the problem in the situation?', 'A quarter of Douala is flooded every year, and people do not know the causes or the solutions.'], ['Why did the gutters overflow?', 'They were blocked with rubbish.'], ['Why were houses destroyed?', 'They were built on the riverbank, a risky zone.']],
  justification: 'This further study helps us to understand and solve the problems of our towns.',
  action: 'Do not throw rubbish in gutters and respect building regulations.',
  activities: [
    { sec: '1. TYPES', img: 'usa_slum.jpg', caption: 'A crowded poor quarter.', q: 'Which urban problem does this picture show?', a: 'Poor housing: a slum.', noProj: 'list problems of Garoua.' },
    { sec: '2. CAUSES', img: 'usa_crowd.jpg', caption: 'A crowded town.', q: 'Why do towns in Cameroon grow faster than their roads, houses and services?', a: 'Many people arrive from the villages (rural exodus), and planning is poor.', noProj: 'discuss why towns grow.' },
    { sec: '3. CONSEQUENCES', img: 'lsa_streetflood.jpg', caption: 'A flooded street.', q: 'Which diseases spread when rubbish and flood water stay in a quarter?', a: 'Cholera, typhoid and malaria.', noProj: 'describe the gutters of the quarter.' },
    { sec: '3. CONSEQUENCES', img: 'usa_traffic.jpg', caption: 'A traffic jam.', q: 'What do traffic jams cost town dwellers?', a: 'Lost time, lost money, accidents and air pollution.', noProj: 'describe rush hour in town.' },
    { sec: '4. SOLUTIONS AND REGULATIONS', img: 'usa_newtown.jpg', caption: 'A planned housing area.', q: 'What document must you get from the council before building a house in town?', a: 'A building permit.', noProj: 'propose solutions for the quarter.' },
  ],
  summary: [
    D([['Urban problem:', 'It is a difficulty that affects the life of people in towns.'],
      ['Town planning:', 'It is the organisation of the use of land in a town: quarters, roads, drains and services.']]),
    { title: '1. Types of Urban Problems', intro: 'Cameroonian towns face the following problems:',
      items: [['Poor housing (slums):', 'Many quarters are crowded, unplanned and built in risky zones.', 'usa_slum.jpg', 'a slum'],
        ['Unemployment:', 'Many young people have no job or only an informal job.'],
        ['Waste management:', 'Rubbish is thrown into gutters, rivers and open dumps.', 'waste_problems_big.png', 'poor waste management'],
        ['Floods:', 'Low quarters are flooded after heavy rains.', 'lsa_streetflood.jpg', 'a flooded street'],
        ['Traffic jams and bad roads:', 'Roads are too narrow and full of potholes.', 'usa_traffic.jpg', 'a traffic jam'],
        ['Insecurity:', 'Theft and aggression are frequent in some quarters.']] },
    { title: '2. Causes of Urban Problems', intro: 'Urban problems have the following causes:',
      items: [['Rapid population growth:', 'Rural exodus and high birth rates make towns grow very fast.', 'usa_crowd.jpg', 'a crowded town'],
        ['Poor town planning:', 'People build without permits, even in marshes and on riverbanks.'],
        ['Poverty:', 'Many people cannot afford decent houses or pay for services.'],
        ['Lack of means:', 'Councils lack money and equipment for roads, drains and waste collection.'],
        ['Bad behaviour:', 'Some people throw rubbish anywhere and do not respect rules.']] },
    { title: '3. Consequences of Urban Problems', intro: 'Urban problems have the following consequences:',
      items: [['Diseases:', 'Waste and dirty water spread cholera, typhoid and malaria.'],
        ['Loss of life and property:', 'Floods and collapsing houses kill people and destroy goods.'],
        ['Crime and insecurity:', 'Unemployment and poverty favour theft and drug abuse.'],
        ['Loss of time and pollution:', 'Traffic jams waste time and fuel and pollute the air.']] },
    { title: '4. Solutions and Regulations in Force', intro: 'Urban problems can be reduced by the following measures:',
      items: [['Town planning:', 'Councils plan quarters, roads and drains, and every building needs a building permit.', 'usa_newtown.jpg', 'a planned housing area'],
        ['Risky zones:', 'The law forbids building in marshes, on riverbanks and on steep slopes, and illegal houses can be demolished.'],
        ['Waste collection:', 'Companies such as HYSACAM collect waste, and throwing rubbish in gutters is punished.'],
        ['Roads and drains:', 'The state and councils build roads and clean gutters regularly.'],
        ['Jobs and housing:', 'The state creates jobs and builds social housing for low-income families.']] },
  ],
  evaluation: [['Give three urban problems in Cameroon.', 'Slums, floods and unemployment.'], ['Give two solutions.', 'Town planning with building permits and waste collection.']],
  remediation: ['A crowded poor quarter is a ______.', 'Permission to build a house is a building ______.', 'Rubbish in gutters causes ______.'],
  remediationAnswers: '1. slum 2. permit 3. floods',
  homework: 'Identify one urban problem in your quarter and propose two solutions.',
  hwAnswer: 'Answers vary. Example: blocked gutters that flood the quarter; solutions: clean the gutters every week and put dustbins along the street.',
  bilingual: [['Town planning', "L'urbanisme"], ['Waste', 'Les ordures'], ['Flood', "L'inondation"], ['Building permit', 'Le permis de bâtir'], ['Insecurity', "L'insécurité"], ['Council', 'La commune']],
});

L.push({ no: 8, title: 'Relationships between Towns and Country Sides', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Flows: population flows, flows of goods, information (newspapers).',
  focus: 'Economic relationships; socio-cultural relationships; information.',
  competence: 'Learners are able to identify the flows between towns and country sides and explain why they depend on each other.',
  objectives: ['Describe the economic relationships between towns and country sides.', 'Describe the socio-cultural relationships.', 'Explain the flows of information.'],
  recall: ['Villages produce food.', 'Towns have factories, shops and services.', 'Many young people move to towns.'],
  situation: 'Every Friday, a buyam-sellam takes onions and groundnuts from a village near Garoua to the town market and returns with soap, oil and clothes. At festivals, town dwellers go back to the village. A pupil asks: "Could the town live without the village, or the village without the town?"',
  sitQA: [['What is the problem in the situation?', 'We want to know whether towns and villages depend on each other.'], ['What goes from the village to the town?', 'Food such as onions and groundnuts.'], ['What goes from the town to the village?', 'Manufactured goods such as soap, oil and clothes.']],
  justification: 'This lesson helps us to understand how towns and villages need each other.',
  action: 'Support exchanges and development projects between your village and your town.',
  activities: [
    { sec: '1. ECONOMIC RELATIONSHIPS', img: 'f2t_cattle_market.jpg', caption: 'A cattle market.', q: 'Where do the cattle sold in town markets come from?', a: 'From the country side, where herders raise them.', noProj: 'list products in the Garoua market.' },
    { sec: '1. ECONOMIC RELATIONSHIPS', img: 'usa_truck.jpg', caption: 'A loaded pick-up on a rural road.', q: 'What does this vehicle bring back to the village from the town?', a: 'Manufactured goods such as soap, oil, sugar, clothes and fertilisers.', noProj: 'list goods bought in town.' },
    { sec: '2. SOCIO-CULTURAL RELATIONSHIPS', img: 'usa_busstation.jpg', caption: 'A bus station.', q: 'Why are bus stations crowded before festivals?', a: 'Town dwellers travel back to their villages for festivals and family ceremonies.', noProj: 'ask about family trips.' },
    { sec: '2. SOCIO-CULTURAL RELATIONSHIPS', img: 'usa_bandjoun.jpg', caption: 'A traditional chiefdom.', q: 'How do the elites in town help their village?', a: 'Through development associations that build schools, wells and roads.', noProj: 'name associations of the area.' },
    { sec: '3. INFORMATION', img: 'f2t_phone_farmer.jpg', caption: 'A farmer uses a phone.', q: 'How does this farmer learn the price of his crops in town?', a: 'By phone; news also comes by radio, newspapers and travellers.', noProj: 'ask how villagers get news.' },
  ],
  summary: [
    D([['Flow:', 'It is the movement of people, goods, money or information between two places.'],
      ['Population flow:', 'It is the movement of people between places, for example between a village and a town.']]),
    { title: '1. Economic Relationships', sub: 'A) From the Country Side to the Town', intro: 'The country side sends the following to towns:',
      items: [['Food:', 'Villages supply towns with cereals, tubers, vegetables, fruits and fish.', 'f2t_market.jpg', 'a town market'],
        ['Livestock:', 'Cattle, sheep, goats and poultry are sold in town markets.', 'f2t_cattle_market.jpg', 'a cattle market'],
        ['Raw materials:', 'Cotton, cocoa, coffee and timber feed town industries and ports.'],
        ['Firewood and charcoal:', 'Most town households cook with wood and charcoal from the country side.'],
        ['Labour:', 'Young villagers go to work in towns.']] },
    { title: '1. Economic Relationships', sub: 'B) From the Town to the Country Side', intro: 'Towns send the following to the country side:',
      items: [['Manufactured goods:', 'Soap, oil, sugar, clothes, tools and phones are sold in villages.', 'usa_truck.jpg', 'goods carried to villages'],
        ['Farm inputs:', 'Fertilisers, seeds and pesticides come from towns.'],
        ['Money:', 'Town dwellers send money to their families, and traders pay farmers for their crops.'],
        ['Services:', 'Towns provide hospitals, secondary schools, banks and administration.']] },
    { title: '1. Economic Relationships', sub: 'C) The Actors of the Exchanges', intro: 'The following actors link towns and country sides:',
      items: [['Buyam-sellams:', 'They buy farm products in villages and sell them in towns.', 'f2t_street_vendor.jpg', 'a trader'],
        ['Clandestine transporters:', 'They carry people and goods on rural roads with cars and motorbikes.'],
        ['Cooperatives and CIGs:', 'Farmers group together to buy inputs and sell their products in towns.'],
        ['Councils:', 'They build markets and rural roads that link villages to towns.']] },
    { title: '2. Socio-cultural Relationships', intro: 'Towns and country sides are linked socially and culturally as follows:',
      items: [['Population flows:', 'People move between villages and towns for work, school, trade and family visits.', 'usa_busstation.jpg', 'a bus station'],
        ['Festivals and ceremonies:', 'Town dwellers return for festivals, weddings and funerals.'],
        ['Development associations:', 'Elites in town build schools, wells and health centres in their villages.', 'usa_bandjoun.jpg', 'a village chiefdom'],
        ['Education and health:', 'Village children study in town schools, and villagers go to town hospitals.'],
        ['Spread of town ways of life:', 'Fashion, music and new ideas spread from towns to villages.']] },
    { title: '3. Information', intro: 'Information flows between towns and country sides as follows:',
      items: [['Radio and television:', 'Radio brings news, market prices and advice to farmers.'],
        ['Telephone and internet:', 'Phones link families and give farmers the prices of crops in town.', 'f2t_phone_farmer.jpg', 'a farmer using a phone'],
        ['Newspapers:', 'Newspapers printed in towns reach villages through travellers and traders.'],
        ['People:', 'Travellers, traders and extension workers carry news and advice.']] },
  ],
  evaluation: [['Give two products sent from villages to towns.', 'Food crops and cattle.'], ['Give two socio-cultural links.', 'Festivals and development associations.']],
  remediation: ['A trader who buys in villages and sells in town is a ______.', 'The movement of goods or people is a ______.', 'Farmers who group together form a ______.'],
  remediationAnswers: '1. buyam-sellam 2. flow 3. cooperative (or CIG)',
  homework: 'List three products your family buys from villages and three goods villagers buy in town.',
  hwAnswer: 'From villages: onions, groundnuts, maize (or firewood). From town: soap, cooking oil, clothes (also phones, sugar).',
  bilingual: [['Town', 'La ville'], ['Village', 'Le village'], ['Flow', 'Le flux'], ['Trader', 'Le commerçant'], ['Festival', 'La fête'], ['News', 'Les nouvelles']],
});

L.push({ kind: 'Further Study', no: 7, title: 'Rural Exodus in Cameroon', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Rural exodus, push factors, pull factors, rural development.',
  focus: 'Causes and consequences of rural exodus; how the country side can be made more attractive.',
  competence: 'Learners are able to explain rural exodus in Cameroon and propose ways to make villages attractive.',
  objectives: ['Explain the causes of rural exodus.', 'Explain its consequences.', 'Propose ways to make the country side more attractive.'],
  recall: ['Villages lack some services.', 'Towns offer jobs and services.', 'Many young people go to towns.'],
  situation: 'In Hamadou\'s village, most young people have left for Garoua, Douala and Yaoundé. Only old people and children remain, and many fields are no longer farmed. The village chief asks: "Why do our young people leave, and what can we do to keep them here?"',
  sitQA: [['What is the problem in the situation?', 'Young people leave the village, and the chief does not know how to keep them.'], ['Who remains in the village?', 'Old people and children.'], ['What happens to the fields?', 'They are abandoned.']],
  justification: 'This further study helps us to understand why young people leave villages and how to keep them.',
  action: 'Create activities in your village and support its development.',
  activities: [
    { sec: '1. CAUSES', img: 'cmr_migration_big.png', caption: 'Migration flows in Cameroon.', q: 'Towards which towns do most migrants of Cameroon go?', a: 'Douala and Yaoundé.', noProj: 'draw arrows to big towns.' },
    { sec: '1. CAUSES', img: 'f2t_muddy_road.jpg', caption: 'A bad rural road.', q: 'What in the village pushes young people to leave?', a: 'Lack of jobs, poverty, bad roads and poor services.', noProj: 'list reasons for leaving.' },
    { sec: '1. CAUSES', img: 'lsa_yaounde.jpg', caption: 'Yaoundé.', q: 'What attracts young people to towns?', a: 'Jobs, schools, hospitals, electricity and modern life.', noProj: 'list what attracts people to towns.' },
    { sec: '2. CONSEQUENCES', img: 'usa_slum.jpg', caption: 'A slum in a town.', q: 'Where do many migrants live when they arrive in a big town?', a: 'In crowded poor quarters (slums).', noProj: 'discuss consequences.' },
    { sec: '3. MAKING THE COUNTRY SIDE ATTRACTIVE', img: 'usa_pump.jpg', caption: 'A village water pump.', q: 'How does a water point like this help to keep people in the village?', a: 'It improves daily life: clean water close to home, better health and more time for work.', noProj: 'propose projects for a village.' },
  ],
  summary: [
    D([['Rural exodus:', 'It is the massive movement of people from the country side to towns.'],
      ['Push factors:', 'They are the conditions that make people leave the village.'],
      ['Pull factors:', 'They are the attractions that draw people to towns.']]),
    { title: '1. Causes of Rural Exodus', sub: 'A) Push Factors', intro: 'The following conditions push people out of villages:',
      items: [['Poverty and unemployment:', 'Farming gives low incomes, and there are few other jobs.', 'f2t_muddy_road.jpg', 'a bad rural road'],
        ['Lack of social amenities:', 'Villages lack secondary schools, hospitals, electricity and pipe-borne water.'],
        ['Bad roads:', 'Villages are isolated, and farm products are hard to sell.'],
        ['Shortage of land and hard work:', 'Land is scarce in crowded areas, and farming with simple tools is tiring.'],
        ['Insecurity and traditions:', 'Conflicts, kidnappings and heavy traditional constraints make some young people leave.']] },
    { title: '1. Causes of Rural Exodus', sub: 'B) Pull Factors', intro: 'The following attractions pull people to towns:',
      items: [['Jobs:', 'Towns offer jobs in industries, offices, trade and the informal sector.', 'lsa_yaounde.jpg', 'Yaoundé'],
        ['Social amenities:', 'Towns have universities, hospitals, electricity and water.'],
        ['Modern life:', 'Young people are attracted by leisure, fashion and freedom.'],
        ['Family links:', 'Relatives already living in town receive the new migrants.']] },
    { title: '2. Consequences of Rural Exodus', sub: 'A) In the Country Side', intro: 'Rural exodus has the following consequences in villages:',
      items: [['Loss of young workers:', 'Only old people and children remain, and many fields are abandoned.'],
        ['Fall of food production:', 'Villages produce less food for themselves and for towns.'],
        ['Money from migrants:', 'Migrants send money and goods that help their families.'],
        ['Village development:', 'Elites in town finance schools, wells and roads in their villages.']] },
    { title: '2. Consequences of Rural Exodus', sub: 'B) In the Towns', intro: 'Rural exodus has the following consequences in towns:',
      items: [['Rapid growth and slums:', 'Towns grow too fast, and migrants settle in crowded, unplanned quarters.', 'usa_slum.jpg', 'a slum'],
        ['Unemployment:', 'There are not enough jobs, so many migrants work in the informal sector.'],
        ['Pressure on services:', 'Schools, hospitals, water and transport become insufficient.'],
        ['Insecurity:', 'Poverty and unemployment favour theft and delinquency.']] },
    { title: '3. Making the Country Side More Attractive', intro: 'The country side can be made more attractive by the following measures:',
      items: [['Roads:', 'Good rural roads link villages to markets and towns.'],
        ['Social amenities:', 'Schools, health centres, water points and electricity improve daily life.', 'usa_pump.jpg', 'a village water pump'],
        ['Modern farming:', 'Credit, tools, improved seeds and extension workers raise incomes.'],
        ['Cooperatives and CIGs:', 'Farmers group together to buy inputs and sell at better prices.'],
        ['Rural jobs:', 'Crafts, small processing units and self-employment projects give young people income.'],
        ['Culture and leisure:', 'Festivals, sports and community projects keep young people attached to their village.']] },
  ],
  evaluation: [['Give two causes of rural exodus.', 'Lack of jobs in villages and attractive services in towns.'], ['Give two ways to make villages attractive.', 'Build roads and create jobs in modern farming.']],
  remediation: ['The movement from villages to towns is rural ______.', 'Jobs in towns are ______ factors.', 'Poverty in villages is a ______ factor.'],
  remediationAnswers: '1. exodus 2. pull 3. push',
  homework: 'Propose three projects that could keep young people in your village.',
  hwAnswer: 'Examples: a cooperative for modern farming and livestock; a vocational training centre for crafts; a health centre and electricity for the village.',
  bilingual: [['Rural exodus', "L'exode rural"], ['Migrant', 'Le migrant'], ['Job', "L'emploi"], ['Village', 'Le village'], ['Cooperative', 'La coopérative'], ['Development', 'Le développement']],
});

module.exports = { B, L };
