// FORM 2 — Module 2: Space Occupation (2023 national syllabus): L6, L7, FS5, PW4, FS6, L8, FS7
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F2', code: 'M2', folder: '', module: 'Module 2: Space Occupation', topicDefault: 'Space Occupation', branch: 'Country Sides and Towns of Africa',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 2, Module 2: Space Occupation.'] };
const L = [];

L.push({ no: 6, title: 'Country Sides in Africa', subtopic: 'Country Sides and Towns of Africa',
  notions: 'Rural landscape, agricultural landscape, rural settlement, land.',
  focus: 'Agricultural landscape; rural settlements; attractive and repulsive aspects of rural areas (emphasis on the attractive aspects).',
  competence: 'Learners are able to describe rural areas of Africa and appreciate their attractive aspects.',
  objectives: ['Describe the agricultural landscape of African country sides.', 'Describe the forms and patterns of rural settlements.', 'Identify the attractive and repulsive aspects of rural areas.'],
  recall: ['Most Africans live in villages.', 'Villagers are mostly farmers.', 'Villages have fewer services than towns.'],
  situation: 'Awa\'s cousin in Yaoundé says that village life is boring and poor. Awa, who lives in a village near Guider, says that the village has fresh food, clean air and solidarity between people.',
  sitQA: [['What is the problem in the situation?', 'The two girls disagree about village life.'], ['Give one negative view of the village.', 'It is boring and poor.'], ['Give two attractive aspects of the village.', 'Fresh food and solidarity (also clean air).']],
  justification: 'This lesson helps us to know and appreciate the country sides of Africa.',
  action: 'Value village life and contribute to the development of your village.',
  activities: [
    { sec: '1. AGRICULTURAL LANDSCAPE', img: 'f2t_cotton_field.jpg', caption: 'A cotton field.', q: 'What activities shape the landscape of the country side?', a: 'Farming, herding, fishing and gathering.', noProj: 'describe farms around the village.' },
    { sec: '2. RURAL SETTLEMENTS', img: 'usa_hillvillage.jpg', caption: 'A village of round huts.', q: 'Describe the houses of this village and their building materials.', a: 'Round huts made of mud walls and grass (thatched) roofs.', noProj: 'describe houses in your village.' },
    { sec: '2. RURAL SETTLEMENTS', img: 'patterns_big.png', caption: 'Patterns of settlements.', q: 'Name three patterns of rural settlements.', a: 'Nucleated (grouped), linear (along a road) and dispersed (scattered).', noProj: 'draw the three patterns.' },
    { sec: '3. ATTRACTIVE ASPECTS', img: 'usa_bandjoun.jpg', caption: 'A chiefdom in the West of Cameroon.', q: 'Give three attractive aspects of rural areas.', a: 'Fresh and cheap food, clean air and quiet life, solidarity and traditions.', noProj: 'list what learners like in villages.' },
    { sec: '3. REPULSIVE ASPECTS', img: 'f2t_muddy_road.jpg', caption: 'A bad rural road.', q: 'Give two repulsive aspects of rural areas.', a: 'Bad roads and lack of services such as hospitals and electricity (also few jobs).', noProj: 'discuss problems of villages.' },
  ],
  summary: [
    D([['Country side:', 'It is the rural area outside towns, where most people are farmers.'],
      ['Rural settlement:', 'It is a village or hamlet where people live mainly from farming.']]),
    { title: '1. The Agricultural Landscape', intro: 'The country side is shaped by the following activities:',
      items: [['Farming:', 'Fields of food crops and cash crops cover much of the land.'],
        ['Herding and other activities:', 'Pastures, fishing and gathering also shape the landscape.']] },
    { title: '2. Rural Settlements', intro: 'Rural settlements have the following characteristics:',
      items: [['Houses:', 'Houses are built with local materials such as mud, wood, stone and grass.'],
        ['Patterns:', 'Settlements can be nucleated, linear or dispersed.']],
      draw: { img: 'patterns_big.png', caption: 'patterns of rural settlements' } },
    { title: '3. Attractive and Repulsive Aspects', intro: 'Rural areas have the following aspects:',
      items: [['Attractive aspects:', 'Fresh food, clean air, calm life, solidarity and rich traditions attract people.'],
        ['Repulsive aspects:', 'Bad roads, few jobs and a lack of hospitals, electricity and schools push people away.']] },
  ],
  evaluation: [['Name three patterns of rural settlements.', 'Nucleated, linear and dispersed.'], ['Give two attractive aspects of rural areas.', 'Fresh food and solidarity.']],
  remediation: ['Houses grouped together form a ______ settlement.', 'Houses along a road form a ______ settlement.', 'The main activity in villages is ______.'],
  remediationAnswers: '1. nucleated 2. linear 3. farming',
  homework: 'Describe your village or a village you know: houses, activities and one attractive aspect.',
  hwAnswer: 'Answers vary. Example: round mud houses with grass roofs grouped around the chief\'s compound; farming of maize and cotton; people help each other at harvest.',
  bilingual: [['Village', 'Le village'], ['Countryside', 'La campagne'], ['Farmer', "L'agriculteur"], ['Hut', 'La case'], ['Field', 'Le champ'], ['Solidarity', 'La solidarité']],
});

L.push({ no: 7, title: 'Towns in Africa', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Town, urban landscape, city, informal sector, megalopolis.',
  focus: 'Urban landscapes; informal activities; problems of African towns and cities.',
  competence: 'Learners are able to describe African towns, their activities and their problems.',
  objectives: ['Describe the urban landscape of African towns.', 'Identify informal activities in towns.', 'Explain the problems of African towns.'],
  recall: ['Towns have many people and buildings.', 'Douala and Yaoundé are big cities.', 'Many young people move to towns.'],
  situation: 'Ibrahim visits Douala for the first time. He sees tall buildings, many cars, traffic jams, street sellers everywhere and also quarters with poor houses and dirty gutters.',
  sitQA: [['What is the problem in the situation?', 'Ibrahim discovers both the good and bad sides of a big town.'], ['Name two things he sees in the urban landscape.', 'Tall buildings and many cars.'], ['Name two problems of the town.', 'Traffic jams and poor quarters with dirty gutters.']],
  justification: 'This lesson helps us to understand life and problems in African towns.',
  action: 'Keep your town clean and respect traffic rules.',
  activities: [
    { sec: '1. URBAN LANDSCAPE', img: 'lsa_yaounde.jpg', caption: 'Yaoundé.', q: 'Describe the urban landscape of Yaoundé.', a: 'Tall buildings, many roads, offices, shops and dense housing.', noProj: 'describe the centre of Garoua.' },
    { sec: '1. URBAN LANDSCAPE', img: 'cmr_towns_big.png', caption: 'The main towns of Cameroon.', q: 'Name the two largest towns of Cameroon.', a: 'Douala and Yaoundé.', noProj: 'use the map.' },
    { sec: '2. INFORMAL ACTIVITIES', img: 'f2t_street_vendor.jpg', caption: 'A street seller roasting maize.', q: 'What is an informal activity? Give two examples.', a: 'A small job that is not registered; for example street selling and moto-taxi driving.', noProj: 'list small jobs in town.' },
    { sec: '3. PROBLEMS', img: 'usa_traffic.jpg', caption: 'A traffic jam.', q: 'Give three problems of African towns.', a: 'Traffic jams, unemployment and poor housing (also waste, floods, insecurity).', noProj: 'discuss problems of Garoua.' },
    { sec: '3. PROBLEMS', img: 'urban_problems_big.png', caption: 'Urban problems.', q: 'Classify the problems of towns.', a: 'Economic (unemployment), social (slums, crime), transport (traffic) and environmental (waste, pollution).', noProj: 'draw four boxes.' },
  ],
  summary: [
    D([['Town:', 'It is a large settlement where most people work in trade, industry and services.'],
      ['Informal sector:', 'It is small, unregistered work such as street selling and moto-taxi driving.']]),
    { title: '1. Urban Landscapes', intro: 'African towns have the following landscape:',
      items: [['Centre:', 'The centre has offices, banks, shops and tall buildings.'],
        ['Quarters:', 'Rich quarters have large houses while poor quarters are crowded.'],
        ['Examples:', 'Douala, Yaoundé, Lagos and Kinshasa are big African cities.']] },
    { title: '2. Informal Activities', intro: 'Many town dwellers work in the informal sector:',
      items: [['Examples:', 'Street selling, moto-taxi driving, tailoring and repairing are informal activities.'],
        ['Importance:', 'They give jobs and income to many people.']] },
    { title: '3. Problems of African Towns', intro: 'African towns face the following problems:',
      items: [['Economic problems:', 'Unemployment and low incomes affect many people.'],
        ['Social problems:', 'Slums, crime and a lack of services affect the poor.'],
        ['Transport and environment:', 'Traffic jams, waste and floods are common.']],
      draw: { img: 'urban_problems_big.png', caption: 'problems of towns' } },
  ],
  evaluation: [['Give two informal activities.', 'Street selling and moto-taxi driving.'], ['Give three problems of African towns.', 'Traffic jams, unemployment and slums.']],
  remediation: ['Small unregistered jobs form the ______ sector.', 'A crowded poor quarter is a ______.', 'The economic capital of Cameroon is ______.'],
  remediationAnswers: '1. informal 2. slum 3. Douala',
  homework: 'List five informal activities you see on your way to school.',
  hwAnswer: 'Moto-taxi driving, selling roasted maize, selling fuel in bottles, shoe repairing, hairdressing in the street.',
  bilingual: [['Town', 'La ville'], ['City', 'La grande ville'], ['Traffic jam', "L'embouteillage"], ['Slum', 'Le bidonville'], ['Street seller', 'Le vendeur ambulant'], ['Unemployment', 'Le chômage']],
});

L.push({ kind: 'Further Study', no: 5, title: 'Informal Sector Activities in African Cities', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Informal sector, small trade, self-employment, tax.',
  focus: 'Types, general characteristics, importance and limitations of informal sector activities (small trades) in African cities.',
  competence: 'Learners are able to describe the informal sector and judge its advantages and limits.',
  objectives: ['Identify types of informal activities.', 'Give their general characteristics.', 'Explain their importance and limitations.'],
  recall: ['Many people in towns have small jobs.', 'Moto-taxis are common in Garoua.', 'The informal sector is not registered.'],
  situation: 'After failing to find a job in an office, Moussa buys a motorbike and becomes a moto-taxi driver in Garoua. He earns money every day but has no insurance and no pension.',
  sitQA: [['What is the problem in the situation?', 'Moussa works in the informal sector without protection.'], ['What job does Moussa do?', 'Moto-taxi driver.'], ['Give one advantage and one limit of his job.', 'He earns money every day; he has no insurance or pension.']],
  justification: 'This further study helps us to understand the small trades that feed many families.',
  action: 'Encourage small traders to register and to save money.',
  activities: [
    { sec: '1. TYPES', img: 'f2t_moto_taxi.jpg', caption: 'Moto-taxis.', q: 'Name four types of informal activities.', a: 'Transport (moto-taxi), street trade, crafts (tailoring) and repairs (also food selling).', noProj: 'list small trades.' },
    { sec: '1. TYPES', img: 'f2t_tailor.jpg', caption: 'A tailor at work.', q: 'Which type of informal activity is this?', a: 'A craft (tailoring).', noProj: 'name craftsmen of the quarter.' },
    { sec: '2. CHARACTERISTICS', img: 'f2t_street_vendor.jpg', caption: 'A street seller.', q: 'Give three characteristics of informal activities.', a: 'Small capital, no registration or taxes, and family or self-employment.', noProj: 'interview a seller.' },
    { sec: '3. IMPORTANCE', img: 'f2t_market.jpg', caption: 'A busy market.', q: 'Why is the informal sector important?', a: 'It gives jobs and income to many people and provides cheap goods and services.', noProj: 'discuss in groups.' },
    { sec: '3. LIMITATIONS', img: 'formal_informal_big.png', caption: 'Formal and informal sectors.', q: 'Give two limitations of the informal sector.', a: 'No social security or pension, and low, irregular income (also no taxes for the state).', noProj: 'compare with a civil servant.' },
  ],
  summary: [
    D([['Informal sector:', 'It is all the small economic activities that are not registered and do not pay taxes regularly.']]),
    { title: '1. Types and Characteristics', intro: 'Informal activities have the following types and characteristics:',
      items: [['Types:', 'They include small trade, moto-taxi transport, crafts, repairs and food selling.'],
        ['Characteristics:', 'They need little capital and little training and are run by individuals or families.']] },
    { title: '2. Importance', intro: 'The informal sector is important for the following reasons:',
      items: [['Jobs and income:', 'It employs most workers in African cities.'],
        ['Cheap goods and services:', 'It provides food, transport and repairs at low prices.']] },
    { title: '3. Limitations', intro: 'The informal sector has the following limitations:',
      items: [['For workers:', 'Workers have low, irregular incomes and no insurance or pension.'],
        ['For the state and towns:', 'The state loses taxes and streets become crowded and dirty.']],
      draw: { img: 'formal_informal_big.png', caption: 'formal and informal sectors' } },
  ],
  evaluation: [['Give two characteristics of informal activities.', 'Little capital and no registration.'], ['Give one importance and one limitation.', 'It gives jobs; workers have no pension.']],
  remediation: ['Informal activities are not ______.', 'A moto-taxi driver works in the ______ sector.', 'Informal workers often have no ______.'],
  remediationAnswers: '1. registered 2. informal 3. pension (or insurance)',
  homework: 'Interview one informal worker: his job, his income and his main problem.',
  hwAnswer: 'Answers vary. Example: a shoe repairer earns about 2,000 FCFA a day; his main problem is irregular income and no place to work when it rains.',
  bilingual: [['Informal sector', 'Le secteur informel'], ['Small trade', 'Le petit commerce'], ['Tax', "L'impôt"], ['Income', 'Le revenu'], ['Craftsman', "L'artisan"], ['Pension', 'La retraite']],
});

L.push({ kind: 'Practical Work', no: 4, title: 'Location of the Regional and Divisional Headquarters of Cameroon', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Region, division, regional headquarters, divisional headquarters, base map.',
  focus: 'Naming the regional and divisional headquarters; locating them on a base map.',
  competence: 'Learners are able to name and locate the regional headquarters of Cameroon and the divisional headquarters of their region.',
  objectives: ['Name the ten regions of Cameroon and their headquarters.', 'Name the divisional headquarters of their region.', 'Locate them on a base map.'],
  recall: ['Cameroon has ten regions.', 'Yaoundé is the capital of Cameroon.', 'Garoua is in the North Region.'],
  situation: 'A new student from Bafoussam asks the class the headquarters of the North Region and of the divisions around Garoua. Nobody can show them correctly on a map.',
  sitQA: [['What is the problem in the situation?', 'The class cannot locate the headquarters on a map.'], ['What is the headquarters of the North Region?', 'Garoua.'], ['What do we need?', 'A base map of Cameroon with regions and divisions.']],
  justification: 'This practical work helps us to know the administrative map of our country.',
  action: 'Draw neat maps with a title, a key and a north arrow.',
  activities: [
    { sec: '1. THEORETICAL BASIS', img: 'cmr_regions_big.png', caption: 'The ten regions of Cameroon.', q: 'Name the ten regions of Cameroon.', a: 'Adamawa, Centre, East, Far North, Littoral, North, North-West, South, South-West and West.', noProj: 'write them on the board.' },
    { sec: '2. REGIONAL HEADQUARTERS', img: 'cmr_regions_big.png', caption: 'Regional headquarters.', q: 'Give the headquarters of the Far North, Adamawa and South-West Regions.', a: 'Maroua, Ngaoundéré and Buea.', noProj: 'match regions and towns.' },
    { sec: '2. REGIONAL HEADQUARTERS', img: 'cmr_towns_big.png', caption: 'Main towns of Cameroon.', q: 'Which regional headquarters is on the coast?', a: 'Douala (Littoral); Buea is near the coast at the foot of Mount Cameroon.', noProj: 'use the atlas.' },
    { sec: '3. DIVISIONAL HEADQUARTERS', img: 'cmr_regions_big.png', caption: 'The North Region.', q: 'Name the four divisions of the North Region and their headquarters.', a: 'Bénoué (Garoua), Faro (Poli), Mayo-Louti (Guider) and Mayo-Rey (Tcholliré).', noProj: 'draw the North Region.' },
    { sec: '4. MAPPING', img: 'map_marginal_big.png', caption: 'Elements of a map.', q: 'How do we show the headquarters on the base map?', a: 'With a star for regional and a dot for divisional headquarters, named, with a key, title and north arrow.', noProj: 'give each learner a base map.' },
  ],
  summary: [
    D([['Regional headquarters:', 'It is the town where the administration of a region is found.'],
      ['Divisional headquarters:', 'It is the town where the administration of a division is found.']]),
    { title: '1. Regional Headquarters of Cameroon', intro: 'The ten regions and their headquarters are the following:',
      items: [['North and Far North:', 'Garoua (North) and Maroua (Far North).'],
        ['Adamawa and East:', 'Ngaoundéré (Adamawa) and Bertoua (East).'],
        ['Centre and South:', 'Yaoundé (Centre) and Ebolowa (South).'],
        ['Littoral and South-West:', 'Douala (Littoral) and Buea (South-West).'],
        ['West and North-West:', 'Bafoussam (West) and Bamenda (North-West).']],
      draw: { img: 'cmr_regions_big.png', caption: 'regions and regional headquarters' } },
    { title: '2. Divisional Headquarters of the North Region', intro: 'The North Region has the following divisions:',
      items: [['Bénoué:', 'Its headquarters is Garoua.'],
        ['Faro:', 'Its headquarters is Poli.'],
        ['Mayo-Louti:', 'Its headquarters is Guider.'],
        ['Mayo-Rey:', 'Its headquarters is Tcholliré.']] },
  ],
  evaluation: [['Give the headquarters of the West and North-West Regions.', 'Bafoussam and Bamenda.'], ['What is the headquarters of Mayo-Louti?', 'Guider.']],
  remediation: ['The headquarters of the East Region is ______.', 'The headquarters of the South Region is ______.', 'The headquarters of the Faro division is ______.'],
  remediationAnswers: '1. Bertoua 2. Ebolowa 3. Poli',
  homework: 'On a base map of Cameroon, locate and name the ten regional headquarters.',
  hwAnswer: 'The map shows Maroua, Garoua, Ngaoundéré, Bertoua, Yaoundé, Ebolowa, Douala, Buea, Bafoussam and Bamenda, with a title, a key and a north arrow.',
  bilingual: [['Region', 'La région'], ['Division', 'Le département'], ['Headquarters', 'Le chef-lieu'], ['Capital', 'La capitale'], ['Base map', 'Le fond de carte'], ['Administration', "L'administration"]],
});

L.push({ kind: 'Further Study', no: 6, title: 'Urban Problems in Cameroon', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Urban problems, slum, unemployment, waste, floods, town planning, regulations.',
  focus: 'Types of urban problems; causes; consequences; practical solutions and regulations in force.',
  competence: 'Learners are able to identify urban problems in Cameroon and propose practical solutions.',
  objectives: ['Identify the types of urban problems in Cameroon.', 'Explain their causes and consequences.', 'Propose practical solutions and know the regulations.'],
  recall: ['Towns grow quickly.', 'Many people work in the informal sector.', 'Waste pollutes the environment.'],
  situation: 'After a heavy rain in Douala, gutters blocked with rubbish overflow and flood a quarter. Houses built on the riverbank are destroyed, and there is no road for rescue vehicles.',
  sitQA: [['What is the problem in the situation?', 'Floods and poor planning damage a quarter of Douala.'], ['Why did the gutters overflow?', 'They were blocked with rubbish.'], ['Why were houses destroyed?', 'They were built on the riverbank.']],
  justification: 'This further study helps us to understand and solve the problems of our towns.',
  action: 'Do not throw rubbish in gutters and respect building regulations.',
  activities: [
    { sec: '1. TYPES', img: 'usa_slum.jpg', caption: 'A crowded poor quarter.', q: 'Name three types of urban problems in Cameroon.', a: 'Poor housing (slums), unemployment and waste (also floods, traffic, insecurity).', noProj: 'list problems of Garoua.' },
    { sec: '2. CAUSES', img: 'usa_crowd.jpg', caption: 'A crowded town.', q: 'Give two causes of urban problems.', a: 'Rapid population growth through rural exodus and poor town planning.', noProj: 'discuss why towns grow.' },
    { sec: '3. CONSEQUENCES', img: 'lsa_streetflood.jpg', caption: 'A flooded street.', q: 'Give two consequences of poor waste management.', a: 'Floods and diseases such as cholera and malaria.', noProj: 'describe gutters of the quarter.' },
    { sec: '3. CONSEQUENCES', img: 'usa_traffic.jpg', caption: 'A traffic jam.', q: 'What are the consequences of traffic jams?', a: 'Loss of time, accidents and air pollution.', noProj: 'describe rush hour in town.' },
    { sec: '4. SOLUTIONS', img: 'usa_newtown.jpg', caption: 'A planned new housing area.', q: 'Give three solutions to urban problems.', a: 'Town planning and building permits, waste collection and job creation (also roads and drains).', noProj: 'propose solutions for the quarter.' },
  ],
  summary: [
    D([['Urban problem:', 'It is a difficulty that affects the life of people in towns.']]),
    { title: '1. Types and Causes', intro: 'Cameroonian towns face the following problems and causes:',
      items: [['Types:', 'Slums, unemployment, waste, floods, traffic jams and insecurity are common.'],
        ['Causes:', 'Rapid growth through rural exodus, poverty and poor town planning cause these problems.']],
      draw: { img: 'urban_problems_big.png', caption: 'urban problems' } },
    { title: '2. Consequences', intro: 'Urban problems have the following consequences:',
      items: [['Health:', 'Waste and floods spread cholera, typhoid and malaria.'],
        ['Social life:', 'Unemployment and poverty increase crime and insecurity.']] },
    { title: '3. Solutions and Regulations', intro: 'Urban problems can be solved by the following measures:',
      items: [['Town planning:', 'Councils plan quarters, roads and drains, and building permits are required.'],
        ['Waste management:', 'Companies such as HYSACAM collect waste and people must not dump it in gutters.'],
        ['Jobs:', 'The state and private sector create jobs and train young people.']] },
  ],
  evaluation: [['Give three urban problems in Cameroon.', 'Slums, floods and unemployment.'], ['Give two solutions.', 'Town planning and waste collection.']],
  remediation: ['A crowded poor quarter is a ______.', 'Permission to build a house is a building ______.', 'Rubbish in gutters causes ______.'],
  remediationAnswers: '1. slum 2. permit 3. floods',
  homework: 'Identify one urban problem in your quarter and propose two solutions.',
  hwAnswer: 'Answers vary. Example: blocked gutters that flood the quarter; solutions: clean the gutters every week and put dustbins along the street.',
  bilingual: [['Town planning', "L'urbanisme"], ['Waste', 'Les ordures'], ['Flood', "L'inondation"], ['Building permit', 'Le permis de bâtir'], ['Insecurity', "L'insécurité"], ['Council', 'La commune']],
});

L.push({ no: 8, title: 'Relationships between Towns and Country Sides', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Flows, population flows, goods, information, rural exodus.',
  focus: 'Economic relationships; socio-cultural relationships; information.',
  competence: 'Learners are able to describe the flows between towns and country sides and explain why they depend on each other.',
  objectives: ['Describe the economic relationships between towns and country sides.', 'Describe the socio-cultural relationships.', 'Explain the flows of information.'],
  recall: ['Villages produce food.', 'Towns have factories, shops and services.', 'Many young people move to towns.'],
  situation: 'Every Friday, a buyam-sellam takes onions and groundnuts from a village near Garoua to the town market, and returns with soap, oil and clothes for the villagers. At festivals, town dwellers go back to the village.',
  sitQA: [['What is the problem in the situation?', 'We want to understand the exchanges between town and village.'], ['What goes from the village to the town?', 'Food such as onions and groundnuts.'], ['What goes from the town to the village?', 'Manufactured goods such as soap, oil and clothes.']],
  justification: 'This lesson helps us to understand how towns and villages need each other.',
  action: 'Support exchanges between your village and your town.',
  activities: [
    { sec: '1. ECONOMIC RELATIONSHIPS', img: 'f2t_cattle_market.jpg', caption: 'A cattle market.', q: 'What products does the country side send to towns?', a: 'Food crops, cattle, firewood and raw materials such as cotton.', noProj: 'list products in the Garoua market.' },
    { sec: '1. ECONOMIC RELATIONSHIPS', img: 'usa_truck.jpg', caption: 'A loaded pick-up on a rural road.', q: 'What products and services do towns send to the country side?', a: 'Manufactured goods, fertilisers, money and services such as health and education.', noProj: 'list goods bought in town.' },
    { sec: '2. POPULATION FLOWS', img: 'usa_busstation.jpg', caption: 'A bus station.', q: 'Why do people travel between towns and villages?', a: 'For work, school, trade, family visits and festivals.', noProj: 'ask about family trips.' },
    { sec: '2. SOCIO-CULTURAL RELATIONSHIPS', img: 'usa_bandjoun.jpg', caption: 'A traditional chiefdom.', q: 'Give two socio-cultural links between towns and villages.', a: 'Festivals and funerals in the village, and development associations of town dwellers.', noProj: 'name village festivals.' },
    { sec: '3. INFORMATION', img: 'f2t_phone_farmer.jpg', caption: 'A farmer uses a phone.', q: 'How does information circulate between towns and villages?', a: 'By phone, radio, newspapers and travellers.', noProj: 'ask how villagers get news.' },
  ],
  summary: [
    D([['Flow:', 'It is the movement of people, goods, money or information between two places.']]),
    { title: '1. Economic Relationships', intro: 'Towns and country sides exchange the following:',
      items: [['From villages to towns:', 'Villages send food, cattle, firewood and raw materials.'],
        ['From towns to villages:', 'Towns send manufactured goods, money and services.']] },
    { title: '2. Socio-cultural Relationships', intro: 'Towns and villages are linked socially as follows:',
      items: [['Population flows:', 'People move for work, school, trade and family visits.'],
        ['Culture and solidarity:', 'Town dwellers return for festivals and funerals and help through development associations.']] },
    { title: '3. Information', intro: 'Information flows as follows:',
      items: [['Media:', 'Radio, phones and newspapers bring news to villages.'],
        ['People:', 'Travellers and traders carry news between towns and villages.']] },
  ],
  evaluation: [['Give two products sent from villages to towns.', 'Food crops and cattle.'], ['Give two socio-cultural links.', 'Festivals and development associations.']],
  remediation: ['A trader who buys in villages and sells in town is a ______.', 'The movement of goods is a ______.', 'News reaches villages by ______.'],
  remediationAnswers: '1. buyam-sellam 2. flow 3. radio (or phone)',
  homework: 'List three products your family buys from villages and three goods villagers buy in town.',
  hwAnswer: 'From villages: onions, groundnuts, maize (or firewood). From town: soap, cooking oil, clothes (also phones, sugar).',
  bilingual: [['Town', 'La ville'], ['Village', 'Le village'], ['Flow', 'Le flux'], ['Trader', 'Le commerçant'], ['Festival', 'La fête'], ['News', 'Les nouvelles']],
});

L.push({ kind: 'Further Study', no: 7, title: 'Rural Exodus in Cameroon', subtopic: 'Towns and Country Sides of Africa',
  notions: 'Rural exodus, push factors, pull factors, rural development.',
  focus: 'Causes and consequences of rural exodus; how the country side can be made more attractive.',
  competence: 'Learners are able to explain rural exodus in Cameroon and propose ways to make villages attractive.',
  objectives: ['Define rural exodus.', 'Explain its causes and consequences.', 'Propose ways to make the country side more attractive.'],
  recall: ['Villages lack some services.', 'Towns offer jobs and services.', 'Many young people go to towns.'],
  situation: 'In Hamadou\'s village, most young people have left for Garoua, Douala and Yaoundé. Only old people and children remain, and many fields are no longer farmed.',
  sitQA: [['What is the problem in the situation?', 'Young people leave the village for towns.'], ['Who remains in the village?', 'Old people and children.'], ['What happens to the fields?', 'They are abandoned.']],
  justification: 'This further study helps us to understand why young people leave villages and how to keep them.',
  action: 'Create activities in your village and support its development.',
  activities: [
    { sec: '1. MEANING', img: 'cmr_migration_big.png', caption: 'Migration flows in Cameroon.', q: 'What is rural exodus? Where do migrants go?', a: 'The massive movement of people from villages to towns; they go mainly to Douala and Yaoundé.', noProj: 'draw arrows to big towns.' },
    { sec: '2. CAUSES', img: 'f2t_muddy_road.jpg', caption: 'A bad rural road.', q: 'Give two push factors of rural exodus.', a: 'Lack of jobs and poor services in villages (also bad roads, poverty).', noProj: 'list reasons for leaving.' },
    { sec: '2. CAUSES', img: 'lsa_yaounde.jpg', caption: 'Yaoundé.', q: 'Give two pull factors of towns.', a: 'Jobs and services such as schools, hospitals and electricity.', noProj: 'list what attracts people to towns.' },
    { sec: '3. CONSEQUENCES', img: 'usa_slum.jpg', caption: 'A slum in a town.', q: 'Give one consequence in villages and one in towns.', a: 'Villages lose young workers and fields are abandoned; towns get slums and unemployment.', noProj: 'discuss consequences.' },
    { sec: '4. SOLUTIONS', img: 'usa_pump.jpg', caption: 'A village water pump.', q: 'How can the country side be made more attractive?', a: 'By building roads, schools, health centres and water points and creating jobs in farming and crafts.', noProj: 'propose projects for a village.' },
  ],
  summary: [
    D([['Rural exodus:', 'It is the massive movement of people from villages to towns.']]),
    { title: '1. Causes', intro: 'Rural exodus has the following causes:',
      items: [['Push factors:', 'Poverty, lack of jobs, bad roads and poor services push people out of villages.'],
        ['Pull factors:', 'Jobs, schools, hospitals and modern life attract people to towns.']],
      draw: { img: 'cmr_migration_big.png', caption: 'migration flows in Cameroon' } },
    { title: '2. Consequences', intro: 'Rural exodus has the following consequences:',
      items: [['In villages:', 'Villages lose young workers, food production falls and old people remain alone.'],
        ['In towns:', 'Towns grow too fast, with slums, unemployment and crime.']] },
    { title: '3. Making the Country Side More Attractive', intro: 'The country side can be made attractive by the following measures:',
      items: [['Infrastructure:', 'Roads, electricity, water, schools and health centres improve village life.'],
        ['Jobs:', 'Modern farming, cooperatives and crafts give young people income.'],
        ['Culture:', 'Cultural festivals and community projects keep people attached to their village.']] },
  ],
  evaluation: [['Give two causes of rural exodus.', 'Lack of jobs in villages and attractive services in towns.'], ['Give two ways to make villages attractive.', 'Build roads and create jobs in modern farming.']],
  remediation: ['The movement from villages to towns is rural ______.', 'Jobs in towns are ______ factors.', 'Poverty in villages is a ______ factor.'],
  remediationAnswers: '1. exodus 2. pull 3. push',
  homework: 'Propose three projects that could keep young people in your village.',
  hwAnswer: 'Examples: a cooperative for modern farming and livestock; a vocational training centre for crafts; a health centre and electricity for the village.',
  bilingual: [['Rural exodus', "L'exode rural"], ['Migrant', 'Le migrant'], ['Job', "L'emploi"], ['Village', 'Le village'], ['Cooperative', 'La coopérative'], ['Development', 'Le développement']],
});

module.exports = { B, L };
