// FORM 4 — Module I: Ecological Systems and their Resources (2023 syllabus), part 1: L1–L11 (soil, ecosystems, biomes)
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F4', code: 'M1', folder: '', module: 'Module I: Ecological Systems and their Resources', topicDefault: "Conservation of World's Biomes and Resources", branch: 'The Soil',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 4, Module I: Ecological Systems and their Resources.'] };
const L = [];

L.push({ no: 1, title: 'Concept of the Soil', subtopic: 'The Soil',
  notions: 'Soil, mineral matter, organic matter, soil texture, structure, depth, fertility.',
  focus: 'Definition; components; the soil system (diagram only); soil characteristics.',
  competence: 'Learners are able to define the soil, name its components and describe its characteristics.',
  objectives: ['Define the soil.', 'Identify the components of the soil.', 'Describe the soil system and the characteristics of soils.'],
  recall: ['Plants grow in the soil.', 'Rocks break down by weathering.', 'Dead leaves rot on the ground.'],
  situation: 'Two farmers near Garoua plant maize. The first farm has dark, soft soil and gives a good harvest. The second has sandy, pale soil and gives a poor harvest. The farmers ask why soils are different.',
  sitQA: [['What is the problem in the situation?', 'The farmers do not know why their soils are different.'], ['Which soil gives a good harvest?', 'The dark, soft soil.'], ['What makes a soil dark?', 'Humus (organic matter).']],
  justification: 'This lesson helps us to know the soil, which feeds plants, animals and people.',
  action: 'Add manure and keep plant cover to keep your soil fertile.',
  activities: [
    { sec: '1. MEANING', img: 'lsa_soilpit.jpg', caption: 'A soil pit.', q: 'What is soil?', a: 'The loose top layer of the Earth\'s surface in which plants grow.', noProj: 'show a handful of soil.' },
    { sec: '2. COMPONENTS', img: 'soil_components_big.png', caption: 'The components of a good soil.', q: 'Name the four components of the soil.', a: 'Mineral matter, organic matter (humus), water and air.', noProj: 'put soil in a jar of water and shake it.' },
    { sec: '3. THE SOIL SYSTEM', img: 'soil_system_big.png', caption: 'The soil as a system.', q: 'Give two inputs and two outputs of the soil system.', a: 'Inputs: rain water and dead leaves. Outputs: uptake by plants and erosion.', noProj: 'draw the soil system.' },
    { sec: '4. CHARACTERISTICS', img: 'texture_triangle_big.png', caption: 'Soil texture.', q: 'What is soil texture?', a: 'The size of the soil particles: sand, silt and clay.', noProj: 'rub soil between the fingers.' },
    { sec: '4. CHARACTERISTICS', img: 'f2t_black_soil.jpg', caption: 'A fertile dark soil.', q: 'What makes a soil fertile?', a: 'Humus, plant food (minerals), water and good depth.', noProj: 'compare two soil samples.' },
  ],
  summary: [
    { title: '1. Meaning of the Soil', intro: 'The soil is defined as follows:',
      items: [['Soil:', 'It is the loose top layer of the Earth\'s surface in which plants grow.']] },
    { title: '2. Components of the Soil', intro: 'The soil is made up of the following components:',
      items: [['Mineral matter:', 'It is made of small pieces of weathered rock and forms about 45 % of the soil.'],
        ['Organic matter:', 'It is humus from dead plants and animals and forms about 5 % of the soil.'],
        ['Water and air:', 'They fill the spaces between the particles and form about half of the soil.']],
      draw: { img: 'soil_components_big.png', caption: 'the components of the soil' } },
    { title: '3. The Soil System', intro: 'The soil works as a system:',
      items: [['Inputs:', 'Rain, dead leaves, weathered rock and sun energy enter the soil.'],
        ['Outputs:', 'Plant uptake, evaporation, leaching and erosion leave the soil.']],
      draw: { img: 'soil_system_big.png', caption: 'the soil system' } },
    { title: '4. Soil Characteristics', intro: 'Soils have the following characteristics:',
      items: [['Texture:', 'It is the size of the particles: sand, silt or clay.'],
        ['Structure:', 'It is the way the particles are grouped together.'],
        ['Depth and fertility:', 'A deep soil rich in humus and minerals is fertile.']] },
  ],
  evaluation: [['Name the four components of the soil.', 'Mineral matter, organic matter, water and air.'], ['What is soil texture?', 'The size of the soil particles.']],
  remediation: ['Dead plants and animals give ______.', 'Sand, silt and clay describe soil ______.', 'A soil able to feed plants well is ______.'],
  remediationAnswers: '1. humus 2. texture 3. fertile',
  homework: 'Collect two soil samples from different places and compare their colour and texture.',
  hwAnswer: 'Example: soil under trees is dark and soft (much humus); soil on the path is pale, sandy and hard (little humus).',
  bilingual: [['Soil', 'Le sol'], ['Humus', "L'humus"], ['Texture', 'La texture'], ['Clay', "L'argile"], ['Sand', 'Le sable'], ['Fertility', 'La fertilité']],
});

L.push({ no: 2, title: 'The Soil Profile', subtopic: 'The Soil',
  notions: 'Soil profile, horizon, topsoil, subsoil, regolith, bedrock.',
  focus: 'A simple soil profile.',
  competence: 'Learners are able to draw and describe a simple soil profile.',
  objectives: ['Define a soil profile and a horizon.', 'Identify the horizons of a simple soil profile.', 'Draw and label a soil profile.'],
  recall: ['Soil has mineral and organic matter.', 'Rocks weather into small pieces.', 'Plant roots grow in the soil.'],
  situation: 'Workers dig a deep well in the school compound. On the side of the hole, the class sees dark soil at the top, reddish soil below and broken rock at the bottom.',
  sitQA: [['What is the problem in the situation?', 'The class wants to understand the layers seen in the well.'], ['What colour is the top layer?', 'Dark.'], ['What is at the bottom?', 'Broken rock.']],
  justification: 'This lesson helps us to understand the layers of the soil.',
  action: 'Protect the topsoil, which is the richest layer.',
  activities: [
    { sec: '1. MEANING', img: 'lsa_soilpit.jpg', caption: 'A soil pit showing layers.', q: 'What is a soil profile?', a: 'A vertical section of the soil from the surface to the bedrock.', noProj: 'describe the sides of a well.' },
    { sec: '2. HORIZONS', img: 'soil_profile_big.png', caption: 'A simple soil profile.', q: 'Name the horizons of the soil profile from top to bottom.', a: 'Topsoil (A), subsoil (B), regolith (C) and bedrock.', noProj: 'draw the profile.' },
    { sec: '2. TOPSOIL', img: 'lsa_litter.jpg', caption: 'Dead leaves on the ground.', q: 'Why is the topsoil dark and rich?', a: 'It contains humus from rotting leaves.', noProj: 'dig a small hole.' },
    { sec: '2. SUBSOIL AND REGOLITH', img: 'f2t_laterite.jpg', caption: 'Red subsoil.', q: 'Describe the subsoil and the regolith.', a: 'The subsoil has little humus and many minerals; the regolith is weathered rock.', noProj: 'compare colours.' },
    { sec: '3. ILLUSTRATION', img: 'ideal_profile_big.png', caption: 'An ideal soil profile.', q: 'Which horizon is most important for farmers?', a: 'The topsoil, where most roots and plant food are.', noProj: 'label a drawing.' },
  ],
  summary: [
    D([['Soil profile:', 'It is a vertical section of the soil from the surface to the bedrock.'],
      ['Horizon:', 'It is a layer of the soil profile with its own colour and texture.']]),
    { title: '1. The Horizons of a Simple Soil Profile', intro: 'A simple soil profile has the following horizons:',
      items: [['Topsoil (A):', 'It is dark and rich in humus, and most roots are found in it.'],
        ['Subsoil (B):', 'It has little humus and receives minerals washed down from the topsoil.'],
        ['Regolith (C):', 'It is made of weathered and broken rock.'],
        ['Bedrock (R):', 'It is the solid rock at the bottom.']],
      draw: { img: 'soil_profile_big.png', caption: 'a simple soil profile' } },
  ],
  evaluation: [['Name the four layers of a soil profile.', 'Topsoil, subsoil, regolith and bedrock.'], ['Which horizon is rich in humus?', 'The topsoil.']],
  remediation: ['A layer of the soil is a ______.', 'The layer of broken rock is the ______.', 'The solid rock at the bottom is the ______.'],
  remediationAnswers: '1. horizon 2. regolith 3. bedrock',
  homework: 'Draw and label a simple soil profile.',
  hwAnswer: 'From the top: topsoil (dark, humus), subsoil (reddish, minerals), regolith (broken rock), bedrock (solid rock).',
  bilingual: [['Profile', 'Le profil'], ['Horizon', "L'horizon"], ['Topsoil', 'La couche arable'], ['Subsoil', 'Le sous-sol'], ['Bedrock', 'La roche mère'], ['Root', 'La racine']],
});

L.push({ no: 3, title: 'Soil Erosion', subtopic: 'The Soil',
  notions: 'Normal (geologic) erosion, accelerated soil erosion, sheet, rill, gully erosion.',
  focus: 'Meaning and types; causes; consequences of soil erosion.',
  competence: 'Learners are able to explain soil erosion and recognise it around them.',
  objectives: ['Define soil erosion and its types.', 'Explain the causes of soil erosion.', 'Give the consequences of soil erosion.'],
  recall: ['The topsoil is the richest layer.', 'Plants cover and protect the soil.', 'Heavy rain falls in the rainy season.'],
  situation: 'After the first heavy rains, the path behind the school has deep channels, and the soil of a nearby bare farm has been washed into the gutter.',
  sitQA: [['What is the problem in the situation?', 'The soil is being washed away.'], ['What caused the channels?', 'Running rain water.'], ['Why was the farm soil washed away?', 'It was bare, with no plants.']],
  justification: 'This lesson helps us to understand how we lose our soil.',
  action: 'Keep the soil covered with plants.',
  activities: [
    { sec: '1. MEANING', img: 'erosion_rain.gif', caption: 'Animation: rain on bare and grassy soil.', q: 'On which side is the soil washed away? Why?', a: 'On the bare side, because no plants protect it.', noProj: 'pour water on bare and grassy soil.' },
    { sec: '2. TYPES', img: 'erosion_types_big.png', caption: 'Types of soil erosion by water.', q: 'Distinguish sheet, rill and gully erosion.', a: 'Sheet: a thin layer removed; rill: small channels; gully: deep channels.', noProj: 'draw the three types.' },
    { sec: '3. CAUSES', img: 'f2t_cattle_field.jpg', caption: 'Cattle grazing.', q: 'Give three human causes of soil erosion.', a: 'Overgrazing, deforestation and bush fires (also bad farming).', noProj: 'list causes near the school.' },
    { sec: '4. CONSEQUENCES', img: 'f4_gully.jpg', caption: 'A gully.', q: 'Give two consequences of soil erosion.', a: 'Soil loses its fertility and gullies destroy farms and roads.', noProj: 'describe damage near the school.' },
    { sec: '4. CONSEQUENCES', img: 'f4_muddyriver.jpg', caption: 'A muddy river.', q: 'Where does the eroded soil go?', a: 'Into rivers and dams, which become muddy and fill up (silting).', noProj: 'describe the Benue after rain.' },
  ],
  summary: [
    D([['Soil erosion:', 'It is the removal of the topsoil by water, wind or people.'],
      ['Accelerated erosion:', 'It is erosion made faster by human activities.']]),
    { title: '1. Types of Soil Erosion', intro: 'Soil erosion takes the following forms:',
      items: [['Normal (geologic) erosion:', 'It is slow natural erosion balanced by soil formation.'],
        ['Sheet erosion:', 'Running water removes a thin layer of soil evenly.'],
        ['Rill and gully erosion:', 'Water cuts small channels (rills) that become deep channels (gullies).'],
        ['Wind erosion:', 'Wind blows away dry, loose soil in dry areas.']],
      draw: { img: 'erosion_types_big.png', caption: 'types of soil erosion' } },
    { title: '2. Causes', intro: 'Soil erosion has the following causes:',
      items: [['Physical causes:', 'Heavy rain, steep slopes and strong winds remove soil.'],
        ['Human causes:', 'Deforestation, overgrazing, bush fires and ploughing down slopes expose the soil.']] },
    { title: '3. Consequences', intro: 'Soil erosion has the following consequences:',
      items: [['On farming:', 'The soil loses its fertility and harvests fall.'],
        ['On the environment:', 'Gullies destroy land and roads, and rivers and dams fill with mud.']] },
  ],
  evaluation: [['Name three types of water erosion.', 'Sheet, rill and gully erosion.'], ['Give two human causes.', 'Deforestation and overgrazing.']],
  remediation: ['A deep channel cut by water is a ______.', 'Too many animals on the same land is ______.', 'Erosion made faster by people is ______ erosion.'],
  remediationAnswers: '1. gully 2. overgrazing 3. accelerated',
  homework: 'Find a place with soil erosion near your home. Describe it and give its cause.',
  hwAnswer: 'Example: a path with deep rills on a slope; caused by running rain water on bare, trampled soil.',
  bilingual: [['Erosion', "L'érosion"], ['Gully', 'La ravine'], ['Slope', 'La pente'], ['Overgrazing', 'Le surpâturage'], ['Wind', 'Le vent'], ['Mud', 'La boue']],
});

L.push({ no: 4, title: 'Soil Conservation', subtopic: 'The Soil',
  notions: 'Soil conservation, checks to soil erosion, conservation measures, terraces, contour ploughing.',
  focus: 'Meaning; measures and methods of soil conservation.',
  competence: 'Learners are able to propose and apply methods to conserve the soil.',
  objectives: ['Define soil conservation.', 'Describe mechanical methods of soil conservation.', 'Describe biological methods of soil conservation.'],
  recall: ['Soil erosion removes the topsoil.', 'Bare soil is eroded quickly.', 'Plants protect the soil.'],
  situation: 'On the Mandara Mountains, farmers grow millet on steep slopes. They build stone walls across the slopes, and their soil is not washed away by the heavy rains.',
  sitQA: [['What is the problem in the situation?', 'Farmers must protect the soil on steep slopes.'], ['What do the farmers build?', 'Stone walls (terraces) across the slopes.'], ['Why does it work?', 'The walls slow down the running water.']],
  justification: 'This lesson helps us to protect the soil that feeds us.',
  action: 'Plant trees, grass and cover crops, and farm along the contours.',
  activities: [
    { sec: '1. MEANING', img: 'soil_conservation_big.png', caption: 'Soil conservation methods.', q: 'What is soil conservation?', a: 'All the methods used to protect the soil from erosion and keep it fertile.', noProj: 'list methods known.' },
    { sec: '2. MECHANICAL METHODS', img: 'f4_terraces.jpg', caption: 'Terraces on a hillside.', q: 'How do terraces reduce soil erosion?', a: 'They make flat steps that slow down running water.', noProj: 'describe Mandara terraces.' },
    { sec: '2. MECHANICAL METHODS', img: 'f4_zai.jpg', caption: 'Zaï pits in a dry area.', q: 'How do zaï pits and contour ridges help the soil?', a: 'They catch water and soil and stop them from running down the slope.', noProj: 'draw contour ridges.' },
    { sec: '3. BIOLOGICAL METHODS', img: 'f2t_shelterbelt.jpg', caption: 'A line of trees against the wind.', q: 'How do trees protect the soil?', a: 'Their roots hold the soil and they slow down wind and rain.', noProj: 'plan trees for the school.' },
    { sec: '3. BIOLOGICAL METHODS', img: 'lsa_litter.jpg', caption: 'Dead leaves covering the soil (mulch).', q: 'Give two other biological methods.', a: 'Mulching and cover crops (also crop rotation, manure).', noProj: 'mulch a school garden.' },
  ],
  summary: [
    D([['Soil conservation:', 'It is the protection of the soil against erosion and loss of fertility.']]),
    { title: '1. Mechanical Methods', intro: 'Soil is protected by the following mechanical methods:',
      items: [['Terracing:', 'Flat steps are built across steep slopes, as on the Mandara Mountains.'],
        ['Contour ploughing and ridges:', 'Ploughing along the contours stops water from running down.'],
        ['Stone lines and check dams:', 'Lines of stones and small dams slow water and fill gullies.']],
      draw: { img: 'soil_conservation_big.png', caption: 'soil conservation methods' } },
    { title: '2. Biological Methods', intro: 'Soil is protected by the following biological methods:',
      items: [['Tree planting:', 'Trees and windbreaks hold the soil and reduce wind.'],
        ['Cover crops and mulching:', 'Plants and dead leaves cover the soil against rain.'],
        ['Crop rotation and manure:', 'Changing crops and adding manure keep the soil fertile.']] },
    { title: '3. Other Measures', intro: 'Other measures also conserve the soil:',
      items: [['Controlled grazing:', 'Limiting the number of animals protects the grass.'],
        ['Stopping bush fires:', 'Avoiding fires keeps the plant cover.']] },
  ],
  evaluation: [['Give two mechanical methods of soil conservation.', 'Terracing and contour ploughing.'], ['Give two biological methods.', 'Tree planting and mulching.']],
  remediation: ['Flat steps on slopes are ______.', 'Covering the soil with dead leaves is ______.', 'Ploughing across the slope is ______ ploughing.'],
  remediationAnswers: '1. terraces 2. mulching 3. contour',
  homework: 'Propose three ways to protect the soil of your school compound.',
  hwAnswer: 'Plant grass and trees on bare areas, build stone lines on slopes, and make paths so that people do not trample the soil everywhere.',
  bilingual: [['Conservation', 'La conservation'], ['Terrace', 'La terrasse'], ['Mulching', 'Le paillage'], ['Windbreak', 'Le brise-vent'], ['Manure', 'Le fumier'], ['Contour', 'La courbe de niveau']],
});

L.push({ no: 5, title: 'The Ecosystem', subtopic: 'The Ecosystem',
  notions: 'Ecosystem, biotic components, abiotic components, equilibrium.',
  focus: 'Definition; components of ecosystems; characteristics with notion of equilibrium.',
  competence: 'Learners are able to identify the components of an ecosystem and explain its balance.',
  objectives: ['Define an ecosystem.', 'Identify its biotic and abiotic components.', 'Explain the notion of equilibrium.'],
  recall: ['Plants and animals depend on each other.', 'Plants need sunlight, water and soil.', 'Animals eat plants or other animals.'],
  situation: 'In a pond near Garoua, there are water lilies, fish, frogs, insects, mud and water. When people used chemicals on the farms nearby, many fish died and the frogs disappeared.',
  sitQA: [['What is the problem in the situation?', 'Chemicals upset the balance of the pond.'], ['Name two living things in the pond.', 'Fish and frogs (also lilies, insects).'], ['Name two non-living things.', 'Water and mud.']],
  justification: 'This lesson helps us to understand how living things and their surroundings depend on each other.',
  action: 'Avoid actions that upset the balance of nature, such as pollution and over-hunting.',
  activities: [
    { sec: '1. MEANING', img: 'lsa_pond.jpg', caption: 'A pond ecosystem.', q: 'What is an ecosystem?', a: 'A community of living things interacting with their non-living environment.', noProj: 'describe a pond.' },
    { sec: '2. COMPONENTS', img: 'ecosystem_components_big.png', caption: 'Biotic and abiotic components.', q: 'Distinguish biotic and abiotic components.', a: 'Biotic: living things (plants, animals). Abiotic: non-living things (sun, water, soil, air).', noProj: 'make two lists.' },
    { sec: '2. COMPONENTS', img: 'lsa_fungi.jpg', caption: 'A mushroom (fungus).', q: 'What is the role of decomposers such as fungi?', a: 'They break down dead matter and return nutrients to the soil.', noProj: 'show rotting leaves.' },
    { sec: '3. CHARACTERISTICS', img: 'f2t_savanna.jpg', caption: 'A savanna ecosystem.', q: 'Give two examples of ecosystems of different sizes.', a: 'A pond (small) and the savanna or the forest (large).', noProj: 'name ecosystems of Cameroon.' },
    { sec: '3. EQUILIBRIUM', img: 'equilibrium_big.png', caption: 'The balance of an ecosystem.', q: 'What happens when one part of an ecosystem is destroyed?', a: 'The balance (equilibrium) is broken and other parts suffer.', noProj: 'discuss the pond in the situation.' },
  ],
  summary: [
    D([['Ecosystem:', 'It is a community of living things interacting with their non-living environment.']]),
    { title: '1. Components of Ecosystems', intro: 'An ecosystem has the following components:',
      items: [['Abiotic components:', 'They are non-living things such as sunlight, water, air, soil and temperature.'],
        ['Producers:', 'They are green plants that make food from sunlight.'],
        ['Consumers:', 'They are animals that eat plants or other animals.'],
        ['Decomposers:', 'They are fungi and bacteria that break down dead matter.']],
      draw: { img: 'ecosystem_components_big.png', caption: 'components of an ecosystem' } },
    { title: '2. Characteristics and Equilibrium', intro: 'Ecosystems have the following characteristics:',
      items: [['Size:', 'Ecosystems can be small, like a pond, or large, like a forest.'],
        ['Interdependence:', 'All components depend on one another.'],
        ['Equilibrium:', 'A healthy ecosystem is in balance, but pollution or over-hunting can break it.']] },
  ],
  evaluation: [['What is an ecosystem?', 'A community of living things interacting with their environment.'], ['Give two abiotic components.', 'Water and sunlight.']],
  remediation: ['Living components are ______ components.', 'Green plants are ______.', 'Fungi and bacteria are ______.'],
  remediationAnswers: '1. biotic 2. producers 3. decomposers',
  homework: 'Choose an ecosystem near your home and list three biotic and three abiotic components.',
  hwAnswer: 'Example (a school garden): biotic – grass, ants, birds; abiotic – soil, water, sunlight.',
  bilingual: [['Ecosystem', "L'écosystème"], ['Living', 'Vivant'], ['Balance', "L'équilibre"], ['Producer', 'Le producteur'], ['Consumer', 'Le consommateur'], ['Decomposer', 'Le décomposeur']],
});

L.push({ no: 6, title: 'The Functioning of Ecosystems', subtopic: 'The Ecosystem',
  notions: 'Energy, food chain, food web, trophic level.',
  focus: 'Energy flow; trophic levels.',
  competence: 'Learners are able to explain how energy flows through an ecosystem.',
  objectives: ['Explain energy flow in an ecosystem.', 'Build a food chain and a food web.', 'Identify trophic levels.'],
  recall: ['Plants make food from sunlight.', 'Animals eat plants or other animals.', 'Decomposers break down dead matter.'],
  situation: 'In Bénoué National Park, grass feeds antelopes and antelopes are eaten by lions. When poachers killed many antelopes, the lions began to attack cattle in nearby villages.',
  sitQA: [['What is the problem in the situation?', 'Poaching broke the food chain.'], ['What do antelopes eat?', 'Grass.'], ['Why did lions attack cattle?', 'They had fewer antelopes to eat.']],
  justification: 'This lesson helps us to understand how living things are linked by food.',
  action: 'Protect wild animals and report poachers.',
  activities: [
    { sec: '1. ENERGY FLOW', img: 'energy_flow_big.png', caption: 'Energy flow from the Sun.', q: 'Where does the energy of an ecosystem come from?', a: 'From the Sun, captured by green plants.', noProj: 'draw the Sun and a plant.' },
    { sec: '2. FOOD CHAIN', img: 'lsa_zebra.jpg', caption: 'Zebras grazing.', q: 'Build a food chain with grass, zebra and lion.', a: 'Grass → zebra → lion.', noProj: 'write the chain with arrows.' },
    { sec: '2. FOOD WEB', img: 'food_web_big.png', caption: 'A food web of the savanna.', q: 'What is a food web?', a: 'Many food chains linked together.', noProj: 'draw a web on the board.' },
    { sec: '3. TROPHIC LEVELS', img: 'trophic_pyramid_big.png', caption: 'Trophic levels.', q: 'Name the trophic levels from the bottom.', a: 'Producers, primary consumers, secondary consumers, tertiary consumers.', noProj: 'draw a pyramid.' },
    { sec: '3. ENERGY LOSS', img: 'energy_flow_big.png', caption: 'Energy passed at each level.', q: 'Why are there fewer lions than zebras?', a: 'Only about 10 % of energy passes to the next level; the rest is lost as heat.', noProj: 'use numbers 1,000 → 100 → 10.' },
  ],
  summary: [
    D([['Food chain:', 'It is the order in which living things eat one another.'],
      ['Trophic level:', 'It is the position of a living thing in a food chain.']]),
    { title: '1. Energy Flow', intro: 'Energy flows through an ecosystem as follows:',
      items: [['Source:', 'Energy comes from the Sun and is captured by green plants.'],
        ['Transfer:', 'Energy passes from plants to herbivores and then to carnivores.'],
        ['Loss:', 'Only about 10 % of energy passes to the next level, and the rest is lost as heat.']],
      draw: { img: 'energy_flow_big.png', caption: 'energy flow' } },
    { title: '2. Food Chains, Food Webs and Trophic Levels', intro: 'Living things are linked by food as follows:',
      items: [['Food chain:', 'An example is grass → zebra → lion.'],
        ['Food web:', 'It is many food chains linked together.'],
        ['Trophic levels:', 'They are producers, primary consumers, secondary consumers and tertiary consumers.']],
      draw: { img: 'trophic_pyramid_big.png', caption: 'trophic levels' } },
  ],
  evaluation: [['Build a food chain of three links.', 'Grass → antelope → lion.'], ['Why does energy decrease along a food chain?', 'Most energy is lost as heat at each level.']],
  remediation: ['The source of energy in ecosystems is the ______.', 'Many linked food chains form a food ______.', 'Herbivores are ______ consumers.'],
  remediationAnswers: '1. Sun 2. web 3. primary',
  homework: 'Build two food chains found in your area.',
  hwAnswer: 'Examples: grass → goat → human; maize → grasshopper → bird → hawk.',
  bilingual: [['Food chain', 'La chaîne alimentaire'], ['Energy', "L'énergie"], ['Herbivore', "L'herbivore"], ['Carnivore', 'Le carnivore'], ['Level', 'Le niveau'], ['Predator', 'Le prédateur']],
});

L.push({ no: 7, title: 'The Tropical Rainforest Biome', subtopic: 'Tropical Biomes and their Significance',
  notions: 'Selvas, ferrallitic soils, convectional rainfall, shifting cultivation, bush fallowing, poaching.',
  focus: 'Location; characteristics (climate, vegetation, soils, animal life); human activities.',
  competence: 'Learners are able to describe the tropical rainforest biome and its human activities.',
  objectives: ['Locate the tropical rainforest biome.', 'Describe its climate, vegetation, soils and animal life.', 'Describe its human activities.'],
  recall: ['An ecosystem has living and non-living components.', 'The equatorial region is hot and wet.', 'Southern Cameroon has a dense forest.'],
  situation: 'A documentary shows the Amazon forest: very tall trees, many animals, heavy rain every afternoon and people who clear small plots to farm cassava.',
  sitQA: [['What is the problem in the situation?', 'We want to know the characteristics of the rainforest biome.'], ['How is the rain?', 'Heavy rain every afternoon.'], ['What do people do?', 'They clear small plots to farm.']],
  justification: 'This lesson helps us to know the richest biome of the Earth.',
  action: 'Protect the rainforest and its animals.',
  activities: [
    { sec: '1. LOCATION', img: 'biomes_map_big.png', caption: 'Biomes of the world.', q: 'Where is the tropical rainforest found?', a: 'In the Amazon Basin, the Congo Basin and South-East Asia, near the Equator.', noProj: 'use the atlas.' },
    { sec: '2. CLIMATE', img: 'yaounde_climate_big.png', caption: 'An equatorial climate (Yaoundé).', q: 'Describe the climate of the rainforest.', a: 'Hot all year (about 25 °C) with heavy convectional rain in most months.', noProj: 'read the data.' },
    { sec: '2. VEGETATION AND SOILS', img: 'rainforest_layers_big.png', caption: 'The layers of the rainforest.', q: 'Describe the vegetation and the soils.', a: 'A dense evergreen forest in layers, on red ferrallitic soils.', noProj: 'draw the layers.' },
    { sec: '2. ANIMAL LIFE', img: 'f2t_rainforest.jpg', caption: 'The rainforest.', q: 'Name three animals of the rainforest.', a: 'Gorillas, chimpanzees and forest elephants (also snakes, birds, insects).', noProj: 'list animals of the South.' },
    { sec: '3. HUMAN ACTIVITIES', img: 'f2t_clearing.jpg', caption: 'A plot cleared for farming.', q: 'Give three human activities in the rainforest.', a: 'Shifting cultivation, lumbering and plantation farming (also hunting, gathering).', noProj: 'discuss activities of the South.' },
  ],
  summary: [
    { title: '1. Location', intro: 'The tropical rainforest is located as follows:',
      items: [['Location:', 'It lies near the Equator, in the Amazon (selvas), the Congo Basin including southern Cameroon, and South-East Asia.']],
      draw: { img: 'biomes_map_big.png', caption: 'biomes of the world' } },
    { title: '2. Characteristics', intro: 'The rainforest has the following characteristics:',
      items: [['Climate:', 'It is hot all year with heavy convectional rain.'],
        ['Vegetation:', 'It is a dense evergreen forest with several layers of tall trees.'],
        ['Soils:', 'The soils are red ferrallitic soils, leached by heavy rain.'],
        ['Animal life:', 'Many animals live there, such as gorillas, chimpanzees, snakes and birds.']] },
    { title: '3. Human Activities', intro: 'People carry out the following activities:',
      items: [['Farming:', 'People practise shifting cultivation, bush fallowing and plantation farming.'],
        ['Lumbering:', 'Companies cut hardwoods for timber.'],
        ['Hunting and gathering:', 'People hunt and gather fruits, but poaching threatens animals.']] },
  ],
  evaluation: [['Give two characteristics of the rainforest climate.', 'Hot all year and heavy rain.'], ['Give two human activities.', 'Shifting cultivation and lumbering.']],
  remediation: ['The rainforest of the Amazon is called the ______.', 'The soils of the rainforest are ______ soils.', 'Illegal hunting is ______.'],
  remediationAnswers: '1. selvas 2. ferrallitic 3. poaching',
  homework: 'Draw a sketch map of the world showing the three main rainforest areas.',
  hwAnswer: 'The map shows the Amazon Basin (South America), the Congo Basin (Central Africa, including southern Cameroon) and South-East Asia (Indonesia, Malaysia).',
  bilingual: [['Rainforest', 'La forêt dense humide'], ['Biome', 'Le biome'], ['Hardwood', 'Le bois dur'], ['Gorilla', 'Le gorille'], ['Plot', 'La parcelle'], ['Poaching', 'Le braconnage']],
});

L.push({ no: 8, title: 'The Tropical Wet and Dry (Savanna) Biome', subtopic: 'Tropical Biomes and their Significance',
  notions: 'Savanna, ferruginous soils, cereal farming, pastoral farming, handicrafts.',
  focus: 'Location; characteristics (climate, vegetation, soils, animal life); human activities.',
  competence: 'Learners are able to describe the savanna biome and its human activities.',
  objectives: ['Locate the savanna biome.', 'Describe its climate, vegetation, soils and animal life.', 'Describe its human activities.'],
  recall: ['Garoua has a rainy and a dry season.', 'The savanna has grass and scattered trees.', 'Many cattle are reared in the North.'],
  situation: 'In the dry season, the grass around Garoua is yellow and many trees lose their leaves. In the rainy season, everything becomes green and farmers sow sorghum and cotton.',
  sitQA: [['What is the problem in the situation?', 'We want to understand the changes of the savanna during the year.'], ['What happens in the dry season?', 'The grass dries and trees lose their leaves.'], ['What do farmers grow?', 'Sorghum and cotton.']],
  justification: 'This lesson helps us to understand the biome in which we live.',
  action: 'Avoid bush fires and protect the savanna.',
  activities: [
    { sec: '1. LOCATION', img: 'savanna_africa_big.png', caption: 'The savanna in Africa.', q: 'Between which latitudes is the savanna found?', a: 'Between about 5° and 15° north and south of the Equator.', noProj: 'use the atlas.' },
    { sec: '2. CLIMATE', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'Describe the savanna climate.', a: 'Hot all year with a wet season and a dry season.', noProj: 'read the data.' },
    { sec: '2. VEGETATION', img: 'f2t_savanna.jpg', caption: 'Savanna with scattered trees.', q: 'Describe the vegetation of the savanna.', a: 'Tall grass with scattered trees such as the baobab and the acacia.', noProj: 'describe plants around Garoua.' },
    { sec: '2. ANIMAL LIFE', img: 'f2t_elephants.jpg', caption: 'Elephants in the savanna.', q: 'Name three animals of the savanna.', a: 'Elephants, lions and antelopes (also giraffes, zebras).', noProj: 'name animals of Bénoué park.' },
    { sec: '3. HUMAN ACTIVITIES', img: 'f2t_cattle.jpg', caption: 'Cattle of the savanna.', q: 'Give three human activities of the savanna.', a: 'Cereal farming, cattle rearing and handicrafts (also cotton farming, tourism).', noProj: 'list activities of the North.' },
  ],
  summary: [
    { title: '1. Location', intro: 'The savanna is located as follows:',
      items: [['Location:', 'It lies between the rainforest and the desert, from about 5° to 15° north and south, including northern Cameroon.']],
      draw: { img: 'savanna_africa_big.png', caption: 'the savanna in Africa' } },
    { title: '2. Characteristics', intro: 'The savanna has the following characteristics:',
      items: [['Climate:', 'It is hot all year with a wet season and a dry season.'],
        ['Vegetation:', 'It is tall grass with scattered trees that lose their leaves in the dry season.'],
        ['Soils:', 'The soils are mainly red ferruginous soils.'],
        ['Animal life:', 'Large herbivores and carnivores live there, such as elephants, antelopes and lions.']] },
    { title: '3. Human Activities', intro: 'People carry out the following activities:',
      items: [['Farming:', 'Farmers grow cereals such as sorghum, millet and maize, and cotton.'],
        ['Pastoral farming:', 'Herders rear cattle, sheep and goats.'],
        ['Handicrafts and tourism:', 'People make crafts and tourists visit parks such as Waza and Bénoué.']] },
  ],
  evaluation: [['Give two characteristics of the savanna climate.', 'Hot all year with a wet and a dry season.'], ['Give two human activities.', 'Cereal farming and cattle rearing.']],
  remediation: ['The soils of the savanna are ______ soils.', 'Sorghum and millet are ______.', 'A big tree of the savanna is the ______.'],
  remediationAnswers: '1. ferruginous 2. cereals 3. baobab',
  homework: 'List five activities of people in the savanna around your home.',
  hwAnswer: 'Farming sorghum and cotton, rearing cattle, making crafts (mats, pottery), trading in markets, fishing in the Benue.',
  bilingual: [['Savanna', 'La savane'], ['Grass', "L'herbe"], ['Cereal', 'La céréale'], ['Herder', "L'éleveur"], ['Craft', "L'artisanat"], ['Dry season', 'La saison sèche']],
});

L.push({ no: 9, title: 'The Tropical Monsoon Biome', subtopic: 'Tropical Biomes and their Significance',
  notions: 'Monsoon, deciduous forest, lumbering, wet rice.',
  focus: 'Location; characteristics (climate, vegetation, soils, animal life); human activities.',
  competence: 'Learners are able to describe the tropical monsoon biome and its human activities.',
  objectives: ['Locate the monsoon biome.', 'Describe its climate, vegetation, soils and animal life.', 'Describe its human activities.'],
  recall: ['Winds blow from high to low pressure.', 'Cameroon has a south-west monsoon.', 'Rice needs a lot of water.'],
  situation: 'In India, farmers wait for the summer monsoon wind from the sea. When it comes, heavy rains fall and they plant rice in flooded fields. When it is late, there is famine.',
  sitQA: [['What is the problem in the situation?', 'Farmers depend on the monsoon rains.'], ['Where does the summer monsoon come from?', 'From the sea.'], ['What happens when the monsoon is late?', 'Harvests fail and there is famine.']],
  justification: 'This lesson helps us to understand the monsoon biome, where many people live.',
  action: 'Compare the monsoon with the rainy season of Cameroon.',
  activities: [
    { sec: '1. LOCATION', img: 'biomes_map_big.png', caption: 'Biomes of the world.', q: 'Where is the monsoon biome found?', a: 'In South and South-East Asia (India, Bangladesh, Myanmar) and northern Australia.', noProj: 'use the atlas.' },
    { sec: '2. CLIMATE', img: 'monsoon_big.png', caption: 'Summer and winter monsoons.', q: 'Describe the two monsoon winds.', a: 'In summer, a wet wind blows from the sea and brings rain; in winter, a dry wind blows from the land.', noProj: 'draw arrows on a map of India.' },
    { sec: '2. VEGETATION', img: 'f2t_dry_trees.jpg', caption: 'Trees without leaves in the dry season.', q: 'Why do monsoon forest trees lose their leaves?', a: 'To save water during the dry season: they are deciduous.', noProj: 'compare with savanna trees.' },
    { sec: '3. HUMAN ACTIVITIES', img: 'usa_ricefarm.jpg', caption: 'Rice fields in Asia.', q: 'Which crop is grown in flooded fields in the monsoon lands?', a: 'Wet rice (paddy).', noProj: 'describe rice fields of Yagoua.' },
    { sec: '3. HUMAN ACTIVITIES', img: 'usa_sawmill.jpg', caption: 'A sawmill.', q: 'Which valuable tree of the monsoon forest is cut for timber?', a: 'Teak (also sal).', noProj: 'name furniture woods.' },
  ],
  summary: [
    { title: '1. Location', intro: 'The monsoon biome is located as follows:',
      items: [['Location:', 'It is found in South and South-East Asia, such as India and Bangladesh, and in northern Australia.']] },
    { title: '2. Characteristics', intro: 'The monsoon biome has the following characteristics:',
      items: [['Climate:', 'A wet summer monsoon from the sea brings heavy rain, and a dry winter monsoon blows from the land.'],
        ['Vegetation:', 'It is a deciduous forest whose trees, such as teak, lose their leaves in the dry season.'],
        ['Soils:', 'The soils are red and alluvial soils, fertile in river valleys.'],
        ['Animal life:', 'Tigers, elephants, monkeys and many birds live there.']],
      draw: { img: 'monsoon_big.png', caption: 'summer and winter monsoons' } },
    { title: '3. Human Activities', intro: 'People carry out the following activities:',
      items: [['Wet rice farming:', 'Farmers grow rice in flooded fields during the monsoon.'],
        ['Lumbering:', 'Teak and sal are cut for timber.'],
        ['Other activities:', 'People grow tea and jute and rear cattle and buffaloes.']] },
  ],
  evaluation: [['What is a monsoon?', 'A seasonal wind that changes direction between summer and winter.'], ['Give two human activities.', 'Wet rice farming and lumbering.']],
  remediation: ['The wet summer wind comes from the ______.', 'Trees that lose their leaves are ______.', 'The main crop of monsoon lands is ______.'],
  remediationAnswers: '1. sea 2. deciduous 3. rice',
  homework: 'Compare the monsoon of India with the rainy season of Garoua: give one similarity and one difference.',
  hwAnswer: 'Similarity: both have a wet season brought by a moist wind from the sea. Difference: the Indian monsoon brings much more rain.',
  bilingual: [['Monsoon', 'La mousson'], ['Rice', 'Le riz'], ['Teak', 'Le teck'], ['Deciduous', 'Caduc'], ['Flood', "L'inondation"], ['Tiger', 'Le tigre']],
});

L.push({ no: 10, title: 'The Tropical Hot Desert Biome', subtopic: 'Tropical Biomes and their Significance',
  notions: 'Aridity, xerophytes, illuviation, desertification.',
  focus: 'Location; characteristics (climate, vegetation, soils, animal life); human activities.',
  competence: 'Learners are able to describe the hot desert biome and its human activities.',
  objectives: ['Locate the hot desert biome.', 'Describe its climate, vegetation, soils and animal life.', 'Describe its human activities.'],
  recall: ['Deserts receive very little rain.', 'The Sahara is north of Cameroon.', 'Camels live in the desert.'],
  situation: 'The Sahara is spreading south. In the Far North of Cameroon, some farms are covered by sand, and herders must travel farther to find grass and water.',
  sitQA: [['What is the problem in the situation?', 'The desert is spreading south.'], ['What covers some farms?', 'Sand.'], ['What is this spreading called?', 'Desertification.']],
  justification: 'This lesson helps us to understand the desert and how to stop it spreading.',
  action: 'Plant trees and save water to fight desertification.',
  activities: [
    { sec: '1. LOCATION', img: 'deserts_world_big.png', caption: 'Hot deserts of the world.', q: 'Name three hot deserts and their continents.', a: 'Sahara (Africa), Arabian Desert (Asia), Great Australian Desert (Australia).', noProj: 'use the atlas.' },
    { sec: '2. CLIMATE', img: 'aswan_temp_big.png', caption: 'Temperatures at Aswan.', q: 'Describe the desert climate.', a: 'Less than 250 mm of rain, very hot days and cold nights (aridity).', noProj: 'read the data.' },
    { sec: '2. VEGETATION', img: 'f2t_cactus.jpg', caption: 'A cactus.', q: 'How are desert plants (xerophytes) adapted?', a: 'They store water, have small leaves or spines and long roots.', noProj: 'describe desert plants.' },
    { sec: '2. ANIMAL LIFE', img: 'f2t_camels.jpg', caption: 'Camels.', q: 'Why is the camel adapted to the desert?', a: 'It can travel for days without water and walk on sand.', noProj: 'list desert animals.' },
    { sec: '3. HUMAN ACTIVITIES', img: 'f2t_oasis.jpg', caption: 'An oasis.', q: 'Give three human activities in the desert.', a: 'Nomadic herding, oasis farming and oil mining (also tourism).', noProj: 'discuss life in the Sahara.' },
  ],
  summary: [
    { title: '1. Location', intro: 'Hot deserts are located as follows:',
      items: [['Location:', 'They lie near the tropics, such as the Sahara, the Kalahari, the Arabian and the Australian deserts.']],
      draw: { img: 'deserts_world_big.png', caption: 'hot deserts of the world' } },
    { title: '2. Characteristics', intro: 'Hot deserts have the following characteristics:',
      items: [['Climate:', 'It is arid, with less than 250 mm of rain, very hot days and cold nights.'],
        ['Vegetation:', 'Few xerophytes such as cacti and acacias grow there.'],
        ['Soils:', 'The soils are sandy or stony, poor in humus and often salty.'],
        ['Animal life:', 'Camels, lizards, snakes and scorpions are adapted to dryness.']] },
    { title: '3. Human Activities', intro: 'People carry out the following activities:',
      items: [['Nomadic herding:', 'Nomads move with camels, goats and sheep.'],
        ['Oasis farming:', 'Farmers grow dates and vegetables with irrigation.'],
        ['Mining:', 'Oil, gas and uranium are extracted.'],
        ['Desertification:', 'Overgrazing and tree cutting make the desert spread.']] },
  ],
  evaluation: [['What are xerophytes?', 'Plants adapted to very dry conditions.'], ['Give two human activities of the desert.', 'Nomadic herding and oasis farming.']],
  remediation: ['Very dry conditions are called ______.', 'The spreading of the desert is ______.', 'A green place with water in the desert is an ______.'],
  remediationAnswers: '1. aridity 2. desertification 3. oasis',
  homework: 'Give three actions that can stop desertification in the Far North of Cameroon.',
  hwAnswer: 'Plant trees (Green Wall, Sahel Vert), control grazing, and use improved stoves to reduce tree cutting.',
  bilingual: [['Desert', 'Le désert'], ['Sand', 'Le sable'], ['Camel', 'Le chameau'], ['Cactus', 'Le cactus'], ['Aridity', "L'aridité"], ['Desertification', 'La désertification']],
});

L.push({ no: 11, title: 'The Mediterranean Biome', subtopic: 'Temperate Biomes and their Significance',
  notions: 'Mediterranean climate, woodland, viticulture, pastoral farming.',
  focus: 'Location; characteristics (climate, vegetation, soils, animal life); human activities.',
  competence: 'Learners are able to describe the Mediterranean biome and its human activities.',
  objectives: ['Locate the Mediterranean biome.', 'Describe its climate, vegetation, soils and animal life.', 'Describe its human activities.'],
  recall: ['Temperate regions have four seasons.', 'Olive oil and grapes come from Europe.', 'The Mediterranean Sea is north of Africa.'],
  situation: 'Awa\'s uncle lives in Tunisia. He says that summers there are hot and dry, winters are mild and rainy, and farmers grow olives, grapes and oranges.',
  sitQA: [['What is the problem in the situation?', 'We want to know the climate and activities of Mediterranean lands.'], ['How are summers?', 'Hot and dry.'], ['Name two crops.', 'Olives and grapes (also oranges).']],
  justification: 'This lesson helps us to know a temperate biome with a special climate.',
  action: 'Compare the Mediterranean seasons with those of Cameroon.',
  activities: [
    { sec: '1. LOCATION', img: 'biomes_map_big.png', caption: 'Biomes of the world.', q: 'Where is the Mediterranean biome found?', a: 'Around the Mediterranean Sea, and in California, central Chile, the Cape (South Africa) and south-west Australia.', noProj: 'use the atlas.' },
    { sec: '2. CLIMATE', img: 'f2t_mediterranean.jpg', caption: 'A Mediterranean landscape.', q: 'Describe the Mediterranean climate.', a: 'Hot, dry summers and mild, wet winters.', noProj: 'compare with Garoua.' },
    { sec: '2. VEGETATION', img: 'f2t_olive_tree.jpg', caption: 'An olive tree.', q: 'How are Mediterranean plants adapted to the dry summer?', a: 'They have small, hard, waxy leaves and deep roots.', noProj: 'describe an olive tree.' },
    { sec: '3. VITICULTURE', img: 'f2t_vineyard.jpg', caption: 'A vineyard.', q: 'What is viticulture?', a: 'The growing of grapes (vines).', noProj: 'name fruits from Mediterranean lands.' },
    { sec: '3. OTHER ACTIVITIES', img: 'usa_beach.jpg', caption: 'A crowded beach.', q: 'Give two other activities of Mediterranean lands.', a: 'Tourism and pastoral farming of sheep and goats (also fishing).', noProj: 'discuss tourism.' },
  ],
  summary: [
    { title: '1. Location', intro: 'The Mediterranean biome is located as follows:',
      items: [['Location:', 'It lies around the Mediterranean Sea and in California, central Chile, the Cape and south-west Australia, between about 30° and 40°.']] },
    { title: '2. Characteristics', intro: 'The Mediterranean biome has the following characteristics:',
      items: [['Climate:', 'Summers are hot and dry and winters are mild and wet.'],
        ['Vegetation:', 'It is woodland and scrub of olive, cork oak and pine with small, hard leaves.'],
        ['Soils:', 'The soils are thin red soils, eroded on slopes.'],
        ['Animal life:', 'Goats, sheep, lizards and birds live there.']] },
    { title: '3. Human Activities', intro: 'People carry out the following activities:',
      items: [['Viticulture and fruit farming:', 'Farmers grow grapes, olives, oranges and lemons.'],
        ['Pastoral farming:', 'Herders rear sheep and goats.'],
        ['Tourism:', 'Millions of tourists visit the sunny beaches.']] },
  ],
  evaluation: [['Describe the Mediterranean climate.', 'Hot, dry summers and mild, wet winters.'], ['What is viticulture?', 'The growing of grapes.']],
  remediation: ['The growing of grapes is ______.', 'Mediterranean summers are hot and ______.', 'A typical tree of this biome is the ______.'],
  remediationAnswers: '1. viticulture 2. dry 3. olive',
  homework: 'List three products from Mediterranean lands sold in Cameroon.',
  hwAnswer: 'Olive oil, oranges or apples, wine or grape juice (also dates, pasta).',
  bilingual: [['Olive', "L'olive"], ['Grape', 'Le raisin'], ['Vineyard', 'Le vignoble'], ['Summer', "L'été"], ['Winter', "L'hiver"], ['Tourism', 'Le tourisme']],
});

module.exports = { B, L };
