// FORM 4 — Module II: Development and the Management of Primary Resources (2023 syllabus), part 1: L18–L24 (development)
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F4', code: 'M2', folder: '', module: 'Module II: Development and the Management of Primary Resources', topicDefault: 'The Process of Development', branch: 'The Concept of Development',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 4, Module II: Development and the Management of Primary Resources.'] };
const L = [];

L.push({ no: 18, title: 'The Notion of Development', subtopic: 'The Concept of Development',
  notions: 'Development, underdevelopment, poverty, sustainable development.',
  focus: 'Definition of development, underdevelopment and sustainable development; main principles of sustainable development.',
  competence: 'Learners are able to explain development and underdevelopment and act for sustainable development.',
  objectives: ['Define development and underdevelopment.', 'Define sustainable development.', 'State the main principles of sustainable development.'],
  recall: ['Some countries are rich and others are poor.', 'People need food, health and education.', 'Resources must be protected for the future.'],
  situation: 'Two brothers compare their lives: one lives in Garoua with no electricity and few jobs; the other lives in Paris with good hospitals, schools and roads. They ask why their countries are so different.',
  sitQA: [['What is the problem in the situation?', 'The brothers want to understand differences in development.'], ['Give two signs of development in Paris.', 'Good hospitals and schools (also roads).'], ['Give one sign of underdevelopment in the situation.', 'No electricity (also few jobs).']],
  justification: 'This lesson helps us to understand what development means and how to achieve it sustainably.',
  action: 'Use resources wisely today so that future generations can also meet their needs.',
  activities: [
    { sec: '1. DEVELOPMENT', img: 'usa_skyline.jpg', caption: 'A city in a rich country.', q: 'What is development?', a: 'The improvement of people\'s living conditions: income, health, education and freedom.', noProj: 'list signs of development.' },
    { sec: '1. UNDERDEVELOPMENT', img: 'usa_slum.jpg', caption: 'A poor neighbourhood.', q: 'What is underdevelopment?', a: 'A situation where most people live in poverty, with poor services and low incomes.', noProj: 'list signs of poverty.' },
    { sec: '2. SUSTAINABLE DEVELOPMENT', img: 'sustain_big.png', caption: 'The three pillars.', q: 'What is sustainable development?', a: 'Development that meets present needs without harming the ability of future generations to meet theirs.', noProj: 'draw three circles.' },
    { sec: '2. PRINCIPLES', img: 'f2t_tree_planting.jpg', caption: 'Planting trees.', q: 'Give two principles of sustainable development.', a: 'Protect the environment and share wealth fairly (also involve people, think of the future).', noProj: 'discuss examples.' },
    { sec: '2. PRINCIPLES', img: 'usa_school.jpg', caption: 'A classroom.', q: 'Why is education a principle of sustainable development?', a: 'It gives people skills to improve their lives and protect their environment.', noProj: 'discuss the role of school.' },
  ],
  summary: [
    D([['Development:', 'It is the improvement of people\'s living conditions and well-being.'],
      ['Underdevelopment:', 'It is a situation of poverty, low income and poor services for most people.'],
      ['Sustainable development:', 'It is development that meets present needs without harming future generations.']]),
    { title: '1. Main Principles of Sustainable Development', intro: 'Sustainable development follows these principles:',
      items: [['Economic principle:', 'Economic growth must create jobs and income.'],
        ['Social principle:', 'Wealth, health and education must be shared fairly.'],
        ['Environmental principle:', 'Resources must be used without destroying the environment.'],
        ['Participation:', 'People must take part in decisions that affect them.']],
      draw: { img: 'sustain_big.png', caption: 'the pillars of sustainable development' } },
  ],
  evaluation: [['Define sustainable development.', 'Development that meets present needs without harming future generations.'], ['Give two principles.', 'Protect the environment and share wealth fairly.']],
  remediation: ['A situation of widespread poverty is ______.', 'Development that protects the future is ______ development.', 'The three pillars are economic, social and ______.'],
  remediationAnswers: '1. underdevelopment 2. sustainable 3. environmental',
  homework: 'Give three examples of sustainable actions in your community.',
  hwAnswer: 'Planting trees; sorting waste for compost; sending all children, including girls, to school.',
  bilingual: [['Development', 'Le développement'], ['Poverty', 'La pauvreté'], ['Sustainable', 'Durable'], ['Well-being', 'Le bien-être'], ['Future', "L'avenir"], ['Wealth', 'La richesse']],
});

L.push({ no: 19, title: 'Indicators of Development', subtopic: 'The Concept of Development',
  notions: 'Life expectancy, literacy, per capita income, Human Development Index (HDI).',
  focus: 'Traditional indicators; the HDI.',
  competence: 'Learners are able to use indicators to compare the development of countries.',
  objectives: ['Identify traditional indicators of development.', 'Explain the HDI.', 'Compare countries using indicators.'],
  recall: ['Some countries are richer than others.', 'Health and education improve lives.', 'Income is the money people earn.'],
  situation: 'A report says that people in Japan live on average 84 years, while in Chad they live about 53 years. Most adults in Japan can read, but many in Chad cannot.',
  sitQA: [['What is the problem in the situation?', 'We must measure the differences in development.'], ['Which indicator is about how long people live?', 'Life expectancy.'], ['Which indicator is about reading?', 'Literacy rate.']],
  justification: 'This lesson helps us to measure and compare development.',
  action: 'Read and compare development figures of Cameroon and other countries.',
  activities: [
    { sec: '1. ECONOMIC INDICATORS', img: 'dev_indicators_big.png', caption: 'Development indicators (approximate).', q: 'What is per capita income?', a: 'The total income of a country divided by its population.', noProj: 'write the formula.' },
    { sec: '1. SOCIAL INDICATORS', img: 'usa_clinic.jpg', caption: 'A health centre.', q: 'Give two social indicators of development.', a: 'Life expectancy and literacy rate (also doctors per person, infant mortality).', noProj: 'list indicators.' },
    { sec: '1. SOCIAL INDICATORS', img: 'usa_girls.jpg', caption: 'Girls at school.', q: 'Why is the literacy rate an indicator of development?', a: 'Educated people can get better jobs and improve their lives.', noProj: 'discuss schooling.' },
    { sec: '2. THE HDI', img: 'hdi_map_big.png', caption: 'Human Development Index (approximate).', q: 'What three things does the HDI combine?', a: 'Income, health (life expectancy) and education.', noProj: 'draw three boxes.' },
    { sec: '2. THE HDI', img: 'hdi_map_big.png', caption: 'HDI around the world.', q: 'Which region has the lowest HDI values?', a: 'Sub-Saharan Africa.', noProj: 'compare regions.' },
  ],
  summary: [
    D([['Indicator of development:', 'It is a measure used to show the level of development of a country.']]),
    { title: '1. Traditional Indicators', intro: 'Development is measured with the following traditional indicators:',
      items: [['Per capita income:', 'It is the income of a country divided by its population.'],
        ['Life expectancy:', 'It is the average number of years a person is expected to live.'],
        ['Literacy rate:', 'It is the percentage of adults who can read and write.'],
        ['Other indicators:', 'Infant mortality, doctors per person and access to water are also used.']],
      draw: { img: 'dev_indicators_big.png', caption: 'development indicators' } },
    { title: '2. The Human Development Index', intro: 'The HDI is explained as follows:',
      items: [['Meaning:', 'The HDI combines income, life expectancy and education on a scale from 0 to 1.'],
        ['Use:', 'Countries near 1 are very developed and countries below 0.55 have low development.'],
        ['Cameroon:', 'Cameroon has a medium HDI of about 0.59.']] },
  ],
  evaluation: [['Give three indicators of development.', 'Per capita income, life expectancy and literacy rate.'], ['What does the HDI combine?', 'Income, health and education.']],
  remediation: ['The average years a person lives is life ______.', 'The HDI ranges from 0 to ______.', 'The percentage of adults who can read is the ______ rate.'],
  remediationAnswers: '1. expectancy 2. 1 3. literacy',
  homework: 'Compare Cameroon and one developed country using two indicators.',
  hwAnswer: 'Example: life expectancy about 61 years in Cameroon vs 83 in France; per capita income about 1,600 US$ vs about 40,000 US$.',
  bilingual: [['Indicator', "L'indicateur"], ['Income', 'Le revenu'], ['Life expectancy', "L'espérance de vie"], ['Literacy', "L'alphabétisation"], ['Index', "L'indice"], ['Health', 'La santé']],
});

L.push({ no: 20, title: 'Classification of Countries in Terms of Development Levels', subtopic: 'Challenges of Development and Fight against Underdevelopment',
  notions: 'Least Industrialised Countries (LICs), Newly Industrialised Countries (NICs), Advanced Industrialised Countries (AICs), industrialisation.',
  focus: 'Least Industrialised Countries; Newly Industrialised Countries; Advanced Industrialised Countries.',
  competence: 'Learners are able to classify countries by level of development.',
  objectives: ['Define LICs, NICs and AICs.', 'Give examples of each group.', 'Give the characteristics of each group.'],
  recall: ['Indicators measure development.', 'Some countries have many factories.', 'Cameroon exports raw materials.'],
  situation: 'In the market, Aminatou sees phones made in China, cars made in Japan and cocoa from Cameroon. She wonders why some countries make machines and others sell raw materials.',
  sitQA: [['What is the problem in the situation?', 'Countries have different levels of industrialisation.'], ['Which country sells raw materials?', 'Cameroon.'], ['Which countries make machines?', 'China and Japan.']],
  justification: 'This lesson helps us to classify countries and understand where Cameroon stands.',
  action: 'Support local processing of raw materials.',
  activities: [
    { sec: '1. LICs', img: 'usa_sacks.jpg', caption: 'Sacks of cocoa for export.', q: 'What are Least Industrialised Countries? Give two examples.', a: 'Poor countries that mainly export raw materials, such as Chad and Niger (Cameroon is close to this group).', noProj: 'list exports of Cameroon.' },
    { sec: '2. NICs', img: 'usa_singapore.jpg', caption: 'Singapore.', q: 'What are Newly Industrialised Countries? Give two examples.', a: 'Countries that industrialised quickly since the 1960s, such as South Korea and Singapore (also China, Brazil).', noProj: 'list goods from Asia.' },
    { sec: '2. NICs', img: 'nics_big.png', caption: 'Generations of NICs.', q: 'Name the four Asian tigers.', a: 'South Korea, Taiwan, Singapore and Hong Kong.', noProj: 'use the atlas.' },
    { sec: '3. AICs', img: 'usa_carfactory.jpg', caption: 'A car factory.', q: 'What are Advanced Industrialised Countries? Give two examples.', a: 'Rich countries with many industries and services, such as the USA and Germany (also Japan, France).', noProj: 'list rich countries.' },
    { sec: '3. COMPARISON', img: 'industry_world_big.png', caption: 'Industrial regions of the world.', q: 'Where are most AICs and NICs located?', a: 'AICs in North America, Europe and Japan; NICs mainly in East Asia and Latin America.', noProj: 'use the map.' },
  ],
  summary: [
    D([['Industrialisation:', 'It is the growth of industries in a country.']]),
    { title: '1. Classification of Countries', intro: 'Countries are classified into the following groups:',
      items: [['Least Industrialised Countries:', 'They are poor, depend on farming and export raw materials, such as Chad and Niger.'],
        ['Newly Industrialised Countries:', 'They industrialised quickly since the 1960s, such as South Korea, Singapore, China and Brazil.'],
        ['Advanced Industrialised Countries:', 'They are rich and have many industries and services, such as the USA, Germany and Japan.']],
      draw: { img: 'industry_world_big.png', caption: 'industrial regions of the world' } },
    { title: '2. Characteristics', intro: 'The groups have the following characteristics:',
      items: [['LICs:', 'They have high birth rates, low incomes and poor services.'],
        ['NICs:', 'They have fast-growing industries and exports of manufactured goods.'],
        ['AICs:', 'They have high incomes, long life expectancy and advanced technology.']] },
  ],
  evaluation: [['Give one example of an LIC, an NIC and an AIC.', 'Chad, South Korea and the USA.'], ['Give one characteristic of NICs.', 'Rapid growth of industries and exports.']],
  remediation: ['South Korea is a ______.', 'Countries that export raw materials are mostly ______.', 'Japan is an ______.'],
  remediationAnswers: '1. NIC 2. LICs 3. AIC',
  homework: 'Find the country of origin of five manufactured goods at home and classify the countries.',
  hwAnswer: 'Examples: phone (China – NIC), television (South Korea – NIC), car (Japan – AIC), medicine (France – AIC), shoes (China – NIC).',
  bilingual: [['Industry', "L'industrie"], ['Raw material', 'La matière première'], ['Export', "L'exportation"], ['Rich', 'Riche'], ['Poor', 'Pauvre'], ['Factory', "L'usine"]],
});

L.push({ no: 21, title: "Rostow's Model of Economic Growth", subtopic: 'Challenges of Development and Fight against Underdevelopment',
  notions: 'Traditional society, preconditions for take-off, take-off, drive to maturity, age of mass consumption.',
  focus: 'Illustration of the model; characteristics of main stages; examples of countries at each stage.',
  competence: 'Learners are able to describe the stages of Rostow\'s model and place countries on it.',
  objectives: ['Illustrate Rostow\'s model.', 'Describe the characteristics of each stage.', 'Give examples of countries at each stage.'],
  recall: ['Countries have different levels of development.', 'NICs industrialised quickly.', 'AICs are rich.'],
  situation: 'The economist W.W. Rostow said that all countries pass through five stages to become developed, like a plane taxiing, taking off and flying. The class wonders where Cameroon is.',
  sitQA: [['What is the problem in the situation?', 'We want to know the stages of economic growth.'], ['How many stages did Rostow describe?', 'Five.'], ['What is the model compared to?', 'An aeroplane taking off.']],
  justification: 'This lesson helps us to understand the stages of economic growth.',
  action: 'Discuss what Cameroon needs to reach take-off.',
  activities: [
    { sec: '1. THE MODEL', img: 'rostow_big.png', caption: "Rostow's five stages.", q: 'Name the five stages of Rostow\'s model.', a: 'Traditional society, preconditions for take-off, take-off, drive to maturity, age of high mass consumption.', noProj: 'draw steps on the board.' },
    { sec: '2. TRADITIONAL SOCIETY', img: 'f2t_cattle_field.jpg', caption: 'Traditional farming.', q: 'Describe the traditional society stage.', a: 'Most people are subsistence farmers with simple tools and little trade.', noProj: 'describe old village life.' },
    { sec: '2. PRECONDITIONS AND TAKE-OFF', img: 'f2t_textile_factory.jpg', caption: 'A textile factory.', q: 'What happens at take-off?', a: 'Industries grow quickly, investment rises and towns grow.', noProj: 'discuss industries of Cameroon.' },
    { sec: '2. MATURITY AND MASS CONSUMPTION', img: 'usa_skyline.jpg', caption: 'A rich city.', q: 'Describe the age of high mass consumption.', a: 'People have high incomes and buy many consumer goods; services dominate.', noProj: 'list consumer goods.' },
    { sec: '3. EXAMPLES', img: 'rostow_big.png', caption: 'Countries at each stage.', q: 'Give one country at take-off and one at mass consumption.', a: 'Take-off: India or Vietnam (Cameroon is at the preconditions stage). Mass consumption: the USA.', noProj: 'place countries on the steps.' },
  ],
  summary: [
    { title: "1. Rostow's Model", intro: 'Rostow (1960) described five stages of economic growth:',
      items: [['Traditional society:', 'People are subsistence farmers with simple technology.'],
        ['Preconditions for take-off:', 'Roads, schools and commercial farming develop.'],
        ['Take-off:', 'Industries grow rapidly and investment increases.'],
        ['Drive to maturity:', 'Industries become varied and technology spreads.'],
        ['Age of high mass consumption:', 'Incomes are high and people buy many consumer goods.']],
      draw: { img: 'rostow_big.png', caption: "Rostow's model" } },
    { title: '2. Examples of Countries', intro: 'Countries can be placed on the model as follows:',
      items: [['Early stages:', 'Many LICs such as Chad are between traditional society and preconditions.'],
        ['Take-off and maturity:', 'NICs such as China and India are at take-off or drive to maturity.'],
        ['Mass consumption:', 'AICs such as the USA, Japan and France have reached this stage.']] },
  ],
  evaluation: [['Name the five stages of Rostow\'s model.', 'Traditional society, preconditions, take-off, drive to maturity, mass consumption.'], ['At which stage are industries growing fastest?', 'Take-off.']],
  remediation: ['The first stage of Rostow\'s model is ______ society.', 'Rapid industrial growth happens at ______.', 'The USA is at the age of high mass ______.'],
  remediationAnswers: '1. traditional 2. take-off 3. consumption',
  homework: 'At which stage of Rostow\'s model is Cameroon? Give two reasons.',
  hwAnswer: 'At the preconditions for take-off: roads, schools and commercial farming are developing, but industries are still few and exports are mainly raw materials.',
  bilingual: [['Stage', "L'étape"], ['Growth', 'La croissance'], ['Take-off', 'Le décollage'], ['Maturity', 'La maturité'], ['Consumption', 'La consommation'], ['Model', 'Le modèle']],
});

L.push({ no: 22, title: 'Challenges of Development', subtopic: 'Challenges of Development and Fight against Underdevelopment',
  notions: 'Poverty, poverty cycle, underdevelopment.',
  focus: 'Definition of poverty and the poverty cycle; causes of poverty and underdevelopment; solutions.',
  competence: 'Learners are able to explain the poverty cycle and propose solutions to underdevelopment.',
  objectives: ['Define poverty and the poverty cycle.', 'Explain the causes of poverty and underdevelopment.', 'Propose solutions.'],
  recall: ['Many people in Africa are poor.', 'Education helps people get jobs.', 'Corruption slows development.'],
  situation: 'A poor farmer earns little, so he cannot buy fertiliser or send his children to school. His harvests stay low, his children cannot find good jobs, and the family stays poor.',
  sitQA: [['What is the problem in the situation?', 'The family is trapped in poverty.'], ['Why do harvests stay low?', 'He cannot buy fertiliser.'], ['What is this repeated situation called?', 'The poverty cycle.']],
  justification: 'This lesson helps us to understand poverty and how to break it.',
  action: 'Value education and hard work to break the poverty cycle.',
  activities: [
    { sec: '1. MEANING', img: 'usa_slum.jpg', caption: 'A poor neighbourhood.', q: 'What is poverty?', a: 'A situation where people cannot meet their basic needs: food, housing, health and education.', noProj: 'list basic needs.' },
    { sec: '1. THE POVERTY CYCLE', img: 'poverty_cycle_big.png', caption: 'The poverty cycle.', q: 'Describe the poverty cycle.', a: 'Low income → low savings → low investment → low production → low income again.', noProj: 'draw the cycle.' },
    { sec: '2. CAUSES', img: 'underdev_causes_big.png', caption: 'Causes of underdevelopment.', q: 'Give three causes of underdevelopment.', a: 'Poor governance and corruption, rapid population growth and conflicts (also unfair trade, debt).', noProj: 'discuss causes.' },
    { sec: '3. SOLUTIONS', img: 'usa_school.jpg', caption: 'Education.', q: 'Give two solutions to poverty.', a: 'Education and job creation (also good governance, health care).', noProj: 'list solutions.' },
    { sec: '3. SOLUTIONS', img: 'f2t_mobile_money.jpg', caption: 'Mobile money.', q: 'How can small loans and savings help the poor?', a: 'They allow poor people to start small businesses and earn income.', noProj: 'discuss njangi (tontines).' },
  ],
  summary: [
    D([['Poverty:', 'It is a situation where people cannot meet their basic needs.'],
      ['Poverty cycle:', 'It is a chain in which low income leads to low savings, low investment and again low income.']]),
    { title: '1. Causes of Poverty and Underdevelopment', intro: 'Poverty and underdevelopment have the following causes:',
      items: [['Political causes:', 'Poor governance, corruption and conflicts slow development.'],
        ['Economic causes:', 'Unfair trade, debt and dependence on raw materials keep countries poor.'],
        ['Social causes:', 'Illiteracy, diseases and rapid population growth reduce progress.']] },
    { title: '2. Solutions to Poverty and Underdevelopment', intro: 'Poverty can be reduced by the following solutions:',
      items: [['Education and health:', 'Schools and hospitals give people skills and strength to work.'],
        ['Jobs and investment:', 'Industries, farming and small loans create income.'],
        ['Good governance:', 'Fighting corruption and keeping peace help development.']] },
  ],
  evaluation: [['What is the poverty cycle?', 'Low income → low savings → low investment → low income.'], ['Give two causes of underdevelopment.', 'Corruption and illiteracy.']],
  remediation: ['Not meeting basic needs is ______.', 'Stealing public money is ______.', 'Education helps to break the poverty ______.'],
  remediationAnswers: '1. poverty 2. corruption 3. cycle',
  homework: 'Draw the poverty cycle and show where education can break it.',
  hwAnswer: 'The cycle: low income → low savings → low investment → low productivity → low income. Education raises productivity and income, breaking the cycle.',
  bilingual: [['Poverty', 'La pauvreté'], ['Cycle', 'Le cercle vicieux'], ['Savings', "L'épargne"], ['Corruption', 'La corruption'], ['Debt', 'La dette'], ['Job', "L'emploi"]],
});

L.push({ no: 23, title: 'Global Solutions to Poverty and Underdevelopment', subtopic: 'Challenges of Development and Fight against Underdevelopment',
  notions: 'Millennium Development Goals (MDGs), Sustainable Development Goals (SDGs).',
  focus: 'The MDGs: evaluation (successes and limitations); other solutions: the SDGs.',
  competence: 'Learners are able to describe the MDGs and SDGs and evaluate their results.',
  objectives: ['Describe the MDGs.', 'Evaluate their successes and limitations.', 'Describe the SDGs.'],
  recall: ['Poverty is a world problem.', 'The United Nations helps countries.', 'Development must be sustainable.'],
  situation: 'In 2000, world leaders promised to halve extreme poverty by 2015. In 2015, they made new promises for 2030 with 17 goals.',
  sitQA: [['What is the problem in the situation?', 'World leaders set goals to fight poverty.'], ['What were the goals of 2000 called?', 'The Millennium Development Goals (MDGs).'], ['What are the goals for 2030 called?', 'The Sustainable Development Goals (SDGs).']],
  justification: 'This lesson helps us to know the world plan against poverty.',
  action: 'Take part in actions that support the SDGs in your community.',
  activities: [
    { sec: '1. THE MDGs', img: 'mdg_sdg_big.png', caption: 'MDGs and SDGs.', q: 'How many MDGs were there and for which period?', a: 'Eight goals, from 2000 to 2015.', noProj: 'list some MDGs.' },
    { sec: '1. EXAMPLES OF MDGs', img: 'usa_children.jpg', caption: 'Children at school.', q: 'Give two MDGs.', a: 'Halve extreme poverty and hunger; primary education for all (also reduce child deaths, fight HIV and malaria).', noProj: 'discuss goals.' },
    { sec: '2. EVALUATION', img: 'usa_vaccine.jpg', caption: 'A child vaccinated.', q: 'Give one success and one limitation of the MDGs.', a: 'Success: extreme poverty was halved in the world. Limitation: many African countries did not reach the goals.', noProj: 'discuss results.' },
    { sec: '3. THE SDGs', img: 'mdg_sdg_big.png', caption: 'The SDGs.', q: 'How many SDGs are there and for which period?', a: 'Seventeen goals, from 2015 to 2030.', noProj: 'list some SDGs.' },
    { sec: '3. THE SDGs', img: 'f2t_tree_planting_sahel.jpg', caption: 'Planting trees.', q: 'What is new in the SDGs compared to the MDGs?', a: 'They concern all countries and add climate, cities, peace and the environment.', noProj: 'compare the two.' },
  ],
  summary: [
    D([['MDGs:', 'They were 8 goals set by the United Nations for 2000–2015 to reduce poverty.'],
      ['SDGs:', 'They are 17 goals set by the United Nations for 2015–2030 for sustainable development.']]),
    { title: '1. The MDGs and their Evaluation', intro: 'The MDGs are evaluated as follows:',
      items: [['Goals:', 'They aimed to halve poverty and hunger, educate all children, reduce child deaths and fight diseases.'],
        ['Successes:', 'Extreme poverty was halved and more children went to school.'],
        ['Limitations:', 'Many African countries did not reach the goals because of lack of money and conflicts.']] },
    { title: '2. The SDGs', intro: 'The SDGs are presented as follows:',
      items: [['Goals:', 'They aim to end poverty and hunger and give health, education, clean water and energy to all.'],
        ['Novelty:', 'They add climate action, sustainable cities, peace and protection of nature.'],
        ['Scope:', 'They concern all countries, rich and poor.']],
      draw: { img: 'mdg_sdg_big.png', caption: 'MDGs and SDGs' } },
  ],
  evaluation: [['How many MDGs and SDGs are there?', '8 MDGs and 17 SDGs.'], ['Give one limitation of the MDGs.', 'Many African countries did not reach them.']],
  remediation: ['The MDGs ended in ______.', 'The SDGs end in ______.', 'There are ______ SDGs.'],
  remediationAnswers: '1. 2015 2. 2030 3. 17',
  homework: 'Choose one SDG and describe what your community does to achieve it.',
  hwAnswer: 'Example: SDG 4 (quality education) – the community builds classrooms and parents send girls to school.',
  bilingual: [['Goal', "L'objectif"], ['Hunger', 'La faim'], ['Education', "L'éducation"], ['United Nations', 'Les Nations unies'], ['Success', 'Le succès'], ['Limit', 'La limite']],
});

L.push({ no: 24, title: 'Strategies for the Emergence of the NICs', subtopic: 'Challenges of Development and Fight against Underdevelopment',
  notions: 'NIC, emergence, export-led growth, enabling environment.',
  focus: 'Strategies (reasons) for the emergence of the NICs.',
  competence: 'Learners are able to explain how NICs developed and draw lessons for Cameroon.',
  objectives: ['Define emergence.', 'Explain the strategies used by NICs.', 'Draw lessons for Cameroon\'s vision of emergence by 2035.'],
  recall: ['South Korea is an NIC.', 'NICs industrialised quickly.', 'Cameroon wants to become emergent.'],
  situation: 'In 1960, South Korea and Cameroon were both poor. Today South Korea exports cars and phones. Cameroon aims to become an emergent country by 2035.',
  sitQA: [['What is the problem in the situation?', 'We want to know how South Korea developed.'], ['What does South Korea export?', 'Cars and phones.'], ['What is Cameroon\'s aim?', 'To become emergent by 2035.']],
  justification: 'This lesson helps us to learn from successful countries.',
  action: 'Study hard and develop technical skills for the emergence of Cameroon.',
  activities: [
    { sec: '1. MEANING', img: 'usa_singapore.jpg', caption: 'Singapore.', q: 'What is an emergent country?', a: 'A country that moves quickly from poverty towards development through industry and trade.', noProj: 'name emergent countries.' },
    { sec: '2. STRATEGIES', img: 'nic_strategies_big.png', caption: 'Strategies of NICs.', q: 'Give three strategies used by NICs.', a: 'Strong governments, education and training, and export-led industries (also foreign investment).', noProj: 'list strategies.' },
    { sec: '2. EDUCATION', img: 'f2t_computer_class.jpg', caption: 'Learners in a computer class.', q: 'Why was education important for NICs?', a: 'It gave a skilled workforce for modern industries.', noProj: 'discuss technical schools.' },
    { sec: '2. EXPORT INDUSTRIES', img: 'usa_electronics.jpg', caption: 'Workers in an electronics factory.', q: 'Why did NICs produce for export?', a: 'To earn foreign currency and grow faster than with the small home market.', noProj: 'list exports of NICs.' },
    { sec: '3. LESSONS FOR CAMEROON', img: 'usa_techpark.jpg', caption: 'A technology park.', q: 'Give two lessons Cameroon can learn from NICs.', a: 'Process raw materials locally and invest in education and infrastructure (also fight corruption).', noProj: 'discuss Vision 2035.' },
  ],
  summary: [
    D([['Emergence:', 'It is the rapid move of a country from poverty towards development.']]),
    { title: '1. Strategies for the Emergence of NICs', intro: 'NICs developed through the following strategies:',
      items: [['Strong and stable governments:', 'They planned development and built roads, ports and energy.'],
        ['Education and training:', 'They trained a skilled and disciplined workforce.'],
        ['Export-led growth:', 'They produced goods such as textiles, electronics and cars for export.'],
        ['Foreign investment:', 'Free zones and low taxes attracted foreign companies.']],
      draw: { img: 'nic_strategies_big.png', caption: 'strategies of NICs' } },
    { title: '2. Lessons for Cameroon', intro: 'Cameroon can learn the following lessons for its Vision 2035:',
      items: [['Industrialisation:', 'Process raw materials such as cocoa and cotton in Cameroon.'],
        ['Human capital:', 'Invest in technical education and health.'],
        ['Governance:', 'Fight corruption and keep peace to attract investors.']] },
  ],
  evaluation: [['Give three strategies of NICs.', 'Strong government, education and export industries.'], ['Give one lesson for Cameroon.', 'Process raw materials locally.']],
  remediation: ['Growth based on selling goods abroad is ______-led growth.', 'Cameroon aims to be emergent by ______.', 'Singapore is an ______.'],
  remediationAnswers: '1. export 2. 2035 3. NIC',
  homework: 'Compare South Korea and Cameroon in 1960 and today using two indicators.',
  hwAnswer: 'In 1960 both had low incomes (under 200 US$ per person). Today South Korea has over 30,000 US$ and exports cars and electronics; Cameroon has about 1,600 US$ and exports raw materials.',
  bilingual: [['Emergence', "L'émergence"], ['Strategy', 'La stratégie'], ['Investment', "L'investissement"], ['Export', "L'exportation"], ['Skill', 'La compétence'], ['Vision', 'La vision']],
});

module.exports = { B, L };
