// FORM 4 — Module II, part 2: L25–L38 (economic activities and agriculture)
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F4', code: 'M2', folder: '', module: 'Module II: Development and the Management of Primary Resources', topicDefault: 'Managing Resources for Development through Economic Activities', branch: 'Agriculture as an Economic Activity of the Primary Sector',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 4, Module II: Development and the Management of Primary Resources.'] };
const L = [];

L.push({ no: 25, title: 'Economic Activities', subtopic: 'Notion of Economic Activity',
  notions: 'Economic activity, primary, secondary, tertiary, quaternary sectors.',
  focus: 'Meaning; classification of economic activities into sectors.',
  competence: 'Learners are able to classify economic activities into sectors.',
  objectives: ['Define an economic activity.', 'Classify economic activities into four sectors.', 'Give examples from Cameroon.'],
  recall: ['People work to earn money.', 'Farmers grow crops and factories make goods.', 'Teachers and doctors give services.'],
  situation: 'In Garoua, Moussa\'s father grows cotton, his uncle works at the CICAM textile factory, his aunt sells cloth in the market and his cousin does research at IRAD.',
  sitQA: [['What is the problem in the situation?', 'We want to classify the jobs of the family.'], ['Which job takes a product from nature?', 'Growing cotton.'], ['Which job makes goods?', 'Working at the textile factory.']],
  justification: 'This lesson helps us to understand how people earn a living.',
  action: 'Value all jobs, because the sectors depend on each other.',
  activities: [
    { sec: '1. MEANING', img: 'f2t_market.jpg', caption: 'A busy market.', q: 'What is an economic activity?', a: 'Any activity people do to produce goods or services and earn money.', noProj: 'list jobs of parents.' },
    { sec: '2. PRIMARY SECTOR', img: 'f2t_cotton_harvest.jpg', caption: 'Cotton harvest.', q: 'What is the primary sector? Give two examples.', a: 'Activities that take products from nature: farming and fishing (also mining, forestry).', noProj: 'list primary jobs.' },
    { sec: '2. SECONDARY SECTOR', img: 'f2t_textile_factory.jpg', caption: 'A textile factory.', q: 'What is the secondary sector?', a: 'Activities that transform raw materials into goods, such as factories and crafts.', noProj: 'list factories of Cameroon.' },
    { sec: '2. TERTIARY SECTOR', img: 'f2t_bank.jpg', caption: 'A bank.', q: 'What is the tertiary sector?', a: 'Activities that provide services, such as trade, transport, banks and schools.', noProj: 'list services.' },
    { sec: '2. QUATERNARY SECTOR', img: 'cotton_journey.gif', caption: 'Animation: the journey of cotton through the sectors.', q: 'What is the quaternary sector?', a: 'Activities of knowledge and research, such as IRAD and ICT.', noProj: 'follow cotton through the sectors.' },
  ],
  summary: [
    D([['Economic activity:', 'It is any activity people do to produce goods or services and earn money.']]),
    { title: '1. Classification of Economic Activities', intro: 'Economic activities are classified into four sectors:',
      items: [['Primary sector:', 'It takes products from nature, such as farming, fishing, forestry and mining.'],
        ['Secondary sector:', 'It transforms raw materials into goods, such as factories and crafts.'],
        ['Tertiary sector:', 'It provides services, such as trade, transport, health and education.'],
        ['Quaternary sector:', 'It produces knowledge, such as research and ICT.']],
      draw: { img: 'cotton_journey_last.png', caption: 'the four sectors of the economy' } },
  ],
  evaluation: [['Name the four sectors of the economy.', 'Primary, secondary, tertiary and quaternary.'], ['Classify: fishing, teaching, weaving.', 'Primary, tertiary, secondary.']],
  remediation: ['Farming belongs to the ______ sector.', 'Factories belong to the ______ sector.', 'Research belongs to the ______ sector.'],
  remediationAnswers: '1. primary 2. secondary 3. quaternary',
  homework: 'List the jobs of five people you know and classify them into sectors.',
  hwAnswer: 'Examples: farmer (primary), mechanic (secondary or tertiary), trader (tertiary), teacher (tertiary), computer programmer (quaternary).',
  bilingual: [['Sector', 'Le secteur'], ['Primary', 'Primaire'], ['Service', 'Le service'], ['Goods', 'Les biens'], ['Research', 'La recherche'], ['Job', "L'emploi"]],
});

L.push({ no: 26, title: 'Agriculture', subtopic: 'Agriculture as an Economic Activity of the Primary Sector',
  notions: 'Agriculture, inputs, processes, outputs.',
  focus: 'Meaning; agriculture as a system (flow diagram only).',
  competence: 'Learners are able to explain agriculture as a system of inputs, processes and outputs.',
  objectives: ['Define agriculture.', 'Identify the inputs, processes and outputs of a farm.', 'Draw the farm system.'],
  recall: ['Farming is a primary activity.', 'Farmers need land, seeds and work.', 'Farms produce crops and animals.'],
  situation: 'A farmer near Garoua uses land, seeds, fertiliser and his family\'s labour. He ploughs, sows, weeds and harvests. He sells some cotton and keeps maize for the family.',
  sitQA: [['What is the problem in the situation?', 'We want to see the farm as a system.'], ['Name two inputs.', 'Seeds and fertiliser (also land, labour).'], ['Name two outputs.', 'Cotton and maize.']],
  justification: 'This lesson helps us to understand how a farm works.',
  action: 'Plan inputs carefully to get good outputs.',
  activities: [
    { sec: '1. MEANING', img: 'f2t_maize.jpg', caption: 'Maize.', q: 'What is agriculture?', a: 'The growing of crops and the rearing of animals.', noProj: 'list crops and animals.' },
    { sec: '2. INPUTS', img: 'agri_system_big.png', caption: 'The farm as a system.', q: 'Name four inputs of a farm.', a: 'Land, labour, seeds and fertiliser (also capital, machines, water).', noProj: 'draw the inputs.' },
    { sec: '2. PROCESSES', img: 'f4_rainyseason.jpg', caption: 'A farmer sowing.', q: 'Name four farm processes.', a: 'Ploughing, sowing, weeding and harvesting.', noProj: 'describe the farming calendar.' },
    { sec: '2. OUTPUTS', img: 'f2t_cotton_harvest2.jpg', caption: 'Carrying harvested cotton.', q: 'Name three outputs of a farm.', a: 'Crops, animal products and income (also waste).', noProj: 'list products.' },
    { sec: '2. FEEDBACK', img: 'agri_system_big.png', caption: 'Feedback in the farm system.', q: 'What is feedback in the farm system?', a: 'Profits or seeds from the harvest are reinvested in the farm.', noProj: 'draw an arrow back to inputs.' },
  ],
  summary: [
    D([['Agriculture:', 'It is the growing of crops and the rearing of animals.']]),
    { title: '1. Agriculture as a System', intro: 'A farm works as a system with the following parts:',
      items: [['Inputs:', 'They are land, labour, seeds, fertiliser, water and capital.'],
        ['Processes:', 'They are ploughing, sowing, weeding, spraying and harvesting.'],
        ['Outputs:', 'They are crops, milk, meat, income and sometimes waste.'],
        ['Feedback:', 'Part of the profit or harvest is reinvested in the farm.']],
      draw: { img: 'agri_system_big.png', caption: 'the farm as a system' } },
  ],
  evaluation: [['Define agriculture.', 'The growing of crops and rearing of animals.'], ['Give two inputs, two processes and two outputs.', 'Inputs: seeds, labour. Processes: sowing, harvesting. Outputs: crops, income.']],
  remediation: ['Seeds and fertiliser are ______.', 'Sowing and weeding are ______.', 'Crops and income are ______.'],
  remediationAnswers: '1. inputs 2. processes 3. outputs',
  homework: 'Draw the system of a farm you know with its inputs, processes and outputs.',
  hwAnswer: 'Example: inputs – land, seeds, family labour, fertiliser; processes – ploughing with oxen, sowing, weeding, harvesting; outputs – maize, cotton, income.',
  bilingual: [['Agriculture', "L'agriculture"], ['Input', "L'intrant"], ['Output', 'Le produit'], ['Harvest', 'La récolte'], ['Seed', 'La semence'], ['Labour', 'La main-d\'œuvre']],
});

L.push({ no: 27, title: 'Agricultural Systems', subtopic: 'Agriculture as an Economic Activity of the Primary Sector',
  notions: 'Arable farming, pastoral farming, intensive, extensive, subsistence, commercial.',
  focus: 'Meaning; classification (intensive and extensive); general characteristics of each system.',
  competence: 'Learners are able to classify agricultural systems and describe their characteristics.',
  objectives: ['Define an agricultural system.', 'Classify systems into intensive and extensive.', 'Describe the characteristics of each system.'],
  recall: ['Agriculture has inputs, processes and outputs.', 'Some farms are small, others very large.', 'Some farmers sell, others eat their harvest.'],
  situation: 'In the Netherlands, a small farm produces a lot using machines, fertiliser and greenhouses. In the Sahel, herders move over very large areas with few inputs.',
  sitQA: [['What is the problem in the situation?', 'We want to compare different farming systems.'], ['Which farm uses many inputs on a small area?', 'The Dutch farm (intensive).'], ['Which uses few inputs on a large area?', 'Sahel herding (extensive).']],
  justification: 'This lesson helps us to classify the ways people farm.',
  action: 'Choose farming methods that suit the land and the capital available.',
  activities: [
    { sec: '1. MEANING', img: 'agri_types_big.png', caption: 'Types of agriculture.', q: 'What is an agricultural system?', a: 'A way of farming defined by its inputs, methods and purpose.', noProj: 'list farming types.' },
    { sec: '2. ARABLE AND PASTORAL', img: 'f2t_cattle.jpg', caption: 'Cattle.', q: 'Distinguish arable farming and pastoral farming.', a: 'Arable farming grows crops; pastoral farming rears animals.', noProj: 'give examples.' },
    { sec: '2. INTENSIVE', img: 'usa_greenhouse.jpg', caption: 'A greenhouse.', q: 'What is intensive farming?', a: 'Using many inputs of labour or capital on a small area to get high yields.', noProj: 'describe a market garden.' },
    { sec: '2. EXTENSIVE', img: 'usa_herders.jpg', caption: 'Herders in the Sahel.', q: 'What is extensive farming?', a: 'Using few inputs on a large area, with low yields per hectare.', noProj: 'describe herding in the north.' },
    { sec: '3. CHARACTERISTICS', img: 'agri_types_big.png', caption: 'Subsistence and commercial farming.', q: 'Distinguish subsistence and commercial farming.', a: 'Subsistence farming feeds the family; commercial farming produces for sale.', noProj: 'classify local farms.' },
  ],
  summary: [
    D([['Agricultural system:', 'It is a way of farming defined by its inputs, methods and purpose.']]),
    { title: '1. Classification', intro: 'Agricultural systems are classified as follows:',
      items: [['Arable and pastoral farming:', 'Arable farming grows crops, while pastoral farming rears animals.'],
        ['Intensive farming:', 'It uses many inputs on a small area and gives high yields per hectare.'],
        ['Extensive farming:', 'It uses few inputs on a large area and gives low yields per hectare.'],
        ['Subsistence and commercial farming:', 'Subsistence farming feeds the family, while commercial farming sells its products.']],
      draw: { img: 'agri_types_big.png', caption: 'types of agriculture' } },
    { title: '2. General Characteristics', intro: 'The systems have the following characteristics:',
      items: [['Intensive systems:', 'Small farms, much labour or capital, fertilisers and irrigation, as in market gardening.'],
        ['Extensive systems:', 'Large areas, few workers, little capital, as in nomadic herding and wheat farming.']] },
  ],
  evaluation: [['Distinguish intensive and extensive farming.', 'Intensive: many inputs on a small area. Extensive: few inputs on a large area.'], ['Give one example of each.', 'Intensive: market gardening. Extensive: nomadic herding.']],
  remediation: ['Growing crops is ______ farming.', 'Rearing animals is ______ farming.', 'Farming for sale is ______ farming.'],
  remediationAnswers: '1. arable 2. pastoral 3. commercial',
  homework: 'Classify three farms of your area as intensive or extensive and justify.',
  hwAnswer: 'Example: onion gardens by the Benue – intensive (much labour and water on small plots); cotton fields – semi-intensive; cattle herding – extensive (large areas, few inputs).',
  bilingual: [['Arable', 'Agricole (cultures)'], ['Pastoral', 'Pastoral'], ['Intensive', 'Intensif'], ['Extensive', 'Extensif'], ['Subsistence', 'La subsistance'], ['Commercial', 'Commercial']],
});

L.push({ no: 28, title: 'Intensive and Extensive Agriculture', subtopic: 'Agriculture as an Economic Activity of the Primary Sector',
  notions: 'Market gardening, mixed farming, dairy farming, viticulture, shifting cultivation, bush fallowing, pastoral nomadism, plantation farming.',
  focus: 'For each type: definition only; where commonly practised.',
  competence: 'Learners are able to define the main types of intensive and extensive agriculture and locate them.',
  objectives: ['Define the main types of intensive agriculture.', 'Define the main types of extensive agriculture.', 'Locate where each type is practised.'],
  recall: ['Intensive farming uses many inputs.', 'Extensive farming uses large areas.', 'Cameroon has plantations.'],
  situation: 'A documentary shows vegetable gardens in Holland, vineyards in France, shifting cultivation in the Congo forest and cattle herds in the Sahel.',
  sitQA: [['What is the problem in the situation?', 'We want to name and locate farming types.'], ['Which type is shown in France?', 'Viticulture.'], ['Which type is shown in the Sahel?', 'Pastoral nomadism.']],
  justification: 'This lesson helps us to know the main farming types of the world.',
  action: 'Recognise the farming types around you.',
  activities: [
    { sec: '1. MARKET GARDENING', img: 'usa_greenhouse.jpg', caption: 'Vegetables in a greenhouse.', q: 'What is market gardening and where is it practised?', a: 'Growing vegetables and fruits for nearby towns; around big cities and in the Netherlands (also near Garoua).', noProj: 'describe onion gardens.' },
    { sec: '1. MIXED AND DAIRY FARMING', img: 'f2t_dairy.jpg', caption: 'A dairy cow.', q: 'Define mixed farming and dairy farming.', a: 'Mixed: crops and animals on one farm (Europe). Dairy: rearing cows for milk (Netherlands, Denmark).', noProj: 'list milk products.' },
    { sec: '1. VITICULTURE AND PLANTATIONS', img: 'lsa_oilpalm.jpg', caption: 'An oil palm plantation.', q: 'Define plantation farming and give an example in Cameroon.', a: 'A large farm growing one cash crop for export, such as the oil palm and rubber of the CDC.', noProj: 'name plantations.' },
    { sec: '2. SHIFTING CULTIVATION AND BUSH FALLOWING', img: 'f2t_clearing.jpg', caption: 'A cleared plot.', q: 'Where are shifting cultivation and bush fallowing practised?', a: 'In the tropical forests of Africa, the Amazon and South-East Asia.', noProj: 'describe farming in the South.' },
    { sec: '2. PASTORAL NOMADISM AND RANCHING', img: 'f2t_ranch.jpg', caption: 'A ranch.', q: 'Distinguish pastoral nomadism and ranching.', a: 'Nomadism: moving with herds (Sahel). Ranching: keeping animals on a large fenced farm (Argentina, Adamawa).', noProj: 'describe herding.' },
  ],
  summary: [
    { title: '1. Intensive Agriculture', intro: 'The main intensive types are the following:',
      items: [['Market gardening:', 'It is growing vegetables and fruits for nearby towns, as around big cities and in the Netherlands.'],
        ['Mixed farming:', 'It is growing crops and rearing animals on the same farm, as in Western Europe.'],
        ['Dairy farming:', 'It is rearing cows for milk, as in the Netherlands and Denmark.'],
        ['Viticulture:', 'It is growing grapes, as in France and Italy.'],
        ['Plantation farming:', 'It is growing one cash crop on a large estate, as oil palm in Cameroon.']] },
    { title: '2. Extensive Agriculture', intro: 'The main extensive types are the following:',
      items: [['Shifting cultivation:', 'Farmers clear a plot, farm it and move on, as in the Congo Basin.'],
        ['Bush fallowing:', 'Farmers leave land to rest and return to it later, as in West Africa.'],
        ['Pastoral nomadism:', 'Herders move with animals to find grass and water, as in the Sahel.'],
        ['Ranching and grain farming:', 'Large farms rear cattle or grow wheat, as in Argentina and Canada.']],
      draw: { img: 'agri_types_big.png', caption: 'types of agriculture' } },
  ],
  evaluation: [['Define market gardening.', 'Growing vegetables and fruits for nearby towns.'], ['Where is pastoral nomadism practised?', 'In the Sahel (also East Africa).']],
  remediation: ['Growing grapes is ______.', 'Leaving land to rest is bush ______.', 'A large farm with one cash crop is a ______.'],
  remediationAnswers: '1. viticulture 2. fallowing 3. plantation',
  homework: 'Name one type of intensive and one type of extensive farming practised in Cameroon and where.',
  hwAnswer: 'Intensive: market gardening around Garoua and Yaoundé (or plantations near Limbe). Extensive: pastoral nomadism in the Far North (or shifting cultivation in the South).',
  bilingual: [['Market gardening', 'Le maraîchage'], ['Dairy', 'La laiterie'], ['Plantation', 'La plantation'], ['Ranch', 'Le ranch'], ['Nomadism', 'Le nomadisme'], ['Vine', 'La vigne']],
});

L.push({ no: 29, title: 'The Green Revolution', subtopic: 'Agriculture as an Economic Activity of the Primary Sector',
  notions: 'Green Revolution, high-yielding varieties, fertiliser, irrigation.',
  focus: 'Meaning and aspects; significance; weaknesses.',
  competence: 'Learners are able to explain the Green Revolution and judge its effects.',
  objectives: ['Define the Green Revolution and its aspects.', 'Explain its significance.', 'Explain its weaknesses.'],
  recall: ['Population grows quickly.', 'Farmers need more food.', 'Fertilisers increase yields.'],
  situation: 'In the 1960s, India faced famine. Farmers began to use new rice and wheat seeds, fertilisers and irrigation. Within a few years, India produced enough food to feed its people.',
  sitQA: [['What is the problem in the situation?', 'India needed more food.'], ['What did farmers use?', 'New seeds, fertilisers and irrigation.'], ['What was the result?', 'Food production increased.']],
  justification: 'This lesson helps us to understand how science increased food production.',
  action: 'Use improved seeds carefully and protect the environment.',
  activities: [
    { sec: '1. MEANING', img: 'green_rev_big.png', caption: 'The Green Revolution.', q: 'What is the Green Revolution?', a: 'The great increase in food production since the 1960s thanks to new seeds, fertilisers and irrigation.', noProj: 'explain the name.' },
    { sec: '1. ASPECTS', img: 'f4_ricefield.jpg', caption: 'Rice harvest.', q: 'Name three aspects of the Green Revolution.', a: 'High-yielding seeds, fertilisers and pesticides, and irrigation (also machines).', noProj: 'list inputs.' },
    { sec: '2. SIGNIFICANCE', img: 'cereal_yield_big.png', caption: 'Cereal yields.', q: 'Give two positive effects.', a: 'Yields doubled or tripled and famine was reduced in Asia.', noProj: 'read the graph.' },
    { sec: '3. WEAKNESSES', img: 'usa_spraying.jpg', caption: 'Spraying chemicals.', q: 'Give two weaknesses.', a: 'Costly inputs that poor farmers cannot buy and pollution by chemicals.', noProj: 'discuss chemicals.' },
    { sec: '3. AFRICA', img: 'f2t_field_trial.jpg', caption: 'A field trial of improved seeds.', q: 'Why did the Green Revolution have less success in Africa?', a: 'Many crops were not improved, irrigation is limited and inputs are costly.', noProj: 'discuss IRAD seeds.' },
  ],
  summary: [
    D([['Green Revolution:', 'It is the great increase in food production since the 1960s through science and new inputs.']]),
    { title: '1. Aspects', intro: 'The Green Revolution has the following aspects:',
      items: [['High-yielding varieties:', 'New seeds of rice, wheat and maize give much higher yields.'],
        ['Fertilisers and pesticides:', 'Chemicals feed the crops and kill pests.'],
        ['Irrigation and machines:', 'Water and machines allow two or three harvests a year.']],
      draw: { img: 'green_rev_big.png', caption: 'the Green Revolution' } },
    { title: '2. Significance', intro: 'The Green Revolution has the following significance:',
      items: [['Food production:', 'Yields doubled or tripled in India, Mexico and the Philippines.'],
        ['Famine:', 'It reduced hunger and famine in Asia.']] },
    { title: '3. Weaknesses', intro: 'The Green Revolution has the following weaknesses:',
      items: [['Cost:', 'Inputs are costly, so rich farmers gain more than poor ones.'],
        ['Environment:', 'Chemicals pollute soils and water, and irrigation overuses water.'],
        ['Africa:', 'It had limited success in Africa.']] },
  ],
  evaluation: [['Give three aspects of the Green Revolution.', 'New seeds, fertilisers and irrigation.'], ['Give one weakness.', 'Inputs are costly.']],
  remediation: ['New seeds giving more food are high-______ varieties.', 'The Green Revolution began in the ______.', 'Chemicals can ______ the environment.'],
  remediationAnswers: '1. yielding 2. 1960s 3. pollute',
  homework: 'Ask a farmer whether he uses improved seeds or fertilisers and what results he gets.',
  hwAnswer: 'Answers vary. Example: a farmer uses improved maize seeds and NPK fertiliser; his harvest rose from 1 to 3 tonnes per hectare, but the inputs are expensive.',
  bilingual: [['Yield', 'Le rendement'], ['Seed', 'La semence'], ['Fertiliser', "L'engrais"], ['Pesticide', 'Le pesticide'], ['Irrigation', "L'irrigation"], ['Famine', 'La famine']],
});

L.push({ no: 30, title: 'The Impact of Agriculture', subtopic: 'Agriculture as an Economic Activity of the Primary Sector',
  notions: 'Employment, Gross Domestic Product (GDP), pollution.',
  focus: 'Impact on the economy; impact on the environment (long and short term effects).',
  competence: 'Learners are able to explain the positive and negative impacts of agriculture.',
  objectives: ['Explain the impact of agriculture on the economy.', 'Explain its impact on the environment.', 'Distinguish short-term and long-term effects.'],
  recall: ['Most Cameroonians are farmers.', 'Cameroon exports cocoa and cotton.', 'Chemicals can pollute water.'],
  situation: 'Agriculture employs most people in Cameroon and brings money from cocoa and cotton exports. But bush fires, clearing and chemicals damage soils, forests and rivers.',
  sitQA: [['What is the problem in the situation?', 'Agriculture has both good and bad effects.'], ['Give one positive effect.', 'It employs many people (also brings export money).'], ['Give one negative effect.', 'Chemicals pollute rivers (also deforestation).']],
  justification: 'This lesson helps us to weigh the benefits and costs of agriculture.',
  action: 'Farm in ways that protect the environment.',
  activities: [
    { sec: '1. ON THE ECONOMY', img: 'f2t_cotton_harvest.jpg', caption: 'Cotton harvest.', q: 'Give two impacts of agriculture on the economy.', a: 'It employs most people and brings foreign currency from exports.', noProj: 'list exports.' },
    { sec: '1. ON THE ECONOMY', img: 'f2t_brewery.jpg', caption: 'A factory processing farm products.', q: 'How does agriculture help industry?', a: 'It gives raw materials to industries such as textiles, breweries and oil mills.', noProj: 'name agro-industries.' },
    { sec: '2. SHORT-TERM ENVIRONMENTAL EFFECTS', img: 'usa_spraying.jpg', caption: 'Spraying pesticides.', q: 'Give two short-term effects on the environment.', a: 'Water pollution by chemicals and smoke from bush fires.', noProj: 'discuss.' },
    { sec: '2. LONG-TERM ENVIRONMENTAL EFFECTS', img: 'f4_gully.jpg', caption: 'Soil erosion.', q: 'Give two long-term effects.', a: 'Soil erosion and deforestation (also loss of biodiversity, desertification).', noProj: 'discuss.' },
    { sec: '2. POSITIVE EFFECTS', img: 'agri_impacts_big.png', caption: 'Impacts of agriculture.', q: 'Give one positive effect of agriculture on the environment.', a: 'Terraces and agroforestry protect the soil and landscapes.', noProj: 'read the table.' },
  ],
  summary: [
    { title: '1. Impact on the Economy', intro: 'Agriculture affects the economy as follows:',
      items: [['Employment:', 'It employs most of the working population of Cameroon.'],
        ['GDP and exports:', 'It contributes to the Gross Domestic Product and brings foreign currency from cocoa, coffee and cotton.'],
        ['Food and industry:', 'It feeds the population and supplies raw materials to industries.']] },
    { title: '2. Impact on the Environment', intro: 'Agriculture affects the environment as follows:',
      items: [['Short-term effects:', 'Chemicals pollute water and bush fires pollute the air.'],
        ['Long-term effects:', 'Deforestation, soil erosion, desertification and loss of biodiversity occur.'],
        ['Positive effects:', 'Terraces, agroforestry and organic farming protect the land.']],
      draw: { img: 'agri_impacts_big.png', caption: 'impacts of agriculture' } },
  ],
  evaluation: [['Give two positive impacts of agriculture on the economy.', 'Employment and exports.'], ['Give two long-term negative effects on the environment.', 'Soil erosion and deforestation.']],
  remediation: ['The total value of goods and services of a country is the ______.', 'Chemicals can ______ rivers.', 'Clearing forests for farms causes ______.'],
  remediationAnswers: '1. GDP 2. pollute 3. deforestation',
  homework: 'Write one positive and one negative impact of farming in your area.',
  hwAnswer: 'Positive: farming gives food and income to families. Negative: bush fires and clearing cause soil erosion.',
  bilingual: [['Impact', "L'impact"], ['Employment', "L'emploi"], ['Export', "L'exportation"], ['Pollution', 'La pollution'], ['Erosion', "L'érosion"], ['Economy', "L'économie"]],
});

L.push({ no: 31, title: 'Sustainable Agriculture', subtopic: 'Agriculture as an Economic Activity of the Primary Sector',
  notions: 'Sustainable agriculture, crop rotation, agro-forestry, cover cropping, controlled grazing.',
  focus: 'Meaning and aims; sustainable agricultural practices; importance.',
  competence: 'Learners are able to propose sustainable agricultural practices.',
  objectives: ['Define sustainable agriculture and its aims.', 'Describe sustainable agricultural practices.', 'Explain its importance.'],
  recall: ['Agriculture can damage the environment.', 'Soil can be conserved.', 'Development must be sustainable.'],
  situation: 'A farmer near Guider plants trees among his crops, changes crops each year and uses manure from his cattle instead of chemicals. His soil stays fertile year after year.',
  sitQA: [['What is the problem in the situation?', 'The farmer wants to farm without damaging the soil.'], ['Name two practices he uses.', 'Crop rotation and manure (also trees among crops).'], ['What is the result?', 'His soil stays fertile.']],
  justification: 'This lesson helps us to farm without destroying the land.',
  action: 'Use manure, crop rotation and trees on farms.',
  activities: [
    { sec: '1. MEANING', img: 'usa_organic.jpg', caption: 'An organic garden.', q: 'What is sustainable agriculture?', a: 'Farming that produces food today while protecting soils, water and biodiversity for the future.', noProj: 'discuss.' },
    { sec: '2. CROP ROTATION', img: 'f2t_mixed_farm.jpg', caption: 'A mixed farm.', q: 'What is crop rotation and why is it useful?', a: 'Changing crops on the same land each year; it keeps the soil fertile and reduces pests.', noProj: 'plan a rotation.' },
    { sec: '2. AGRO-FORESTRY', img: 'f2t_shea_tree.jpg', caption: 'Trees in farmland.', q: 'What is agro-forestry?', a: 'Growing trees together with crops or animals.', noProj: 'name useful farm trees.' },
    { sec: '2. COVER CROPS AND GRAZING', img: 'f4_terraces.jpg', caption: 'Terraces.', q: 'How do cover crops and controlled grazing help?', a: 'Cover crops protect the soil; controlled grazing prevents overgrazing.', noProj: 'discuss.' },
    { sec: '3. IMPORTANCE', img: 'soil_conservation_big.png', caption: 'Soil conservation.', q: 'Give two reasons why sustainable agriculture is important.', a: 'It keeps the soil fertile for future generations and reduces pollution.', noProj: 'list reasons.' },
  ],
  summary: [
    D([['Sustainable agriculture:', 'It is farming that meets present needs while protecting the environment for the future.']]),
    { title: '1. Aims', intro: 'Sustainable agriculture has the following aims:',
      items: [['Food security:', 'It produces enough food for everyone.'],
        ['Environment:', 'It protects soils, water, forests and biodiversity.'],
        ['Income:', 'It gives farmers a fair and lasting income.']] },
    { title: '2. Sustainable Agricultural Practices', intro: 'Farmers use the following practices:',
      items: [['Crop rotation:', 'Changing crops each year keeps the soil fertile.'],
        ['Agro-forestry:', 'Trees grown with crops protect and enrich the soil.'],
        ['Cover cropping and mulching:', 'Plants and dead leaves cover the soil against erosion.'],
        ['Controlled grazing and manure:', 'Limiting animals and using manure protect and feed the soil.']],
      draw: { img: 'soil_conservation_big.png', caption: 'sustainable practices' } },
  ],
  evaluation: [['Define sustainable agriculture.', 'Farming that protects the environment for the future.'], ['Give three sustainable practices.', 'Crop rotation, agro-forestry and cover cropping.']],
  remediation: ['Changing crops each year is crop ______.', 'Growing trees with crops is ______.', 'Using animal waste to feed the soil is using ______.'],
  remediationAnswers: '1. rotation 2. agro-forestry 3. manure',
  homework: 'Propose a crop rotation plan for three years on a farm in your area.',
  hwAnswer: 'Example: year 1 – maize; year 2 – groundnuts or beans (which enrich the soil); year 3 – cotton or sorghum; then start again.',
  bilingual: [['Sustainable', 'Durable'], ['Rotation', "L'assolement"], ['Agro-forestry', "L'agroforesterie"], ['Manure', 'Le fumier'], ['Cover crop', 'La culture de couverture'], ['Grazing', 'Le pâturage']],
});

L.push({ no: 32, title: 'Climate-Smart Agriculture', subtopic: 'Agriculture as an Economic Activity of the Primary Sector',
  notions: 'Climate-smart agriculture, mulching, water management, shade house, intercropping, improved grazing.',
  focus: 'Meaning; aims (main pillars); practical techniques.',
  competence: 'Learners are able to explain climate-smart agriculture and apply its techniques.',
  objectives: ['Define climate-smart agriculture.', 'State its three pillars.', 'Describe its practical techniques.'],
  recall: ['The climate is changing.', 'Rains are irregular in the north.', 'Sustainable agriculture protects the soil.'],
  situation: 'Because the rains now start late in the Far North, some farmers dig zaï pits, cover the soil with straw and plant drought-resistant sorghum. Their harvests are better than their neighbours\'.',
  sitQA: [['What is the problem in the situation?', 'Farmers must adapt to irregular rains.'], ['Name two techniques they use.', 'Zaï pits and mulching (also drought-resistant seeds).'], ['What is the result?', 'Better harvests.']],
  justification: 'This lesson helps farmers to adapt to climate change.',
  action: 'Use mulching, water harvesting and resistant seeds on farms.',
  activities: [
    { sec: '1. MEANING', img: 'f4_zai.jpg', caption: 'Farmers digging zaï pits.', q: 'What is climate-smart agriculture?', a: 'Farming that increases production, adapts to climate change and reduces greenhouse gases.', noProj: 'discuss.' },
    { sec: '2. PILLARS', img: 'mit_adapt_big.png', caption: 'Mitigation and adaptation.', q: 'Name the three pillars of climate-smart agriculture.', a: 'Increase productivity, adapt to climate change and reduce emissions (mitigation).', noProj: 'draw three pillars.' },
    { sec: '3. MULCHING AND WATER', img: 'lsa_litter.jpg', caption: 'Mulch covering the soil.', q: 'How do mulching and water harvesting help?', a: 'They keep moisture in the soil and save water.', noProj: 'mulch a garden bed.' },
    { sec: '3. INTERCROPPING', img: 'f2t_cassava_farm.jpg', caption: 'Mixed crops.', q: 'What is intercropping and why is it smart?', a: 'Growing two or more crops together; it reduces risk and covers the soil.', noProj: 'describe mixed fields.' },
    { sec: '3. SHADE HOUSES AND GRAZING', img: 'usa_greenhouse.jpg', caption: 'A covered garden.', q: 'How do shade houses and improved grazing help?', a: 'Shade houses protect plants from heat; improved grazing keeps pastures healthy.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Climate-smart agriculture:', 'It is farming that raises production, adapts to climate change and reduces greenhouse gases.']]),
    { title: '1. Aims (Main Pillars)', intro: 'Climate-smart agriculture has three pillars:',
      items: [['Productivity:', 'It increases yields and farmers\' incomes.'],
        ['Adaptation:', 'It helps farms resist droughts, floods and heat.'],
        ['Mitigation:', 'It reduces greenhouse gas emissions from farming.']] },
    { title: '2. Practical Techniques', intro: 'Farmers use the following techniques:',
      items: [['Mulching:', 'Covering the soil keeps it moist and cool.'],
        ['Water management:', 'Zaï pits, water harvesting and drip irrigation save water.'],
        ['Intercropping and resistant seeds:', 'Mixed crops and drought-resistant varieties reduce risk.'],
        ['Shade houses and improved grazing:', 'They protect plants from heat and keep pastures healthy.']],
      draw: { img: 'mit_adapt_big.png', caption: 'adaptation and mitigation' } },
  ],
  evaluation: [['Name the three pillars of climate-smart agriculture.', 'Productivity, adaptation and mitigation.'], ['Give two techniques.', 'Mulching and zaï pits.']],
  remediation: ['Covering the soil with straw is ______.', 'Growing crops together is ______.', 'Reducing greenhouse gases is ______.'],
  remediationAnswers: '1. mulching 2. intercropping 3. mitigation',
  homework: 'Propose three climate-smart techniques for a farm near Garoua.',
  hwAnswer: 'Plant drought-resistant sorghum, dig zaï pits or contour ridges to catch rain, and mulch the soil with crop residues.',
  bilingual: [['Climate', 'Le climat'], ['Drought', 'La sécheresse'], ['Mulch', 'Le paillis'], ['Water harvesting', "La collecte de l'eau"], ['Adaptation', "L'adaptation"], ['Resistant', 'Résistant']],
});

L.push({ no: 33, title: "Spatial Patterns of Agriculture: Von Thünen's Model of Agricultural Land Use", subtopic: 'Agriculture as an Economic Activity of the Primary Sector',
  notions: 'Land use pattern, locational rent, isolated state.',
  focus: 'Principle (locational rent); three main assumptions; conclusions and spatial outcome diagram; some areas where applicable.',
  competence: 'Learners are able to explain Von Thünen\'s model and apply it to real areas.',
  objectives: ['State the principle of locational rent.', 'Give the main assumptions of the model.', 'Draw the spatial outcome and give examples.'],
  recall: ['Farmers sell in town markets.', 'Transport costs money.', 'Some products spoil quickly.'],
  situation: 'Around Garoua, vegetable gardens are close to the town, maize fields are farther away and cattle graze far out in the bush. Rachid asks why farming is organised like this.',
  sitQA: [['What is the problem in the situation?', 'We want to explain the pattern of farming around a town.'], ['What is closest to the town?', 'Vegetable gardens.'], ['What is farthest?', 'Cattle grazing.']],
  justification: 'This lesson helps us to understand why farming changes with distance from the market.',
  action: 'Observe how land use changes around your town.',
  activities: [
    { sec: '1. PRINCIPLE', img: 'rent_curves_big.png', caption: 'Locational rent curves.', q: 'What is locational rent?', a: 'The profit from a piece of land after production and transport costs; it falls with distance from the market.', noProj: 'explain with an example.' },
    { sec: '2. ASSUMPTIONS', img: 'vonthunen_big.png', caption: "Von Thünen's model.", q: 'Give three assumptions of the model.', a: 'An isolated state with one central market, flat land of equal fertility, and transport costs that rise with distance.', noProj: 'list assumptions.' },
    { sec: '3. SPATIAL OUTCOME', img: 'vonthunen_big.png', caption: 'The rings of land use.', q: 'Name the four rings from the centre.', a: 'Market gardening and dairy, forestry, arable crops, livestock ranching.', noProj: 'draw the rings.' },
    { sec: '3. CONCLUSION', img: 'f2t_market.jpg', caption: 'A town market.', q: 'Why are vegetables grown near the town?', a: 'They are perishable and heavy to transport, so they give high rent near the market.', noProj: 'discuss vegetables of Garoua.' },
    { sec: '4. APPLICATION', img: 'farm_distance_big.png', caption: 'Farm intensity and distance.', q: 'Where can the model be applied?', a: 'Around towns in Africa, such as Garoua, and around villages (farm intensity falls with distance).', noProj: 'map farming around Garoua.' },
  ],
  summary: [
    D([['Locational rent:', 'It is the profit from land after production and transport costs are paid.']]),
    { title: '1. Principle and Assumptions', intro: 'Von Thünen (1826) based his model on the following ideas:',
      items: [['Principle:', 'Locational rent falls as the distance from the market increases.'],
        ['Isolated state:', 'There is one central market town and no trade with the outside.'],
        ['Uniform land:', 'The land is flat and equally fertile everywhere.'],
        ['Transport:', 'Transport costs rise with distance and farmers seek maximum profit.']] },
    { title: '2. Conclusions and Spatial Outcome', intro: 'Land use forms rings around the market:',
      items: [['Ring 1:', 'Market gardening and dairy farming near the town.'],
        ['Ring 2:', 'Forestry for firewood and timber.'],
        ['Ring 3:', 'Arable crops such as cereals.'],
        ['Ring 4:', 'Livestock ranching far from the town.']],
      draw: { img: 'vonthunen_big.png', caption: "Von Thünen's rings" } },
    { title: '3. Areas where Applicable', intro: 'The model applies in the following areas:',
      items: [['Examples:', 'Rings of land use can be seen around African towns such as Garoua and around villages.']] },
  ],
  evaluation: [['What is locational rent?', 'Profit from land after production and transport costs.'], ['Name the four rings of Von Thünen\'s model.', 'Market gardening/dairy, forestry, arable, ranching.']],
  remediation: ['Von Thünen\'s model has ______ rings.', 'The first ring is market ______.', 'Rent ______ with distance from the market.'],
  remediationAnswers: '1. four 2. gardening 3. falls',
  homework: 'Draw the land use around your town or village and compare it with Von Thünen\'s rings.',
  hwAnswer: 'Around Garoua: vegetable gardens and dairy near town, then maize and cotton fields, then bush pasture for cattle — similar to Von Thünen, though rivers and roads distort the rings.',
  bilingual: [['Land use', "L'utilisation du sol"], ['Rent', 'La rente'], ['Ring', "L'anneau"], ['Market', 'Le marché'], ['Distance', 'La distance'], ['Model', 'Le modèle']],
});

L.push({ no: 34, title: 'Arable Agriculture in Cameroon', subtopic: 'The Economic Development Potentials of Cameroon in the Primary Sector: Agriculture',
  notions: 'Food crops, cash crops, subsistence farming, commercial farming.',
  focus: 'Subsistence and commercial farming.',
  competence: 'Learners are able to describe arable farming in Cameroon and locate its main crops.',
  objectives: ['Describe subsistence farming in Cameroon.', 'Describe commercial farming in Cameroon.', 'Locate the main crops.'],
  recall: ['Cameroon has forest and savanna regions.', 'Farmers grow food crops and cash crops.', 'Cocoa grows in the south and cotton in the north.'],
  situation: 'In the South, farmers grow cassava and plantains for the family and cocoa for sale. In the North, farmers grow sorghum and maize to eat and cotton to sell to SODECOTON.',
  sitQA: [['What is the problem in the situation?', 'We want to describe arable farming in Cameroon.'], ['Name two food crops.', 'Cassava and sorghum (also plantains, maize).'], ['Name two cash crops.', 'Cocoa and cotton.']],
  justification: 'This lesson helps us to know the farming that feeds Cameroon.',
  action: 'Support local farmers by buying local food.',
  activities: [
    { sec: '1. SUBSISTENCE FARMING', img: 'f2t_cassava_farm.jpg', caption: 'A food crop farm.', q: 'What is subsistence farming? Name three food crops of Cameroon.', a: 'Farming to feed the family; cassava, maize and sorghum (also plantains, yams).', noProj: 'list foods.' },
    { sec: '1. SUBSISTENCE FARMING', img: 'f2t_maize.jpg', caption: 'Maize.', q: 'Give two characteristics of subsistence farming.', a: 'Small farms and simple tools with family labour.', noProj: 'describe family farms.' },
    { sec: '2. COMMERCIAL FARMING', img: 'usa_cocoa.jpg', caption: 'Drying cocoa.', q: 'What is commercial farming? Name three cash crops.', a: 'Farming for sale; cocoa, coffee and cotton (also bananas, oil palm, rubber).', noProj: 'list exports.' },
    { sec: '2. PLANTATIONS', img: 'usa_banana.jpg', caption: 'A banana plantation.', q: 'Name two agro-industrial companies of Cameroon.', a: 'The CDC and SODECOTON (also SOCAPALM, SOSUCAM).', noProj: 'name companies.' },
    { sec: '3. DISTRIBUTION', img: 'cmr_agri_big.png', caption: 'Farming regions of Cameroon.', q: 'Where are cocoa, coffee and cotton grown?', a: 'Cocoa in the Centre and South; arabica coffee in the West; cotton in the North and Far North.', noProj: 'use the map.' },
  ],
  summary: [
    { title: '1. Subsistence Farming', intro: 'Subsistence farming in Cameroon has the following characteristics:',
      items: [['Purpose:', 'Farmers grow food mainly to feed their families.'],
        ['Crops:', 'They grow cassava, plantains and cocoyams in the south and sorghum, millet and maize in the north.'],
        ['Methods:', 'Farms are small, with hoes, family labour and bush fallowing.']] },
    { title: '2. Commercial Farming', intro: 'Commercial farming in Cameroon has the following characteristics:',
      items: [['Small-holder cash crops:', 'Farmers grow cocoa, coffee and cotton for sale.'],
        ['Plantations:', 'Agro-industries such as the CDC, SOCAPALM and SOSUCAM grow bananas, oil palm, rubber and sugar cane.'],
        ['Distribution:', 'Cocoa grows in the Centre and South, coffee in the West and cotton in the North.']],
      draw: { img: 'cmr_agri_big.png', caption: 'farming regions of Cameroon' } },
  ],
  evaluation: [['Distinguish subsistence and commercial farming.', 'Subsistence feeds the family; commercial farming sells the produce.'], ['Where is cotton grown?', 'In the North and Far North.']],
  remediation: ['Farming to feed the family is ______ farming.', 'Cotton is bought by ______.', 'Arabica coffee is grown in the ______ Region.'],
  remediationAnswers: '1. subsistence 2. SODECOTON 3. West',
  homework: 'List the food crops and cash crops grown in your region.',
  hwAnswer: 'North Region: food crops – maize, sorghum, millet, groundnuts, onions; cash crops – cotton (also rice and onions sold).',
  bilingual: [['Food crop', 'La culture vivrière'], ['Cash crop', 'La culture de rente'], ['Cassava', 'Le manioc'], ['Cocoa', 'Le cacao'], ['Coffee', 'Le café'], ['Cotton', 'Le coton']],
});

L.push({ no: 35, title: 'Pastoral Agriculture in Cameroon', subtopic: 'The Economic Development Potentials of Cameroon in the Primary Sector: Agriculture',
  notions: 'Pastoral farming, pastoral nomadism, transhumance, ranching.',
  focus: 'Pastoral nomadism; ranching.',
  competence: 'Learners are able to describe pastoral farming in Cameroon.',
  objectives: ['Describe pastoral nomadism and transhumance in Cameroon.', 'Describe ranching in Cameroon.', 'Explain the problems of pastoral farming.'],
  recall: ['Herders rear cattle in the North.', 'Nomads move with animals.', 'The Adamawa Plateau has good pasture.'],
  situation: 'In the dry season, Mbororo herders leave the Far North with their cattle and walk south towards the Benue valley. On the Adamawa Plateau, the SODEPA ranch keeps cattle in fenced pastures.',
  sitQA: [['What is the problem in the situation?', 'We want to know how cattle are reared in Cameroon.'], ['Why do herders move south in the dry season?', 'To find grass and water.'], ['What is a ranch?', 'A large fenced farm for rearing animals.']],
  justification: 'This lesson helps us to understand livestock farming in northern Cameroon.',
  action: 'Respect grazing corridors and farm boundaries.',
  activities: [
    { sec: '1. PASTORAL NOMADISM', img: 'usa_nomad.jpg', caption: 'A nomadic camp.', q: 'What is pastoral nomadism?', a: 'Moving with animals from place to place to find grass and water.', noProj: 'describe nomads.' },
    { sec: '1. TRANSHUMANCE', img: 'transhumance.gif', caption: 'Animation: seasonal movement of herds.', q: 'What is transhumance?', a: 'Seasonal movement of herds between dry-season and wet-season pastures.', noProj: 'draw the route.' },
    { sec: '2. RANCHING', img: 'f2t_ranch.jpg', caption: 'Cattle on a ranch.', q: 'What is ranching? Where is it practised in Cameroon?', a: 'Rearing animals on a large fenced farm; on the Adamawa Plateau (SODEPA ranches).', noProj: 'describe a ranch.' },
    { sec: '3. IMPORTANCE', img: 'f2t_cattle_market.jpg', caption: 'A cattle market.', q: 'Give two importance of livestock farming.', a: 'Meat and milk for people, and income from sales to towns and neighbouring countries.', noProj: 'describe the cattle market.' },
    { sec: '3. PROBLEMS', img: 'f2t_cattle_field.jpg', caption: 'Cattle near farms.', q: 'Give two problems of pastoral farming.', a: 'Farmer–herder conflicts and animal diseases (also drought, cattle theft).', noProj: 'discuss conflicts.' },
  ],
  summary: [
    D([['Pastoral farming:', 'It is the rearing of animals such as cattle, sheep and goats.']]),
    { title: '1. Pastoral Nomadism and Transhumance', intro: 'Traditional herding in Cameroon is organised as follows:',
      items: [['Nomadism:', 'Herders such as the Mbororo move with their animals to find grass and water.'],
        ['Transhumance:', 'Herds move south to river valleys in the dry season and return north in the rainy season.']] },
    { title: '2. Ranching', intro: 'Modern ranching in Cameroon has the following characteristics:',
      items: [['Location:', 'Ranches are found on the Adamawa Plateau and in the North-West.'],
        ['Methods:', 'Animals are kept in fenced pastures, vaccinated and fed improved grass.']] },
    { title: '3. Importance and Problems', intro: 'Pastoral farming has the following importance and problems:',
      items: [['Importance:', 'It gives meat, milk, hides and income, and cattle are sold to Nigeria and Gabon.'],
        ['Problems:', 'Drought, animal diseases, cattle theft and farmer–herder conflicts reduce production.']] },
  ],
  evaluation: [['Distinguish nomadism and ranching.', 'Nomadism moves with herds; ranching keeps them on fenced farms.'], ['Give two problems of pastoral farming.', 'Diseases and farmer–herder conflicts.']],
  remediation: ['Seasonal movement of herds is ______.', 'A large fenced farm for animals is a ______.', 'Ranches are found on the ______ Plateau.'],
  remediationAnswers: '1. transhumance 2. ranch 3. Adamawa',
  homework: 'Propose two solutions to farmer–herder conflicts in the North.',
  hwAnswer: 'Create and mark grazing corridors and zones; set up local committees of farmers and herders to settle disputes.',
  bilingual: [['Herder', "L'éleveur"], ['Cattle', 'Le bétail'], ['Ranch', 'Le ranch'], ['Pasture', 'Le pâturage'], ['Transhumance', 'La transhumance'], ['Conflict', 'Le conflit']],
});

L.push({ no: 36, title: 'The Impact of Agriculture on the Economy of Cameroon', subtopic: 'The Economic Development Potentials of Cameroon in the Primary Sector: Agriculture',
  notions: 'Short-term effects, long-term effects, GDP, exports.',
  focus: 'Short-term effects; long-term effects.',
  competence: 'Learners are able to explain the importance of agriculture for the economy of Cameroon.',
  objectives: ['Explain the short-term effects of agriculture on the economy.', 'Explain its long-term effects.', 'Propose ways to increase its benefits.'],
  recall: ['Agriculture employs most Cameroonians.', 'Cameroon exports cocoa, coffee and cotton.', 'Agro-industries use farm products.'],
  situation: 'When the price of cocoa rose, cocoa farmers in the Centre built houses and sent their children to school. When it fell, many could not pay school fees.',
  sitQA: [['What is the problem in the situation?', 'Farm incomes depend on world prices.'], ['What happened when the price rose?', 'Farmers built houses and paid school fees.'], ['What happened when it fell?', 'Many could not pay school fees.']],
  justification: 'This lesson helps us to see how agriculture drives the economy of Cameroon.',
  action: 'Support the local processing of farm products.',
  activities: [
    { sec: '1. SHORT-TERM EFFECTS', img: 'f2t_market.jpg', caption: 'A food market.', q: 'Give two short-term effects of agriculture on the economy.', a: 'It feeds the population and gives daily income to farmers and traders.', noProj: 'discuss.' },
    { sec: '1. SHORT-TERM EFFECTS', img: 'cmr_trade_big.png', caption: 'Exports of Cameroon.', q: 'Which farm products does Cameroon export?', a: 'Cocoa, coffee, cotton, bananas and timber.', noProj: 'read the chart.' },
    { sec: '2. LONG-TERM EFFECTS', img: 'f2t_brewery.jpg', caption: 'A factory.', q: 'How does agriculture help industry in the long term?', a: 'It supplies raw materials to agro-industries such as textiles, breweries and oil mills.', noProj: 'name agro-industries.' },
    { sec: '2. LONG-TERM EFFECTS', img: 'f2t_muddy_road.jpg', caption: 'A rural road.', q: 'How does agriculture help rural development?', a: 'Farm incomes and agro-industries lead to roads, schools and health centres.', noProj: 'discuss.' },
    { sec: '3. LIMITS', img: 'usa_sacks.jpg', caption: 'Sacks of raw cocoa.', q: 'Why is dependence on raw exports a problem?', a: 'World prices change often, so farmers\' incomes are unstable.', noProj: 'discuss price changes.' },
  ],
  summary: [
    { title: '1. Short-term Effects', intro: 'Agriculture has the following short-term effects on the economy:',
      items: [['Food supply:', 'It feeds the population and reduces food imports.'],
        ['Income and jobs:', 'It gives jobs and daily income to most rural people.'],
        ['Exports:', 'Cocoa, coffee, cotton and bananas bring foreign currency.']],
      draw: { img: 'cmr_trade_big.png', caption: 'exports of Cameroon' } },
    { title: '2. Long-term Effects', intro: 'Agriculture has the following long-term effects:',
      items: [['Industrialisation:', 'It supplies raw materials to agro-industries.'],
        ['Rural development:', 'It helps to build roads, schools and health centres.'],
        ['Limits:', 'Dependence on raw exports makes incomes unstable when world prices fall.']] },
  ],
  evaluation: [['Give two short-term effects of agriculture on the economy.', 'Food supply and income.'], ['Give one long-term effect.', 'Raw materials for agro-industries.']],
  remediation: ['Money from exports is foreign ______.', 'Factories that process farm products are ______.', 'Cocoa prices depend on the ______ market.'],
  remediationAnswers: '1. currency 2. agro-industries 3. world',
  homework: 'Name three factories in Cameroon that use farm products and their raw materials.',
  hwAnswer: 'CICAM (cotton → cloth), SABC (maize and sorghum → drinks), SOSUCAM (sugar cane → sugar) (also SOCAPALM: palm oil).',
  bilingual: [['Economy', "L'économie"], ['Export', "L'exportation"], ['Price', 'Le prix'], ['Agro-industry', "L'agro-industrie"], ['Income', 'Le revenu'], ['Development', 'Le développement']],
});

L.push({ no: 37, title: 'Food Loss and Food Waste', subtopic: 'The Economic Development Potentials of Cameroon in the Primary Sector: Agriculture',
  notions: 'Food loss, food waste, production waste, retail waste.',
  focus: 'Definitions; causes; consequences; solutions.',
  competence: 'Learners are able to explain food loss and waste and act to reduce them.',
  objectives: ['Define food loss and food waste.', 'Explain their causes and consequences.', 'Propose solutions.'],
  recall: ['Farmers harvest crops.', 'Food is sold in markets.', 'Some food rots before it is eaten.'],
  situation: 'After the harvest, tomatoes rot in a village near Garoua because the road is bad and there is no storage. In town, families throw away leftover food.',
  sitQA: [['What is the problem in the situation?', 'Food is lost and wasted.'], ['Why do tomatoes rot in the village?', 'Bad roads and no storage.'], ['What do families in town throw away?', 'Leftover food.']],
  justification: 'This lesson helps us to save food and money.',
  action: 'Buy only what you need and store food well.',
  activities: [
    { sec: '1. DEFINITIONS', img: 'food_solutions_big.png', caption: 'Solutions to food problems.', q: 'Distinguish food loss and food waste.', a: 'Food loss happens during harvest, storage and transport; food waste happens in shops and homes.', noProj: 'give examples.' },
    { sec: '2. CAUSES OF LOSS', img: 'f2t_muddy_road.jpg', caption: 'A bad road.', q: 'Give two causes of food loss.', a: 'Poor storage and bad roads (also pests, lack of processing).', noProj: 'discuss.' },
    { sec: '2. CAUSES OF WASTE', img: 'f2t_market.jpg', caption: 'A market.', q: 'Give two causes of food waste.', a: 'Buying too much and throwing away leftovers (also food spoiling in shops).', noProj: 'discuss home habits.' },
    { sec: '3. CONSEQUENCES', img: 'usa_foodaid.jpg', caption: 'Food aid.', q: 'Give two consequences.', a: 'Hunger and loss of money (also wasted water and land, pollution).', noProj: 'discuss.' },
    { sec: '4. SOLUTIONS', img: 'usa_sacks.jpg', caption: 'Stored sacks.', q: 'Give three solutions.', a: 'Better storage and processing, good roads, and buying only what we need.', noProj: 'list actions.' },
  ],
  summary: [
    D([['Food loss:', 'It is food lost during harvest, storage, processing and transport.'],
      ['Food waste:', 'It is good food thrown away by shops, restaurants and households.']]),
    { title: '1. Causes', intro: 'Food loss and waste have the following causes:',
      items: [['Causes of loss:', 'Poor storage, pests, bad roads and lack of processing cause food loss.'],
        ['Causes of waste:', 'Buying too much, poor planning and throwing away leftovers cause food waste.']] },
    { title: '2. Consequences', intro: 'Food loss and waste have the following consequences:',
      items: [['Social consequences:', 'Hunger remains while food is thrown away.'],
        ['Economic and environmental consequences:', 'Money, water, land and energy are wasted and rotting food pollutes.']] },
    { title: '3. Solutions', intro: 'Food loss and waste can be reduced as follows:',
      items: [['Better storage and processing:', 'Granaries, drying and processing keep food longer.'],
        ['Good roads and markets:', 'They bring food quickly to consumers.'],
        ['Good habits:', 'People buy what they need and use leftovers.']],
      draw: { img: 'food_solutions_big.png', caption: 'food solutions' } },
  ],
  evaluation: [['Distinguish food loss and food waste.', 'Loss: during production and transport. Waste: in shops and homes.'], ['Give two solutions.', 'Better storage and buying only what we need.']],
  remediation: ['Food rotting in storage is food ______.', 'Food thrown away at home is food ______.', 'Drying tomatoes is a form of ______.'],
  remediationAnswers: '1. loss 2. waste 3. processing',
  homework: 'Observe food waste at home for three days and suggest how to reduce it.',
  hwAnswer: 'Answers vary. Example: leftover rice and rotten tomatoes were thrown away; solutions: cook smaller amounts, reheat leftovers, and dry or preserve tomatoes.',
  bilingual: [['Food', 'La nourriture'], ['Loss', 'La perte'], ['Waste', 'Le gaspillage'], ['Storage', 'Le stockage'], ['Leftovers', 'Les restes'], ['Hunger', 'La faim']],
});

L.push({ no: 38, title: 'Problems of Tropical Agriculture with Reference to Cameroon', subtopic: 'The Economic Development Potentials of Cameroon in the Primary Sector: Agriculture',
  notions: 'Physical problems, human problems, solutions.',
  focus: 'Physical problems and solutions; human problems and solutions.',
  competence: 'Learners are able to explain the problems of agriculture in Cameroon and propose solutions.',
  objectives: ['Explain the physical problems of tropical agriculture.', 'Explain the human problems.', 'Propose solutions to each.'],
  recall: ['Rains are irregular in the north.', 'Soils can be poor.', 'Farmers lack money for inputs.'],
  situation: 'A farmer near Maroua lost his crops to drought and locusts. He also cannot get a loan to buy fertiliser, and the road to the market is impassable in the rainy season.',
  sitQA: [['What is the problem in the situation?', 'The farmer faces many problems.'], ['Give two physical problems.', 'Drought and locusts.'], ['Give two human problems.', 'No loan and a bad road.']],
  justification: 'This lesson helps us to understand why farmers struggle and how to help them.',
  action: 'Support farmers\' cooperatives and good farming techniques.',
  activities: [
    { sec: '1. PHYSICAL PROBLEMS', img: 'f2t_drought.jpg', caption: 'Dry, cracked soil.', q: 'Give three physical problems of tropical agriculture.', a: 'Drought or irregular rain, poor leached soils and pests (also floods, erosion).', noProj: 'list problems.' },
    { sec: '1. PHYSICAL SOLUTIONS', img: 'usa_irrigation.jpg', caption: 'An irrigation canal.', q: 'Give two solutions to physical problems.', a: 'Irrigation and fertilisers (also pest control, soil conservation).', noProj: 'discuss.' },
    { sec: '2. HUMAN PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A bad rural road.', q: 'Give three human problems.', a: 'Lack of capital and credit, bad roads and poor storage (also land disputes, low prices).', noProj: 'list problems.' },
    { sec: '2. HUMAN PROBLEMS', img: 'f2t_cattle_field.jpg', caption: 'Cattle near farms.', q: 'How do farmer–herder conflicts affect agriculture?', a: 'Crops are destroyed and people are hurt or displaced.', noProj: 'discuss.' },
    { sec: '2. HUMAN SOLUTIONS', img: 'f2t_phone_farmer.jpg', caption: 'A farmer using a phone.', q: 'Give three solutions to human problems.', a: 'Credit and cooperatives, better roads and storage, and training by extension workers.', noProj: 'list solutions.' },
  ],
  summary: [
    { title: '1. Physical Problems and Solutions', intro: 'Tropical agriculture faces the following physical problems and solutions:',
      items: [['Climate:', 'Drought, irregular rain and floods destroy crops, so irrigation and resistant seeds are needed.'],
        ['Soils:', 'Leached and eroded soils are poor, so fertilisers and soil conservation are needed.'],
        ['Pests and diseases:', 'Locusts, birds and diseases attack crops and animals, so pest control and vaccination are needed.']] },
    { title: '2. Human Problems and Solutions', intro: 'Tropical agriculture faces the following human problems and solutions:',
      items: [['Capital:', 'Farmers lack money and credit, so banks and cooperatives must give loans.'],
        ['Infrastructure:', 'Bad roads and poor storage cause losses, so roads and granaries must be built.'],
        ['Techniques and training:', 'Simple tools and low training limit yields, so extension services must train farmers.'],
        ['Conflicts and land:', 'Farmer–herder conflicts and land disputes must be solved by clear rules.']] },
  ],
  evaluation: [['Give two physical problems and their solutions.', 'Drought – irrigation; poor soils – fertilisers.'], ['Give two human problems and their solutions.', 'Lack of credit – cooperatives; bad roads – road building.']],
  remediation: ['Insects that destroy crops in swarms are ______.', 'Groups of farmers working together form a ______.', 'Bringing water to crops is ______.'],
  remediationAnswers: '1. locusts 2. cooperative 3. irrigation',
  homework: 'Interview a farmer about his two main problems and propose solutions.',
  hwAnswer: 'Answers vary. Example: lack of fertiliser (solution: cooperative purchase) and cattle destroying crops (solution: grazing corridors and dialogue).',
  bilingual: [['Problem', 'Le problème'], ['Drought', 'La sécheresse'], ['Pest', 'Le ravageur'], ['Credit', 'Le crédit'], ['Cooperative', 'La coopérative'], ['Extension worker', 'Le vulgarisateur agricole']],
});

module.exports = { B, L };
