// FORM 5 — Module I (2023 syllabus), part 3: L17–L22 (trade, tourism, economic growth of Cameroon)
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F5', code: 'M1', folder: '', module: 'Module I: Management of Manufacturing and Tertiary Activities', topicDefault: 'Managing Resources for Development through Economic Activities', branch: 'Global Trade',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 5, Module I: Management of Manufacturing and Tertiary Activities.'] };
const L = [];

L.push({ no: 17, title: 'Volume of Trade', subtopic: 'Global Trade',
  notions: 'Trade, internal trade, international trade, exports, imports, trade routes.',
  focus: 'Meaning of trade; types of trade; major trade routes; global trade patterns; reasons for global trade patterns.',
  competence: 'Learners are able to explain trade, locate the major trade routes and explain global trade patterns.',
  objectives: ['Define trade and give its types.', 'Locate the major world trade routes.', 'Describe and explain global trade patterns.'],
  recall: ['Cameroon exports cocoa, coffee, timber and oil.', 'Ships carry most world trade.', 'AICs produce manufactured goods.'],
  situation: 'Cameroon sells raw cocoa to Europe at a low price and buys cars and machines at high prices. Most world trade takes place between Europe, North America and East Asia.',
  sitQA: [['What is the problem in the situation?', 'We want to understand world trade patterns.'], ['What does Cameroon export?', 'Raw materials such as cocoa.'], ['Which regions dominate world trade?', 'Europe, North America and East Asia.']],
  justification: 'This lesson helps us to understand how countries exchange goods and why some gain more.',
  action: 'Denounce unfair trade and support fair prices for producers.',
  activities: [
    { sec: '1. MEANING AND TYPES', img: 'f2t_market.jpg', caption: 'A market.', q: 'What is trade?', a: 'The buying and selling or exchange of goods and services.', noProj: 'give examples.' },
    { sec: '1. MEANING AND TYPES', img: 'usa_container.jpg', caption: 'International trade.', q: 'Distinguish internal and international trade.', a: 'Internal trade is within a country; international trade is between countries.', noProj: 'give examples.' },
    { sec: '2. MAJOR TRADE ROUTES', img: 'f2t_suez.jpg', caption: 'The Suez Canal.', q: 'Name two major world trade routes.', a: 'The North Atlantic route and the Suez Canal route (also the Panama Canal and Cape routes).', noProj: 'use the atlas.' },
    { sec: '3. GLOBAL TRADE PATTERNS', img: 'triad_big.png', caption: 'The world economic triad.', q: 'Describe the global pattern of trade.', a: 'Most trade is between AICs and East Asia, while LICs export raw materials and import manufactured goods.', noProj: 'discuss.' },
    { sec: '3. REASONS', img: 'terms_trade_big.png', caption: 'Terms of trade.', q: 'Why do AICs dominate world trade?', a: 'They export valuable manufactured goods and control transport, finance and markets.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Trade:', 'It is the buying and selling or exchange of goods and services.'],
      ['Exports and imports:', 'Exports are goods sold abroad and imports are goods bought from abroad.']]),
    { title: '1. Types of Trade', intro: 'The types of trade are the following:',
      items: [['Internal trade:', 'It takes place within a country.'],
        ['International trade:', 'It takes place between countries.'],
        ['Bilateral and multilateral trade:', 'Bilateral trade is between two countries and multilateral trade is among many.']] },
    { title: '2. Major Trade Routes and Global Patterns', sub: 'A) Routes and Pattern', intro: 'World trade follows the following routes and pattern:',
      items: [['North Atlantic route:', 'It links Europe and North America and is the busiest route.'],
        ['Suez and Panama routes:', 'They link Europe, Asia and the Americas through canals.'],
        ['Pattern:', 'Most trade is among AICs and East Asia, and LICs export raw materials.']] },
    { title: '2. Major Trade Routes and Global Patterns', sub: 'B) Reasons for the Dominance of AICs', intro: 'AICs dominate world trade for the following reasons:',
      items: [['Valuable goods:', 'They export manufactured goods and services.'],
        ['Capital:', 'They have money to invest.'],
        ['Control of transport and markets:', 'They own ships, banks and markets.']],
      draw: { img: 'triad_big.png', caption: 'the world economic triad' } },
  ],
  evaluation: [['Define international trade.', 'Trade between countries.'], ['Give two reasons for the dominance of AICs in world trade.', 'They export manufactured goods and control transport and finance.']],
  remediation: ['Goods sold abroad are ______.', 'Trade within a country is ______ trade.', 'The busiest trade route is the North ______ route.'],
  remediationAnswers: '1. exports 2. internal 3. Atlantic',
  homework: 'List three exports and three imports of Cameroon.',
  hwAnswer: 'Exports: crude oil, cocoa, timber (also coffee, cotton, bananas); imports: cars, machines, rice (also fuel products, medicines, clothes).',
  bilingual: [['Trade', 'Le commerce'], ['Export', "L'exportation"], ['Import', "L'importation"], ['Trade route', 'La route commerciale'], ['Balance of trade', 'La balance commerciale'], ['Fair trade', 'Le commerce équitable']],
});

L.push({ no: 18, title: 'Trade Blocs', subtopic: 'Cameroon and Trade',
  notions: 'Trade bloc, ECOWAS, CEMAC, European Union, ASEAN, LAFTA.',
  focus: 'Definition and types; aims for creation; reasons for creation; advantages and disadvantages, with a case study in LICs.',
  competence: 'Learners are able to explain trade blocs and assess their advantages and disadvantages.',
  objectives: ['Define a trade bloc and give its types.', 'Explain the aims and reasons for creating trade blocs.', 'Assess the advantages and disadvantages with a case study of CEMAC.'],
  recall: ['Countries trade with each other.', 'Cameroon uses the CFA franc.', 'The European Union has many members.'],
  situation: 'Cameroonian traders sell goods to Chad, Gabon and Congo with fewer customs duties because the countries belong to CEMAC. However, some traders still face many road checks.',
  sitQA: [['What is the problem in the situation?', 'We want to understand trade blocs.'], ['Which bloc is mentioned?', 'CEMAC.'], ['What advantage do traders have?', 'Fewer customs duties.']],
  justification: 'This lesson helps us to understand regional cooperation in trade.',
  action: 'Support regional integration and denounce unfair trade practices.',
  activities: [
    { sec: '1. DEFINITION AND TYPES', img: 'blocs_africa_big.png', caption: 'Trade blocs in Africa.', q: 'What is a trade bloc?', a: 'A group of countries that agree to reduce trade barriers among themselves.', noProj: 'name blocs.' },
    { sec: '1. DEFINITION AND TYPES', img: 'blocs_table_big.png', caption: 'Types of trade blocs.', q: 'Name three types of trade blocs.', a: 'Free trade area, customs union and common market (also economic union).', noProj: 'classify.' },
    { sec: '2. AIMS AND REASONS', img: 'wto_epa_big.png', caption: 'Trade agreements.', q: 'Give two aims of trade blocs.', a: 'To increase trade among members and to be stronger in world markets.', noProj: 'discuss.' },
    { sec: '3. CASE STUDY: CEMAC', img: 'cmr_trade_big.png', caption: 'Trade of Cameroon.', q: 'Name the member states of CEMAC.', a: 'Cameroon, Chad, Gabon, Congo, the Central African Republic and Equatorial Guinea.', noProj: 'use the map.' },
    { sec: '4. ADVANTAGES AND DISADVANTAGES', img: 'usa_passport.jpg', caption: 'Free movement.', q: 'Give one advantage and one disadvantage of trade blocs.', a: 'Larger market; weak countries may lose customs revenue and local industries.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Trade bloc:', 'It is a group of countries that agree to reduce trade barriers among themselves.']]),
    { title: '1. Types, Aims and Reasons for Creation', sub: 'A) Types', intro: 'There are the following types of trade blocs:',
      items: [['Free trade areas:', 'Members remove customs duties among themselves.'],
        ['Customs unions:', 'Members also share a common external tariff.'],
        ['Common markets:', 'Goods, people and capital move freely.'],
        ['Economic unions:', 'Members also share common policies and sometimes a currency.']] },
    { title: '1. Types, Aims and Reasons for Creation', sub: 'B) Examples, Aims and Reasons', intro: 'Trade blocs are created as follows:',
      items: [['Examples:', 'CEMAC, ECOWAS, the European Union, ASEAN and LAFTA are trade blocs.'],
        ['Aims:', 'They increase trade, attract investment and strengthen members in world markets.'],
        ['Reasons:', 'Small national markets and competition from big powers push countries to unite.']],
      draw: { img: 'blocs_africa_big.png', caption: 'trade blocs in Africa' } },
    { title: '2. Case Study: CEMAC', sub: 'A) Members and Achievements', intro: 'CEMAC has the following members and achievements:',
      items: [['Members:', 'Cameroon, Chad, Gabon, Congo, the Central African Republic and Equatorial Guinea are members.'],
        ['Common currency:', 'Members share the CFA franc.'],
        ['Common external tariff:', 'Members charge the same duties on imports.']] },
    { title: '2. Case Study: CEMAC', sub: 'B) Problems', intro: 'CEMAC faces the following problems:',
      items: [['Poor roads:', 'Goods move slowly between members.'],
        ['Road checks:', 'Many checkpoints delay traders.'],
        ['Similar exports:', 'Members sell the same products, so they trade little with each other.']] },
    { title: '3. Advantages and Disadvantages', sub: 'A) Advantages', intro: 'Trade blocs have the following advantages:',
      items: [['A larger market:', 'Firms can sell to all member countries.'],
        ['More investment:', 'Investors are attracted by the big market.'],
        ['Free movement of people:', 'Citizens travel and work more easily.']] },
    { title: '3. Advantages and Disadvantages', sub: 'B) Disadvantages', intro: 'Trade blocs have the following disadvantages:',
      items: [['Loss of customs revenue:', 'Weak members collect less money at borders.'],
        ['Loss of local industries:', 'Stronger firms of other members compete with them.']] },
  ],
  evaluation: [['Define a trade bloc.', 'A group of countries that reduce trade barriers among themselves.'], ['Name two trade blocs and one advantage.', 'CEMAC and ECOWAS; a larger market.']],
  remediation: ['Cameroon belongs to the trade bloc ______.', 'The trade bloc of West Africa is ______.', 'The trade bloc of South-East Asia is ______.'],
  remediationAnswers: '1. CEMAC 2. ECOWAS 3. ASEAN',
  homework: 'Draw a sketch map of the CEMAC member states and name their capitals.',
  hwAnswer: 'Cameroon (Yaoundé), Chad (N’Djamena), Gabon (Libreville), Congo (Brazzaville), CAR (Bangui), Equatorial Guinea (Malabo).',
  bilingual: [['Trade bloc', 'Le bloc commercial'], ['Customs union', "L'union douanière"], ['Common market', 'Le marché commun'], ['Customs duty', 'Le droit de douane'], ['Member state', "L'État membre"], ['Integration', "L'intégration"]],
});

L.push({ no: 19, title: 'Tourism', subtopic: 'Global Tourism',
  notions: 'Tourism, mass tourism, ecotourism, tourist attraction.',
  focus: 'Meaning; types (only definitions); factors for the promotion of mass tourism; tourist destinations; major characteristics; general tourist attractions.',
  competence: 'Learners are able to explain tourism, its types, factors and destinations.',
  objectives: ['Define tourism and its types.', 'Explain the factors for the promotion of mass tourism.', 'Identify tourist destinations and attractions.'],
  recall: ['Tourism is a tertiary activity.', 'Waza Park has wild animals.', 'Many tourists visit Europe.'],
  situation: 'Every year, millions of Europeans travel to the beaches of Spain, while a few tourists visit Waza Park in Cameroon to see elephants and lions.',
  sitQA: [['What is the problem in the situation?', 'We want to understand tourism.'], ['Where do many Europeans go?', 'To the beaches of Spain.'], ['What attracts tourists to Waza?', 'Wild animals.']],
  justification: 'This lesson helps us to understand a growing economic activity.',
  action: 'Welcome visitors and protect tourist sites.',
  activities: [
    { sec: '1. MEANING', img: 'usa_beach.jpg', caption: 'A tourist beach.', q: 'What is tourism?', a: 'Travel for leisure, business or culture away from home for at least one night.', noProj: 'give examples.' },
    { sec: '2. TYPES', img: 'usa_safari.jpg', caption: 'A safari.', q: 'Define mass tourism and ecotourism.', a: 'Mass tourism is travel by very many people to the same places; ecotourism is responsible travel to natural areas.', noProj: 'define.' },
    { sec: '3. FACTORS FOR MASS TOURISM', img: 'f5_plane.jpg', caption: 'An aeroplane.', q: 'Give three factors that promote mass tourism.', a: 'Cheap air travel, paid holidays and higher incomes (also advertising).', noProj: 'discuss.' },
    { sec: '4. DESTINATIONS AND CHARACTERISTICS', img: 'tourism_flows_big.png', caption: 'World tourist flows.', q: 'Name three major tourist destinations.', a: 'France, Spain and the USA (also Italy and China).', noProj: 'use the map.' },
    { sec: '5. TOURIST ATTRACTIONS', img: 'lsa_mtcameroon.jpg', caption: 'Mount Cameroon.', q: 'Give three types of tourist attractions.', a: 'Natural sites, wildlife and cultural or historical sites.', noProj: 'list.' },
  ],
  summary: [
    D([['Tourism:', 'It is travel away from home for leisure, business or culture for at least one night.'],
      ['Mass tourism:', 'It is the travel of very many people to the same destinations.'],
      ['Ecotourism:', 'It is responsible travel to natural areas that protects the environment.']]),
    { title: '1. Factors for the Promotion of Mass Tourism', intro: 'Mass tourism is promoted by the following factors:',
      items: [['Transport:', 'Cheap air travel and good roads make travel easy.'],
        ['Income and leisure:', 'Higher incomes and paid holidays allow people to travel.'],
        ['Advertising:', 'Travel agencies and the internet promote holiday packages.']] },
    { title: '2. Destinations, Characteristics and Attractions', intro: 'Tourism has the following destinations and attractions:',
      items: [['Destinations:', 'France, Spain, the USA, Italy and China receive the most tourists.'],
        ['Characteristics:', 'Tourism is seasonal and concentrated in coasts, mountains and cities.'],
        ['Natural attractions:', 'Beaches, mountains, waterfalls and wildlife attract tourists.'],
        ['Cultural attractions:', 'Monuments, museums, festivals and crafts attract tourists.']],
      draw: { img: 'tourism_flows_big.png', caption: 'world tourist flows' } },
  ],
  evaluation: [['Define mass tourism.', 'The travel of very many people to the same destinations.'], ['Give two factors of mass tourism.', 'Cheap air travel and paid holidays.']],
  remediation: ['Responsible travel to natural areas is ______.', 'The most visited country in the world is ______.', 'Beaches are ______ attractions.'],
  remediationAnswers: '1. ecotourism 2. France 3. natural',
  homework: 'List five tourist attractions in Cameroon and classify them as natural or cultural.',
  hwAnswer: 'Natural: Mount Cameroon, Waza Park, Kribi beaches (Lobé Falls); cultural: Foumban palace, Rhumsiki landscape and villages (Ngondo festival).',
  bilingual: [['Tourism', 'Le tourisme'], ['Tourist', 'Le touriste'], ['Mass tourism', 'Le tourisme de masse'], ['Ecotourism', "L'écotourisme"], ['Attraction', "L'attraction"], ['Holiday', 'Les vacances']],
});

L.push({ no: 20, title: 'General Effects of Tourism', subtopic: 'Global Tourism',
  notions: 'Positive effects, negative effects, sustainable tourism.',
  focus: 'Positive and negative effects of tourism on the people, the economy and the environment.',
  competence: 'Learners are able to assess the effects of tourism.',
  objectives: ['Explain the effects of tourism on the people.', 'Explain the effects on the economy.', 'Explain the effects on the environment.'],
  recall: ['Tourism is travel for leisure.', 'Tourists spend money.', 'Many tourists visit beaches and parks.'],
  situation: 'In a coastal town, new hotels create jobs and bring money, but the beach is full of waste and local traditions are changing.',
  sitQA: [['What is the problem in the situation?', 'Tourism has both good and bad effects.'], ['Give one positive effect.', 'Jobs and money.'], ['Give one negative effect.', 'Waste on the beach (also loss of traditions).']],
  justification: 'This lesson helps us to manage tourism for sustainable development.',
  action: 'Clean up tourist sites and respect local cultures.',
  activities: [
    { sec: '1. EFFECTS ON THE PEOPLE', img: 'f2t_maasai.jpg', caption: 'Local culture.', q: 'Give one positive and one negative effect of tourism on the people.', a: 'Jobs and cultural exchange; loss of traditions and crime.', noProj: 'discuss.' },
    { sec: '2. EFFECTS ON THE ECONOMY', img: 'usa_hotel.jpg', caption: 'A hotel.', q: 'Give two positive effects on the economy.', a: 'Foreign currency and jobs (also infrastructure).', noProj: 'discuss.' },
    { sec: '2. EFFECTS ON THE ECONOMY', img: 'butler_big.png', caption: 'The Butler model.', q: 'Give one negative effect on the economy.', a: 'Profits leave the country and jobs are seasonal (also rising prices).', noProj: 'discuss.' },
    { sec: '3. EFFECTS ON THE ENVIRONMENT', img: 'usa_litter.jpg', caption: 'Litter.', q: 'Give two negative effects on the environment.', a: 'Pollution and destruction of habitats.', noProj: 'discuss.' },
    { sec: '3. EFFECTS ON THE ENVIRONMENT', img: 'tourism_impacts_big.png', caption: 'Impacts of tourism.', q: 'Give one positive effect on the environment.', a: 'Tourism money is used to protect parks and wildlife.', noProj: 'discuss.' },
  ],
  summary: [
    { title: '1. Effects on the People', sub: 'A) Positive Effects', intro: 'Tourism has the following positive effects on the people:',
      items: [['Jobs:', 'People work as guides, cooks and drivers.'],
        ['Cultural exchange:', 'People learn about other cultures.']] },
    { title: '1. Effects on the People', sub: 'B) Negative Effects', intro: 'Tourism has the following negative effects on the people:',
      items: [['Crime and drugs:', 'They may increase in tourist areas.'],
        ['Loss of traditions:', 'Local customs may disappear.']] },
    { title: '2. Effects on the Economy', sub: 'A) Positive Effects', intro: 'Tourism has the following positive effects on the economy:',
      items: [['Foreign currency:', 'Tourists spend money from abroad.'],
        ['Jobs:', 'Hotels, restaurants and transport employ people.'],
        ['New infrastructure:', 'Roads, airports and hotels are built.']] },
    { title: '2. Effects on the Economy', sub: 'B) Negative Effects', intro: 'Tourism has the following negative effects on the economy:',
      items: [['Profits leave the country:', 'Foreign companies take much of the money.'],
        ['Seasonal jobs:', 'Many jobs last only during the tourist season.']] },
    { title: '3. Effects on the Environment', sub: 'A) Positive Effects', intro: 'Tourism has the following positive effects on the environment:',
      items: [['Protection of parks:', 'Money from tourists pays for park guards.'],
        ['Protection of monuments:', 'Old buildings are repaired.']] },
    { title: '3. Effects on the Environment', sub: 'B) Negative Effects', intro: 'Tourism has the following negative effects on the environment:',
      items: [['Pollution:', 'Tourists leave waste on beaches and sites.'],
        ['Erosion:', 'Many visitors wear down paths and slopes.'],
        ['Destruction of habitats:', 'Hotels are built where animals live.']],
      draw: { img: 'tourism_impacts_big.png', caption: 'impacts of tourism' } },
  ],
  evaluation: [['Give one positive effect of tourism on the economy.', 'It brings foreign currency.'], ['Give one negative effect on the environment.', 'Pollution of beaches.']],
  remediation: ['Tourism brings foreign ______.', 'Jobs that exist only during holidays are ______.', 'Tourism that protects nature is ______ tourism.'],
  remediationAnswers: '1. currency 2. seasonal 3. sustainable (eco-)',
  homework: 'Give two positive and two negative effects of tourism at Kribi.',
  hwAnswer: 'Positive: jobs in hotels and restaurants, income for fishermen and craftsmen; negative: waste on beaches, rising prices and pressure on the Lobé Falls site.',
  bilingual: [['Effect', "L'effet"], ['Foreign currency', 'Les devises'], ['Hotel', "L'hôtel"], ['Habitat', "L'habitat"], ['Tradition', 'La tradition'], ['Sustainable tourism', 'Le tourisme durable']],
});

L.push({ no: 21, title: 'Development of Tourism in Cameroon', subtopic: 'Economic Development Potentials of Cameroon',
  notions: 'Tourist attractions, national parks, cultural sites.',
  focus: 'Identification and location of attractions; distribution of attractions; problems of tourism; effects on the environment, the people (culture) and the economy; government effort to promote tourism.',
  competence: 'Learners are able to locate tourist attractions in Cameroon and propose ways to develop tourism.',
  objectives: ['Identify and locate tourist attractions in Cameroon.', 'Explain the problems and effects of tourism in Cameroon.', 'Describe government efforts to promote tourism.'],
  recall: ['Cameroon is called Africa in miniature.', 'Waza is a national park.', 'Tourism brings foreign currency.'],
  situation: 'Cameroon has beaches, mountains, parks and rich cultures, but it receives few tourists compared with Kenya. Visitors complain about bad roads and insecurity.',
  sitQA: [['What is the problem in the situation?', 'Cameroon receives few tourists despite its attractions.'], ['Name two attractions of Cameroon.', 'Beaches and national parks.'], ['What do visitors complain about?', 'Bad roads and insecurity.']],
  justification: 'This lesson helps us to value the tourist potential of our country.',
  action: 'Use tourist guides, produce works of art and denounce harassment of tourists.',
  activities: [
    { sec: '1. ATTRACTIONS: NATURAL', img: 'cmr_tourism_big.png', caption: 'Tourist attractions of Cameroon.', q: 'Name and locate three natural attractions.', a: 'Waza Park (Far North), Mount Cameroon (South West) and Kribi beaches (South).', noProj: 'use the map.' },
    { sec: '1. ATTRACTIONS: CULTURAL', img: 'lsa_mandara.jpg', caption: 'The Mandara Mountains.', q: 'Name two cultural attractions.', a: 'The Foumban palace and the Rhumsiki villages (also the Ngondo festival).', noProj: 'list.' },
    { sec: '2. DISTRIBUTION', img: 'cmr_tourism_big.png', caption: 'Distribution of attractions.', q: 'Describe the distribution of attractions.', a: 'Wildlife parks are in the North, mountains and cultures in the West, and beaches on the coast.', noProj: 'describe.' },
    { sec: '3. PROBLEMS AND EFFECTS', img: 'f2t_muddy_road.jpg', caption: 'A bad road.', q: 'Give three problems of tourism in Cameroon.', a: 'Bad roads, insecurity and poor hotels (also high costs and poor advertising).', noProj: 'discuss.' },
    { sec: '4. GOVERNMENT EFFORTS', img: 'usa_limbe.jpg', caption: 'Limbe.', q: 'Give two government efforts to promote tourism.', a: 'Creating national parks and training tourism workers (also building roads and hotels).', noProj: 'list.' },
  ],
  summary: [
    { title: '1. Identification, Location and Distribution of Attractions', intro: 'The tourist attractions of Cameroon are distributed as follows:',
      items: [['North:', 'Waza, Benue and Bouba Ndjida parks and the Rhumsiki landscape attract visitors.'],
        ['West:', 'The Foumban palace, crater lakes and highland cultures attract visitors.'],
        ['Coast:', 'The beaches of Kribi and Limbe, the Lobé Falls and Mount Cameroon attract visitors.'],
        ['South and East:', 'Dja and Lobéké reserves protect forests and gorillas.']],
      draw: { img: 'cmr_tourism_big.png', caption: 'tourist attractions of Cameroon' } },
    { title: '2. Problems and Effects of Tourism', sub: 'A) Problems', intro: 'Tourism in Cameroon faces the following problems:',
      items: [['Bad roads:', 'Many sites are hard to reach.'],
        ['Insecurity:', 'Some regions are dangerous for visitors.'],
        ['Poor hotels:', 'There are few good hotels outside the big towns.'],
        ['Harassment and weak advertising:', 'Tourists are disturbed, and Cameroon is little known abroad.']] },
    { title: '2. Problems and Effects of Tourism', sub: 'B) Effects', intro: 'Tourism in Cameroon has the following effects:',
      items: [['On the economy:', 'It brings foreign currency and jobs.'],
        ['On the people:', 'It promotes local crafts but can change cultures.'],
        ['On the environment:', 'It can pollute tourist sites.']] },
    { title: '3. Government Efforts to Promote Tourism', intro: 'The government promotes tourism in the following ways:',
      items: [['Protection of sites:', 'National parks and reserves are created and guarded.'],
        ['Infrastructure:', 'Roads, airports and hotels are built and improved.'],
        ['Training and promotion:', 'Tourism schools train workers and fairs advertise Cameroon.']] },
  ],
  evaluation: [['Name and locate two tourist attractions in Cameroon.', 'Waza Park (Far North) and Kribi beaches (South).'], ['Give two problems of tourism in Cameroon.', 'Bad roads and insecurity.']],
  remediation: ['Cameroon is called Africa in ______.', 'The famous palace in the West is at ______.', 'The Lobé Falls are near ______.'],
  remediationAnswers: '1. miniature 2. Foumban 3. Kribi',
  homework: 'Draw a sketch map of Cameroon showing six tourist attractions.',
  hwAnswer: 'A framed sketch with Waza, Benue Park, Rhumsiki, Foumban, Mount Cameroon and Kribi (Lobé Falls), with a key and north arrow.',
  bilingual: [['National park', 'Le parc national'], ['Tourist guide', 'Le guide touristique'], ['Craft', "L'artisanat"], ['Palace', 'Le palais'], ['Waterfall', 'La chute'], ['Harassment', 'Le harcèlement']],
});

L.push({ no: 22, title: 'Economic Growth of Cameroon', subtopic: 'The Challenges to the Vision of Economic Emergence of Cameroon',
  notions: 'Economic growth, GDP, GNP, emergence, Vision 2035.',
  focus: 'Background on the levels of economic development; the reasons for the slow rate of economic growth; ways to uplift the economy to emergence.',
  competence: 'Learners are able to explain the level of economic growth of Cameroon and propose ways to reach emergence.',
  objectives: ['Describe the level of economic development of Cameroon.', 'Explain the reasons for slow economic growth.', 'Propose ways to uplift the economy to emergence.'],
  recall: ['Cameroon exports raw materials.', 'GDP measures the wealth produced in a country.', 'Cameroon wants to be emergent by 2035.'],
  situation: 'Cameroon plans to become an emerging country by 2035, but many young graduates are unemployed and the economy grows slowly.',
  sitQA: [['What is the problem in the situation?', 'The economy of Cameroon grows slowly.'], ['What is the target year for emergence?', '2035.'], ['What problem do young graduates face?', 'Unemployment.']],
  justification: 'This lesson helps us to understand the challenges of our country and our role in its development.',
  action: 'Create village cooperatives and development associations and participate in human investment.',
  activities: [
    { sec: '1. MEANING', img: 'dev_indicators_big.png', caption: 'Development indicators.', q: 'Distinguish GDP and GNP.', a: 'GDP is the value produced inside a country in a year; GNP adds income from abroad.', noProj: 'define.' },
    { sec: '1. BACKGROUND', img: 'cmr_gdp_big.png', caption: 'Economic growth of Cameroon (approximate).', q: 'Describe the evolution of the economy of Cameroon.', a: 'Fast growth until 1985, crisis from 1986 to 1994, then moderate growth.', noProj: 'describe the graph.' },
    { sec: '2. REASONS FOR SLOW GROWTH', img: 'underdev_causes_big.png', caption: 'Causes of underdevelopment.', q: 'Give three reasons for slow economic growth.', a: 'Dependence on raw materials, corruption and poor infrastructure (also insecurity).', noProj: 'discuss.' },
    { sec: '2. REASONS FOR SLOW GROWTH', img: 'terms_trade_big.png', caption: 'Terms of trade.', q: 'How do falling export prices affect Cameroon?', a: 'Income falls, so the country earns less to invest.', noProj: 'discuss.' },
    { sec: '3. WAYS TO EMERGENCE', img: 'rostow_big.png', caption: 'Stages of economic growth.', q: 'Give three ways to uplift the economy.', a: 'Process raw materials, build infrastructure and fight corruption (also train youths).', noProj: 'list.' },
  ],
  summary: [
    D([['Economic growth:', 'It is the increase in the value of goods and services produced by a country.'],
      ['Emergence:', 'It is the stage where a developing country has strong and lasting growth and industrialisation.']]),
    { title: '1. Background on the Levels of Economic Development', intro: 'The economy of Cameroon evolved as follows:',
      items: [['1960 to 1985:', 'Growth was fast thanks to agriculture and oil.'],
        ['1986 to 1994:', 'The economic crisis caused salary cuts and devaluation of the CFA franc.'],
        ['Since 1995:', 'Growth is moderate, and Vision 2035 aims at emergence.']],
      draw: { img: 'cmr_gdp_big.png', caption: 'economic growth of Cameroon' } },
    { title: '2. Reasons for the Slow Rate of Economic Growth', intro: 'The economy grows slowly for the following reasons:',
      items: [['Raw material exports:', 'Low and unstable prices reduce national income.'],
        ['Poor infrastructure:', 'Bad roads and power cuts raise production costs.'],
        ['Governance:', 'Corruption, embezzlement and administrative bottlenecks discourage investors.'],
        ['Insecurity:', 'Crises in some regions disturb economic activities.']] },
    { title: '3. Ways to Uplift the Economy to Emergence', intro: 'The economy can be uplifted in the following ways:',
      items: [['Industrialisation:', 'Raw materials should be processed locally.'],
        ['Infrastructure:', 'Roads, ports, dams and electricity should be developed.'],
        ['Good governance and human capital:', 'Fighting corruption and training youths attract investment.']] },
  ],
  evaluation: [['What is economic growth?', 'The increase in the value of goods and services produced.'], ['Give two reasons for slow growth and two solutions.', 'Corruption and poor infrastructure; fight corruption and build infrastructure.']],
  remediation: ['The value produced inside a country in a year is the ______.', 'Cameroon aims at emergence by ______.', 'The economic crisis began in ______.'],
  remediationAnswers: '1. GDP 2. 2035 3. 1986 (the mid-1980s)',
  homework: 'Suggest three actions young people can take to help Cameroon reach emergence.',
  hwAnswer: 'Learn technical skills, create small businesses or cooperatives, buy local products, and refuse corruption (also take part in community work).',
  bilingual: [['Economic growth', 'La croissance économique'], ['Emergence', "L'émergence"], ['GDP', 'Le PIB'], ['Crisis', 'La crise'], ['Corruption', 'La corruption'], ['Investment', "L'investissement"]],
});

module.exports = { B, L };
