// FORM 5 — Module II: Preservation of the Natural Environment (2023 syllabus): L23–L27
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F5', code: 'M2', folder: '', module: 'Module II: Preservation of the Natural Environment', topicDefault: 'Development Projects and Environmental Management', branch: 'Development Projects',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 5, Module II: Preservation of the Natural Environment.'] };
const L = [];

L.push({ no: 23, title: 'Land Reclamation', subtopic: 'Development Projects',
  notions: 'Land reclamation, landfill, dykes, irrigation, poldering, drainage.',
  focus: 'Meaning; examples; advantages and disadvantages of land reclamation schemes; challenges of land reclamation.',
  competence: 'Learners are able to explain land reclamation and assess reclamation schemes.',
  objectives: ['Define land reclamation.', 'Give examples of land reclamation schemes.', 'Assess their advantages, disadvantages and challenges.'],
  recall: ['Some lands are too wet, too dry or eroded to be used.', 'The Netherlands is a low country.', 'Irrigation brings water to dry land.'],
  situation: 'In the Netherlands, people built dykes and pumped water out of the sea to create farmland. In the Far North of Cameroon, farmers irrigate dry land to grow rice.',
  sitQA: [['What is the problem in the situation?', 'We want to know how people make unused land useful.'], ['How did the Dutch gain land?', 'By building dykes and pumping out water.'], ['How is dry land used in the Far North?', 'By irrigation.']],
  justification: 'This lesson helps us to understand how people improve difficult environments.',
  action: 'Use manures, terraces and tree planting to restore degraded land.',
  activities: [
    { sec: '1. MEANING', img: 'reclamation_big.png', caption: 'Methods of land reclamation.', q: 'What is land reclamation?', a: 'Making unused or degraded land usable for farming, settlement or industry.', noProj: 'discuss.' },
    { sec: '2. EXAMPLES: POLDERS', img: 'f5_polder.jpg', caption: 'A polder in the Netherlands.', q: 'What is a polder?', a: 'Land taken from the sea or a lake by building dykes and pumping out the water.', noProj: 'describe.' },
    { sec: '2. EXAMPLES: DRYLANDS AND COASTS', img: 'usa_irrigation.jpg', caption: 'Irrigation canals.', q: 'Give two other examples of land reclamation.', a: 'Irrigation of drylands and landfill on coasts (Singapore, Dubai).', noProj: 'list.' },
    { sec: '3. ADVANTAGES AND DISADVANTAGES', img: 'usa_singapore.jpg', caption: 'Singapore, built partly on reclaimed land.', q: 'Give one advantage and one disadvantage of land reclamation.', a: 'More land for farming or building; destruction of wetlands and high costs.', noProj: 'discuss.' },
    { sec: '4. CHALLENGES', img: 'f4_floodvillage.jpg', caption: 'A flood.', q: 'Give two challenges of land reclamation.', a: 'High costs and the risk of floods or salinisation.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Land reclamation:', 'It is the process of making unused or degraded land usable.']]),
    { title: '1. Examples of Land Reclamation Schemes', intro: 'Land is reclaimed in the following ways:',
      items: [['Poldering:', 'Dykes are built and water is pumped out, as in the Netherlands.'],
        ['Drainage and landfill:', 'Swamps are drained and coasts are filled, as in Singapore.'],
        ['Irrigation:', 'Dry lands are watered, as at SEMRY in the Far North of Cameroon.'],
        ['Soil restoration:', 'Terraces, manures and trees restore eroded land.']],
      draw: { img: 'reclamation_big.png', caption: 'methods of land reclamation' } },
    { title: '2. Advantages, Disadvantages and Challenges', intro: 'Land reclamation has the following effects and challenges:',
      items: [['Advantages:', 'It gives more land for farming, settlement and industry.'],
        ['Disadvantages:', 'It destroys wetlands and habitats and can cause salinisation.'],
        ['Challenges:', 'It needs much capital, technology and maintenance.']] },
  ],
  evaluation: [['What is a polder?', 'Land taken from the sea by dykes and pumping.'], ['Give one advantage and one challenge of land reclamation.', 'More farmland; high costs.']],
  remediation: ['Land taken from the sea is a ______.', 'Walls built to hold back water are ______.', 'Watering dry land is ______.'],
  remediationAnswers: '1. polder 2. dykes 3. irrigation',
  homework: 'Propose three ways to reclaim degraded land in the North of Cameroon.',
  hwAnswer: 'Irrigation from the Benue or Logone, tree planting (Green Sahel), and zaï pits, stone lines and manure on eroded fields.',
  bilingual: [['Land reclamation', 'La mise en valeur des terres'], ['Polder', 'Le polder'], ['Dyke', 'La digue'], ['Drainage', 'Le drainage'], ['Landfill', 'Le remblai'], ['Salinisation', 'La salinisation']],
});

L.push({ no: 24, title: 'Multipurpose River Development Project (MRDP)', subtopic: 'Development Projects',
  notions: 'Dams, irrigation, navigation, hydro-electricity, flood control.',
  focus: 'Meaning; reasons and objectives; achievements; problems and solutions, with a case study from an NIC.',
  competence: 'Learners are able to explain the objectives, achievements and problems of a multipurpose river project.',
  objectives: ['Define a multipurpose river development project.', 'Explain its objectives.', 'Assess its achievements and problems with the case of the Three Gorges Dam.'],
  recall: ['Dams produce hydro-electricity.', 'Irrigation helps agriculture.', 'China is an NIC.'],
  situation: 'China built the Three Gorges Dam on the Yangtze River to produce electricity, control floods and improve navigation. More than one million people were moved.',
  sitQA: [['What is the problem in the situation?', 'We want to assess a big river project.'], ['Give two aims of the dam.', 'Electricity and flood control (also navigation).'], ['What negative effect is mentioned?', 'The displacement of more than one million people.']],
  justification: 'This lesson helps us to understand how rivers are developed for many uses.',
  action: 'Use water from dams carefully and protect river banks.',
  activities: [
    { sec: '1. MEANING', img: 'mrdp_big.png', caption: 'Uses of a multipurpose river project.', q: 'What is a multipurpose river development project?', a: 'The development of a river basin with dams for several uses at the same time.', noProj: 'discuss.' },
    { sec: '2. REASONS AND OBJECTIVES', img: 'lsa_dam.jpg', caption: 'A dam spillway.', q: 'Give four objectives of an MRDP.', a: 'Hydro-electricity, irrigation, flood control and navigation (also water supply and fishing).', noProj: 'list.' },
    { sec: '3. CASE STUDY: THREE GORGES DAM', img: 'f5_threegorges.jpg', caption: 'The Three Gorges Dam, China.', q: 'Where is the Three Gorges Dam?', a: 'On the Yangtze River in central China.', noProj: 'use the atlas.' },
    { sec: '3. ACHIEVEMENTS', img: 'usa_powerplant.jpg', caption: 'Power supply.', q: 'Give two achievements of the Three Gorges Dam.', a: 'It is the biggest power station in the world and it reduces floods downstream.', noProj: 'discuss.' },
    { sec: '4. PROBLEMS AND SOLUTIONS', img: 'usa_refugee.jpg', caption: 'Displaced people.', q: 'Give two problems and one solution.', a: 'Displacement of people and silting; resettlement and reforestation of the basin.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Multipurpose river development project:', 'It is the development of a river basin with dams for several uses at the same time.']]),
    { title: '1. Reasons and Objectives', intro: 'MRDPs are built for the following objectives:',
      items: [['Energy:', 'Dams produce hydro-electricity for homes and industries.'],
        ['Agriculture and water supply:', 'Reservoirs supply water for irrigation, towns and fishing.'],
        ['Flood control and navigation:', 'Dams regulate the river flow and make navigation easier.']],
      draw: { img: 'mrdp_big.png', caption: 'uses of a multipurpose river project' } },
    { title: '2. Case Study: The Three Gorges Dam in China', intro: 'The Three Gorges project on the Yangtze River shows the following:',
      items: [['Achievements:', 'It is the largest power station in the world and it controls floods.'],
        ['More achievements:', 'Large ships can now sail upstream to Chongqing.'],
        ['Problems:', 'More than one million people were moved and the reservoir is silting.'],
        ['Solutions:', 'Displaced people were resettled and trees are planted to reduce erosion.']] },
  ],
  evaluation: [['Define an MRDP.', 'The development of a river basin with dams for several uses.'], ['Give two achievements and one problem of the Three Gorges Dam.', 'Electricity and flood control; displacement of people.']],
  remediation: ['Electricity from falling water is ______.', 'The Three Gorges Dam is on the ______ River.', 'A lake behind a dam is a ______.'],
  remediationAnswers: '1. hydro-electricity 2. Yangtze 3. reservoir',
  homework: 'Draw a diagram showing the uses of a multipurpose dam.',
  hwAnswer: 'A central box (multipurpose dam) with arrows to hydro-electricity, irrigation, navigation, flood control, water supply, fishing and tourism.',
  bilingual: [['Dam', 'Le barrage'], ['Reservoir', 'La retenue'], ['Hydro-electricity', "L'hydroélectricité"], ['Navigation', 'La navigation'], ['Flood control', 'La maîtrise des crues'], ['Resettlement', 'La réinstallation']],
});

L.push({ no: 25, title: 'Multipurpose River Development Project in Cameroon', subtopic: 'Development Projects in Cameroon',
  notions: 'Multipurpose river development, Lagdo dam, SEMRY, Lom Pangar.',
  focus: 'Objectives; achievements; problems; attempted solutions.',
  competence: 'Learners are able to assess a multipurpose river project in Cameroon.',
  objectives: ['Locate the Lagdo multipurpose project.', 'Explain its objectives and achievements.', 'Explain its problems and attempted solutions.'],
  recall: ['An MRDP has several uses.', 'The Benue flows through Garoua.', 'Lagdo is in the North Region.'],
  situation: 'The Lagdo dam on the Benue supplies electricity to the North and water for irrigated farms and fishing. However, power cuts remain and the 2012 release of water flooded villages.',
  sitQA: [['What is the problem in the situation?', 'We want to assess the Lagdo project.'], ['On which river is the dam?', 'The Benue.'], ['Give one problem mentioned.', 'Power cuts (also floods downstream).']],
  justification: 'This lesson helps us to understand a development project close to us.',
  action: 'Protect the dam area and respect the rules of fishing in the lake.',
  activities: [
    { sec: '1. LOCATION', img: 'cmr_water_big.png', caption: 'Dams and irrigation schemes of Cameroon.', q: 'Locate the Lagdo dam.', a: 'On the Benue River, about 50 km upstream of Garoua in the North Region.', noProj: 'use the map.' },
    { sec: '2. OBJECTIVES', img: 'mrdp_big.png', caption: 'Uses of an MRDP.', q: 'Give three objectives of the Lagdo project.', a: 'Electricity for the North, irrigation and fishing (also flood control).', noProj: 'list.' },
    { sec: '3. ACHIEVEMENTS', img: 'f2t_rice_field.jpg', caption: 'Irrigated rice.', q: 'Give two achievements of the Lagdo project.', a: 'It supplies electricity to the northern regions and supports fishing and irrigated farming.', noProj: 'discuss.' },
    { sec: '4. PROBLEMS', img: 'f4_floodvillage.jpg', caption: 'A flooded village.', q: 'Give three problems of the Lagdo project.', a: 'Low water in the dry season, silting and floods downstream when water is released.', noProj: 'discuss.' },
    { sec: '5. ATTEMPTED SOLUTIONS', img: 'f2t_tree_planting.jpg', caption: 'Tree planting.', q: 'Give two attempted solutions.', a: 'Tree planting in the basin and the interconnection of power grids (also warning before releases).', noProj: 'list.' },
  ],
  summary: [
    { title: '1. Objectives of the Lagdo Project', intro: 'The Lagdo dam on the Benue was built for the following objectives:',
      items: [['Energy:', 'It produces hydro-electricity for the northern regions.'],
        ['Agriculture:', 'It supplies water to irrigate rice and other crops.'],
        ['Fishing and flood control:', 'The lake supports fishing and the dam regulates the Benue.']],
      draw: { img: 'cmr_water_big.png', caption: 'dams and irrigation schemes of Cameroon' } },
    { title: '2. Achievements', intro: 'The project achieved the following:',
      items: [['Electricity:', 'Towns such as Garoua, Maroua and Ngaoundéré receive power.'],
        ['Food production:', 'Lake fishing and irrigated farms feed the region.'],
        ['Other projects:', 'Lom Pangar, Memve\'ele and Song Loulou dams also serve Cameroon.']] },
    { title: '3. Problems and Attempted Solutions', intro: 'The project faces problems and attempted solutions as follows:',
      items: [['Problems:', 'Low water in the dry season causes power cuts, and the lake is silting.'],
        ['More problems:', 'Water releases can flood villages downstream, as in 2012.'],
        ['Attempted solutions:', 'Tree planting, new dams, grid interconnection and flood warnings are used.']] },
  ],
  evaluation: [['Give two objectives of the Lagdo dam.', 'Electricity and irrigation.'], ['Give one problem and one solution.', 'Power cuts in the dry season; interconnection of power grids.']],
  remediation: ['The Lagdo dam is on the ______ River.', 'The dam produces ______ for the North.', 'A dam on the Lom in the East is ______.'],
  remediationAnswers: '1. Benue 2. hydro-electricity 3. Lom Pangar',
  homework: 'Explain how the Lagdo dam affects the life of the people of Garoua.',
  hwAnswer: 'It gives electricity for homes and industries, fish and irrigated food, but power cuts occur and floods can affect the riverside areas.',
  bilingual: [['Lake', 'Le lac'], ['Silting', "L'envasement"], ['Power cut', 'La coupure de courant'], ['Irrigated farm', 'La ferme irriguée'], ['Downstream', 'En aval'], ['Grid', 'Le réseau électrique']],
});

L.push({ no: 26, title: 'Problems of Waste Management', subtopic: 'Environmental Degradation',
  notions: 'Waste, waste management, landfill, recycling, pollution.',
  focus: 'Definition; causes; consequences; solutions.',
  competence: 'Learners are able to explain the problems of waste management and propose solutions.',
  objectives: ['Define waste and waste management.', 'Explain the causes and consequences of poor waste management.', 'Propose solutions.'],
  recall: ['Towns produce much waste.', 'Plastic bags block drains.', 'Dirty water causes diseases.'],
  situation: 'In a quarter of Garoua, people throw waste into the gutters and the river. In the rainy season, the gutters overflow and many children suffer from cholera.',
  sitQA: [['What is the problem in the situation?', 'Poor waste management.'], ['Where is the waste thrown?', 'Into gutters and the river.'], ['What are the consequences?', 'Floods and cholera.']],
  justification: 'This lesson helps us to keep our environment clean and healthy.',
  action: 'Sort your waste, use bins and denounce the dumping of waste into streams.',
  activities: [
    { sec: '1. DEFINITION', img: 'usa_dump.jpg', caption: 'A waste dump.', q: 'What is waste management?', a: 'The collection, transport, treatment and disposal of waste.', noProj: 'discuss.' },
    { sec: '2. CAUSES', img: 'usa_litter.jpg', caption: 'Litter.', q: 'Give three causes of poor waste management.', a: 'Rapid urban growth, few bins and trucks, and bad habits of people.', noProj: 'discuss.' },
    { sec: '3. CONSEQUENCES', img: 'waste_problems_big.png', caption: 'Consequences of poor waste management.', q: 'Give three consequences.', a: 'Diseases, floods from blocked drains and water pollution.', noProj: 'list.' },
    { sec: '3. CONSEQUENCES', img: 'f5_plastic.jpg', caption: 'Plastic waste in water.', q: 'Why is plastic waste dangerous?', a: 'It lasts a long time, blocks drains and kills animals.', noProj: 'discuss.' },
    { sec: '4. SOLUTIONS', img: 'waste_sort_big.png', caption: 'Sorting waste.', q: 'Give three solutions.', a: 'Sorting and recycling, sanitary landfills and education of the population.', noProj: 'list.' },
  ],
  summary: [
    D([['Waste:', 'It is any material that is thrown away because it is no longer useful.'],
      ['Waste management:', 'It is the collection, transport, treatment and disposal of waste.']]),
    { title: '1. Causes of Poor Waste Management', intro: 'Poor waste management has the following causes:',
      items: [['Urban growth:', 'Fast-growing towns produce more waste than can be collected.'],
        ['Lack of means:', 'Councils lack bins, trucks and landfills.'],
        ['Bad habits:', 'People throw waste into streets, gutters and rivers.']] },
    { title: '2. Consequences', intro: 'Poor waste management has the following consequences:',
      items: [['Health:', 'Flies, mosquitoes and dirty water spread cholera, typhoid and malaria.'],
        ['Floods:', 'Waste blocks drains and causes floods.'],
        ['Pollution:', 'Burning and dumping pollute the air, soil and water.']],
      draw: { img: 'waste_problems_big.png', caption: 'consequences of poor waste management' } },
    { title: '3. Solutions', intro: 'Waste can be better managed in the following ways:',
      items: [['Reduce, reuse and recycle:', 'Waste should be sorted and reused or recycled.'],
        ['Infrastructure:', 'Bins, collection trucks and sanitary landfills should be provided.'],
        ['Education and laws:', 'People should be sensitised and dumping should be punished.']] },
  ],
  evaluation: [['Define waste management.', 'The collection, transport, treatment and disposal of waste.'], ['Give two consequences and two solutions.', 'Diseases and floods; recycling and landfills.']],
  remediation: ['A controlled site for burying waste is a sanitary ______.', 'Making new products from waste is ______.', 'Waste in gutters causes ______.'],
  remediationAnswers: '1. landfill 2. recycling 3. floods',
  homework: 'Describe how waste is managed in your quarter and propose three improvements.',
  hwAnswer: 'Example: waste is burnt or dumped in gutters; provide bins, organise collection with HYSACAM or the council, and sort plastics for recycling.',
  bilingual: [['Waste', 'Les déchets'], ['Bin', 'La poubelle'], ['Recycling', 'Le recyclage'], ['Landfill', 'La décharge'], ['Gutter', 'Le caniveau'], ['Cholera', 'Le choléra']],
});

L.push({ no: 27, title: 'Pollution', subtopic: 'Environmental Degradation',
  notions: 'Pollution, pollutant, air, water, soil and noise pollution.',
  focus: 'Definition; types; causes and sources of each type; consequences and solutions of each type; adaptation strategies.',
  competence: 'Learners are able to explain the types of pollution and propose solutions and adaptation strategies.',
  objectives: ['Define pollution and give its types.', 'Explain the causes and sources of each type.', 'Explain the consequences, solutions and adaptation strategies.'],
  recall: ['Waste pollutes the environment.', 'Cars produce smoke.', 'Dirty water causes diseases.'],
  situation: 'In a town, factories and old cars release thick smoke, a river is full of waste and loud music disturbs the neighbours every night.',
  sitQA: [['What is the problem in the situation?', 'The town suffers from pollution.'], ['Name two sources of pollution.', 'Factories and cars.'], ['Name the types of pollution in the situation.', 'Air, water and noise pollution.']],
  justification: 'This lesson helps us to protect our health and our environment.',
  action: 'Denounce polluters, plant trees and reduce noise and waste.',
  activities: [
    { sec: '1. DEFINITION AND TYPES', img: 'env_pollution_big.png', caption: 'Types of pollution.', q: 'What is pollution?', a: 'The introduction of harmful substances or energy into the environment.', noProj: 'list types.' },
    { sec: '2. AIR POLLUTION', img: 'lsa_smog.jpg', caption: 'Smog in a city.', q: 'Give two sources and one consequence of air pollution.', a: 'Factories and vehicles; respiratory diseases (also acid rain).', noProj: 'discuss.' },
    { sec: '2. WATER POLLUTION', img: 'f5_plastic.jpg', caption: 'Plastic in water.', q: 'Give two sources and one consequence of water pollution.', a: 'Household waste and chemicals; waterborne diseases.', noProj: 'discuss.' },
    { sec: '2. SOIL AND NOISE POLLUTION', img: 'usa_spraying.jpg', caption: 'Spraying chemicals.', q: 'Give one source each of soil and noise pollution.', a: 'Pesticides and plastics pollute soil; traffic and loud music cause noise.', noProj: 'discuss.' },
    { sec: '3. SOLUTIONS AND ADAPTATION', img: 'pollution_table_big.png', caption: 'Pollution: causes and solutions.', q: 'Give two solutions and one adaptation strategy.', a: 'Laws and clean technology; wearing masks or boiling water.', noProj: 'list.' },
  ],
  summary: [
    D([['Pollution:', 'It is the introduction of harmful substances or energy into the environment.']]),
    { title: '1. Types, Causes and Sources', intro: 'The types of pollution and their sources are the following:',
      items: [['Air pollution:', 'It comes from factories, vehicles, burning waste and bush fires.'],
        ['Water pollution:', 'It comes from sewage, household waste, chemicals and oil spills.'],
        ['Soil pollution:', 'It comes from pesticides, fertilisers, plastics and mining waste.'],
        ['Noise pollution:', 'It comes from traffic, machines, aircraft and loud music.']],
      draw: { img: 'env_pollution_big.png', caption: 'types of pollution' } },
    { title: '2. Consequences and Solutions', intro: 'Pollution has the following consequences and solutions:',
      items: [['Consequences:', 'It causes diseases, acid rain, death of plants and animals, and stress.'],
        ['Solutions:', 'Laws, clean technology, waste treatment and tree planting reduce pollution.'],
        ['Adaptation strategies:', 'People wear masks, boil or filter water and plant trees around homes.']] },
  ],
  evaluation: [['Define pollution.', 'The introduction of harmful substances or energy into the environment.'], ['Give one source and one solution for air pollution.', 'Vehicles; clean technology (also tree planting).']],
  remediation: ['Loud sounds cause ______ pollution.', 'Oil spills cause ______ pollution.', 'Rain made acid by gases is acid ______.'],
  remediationAnswers: '1. noise 2. water 3. rain',
  homework: 'Identify two types of pollution in your town, their sources and one solution for each.',
  hwAnswer: 'Example: air pollution from old cars and burning waste (inspect vehicles, stop burning); water pollution from waste in the river (bins and sanitation).',
  bilingual: [['Pollution', 'La pollution'], ['Pollutant', 'Le polluant'], ['Smoke', 'La fumée'], ['Noise', 'Le bruit'], ['Sewage', 'Les eaux usées'], ['Acid rain', 'La pluie acide']],
});

module.exports = { B, L };
