// FORM 5 — Module III: Management of Population Growth and Space Colonisation (2023 syllabus), part 1: L28–L40 with FS3, PW3, FS4, PW4
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'F5', code: 'M3', folder: '', module: 'Module III: Management of Population Growth and Space Colonisation', topicDefault: 'The Dynamics of Population and Implications', branch: 'Population and Population Distribution',
  refs: ['Geography Syllabus, Forms I–V, MINESEC (2023) — Form 5, Module III: Management of Population Growth and Space Colonisation.'] };
const L = [];
const PD = 'Population and Population Distribution', PS = 'Population Structure and Composition', PG = 'Population Change in Time (Population Growth)';

L.push({ no: 28, title: 'Basic Notions on Population', subtopic: PD,
  notions: 'Population, demography, census, world population.',
  focus: 'Definition; evolution of world\'s population.',
  competence: 'Learners are able to define population and describe the evolution of the world population.',
  objectives: ['Define population and demography.', 'Describe the evolution of the world population.', 'Explain the causes of rapid growth since 1950.'],
  recall: ['Cameroon has about 28 million people.', 'Many children are born in Africa.', 'Some regions are crowded.'],
  situation: 'In 1950 the world had about 2.5 billion people, but today it has more than 8 billion. A pupil wonders why the population grew so fast.',
  sitQA: [['What is the problem in the situation?', 'We want to understand the growth of the world population.'], ['What was the world population in 1950?', 'About 2.5 billion.'], ['What is it today?', 'More than 8 billion.']],
  justification: 'This lesson introduces the study of population and its challenges.',
  action: 'Take part in census operations and give correct information.',
  activities: [
    { sec: '1. DEFINITION', img: 'usa_crowd.jpg', caption: 'A crowd.', q: 'What is population?', a: 'The total number of people living in an area at a given time.', noProj: 'discuss.' },
    { sec: '1. DEFINITION', img: 'data_sources_big.png', caption: 'Sources of data.', q: 'What is demography?', a: 'The scientific study of human population.', noProj: 'define.' },
    { sec: '2. EVOLUTION: SLOW GROWTH', img: 'world_pop_big.png', caption: 'Growth of the world population.', q: 'Describe world population growth before 1800.', a: 'It was very slow because of high death rates from famine, disease and wars.', noProj: 'describe the graph.' },
    { sec: '2. EVOLUTION: RAPID GROWTH', img: 'world_growth_big.png', caption: 'World population growth.', q: 'Describe world population growth since 1950.', a: 'It is very rapid, from 2.5 billion in 1950 to more than 8 billion today.', noProj: 'describe.' },
    { sec: '3. CAUSES', img: 'usa_vaccine.jpg', caption: 'Vaccination.', q: 'Why did the population grow fast after 1950?', a: 'Death rates fell with medicine and food, while birth rates stayed high in LICs.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Population:', 'It is the total number of people living in an area at a given time.'],
      ['Demography:', 'It is the scientific study of human population.']]),
    { title: '1. Evolution of the World Population', intro: 'The world population evolved as follows:',
      items: [['Before 1800:', 'Growth was slow because of famine, diseases and wars.'],
        ['1800 to 1950:', 'Growth increased with the Industrial Revolution in Europe.'],
        ['Since 1950:', 'Growth is very fast, reaching more than 8 billion people today.'],
        ['Causes:', 'Medicine, vaccines and more food reduced death rates.']],
      draw: { img: 'world_pop_big.png', caption: 'growth of the world population' } },
  ],
  evaluation: [['Define population.', 'The total number of people in an area at a given time.'], ['Give one cause of rapid growth since 1950.', 'Falling death rates due to medicine.']],
  remediation: ['The study of population is ______.', 'The world population passed ______ billion in 2022.', 'Vaccines reduced the ______ rate.'],
  remediationAnswers: '1. demography 2. eight (8) 3. death',
  homework: 'Find the population of Cameroon in the censuses of 1976, 1987 and 2005.',
  hwAnswer: '1976: about 7.7 million; 1987: about 10.5 million; 2005: about 17.5 million (about 28 million estimated today).',
  bilingual: [['Population', 'La population'], ['Demography', 'La démographie'], ['Census', 'Le recensement'], ['Growth', 'La croissance'], ['Billion', 'Le milliard'], ['Death rate', 'Le taux de mortalité']],
});

L.push({ kind: 'Further Study', no: 3, title: 'Sources of Population Data', subtopic: PD,
  notions: 'Census, survey, vital registration, migration records.',
  focus: 'Census: meaning, methods, advantages and weaknesses; surveys: meaning, types, advantages and weaknesses; vital registrations; migration records.',
  competence: 'Learners are able to explain the sources of population data and assess them.',
  objectives: ['Explain the census and its methods.', 'Explain surveys and vital registrations.', 'Assess the advantages and weaknesses of each source.'],
  recall: ['BUCREP organises censuses in Cameroon.', 'Births must be declared.', 'Passports record travel.'],
  situation: 'Census agents visit every house in Garoua to count the people. At the same time, the council records births and deaths, and the police record travellers at the border.',
  sitQA: [['What is the problem in the situation?', 'We want to know how population data are collected.'], ['Who counts people in every house?', 'Census agents.'], ['Who records births and deaths?', 'The council (civil status).']],
  justification: 'This further study helps us to understand where population figures come from.',
  action: 'Declare births and deaths and cooperate with census agents.',
  activities: [
    { sec: '1. CENSUS', img: 'questionnaire_big.png', caption: 'A questionnaire.', q: 'What is a census?', a: 'The official counting of all the people of a country at a given time.', noProj: 'discuss.' },
    { sec: '1. CENSUS: METHODS', img: 'data_sources_big.png', caption: 'Sources of data.', q: 'Distinguish de facto and de jure census.', a: 'De facto counts people where they are on census night; de jure counts them at their usual residence.', noProj: 'discuss.' },
    { sec: '2. SURVEYS', img: 'usa_girls.jpg', caption: 'People interviewed.', q: 'What is a sample survey?', a: 'The study of a small part of the population to learn about the whole.', noProj: 'discuss.' },
    { sec: '3. VITAL REGISTRATION', img: 'usa_newborn.jpg', caption: 'A newborn baby.', q: 'What is vital registration?', a: 'The recording of births, deaths and marriages by civil status offices.', noProj: 'discuss.' },
    { sec: '4. MIGRATION RECORDS', img: 'usa_passport.jpg', caption: 'A passport.', q: 'Give one advantage and one weakness of migration records.', a: 'They count people crossing borders; clandestine migrants are not recorded.', noProj: 'discuss.' },
  ],
  summary: [
    { title: '1. The Census', intro: 'The census is organised as follows:',
      items: [['Meaning:', 'It is the official counting of all the people of a country at a given time.'],
        ['Methods:', 'A de facto census counts people where they are, and a de jure census counts them at their usual home.'],
        ['Advantages:', 'It gives complete data on age, sex, education and housing.'],
        ['Weaknesses:', 'It is costly, rare and some people are not counted.']],
      draw: { img: 'data_sources_big.png', caption: 'sources of population data' } },
    { title: '2. Other Sources', intro: 'Other sources of population data are the following:',
      items: [['Surveys:', 'They study a sample of the population, and they are cheap but less complete.'],
        ['Vital registration:', 'It records births, deaths and marriages, but many events are not declared.'],
        ['Migration records:', 'They record people crossing borders, but clandestine migrants escape them.']] },
  ],
  evaluation: [['What is a census?', 'The official counting of all the people of a country.'], ['Give one weakness of vital registration in Cameroon.', 'Many births and deaths are not declared.']],
  remediation: ['The institution in charge of censuses in Cameroon is ______.', 'Recording births and deaths is ______ registration.', 'A study of part of the population is a ______.'],
  remediationAnswers: '1. BUCREP 2. vital 3. survey (sample survey)',
  homework: 'Explain two reasons why census figures in Cameroon may be inaccurate.',
  hwAnswer: 'Some people are absent, hide or are counted twice; insecurity and poor roads prevent agents from reaching some areas.',
  bilingual: [['Census', 'Le recensement'], ['Survey', "L'enquête"], ['Sample', "L'échantillon"], ['Birth certificate', "L'acte de naissance"], ['Civil status', "L'état civil"], ['Border', 'La frontière']],
});

L.push({ no: 29, title: 'Population Distribution', subtopic: PD,
  notions: 'Population distribution, population density, dense, moderate, sparse.',
  focus: 'Meaning of population distribution and population density; measures of population density.',
  competence: 'Learners are able to define and calculate population density.',
  objectives: ['Define population distribution and density.', 'Distinguish dense, moderate and sparse areas.', 'Calculate the population density.'],
  recall: ['Population is not evenly spread.', 'Cities are crowded.', 'The East of Cameroon has few people.'],
  situation: 'The Littoral Region is small but very crowded, while the East Region is very large with few people. The teacher asks the class how to compare them.',
  sitQA: [['What is the problem in the situation?', 'We want to compare how crowded regions are.'], ['Which region is crowded?', 'The Littoral.'], ['How can we compare them?', 'By calculating the population density.']],
  justification: 'This lesson helps us to measure how people are spread on the land.',
  action: 'Use density data to plan services such as schools and hospitals.',
  activities: [
    { sec: '1. MEANING: DISTRIBUTION', img: 'world_density_big.png', caption: 'World population distribution.', q: 'What is population distribution?', a: 'The way people are spread over an area.', noProj: 'describe.' },
    { sec: '1. MEANING: DENSITY', img: 'density_types_big.png', caption: 'Types of density.', q: 'What is population density?', a: 'The average number of people per square kilometre.', noProj: 'define.' },
    { sec: '2. MEASURES', img: 'density_types_big.png', caption: 'Formula.', q: 'Calculate the density of an area of 500 km² with 25,000 people.', a: '25,000 ÷ 500 = 50 people per km².', noProj: 'calculate.' },
    { sec: '2. MEASURES', img: 'choropleth_big.png', caption: 'Density of Cameroon by region.', q: 'Distinguish dense, moderate and sparse areas.', a: 'Dense: over 100 per km²; moderate: 20 to 100; sparse: under 20.', noProj: 'classify.' },
    { sec: '2. MEASURES', img: 'density_types_big.png', caption: 'Other densities.', q: 'What is physiological density?', a: 'The number of people per square kilometre of farmland.', noProj: 'define.' },
  ],
  summary: [
    D([['Population distribution:', 'It is the way people are spread over an area.'],
      ['Population density:', 'It is the average number of people per square kilometre.']]),
    { title: '1. Measures of Population Density', intro: 'Population density is measured as follows:',
      items: [['Arithmetic density:', 'It is the total population divided by the total area.'],
        ['Physiological density:', 'It is the population divided by the area of farmland.'],
        ['Agricultural density:', 'It is the number of farmers divided by the area of farmland.']],
      draw: { img: 'density_types_big.png', caption: 'types of population density' } },
    { title: '2. Levels of Density', intro: 'Areas are classified by density as follows:',
      items: [['Dense areas:', 'They have more than 100 people per km².'],
        ['Moderate areas:', 'They have 20 to 100 people per km².'],
        ['Sparse areas:', 'They have fewer than 20 people per km².']] },
  ],
  evaluation: [['Define population density.', 'The average number of people per km².'], ['Calculate the density of 60,000 people on 1,200 km².', '60,000 ÷ 1,200 = 50 people per km².']],
  remediation: ['Density = population ÷ ______.', 'An area with under 20 people per km² is ______.', 'People per km² of farmland is ______ density.'],
  remediationAnswers: '1. area 2. sparse 3. physiological',
  homework: 'Calculate the density of Cameroon if it has 28 million people on 475,000 km².',
  hwAnswer: '28,000,000 ÷ 475,000 ≈ 59 people per km² (moderate).',
  bilingual: [['Distribution', 'La répartition'], ['Density', 'La densité'], ['Dense', 'Dense'], ['Sparse', 'Clairsemé'], ['Square kilometre', 'Le kilomètre carré'], ['Farmland', 'Les terres agricoles']],
});

L.push({ kind: 'Practical Work', no: 3, title: 'Population Densities in Cameroon', subtopic: PD,
  notions: 'Population density, choropleth map, interpretation.',
  focus: 'Calculation of population densities; interpretation of results; draw map of spatial distribution of the population densities in Cameroon.',
  competence: 'Learners are able to calculate densities, interpret them and draw a density map of Cameroon.',
  objectives: ['Calculate the population densities of the regions of Cameroon.', 'Interpret the results.', 'Draw a choropleth map of densities.'],
  recall: ['Density = population ÷ area.', 'Cameroon has ten regions.', 'A choropleth map uses shades.'],
  situation: 'The teacher gives a table of the population and area of the ten regions of Cameroon. The class must calculate the densities and map them.',
  sitQA: [['What is the problem in the situation?', 'The class must calculate and map densities.'], ['What formula is used?', 'Population ÷ area.'], ['What map will be drawn?', 'A choropleth map.']],
  justification: 'This practical work helps us to understand the population of our country with real figures.',
  action: 'Present calculations clearly and check them.',
  activities: [
    { sec: '1. CALCULATION', img: 'cmr_popdata_big.png', caption: 'Population and area of the regions (approximate).', q: 'Calculate the densities of the Littoral, the West and the Far North.', a: 'Littoral 3,850,000 ÷ 20,248 ≈ 190; West ≈ 150; Far North ≈ 130 people per km².', noProj: 'copy the table.' },
    { sec: '1. CALCULATION', img: 'cmr_popdata_big.png', caption: 'Population and area of the regions (approximate).', q: 'Calculate the densities of the East, the South and the Adamaoua.', a: 'East ≈ 11; South ≈ 17; Adamaoua ≈ 20 people per km².', noProj: 'calculate.' },
    { sec: '2. INTERPRETATION', img: 'choropleth_big.png', caption: 'Density of Cameroon by region.', q: 'Which regions are dense and which are sparse?', a: 'Dense: Littoral, West, Far North, North-West; sparse: East, South, Adamaoua.', noProj: 'classify.' },
    { sec: '2. INTERPRETATION', img: 'cmr_regions_big.png', caption: 'Regions of Cameroon.', q: 'Explain why the West and the East differ.', a: 'The West has fertile volcanic soils and a mild climate; the East has dense forest and poor roads.', noProj: 'discuss.' },
    { sec: '3. MAPPING', img: 'choropleth_big.png', caption: 'A choropleth map.', q: 'How do we draw the density map?', a: 'Group densities into classes and shade each region darker for higher density, with a key.', noProj: 'draw the map.' },
  ],
  summary: [
    { title: '1. Calculation of Population Densities', intro: 'The densities of the regions of Cameroon are calculated as follows:',
      items: [['Formula:', 'Density equals population divided by area in km².'],
        ['Dense regions:', 'The Littoral has about 190, the West 150, the Far North 130 and the North-West 125 people per km².'],
        ['Moderate regions:', 'The South-West has about 70, the Centre 67 and the North 42 people per km².'],
        ['Sparse regions:', 'The Adamaoua has about 20, the South 17 and the East 11 people per km².']],
      draw: { img: 'cmr_popdata_big.png', caption: 'data table' } },
    { title: '2. Interpretation and Mapping', intro: 'The results are interpreted and mapped as follows:',
      items: [['Interpretation:', 'Densities are high in fertile highlands, the coast and cities, and low in the forest and plateau.'],
        ['Choropleth map:', 'Each region is shaded according to its density class.'],
        ['Map elements:', 'The map needs a title, key, frame, scale and north arrow.']],
      draw: { img: 'choropleth_big.png', caption: 'density map of Cameroon' } },
  ],
  evaluation: [['Calculate the density of a region with 2,160,000 people on 17,300 km².', 'About 125 people per km².'], ['Name the densest and the least dense regions.', 'The Littoral and the East.']],
  remediation: ['The densest region of Cameroon is the ______.', 'The least dense region is the ______.', 'A map with shades by area is a ______ map.'],
  remediationAnswers: '1. Littoral 2. East 3. choropleth',
  homework: 'Draw the choropleth map of population densities of Cameroon using four classes.',
  hwAnswer: 'Classes: under 20, 20–50, 50–100, over 100 per km²; darkest for the Littoral, West, Far North and North-West; lightest for the East and South.',
  bilingual: [['Calculation', 'Le calcul'], ['Table', 'Le tableau'], ['Class', 'La classe'], ['Shade', 'La teinte'], ['Key', 'La légende'], ['Region', 'La région']],
});

L.push({ no: 30, title: 'Spatial Distribution of the World\'s Population', subtopic: PD,
  notions: 'Dense, moderate, sparse, uneven distribution.',
  focus: 'Uneven distribution (map); major areas of dense, moderate and sparse population.',
  competence: 'Learners are able to locate and explain the dense and sparse areas of the world.',
  objectives: ['Describe the uneven distribution of the world population.', 'Locate the major dense, moderate and sparse areas.', 'Explain the distribution.'],
  recall: ['Population density is people per km².', 'Asia has many people.', 'Deserts have few people.'],
  situation: 'On a world map of population, some areas like South and East Asia are dark with people, while the Sahara and Siberia are almost empty.',
  sitQA: [['What is the problem in the situation?', 'The world population is unevenly distributed.'], ['Name a dense area.', 'South or East Asia.'], ['Name a sparse area.', 'The Sahara or Siberia.']],
  justification: 'This lesson helps us to understand where people live in the world and why.',
  action: 'Create social amenities in areas of low density.',
  activities: [
    { sec: '1. UNEVEN DISTRIBUTION', img: 'world_density_big.png', caption: 'World population distribution.', q: 'Describe the world distribution of population.', a: 'It is uneven: most people live in a few regions, and large areas are almost empty.', noProj: 'use the atlas.' },
    { sec: '2. DENSE AREAS', img: 'usa_tokyo.jpg', caption: 'Tokyo.', q: 'Name four dense areas of the world.', a: 'East Asia, South Asia, Western Europe and North-East USA (also West Africa and the Nile valley).', noProj: 'locate them.' },
    { sec: '2. MODERATE AREAS', img: 'pop_share_big.png', caption: 'Share of world population.', q: 'Name two moderately populated areas.', a: 'The savannas of Africa and the pampas of South America.', noProj: 'locate them.' },
    { sec: '2. SPARSE AREAS', img: 'f2t_erg.jpg', caption: 'A sand desert.', q: 'Name three sparse areas.', a: 'Hot deserts, cold polar lands and equatorial forests (also high mountains).', noProj: 'locate them.' },
    { sec: '3. EXPLANATION', img: 'altitude_pop_big.png', caption: 'Population and altitude.', q: 'Give two reasons for dense and sparse areas.', a: 'Fertile plains and moderate climates attract people; extreme climates and poor soils repel them.', noProj: 'discuss.' },
  ],
  summary: [
    { title: '1. Uneven Distribution', intro: 'The world population is distributed as follows:',
      items: [['Uneven pattern:', 'Most people live on a small part of the land.'],
        ['Hemispheres:', 'About 90 percent of people live in the Northern Hemisphere.']],
      draw: { img: 'world_density_big.png', caption: 'world population distribution' } },
    { title: '2. Major Areas of Dense, Moderate and Sparse Population', intro: 'The main population areas are the following:',
      items: [['Dense areas:', 'East Asia, South Asia, Western Europe, North-East USA and West Africa are dense.'],
        ['Moderate areas:', 'Savannas, prairies and pampas have moderate densities.'],
        ['Sparse areas:', 'Hot deserts, polar lands, equatorial forests and high mountains are sparse.'],
        ['Reasons:', 'Relief, climate, soils, water, resources and history explain the pattern.']] },
  ],
  evaluation: [['Name two dense and two sparse areas of the world.', 'East Asia and Western Europe; the Sahara and Siberia.'], ['Give one reason for a sparse area.', 'An extreme climate (hot or cold deserts).']],
  remediation: ['The most populated continent is ______.', 'The Sahara is a ______ area.', 'Most people live in the ______ Hemisphere.'],
  remediationAnswers: '1. Asia 2. sparse 3. Northern',
  homework: 'Draw a sketch map of the world showing three dense and three sparse areas.',
  hwAnswer: 'Dense: East Asia, South Asia, Western Europe; sparse: Sahara, Siberia (or Arctic), Amazon forest, with a title and key.',
  bilingual: [['Uneven', 'Inégal'], ['Hemisphere', "L'hémisphère"], ['Desert', 'Le désert'], ['Plain', 'La plaine'], ['Polar', 'Polaire'], ['Settlement', "Le peuplement"]],
});

L.push({ no: 31, title: 'Age Composition of Population', subtopic: PS,
  notions: 'Population composition, age groups, dependency ratio.',
  focus: 'Definition of population composition; main age-groups and their demographic and economic implications.',
  competence: 'Learners are able to explain the age groups of a population and their implications.',
  objectives: ['Define population composition.', 'Identify the main age groups.', 'Explain their demographic and economic implications.'],
  recall: ['Cameroon has many children.', 'Europe has many old people.', 'Adults work to feed families.'],
  situation: 'In Cameroon, about 42 percent of the people are under 15, while in Japan about 29 percent are over 65. Both countries face different problems.',
  sitQA: [['What is the problem in the situation?', 'Countries have different age structures.'], ['Which country has many young people?', 'Cameroon.'], ['Which has many old people?', 'Japan.']],
  justification: 'This lesson helps us to understand the needs of the different age groups.',
  action: 'Acquire an education and skills to be productive.',
  activities: [
    { sec: '1. DEFINITION', img: 'pyramid_cameroon_big.png', caption: 'Age-sex pyramid of Cameroon.', q: 'What is population composition?', a: 'The characteristics of a population by age, sex, occupation and other criteria.', noProj: 'discuss.' },
    { sec: '2. MAIN AGE GROUPS', img: 'youth_ageing_big.png', caption: 'Young and ageing populations.', q: 'Name the three main age groups.', a: 'Young people (0–14), adults (15–64) and old people (65 and over).', noProj: 'list.' },
    { sec: '3. IMPLICATIONS: YOUNG', img: 'usa_children.jpg', caption: 'Children.', q: 'Give two implications of many young people.', a: 'Need for many schools and health centres, and future rapid growth.', noProj: 'discuss.' },
    { sec: '3. IMPLICATIONS: ADULTS', img: 'f2t_factory_workers.jpg', caption: 'Workers.', q: 'Why is the adult group important?', a: 'It is the active population that works and pays taxes.', noProj: 'discuss.' },
    { sec: '3. IMPLICATIONS: OLD', img: 'pyramid_japan_big.png', caption: 'Age-sex pyramid of Japan.', q: 'Give two implications of many old people.', a: 'High pension and health costs and a shortage of workers.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Population composition:', 'It is the structure of a population by age, sex and other characteristics.']]),
    { title: '1. Main Age Groups', intro: 'The population is divided into the following age groups:',
      items: [['Young people:', 'They are 0 to 14 years old and are dependants.'],
        ['Adults:', 'They are 15 to 64 years old and form the active population.'],
        ['Old people:', 'They are 65 years and above and are also dependants.']],
      draw: { img: 'youth_ageing_big.png', caption: 'young and ageing populations' } },
    { title: '2. Demographic and Economic Implications', intro: 'Each age group has the following implications:',
      items: [['Many young people:', 'Countries need more schools, health care and future jobs.'],
        ['Many adults:', 'A large workforce can boost production if jobs exist.'],
        ['Many old people:', 'Pensions and health costs rise and workers become scarce.']] },
  ],
  evaluation: [['Name the three age groups.', 'Young (0–14), adults (15–64), old (65+).'], ['Give one implication of a youthful population.', 'Need for many schools.']],
  remediation: ['People aged 15 to 64 form the ______ population.', 'Young and old people are ______.', 'Japan has an ______ population.'],
  remediationAnswers: '1. active 2. dependants 3. ageing (old)',
  homework: 'Give three needs of the young population of Cameroon.',
  hwAnswer: 'Schools and teachers, health care and vaccines, and jobs for school leavers (also sports and leisure facilities).',
  bilingual: [['Age group', "Le groupe d'âge"], ['Youth', 'La jeunesse'], ['Adult', "L'adulte"], ['Old age', 'La vieillesse'], ['Dependant', 'La personne à charge'], ['Pension', 'La pension de retraite']],
});

L.push({ no: 32, title: 'Basic Types of Age-Sex Pyramids', subtopic: PS,
  notions: 'Population pyramid, progressive, regressive, stationary.',
  focus: 'Meaning of population pyramid; types (progressive, regressive, stationary) with diagrams and examples of countries; main characteristics of each group.',
  competence: 'Learners are able to draw and interpret the types of age-sex pyramids.',
  objectives: ['Define an age-sex pyramid.', 'Draw the three types of pyramids.', 'Give the characteristics and examples of each type.'],
  recall: ['Population has age groups.', 'Cameroon has many young people.', 'Japan has many old people.'],
  situation: 'The teacher shows two pyramids: one with a wide base and a narrow top, the other narrow at the base and wide at the top. The class must name and explain them.',
  sitQA: [['What is the problem in the situation?', 'The class must interpret population pyramids.'], ['What does a wide base show?', 'Many young people (high birth rate).'], ['What does a narrow base show?', 'Few births.']],
  justification: 'This lesson helps us to read the age structure of countries.',
  action: 'Draw graphs neatly with a title, axes and key.',
  activities: [
    { sec: '1. MEANING', img: 'pyramid_cameroon_big.png', caption: 'Pyramid of Cameroon.', q: 'What is an age-sex pyramid?', a: 'A graph showing the population by age groups and sex.', noProj: 'describe.' },
    { sec: '2. PROGRESSIVE PYRAMID', img: 'pyramid_types_big.png', caption: 'Types of pyramids.', q: 'Describe a progressive pyramid and give an example.', a: 'Wide base and narrow top (high birth and death rates), as in Cameroon or Niger.', noProj: 'draw.' },
    { sec: '2. STATIONARY PYRAMID', img: 'pyramid_types_big.png', caption: 'Types of pyramids.', q: 'Describe a stationary pyramid and give an example.', a: 'Almost straight sides (low birth and death rates), as in the USA or France.', noProj: 'draw.' },
    { sec: '2. REGRESSIVE PYRAMID', img: 'pyramid_japan_big.png', caption: 'Pyramid of Japan.', q: 'Describe a regressive pyramid and give an example.', a: 'Narrow base and wider top (very low births, many old people), as in Japan or Germany.', noProj: 'draw.' },
    { sec: '3. CHARACTERISTICS', img: 'youth_ageing_big.png', caption: 'Young and ageing populations.', q: 'Which type shows a growing population?', a: 'The progressive pyramid.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Age-sex pyramid:', 'It is a graph showing the population by age groups and sex.']]),
    { title: '1. Types of Pyramids', intro: 'There are three basic types of pyramids:',
      items: [['Progressive pyramid:', 'It has a wide base and a narrow top, as in Cameroon and Niger.'],
        ['Stationary pyramid:', 'It has almost straight sides, as in the USA and France.'],
        ['Regressive pyramid:', 'It has a narrow base and a wider top, as in Japan and Germany.']],
      draw: { img: 'pyramid_types_big.png', caption: 'types of age-sex pyramids' } },
    { title: '2. Main Characteristics', intro: 'Each type has the following characteristics:',
      items: [['Progressive:', 'High birth rates, many young people and rapid growth.'],
        ['Stationary:', 'Low birth and death rates and slow growth.'],
        ['Regressive:', 'Very low birth rates, many old people and declining population.']] },
  ],
  evaluation: [['Name the three types of pyramids.', 'Progressive, stationary and regressive.'], ['Give one characteristic and one example of a progressive pyramid.', 'Wide base; Cameroon.']],
  remediation: ['A pyramid with a wide base is ______.', 'Japan has a ______ pyramid.', 'Males are shown on the ______ side.'],
  remediationAnswers: '1. progressive 2. regressive 3. left',
  homework: 'Draw the three types of age-sex pyramids and give one example of a country for each.',
  hwAnswer: 'Progressive (Cameroon), stationary (USA), regressive (Japan), each with age groups on the vertical axis, males left and females right.',
  bilingual: [['Pyramid', 'La pyramide'], ['Progressive', 'Progressive'], ['Regressive', 'Régressive'], ['Stationary', 'Stationnaire'], ['Male', 'Masculin'], ['Female', 'Féminin']],
});

L.push({ no: 33, title: 'Population Growth', subtopic: PG,
  notions: 'Birth rate, death rate, natural increase, growth rate.',
  focus: 'Meaning; determinants; measurement of population growth.',
  competence: 'Learners are able to explain and measure population growth.',
  objectives: ['Define population growth.', 'Explain its determinants.', 'Calculate the birth rate, death rate and natural increase.'],
  recall: ['Babies are born every day.', 'People die.', 'People move in and out of countries.'],
  situation: 'In a village of 2,000 people, 80 babies are born and 20 people die in one year. The chief wants to know how fast the village is growing.',
  sitQA: [['What is the problem in the situation?', 'We want to measure population growth.'], ['How many births are there?', '80.'], ['How many deaths are there?', '20.']],
  justification: 'This lesson helps us to measure the growth of population.',
  action: 'Acquire sex education and respect birth control advice.',
  activities: [
    { sec: '1. MEANING', img: 'world_growth_big.png', caption: 'World population growth.', q: 'What is population growth?', a: 'The change in the number of people in an area over time.', noProj: 'discuss.' },
    { sec: '2. DETERMINANTS', img: 'growth_factors_big.png', caption: 'Factors of growth.', q: 'Name the three determinants of population growth.', a: 'Births, deaths and migration.', noProj: 'list.' },
    { sec: '3. MEASUREMENT: BIRTH RATE', img: 'pw_indices_big.png', caption: 'Calculating indices.', q: 'Calculate the birth rate of the village.', a: '80 ÷ 2,000 × 1,000 = 40 per thousand.', noProj: 'calculate.' },
    { sec: '3. MEASUREMENT: DEATH RATE', img: 'birth_death_big.png', caption: 'Birth and death rates.', q: 'Calculate the death rate of the village.', a: '20 ÷ 2,000 × 1,000 = 10 per thousand.', noProj: 'calculate.' },
    { sec: '3. MEASUREMENT: NATURAL INCREASE', img: 'growth_rates_big.png', caption: 'Growth rates.', q: 'Calculate the natural increase rate.', a: '(40 − 10) ÷ 10 = 3 percent.', noProj: 'calculate.' },
  ],
  summary: [
    D([['Population growth:', 'It is the change in the number of people in an area over a period.']]),
    { title: '1. Determinants of Population Growth', intro: 'Population growth depends on the following:',
      items: [['Births:', 'They add people to the population.'],
        ['Deaths:', 'They remove people from the population.'],
        ['Migration:', 'Immigrants add people and emigrants remove people.']],
      draw: { img: 'growth_factors_big.png', caption: 'factors of population growth' } },
    { title: '2. Measurement of Population Growth', intro: 'Population growth is measured with the following indices:',
      items: [['Birth rate:', 'It is births divided by population times 1,000, in per thousand.'],
        ['Death rate:', 'It is deaths divided by population times 1,000, in per thousand.'],
        ['Natural increase rate:', 'It is birth rate minus death rate, divided by 10, in percent.'],
        ['Growth rate:', 'It adds net migration to the natural increase.']] },
  ],
  evaluation: [['Name the determinants of population growth.', 'Births, deaths and migration.'], ['A town of 10,000 has 350 births and 100 deaths. Calculate the natural increase rate.', 'BR 35‰, DR 10‰, NIR = 2.5 %.']],
  remediation: ['Births per 1,000 people is the ______ rate.', 'Birth rate minus death rate gives the natural ______.', 'People who leave a country are ______.'],
  remediationAnswers: '1. birth 2. increase 3. emigrants',
  homework: 'A town of 50,000 people has 1,900 births and 450 deaths in a year. Calculate the birth rate, death rate and natural increase rate.',
  hwAnswer: 'BR = 1,900 ÷ 50,000 × 1,000 = 38‰; DR = 9‰; NIR = (38 − 9) ÷ 10 = 2.9 %.',
  bilingual: [['Birth rate', 'Le taux de natalité'], ['Death rate', 'Le taux de mortalité'], ['Natural increase', "L'accroissement naturel"], ['Migration', 'La migration'], ['Per thousand', 'Pour mille'], ['Growth rate', 'Le taux de croissance']],
});

L.push({ no: 34, title: 'The Demographic Transition Model (DTM)', subtopic: PG,
  notions: 'Demographic transition, stages, birth rate, death rate.',
  focus: 'Meaning; stages (diagram); main characteristics.',
  competence: 'Learners are able to draw and explain the demographic transition model.',
  objectives: ['Define the demographic transition model.', 'Draw the DTM with its stages.', 'Give the characteristics of each stage.'],
  recall: ['Birth and death rates change over time.', 'Death rates fell with medicine.', 'Europe now has low birth rates.'],
  situation: 'In Britain, birth and death rates were high in 1700 and are low today. Cameroon is now between these two situations.',
  sitQA: [['What is the problem in the situation?', 'We want to explain how birth and death rates change.'], ['What were the rates in Britain in 1700?', 'High.'], ['What are they today?', 'Low.']],
  justification: 'This lesson helps us to understand the stages of population change of countries.',
  action: 'Support education and health, which lower birth and death rates.',
  activities: [
    { sec: '1. MEANING', img: 'dtm_big.png', caption: 'The demographic transition model.', q: 'What is the DTM?', a: 'A model showing how birth and death rates change as a country develops.', noProj: 'describe.' },
    { sec: '2. STAGES 1 AND 2', img: 'dtm_big.png', caption: 'Stages 1 and 2.', q: 'Describe stages 1 and 2.', a: 'Stage 1: high birth and death rates; stage 2: death rate falls and population grows fast.', noProj: 'draw.' },
    { sec: '2. STAGES 3 AND 4', img: 'dtm_big.png', caption: 'Stages 3 and 4.', q: 'Describe stages 3 and 4.', a: 'Stage 3: birth rate falls; stage 4: both rates are low and growth is slow.', noProj: 'draw.' },
    { sec: '2. STAGE 5', img: 'pyramid_japan_big.png', caption: 'An ageing country.', q: 'Describe stage 5.', a: 'The birth rate falls below the death rate and the population declines.', noProj: 'discuss.' },
    { sec: '3. EXAMPLES', img: 'dtm_countries_big.png', caption: 'Countries in the DTM.', q: 'Place Cameroon, Brazil and Japan in the DTM.', a: 'Cameroon: stage 2–3; Brazil: stage 3–4; Japan: stage 5.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Demographic transition model:', 'It is a model showing how birth and death rates change as a country develops.']]),
    { title: '1. Stages of the DTM', intro: 'The DTM has the following stages:',
      items: [['Stage 1 (high stationary):', 'Birth and death rates are high and growth is slow.'],
        ['Stage 2 (early expanding):', 'The death rate falls fast and the population grows rapidly.'],
        ['Stage 3 (late expanding):', 'The birth rate falls and growth slows down.'],
        ['Stage 4 (low stationary):', 'Birth and death rates are low and growth is slow.'],
        ['Stage 5 (declining):', 'The birth rate falls below the death rate and the population declines.']],
      draw: { img: 'dtm_big.png', caption: 'the demographic transition model' } },
    { title: '2. Examples of Countries', intro: 'Countries are at different stages:',
      items: [['Stages 2 and 3:', 'Most LICs such as Cameroon and Niger are here.'],
        ['Stage 4:', 'The USA and France are here.'],
        ['Stage 5:', 'Japan and Germany are here.']] },
  ],
  evaluation: [['What is the DTM?', 'A model of changing birth and death rates with development.'], ['Describe stage 2.', 'The death rate falls and the population grows rapidly.']],
  remediation: ['In stage 1, birth and death rates are ______.', 'Rapid growth happens in stage ______.', 'Japan is in stage ______.'],
  remediationAnswers: '1. high 2. 2 (two) 3. 5 (five)',
  homework: 'Draw the DTM and place Cameroon on it.',
  hwAnswer: 'A graph with birth rate and death rate lines over five stages; Cameroon at the end of stage 2 or in stage 3 (falling death rate, slowly falling birth rate).',
  bilingual: [['Transition', 'La transition'], ['Stage', 'Le stade'], ['Model', 'Le modèle'], ['Decline', 'Le déclin'], ['Development', 'Le développement'], ['Rate', 'Le taux']],
});

L.push({ no: 35, title: 'Rapid Population Growth in Least Industrialised Countries', subtopic: PG,
  notions: 'Rapid population growth, high fertility, dependency.',
  focus: 'Reasons; implications.',
  competence: 'Learners are able to explain the causes and implications of rapid population growth in LICs.',
  objectives: ['Explain the reasons for rapid population growth in LICs.', 'Explain the implications.', 'Propose solutions.'],
  recall: ['LICs have high birth rates.', 'Death rates have fallen.', 'Cameroon grows by about 2.6 percent per year.'],
  situation: 'A family in a village has nine children. The school is overcrowded and there are not enough jobs for young people.',
  sitQA: [['What is the problem in the situation?', 'Rapid population growth.'], ['How many children does the family have?', 'Nine.'], ['Give two consequences.', 'Overcrowded schools and unemployment.']],
  justification: 'This lesson helps us to understand a major challenge of developing countries.',
  action: 'Refuse early marriages and send girls to school.',
  activities: [
    { sec: '1. REASONS: HIGH BIRTH RATES', img: 'usa_children.jpg', caption: 'Children.', q: 'Give three reasons for high birth rates in LICs.', a: 'Early marriages, children as labour and security, and low use of contraception.', noProj: 'discuss.' },
    { sec: '1. REASONS: FALLING DEATH RATES', img: 'usa_clinic.jpg', caption: 'A health centre.', q: 'Why have death rates fallen in LICs?', a: 'Vaccines, better health care, clean water and more food.', noProj: 'discuss.' },
    { sec: '2. IMPLICATIONS: SOCIAL', img: 'usa_school.jpg', caption: 'A crowded classroom.', q: 'Give two social implications.', a: 'Overcrowded schools and hospitals and a shortage of housing.', noProj: 'discuss.' },
    { sec: '2. IMPLICATIONS: ECONOMIC', img: 'usa_slum.jpg', caption: 'A slum.', q: 'Give two economic implications.', a: 'Unemployment and a high dependency burden (also food shortages).', noProj: 'discuss.' },
    { sec: '2. IMPLICATIONS: ENVIRONMENTAL', img: 'usa_clearcut.jpg', caption: 'Deforestation.', q: 'Give one environmental implication.', a: 'Deforestation and soil exhaustion from pressure on land.', noProj: 'discuss.' },
  ],
  summary: [
    { title: '1. Reasons for Rapid Population Growth', intro: 'The population of LICs grows fast for the following reasons:',
      items: [['High birth rates:', 'Early marriages, polygamy and the value of children keep births high.'],
        ['Low use of contraception:', 'Religious beliefs, ignorance and cost limit family planning.'],
        ['Falling death rates:', 'Vaccines, medicine and clean water save many lives.']] },
    { title: '2. Implications', intro: 'Rapid population growth has the following implications:',
      items: [['Social:', 'Schools, hospitals and housing become overcrowded.'],
        ['Economic:', 'Unemployment, food shortages and dependency increase.'],
        ['Environmental:', 'Forests are cleared and soils are overused.'],
        ['Positive:', 'A large population can provide labour and a big market.']],
      draw: { img: 'youth_ageing_big.png', caption: 'a youthful population' } },
  ],
  evaluation: [['Give two reasons for rapid population growth in LICs.', 'Early marriages and falling death rates.'], ['Give two implications.', 'Unemployment and overcrowded schools.']],
  remediation: ['Marriage of young girls is ______ marriage.', 'Family planning reduces the ______ rate.', 'Too many people for the jobs available causes ______.'],
  remediationAnswers: '1. early 2. birth 3. unemployment',
  homework: 'Explain three ways rapid population growth affects your town.',
  hwAnswer: 'Crowded schools and hospitals, unemployment of youths, and growth of unplanned quarters (also higher food prices).',
  bilingual: [['Rapid growth', 'La croissance rapide'], ['Early marriage', 'Le mariage précoce'], ['Contraception', 'La contraception'], ['Family planning', 'La planification familiale'], ['Unemployment', 'Le chômage'], ['Overcrowding', 'Le surpeuplement']],
});

L.push({ kind: 'Further Study', no: 4, title: 'Control of Population Growth', subtopic: PG,
  notions: 'Birth control, family planning, one-child policy.',
  focus: 'Measures of birth control; population control policies in modern China: a successful case of control of population growth in the NICs.',
  competence: 'Learners are able to explain measures of birth control and assess China\'s population policy.',
  objectives: ['Explain the measures of birth control.', 'Describe the population policies of China.', 'Assess the results of the Chinese policy.'],
  recall: ['Rapid growth causes problems.', 'China has a very large population.', 'Family planning reduces births.'],
  situation: 'In 1979, China introduced a policy allowing most families only one child. Later, it allowed two and then three children because the population was ageing.',
  sitQA: [['What is the problem in the situation?', 'We want to understand how China controlled its population.'], ['What policy began in 1979?', 'The one-child policy.'], ['Why did China change it?', 'Because the population was ageing.']],
  justification: 'This further study helps us to understand how countries control population growth.',
  action: 'Acquire sex education and support responsible parenthood.',
  activities: [
    { sec: '1. MEASURES OF BIRTH CONTROL', img: 'policies_big.png', caption: 'Population policies.', q: 'Give three measures of birth control.', a: 'Contraception, education of girls and raising the marriage age.', noProj: 'list.' },
    { sec: '2. CHINA: THE ONE-CHILD POLICY', img: 'usa_onechild.jpg', caption: 'A one-child poster in China.', q: 'What was the one-child policy?', a: 'A 1979 law allowing most urban couples only one child.', noProj: 'discuss.' },
    { sec: '2. CHINA: METHODS', img: 'usa_newborn.jpg', caption: 'A newborn baby.', q: 'How was the policy applied?', a: 'Rewards for one-child families, fines for extra births and free contraception.', noProj: 'discuss.' },
    { sec: '3. RESULTS', img: 'growth_rates_big.png', caption: 'Growth rates.', q: 'Give two positive results.', a: 'About 400 million fewer births and faster economic growth.', noProj: 'discuss.' },
    { sec: '3. PROBLEMS', img: 'pyramid_japan_big.png', caption: 'An ageing pyramid.', q: 'Give two problems of the policy.', a: 'An ageing population and more boys than girls.', noProj: 'discuss.' },
  ],
  summary: [
    { title: '1. Measures of Birth Control', intro: 'Birth rates are reduced by the following measures:',
      items: [['Family planning:', 'Contraceptives are made available and affordable.'],
        ['Education:', 'Educated girls marry later and have fewer children.'],
        ['Laws and incentives:', 'Governments raise the marriage age and reward small families.']],
      draw: { img: 'policies_big.png', caption: 'population policies' } },
    { title: '2. Case Study: Population Policies in China', intro: 'China controlled its population as follows:',
      items: [['One-child policy:', 'From 1979, most couples were allowed only one child.'],
        ['Methods:', 'Rewards, fines and free contraception were used.'],
        ['Results:', 'Growth fell sharply and about 400 million births were avoided.'],
        ['Problems and changes:', 'Ageing and a surplus of boys led China to allow two children in 2016 and three in 2021.']] },
  ],
  evaluation: [['Give two measures of birth control.', 'Contraception and education of girls.'], ['Give one success and one problem of China\'s policy.', 'Slower growth; an ageing population.']],
  remediation: ['China introduced the one-child policy in ______.', 'Using pills and condoms is ______.', 'China now allows ______ children.'],
  remediationAnswers: '1. 1979 2. contraception 3. three',
  homework: 'Should Cameroon adopt a one-child policy? Give two arguments for and two against.',
  hwAnswer: 'For: slower growth, fewer pressures on schools and jobs. Against: cultural values, future ageing, and education and health work better without force.',
  bilingual: [['Birth control', 'Le contrôle des naissances'], ['One-child policy', "La politique de l'enfant unique"], ['Incentive', "L'incitation"], ['Fine', "L'amende"], ['Ageing', 'Le vieillissement'], ['Policy', 'La politique']],
});

L.push({ no: 36, title: 'Migration', subtopic: 'Population Change in Space (Migration)',
  notions: 'Immigration, emigration, net migration, standards of living.',
  focus: 'Meaning; types (internal and external); general causes; general consequences of migration at source and destination.',
  competence: 'Learners are able to explain migration, its causes and consequences.',
  objectives: ['Define migration and its types.', 'Explain the causes of migration.', 'Explain the consequences at source and destination.'],
  recall: ['Many young people leave villages for towns.', 'Some Cameroonians go abroad.', 'Refugees flee wars.'],
  situation: 'A young man leaves his village in the Far North for Douala to find work, while his cousin travels to Europe to study. Their village is left with old people.',
  sitQA: [['What is the problem in the situation?', 'People are migrating.'], ['Where does the young man go?', 'To Douala (internal migration).'], ['What is the effect on the village?', 'Only old people remain.']],
  justification: 'This lesson helps us to understand the movement of people.',
  action: 'Create social amenities in rural areas to reduce rural exodus.',
  activities: [
    { sec: '1. MEANING', img: 'migration_types_big.png', caption: 'Types of migration.', q: 'What is migration?', a: 'The movement of people from one place to another to live.', noProj: 'discuss.' },
    { sec: '2. TYPES', img: 'migration_types_big.png', caption: 'Types of migration.', q: 'Distinguish internal and external migration.', a: 'Internal migration is within a country; external migration crosses borders.', noProj: 'give examples.' },
    { sec: '2. TERMS', img: 'usa_ellis.jpg', caption: 'Immigrants arriving.', q: 'Distinguish immigration and emigration.', a: 'Immigration is entering a country; emigration is leaving it.', noProj: 'define.' },
    { sec: '3. CAUSES', img: 'usa_refugee.jpg', caption: 'Refugees.', q: 'Give two push and two pull factors.', a: 'Push: poverty and war; pull: jobs and better services.', noProj: 'list.' },
    { sec: '4. CONSEQUENCES', img: 'usa_slum.jpg', caption: 'A slum.', q: 'Give one consequence at the source and one at the destination.', a: 'Source: loss of young workers; destination: overcrowding and slums.', noProj: 'discuss.' },
  ],
  summary: [
    D([['Migration:', 'It is the movement of people from one place to another to live.'],
      ['Immigration and emigration:', 'Immigration is entering a country and emigration is leaving it.'],
      ['Net migration:', 'It is the difference between immigrants and emigrants.']]),
    { title: '1. Types and Causes of Migration', intro: 'Migration has the following types and causes:',
      items: [['Internal migration:', 'It takes place within a country, such as rural-urban migration.'],
        ['External migration:', 'It crosses international borders.'],
        ['Push factors:', 'Poverty, wars, disasters and lack of jobs push people away.'],
        ['Pull factors:', 'Jobs, schools, hospitals and security attract people.']],
      draw: { img: 'migration_types_big.png', caption: 'types of migration' } },
    { title: '2. Consequences of Migration', intro: 'Migration has the following consequences:',
      items: [['At the source:', 'Villages lose young workers but receive money sent by migrants.'],
        ['At the destination:', 'Towns gain workers but suffer overcrowding, slums and unemployment.'],
        ['Brain drain:', 'Skilled people leave poor countries for rich ones.']] },
  ],
  evaluation: [['Define migration.', 'The movement of people from one place to another to live.'], ['Give one push factor and one pull factor.', 'War; jobs.']],
  remediation: ['Leaving a country is ______.', 'Moving from villages to towns is ______ exodus.', 'The departure of skilled people is ______ drain.'],
  remediationAnswers: '1. emigration 2. rural 3. brain',
  homework: 'Interview a migrant in your area and write the causes of his or her migration.',
  hwAnswer: 'Example: came from a village to Garoua for work or school (pull), because of poor harvests or insecurity (push).',
  bilingual: [['Migration', 'La migration'], ['Immigration', "L'immigration"], ['Emigration', "L'émigration"], ['Refugee', 'Le réfugié'], ['Rural exodus', "L'exode rural"], ['Brain drain', 'La fuite des cerveaux']],
});

L.push({ no: 37, title: 'Notions on Optimum Population, Over-population and Under-population', subtopic: 'Population and Resources',
  notions: 'Optimum population, over-population, under-population, standards of living.',
  focus: 'Meaning; examples of areas; indicators.',
  competence: 'Learners are able to explain the relationship between population and resources.',
  objectives: ['Define optimum, over- and under-population.', 'Give examples of areas.', 'Give the indicators of each.'],
  recall: ['Resources feed people.', 'Some areas are crowded and poor.', 'Some areas have few people and many resources.'],
  situation: 'In a crowded village, farms are tiny and many youths leave, while a neighbouring region has fertile land but few people to farm it.',
  sitQA: [['What is the problem in the situation?', 'Population and resources are not balanced.'], ['What happens in the crowded village?', 'Farms are tiny and youths leave.'], ['What happens in the other region?', 'Land is not fully used.']],
  justification: 'This lesson helps us to understand the balance between people and resources.',
  action: 'Encourage out-migration from crowded areas and birth control.',
  activities: [
    { sec: '1. MEANING: OPTIMUM', img: 'optimum_big.png', caption: 'Optimum population.', q: 'What is optimum population?', a: 'The number of people that gives the highest standard of living with the available resources.', noProj: 'discuss.' },
    { sec: '1. MEANING: OVER-POPULATION', img: 'usa_slum.jpg', caption: 'A crowded area.', q: 'What is over-population?', a: 'Too many people for the resources available.', noProj: 'define.' },
    { sec: '1. MEANING: UNDER-POPULATION', img: 'f2t_rainforest.jpg', caption: 'A forest area.', q: 'What is under-population?', a: 'Too few people to use the resources fully.', noProj: 'define.' },
    { sec: '2. EXAMPLES', img: 'carrying_big.png', caption: 'Carrying capacity.', q: 'Give one example of an over-populated and an under-populated area.', a: 'Over-populated: Bangladesh or the Mandara Mountains; under-populated: Canada or the East Region of Cameroon.', noProj: 'discuss.' },
    { sec: '3. INDICATORS', img: 'usa_foodaid.jpg', caption: 'Food aid.', q: 'Give two indicators of over-population.', a: 'Unemployment and food shortages (also out-migration and land degradation).', noProj: 'list.' },
  ],
  summary: [
    D([['Optimum population:', 'It is the number of people that gives the highest standard of living with the available resources.'],
      ['Over-population:', 'It is a situation where there are too many people for the resources.'],
      ['Under-population:', 'It is a situation where there are too few people to use the resources fully.']]),
    { title: '1. Examples of Areas', intro: 'Examples of areas are the following:',
      items: [['Over-populated areas:', 'Bangladesh, parts of the Sahel and the Mandara Mountains are examples.'],
        ['Under-populated areas:', 'Canada, Australia and the East Region of Cameroon are examples.']],
      draw: { img: 'optimum_big.png', caption: 'optimum population' } },
    { title: '2. Indicators', intro: 'Each situation has the following indicators:',
      items: [['Over-population:', 'Unemployment, food shortages, out-migration and land degradation are signs.'],
        ['Under-population:', 'Unused resources, labour shortages and immigration are signs.'],
        ['Optimum:', 'Full employment and a high standard of living are signs.']] },
  ],
  evaluation: [['Define over-population.', 'Too many people for the resources available.'], ['Give one indicator of under-population.', 'Unused resources (labour shortage).']],
  remediation: ['The best number of people for the resources is the ______ population.', 'Canada is ______.', 'Food shortage is a sign of ______.'],
  remediationAnswers: '1. optimum 2. under-populated 3. over-population',
  homework: 'Is the East Region of Cameroon over-populated or under-populated? Justify your answer.',
  hwAnswer: 'Under-populated: about 11 people per km², large forests, minerals and farmland not fully used, and labour shortages.',
  bilingual: [['Optimum population', "L'optimum de peuplement"], ['Over-population', 'La surpopulation'], ['Under-population', 'Le sous-peuplement'], ['Resource', 'La ressource'], ['Standard of living', 'Le niveau de vie'], ['Shortage', 'La pénurie']],
});

L.push({ no: 38, title: 'Population and Resource Model (Malthus)', subtopic: 'Population and Resources',
  notions: 'Carrying capacity, standards of living, geometric and arithmetic growth.',
  focus: 'Principles; conclusions.',
  competence: 'Learners are able to explain Malthus\'s theory and assess it.',
  objectives: ['State the principles of Malthus\'s theory.', 'Draw the Malthus graph.', 'Give the conclusions and criticisms.'],
  recall: ['Population needs food.', 'Food shortages cause famine.', 'Population can grow fast.'],
  situation: 'In 1798, an English priest, Thomas Malthus, predicted that population would grow faster than food and cause famine, wars and diseases.',
  sitQA: [['What is the problem in the situation?', 'We want to understand Malthus\'s theory.'], ['Who was Malthus?', 'An English priest and economist.'], ['What did he predict?', 'Population would grow faster than food.']],
  justification: 'This lesson helps us to reflect on the balance between population and food.',
  action: 'Support both birth control and food production.',
  activities: [
    { sec: '1. PRINCIPLES', img: 'malthus_big.png', caption: 'The Malthus model.', q: 'How did Malthus say population and food grow?', a: 'Population grows geometrically (1, 2, 4, 8) and food arithmetically (1, 2, 3, 4).', noProj: 'draw.' },
    { sec: '1. PRINCIPLES', img: 'malthus_big.png', caption: 'The crisis point.', q: 'What happens when population passes food supply?', a: 'A crisis occurs: famine, diseases and wars.', noProj: 'discuss.' },
    { sec: '2. CHECKS', img: 'usa_foodaid.jpg', caption: 'Famine relief.', q: 'Distinguish positive and preventive checks.', a: 'Positive checks raise deaths (famine, war); preventive checks reduce births (late marriage).', noProj: 'define.' },
    { sec: '3. CONCLUSIONS', img: 'carrying_big.png', caption: 'Carrying capacity.', q: 'What did Malthus conclude?', a: 'Population must be controlled to avoid misery.', noProj: 'discuss.' },
    { sec: '3. CRITICISMS', img: 'boserup_big.png', caption: 'Boserup\'s view.', q: 'Give one criticism of Malthus.', a: 'Technology such as the Green Revolution increased food faster than he expected.', noProj: 'discuss.' },
  ],
  summary: [
    { title: '1. Principles of the Malthus Model', intro: 'Malthus stated the following principles in 1798:',
      items: [['Population growth:', 'Population grows geometrically, as 1, 2, 4, 8, 16.'],
        ['Food growth:', 'Food supply grows arithmetically, as 1, 2, 3, 4, 5.'],
        ['Crisis:', 'When population passes food supply, famine, diseases and wars occur.']],
      draw: { img: 'malthus_big.png', caption: 'the Malthus model' } },
    { title: '2. Conclusions and Criticisms', intro: 'Malthus concluded and was criticised as follows:',
      items: [['Positive checks:', 'Famine, diseases and wars raise death rates.'],
        ['Preventive checks:', 'Late marriage and moral restraint reduce birth rates.'],
        ['Criticisms:', 'Technology increased food production, and trade supplies food.'],
        ['Relevance:', 'Famines in some LICs show that his ideas are still discussed.']] },
  ],
  evaluation: [['State the two principles of Malthus.', 'Population grows geometrically and food arithmetically.'], ['Give one criticism.', 'Technology increased food production.']],
  remediation: ['Malthus published his theory in ______.', 'Famine and war are ______ checks.', 'Late marriage is a ______ check.'],
  remediationAnswers: '1. 1798 2. positive 3. preventive',
  homework: 'Is Malthus\'s theory relevant to Cameroon today? Give two arguments.',
  hwAnswer: 'Yes: rapid growth and food shortages in the Far North. No: Cameroon has much unused fertile land and can raise production with technology.',
  bilingual: [['Theory', 'La théorie'], ['Famine', 'La famine'], ['Food supply', "L'approvisionnement alimentaire"], ['Check', 'Le frein'], ['Geometric', 'Géométrique'], ['Arithmetic', 'Arithmétique']],
});

L.push({ no: 39, title: 'Population in Cameroon', subtopic: 'Population of Cameroon',
  notions: 'Population growth, structure, distribution.',
  focus: 'Growth pattern and structure; spatial pattern of distribution; reasons for distribution.',
  competence: 'Learners are able to describe and explain the population of Cameroon.',
  objectives: ['Describe the growth and structure of the population of Cameroon.', 'Describe its spatial distribution.', 'Explain the reasons for the distribution.'],
  recall: ['Cameroon has about 28 million people.', 'The Littoral is dense.', 'The East is sparse.'],
  situation: 'The population of Cameroon has almost quadrupled since 1976. People are crowded in the West, the Littoral and the Far North, but the East has few people.',
  sitQA: [['What is the problem in the situation?', 'We want to describe the population of Cameroon.'], ['How has the population changed?', 'It has grown very fast.'], ['Which region has few people?', 'The East.']],
  justification: 'This lesson helps us to know the population of our country.',
  action: 'Participate in planning services for the growing population.',
  activities: [
    { sec: '1. GROWTH PATTERN', img: 'cmr_growth_big.png', caption: 'Population of Cameroon.', q: 'Describe the growth of the population of Cameroon.', a: 'It grew from 7.7 million in 1976 to about 28 million today.', noProj: 'describe the graph.' },
    { sec: '1. STRUCTURE', img: 'pyramid_cameroon_big.png', caption: 'Pyramid of Cameroon.', q: 'Describe the structure of the population.', a: 'It is youthful, with a progressive pyramid and about 42 percent under 15.', noProj: 'describe.' },
    { sec: '2. SPATIAL PATTERN', img: 'choropleth_big.png', caption: 'Density by region.', q: 'Name the dense and sparse regions.', a: 'Dense: Littoral, West, Far North, North-West; sparse: East, South, Adamaoua.', noProj: 'use the map.' },
    { sec: '3. REASONS: PHYSICAL', img: 'lsa_mtcameroon.jpg', caption: 'Volcanic highlands.', q: 'Give two physical reasons for dense areas.', a: 'Fertile volcanic soils and a mild highland climate.', noProj: 'discuss.' },
    { sec: '3. REASONS: HUMAN', img: 'lsa_douala.jpg', caption: 'Douala.', q: 'Give two human reasons for dense areas.', a: 'Industries and jobs in towns, and history (old kingdoms, refuges).', noProj: 'discuss.' },
  ],
  summary: [
    { title: '1. Growth Pattern and Structure', intro: 'The population of Cameroon has the following growth and structure:',
      items: [['Growth:', 'It grew from about 7.7 million in 1976 to about 28 million today.'],
        ['Rates:', 'The birth rate is about 35 per thousand and the death rate about 9 per thousand.'],
        ['Structure:', 'The population is youthful, with about 42 percent under 15 years.']],
      draw: { img: 'pyramid_cameroon_big.png', caption: 'age-sex pyramid of Cameroon' } },
    { title: '2. Spatial Pattern of Distribution', intro: 'The population is distributed as follows:',
      items: [['Dense areas:', 'The Littoral, West, North-West and Far North are dense.'],
        ['Moderate areas:', 'The Centre, South-West and North have moderate densities.'],
        ['Sparse areas:', 'The East, South and Adamaoua are sparse.']],
      draw: { img: 'choropleth_big.png', caption: 'population density of Cameroon' } },
    { title: '3. Reasons for the Distribution', intro: 'The distribution is explained by the following reasons:',
      items: [['Physical factors:', 'Fertile volcanic soils and mild climates attract people, while dense forest repels them.'],
        ['Economic factors:', 'Towns, ports and plantations offer jobs.'],
        ['Historical factors:', 'Old kingdoms and refuges in the mountains concentrated people.']] },
  ],
  evaluation: [['Describe the structure of the population of Cameroon.', 'It is youthful with a progressive pyramid.'], ['Give two reasons for the high density of the West.', 'Fertile volcanic soils and a mild climate.']],
  remediation: ['The population of Cameroon is about ______ million.', 'The pyramid of Cameroon is ______.', 'The East is sparse because of the dense ______.'],
  remediationAnswers: '1. 28 2. progressive 3. forest',
  homework: 'Explain why the Mandara Mountains are densely populated.',
  hwAnswer: 'They served as refuges during wars and raids; the people farm the slopes with terraces; and the climate is healthier than the plains.',
  bilingual: [['Structure', 'La structure'], ['Youthful', 'Jeune'], ['Volcanic soil', 'Le sol volcanique'], ['Refuge', 'Le refuge'], ['Plantation', 'La plantation'], ['Kingdom', 'Le royaume']],
});

L.push({ no: 40, title: 'Migration Patterns in Cameroon', subtopic: 'Population of Cameroon',
  notions: 'Migration, rural exodus, push and pull factors.',
  focus: 'Pull migration zones and destinations (inter-regional migration); factors of rural exodus (push and pull factors).',
  competence: 'Learners are able to describe migration patterns in Cameroon and explain rural exodus.',
  objectives: ['Identify the main migration zones and destinations in Cameroon.', 'Explain the push and pull factors of rural exodus.', 'Propose solutions.'],
  recall: ['Migration is the movement of people.', 'Many youths leave villages.', 'Douala and Yaoundé are big towns.'],
  situation: 'Many young people from the West and the North go to Douala, Yaoundé and the plantations of the South-West. Villages are left with old people.',
  sitQA: [['What is the problem in the situation?', 'Many people migrate within Cameroon.'], ['Where do they go?', 'Douala, Yaoundé and the plantations.'], ['What is the effect on villages?', 'Only old people remain.']],
  justification: 'This lesson helps us to understand population movements in our country.',
  action: 'Create farms and cooperatives in rural areas and support rural development.',
  activities: [
    { sec: '1. DESTINATIONS', img: 'cmr_migration_big.png', caption: 'Migration in Cameroon.', q: 'Name three pull zones in Cameroon.', a: 'Douala, Yaoundé and the plantations of the South-West (also Garoua and the East mining areas).', noProj: 'use the map.' },
    { sec: '1. SOURCE AREAS', img: 'cmr_migration_big.png', caption: 'Migration flows.', q: 'Name two source regions of migrants.', a: 'The West and the Far North (also the North-West).', noProj: 'use the map.' },
    { sec: '2. PUSH FACTORS', img: 'f2t_drought.jpg', caption: 'Drought.', q: 'Give three push factors of rural exodus.', a: 'Poverty, lack of jobs and amenities, and land shortage (also insecurity and drought).', noProj: 'list.' },
    { sec: '2. PULL FACTORS', img: 'lsa_yaounde.jpg', caption: 'Yaoundé.', q: 'Give three pull factors of towns.', a: 'Jobs, schools and hospitals, and modern life (electricity, water).', noProj: 'list.' },
    { sec: '3. SOLUTIONS', img: 'f2t_mixed_farm.jpg', caption: 'A farm.', q: 'Give two solutions to rural exodus.', a: 'Create amenities in villages and support modern farming and cooperatives.', noProj: 'list.' },
  ],
  summary: [
    { title: '1. Migration Zones and Destinations', intro: 'Inter-regional migration in Cameroon follows these patterns:',
      items: [['Source regions:', 'The West, North-West and Far North send many migrants.'],
        ['Urban destinations:', 'Douala and Yaoundé attract most migrants.'],
        ['Rural destinations:', 'Plantations in the South-West and Littoral, and farmlands of the Benue valley attract migrants.']],
      draw: { img: 'cmr_migration_big.png', caption: 'migration in Cameroon' } },
    { title: '2. Factors of Rural Exodus', intro: 'Rural exodus is explained by push and pull factors:',
      items: [['Push factors:', 'Poverty, land shortage, lack of amenities, drought and insecurity push people.'],
        ['Pull factors:', 'Jobs, schools, hospitals and modern life in towns attract people.'],
        ['Solutions:', 'Rural development, amenities and cultural festivals keep people in villages.']] },
  ],
  evaluation: [['Name two destinations of migrants in Cameroon.', 'Douala and Yaoundé.'], ['Give two push and two pull factors.', 'Poverty and land shortage; jobs and schools.']],
  remediation: ['Movement from villages to towns is rural ______.', 'The biggest pull town of Cameroon is ______.', 'Lack of land in villages is a ______ factor.'],
  remediationAnswers: '1. exodus 2. Douala 3. push',
  homework: 'Propose three actions to reduce rural exodus in your region.',
  hwAnswer: 'Bring electricity, water and schools to villages; create farms, cooperatives and small industries; and organise cultural festivals.',
  bilingual: [['Rural exodus', "L'exode rural"], ['Push factor', 'Le facteur répulsif'], ['Pull factor', 'Le facteur attractif'], ['Destination', 'La destination'], ['Amenity', "L'équipement"], ['Rural development', 'Le développement rural']],
});

L.push({ kind: 'Practical Work', no: 4, title: 'Calculation of the Determinants of Population Growth (Indices)', subtopic: 'Population of Cameroon',
  notions: 'Birth rate, death rate, natural increase, growth rate.',
  focus: 'Theoretical basis (definitions of birth rate, death rate, natural growth rate and population growth); calculation of birth rate, death rate, natural population increase and population growth rate, using concrete data on the population of Cameroon.',
  competence: 'Learners are able to calculate the indices of population growth with data on Cameroon.',
  objectives: ['Recall the definitions and formulas of the indices.', 'Calculate the indices with data on Cameroon.', 'Interpret the results.'],
  recall: ['Birth rate is in per thousand.', 'Natural increase is birth rate minus death rate.', 'Migration also changes population.'],
  situation: 'The teacher gives the class approximate data on the population of Cameroon for one year. The class must calculate the growth indices and interpret them.',
  sitQA: [['What is the problem in the situation?', 'The class must calculate population indices.'], ['What data are given?', 'Population, births, deaths and migrants.'], ['What is the unit of the birth rate?', 'Per thousand.']],
  justification: 'This practical work helps us to use numbers to understand population growth.',
  action: 'Show all formulas and steps in calculations.',
  activities: [
    { sec: '1. THEORETICAL BASIS', img: 'pw_indices_big.png', caption: 'Formulas.', q: 'Give the formula of the birth rate.', a: 'Births ÷ total population × 1,000.', noProj: 'write the formulas.' },
    { sec: '2. BIRTH RATE', img: 'cmr_pw_rates_big.png', caption: 'Data on Cameroon (approximate).', q: 'Calculate the birth rate of Cameroon.', a: '980,000 ÷ 28,000,000 × 1,000 = 35 per thousand.', noProj: 'calculate.' },
    { sec: '3. DEATH RATE', img: 'cmr_pw_rates_big.png', caption: 'Data on Cameroon (approximate).', q: 'Calculate the death rate.', a: '252,000 ÷ 28,000,000 × 1,000 = 9 per thousand.', noProj: 'calculate.' },
    { sec: '4. NATURAL INCREASE', img: 'cmr_pw_rates_big.png', caption: 'Data on Cameroon (approximate).', q: 'Calculate the natural increase rate.', a: '(35 − 9) ÷ 10 = 2.6 percent.', noProj: 'calculate.' },
    { sec: '5. GROWTH RATE', img: 'cmr_pw_rates_big.png', caption: 'Data on Cameroon (approximate).', q: 'Calculate the growth rate with migration.', a: '(980,000 − 252,000 + 30,000 − 20,000) ÷ 28,000,000 × 100 ≈ 2.64 percent.', noProj: 'calculate.' },
  ],
  summary: [
    { title: '1. Theoretical Basis', intro: 'The indices of population growth are calculated as follows:',
      items: [['Birth rate:', 'It is births divided by population times 1,000.'],
        ['Death rate:', 'It is deaths divided by population times 1,000.'],
        ['Natural increase rate:', 'It is birth rate minus death rate, divided by 10, in percent.'],
        ['Growth rate:', 'It is natural increase plus net migration, divided by population, times 100.']],
      draw: { img: 'pw_indices_big.png', caption: 'formulas and example' } },
    { title: '2. Application to Cameroon', intro: 'With the data of Cameroon, the results are the following:',
      items: [['Birth rate:', 'It is 980,000 ÷ 28,000,000 × 1,000, which equals 35 per thousand.'],
        ['Death rate:', 'It is 252,000 ÷ 28,000,000 × 1,000, which equals 9 per thousand.'],
        ['Natural increase:', 'It is (35 − 9) ÷ 10, which equals 2.6 percent.'],
        ['Interpretation:', 'Cameroon grows fast and its population may double in about 27 years.']],
      draw: { img: 'cmr_pw_rates_big.png', caption: 'data on Cameroon' } },
  ],
  evaluation: [['A country of 10 million has 400,000 births and 100,000 deaths. Calculate BR, DR and NIR.', 'BR 40‰, DR 10‰, NIR 3 %.'], ['What does a natural increase of 2.6 percent mean?', 'The population grows fast and doubles in about 27 years.']],
  remediation: ['Birth rate is expressed in per ______.', 'Natural increase is expressed in ______.', 'Doubling time is about 70 ÷ growth ______.'],
  remediationAnswers: '1. thousand 2. percent 3. rate',
  homework: 'A town of 400,000 people has 14,000 births, 3,600 deaths, 5,000 immigrants and 1,000 emigrants in a year. Calculate all the indices.',
  hwAnswer: 'BR = 35‰; DR = 9‰; NIR = 2.6 %; growth rate = (14,000 − 3,600 + 4,000) ÷ 400,000 × 100 = 3.6 %.',
  bilingual: [['Index', "L'indice"], ['Formula', 'La formule'], ['Birth', 'La naissance'], ['Death', 'Le décès'], ['Immigrant', "L'immigrant"], ['Doubling time', 'Le temps de doublement']],
});

module.exports = { B, L };
