// LOWER SIXTH ARTS — Geography of Cameroon, lessons 6–10 (population, towns, agriculture, forests, minerals and energy)
// Syllabus 2019: M4 FS1, M5 FS1, M6 FS1, M6 FS2, M6 FS3. Guided by the teacher's course notes (LSA/USA_CAM_GEO_2026).
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'LSA', code: 'CAM', folder: 'Geography of Cameroon', module: 'Geography of Cameroon', topicDefault: 'Geography of Cameroon', branch: 'Population, Settlement and Resources of Cameroon',
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Geography of Cameroon.', 'Teacher\'s course notes: Mr KAMDEM E., Cameroon Geography (LSA and USA), GBHS Garoua, 2026.', 'BUCREP, 3rd General Census of Population and Housing (2005); United Nations, World Population Prospects (2024 revision).'] };
const L = [];

L.push({ no: 6, title: 'Population Change in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon',
  notions: 'Demographic characteristics, census, growth rate, age-sex structure, population pyramid, density, migration, push and pull factors.',
  focus: 'Demographic characteristics (evolution in numbers and growth rate, age-sex distribution and pyramid type); population distribution (densities and their spatial variation, factors); major migration trends (inter-regional and rural-urban; pre- and post-independence; causes and effects).',
  competence: 'Learners are able to describe the population of Cameroon, explain its uneven distribution and analyse its main migrations.',
  objectives: ['Describe the evolution of the population of Cameroon and its growth rate.', 'Describe the age-sex structure and the type of pyramid of Cameroon.', 'Explain the spatial variation of population densities.', 'Analyse the major migration trends, their causes and effects.'],
  recall: ['Population density = population ÷ area.', 'The natural increase is the difference between births and deaths.', 'Migration is a movement of people to live in another place.'],
  situation: 'Aïssatou lives in a quarter of Garoua where her neighbours come from everywhere: a family from Maroua, civil servants from Yaoundé and farmers from the Mandara Mountains. She also notices that some quarters are crowded while others are almost empty. She asks: "Why is the population of Cameroon growing so fast, why is it so unevenly spread, and why do people move so much?"',
  sitQA: [['What is the problem in the situation?', 'Aïssatou wants to understand the growth, the distribution and the migrations of the population of Cameroon.'],
    ['Where do Aïssatou\'s neighbours come from?', 'From Maroua, Yaoundé and the Mandara Mountains.'],
    ['What do we call the movement of people to live elsewhere?', 'Migration.']],
  justification: 'This lesson helps us to understand the population of Cameroon, which is the basis of planning schools, health, jobs and housing.',
  action: 'Use population data to explain the needs of your region in schools, jobs and health.',
  activities: [
    { sec: '1. DEMOGRAPHIC CHARACTERISTICS', img: 'cmr_growth_big.png', caption: 'The growth of the population of Cameroon.', q: 'How has the population of Cameroon changed since 1960?', a: 'It has grown very fast, from about 5 million to about 29 million.', noProj: 'write the census figures on the board.' },
    { sec: '1. DEMOGRAPHIC CHARACTERISTICS', img: 'pyramid_cameroon_big.png', caption: 'The population pyramid of Cameroon.', q: 'What does the wide base of this pyramid show?', a: 'A high birth rate and a very young population.', noProj: 'draw a triangle-shaped pyramid.' },
    { sec: '2. POPULATION DISTRIBUTION', img: 'cmr_popdata_big.png', caption: 'Population and area of the regions.', q: 'Which region has the lowest density: the Littoral or the East?', a: 'The East (about 11 people per km², against about 190 in the Littoral).', noProj: 'calculate one density.' },
    { sec: '3. MIGRATION TRENDS', img: 'cmr_migration_big.png', caption: 'Main migrations in Cameroon.', q: 'Towards which towns do most migrants of Cameroon go?', a: 'Douala and Yaoundé.', noProj: 'draw arrows on a sketch map.' },
    { sec: '3. MIGRATION TRENDS', img: 'usa_refugee.jpg', caption: 'Displaced people in a camp.', q: 'Why have many people left parts of the Far North since 2014?', a: 'Because of the insecurity caused by Boko Haram attacks.', noProj: 'discuss forced migration.' },
  ],
  summary: [
    D([['Census:', 'It is the official counting of the whole population of a country at a given date.'],
      ['Growth rate:', 'It is the yearly increase of a population, in per cent.'],
      ['Population pyramid:', 'It is a graph showing the population by age groups and sex.'],
      ['Population density:', 'It is the average number of people per km².'],
      ['Migration:', 'It is the movement of people from one place to another to live there.']]),
    { title: '1. Demographic Characteristics', sub: 'A) Evolution in Numbers and Growth Rate', intro: 'The evolution of the population of Cameroon and its causes are the following:',
      items: [['Censuses:', ['1976: about 7.7 million.', '1987: about 10.5 million.', '2005: about 17.5 million (17,463,836).'], 'cmr_growth_big.png', 'the growth of the population'],
        ['Present population:', 'It is estimated at about 29 million in 2024 (United Nations).'],
        ['High growth rate:', 'The population grows by about 2.6 % per year, so it doubles in about 27 years.'],
        ['High birth rate:', 'The birth rate is about 34 ‰, because of early marriage, the value placed on large families and low use of family planning.'],
        ['Falling death rate:', 'The death rate has fallen to about 8 ‰ thanks to vaccination, health care and better nutrition.']] },
    { title: '1. Demographic Characteristics', sub: 'B) Age-Sex Distribution and Pyramid Type', intro: 'The age-sex structure of the population of Cameroon is the following:',
      items: [['Young population:', 'About 42 % of the people are under 15 years, and only about 3 % are 65 or older.', 'pyramid_cameroon_big.png', 'the population pyramid of Cameroon'],
        ['Expansive pyramid:', 'The pyramid has a wide base and a narrow top, typical of a developing country with high fertility.'],
        ['High dependency:', 'Many young dependants rely on a smaller working population.'],
        ['Sex ratio:', 'Men and women are nearly equal in number, but towns and plantation areas have more men, and rural areas that lose migrants have more women.']] },
    { title: '2. Population Distribution', sub: 'A) Densities and Their Spatial Variation', intro: 'The population densities of Cameroon and their variation are the following:',
      items: [['Average density:', 'The average density is about 60 people per km².', 'cmr_popdata_big.png', 'population and area of the regions'],
        ['High densities (above 100 per km²):', 'The Littoral (Douala), the West, the North-West and the plains of the Far North.'],
        ['Moderate densities (40–70 per km²):', 'The Centre (with Yaoundé), the South-West and the North.'],
        ['Low densities (below 25 per km²):', 'The Adamawa, the South and especially the East (about 11 per km²).'],
        ['Towns:', 'Douala and Yaoundé alone contain about a quarter of the population.']] },
    { title: '2. Population Distribution', sub: 'B) Factors of Distribution', intro: 'The distribution of population is explained by the following factors:',
      items: [['Physical factors:', 'Fertile volcanic soils and a cool, healthy climate attract dense populations to the Western Highlands, while dense forest, poor soils and tsetse flies repel people in the East.'],
        ['Economic factors:', 'Ports, industries and administration attract people to Douala and Yaoundé, and plantations attract them to the South-West and the Mungo.'],
        ['Historical factors:', 'Slave raids pushed peoples into refuge areas such as the Mandara Mountains, and colonial rulers developed the coast first.'],
        ['Political and social factors:', 'Security, roads and social amenities attract people, while insecurity in the Far North and the North-West and South-West has displaced many.']] },
    { title: '3. Major Migration Trends', sub: 'A) Inter-Regional and Rural-Urban Movements', intro: 'The main migration trends are the following:',
      items: [['Highlands to lowlands:', 'People of the West and North-West have long moved to the coastal lowlands (Mungo, South-West, Douala) to work on plantations and in towns.', 'cmr_migration_big.png', 'main migrations in Cameroon'],
        ['Mountains to plains in the north:', 'Mountain peoples of the Mandara have moved down to the plains, and settlers from the Far North were moved to the Benue valley (Nord-Est Bénoué project).'],
        ['North to south:', 'Young people move from the northern regions to Yaoundé and Douala for jobs and studies.'],
        ['Rural-urban migration:', 'People leave villages for towns everywhere, which explains the fast growth of towns.'],
        ['Forced migrations:', 'Since 2014 (Boko Haram) and 2016 (crisis in the North-West and South-West), many people have fled to safer towns and regions.']] },
    { title: '3. Major Migration Trends', sub: 'B) Pre- and Post-Independence Migrations', intro: 'The migrations before and after independence are the following:',
      items: [['Before independence:', 'The Germans and then the British and French recruited, often by force, workers for coastal plantations, ports and railways.'],
        ['After independence:', 'Rural exodus to towns became the main movement, together with movements to new agricultural schemes and mining areas.']] },
    { title: '3. Major Migration Trends', sub: 'C) Causes and Effects', intro: 'Migrations have the following causes and effects:',
      items: [['Push factors:', 'Land shortage, poverty, lack of jobs and amenities, drought and insecurity.'],
        ['Pull factors:', 'Jobs, schools, hospitals, electricity and the attraction of town life.'],
        ['Effects at the source:', 'Loss of young workers, fewer farm workers, more women and old people, but money sent home by migrants.'],
        ['Effects at the destination:', 'Labour for industries and plantations and cultural mixing, but overcrowding, slums, unemployment and pressure on services.']] },
  ],
  evaluation: [['Give the population of Cameroon at the 2005 census and today.', 'About 17.5 million in 2005 and about 29 million in 2024.'], ['Give one physical factor of the high density of the Western Highlands.', 'Fertile volcanic soils (or a cool, healthy climate).']],
  remediation: ['Cameroon has an ______ (wide-based) population pyramid.', 'The least densely populated region of Cameroon is the ______.', 'Movement from villages to towns is called ______ migration.'],
  remediationAnswers: '1. expansive 2. East 3. rural-urban',
  homework: 'Name the two largest towns of Cameroon.',
  hwAnswer: 'Douala, the economic capital, and Yaoundé, the political capital.',
  bilingual: [['Census', 'Le recensement'], ['Growth rate', 'Le taux de croissance'], ['Population pyramid', 'La pyramide des âges'], ['Density', 'La densité'], ['Migration', 'La migration'], ['Rural exodus', "L'exode rural"], ['Displaced person', 'Le déplacé'], ['Birth rate', 'Le taux de natalité']],
});

L.push({ no: 7, title: 'Urbanisation in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon',
  notions: 'Urbanisation, urban growth, urban hierarchy, primate city, site, situation, function, hinterland, urban problems.',
  focus: 'Spatial distribution and ranking of urban centres; increasing urbanisation since colonial times and its factors; site and situation of two major towns (Douala and Garoua); functions and linkages with their hinterlands; urban problems, their causes, solutions and difficulties.',
  competence: 'Learners are able to explain the growth of towns in Cameroon, describe the site, situation and functions of towns and propose solutions to urban problems.',
  objectives: ['Explain the increase of urbanisation since colonial times and its factors.', 'Describe the distribution and ranking of urban centres.', 'Describe the site, situation and functions of Douala and Garoua.', 'Explain the links between towns and their hinterlands.', 'Analyse urban problems, solutions and difficulties.'],
  recall: ['Many young people move from villages to towns.', 'Douala and Yaoundé are the largest towns of Cameroon.', 'Towns offer jobs and services.'],
  situation: 'Saratou comes from a village near Lagdo to study in Garoua. She is amazed by the crowds, the cars and the moto-taxis, but she also sees waste in the gutters and crowded quarters. She says: "In my village, most young people have left." She asks: "Why is everybody moving to town, and how can a town like Garoua cope with so many people?"',
  sitQA: [['What is the problem in the situation?', 'Saratou does not know why towns grow so fast and how they cope with their problems.'],
    ['What does Saratou see in Garoua?', 'Crowds, cars, moto-taxis, waste and crowded quarters.'],
    ['What is happening in her village?', 'Most young people have left (rural exodus).']],
  justification: 'This lesson helps us to understand the growth of our towns and to take part in solving urban problems.',
  action: 'Respect town-planning rules, keep your quarter clean and use public spaces responsibly.',
  activities: [
    { sec: '1. SPATIAL DISTRIBUTION AND RANKING', img: 'cmr_towns_big.png', caption: 'The main towns of Cameroon.', q: 'Which two towns are much larger than all the others?', a: 'Douala and Yaoundé.', noProj: 'list towns by size.' },
    { sec: '2. INCREASING URBANISATION', img: 'lsa_yaounde.jpg', caption: 'Yaoundé.', q: 'Why do many young people leave villages for towns?', a: 'To find jobs, schools, hospitals and modern services.', noProj: 'discuss rural exodus.' },
    { sec: '3. SITE AND SITUATION', img: 'douala_site_big.png', caption: 'The site of Douala.', q: 'On what kind of land is Douala built?', a: 'On a low, swampy plain at the estuary of the Wouri.', noProj: 'draw the Wouri estuary.' },
    { sec: '4. FUNCTIONS AND HINTERLAND', img: 'f2t_cattle_market.jpg', caption: 'A cattle market.', q: 'What does Garoua receive from its hinterland?', a: 'Food, cattle, cotton and labour.', noProj: 'list products in the Garoua market.' },
    { sec: '5. URBAN PROBLEMS', img: 'usa_traffic.jpg', caption: 'Traffic in an African city.', q: 'Give one cause of traffic jams in Douala.', a: 'Narrow roads for a fast-growing number of vehicles.', noProj: 'describe traffic in Garoua.' },
  ],
  summary: [
    D([['Urbanisation:', 'It is the increase in the proportion of a country\'s population living in towns.'],
      ['Urban growth:', 'It is the increase in the size and number of people of a town.'],
      ['Site:', 'It is the land on which a town is built.'],
      ['Situation:', 'It is the position of a town in relation to its surroundings (rivers, routes, resources, other towns).'],
      ['Hinterland:', 'It is the area around a town that it serves and from which it draws food, labour and raw materials.']]),
    { title: '1. Spatial Distribution and Ranking of Urban Centres', intro: 'The distribution and ranking of towns in Cameroon are the following:',
      items: [['Distribution:', 'Towns are most numerous in the coastal lowlands and Western Highlands, fewer in the forest south and east, and grouped along main roads in the north.', 'cmr_towns_big.png', 'the main towns of Cameroon'],
        ['First order (dual primacy):', 'Douala (economic capital) and Yaoundé (political capital) each have about 4 million people.'],
        ['Second order:', 'Regional capitals such as Garoua, Maroua, Bamenda, Bafoussam and Ngaoundéré.'],
        ['Third order:', 'Divisional and industrial towns such as Kumba, Nkongsamba, Edéa, Kribi and Guider.']] },
    { title: '2. Increasing Urbanisation and Its Factors', intro: 'The growth of urbanisation since colonial times and its factors are the following:',
      items: [['Rapid increase:', 'The urban share rose from about 14 % in 1960 to about 49 % in 2005 and about 59 % today.', 'lsa_douala.jpg', 'Douala'],
        ['Colonial origins:', 'Towns grew as ports, administrative posts and railway stations, such as Douala, Yaoundé and Ngaoundéré.'],
        ['Rural exodus:', 'Poverty, land shortage and lack of amenities push people from villages.'],
        ['Pull of towns:', 'Jobs, schools, universities, hospitals and electricity attract people.'],
        ['Administration and natural increase:', 'The creation of regions and divisions has made new towns grow, and many children are born in towns.']] },
    { title: '3. Site and Situation', sub: 'A) Douala', intro: 'Douala has the following site and situation:',
      items: [['Site:', 'A low, flat, swampy plain on both banks of the Wouri estuary, easily flooded.', 'douala_site_big.png', 'the site of Douala'],
        ['Situation:', 'On the Atlantic coast, at the end of the railway and main roads, it is the gateway of Cameroon, Chad and the Central African Republic.']] },
    { title: '3. Site and Situation', sub: 'B) Garoua', intro: 'Garoua has the following site and situation:',
      items: [['Site:', 'A flat plain on the right bank of the Benue, dominated by small hills.', 'f2t_benue.jpg', 'the Benue at Garoua'],
        ['Situation:', 'On the main road (N1) between Ngaoundéré and Maroua, near Nigeria and Chad, and on the seasonally navigable Benue.']] },
    { title: '4. Functions and Linkages with the Hinterland', intro: 'The functions of Douala and Garoua and their links with their hinterlands are the following:',
      items: [['Functions of Douala:', 'Port, industry, trade, banking, transport (airport, railway terminus).'],
        ['Functions of Garoua:', 'Regional capital, cotton and textile industries (SODECOTON, CICAM), trade, river port, international airport and university.'],
        ['What the hinterland gives:', 'Food, cattle, cotton, fuelwood and labour.', 'f2t_cattle_market.jpg', 'a cattle market'],
        ['What the town gives:', 'Markets, manufactured goods, jobs, hospitals, schools, banks and administration.']] },
    { title: '5. Urban Problems and Their Causes', intro: 'Towns such as Douala, Yaoundé and Garoua face the following problems:',
      items: [['Housing and slums:', 'Rapid growth creates crowded, unplanned quarters such as New Bell (Douala) and Briqueterie (Yaoundé), often in flood-prone areas.', 'usa_slum.jpg', 'a crowded, unplanned quarter'],
        ['Traffic congestion:', 'Narrow roads and a fast-growing number of cars and moto-taxis cause traffic jams and accidents.', 'usa_traffic.jpg', 'traffic in an African city'],
        ['Unemployment:', 'Many migrants find only informal jobs (street selling, moto-taxis).'],
        ['Waste and floods:', 'Uncollected waste blocks drains and causes floods and diseases such as cholera.'],
        ['Shortage of services:', 'Water, electricity, schools and health services cannot follow population growth.'],
        ['Insecurity:', 'Poverty and unemployment favour crime.']] },
    { title: '6. Solutions and Difficulties', intro: 'The solutions proposed and their difficulties are the following:',
      items: [['Housing:', 'The SIC and MAETUR build social housing and prepare serviced plots.'],
        ['Roads and transport:', 'New roads, flyovers and bus services are built, especially in Douala and Yaoundé.'],
        ['Waste:', 'HYSACAM collects waste, and councils clean drains.'],
        ['Decentralisation:', 'City and local councils receive more powers to manage their towns and develop secondary towns.'],
        ['Difficulties:', 'Lack of funds, poor planning, corruption, land disputes and illegal building limit these solutions.']] },
  ],
  evaluation: [['Distinguish between the site and the situation of a town.', 'The site is the land on which the town is built; the situation is its position in relation to its surroundings.'], ['Give two urban problems of Douala and one solution.', 'Floods and traffic congestion; drainage works (or new roads).']],
  remediation: ['The increase in the share of people living in towns is ______.', 'Douala and Yaoundé form a case of dual ______.', 'The area served by a town is its ______.'],
  remediationAnswers: '1. urbanisation 2. primacy 3. hinterland',
  homework: 'Name two agro-industrial companies of Cameroon.',
  hwAnswer: 'SODECOTON (cotton) and the CDC (bananas, rubber, oil palm); also SEMRY (rice) and PAMOL (oil palm).',
  bilingual: [['Town', 'La ville'], ['Urbanisation', "L'urbanisation"], ['Site', 'Le site'], ['Situation', 'La situation'], ['Hinterland', "L'arrière-pays"], ['Slum', 'Le bidonville'], ['Traffic jam', "L'embouteillage"], ['Waste', 'Les déchets']],
});

L.push({ no: 8, title: 'Agricultural Development and Change in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon',
  notions: 'Agriculture, peasant farming, plantation, livestock farming, intensive, extensive, yield, second-generation agriculture.',
  focus: 'General characteristics, types, productivity and importance of agriculture; systems (peasant crop production, modern plantations, traditional and modern livestock farming) and their spatial distribution; factors; impacts; problems and solutions; changes since independence.',
  competence: 'Learners are able to describe the agricultural systems of Cameroon, explain their distribution and propose solutions to agricultural problems.',
  objectives: ['Explain the characteristics and importance of agriculture in Cameroon.', 'Describe the agricultural systems and their distribution.', 'Explain the factors that influence agriculture.', 'Analyse the impacts and problems of agriculture and their solutions.', 'Describe the changes in agriculture since independence.'],
  recall: ['Most people in rural areas are farmers.', 'Cotton is the main cash crop of the North.', 'SODECOTON buys cotton from farmers.'],
  situation: 'Near Garoua, old Mallam Issa grows millet and sorghum on a small plot with a hoe and his family\'s help, mostly to feed his family. His neighbour\'s son Abdou works for SODECOTON, where cotton is grown with selected seeds, fertilisers and tractors and sold for export. Abdou asks: "Why are there such different ways of farming in Cameroon, and how can our agriculture improve?"',
  sitQA: [['What is the problem in the situation?', 'Abdou wants to understand the different farming systems and how agriculture can improve.'],
    ['What does Mallam Issa grow and why?', 'Millet and sorghum, mainly to feed his family.'],
    ['What does SODECOTON produce?', 'Cotton for sale and export.']],
  justification: 'This lesson helps us to understand agriculture, the main activity of Cameroonians, and the changes needed to feed the nation.',
  action: 'Support modern, sustainable farming and protect farmland from erosion.',
  activities: [
    { sec: '1. GENERAL CHARACTERISTICS', img: 'usa_womenfarm.jpg', caption: 'Women working on a farm.', q: 'Which tools do most peasant farmers use?', a: 'Simple tools such as hoes and cutlasses.', noProj: 'list farm tools.' },
    { sec: '2. AGRICULTURAL SYSTEMS', img: 'cmr_agri_big.png', caption: 'Agricultural regions of Cameroon.', q: 'Which crops dominate the north of Cameroon?', a: 'Cotton, millet, sorghum and groundnuts, with cattle rearing.', noProj: 'shade farming regions.' },
    { sec: '2. AGRICULTURAL SYSTEMS', img: 'lsa_oilpalm.jpg', caption: 'An oil palm plantation.', q: 'What is special about a plantation?', a: 'It is a very large farm growing one cash crop for sale, with hired workers and much capital.', noProj: 'name plantations.' },
    { sec: '2. AGRICULTURAL SYSTEMS', img: 'usa_herders.jpg', caption: 'Herders with cattle.', q: 'Why do Mbororo herders move with their cattle in the dry season?', a: 'To find grass and water (transhumance).', noProj: 'describe transhumance.' },
    { sec: '5. CHANGES SINCE INDEPENDENCE', img: 'f2t_field_trial.jpg', caption: 'A research field.', q: 'How does IRAD help farmers?', a: 'It creates improved seeds and teaches better methods.', noProj: 'name improved crops.' },
  ],
  summary: [
    D([['Agriculture:', 'It is the growing of crops and the rearing of animals for food, income and raw materials.'],
      ['Peasant farming:', 'It is small-scale farming by families, mainly for their own food.'],
      ['Plantation:', 'It is a very large farm that specialises in one cash crop for sale, with much capital and hired labour.'],
      ['Yield:', 'It is the quantity produced per hectare or per animal.']]),
    { title: '1. General Characteristics, Types, Productivity and Importance', intro: 'The characteristics, types, productivity and importance of agriculture in Cameroon are the following:',
      items: [['Characteristics:', 'It is dominated by small family farms using simple tools, rainfall and little capital, beside a few large plantations.', 'usa_womenfarm.jpg', 'peasant farming'],
        ['Types:', 'Food crops (cassava, maize, plantain, sorghum), cash crops (cocoa, coffee, cotton, bananas, rubber, oil palm) and livestock (cattle, sheep, goats, poultry).'],
        ['Productivity:', 'Yields are generally low on peasant farms and high on plantations.'],
        ['Importance:', 'It employs over 40 % of workers (most rural people), provides food, supplies raw materials to industries and earns export revenue; Cameroon is one of the world\'s leading cocoa producers.']] },
    { title: '2. Agricultural Systems and Their Distribution', sub: 'A) Crop Production by Peasants', intro: 'Peasant crop production has the following characteristics:',
      items: [['Farm size and ownership:', 'Small plots (often under 2 ha) owned by families or held under customary law.', 'cmr_agri_big.png', 'agricultural regions of Cameroon'],
        ['Labour and capital:', 'Family labour, hoes and cutlasses, little money.'],
        ['Methods:', 'Shifting cultivation and bush fallowing in the forest, permanent farming with manure in dense areas, terraces in the Mandara Mountains.'],
        ['Purpose and products:', 'Mainly food for the family, with some cash crops: cocoa and coffee in the south and west, cotton in the north.']] },
    { title: '2. Agricultural Systems and Their Distribution', sub: 'B) Modern Plantation Systems', intro: 'The characteristics and location of modern plantations are the following:',
      items: [['Farm size and ownership:', 'Estates of hundreds or thousands of hectares owned by the state or companies (CDC, SOCAPALM, PAMOL, PHP, SOSUCAM).', 'lsa_oilpalm.jpg', 'an oil palm plantation'],
        ['Labour and capital:', 'Many paid workers, machines, fertilisers, pesticides and processing factories.'],
        ['Location:', 'Mainly in the fertile coastal lowlands (South-West, Littoral, Mungo) and near Mbandjock (sugar cane).'],
        ['Purpose and products:', 'Bananas, rubber, oil palm, tea and sugar cane, mainly for export and industry.']] },
    { title: '2. Agricultural Systems and Their Distribution', sub: 'C) Livestock Farming Systems', intro: 'The traditional and modern livestock systems and their main areas are the following:',
      items: [['Traditional (extensive):', 'Nomadism and transhumance by Mbororo and Fulani herders in the Adamawa, North, Far North and North-West, with large herds and little capital.', 'usa_herders.jpg', 'herders and cattle'],
        ['Modern (intensive):', 'Ranches with fenced pastures and veterinary care, such as SODEPA ranches in the Adamawa, and modern poultry and pig farms near towns.'],
        ['Main areas:', 'The Adamawa Plateau is the main cattle region, free of tsetse flies at high altitude.']] },
    { title: '3. Factors of Agricultural Systems', intro: 'The characteristics and distribution of farming depend on the following factors:',
      items: [['Physical factors:', 'Climate (cocoa in the wet south, cotton and sorghum in the dry north), soils (volcanic and black soils) and relief (terraces on slopes).'],
        ['Human factors:', 'Population density, land tenure and farming traditions.'],
        ['Economic inputs:', 'Capital, credit, roads, markets, machines, fertilisers and research.'],
        ['Cultural influences:', 'Cattle are a sign of wealth among the Fulani, and some groups prefer certain crops.']] },
    { title: '4. Impacts, Problems and Solutions', sub: 'A) Impacts of Agriculture', intro: 'Agriculture has the following impacts:',
      items: [['On the economy and communities:', 'Employment, export revenue, food supply and better living standards for farmers.'],
        ['On the environment:', 'Deforestation, soil erosion, bush fires, overgrazing and pollution by fertilisers and pesticides.']] },
    { title: '4. Impacts, Problems and Solutions', sub: 'B) Problems and Solutions', intro: 'Agriculture faces the following problems and solutions:',
      items: [['Physical problems:', 'Drought and irregular rain in the north, poor leached soils in the south, floods, pests (locusts, caterpillars) and diseases.'],
        ['Man-made problems:', 'Land tenure disputes, small farms, simple techniques, bad roads, poor storage and low, unstable prices.'],
        ['Solutions:', 'Irrigation, improved seeds, fertilisers, credit, farm roads, storage facilities, cooperatives and training by extension workers.']] },
    { title: '5. Changes and Reforms since Independence', intro: 'Agriculture has changed in the following ways:',
      items: [['State agro-industrial companies:', 'SODECOTON (cotton), CDC (plantations), SEMRY (rice), UNVDA (rice at Ndop) and SODECAO (cocoa) organise production.'],
        ['Green Revolution (1970s):', 'The state promoted intensification with improved seeds, fertilisers and credit.'],
        ['Research:', 'IRAD develops higher-yielding, disease-resistant varieties of maize, sorghum, cassava and cotton.', 'f2t_field_trial.jpg', 'a research field'],
        ['Liberalisation (1990s):', 'The state withdrew from marketing, and farmers formed cooperatives and common initiative groups (CIGs).'],
        ['Second-generation agriculture:', 'Since 2011 the state promotes modern, mechanised and commercial farming by young farmers and agro-industries.']] },
  ],
  evaluation: [['Give two differences between peasant farming and plantations.', 'Peasant farms are small with family labour and produce mainly food; plantations are huge, use hired labour and capital and produce cash crops for sale.'], ['Give two problems of agriculture in the North and one solution.', 'Drought and poor storage; irrigation (or improved storage).']],
  remediation: ['The company that organises cotton farming is ______.', 'Moving herds seasonally in search of pasture is ______.', 'The research institute that creates improved seeds is ______.'],
  remediationAnswers: '1. SODECOTON 2. transhumance 3. IRAD',
  homework: 'Name two valuable timber species of Cameroon.',
  hwAnswer: 'Examples: sapele, iroko, ayous, moabi, azobé and ebony.',
  bilingual: [['Agriculture', "L'agriculture"], ['Peasant farming', "L'agriculture paysanne"], ['Plantation', 'La plantation'], ['Yield', 'Le rendement'], ['Livestock', 'Le bétail'], ['Irrigation', "L'irrigation"], ['Cooperative', 'La coopérative'], ['Cash crop', 'La culture de rente']],
});

L.push({ no: 9, title: 'Management of Forest Resources in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon',
  notions: 'Forest resource, timber, non-timber forest products, logging, forest management unit, community forest, conservation, deforestation.',
  focus: 'Types and distribution of forests; resources and ownership; exploitation (stakeholders, large- and small-scale methods, localities); uses including fuel; problems of exploitation and over-exploitation; socio-economic impacts; environmental role; conservation and management measures; reserves and the role of government.',
  competence: 'Learners are able to explain how the forests of Cameroon are exploited and propose measures for their sustainable management.',
  objectives: ['Describe the types, distribution, resources and ownership of forests.', 'Describe the exploitation of forests: stakeholders, methods and localities.', 'Explain the problems of exploitation and the impacts of forests.', 'Describe the conservation and management measures.'],
  recall: ['The rainforest covers the south of Cameroon.', 'Sapele and iroko are valuable timbers.', 'Many households cook with firewood and charcoal.'],
  situation: 'Binta helps her mother cook with charcoal in Garoua. Her mother complains that the price of a bag of charcoal has risen again, because the sellers now go far into the bush to find trees, and the land around the town is becoming bare. Binta asks: "Who owns the trees, why are we using them so fast, and how can our forests be managed so that they last?"',
  sitQA: [['What is the problem in the situation?', 'The trees near Garoua are disappearing, and Binta wants to know how forests can be managed sustainably.'],
    ['Why has the price of charcoal risen?', 'Sellers must go farther to find trees, so transport costs more.'],
    ['What happens to the land around the town?', 'It becomes bare (deforestation).']],
  justification: 'This lesson helps us to understand the value of our forests and our role in protecting them.',
  action: 'Use improved stoves, plant trees and respect protected areas.',
  activities: [
    { sec: '1. TYPES AND RESOURCES', img: 'cmr_forest_big.png', caption: 'Forests and timber in Cameroon.', q: 'In which region is logging most intensive?', a: 'The East (also the South and the Centre).', noProj: 'shade the forest zone.' },
    { sec: '2. EXPLOITATION', img: 'f2t_logging_truck.jpg', caption: 'A lorry carrying logs.', q: 'Who carries out large-scale logging?', a: 'Logging companies holding concessions from the state.', noProj: 'name logging towns.' },
    { sec: '2. EXPLOITATION', img: 'f2t_charcoal.jpg', caption: 'Bags of charcoal.', q: 'Which forest product is the main source of energy for most households?', a: 'Fuelwood and charcoal.', noProj: 'ask how families cook.' },
    { sec: '3. PROBLEMS AND IMPACTS', img: 'usa_clearcut.jpg', caption: 'A cleared forest.', q: 'Give one environmental effect of removing forests.', a: 'Soil erosion (also loss of biodiversity and climate change).', noProj: 'discuss bare land around Garoua.' },
    { sec: '4. CONSERVATION AND MANAGEMENT', img: 'cmr_protected_areas.png', caption: 'Protected areas of the forest zone.', q: 'Why does the state create national parks?', a: 'To protect plants, animals, soils and water sources.', noProj: 'name parks of Cameroon.' },
  ],
  summary: [
    D([['Forest resource:', 'It is anything useful obtained from a forest: timber, fuelwood, food, medicines, wildlife.'],
      ['Non-timber forest products (NTFPs):', 'They are forest products other than timber, such as eru, bush mango, honey and medicinal bark.'],
      ['Forest management unit (UFA):', 'It is a forest concession given to a company for long-term logging under a management plan.'],
      ['Conservation:', 'It is the careful use and protection of resources so that they last.']]),
    { title: '1. Types, Distribution, Resources and Ownership', intro: 'The types, extent, resources and ownership of the forests of Cameroon are the following:',
      items: [['Types and distribution:', 'Dense rainforest (South, East, Centre, Littoral, South-West), mangroves (coast), montane forests (Western Highlands) and savanna woodlands (north).', 'cmr_forest_big.png', 'forests and timber in Cameroon'],
        ['Extent:', 'Forests cover about 40 % of Cameroon (about 20 million hectares), one of the largest forest areas of the Congo Basin.'],
        ['Resources:', 'More than 300 commercial timber species (sapele, ayous, iroko, azobé, moabi, ebony), NTFPs, fuelwood and wildlife.'],
        ['Ownership:', ['State forests (production forests, parks and reserves) and council forests in the permanent forest estate.', 'Community forests managed by villages (up to 5,000 ha).', 'Private forests and plantations.']]] },
    { title: '2. Exploitation', sub: 'A) Stakeholders', intro: 'The main stakeholders in forest exploitation are the following:',
      items: [['The state:', 'The Ministry of Forestry and Wildlife (MINFOF) makes rules, grants concessions and controls logging.'],
        ['Logging companies:', 'Large national and foreign companies log concessions and process timber.', 'f2t_logging_truck.jpg', 'transporting logs'],
        ['Local communities:', 'Villages and indigenous peoples (Baka) use the forest for food, fuel, medicine and culture.'],
        ['NGOs and partners:', 'WWF, WCS and others support conservation and community forestry.']] },
    { title: '2. Exploitation', sub: 'B) Methods, Localities and Uses', intro: 'The methods, localities and uses of forest exploitation are the following:',
      items: [['Modern large-scale exploitation:', 'Selective logging with chainsaws, bulldozers and lorries in concessions, and processing in sawmills.', 'usa_sawmill.jpg', 'a sawmill'],
        ['Small-scale exploitation:', 'Chainsaw sawing, fuelwood cutting, charcoal making and gathering of NTFPs by local people.'],
        ['Localities:', 'Intensive in the East (Bertoua, Yokadouma), the South and the Centre; less intensive in the north; none in parks and reserves.'],
        ['Uses:', 'Timber for building, furniture and export (through Douala and Kribi), and fuelwood and charcoal, the main energy of most households.', 'f2t_charcoal.jpg', 'charcoal']] },
    { title: '3. Problems and Impacts', intro: 'The problems, impacts and environmental role of forests are the following:',
      items: [['Problems hindering full exploitation:', 'Remote forests, bad roads, heavy rain, high costs and lack of capital for local operators.'],
        ['Problems of over-exploitation:', 'Illegal logging, fuelwood cutting around towns, poaching and shifting cultivation cause deforestation.', 'usa_clearcut.jpg', 'a cleared forest'],
        ['Socio-economic impacts:', 'Jobs, export revenue and forestry taxes shared with councils and communities, but conflicts over land and benefits.'],
        ['Environmental role:', 'Forests protect soils and water sources, store carbon, regulate climate and shelter biodiversity.']] },
    { title: '4. Conservation and Management Measures', intro: 'The following measures are taken to manage forests sustainably:',
      items: [['Legislation:', 'The 1994 Forestry and Wildlife Law organises logging, taxes and community forests.'],
        ['Protected areas:', 'National parks and reserves (Dja, Lobéké, Campo-Ma\'an, Korup, Bénoué, Bouba Ndjida) cover about a fifth of the territory.', 'cmr_protected_areas.png', 'protected areas'],
        ['Management plans:', 'Concessions (UFA) must follow management plans, and log exports of many species are restricted to encourage local processing.'],
        ['Community forestry and reforestation:', 'Villages manage community forests, and ANAFOR and projects replant trees.'],
        ['Control and certification:', 'Forest control, satellite monitoring and certification (FSC, the EU FLEGT agreement) fight illegal logging.']] },
  ],
  evaluation: [['Name two stakeholders in forest exploitation in Cameroon.', 'The state (MINFOF) and logging companies (also local communities and NGOs).'], ['Give two measures taken to manage forests sustainably.', 'Protected areas and management plans (also the 1994 law and community forests).']],
  remediation: ['Forest products other than timber are called ______.', 'The ministry in charge of forests is ______.', 'Forests managed by villages are ______ forests.'],
  remediationAnswers: '1. NTFPs (non-timber forest products) 2. MINFOF 3. community',
  homework: 'Name two minerals exploited in Cameroon.',
  hwAnswer: 'Examples: crude oil, natural gas, limestone, gold, bauxite (planned) and iron ore (planned).',
  bilingual: [['Forest', 'La forêt'], ['Timber', 'Le bois d\'œuvre'], ['Logging', "L'exploitation forestière"], ['Sawmill', 'La scierie'], ['Fuelwood', 'Le bois de chauffe'], ['Deforestation', 'La déforestation'], ['Community forest', 'La forêt communautaire'], ['Reforestation', 'Le reboisement']],
});

L.push({ no: 10, title: 'Management of Mineral and Energy Resources in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon',
  notions: 'Mineral, energy resource, hydrocarbons, open-pit mining, artisanal mining, stakeholder, mining code, sustainable exploitation.',
  focus: 'Low level of exploitation; types, distribution, quality and quantity of minerals; methods and stakeholders; uses (including energy minerals); problems and recent state efforts; benefits; measures for sustainable exploitation.',
  competence: 'Learners are able to locate the mineral and energy resources of Cameroon, explain their low exploitation and propose measures for sustainable management.',
  objectives: ['Explain the low level of exploitation of minerals in Cameroon.', 'Describe the types and distribution of minerals and energy resources.', 'Describe the methods of exploitation and the stakeholders.', 'Explain the problems, state efforts, benefits and measures for sustainable exploitation.'],
  recall: ['Minerals are natural substances taken from the ground.', 'Oil is extracted near the coast of Cameroon.', 'Most electricity in Cameroon comes from dams.'],
  situation: 'Oumarou hears on the news that the state has signed an agreement to exploit the iron ore of Mbalam in the East, with a railway to the port of Kribi. His uncle, an artisanal gold miner near Batouri, works with shovels and pans. Oumarou asks his father: "If Cameroon is so rich in minerals, why are so few of them exploited, and how can they benefit the country?"',
  sitQA: [['What is the problem in the situation?', 'Oumarou does not understand why the rich minerals of Cameroon are little exploited and how they can benefit the country.'],
    ['Which mineral is found at Mbalam?', 'Iron ore.'],
    ['How does the uncle mine gold?', 'By hand, with shovels and pans (artisanal mining).']],
  justification: 'This lesson helps us to know the mineral and energy wealth of Cameroon and the conditions for using it well.',
  action: 'Save energy at home and support the responsible use of mineral wealth.',
  activities: [
    { sec: '1. TYPES AND DISTRIBUTION', img: 'cmr_minerals_big.png', caption: 'Minerals of Cameroon.', q: 'Where are the bauxite deposits of Cameroon?', a: 'At Minim-Martap and Ngaoundal (Adamawa) and Fongo-Tongo (West).', noProj: 'mark minerals on a sketch map.' },
    { sec: '1. TYPES AND DISTRIBUTION', img: 'usa_offshore.jpg', caption: 'An offshore oil platform.', q: 'Where is most of Cameroon\'s oil extracted?', a: 'Offshore, in the Rio del Rey basin (and the Douala/Kribi-Campo basin).', noProj: 'show the coast on a map.' },
    { sec: '2. METHODS AND STAKEHOLDERS', img: 'usa_goldminers.jpg', caption: 'Artisanal miners.', q: 'What are the characteristics of artisanal mining?', a: 'It uses simple tools and much labour, and it is often informal.', noProj: 'describe gold mining in the East.' },
    { sec: '3. PROBLEMS AND STATE EFFORTS', img: 'lsa_nachtigal.jpg', caption: 'A dam on the Sanaga.', q: 'Why does mining need dams and railways?', a: 'Mines need a lot of electricity and transport for heavy ores.', noProj: 'name dams and ports.' },
    { sec: '4. BENEFITS AND SUSTAINABILITY', img: 'usa_openpit.jpg', caption: 'An open-pit mine.', q: 'What must a mining company do when the mine closes?', a: 'Restore the land (fill, replant trees).', noProj: 'discuss old quarries.' },
  ],
  summary: [
    D([['Mineral:', 'It is a natural substance obtained from the Earth\'s crust, such as iron ore, bauxite or gold.'],
      ['Energy resource:', 'It is a source of power, such as oil, gas, water (hydroelectricity) or the sun.'],
      ['Artisanal mining:', 'It is small-scale mining with simple tools and much labour.'],
      ['Sustainable exploitation:', 'It is the use of resources that meets present needs without destroying them for future generations.']]),
    { title: '1. Introduction: A Low Level of Exploitation', intro: 'The mineral wealth of Cameroon and its level of exploitation are the following:',
      items: [['Rich subsoil:', 'Cameroon has oil, gas, iron ore, bauxite, cobalt, nickel, gold, diamonds, limestone and other minerals.', 'cmr_minerals_big.png', 'minerals of Cameroon'],
        ['Little exploitation:', 'Apart from oil, gas and limestone, most deposits are not yet mined on a large scale.'],
        ['Little local use:', 'Most minerals, like crude oil, are exported without much processing.']] },
    { title: '2. Types, Distribution, Quality and Quantity', sub: 'A) Energy Minerals and Energy Resources', intro: 'The energy resources of Cameroon are the following:',
      items: [['Crude oil:', 'It is extracted mainly offshore in the Rio del Rey basin and in the Douala/Kribi-Campo basin; production has fallen from about 180,000 barrels a day (1985) to about 60,000.', 'usa_offshore.jpg', 'an offshore platform'],
        ['Natural gas:', 'Gas from Logbaba (Douala) and offshore Kribi supplies factories and the Kribi power plant, and is exported as liquefied gas since 2018.'],
        ['Hydroelectricity:', 'The rivers provide most of the electricity (Song Loulou, Edéa, Lagdo, Memve\'ele, Nachtigal).'],
        ['Other sources:', 'Fuelwood (the main household energy), thermal plants and growing solar energy in the north.']] },
    { title: '2. Types, Distribution, Quality and Quantity', sub: 'B) Metallic and Industrial Minerals', intro: 'The main metallic and industrial minerals are the following:',
      items: [['Iron ore:', 'Large deposits at Mbalam (East), Nkout (South) and near Kribi, some of good quality.'],
        ['Bauxite:', 'Large reserves at Minim-Martap and Ngaoundal (Adamawa) and Fongo-Tongo (West), still not mined.', 'lsa_bauxite.jpg', 'bauxite'],
        ['Cobalt, nickel and manganese:', 'Deposits at Nkamouna near Lomié (East).'],
        ['Gold and diamonds:', 'Mainly in the East (Bétaré-Oya, Batouri, Mobilong), mostly mined by artisans.'],
        ['Industrial minerals:', 'Limestone at Figuil (North) for cement, marble at Bidzar (Far North), rutile at Akonolinga, uranium at Poli and Lolodorf (not mined).']] },
    { title: '3. Methods of Exploitation and Stakeholders', intro: 'The methods of exploitation and the stakeholders are the following:',
      items: [['Industrial mining:', 'Offshore drilling for oil and gas; open-pit mining planned for iron ore and bauxite; quarries for limestone and marble.', 'usa_openpit.jpg', 'an open-pit mine'],
        ['Artisanal mining:', 'Gold and diamonds are dug and washed by hand, often informally.', 'usa_goldminers.jpg', 'artisanal miners'],
        ['The state:', 'The Ministry of Mines (MINMIDT), the SNH (hydrocarbons) and SONAMINES (national mining company) grant permits and collect revenue.'],
        ['Companies and communities:', 'Multinational and national companies invest, while local communities provide land and labour and receive compensation.']] },
    { title: '4. Uses of the Minerals', intro: 'Minerals are used in the following ways:',
      items: [['Oil:', 'Refined into fuels at SONARA (Limbe) and exported as crude.'],
        ['Gas:', 'Electricity production, industrial fuel and export.'],
        ['Limestone:', 'Cement (CIMENCAM at Figuil and other plants).'],
        ['Bauxite and iron ore:', 'Aluminium and steel (planned); ALUCAM at Edéa uses imported alumina.'],
        ['Gold and diamonds:', 'Jewellery and savings.']] },
    { title: '5. Problems and Recent State Efforts', sub: 'A) Problems Hindering Exploitation', intro: 'The exploitation of minerals faces the following problems:',
      items: [['Lack of infrastructure:', 'Railways, ports, roads and electricity are lacking near deposits.'],
        ['High investment costs:', 'Large mines need billions of francs, often from foreign investors.'],
        ['Poor geological knowledge:', 'Many areas are not yet fully surveyed.'],
        ['Governance problems:', 'Slow procedures, corruption and conflicts with local communities discourage investors.'],
        ['Falling oil output:', 'Old oil fields are declining.']] },
    { title: '5. Problems and Recent State Efforts', sub: 'B) Recent State Efforts', intro: 'The state has taken the following measures:',
      items: [['Mining Code:', 'The Mining Code (2016, revised in 2023) aims to attract investors and increase benefits for Cameroon.'],
        ['Infrastructure:', 'The Kribi deep-sea port, the Lom Pangar and Nachtigal dams and planned mining railways.', 'lsa_nachtigal.jpg', 'the Nachtigal dam site'],
        ['Institutions:', 'SONAMINES (2020) and the formalisation of artisanal mining.'],
        ['Partnerships:', 'Agreements with foreign companies to develop iron ore and bauxite.']] },
    { title: '6. Benefits and Sustainable Exploitation', intro: 'The benefits of mineral exploitation and the measures for sustainable exploitation are the following:',
      items: [['Benefits:', 'Revenue for the state, jobs, raw materials for industries (cement, aluminium, steel) and new roads, railways and services.'],
        ['Environmental impact assessments:', 'Projects must study and reduce their effects on the environment before they start.'],
        ['Land restoration:', 'Companies must restore mined land and replant it.'],
        ['Community development:', 'Part of the revenue must go to affected communities.'],
        ['Transparency:', 'Cameroon belongs to the Extractive Industries Transparency Initiative (EITI), which publishes mining payments.']] },
  ],
  evaluation: [['Name two minerals of the East Region and their location.', 'Iron ore at Mbalam and gold at Bétaré-Oya (also cobalt-nickel at Lomié).'], ['Give two problems that hinder mineral exploitation in Cameroon.', 'Lack of infrastructure and high investment costs.']],
  remediation: ['The company that refines oil at Limbe is ______.', 'Limestone for cement is quarried at ______ in the North.', 'Small-scale mining with simple tools is ______ mining.'],
  remediationAnswers: '1. SONARA 2. Figuil 3. artisanal',
  homework: 'Name the dam built on the Benue.',
  hwAnswer: 'The Lagdo dam.',
  bilingual: [['Mineral', 'Le minerai / le minéral'], ['Mine', 'La mine'], ['Oil', 'Le pétrole'], ['Gas', 'Le gaz'], ['Iron ore', 'Le minerai de fer'], ['Bauxite', 'La bauxite'], ['Gold', "L'or"], ['Quarry', 'La carrière']],
});

module.exports = { B, L };
