// LOWER SIXTH ARTS — Geography of Cameroon, lessons 11–15 (water, industry, transport, tourism, regional contrasts)
// Syllabus 2019: M6 FS4, FS5, FS6, FS7; M7 FS1. Guided by the teacher's course notes (LSA/USA_CAM_GEO_2026).
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'LSA', code: 'CAM', folder: 'Geography of Cameroon', module: 'Geography of Cameroon', topicDefault: 'Geography of Cameroon', branch: 'Economic Activities and Development of Cameroon',
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Geography of Cameroon.', 'Teacher\'s course notes: Mr KAMDEM E., Cameroon Geography (LSA and USA), GBHS Garoua, 2026.', 'INS, Fourth Cameroon Household Survey (ECAM 4), 2014.'] };
const L = [];

L.push({ no: 11, title: 'Management of Water Resources in Cameroon', subtopic: 'Economic Activities and Development of Cameroon', pointPerSlide: true,
  notions: 'Water resources, fishing, aquaculture, irrigation scheme, flood-retreat cultivation, navigation, hydroelectric power, water supply.',
  focus: 'Distribution of water bodies and their resources; use for fishing (modern and traditional), agriculture (irrigation schemes and flood-retreat cultivation), transport, water supply, sand extraction and hydroelectric power; problems, solutions and impacts.',
  competence: 'Learners are able to describe the uses of the water resources of Cameroon and propose solutions to the problems of their management.',
  objectives: ['Describe the distribution of water bodies and their resources.', 'Explain the use of water for fishing and agriculture, with their problems and solutions.', 'Explain the use of water for transport, water supply and other uses.', 'Describe the hydroelectric sites, their problems and solutions.'],
  recall: ['The Lagdo dam is on the Benue.', 'The Sanaga has the largest dams of Cameroon.', 'SEMRY grows rice with water from the Logone.'],
  situation: 'Hamadou visits his uncle, a fisherman on the Lagdo reservoir. The uncle complains that his catches are smaller and that the water level is low, which reduces the water in his irrigation channels. That evening the electricity goes off, and a neighbour says: "It is the low water at the dam again." Hamadou asks: "How is one lake used for so many things, and how can we manage it better?"',
  sitQA: [['What is the problem in the situation?', 'The Lagdo reservoir serves many uses, and low water affects them all; Hamadou wants to know how to manage it better.'],
    ['Name three uses of the Lagdo reservoir in the situation.', 'Fishing, irrigation and electricity.'],
    ['Why does the electricity go off?', 'The water level at the dam is low, so less electricity is produced.']],
  justification: 'This lesson helps us to understand the value of water resources for food, energy and transport, and the need to manage them carefully.',
  action: 'Save water and electricity, and protect rivers and lakes from pollution.',
  activities: [
    { sec: '1. DISTRIBUTION', img: 'cmr_water_big.png', caption: 'Water resources of Cameroon.', q: 'Name one large irrigation scheme of the Far North.', a: 'SEMRY (rice, near Yagoua and Maga).', noProj: 'mark dams and schemes on a sketch map.' },
    { sec: '2. FISHING', img: 'f2t_fishing.jpg', caption: 'Fishermen in canoes.', q: 'What is the difference between artisanal and industrial fishing?', a: 'Artisanal fishing uses canoes and nets; industrial fishing uses large motorised trawlers.', noProj: 'describe fishing on the Lagdo lake.' },
    { sec: '3. AGRICULTURE', img: 'f4_ricefield.jpg', caption: 'An irrigated rice field.', q: 'Why is irrigation important in the North?', a: 'It allows farming during the long dry season.', noProj: 'describe irrigated onion fields.' },
    { sec: '4. TRANSPORT AND OTHER USES', img: 'lsa_wouri.jpg', caption: 'The Wouri estuary.', q: 'Why is the Wouri estuary important for Cameroon?', a: 'It gives access to the port of Douala, the main port of the country.', noProj: 'show Douala on a map.' },
    { sec: '5. HYDROELECTRIC POWER', img: 'f2t_lagdo.jpg', caption: 'The Lagdo dam.', q: 'Which regions receive electricity from the Lagdo dam?', a: 'The North, the Far North and the Adamawa.', noProj: 'list the dams of Cameroon.' },
  ],
  summary: [
    D([['Water resources:', 'They are the water bodies of a country (sea, rivers, lakes, underground water) and what they provide.'],
      ['Irrigation:', 'It is the artificial supply of water to crops.'],
      ['Flood-retreat cultivation:', 'It is farming on land left moist when river floods go down.'],
      ['Aquaculture:', 'It is the rearing of fish in ponds or cages.']]),
    { title: '1. Distribution of Water Bodies and their Resources', intro: 'The water bodies of Cameroon and their resources are the following:',
      items: [['The sea:', 'The Atlantic coast, about 400 km long, provides fish, shrimps, oil and gas. It also has the ports of the country and beaches for tourism.', 'cmr_water_big.png', 'the water resources of Cameroon'],
        ['Rivers:', 'The Sanaga, the Wouri, the Nyong, the Ntem, the Benue and the Logone provide water, fish, energy and transport. Sand is also dredged from their beds for building.'],
        ['Lakes:', 'Cameroon has Lake Chad, crater lakes such as Barombi Mbo, Nyos and Ossa, and reservoirs such as Lagdo, Maga, Mbakaou and Lom Pangar. They supply fish, water and energy.'],
        ['Underground water:', 'Aquifers supply boreholes and wells in towns and villages. They are especially important in the north, where rivers dry up in the dry season.']] },
    { title: '2. Use for Fishing', sub: 'A) Methods of Fishing', intro: 'Fishing is carried out by the following methods:',
      items: [['Modern large-scale fishing:', 'Motorised trawlers from Douala, Limbe and Kribi catch fish and shrimps at sea. They use large nets and keep the catch in cold stores.', 'usa_fishing.jpg', 'a fishing trawler'],
        ['Traditional small-scale fishing:', 'Fishermen use canoes, nets, lines and traps on rivers, lakes and along the coast. This fishing supplies most of the fish eaten locally.', 'f2t_fishing.jpg', 'fishing canoes'],
        ['Main inland fisheries:', 'Lake Chad, the Lagdo and Maga reservoirs and the floodplains of the Logone are the main inland fishing areas. Their fish is smoked or dried and sold in the towns of the north and in Nigeria.'],
        ['Aquaculture:', 'Fish farms and ponds are developing, especially in the Centre and the West. They produce tilapia and catfish and reduce the pressure on wild fish.']] },
    { title: "2. Use for Fishing", sub: "B) Problems of Fishing", intro: "Fishing faces the following problems:",
      items: [["Overfishing:", "Too many fishermen use nets with very small meshes, which catch young fish before they can breed. As a result, fish stocks are falling in many lakes and rivers."],
        ["Pollution:", "Waste from towns and industries pollutes rivers and the coast. Fish die or move away from polluted waters."],
        ["The shrinking of Lake Chad:", "Lake Chad has shrunk greatly since the 1960s because of droughts and irrigation. Fishermen have lost much of their fishing area."],
        ["Poor storage:", "Many fishermen have no cold stores or good smoking ovens. Part of the catch therefore rots before it is sold."]] },
    { title: "2. Use for Fishing", sub: "C) Solutions to the Problems of Fishing", intro: "The problems of fishing are solved in the following ways:",
      items: [["Fishing rules:", "Rules fix the minimum size of net meshes and closed seasons when fishing is forbidden. Young fish can then grow and breed."],
        ["Control:", "MINEPIA controls fishermen and seizes illegal nets. This makes fishermen respect the rules."],
        ["Cold storage and improved ovens:", "Cold stores and improved smoking ovens reduce the loss of fish. Improved ovens also use less wood, which protects the mangroves."],
        ["Aquaculture:", "Fish farms produce tilapia and catfish in ponds. They increase production without emptying rivers and lakes."]] },
    { title: "2. Use for Fishing", sub: "D) Impacts of Fishing", intro: "Fishing has the following impacts:",
      items: [["Jobs:", "Fishing gives jobs to fishermen, fish sellers, smokers and boat builders. Whole villages along the coast and the lakes live from it."],
        ["Cheap protein:", "Fish is cheaper than meat in many areas. It supplies protein to a large part of the population."],
        ["Falling fish stocks:", "Overfishing reduces the number of fish and the diversity of species. Some species have become rare."],
        ["Destruction of mangroves:", "Mangroves are cut to provide wood for smoking fish. This destroys the breeding grounds of many fish."]] },
    { title: "3. Use for Agriculture", sub: "A) Irrigation Schemes and Methods", intro: "Water is used for agriculture in the following ways:",
      items: [["SEMRY:", "SEMRY runs large irrigated rice schemes on the Logone near Yagoua and Maga in the Far North. Water from the Maga reservoir and the Logone allows two harvests a year.", "f4_ricefield.jpg", "a rice field"],
        ["Lagdo:", "Farmers grow irrigated rice and other crops around the Lagdo reservoir on the Benue. The reservoir supplies water all year."],
        ["UNVDA:", "In the North-West, UNVDA irrigates rice in the Ndop plain. It also supplies seeds and buys the rice of the farmers."],
        ["Flood-retreat cultivation:", "When the floods of the Logone and the Benue go down, farmers plant dry-season sorghum (muskwari), maize and vegetables on the moist land. This gives food during the dry season."]] },
    { title: "3. Use for Agriculture", sub: "B) Benefits and Problems of Irrigation", intro: "Irrigation has the following benefits and problems:",
      items: [["More food:", "Irrigation allows crops to grow in the dry season and protects them from drought. Food production therefore increases."],
        ["Dry-season jobs:", "Irrigated farms give work during the dry season, when other farm work stops. This reduces seasonal migration to towns."],
        ["High costs and silting:", "Dams, canals and pumps are expensive to build and maintain. Canals silt up and must be cleaned regularly."],
        ["Waterlogging and conflicts:", "Too much water makes some soils waterlogged or salty. Farmers and herders also quarrel over access to water."]] },
    { title: '4. Use for Transport and Other Purposes', intro: 'Water is used for transport and other purposes in the following ways:',
      items: [['Sea transport:', 'The ports of Douala, Kribi (a deep-sea port) and Limbe handle almost all the foreign trade of Cameroon. Douala also serves Chad and the Central African Republic.', 'lsa_wouri.jpg', 'the Wouri'],
        ['River transport:', 'The Benue is navigable to Garoua only from about August to October. The Sangha is used for transport in the south-east.'],
        ['Water supply:', 'CAMWATER treats river and underground water and supplies it to towns such as Douala, Yaoundé and Garoua. Industries also use large amounts of water.'],
        ['Sand extraction:', 'Sand is dredged from the Wouri, the Sanaga and the Benue for building. It supplies the construction industry of the towns.']] },
    { title: '5. Use for Hydroelectric Power', sub: 'A) The Hydroelectric Sites', intro: 'Hydroelectricity is produced at the following sites:',
      items: [['Southern sites:', 'Song Loulou and Edéa on the Sanaga, Nachtigal (420 MW) and Memve\'ele on the Ntem supply the southern grid. This grid serves the Littoral, Centre, South, West and East Regions.', 'lsa_nachtigal.jpg', 'the Nachtigal dam'],
        ['The northern site:', 'The Lagdo dam (72 MW) on the Benue supplies the North, the Far North and the Adamawa. It is the only large dam of the northern grid.', 'f2t_lagdo.jpg', 'Lake Lagdo'],
        ['Regulating dams:', 'Lom Pangar, Mbakaou, Bamendjin and Mapé store water in the rainy season. They release it in the dry season to keep the Sanaga flowing through the power stations.']] },
    { title: "5. Use for Hydroelectric Power", sub: "B) Problems", intro: "Hydroelectricity faces the following problems:",
      items: [["Low water in the dry season:", "Rivers carry less water in the dry season, so the power stations produce less. This causes power cuts called load shedding."],
        ["Silting and weeds:", "Soil eroded from the catchments fills the reservoirs, and weeds block the water intakes. The dams then store less water."],
        ["Old equipment and weak grids:", "Many turbines and power lines are old and break down often. Electricity is lost on the way to the consumers."],
        ["Separate grids:", "The northern grid is not linked to the southern one. When Lagdo produces too little, the north cannot receive power from the south."]] },
    { title: "5. Use for Hydroelectric Power", sub: "C) Solutions", intro: "The problems of hydroelectricity are solved in the following ways:",
      items: [["New dams:", "New dams such as Lom Pangar, Nachtigal and Memve'ele increase production. Lom Pangar also stores water to keep the Sanaga flowing in the dry season.", "lsa_nachtigal.jpg", "the Nachtigal dam"],
        ["Dredging and catchment protection:", "Reservoirs are dredged, and trees are planted in the catchments to reduce erosion. The dams then keep their storage capacity."],
        ["Linking the grids:", "The northern and southern grids are to be linked by a long power line. Electricity can then be sent where it is needed."],
        ["Solar energy:", "Solar power plants are being built in the north, as at Guider and Maroua. They complete the supply from Lagdo."]] },
  ],
  evaluation: [['Name two irrigation schemes of Cameroon.', 'SEMRY (Logone) and UNVDA (Ndop); also Lagdo.'], ['Give two problems of hydroelectric production and one solution.', 'Low water in the dry season and silting; building regulating dams (or dredging).']],
  remediation: ['Farming on moist land left by floods is ______ cultivation.', 'The dam that supplies the north is ______.', 'The state company that supplies drinking water is ______.'],
  remediationAnswers: '1. flood-retreat 2. Lagdo 3. CAMWATER',
  homework: 'Name one factory in Garoua and what it produces.',
  hwAnswer: 'CICAM makes cotton cloth (textiles); SODECOTON gins cotton and makes cotton-seed oil; the SABC brews drinks.',
  bilingual: [['Water resources', 'Les ressources en eau'], ['Fishing', 'La pêche'], ['Irrigation', "L'irrigation"], ['Dam', 'Le barrage'], ['Reservoir', 'La retenue'], ['Navigation', 'La navigation'], ['Power cut', "La coupure d'électricité"], ['Drinking water', "L'eau potable"]],
});

L.push({ no: 12, title: 'Industrial Development and Change in Cameroon', subtopic: 'Economic Activities and Development of Cameroon', pointPerSlide: true,
  notions: 'Manufacturing industry, light industry, import substitution, raw-material oriented industry, industrial region, locational factors.',
  focus: 'Characteristics of manufacturing industries; the main industrial regions (Coastal, Centre-South, Western, Northern) and their types of industries; locational and growth factors; reasons for the low level of industrialisation; efforts of the state; socio-economic impacts.',
  competence: 'Learners are able to describe the industrial regions of Cameroon, explain their location and propose ways to develop industry.',
  objectives: ['Describe the characteristics of manufacturing industries in Cameroon.', 'Describe the four industrial regions and explain their pattern.', 'Explain the reasons for the low level of industrialisation.', 'Describe the efforts of the state and the impacts of industrialisation.'],
  recall: ['CICAM makes cloth in Garoua.', 'Douala is the main port of Cameroon.', 'Industries transform raw materials into finished goods.'],
  situation: 'Issa drinks a bottle of juice made by the SABC in Douala, and his new school uniform is made of cloth from CICAM in Garoua. He asks his friend: "Why is my drink made far away in Douala while our cloth is made here, and why are there so few big factories in Garoua?"',
  sitQA: [['What is the problem in the situation?', 'Issa wants to understand the location of industries and the low industrialisation of the north.'],
    ['Where is the cloth of the uniform made?', 'At CICAM in Garoua.'],
    ['Why is cloth made in Garoua?', 'Garoua is in the main cotton-growing region (raw material).']],
  justification: 'This lesson helps us to understand the industries of Cameroon, their location and their role in development.',
  action: 'Buy products made in Cameroon and develop skills useful to industry.',
  activities: [
    { sec: '1. CHARACTERISTICS', img: 'f2t_textile_factory.jpg', caption: 'A textile factory.', q: 'What raw material does a textile factory in Garoua use?', a: 'Cotton.', noProj: 'show a piece of cotton cloth.' },
    { sec: '2. INDUSTRIAL REGIONS', img: 'cmr_industry_big.png', caption: 'Industrial regions of Cameroon.', q: 'Which region has the most industries?', a: 'The Coastal region, around Douala, Edéa and Limbe.', noProj: 'mark industrial towns on a sketch map.' },
    { sec: '2. INDUSTRIAL REGIONS', img: 'f2t_aluminium.jpg', caption: 'An aluminium smelter.', q: 'Why was the aluminium smelter built at Edéa?', a: 'Because of the cheap electricity from the Edéa dam and the nearby port of Douala.', noProj: 'name the Sanaga dams.' },
    { sec: '3. LOW LEVEL OF INDUSTRIALISATION', img: 'usa_carfactory.jpg', caption: 'A modern factory.', q: 'Give one reason why Cameroon has few heavy industries.', a: 'Lack of capital (also technology, energy or a large market).', noProj: 'discuss imported goods in the market.' },
    { sec: '4. IMPACTS', img: 'f2t_factory_workers.jpg', caption: 'Factory workers.', q: 'Give one positive impact of industries on a town.', a: 'They create jobs (and attract services).', noProj: 'list jobs in factories of Garoua.' },
  ],
  summary: [
    D([['Manufacturing industry:', 'It is the transformation of raw materials into finished or semi-finished goods in factories.'],
      ['Light industry:', 'It produces consumer goods with little raw material and capital (food, drinks, textiles, soap).'],
      ['Import substitution:', 'It is producing locally goods that were formerly imported.'],
      ['Industrial region:', 'It is an area where many industries are concentrated.']]),
    { title: '1. Characteristics of Manufacturing Industries', intro: 'The manufacturing industries of Cameroon have the following characteristics:',
      items: [['A low level of industrialisation:', 'Manufacturing is small and provides only about a sixth of national production. Many manufactured goods are still imported.', 'f2t_textile_factory.jpg', 'a textile factory'],
        ['Light and import-substitution industries:', 'Most factories make food, drinks, textiles, soap, wood products and cement. Many were created to replace imported goods such as cement, sugar, cloth and drinks.'],
        ['Raw-material orientation:', 'Many industries are located near their raw materials, because these are heavy or perishable. Ginneries are near cotton farms and sawmills near forests.'],
        ['Concentration:', 'Most industries are concentrated in Douala and Yaoundé. Other regions have only a few factories.']] },
    { title: "2. The Main Industrial Regions", sub: "A) The Coastal Region", intro: "The Coastal region has the following industries and location factors:",
      items: [["Industries of Douala:", "Douala makes drinks, food, chocolate, soap, cement and metal goods. It is the largest industrial town of Cameroon.", "cmr_industry_big.png", "the industrial regions"],
        ["Other industrial towns:", "Edéa produces aluminium at ALUCAM, Limbe had the SONARA oil refinery, and Kribi has a new industrial port zone. These towns use the energy and ports of the coast.", "f2t_aluminium.jpg", "aluminium"],
        ["The port of Douala:", "The port allows the import of raw materials and machines and the export of products. Industries therefore settle close to it."],
        ["Cheap electricity and a large market:", "The dams of Edéa and Song Loulou supply cheap electricity. Douala also offers a large market, skilled labour and banks."]] },
    { title: "2. The Main Industrial Regions", sub: "B) The Centre-South Region", intro: "The Centre-South region has the following industries and location factors:",
      items: [["Industries:", "Yaoundé has drinks, printing, food and building-material industries, and Mbalmayo processes wood. SOSUCAM produces sugar at Mbandjock and Nkoteng."],
        ["The political capital:", "Yaoundé is the political capital, with many civil servants and a large market. Industries producing consumer goods settle there to be close to their customers."],
        ["Raw materials and transport:", "The forest supplies timber, and sugar cane grows well near Mbandjock. The railway and nearby electricity make transport and production easier."]] },
    { title: "2. The Main Industrial Regions", sub: "C) The Western Region", intro: "The Western region has the following industries and location factors:",
      items: [["Industries:", "Bafoussam, Bamenda and Dschang process coffee and tea and produce food, drinks and crafts. Most factories are small."],
        ["Farm raw materials:", "The rich farming areas of the highlands produce coffee, tea, maize and vegetables. These supply the processing industries."],
        ["Labour and markets:", "The dense population provides many workers. It also forms a large market for food, drinks and crafts."]] },
    { title: "2. The Main Industrial Regions", sub: "D) The Northern Region", intro: "The Northern region has the following industries and location factors:",
      items: [["Industries of Garoua:", "Garoua has the CICAM cloth factory, the SODECOTON cotton and oil mills and a brewery. It is the main industrial town of the north."],
        ["Other industrial towns:", "Figuil makes cement, Maroua works leather and Ngaoundéré processes meat and milk. Each town uses the resources of its area."],
        ["Raw materials:", "The region supplies cotton, limestone, cattle, hides and skins. Industries settle near these raw materials, which are heavy or perishable."],
        ["Electricity and markets:", "The Lagdo dam supplies electricity to the factories. The northern regions and neighbouring Chad form their market."]] },
    { title: "3. Reasons for the Low Level of Industrialisation", sub: "A) Economic Reasons", intro: "Industry remains weak for the following economic reasons:",
      items: [["Lack of capital:", "There are few local investors, and bank loans are expensive. Many industrial projects therefore depend on foreign capital."],
        ["A small market:", "Most people have low incomes, so they buy few manufactured goods. Factories cannot produce large quantities at low cost."],
        ["Competition from imports:", "Cheap imported goods, especially from Asia, compete strongly with local products. Many local factories cannot sell enough and close."],
        ["Administrative problems:", "Slow procedures, high taxes and corruption raise the cost of setting up a factory. Investors are therefore discouraged."]] },
    { title: "3. Reasons for the Low Level of Industrialisation", sub: "B) Technical Reasons", intro: "Industry also remains weak for the following technical reasons:",
      items: [["Power cuts:", "Frequent power cuts stop the machines. Factories must buy their own generators, which makes their goods more expensive."],
        ["Poor transport:", "Bad roads and a limited railway raise the cost of moving raw materials and products. Factories far from Douala are at a disadvantage."],
        ["Old technology:", "Many factories use old machines that break down often. Productivity and quality therefore remain low."],
        ["Lack of skilled workers:", "Engineers and technicians are too few, and many leave for other countries. Factories lack the people to run and repair their machines."]] },
    { title: '4. Efforts of the State', intro: 'The state has taken the following measures to develop industry:',
      items: [['Infrastructure:', 'The state has built new dams (Lom Pangar, Nachtigal, Memve\'ele), the Kribi deep-sea port and new roads. These give industries more electricity and better transport.'],
        ['Investment incentives:', 'The law on private investment of 2013 gives tax advantages to new industries. It aims to attract national and foreign investors.'],
        ['Industrial zones:', 'MAGZI prepares industrial zones with water, electricity and roads. Investors can then set up factories quickly.'],
        ['Import-substitution plans:', 'Programmes encourage the local processing of rice, maize, milk, fish and cotton. They aim to reduce imports and create jobs.']] },
    { title: "5. Socio-Economic Impacts of Industrialisation", sub: "A) Positive Impacts", intro: "Industrialisation has the following positive impacts:",
      items: [["Jobs and income:", "Factories give jobs to thousands of workers and pay taxes to the state. They thus increase national income.", "f2t_factory_workers.jpg", "factory workers"],
        ["Local goods:", "Industries supply local goods such as cement, cloth, soap and drinks. The country then imports less."],
        ["A market for farmers:", "Industries buy cotton, cocoa, sugar cane and cattle from farmers. Farmers therefore have a sure market for their products."],
        ["Growth of towns:", "Industries attract people and services to towns such as Douala, Edéa and Garoua. They help these towns to grow and modernise."]] },
    { title: '5. Socio-Economic Impacts of Industrialisation', sub: 'B) Negative Impacts', intro: 'Industrialisation has the following negative impacts:',
      items: [['Pollution:', 'Factories pollute the air, rivers and soils with smoke, waste and chemicals. The Wouri estuary around Douala is especially affected.'],
        ['Rural exodus and slums:', 'Industries attract many young people from villages. Industrial towns then grow too fast, and slums appear around them.'],
        ['Regional inequality:', 'Most industries are in Douala and Yaoundé, so these regions become richer than the others. This increases the gap between regions.']] },
  ],
  evaluation: [['Name the four industrial regions of Cameroon.', 'The Coastal, Centre-South, Western and Northern regions.'], ['Why is the Coastal region the most industrialised?', 'It has the port of Douala, cheap electricity, a large market and good transport.']],
  remediation: ['The aluminium smelter of Edéa is ______.', 'Producing locally goods that were imported is import ______.', 'The oil refinery of Limbe is ______.'],
  remediationAnswers: '1. ALUCAM 2. substitution 3. SONARA',
  homework: 'Name the two end towns of the Transcam railway.',
  hwAnswer: 'Douala and Ngaoundéré (through Yaoundé).',
  bilingual: [['Industry', "L'industrie"], ['Factory', "L'usine"], ['Raw material', 'La matière première'], ['Import substitution', 'La substitution aux importations'], ['Industrial zone', 'La zone industrielle'], ['Refinery', 'La raffinerie'], ['Brewery', 'La brasserie'], ['Investment', "L'investissement"]],
});

L.push({ no: 13, title: 'Transport Development in Cameroon', subtopic: 'Economic Activities and Development of Cameroon', pointPerSlide: true,
  notions: 'Transport network, road, railway, port, airport, corridor, spatial pattern, transit.',
  focus: 'The different route networks: description and explanation of their spatial pattern; problems of transport development; efforts to improve transport.',
  competence: 'Learners are able to describe the transport networks of Cameroon, explain their pattern and propose ways to improve them.',
  objectives: ['Describe the road, rail, air and water networks of Cameroon.', 'Explain the spatial pattern of the transport network.', 'Explain the problems of transport development.', 'Describe the efforts to improve transport.'],
  recall: ['The railway ends at Ngaoundéré.', 'Douala is the main port.', 'Garoua has an international airport.'],
  situation: 'Moussa drives a lorry of cotton from Garoua to the south. Near Ngaoundéré a tyre bursts in a huge pothole, and while he waits he sees the Camrail freight train pass smoothly towards Douala. He says: "If only the roads were better, or the train came to Garoua!" His son asks: "Why is transport so difficult in Cameroon, and what is being done to improve it?"',
  sitQA: [['What is the problem in the situation?', 'Transport is slow and costly because of bad roads and the limited railway.'],
    ['Where does the railway end in the north?', 'At Ngaoundéré.'],
    ['Why is a bad road costly for Moussa?', 'It damages the lorry and wastes time and money.']],
  justification: 'This lesson helps us to understand the role of transport in trade, national unity and development.',
  action: 'Respect traffic rules and protect roads and public transport equipment.',
  activities: [
    { sec: '1. ROUTE NETWORKS', img: 'cmr_transport_big.png', caption: 'The transport network of Cameroon.', q: 'Which towns are linked by the Transcam railway?', a: 'Douala, Yaoundé and Ngaoundéré.', noProj: 'draw the railway on a sketch map.' },
    { sec: '1. ROUTE NETWORKS', img: 'f2t_train.jpg', caption: 'A train.', q: 'Which goods does the railway carry from the north to Douala?', a: 'Cotton, cattle and goods for Chad and the Central African Republic.', noProj: 'list goods at the railway station.' },
    { sec: '1. ROUTE NETWORKS', img: 'usa_container.jpg', caption: 'A container port.', q: 'Why was the deep-sea port of Kribi built?', a: 'To receive very large ships that cannot enter Douala.', noProj: 'compare Douala and Kribi.' },
    { sec: '2. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A damaged road.', q: 'Give one problem of roads in Cameroon.', a: 'Many roads are unpaved or full of potholes.', noProj: 'describe roads around Garoua.' },
    { sec: '3. EFFORTS', img: 'f5_motorway.jpg', caption: 'A motorway.', q: 'Which motorway is being built between the two largest towns?', a: 'The Yaoundé–Douala motorway.', noProj: 'name new roads of the region.' },
  ],
  summary: [
    D([['Transport network:', 'It is the set of routes (roads, railways, air routes, waterways) that link places.'],
      ['Spatial pattern:', 'It is the arrangement of the network on the map.'],
      ['Corridor:', 'It is a main transport route used to carry goods between a port and inland areas or countries.']]),
    { title: '1. The Route Networks and their Spatial Pattern', sub: 'A) The Road Network', intro: 'The road network has the following characteristics:',
      items: [['Importance and radial pattern:', 'Roads carry most of the passengers and goods of Cameroon. The main roads radiate from Douala and Yaoundé to the regional capitals.', 'cmr_transport_big.png', 'the transport network of Cameroon'],
        ['A dense south and a sparse north and east:', 'The network is densest in the south and west. The north depends mainly on one road, the N1, from Ngaoundéré to Garoua, Maroua and Kousseri.'],
        ['Paved and unpaved roads:', 'Only a small part of the network is paved. Most rural roads are earth roads that become muddy in the rainy season.'],
        ['Corridors:', 'The Douala–N\'Djamena and Douala–Bangui corridors carry goods for Chad and the Central African Republic. These landlocked countries depend on the port of Douala.']] },
    { title: '1. The Route Networks and their Spatial Pattern', sub: 'B) The Rail Network', intro: 'The rail network has the following characteristics:',
      items: [['A linear pattern:', 'The Transcam railway runs from Douala to Yaoundé (Transcam I) and from Yaoundé to Ngaoundéré (Transcam II), with a branch to Kumba. It is operated by Camrail.', 'f2t_train.jpg', 'a train'],
        ['Role:', 'It carries heavy goods such as timber, cotton, cattle, fuel and cement. From the railhead at Ngaoundéré, goods continue by road to the North, Chad and the Central African Republic.'],
        ['Limits:', 'The north, including Garoua and Maroua, the west and the east are not served by the railway. These regions depend on roads.']] },
    { title: '1. The Route Networks and their Spatial Pattern', sub: 'C) The Air Network', intro: 'The air network has the following characteristics:',
      items: [['International airports:', 'Douala, the busiest, Yaoundé-Nsimalen and Garoua are the international airports. They link Cameroon with Africa, Europe and the rest of the world.', 'usa_airport.jpg', 'an airport'],
        ['Domestic airports:', 'Maroua-Salak, Ngaoundéré, Bertoua, Bamenda and other towns have smaller airports. They are used by domestic flights.'],
        ['Role:', 'Air transport allows fast travel for business, administration and tourism. It is especially useful between the south and the far north, which are more than 1,000 km apart.']] },
    { title: '1. The Route Networks and their Spatial Pattern', sub: 'D) The Water Network', intro: 'The water network has the following characteristics:',
      items: [['Sea ports:', 'Douala is the main port, and Kribi is a deep-sea port opened in 2018 that can receive very large ships. Limbe and Tiko are smaller ports.', 'usa_container.jpg', 'a container port'],
        ['River transport:', 'The Benue is navigable to Garoua only in the rainy season. The Sangha and the lower Sanaga and Nyong are used for local transport.'],
        ['Role:', 'The ports handle almost all the foreign trade of Cameroon. They also handle part of the trade of Chad and the Central African Republic.']] },
    { title: "2. Problems of Transport Development", sub: "A) Physical Problems", intro: "Transport development faces the following physical problems:",
      items: [["Heavy rain:", "In the south, heavy rain turns earth roads into mud and washes away bridges. Many roads become impassable in the rainy season.", "f2t_muddy_road.jpg", "a muddy road"],
        ["Relief and forest:", "Steep slopes in the west and dense forest in the south make roads difficult and costly to build. Roads must climb escarpments and cross many rivers."],
        ["Floods and sand in the north:", "In the north, floods cut roads in the rainy season, and sand covers them in the dry season. Travel is then slow and dangerous."]] },
    { title: "2. Problems of Transport Development", sub: "B) Economic and Technical Problems", intro: "Transport development also faces the following economic and technical problems:",
      items: [["Lack of funds:", "Building and maintaining roads and railways is very costly, and the state lacks money. Many roads are therefore left with potholes and old bridges."],
        ["Incomplete networks:", "The railway does not reach the north, the west or the east, and many rural areas have no paved road. These regions remain isolated."],
        ["Old equipment and congestion:", "Old trains and lorries break down often. Congestion at the port of Douala also slows down traffic."]] },
    { title: "2. Problems of Transport Development", sub: "C) Security Problems", intro: "Transport development also faces the following security problems:",
      items: [["Road bandits:", "Road bandits, called coupeurs de route, attack vehicles on some roads of the north and east. Travellers and transporters avoid these roads."],
        ["Numerous checkpoints:", "Many checkpoints stop vehicles on the main roads. They delay traffic and raise transport costs."]] },
    { title: "3. Efforts to Improve Transport Development", intro: "The following efforts are made to improve transport:",
      items: [["Roads:", "Major roads are being paved, and motorways are being built between Yaoundé and Douala and between Kribi and Lolabé. The Bamenda–Enugu road links Cameroon to Nigeria.", "f5_motorway.jpg", "a motorway"],
        ["Ports:", "The Kribi deep-sea port has been built and the port of Douala modernised. They can now handle more and larger ships."],
        ["Railway:", "The Transcam line is being rehabilitated and new trains have been bought. There are plans to extend the railway to the north and to Chad."],
        ["Airports and bridges:", "Airports have been modernised, and a second bridge has been built over the Wouri in Douala. Traffic between the two banks of Douala is now faster."]] },
  ],
  evaluation: [['Describe the spatial pattern of the road network of Cameroon.', 'Radial from Douala and Yaoundé, dense in the south and west, sparse in the north and east.'], ['Give two problems of transport and one effort to solve them.', 'Bad roads and lack of funds; building motorways (or the Kribi port).']],
  remediation: ['The company that operates the railway is ______.', 'The deep-sea port opened in 2018 is at ______.', 'The railway ends in the north at ______.'],
  remediationAnswers: '1. Camrail 2. Kribi 3. Ngaoundéré',
  homework: 'Name two national parks of the North Region.',
  hwAnswer: 'The Bénoué, Bouba Ndjida and Faro National Parks.',
  bilingual: [['Road', 'La route'], ['Railway', 'Le chemin de fer'], ['Port', 'Le port'], ['Airport', "L'aéroport"], ['Motorway', "L'autoroute"], ['Pothole', 'Le nid-de-poule'], ['Corridor', 'Le corridor'], ['Transit', 'Le transit']],
});

L.push({ no: 14, title: 'Tourism Development in Cameroon', subtopic: 'Economic Activities and Development of Cameroon', pointPerSlide: true,
  notions: 'Tourism, tourist resource, tourist infrastructure, destination, ecotourism, cultural tourism.',
  focus: 'Tourism resources (natural and human) and their distribution and exploitation; tourism infrastructure; sources of tourists and prime destinations; problems; measures to promote tourism; impacts on the economy, communities and environment.',
  competence: 'Learners are able to describe the tourist resources of Cameroon, explain the problems of tourism and propose measures to promote it.',
  objectives: ['Describe the natural and human tourism resources of Cameroon.', 'Describe the tourism infrastructure, sources of tourists and destinations.', 'Explain the problems hindering tourism and the measures to promote it.', 'Assess the impacts of tourism.'],
  recall: ['Cameroon is called "Africa in miniature".', 'The Bénoué National Park is near Garoua.', 'Mount Cameroon is the highest mountain of Cameroon.'],
  situation: 'French tourists arrive at Garoua airport for a safari in the Bénoué National Park. Their guide Oumarou is worried: the road to the park is damaged, and good hotels with electricity and internet are hard to find near the park. The tourists are delighted by the elephants and hippos but find few services. Oumarou asks: "How can Cameroon, so rich in attractions, receive more tourists and benefit more from them?"',
  sitQA: [['What is the problem in the situation?', 'Cameroon has rich attractions, but poor infrastructure limits tourism.'],
    ['What attracted the tourists?', 'The wildlife of the Bénoué National Park (elephants, hippos).'],
    ['What worries the guide?', 'The damaged road and the lack of good hotels.']],
  justification: 'This lesson helps us to know the tourist wealth of Cameroon and the conditions for developing tourism.',
  action: 'Welcome visitors, protect tourist sites and value our cultures.',
  activities: [
    { sec: '1. TOURISM RESOURCES', img: 'cmr_tourism_big.png', caption: 'Tourist sites of Cameroon.', q: 'Name one national park of the Far North.', a: 'The Waza National Park.', noProj: 'mark tourist sites on a sketch map.' },
    { sec: '1. TOURISM RESOURCES', img: 'lsa_mandara.jpg', caption: 'Mountains of the Far North.', q: 'Why do tourists visit Rhumsiki?', a: 'For its volcanic peaks and landscapes in the Mandara Mountains.', noProj: 'describe the Mandara landscapes.' },
    { sec: '1. TOURISM RESOURCES', img: 'usa_bandjoun.jpg', caption: 'A traditional chiefdom.', q: 'Which kind of tourism does this chiefdom attract?', a: 'Cultural tourism.', noProj: 'name palaces and festivals.' },
    { sec: '2. INFRASTRUCTURE AND DESTINATIONS', img: 'usa_hotel.jpg', caption: 'A hotel.', q: 'Why are hotels important for tourism?', a: 'Tourists need safe, comfortable accommodation near the sites.', noProj: 'list hotels of Garoua.' },
    { sec: '3. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A damaged road.', q: 'Give one problem that limits tourism in Cameroon.', a: 'Bad roads (also insecurity and poor marketing).', noProj: 'discuss the road to the Bénoué park.' },
  ],
  summary: [
    D([['Tourism:', "It is travelling to and staying in places outside one's usual environment for leisure, business or other purposes."],
      ['Tourist resource:', 'It is a natural or human feature that attracts visitors.'],
      ['Tourism infrastructure:', 'It is the set of facilities that serve tourists: roads, airports, hotels, restaurants and guides.'],
      ['Ecotourism:', 'It is tourism in natural areas that protects the environment and benefits local people.']]),
    { title: '1. Tourism Resources', sub: 'A) Natural Resources', intro: 'The natural tourism resources of Cameroon are the following:',
      items: [['Wildlife parks:', 'Waza in the Far North, the Bénoué, Bouba Ndjida and Faro in the North, Korup in the South-West and the Dja and Lobéké in the forest zone attract visitors. They shelter elephants, lions, giraffes, gorillas and many birds.', 'cmr_tourism_big.png', 'the tourist sites of Cameroon'],
        ['Beaches and coasts:', 'Kribi has fine beaches and the Lobé Falls, which fall directly into the sea. Limbe has black volcanic sand and a botanical garden.', 'usa_limbe.jpg', 'Limbe'],
        ['Mountains and landscapes:', 'Mount Cameroon attracts climbers and the Race of Hope, and the Mandara Mountains offer the landscapes of Rhumsiki. The Bamenda Highlands (the Ring Road) and the Adamawa also have fine scenery.', 'lsa_mandara.jpg', 'Rhumsiki'],
        ['Lakes and waterfalls:', 'Crater lakes such as Barombi Mbo, Nyos and Ossa, the Ekom-Nkam and Menchum Falls and Lake Lagdo attract visitors. They offer fine landscapes for visitors and for boat trips.']] },
    { title: '1. Tourism Resources', sub: 'B) Human (Cultural) Resources', intro: 'The human tourism resources of Cameroon are the following:',
      items: [['Traditional palaces:', 'The Sultan\'s palace of Foumban, the palaces of the Fons such as Bafut and the lamidats of the north, such as Garoua and Rey Bouba, show the history and art of their peoples. They attract many visitors.', 'usa_bandjoun.jpg', 'a traditional palace'],
        ['Festivals:', 'The Ngondo of the Sawa in Douala, the Nguon of the Bamoun in Foumban and the Lela of Bali attract crowds every year. They show dances, costumes and rituals.'],
        ['Historical sites:', 'The slave-trade site of Bimbia recalls the history of the slave trade. German colonial buildings in Buea and other towns recall the colonial period.'],
        ['Crafts and cultures:', 'Cameroon has more than 250 ethnic groups, with their own crafts, music, dances and cuisine. This diversity is a major attraction.']] },
    { title: '2. Tourism Infrastructure, Sources and Destinations', intro: 'Tourism in Cameroon is organised as follows:',
      items: [['Infrastructure:', 'Tourists arrive through the international airports of Douala, Yaoundé and Garoua. Hotels are concentrated in the large towns, with only a few lodges near the parks.', 'usa_hotel.jpg', 'a hotel'],
        ['Organs:', 'The Ministry of Tourism and Leisure (MINTOUL) plans and promotes tourism. Regional and local councils also develop sites in their areas.'],
        ['Sources of tourists:', 'Most foreign tourists come from Europe, especially France, and from neighbouring African countries such as Nigeria, Chad and Gabon. Some also come from North America.'],
        ['Prime destinations:', 'The main destinations are Kribi, Limbe and Buea, the Western Highlands, Waza and the northern parks, and Foumban. Business tourism is important in Douala and Yaoundé.']] },
    { title: "3. Problems Hindering Tourism", sub: "A) Access and Security", intro: "Tourism is hindered by the following problems of access and security:",
      items: [["Poor access:", "Bad roads and few domestic flights make many tourist sites difficult to reach. Tourists therefore spend too much time and money on travel.", "f2t_muddy_road.jpg", "a bad road"],
        ["Insecurity:", "Boko Haram in the Far North and the crisis in the North-West and South-West have closed some sites, such as Waza and the Ring Road. Many countries advise their citizens not to visit these regions."]] },
    { title: "3. Problems Hindering Tourism", sub: "B) Services and Resources", intro: "Tourism is also hindered by the following problems:",
      items: [["Few services:", "There are few good hotels, guides and restaurants outside the large towns. Tourists find it hard to stay near the sites."],
        ["Poor promotion:", "Cameroon is little known on the international tourist market. Few tour operators sell trips to the country."],
        ["Poaching and degradation:", "Poaching and bush fires reduce the wildlife of the parks. The parks then attract fewer visitors."]] },
    { title: "4. Measures to Promote Tourism", sub: "A) Measures by the Government", intro: "The government can promote tourism by the following measures:",
      items: [["Improving security:", "The army and police must make tourist regions safe again. Tourists will return when they feel safe."],
        ["Improving roads and airports:", "Good roads and more domestic flights make the sites easier to reach. Tourists then spend less time and money on travel."],
        ["Training tourism staff:", "Schools of tourism train guides, cooks and hotel staff. Better services satisfy tourists."],
        ["Promotion abroad:", "The government should advertise \"Destination Cameroon\" at international fairs and on the internet. More foreign tourists will then know the country."]] },
    { title: "4. Measures to Promote Tourism", sub: "B) Measures by Communities and Individuals", intro: "Communities and individuals can promote tourism by the following measures:",
      items: [["Community-based tourism:", "Villages can offer village stays, cultural festivals and crafts to visitors. The money earned stays in the community."],
        ["Protection of sites:", "Communities must protect the parks, forests and monuments near them. These sites are the source of their tourist income."],
        ["Good services at fair prices:", "Guides, hotel owners and drivers should offer good, honest services at fair prices. Satisfied tourists then return and recommend Cameroon to others."]] },
    { title: "5. Impacts of Tourism", sub: "A) Positive Impacts", intro: "Tourism has the following positive impacts:",
      items: [["Foreign currency:", "Foreign tourists spend money in hotels, restaurants and markets. Tourism therefore brings foreign currency to the country."],
        ["Jobs:", "Tourism creates jobs for guides, hotel staff, drivers and craftsmen. It also provides a market for crafts and local food."],
        ["Pride in local culture:", "Visitors show interest in palaces, festivals and crafts. Local people become proud of their culture and preserve it."],
        ["Money for conservation:", "Entry fees to parks pay for guards and conservation. Local people see that protecting wildlife is profitable."]] },
    { title: "5. Impacts of Tourism", sub: "B) Negative Impacts", intro: "Tourism has the following negative impacts:",
      items: [["Unstable income:", "The number of tourists falls quickly in times of insecurity or crisis. People who live from tourism then lose their income."],
        ["Rising prices:", "Prices of food and land rise in tourist areas. Local people find life more expensive."],
        ["Loss of meaning of traditions:", "Some dances and rituals are performed only for money. They then lose their original meaning."],
        ["Pollution and disturbance of wildlife:", "Tourists and hotels produce waste and pollution. Vehicles and visitors also disturb the animals of the parks."]] },
  ],
  evaluation: [['Give two natural and two human tourism resources of Cameroon.', 'Waza National Park and the beaches of Kribi; the Foumban palace and the Ngondo festival.'], ['Give two problems of tourism and one measure to promote it.', 'Bad roads and insecurity; improving security (or roads).']],
  remediation: ['The ministry in charge of tourism is ______.', 'The festival of the Sawa people in Douala is the ______.', 'The waterfall of Kribi that falls into the sea is the ______ Falls.'],
  remediationAnswers: '1. MINTOUL 2. Ngondo 3. Lobé',
  homework: 'Name one region of Cameroon that is more developed and one that is less developed.',
  hwAnswer: 'More developed: the Littoral (Douala) or the Centre (Yaoundé). Less developed: the Far North, the North or the Adamawa.',
  bilingual: [['Tourism', 'Le tourisme'], ['Tourist', 'Le touriste'], ['Hotel', "L'hôtel"], ['National park', 'Le parc national'], ['Festival', 'Le festival'], ['Guide', 'Le guide'], ['Beach', 'La plage'], ['Crafts', "L'artisanat"]],
});

L.push({ no: 15, title: 'Contrasts in Development within Cameroon', subtopic: 'Economic Activities and Development of Cameroon', pointPerSlide: true,
  notions: 'Development, regional inequality, core, periphery, backwash effects, spread effects, indicators of development, decentralisation.',
  focus: 'Recall of the models of regional inequality (Friedmann and Myrdal); contrasting regions (case study: Adamawa versus the Coastal lowlands); indicators of differences in development; factors; measures attempted to reduce inequality.',
  competence: 'Learners are able to explain the contrasts in development between regions of Cameroon and assess the measures taken to reduce them.',
  objectives: ['Recall the models of Friedmann and Myrdal.', 'Compare a prosperous region and a lagging region with indicators of development.', 'Explain the factors of the inequality.', 'Assess the measures attempted to reduce regional inequality.'],
  recall: ['Douala is the economic capital of Cameroon.', 'The Adamawa is mainly a cattle-rearing region.', 'Development means improving the living conditions of people.'],
  situation: 'Hamadou, from Garoua, wants to become a software engineer. He discovers that the best courses, the technology companies and fast internet are in Yaoundé and Douala, where his cousin has already found an internship. Hamadou asks: "Why are some regions of Cameroon so much more developed than others, and what can be done about it?"',
  sitQA: [['What is the problem in the situation?', 'Development is unequal between regions, and Hamadou wants to know why and what can be done.'],
    ['Where are the best opportunities?', 'In Yaoundé and Douala.'],
    ['What is this unequal development called?', 'Regional inequality (contrasts in development).']],
  justification: 'This lesson helps us to understand regional inequalities in Cameroon and the policies to reduce them.',
  action: 'Take part in the development of your region and support balanced national development.',
  activities: [
    { sec: '1. MODELS OF REGIONAL INEQUALITY', img: 'core_periphery_big.png', caption: 'A core and its periphery.', q: 'Where do skilled people and capital go in the core-periphery model?', a: 'Towards the core (the most developed region).', noProj: 'draw a core and its periphery.' },
    { sec: '2. CONTRASTING REGIONS', img: 'cmr_contrast_big.png', caption: 'Prosperous and lagging regions.', q: 'Is Douala a prosperous or a lagging region?', a: 'A prosperous region (a core).', noProj: 'mark cores and lagging regions.' },
    { sec: '3. INDICATORS', img: 'cmr_dev_table_big.png', caption: 'Coastal lowlands and Adamawa compared.', q: 'Which region has more schools and hospitals?', a: 'The coastal lowlands (Littoral).', noProj: 'copy the table.' },
    { sec: '4. FACTORS', img: 'lsa_douala.jpg', caption: 'Douala.', q: 'Give one natural advantage of the coastal lowlands.', a: 'Access to the sea (port), also oil and fertile soils.', noProj: 'compare Douala and Ngaoundéré.' },
    { sec: '5. MEASURES', img: 'usa_school.jpg', caption: 'A school.', q: 'How can building schools in lagging regions reduce inequality?', a: 'It trains local people, who can find better jobs and develop their region.', noProj: 'name new universities of the north.' },
  ],
  summary: [
    D([['Development:', 'It is the improvement of the living conditions of people (income, health, education, services).'],
      ['Regional inequality:', 'It is the unequal level of development between regions of a country.'],
      ['Core:', 'It is a prosperous region where population, capital and activities are concentrated.'],
      ['Periphery:', 'It is a less developed region that depends on the core.']]),
    { title: '1. Recall of the Models of Regional Inequality', intro: 'Regional inequality is explained by the following models:',
      items: [["Myrdal's cumulative causation (1957):", 'A region with an initial advantage, such as a port or a capital, attracts investment and grows. Its growth then attracts even more activities, so the advantage keeps increasing by a cumulative process.', 'core_periphery_big.png', 'the core and the periphery'],
        ['Backwash and spread effects:', 'The growing region draws labour, capital and raw materials from poorer regions, which is the backwash effect. Later, some growth spreads to them through demand for their products, which is the spread effect, but backwash is often stronger.'],
        ["Friedmann's core-periphery model (1966):", 'A dominant core concentrates wealth, while a dependent periphery supplies it with labour and raw materials. Inequality grows in the early stages of development and may fall later, when development spreads to the periphery.']] },
    { title: '2. The Contrasting Regions: Case Study', intro: 'The case study compares the following two regions:',
      items: [['The prosperous region, the Coastal lowlands:', 'With Douala, Limbe and Kribi, the Coastal lowlands are the economic heart of Cameroon. They concentrate the port, industries, plantations, oil and most services.', 'cmr_contrast_big.png', 'a prosperous and a lagging region'],
        ['The lagging region, the Adamawa:', 'The Adamawa is a high, landlocked plateau, sparsely populated and far from the sea. Its people live mainly from cattle rearing and farming.', 'lsa_adamawa.jpg', 'the Adamawa']] },
    { title: "3. Indicators of Differences in Development", sub: "A) Economic Indicators", intro: "The differences between the two regions are shown by the following economic indicators:",
      items: [["Income and poverty:", "In 2014, only about 4 % of the people of Douala were poor, against about 47 % in the Adamawa. Incomes are therefore much higher on the coast.", "cmr_dev_table_big.png", "indicators of development"],
        ["Employment:", "The coast offers many formal jobs in industry, the port and services, with regular wages. In the Adamawa, most people work in farming and herding, with low and irregular incomes."],
        ["Infrastructure:", "Paved roads, electricity, piped water and internet are much better on the coast. Many villages of the Adamawa still lack them."]] },
    { title: "3. Indicators of Differences in Development", sub: "B) Social Indicators", intro: "The differences are also shown by the following social indicators:",
      items: [["Education:", "The coast has many schools and universities, such as those of Douala and Buea. The Adamawa has fewer schools, and school enrolment is lower."],
        ["Health:", "The coast has many hospitals and doctors. In the Adamawa, health centres are fewer and farther apart, so many people lack care."]] },
    { title: '4. Factors of the Inequality', intro: 'The inequality is explained by the following factors:',
      items: [['Natural resources and position:', 'The coast has the sea, oil, gas and fertile volcanic soils, and it is the gateway for trade. The Adamawa is landlocked, far from the ports and has poorer soils.', 'lsa_douala.jpg', 'Douala'],
        ['Human resources:', 'The coast attracts skilled people and has more educated workers. The Adamawa loses many of its young people to the towns of the south, which is the backwash effect.'],
        ['Historical factors:', 'The colonial rulers invested first on the coast, where they built the port, the railway and the plantations. This early advantage has lasted until today.'],
        ['Government policy and investment:', 'For a long time, public investment was concentrated in Douala and Yaoundé. This attracted private investment there and left other regions behind.']] },
    { title: '5. Measures Attempted to Reduce Inequality', sub: 'A) Political and Administrative Measures', intro: 'Each measure reduces the gap between the rich coast and lagging regions such as the Adamawa and the North in the following way:',
      items: [['Decentralisation:', "The State transfers powers and money to elected Regional Councils (since 2020) and to councils. It reduces inequality because decisions and money are no longer concentrated in Yaoundé; each region can spend its own budget on its own roads, schools and water points."],
        ['Regional development agencies (MEADEN in the North, MIDENO and UNVDA in the North-West):', "These bodies bring projects, technicians and money to regions that private investors neglect. They reduce inequality because they replace the missing private investment and create jobs and income where there were few."],
        ['Special reconstruction plans (Far North, North-West, South-West):', "The State rebuilds schools, health centres and roads destroyed by insecurity. They reduce inequality because they stop these regions from falling further behind and allow people to return and work."]] },
    { title: '5. Measures Attempted to Reduce Inequality', sub: 'B) Socio-Economic Measures', intro: 'Each measure reduces the gap between the rich coast and lagging regions such as the Adamawa and the North in the following way:',
      items: [['Roads and railway (National Road No. 1, Ngaoundéré–Garoua road, railway to Ngaoundéré):', "Remote regions are connected to markets and to the port of Douala. This reduces inequality because transport becomes cheaper and faster, so farmers and herders sell more at better prices, and firms can settle outside the coast."],
        ['Electricity and water (Lagdo dam, rural electrification):', "The North receives electricity and water for irrigation. This reduces inequality because factories, mills and shops can work, and irrigated rice gives farmers a second harvest and more income."],
        ['Support to agriculture and livestock (SODECOTON, Adamawa livestock projects):', "Farmers receive seeds, fertiliser and a guaranteed market. This reduces inequality because it raises incomes in rural regions whose economy depends almost only on farming and herding."],
        ['Universities and hospitals (Ngaoundéré 1993, Maroua 2008, Garoua 2022; regional hospitals):', "Higher education and health care come closer to the people. This reduces inequality because young people study near home instead of leaving for Douala or Yaoundé, skilled workers stay in their region, and people live healthier and work more."]] },
    { title: '5. Measures Attempted to Reduce Inequality', sub: 'C) Difficulties and Challenges', intro: 'These measures have only partly reduced inequality for the following reasons:',
      items: [['Limited funding and poor management:', "The national budget is small, large projects such as roads and dams often depend on foreign loans, and part of the money is misused. As a result, many projects in lagging regions are delayed, badly built or left unfinished."],
        ['Incomplete decentralisation:', "Regional and local councils still receive only a small share of the State budget and lack qualified staff. They therefore cannot really plan and finance their own development, and many decisions are still taken in Yaoundé."],
        ['Insecurity:', "Boko Haram attacks in the Far North and the crisis in the North-West and South-West have destroyed schools, health centres, markets and roads. Investors and civil servants avoid these regions, and many people have fled, so the gap with the coast has widened."],
        ["Strong backwash effects:", "Douala and Yaoundé keep attracting capital, industries and educated young people from the whole country. Growth spreads to the periphery much more slowly than resources leave it, as Myrdal's model predicts."]] },
  ],
  evaluation: [['Distinguish between backwash and spread effects.', 'Backwash effects draw labour and capital from poor regions to the core; spread effects are the growth that spreads from the core to poorer regions.'], ['Give two indicators that show that the coast is more developed than the Adamawa.', 'Lower poverty and more schools and hospitals (also more formal jobs and better roads).']],
  remediation: ['The prosperous region in the core-periphery model is the ______.', 'The model of cumulative causation was proposed by ______.', 'Giving powers to regional and local councils is ______.'],
  remediationAnswers: '1. core 2. Myrdal 3. decentralisation',
  homework: 'List three indicators of development.',
  hwAnswer: 'Examples: income per person, literacy (school enrolment), life expectancy, access to health care, safe water and electricity.',
  bilingual: [['Development', 'Le développement'], ['Regional inequality', "L'inégalité régionale"], ['Core', 'Le centre'], ['Periphery', 'La périphérie'], ['Poverty', 'La pauvreté'], ['Indicator', "L'indicateur"], ['Decentralisation', 'La décentralisation'], ['Infrastructure', "L'infrastructure"]],
});

module.exports = { B, L };
