// LOWER SIXTH ARTS — Climatology: Lesson 19, Further Study 1, Lessons 20–21 (Climates)
// Rewritten from the teacher's course supports (LSA_LESSONS_METEOROLOGY_2026, USA_LESSONS_METEO) in our own words; facts checked.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const OLD = require('../v2_lsa_clim').B;
const B = Object.assign({}, OLD, {
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Module 1 (Meteorology, Climatology & Hydrology).', 'Teacher\'s course notes: Mr KAMDEM E., Meteorology and Climatology (LSA), GBHS Garoua, 2026.'] });
const L = [];
const T = 'Climates';

L.push({ no: 19, title: "Meaning of Climate and Köppen's Classification", topic: T, subtopic: 'Basic Notions of Climate', pointPerSlide: true,
  notions: 'Weather, climate, elements of climate, controls of climate, temperature range, genetic classification, empirical classification, Köppen.',
  focus: 'Meaning and characteristics of climate; elements of climate; general factors (controls) of climate; genetic and empirical classifications; Köppen\'s classification and its main groups.',
  competence: 'Learners are able to distinguish weather from climate, explain the controls of climate and classify climates with Köppen\'s system, including that of Garoua.',
  objectives: ['Distinguish weather from climate.', 'Name and describe the elements of climate.', 'Explain the controls of climate.', 'Distinguish genetic and empirical classifications.', 'Describe the main groups of Köppen\'s classification.'],
  recall: ['Air masses control the seasons of Garoua.', 'Temperature falls with altitude.', 'Deserts lie under high-pressure belts.'],
  situation: 'In the evening, you tell your grandfather how hot the day was. He answers: "Yes, but things have changed. When I was young, the rainy season was longer and the Harmattan nights were colder; we knew exactly when to plant. Now everything is less predictable." You ask: "What is the difference between the weather of one day and what grandfather remembers over many years, and how do geographers describe and compare the climates of the world?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not distinguish weather from climate and does not know how climates are classified.'],
    ['What is "how hot the day was"?', 'The weather: the state of the atmosphere at a given time.'],
    ['What does grandfather describe?', 'The climate: the average weather over many years (30 years or more).']],
  justification: 'This lesson gives the basic notions needed to describe and compare the climates of the world and to understand climate change.',
  action: 'Use long-term averages, not one day\'s weather, to describe the climate of a place.',
  activities: [
    { sec: '1. MEANING', img: 'clim2_weather_climate.png', caption: 'Weather and climate.', q: 'Over how many years are climate averages usually calculated?', a: 'At least 30 years.', noProj: 'describe today\'s weather and the climate of Garoua.' },
    { sec: '1. ELEMENTS', img: 'f4_stevenson.jpg', caption: 'A Stevenson screen.', q: 'Name three elements of climate.', a: 'Temperature, precipitation, humidity, wind, sunshine or pressure (any three).', noProj: 'list the instruments of a weather station.' },
    { sec: '2. CONTROLS', img: 'clim2_controls.png', caption: 'The controls of climate.', q: 'Which control of climate is the most important?', a: 'Latitude (insolation).', noProj: 'compare Garoua and Paris.' },
    { sec: '3. KÖPPEN', img: 'koppen_big.png', caption: 'Köppen\'s climate groups.', q: 'Which letter does Köppen use for dry climates?', a: 'B.', noProj: 'write the five letters on the board.' },
    { sec: '3. KÖPPEN', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'Why is Garoua\'s climate classified as Aw?', a: 'All months are above 18 °C (A) and there is a dry season in winter (w).', noProj: 'read the graph of Garoua.' },
  ],
  summary: [
    D([['Weather:', 'It is the state of the atmosphere at a given place and time.'],
      ['Climate:', 'It is the average state of the weather of a place over a long period, usually 30 years or more.'],
      ['Elements of climate:', 'They are the measurable components of climate, such as temperature and rainfall.'],
      ['Controls of climate:', 'They are the factors that explain the climate of a place, such as latitude and relief.']]),
    { title: '1. Meaning of Climate', intro: 'Climate is explained as follows:',
      items: [['Weather and climate:', 'Weather is the condition of the air at a given moment and changes from hour to hour and day to day. Climate is the average weather of a place calculated over at least 30 years, so it describes what people normally expect.', 'clim2_weather_climate.png', 'weather and climate'],
        ['Example of Garoua:', 'A rainstorm on a July afternoon in Garoua is weather. The fact that Garoua normally has a long hot, dry season and a warm, wet season from May to October is its climate.']] },
    { title: '2. Elements of Climate', intro: 'The elements of climate are the following:',
      items: [['Temperature:', 'Temperature is measured in °C with thermometers kept in a Stevenson screen. Its monthly means and its range between the hottest and coolest months are used to describe a climate.', 'f4_stevenson.jpg', 'a Stevenson screen'],
        ['Precipitation:', 'Precipitation is measured in millimetres with a rain gauge. Its annual total and its distribution through the months show whether a climate is wet, dry or seasonal.'],
        ['Humidity and wind:', 'Humidity, measured in %, affects comfort, clouds and rain. Wind, measured by its direction and speed, carries heat and moisture from one region to another.'],
        ['Sunshine and pressure:', 'Sunshine, measured in hours per day, controls heating and evaporation. Atmospheric pressure, measured in hPa, controls the winds and the rising or sinking of air.', 'clim2_elements.png', 'the elements of climate']] },
    { title: '3. Characteristics of Climate', intro: 'A climate is characterised by the following features:',
      items: [['Range of temperature:', 'The range is the difference between the mean temperature of the hottest and the coolest months. It is small near the Equator and on coasts (2 to 3 °C at Douala) but larger inland and at high latitudes.'],
        ['Seasons:', 'Temperate regions have four seasons based on temperature: spring, summer, autumn and winter. Tropical regions such as Cameroon have seasons based on rainfall, a wet season and a dry season.'],
        ['Rainfall regime:', 'In some places, rain falls in every month, as in the Congo Basin; in others, it falls in one season only, as in Garoua. The regime shows when the rain falls during the year.']] },
    { title: '4. General Factors (Controls) of Climate', sub: 'A) Natural Factors', intro: 'Climate is controlled by the following natural factors:',
      items: [['Insolation (latitude):', 'Places near the Equator receive the rays of the sun almost vertically and are hot all year, while high latitudes receive slanting rays and are cold. Latitude is therefore the most important control of temperature.', 'clim2_controls.png', 'the controls of climate'],
        ['Pressure, air masses and winds:', 'Low-pressure belts bring rising air and rain, while high-pressure belts bring sinking air and drought. Winds and air masses carry heat and moisture, as the Harmattan and the monsoon do over Garoua.'],
        ['Relief:', 'Temperature falls with altitude by about 6.5 °C per 1,000 m, so highlands are cooler than lowlands. Mountains also force moist air to rise, giving heavy rain on the windward side and a rain shadow on the leeward side.'],
        ['Ocean currents:', 'Warm currents warm and moisten the air of the coasts they touch, while cold currents cool and dry it. For example, the cold Benguela Current helps to form the Namib Desert.']] },
    { title: '4. General Factors (Controls) of Climate', sub: 'B) Man', intro: 'Man influences climate in the following ways:',
      items: [['Deforestation and urbanisation:', 'Cutting forests reduces transpiration and can reduce local rainfall, while towns create heat islands. These changes modify the local climate.'],
        ['Emission of greenhouse gases:', 'Burning coal, oil, gas and forests adds carbon dioxide and methane to the atmosphere. These gases trap more heat and cause global warming, which is changing climates all over the world.']] },
    { title: '5. Classification of Climates', sub: "A) Genetic and Empirical Classifications", intro: 'Climates are classified in the following two ways:',
      items: [['Genetic classification:', 'It groups climates according to their causes, such as the air masses, pressure systems and winds that dominate each region. It explains why climates exist but is difficult to apply to data.'],
        ['Empirical classification:', 'It groups climates according to observed data, mainly temperature and rainfall, and their effect on vegetation. Köppen\'s classification is the most widely used empirical system.', 'koppen_big.png', 'the Köppen climates']] },
    { title: '5. Classification of Climates', sub: "B) Köppen's System", intro: "Köppen's system works as follows:",
      items: [['Principle:', 'Wladimir Köppen (1846 to 1940) believed that natural vegetation is the best expression of climate. He used limits of temperature and rainfall that correspond to the limits of the main vegetation zones.'],
        ['Nomenclature by letters:', 'A capital letter gives the main climate group, from A to E. A second letter shows the rainfall regime (f: rain all year, s: dry summer, w: dry winter, W: desert, S: steppe), and a third letter gives details of temperature (a: hot summer, b: warm summer, h: hot dry climate).']] },
    { title: '5. Classification of Climates', sub: "C) Köppen's Climate Groups", intro: "Köppen's five climate groups have the following characteristics:",
      items: [['Group A, tropical humid climates:', 'The coolest month is above 18 °C and rainfall is high. It includes Af (equatorial rainforest, as in the Congo Basin), Am (monsoon) and Aw (savanna with a dry winter, as in Garoua).', 'clim2_koppen.png', 'Köppen climates of Cameroon'],
        ['Group B, dry climates:', 'Evaporation is greater than rainfall. It includes BW (desert, as the Sahara) and BS (steppe, as the Sahel and the far north of Cameroon, close to BSh).'],
        ['Group C, warm temperate climates:', 'The coolest month is between −3 °C and 18 °C, so winters are mild. It includes Cs (Mediterranean, with dry summers) and Cf (always moist, as in London, Cfb).'],
        ['Groups D and E, cold climates:', 'In group D (cold continental), the coolest month is below −3 °C and the warmest above 10 °C, as in Siberia and Canada. In group E (polar), the warmest month is below 10 °C, with tundra (ET) and ice cap (EF).']] },
  ],
  evaluation: [['Distinguish weather from climate.', 'Weather is the state of the atmosphere at a given time; climate is the average weather over 30 years or more.'],
    ['Give three controls of the climate of Garoua.', 'Latitude, the Harmattan and monsoon air masses, distance from the sea (continentality), relief (any three).']],
  remediation: ['Climate is averaged over at least ______ years.', 'In Köppen\'s system, dry climates are group ______.', 'Garoua has a ______ climate (Köppen).'],
  remediationAnswers: '1. 30 2. B 3. Aw (tropical savanna)',
  homework: 'Name the cloud that produces thunderstorms.',
  hwAnswer: 'The cumulonimbus.',
  bilingual: [['Climate', 'Le climat'], ['Weather', 'Le temps'], ['Tropical', 'Tropical'], ['Dry', 'Sec, aride'], ['Temperate', 'Tempéré'], ['Classification', 'La classification']],
});

L.push({ kind: 'Further Study', no: 1, title: 'Tropical Weather Disturbances', topic: T, subtopic: 'Air Mass Interactions at Fronts and Convergence Zones', pointPerSlide: true,
  notions: 'Weather disturbance, thunderstorm, lightning, supercell, tornado, wind shear, tropical cyclone, hurricane, typhoon, storm surge, early warning.',
  focus: 'Thunderstorms, tornadoes and tropical cyclones: meaning, distribution, causes, consequences; associated hazards and control measures.',
  competence: 'Learners are able to explain the formation and dangers of tropical weather disturbances and the measures to reduce their effects.',
  objectives: ['Define thunderstorms, tornadoes and tropical cyclones.', 'Describe their distribution and causes.', 'Explain their consequences.', 'Propose measures to reduce their hazards.'],
  recall: ['Unstable air forms cumulonimbus clouds.', 'The Coriolis effect deflects winds.', 'The ITCZ is a zone of rising air.'],
  situation: 'One July afternoon in Garoua, the sky suddenly turns dark grey. A strong wind bends the trees and raises dust, then an extremely heavy rain falls so loudly on the metal roof that you hear nothing else. A flash of lightning is followed by a deafening crash of thunder. After about an hour, the storm passes, leaving flooded streets and broken branches. You ask: "What causes such storms, and are there even more dangerous storms elsewhere in the world?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the types, causes and dangers of tropical weather disturbances.'],
    ['What kind of storm hit Garoua?', 'A thunderstorm.'],
    ['Name a larger storm that forms over warm oceans.', 'A tropical cyclone (hurricane).']],
  justification: 'This lesson helps us to understand and prepare for dangerous storms, from the thunderstorms of Garoua to the cyclones of other tropical coasts.',
  action: 'During a thunderstorm, shelter inside a building and keep away from trees, water and metal objects.',
  activities: [
    { sec: '1. THUNDERSTORMS', img: 'thunderstorm_big.png', caption: 'The life of a thunderstorm.', q: 'What are the three stages of a thunderstorm?', a: 'Cumulus (growing), mature and dissipating.', noProj: 'draw the three stages.' },
    { sec: '1. THUNDERSTORMS', img: 'f4_cumulonimbus.jpg', caption: 'A cumulonimbus cloud.', q: 'Give two dangers of a thunderstorm.', a: 'Lightning, flash floods, strong winds and hail (any two).', noProj: 'describe the last storm in Garoua.' },
    { sec: '2. TORNADOES', img: 'clim2_storms.png', caption: 'Three storms compared.', q: 'Where are tornadoes most frequent?', a: 'In the central USA ("Tornado Alley").', noProj: 'compare the sizes of the storms.' },
    { sec: '3. TROPICAL CYCLONES', img: 'cyclone_big.png', caption: 'A tropical cyclone.', q: 'What are tropical cyclones called in the Atlantic?', a: 'Hurricanes.', noProj: 'draw the eye and the spiral bands.' },
    { sec: '4. CONTROL MEASURES', img: 'clim2_storm_measures.png', caption: 'Reducing storm hazards.', q: 'How can a building be protected from lightning?', a: 'With a lightning rod (conductor).', noProj: 'list safety rules for a storm.' },
  ],
  summary: [
    D([['Thunderstorm:', 'It is a local storm from a cumulonimbus cloud, with lightning, thunder, strong winds and heavy rain or hail.'],
      ['Tornado:', 'It is a violently rotating narrow column of air extending from a thunderstorm to the ground.'],
      ['Tropical cyclone:', 'It is a very large rotating storm system with a low-pressure centre, strong winds and heavy rain, formed over warm tropical seas.'],
      ['Storm surge:', 'It is an abnormal rise of the sea level caused by a storm.']]),
    { title: '1. Thunderstorms', intro: 'Thunderstorms are explained as follows:',
      items: [['Meaning:', 'A thunderstorm is a local storm produced by a cumulonimbus cloud. It brings lightning, thunder, strong gusts of wind and heavy rain or hail, usually for one or two hours.', 'f4_cumulonimbus.jpg', 'a cumulonimbus cloud'],
        ['Distribution:', 'Thunderstorms are most frequent in hot, humid regions near the Equator, such as the Congo Basin, where they occur on more than 100 days a year. In Garoua, they are common in the rainy season, especially at its start and end.'],
        ['Causes:', 'Strong heating of the ground makes moist, unstable air rise quickly by convection, and fronts or mountains can also lift it. As the vapour condenses, it releases latent heat that makes the cloud grow up to the tropopause and separates electric charges, which produce lightning.', 'thunderstorm_big.png', 'a thunderstorm'],
        ['Consequences:', 'Lightning kills people and animals and starts fires, and strong winds tear off roofs and break trees. Intense rain causes flash floods, and hail destroys crops.']] },
    { title: '2. Tornadoes', intro: 'Tornadoes are explained as follows:',
      items: [['Meaning:', 'A tornado is a narrow column of air that rotates violently and hangs from the base of a thunderstorm down to the ground. It looks like a dark funnel and usually lasts only a few minutes.'],
        ['Distribution:', 'Tornadoes occur in many parts of the world but are most frequent and violent in the central United States, called Tornado Alley, with more than 1,000 a year. They also occur in Bangladesh, Argentina and sometimes in West Africa.', 'clim2_storms.png', 'storm hazards'],
        ['Causes:', 'They form in the most severe thunderstorms, called supercells, where warm, moist air meets cold, dry air. Changes of wind speed and direction with height (wind shear) make the rising air rotate, and the rotation tightens into a funnel.'],
        ['Consequences:', 'Winds can exceed 400 km/h and turn debris into dangerous missiles that destroy houses and vehicles. The damage is very severe but limited to a narrow path, usually less than 1 to 2 km wide.']] },
    { title: '3. Tropical Cyclones', intro: 'Tropical cyclones are explained as follows:',
      items: [['Meaning:', 'A tropical cyclone is a huge rotating storm, 500 to 1,000 km wide, around a calm centre called the eye, with winds above 119 km/h. It is called a hurricane in the Atlantic, a typhoon in the north-west Pacific and a cyclone in the Indian Ocean.', 'cyclone_big.png', 'a tropical cyclone'],
        ['Distribution:', 'Tropical cyclones form over warm oceans between about 5° and 20° N and S, and then move westwards and towards the poles. They are almost absent from the South Atlantic, so the coast of Cameroon is rarely affected.'],
        ['Causes:', 'Sea water warmer than 26.5 °C supplies heat and moisture, and the rising air forms a deep low pressure. The Coriolis effect, which is absent at the Equator, makes the air spin, and the latent heat released in the clouds feeds the storm.', 'f4_hurricane.jpg', 'a hurricane seen from space'],
        ['Consequences:', 'Violent winds destroy buildings, crops and power lines over hundreds of kilometres. Storm surges flood the coasts and cause most of the deaths, and days of torrential rain cause floods and landslides.']] },
    { title: '4. Hazards and Control Measures', intro: 'The hazards of these disturbances are reduced by the following measures:',
      items: [['Early warning:', 'Radars and satellites follow storms, and weather services send alerts by radio, television and telephone. People then have time to take shelter or to leave threatened areas.', 'clim2_storm_measures.png', 'control measures'],
        ['Public education:', 'People learn to shelter indoors during storms and to avoid trees, open fields, water and metal objects when there is lightning. Drills teach them what to do when a warning is given.'],
        ['Protection of buildings:', 'Lightning rods, strong roofs and building codes that resist wind reduce damage. Good drains reduce the floods caused by heavy rain.'],
        ['Emergency preparedness:', 'Governments build storm shelters, plan evacuation routes and train rescue services. After a disaster, they provide water, food, shelter and medical care.']] },
  ],
  evaluation: [['Compare a thunderstorm and a tropical cyclone by size and place of formation.', 'A thunderstorm is small (a few km) and forms over land or sea; a cyclone is hundreds of km wide and forms over warm tropical oceans.'],
    ['Give two measures to reduce the hazards of thunderstorms.', 'Early warnings, lightning rods, staying indoors, good drainage (any two).']],
  remediation: ['Thunderstorms form from ______ clouds.', 'Atlantic tropical cyclones are called ______.', 'A rise of the sea caused by a storm is a storm ______.'],
  remediationAnswers: '1. cumulonimbus 2. hurricanes 3. surge',
  homework: 'Define a micro-climate.',
  hwAnswer: 'A micro-climate is the climate of a small area that differs from the climate of the surrounding region.',
  bilingual: [['Thunderstorm', "L'orage"], ['Tornado', 'La tornade'], ['Tropical cyclone', 'Le cyclone tropical'], ['Lightning', "L'éclair, la foudre"], ['Flooding', "L'inondation"], ['Storm surge', "L'onde de tempête"]],
});

L.push({ no: 20, title: 'Micro-climates', topic: T, subtopic: 'Concept of Micro-climate', pointPerSlide: true,
  notions: 'Micro-climate, urban climate, urban heat island, anthropogenic heat, evapotranspiration, urban canyon, lakeside climate, forest climate.',
  focus: 'Meaning and classification of micro-climates; characteristics of urban climates; factors of the urban heat island.',
  competence: 'Learners are able to explain micro-climates, especially why the centre of Garoua is hotter than its outskirts, and propose ways to reduce urban heat.',
  objectives: ['Define a micro-climate.', 'Classify micro-climates.', 'Describe the characteristics of urban climates.', 'Explain the factors of the urban heat island.'],
  recall: ['Tar and concrete absorb heat.', 'Plants cool the air by transpiration.', 'Climate is controlled by several factors.'],
  situation: 'On a very hot May afternoon, you leave your family\'s compound in Roumdé Adjia, with many trees and bare ground, and take a moto-taxi to the Grand Marché in the centre of Garoua. As you approach the market, the air becomes hotter and more suffocating; heat rises from the tarred roads and concrete buildings. You ask: "Why does such a short distance make such a big difference in temperature?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand micro-climates and the urban heat island.'],
    ['What is the climate of a small area called?', 'A micro-climate.'],
    ['Why is the town centre hotter?', 'Tar, concrete, engines and few trees create an urban heat island.']],
  justification: 'This lesson helps us to understand local differences of climate and to plan cooler, healthier towns.',
  action: 'Plant and protect trees and green spaces in town, and use light-coloured roofs.',
  activities: [
    { sec: '1. MEANING', img: 'clim2_micro_types.png', caption: 'Types of micro-climates.', q: 'Give two types of micro-climates.', a: 'Urban, mountain, lakeside or forest micro-climates (any two).', noProj: 'list micro-climates around Garoua.' },
    { sec: '1. MEANING', img: 'lsa_lake.jpg', caption: 'A lakeside.', q: 'Why is the air near Lake Lagdo cooler and more humid?', a: 'The water evaporates and heats slowly.', noProj: 'describe a lakeside.' },
    { sec: '2. URBAN CLIMATE', img: 'heat_island_big.png', caption: 'The urban heat island.', q: 'When is the urban heat island strongest?', a: 'At night, when buildings and roads release stored heat.', noProj: 'draw the temperature profile.' },
    { sec: '2. URBAN CLIMATE', img: 'lsa_douala.jpg', caption: 'A large city.', q: 'Why is the air of a city drier?', a: 'There are fewer plants and less open water, so less evapotranspiration.', noProj: 'compare a street and a garden.' },
    { sec: '3. FACTORS', img: 'f2t_rainforest.jpg', caption: 'A forest.', q: 'Why is it cooler under trees?', a: 'Trees give shade and cool the air by transpiration.', noProj: 'stand in the sun and in the shade of a mango tree.' },
  ],
  summary: [
    D([['Micro-climate:', 'It is the climate of a small area that differs from the climate of the surrounding region.'],
      ['Meso-climate:', 'It is the climate of a medium-sized area, such as a town, a valley or a lake shore, a few kilometres to tens of kilometres wide.'],
      ['Heat island:', 'It is the higher temperature of a town compared with the surrounding countryside.'],
      ['Anthropogenic heat:', 'It is the heat released by human activities (vehicles, machines, air conditioners).']]),
    { title: '1. Meaning of Micro-climates', intro: 'Micro-climates are explained as follows:',
      items: [['Micro-climate:', 'A micro-climate is the special climate of a small area, from a few metres to a few kilometres, such as a garden, a forest clearing or a street. It differs from the regional climate because of local surfaces, relief, water or vegetation.', 'clim2_micro_types.png', 'types of micro-climates'],
        ['Micro- and meso-climates:', 'The climate of a larger area, such as a whole town or a valley, is called a meso-climate. In practice, both are studied together as local climates, different from the macro-climate of a region.']] },
    { title: '2. Classification of Micro-climates', intro: 'Micro-climates are classified into the following types:',
      items: [['Urban climate:', 'The climate of a town is warmer, drier and more polluted than that of the surrounding countryside. It is created by buildings, roads, vehicles and industries.', 'lsa_douala.jpg', 'Douala'],
        ['Mountain climate:', 'On a mountain, temperature and rainfall change with altitude and with the side of the slope. Each level therefore has its own climate and vegetation.'],
        ['Lakeside climate:', 'Along a large lake, such as Lake Lagdo or Lake Chad, the water keeps the air cooler by day and more humid. Lake breezes blow onto the shore in the afternoon.', 'lsa_lake.jpg', 'a lake shore'],
        ['Forest climate:', 'Inside a forest, the trees block the sun and the wind and release water vapour. The air is therefore shady, cool, humid and calm, with a small daily range of temperature.', 'f2t_rainforest.jpg', 'a forest']] },
    { title: '3. Characteristics of Urban Climates', intro: 'Compared with the countryside, towns have the following climatic characteristics:',
      items: [['Higher temperatures:', 'Towns are warmer than the countryside, especially at night, by 2 to 5 °C in large cities. This is the urban heat island, strongest in the town centre.', 'heat_island_big.png', 'the urban heat island'],
        ['Lower humidity:', 'Rainwater runs quickly into drains, and there are few plants and little open water. As a result, there is less evapotranspiration and the air is drier.'],
        ['Modified winds:', 'Buildings slow down the wind, so towns are generally calmer. However, wind can be channelled and strengthened in narrow streets between tall buildings.'],
        ['More pollution and more rain:', 'Dust, smoke and gases from vehicles, generators and factories are concentrated over towns. These particles and the extra heat can trigger more convectional storms over and downwind of large cities.', 'clim2_urban.png', 'the urban climate']] },
    { title: '4. Factors of Urban Climates', intro: 'The urban climate is explained by the following factors:',
      items: [['Artificial surfaces:', 'Tarred roads, concrete and bricks absorb much solar energy by day and release it slowly at night. They also make rainwater run off quickly, so less water is available for evaporation.'],
        ['Anthropogenic heat:', 'Cars, moto-taxis, generators, air conditioners, factories and crowds all release heat. In big cities, this heat can equal a large part of the energy received from the sun in winter.'],
        ['Reduced evapotranspiration:', 'Towns have few trees, gardens and open soils. The energy that would be used to evaporate water is used instead to warm the air.'],
        ['Urban geometry:', 'Tall buildings and narrow streets form urban canyons that trap the heat radiated by walls and roads. They also block the wind that could carry this heat away.']] },
  ],
  evaluation: [['What is the urban heat island, and give two of its causes in Garoua?', 'The town is warmer than the countryside; causes: tar and concrete, heat from vehicles and generators, few trees (any two).'],
    ['Give two differences between an urban climate and a rural climate.', 'Towns are warmer, drier, less windy and more polluted (any two).']],
  remediation: ['The climate of a small area is a ______.', 'A town warmer than the countryside is an urban heat ______.', 'Heat from vehicles and machines is ______ heat.'],
  remediationAnswers: '1. micro-climate 2. island 3. anthropogenic',
  homework: 'State how temperature changes with altitude.',
  hwAnswer: 'Temperature decreases as altitude increases, by about 6.5 °C per 1,000 m.',
  bilingual: [['Micro-climate', 'Le microclimat'], ['Urban climate', 'Le climat urbain'], ['Urban heat island', "L'îlot de chaleur urbain"], ['Pollution', 'La pollution'], ['Evapotranspiration', "L'évapotranspiration"], ['Green space', "L'espace vert"]],
});

L.push({ no: 21, title: 'Mountain Climates', topic: T, subtopic: 'Concept of Micro-climate', pointPerSlide: true,
  notions: 'Mountain (highland) climate, lapse rate, air pressure, orographic rain, rain shadow, ultraviolet radiation, daily range, vertical zonation, altitude, relief, aspect, latitude.',
  focus: 'Characteristics of mountain climates; vertical zonation; factors of mountain climates (altitude, relief, aspect, latitude).',
  competence: 'Learners are able to explain the climate of mountains such as the Mandara Mountains and Mount Cameroon and its effects on vegetation and people.',
  objectives: ['Define a mountain climate.', 'Describe its main characteristics.', 'Explain the vertical zonation of climate and vegetation.', 'Explain the factors of mountain climates.'],
  recall: ['Temperature falls about 6.5 °C per 1,000 m.', 'Moist air rising over mountains gives relief rain.', 'Aspect is the direction a slope faces.'],
  situation: 'Your family travels from Garoua to Mokolo in the Mandara Mountains. In Garoua the air is hot and dusty, but as the car climbs the winding road, the air through the window becomes cooler and fresher. Yet the sun on your arm feels sharper than in Garoua. You ask: "Why is the air cooler in the mountains while the sun burns more, and how does the climate change so much over such a short distance?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the characteristics and factors of mountain climates.'],
    ['Why is the air cooler in the mountains?', 'Because of altitude: temperature falls as height increases.'],
    ['Why does the sun burn more?', 'The thin, clean air filters less of the Sun\'s ultraviolet rays.']],
  justification: 'This lesson explains the cool, wet highland climates of Cameroon that support dense populations, tea, coffee and tourism.',
  action: 'Protect your skin from strong sun in the mountains and carry warm clothes for cold nights.',
  activities: [
    { sec: '1. CHARACTERISTICS', img: 'lapse_rate_big.png', caption: 'Temperature and height.', q: 'If Garoua (about 200 m) is at 34 °C, what is the temperature at Mokolo (about 800 m)?', a: '34 − (0.6 × 6.5) ≈ 30 °C.', noProj: 'calculate on the board.' },
    { sec: '1. CHARACTERISTICS', img: 'rainfall_types_big.png', caption: 'Relief rain and rain shadow.', q: 'Which side of a mountain receives more rain?', a: 'The windward side.', noProj: 'draw a mountain with wind and rain.' },
    { sec: '1. CHARACTERISTICS', img: 'clim2_mountain.png', caption: 'Characteristics of mountain climates.', q: 'Why are mountain nights very cold?', a: 'The thin air cannot keep the heat, which escapes quickly.', noProj: 'list the five characteristics.' },
    { sec: '2. VERTICAL ZONATION', img: 'veg_altitude_big.png', caption: 'Vegetation zones on Mount Cameroon.', q: 'What is found near the summit of Mount Cameroon?', a: 'Bare lava and rock (with montane grassland below).', noProj: 'draw the zones on a mountain.' },
    { sec: '3. FACTORS', img: 'aspect_big.png', caption: 'The aspect of slopes.', q: 'Which slope is warmer and drier: the one facing the sun or the one facing away?', a: 'The one facing the sun.', noProj: 'compare two sides of a hill.' },
  ],
  summary: [
    D([['Mountain climate:', 'It is the climate of high-altitude areas, cooler and wetter than the surrounding lowlands.'],
      ['Vertical zonation:', 'It is the succession of climate and vegetation zones from the foot to the top of a mountain.'],
      ['Mountain barrier:', 'It is a mountain range that blocks moving air, forcing it to rise on one side and descend on the other.']]),
    { title: '1. Characteristics of Mountain Climates', sub: 'A) Temperature and Pressure', intro: 'Mountain climates have the following characteristics of temperature and pressure:',
      items: [['Lower temperatures:', 'Temperature falls by about 6.5 °C for every 1,000 m of altitude. This is why Bamenda (about 1,200 m) and the Mandara Mountains are cooler than the plains around them.', 'lapse_rate_big.png', 'the fall of temperature with height'],
        ['Lower air pressure:', 'The higher we climb, the less air there is above us, so the pressure and the amount of oxygen fall. At high altitude, people breathe with difficulty and water boils below 100 °C.'],
        ['Large daily range of temperature:', 'The thin air lets the sun heat the ground strongly by day but lets heat escape quickly at night. Days are therefore warm in the sun, while nights are very cold, with frost on high summits.', 'clim2_mountain.png', 'the mountain climate']] },
    { title: '1. Characteristics of Mountain Climates', sub: 'B) Rainfall and Radiation', intro: 'Mountain climates have the following characteristics of rainfall and radiation:',
      items: [['Heavy rain on windward slopes:', 'Moist air forced to rise over mountains cools and gives orographic rain, as on the seaward side of Mount Cameroon. The leeward side receives much less rain and forms a rain shadow.', 'rainfall_types_big.png', 'relief rainfall'],
        ['Mist and cloud:', 'The slopes are often in the clouds, especially in the rainy season. Mist and drizzle keep the air humid on the middle slopes.'],
        ['Strong solar radiation:', 'The thin, clean air lets more sunshine and ultraviolet rays through than in the lowlands. People can therefore get sunburnt quickly even when the air is cool.']] },
    { title: '2. Vertical Zonation: Mount Cameroon', intro: 'On Mount Cameroon, climate and vegetation change with height as follows:',
      items: [['Lower slopes (0 to 800 m):', 'The climate is hot and very wet, with more than 3,000 mm of rain on the seaward side. The natural vegetation is lowland rainforest, largely replaced by plantations of the CDC.', 'veg_altitude_big.png', 'vertical zonation'],
        ['Middle slopes (800 to 2,400 m):', 'The climate is cooler and often misty. It supports submontane and montane forest with tree ferns, mosses and epiphytes.'],
        ['Upper slopes (2,400 to 3,800 m):', 'The climate is cool to cold, with less rain above the cloud layer. Montane grassland replaces the forest.'],
        ['Summit (above 3,800 m):', 'The climate is cold, windy and dry, with frost at night. The ground is mostly bare lava and rock with few plants.']] },
    { title: '3. Factors of Mountain Climates', intro: 'Mountain climates are controlled by the following factors:',
      items: [['Altitude:', 'Altitude is the most important factor, because height lowers both temperature and pressure. Each rise of 1,000 m cools the air by about 6.5 °C.'],
        ['Relief (mountain barrier):', 'The shape and direction of a mountain range force moving air to rise on one side and descend on the other. This gives rain on the windward side and a dry, warm rain shadow on the leeward side.'],
        ['Aspect:', 'Slopes facing the sun (adret) receive more heat and are warmer and drier. Slopes facing away from it (ubac) are cooler, shadier and moister.', 'aspect_big.png', 'adret and ubac'],
        ['Latitude:', 'Latitude sets the base temperature of the mountain. A mountain near Garoua has a much warmer foot, and a higher snow line, than a mountain of the same height in Europe.']] },
  ],
  evaluation: [['Give three characteristics of mountain climates.', 'Lower temperatures, lower pressure, heavy windward rain, strong sunshine, large daily range (any three).'],
    ['Explain why the sun feels stronger in the mountains although the air is cooler.', 'The thin, clean air filters less solar and ultraviolet radiation.']],
  remediation: ['The most important factor of mountain climates is ______.', 'The sheltered side of a mountain is the ______ side.', 'The change of vegetation with height is vertical ______.'],
  remediationAnswers: '1. altitude 2. leeward 3. zonation',
  homework: 'Name one instrument of a weather station.',
  hwAnswer: 'A thermometer, a rain gauge, a barometer, a wind vane, an anemometer or a hygrometer (any one).',
  bilingual: [['Mountain', 'La montagne'], ['Altitude', "L'altitude"], ['Aspect', "L'exposition"], ['Relief', 'Le relief'], ['Precipitation', 'Les précipitations'], ['Rain shadow', "L'ombre pluviométrique"]],
});

module.exports = { B, L };
