// LOWER SIXTH ARTS — Geography of Cameroon, lessons 1–5 (physical geography of Cameroon)
// Syllabus 2019: M2 FS2 (relief), M1 FS3 (climate), M3 FS1 (soils), M3 FS2 (vegetation), M1 FS4 (drainage).
// Guided by the teacher's course notes (LSA_CAM_GEO_2026); figures checked and updated.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'LSA', code: 'CAM', folder: 'Geography of Cameroon', module: 'Geography of Cameroon', topicDefault: 'Geography of Cameroon', branch: 'The Physical Environment of Cameroon',
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Geography of Cameroon.', 'Teacher\'s course notes: Mr KAMDEM E., Cameroon Geography (LSA), GBHS Garoua, 2026.'] };
const L = [];

L.push({ no: 1, title: 'Relief of Cameroon', subtopic: 'The Physical Environment of Cameroon', pointPerSlide: true,
  notions: 'Relief, physiography, physiographic region, highland, lowland, plateau, depression, Cameroon Volcanic Line.',
  focus: 'Physiography: physiographic regions; major highlands and lowlands of Cameroon; general characteristics of each unit.',
  competence: 'Learners are able to identify the physiographic regions of Cameroon on a map and describe the characteristics of its major highlands and lowlands.',
  objectives: ['Define relief, physiography, highland and lowland.', 'Identify the major physiographic regions of Cameroon on a map.', 'Describe the general characteristics of the major highlands.', 'Describe the general characteristics of the major lowlands.'],
  recall: ['Relief is made of mountains, plateaux, plains and valleys.', 'Altitude is the height of a place above sea level.', 'Cameroon lies in Central Africa, on the Gulf of Guinea.'],
  situation: 'Your family travels from Garoua to Mokolo for a festival. Around Garoua the land is flat for many kilometres, with wide fields of cotton and millet; near Mokolo the bus climbs steep, winding roads between rocky mountains, and the air becomes cooler. Your little brother asks: "Why is the land so flat around Garoua and so mountainous near Mokolo, and what does the rest of Cameroon look like?"',
  sitQA: [['What is the problem in the situation?', 'The brother does not know why the relief changes between Garoua and Mokolo, nor what the relief of Cameroon is like.'],
    ['In which relief unit is Garoua?', 'In the Benue depression, part of the Northern lowlands.'],
    ['Which mountains are near Mokolo?', 'The Mandara Mountains.']],
  justification: 'This lesson helps us to understand the relief of Cameroon, which influences its climate, rivers, soils, population and economic activities.',
  action: 'Use a relief map of Cameroon to explain differences in farming, roads and settlement between regions.',
  activities: [
    { sec: '1. PHYSIOGRAPHIC REGIONS', img: 'cameroon_relief_big.png', caption: 'The relief of Cameroon.', q: 'Which relief unit lies in the centre of Cameroon, between the south and the north?', a: 'The Adamawa Plateau.', noProj: 'draw the outline of Cameroon and shade the highlands.' },
    { sec: '2. MAJOR HIGHLANDS', img: 'lsa_mtcameroon.jpg', caption: 'Mount Cameroon.', q: 'What is the highest mountain of Cameroon?', a: 'Mount Cameroon (4,095 m), an active volcano near Buea.', noProj: 'compare its height with the Adamawa Plateau.' },
    { sec: '2. MAJOR HIGHLANDS', img: 'cameroon_volcanic_line.png', caption: 'Volcanoes of Cameroon.', q: 'In which direction are the volcanic mountains of the West arranged?', a: 'In a line from the south-west to the north-east: the Cameroon Volcanic Line.', noProj: 'draw the line on the sketch map.' },
    { sec: '3. MAJOR LOWLANDS', img: 'cam_profile_big.png', caption: 'A relief section of Cameroon.', q: 'Why is Garoua much lower than Ngaoundéré?', a: 'Garoua is in the Benue depression (about 200 m), while Ngaoundéré is on the Adamawa Plateau (about 1,100 m).', noProj: 'draw the section on the board.' },
    { sec: '3. MAJOR LOWLANDS', img: 'lsa_mandara.jpg', caption: 'Mountains of the Far North.', q: 'Which mountains rise above the northern lowlands near Mokolo?', a: 'The Mandara Mountains.', noProj: 'describe the road to Mokolo.' },
  ],
  summary: [
    D([['Relief:', "It is the shape of the Earth's surface: its altitude and its slopes (mountains, plateaux, plains, valleys)."],
      ['Physiography:', 'It is the description of the landforms of an area and of the processes that formed them.'],
      ['Physiographic region:', 'It is a large area with the same general type of relief.'],
      ['Highland:', 'It is land that stands high above the surrounding area, such as a mountain range or a high plateau.'],
      ['Lowland:', 'It is low, generally flat land, such as a plain, a basin or a depression.']]),
    { title: '1. Physiography: The Physiographic Regions', intro: 'The relief of Cameroon is organised as follows:',
      items: [['A varied relief:', 'Cameroon has high volcanic mountains, old plateaux, deep basins and wide plains. This variety of relief is one of the reasons why the country is called "Africa in miniature".', 'cameroon_relief_big.png', 'the relief of Cameroon'],
        ['The physiographic regions:', 'The country has three major highlands, the Western Highlands, the Adamawa Plateau and the Southern Plateau. It also has two major lowlands, the Coastal lowlands and the Northern lowlands, the latter dominated by the Mandara Mountains.'],
        ['General arrangement:', 'From the coast, the land rises to the Southern Plateau and the central highlands of the West and the Adamawa. It then falls northwards to the Benue depression and the Chad plain.', 'cam_profile_big.png', 'a profile of Cameroon']] },
    { title: '2. The Major Highlands', sub: 'A) The Western Highlands', intro: 'The Western Highlands have the following characteristics:',
      items: [['Location and origin:', 'They cover the West and North-West Regions and parts of the South-West and Littoral. They lie on the Cameroon Volcanic Line, a chain of volcanoes running from the Gulf of Guinea to the north-east.', 'cameroon_volcanic_line.png', 'the Cameroon Volcanic Line'],
        ['Altitude and plateaux:', 'Most of the land is above 1,000 m, with high plateaux such as the Bamileke and Bamenda Plateaux. Their cool climate and rich volcanic soils support very dense populations.', 'usa_bamenda.jpg', 'the Bamenda Highlands'],
        ['Main peaks:', 'Mount Cameroon (4,095 m), an active volcano, is the highest peak of West and Central Africa. Other peaks include Mount Oku (3,011 m), the Bamboutos Mountains (2,740 m), Mount Manengouba (2,411 m) and Mount Kupe (2,064 m).'],
        ['Plains and valleys:', 'The highlands also contain lower areas such as the Ndop plain, the Mbaw-Tikar plain, the Mbo plain and the Menchum valley. These plains are used for rice and food crops.']] },
    { title: '2. The Major Highlands', sub: 'B) The Adamawa Plateau', intro: 'The Adamawa Plateau has the following characteristics:',
      items: [['Location and origin:', 'It crosses the centre of Cameroon from Nigeria to the Central African Republic. It is an old block of hard rocks raised by faulting and covered in places by volcanic rocks.', 'lsa_adamawa.jpg', 'the Adamawa Plateau'],
        ['Altitude and peaks:', 'It averages about 1,100 m, which gives Ngaoundéré a mild climate. Volcanic peaks rise above it, such as Tchabal Mbabo (2,460 m).'],
        ['The northern escarpment:', 'Its northern edge is a steep escarpment that drops towards the Benue depression. The road and the railway from Ngaoundéré to the North must climb this escarpment.'],
        ['The main watershed:', 'The Adamawa is the main watershed of Cameroon, the water tower of the country. The Benue, the Vina (Logone), the Djerem (Sanaga) and other rivers rise on it and flow in different directions.']] },
    { title: '2. The Major Highlands', sub: 'C) The Southern Plateau', intro: 'The Southern Plateau has the following characteristics:',
      items: [['Location and altitude:', 'It covers the Centre, South and East Regions, south of the Adamawa and east of the coastal lowlands. It is lower than the other highlands, averaging about 650 m.'],
        ['Relief:', 'It is dissected into many rounded, dome-shaped hills, called half-orange relief, with inselbergs such as the hills around Yaoundé. Its highest hills include Mbam Minkom (about 1,295 m) near Yaoundé.'],
        ['Drainage:', 'It is drained by the Nyong and the Ntem towards the Atlantic and by the tributaries of the Congo towards the south-east. Its rivers flow slowly across swampy valleys and then fall over rapids towards the coast.']] },
    { title: '3. The Major Lowlands', sub: 'A) The Coastal Lowlands', intro: 'The Coastal lowlands have the following characteristics:',
      items: [['Location and altitude:', 'They stretch along the Atlantic coast from the Nigerian border to Equatorial Guinea, generally below 300 m. They are interrupted by the mass of Mount Cameroon, which reaches the sea near Limbe.', 'lsa_wouri_sat.jpg', 'the Wouri estuary'],
        ['Sub-units:', 'They include the Mamfe and Ndian basins in the north-west and the Douala basin around the Wouri and Sanaga estuaries. In the south, the coast of Kribi and Campo is rocky, with the Lobé Falls dropping into the sea.'],
        ['Features:', 'They have wide estuaries, creeks, mangrove swamps and sandy beaches. The Douala basin contains the main port and industrial region of the country.']] },
    { title: '3. The Major Lowlands', sub: 'B) The Northern Lowlands', intro: 'The Northern lowlands have the following characteristics:',
      items: [['The Benue depression:', 'It is a long trough of sedimentary rocks drained by the Benue, about 200 m high at Garoua. It is dotted with isolated hills and inselbergs, such as those of Garoua and Pitoa.', 'f2t_benue.jpg', 'the Benue'],
        ['The Chad plain:', 'It is a very flat plain of about 300 m that slopes gently towards Lake Chad. The Logone floods its lowest parts, the yaérés, in the rainy season.'],
        ['The Mandara Mountains:', 'They rise above the plains along the Nigerian border, up to 1,494 m at Mount Oupay. They contain spectacular volcanic necks, such as those of Rhumsiki.', 'lsa_mandara.jpg', 'the Mandara Mountains']] },
  ],
  evaluation: [['Name the three major highland units of Cameroon.', 'The Western Highlands, the Adamawa Plateau and the Southern Plateau.'], ['Why is the Adamawa Plateau called the main watershed of Cameroon?', 'Many major rivers rise on it and flow in different directions, such as the Benue, the Vina and the Djerem.']],
  remediation: ['The highest peak of Cameroon is Mount ______ (4,095 m).', 'Garoua lies in the ______ depression.', 'The Western Highlands lie along the Cameroon ______ Line.'],
  remediationAnswers: '1. Cameroon 2. Benue 3. Volcanic',
  homework: 'Name the two air masses that affect the climate of Cameroon.',
  hwAnswer: 'The dry North-East Trade Wind (Harmattan) from the Sahara, and the moist South-West Monsoon from the Atlantic Ocean.',
  bilingual: [['Relief', 'Le relief'], ['Highland', 'La haute terre'], ['Lowland', 'La basse terre'], ['Plateau', 'Le plateau'], ['Mountain', 'La montagne'], ['Depression', 'La dépression'], ['Watershed', 'La ligne de partage des eaux'], ['Plain', 'La plaine']],
});

L.push({ no: 2, title: 'The Climate of Cameroon', subtopic: 'The Physical Environment of Cameroon', pointPerSlide: true,
  notions: 'Climate, climatic domain, air mass, Harmattan, monsoon, Intertropical Convergence Zone (ITCZ), continentality, seasons.',
  focus: 'Location of Cameroon in Africa; major climatic domains and their types (Equatorial: Guinea, Cameroon maritime and mountain types; Tropical continental: humid and dry tropical); temperature, sunshine and precipitation; role of air masses and the ITCZ; seasons and continentality.',
  competence: 'Learners are able to describe the climatic types of Cameroon and explain the role of air masses, the ITCZ and continentality.',
  objectives: ['Locate Cameroon and situate it in Africa.', 'Describe the role of air masses and the ITCZ.', 'Describe the types of climate of the Equatorial domain.', 'Describe the types of climate of the Tropical continental domain.', 'Explain the variation of seasons with continentality.'],
  recall: ['Climate is the average weather of a place over about 30 years.', 'Garoua has a wet season and a long dry season.', 'The Harmattan is a dry, dusty wind.'],
  situation: 'In January your cousin from Kribi visits Garoua. The air is full of Harmattan dust, the sun is burning and the Benue is almost dry. He asks: "Does it ever rain here?" You tell him to come back in August, when the land is green and the rain is heavy. He then asks: "Why is the climate of Garoua so different from the climate of Kribi?"',
  sitQA: [['What is the problem in the situation?', 'The cousin does not understand why the climates of Garoua and Kribi are so different.'],
    ['How is the weather of Garoua in January?', 'Hot, dry and dusty, with the Harmattan.'],
    ['When does Garoua have its rain?', 'In the wet season, mainly from May to September.']],
  justification: 'This lesson helps us to understand the climates of Cameroon, which control farming calendars, water supply and the way of life in each region.',
  action: 'Plan farming and daily activities according to the seasons of your region.',
  activities: [
    { sec: '1. LOCATION', img: 'cameroon_grid_big.png', caption: 'Cameroon with its latitudes.', q: 'Between which latitudes does Cameroon stretch?', a: 'From about 2° N to 13° N.', noProj: 'draw the latitudes on a sketch map.' },
    { sec: '2. AIR MASSES AND THE ITCZ', img: 'itcz.gif', caption: 'Animation: the rain belt moves during the year.', q: 'Which wind brings rain to Garoua in July?', a: 'The moist South-West Monsoon from the Atlantic.', noProj: 'draw the two winds meeting.' },
    { sec: '3. EQUATORIAL DOMAIN', img: 'douala_climate_big.png', caption: 'The climate of Douala.', q: 'Why does Douala receive so much rain?', a: 'It is on the coast, where moist monsoon air is forced to rise over the land and Mount Cameroon.', noProj: 'write Douala\'s rainfall on the board.' },
    { sec: '4. TROPICAL CONTINENTAL DOMAIN', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'How many months of rain does Garoua have?', a: 'About five months (May to September).', noProj: 'count the wet months on the graph.' },
    { sec: '5. SEASONS AND CONTINENTALITY', img: 'cam_rain_towns_big.png', caption: 'Rainfall of some towns of Cameroon.', q: 'How does the rainfall change from Douala to Kousseri?', a: 'It decreases steadily from the coast inland.', noProj: 'write the rainfall of the towns in a column.' },
  ],
  summary: [
    D([['Climate:', 'It is the average state of the weather of a place over a long period, usually 30 years.'],
      ['Climatic domain:', 'It is a large region with the same general climate, divided into types of climate.'],
      ['Air mass:', 'It is a very large body of air with nearly the same temperature and humidity.'],
      ['Intertropical Convergence Zone (ITCZ):', 'It is the zone where the dry north-east trade winds and the moist south-west monsoon meet; its surface line is the Intertropical Front (ITF).'],
      ['Continentality:', 'It is the effect of distance from the sea on climate: rainfall decreases and temperature range increases inland.']]),
    { title: '1. Location of Cameroon in Africa', intro: 'The location of Cameroon influences its climate as follows:',
      items: [['Latitude and longitude:', 'Cameroon stretches from about 2° N to 13° N, about 1,200 km from south to north, and from about 8° E to 16° E. It lies entirely in the tropics, so it is hot almost everywhere.', 'cameroon_grid_big.png', 'the location of Cameroon'],
        ['Position in Africa:', 'It is in Central Africa, at the bend of the Gulf of Guinea, with an area of about 475,000 km². Its south-west is open to the moist winds of the Atlantic Ocean.'],
        ['Consequence on climate:', 'Its great length from the equatorial south to the Sahel in the north gives it very varied climates. Rainfall falls and the dry season lengthens from south to north.']] },
    { title: '2. The Role of Air Masses and the ITCZ', intro: 'The climate of Cameroon is controlled by the following air masses and by the ITCZ:',
      items: [['The south-west monsoon:', 'It is a tropical maritime air mass from the Atlantic Ocean, warm and very moist. It brings the rainy season to the places it covers.', 'itcz_july.png', 'the ITCZ in July'],
        ['The Harmattan:', 'It is the north-east trade wind, a tropical continental air mass from the Sahara, hot by day, very dry and dusty. It brings the dry season.', 'f2t_harmattan.jpg', 'the Harmattan'],
        ['The movement of the ITCZ:', 'The ITCZ follows the overhead sun: in July and August it lies north of Cameroon, and in January it lies near the coast. Places south of it are in the monsoon and get rain, while places north of it are in the Harmattan and are dry.']] },
    { title: '3. The Equatorial Domain', sub: 'A) The Guinea (Equatorial) Type', intro: 'The Guinea type has the following location and characteristics:',
      items: [['Location and temperature:', 'It covers the Southern Plateau, for example Yaoundé, Ebolowa and Bertoua. It is hot all year (about 23 to 25 °C), with a small annual range of only 2 to 3 °C.', 'yaounde_climate_big.png', 'the climate of Yaoundé'],
        ['Rainfall and sunshine:', 'It receives about 1,500 to 2,000 mm of rain per year, about 1,600 mm at Yaoundé. The sky is often cloudy, so sunshine is moderate.'],
        ['Four seasons:', 'It has a long dry season (December to February), a short rainy season (March to June), a short dry season (July to August) and a long rainy season (September to November). These four seasons come from the double passage of the overhead sun.']] },
    { title: '3. The Equatorial Domain', sub: 'B) The Cameroon (Maritime) Type', intro: 'The Cameroon maritime type has the following location and characteristics:',
      items: [['Location:', 'It covers the coast and the seaward slopes of Mount Cameroon, for example Douala, Limbe, Kribi and Debundscha. These places face the moist monsoon winds coming from the sea.', 'douala_climate_big.png', 'the climate of Douala'],
        ['Very heavy rainfall:', 'Rainfall is between 2,500 and 10,000 mm per year: about 4,000 mm at Douala and about 10,000 mm at Debundscha, one of the wettest places in the world. It is caused by the monsoon rising over Mount Cameroon.'],
        ['Seasons, temperature and humidity:', 'It has a long rainy season from March to November and a short dry season from December to February. It is hot (about 26 to 27 °C) and very humid all year, with little sunshine.']] },
    { title: '3. The Equatorial Domain', sub: 'C) The Mountain Type', intro: 'The mountain type has the following location and characteristics:',
      items: [['Location and temperature:', 'It covers the Western Highlands, for example Bamenda, Dschang and Buea. Because temperature falls by about 0.6 °C every 100 m, these highlands are cool, about 18 to 21 °C.', 'usa_bamenda.jpg', 'the Western Highlands'],
        ['Rainfall:', 'Rainfall is high on the windward slopes, often above 2,000 mm, because the monsoon is forced to rise. It is lower on the sheltered leeward slopes.'],
        ['Mist and cold nights:', 'Mist, fog and drizzle are common in the rainy season. Nights are cold, especially in the dry season.']] },
    { title: '4. The Tropical Continental Domain', sub: 'A) The Humid Tropical (Sudan) Type', intro: 'The humid tropical type has the following location and characteristics:',
      items: [['Location:', 'It covers the Adamawa Plateau and the north of the Centre and East Regions, for example Ngaoundéré. It is a zone of transition between the equatorial south and the dry north.', 'ngaoundere_climate_big.png', 'the climate of Ngaoundéré'],
        ['Two seasons and rainfall:', 'It has a rainy season of about 7 months (April to October) and a dry season of about 5 months. It receives about 1,500 mm of rain per year.'],
        ['Temperature:', 'Altitude keeps the temperature mild, about 22 °C on average. Harmattan nights in December and January are cool.']] },
    { title: '4. The Tropical Continental Domain', sub: 'B) The Dry Tropical (Sudano-Sahelian) Type', intro: 'The dry tropical type has the following location and characteristics:',
      items: [['Location:', 'It covers the North and Far North Regions, for example Garoua, Maroua and Kousseri. It is the part of Cameroon furthest from the sea.', 'garoua_climate_big.png', 'the climate of Garoua'],
        ['Rainfall and seasons:', 'Rainfall falls northwards from about 1,000 mm at Garoua to about 800 mm at Maroua and about 550 mm at Kousseri. The rainy season lasts about 5 months at Garoua but only 3 to 4 months further north.', 'maroua_climate_big.png', 'the climate of Maroua'],
        ['High temperatures:', 'It is very hot, with maxima above 40 °C in March and April before the rains. The annual range of temperature is larger than in the south.'],
        ['Long dry season:', 'The dry season lasts 7 to 9 months, dominated by the Harmattan. The air is dry and dusty, with low humidity and a lot of sunshine.']] },
    { title: '5. The Seasons and Continentality', intro: 'From the coast inland, the climate changes in the following ways:',
      items: [['Rainfall decreases inland:', 'Annual rainfall falls from about 10,000 mm at Debundscha to about 550 mm at Kousseri. The monsoon loses its moisture as it moves further from the sea.', 'cam_rain_towns_big.png', 'rainfall of some towns'],
        ['Shorter rainy season:', 'The monsoon reaches the north later and leaves it earlier. The rainy season therefore becomes shorter northwards, and the dry season longer.'],
        ['Fewer seasons:', 'The south has four seasons, two rainy and two dry. The centre and north have only two seasons, one rainy and one dry.'],
        ['Larger temperature range:', 'Far from the moderating influence of the sea, the difference between the hottest and coolest months becomes larger. Daily ranges are also larger in the north, especially in the Harmattan season.']] },
  ],
  evaluation: [['Name the three types of climate of the Equatorial domain in Cameroon.', 'The Guinea type, the Cameroon maritime type and the mountain type.'], ['Why is the rainy season shorter at Maroua than at Ngaoundéré?', 'Maroua is farther from the sea: the monsoon reaches it later and leaves it earlier (continentality).']],
  remediation: ['The dry, dusty wind from the Sahara is the ______.', 'The wettest place in Cameroon is ______.', 'The zone where the monsoon and the Harmattan meet is the ______.'],
  remediationAnswers: '1. Harmattan 2. Debundscha 3. ITCZ (Intertropical Convergence Zone)',
  homework: 'Name the three groups of soils studied in Cameroon.',
  hwAnswer: 'Zonal soils, azonal soils and intrazonal soils.',
  bilingual: [['Climate', 'Le climat'], ['Season', 'La saison'], ['Air mass', "La masse d'air"], ['Monsoon', 'La mousson'], ['Rainfall', 'Les précipitations'], ['Humidity', "L'humidité"], ['Continentality', 'La continentalité'], ['Intertropical Front', 'Le front intertropical']],
});

L.push({ no: 3, title: 'Soils of Cameroon', subtopic: 'The Physical Environment of Cameroon', pointPerSlide: true,
  notions: 'Soil, zonal soils, azonal soils, intrazonal soils, ferrallitic soils, ferruginous soils, vertisols, leaching, laterite.',
  focus: 'Zonal soils (ferrallitic, ferruginous, tropical black earths); azonal soils (alluvial, volcanic, mountain); intrazonal soils (hydromorphic); characteristics and location of each type.',
  competence: 'Learners are able to identify the soil types of Cameroon, give their characteristics and locate them.',
  objectives: ['Define zonal, azonal and intrazonal soils.', 'Describe the characteristics and location of the zonal soils of Cameroon.', 'Describe the characteristics and location of the azonal soils.', 'Describe the characteristics and location of the hydromorphic soils.'],
  recall: ['Soil forms from the weathering of rocks and the decay of plants.', 'Heavy rain washes plant food deep into the soil.', 'The South is wetter than the North.'],
  situation: 'Yves, from a village near Sangmélima, helps his friend Alim on a farm in the Far North. He picks up the dark soil and says: "At home our soil is red and hard, and after a few years of cassava it is finished." Alim answers that here the soil cracks in the dry season but gives good sorghum. Yves asks: "Why are the soils of Cameroon so different from one region to another?"',
  sitQA: [['What is the problem in the situation?', 'Yves does not know why the soils of Cameroon differ from region to region.'],
    ['Describe the soil of Sangmélima.', 'It is red, hard and loses its fertility quickly.'],
    ['What does the soil of the Far North do in the dry season?', 'It cracks.']],
  justification: 'This lesson helps us to know the soils of Cameroon, their fertility and the crops that suit them.',
  action: 'Choose crops and farming methods that suit the soil of your area and protect it from erosion.',
  activities: [
    { sec: '1. ZONAL SOILS', img: 'cameroon_soils_big.png', caption: 'The soils of Cameroon.', q: 'Which soil covers most of the southern half of Cameroon?', a: 'Ferrallitic soils.', noProj: 'shade the soils on a sketch map.' },
    { sec: '1. ZONAL SOILS', img: 'f4_redsoil.jpg', caption: 'A red soil of the forest zone.', q: 'Why are these soils red and poor?', a: 'They contain iron oxides, and heavy rain washes the plant food away (leaching).', noProj: 'show red soil.' },
    { sec: '1. ZONAL SOILS', img: 'f2t_cracked_soil.jpg', caption: 'A dark clay soil in the dry season.', q: 'Why does this dark soil crack in the dry season?', a: 'It is rich in clay that swells when wet and shrinks when dry.', noProj: 'wet and dry some clay.' },
    { sec: '2. AZONAL SOILS', img: 'lsa_mtcameroon.jpg', caption: 'Farms on Mount Cameroon.', q: 'Why are the soils around Mount Cameroon so fertile?', a: 'They come from young volcanic rocks rich in minerals.', noProj: 'name crops of the South-West.' },
    { sec: '3. INTRAZONAL SOILS', img: 'f4_ricefield.jpg', caption: 'A flooded rice field.', q: 'Which crop suits waterlogged soils?', a: 'Rice.', noProj: 'name the SEMRY rice scheme.' },
  ],
  summary: [
    D([['Soil:', "It is the loose top layer of the Earth's surface, made of mineral particles, humus, air and water, in which plants grow."],
      ['Zonal soils:', 'They are mature soils whose characteristics mainly reflect the climate and vegetation of a large zone.'],
      ['Azonal soils:', 'They are young soils whose characteristics mainly reflect their parent material (volcanic rock, river deposits) or steep slopes.'],
      ['Intrazonal soils:', 'They are soils formed by a strong local condition, such as waterlogging, which overrides the effect of climate.'],
      ['Leaching:', 'It is the washing of soluble plant nutrients down through the soil by rainwater.']]),
    { title: '1. Zonal Soils', sub: 'A) Ferrallitic Soils', intro: 'Ferrallitic soils have the following location and characteristics:',
      items: [['Location:', 'They cover the Southern Plateau (Centre, South and East), the forest parts of the Littoral and South-West and much of the Adamawa Plateau. They are the most widespread soils of Cameroon.', 'cameroon_soils_big.png', 'the soils of Cameroon'],
        ['Characteristics:', 'They are deep, red or yellow soils, coloured by oxides of iron and aluminium. Heavy rain all year leaches their nutrients, so they are acid and become poor once the forest is cleared.', 'f4_redsoil.jpg', 'a red ferrallitic soil'],
        ['Use:', 'They suit tree crops such as cocoa, coffee, oil palm and rubber, whose roots go deep. Food crops are grown by shifting cultivation, which lets the soil rest.']] },
    { title: '1. Zonal Soils', sub: 'B) Ferruginous Soils', intro: 'Tropical ferruginous soils have the following location and characteristics:',
      items: [['Location:', 'They cover the savanna of the North Region, in the Benue plain around Garoua, and the northern edge of the Adamawa. They are the typical soils of the Sudan savanna.'],
        ['Characteristics:', 'They are reddish-brown, rich in iron and less leached than ferrallitic soils because the rainy season is shorter. Where the vegetation is removed, iron can harden into a lateritic crust that is hard to plough.', 'f2t_laterite.jpg', 'a lateritic crust'],
        ['Use:', 'They support cotton, maize, groundnuts, sorghum and grazing. Because they are not very rich, they need manure or fertilisers to give good yields.']] },
    { title: '1. Zonal Soils', sub: 'C) Tropical Black Earths (Vertisols)', intro: 'Tropical black earths have the following location and characteristics:',
      items: [['Location:', 'They are found in the plains of the Far North, around Maroua, Kaélé and the Mayo-Danay, and in patches of the Benue plain. They form in flat areas with a long dry season.', 'f2t_black_soil.jpg', 'a black soil'],
        ['Characteristics:', 'They are dark grey to black clay soils, rich in calcium and magnesium. They swell and become sticky when wet, and shrink and crack deeply when dry.', 'f2t_cracked_soil.jpg', 'a cracked black soil'],
        ['Use:', 'They are fertile and hold water for a long time after the rains. They support cotton and dry-season sorghum (muskwari), grown on the land called karal.']] },
    { title: '2. Azonal Soils', sub: 'A) Volcanic Soils', intro: 'Volcanic soils have the following location and characteristics:',
      items: [['Location and characteristics:', 'They are young, dark soils formed from lava and ash, very rich in minerals. They are found on Mount Cameroon, the Bamboutos, the Bamenda Highlands and parts of the Adamawa.', 'lsa_mtcameroon.jpg', 'Mount Cameroon'],
        ['Use:', 'They allow intensive farming of bananas, tea, coffee and food crops all year. Their fertility explains the dense population of the Western Highlands and the plantations of the CDC.']] },
    { title: '2. Azonal Soils', sub: 'B) Alluvial and Mountain Soils', intro: 'Alluvial and mountain soils have the following location and characteristics:',
      items: [['Alluvial soils:', 'They are layers of silt, sand and clay deposited by rivers along the Benue, the Logone, the Sanaga, the Mungo and the Wouri. Renewed by each flood, they are very fertile and good for rice, market gardening and dry-season crops.'],
        ['Mountain soils:', 'They are thin, stony, young soils on steep slopes, such as those of the Mandara Mountains and the high slopes of the Western Highlands. They are easily eroded, so farmers build terraces to keep them, as in the Mandara Mountains.', 'f4_terraces.jpg', 'terraces']] },
    { title: '3. Intrazonal Soils: Hydromorphic Soils', intro: 'Hydromorphic soils have the following location and characteristics:',
      items: [['Location:', 'They are found in poorly drained areas: the floodplains (yaérés) of the Logone, the Ndop plain and the coastal swamps and mangroves. Water covers them for several months of the year.'],
        ['Characteristics:', 'They are grey or bluish clay soils, waterlogged for long periods and poor in oxygen. Their colour comes from iron that has lost its oxygen.'],
        ['Use:', 'They are unsuitable for most crops but very good for rice. They are used by the SEMRY scheme at Yagoua and Maga and by the UNVDA scheme at Ndop.', 'f4_ricefield.jpg', 'a rice field']] },
  ],
  evaluation: [['Give one characteristic and one location of ferrallitic soils.', 'They are red, deep and leached; they cover the Southern Plateau.'], ['Why are volcanic soils fertile?', 'They are young soils formed from lava and ash rich in minerals and not yet leached.']],
  remediation: ['Soils whose character depends mainly on climate are ______ soils.', 'Black clay soils that crack in the dry season are ______.', 'Waterlogged soils are called ______ soils.'],
  remediationAnswers: '1. zonal 2. vertisols (tropical black earths) 3. hydromorphic',
  homework: 'Name the three types of savanna found in Cameroon.',
  hwAnswer: 'The Guinea savanna, the Sudan savanna and the Sahel savanna.',
  bilingual: [['Soil', 'Le sol'], ['Fertile', 'Fertile'], ['Clay', "L'argile"], ['Leaching', 'Le lessivage'], ['Volcanic', 'Volcanique'], ['Alluvium', "L'alluvion"], ['Waterlogged', 'Engorgé d\'eau'], ['Crust', 'La cuirasse']],
});

L.push({ no: 4, title: 'Vegetation of Cameroon', subtopic: 'The Physical Environment of Cameroon', pointPerSlide: true,
  notions: 'Vegetation, forest, savanna, mangrove, montane forest, forest reserve, domesticated landscape, desertification.',
  focus: 'Forest vegetation types (mangrove, rainforest, montane and submontane) and forest reserves; grassland types (Guinea, Sudan, Sahel); domesticated landscapes; distribution, species, exploitation, threats and measures of each type.',
  competence: 'Learners are able to describe the vegetation types of Cameroon, their exploitation and the measures needed to protect them.',
  objectives: ['Define vegetation, forest, savanna and domesticated landscape.', 'Describe the forest vegetation types of Cameroon.', 'Describe the grassland vegetation types of Cameroon.', 'Explain the threats to vegetation and the measures of protection.'],
  recall: ['Vegetation depends mainly on climate and soils.', 'The South is wet all year; the North has a long dry season.', 'Many trees around Garoua are cut for firewood and charcoal.'],
  situation: 'One evening in Garoua you watch a documentary on the Dja Reserve: giant trees form a roof so dense that the ground is dark. Outside your window you see golden grass with scattered acacias and baobabs. Your sister asks: "Why does Cameroon have such different vegetation, and how can we protect it?"',
  sitQA: [['What is the problem in the situation?', 'The sister does not know why vegetation differs across Cameroon and how to protect it.'],
    ['Describe the vegetation of the Dja Reserve.', 'A very dense forest of giant trees.'],
    ['Describe the vegetation around Garoua.', 'Grass with scattered trees such as acacias and baobabs (savanna).']],
  justification: 'This lesson helps us to know the vegetation of Cameroon, its resources and the need to protect it.',
  action: 'Protect trees around your home and avoid bush fires.',
  activities: [
    { sec: '1. FOREST VEGETATION', img: 'cameroon_veg_big.png', caption: 'The vegetation of Cameroon.', q: 'Which vegetation covers the south of Cameroon?', a: 'Dense rainforest.', noProj: 'shade the vegetation zones on a sketch map.' },
    { sec: '1. FOREST VEGETATION', img: 'lsa_mangrove.jpg', caption: 'Trees with stilt roots.', q: 'Where does this forest with stilt roots grow in Cameroon?', a: 'In the estuaries of the coast, such as the Wouri and the Rio del Rey (mangroves).', noProj: 'show the coast on a map.' },
    { sec: '2. GRASSLAND VEGETATION', img: 'f2t_savanna.jpg', caption: 'Grass with scattered trees.', q: 'Which type of savanna surrounds Garoua?', a: 'The Sudan savanna.', noProj: 'describe the vegetation around the school.' },
    { sec: '2. GRASSLAND VEGETATION', img: 'f2t_tree_planting_sahel.jpg', caption: 'Tree planting in a dry area.', q: 'Which threat does tree planting fight in the Far North?', a: 'Desertification.', noProj: 'name tree-planting projects.' },
    { sec: '3. DOMESTICATED LANDSCAPES', img: 'lsa_oilpalm.jpg', caption: 'Oil palms in rows.', q: 'Is this natural vegetation? Why?', a: 'No: the trees were planted by people (a plantation).', noProj: 'name plantations of Cameroon.' },
  ],
  summary: [
    D([['Vegetation:', 'It is the plant cover of an area.'],
      ['Forest:', 'It is a vegetation dominated by trees whose crowns touch.'],
      ['Savanna:', 'It is a tropical grassland with scattered trees and shrubs.'],
      ['Forest reserve:', 'It is a forest protected by the state, where cutting trees is controlled or forbidden.'],
      ['Domesticated landscape:', 'It is an area where natural vegetation has been replaced by vegetation planted by people.']]),
    { title: '1. Forest Vegetation Types', sub: 'A) Mangrove Forests', intro: 'Mangrove forests are presented as follows:',
      items: [['Distribution:', 'Mangroves grow in the estuaries and creeks of the coast, where fresh water meets salt water. The main areas are Rio del Rey, the Cameroon (Wouri) estuary and the mouth of the Ntem.', 'lsa_mangrove.jpg', 'mangroves'],
        ['Characteristics and species:', 'Salt-tolerant trees grow in muddy, salty water that rises and falls with the tides. Rhizophora has stilt roots that hold it in the mud, and Avicennia has breathing roots that rise above it.'],
        ['Exploitation:', 'People cut mangroves for fuelwood, especially to smoke fish, and for building poles. They are also breeding grounds for fish, shrimps and crabs, which support fishing.'],
        ['Threats and measures:', 'They are destroyed by cutting for fuelwood, the growth of Douala, pollution and oil activities. They are protected in the Douala-Edéa National Park, by replanting and by improved fish-smoking ovens that use less wood.']] },
    { title: '1. Forest Vegetation Types', sub: 'B) The Equatorial Rainforest', intro: 'The equatorial rainforest is presented as follows:',
      items: [['Distribution:', 'It covers the South, East, Centre, Littoral and South-West Regions, about 20 million hectares. It grows where rain falls almost all year.', 'cameroon_veg_big.png', 'the vegetation of Cameroon'],
        ['Characteristics and species:', 'It is a dense, evergreen, broad-leaved forest in several layers, with emergent trees up to 50 or 60 m, lianas and little undergrowth. Valuable hardwoods include sapele, iroko, ayous, moabi, azobé, ebony and mahogany.', 'rainforest_layers_big.png', 'the layers of the rainforest'],
        ['Exploitation:', 'Timber is logged, especially in the East, and exported through Douala and Kribi. People also collect fuelwood and non-timber products such as eru, bush mango and medicinal plants.'],
        ['Threats and measures:', 'Logging, shifting cultivation, plantations, mining and poaching reduce the forest. It is protected by the forestry law, community forests and protected areas such as the Dja Reserve, a UNESCO World Heritage Site, Lobéké, Campo-Ma\'an and Korup.']] },
    { title: '1. Forest Vegetation Types', sub: 'C) Montane and Submontane Forests', intro: 'Montane and submontane forests are presented as follows:',
      items: [['Distribution:', 'They grow on the high mountains of the West: Mount Cameroon, Mount Oku (the Kilum-Ijim forest), the Bamboutos and Mount Manengouba. They are found above about 800 m.', 'usa_bamenda.jpg', 'the Western Highlands'],
        ['Characteristics and species:', 'Submontane forest grows on the lower slopes, then montane forest with smaller trees, tree ferns and mosses, and grassland near the summits. It contains Prunus africana (pygeum), Podocarpus and many rare birds and plants.'],
        ['Exploitation:', 'The bark of Prunus africana is harvested to make medicine for export. The forests also supply fuelwood and land for farming and grazing.'],
        ['Threats and measures:', 'Farming, grazing and bush fires destroy these forests. They are protected by the Mount Cameroon National Park and by community forests such as Kilum-Ijim, managed by the villagers.']] },
    { title: '1. Forest Vegetation Types', sub: 'D) Forest Reserves', intro: 'Forest reserves are presented as follows:',
      items: [['Types:', 'Protected forests include national parks, wildlife reserves, forest reserves and community forests. Each type has its own rules on cutting, hunting and farming.', 'cmr_protected_areas.png', 'the protected areas of Cameroon'],
        ['Examples:', 'Examples are the Dja Faunal Reserve, the Lobéké, Campo-Ma\'an and Korup National Parks and the Mbalmayo Forest Reserve. Together they cover a large part of the southern forest.'],
        ['Purpose:', 'They protect biodiversity, water sources and soils from destruction. They also support scientific research and tourism, which brings income.']] },
    { title: '2. Grassland Vegetation Types', sub: 'A) The Guinea Savanna', intro: 'The Guinea savanna is presented as follows:',
      items: [['Distribution:', 'It covers the Adamawa Plateau and the north of the Centre and East Regions. It grows where the dry season lasts about 4 to 5 months.', 'lsa_adamawa.jpg', 'the Adamawa'],
        ['Characteristics and species:', 'Tall grasses up to 3 m grow with many trees such as Daniellia oliveri and Lophira lanceolata. Gallery forests line the rivers.'],
        ['Exploitation:', 'It is the main cattle-grazing area of Cameroon, around Ngaoundéré. People also grow maize, yams and cassava and collect fuelwood.'],
        ['Threats and measures:', 'Bush fires and overgrazing degrade it and cause erosion. Controlled early burning, ranching and parks such as Mbam et Djerem protect it.']] },
    { title: '2. Grassland Vegetation Types', sub: 'B) The Sudan Savanna', intro: 'The Sudan savanna is presented as follows:',
      items: [['Distribution:', 'It covers the Benue plain and the North Region, around Garoua. It grows where the dry season lasts about 6 to 7 months.', 'f2t_savanna.jpg', 'the Sudan savanna'],
        ['Characteristics and species:', 'Shorter grasses, 1 to 2 m high, grow with scattered drought-resistant trees. The main trees are shea (karité), locust bean (néré), baobab, tamarind and acacias.'],
        ['Exploitation:', 'The land is used for cotton, food crops and grazing, and women produce shea butter. It also supplies fuelwood and charcoal for towns such as Garoua.'],
        ['Threats and measures:', 'Tree cutting, bush fires and overgrazing degrade it. The Bénoué, Bouba Ndjida and Faro National Parks and reforestation protect it.']] },
    { title: '2. Grassland Vegetation Types', sub: 'C) The Sahel Savanna', intro: 'The Sahel savanna is presented as follows:',
      items: [['Distribution:', 'It covers the Far North, north of about 11° N, towards Lake Chad. It grows where the dry season lasts 8 months or more.'],
        ['Characteristics and species:', 'Short, sparse grasses grow with thorny shrubs adapted to drought. The main species are acacias, including the gum arabic tree, doum palms and Balanites.'],
        ['Exploitation:', 'It is used mainly for pastoralism by herders of cattle, sheep and goats. People also collect gum arabic and fuelwood.'],
        ['Threats and measures:', 'Drought, overgrazing and tree cutting cause desertification. Operation Sahel Vert, the Great Green Wall and the Waza National Park protect it.', 'f2t_tree_planting_sahel.jpg', 'tree planting in the Sahel']] },
    { title: '3. Domesticated Landscapes', intro: 'Domesticated landscapes are presented as follows:',
      items: [['Examples:', 'Natural vegetation has been replaced by plantations of oil palm, rubber and bananas (CDC, SOCAPALM), tea estates (Tole, Ndu) and cocoa agroforests. In the Western Highlands, eucalyptus trees are planted for poles and fuelwood.', 'lsa_oilpalm.jpg', 'an oil palm plantation'],
        ['Importance:', 'These landscapes provide food, raw materials for industry and export crops. They also give jobs and income to many people.'],
        ['Problems:', 'They reduce the area of natural forest and the diversity of plants and animals. Eucalyptus also uses a lot of water and dries out the soil.']] },
  ],
  evaluation: [['Name the three types of savanna in Cameroon from south to north.', 'The Guinea, the Sudan and the Sahel savanna.'], ['Give two threats to the rainforest.', 'Logging and shifting cultivation (also mining and plantations).']],
  remediation: ['Salt-tolerant forests of estuaries are ______ forests.', 'The Dja Reserve is a UNESCO World ______ Site.', 'The spread of desert conditions in the Far North is called ______.'],
  remediationAnswers: '1. mangrove 2. Heritage 3. desertification',
  homework: 'Name the four drainage basins of Cameroon.',
  hwAnswer: 'The Atlantic basin, the Congo basin, the Niger basin and the Chad basin.',
  bilingual: [['Vegetation', 'La végétation'], ['Forest', 'La forêt'], ['Savanna', 'La savane'], ['Mangrove', 'La mangrove'], ['Bush fire', 'Le feu de brousse'], ['Reserve', 'La réserve'], ['Plantation', 'La plantation'], ['Desertification', 'La désertification']],
});

L.push({ no: 5, title: 'The Drainage of Cameroon', subtopic: 'The Physical Environment of Cameroon', pointPerSlide: true,
  notions: 'Drainage, drainage basin, watershed, river system, tributary, river regime, hydroelectric power.',
  focus: 'Drainage potentials of Cameroon; main watersheds, drainage basins and their river systems; distribution and general characteristics of the drainage networks.',
  competence: 'Learners are able to locate the drainage basins and main rivers of Cameroon and explain their potentials.',
  objectives: ['Define drainage basin, watershed and river regime.', 'Explain the drainage potentials of Cameroon.', 'Locate the main watersheds, drainage basins and river systems on a map.', 'Describe the general characteristics of the drainage networks.'],
  recall: ['The Adamawa Plateau is the main watershed of Cameroon.', 'The Benue flows through Garoua.', 'The north has a long dry season.'],
  situation: 'In August you stand with Ali on the bridge over the Benue at Garoua: the river is high, brown and fast. In March, at the same place, the river is small and full of sandbanks. Ali asks: "Where does all this water come from, where does it go, and why does it change so much between the seasons?"',
  sitQA: [['What is the problem in the situation?', 'Ali does not know where the Benue comes from, where it goes and why its flow changes.'],
    ['When is the Benue high?', 'In August, in the rainy season.'],
    ['Where does the Benue go?', 'West into Nigeria, where it joins the Niger.']],
  justification: 'This lesson helps us to know the rivers of Cameroon and their use for energy, farming, transport and water supply.',
  action: 'Protect river banks and water sources, and use water carefully in the dry season.',
  activities: [
    { sec: '2. WATERSHEDS AND BASINS', img: 'cameroon_drainage_big.png', caption: 'The drainage basins of Cameroon.', q: 'Into which major basin does the Benue flow?', a: 'The Niger basin.', noProj: 'draw the rivers on a sketch map.' },
    { sec: '2. WATERSHEDS AND BASINS', img: 'lsa_wouri.jpg', caption: 'A river near Douala.', q: 'Into which ocean do the Sanaga and the Wouri flow?', a: 'The Atlantic Ocean.', noProj: 'show the Atlantic basin.' },
    { sec: '2. WATERSHEDS AND BASINS', img: 'f2t_lake_chad.jpg', caption: 'Lake Chad.', q: 'Why is the Chad basin called an inland basin?', a: 'Its rivers (Logone, Chari) flow into Lake Chad and never reach the sea.', noProj: 'show Lake Chad on a map.' },
    { sec: '1. DRAINAGE POTENTIALS', img: 'lsa_nachtigal.jpg', caption: 'A dam on the Sanaga.', q: 'Why are the rivers of the south good for producing electricity?', a: 'They have steep slopes with rapids and falls and a large volume of water.', noProj: 'name the dams of Cameroon.' },
    { sec: '3. GENERAL CHARACTERISTICS', img: 'f2t_benue.jpg', caption: 'The Benue at Garoua.', q: 'Why is the Benue low in March?', a: 'It is the dry season: there is no rain in its basin.', noProj: 'compare the river in March and August.' },
  ],
  summary: [
    D([['Drainage:', 'It is the system of rivers, lakes and other water bodies of an area.'],
      ['Drainage basin:', 'It is the area drained by a river and its tributaries (its catchment area).'],
      ['Watershed:', 'It is a line of high ground that separates one drainage basin from another.'],
      ['River regime:', 'It is the pattern of changes in the flow of a river during the year.']]),
    { title: '1. The Drainage Potentials of Cameroon', intro: 'The rivers and lakes of Cameroon offer the following potentials:',
      items: [['Hydroelectric power:', 'Steep rivers with rapids and falls give Cameroon one of the largest hydroelectric potentials in Africa. The main dams are Edéa, Song Loulou and Nachtigal (420 MW) on the Sanaga, Lom Pangar, Memve\'ele on the Ntem and Lagdo on the Benue.', 'lsa_nachtigal.jpg', 'the Nachtigal dam'],
        ['Irrigation:', 'Rivers water rice and other crops during the dry season. The SEMRY scheme uses the Logone, and farmers irrigate around the Lagdo reservoir on the Benue.'],
        ['Navigation:', 'The Wouri estuary serves the port of Douala, the main port of the country. The Benue is navigable up to Garoua only for a short period in the rainy season.'],
        ['Fishing and water supply:', 'Rivers and lakes such as Lagdo, Maga and Lake Chad supply fish, an important source of food and income. They also supply water to towns and industries.']] },
    { title: '2. Main Watersheds and Drainage Basins', sub: 'A) The Watersheds', intro: 'The main watersheds of Cameroon are the following:',
      items: [['The Adamawa Plateau:', 'It is the main watershed of Cameroon. Its rivers flow north to the Benue and the Logone and south to the Sanaga.', 'cameroon_drainage_big.png', 'the drainage of Cameroon'],
        ['The Western Highlands:', 'Rivers flow west and south from them to the Atlantic, such as the Cross River, the Mungo and the Wouri. Others flow east to the Mbam, a tributary of the Sanaga.'],
        ['The Southern Plateau:', 'It separates the rivers of the Atlantic basin, such as the Nyong and the Ntem, from those of the Congo basin, such as the Dja and the Boumba. This watershed is low and hardly visible in the landscape.']] },
    { title: '2. Main Watersheds and Drainage Basins', sub: 'B) The Atlantic Basin', intro: 'The Atlantic basin, the largest basin of Cameroon, has the following river systems:',
      items: [['The Sanaga system:', 'The Sanaga, about 920 km long, is the longest river entirely in Cameroon. It forms from the Djerem and the Lom, receives the Mbam and carries most of the hydroelectric dams of the country.'],
        ['The southern rivers:', 'The Nyong, the Ntem and the Lokoundjé drain the Southern Plateau towards the Atlantic. They cross swampy valleys and fall over rapids near the coast.'],
        ['The western rivers:', 'The Wouri (formed by the Nkam and the Makombé), the Mungo, the Meme and the Cross River (Manyu) drain the Western Highlands. They are short and fast.', 'lsa_wouri.jpg', 'the Wouri'],
        ['Characteristics:', 'The rivers of this basin are short and powerful, with many rapids and falls, such as the Lobé Falls at Kribi. They flow all year because of the heavy rainfall.']] },
    { title: '2. Main Watersheds and Drainage Basins', sub: 'C) The Congo Basin', intro: 'The Congo basin, in the south-east, has the following characteristics:',
      items: [['Main rivers:', 'The Sangha, the Dja, the Ngoko, the Boumba and the Kadéi flow south-east towards the Congo River. The Dja Faunal Reserve lies in this basin.'],
        ['Characteristics:', 'In the equatorial zone, these rivers have a fairly regular flow all year. They flow slowly through the dense forest and are used for transporting timber.']] },
    { title: '2. Main Watersheds and Drainage Basins', sub: 'D) The Niger Basin', intro: 'The Niger basin, in the North Region, has the following characteristics:',
      items: [['The Benue:', 'It rises on the Adamawa Plateau east of Ngaoundéré, flows past Garoua and enters Nigeria, where it joins the Niger. Its main tributaries are the Faro, the Mayo Rey and the Mayo Kébi.', 'f2t_benue.jpg', 'the Benue'],
        ['The Lagdo reservoir:', 'The Lagdo dam on the Benue produces electricity for the northern regions. Its reservoir also supplies water for irrigation and fish.', 'f2t_lagdo.jpg', 'Lake Lagdo'],
        ['Regime:', 'The Benue is strongly seasonal, with high water from August to October and very low water from February to April. In the dry season, large sandbanks appear in its bed at Garoua.']] },
    { title: '2. Main Watersheds and Drainage Basins', sub: 'E) The Chad Basin', intro: 'The Chad basin, in the Far North, has the following characteristics:',
      items: [['An inland basin:', 'Its rivers flow into Lake Chad and never reach the sea. The Logone, formed by the Vina and the Mbéré from the Adamawa, forms part of the border with Chad before joining the Chari.', 'f2t_lake_chad.jpg', 'Lake Chad'],
        ['Seasonal rivers:', 'Many rivers, called mayos, such as the Mayo Tsanaga, flow only in the rainy season. For the rest of the year, their beds are dry and sandy.'],
        ['Lake Chad:', 'Lake Chad is very shallow and changes size with the seasons and the years. It has shrunk greatly since the 1960s because of droughts and the use of water for irrigation.']] },
    { title: '3. Distribution and General Characteristics', intro: 'The drainage network of Cameroon has the following characteristics:',
      items: [['Radial pattern:', 'Rivers flow outwards in all directions from the central highlands of the Adamawa and the West. This is why these highlands are the water tower of the country.'],
        ['Dense network in the south:', 'The wet south has a dense network of permanent rivers. The dry north has fewer rivers, and many of them are seasonal.'],
        ['Regimes:', 'Southern rivers have two periods of high water, following the two rainy seasons. Northern rivers have only one flood, in the single rainy season.'],
        ['Rapids and falls:', 'Many rivers fall over rapids and waterfalls as they leave the plateaux. These limit navigation but favour the production of hydroelectricity.']] },
  ],
  evaluation: [['Name the four drainage basins of Cameroon.', 'The Atlantic, Congo, Niger and Chad basins.'], ['Why is the Chad basin an inland basin?', 'Its rivers flow into Lake Chad and do not reach the sea.']],
  remediation: ['The longest river entirely in Cameroon is the ______.', 'The Benue is part of the ______ basin.', 'A line of high ground separating two basins is a ______.'],
  remediationAnswers: '1. Sanaga 2. Niger 3. watershed',
  homework: 'Give the total population of Cameroon at the 2005 census.',
  hwAnswer: 'About 17.5 million inhabitants (17,463,836).',
  bilingual: [['Drainage basin', 'Le bassin versant'], ['Watershed', 'La ligne de partage des eaux'], ['River', 'Le fleuve / la rivière'], ['Tributary', "L'affluent"], ['Dam', 'Le barrage'], ['Hydroelectric power', "L'hydroélectricité"], ['Flood', 'La crue'], ['Low water', "L'étiage"]],
});

module.exports = { B, L };
