// LOWER SIXTH ARTS — Climatology: Lesson 19, Further Study 1, Lessons 20–21 (Climates)
// Rewritten from the teacher's course supports (LSA_LESSONS_METEOROLOGY_2026, USA_LESSONS_METEO) in our own words; facts checked.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const OLD = require('../v2_lsa_clim').B;
const B = Object.assign({}, OLD, {
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Module 1 (Meteorology, Climatology & Hydrology).', 'Teacher\'s course notes: Mr KAMDEM E., Meteorology and Climatology (LSA), GBHS Garoua, 2026.'] });
const L = [];
const T = 'Climates';

L.push({ no: 19, title: "Meaning of Climate and Köppen's Classification", topic: T, subtopic: 'Basic Notions of Climate',
  notions: 'Weather, climate, elements of climate, controls of climate, temperature range, genetic classification, empirical classification, Köppen.',
  focus: 'Meaning and characteristics of climate; elements of climate; general factors (controls) of climate; genetic and empirical classifications; Köppen\'s classification and its main groups.',
  competence: 'Learners are able to distinguish weather from climate, explain the controls of climate and classify climates with Köppen\'s system, including that of Garoua.',
  objectives: ['Distinguish weather from climate.', 'Name and describe the elements of climate.', 'Explain the controls of climate.', 'Distinguish genetic and empirical classifications.', 'Describe the main groups of Köppen\'s classification.'],
  recall: ['Air masses control the seasons of Garoua.', 'Temperature falls with altitude.', 'Deserts lie under high-pressure belts.'],
  situation: 'In the evening, you tell your grandfather how hot the day was. He answers: "Yes, but things have changed. When I was young, the rainy season was longer and the Harmattan nights were colder; we knew exactly when to plant. Now everything is less predictable." You ask: "What is the difference between the weather of one day and what grandfather remembers over many years, and how do geographers describe and compare the climates of the world?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not distinguish weather from climate and does not know how climates are classified.'],
    ['What is "how hot the day was"?', 'The weather: the state of the atmosphere at a given time.'],
    ['What does grandfather describe?', 'The climate: the average weather over many years (30 years or more).']],
  justification: 'This lesson gives the basic notions needed to describe and compare the climates of the world and to understand climate change.',
  action: 'Use long-term averages, not one day\'s weather, to describe the climate of a place.',
  activities: [
    { sec: '1. MEANING', img: 'clim2_weather_climate.png', caption: 'Weather and climate.', q: 'Over how many years are climate averages usually calculated?', a: 'At least 30 years.', noProj: 'describe today\'s weather and the climate of Garoua.' },
    { sec: '1. ELEMENTS', img: 'f4_stevenson.jpg', caption: 'A Stevenson screen.', q: 'Name three elements of climate.', a: 'Temperature, precipitation, humidity, wind, sunshine or pressure (any three).', noProj: 'list the instruments of a weather station.' },
    { sec: '2. CONTROLS', img: 'clim2_controls.png', caption: 'The controls of climate.', q: 'Which control of climate is the most important?', a: 'Latitude (insolation).', noProj: 'compare Garoua and Paris.' },
    { sec: '3. KÖPPEN', img: 'koppen_big.png', caption: 'Köppen\'s climate groups.', q: 'Which letter does Köppen use for dry climates?', a: 'B.', noProj: 'write the five letters on the board.' },
    { sec: '3. KÖPPEN', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'Why is Garoua\'s climate classified as Aw?', a: 'All months are above 18 °C (A) and there is a dry season in winter (w).', noProj: 'read the graph of Garoua.' },
  ],
  summary: [
    D([['Weather:', 'It is the state of the atmosphere at a given place and time.'],
      ['Climate:', 'It is the average state of the weather of a place over a long period, usually 30 years or more.'],
      ['Elements of climate:', 'They are the measurable components of climate, such as temperature and rainfall.'],
      ['Controls of climate:', 'They are the factors that explain the climate of a place, such as latitude and relief.']]),
    { title: '1. Meaning and Characteristics of Climate', intro: 'Climate is presented as follows:',
      items: [['Weather and climate:', 'Weather changes from day to day, while climate is the expected long-term pattern: Garoua has a long hot, dry season and a warm, wet season.', 'clim2_weather_climate.png', 'weather and climate'],
        ['Temperature range:', 'The difference between the hottest and coolest months is small near the Equator and larger inland.'],
        ['Seasons:', 'Some regions have four seasons, others, like Cameroon, have wet and dry seasons.'],
        ['Rainfall pattern:', 'Rain may fall all year, as in the Congo Basin, or in one season, as in Garoua.']] },
    { title: '2. Elements and Controls of Climate', sub: 'A) Elements of Climate', intro: 'The elements of climate are the following:',
      items: [['Temperature and precipitation:', 'They are the two main elements, measured with thermometers (°C) and rain gauges (mm).', 'f4_stevenson.jpg', 'a Stevenson screen'],
        ['Other elements:', ['Humidity (%), which affects comfort and clouds.', 'Wind (direction and speed), which moves heat and moisture.', 'Sunshine (hours), which affects heating and evaporation.', 'Atmospheric pressure (hPa), which controls winds.']],
        ['Measurement:', 'Long records of these elements give the averages that describe a climate.', 'clim2_elements.png', 'the elements of climate']] },
    { title: '2. Elements and Controls of Climate', sub: 'B) Controls of Climate', intro: 'The controls of climate are the following:',
      items: [['Latitude (insolation):', 'It is the most important control: places near the Equator receive more direct solar energy.', 'clim2_controls.png', 'the controls of climate'],
        ['Pressure, winds and air masses:', 'They distribute heat and moisture, like the Harmattan and the monsoon over Garoua.'],
        ['Altitude and relief:', 'Highlands are cooler, and mountains create relief rain and rain shadows.'],
        ['Distance from the sea and ocean currents:', 'Inland areas have larger ranges, and warm or cold currents change coastal climates.'],
        ['Vegetation and human activities:', 'Forests add moisture, while deforestation, towns and greenhouse gases change local and global climates.']] },
    { title: '3. Classification of Climates', intro: 'Climates are classified as follows:',
      items: [['Genetic classification:', 'It groups climates by their causes, such as air masses and pressure systems.'],
        ['Empirical classification:', 'It groups climates by observed data, mainly temperature and rainfall; Köppen\'s system is the most used.', 'koppen_big.png', 'Köppen\'s groups'],
        ['Köppen\'s idea:', 'Wladimir Köppen used natural vegetation as the best expression of climate, with letters for groups and types.'],
        ['The five groups:', ['A: tropical humid, coldest month above 18 °C (Af rainforest, Am monsoon, Aw savanna).', 'B: dry, evaporation greater than rainfall (BW desert, BS steppe).', 'C: temperate, mild winters (Cs Mediterranean, Cfb London).', 'D: continental, cold winters.', 'E: polar, warmest month below 10 °C (tundra, ice cap).']],
        ['Garoua:', 'It is Aw, a tropical savanna climate with a dry winter season; the Congo Basin is Af, and the far north of Cameroon is close to BSh.', 'clim2_koppen.png', 'Köppen\'s classification']] },
  ],
  evaluation: [['Distinguish weather from climate.', 'Weather is the state of the atmosphere at a given time; climate is the average weather over 30 years or more.'],
    ['Give three controls of the climate of Garoua.', 'Latitude, the Harmattan and monsoon air masses, distance from the sea (continentality), relief (any three).']],
  remediation: ['Climate is averaged over at least ______ years.', 'In Köppen\'s system, dry climates are group ______.', 'Garoua has a ______ climate (Köppen).'],
  remediationAnswers: '1. 30 2. B 3. Aw (tropical savanna)',
  homework: 'Name the cloud that produces thunderstorms.',
  hwAnswer: 'The cumulonimbus.',
  bilingual: [['Climate', 'Le climat'], ['Weather', 'Le temps'], ['Tropical', 'Tropical'], ['Dry', 'Sec, aride'], ['Temperate', 'Tempéré'], ['Classification', 'La classification']],
});

L.push({ kind: 'Further Study', no: 1, title: 'Tropical Weather Disturbances', topic: T, subtopic: 'Air Mass Interactions at Fronts and Convergence Zones',
  notions: 'Weather disturbance, thunderstorm, lightning, supercell, tornado, wind shear, tropical cyclone, hurricane, typhoon, storm surge, early warning.',
  focus: 'Thunderstorms, tornadoes and tropical cyclones: meaning, distribution, causes, consequences; associated hazards and control measures.',
  competence: 'Learners are able to explain the formation and dangers of tropical weather disturbances and the measures to reduce their effects.',
  objectives: ['Define thunderstorms, tornadoes and tropical cyclones.', 'Describe their distribution and causes.', 'Explain their consequences.', 'Propose measures to reduce their hazards.'],
  recall: ['Unstable air forms cumulonimbus clouds.', 'The Coriolis effect deflects winds.', 'The ITCZ is a zone of rising air.'],
  situation: 'One July afternoon in Garoua, the sky suddenly turns dark grey. A strong wind bends the trees and raises dust, then an extremely heavy rain falls so loudly on the metal roof that you hear nothing else. A flash of lightning is followed by a deafening crash of thunder. After about an hour, the storm passes, leaving flooded streets and broken branches. You ask: "What causes such storms, and are there even more dangerous storms elsewhere in the world?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the types, causes and dangers of tropical weather disturbances.'],
    ['What kind of storm hit Garoua?', 'A thunderstorm.'],
    ['Name a larger storm that forms over warm oceans.', 'A tropical cyclone (hurricane).']],
  justification: 'This lesson helps us to understand and prepare for dangerous storms, from the thunderstorms of Garoua to the cyclones of other tropical coasts.',
  action: 'During a thunderstorm, shelter inside a building and keep away from trees, water and metal objects.',
  activities: [
    { sec: '1. THUNDERSTORMS', img: 'thunderstorm_big.png', caption: 'The life of a thunderstorm.', q: 'What are the three stages of a thunderstorm?', a: 'Cumulus (growing), mature and dissipating.', noProj: 'draw the three stages.' },
    { sec: '1. THUNDERSTORMS', img: 'f4_cumulonimbus.jpg', caption: 'A cumulonimbus cloud.', q: 'Give two dangers of a thunderstorm.', a: 'Lightning, flash floods, strong winds and hail (any two).', noProj: 'describe the last storm in Garoua.' },
    { sec: '2. TORNADOES', img: 'clim2_storms.png', caption: 'Three storms compared.', q: 'Where are tornadoes most frequent?', a: 'In the central USA ("Tornado Alley").', noProj: 'compare the sizes of the storms.' },
    { sec: '3. TROPICAL CYCLONES', img: 'cyclone_big.png', caption: 'A tropical cyclone.', q: 'What are tropical cyclones called in the Atlantic?', a: 'Hurricanes.', noProj: 'draw the eye and the spiral bands.' },
    { sec: '4. CONTROL MEASURES', img: 'clim2_storm_measures.png', caption: 'Reducing storm hazards.', q: 'How can a building be protected from lightning?', a: 'With a lightning rod (conductor).', noProj: 'list safety rules for a storm.' },
  ],
  summary: [
    D([['Thunderstorm:', 'It is a local storm from a cumulonimbus cloud, with lightning, thunder, strong winds and heavy rain or hail.'],
      ['Tornado:', 'It is a violently rotating narrow column of air extending from a thunderstorm to the ground.'],
      ['Tropical cyclone:', 'It is a very large rotating storm system with a low-pressure centre, strong winds and heavy rain, formed over warm tropical seas.'],
      ['Storm surge:', 'It is an abnormal rise of the sea level caused by a storm.']]),
    { title: '1. Thunderstorms', intro: 'Thunderstorms are presented as follows:',
      items: [['Distribution:', 'They are very common in hot, humid regions, such as Central Africa and Garoua in the rainy season.', 'f4_cumulonimbus.jpg', 'a cumulonimbus'],
        ['Causes:', 'Strong heating makes moist air rise quickly (convection) in unstable air; condensation releases latent heat and builds a tall cumulonimbus with electric charges.', 'thunderstorm_big.png', 'the life of a thunderstorm'],
        ['Consequences:', ['Flash floods from intense rain.', 'Lightning that kills people and animals and starts fires.', 'Strong winds that damage roofs and trees.', 'Hail that destroys crops.']]] },
    { title: '2. Tornadoes', intro: 'Tornadoes are presented as follows:',
      items: [['Distribution:', 'They occur in many regions but are most frequent and violent in the central USA ("Tornado Alley").', 'clim2_storms.png', 'three storms compared'],
        ['Causes:', 'They form in the most severe thunderstorms (supercells), where changes of wind speed and direction with height (wind shear) make the air rotate.'],
        ['Consequences:', 'Winds can exceed 400 km/h and turn debris into missiles, but the path is narrow (usually less than 1–2 km).']] },
    { title: '3. Tropical Cyclones', intro: 'Tropical cyclones are presented as follows:',
      items: [['Names:', 'They are hurricanes in the Atlantic, typhoons in the north-west Pacific and cyclones in the Indian Ocean.', 'cyclone_big.png', 'a tropical cyclone'],
        ['Distribution:', 'They form over warm oceans between about 5° and 20° N and S; they are almost absent from the South Atlantic, so the coast of Cameroon is rarely hit.'],
        ['Causes:', 'Sea water above 26.5 °C supplies heat and moisture, rising air forms deep low pressure, and the Coriolis effect makes it spin.', 'f4_hurricane.jpg', 'a hurricane from space'],
        ['Consequences:', ['Violent winds over hundreds of kilometres.', 'Storm surges that flood coasts and cause most deaths.', 'Days of torrential rain and floods.']]] },
    { title: '4. Hazards and Control Measures', intro: 'The hazards of storms are reduced by the following measures:',
      items: [['Early warning:', 'Radars, satellites and weather services give alerts by radio and telephone.', 'clim2_storm_measures.png', 'reducing storm hazards'],
        ['Public education:', 'People learn to shelter indoors and to avoid trees, water and metal during storms.'],
        ['Protection of buildings:', 'Lightning rods, strong roofs, wind-resistant building codes and good drains reduce damage.'],
        ['Emergency preparedness:', 'Shelters, drills and rescue services save lives.']] },
  ],
  evaluation: [['Compare a thunderstorm and a tropical cyclone by size and place of formation.', 'A thunderstorm is small (a few km) and forms over land or sea; a cyclone is hundreds of km wide and forms over warm tropical oceans.'],
    ['Give two measures to reduce the hazards of thunderstorms.', 'Early warnings, lightning rods, staying indoors, good drainage (any two).']],
  remediation: ['Thunderstorms form from ______ clouds.', 'Atlantic tropical cyclones are called ______.', 'A rise of the sea caused by a storm is a storm ______.'],
  remediationAnswers: '1. cumulonimbus 2. hurricanes 3. surge',
  homework: 'Define a micro-climate.',
  hwAnswer: 'A micro-climate is the climate of a small area that differs from the climate of the surrounding region.',
  bilingual: [['Thunderstorm', "L'orage"], ['Tornado', 'La tornade'], ['Tropical cyclone', 'Le cyclone tropical'], ['Lightning', "L'éclair, la foudre"], ['Flooding', "L'inondation"], ['Storm surge', "L'onde de tempête"]],
});

L.push({ no: 20, title: 'Micro-climates', topic: T, subtopic: 'Concept of Micro-climate',
  notions: 'Micro-climate, urban climate, urban heat island, anthropogenic heat, evapotranspiration, urban canyon, lakeside climate, forest climate.',
  focus: 'Meaning and classification of micro-climates; characteristics of urban climates; factors of the urban heat island.',
  competence: 'Learners are able to explain micro-climates, especially why the centre of Garoua is hotter than its outskirts, and propose ways to reduce urban heat.',
  objectives: ['Define a micro-climate.', 'Classify micro-climates.', 'Describe the characteristics of urban climates.', 'Explain the factors of the urban heat island.'],
  recall: ['Tar and concrete absorb heat.', 'Plants cool the air by transpiration.', 'Climate is controlled by several factors.'],
  situation: 'On a very hot May afternoon, you leave your family\'s compound in Roumdé Adjia, with many trees and bare ground, and take a moto-taxi to the Grand Marché in the centre of Garoua. As you approach the market, the air becomes hotter and more suffocating; heat rises from the tarred roads and concrete buildings. You ask: "Why does such a short distance make such a big difference in temperature?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand micro-climates and the urban heat island.'],
    ['What is the climate of a small area called?', 'A micro-climate.'],
    ['Why is the town centre hotter?', 'Tar, concrete, engines and few trees create an urban heat island.']],
  justification: 'This lesson helps us to understand local differences of climate and to plan cooler, healthier towns.',
  action: 'Plant and protect trees and green spaces in town, and use light-coloured roofs.',
  activities: [
    { sec: '1. MEANING', img: 'clim2_micro_types.png', caption: 'Types of micro-climates.', q: 'Give two types of micro-climates.', a: 'Urban, mountain, lakeside or forest micro-climates (any two).', noProj: 'list micro-climates around Garoua.' },
    { sec: '1. MEANING', img: 'lsa_lake.jpg', caption: 'A lakeside.', q: 'Why is the air near Lake Lagdo cooler and more humid?', a: 'The water evaporates and heats slowly.', noProj: 'describe a lakeside.' },
    { sec: '2. URBAN CLIMATE', img: 'heat_island_big.png', caption: 'The urban heat island.', q: 'When is the urban heat island strongest?', a: 'At night, when buildings and roads release stored heat.', noProj: 'draw the temperature profile.' },
    { sec: '2. URBAN CLIMATE', img: 'lsa_douala.jpg', caption: 'A large city.', q: 'Why is the air of a city drier?', a: 'There are fewer plants and less open water, so less evapotranspiration.', noProj: 'compare a street and a garden.' },
    { sec: '3. FACTORS', img: 'f2t_rainforest.jpg', caption: 'A forest.', q: 'Why is it cooler under trees?', a: 'Trees give shade and cool the air by transpiration.', noProj: 'stand in the sun and in the shade of a mango tree.' },
  ],
  summary: [
    D([['Micro-climate:', 'It is the climate of a small area that differs from the climate of the surrounding region.'],
      ['Urban heat island:', 'It is the higher temperature of a town compared with the surrounding countryside.'],
      ['Anthropogenic heat:', 'It is the heat released by human activities (vehicles, machines, air conditioners).'],
      ['Evapotranspiration:', 'It is the combined loss of water by evaporation and by plant transpiration.']]),
    { title: '1. Meaning and Classification of Micro-climates', intro: 'Micro-climates are classified as follows:',
      items: [['Urban climate:', 'The climate of a town, warmer, drier and more polluted than the countryside.', 'clim2_micro_types.png', 'types of micro-climates'],
        ['Mountain climate:', 'Conditions vary with altitude and with the side of the mountain.'],
        ['Lakeside climate:', 'Along a large lake such as Lake Lagdo, the air is cooler and more humid.', 'lsa_lake.jpg', 'a lakeside'],
        ['Forest climate:', 'Inside a forest, the air is shady, cool, humid and calm.', 'f2t_rainforest.jpg', 'a forest']] },
    { title: '2. Characteristics of Urban Climates', intro: 'Compared with the countryside, towns have the following characteristics:',
      items: [['Higher temperatures:', 'Towns are warmer, especially at night: this is the urban heat island.', 'heat_island_big.png', 'the urban heat island'],
        ['Lower humidity:', 'Fewer plants and less water mean less evapotranspiration and drier air.'],
        ['Different winds:', 'Buildings slow the wind or channel it along streets (canyon effect).'],
        ['More pollution:', 'Dust, smoke and gases from vehicles, generators and industries are concentrated.'],
        ['Slightly more rain:', 'Extra heat and particles can trigger convectional storms over the city.', 'clim2_urban.png', 'town and countryside compared']] },
    { title: '3. Factors of the Urban Heat Island', intro: 'The urban heat island is caused by the following factors:',
      items: [['Surfaces:', 'Tarred roads, concrete and bricks absorb solar energy by day and release it slowly at night.', 'lsa_douala.jpg', 'a large city'],
        ['Anthropogenic heat:', 'Cars, moto-taxis, generators, air conditioners, factories and crowds release heat.'],
        ['Reduced evapotranspiration:', 'Few trees, gardens and open soils mean little natural cooling.'],
        ['Urban geometry:', 'Tall buildings and narrow streets form "urban canyons" that trap heat and block the wind.'],
        ['Solutions:', 'Trees, parks, light roofs and less traffic reduce urban heat.']] },
  ],
  evaluation: [['What is the urban heat island, and give two of its causes in Garoua?', 'The town is warmer than the countryside; causes: tar and concrete, heat from vehicles and generators, few trees (any two).'],
    ['Give two differences between an urban climate and a rural climate.', 'Towns are warmer, drier, less windy and more polluted (any two).']],
  remediation: ['The climate of a small area is a ______.', 'A town warmer than the countryside is an urban heat ______.', 'Heat from vehicles and machines is ______ heat.'],
  remediationAnswers: '1. micro-climate 2. island 3. anthropogenic',
  homework: 'State how temperature changes with altitude.',
  hwAnswer: 'Temperature decreases as altitude increases, by about 6.5 °C per 1,000 m.',
  bilingual: [['Micro-climate', 'Le microclimat'], ['Urban climate', 'Le climat urbain'], ['Urban heat island', "L'îlot de chaleur urbain"], ['Pollution', 'La pollution'], ['Evapotranspiration', "L'évapotranspiration"], ['Green space', "L'espace vert"]],
});

L.push({ no: 21, title: 'Mountain Climates', topic: T, subtopic: 'Concept of Micro-climate',
  notions: 'Mountain (highland) climate, lapse rate, air pressure, orographic rain, rain shadow, ultraviolet radiation, daily range, vertical zonation, altitude, relief, aspect, latitude.',
  focus: 'Characteristics of mountain climates; vertical zonation; factors of mountain climates (altitude, relief, aspect, latitude).',
  competence: 'Learners are able to explain the climate of mountains such as the Mandara Mountains and Mount Cameroon and its effects on vegetation and people.',
  objectives: ['Define a mountain climate.', 'Describe its main characteristics.', 'Explain the vertical zonation of climate and vegetation.', 'Explain the factors of mountain climates.'],
  recall: ['Temperature falls about 6.5 °C per 1,000 m.', 'Moist air rising over mountains gives relief rain.', 'Aspect is the direction a slope faces.'],
  situation: 'Your family travels from Garoua to Mokolo in the Mandara Mountains. In Garoua the air is hot and dusty, but as the car climbs the winding road, the air through the window becomes cooler and fresher. Yet the sun on your arm feels sharper than in Garoua. You ask: "Why is the air cooler in the mountains while the sun burns more, and how does the climate change so much over such a short distance?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the characteristics and factors of mountain climates.'],
    ['Why is the air cooler in the mountains?', 'Because of altitude: temperature falls as height increases.'],
    ['Why does the sun burn more?', 'The thin, clean air filters less of the Sun\'s ultraviolet rays.']],
  justification: 'This lesson explains the cool, wet highland climates of Cameroon that support dense populations, tea, coffee and tourism.',
  action: 'Protect your skin from strong sun in the mountains and carry warm clothes for cold nights.',
  activities: [
    { sec: '1. CHARACTERISTICS', img: 'lapse_rate_big.png', caption: 'Temperature and height.', q: 'If Garoua (about 200 m) is at 34 °C, what is the temperature at Mokolo (about 800 m)?', a: '34 − (0.6 × 6.5) ≈ 30 °C.', noProj: 'calculate on the board.' },
    { sec: '1. CHARACTERISTICS', img: 'rainfall_types_big.png', caption: 'Relief rain and rain shadow.', q: 'Which side of a mountain receives more rain?', a: 'The windward side.', noProj: 'draw a mountain with wind and rain.' },
    { sec: '1. CHARACTERISTICS', img: 'clim2_mountain.png', caption: 'Characteristics of mountain climates.', q: 'Why are mountain nights very cold?', a: 'The thin air cannot keep the heat, which escapes quickly.', noProj: 'list the five characteristics.' },
    { sec: '2. VERTICAL ZONATION', img: 'veg_altitude_big.png', caption: 'Vegetation zones on Mount Cameroon.', q: 'What is found near the summit of Mount Cameroon?', a: 'Bare lava and rock (with montane grassland below).', noProj: 'draw the zones on a mountain.' },
    { sec: '3. FACTORS', img: 'aspect_big.png', caption: 'The aspect of slopes.', q: 'Which slope is warmer and drier: the one facing the sun or the one facing away?', a: 'The one facing the sun.', noProj: 'compare two sides of a hill.' },
  ],
  summary: [
    D([['Mountain climate:', 'It is the climate of high-altitude areas, cooler and wetter than the surrounding lowlands.'],
      ['Vertical zonation:', 'It is the succession of climate and vegetation zones from the foot to the top of a mountain.'],
      ['Windward side:', 'It is the side of a mountain facing the wind.'],
      ['Leeward side:', 'It is the side of a mountain sheltered from the wind.']]),
    { title: '1. Characteristics of Mountain Climates', intro: 'Mountain climates have the following characteristics:',
      items: [['Lower temperatures:', 'Temperature falls by about 6.5 °C per 1,000 m, so Bamenda and the Mandara Mountains are cooler than the plains.', 'lapse_rate_big.png', 'temperature and height'],
        ['Lower air pressure:', 'The air is thinner and contains less oxygen.'],
        ['Heavy rain on windward slopes:', 'Rising moist air cools and gives orographic rain, as on the seaward side of Mount Cameroon.', 'rainfall_types_big.png', 'relief rain'],
        ['Strong solar radiation:', 'The thin, clean air lets more sunshine and ultraviolet rays through.'],
        ['Large daily range:', 'Days are warm in the sun, but nights are very cold, with frost on high summits.', 'clim2_mountain.png', 'characteristics of mountain climates'],
        ['Vertical zonation:', 'Climbing a mountain is like travelling from the Equator towards the poles.']] },
    { title: '2. Vertical Zonation: Mount Cameroon', intro: 'On Mount Cameroon, climate and vegetation change with height as follows:',
      items: [['Lower slopes (0–800 m):', 'Hot and very wet, with lowland rainforest and plantations of the CDC.', 'veg_altitude_big.png', 'vegetation zones on Mount Cameroon'],
        ['Middle slopes (800–2,400 m):', 'Cooler and misty, with submontane and montane forest.'],
        ['Upper slopes (2,400–3,800 m):', 'Cool to cold, with montane grassland.'],
        ['Summit (above 3,800 m):', 'Cold, windy and dry, with bare lava and rock and frost at night.']] },
    { title: '3. Factors of Mountain Climates', intro: 'Mountain climates are controlled by the following factors:',
      items: [['Altitude:', 'It is the most important factor: height lowers temperature and pressure.'],
        ['Relief:', 'The shape and orientation of mountains force air to rise, giving rain on the windward side and a dry rain shadow on the leeward side.'],
        ['Aspect:', 'Slopes facing the sun are warmer and drier, while slopes facing away are cooler, shadier and moister.', 'aspect_big.png', 'the aspect of slopes'],
        ['Latitude:', 'It sets the base temperature: a mountain near Garoua has a much warmer base than a mountain of the same height in Europe.'],
        ['Human use:', 'The cool, healthy highlands of the West support dense populations, tea, coffee and tourism.', 'f2t_tea_highlands.jpg', 'tea on highlands']] },
  ],
  evaluation: [['Give three characteristics of mountain climates.', 'Lower temperatures, lower pressure, heavy windward rain, strong sunshine, large daily range (any three).'],
    ['Explain why the sun feels stronger in the mountains although the air is cooler.', 'The thin, clean air filters less solar and ultraviolet radiation.']],
  remediation: ['The most important factor of mountain climates is ______.', 'The sheltered side of a mountain is the ______ side.', 'The change of vegetation with height is vertical ______.'],
  remediationAnswers: '1. altitude 2. leeward 3. zonation',
  homework: 'Name one instrument of a weather station.',
  hwAnswer: 'A thermometer, a rain gauge, a barometer, a wind vane, an anemometer or a hygrometer (any one).',
  bilingual: [['Mountain', 'La montagne'], ['Altitude', "L'altitude"], ['Aspect', "L'exposition"], ['Relief', 'Le relief'], ['Precipitation', 'Les précipitations'], ['Rain shadow', "L'ombre pluviométrique"]],
});

module.exports = { B, L };
