// LOWER SIXTH ARTS — Geography of Cameroon, lessons 6–10 (population, towns, agriculture, forests, minerals and energy)
// Syllabus 2019: M4 FS1, M5 FS1, M6 FS1, M6 FS2, M6 FS3. Guided by the teacher's course notes (LSA/USA_CAM_GEO_2026).
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'LSA', code: 'CAM', folder: 'Geography of Cameroon', module: 'Geography of Cameroon', topicDefault: 'Geography of Cameroon', branch: 'Population, Settlement and Resources of Cameroon',
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Geography of Cameroon.', 'Teacher\'s course notes: Mr KAMDEM E., Cameroon Geography (LSA and USA), GBHS Garoua, 2026.', 'BUCREP, 3rd General Census of Population and Housing (2005); United Nations, World Population Prospects (2024 revision).'] };
const L = [];

L.push({ no: 6, title: 'Population Change in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon', pointPerSlide: true,
  notions: 'Demographic characteristics, census, growth rate, age-sex structure, population pyramid, density, migration, push and pull factors.',
  focus: 'Demographic characteristics (evolution in numbers and growth rate, age-sex distribution and pyramid type); population distribution (densities and their spatial variation, factors); major migration trends (inter-regional and rural-urban; pre- and post-independence; causes and effects).',
  competence: 'Learners are able to describe the population of Cameroon, explain its uneven distribution and analyse its main migrations.',
  objectives: ['Describe the evolution of the population of Cameroon and its growth rate.', 'Describe the age-sex structure and the type of pyramid of Cameroon.', 'Explain the spatial variation of population densities.', 'Analyse the major migration trends, their causes and effects.'],
  recall: ['Population density = population ÷ area.', 'The natural increase is the difference between births and deaths.', 'Migration is a movement of people to live in another place.'],
  situation: 'Aïssatou lives in a quarter of Garoua where her neighbours come from everywhere: a family from Maroua, civil servants from Yaoundé and farmers from the Mandara Mountains. She also notices that some quarters are crowded while others are almost empty. She asks: "Why is the population of Cameroon growing so fast, why is it so unevenly spread, and why do people move so much?"',
  sitQA: [['What is the problem in the situation?', 'Aïssatou wants to understand the growth, the distribution and the migrations of the population of Cameroon.'],
    ['Where do Aïssatou\'s neighbours come from?', 'From Maroua, Yaoundé and the Mandara Mountains.'],
    ['What do we call the movement of people to live elsewhere?', 'Migration.']],
  justification: 'This lesson helps us to understand the population of Cameroon, which is the basis of planning schools, health, jobs and housing.',
  action: 'Use population data to explain the needs of your region in schools, jobs and health.',
  activities: [
    { sec: '1. DEMOGRAPHIC CHARACTERISTICS', img: 'cmr_growth_big.png', caption: 'The growth of the population of Cameroon.', q: 'How has the population of Cameroon changed since 1960?', a: 'It has grown very fast, from about 5 million to about 29 million.', noProj: 'write the census figures on the board.' },
    { sec: '1. DEMOGRAPHIC CHARACTERISTICS', img: 'pyramid_cameroon_big.png', caption: 'The population pyramid of Cameroon.', q: 'What does the wide base of this pyramid show?', a: 'A high birth rate and a very young population.', noProj: 'draw a triangle-shaped pyramid.' },
    { sec: '2. POPULATION DISTRIBUTION', img: 'cmr_popdata_big.png', caption: 'Population and area of the regions.', q: 'Which region has the lowest density: the Littoral or the East?', a: 'The East (about 11 people per km², against about 190 in the Littoral).', noProj: 'calculate one density.' },
    { sec: '3. MIGRATION TRENDS', img: 'cmr_migration_big.png', caption: 'Main migrations in Cameroon.', q: 'Towards which towns do most migrants of Cameroon go?', a: 'Douala and Yaoundé.', noProj: 'draw arrows on a sketch map.' },
    { sec: '3. MIGRATION TRENDS', img: 'usa_refugee.jpg', caption: 'Displaced people in a camp.', q: 'Why have many people left parts of the Far North since 2014?', a: 'Because of the insecurity caused by Boko Haram attacks.', noProj: 'discuss forced migration.' },
  ],
  summary: [
    D([['Census:', 'It is the official counting of the whole population of a country at a given date.'],
      ['Growth rate:', 'It is the yearly increase of a population, in per cent.'],
      ['Population pyramid:', 'It is a graph showing the population by age groups and sex.'],
      ['Population density:', 'It is the average number of people per km².'],
      ['Migration:', 'It is the movement of people from one place to another to live there.']]),
    { title: '1. Demographic Characteristics', sub: 'A) Evolution in Numbers and Growth Rate', intro: 'The population of Cameroon has evolved as follows:',
      items: [['Censuses:', 'The censuses counted about 7.7 million people in 1976, about 10.5 million in 1987 and about 17.5 million (17,463,836) in 2005. The population more than doubled in 30 years.', 'cmr_growth_big.png', 'the growth of the population'],
        ['Present population and growth rate:', 'The population is estimated at about 29 million in 2024 by the United Nations. It grows by about 2.6 % per year, so it doubles in about 27 years.'],
        ['High birth rate:', 'The birth rate is about 34 per thousand, because of early marriage, the value placed on large families and the low use of family planning. Each woman has on average more than four children.'],
        ['Falling death rate:', 'The death rate has fallen to about 8 per thousand thanks to vaccination, health care and better nutrition. The gap between births and deaths explains the rapid growth.']] },
    { title: '1. Demographic Characteristics', sub: 'B) Age-Sex Distribution and Pyramid Type', intro: 'The age-sex structure of the population has the following characteristics:',
      items: [['A young population:', 'About 42 % of the people are under 15 years, and only about 3 % are 65 or older. This is the result of the high birth rate.', 'pyramid_cameroon_big.png', 'the pyramid of Cameroon'],
        ['An expansive pyramid:', 'The pyramid has a wide base and a narrow top, and its sides slope steeply. This shape is typical of a developing country with high fertility and a short life expectancy.'],
        ['High dependency:', 'Many young dependants rely on a smaller working population. The state and families must spend a lot on schools, health and food.'],
        ['Sex ratio:', 'Men and women are nearly equal in number in the whole country. However, towns and plantation areas have more men, while rural areas that lose migrants have more women.']] },
    { title: '2. Population Distribution', sub: 'A) Densities and their Spatial Variation', intro: 'The population of Cameroon is distributed as follows:',
      items: [['Average density:', 'The average density is about 60 people per km², but the population is very unevenly spread. The Centre, the South-West and the North have moderate densities, between 40 and 70 per km².', 'cmr_popdata_big.png', 'population data by region'],
        ['High densities:', 'The Littoral with Douala, the West, the North-West and the plains of the Far North have more than 100 people per km². These regions have fertile soils, towns or old farming traditions.'],
        ['Low densities:', 'The Adamawa, the South and especially the East, with about 11 people per km², are thinly populated. Dense forest, poor soils and isolation explain these low densities.'],
        ['Concentration in towns:', 'Douala and Yaoundé alone contain about a quarter of the population of Cameroon. Most other people live in regional towns and along the main roads.']] },
    { title: "2. Population Distribution", sub: "B) Physical Factors of Distribution", intro: "The distribution of the population is explained by the following physical factors:",
      items: [["Fertile volcanic soils:", "The rich volcanic soils of the Western Highlands allow intensive farming all year. They therefore support very dense populations."],
        ["A cool, healthy climate:", "The altitude of the Western Highlands and the Adamawa gives a cool climate with fewer diseases. People are attracted to these healthy areas."],
        ["Dense forest and poor soils:", "In the East and the South, dense forest is hard to clear and leached soils are poor. These areas therefore remain thinly populated."],
        ["Tsetse flies:", "Tsetse flies spread sleeping sickness among people and cattle in parts of the East and the North. People avoid settling in these areas."]] },
    { title: "2. Population Distribution", sub: "C) Human Factors of Distribution", intro: "The distribution of the population is also explained by the following human factors:",
      items: [["Towns and industries:", "Ports, industries and administration attract people to Douala and Yaoundé. These two cities have the highest densities of the country."],
        ["Plantations:", "Plantations of bananas, rubber and oil palm attract workers to the South-West and the Mungo. These areas became densely populated during the colonial period."],
        ["Historical refuges:", "Slave raids pushed some peoples into refuge areas such as the Mandara Mountains. These mountains are still densely populated today."],
        ["Security and amenities:", "Security, roads, schools and hospitals attract people. Insecurity in the Far North and in the North-West and South-West has displaced many people."]] },
    { title: '3. Major Migration Trends', sub: 'A) Inter-Regional and Rural-Urban Movements', intro: 'The main migration trends in Cameroon are the following:',
      items: [['From the highlands to the lowlands:', 'People of the West and North-West have long moved to the coastal lowlands of the Mungo, the South-West and Douala. They go to work on plantations, in trade and in towns.', 'cmr_migration_big.png', 'migrations in Cameroon'],
        ['Movements in the north:', 'Mountain peoples of the Mandara have moved down to the plains, and settlers from the Far North were moved to the Benue valley by the Nord-Est Bénoué project. Young northerners also move south to Yaoundé and Douala for jobs and studies.'],
        ['Rural-urban migration:', 'Everywhere, people leave villages for towns in search of jobs and services. This rural exodus explains the fast growth of the towns.'],
        ['Forced migrations:', 'Since 2014, Boko Haram attacks in the Far North, and since 2016, the crisis in the North-West and South-West, have forced many people to flee. They have moved to safer towns and regions, and some to Nigeria.']] },
    { title: '3. Major Migration Trends', sub: 'B) Pre- and Post-Independence Migrations', intro: 'Migrations before and after independence were the following:',
      items: [['Before independence:', 'The Germans, and then the British and French, recruited workers, often by force, for coastal plantations, ports and railways. This started the movement from the highlands to the coast.'],
        ['After independence:', 'The rural exodus to towns became the main movement. People also moved to new agricultural schemes, such as SEMRY and the Benue valley, and to mining areas.']] },
    { title: "3. Major Migration Trends", sub: "C) Causes of Migration", intro: "Migrations in Cameroon have the following causes:",
      items: [["Land shortage and poverty:", "In overcrowded areas such as the West and the Mandara Mountains, there is not enough land for all families. Poor young people therefore leave to find a living elsewhere."],
        ["Lack of jobs and amenities:", "Villages offer few paid jobs, and they often lack electricity, water, schools and hospitals. People leave for places where these exist."],
        ["Insecurity and drought:", "Boko Haram attacks, the crisis in the North-West and South-West and droughts in the Far North force people to leave. They move to safer or wetter areas."],
        ["The pull of towns:", "Jobs, schools, hospitals, electricity and the attraction of town life draw people to towns. Douala and Yaoundé have the strongest pull."]] },
    { title: "3. Major Migration Trends", sub: "D) Effects of Migration", intro: "Migrations in Cameroon have the following effects:",
      items: [["Loss of young workers:", "The areas of departure lose their young people, so there are fewer farm workers. Villages are left with mostly women, children and old people."],
        ["Remittances:", "Migrants send money home to their families. This money pays for school fees, houses and small businesses in the villages."],
        ["Labour and cultural mixing:", "Migrants supply labour to industries and plantations in the receiving areas. People of different ethnic groups live together and exchange their cultures."],
        ["Overcrowding in towns:", "Towns receive more people than they can house and employ. Slums, unemployment and pressure on services increase."]] },
  ],
  evaluation: [['Give the population of Cameroon at the 2005 census and today.', 'About 17.5 million in 2005 and about 29 million in 2024.'], ['Give one physical factor of the high density of the Western Highlands.', 'Fertile volcanic soils (or a cool, healthy climate).']],
  remediation: ['Cameroon has an ______ (wide-based) population pyramid.', 'The least densely populated region of Cameroon is the ______.', 'Movement from villages to towns is called ______ migration.'],
  remediationAnswers: '1. expansive 2. East 3. rural-urban',
  homework: 'Name the two largest towns of Cameroon.',
  hwAnswer: 'Douala, the economic capital, and Yaoundé, the political capital.',
  bilingual: [['Census', 'Le recensement'], ['Growth rate', 'Le taux de croissance'], ['Population pyramid', 'La pyramide des âges'], ['Density', 'La densité'], ['Migration', 'La migration'], ['Rural exodus', "L'exode rural"], ['Displaced person', 'Le déplacé'], ['Birth rate', 'Le taux de natalité']],
});

L.push({ no: 7, title: 'Urbanisation in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon', pointPerSlide: true,
  notions: 'Urbanisation, urban growth, urban hierarchy, primate city, site, situation, function, hinterland, urban problems.',
  focus: 'Spatial distribution and ranking of urban centres; increasing urbanisation since colonial times and its factors; site and situation of two major towns (Douala and Garoua); functions and linkages with their hinterlands; urban problems, their causes, solutions and difficulties.',
  competence: 'Learners are able to explain the growth of towns in Cameroon, describe the site, situation and functions of towns and propose solutions to urban problems.',
  objectives: ['Explain the increase of urbanisation since colonial times and its factors.', 'Describe the distribution and ranking of urban centres.', 'Describe the site, situation and functions of Douala and Garoua.', 'Explain the links between towns and their hinterlands.', 'Analyse urban problems, solutions and difficulties.'],
  recall: ['Many young people move from villages to towns.', 'Douala and Yaoundé are the largest towns of Cameroon.', 'Towns offer jobs and services.'],
  situation: 'Saratou comes from a village near Lagdo to study in Garoua. She is amazed by the crowds, the cars and the moto-taxis, but she also sees waste in the gutters and crowded quarters. She says: "In my village, most young people have left." She asks: "Why is everybody moving to town, and how can a town like Garoua cope with so many people?"',
  sitQA: [['What is the problem in the situation?', 'Saratou does not know why towns grow so fast and how they cope with their problems.'],
    ['What does Saratou see in Garoua?', 'Crowds, cars, moto-taxis, waste and crowded quarters.'],
    ['What is happening in her village?', 'Most young people have left (rural exodus).']],
  justification: 'This lesson helps us to understand the growth of our towns and to take part in solving urban problems.',
  action: 'Respect town-planning rules, keep your quarter clean and use public spaces responsibly.',
  activities: [
    { sec: '1. SPATIAL DISTRIBUTION AND RANKING', img: 'cmr_towns_big.png', caption: 'The main towns of Cameroon.', q: 'Which two towns are much larger than all the others?', a: 'Douala and Yaoundé.', noProj: 'list towns by size.' },
    { sec: '2. INCREASING URBANISATION', img: 'lsa_yaounde.jpg', caption: 'Yaoundé.', q: 'Why do many young people leave villages for towns?', a: 'To find jobs, schools, hospitals and modern services.', noProj: 'discuss rural exodus.' },
    { sec: '3. SITE AND SITUATION', img: 'douala_site_big.png', caption: 'The site of Douala.', q: 'On what kind of land is Douala built?', a: 'On a low, swampy plain at the estuary of the Wouri.', noProj: 'draw the Wouri estuary.' },
    { sec: '4. FUNCTIONS AND HINTERLAND', img: 'f2t_cattle_market.jpg', caption: 'A cattle market.', q: 'What does Garoua receive from its hinterland?', a: 'Food, cattle, cotton and labour.', noProj: 'list products in the Garoua market.' },
    { sec: '5. URBAN PROBLEMS', img: 'usa_traffic.jpg', caption: 'Traffic in an African city.', q: 'Give one cause of traffic jams in Douala.', a: 'Narrow roads for a fast-growing number of vehicles.', noProj: 'describe traffic in Garoua.' },
  ],
  summary: [
    D([['Urbanisation:', "It is the increase in the proportion of a country's population living in towns."],
      ['Urban growth:', 'It is the increase in the size and number of people of a town.'],
      ['Site:', 'It is the land on which a town is built.'],
      ['Situation:', 'It is the position of a town in relation to its surroundings (rivers, routes, resources, other towns).'],
      ['Hinterland:', 'It is the area around a town that it serves and from which it draws food, labour and raw materials.']]),
    { title: '1. Spatial Distribution and Ranking of Urban Centres', intro: 'The towns of Cameroon are distributed and ranked as follows:',
      items: [['Distribution:', 'Towns are most numerous in the coastal lowlands and the Western Highlands, fewer in the forest south and east. In the north, they are grouped along the main roads.', 'cmr_towns_big.png', 'the towns of Cameroon'],
        ['First order (dual primacy):', 'Douala, the economic capital, and Yaoundé, the political capital, each have about 4 million people. Cameroon therefore has two dominant cities instead of one.'],
        ['Second order:', 'The regional capitals, such as Garoua, Maroua, Bamenda, Bafoussam and Ngaoundéré, form the second level. They have several hundred thousand people and serve whole regions.'],
        ['Third order:', 'Divisional and industrial towns, such as Kumba, Nkongsamba, Edéa, Kribi and Guider, form the third level. They serve smaller areas.']] },
    { title: "2. Increasing Urbanisation and its Factors", sub: "A) Increasing Urbanisation", intro: "Urbanisation in Cameroon has increased as follows:",
      items: [["Colonial origins:", "Many towns grew as ports, administrative posts or railway stations during the colonial period. Douala, Yaoundé and Ngaoundéré are examples."],
        ["A rapid increase:", "The share of the population living in towns rose from about 14 % in 1960 to about 49 % in 2005 and about 59 % today. More than half of Cameroonians now live in towns.", "lsa_douala.jpg", "Douala"]] },
    { title: "2. Increasing Urbanisation and its Factors", sub: "B) Factors", intro: "Urbanisation has increased because of the following factors:",
      items: [["Rural exodus:", "Poverty, land shortage and lack of amenities push people out of villages. Many of them settle in towns."],
        ["The pull of towns:", "Jobs, schools, universities, hospitals and electricity attract people to towns. Young people also seek the modern way of life of the city."],
        ["Administration:", "The creation of new regions and divisions has brought offices, schools and civil servants to small towns. These towns have therefore grown quickly."],
        ["Natural increase:", "Many children are born in towns, where health care reduces deaths. This natural increase adds to the growth from migration."]] },
    { title: '3. Site and Situation', sub: 'A) Douala', intro: 'Douala has the following site and situation:',
      items: [['Site:', 'Douala is built on a low, flat, swampy plain on both banks of the Wouri estuary. This site is easily flooded and difficult to build on.', 'douala_site_big.png', 'the site of Douala'],
        ['Situation:', 'It lies on the Atlantic coast, at the end of the railway and the main roads. It is therefore the gateway of Cameroon and of Chad and the Central African Republic.']] },
    { title: '3. Site and Situation', sub: 'B) Garoua', intro: 'Garoua has the following site and situation:',
      items: [['Site:', 'Garoua is built on a flat plain on the right bank of the Benue, dominated by small hills. The river supplies water and the plain offers space for the town to grow.', 'f2t_benue.jpg', 'the Benue at Garoua'],
        ['Situation:', 'It lies on the main road (N1) between Ngaoundéré and Maroua, near the borders of Nigeria and Chad. It is also a river port on the Benue, navigable for a short period in the rainy season.']] },
    { title: '4. Functions and Linkages with the Hinterland', intro: 'Towns and their hinterlands are linked in the following ways:',
      items: [['Functions of Douala:', 'Douala is the main port, industrial and commercial centre of Cameroon. It also has the headquarters of banks, the terminus of the railway and the main airport.'],
        ['Functions of Garoua:', 'Garoua is the capital of the North Region, with cotton and textile industries such as SODECOTON and CICAM. It is also a centre of trade, with a river port, an international airport and a university.'],
        ['What the hinterland gives:', 'The hinterland supplies the town with food, cattle, cotton, fuelwood and labour. For example, the cattle markets of Garoua receive animals from the whole North.', 'f2t_cattle_market.jpg', 'a cattle market'],
        ['What the town gives:', 'The town offers markets, manufactured goods and jobs to the people of the hinterland. It also provides hospitals, schools, banks and administration.']] },
    { title: "5. Urban Problems and their Causes", sub: "A) Housing and Transport", intro: "Towns such as Douala, Yaoundé and Garoua face the following housing and transport problems:",
      items: [["Housing and slums:", "The towns grow faster than houses can be built, so crowded, unplanned quarters appear, such as New Bell in Douala and Briqueterie in Yaoundé. Many are built in flood-prone areas without water or drains."],
        ["Traffic congestion:", "The number of cars and moto-taxis grows quickly, while the roads remain narrow and poorly maintained. This causes traffic jams, pollution and accidents.", "usa_traffic.jpg", "traffic congestion"]] },
    { title: "5. Urban Problems and their Causes", sub: "B) Social and Environmental Problems", intro: "Towns also face the following social and environmental problems:",
      items: [["Unemployment:", "Industries cannot employ all the migrants who arrive. Many find only informal jobs such as street selling and moto-taxi driving."],
        ["Insecurity:", "Poverty and unemployment push some young people into crime. Theft and attacks are common in poorly lit and unplanned quarters."],
        ["Waste and floods:", "Uncollected waste blocks the drains, so heavy rains cause floods. Stagnant water then spreads diseases such as cholera."],
        ["Shortage of services:", "Water, electricity, schools and health services cannot follow the growth of the population. Many quarters have frequent power and water cuts."]] },
    { title: '6. Solutions and Difficulties', sub: 'A) Solutions', intro: 'The following solutions have been proposed:',
      items: [['Housing:', 'The SIC builds social housing, and MAETUR prepares plots with roads, water and electricity. These reduce the growth of slums.'],
        ['Roads and transport:', 'New roads, flyovers and bus services are built, especially in Douala and Yaoundé. They reduce traffic jams and the time spent travelling.'],
        ['Waste management:', 'HYSACAM collects waste in the main towns, and councils clean the drains. This reduces floods and diseases.'],
        ['Decentralisation:', 'City and local councils receive more powers and money to manage their towns. The state also develops secondary towns to reduce the pressure on Douala and Yaoundé.']] },
    { title: "6. Solutions and Difficulties", sub: "B) Difficulties", intro: "These solutions face the following difficulties:",
      items: [["Lack of funds:", "Councils and the state do not have enough money for roads, drains and housing. As a result, projects are slow and cover only small parts of the towns."],
        ["Uncontrolled building:", "Many quarters grow without plans, and people build on land reserved for roads or in dangerous zones. It then becomes very costly to provide services."],
        ["Corruption:", "Part of the money for urban projects is misused. Social housing is sometimes given to people who are not poor."],
        ["Land disputes:", "Several people often claim the same piece of land. These conflicts delay the building of roads and houses."]] },
  ],
  evaluation: [['Distinguish between the site and the situation of a town.', 'The site is the land on which the town is built; the situation is its position in relation to its surroundings.'], ['Give two urban problems of Douala and one solution.', 'Floods and traffic congestion; drainage works (or new roads).']],
  remediation: ['The increase in the share of people living in towns is ______.', 'Douala and Yaoundé form a case of dual ______.', 'The area served by a town is its ______.'],
  remediationAnswers: '1. urbanisation 2. primacy 3. hinterland',
  homework: 'Name two agro-industrial companies of Cameroon.',
  hwAnswer: 'SODECOTON (cotton) and the CDC (bananas, rubber, oil palm); also SEMRY (rice) and PAMOL (oil palm).',
  bilingual: [['Town', 'La ville'], ['Urbanisation', "L'urbanisation"], ['Site', 'Le site'], ['Situation', 'La situation'], ['Hinterland', "L'arrière-pays"], ['Slum', 'Le bidonville'], ['Traffic jam', "L'embouteillage"], ['Waste', 'Les déchets']],
});

L.push({ no: 8, title: 'Agricultural Development and Change in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon', pointPerSlide: true,
  notions: 'Agriculture, peasant farming, plantation, livestock farming, intensive, extensive, yield, second-generation agriculture.',
  focus: 'General characteristics, types, productivity and importance of agriculture; systems (peasant crop production, modern plantations, traditional and modern livestock farming) and their spatial distribution; factors; impacts; problems and solutions; changes since independence.',
  competence: 'Learners are able to describe the agricultural systems of Cameroon, explain their distribution and propose solutions to agricultural problems.',
  objectives: ['Explain the characteristics and importance of agriculture in Cameroon.', 'Describe the agricultural systems and their distribution.', 'Explain the factors that influence agriculture.', 'Analyse the impacts and problems of agriculture and their solutions.', 'Describe the changes in agriculture since independence.'],
  recall: ['Most people in rural areas are farmers.', 'Cotton is the main cash crop of the North.', 'SODECOTON buys cotton from farmers.'],
  situation: 'Near Garoua, old Mallam Issa grows millet and sorghum on a small plot with a hoe and his family\'s help, mostly to feed his family. His neighbour\'s son Abdou works for SODECOTON, where cotton is grown with selected seeds, fertilisers and tractors and sold for export. Abdou asks: "Why are there such different ways of farming in Cameroon, and how can our agriculture improve?"',
  sitQA: [['What is the problem in the situation?', 'Abdou wants to understand the different farming systems and how agriculture can improve.'],
    ['What does Mallam Issa grow and why?', 'Millet and sorghum, mainly to feed his family.'],
    ['What does SODECOTON produce?', 'Cotton for sale and export.']],
  justification: 'This lesson helps us to understand agriculture, the main activity of Cameroonians, and the changes needed to feed the nation.',
  action: 'Support modern, sustainable farming and protect farmland from erosion.',
  activities: [
    { sec: '1. GENERAL CHARACTERISTICS', img: 'usa_womenfarm.jpg', caption: 'Women working on a farm.', q: 'Which tools do most peasant farmers use?', a: 'Simple tools such as hoes and cutlasses.', noProj: 'list farm tools.' },
    { sec: '2. AGRICULTURAL SYSTEMS', img: 'cmr_agri_big.png', caption: 'Agricultural regions of Cameroon.', q: 'Which crops dominate the north of Cameroon?', a: 'Cotton, millet, sorghum and groundnuts, with cattle rearing.', noProj: 'shade farming regions.' },
    { sec: '2. AGRICULTURAL SYSTEMS', img: 'lsa_oilpalm.jpg', caption: 'An oil palm plantation.', q: 'What is special about a plantation?', a: 'It is a very large farm growing one cash crop for sale, with hired workers and much capital.', noProj: 'name plantations.' },
    { sec: '2. AGRICULTURAL SYSTEMS', img: 'usa_herders.jpg', caption: 'Herders with cattle.', q: 'Why do Mbororo herders move with their cattle in the dry season?', a: 'To find grass and water (transhumance).', noProj: 'describe transhumance.' },
    { sec: '5. CHANGES SINCE INDEPENDENCE', img: 'f2t_field_trial.jpg', caption: 'A research field.', q: 'How does IRAD help farmers?', a: 'It creates improved seeds and teaches better methods.', noProj: 'name improved crops.' },
  ],
  summary: [
    D([['Agriculture:', 'It is the growing of crops and the rearing of animals for food, income and raw materials.'],
      ['Peasant farming:', 'It is small-scale farming by families, mainly for their own food.'],
      ['Plantation:', 'It is a very large farm that specialises in one cash crop for sale, with much capital and hired labour.'],
      ['Yield:', 'It is the quantity produced per hectare or per animal.']]),
    { title: "1. General Characteristics, Types, Productivity and Importance", sub: "A) Characteristics, Types and Productivity", intro: "Agriculture in Cameroon has the following characteristics:",
      items: [["Small family farms:", "Agriculture is dominated by small family farms that use simple tools, depend on rainfall and have little capital. Beside them, a few large plantations use modern methods.", "usa_womenfarm.jpg", "women farming"],
        ["Food crops and cash crops:", "Farmers grow food crops such as cassava, maize, plantain and sorghum. They also grow cash crops such as cocoa, coffee, cotton, bananas, rubber and oil palm."],
        ["Livestock:", "Farmers rear cattle, sheep, goats and poultry. Cattle rearing is most important in the Adamawa and the north."],
        ["Productivity:", "Yields are generally low on peasant farms because of poor seeds, few fertilisers and simple tools. They are much higher on plantations, which use improved inputs and machines."]] },
    { title: "1. General Characteristics, Types, Productivity and Importance", sub: "B) Importance", intro: "Agriculture is important in the following ways:",
      items: [["Employment:", "Agriculture employs more than 40 % of the workers of Cameroon. It is the main source of income in rural areas."],
        ["Food supply:", "It feeds the population of the country. It also supplies food to neighbouring countries such as Gabon and Chad."],
        ["Raw materials for industry:", "It supplies cotton to CICAM, cocoa to chocolate factories and palm oil to soap factories. These industries create more jobs."],
        ["Export revenue:", "Cocoa, coffee, cotton, bananas and rubber are exported. Cameroon is one of the leading cocoa producers of the world."]] },
    { title: '2. Agricultural Systems and their Distribution', sub: 'A) Crop Production by Peasants', intro: 'Peasant crop production has the following characteristics:',
      items: [['Farm size and ownership:', 'Plots are small, often under 2 hectares, and owned by families or held under customary law. They are often divided into several scattered fields.', 'cmr_agri_big.png', 'the farming systems of Cameroon'],
        ['Labour and capital:', 'The work is done by the family, with hoes and cutlasses. Farmers have little money to buy seeds, fertilisers or machines.'],
        ['Methods:', 'Shifting cultivation and bush fallowing are practised in the forest, and permanent farming with manure in densely populated areas. In the Mandara Mountains, farmers cultivate terraces.'],
        ['Purpose and products:', 'The main purpose is to feed the family, with any surplus sold at local markets. Some cash crops are also grown: cocoa and coffee in the south and west, and cotton in the north.']] },
    { title: '2. Agricultural Systems and their Distribution', sub: 'B) Modern Plantation Systems', intro: 'Modern plantations have the following characteristics:',
      items: [['Farm size and ownership:', 'Plantations cover hundreds or thousands of hectares and belong to the state or to companies such as CDC, SOCAPALM, PAMOL, PHP and SOSUCAM. Many date from the colonial period.', 'lsa_oilpalm.jpg', 'an oil palm plantation'],
        ['Labour and capital:', 'They employ many paid workers and use machines, fertilisers and pesticides. They also have factories to process their products.'],
        ['Location:', 'They are found mainly in the fertile volcanic lowlands of the South-West, the Littoral and the Mungo. Sugar cane is grown near Mbandjock in the Centre.'],
        ['Purpose and products:', 'They produce bananas, rubber, oil palm, tea and sugar cane. Their products are mainly for export and for local industries.']] },
    { title: '2. Agricultural Systems and their Distribution', sub: 'C) Livestock Farming Systems', intro: 'Livestock farming is organised in the following systems:',
      items: [['Traditional (extensive) systems:', 'Mbororo and Fulani herders practise nomadism and transhumance with large herds of cattle in the Adamawa, the North, the Far North and the North-West. They use natural pastures and invest little capital.', 'usa_herders.jpg', 'herders with cattle'],
        ['Modern (intensive) systems:', 'Ranches with fenced pastures and veterinary care, such as the SODEPA ranches in the Adamawa, produce better-quality animals. Modern poultry and pig farms are found near the towns.'],
        ['The main area:', 'The Adamawa Plateau is the main cattle region of Cameroon. Its altitude keeps it free of tsetse flies, and its grasslands offer good pastures.']] },
    { title: "3. Factors of the Agricultural Systems", sub: "A) Physical Factors", intro: "The characteristics and distribution of farming depend on the following physical factors:",
      items: [["Climate:", "Climate decides which crops can be grown in each region. Cocoa grows in the wet south, while cotton and sorghum grow in the dry north."],
        ["Soils:", "Fertile volcanic and black soils favour intensive farming. Leached forest soils need long fallows."],
        ["Relief:", "Steep slopes, as in the Mandara Mountains, require terraces. Cool highlands such as the Adamawa favour cattle rearing."]] },
    { title: "3. Factors of the Agricultural Systems", sub: "B) Human and Economic Factors", intro: "Farming also depends on the following human and economic factors:",
      items: [["Population density:", "In densely populated areas, land is scarce, so farming is more intensive. Farmers use manure and grow crops on the same land every year."],
        ["Land tenure:", "Customary law often divides land into small family plots. Farmers without secure ownership invest little in their land."],
        ["Capital and markets:", "Capital, credit, roads, machines and fertilisers allow modern farming. Where they are lacking, farming remains traditional."],
        ["Cultural values:", "Among the Fulani and Mbororo, cattle are a sign of wealth and prestige. Some groups also prefer certain crops for their food."]] },
    { title: "4. Impacts of the Agricultural Systems", sub: "A) Positive Impacts", intro: "Agriculture has the following positive impacts:",
      items: [["Employment:", "Agriculture gives work to most rural people and to many plantation workers. It reduces unemployment in rural areas."],
        ["Better living standards:", "The income from crops and livestock pays for food, school fees and houses. Rural living standards therefore improve."],
        ["Food security:", "Agriculture feeds the population of the country and of neighbouring countries. It reduces the need to import food."],
        ["Foreign currency:", "Cocoa, coffee, cotton, bananas and rubber are sold abroad. They earn foreign currency for the country."]] },
    { title: "4. Impacts of the Agricultural Systems", sub: "B) Negative Impacts", intro: "Agriculture also has the following negative impacts:",
      items: [["Deforestation:", "Farms and plantations replace natural forests and savanna. Many plants and animals lose their habitats."],
        ["Soil erosion:", "Bare soils are washed away by rain, especially on slopes. The land then becomes less fertile."],
        ["Pollution:", "Fertilisers and pesticides are washed into rivers and soils. They harm fish and pollute drinking water."],
        ["Overgrazing:", "Too many cattle and frequent bush fires degrade the pastures of the north. The bare land is exposed to erosion and desertification."]] },
    { title: "5. Problems and Solutions", sub: "A) Physical Problems", intro: "Agriculture faces the following physical problems:",
      items: [["Drought:", "The north suffers from drought and irregular rain. Crops dry up and harvests are poor in bad years."],
        ["Poor soils:", "The forest soils of the south are leached and acid. Their yields fall quickly after a few years of farming."],
        ["Floods:", "Rivers such as the Benue and the Logone flood fields in the rainy season. Crops and animals are destroyed."],
        ["Pests and diseases:", "Locusts, caterpillars and plant diseases destroy crops, and cattle suffer from diseases. Farmers lose part of their production."]] },
    { title: "5. Problems and Solutions", sub: "B) Human Problems", intro: "Agriculture also faces the following human problems:",
      items: [["Land disputes:", "Conflicts over land between families, farmers and herders are common. They discourage farmers from investing in their land."],
        ["Simple techniques:", "Most farmers use hoes and cutlasses on small farms. They cannot produce large quantities."],
        ["Bad roads and poor storage:", "Many farm roads are impassable in the rainy season, and crops rot in poor stores. Farmers lose part of their harvest."],
        ["Low and unstable prices:", "Prices paid to farmers are low and change from year to year. Farmers therefore earn little and cannot plan."]] },
    { title: "5. Problems and Solutions", sub: "C) Solutions", intro: "The following solutions are proposed:",
      items: [["Irrigation:", "Irrigation schemes such as SEMRY allow farming in the dry season. They protect crops against drought."],
        ["Improved seeds and fertilisers:", "Improved seeds resist drought and diseases, and fertilisers enrich the soil. Together they raise yields."],
        ["Credit, roads and storage:", "Credit allows farmers to buy inputs and equipment. Farm roads and storage facilities reduce losses and give access to markets."],
        ["Cooperatives and training:", "Cooperatives help farmers to buy inputs and sell their products at better prices. Extension workers train them in modern techniques."]] },
    { title: '6. Changes and Reforms since Independence', intro: 'Agriculture has changed in the following ways since independence:',
      items: [['State agro-industrial companies:', 'The state created companies to organise production, such as SODECOTON (cotton), CDC (plantations), SEMRY and UNVDA (rice) and SODECAO (cocoa). They supply inputs, buy crops and build roads.'],
        ['The Green Revolution and research:', 'In the 1970s, the state promoted improved seeds, fertilisers and credit to intensify farming. IRAD develops higher-yielding, disease-resistant varieties of maize, sorghum, cassava and cotton.', 'f2t_field_trial.jpg', 'a field trial'],
        ['Liberalisation (1990s):', 'The state withdrew from marketing and closed or sold some companies. Farmers formed cooperatives and common initiative groups (CIGs) to sell their products.'],
        ['Second-generation agriculture:', 'Since 2011, the state has promoted modern, mechanised and commercial farming. It encourages young farmers and agro-industries to raise production and create jobs.']] },
  ],
  evaluation: [['Give two differences between peasant farming and plantations.', 'Peasant farms are small with family labour and produce mainly food; plantations are huge, use hired labour and capital and produce cash crops for sale.'], ['Give two problems of agriculture in the North and one solution.', 'Drought and poor storage; irrigation (or improved storage).']],
  remediation: ['The company that organises cotton farming is ______.', 'Moving herds seasonally in search of pasture is ______.', 'The research institute that creates improved seeds is ______.'],
  remediationAnswers: '1. SODECOTON 2. transhumance 3. IRAD',
  homework: 'Name two valuable timber species of Cameroon.',
  hwAnswer: 'Examples: sapele, iroko, ayous, moabi, azobé and ebony.',
  bilingual: [['Agriculture', "L'agriculture"], ['Peasant farming', "L'agriculture paysanne"], ['Plantation', 'La plantation'], ['Yield', 'Le rendement'], ['Livestock', 'Le bétail'], ['Irrigation', "L'irrigation"], ['Cooperative', 'La coopérative'], ['Cash crop', 'La culture de rente']],
});

L.push({ no: 9, title: 'Management of Forest Resources in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon', pointPerSlide: true,
  notions: 'Forest resource, timber, non-timber forest products, logging, forest management unit, community forest, conservation, deforestation.',
  focus: 'Types and distribution of forests; resources and ownership; exploitation (stakeholders, large- and small-scale methods, localities); uses including fuel; problems of exploitation and over-exploitation; socio-economic impacts; environmental role; conservation and management measures; reserves and the role of government.',
  competence: 'Learners are able to explain how the forests of Cameroon are exploited and propose measures for their sustainable management.',
  objectives: ['Describe the types, distribution, resources and ownership of forests.', 'Describe the exploitation of forests: stakeholders, methods and localities.', 'Explain the problems of exploitation and the impacts of forests.', 'Describe the conservation and management measures.'],
  recall: ['The rainforest covers the south of Cameroon.', 'Sapele and iroko are valuable timbers.', 'Many households cook with firewood and charcoal.'],
  situation: 'Binta helps her mother cook with charcoal in Garoua. Her mother complains that the price of a bag of charcoal has risen again, because the sellers now go far into the bush to find trees, and the land around the town is becoming bare. Binta asks: "Who owns the trees, why are we using them so fast, and how can our forests be managed so that they last?"',
  sitQA: [['What is the problem in the situation?', 'The trees near Garoua are disappearing, and Binta wants to know how forests can be managed sustainably.'],
    ['Why has the price of charcoal risen?', 'Sellers must go farther to find trees, so transport costs more.'],
    ['What happens to the land around the town?', 'It becomes bare (deforestation).']],
  justification: 'This lesson helps us to understand the value of our forests and our role in protecting them.',
  action: 'Use improved stoves, plant trees and respect protected areas.',
  activities: [
    { sec: '1. TYPES AND RESOURCES', img: 'cmr_forest_big.png', caption: 'Forests and timber in Cameroon.', q: 'In which region is logging most intensive?', a: 'The East (also the South and the Centre).', noProj: 'shade the forest zone.' },
    { sec: '2. EXPLOITATION', img: 'f2t_logging_truck.jpg', caption: 'A lorry carrying logs.', q: 'Who carries out large-scale logging?', a: 'Logging companies holding concessions from the state.', noProj: 'name logging towns.' },
    { sec: '2. EXPLOITATION', img: 'f2t_charcoal.jpg', caption: 'Bags of charcoal.', q: 'Which forest product is the main source of energy for most households?', a: 'Fuelwood and charcoal.', noProj: 'ask how families cook.' },
    { sec: '3. PROBLEMS AND IMPACTS', img: 'usa_clearcut.jpg', caption: 'A cleared forest.', q: 'Give one environmental effect of removing forests.', a: 'Soil erosion (also loss of biodiversity and climate change).', noProj: 'discuss bare land around Garoua.' },
    { sec: '4. CONSERVATION AND MANAGEMENT', img: 'cmr_protected_areas.png', caption: 'Protected areas of the forest zone.', q: 'Why does the state create national parks?', a: 'To protect plants, animals, soils and water sources.', noProj: 'name parks of Cameroon.' },
  ],
  summary: [
    D([['Forest resource:', 'It is anything useful obtained from a forest: timber, fuelwood, food, medicines, wildlife.'],
      ['Non-timber forest products (NTFPs):', 'They are forest products other than timber, such as eru, bush mango, honey and medicinal bark.'],
      ['Forest management unit (UFA):', 'It is a forest concession given to a company for long-term logging under a management plan.'],
      ['Conservation:', 'It is the careful use and protection of resources so that they last.']]),
    { title: "1. Types, Distribution, Resources and Ownership", sub: "A) Types and Distribution", intro: "The forests of Cameroon are of the following types:",
      items: [["Dense rainforest:", "It covers the South, East, Centre, Littoral and South-West. It is the largest and richest forest of the country.", "cmr_forest_big.png", "the forests of Cameroon"],
        ["Mangroves:", "They line the estuaries and creeks of the coast, from Rio del Rey to the Ntem. They grow in salty, muddy water."],
        ["Montane forests:", "They cover the high mountains of the Western Highlands, such as Mount Cameroon and Mount Oku. They are small and threatened."],
        ["Savanna woodlands:", "They are found in the Adamawa and the north. Their trees are smaller and more scattered."]] },
    { title: "1. Types, Distribution, Resources and Ownership", sub: "B) Extent, Resources and Ownership", intro: "The forests of Cameroon have the following extent, resources and owners:",
      items: [["Extent:", "Forests cover about 40 % of Cameroon, about 20 million hectares. It is one of the largest forest areas of the Congo Basin."],
        ["Timber resources:", "The forests contain more than 300 commercial timber species, such as sapele, ayous, iroko, azobé, moabi and ebony. Many of them are valuable hardwoods."],
        ["Other resources:", "The forests provide non-timber forest products such as eru, bush mango and medicinal plants. They also supply fuelwood and wildlife."],
        ["Ownership:", "The permanent forest estate includes state forests, such as production forests, parks and reserves, and council forests. Villages manage community forests of up to 5,000 hectares, and some forests and plantations are private."]] },
    { title: '2. Exploitation', sub: 'A) Stakeholders', intro: 'The main stakeholders in the exploitation of forests are the following:',
      items: [['The state:', 'The Ministry of Forestry and Wildlife (MINFOF) makes the rules, grants concessions and controls logging. It also collects forestry taxes.'],
        ['Logging companies:', 'Large national and foreign companies log the concessions and process the timber in sawmills. They build roads into the forest to reach the trees.', 'f2t_logging_truck.jpg', 'a logging truck'],
        ['Local communities:', 'Villages and indigenous peoples such as the Baka use the forest for food, fuel, medicine and culture. They also manage community forests.'],
        ['NGOs and partners:', 'Organisations such as WWF and WCS support conservation and community forestry. They also help to monitor illegal logging and poaching.']] },
    { title: "2. Exploitation", sub: "B) Methods and Localities", intro: "Forests are exploited by the following methods and in the following localities:",
      items: [["Modern large-scale exploitation:", "Companies practise selective logging with chainsaws, bulldozers and lorries in their concessions. The logs are processed in sawmills into planks and plywood.", "usa_sawmill.jpg", "a sawmill"],
        ["Small-scale exploitation:", "Local people saw timber with chainsaws, cut fuelwood, make charcoal and gather forest products. This activity supplies local markets and towns."],
        ["Localities:", "Logging is intensive in the East, around Bertoua and Yokadouma, and in the South and the Centre. It is less intensive in the north and forbidden in parks and reserves."]] },
    { title: "2. Exploitation", sub: "C) Uses", intro: "Forest products are used in the following ways:",
      items: [["Timber:", "Timber is used for building and furniture in Cameroon. It is also exported through the ports of Douala and Kribi."],
        ["Fuel:", "Fuelwood and charcoal are the main energy of most households. Towns such as Garoua and Yaoundé consume large quantities.", "f2t_charcoal.jpg", "charcoal"],
        ["Food and medicine:", "People collect eru, bush mango, honey and bushmeat for food. Bark and leaves are used as traditional medicine."]] },
    { title: "3. Problems and Impacts", sub: "A) Problems Hindering Exploitation", intro: "Forest exploitation faces the following problems:",
      items: [["Remote forests and bad roads:", "Many forests are far from towns and ports, and the roads are bad. Transporting the logs is therefore slow and costly."],
        ["Heavy rain:", "Heavy rain makes forest roads impassable for several months. Logging must then stop."],
        ["Lack of capital:", "Machines, lorries and sawmills are very expensive. Local operators lack the money to buy them."]] },
    { title: "3. Problems and Impacts", sub: "B) Over-Exploitation", intro: "The forests are over-exploited in the following ways:",
      items: [["Illegal logging:", "Some operators cut trees without permits or outside their concessions. The forest loses its most valuable trees without control.", "usa_clearcut.jpg", "a cleared forest"],
        ["Fuelwood cutting around towns:", "The demand for fuelwood and charcoal is high in towns. The forests and savannas around them are cleared year after year."],
        ["Poaching:", "Animals are hunted illegally for bushmeat and ivory. Elephants, gorillas and other species become rare."],
        ["Shifting cultivation:", "Farmers clear new forest plots each year for their crops. As the population grows, the forest shrinks."]] },
    { title: "3. Problems and Impacts", sub: "C) Socio-Economic Impacts", intro: "Forest exploitation has the following socio-economic impacts:",
      items: [["Jobs:", "Logging companies, sawmills and transporters employ many people. Local people also earn income from fuelwood and forest products."],
        ["Revenue and taxes:", "Timber exports bring foreign currency, and forestry taxes are shared with councils and communities. This money builds schools, wells and roads."],
        ["Conflicts:", "Companies, the state and villagers often disagree over land and the sharing of benefits. These conflicts can delay logging or lead to violence."]] },
    { title: "3. Problems and Impacts", sub: "D) Environmental Role of Forests", intro: "Forests play the following environmental role:",
      items: [["Protection of soils and water:", "Tree roots hold the soil, and the forest cover reduces erosion. Forests also protect the sources of rivers."],
        ["Climate regulation:", "Forests store carbon and release water vapour. They help to regulate the climate of the region and of the world."],
        ["Biodiversity:", "Forests shelter a rich variety of plants and animals. This biodiversity is lost when they are cleared."]] },
    { title: "4. Conservation and Management Measures", sub: "A) Legal and Protective Measures", intro: "Forests are protected by the following measures:",
      items: [["Legislation:", "The 1994 Forestry and Wildlife Law organises logging, taxes and community forests. It divides the forest into permanent and non-permanent estates."],
        ["Protected areas:", "National parks and reserves such as the Dja, Lobéké, Campo-Ma'an, Korup, Bénoué and Bouba Ndjida protect a large part of the forest. Logging and hunting are forbidden or controlled in them.", "cmr_protected_areas.png", "the protected areas"],
        ["Management plans:", "Concessions must follow management plans that limit how many trees are cut each year. The export of logs of many species is also restricted, so that more wood is processed in Cameroon."]] },
    { title: "4. Conservation and Management Measures", sub: "B) Other Management Measures", intro: "Forests are also managed by the following measures:",
      items: [["Reforestation:", "ANAFOR and other projects replant trees in degraded areas. This restores the forest cover and supplies future timber."],
        ["Community forests:", "Villages manage their own forests and receive the benefits. They therefore protect them from illegal cutting."],
        ["Control of illegal logging:", "Forest guards and satellite monitoring detect illegal logging. The FLEGT agreement with the European Union allows only legal timber to be exported to Europe."],
        ["Certification:", "The FSC label shows that timber comes from well-managed forests. Certified companies can sell their timber at better prices."]] },
  ],
  evaluation: [['Name two stakeholders in forest exploitation in Cameroon.', 'The state (MINFOF) and logging companies (also local communities and NGOs).'], ['Give two measures taken to manage forests sustainably.', 'Protected areas and management plans (also the 1994 law and community forests).']],
  remediation: ['Forest products other than timber are called ______.', 'The ministry in charge of forests is ______.', 'Forests managed by villages are ______ forests.'],
  remediationAnswers: '1. NTFPs (non-timber forest products) 2. MINFOF 3. community',
  homework: 'Name two minerals exploited in Cameroon.',
  hwAnswer: 'Examples: crude oil, natural gas, limestone, gold, bauxite (planned) and iron ore (planned).',
  bilingual: [['Forest', 'La forêt'], ['Timber', 'Le bois d\'œuvre'], ['Logging', "L'exploitation forestière"], ['Sawmill', 'La scierie'], ['Fuelwood', 'Le bois de chauffe'], ['Deforestation', 'La déforestation'], ['Community forest', 'La forêt communautaire'], ['Reforestation', 'Le reboisement']],
});

L.push({ no: 10, title: 'Management of Mineral and Energy Resources in Cameroon', subtopic: 'Population, Settlement and Resources of Cameroon', pointPerSlide: true,
  notions: 'Mineral, energy resource, hydrocarbons, open-pit mining, artisanal mining, stakeholder, mining code, sustainable exploitation.',
  focus: 'Low level of exploitation; types, distribution, quality and quantity of minerals; methods and stakeholders; uses (including energy minerals); problems and recent state efforts; benefits; measures for sustainable exploitation.',
  competence: 'Learners are able to locate the mineral and energy resources of Cameroon, explain their low exploitation and propose measures for sustainable management.',
  objectives: ['Explain the low level of exploitation of minerals in Cameroon.', 'Describe the types and distribution of minerals and energy resources.', 'Describe the methods of exploitation and the stakeholders.', 'Explain the problems, state efforts, benefits and measures for sustainable exploitation.'],
  recall: ['Minerals are natural substances taken from the ground.', 'Oil is extracted near the coast of Cameroon.', 'Most electricity in Cameroon comes from dams.'],
  situation: 'Oumarou hears on the news that the state has signed an agreement to exploit the iron ore of Mbalam in the East, with a railway to the port of Kribi. His uncle, an artisanal gold miner near Batouri, works with shovels and pans. Oumarou asks his father: "If Cameroon is so rich in minerals, why are so few of them exploited, and how can they benefit the country?"',
  sitQA: [['What is the problem in the situation?', 'Oumarou does not understand why the rich minerals of Cameroon are little exploited and how they can benefit the country.'],
    ['Which mineral is found at Mbalam?', 'Iron ore.'],
    ['How does the uncle mine gold?', 'By hand, with shovels and pans (artisanal mining).']],
  justification: 'This lesson helps us to know the mineral and energy wealth of Cameroon and the conditions for using it well.',
  action: 'Save energy at home and support the responsible use of mineral wealth.',
  activities: [
    { sec: '1. TYPES AND DISTRIBUTION', img: 'cmr_minerals_big.png', caption: 'Minerals of Cameroon.', q: 'Where are the bauxite deposits of Cameroon?', a: 'At Minim-Martap and Ngaoundal (Adamawa) and Fongo-Tongo (West).', noProj: 'mark minerals on a sketch map.' },
    { sec: '1. TYPES AND DISTRIBUTION', img: 'usa_offshore.jpg', caption: 'An offshore oil platform.', q: 'Where is most of Cameroon\'s oil extracted?', a: 'Offshore, in the Rio del Rey basin (and the Douala/Kribi-Campo basin).', noProj: 'show the coast on a map.' },
    { sec: '2. METHODS AND STAKEHOLDERS', img: 'usa_goldminers.jpg', caption: 'Artisanal miners.', q: 'What are the characteristics of artisanal mining?', a: 'It uses simple tools and much labour, and it is often informal.', noProj: 'describe gold mining in the East.' },
    { sec: '3. PROBLEMS AND STATE EFFORTS', img: 'lsa_nachtigal.jpg', caption: 'A dam on the Sanaga.', q: 'Why does mining need dams and railways?', a: 'Mines need a lot of electricity and transport for heavy ores.', noProj: 'name dams and ports.' },
    { sec: '4. BENEFITS AND SUSTAINABILITY', img: 'usa_openpit.jpg', caption: 'An open-pit mine.', q: 'What must a mining company do when the mine closes?', a: 'Restore the land (fill, replant trees).', noProj: 'discuss old quarries.' },
  ],
  summary: [
    D([['Mineral:', "It is a natural substance obtained from the Earth's crust, such as iron ore, bauxite or gold."],
      ['Energy resource:', 'It is a source of power, such as oil, gas, water (hydroelectricity) or the sun.'],
      ['Artisanal mining:', 'It is small-scale mining with simple tools and much labour.'],
      ['Sustainable exploitation:', 'It is the use of resources that meets present needs without destroying them for future generations.']]),
    { title: "1. Introduction: A Low Level of Exploitation", intro: "The mineral wealth of Cameroon is characterised as follows:",
      items: [["A rich subsoil:", "Cameroon has oil, gas, iron ore, bauxite, cobalt, nickel, gold, diamonds, limestone and other minerals. Some deposits are among the largest in Africa.", "cmr_minerals_big.png", "the minerals of Cameroon"],
        ["Little exploitation:", "Apart from oil, gas and limestone, most deposits are not yet mined on a large scale. Large deposits such as the bauxite of Minim-Martap remain in the ground."],
        ["Little local processing:", "Most minerals, like crude oil, are exported without much processing. Cameroon therefore earns little from them and creates few industrial jobs."]] },
    { title: '2. Types, Distribution, Quality and Quantity', sub: 'A) Energy Resources', intro: 'The energy resources of Cameroon are the following:',
      items: [['Crude oil:', 'Oil is extracted mainly offshore in the Rio del Rey basin and in the Douala and Kribi-Campo basins. Production has fallen from about 180,000 barrels a day in 1985 to about 60,000 today.', 'usa_offshore.jpg', 'an offshore platform'],
        ['Natural gas:', 'Gas from Logbaba near Douala and from offshore Kribi supplies factories and the Kribi power plant. Since 2018, it has also been exported as liquefied gas.'],
        ['Hydroelectricity:', 'The rivers provide most of the electricity of Cameroon, from dams such as Song Loulou, Edéa, Lagdo, Memve\'ele and Nachtigal. The potential is very large but only partly used.'],
        ['Fuelwood and solar energy:', 'Fuelwood remains the main energy of households, especially in villages. Solar energy is growing in the north, and thermal power plants complete the supply when rivers are low.']] },
    { title: "2. Types, Distribution, Quality and Quantity", sub: "B) Metallic Minerals", intro: "The main metallic minerals are the following:",
      items: [["Iron ore:", "Large deposits are found at Mbalam in the East, at Nkout in the South and near Kribi. Some of them are of good quality."],
        ["Bauxite:", "Large reserves are found at Minim-Martap and Ngaoundal in the Adamawa and at Fongo-Tongo in the West. They are still not mined.", "lsa_bauxite.jpg", "bauxite"],
        ["Cobalt and nickel:", "Cobalt, nickel and manganese are found at Nkamouna near Lomié in the East. These metals are in high demand for batteries."],
        ["Gold and diamonds:", "Gold and diamonds are found mainly in the East, at Bétaré-Oya, Batouri and Mobilong. They are mostly mined by hand."]] },
    { title: "2. Types, Distribution, Quality and Quantity", sub: "C) Industrial and Other Minerals", intro: "Cameroon also has the following industrial and other minerals:",
      items: [["Limestone:", "Limestone at Figuil in the North is used to make cement. It is one of the few minerals mined for local use."],
        ["Marble:", "Marble is found at Bidzar in the Far North. It is used for building and decoration."],
        ["Rutile and uranium:", "Rutile is found at Akonolinga and uranium at Poli and Lolodorf. They are not yet mined."]] },
    { title: "3. Methods of Exploitation and Stakeholders", sub: "A) Methods", intro: "Minerals are exploited by the following methods:",
      items: [["Industrial mining:", "Oil and gas are extracted by offshore drilling, and limestone and marble are quarried. Open-pit mining is planned for iron ore and bauxite.", "usa_openpit.jpg", "an open-pit mine"],
        ["Artisanal mining:", "Gold and diamonds are dug and washed by hand, often informally, by thousands of miners. This work is dangerous and pollutes rivers.", "usa_goldminers.jpg", "artisanal gold miners"]] },
    { title: "3. Methods of Exploitation and Stakeholders", sub: "B) Stakeholders", intro: "The following stakeholders take part in mining:",
      items: [["The state:", "The Ministry of Mines, the SNH for hydrocarbons and SONAMINES, the national mining company, grant permits and collect revenue. The state is also a partner in some projects."],
        ["Companies:", "Multinational and national companies bring capital and technology. They build the mines and sell the minerals."],
        ["Local communities:", "Local communities provide land and labour for the mines. They should receive compensation and a share of the benefits."]] },
    { title: '4. Uses of the Minerals', intro: 'Minerals are used in the following ways:',
      items: [['Oil and gas:', 'Crude oil was refined into fuels at SONARA in Limbe and is mostly exported. Gas is used to produce electricity, as a fuel for industries and for export.'],
        ['Limestone:', 'Limestone is used to make cement at Figuil and in other plants. Cement is essential for building houses, roads and dams.'],
        ['Bauxite and iron ore:', 'Bauxite is the raw material of aluminium, and iron ore of steel. ALUCAM at Edéa makes aluminium, but it uses imported alumina.'],
        ['Gold and diamonds:', 'Gold and diamonds are used for jewellery and as a form of savings. They bring income to miners and traders in the East.']] },
    { title: "5. Problems and Recent State Efforts", sub: "A) Problems Hindering Exploitation", intro: "The exploitation of minerals faces the following problems:",
      items: [["Lack of infrastructure:", "Railways, ports, roads and electricity are lacking near most deposits. Minerals such as iron ore cannot be exported without a railway to the coast."],
        ["High investment costs:", "Large mines need billions of francs, which must often come from foreign investors. When world prices fall, investors abandon projects."],
        ["Poor geological knowledge:", "Many areas of the country are not yet fully surveyed. The size and quality of many deposits are therefore unknown."],
        ["Poor governance:", "Slow procedures, corruption and conflicts with local communities discourage investors. Projects are therefore delayed for years."]] },
    { title: '5. Problems and Recent State Efforts', sub: 'B) Recent State Efforts', intro: 'The state has taken the following measures:',
      items: [['A new Mining Code:', 'The Mining Code of 2016, revised in 2023, aims to attract investors and increase the benefits for Cameroon. It also protects local communities and the environment.'],
        ['Infrastructure:', 'The state has built the Kribi deep-sea port and the Lom Pangar and Nachtigal dams, and plans mining railways. These will supply the energy and transport needed by mines.', 'lsa_nachtigal.jpg', 'the Nachtigal dam'],
        ['New institutions:', 'SONAMINES was created in 2020 to manage the interests of the state in mining. The state also organises artisanal miners so that their activity becomes legal and safer.'],
        ['Partnerships:', 'Agreements are signed with foreign companies to develop the iron ore and bauxite deposits. The state takes shares in these projects.']] },
    { title: "6. Benefits and Sustainable Exploitation", sub: "A) Benefits", intro: "The exploitation of minerals brings the following benefits:",
      items: [["State revenue:", "Oil and gas provide a large part of the revenue of the state. This money pays for roads, schools and hospitals."],
        ["Jobs:", "Mines, quarries and oil companies create jobs for local people. Small businesses also grow around the mining sites."],
        ["Raw materials for industry:", "Minerals supply raw materials to industries such as cement, aluminium and steel. These industries create more wealth in the country."],
        ["New infrastructure:", "Mining projects bring new roads, railways and services to remote areas. These also serve the local people."]] },
    { title: '6. Benefits and Sustainable Exploitation', sub: 'B) Measures for Sustainable Exploitation', intro: 'Minerals are exploited sustainably by the following measures:',
      items: [['Environmental impact assessments:', 'Before starting, every project must study its effects on the environment and propose ways to reduce them. The government must approve this study.'],
        ['Land restoration:', 'Companies must fill the pits and replant the land after mining. This allows the land to be used again for farming or forest.'],
        ['Community development:', 'Part of the mining revenue must go to the affected communities for schools, water and health. The local people then benefit from the minerals of their land.'],
        ['Transparency:', 'Cameroon belongs to the Extractive Industries Transparency Initiative (EITI), which publishes mining payments. This makes it harder to misuse mining revenue.']] },
  ],
  evaluation: [['Name two minerals of the East Region and their location.', 'Iron ore at Mbalam and gold at Bétaré-Oya (also cobalt-nickel at Lomié).'], ['Give two problems that hinder mineral exploitation in Cameroon.', 'Lack of infrastructure and high investment costs.']],
  remediation: ['The company that refines oil at Limbe is ______.', 'Limestone for cement is quarried at ______ in the North.', 'Small-scale mining with simple tools is ______ mining.'],
  remediationAnswers: '1. SONARA 2. Figuil 3. artisanal',
  homework: 'Name the dam built on the Benue.',
  hwAnswer: 'The Lagdo dam.',
  bilingual: [['Mineral', 'Le minerai / le minéral'], ['Mine', 'La mine'], ['Oil', 'Le pétrole'], ['Gas', 'Le gaz'], ['Iron ore', 'Le minerai de fer'], ['Bauxite', 'La bauxite'], ['Gold', "L'or"], ['Quarry', 'La carrière']],
});

module.exports = { B, L };
