// LOWER SIXTH ARTS — Geography of Cameroon, lessons 11–15 (water, industry, transport, tourism, regional contrasts)
// Syllabus 2019: M6 FS4, FS5, FS6, FS7; M7 FS1. Guided by the teacher's course notes (LSA/USA_CAM_GEO_2026).
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const B = { level: 'LSA', code: 'CAM', folder: 'Geography of Cameroon', module: 'Geography of Cameroon', topicDefault: 'Geography of Cameroon', branch: 'Economic Activities and Development of Cameroon',
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Geography of Cameroon.', 'Teacher\'s course notes: Mr KAMDEM E., Cameroon Geography (LSA and USA), GBHS Garoua, 2026.', 'INS, Fourth Cameroon Household Survey (ECAM 4), 2014.'] };
const L = [];

L.push({ no: 11, title: 'Management of Water Resources in Cameroon', subtopic: 'Economic Activities and Development of Cameroon',
  notions: 'Water resources, fishing, aquaculture, irrigation scheme, flood-retreat cultivation, navigation, hydroelectric power, water supply.',
  focus: 'Distribution of water bodies and their resources; use for fishing (modern and traditional), agriculture (irrigation schemes and flood-retreat cultivation), transport, water supply, sand extraction and hydroelectric power; problems, solutions and impacts.',
  competence: 'Learners are able to describe the uses of the water resources of Cameroon and propose solutions to the problems of their management.',
  objectives: ['Describe the distribution of water bodies and their resources.', 'Explain the use of water for fishing and agriculture, with their problems and solutions.', 'Explain the use of water for transport, water supply and other uses.', 'Describe the hydroelectric sites, their problems and solutions.'],
  recall: ['The Lagdo dam is on the Benue.', 'The Sanaga has the largest dams of Cameroon.', 'SEMRY grows rice with water from the Logone.'],
  situation: 'Hamadou visits his uncle, a fisherman on the Lagdo reservoir. The uncle complains that his catches are smaller and that the water level is low, which reduces the water in his irrigation channels. That evening the electricity goes off, and a neighbour says: "It is the low water at the dam again." Hamadou asks: "How is one lake used for so many things, and how can we manage it better?"',
  sitQA: [['What is the problem in the situation?', 'The Lagdo reservoir serves many uses, and low water affects them all; Hamadou wants to know how to manage it better.'],
    ['Name three uses of the Lagdo reservoir in the situation.', 'Fishing, irrigation and electricity.'],
    ['Why does the electricity go off?', 'The water level at the dam is low, so less electricity is produced.']],
  justification: 'This lesson helps us to understand the value of water resources for food, energy and transport, and the need to manage them carefully.',
  action: 'Save water and electricity, and protect rivers and lakes from pollution.',
  activities: [
    { sec: '1. DISTRIBUTION', img: 'cmr_water_big.png', caption: 'Water resources of Cameroon.', q: 'Name one large irrigation scheme of the Far North.', a: 'SEMRY (rice, near Yagoua and Maga).', noProj: 'mark dams and schemes on a sketch map.' },
    { sec: '2. FISHING', img: 'f2t_fishing.jpg', caption: 'Fishermen in canoes.', q: 'What is the difference between artisanal and industrial fishing?', a: 'Artisanal fishing uses canoes and nets; industrial fishing uses large motorised trawlers.', noProj: 'describe fishing on the Lagdo lake.' },
    { sec: '3. AGRICULTURE', img: 'f4_ricefield.jpg', caption: 'An irrigated rice field.', q: 'Why is irrigation important in the North?', a: 'It allows farming during the long dry season.', noProj: 'describe irrigated onion fields.' },
    { sec: '4. TRANSPORT AND OTHER USES', img: 'lsa_wouri.jpg', caption: 'The Wouri estuary.', q: 'Why is the Wouri estuary important for Cameroon?', a: 'It gives access to the port of Douala, the main port of the country.', noProj: 'show Douala on a map.' },
    { sec: '5. HYDROELECTRIC POWER', img: 'f2t_lagdo.jpg', caption: 'The Lagdo dam.', q: 'Which regions receive electricity from the Lagdo dam?', a: 'The North, the Far North and the Adamawa.', noProj: 'list the dams of Cameroon.' },
  ],
  summary: [
    D([['Water resources:', 'They are the water bodies of a country (sea, rivers, lakes, underground water) and what they provide.'],
      ['Irrigation:', 'It is the artificial supply of water to crops.'],
      ['Flood-retreat cultivation:', 'It is farming on land left moist when river floods go down.'],
      ['Aquaculture:', 'It is the rearing of fish in ponds or cages.']]),
    { title: '1. Distribution of Water Bodies and Their Resources', intro: 'The water bodies of Cameroon and their resources are the following:',
      items: [['The sea:', 'The Atlantic coast (about 400 km) provides fish, shrimps, oil and gas, ports and beaches.', 'cmr_water_big.png', 'water resources of Cameroon'],
        ['Rivers:', 'The Sanaga, Wouri, Nyong, Ntem, Benue and Logone provide water, fish, energy, transport and sand.'],
        ['Lakes:', 'Lake Chad, crater lakes (Barombi Mbo, Nyos, Ossa) and reservoirs (Lagdo, Maga, Mbakaou, Lom Pangar).'],
        ['Underground water:', 'Aquifers supply boreholes and wells, especially in the north in the dry season.']] },
    { title: '2. Use for Fishing', sub: 'A) Methods of Fishing', intro: 'Fishing is carried out by the following methods:',
      items: [['Modern large-scale fishing:', 'Motorised trawlers from Douala, Limbe and Kribi catch fish and shrimps at sea.', 'usa_fishing.jpg', 'a fishing boat'],
        ['Traditional small-scale fishing:', 'Canoes, nets, lines and traps are used on rivers, lakes and along the coast; it supplies most of the fish eaten locally.', 'f2t_fishing.jpg', 'artisanal fishing'],
        ['Main inland fisheries:', 'Lake Chad, the Lagdo and Maga reservoirs and the Logone floodplains.'],
        ['Aquaculture:', 'Fish farms and ponds are developing, especially in the Centre and West.']] },
    { title: '2. Use for Fishing', sub: 'B) Problems, Solutions and Impacts', intro: 'The problems, solutions and impacts of fishing are the following:',
      items: [['Problems:', 'Overfishing, illegal nets, pollution, shrinking of Lake Chad, poor conservation and storage of fish.'],
        ['Solutions:', 'Fishing rules (net size, closed seasons), control by MINEPIA, cold storage and aquaculture.'],
        ['Socio-economic impacts:', 'Jobs, cheap protein and income for fishermen and fish sellers.'],
        ['Environmental impacts:', 'Loss of fish stocks and destruction of mangroves for fish smoking.']] },
    { title: '3. Use for Agriculture', intro: 'Water is used for agriculture as follows:',
      items: [['SEMRY:', 'Large irrigated rice schemes on the Logone near Yagoua and Maga (Far North).', 'f4_ricefield.jpg', 'an irrigated rice field'],
        ['Lagdo:', 'Irrigated rice and other crops around the Lagdo reservoir on the Benue.'],
        ['UNVDA:', 'Irrigated rice in the Ndop plain (North-West).'],
        ['Flood-retreat cultivation:', 'Farmers grow dry-season sorghum (muskwari), maize and vegetables on moist land left by the floods of the Logone and the Benue.'],
        ['Benefits and problems:', 'More food and dry-season jobs, but high costs, silting of canals, waterlogging, salinity and conflicts over water.']] },
    { title: '4. Use for Transport and Other Purposes', intro: 'Water is used for transport and other purposes as follows:',
      items: [['Sea transport:', 'The ports of Douala, Kribi (deep-sea port) and Limbe handle almost all foreign trade.', 'lsa_wouri.jpg', 'the Wouri estuary'],
        ['River transport:', 'The Benue is navigable to Garoua only from about August to October, and the Sangha is used in the south-east.'],
        ['Water supply:', 'CAMWATER treats river and underground water for towns (Douala, Yaoundé, Garoua).'],
        ['Sand extraction:', 'Sand is dredged from the Wouri, the Sanaga and the Benue for building.']] },
    { title: '5. Use for Hydroelectric Power', intro: 'The hydroelectric sites, their problems and solutions are the following:',
      items: [['Southern sites:', 'Song Loulou and Edéa on the Sanaga, Nachtigal (420 MW) and Memve\'ele on the Ntem supply the southern grid (Littoral, Centre, South, West, East).', 'lsa_nachtigal.jpg', 'the Nachtigal site'],
        ['Northern site:', 'The Lagdo dam (72 MW) supplies the North, the Far North and the Adamawa.', 'f2t_lagdo.jpg', 'the Lagdo dam'],
        ['Regulating dams:', 'Lom Pangar, Mbakaou, Bamendjin and Mapé store water to keep the Sanaga flowing in the dry season.'],
        ['Problems:', 'Low water in the dry season, silting, weeds, old equipment and weak grids cause power cuts (load shedding).'],
        ['Solutions:', 'New dams, dredging, protection of catchments, linking the northern and southern grids and developing solar energy.']] },
  ],
  evaluation: [['Name two irrigation schemes of Cameroon.', 'SEMRY (Logone) and UNVDA (Ndop); also Lagdo.'], ['Give two problems of hydroelectric production and one solution.', 'Low water in the dry season and silting; building regulating dams (or dredging).']],
  remediation: ['Farming on moist land left by floods is ______ cultivation.', 'The dam that supplies the north is ______.', 'The state company that supplies drinking water is ______.'],
  remediationAnswers: '1. flood-retreat 2. Lagdo 3. CAMWATER',
  homework: 'Name one factory in Garoua and what it produces.',
  hwAnswer: 'CICAM makes cotton cloth (textiles); SODECOTON gins cotton and makes cotton-seed oil; the SABC brews drinks.',
  bilingual: [['Water resources', 'Les ressources en eau'], ['Fishing', 'La pêche'], ['Irrigation', "L'irrigation"], ['Dam', 'Le barrage'], ['Reservoir', 'La retenue'], ['Navigation', 'La navigation'], ['Power cut', "La coupure d'électricité"], ['Drinking water', "L'eau potable"]],
});

L.push({ no: 12, title: 'Industrial Development and Change in Cameroon', subtopic: 'Economic Activities and Development of Cameroon',
  notions: 'Manufacturing industry, light industry, import substitution, raw-material oriented industry, industrial region, locational factors.',
  focus: 'Characteristics of manufacturing industries; the main industrial regions (Coastal, Centre-South, Western, Northern) and their types of industries; locational and growth factors; reasons for the low level of industrialisation; efforts of the state; socio-economic impacts.',
  competence: 'Learners are able to describe the industrial regions of Cameroon, explain their location and propose ways to develop industry.',
  objectives: ['Describe the characteristics of manufacturing industries in Cameroon.', 'Describe the four industrial regions and explain their pattern.', 'Explain the reasons for the low level of industrialisation.', 'Describe the efforts of the state and the impacts of industrialisation.'],
  recall: ['CICAM makes cloth in Garoua.', 'Douala is the main port of Cameroon.', 'Industries transform raw materials into finished goods.'],
  situation: 'Issa drinks a bottle of juice made by the SABC in Douala, and his new school uniform is made of cloth from CICAM in Garoua. He asks his friend: "Why is my drink made far away in Douala while our cloth is made here, and why are there so few big factories in Garoua?"',
  sitQA: [['What is the problem in the situation?', 'Issa wants to understand the location of industries and the low industrialisation of the north.'],
    ['Where is the cloth of the uniform made?', 'At CICAM in Garoua.'],
    ['Why is cloth made in Garoua?', 'Garoua is in the main cotton-growing region (raw material).']],
  justification: 'This lesson helps us to understand the industries of Cameroon, their location and their role in development.',
  action: 'Buy products made in Cameroon and develop skills useful to industry.',
  activities: [
    { sec: '1. CHARACTERISTICS', img: 'f2t_textile_factory.jpg', caption: 'A textile factory.', q: 'What raw material does a textile factory in Garoua use?', a: 'Cotton.', noProj: 'show a piece of cotton cloth.' },
    { sec: '2. INDUSTRIAL REGIONS', img: 'cmr_industry_big.png', caption: 'Industrial regions of Cameroon.', q: 'Which region has the most industries?', a: 'The Coastal region, around Douala, Edéa and Limbe.', noProj: 'mark industrial towns on a sketch map.' },
    { sec: '2. INDUSTRIAL REGIONS', img: 'f2t_aluminium.jpg', caption: 'An aluminium smelter.', q: 'Why was the aluminium smelter built at Edéa?', a: 'Because of the cheap electricity from the Edéa dam and the nearby port of Douala.', noProj: 'name the Sanaga dams.' },
    { sec: '3. LOW LEVEL OF INDUSTRIALISATION', img: 'usa_carfactory.jpg', caption: 'A modern factory.', q: 'Give one reason why Cameroon has few heavy industries.', a: 'Lack of capital (also technology, energy or a large market).', noProj: 'discuss imported goods in the market.' },
    { sec: '4. IMPACTS', img: 'f2t_factory_workers.jpg', caption: 'Factory workers.', q: 'Give one positive impact of industries on a town.', a: 'They create jobs (and attract services).', noProj: 'list jobs in factories of Garoua.' },
  ],
  summary: [
    D([['Manufacturing industry:', 'It is the transformation of raw materials into finished or semi-finished goods in factories.'],
      ['Light industry:', 'It produces consumer goods with little raw material and capital (food, drinks, textiles, soap).'],
      ['Import substitution:', 'It is producing locally goods that were formerly imported.'],
      ['Industrial region:', 'It is an area where many industries are concentrated.']]),
    { title: '1. Characteristics of Manufacturing Industries', intro: 'The manufacturing industries of Cameroon have the following characteristics:',
      items: [['Low level:', 'Manufacturing is small and provides only about a sixth of national production.', 'f2t_textile_factory.jpg', 'a textile factory'],
        ['Light industries:', 'Most factories make food, drinks, textiles, soap, wood products and cement.'],
        ['Import substitution:', 'Many were created to replace imports (cement, sugar, cloth, drinks).'],
        ['Raw-material oriented:', 'Many are located near their raw materials: ginneries near cotton farms, sawmills near forests.'],
        ['Concentration:', 'Most are concentrated in Douala and Yaoundé.']] },
    { title: '2. The Main Industrial Regions', sub: 'A) The Coastal Region', intro: 'The industries and location factors of the Coastal region are the following:',
      items: [['Towns and industries:', 'Douala (drinks, food, chocolate, soap, cement, metal works), Edéa (ALUCAM aluminium), Limbe (SONARA oil refinery) and Kribi (industrial port zone).', 'cmr_industry_big.png', 'industrial regions of Cameroon'],
        ['Location factors:', 'The port of Douala, cheap electricity from Edéa and Song Loulou, a large market, skilled labour, banks and good transport.', 'f2t_aluminium.jpg', 'an aluminium smelter']] },
    { title: '2. The Main Industrial Regions', sub: 'B) The Centre-South Region', intro: 'The industries and location factors of the Centre-South region are the following:',
      items: [['Towns and industries:', 'Yaoundé (drinks, printing, food, building materials), Mbalmayo (wood) and Mbandjock–Nkoteng (sugar of SOSUCAM).'],
        ['Location factors:', 'The political capital and its large market, forest timber, the railway and nearby electricity.']] },
    { title: '2. The Main Industrial Regions', sub: 'C) The Western Region', intro: 'The industries and location factors of the Western region are the following:',
      items: [['Towns and industries:', 'Bafoussam, Bamenda and Dschang: coffee and tea processing, food processing, drinks and crafts.'],
        ['Location factors:', 'Rich farming areas supplying raw materials and a dense population giving labour and markets.']] },
    { title: '2. The Main Industrial Regions', sub: 'D) The Northern Region', intro: 'The industries and location factors of the Northern region are the following:',
      items: [['Towns and industries:', 'Garoua (CICAM cloth, SODECOTON cotton and oil, a brewery), Figuil (cement), Maroua (leather) and Ngaoundéré (meat and milk).', 'f2t_textile_factory.jpg', 'textile production'],
        ['Location factors:', 'Raw materials (cotton, limestone, cattle, hides and skins), electricity from Lagdo and the market of the northern regions and Chad.']] },
    { title: '3. Reasons for the Low Level of Industrialisation', intro: 'Industry remains weak for the following reasons:',
      items: [['Lack of capital:', 'Few local investors and costly loans.'],
        ['Energy and infrastructure:', 'Power cuts, bad roads and limited railways raise costs.'],
        ['Technology and skills:', 'Old machines and a shortage of engineers and technicians.'],
        ['Small market:', 'Low incomes and strong competition from imported goods.'],
        ['Administrative problems:', 'Slow procedures, taxes and corruption discourage investors.']] },
    { title: '4. Efforts of the State', intro: 'The state has taken the following measures to develop industry:',
      items: [['Infrastructure:', 'New dams (Lom Pangar, Nachtigal, Memve\'ele), the Kribi deep-sea port and roads.'],
        ['Investment incentives:', 'The law on private investment (2013) gives tax advantages to new industries.'],
        ['Industrial zones:', 'MAGZI prepares industrial zones with water, electricity and roads.'],
        ['Import-substitution plans:', 'Programmes encourage local processing of rice, maize, milk, fish and cotton.']] },
    { title: '5. Socio-Economic Impacts of Industrialisation', intro: 'Industrialisation has the following impacts:',
      items: [['Positive impacts:', 'Jobs, national income, local goods, growth of towns and markets for farmers.', 'f2t_factory_workers.jpg', 'factory workers'],
        ['Negative impacts:', 'Pollution of air, water and soil, rural exodus, slums around industrial towns and regional inequality.']] },
  ],
  evaluation: [['Name the four industrial regions of Cameroon.', 'The Coastal, Centre-South, Western and Northern regions.'], ['Why is the Coastal region the most industrialised?', 'It has the port of Douala, cheap electricity, a large market and good transport.']],
  remediation: ['The aluminium smelter of Edéa is ______.', 'Producing locally goods that were imported is import ______.', 'The oil refinery of Limbe is ______.'],
  remediationAnswers: '1. ALUCAM 2. substitution 3. SONARA',
  homework: 'Name the two end towns of the Transcam railway.',
  hwAnswer: 'Douala and Ngaoundéré (through Yaoundé).',
  bilingual: [['Industry', "L'industrie"], ['Factory', "L'usine"], ['Raw material', 'La matière première'], ['Import substitution', 'La substitution aux importations'], ['Industrial zone', 'La zone industrielle'], ['Refinery', 'La raffinerie'], ['Brewery', 'La brasserie'], ['Investment', "L'investissement"]],
});

L.push({ no: 13, title: 'Transport Development in Cameroon', subtopic: 'Economic Activities and Development of Cameroon',
  notions: 'Transport network, road, railway, port, airport, corridor, spatial pattern, transit.',
  focus: 'The different route networks: description and explanation of their spatial pattern; problems of transport development; efforts to improve transport.',
  competence: 'Learners are able to describe the transport networks of Cameroon, explain their pattern and propose ways to improve them.',
  objectives: ['Describe the road, rail, air and water networks of Cameroon.', 'Explain the spatial pattern of the transport network.', 'Explain the problems of transport development.', 'Describe the efforts to improve transport.'],
  recall: ['The railway ends at Ngaoundéré.', 'Douala is the main port.', 'Garoua has an international airport.'],
  situation: 'Moussa drives a lorry of cotton from Garoua to the south. Near Ngaoundéré a tyre bursts in a huge pothole, and while he waits he sees the Camrail freight train pass smoothly towards Douala. He says: "If only the roads were better, or the train came to Garoua!" His son asks: "Why is transport so difficult in Cameroon, and what is being done to improve it?"',
  sitQA: [['What is the problem in the situation?', 'Transport is slow and costly because of bad roads and the limited railway.'],
    ['Where does the railway end in the north?', 'At Ngaoundéré.'],
    ['Why is a bad road costly for Moussa?', 'It damages the lorry and wastes time and money.']],
  justification: 'This lesson helps us to understand the role of transport in trade, national unity and development.',
  action: 'Respect traffic rules and protect roads and public transport equipment.',
  activities: [
    { sec: '1. ROUTE NETWORKS', img: 'cmr_transport_big.png', caption: 'The transport network of Cameroon.', q: 'Which towns are linked by the Transcam railway?', a: 'Douala, Yaoundé and Ngaoundéré.', noProj: 'draw the railway on a sketch map.' },
    { sec: '1. ROUTE NETWORKS', img: 'f2t_train.jpg', caption: 'A train.', q: 'Which goods does the railway carry from the north to Douala?', a: 'Cotton, cattle and goods for Chad and the Central African Republic.', noProj: 'list goods at the railway station.' },
    { sec: '1. ROUTE NETWORKS', img: 'usa_container.jpg', caption: 'A container port.', q: 'Why was the deep-sea port of Kribi built?', a: 'To receive very large ships that cannot enter Douala.', noProj: 'compare Douala and Kribi.' },
    { sec: '2. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A damaged road.', q: 'Give one problem of roads in Cameroon.', a: 'Many roads are unpaved or full of potholes.', noProj: 'describe roads around Garoua.' },
    { sec: '3. EFFORTS', img: 'f5_motorway.jpg', caption: 'A motorway.', q: 'Which motorway is being built between the two largest towns?', a: 'The Yaoundé–Douala motorway.', noProj: 'name new roads of the region.' },
  ],
  summary: [
    D([['Transport network:', 'It is the set of routes (roads, railways, air routes, waterways) that link places.'],
      ['Spatial pattern:', 'It is the arrangement of the network on the map.'],
      ['Corridor:', 'It is a main transport route used to carry goods between a port and inland areas or countries.']]),
    { title: '1. The Route Networks and Their Spatial Pattern', sub: 'A) The Road Network', intro: 'The road network has the following characteristics:',
      items: [['Importance:', 'Roads carry most passengers and goods in Cameroon.', 'cmr_transport_big.png', 'the transport network of Cameroon'],
        ['Radial pattern:', 'Main roads radiate from Douala and Yaoundé to the regional capitals.'],
        ['Dense south, sparse north and east:', 'The network is densest in the south and west; the north depends mainly on the N1 (Ngaoundéré–Garoua–Maroua–Kousseri).'],
        ['Paved and unpaved roads:', 'Only a small part of the network is paved; most rural roads are earth roads.'],
        ['Corridors:', 'Douala–N\'Djamena and Douala–Bangui carry transit goods for Chad and the Central African Republic.']] },
    { title: '1. The Route Networks and Their Spatial Pattern', sub: 'B) The Rail Network', intro: 'The rail network has the following characteristics:',
      items: [['Linear pattern:', 'The Transcam railway runs from Douala to Yaoundé (Transcam I) and from Yaoundé to Ngaoundéré (Transcam II), with a branch to Kumba.', 'f2t_train.jpg', 'a train'],
        ['Operator:', 'It is operated by Camrail.'],
        ['Role:', 'It carries heavy goods (timber, cotton, cattle, fuel, cement) and transit goods for Chad and the Central African Republic from the Ngaoundéré railhead.'],
        ['Limits:', 'The north (Garoua, Maroua), the west and the east are not served.']] },
    { title: '1. The Route Networks and Their Spatial Pattern', sub: 'C) The Air Network', intro: 'The air network has the following characteristics:',
      items: [['International airports:', 'Douala (the busiest), Yaoundé-Nsimalen and Garoua.', 'usa_airport.jpg', 'an airport'],
        ['Domestic airports:', 'Maroua-Salak, Ngaoundéré, Bertoua, Bamenda and others.'],
        ['Role:', 'Fast travel for business, administration and tourism, especially between the south and the north.']] },
    { title: '1. The Route Networks and Their Spatial Pattern', sub: 'D) The Water Network', intro: 'The water network has the following characteristics:',
      items: [['Sea ports:', 'Douala (the main port), Kribi (deep-sea port opened in 2018), Limbe and Tiko.', 'usa_container.jpg', 'a container port'],
        ['River transport:', 'The Benue (to Garoua in the rainy season), the Sangha and the lower Sanaga and Nyong are used locally.'],
        ['Role:', 'The ports handle almost all the foreign trade of Cameroon and part of that of Chad and the Central African Republic.']] },
    { title: '2. Problems of Transport Development', intro: 'Transport development faces the following problems:',
      items: [['Poor infrastructure:', 'Unpaved roads, potholes and old bridges cause accidents and delays.', 'f2t_muddy_road.jpg', 'a damaged road'],
        ['Lack of funds:', 'Building and maintaining roads and railways is very costly.'],
        ['Physical problems:', 'Heavy rain, steep slopes and dense forest in the south; floods and sand in the north.'],
        ['Incomplete networks:', 'The railway does not reach the north, and many regions remain isolated.'],
        ['Old equipment and congestion:', 'Old trains, congestion at the port of Douala and road checkpoints slow traffic.'],
        ['Insecurity:', 'Road bandits (coupeurs de route) and conflicts make some roads unsafe.']] },
    { title: '3. Efforts to Improve Transport Development', intro: 'The following efforts are made to improve transport:',
      items: [['Roads:', 'Paving of major roads, the Yaoundé–Douala motorway, the Kribi–Lolabé motorway and the Bamenda–Enugu road to Nigeria.', 'f5_motorway.jpg', 'a motorway'],
        ['Ports:', 'The Kribi deep-sea port and the modernisation of the port of Douala.'],
        ['Railway:', 'Rehabilitation of the Transcam line and new trains, with plans to extend the railway.'],
        ['Airports and bridges:', 'Modernised airports and the second bridge over the Wouri in Douala.'],
        ['Partnerships:', 'Public-private partnerships to finance and manage infrastructure.']] },
  ],
  evaluation: [['Describe the spatial pattern of the road network of Cameroon.', 'Radial from Douala and Yaoundé, dense in the south and west, sparse in the north and east.'], ['Give two problems of transport and one effort to solve them.', 'Bad roads and lack of funds; building motorways (or the Kribi port).']],
  remediation: ['The company that operates the railway is ______.', 'The deep-sea port opened in 2018 is at ______.', 'The railway ends in the north at ______.'],
  remediationAnswers: '1. Camrail 2. Kribi 3. Ngaoundéré',
  homework: 'Name two national parks of the North Region.',
  hwAnswer: 'The Bénoué, Bouba Ndjida and Faro National Parks.',
  bilingual: [['Road', 'La route'], ['Railway', 'Le chemin de fer'], ['Port', 'Le port'], ['Airport', "L'aéroport"], ['Motorway', "L'autoroute"], ['Pothole', 'Le nid-de-poule'], ['Corridor', 'Le corridor'], ['Transit', 'Le transit']],
});

L.push({ no: 14, title: 'Tourism Development in Cameroon', subtopic: 'Economic Activities and Development of Cameroon',
  notions: 'Tourism, tourist resource, tourist infrastructure, destination, ecotourism, cultural tourism.',
  focus: 'Tourism resources (natural and human) and their distribution and exploitation; tourism infrastructure; sources of tourists and prime destinations; problems; measures to promote tourism; impacts on the economy, communities and environment.',
  competence: 'Learners are able to describe the tourist resources of Cameroon, explain the problems of tourism and propose measures to promote it.',
  objectives: ['Describe the natural and human tourism resources of Cameroon.', 'Describe the tourism infrastructure, sources of tourists and destinations.', 'Explain the problems hindering tourism and the measures to promote it.', 'Assess the impacts of tourism.'],
  recall: ['Cameroon is called "Africa in miniature".', 'The Bénoué National Park is near Garoua.', 'Mount Cameroon is the highest mountain of Cameroon.'],
  situation: 'French tourists arrive at Garoua airport for a safari in the Bénoué National Park. Their guide Oumarou is worried: the road to the park is damaged, and good hotels with electricity and internet are hard to find near the park. The tourists are delighted by the elephants and hippos but find few services. Oumarou asks: "How can Cameroon, so rich in attractions, receive more tourists and benefit more from them?"',
  sitQA: [['What is the problem in the situation?', 'Cameroon has rich attractions, but poor infrastructure limits tourism.'],
    ['What attracted the tourists?', 'The wildlife of the Bénoué National Park (elephants, hippos).'],
    ['What worries the guide?', 'The damaged road and the lack of good hotels.']],
  justification: 'This lesson helps us to know the tourist wealth of Cameroon and the conditions for developing tourism.',
  action: 'Welcome visitors, protect tourist sites and value our cultures.',
  activities: [
    { sec: '1. TOURISM RESOURCES', img: 'cmr_tourism_big.png', caption: 'Tourist sites of Cameroon.', q: 'Name one national park of the Far North.', a: 'The Waza National Park.', noProj: 'mark tourist sites on a sketch map.' },
    { sec: '1. TOURISM RESOURCES', img: 'lsa_mandara.jpg', caption: 'Mountains of the Far North.', q: 'Why do tourists visit Rhumsiki?', a: 'For its volcanic peaks and landscapes in the Mandara Mountains.', noProj: 'describe the Mandara landscapes.' },
    { sec: '1. TOURISM RESOURCES', img: 'usa_bandjoun.jpg', caption: 'A traditional chiefdom.', q: 'Which kind of tourism does this chiefdom attract?', a: 'Cultural tourism.', noProj: 'name palaces and festivals.' },
    { sec: '2. INFRASTRUCTURE AND DESTINATIONS', img: 'usa_hotel.jpg', caption: 'A hotel.', q: 'Why are hotels important for tourism?', a: 'Tourists need safe, comfortable accommodation near the sites.', noProj: 'list hotels of Garoua.' },
    { sec: '3. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A damaged road.', q: 'Give one problem that limits tourism in Cameroon.', a: 'Bad roads (also insecurity and poor marketing).', noProj: 'discuss the road to the Bénoué park.' },
  ],
  summary: [
    D([['Tourism:', 'It is travelling to and staying in places outside one\'s usual environment for leisure, business or other purposes.'],
      ['Tourist resource:', 'It is a natural or human feature that attracts visitors.'],
      ['Tourism infrastructure:', 'It is the set of facilities that serve tourists: roads, airports, hotels, restaurants and guides.'],
      ['Ecotourism:', 'It is tourism in natural areas that protects the environment and benefits local people.']]),
    { title: '1. Tourism Resources', sub: 'A) Natural Resources', intro: 'The natural tourism resources of Cameroon and their distribution are the following:',
      items: [['Wildlife parks:', 'Waza (Far North), Bénoué, Bouba Ndjida and Faro (North), Korup (South-West), Dja and Lobéké (forest zone).', 'cmr_tourism_big.png', 'tourist sites of Cameroon'],
        ['Beaches and coasts:', 'Kribi, with the Lobé Falls that fall into the sea, and Limbe, with black volcanic sand and a botanical garden.', 'usa_limbe.jpg', 'the coast at Limbe'],
        ['Mountains and landscapes:', 'Mount Cameroon (Race of Hope), the Mandara Mountains (Rhumsiki), the Bamenda Highlands (Ring Road) and the Adamawa.', 'lsa_mandara.jpg', 'the Mandara Mountains'],
        ['Lakes and waterfalls:', 'Crater lakes (Barombi Mbo, Nyos, Ossa), the Ekom-Nkam and Menchum Falls and the Lagdo lake.'],
        ['Level of exploitation:', 'Most sites are little exploited because of poor access and few services.']] },
    { title: '1. Tourism Resources', sub: 'B) Human (Cultural) Resources', intro: 'The human tourism resources of Cameroon are the following:',
      items: [['Traditional palaces:', 'The Sultan\'s palace of Foumban, the palaces of the Fons (Bafut) and the lamidats of the north (Garoua, Rey Bouba).', 'usa_bandjoun.jpg', 'a traditional chiefdom'],
        ['Festivals:', 'The Ngondo of the Sawa (Douala), the Nguon of the Bamoun (Foumban) and the Lela of Bali.'],
        ['Historical sites:', 'The slave-trade site of Bimbia, German colonial buildings in Buea and other towns.'],
        ['Crafts and cultures:', 'Over 250 ethnic groups, with crafts, music, dances and cuisine.']] },
    { title: '2. Tourism Infrastructure, Sources and Destinations', intro: 'Tourism infrastructure, sources of tourists and destinations are the following:',
      items: [['Infrastructure:', 'International airports (Douala, Yaoundé, Garoua), hotels concentrated in large towns and a few lodges near parks.', 'usa_hotel.jpg', 'a hotel'],
        ['Organs:', 'The Ministry of Tourism and Leisure (MINTOUL) and regional and local councils promote tourism.'],
        ['Sources of tourists:', 'Mainly Europe (especially France), neighbouring African countries (Nigeria, Chad, Gabon) and North America.'],
        ['Prime destinations:', 'Kribi, Limbe and Buea, the Western Highlands, Waza and the northern parks, and Foumban.']] },
    { title: '3. Problems Hindering Tourism', intro: 'Tourism is hindered by the following problems:',
      items: [['Poor access:', 'Bad roads and few flights to tourist sites.', 'f2t_muddy_road.jpg', 'a damaged road'],
        ['Insecurity:', 'Boko Haram in the Far North and the crisis in the North-West and South-West have closed some sites.'],
        ['Few services:', 'Few good hotels, guides and restaurants outside large towns.'],
        ['Poor promotion:', 'Cameroon is little known on the international market.'],
        ['Poaching and degradation:', 'Poaching and bush fires reduce wildlife in parks.']] },
    { title: '4. Measures to Promote Tourism', intro: 'Tourism can be promoted by the following measures:',
      items: [['By the government:', 'Improve security, roads and airports, train staff, promote "Destination Cameroon" and protect parks.'],
        ['By communities:', 'Develop community-based tourism (village stays, cultural festivals, crafts) and protect sites.'],
        ['By individuals:', 'Guides, hotel owners and drivers offer good, honest services.']] },
    { title: '5. Impacts of Tourism', intro: 'Tourism has the following impacts:',
      items: [['On the economy:', 'Foreign currency, jobs (guides, hotels, transport) and markets for crafts; but dependence on an unstable activity.'],
        ['On local communities:', 'Income and pride in local culture; but rising prices and loss of the meaning of some traditions.'],
        ['On the environment:', 'Money for conservation (ecotourism); but pollution, waste and disturbance of wildlife.']] },
  ],
  evaluation: [['Give two natural and two human tourism resources of Cameroon.', 'Waza National Park and the beaches of Kribi; the Foumban palace and the Ngondo festival.'], ['Give two problems of tourism and one measure to promote it.', 'Bad roads and insecurity; improving security (or roads).']],
  remediation: ['The ministry in charge of tourism is ______.', 'The festival of the Sawa people in Douala is the ______.', 'The waterfall of Kribi that falls into the sea is the ______ Falls.'],
  remediationAnswers: '1. MINTOUL 2. Ngondo 3. Lobé',
  homework: 'Name one region of Cameroon that is more developed and one that is less developed.',
  hwAnswer: 'More developed: the Littoral (Douala) or the Centre (Yaoundé). Less developed: the Far North, the North or the Adamawa.',
  bilingual: [['Tourism', 'Le tourisme'], ['Tourist', 'Le touriste'], ['Hotel', "L'hôtel"], ['National park', 'Le parc national'], ['Festival', 'Le festival'], ['Guide', 'Le guide'], ['Beach', 'La plage'], ['Crafts', "L'artisanat"]],
});

L.push({ no: 15, title: 'Contrasts in Development within Cameroon', subtopic: 'Economic Activities and Development of Cameroon',
  notions: 'Development, regional inequality, core, periphery, backwash effects, spread effects, indicators of development, decentralisation.',
  focus: 'Recall of the models of regional inequality (Friedmann and Myrdal); contrasting regions (case study: Adamawa versus the Coastal lowlands); indicators of differences in development; factors; measures attempted to reduce inequality.',
  competence: 'Learners are able to explain the contrasts in development between regions of Cameroon and assess the measures taken to reduce them.',
  objectives: ['Recall the models of Friedmann and Myrdal.', 'Compare a prosperous region and a lagging region with indicators of development.', 'Explain the factors of the inequality.', 'Assess the measures attempted to reduce regional inequality.'],
  recall: ['Douala is the economic capital of Cameroon.', 'The Adamawa is mainly a cattle-rearing region.', 'Development means improving the living conditions of people.'],
  situation: 'Hamadou, from Garoua, wants to become a software engineer. He discovers that the best courses, the technology companies and fast internet are in Yaoundé and Douala, where his cousin has already found an internship. Hamadou asks: "Why are some regions of Cameroon so much more developed than others, and what can be done about it?"',
  sitQA: [['What is the problem in the situation?', 'Development is unequal between regions, and Hamadou wants to know why and what can be done.'],
    ['Where are the best opportunities?', 'In Yaoundé and Douala.'],
    ['What is this unequal development called?', 'Regional inequality (contrasts in development).']],
  justification: 'This lesson helps us to understand regional inequalities in Cameroon and the policies to reduce them.',
  action: 'Take part in the development of your region and support balanced national development.',
  activities: [
    { sec: '1. MODELS OF REGIONAL INEQUALITY', img: 'core_periphery_big.png', caption: 'A core and its periphery.', q: 'Where do skilled people and capital go in the core-periphery model?', a: 'Towards the core (the most developed region).', noProj: 'draw a core and its periphery.' },
    { sec: '2. CONTRASTING REGIONS', img: 'cmr_contrast_big.png', caption: 'Prosperous and lagging regions.', q: 'Is Douala a prosperous or a lagging region?', a: 'A prosperous region (a core).', noProj: 'mark cores and lagging regions.' },
    { sec: '3. INDICATORS', img: 'cmr_dev_table_big.png', caption: 'Coastal lowlands and Adamawa compared.', q: 'Which region has more schools and hospitals?', a: 'The coastal lowlands (Littoral).', noProj: 'copy the table.' },
    { sec: '4. FACTORS', img: 'lsa_douala.jpg', caption: 'Douala.', q: 'Give one natural advantage of the coastal lowlands.', a: 'Access to the sea (port), also oil and fertile soils.', noProj: 'compare Douala and Ngaoundéré.' },
    { sec: '5. MEASURES', img: 'usa_school.jpg', caption: 'A school.', q: 'How can building schools in lagging regions reduce inequality?', a: 'It trains local people, who can find better jobs and develop their region.', noProj: 'name new universities of the north.' },
  ],
  summary: [
    D([['Development:', 'It is the improvement of the living conditions of people (income, health, education, services).'],
      ['Regional inequality:', 'It is the unequal level of development between regions of a country.'],
      ['Core:', 'It is a prosperous region where population, capital and activities are concentrated.'],
      ['Periphery:', 'It is a less developed region that depends on the core.']]),
    { title: '1. Recall of the Models of Regional Inequality', intro: 'The models of regional inequality are the following:',
      items: [['Myrdal (cumulative causation, 1957):', 'An initial advantage (a port, a capital) attracts investment and grows by a cumulative process.', 'core_periphery_big.png', 'core and periphery'],
        ['Backwash and spread effects:', 'The growing region draws labour, capital and raw materials from poorer regions (backwash), and later some growth spreads to them (spread), but backwash is often stronger.'],
        ['Friedmann (core-periphery, 1966):', 'A dominant core and a dependent periphery; inequality grows in the early stages and may fall later when development spreads.']] },
    { title: '2. The Contrasting Regions: Case Study', intro: 'The case study compares the following two regions:',
      items: [['Prosperous region: the Coastal lowlands:', 'With Douala, Limbe and Kribi, they are the economic heart of Cameroon: port, industries, plantations, oil, services.', 'cmr_contrast_big.png', 'prosperous and lagging regions'],
        ['Lagging region: the Adamawa:', 'A high, landlocked plateau, sparsely populated, living mainly from cattle rearing and farming.', 'lsa_adamawa.jpg', 'the Adamawa Plateau']] },
    { title: '3. Indicators of Differences in Development', intro: 'The indicators of the differences between the two regions are the following:',
      items: [['Income and poverty:', 'Poverty is very low in Douala (about 4 % of people in 2014) but high in the Adamawa (about 47 %).', 'cmr_dev_table_big.png', 'indicators compared'],
        ['Employment:', 'Many formal jobs in industry, the port and services on the coast; mostly farming and herding in the Adamawa.'],
        ['Education:', 'Many schools and universities (Douala, Buea) on the coast; fewer schools and lower school enrolment in the Adamawa.'],
        ['Health:', 'Many hospitals and doctors on the coast; fewer health centres in the Adamawa.'],
        ['Other infrastructure:', 'Paved roads, electricity, water and internet are much better on the coast.']] },
    { title: '4. Factors of the Inequality', intro: 'The inequality is explained by the following factors:',
      items: [['Natural resources and position:', 'The coast has the sea, oil, gas and fertile soils; the Adamawa is landlocked and far from the ports.', 'lsa_douala.jpg', 'Douala'],
        ['Human resources:', 'The coast attracts skilled people and has more educated workers; the Adamawa loses young people (backwash).'],
        ['Historical factors:', 'Colonial rulers invested first on the coast (port, railway, plantations).'],
        ['Government policy and investment:', 'Investment has long been concentrated in Douala and Yaoundé, attracting private investment.']] },
    { title: '5. Measures Attempted to Reduce Inequality', sub: 'A) Political and Administrative Measures', intro: 'Each measure reduces the gap between the rich coast and lagging regions such as the Adamawa and the North in the following way:',
      items: [['Decentralisation:', ['The State transfers powers and money to elected Regional Councils (since 2020) and to councils.', 'It reduces inequality because decisions and money are no longer concentrated in Yaoundé; each region can spend its own budget on its own roads, schools and water points.']],
        ['Regional development agencies (MEADEN in the North, MIDENO and UNVDA in the North-West):', ['These bodies bring projects, technicians and money to regions that private investors neglect.', 'They reduce inequality because they replace the missing private investment and create jobs and income where there were few.']],
        ['Special reconstruction plans (Far North, North-West, South-West):', ['The State rebuilds schools, health centres and roads destroyed by insecurity.', 'They reduce inequality because they stop these regions from falling further behind and allow people to return and work.']]] },
    { title: '5. Measures Attempted to Reduce Inequality', sub: 'B) Socio-Economic Measures', intro: 'Each measure reduces the gap between the rich coast and lagging regions such as the Adamawa and the North in the following way:',
      items: [['Roads and railway (National Road No. 1, Ngaoundéré–Garoua road, railway to Ngaoundéré):', ['Remote regions are connected to markets and to the port of Douala.', 'This reduces inequality because transport becomes cheaper and faster, so farmers and herders sell more at better prices, and firms can settle outside the coast.']],
        ['Electricity and water (Lagdo dam, rural electrification):', ['The North receives electricity and water for irrigation.', 'This reduces inequality because factories, mills and shops can work, and irrigated rice gives farmers a second harvest and more income.']],
        ['Support to agriculture and livestock (SODECOTON, Adamawa livestock projects):', ['Farmers receive seeds, fertiliser and a guaranteed market.', 'This reduces inequality because it raises incomes in rural regions whose economy depends almost only on farming and herding.']],
        ['Universities and hospitals (Ngaoundéré 1993, Maroua 2008, Garoua 2022; regional hospitals):', ['Higher education and health care come closer to the people.', 'This reduces inequality because young people study near home instead of leaving for Douala or Yaoundé, skilled workers stay in their region, and people live healthier and work more.']]] },
    { title: '5. Measures Attempted to Reduce Inequality', sub: 'C) Difficulties and Challenges', intro: 'These measures have only partly reduced inequality for the following reasons:',
      items: [['Limited funding and poor management:', ['The national budget is small, large projects such as roads and dams often depend on foreign loans, and part of the money is misused.', 'As a result, many projects in lagging regions are delayed, badly built or left unfinished.']],
        ['Incomplete decentralisation:', ['Regional and local councils still receive only a small share of the State budget and lack qualified staff.', 'They therefore cannot really plan and finance their own development, and many decisions are still taken in Yaoundé.']],
        ['Insecurity:', ['Boko Haram attacks in the Far North and the crisis in the North-West and South-West have destroyed schools, health centres, markets and roads.', 'Investors and civil servants avoid these regions, and many people have fled, so the gap with the coast has widened.']],
        ["Strong backwash effects:", ["Douala and Yaoundé keep attracting capital, industries and educated young people from the whole country.", "Growth spreads to the periphery much more slowly than resources leave it, as Myrdal's model predicts."]]] },
  ],
  evaluation: [['Distinguish between backwash and spread effects.', 'Backwash effects draw labour and capital from poor regions to the core; spread effects are the growth that spreads from the core to poorer regions.'], ['Give two indicators that show that the coast is more developed than the Adamawa.', 'Lower poverty and more schools and hospitals (also more formal jobs and better roads).']],
  remediation: ['The prosperous region in the core-periphery model is the ______.', 'The model of cumulative causation was proposed by ______.', 'Giving powers to regional and local councils is ______.'],
  remediationAnswers: '1. core 2. Myrdal 3. decentralisation',
  homework: 'List three indicators of development.',
  hwAnswer: 'Examples: income per person, literacy (school enrolment), life expectancy, access to health care, safe water and electricity.',
  bilingual: [['Development', 'Le développement'], ['Regional inequality', "L'inégalité régionale"], ['Core', 'Le centre'], ['Periphery', 'La périphérie'], ['Poverty', 'La pauvreté'], ['Indicator', "L'indicateur"], ['Decentralisation', 'La décentralisation'], ['Infrastructure', "L'infrastructure"]],
});

module.exports = { B, L };
