// LOWER SIXTH ARTS — Geomorphology, part 3: Lessons 9–16 (Denudational Processes on Slopes)
// Rewritten from the teacher's course support (LSA_LESSON_GEOMO_2026) in our own words; facts checked and updated.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const { B } = require('./lsageo_1');
const L = [];
const T = 'Denudational Processes on Slopes';
const W = 'Weathering', M = 'Mass Movements', E = 'Erosion and Depositional Processes and Landforms';

L.push({ no: 9, title: 'Denudation and Weathering', topic: T, subtopic: W,
  notions: 'Denudation, weathering, erosion, mass movement, slope, convex, concave, rectilinear, slope system, mechanical, chemical and biological weathering.',
  focus: 'Meaning of denudation; slopes (types and the slope system); weathering and its types (mechanical, chemical, biological).',
  competence: 'Learners are able to explain how rocks are broken down and how slopes work as systems, using examples from Garoua.',
  objectives: ['Define denudation, weathering and slope.', 'Describe the types of slopes.', 'Explain the slope as an open system.', 'Explain mechanical, chemical and biological weathering.'],
  recall: ['External forces wear down the land.', 'Igneous rocks form from cooled magma.', 'Garoua is very hot in the dry season.'],
  situation: 'In the dry season, you notice that the surface of a large rock in your quarter of Garoua is peeling off in thin layers, like an onion. After the first heavy rains, you see small gullies cut into the slopes of nearby hills, with piles of sand at the bottom. You ask: "What makes hard rock crumble, and where does all the soil that moves down the hills come from?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how rocks break down and how material moves down slopes.'],
    ['What is the general name for the wearing down of the land?', 'Denudation.'],
    ['What breaks the rock before it is moved?', 'Weathering.']],
  justification: 'This lesson explains how landscapes are worn down and how soils form, which matters for farming and building.',
  action: 'Protect slopes with vegetation to limit the removal of weathered material.',
  activities: [
    { sec: '1. DENUDATION', img: 'geo2_denudation.png', caption: 'The three parts of denudation.', q: 'Which part of denudation happens without any movement?', a: 'Weathering.', noProj: 'write the three processes on the board.' },
    { sec: '2. SLOPES', img: 'geo2_slopes.png', caption: 'Three types of slopes.', q: 'Which slope becomes steeper as you go down?', a: 'The convex slope.', noProj: 'draw the three slopes.' },
    { sec: '2. SLOPES', img: 'slope_system_big.png', caption: 'The slope system.', q: 'Give one input of the slope system.', a: 'Rainwater or heat from the Sun.', noProj: 'draw inputs, processes and outputs.' },
    { sec: '3. WEATHERING', img: 'exfoliation.gif', caption: 'Animation: exfoliation.', q: 'Why does a rock peel like an onion in Garoua?', a: 'It expands in the heat of the day and contracts at night, so the outer layers crack.', noProj: 'describe a peeling rock.' },
    { sec: '3. WEATHERING', img: 'f4_roots.jpg', caption: 'Roots in a rock.', q: 'What type of weathering do these roots cause?', a: 'Biological weathering.', noProj: 'find a tree growing in a crack.' },
  ],
  summary: [
    D([['Denudation:', 'It is the general wearing down and lowering of the land surface by weathering, mass movement and erosion.'],
      ['Weathering:', 'It is the breakdown of rocks in place, at or near the surface, without movement.'],
      ['Erosion:', 'It is the wearing away and removal of material by rivers, wind, ice or waves.'],
      ['Slope:', 'It is any inclined surface of the land.']]),
    { title: '1. Denudation', intro: 'Denudation is made up of the following processes:',
      items: [['Weathering:', 'Rocks are broken down in place.', 'geo2_denudation.png', 'the three parts of denudation'],
        ['Mass movement:', 'Weathered material moves down slopes under gravity.'],
        ['Erosion:', 'Rivers, wind, ice and waves carry the material away.', 'f4_gully.jpg', 'a gully']] },
    { title: '2. Slopes', intro: 'Slopes are presented as follows:',
      items: [['Types of slopes:', ['Convex: it becomes steeper downwards.', 'Concave: it becomes gentler downwards.', 'Rectilinear: it keeps a constant angle.']],
        ['Illustration:', 'Most hills combine a convex top, a straight middle and a concave foot.', 'geo2_slopes.png', 'three types of slopes'],
        ['Inputs of the slope system:', 'Heat from the Sun, rainwater and weathered rock enter the system.', 'slope_system_big.png', 'the slope system'],
        ['Processes:', 'Weathering, soil creep and surface runoff act on the slope.'],
        ['Outputs:', 'Soil, rock fragments and water leave the slope, usually into a river.']] },
    { title: '3. Weathering', sub: 'A) Mechanical and Chemical Weathering', intro: 'Mechanical and chemical weathering are presented as follows:',
      items: [['Mechanical (physical) weathering:', 'Rocks break into pieces without changing their chemical composition.'],
        ['Exfoliation:', 'The Sun heats the outer layer of rock by day and it cools at night, so layers crack and peel off; it is the main type around Garoua.', 'exfoliation_last.png', 'exfoliation'],
        ['Frost action:', 'Water in cracks freezes, expands by about 9 % and splits the rock, in cold mountains.'],
        ['Chemical weathering:', 'Chemical reactions change the minerals of rocks and weaken them; it is fastest in hot, wet climates.'],
        ['Chemical processes:', ['Oxidation: iron minerals rust, giving red soils and rocks.', 'Solution: minerals such as rock salt dissolve.', 'Carbonation: rain with carbon dioxide dissolves limestone.']]] },
    { title: '3. Weathering', sub: 'B) Biological Weathering', intro: 'Biological weathering is caused by the following agents:',
      items: [['Plants:', 'Roots grow into cracks and force them apart.', 'f4_roots.jpg', 'roots in a rock'],
        ['Animals:', 'Termites, rodents and worms bring rock fragments to the surface and expose them.'],
        ['Humans:', 'Building, quarrying and farming break up rocks and speed up weathering.'],
        ['Summary:', 'The types of weathering usually act together.', 'geo2_weathering.png', 'types of weathering']] },
  ],
  evaluation: [['Distinguish weathering from erosion.', 'Weathering breaks rocks in place; erosion removes and carries the material away.'],
    ['Explain exfoliation in Garoua.', 'Strong heating by day and cooling at night make the outer layers of rocks expand and contract until they crack and peel off.']],
  remediation: ['Denudation means "to make ______".', 'A slope that becomes gentler downwards is ______.', 'Rusting of iron in rocks is ______.'],
  remediationAnswers: '1. bare 2. concave 3. oxidation',
  homework: 'Name the most important factor of weathering.',
  hwAnswer: 'Climate (temperature and rainfall).',
  bilingual: [['Denudation', 'La dénudation'], ['Weathering', "L'altération"], ['Slope', 'La pente'], ['Erosion', "L'érosion"], ['Rock', 'La roche'], ['Exfoliation', 'La desquamation']],
});

L.push({ no: 10, title: 'Intensity and Factors of Weathering', topic: T, subtopic: W,
  notions: 'Intensity of weathering, climate, Peltier\'s diagram, rock hardness, joints, relief, vegetation, human activities, acid rain.',
  focus: 'Factors of the intensity of weathering: climate (Peltier\'s diagram), geology, relief, vegetation and human activities.',
  competence: 'Learners are able to explain why weathering is faster in some places and apply this to Garoua.',
  objectives: ['Explain the role of climate and read Peltier\'s diagram.', 'Explain the role of rock characteristics.', 'Explain the role of relief.', 'Explain the roles of vegetation and human activities.'],
  recall: ['Weathering can be mechanical, chemical or biological.', 'Chemical weathering is fastest where it is hot and wet.', 'Oxidation gives red soils.'],
  situation: 'In an old quarter of Garoua, you see two stone walls. One was built last year: its stones are sharp and bright. The other, about 100 years old, has rounded, cracked stones covered with green algae, and its surface is crumbly. Both are made of the same local rock. You ask: "Why has the old wall weathered so much, and what controls the speed of weathering?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the factors that control the intensity of weathering.'],
    ['Which process has worn the old wall?', 'Weathering.'],
    ['What is the most important factor of weathering in Garoua?', 'Climate: strong heat and seasonal heavy rain.']],
  justification: 'This lesson helps us to understand the soils and landscapes of our region and to choose durable building materials.',
  action: 'Choose resistant rocks and protect buildings from water to slow down weathering.',
  activities: [
    { sec: '1. CLIMATE', img: 'peltier_big.png', caption: 'Peltier\'s diagram.', q: 'In which climate is chemical weathering strongest?', a: 'In hot, wet climates.', noProj: 'draw the two axes of the diagram.' },
    { sec: '1. CLIMATE', img: 'f2t_laterite.jpg', caption: 'Red laterite.', q: 'Why are soils around Garoua red?', a: 'Iron minerals are oxidised in the hot, seasonally wet climate.', noProj: 'show a handful of red soil.' },
    { sec: '2. ROCK', img: 'f4_karst.jpg', caption: 'Limestone dissolved by water.', q: 'Which weathers faster: limestone or granite?', a: 'Limestone.', noProj: 'drop vinegar on chalk.' },
    { sec: '3. RELIEF', img: 'lsa_scree.jpg', caption: 'Scree on a steep slope.', q: 'Why is fresh rock often exposed on steep slopes?', a: 'Weathered material is quickly washed away.', noProj: 'compare a hill and a plain.' },
    { sec: '4. HUMANS', img: 'lsa_weathered.jpg', caption: 'A weathered stone surface.', q: 'How does acid rain speed up weathering?', a: 'Its acids dissolve and weaken rocks and buildings.', noProj: 'list human activities that expose rock.' },
  ],
  summary: [
    D([['Intensity of weathering:', 'It is the speed and depth at which rocks are broken down.'],
      ['Peltier\'s diagram:', 'It is a graph linking mean annual temperature and rainfall to the dominant type of weathering.'],
      ['Joints:', 'They are natural cracks in rocks that let water in.']]),
    { title: '1. Climate', intro: 'Climate influences weathering as follows:',
      items: [['The most important factor:', 'Temperature and rainfall control both the type and the speed of weathering.', 'peltier_big.png', 'Peltier\'s diagram'],
        ['Temperature:', 'Large daily ranges cause expansion and contraction (exfoliation), and high temperatures speed up chemical reactions.'],
        ['Moisture:', 'Water is necessary for chemical weathering, so rainy areas weather faster.'],
        ['Peltier\'s diagram:', ['Strong chemical weathering in hot, wet climates.', 'Strong frost action in cold, wet climates.', 'Weak weathering in dry areas.']],
        ['Garoua:', 'Its heat and heavy rainy-season showers give strong mechanical and chemical weathering and deep red soils.', 'f2t_laterite.jpg', 'red laterite']] },
    { title: '2. Geology (Rock Characteristics)', intro: 'Rock characteristics influence weathering as follows:',
      items: [['Hardness and minerals:', 'Soft or soluble rocks such as limestone weather faster than hard granite.', 'f4_karst.jpg', 'dissolved limestone'],
        ['Structure:', 'Joints, cracks and layers let water in and speed up weathering.'],
        ['Colour:', 'Dark rocks absorb more heat and expand more.']] },
    { title: '3. Relief, Vegetation and Human Activities', intro: 'Relief, vegetation and human activities influence weathering as follows:',
      items: [['Steep slopes:', 'In the Mandara Mountains, weathered material is washed away quickly, exposing fresh rock.', 'lsa_scree.jpg', 'scree on a slope'],
        ['Gentle slopes and plains:', 'Water stays longer, so chemical weathering forms deep soils.'],
        ['Vegetation:', ['Roots split rocks and increase weathering.', 'A dense plant cover protects rocks from sun and rain and slows weathering.']],
        ['Human activities:', 'Quarries around Garoua, roads and ploughing expose fresh rock, and acid rain from vehicles and industries dissolves rocks.']] },
  ],
  evaluation: [['Why is climate the most important factor of weathering in North Cameroon?', 'Strong heat causes exfoliation and speeds up chemical reactions, while the heavy rains provide water for chemical weathering.'],
    ['How can vegetation both increase and reduce weathering?', 'Roots split rocks, but a dense cover protects rocks from sun and rain.']],
  remediation: ['The diagram linking climate and weathering is by ______.', 'Limestone weathers faster than ______.', 'Acid rain speeds up ______ weathering.'],
  remediationAnswers: '1. Peltier 2. granite 3. chemical',
  homework: 'Define regolith.',
  hwAnswer: 'Regolith is the layer of loose, weathered material covering the solid bedrock.',
  bilingual: [['Weathering', "L'altération"], ['Climate', 'Le climat'], ['Rock', 'La roche'], ['Relief', 'Le relief'], ['Vegetation', 'La végétation'], ['Acid rain', 'Les pluies acides']],
});

L.push({ no: 11, title: 'The Impact of Weathering', topic: T, subtopic: W,
  notions: 'Regolith, soil, humus, construction materials, residual ores, bauxite, inselberg, leaching.',
  focus: 'Products of weathering as a resource (regolith, soil, materials, ores); positive and negative effects of weathering on the landscape and on man.',
  competence: 'Learners are able to explain the value of weathering products and the damage weathering causes.',
  objectives: ['Define regolith and soil.', 'Explain the economic importance of weathering products.', 'Explain the positive effects of weathering.', 'Explain its negative effects.'],
  recall: ['Climate controls weathering.', 'Oxidation gives red soils.', 'The North grows cotton, millet and sorghum.'],
  situation: 'You help your family prepare a millet field near Garoua. As you dig, you feel the soft soil that will feed the crops. On the way home, you see cracks in the wall of an old building and potholes in the tarred road. You think: the same natural force that makes good soil for our farms also destroys the walls and roads we build. You ask: "How can weathering be both useful and harmful?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand the positive and negative impacts of weathering.'],
    ['What is the layer of loose weathered material called?', 'Regolith; its upper part is the soil.'],
    ['Give one harmful effect of weathering.', 'It damages buildings and roads.']],
  justification: 'This lesson shows the importance of weathering for farming, building and mining, and the costs it causes.',
  action: 'Protect farm soils from erosion and maintain buildings and roads regularly.',
  activities: [
    { sec: '1. PRODUCTS', img: 'soil_profile_big.png', caption: 'A soil profile.', q: 'What lies at the bottom of the soil profile?', a: 'The hard rock (bedrock).', noProj: 'draw a soil profile.' },
    { sec: '1. PRODUCTS', img: 'lsa_bauxite.jpg', caption: 'Bauxite.', q: 'Which metal is made from bauxite?', a: 'Aluminium.', noProj: 'name the bauxite of Minim-Martap.' },
    { sec: '2. POSITIVE EFFECTS', img: 'f2t_cotton_field.jpg', caption: 'A cotton field.', q: 'Why is soil the most important product of weathering?', a: 'It supports all farming and ecosystems.', noProj: 'name crops of the North.' },
    { sec: '2. POSITIVE EFFECTS', img: 'lsa_mandara.jpg', caption: 'Landscape near Rhumsiki.', q: 'How can weathered landscapes help the economy?', a: 'They attract tourists.', noProj: 'describe Rhumsiki.' },
    { sec: '3. NEGATIVE EFFECTS', img: 'f4_oldwall.jpg', caption: 'A weathered old wall.', q: 'Give one negative effect of weathering.', a: 'Damage to buildings and roads, landslides or leaching of soils.', noProj: 'look for cracks on the school walls.' },
  ],
  summary: [
    D([['Regolith:', 'It is the layer of loose, weathered rock, gravel, sand and clay covering the bedrock.'],
      ['Soil:', 'It is the upper part of the regolith, mixed with water, air and humus, which supports plants.'],
      ['Leaching:', 'It is the washing of nutrients down the soil, out of reach of plant roots.']]),
    { title: '1. Products of Weathering as a Resource', intro: 'The products of weathering are useful resources as follows:',
      items: [['Regolith:', 'It is a few centimetres to hundreds of metres thick.', 'soil_profile_big.png', 'a soil profile'],
        ['Soil for agriculture:', 'The North grows cotton, millet, sorghum and groundnuts on soils made by weathering.', 'f2t_cotton_field.jpg', 'a cotton field'],
        ['Construction materials:', 'Sand and gravel make concrete and roads, and clay makes bricks.'],
        ['Mineral ores:', 'Chemical weathering removes unwanted minerals and concentrates bauxite and iron, like the bauxite of Minim-Martap and Fongo-Tongo.', 'lsa_bauxite.jpg', 'bauxite']] },
    { title: '2. Effects of Weathering on the Landscape and Man', sub: 'A) Positive Effects', intro: 'Weathering has the following positive effects:',
      items: [['Creation of soil:', 'It is the most important benefit, the basis of farming and land ecosystems.'],
        ['Landscapes:', 'Weathering carves inselbergs, domes and arches that attract tourists, like the landscapes of Rhumsiki.', 'lsa_mandara.jpg', 'landscape near Rhumsiki'],
        ['Groundwater:', 'The regolith stores rainwater like a sponge, which feeds wells and boreholes.']] },
    { title: '2. Effects of Weathering on the Landscape and Man', sub: 'B) Negative Effects', intro: 'Weathering has the following negative effects:',
      items: [['Damage to structures:', 'It cracks walls, makes potholes and weakens bridges and monuments, which are costly to repair.', 'f4_oldwall.jpg', 'a weathered wall'],
        ['Hazards:', 'Weathered rocks on steep slopes cause landslides and rockfalls.'],
        ['Leaching:', 'Heavy rain washes nutrients deep into the soil and reduces fertility.']] },
  ],
  evaluation: [['Give two economic uses of weathering products.', 'Soils for farming, sand and gravel for building, clay for bricks, bauxite ore (any two).'],
    ['Give one positive and one negative effect of weathering.', 'Positive: soil formation; negative: damage to buildings and roads.']],
  remediation: ['The loose layer above the bedrock is the ______.', 'Aluminium comes from ______.', 'The washing of nutrients down the soil is ______.'],
  remediationAnswers: '1. regolith 2. bauxite 3. leaching',
  homework: 'Define mass wasting.',
  hwAnswer: 'Mass wasting is the movement of rock, soil and debris down a slope under the influence of gravity.',
  bilingual: [['Weathering', "L'altération"], ['Soil', 'Le sol'], ['Regolith', 'Le régolithe'], ['Landscape', 'Le paysage'], ['Resource', 'La ressource'], ['Leaching', 'Le lessivage']],
});

L.push({ no: 12, title: 'Mass Wasting (Movement)', topic: T, subtopic: M,
  notions: 'Mass wasting, gravity, angle of repose, soil creep, terracettes, tension cracks, fall, slide, flow, Carson and Kirkby.',
  focus: 'Meaning and evidence of mass wasting; factors influencing it; classification by speed and water content (Carson and Kirkby).',
  competence: 'Learners are able to recognise signs of mass wasting, explain its factors and classify its types.',
  objectives: ['Define mass wasting.', 'Identify the evidence of mass wasting.', 'Explain its factors.', 'Classify mass movements by speed and water content.'],
  recall: ['Weathered material moves down slopes.', 'Water adds weight to soil.', 'Roots bind the soil.'],
  situation: 'In the rainy season, you travel on the road from Garoua towards Maroua through hilly areas. A telephone pole on a hillside, straight last year, now leans downhill. Further on, part of a muddy slope has slid onto the road and workers are clearing it. You ask: "Why is the ground moving, and why does a whole part of a hill suddenly give way, especially when it rains a lot?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the causes and types of mass wasting.'],
    ['What is the movement of soil and rock down a slope called?', 'Mass wasting (mass movement).'],
    ['Is the leaning pole the same as the slide onto the road?', 'No: the pole shows slow creep, the road shows a fast slide or flow.']],
  justification: 'This lesson helps us to recognise dangerous slopes and to avoid building or travelling where the ground may move.',
  action: 'Report signs of moving slopes (cracks, leaning poles) to the authorities.',
  activities: [
    { sec: '1. EVIDENCE', img: 'creep.gif', caption: 'Animation: soil creep.', q: 'Give one sign of soil creep.', a: 'Leaning poles or fences, curved tree trunks, terracettes.', noProj: 'list signs on the board.' },
    { sec: '1. EVIDENCE', img: 'geo2_mw_evidence.png', caption: 'Evidence of mass wasting.', q: 'What do tension cracks at the top of a slope show?', a: 'That part of the slope is starting to pull away.', noProj: 'draw a slope with cracks.' },
    { sec: '2. FACTORS', img: 'geo2_mw_factors.png', caption: 'Factors of mass wasting.', q: 'What is the most common trigger of mass wasting?', a: 'Heavy rainfall (water).', noProj: 'tilt a book with an eraser on it.' },
    { sec: '3. CLASSIFICATION', img: 'carson_kirkby_big.png', caption: 'Classification of mass movements.', q: 'Which movement is fast and dry?', a: 'A rockfall.', noProj: 'draw the triangle.' },
    { sec: '3. CLASSIFICATION', img: 'f4_landslide.jpg', caption: 'A landslide.', q: 'Is a landslide slow or fast?', a: 'Fast.', noProj: 'describe a landslide on a road.' },
  ],
  summary: [
    D([['Mass wasting (mass movement):', 'It is the large-scale movement of rock, soil and debris down slopes under the direct influence of gravity.'],
      ['Angle of repose:', 'It is the steepest angle at which loose material remains stable.'],
      ['Soil creep:', 'It is the very slow downhill movement of soil.']]),
    { title: '1. Meaning and Evidence of Mass Wasting', intro: 'Mass wasting and its evidence are presented as follows:',
      items: [['Meaning:', 'Unlike erosion, mass wasting needs no transporting agent: gravity is the main force.', 'creep_last.png', 'soil creep'],
        ['Tilted objects:', 'Fences, poles and walls lean downhill.'],
        ['Curved tree trunks:', 'Trees keep growing upwards while the soil moves, so their base curves.'],
        ['Terracettes:', 'Small step-like ridges form on grassy slopes.', 'geo2_mw_evidence.png', 'evidence of mass wasting'],
        ['Tension cracks:', 'Cracks at the top of a slope show that a block is pulling away.']] },
    { title: '2. Factors of Mass Wasting', intro: 'The factors of mass wasting are the following:',
      items: [['Gravity:', 'It is the driving force pulling material downslope.', 'geo2_mw_factors.png', 'factors of mass wasting'],
        ['Water:', 'Heavy rain adds weight and lubricates particles; it is the most common trigger.'],
        ['Slope angle:', 'Slopes steeper than the angle of repose become unstable.'],
        ['Lack of vegetation:', 'Deforestation, bush fires and overgrazing remove the roots that bind the soil.'],
        ['Human activities and vibrations:', 'Road cuts, waste tips, earthquakes and heavy traffic destabilise slopes.']] },
    { title: '3. Classification of Mass Wasting', intro: 'Mass movements are classified by speed and water content as follows:',
      items: [['Carson and Kirkby:', 'Their triangle classifies movements from slow to fast and from dry to wet.', 'carson_kirkby_big.png', 'classification of mass movements'],
        ['Creep:', 'It is the slowest and most common movement.'],
        ['Falls:', 'They are fast and dry: rocks fall freely from steep cliffs.'],
        ['Slides:', 'A block moves quickly over a distinct surface, as in a landslide.', 'f4_landslide.jpg', 'a landslide'],
        ['Flows:', 'They are fast and wet: material moves like a thick liquid, as in mudflows after sudden storms.']] },
  ],
  evaluation: [['How does removing trees from a steep slope increase the risk of mass wasting?', 'Without roots, the soil is no longer bound and absorbs more water, so it slides more easily.'],
    ['Give two pieces of evidence of soil creep.', 'Leaning poles or fences, curved tree trunks, terracettes (any two).']],
  remediation: ['The main force of mass wasting is ______.', 'The slowest mass movement is soil ______.', 'A fast, wet movement is a ______.'],
  remediationAnswers: '1. gravity 2. creep 3. flow (mudflow)',
  homework: 'Name one slow mass movement.',
  hwAnswer: 'Soil creep or solifluction.',
  bilingual: [['Mass wasting', 'Le mouvement de masse'], ['Gravity', 'La gravité'], ['Slope', 'La pente'], ['Landslide', 'Le glissement de terrain'], ['Soil creep', 'La reptation du sol'], ['Rockfall', "L'éboulement"]],
});

L.push({ no: 13, title: 'Processes and Features of Mass Wasting', topic: T, subtopic: M,
  notions: 'Soil creep, solifluction, landslide, slump, mudflow, debris flow, rockfall, scree (talus), afforestation, retaining wall, terracing, zoning.',
  focus: 'Slow mass movements (creep, solifluction); fast mass movements (landslides, slumps, mudflows, rockfalls); impacts on man and the environment; control measures.',
  competence: 'Learners are able to describe the types of mass movements, explain their impacts and propose measures to control them.',
  objectives: ['Describe slow mass movements.', 'Describe fast mass movements and their features.', 'Explain the impacts of mass wasting.', 'Propose solutions to control mass wasting.'],
  recall: ['Water is the main trigger of mass wasting.', 'Creep is slow and falls are fast.', 'The angle of repose limits stable slopes.'],
  situation: 'At the peak of the rainy season, you pass a steep road cutting near the high banks of the Benue. A large section of soil and rock that was stable in the dry season has collapsed, leaving a fresh scar on the slope. A small tree at the edge now leans at a strange angle. You ask: "What force made this part of the slope fall suddenly, can it also happen slowly, and how can we prevent it?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the types of mass movements and how to control them.'],
    ['What is a very slow movement that tilts trees over years?', 'Soil creep.'],
    ['What is a sudden collapse after heavy rain?', 'A fast mass movement such as a landslide or a slump.']],
  justification: 'This lesson helps us to protect lives, houses and roads from landslides and bank collapses.',
  action: 'Plant trees and keep drains clear on slopes near your home.',
  activities: [
    { sec: '1. SLOW MOVEMENTS', img: 'lsa_solifluction.jpg', caption: 'Solifluction lobes.', q: 'What is solifluction?', a: 'The slow flow of waterlogged soil over impermeable ground.', noProj: 'describe waterlogged soil.' },
    { sec: '2. FAST MOVEMENTS', img: 'lsa_slump.jpg', caption: 'A slump.', q: 'How does a slump move?', a: 'Along a curved surface, with the block rotating backwards.', noProj: 'draw a curved slip surface.' },
    { sec: '2. FAST MOVEMENTS', img: 'lsa_scree.jpg', caption: 'Scree at the foot of a cliff.', q: 'What is the pile of rocks at the foot of a cliff called?', a: 'Scree (talus).', noProj: 'pour gravel into a pile.' },
    { sec: '3. IMPACTS', img: 'lsa_landscar.jpg', caption: 'A landslide scar.', q: 'Give one impact of mass wasting on man.', a: 'Deaths, destroyed houses and farms, blocked roads.', noProj: 'list impacts on the board.' },
    { sec: '4. SOLUTIONS', img: 'f4_terraces.jpg', caption: 'Terraced slopes.', q: 'How do terraces reduce mass wasting?', a: 'They reduce the slope angle and slow down runoff.', noProj: 'describe terraces in the Mandara Mountains.' },
  ],
  summary: [
    D([['Solifluction:', 'It is the slow flow of waterlogged soil over impermeable ground.'],
      ['Landslide:', 'It is the rapid movement of a mass of rock or soil down a slope.'],
      ['Slump:', 'It is a slide along a curved surface.'],
      ['Scree (talus):', 'It is the pile of rock fragments at the foot of a cliff.']]),
    { title: '1. Slow Mass Movements', intro: 'The slow mass movements are the following:',
      items: [['Soil creep:', 'The slow downhill movement of soil, a few centimetres a year, shown by tilted poles and cracked roads.', 'creep_last.png', 'soil creep'],
        ['Solifluction:', 'Waterlogged soil flows slowly over frozen ground or impermeable clay.', 'lsa_solifluction.jpg', 'solifluction lobes']] },
    { title: '2. Fast Mass Movements', intro: 'The fast mass movements are the following:',
      items: [['Landslides:', 'A large block of rock or soil moves rapidly down a slope.', 'f4_landslide.jpg', 'a landslide'],
        ['Slumps:', 'Material slides along a curved surface and rotates, as on the banks of the Benue after heavy rain.', 'lsa_slump.jpg', 'a slump'],
        ['Mudflows and debris flows:', 'Water, soil and rock move like wet concrete in hilly areas after heavy rain.', 'lsa_lahar.jpg', 'a mudflow'],
        ['Rockfalls:', 'Rocks fall freely from a steep cliff and pile up as scree at its foot.', 'lsa_scree.jpg', 'scree']] },
    { title: '3. Impacts of Mass Wasting', intro: 'Mass wasting has the following impacts:',
      items: [['On man:', ['Loss of life and injuries.', 'Destruction of houses and farms.', 'Damage to roads, railways and bridges.', 'High costs of repair and cleaning.']],
        ['On the environment:', ['Bare scars on slopes.', 'Rivers dammed by debris, causing floods upstream.', 'Destruction of habitats.']],
        ['Example:', 'The landslide at Gouache (Bafoussam) in 2019 killed more than 40 people.', 'lsa_landscar.jpg', 'a landslide scar']] },
    { title: '4. Solutions to Control Mass Wasting', intro: 'Mass wasting is controlled by the following measures:',
      items: [['Afforestation:', 'Trees and grass bind the soil with their roots.', 'geo2_mw_solutions.png', 'controlling mass wasting'],
        ['Drainage:', 'Channels and pipes remove excess water from slopes.'],
        ['Retaining walls:', 'Strong walls at the foot of slopes hold back soil and rock.'],
        ['Terracing:', 'Steps cut into slopes reduce the angle and slow runoff, as in the Mandara Mountains.', 'f4_terraces.jpg', 'terraced slopes'],
        ['Land-use zoning:', 'Laws forbid building in high-risk zones.']] },
  ],
  evaluation: [['Distinguish soil creep from a landslide.', 'Soil creep is a very slow, continuous movement of soil; a landslide is a sudden, rapid movement of a large mass.'],
    ['Give two measures to control mass wasting.', 'Afforestation, drainage, retaining walls, terracing, zoning (any two).']],
  remediation: ['A slide along a curved surface is a ______.', 'Rock fragments at the foot of a cliff form ______.', 'Planting trees on slopes is ______.'],
  remediationAnswers: '1. slump 2. scree (talus) 3. afforestation',
  homework: 'Name the three types of work of a river.',
  hwAnswer: 'Erosion, transportation and deposition.',
  bilingual: [['Mass wasting', 'Le mouvement de masse'], ['Landslide', 'Le glissement de terrain'], ['Soil creep', 'La reptation du sol'], ['Mudflow', 'La coulée de boue'], ['Retaining wall', 'Le mur de soutènement'], ['Terracing', 'Les cultures en terrasses']],
});

L.push({ no: 14, title: 'Erosional Processes and the Fluvial System', topic: T, subtopic: E,
  notions: 'River system, input, output, hydraulic action, abrasion, attrition, solution, traction, saltation, suspension, load, deposition.',
  focus: 'The river as a system; river erosion (four processes); transportation (four methods); deposition and its conditions.',
  competence: 'Learners are able to explain how a river erodes, carries and deposits material, using the Benue as an example.',
  objectives: ['Describe the river as an open system.', 'Explain the four processes of river erosion.', 'Explain the four methods of transportation.', 'Explain why and where a river deposits its load.'],
  recall: ['Erosion removes weathered material.', 'The Benue flows past Garoua.', 'The Benue has sandbanks in the dry season.'],
  situation: 'In the rainy season, you stand on the bridge of Garoua and look at the Benue: it is wide, fast and brown, carrying soil, branches and debris. In the dry season, from the same place, the river is low, slow and clearer, and huge sandbanks appear where deep water flowed before. You ask: "Where did all the brown mud go, and where did this new sand come from?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how a river erodes, carries and deposits material.'],
    ['What is the river doing in the rainy season?', 'Eroding its banks and transporting a large load.'],
    ['Why do sandbanks appear in the dry season?', 'The river slows down, loses energy and deposits its load.']],
  justification: 'This lesson helps us to understand the changing channel of the Benue, which affects farming, fishing and navigation.',
  action: 'Protect river banks with vegetation and avoid building on unstable banks.',
  activities: [
    { sec: '1. RIVER SYSTEM', img: 'open_system_big.png', caption: 'An open system.', q: 'Give one input of a river system.', a: 'Rainwater (or sediments from the slopes).', noProj: 'draw inputs, stores and outputs.' },
    { sec: '2. EROSION', img: 'river_erosion_big.png', caption: 'The four processes of erosion.', q: 'Distinguish abrasion from attrition.', a: 'Abrasion: the load scrapes the bed and banks; attrition: stones hit each other and become smaller and rounder.', noProj: 'rub two stones together.' },
    { sec: '3. TRANSPORTATION', img: 'geo2_transport.png', caption: 'Four ways of carrying the load.', q: 'Which method carries the largest amount of load?', a: 'Suspension.', noProj: 'shake a bottle with water, sand and soil.' },
    { sec: '3. TRANSPORTATION', img: 'f4_muddyriver.jpg', caption: 'A muddy river.', q: 'Why is the Benue brown in the rainy season?', a: 'It carries a lot of silt and clay in suspension.', noProj: 'compare rainy and dry seasons.' },
    { sec: '4. DEPOSITION', img: 'load.gif', caption: 'Animation: the load settles.', q: 'Which material is deposited first?', a: 'The heaviest (boulders and pebbles).', noProj: 'let the shaken bottle settle.' },
  ],
  summary: [
    D([['River system:', 'It is a river seen as an open system with inputs, processes and outputs.'],
      ['Load:', 'It is the material carried by a river.'],
      ['Deposition:', 'It is the dropping of the load when a river loses energy.']]),
    { title: '1. The River as a System', intro: 'The river works as a system as follows:',
      items: [['Inputs:', 'Rainwater, springs and sediments from the valley slopes enter the river.', 'open_system_big.png', 'an open system'],
        ['Processes:', 'The river erodes, transports and deposits.'],
        ['Outputs:', 'Water and sediments flow out into a larger river, a lake or the sea; the Benue flows into the Niger.']] },
    { title: '2. River Erosion', intro: 'A river erodes its bed and banks by the following processes:',
      items: [['Hydraulic action:', 'The force of the water hits the bed and banks and compresses air in cracks, breaking pieces off.', 'river_erosion_big.png', 'the four processes'],
        ['Abrasion (corrasion):', 'The load scrapes and grinds the bed and banks like sandpaper.'],
        ['Attrition:', 'Stones carried by the river knock against each other and become smaller and rounder.'],
        ['Solution (corrosion):', 'The water dissolves soluble rocks such as limestone.']] },
    { title: '3. River Transportation', intro: 'A river carries its load by the following methods:',
      items: [['Traction:', 'The largest boulders roll along the bed.', 'geo2_transport.png', 'four ways of carrying the load'],
        ['Saltation:', 'Small pebbles and sand bounce along the bed.'],
        ['Suspension:', 'Silt and clay are carried within the water, making it brown; this is the largest part of the load.', 'f4_muddyriver.jpg', 'a muddy river'],
        ['Solution:', 'Dissolved minerals are carried invisibly.']] },
    { title: '4. River Deposition', intro: 'A river deposits its load in the following conditions:',
      items: [['Loss of energy:', 'Deposition happens when velocity falls, and the heaviest material is dropped first.', 'load_mid.png', 'the load settles'],
        ['Less water:', 'The volume falls in the dry season, so the Benue leaves sandbanks.'],
        ['Flat land:', 'The river enters a gentle plain and slows down.'],
        ['Lakes and seas:', 'The river enters still water, as the Benue enters the Lagdo reservoir.']] },
  ],
  evaluation: [['Distinguish abrasion from attrition.', 'Abrasion is the scraping of the bed and banks by the load; attrition is the collision of stones that makes them smaller and rounder.'],
    ['Give two conditions for river deposition.', 'Fall in water volume, entry into flat land, entry into a lake or the sea (any two).']],
  remediation: ['The rolling of boulders is ______.', 'Silt carried in the water moves by ______.', 'The Benue leaves ______ in the dry season.'],
  remediationAnswers: '1. traction 2. suspension 3. sandbanks',
  homework: 'Name the three courses of a river.',
  hwAnswer: 'The upper course, the middle course and the lower course.',
  bilingual: [['Erosion', "L'érosion"], ['Transportation', 'Le transport'], ['Deposition', 'Le dépôt'], ['River load', 'La charge du fleuve'], ['River bank', 'La berge'], ['Sandbank', 'Le banc de sable']],
});

L.push({ no: 15, title: 'River Action on its Long Profile', topic: T, subtopic: E,
  notions: 'Long profile, source, mouth, upper, middle and lower course, V-shaped valley, interlocking spurs, waterfall, gorge, meander, river cliff, slip-off slope, floodplain, ox-bow lake, levee, delta.',
  focus: 'The long profile; characteristics and landforms of the upper, middle and lower courses; application to the Benue.',
  competence: 'Learners are able to describe the changes of a river from source to mouth and explain the landforms of each course.',
  objectives: ['Define the long profile of a river.', 'Describe the upper course and its landforms.', 'Describe the middle course and its landforms.', 'Describe the lower course and its landforms.'],
  recall: ['Rivers erode, transport and deposit.', 'Deposition happens when rivers slow down.', 'The Benue rises on the Adamawa Plateau.'],
  situation: 'You travel from Garoua up to the Adamawa Plateau, near the source of streams that feed the Benue. In the hills, the streams are small, fast and noisy, tumbling over rocks in narrow valleys. Back in Garoua, the Benue is huge, wide, slow and quiet, flowing across a vast flat plain. You ask: "Why does the same river system behave so differently in the hills and on the plain?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how a river changes from source to mouth.'],
    ['What is the path of a river from source to mouth called?', 'The long profile.'],
    ['What is the main work of the river at Garoua?', 'Deposition, because it is in its lower course.']],
  justification: 'This lesson explains the landforms of river valleys, which influence farming, settlement and flooding in the Benue valley.',
  action: 'Use floodplains for farming but avoid building houses on them.',
  activities: [
    { sec: '1. LONG PROFILE', img: 'long_profile_big.png', caption: 'The long profile.', q: 'Where is the gradient steepest?', a: 'In the upper course.', noProj: 'draw the concave long profile.' },
    { sec: '2. UPPER COURSE', img: 'f4_waterfall.jpg', caption: 'A waterfall.', q: 'How does a waterfall form?', a: 'The river flows over hard rock and undercuts the soft rock below.', noProj: 'describe a waterfall in Cameroon.' },
    { sec: '3. MIDDLE COURSE', img: 'meander.gif', caption: 'Animation: a meander.', q: 'On which side of a meander is the river cliff?', a: 'On the outside of the bend.', noProj: 'draw a meander with its cliff and slip-off slope.' },
    { sec: '4. LOWER COURSE', img: 'oxbow.gif', caption: 'Animation: an ox-bow lake forms.', q: 'How is an ox-bow lake formed?', a: 'A meander is cut off from the main channel.', noProj: 'draw the stages.' },
    { sec: '4. LOWER COURSE', img: 'f4_floodplain.jpg', caption: 'A floodplain.', q: 'Why are floodplains fertile?', a: 'Floods deposit fresh silt each year.', noProj: 'talk about farms along the Benue.' },
  ],
  summary: [
    D([['Long profile:', 'It is the line showing the gradient of a river from its source to its mouth.'],
      ['Meander:', 'It is a wide bend of a river channel.'],
      ['Floodplain:', 'It is the wide, flat land beside a river covered by floods.'],
      ['Delta:', 'It is a fan-shaped area of deposits at the mouth of a river.']]),
    { title: '1. The Long Profile', intro: 'The long profile is presented as follows:',
      items: [['Shape:', 'It is a concave curve, steep near the source and almost flat near the mouth.', 'long_profile_big.png', 'the long profile'],
        ['Three courses:', 'It is divided into the upper, middle and lower courses.', 'geo2_courses.png', 'the three courses']] },
    { title: '2. The Upper Course (Youthful Stage)', intro: 'The upper course has the following characteristics and landforms:',
      items: [['Characteristics:', 'The gradient is very steep, the channel narrow and shallow, and vertical erosion dominates.'],
        ['V-shaped valleys:', 'The river cuts down quickly while weathering wears back the sides.', 'vvalley_big.png', 'a V-shaped valley'],
        ['Interlocking spurs:', 'Hill spurs seem to lock together as the river winds between them.'],
        ['Waterfalls and gorges:', 'Hard rock over soft rock forms a waterfall, which retreats and leaves a gorge, like the falls of the Vina near Ngaoundéré.', 'f4_waterfall.jpg', 'a waterfall']] },
    { title: '3. The Middle Course (Mature Stage)', intro: 'The middle course has the following characteristics and landforms:',
      items: [['Characteristics:', 'The gradient is gentle, the valley wider and transport is the main work, with more lateral erosion.'],
        ['Meanders:', 'The river swings from side to side, forming wide bends.', 'meander_last.png', 'a meander'],
        ['River cliffs and slip-off slopes:', 'Fast water erodes the outside of the bend (river cliff), while slow water deposits on the inside (slip-off slope).', 'rivercliff_big.png', 'river cliff and slip-off slope']] },
    { title: '4. The Lower Course (Old Stage)', intro: 'The lower course has the following characteristics and landforms:',
      items: [['Characteristics:', 'The gradient is almost flat, the channel wide and deep, and deposition dominates, as on the Benue at Garoua.'],
        ['Floodplains:', 'Floods deposit silt on wide flat land, making it very fertile.', 'f4_floodplain.jpg', 'a floodplain'],
        ['Ox-bow lakes:', 'A meander is cut off and forms a U-shaped lake.', 'oxbow_last.png', 'an ox-bow lake'],
        ['Levees:', 'Floods build raised banks along the river.'],
        ['Deltas:', 'Deposits form a fan at the mouth, like the Niger delta.', 'f4_delta.jpg', 'a delta']] },
  ],
  evaluation: [['Give three differences between the upper and the lower course of a river.', 'Upper: steep gradient, narrow V-shaped valley, vertical erosion; lower: flat gradient, wide floodplain, deposition.'],
    ['Why does the Benue at Garoua form sandbanks?', 'In its lower course it flows slowly on flat land and deposits its load, especially in the dry season.']],
  remediation: ['Vertical erosion dominates in the ______ course.', 'A cut-off meander forms an ______ lake.', 'Raised banks built by floods are ______.'],
  remediationAnswers: '1. upper 2. ox-bow 3. levees',
  homework: 'Define longshore drift.',
  hwAnswer: 'Longshore drift is the movement of sand and pebbles along a coast by waves that reach the shore at an angle.',
  bilingual: [['Upper course', 'Le cours supérieur'], ['Lower course', 'Le cours inférieur'], ['Meander', 'Le méandre'], ['Floodplain', "La plaine d'inondation"], ['Waterfall', 'La chute d\'eau'], ['Delta', 'Le delta']],
});

L.push({ no: 16, title: 'Coastal Processes and Features', topic: T, subtopic: E,
  notions: 'Coast, wave, fetch, tide, storm surge, hydraulic action, abrasion, attrition, solution, longshore drift, swash, backwash, cliff, wave-cut platform, cave, arch, stack, stump, beach, spit, bar.',
  focus: 'The coastal system and wave action; coastal processes (erosion, transportation, deposition); landforms of erosion and deposition; threats to coasts in Cameroon.',
  competence: 'Learners are able to explain coastal processes and landforms and the problems of the coast of Cameroon.',
  objectives: ['Describe waves, tides and storm surges.', 'Explain the processes of wave erosion.', 'Explain longshore drift.', 'Describe landforms of coastal erosion and deposition.', 'Explain the threats to coasts.'],
  recall: ['Rivers erode by hydraulic action, abrasion, attrition and solution.', 'Deposition happens when energy falls.', 'Kribi and Limbe are on the coast of Cameroon.'],
  situation: 'You travel from Garoua to Kribi for the holidays and see the sea for the first time. Unlike the Benue, which flows in one direction, the sea moves constantly, with waves crashing on the shore. You build a sandcastle, but a few hours later the rising water washes it away. In some places the shore is sandy and wide; in others, tall rocks are being worn away. You ask: "What forces shape and change the land where it meets the sea?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the processes and landforms of the coast.'],
    ['What gives waves their energy?', 'The wind blowing over the sea.'],
    ['Why was the sandcastle washed away?', 'The tide rose and brought the water further up the shore.']],
  justification: 'This lesson helps us to understand the coast of Cameroon, its landforms and the dangers faced by coastal towns.',
  action: 'Protect mangroves and beaches and avoid dumping waste on the coast.',
  activities: [
    { sec: '1. WAVES AND TIDES', img: 'f4_bigwaves.jpg', caption: 'Large waves.', q: 'Name one factor of the size of waves.', a: 'Wind speed, wind duration or the fetch.', noProj: 'blow over a basin of water.' },
    { sec: '2. EROSION', img: 'headland.gif', caption: 'Animation: erosion of a headland.', q: 'Put in order: arch, cave, stack, stump.', a: 'Cave, arch, stack, stump.', noProj: 'draw the four stages.' },
    { sec: '2. TRANSPORTATION', img: 'longshore.gif', caption: 'Animation: longshore drift.', q: 'Why does longshore drift move sand along the beach?', a: 'The swash comes up at an angle and the backwash goes straight down, so sand zig-zags along.', noProj: 'draw the zig-zag.' },
    { sec: '3. DEPOSITION', img: 'f4_spit.jpg', caption: 'A spit.', q: 'What is a spit?', a: 'A long ridge of sand or shingle joined to the land and projecting into the sea.', noProj: 'draw a spit and a bar.' },
    { sec: '4. THREATS', img: 'geo2_coast_threats.png', caption: 'Threats to the coast.', q: 'Give one threat faced by Kribi or Limbe.', a: 'Coastal erosion, flooding or pollution.', noProj: 'discuss coastal problems.' },
  ],
  summary: [
    D([['Coast:', 'It is the narrow zone where the land meets the sea.'],
      ['Fetch:', 'It is the distance of open water over which the wind blows.'],
      ['Longshore drift:', 'It is the movement of sediment along the coast by waves reaching the shore at an angle.'],
      ['Spit:', 'It is a long ridge of sand or shingle joined to the land at one end and projecting into the sea.']]),
    { title: '1. The Coastal System and Wave Action', intro: 'The forces acting on the coast are the following:',
      items: [['Waves:', 'The wind transfers energy to the water; wave size depends on wind speed, duration and fetch.', 'f4_bigwaves.jpg', 'large waves'],
        ['Tides:', 'The sea rises and falls about twice a day, because of the pull of the Moon and the Sun.', 'f4_lowtide.jpg', 'low tide'],
        ['Storm surges:', 'Powerful storms raise the sea level abnormally and flood the coast.']] },
    { title: '2. Coastal Processes', intro: 'Waves shape the coast by the following processes:',
      items: [['Hydraulic action:', 'Waves crash against the coast and compress air in cracks, breaking the rock.', 'geo2_coast.png', 'coastal processes'],
        ['Abrasion:', 'Waves throw sand and pebbles against cliffs like sandpaper.'],
        ['Attrition and solution:', 'Pebbles hit each other and become rounded, and seawater dissolves limestone.'],
        ['Longshore drift:', 'The swash carries sediment up the beach at an angle and the backwash brings it straight back, moving it along the coast.', 'longshore_last.png', 'longshore drift'],
        ['Deposition:', 'Waves drop their load where they lose energy, in sheltered bays.']] },
    { title: '3. Coastal Landforms', intro: 'Coastal processes create the following landforms:',
      items: [['Cliffs and wave-cut platforms:', 'Waves erode the foot of a cliff, which collapses and retreats, leaving a flat rock platform.', 'f4_cliff.jpg', 'a cliff'],
        ['Caves, arches, stacks and stumps:', 'On a headland, a crack becomes a cave, then an arch; the arch collapses into a stack, which wears down to a stump.', 'headland_last.png', 'erosion of a headland'],
        ['Beaches:', 'Sand and shingle accumulate in bays, like the beaches of Kribi and Limbe.', 'usa_beach.jpg', 'a beach'],
        ['Spits and bars:', 'Longshore drift builds spits into the sea; a bar closes a bay and traps a lagoon.', 'f4_spit.jpg', 'a spit']] },
    { title: '4. Threats to Coasts', intro: 'The coasts of Cameroon face the following threats:',
      items: [['Coastal erosion:', 'Beaches, roads and houses are lost, especially at Kribi and Limbe.', 'geo2_coast_threats.png', 'threats to the coast'],
        ['Flooding:', 'Storm surges and rising sea level threaten low areas such as parts of Douala.'],
        ['Pollution:', 'Waste from towns, industries and ships damages mangroves, fishing and tourism.', 'usa_oilspill.jpg', 'oil pollution']] },
  ],
  evaluation: [['Explain how waves break a hard cliff.', 'Hydraulic action compresses air in cracks, abrasion hurls pebbles against the rock, and solution dissolves some minerals.'],
    ['Describe the formation of a stack.', 'A crack in a headland is enlarged into a cave, then an arch; the arch collapses, leaving a stack.']],
  remediation: ['The distance of open water over which wind blows is the ______.', 'Waves going up the beach are the ______.', 'A ridge of sand closing a bay is a ______.'],
  remediationAnswers: '1. fetch 2. swash 3. bar',
  homework: 'Name the highest mountain of Cameroon.',
  hwAnswer: 'Mount Cameroon (4,095 m).',
  bilingual: [['Coast', 'La côte'], ['Wave', 'La vague'], ['Erosion', "L'érosion"], ['Beach', 'La plage'], ['Tide', 'La marée'], ['Cliff', 'La falaise']],
});

module.exports = { B, L };
