// LOWER SIXTH ARTS — Geomorphology, part 3: Lessons 9–16 (Denudational Processes on Slopes)
// Rewritten from the teacher's course support (LSA_LESSON_GEOMO_2026) in our own words; facts checked and updated.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const { B } = require('./lsageo_1');
const L = [];
const T = 'Denudational Processes on Slopes';
const W = 'Weathering', M = 'Mass Movements', E = 'Erosion and Depositional Processes and Landforms';

L.push({ no: 9, title: 'Denudation and Weathering', topic: T, subtopic: W, pointPerSlide: true,
  notions: 'Denudation, weathering, erosion, mass movement, slope, convex, concave, rectilinear, slope system, mechanical, chemical and biological weathering.',
  focus: 'Meaning of denudation; slopes (types and the slope system); weathering and its types (mechanical, chemical, biological).',
  competence: 'Learners are able to explain how rocks are broken down and how slopes work as systems, using examples from Garoua.',
  objectives: ['Define denudation, weathering and slope.', 'Describe the types of slopes.', 'Explain the slope as an open system.', 'Explain mechanical, chemical and biological weathering.'],
  recall: ['External forces wear down the land.', 'Igneous rocks form from cooled magma.', 'Garoua is very hot in the dry season.'],
  situation: 'In the dry season, you notice that the surface of a large rock in your quarter of Garoua is peeling off in thin layers, like an onion. After the first heavy rains, you see small gullies cut into the slopes of nearby hills, with piles of sand at the bottom. You ask: "What makes hard rock crumble, and where does all the soil that moves down the hills come from?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how rocks break down and how material moves down slopes.'],
    ['What is the general name for the wearing down of the land?', 'Denudation.'],
    ['What breaks the rock before it is moved?', 'Weathering.']],
  justification: 'This lesson explains how landscapes are worn down and how soils form, which matters for farming and building.',
  action: 'Protect slopes with vegetation to limit the removal of weathered material.',
  activities: [
    { sec: '1. DENUDATION', img: 'geo2_denudation.png', caption: 'The three parts of denudation.', q: 'Which part of denudation happens without any movement?', a: 'Weathering.', noProj: 'write the three processes on the board.' },
    { sec: '2. SLOPES', img: 'geo2_slopes.png', caption: 'Three types of slopes.', q: 'Which slope becomes steeper as you go down?', a: 'The convex slope.', noProj: 'draw the three slopes.' },
    { sec: '2. SLOPES', img: 'slope_system_big.png', caption: 'The slope system.', q: 'Give one input of the slope system.', a: 'Rainwater or heat from the Sun.', noProj: 'draw inputs, processes and outputs.' },
    { sec: '3. WEATHERING', img: 'exfoliation.gif', caption: 'Animation: exfoliation.', q: 'Why does a rock peel like an onion in Garoua?', a: 'It expands in the heat of the day and contracts at night, so the outer layers crack.', noProj: 'describe a peeling rock.' },
    { sec: '3. WEATHERING', img: 'f4_roots.jpg', caption: 'Roots in a rock.', q: 'What type of weathering do these roots cause?', a: 'Biological weathering.', noProj: 'find a tree growing in a crack.' },
  ],
  summary: [
    D([['Denudation:', 'It is the general wearing down and lowering of the land surface by weathering, mass movement and erosion.'],
      ['Degradation:', 'It is the lowering of the land surface by the removal of material.'],
      ['Aggradation:', 'It is the building up of the land surface by the deposition of material.'],
      ['Weathering:', 'It is the breakdown of rocks in place, at or near the surface, without movement.'],
      ['Slope:', 'It is any inclined surface of the land.']]),
    { title: '1. Denudation', intro: 'Denudation is explained and classified as follows:',
      items: [['Meaning:', 'Denudation is the sum of all the processes that wear down the relief, lowering high land (degradation) and filling low land with deposits (aggradation). It is driven by the energy of the Sun and by gravity.', 'geo2_denudation.png', 'the processes of denudation'],
        ['Weathering:', 'Weathering is the first stage of denudation: rocks are broken down in place by heat, water, chemicals and living things. It prepares loose material that can be moved.'],
        ['Mass movement:', 'Mass movement is the second stage: the weathered material moves down the slopes under the pull of gravity. It feeds material to the valleys.'],
        ['Erosion, transport and deposition:', 'Rivers, wind, ice and waves then remove the material, carry it away and deposit it in lowlands, lakes and seas. For example, the Benue carries the sand of the North towards the Niger.', 'f4_gully.jpg', 'gully erosion']] },
    { title: '2. Slopes', intro: 'Slopes are explained as follows:',
      items: [['Meaning:', 'A slope is any inclined surface of the land, from a gentle river bank to a steep mountain side. Slopes cover most of the land surface and are the place where weathering and mass movement act.'],
        ['Types of slopes:', 'A convex slope becomes steeper downwards, a concave slope becomes gentler downwards, and a rectilinear slope keeps the same angle. A free face is a vertical rock wall, and most hills combine a convex top, a straight middle and a concave foot.', 'geo2_slopes.png', 'types of slopes'],
        ['The slope system:', 'Inputs such as solar energy, rainwater and weathered rock enter the slope, and processes such as weathering, soil creep and runoff act on it. Outputs of soil, rock fragments and water leave it at the foot, usually into a river.', 'slope_system_big.png', 'the slope system']] },
    { title: '3. Weathering and its Products', sub: 'A) Mechanical (Physical) Weathering', intro: 'Mechanical weathering breaks rocks without changing their minerals, by the following processes:',
      items: [['Exfoliation (thermal expansion):', 'The sun heats the outer layer of the rock by day, and it cools quickly at night, so it expands and contracts more than the inside. The outer layers crack and peel off like an onion skin, as is common around Garoua.'],
        ['Frost action:', 'Water in cracks freezes at night, expands by about 9 % and forces the cracks open. When repeated, it splits the rock into sharp fragments that form scree on cold mountains.'],
        ['Pressure release:', 'When the rocks above a buried granite are removed by erosion, the pressure on it is reduced and it expands. Cracks parallel to the surface form, and sheets of rock break off, giving rounded domes.', 'exfoliation_last.png', 'exfoliation and sheeting']] },
    { title: '3. Weathering and its Products', sub: 'B) Chemical Weathering', intro: 'Chemical weathering changes the minerals of rocks by the following processes:',
      items: [['Oxidation:', 'Oxygen dissolved in water reacts with iron minerals in the rock and turns them into rust. This weakens the rock and gives the red colour of soils and laterite in the tropics.'],
        ['Solution and carbonation:', 'Some minerals, such as rock salt, dissolve directly in water. Rainwater that contains carbon dioxide forms a weak acid, which slowly dissolves limestone and forms caves and karst.'],
        ['Hydrolysis and hydration:', 'In hydrolysis, water reacts with minerals such as feldspar in granite and turns them into clay. In hydration, minerals absorb water, swell and crumble; both are fastest in hot, wet climates.']] },
    { title: '3. Weathering and its Products', sub: 'C) Biological Weathering', intro: 'Biological weathering is caused by the following agents:',
      items: [['Plants:', 'Roots grow into cracks and force them apart as they thicken, and decaying plants release acids that attack the rock. Lichens and mosses also slowly eat into bare rock surfaces.', 'f4_roots.jpg', 'roots splitting a rock'],
        ['Animals:', 'Termites, rodents and earthworms dig in the soil and bring rock fragments to the surface, where they are exposed to weathering. Their burrows also let water and air enter deeper.'],
        ['Man:', 'Quarrying, building, mining and ploughing break up rocks and expose fresh surfaces. Pollution also produces acid rain, which speeds up chemical weathering.', 'geo2_weathering.png', 'the types of weathering']] },
  ],
  evaluation: [['Distinguish weathering from erosion.', 'Weathering breaks rocks in place; erosion removes and carries the material away.'],
    ['Explain exfoliation in Garoua.', 'Strong heating by day and cooling at night make the outer layers of rocks expand and contract until they crack and peel off.']],
  remediation: ['Denudation means "to make ______".', 'A slope that becomes gentler downwards is ______.', 'Rusting of iron in rocks is ______.'],
  remediationAnswers: '1. bare 2. concave 3. oxidation',
  homework: 'Name the most important factor of weathering.',
  hwAnswer: 'Climate (temperature and rainfall).',
  bilingual: [['Denudation', 'La dénudation'], ['Weathering', "L'altération"], ['Slope', 'La pente'], ['Erosion', "L'érosion"], ['Rock', 'La roche'], ['Exfoliation', 'La desquamation']],
});

L.push({ no: 10, title: 'Intensity and Factors of Weathering', topic: T, subtopic: W, pointPerSlide: true,
  notions: 'Intensity of weathering, climate, Peltier\'s diagram, rock hardness, joints, relief, vegetation, human activities, acid rain.',
  focus: 'Factors of the intensity of weathering: climate (Peltier\'s diagram), geology, relief, vegetation and human activities.',
  competence: 'Learners are able to explain why weathering is faster in some places and apply this to Garoua.',
  objectives: ['Explain the role of climate and read Peltier\'s diagram.', 'Explain the role of rock characteristics.', 'Explain the role of relief.', 'Explain the roles of vegetation and human activities.'],
  recall: ['Weathering can be mechanical, chemical or biological.', 'Chemical weathering is fastest where it is hot and wet.', 'Oxidation gives red soils.'],
  situation: 'In an old quarter of Garoua, you see two stone walls. One was built last year: its stones are sharp and bright. The other, about 100 years old, has rounded, cracked stones covered with green algae, and its surface is crumbly. Both are made of the same local rock. You ask: "Why has the old wall weathered so much, and what controls the speed of weathering?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the factors that control the intensity of weathering.'],
    ['Which process has worn the old wall?', 'Weathering.'],
    ['What is the most important factor of weathering in Garoua?', 'Climate: strong heat and seasonal heavy rain.']],
  justification: 'This lesson helps us to understand the soils and landscapes of our region and to choose durable building materials.',
  action: 'Choose resistant rocks and protect buildings from water to slow down weathering.',
  activities: [
    { sec: '1. CLIMATE', img: 'peltier_big.png', caption: 'Peltier\'s diagram.', q: 'In which climate is chemical weathering strongest?', a: 'In hot, wet climates.', noProj: 'draw the two axes of the diagram.' },
    { sec: '1. CLIMATE', img: 'f2t_laterite.jpg', caption: 'Red laterite.', q: 'Why are soils around Garoua red?', a: 'Iron minerals are oxidised in the hot, seasonally wet climate.', noProj: 'show a handful of red soil.' },
    { sec: '2. ROCK', img: 'f4_karst.jpg', caption: 'Limestone dissolved by water.', q: 'Which weathers faster: limestone or granite?', a: 'Limestone.', noProj: 'drop vinegar on chalk.' },
    { sec: '3. RELIEF', img: 'lsa_scree.jpg', caption: 'Scree on a steep slope.', q: 'Why is fresh rock often exposed on steep slopes?', a: 'Weathered material is quickly washed away.', noProj: 'compare a hill and a plain.' },
    { sec: '4. HUMANS', img: 'lsa_weathered.jpg', caption: 'A weathered stone surface.', q: 'How does acid rain speed up weathering?', a: 'Its acids dissolve and weaken rocks and buildings.', noProj: 'list human activities that expose rock.' },
  ],
  summary: [
    D([['Intensity of weathering:', 'It is the speed and depth at which rocks are broken down.'],
      ["Peltier's graph:", 'It is a graph linking mean annual temperature and rainfall to the dominant type and intensity of weathering.'],
      ['Joints:', 'They are natural cracks in rocks that let water in.']]),
    { title: '1. Climate', intro: 'Climate influences weathering in the following ways:',
      items: [['Temperature:', 'High temperatures speed up chemical reactions, which are about twice as fast for each rise of 10 °C. Large daily ranges of temperature, as in deserts and in Garoua in the dry season, cause exfoliation.', 'peltier_big.png', "Peltier's graph"],
        ['Moisture:', 'Water is needed for almost all chemical weathering and for frost action. Wet regions therefore weather faster and more deeply than dry regions.'],
        ["Peltier's weathering regions:", 'Peltier showed that chemical weathering is strongest in hot, wet climates, and frost action is strongest in cold, moist climates. In hot or cold deserts, weathering is weak and mostly mechanical, while in Garoua both types act and give deep red soils.', 'f2t_laterite.jpg', 'red laterite']] },
    { title: '2. Geology (Rock Characteristics)', intro: 'Rock characteristics influence weathering in the following ways:',
      items: [['Mineral composition and hardness:', 'Rocks made of soluble or weak minerals, such as limestone or rocks rich in feldspar, weather quickly. Rocks rich in quartz, such as quartzite, resist weathering.', 'f4_karst.jpg', 'weathered limestone'],
        ['Structure (joints and bedding):', 'Joints, cracks and bedding planes let water and roots enter the rock. The more jointed a rock is, the faster it weathers, and weathering follows the joints.'],
        ['Colour and grain size:', 'Dark rocks absorb more heat and expand and contract more than light rocks. Coarse-grained rocks such as granite break apart more easily into grains than fine-grained rocks.']] },
    { title: '3. Relief', intro: 'Relief influences weathering in the following ways:',
      items: [['Steep slopes:', 'On steep slopes, as in the Mandara Mountains, weathered material is quickly removed by gravity and runoff. Fresh rock is constantly exposed, so mechanical weathering dominates and soils remain thin.', 'lsa_scree.jpg', 'scree on a steep slope'],
        ['Gentle slopes and plains:', 'On gentle slopes and plains, water stays longer in contact with the rock and the weathered material remains in place. Chemical weathering therefore acts deeply and forms thick soils.']] },
    { title: '4. Vegetation', intro: 'Vegetation influences weathering in the following ways:',
      items: [['Increase of weathering:', 'Roots split rocks, and decaying leaves release humic acids and carbon dioxide into the soil water. This makes chemical weathering faster under forests.'],
        ['Protection of rocks:', 'A dense plant cover shades the rocks from the sun and keeps the soil moist. It therefore reduces the daily range of temperature and slows down mechanical weathering.', 'geo2_wfactors.png', 'the factors of weathering']] },
    { title: '5. Human Activities', intro: 'Human activities influence weathering in the following ways:',
      items: [['Quarrying and construction:', 'Quarries, road cuts and building sites, as around Garoua, break rocks and expose fresh surfaces to the weather. They speed up weathering locally.'],
        ['Agriculture and deforestation:', 'Clearing forests and ploughing remove the protective plant cover. The bare rocks and soils are then exposed to strong heating and to rain.'],
        ['Pollution:', 'Smoke from vehicles, factories and power stations produces acid rain. It dissolves limestone and marble and damages buildings and monuments.']] },
  ],
  evaluation: [['Why is climate the most important factor of weathering in North Cameroon?', 'Strong heat causes exfoliation and speeds up chemical reactions, while the heavy rains provide water for chemical weathering.'],
    ['How can vegetation both increase and reduce weathering?', 'Roots split rocks, but a dense cover protects rocks from sun and rain.']],
  remediation: ['The diagram linking climate and weathering is by ______.', 'Limestone weathers faster than ______.', 'Acid rain speeds up ______ weathering.'],
  remediationAnswers: '1. Peltier 2. granite 3. chemical',
  homework: 'Define regolith.',
  hwAnswer: 'Regolith is the layer of loose, weathered material covering the solid bedrock.',
  bilingual: [['Weathering', "L'altération"], ['Climate', 'Le climat'], ['Rock', 'La roche'], ['Relief', 'Le relief'], ['Vegetation', 'La végétation'], ['Acid rain', 'Les pluies acides']],
});

L.push({ no: 11, title: 'The Impact of Weathering', topic: T, subtopic: W, pointPerSlide: true,
  notions: 'Regolith, soil, humus, construction materials, residual ores, bauxite, inselberg, leaching.',
  focus: 'Products of weathering as a resource (regolith, soil, materials, ores); positive and negative effects of weathering on the landscape and on man.',
  competence: 'Learners are able to explain the value of weathering products and the damage weathering causes.',
  objectives: ['Define regolith and soil.', 'Explain the economic importance of weathering products.', 'Explain the positive effects of weathering.', 'Explain its negative effects.'],
  recall: ['Climate controls weathering.', 'Oxidation gives red soils.', 'The North grows cotton, millet and sorghum.'],
  situation: 'You help your family prepare a millet field near Garoua. As you dig, you feel the soft soil that will feed the crops. On the way home, you see cracks in the wall of an old building and potholes in the tarred road. You think: the same natural force that makes good soil for our farms also destroys the walls and roads we build. You ask: "How can weathering be both useful and harmful?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand the positive and negative impacts of weathering.'],
    ['What is the layer of loose weathered material called?', 'Regolith; its upper part is the soil.'],
    ['Give one harmful effect of weathering.', 'It damages buildings and roads.']],
  justification: 'This lesson shows the importance of weathering for farming, building and mining, and the costs it causes.',
  action: 'Protect farm soils from erosion and maintain buildings and roads regularly.',
  activities: [
    { sec: '1. PRODUCTS', img: 'soil_profile_big.png', caption: 'A soil profile.', q: 'What lies at the bottom of the soil profile?', a: 'The hard rock (bedrock).', noProj: 'draw a soil profile.' },
    { sec: '1. PRODUCTS', img: 'lsa_bauxite.jpg', caption: 'Bauxite.', q: 'Which metal is made from bauxite?', a: 'Aluminium.', noProj: 'name the bauxite of Minim-Martap.' },
    { sec: '2. POSITIVE EFFECTS', img: 'f2t_cotton_field.jpg', caption: 'A cotton field.', q: 'Why is soil the most important product of weathering?', a: 'It supports all farming and ecosystems.', noProj: 'name crops of the North.' },
    { sec: '2. POSITIVE EFFECTS', img: 'lsa_mandara.jpg', caption: 'Landscape near Rhumsiki.', q: 'How can weathered landscapes help the economy?', a: 'They attract tourists.', noProj: 'describe Rhumsiki.' },
    { sec: '3. NEGATIVE EFFECTS', img: 'f4_oldwall.jpg', caption: 'A weathered old wall.', q: 'Give one negative effect of weathering.', a: 'Damage to buildings and roads, landslides or leaching of soils.', noProj: 'look for cracks on the school walls.' },
  ],
  summary: [
    D([['Regolith:', 'It is the layer of loose, weathered rock, gravel, sand and clay covering the bedrock.'],
      ['Soil:', 'It is the upper part of the regolith, mixed with water, air and humus, which supports plants.'],
      ['Inselberg:', 'It is an isolated hill of hard rock rising steeply from a plain.'],
      ['Leaching:', 'It is the washing of nutrients down the soil, out of reach of plant roots.']]),
    { title: '1. Products of Weathering as a Resource', intro: 'The products of weathering have the following economic importance:',
      items: [['Soil for agriculture:', 'Weathering produces the regolith, whose upper part becomes soil, the basis of all farming. In the North, cotton, millet, sorghum and groundnuts are grown on soils formed by the weathering of rocks.', 'f2t_cotton_field.jpg', 'a cotton field'],
        ['Construction materials:', 'Weathering produces sand, gravel and clay. Sand and gravel are used to make concrete and roads, and clay is used to make bricks, tiles and pottery.'],
        ['Mineral ores:', 'Chemical weathering removes unwanted minerals and concentrates useful ones, such as bauxite and iron ore. The bauxite deposits of Minim-Martap in the Adamawa and Fongo-Tongo in the West formed in this way.', 'lsa_bauxite.jpg', 'bauxite'],
        ['Groundwater storage:', 'The thick regolith is porous and stores rainwater like a sponge. It feeds the wells and boreholes that supply water to villages and towns.']] },
    { title: '2. Effects of Weathering on the Landscape', intro: 'Weathering shapes the landscape in the following ways:',
      items: [['Inselbergs and tors:', 'Deep weathering attacks the jointed rock, and the weathered material is later removed, leaving hard blocks standing above the plain. These form inselbergs and piles of boulders called tors, common around Garoua and in the Mandara Mountains.', 'inselberg.jpg', 'an inselberg'],
        ['Rounded boulders and domes:', 'Exfoliation and pressure release remove curved sheets of rock. They give rounded boulders and large bare domes of granite.', 'lsa_mandara.jpg', 'the landscape of Rhumsiki'],
        ['Karst landscapes:', 'The solution of limestone forms caves, sinkholes and bare rock pavements. Rivers may disappear underground in these regions.'],
        ['Deep regolith and laterite:', 'In hot, wet regions, weathering can reach tens of metres deep. Iron oxides can harden into laterite crusts that form flat-topped hills.']] },
    { title: '3. Effects of Weathering on Man', intro: 'Weathering affects man in the following ways:',
      items: [['Farming and tourism:', 'Weathering creates the soils that feed the population. Its landforms, such as the inselbergs and volcanic necks of Rhumsiki, attract tourists and bring income.'],
        ['Damage to structures:', 'Weathering cracks walls, makes potholes in roads and weakens bridges and monuments. Their repair costs a lot of money every year.', 'f4_oldwall.jpg', 'a weathered wall'],
        ['Slope hazards:', 'Deeply weathered rock on steep slopes becomes weak and unstable. It favours landslides and rockfalls, as in the Western Highlands during the rainy season.'],
        ['Loss of soil fertility:', 'In hot, wet regions, intense weathering and leaching wash the nutrients out of the soil. Laterite crusts also form hard layers that are difficult to cultivate.', 'geo2_wimpact.png', 'the impacts of weathering']] },
  ],
  evaluation: [['Give two economic uses of weathering products.', 'Soils for farming, sand and gravel for building, clay for bricks, bauxite ore (any two).'],
    ['Give one positive and one negative effect of weathering.', 'Positive: soil formation; negative: damage to buildings and roads.']],
  remediation: ['The loose layer above the bedrock is the ______.', 'Aluminium comes from ______.', 'The washing of nutrients down the soil is ______.'],
  remediationAnswers: '1. regolith 2. bauxite 3. leaching',
  homework: 'Define mass wasting.',
  hwAnswer: 'Mass wasting is the movement of rock, soil and debris down a slope under the influence of gravity.',
  bilingual: [['Weathering', "L'altération"], ['Soil', 'Le sol'], ['Regolith', 'Le régolithe'], ['Landscape', 'Le paysage'], ['Resource', 'La ressource'], ['Leaching', 'Le lessivage']],
});

L.push({ no: 12, title: 'Mass Wasting (Movement)', topic: T, subtopic: M, pointPerSlide: true,
  notions: 'Mass wasting, gravity, angle of repose, soil creep, terracettes, tension cracks, fall, slide, flow, Carson and Kirkby.',
  focus: 'Meaning and evidence of mass wasting; factors influencing it; classification by speed and water content (Carson and Kirkby).',
  competence: 'Learners are able to recognise signs of mass wasting, explain its factors and classify its types.',
  objectives: ['Define mass wasting.', 'Identify the evidence of mass wasting.', 'Explain its factors.', 'Classify mass movements by speed and water content.'],
  recall: ['Weathered material moves down slopes.', 'Water adds weight to soil.', 'Roots bind the soil.'],
  situation: 'In the rainy season, you travel on the road from Garoua towards Maroua through hilly areas. A telephone pole on a hillside, straight last year, now leans downhill. Further on, part of a muddy slope has slid onto the road and workers are clearing it. You ask: "Why is the ground moving, and why does a whole part of a hill suddenly give way, especially when it rains a lot?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the causes and types of mass wasting.'],
    ['What is the movement of soil and rock down a slope called?', 'Mass wasting (mass movement).'],
    ['Is the leaning pole the same as the slide onto the road?', 'No: the pole shows slow creep, the road shows a fast slide or flow.']],
  justification: 'This lesson helps us to recognise dangerous slopes and to avoid building or travelling where the ground may move.',
  action: 'Report signs of moving slopes (cracks, leaning poles) to the authorities.',
  activities: [
    { sec: '1. EVIDENCE', img: 'creep.gif', caption: 'Animation: soil creep.', q: 'Give one sign of soil creep.', a: 'Leaning poles or fences, curved tree trunks, terracettes.', noProj: 'list signs on the board.' },
    { sec: '1. EVIDENCE', img: 'geo2_mw_evidence.png', caption: 'Evidence of mass wasting.', q: 'What do tension cracks at the top of a slope show?', a: 'That part of the slope is starting to pull away.', noProj: 'draw a slope with cracks.' },
    { sec: '2. FACTORS', img: 'geo2_mw_factors.png', caption: 'Factors of mass wasting.', q: 'What is the most common trigger of mass wasting?', a: 'Heavy rainfall (water).', noProj: 'tilt a book with an eraser on it.' },
    { sec: '3. CLASSIFICATION', img: 'carson_kirkby_big.png', caption: 'Classification of mass movements.', q: 'Which movement is fast and dry?', a: 'A rockfall.', noProj: 'draw the triangle.' },
    { sec: '3. CLASSIFICATION', img: 'f4_landslide.jpg', caption: 'A landslide.', q: 'Is a landslide slow or fast?', a: 'Fast.', noProj: 'describe a landslide on a road.' },
  ],
  summary: [
    D([['Mass wasting (mass movement):', 'It is the large-scale movement of rock, soil and debris down slopes under the direct influence of gravity.'],
      ['Angle of repose:', 'It is the steepest angle at which loose material remains stable.'],
      ['Terracettes:', 'They are small step-like ridges formed on grassy slopes by soil creep.']]),
    { title: '1. Meaning and Evidence of Mass Wasting', intro: 'Mass wasting and its evidence are explained as follows:',
      items: [['Meaning:', 'Mass wasting is the movement of weathered material down a slope as a single mass, pulled by gravity. Unlike erosion, it needs no transporting agent such as a river or wind.', 'creep_last.png', 'soil creep'],
        ['Tilted objects and curved trees:', 'Fences, electric poles, gravestones and walls lean downhill because the soil below them moves. Trees keep growing upwards while the soil moves, so their trunks curve at the base.'],
        ['Terracettes and tension cracks:', 'Small step-like ridges called terracettes form on grassy slopes. Cracks at the top of a slope show that a block of land is pulling away and may slide.', 'geo2_mw_evidence.png', 'evidence of mass wasting']] },
    { title: '2. Factors of Mass Wasting', intro: 'Mass wasting is influenced by the following factors:',
      items: [['Gravity and slope angle:', 'Gravity is the force that pulls material downhill, and it acts more strongly on steep slopes. When a slope becomes steeper than the angle of repose of its material, it becomes unstable.', 'geo2_mw_factors.png', 'the factors of mass wasting'],
        ['Water:', 'Heavy or prolonged rain adds weight to the soil and reduces the friction between its particles. It is the most common trigger of landslides, especially at the end of the rainy season.'],
        ['Vegetation:', 'Roots bind the soil and plants absorb part of the rainwater. Deforestation, bush fires and overgrazing remove this protection and make slopes unstable.'],
        ['Human activities and vibrations:', 'Road cuts, quarries and houses built on steep slopes remove the support at the foot of slopes or add weight at the top. Earthquakes, blasting and heavy traffic shake the ground and can set off movements.']] },
    { title: '3. Classification of Mass Wasting', intro: 'Carson and Kirkby classify mass movements as follows:',
      items: [['Basis of the classification:', 'The triangular graph of Carson and Kirkby classifies movements by their speed and their water content. Its three corners are heave (slow, like creep), flow (wet) and slide (fast and dry).', 'carson_kirkby_big.png', "Carson and Kirkby's triangle"],
        ['Heave (slow movements):', 'Heave movements, such as soil creep, are very slow, a few millimetres to centimetres a year. They are caused by the repeated expansion and contraction of the soil when it wets and dries.'],
        ['Slides and falls (fast, dry movements):', 'In slides, a block moves quickly over a distinct surface, as in landslides and slumps. In falls, rocks drop freely from cliffs.', 'f4_landslide.jpg', 'a landslide'],
        ['Flows (wet movements):', 'In flows, the material contains much water and moves like a thick liquid. Solifluction is a slow flow, while mudflows are fast.']] },
  ],
  evaluation: [['How does removing trees from a steep slope increase the risk of mass wasting?', 'Without roots, the soil is no longer bound and absorbs more water, so it slides more easily.'],
    ['Give two pieces of evidence of soil creep.', 'Leaning poles or fences, curved tree trunks, terracettes (any two).']],
  remediation: ['The main force of mass wasting is ______.', 'The slowest mass movement is soil ______.', 'A fast, wet movement is a ______.'],
  remediationAnswers: '1. gravity 2. creep 3. flow (mudflow)',
  homework: 'Name one slow mass movement.',
  hwAnswer: 'Soil creep or solifluction.',
  bilingual: [['Mass wasting', 'Le mouvement de masse'], ['Gravity', 'La gravité'], ['Slope', 'La pente'], ['Landslide', 'Le glissement de terrain'], ['Soil creep', 'La reptation du sol'], ['Rockfall', "L'éboulement"]],
});

L.push({ no: 13, title: 'Processes and Features of Mass Wasting', topic: T, subtopic: M, pointPerSlide: true,
  notions: 'Soil creep, solifluction, landslide, slump, mudflow, debris flow, rockfall, scree (talus), afforestation, retaining wall, terracing, zoning.',
  focus: 'Slow mass movements (creep, solifluction); fast mass movements (landslides, slumps, mudflows, rockfalls); impacts on man and the environment; control measures.',
  competence: 'Learners are able to describe the types of mass movements, explain their impacts and propose measures to control them.',
  objectives: ['Describe slow mass movements.', 'Describe fast mass movements and their features.', 'Explain the impacts of mass wasting.', 'Propose solutions to control mass wasting.'],
  recall: ['Water is the main trigger of mass wasting.', 'Creep is slow and falls are fast.', 'The angle of repose limits stable slopes.'],
  situation: 'At the peak of the rainy season, you pass a steep road cutting near the high banks of the Benue. A large section of soil and rock that was stable in the dry season has collapsed, leaving a fresh scar on the slope. A small tree at the edge now leans at a strange angle. You ask: "What force made this part of the slope fall suddenly, can it also happen slowly, and how can we prevent it?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the types of mass movements and how to control them.'],
    ['What is a very slow movement that tilts trees over years?', 'Soil creep.'],
    ['What is a sudden collapse after heavy rain?', 'A fast mass movement such as a landslide or a slump.']],
  justification: 'This lesson helps us to protect lives, houses and roads from landslides and bank collapses.',
  action: 'Plant trees and keep drains clear on slopes near your home.',
  activities: [
    { sec: '1. SLOW MOVEMENTS', img: 'lsa_solifluction.jpg', caption: 'Solifluction lobes.', q: 'What is solifluction?', a: 'The slow flow of waterlogged soil over impermeable ground.', noProj: 'describe waterlogged soil.' },
    { sec: '2. FAST MOVEMENTS', img: 'lsa_slump.jpg', caption: 'A slump.', q: 'How does a slump move?', a: 'Along a curved surface, with the block rotating backwards.', noProj: 'draw a curved slip surface.' },
    { sec: '2. FAST MOVEMENTS', img: 'lsa_scree.jpg', caption: 'Scree at the foot of a cliff.', q: 'What is the pile of rocks at the foot of a cliff called?', a: 'Scree (talus).', noProj: 'pour gravel into a pile.' },
    { sec: '3. IMPACTS', img: 'lsa_landscar.jpg', caption: 'A landslide scar.', q: 'Give one impact of mass wasting on man.', a: 'Deaths, destroyed houses and farms, blocked roads.', noProj: 'list impacts on the board.' },
    { sec: '4. SOLUTIONS', img: 'f4_terraces.jpg', caption: 'Terraced slopes.', q: 'How do terraces reduce mass wasting?', a: 'They reduce the slope angle and slow down runoff.', noProj: 'describe terraces in the Mandara Mountains.' },
  ],
  summary: [
    D([['Solifluction:', 'It is the slow flow of waterlogged soil over impermeable or frozen ground.'],
      ['Slumping:', 'It is the sliding of a mass of material along a curved surface, with a backward rotation.'],
      ['Subsidence:', 'It is the sinking of the ground surface into a hollow below it.'],
      ['Scree (talus):', 'It is the pile of rock fragments at the foot of a cliff.']]),
    { title: '1. Slow Mass Movements', intro: 'The slow mass movements are the following:',
      items: [['Soil creep:', 'Soil creep is the very slow downhill movement of soil, a few centimetres a year, caused by wetting and drying or heating and cooling. It is shown by tilted poles, curved tree trunks and cracked walls and roads.', 'creep_last.png', 'soil creep'],
        ['Solifluction:', 'Solifluction is the slow flow of waterlogged soil over frozen ground or impermeable clay. It forms tongue-shaped lobes on slopes, especially in cold regions when the top layer thaws.', 'lsa_solifluction.jpg', 'solifluction lobes']] },
    { title: '2. Fast Mass Movements', intro: 'The fast mass movements are the following:',
      items: [['Landslides and slumps:', 'In a landslide, a mass of rock or soil slides rapidly down a slope over a flat surface. In a slump, it slides along a curved surface and rotates backwards, as on the banks of the Benue after heavy rain.', 'lsa_slump.jpg', 'a slump'],
        ['Rockfalls:', 'Blocks of rock loosened by weathering fall freely from steep cliffs. They pile up at the foot of the cliff and form scree.', 'lsa_scree.jpg', 'scree'],
        ['Mudflows and debris flows:', 'After heavy rain, a mixture of water, soil and rocks rushes down valleys like wet concrete. They are very destructive and can travel several kilometres.', 'lsa_lahar.jpg', 'a mudflow'],
        ['Subsidence:', 'The ground sinks vertically into a hollow below it, such as a cave in limestone or an old mine. Pumping too much groundwater can also make the land sink, as in parts of Mexico City.']] },
    { title: '3. Impacts of Mass Wasting', sub: 'A) Impacts on Man', intro: 'Mass wasting has the following impacts on man:',
      items: [['Loss of life:', 'Fast movements bury people in their houses, often at night. The landslide at Gouache, in Bafoussam, killed more than 40 people in October 2019.', 'lsa_landscar.jpg', 'a landslide scar'],
        ['Destruction of property:', 'Houses, farms and livestock are destroyed or buried. Many families lose their homes and their means of living.'],
        ['Damage to infrastructure:', 'Roads, railways, bridges and pipes are cut or blocked. Their repair and the cleaning of debris cost large sums of money.']] },
    { title: '3. Impacts of Mass Wasting', sub: 'B) Impacts on the Environment', intro: 'Mass wasting has the following impacts on the environment:',
      items: [['Scars on the landscape:', 'Landslides leave bare scars on the slopes and piles of debris at their foot. The soil is lost and takes a long time to form again.'],
        ['Damming of rivers:', 'Debris can block a river and form a temporary lake upstream. When the dam breaks, it causes sudden floods downstream.'],
        ['Destruction of habitats:', 'Forests and grasslands are destroyed, and animals lose their homes. The sediments also pollute rivers and harm fish.']] },
    { title: '4. Solutions', intro: 'Mass wasting is controlled by the following measures:',
      items: [['Afforestation:', 'Planting trees and grass binds the soil with their roots and reduces the water that enters it. It is the cheapest way to stabilise slopes.', 'geo2_mw_solutions.png', 'solutions to mass wasting'],
        ['Drainage of slopes:', 'Channels and pipes remove excess water from slopes before it soaks in. This keeps the soil dry and heavy slopes lighter.'],
        ['Retaining walls and terracing:', 'Strong walls at the foot of slopes hold back soil and rock, and wire nets stop falling rocks. Terraces, as in the Mandara Mountains, reduce the angle of slopes and slow runoff.', 'f4_terraces.jpg', 'terraces'],
        ['Land-use planning and warning:', 'Maps show the high-risk zones, and laws forbid building on them. Monitoring of cracks and rainfall allows people to be evacuated in time.']] },
  ],
  evaluation: [['Distinguish soil creep from a landslide.', 'Soil creep is a very slow, continuous movement of soil; a landslide is a sudden, rapid movement of a large mass.'],
    ['Give two measures to control mass wasting.', 'Afforestation, drainage, retaining walls, terracing, zoning (any two).']],
  remediation: ['A slide along a curved surface is a ______.', 'Rock fragments at the foot of a cliff form ______.', 'Planting trees on slopes is ______.'],
  remediationAnswers: '1. slump 2. scree (talus) 3. afforestation',
  homework: 'Name the three types of work of a river.',
  hwAnswer: 'Erosion, transportation and deposition.',
  bilingual: [['Mass wasting', 'Le mouvement de masse'], ['Landslide', 'Le glissement de terrain'], ['Soil creep', 'La reptation du sol'], ['Mudflow', 'La coulée de boue'], ['Retaining wall', 'Le mur de soutènement'], ['Terracing', 'Les cultures en terrasses']],
});

L.push({ no: 14, title: 'Erosional Processes and the Fluvial System', topic: T, subtopic: E, pointPerSlide: true,
  notions: 'River system, input, output, hydraulic action, abrasion, attrition, solution, traction, saltation, suspension, load, deposition.',
  focus: 'The river as a system; river erosion (four processes); transportation (four methods); deposition and its conditions.',
  competence: 'Learners are able to explain how a river erodes, carries and deposits material, using the Benue as an example.',
  objectives: ['Describe the river as an open system.', 'Explain the four processes of river erosion.', 'Explain the four methods of transportation.', 'Explain why and where a river deposits its load.'],
  recall: ['Erosion removes weathered material.', 'The Benue flows past Garoua.', 'The Benue has sandbanks in the dry season.'],
  situation: 'In the rainy season, you stand on the bridge of Garoua and look at the Benue: it is wide, fast and brown, carrying soil, branches and debris. In the dry season, from the same place, the river is low, slow and clearer, and huge sandbanks appear where deep water flowed before. You ask: "Where did all the brown mud go, and where did this new sand come from?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how a river erodes, carries and deposits material.'],
    ['What is the river doing in the rainy season?', 'Eroding its banks and transporting a large load.'],
    ['Why do sandbanks appear in the dry season?', 'The river slows down, loses energy and deposits its load.']],
  justification: 'This lesson helps us to understand the changing channel of the Benue, which affects farming, fishing and navigation.',
  action: 'Protect river banks with vegetation and avoid building on unstable banks.',
  activities: [
    { sec: '1. RIVER SYSTEM', img: 'open_system_big.png', caption: 'An open system.', q: 'Give one input of a river system.', a: 'Rainwater (or sediments from the slopes).', noProj: 'draw inputs, stores and outputs.' },
    { sec: '2. EROSION', img: 'river_erosion_big.png', caption: 'The four processes of erosion.', q: 'Distinguish abrasion from attrition.', a: 'Abrasion: the load scrapes the bed and banks; attrition: stones hit each other and become smaller and rounder.', noProj: 'rub two stones together.' },
    { sec: '3. TRANSPORTATION', img: 'geo2_transport.png', caption: 'Four ways of carrying the load.', q: 'Which method carries the largest amount of load?', a: 'Suspension.', noProj: 'shake a bottle with water, sand and soil.' },
    { sec: '3. TRANSPORTATION', img: 'f4_muddyriver.jpg', caption: 'A muddy river.', q: 'Why is the Benue brown in the rainy season?', a: 'It carries a lot of silt and clay in suspension.', noProj: 'compare rainy and dry seasons.' },
    { sec: '4. DEPOSITION', img: 'load.gif', caption: 'Animation: the load settles.', q: 'Which material is deposited first?', a: 'The heaviest (boulders and pebbles).', noProj: 'let the shaken bottle settle.' },
  ],
  summary: [
    D([['Erosion:', 'It is the wearing away and removal of material by rivers, wind, ice or waves.'],
      ['Transportation:', 'It is the movement of eroded material by a river, wind, ice or waves.'],
      ['Deposition:', 'It is the dropping of the load when a river loses energy.'],
      ['Competence:', 'It is the size of the largest particle that a river can carry.'],
      ['Capacity:', 'It is the total amount of load that a river can carry.']]),
    { title: '1. Erosion', sub: 'A) Processes of River Erosion', intro: 'A river erodes its bed and banks by the following processes:',
      items: [['Hydraulic action:', 'The force of the moving water hits the bed and banks and compresses air in cracks. When the water retreats, the air expands suddenly and breaks pieces off.', 'river_erosion_big.png', 'river erosion'],
        ['Abrasion (corrasion):', 'The stones and sand carried by the river scrape and grind the bed and banks like sandpaper. It is the main process of erosion in most rivers.'],
        ['Attrition:', 'The stones carried by the river knock against each other and break into smaller, rounder pieces. It does not erode the channel but reduces the size of the load.'],
        ['Solution (corrosion):', 'The river water, which is slightly acidic, dissolves soluble rocks such as limestone. The dissolved minerals are then carried away invisibly.']] },
    { title: '1. Erosion', sub: 'B) Types of River Erosion', intro: 'A river erodes in the following directions:',
      items: [['Vertical erosion:', 'The river cuts down into its bed and deepens its valley. It dominates in the upper course, where the gradient is steep.'],
        ['Lateral erosion:', 'The river erodes its banks sideways and widens its valley. It dominates in the middle and lower courses, where the river meanders.'],
        ['Headward erosion:', 'The river erodes backwards at its source and lengthens its valley upstream. It can lead to river capture, when a river takes the headwaters of another.']] },
    { title: '2. Transportation', sub: 'A) Sources and Types of Load', intro: 'The load of a river has the following sources and is carried in the following ways:',
      items: [['Sources of load:', 'The load comes from the erosion of the bed and banks and from material brought from the valley slopes by mass movement and runoff. Tributaries and wind also add material.'],
        ['Traction and saltation (bed load):', 'The largest boulders roll along the bed (traction), and pebbles and sand bounce along it (saltation). This bed load moves only when the river is in flood.', 'geo2_transport.png', 'the methods of transport'],
        ['Suspension:', 'Fine silt and clay are carried within the water, which makes it brown. It is the largest part of the load of most rivers, like the Benue in the rainy season.', 'f4_muddyriver.jpg', 'a muddy river'],
        ['Solution:', 'Dissolved minerals are carried invisibly in the water. They come mainly from the chemical weathering of rocks in the basin.']] },
    { title: '2. Transportation', sub: 'B) The Hjulström Graph', intro: 'The Hjulström graph explains erosion, transport and deposition as follows:',
      items: [['The graph:', 'It shows the velocity needed to erode, transport and deposit particles of different sizes. Sand is the easiest to erode, while clay needs a high velocity because its particles stick together.', 'hjulstrom_big.png', 'the Hjulström graph'],
        ['Transport and deposition:', 'Once eroded, particles can be carried at lower velocities than those needed to erode them. When the velocity falls below the settling velocity, the particles are deposited, the largest first.'],
        ['Competence and capacity:', 'The competence is the size of the largest particle the river can carry, and the capacity is the total load it can carry. Both increase greatly with velocity and discharge, so a river in flood carries huge boulders.']] },
    { title: '3. Deposition', intro: 'A river deposits its load in the following conditions:',
      items: [['Loss of velocity:', 'Deposition happens when the river slows down, on the inside of bends, on flat land or where it enters a lake or the sea. The heaviest material is dropped first and the finest last.', 'load_mid.png', 'the load of a river'],
        ['Decrease in discharge:', 'In the dry season, the volume of water falls and the river can no longer carry its load. The Benue then leaves large sandbanks in its bed at Garoua.'],
        ['Increase in load:', 'When a river receives more load than it can carry, after a landslide or from a tributary, it drops the excess. It then builds bars and islands in its channel.']] },
    { title: '4. The River as a System and its Functions', intro: 'The river works as a system and has the following functions:',
      items: [['Inputs:', 'Rainwater, springs, tributaries and sediments from the valley slopes enter the river. The energy of the system comes from the height of the land.', 'open_system_big.png', 'the river as a system'],
        ['Processes in the channel:', 'The river uses its energy to erode, transport and deposit material. In doing so, it shapes valleys, waterfalls, meanders and floodplains.'],
        ['Outputs:', 'Water and sediments leave the system into a larger river, a lake or the sea. For example, the Benue flows into the Niger, which carries the water to the Gulf of Guinea.'],
        ['Functions in the natural environment:', 'Rivers drain the land and carry water and nutrients to plains and seas. They create fertile floodplains and provide habitats for fish, birds and plants.']] },
  ],
  evaluation: [['Distinguish abrasion from attrition.', 'Abrasion is the scraping of the bed and banks by the load; attrition is the collision of stones that makes them smaller and rounder.'],
    ['Give two conditions for river deposition.', 'Fall in water volume, entry into flat land, entry into a lake or the sea (any two).']],
  remediation: ['The rolling of boulders is ______.', 'Silt carried in the water moves by ______.', 'The Benue leaves ______ in the dry season.'],
  remediationAnswers: '1. traction 2. suspension 3. sandbanks',
  homework: 'Name the three courses of a river.',
  hwAnswer: 'The upper course, the middle course and the lower course.',
  bilingual: [['Erosion', "L'érosion"], ['Transportation', 'Le transport'], ['Deposition', 'Le dépôt'], ['River load', 'La charge du fleuve'], ['River bank', 'La berge'], ['Sandbank', 'Le banc de sable']],
});

L.push({ no: 15, title: 'River Action on its Long Profile', topic: T, subtopic: E, pointPerSlide: true,
  notions: 'Long profile, source, mouth, upper, middle and lower course, V-shaped valley, interlocking spurs, waterfall, gorge, meander, river cliff, slip-off slope, floodplain, ox-bow lake, levee, delta.',
  focus: 'The long profile; characteristics and landforms of the upper, middle and lower courses; application to the Benue.',
  competence: 'Learners are able to describe the changes of a river from source to mouth and explain the landforms of each course.',
  objectives: ['Define the long profile of a river.', 'Describe the upper course and its landforms.', 'Describe the middle course and its landforms.', 'Describe the lower course and its landforms.'],
  recall: ['Rivers erode, transport and deposit.', 'Deposition happens when rivers slow down.', 'The Benue rises on the Adamawa Plateau.'],
  situation: 'You travel from Garoua up to the Adamawa Plateau, near the source of streams that feed the Benue. In the hills, the streams are small, fast and noisy, tumbling over rocks in narrow valleys. Back in Garoua, the Benue is huge, wide, slow and quiet, flowing across a vast flat plain. You ask: "Why does the same river system behave so differently in the hills and on the plain?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how a river changes from source to mouth.'],
    ['What is the path of a river from source to mouth called?', 'The long profile.'],
    ['What is the main work of the river at Garoua?', 'Deposition, because it is in its lower course.']],
  justification: 'This lesson explains the landforms of river valleys, which influence farming, settlement and flooding in the Benue valley.',
  action: 'Use floodplains for farming but avoid building houses on them.',
  activities: [
    { sec: '1. LONG PROFILE', img: 'long_profile_big.png', caption: 'The long profile.', q: 'Where is the gradient steepest?', a: 'In the upper course.', noProj: 'draw the concave long profile.' },
    { sec: '2. UPPER COURSE', img: 'f4_waterfall.jpg', caption: 'A waterfall.', q: 'How does a waterfall form?', a: 'The river flows over hard rock and undercuts the soft rock below.', noProj: 'describe a waterfall in Cameroon.' },
    { sec: '3. MIDDLE COURSE', img: 'meander.gif', caption: 'Animation: a meander.', q: 'On which side of a meander is the river cliff?', a: 'On the outside of the bend.', noProj: 'draw a meander with its cliff and slip-off slope.' },
    { sec: '4. LOWER COURSE', img: 'oxbow.gif', caption: 'Animation: an ox-bow lake forms.', q: 'How is an ox-bow lake formed?', a: 'A meander is cut off from the main channel.', noProj: 'draw the stages.' },
    { sec: '4. LOWER COURSE', img: 'f4_floodplain.jpg', caption: 'A floodplain.', q: 'Why are floodplains fertile?', a: 'Floods deposit fresh silt each year.', noProj: 'talk about farms along the Benue.' },
  ],
  summary: [
    D([['Long profile:', 'It is the line showing the gradient of a river from its source to its mouth.'],
      ['Meander:', 'It is a wide bend of a river channel.'],
      ['Floodplain:', 'It is the wide, flat land beside a river covered by floods.'],
      ['Delta:', 'It is a fan-shaped area of deposits at the mouth of a river.']]),
    { title: '1. The Long Profile', intro: 'The long profile of a river is explained as follows:',
      items: [['Shape:', 'The long profile is a concave curve, steep near the source and almost flat near the mouth. The river tends to smooth it by eroding the steep parts and filling the low parts.', 'long_profile_big.png', 'the long profile'],
        ['Three courses:', 'The profile is divided into the upper, middle and lower courses. Each has its own gradient, work and landforms.', 'geo2_courses.png', 'the three courses']] },
    { title: '2. The Upper Course', intro: 'The upper course has the following characteristics and features:',
      items: [['Characteristics:', 'The gradient is steep, the channel is narrow and shallow and full of boulders, and the volume of water is small. The river uses its energy mainly for vertical erosion.'],
        ['V-shaped valleys and interlocking spurs:', 'The river cuts down quickly while weathering and mass movement wear back the valley sides, giving a V-shaped valley. The river winds around hard spurs of land, which seem to lock together.', 'vvalley_big.png', 'a V-shaped valley'],
        ['Waterfalls and gorges:', 'Where hard rock lies over soft rock, the soft rock is eroded faster and a waterfall forms. The waterfall slowly retreats upstream and leaves a gorge, as with the falls of the Vina near Ngaoundéré.', 'f4_waterfall.jpg', 'a waterfall'],
        ['Rapids and potholes:', 'Where bands of hard and soft rock alternate, the water flows fast and rough over rapids. Stones swirled by eddies drill round holes called potholes in the rock bed.']] },
    { title: '3. The Middle Course', intro: 'The middle course has the following characteristics and features:',
      items: [['Characteristics:', 'The gradient is gentler, the valley is wider and the volume of water is larger because of tributaries. Transport is the main work, and lateral erosion becomes more important.'],
        ['Meanders:', 'The river swings from side to side and forms wide bends called meanders. The fastest water flows on the outside of each bend.', 'meander_last.png', 'a meander'],
        ['River cliffs and slip-off slopes:', 'Fast water erodes the outside of the bend and forms a steep river cliff. Slow water deposits sand and gravel on the inside and forms a gentle slip-off slope.', 'rivercliff_big.png', 'a river cliff and slip-off slope']] },
    { title: '4. The Lower Course', sub: 'A) Characteristics and Floodplain Features', intro: 'The lower course has the following characteristics and features:',
      items: [['Characteristics:', 'The gradient is almost flat, the channel is wide and deep and the volume of water is at its largest. Deposition dominates, as on the Benue at Garoua.'],
        ['Floodplains:', 'When the river floods, it spreads over the flat land beside it and deposits silt. Over time, these deposits build a wide, very fertile floodplain used for farming.', 'f4_floodplain.jpg', 'a floodplain'],
        ['Levees:', 'During floods, the heaviest material is deposited first, just beside the channel. Repeated floods build natural raised banks called levees.'],
        ['Ox-bow lakes:', 'Erosion on the outside of two bends narrows the neck of a meander until the river cuts through it during a flood. The old bend is cut off and becomes a U-shaped ox-bow lake.', 'oxbow_last.png', 'an ox-bow lake']] },
    { title: '4. The Lower Course', sub: 'B) Features at the Mouth', intro: 'At its mouth, a river forms the following features:',
      items: [['Deltas:', 'Where a river enters a calm sea or lake, it deposits its load faster than waves and currents can remove it. The deposits build a fan-shaped delta crossed by many channels, like the Niger delta.', 'f4_delta.jpg', 'a delta'],
        ['Estuaries:', 'Where the sea has strong tides and currents, the load is carried away and the mouth remains a wide, open channel. The Wouri estuary at Douala is an example.']] },
  ],
  evaluation: [['Give three differences between the upper and the lower course of a river.', 'Upper: steep gradient, narrow V-shaped valley, vertical erosion; lower: flat gradient, wide floodplain, deposition.'],
    ['Why does the Benue at Garoua form sandbanks?', 'In its lower course it flows slowly on flat land and deposits its load, especially in the dry season.']],
  remediation: ['Vertical erosion dominates in the ______ course.', 'A cut-off meander forms an ______ lake.', 'Raised banks built by floods are ______.'],
  remediationAnswers: '1. upper 2. ox-bow 3. levees',
  homework: 'Define longshore drift.',
  hwAnswer: 'Longshore drift is the movement of sand and pebbles along a coast by waves that reach the shore at an angle.',
  bilingual: [['Upper course', 'Le cours supérieur'], ['Lower course', 'Le cours inférieur'], ['Meander', 'Le méandre'], ['Floodplain', "La plaine d'inondation"], ['Waterfall', 'La chute d\'eau'], ['Delta', 'Le delta']],
});

L.push({ no: 16, title: 'Coastal Processes and Features', topic: T, subtopic: E, pointPerSlide: true,
  notions: 'Coast, wave, fetch, tide, storm surge, hydraulic action, abrasion, attrition, solution, longshore drift, swash, backwash, cliff, wave-cut platform, cave, arch, stack, stump, beach, spit, bar.',
  focus: 'The coastal system and wave action; coastal processes (erosion, transportation, deposition); landforms of erosion and deposition; threats to coasts in Cameroon.',
  competence: 'Learners are able to explain coastal processes and landforms and the problems of the coast of Cameroon.',
  objectives: ['Describe waves, tides and storm surges.', 'Explain the processes of wave erosion.', 'Explain longshore drift.', 'Describe landforms of coastal erosion and deposition.', 'Explain the threats to coasts.'],
  recall: ['Rivers erode by hydraulic action, abrasion, attrition and solution.', 'Deposition happens when energy falls.', 'Kribi and Limbe are on the coast of Cameroon.'],
  situation: 'You travel from Garoua to Kribi for the holidays and see the sea for the first time. Unlike the Benue, which flows in one direction, the sea moves constantly, with waves crashing on the shore. You build a sandcastle, but a few hours later the rising water washes it away. In some places the shore is sandy and wide; in others, tall rocks are being worn away. You ask: "What forces shape and change the land where it meets the sea?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the processes and landforms of the coast.'],
    ['What gives waves their energy?', 'The wind blowing over the sea.'],
    ['Why was the sandcastle washed away?', 'The tide rose and brought the water further up the shore.']],
  justification: 'This lesson helps us to understand the coast of Cameroon, its landforms and the dangers faced by coastal towns.',
  action: 'Protect mangroves and beaches and avoid dumping waste on the coast.',
  activities: [
    { sec: '1. WAVES AND TIDES', img: 'f4_bigwaves.jpg', caption: 'Large waves.', q: 'Name one factor of the size of waves.', a: 'Wind speed, wind duration or the fetch.', noProj: 'blow over a basin of water.' },
    { sec: '2. EROSION', img: 'headland.gif', caption: 'Animation: erosion of a headland.', q: 'Put in order: arch, cave, stack, stump.', a: 'Cave, arch, stack, stump.', noProj: 'draw the four stages.' },
    { sec: '2. TRANSPORTATION', img: 'longshore.gif', caption: 'Animation: longshore drift.', q: 'Why does longshore drift move sand along the beach?', a: 'The swash comes up at an angle and the backwash goes straight down, so sand zig-zags along.', noProj: 'draw the zig-zag.' },
    { sec: '3. DEPOSITION', img: 'f4_spit.jpg', caption: 'A spit.', q: 'What is a spit?', a: 'A long ridge of sand or shingle joined to the land and projecting into the sea.', noProj: 'draw a spit and a bar.' },
    { sec: '4. THREATS', img: 'geo2_coast_threats.png', caption: 'Threats to the coast.', q: 'Give one threat faced by Kribi or Limbe.', a: 'Coastal erosion, flooding or pollution.', noProj: 'discuss coastal problems.' },
  ],
  summary: [
    D([['Coast:', 'It is the narrow zone where the land meets the sea.'],
      ['Fetch:', 'It is the distance of open water over which the wind blows.'],
      ['Wave refraction:', 'It is the bending of waves as they approach an irregular coastline.'],
      ['Longshore drift:', 'It is the movement of sediment along the coast by waves reaching the shore at an angle.'],
      ['Storm surge:', 'It is an abnormal rise of the sea level caused by a storm.']]),
    { title: '1. The Coast and the Coastal System', intro: 'The coast and the coastal system are explained as follows:',
      items: [['The coast:', 'The coast is the zone where the land meets the sea, from the highest level reached by storm waves to the lowest level of the tides. It is always changing because of waves, tides and currents.', 'usa_beach.jpg', 'a beach'],
        ['The coastal system:', 'Energy from waves, tides and winds and sediments from rivers and cliffs are the inputs of the system. Erosion, transport and deposition are its processes, and landforms and sediments carried out to sea are its outputs.']] },
    { title: '2. Factors Influencing Coasts', intro: 'The form of a coast depends on the following factors:',
      items: [['Wave energy:', 'Strong waves, driven by strong winds over a long fetch, erode the coast quickly. Sheltered coasts with weak waves favour deposition.'],
        ['Geology:', 'Hard rocks such as granite form headlands and high cliffs, while soft rocks such as clay are eroded into bays. The structure of the rocks, their joints and dip, also controls the shape of cliffs.'],
        ['Changes of sea level:', 'A rise of sea level drowns valleys and forms estuaries and rias, while a fall leaves raised beaches. The present rise of sea level increases erosion on many coasts.'],
        ['Human activities and vegetation:', 'Ports, sea walls and the removal of sand change the movement of sediments. Mangroves and dune vegetation protect coasts, and their destruction increases erosion.']] },
    { title: '3. Waves and Energy', intro: 'Waves carry energy to the coast in the following ways:',
      items: [['Formation of waves:', 'Wind blowing over the sea transfers energy to the water and forms waves. Their size depends on the wind speed, how long it blows and the fetch.', 'f4_bigwaves.jpg', 'large waves'],
        ['Breaking waves:', 'Near the shore, the base of the wave is slowed by the sea bed, and the top falls forward and breaks. Constructive waves have a strong swash and build beaches, while destructive waves have a strong backwash and erode them.'],
        ['Wave refraction:', 'Waves slow down in shallow water off headlands and bend so that they strike the headlands on three sides. Energy is concentrated on headlands, which are eroded, and spread out in bays, where deposition takes place.', 'refraction_big.png', 'wave refraction']] },
    { title: '4. Other Coastal Processes', intro: 'Coasts are also affected by the following processes:',
      items: [['Tides:', 'The sea rises and falls about twice a day because of the pull of the Moon and the Sun. The tidal range decides how much of the shore is attacked by waves.', 'tides.png', 'the tides'],
        ['Storm surges:', 'Strong winds and low pressure during a storm raise the sea level well above normal. The surge floods low coasts and causes severe erosion.'],
        ['Tsunamis:', 'Undersea earthquakes, eruptions or landslides set off giant waves that can reach tens of metres high at the coast. They flood the land and destroy everything in their path.', 'lsa_tsunami.jpg', 'a tsunami']] },
    { title: '5. Wave Erosion, Transport and Deposition', intro: 'Waves shape the coast by the following processes:',
      items: [['Wave erosion:', 'Waves erode the coast by hydraulic action, when water and compressed air break the rock, and by abrasion, when they throw sand and pebbles against cliffs. Attrition rounds the pebbles, and solution dissolves limestone.', 'geo2_coast.png', 'coastal processes'],
        ['Longshore drift:', 'Waves reaching the beach at an angle carry sediment up the beach in the swash, and the backwash brings it straight back down. The sediment therefore moves step by step along the coast.', 'longshore_last.png', 'longshore drift'],
        ['Deposition:', 'Waves drop their load where they lose energy, in sheltered bays, behind islands and where the coast changes direction. Constructive waves build beaches in these places.']] },
    { title: '6. Features Produced', sub: 'A) Features of Erosion', intro: 'Wave erosion produces the following features:',
      items: [['Headlands and bays:', 'Where hard and soft rocks alternate along the coast, the soft rocks are eroded into bays and the hard rocks remain as headlands. Refraction then concentrates erosion on the headlands.'],
        ['Cliffs and wave-cut platforms:', 'Waves cut a notch at the foot of a cliff; the rock above collapses and the cliff retreats. A flat rock platform, visible at low tide, is left in front of it.', 'f4_cliff.jpg', 'a cliff'],
        ['Caves, arches, stacks and stumps:', 'On a headland, waves widen a crack into a cave, and two caves meet to form an arch. The arch collapses and leaves a stack, which is worn down into a stump.', 'headland_last.png', 'the erosion of a headland']] },
    { title: '6. Features Produced', sub: 'B) Features of Deposition', intro: 'Wave deposition produces the following features:',
      items: [['Beaches:', 'Sand and shingle accumulate between the low and high tide levels, especially in bays. The beaches of Kribi and Limbe, with black volcanic sand at Limbe, are examples.'],
        ['Spits:', 'Where the coast changes direction, longshore drift continues to deposit sand into the sea. It builds a long, narrow ridge attached to the land at one end, often with a curved tip.', 'f4_spit.jpg', 'a spit'],
        ['Bars and tombolos:', 'A spit that grows across a bay forms a bar, which traps a lagoon behind it. A ridge of sand that joins an island to the mainland is a tombolo.']] },
    { title: '7. Threats to Coasts', intro: 'Coasts face the following threats:',
      items: [['Coastal erosion:', 'Beaches, roads and houses are lost as the coast retreats, especially at Kribi and Limbe. Sand mining on beaches makes erosion worse.', 'geo2_coast_threats.png', 'threats to coasts'],
        ['Flooding and sea-level rise:', 'Global warming is raising the sea level, and storm surges flood low areas. Parts of Douala and the Wouri estuary are threatened.'],
        ['Pollution:', 'Waste from towns and industries, and oil from ships and platforms, pollute the water and the beaches. They harm fishing and tourism.', 'usa_oilspill.jpg', 'an oil spill'],
        ['Destruction of mangroves:', 'Mangroves are cut for firewood, for smoking fish and to build houses, as around Douala. Without them, the coast loses its natural protection against waves and its fish nurseries.', 'lsa_mangrove.jpg', 'mangroves']] },
  ],
  evaluation: [['Explain how waves break a hard cliff.', 'Hydraulic action compresses air in cracks, abrasion hurls pebbles against the rock, and solution dissolves some minerals.'],
    ['Describe the formation of a stack.', 'A crack in a headland is enlarged into a cave, then an arch; the arch collapses, leaving a stack.']],
  remediation: ['The distance of open water over which wind blows is the ______.', 'Waves going up the beach are the ______.', 'A ridge of sand closing a bay is a ______.'],
  remediationAnswers: '1. fetch 2. swash 3. bar',
  homework: 'Name the highest mountain of Cameroon.',
  hwAnswer: 'Mount Cameroon (4,095 m).',
  bilingual: [['Coast', 'La côte'], ['Wave', 'La vague'], ['Erosion', "L'érosion"], ['Beach', 'La plage'], ['Tide', 'La marée'], ['Cliff', 'La falaise']],
});

module.exports = { B, L };
