// LOWER SIXTH ARTS — Geomorphology, part 2: Lessons 4–8 (landforms at plate margins; volcanicity; earthquakes)
// Rewritten from the teacher's course support (LSA_LESSON_GEOMO_2026) in our own words; facts checked and updated.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const { B } = require('./lsageo_1');
const L = [];
const T1 = "The Development of the Earth's Structure", T2 = 'Crustal Processes and their Effect on the Land Surface and Man';

L.push({ no: 4, title: 'Landforms at Constructive or Divergent Margins', topic: T1, subtopic: 'Theories of Earth Structure and Resultant Landforms', pointPerSlide: true,
  notions: 'Divergence, tension, fault, rift valley (graben), block mountain (horst), escarpment, basin and range, mid-ocean ridge, shield volcano.',
  focus: 'Divergence and faulting; landforms of continental rifting (rift valley, horst, escarpment, basin and range, the Benue Trough); landforms of oceanic spreading (ridges, shield volcanoes); associated hazards.',
  competence: 'Learners are able to explain the formation of rift valleys, block mountains and ridges and relate them to the Benue Trough.',
  objectives: ['Explain how tension creates faults.', 'Explain the formation of rift valleys and block mountains.', 'Describe the landforms of oceanic spreading.', 'Describe the hazards of divergent margins.'],
  recall: ['At a divergent margin, plates move apart.', 'A fault is a crack along which rocks have moved.', 'Mid-ocean ridges are made of basalt.'],
  situation: 'You travel by bus from Garoua to Ngaoundéré. After the wide, flat plain of the Benue, the road climbs a long, steep slope. From the top, you look back and see the vast low valley stretching for kilometres, as if a huge piece of land had sunk between two higher blocks. You ask: "Why is the landscape arranged like this, with a sunken basin next to high, steep-sided land?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how land sinks and rises along faults at divergent margins.'],
    ['What happens to the crust when it is stretched?', 'It cracks along faults.'],
    ['What do we call a block of land that has sunk between two faults?', 'A rift valley (graben).']],
  justification: 'This lesson explains the formation of major landforms of Africa and Cameroon, such as the Rift Valley and the Benue Trough.',
  action: 'Recognise fault landforms such as escarpments and valleys in the relief of Cameroon.',
  activities: [
    { sec: '1. FAULTING', img: 'horst_graben.gif', caption: 'Animation: a rift valley forms.', q: 'Which force pulls the crust apart at a divergent margin?', a: 'Tension.', noProj: 'pull a slab of clay apart.' },
    { sec: '2. CONTINENTAL RIFTING', img: 'f2t_rift_valley.jpg', caption: 'The Great Rift Valley.', q: 'What is the sunken block of a rift valley called?', a: 'The graben.', noProj: 'draw a graben between two faults.' },
    { sec: '2. CONTINENTAL RIFTING', img: 'lsa_escarpment.jpg', caption: 'An escarpment.', q: 'What is the steep slope at the edge of a horst called?', a: 'An escarpment (fault scarp).', noProj: 'describe the Adamawa escarpment.' },
    { sec: '3. OCEANIC SPREADING', img: 'lsa_shield.jpg', caption: 'A shield volcano.', q: 'Why are shield volcanoes wide with gentle slopes?', a: 'Their runny basic lava flows far before cooling.', noProj: 'pour honey and thick porridge to compare.' },
    { sec: '4. HAZARDS', img: 'f4_thingvellir.jpg', caption: 'A rift in Iceland.', q: 'Are earthquakes at divergent margins usually strong or weak?', a: 'Usually frequent but shallow and weak.', noProj: 'compare with destructive margins.' },
  ],
  summary: [
    D([['Constructive (divergent) margin:', 'It is a boundary where two plates move apart and new crust is formed.'],
      ['Faulting:', 'It is the breaking of rocks of the crust under stress, with movement of blocks along the fractures.'],
      ['Fault:', 'It is a fracture in the crust along which rocks have moved.'],
      ['Folding:', 'It is the bending of layers of rock under compression.']]),
    { title: '1. Divergence and Faulting', intro: 'At constructive margins, faulting takes place as follows:',
      items: [['Tension:', 'At a constructive margin, the plates move apart and the crust is stretched by tension. The brittle rocks of the crust cannot bend much, so they break.', 'horst_graben_last.png', 'horst and graben'],
        ['Normal faults:', 'Tension produces normal faults, in which one block slides down along a sloping fracture. Parallel faults divide the crust into blocks that move up or down.'],
        ['Result on the relief:', 'Faulting creates rift valleys, block mountains and escarpments on the continents. On the ocean floor, it creates the central rift of the mid-ocean ridges.']] },
    { title: '2. Major Landforms', sub: 'A) Ridges, Rift Valleys and Shield Volcanoes', intro: 'Divergence creates the following major landforms:',
      items: [['Mid-ocean ridges:', 'Where two oceanic plates move apart, rising magma builds long underwater mountain chains, like the Mid-Atlantic Ridge. They are cut by a central rift and by many transform faults.', 'seafloor_last.png', 'a mid-ocean ridge'],
        ['Rift valleys:', 'Where a continent is pulled apart, a long block sinks between two parallel faults and forms a rift valley (graben), like the Great Rift Valley of East Africa. The Benue Trough, in which the Benue flows past Garoua, is an old rift formed when Africa and South America separated.', 'f2t_rift_valley.jpg', 'a rift valley'],
        ['Shield volcanoes:', 'Magma at divergent margins is basic and runny, so lava flows far before it cools. It builds broad volcanoes with gentle slopes, as in Iceland and along the East African Rift.', 'lsa_shield.jpg', 'a shield volcano']] },
    { title: '2. Major Landforms', sub: 'B) Faulted Landforms', intro: 'Faulting at divergent margins creates the following landforms:',
      items: [['Block mountains (horsts):', 'A block of land left standing high between two faults, or pushed up, forms a block mountain with a flat top. The Ruwenzori Mountains, between Uganda and the Democratic Republic of Congo, are an example.'],
        ['Plateaux:', 'Where large blocks are uplifted as a whole, they form high, flat plateaux bounded by faults. Parts of the East African plateau were formed in this way.'],
        ['Escarpments (fault scarps):', 'An escarpment is the steep slope along the edge of a horst or a rift valley, which marks the line of the fault. Its steepness shows that the fault is recent or active.', 'lsa_escarpment.jpg', 'an escarpment'],
        ['Basin and range landscape:', 'Where the crust is stretched over a wide area, many parallel faults form alternating horsts (ranges) and grabens (basins). This landscape is found in Nevada and Utah in the United States.']] },
    { title: '3. Volcanic Eruptions and Earthquakes', intro: 'Constructive margins have the following types of eruptions and earthquakes:',
      items: [['Fissure (Icelandic) eruptions:', 'Runny basaltic lava pours quietly out of long cracks in the ground. These eruptions build lava plateaux and give people time to move away.', 'f4_thingvellir.jpg', 'a fissure in Iceland'],
        ['Hawaiian-type eruptions:', 'Lava flows out of a central vent with fountains of red-hot lava but few explosions, because the magma contains little gas. They build shield volcanoes.'],
        ['Shallow earthquakes:', 'Movements along the faults cause frequent earthquakes, with a focus less than about 70 km deep. They are usually weaker than those of destructive and conservative margins.']] },
  ],
  evaluation: [['Explain the formation of a rift valley.', 'Tension pulls the crust apart; faults form and the block between two parallel faults sinks to form a graben.'],
    ['How was the Benue Trough formed?', 'By rifting when Africa separated from South America, which made a block of crust sink.']],
  remediation: ['A sunken block between two faults is a ______.', 'A block left standing high is a ______.', 'Shield volcanoes are built by ______ lava.'],
  remediationAnswers: '1. graben (rift valley) 2. horst (block mountain) 3. basic (runny)',
  homework: 'Name one range of fold mountains.',
  hwAnswer: 'The Himalayas, the Andes, the Alps, the Atlas or the Rockies (any one).',
  bilingual: [['Rift valley', 'Le fossé d\'effondrement'], ['Fault', 'La faille'], ['Block mountain', 'Le horst'], ['Escarpment', "L'escarpement"], ['Volcano', 'Le volcan'], ['Ridge', 'La dorsale']],
});

L.push({ no: 5, title: 'Landforms at Destructive and Conservative Margins', topic: T1, subtopic: 'Theories of Earth Structure and Resultant Landforms', pointPerSlide: true,
  notions: 'Convergence, subduction, Benioff zone, fold mountain, anticline, syncline, ocean trench, island arc, transform fault.',
  focus: 'Destructive margins: fold mountains, ocean trenches, island arcs, volcanoes and earthquakes; conservative margins: transform faults and earthquakes.',
  competence: 'Learners are able to explain the landforms and hazards of destructive and conservative margins with world examples.',
  objectives: ['Explain the formation of fold mountains.', 'Explain the formation of ocean trenches and island arcs.', 'Explain why destructive margins have volcanoes and earthquakes.', 'Describe conservative margins and their earthquakes.'],
  recall: ['At a destructive margin, plates move towards each other.', 'The denser plate sinks by subduction.', 'At a conservative margin, plates slide past each other.'],
  situation: 'On CRTV, a reporter explains that a small tremor was felt in Buea but that Mount Cameroon is monitored. Later, a documentary shows the huge Himalayas and the great earthquakes of Japan and California. In Garoua the ground is always still. You ask: "What happens when plates crash into each other or slide past each other, and what landforms and dangers do they create?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the landforms and hazards of destructive and conservative margins.'],
    ['What forms when two continental plates collide?', 'Fold mountains such as the Himalayas.'],
    ['Why is there no volcano on the San Andreas Fault?', 'Plates slide past each other, so no crust sinks and melts.']],
  justification: 'This lesson explains the highest mountains, the deepest trenches and the most dangerous hazards on Earth.',
  action: 'Locate the hazard zones of the world on a map of plate margins.',
  activities: [
    { sec: '1. FOLD MOUNTAINS', img: 'folding.gif', caption: 'Animation: rock layers fold.', q: 'What is an upward fold called?', a: 'An anticline.', noProj: 'push a pile of cloths to make folds.' },
    { sec: '1. FOLD MOUNTAINS', img: 'lsa_himalaya.jpg', caption: 'The Himalayas.', q: 'Which plates collide to form the Himalayas?', a: 'The Indian (Indo-Australian) and Eurasian plates.', noProj: 'locate the Himalayas.' },
    { sec: '1. TRENCHES AND ARCS', img: 'subduction_big.png', caption: 'Subduction.', q: 'What is the deepest trench in the world?', a: 'The Mariana Trench (about 11,000 m).', noProj: 'draw a trench and an island arc.' },
    { sec: '1. VOLCANOES', img: 'lsa_sthelens.jpg', caption: 'An explosive volcano.', q: 'Why are volcanoes at destructive margins explosive?', a: 'The sinking plate melts into thick, gas-rich magma.', noProj: 'compare with shield volcanoes.' },
    { sec: '2. CONSERVATIVE MARGINS', img: 'f4_sanandreas.jpg', caption: 'The San Andreas Fault.', q: 'What causes the strong earthquakes along this fault?', a: 'Plates get stuck, stress builds up and is suddenly released.', noProj: 'rub two rough blocks together.' },
  ],
  summary: [
    D([['Destructive (convergent) margin:', 'It is a boundary where two plates move towards each other and crust is destroyed.'],
      ['Conservative margin:', 'It is a boundary where two plates slide past each other without creating or destroying crust.'],
      ['Benioff zone:', 'It is the sloping zone of earthquakes along a sinking plate.'],
      ['Anticline and syncline:', 'An anticline is an upward fold of rock layers and a syncline is a downward fold.'],
      ['Tear (transform) fault:', 'It is a fault along which two blocks slide past each other horizontally.']]),
    { title: '1. Destructive (Convergent) Margins', sub: 'A) Folding and Fold Mountains', intro: 'Fold mountains are formed as follows:',
      items: [['Compression and folding:', 'When two plates collide, the layers of sedimentary rock between them are squeezed and bend into folds. Upward folds are called anticlines and downward folds synclines.', 'folding_last.png', 'folding'],
        ['Types of folds:', 'Gentle pressure forms simple, symmetrical folds, while stronger pressure forms asymmetrical and overturned folds. Very strong pressure lays the folds flat (recumbent folds) and can push them far forward as nappes, as in the Alps.'],
        ['Continent against continent:', 'When two continental plates collide, neither sinks, so the crust is crumpled and thickened into very high mountains. The Himalayas rose where the Indian plate pushes into the Eurasian plate.', 'lsa_himalaya.jpg', 'the Himalayas'],
        ['Ocean against continent:', 'When an oceanic plate sinks under a continental plate, the edge of the continent is folded and uplifted. The Andes rose in this way where the Nazca plate sinks under the South American plate.']] },
    { title: '1. Destructive (Convergent) Margins', sub: 'B) Trenches and the Benioff Zone', intro: 'Subduction forms the following features:',
      items: [['Ocean trenches:', 'Where a dense oceanic plate bends down into the mantle, a very deep, narrow trench forms on the ocean floor. The Mariana Trench in the Pacific is about 11,000 m deep, the deepest point on Earth.', 'subduction_big.png', 'subduction'],
        ['The Benioff zone:', 'As the plate sinks, friction and breaking of rocks cause earthquakes along a sloping zone that goes down to about 700 km. This zone, called the Benioff zone, shows the path of the sinking plate.']] },
    { title: '1. Destructive (Convergent) Margins', sub: 'C) Island Arcs, Volcanoes and Earthquakes', intro: 'Destructive margins also have the following features and activities:',
      items: [['Island arcs:', 'When two oceanic plates meet, one sinks and melts, and the rising magma builds a curved chain of volcanic islands. Japan, the Philippines and the Aleutian Islands are island arcs.'],
        ['Explosive volcanoes:', 'The melting of the sinking plate produces thick, sticky magma rich in silica and gas. It causes violent eruptions, as at Mount St Helens in 1980 and Mount Pinatubo in 1991.', 'lsa_sthelens.jpg', 'Mount St Helens'],
        ['Powerful earthquakes:', 'Earthquakes occur at all depths: shallow near the trench, intermediate and deep along the Benioff zone. The shallow ones are the strongest on Earth, like the Chile earthquake of 1960 (magnitude 9.5).']] },
    { title: '1. Destructive (Convergent) Margins', sub: 'D) Location on a Global Scale', intro: 'These features and processes are located in the following zones:',
      items: [['The Pacific Ring of Fire:', 'It surrounds the Pacific Ocean, from the Andes to Japan and New Zealand, and contains about 75 % of the active volcanoes of the world. About 80 % of the largest earthquakes of the world occur along it.', 'plates_big.png', 'the tectonic plates'],
        ['The Alpine–Himalayan belt:', 'It runs from the Atlas Mountains through the Alps, Turkey and Iran to the Himalayas. It is a zone of collision with young fold mountains and frequent earthquakes.']] },
    { title: '2. Conservative (Neutral) Margins', intro: 'Conservative margins have the following processes:',
      items: [['By-passing of plates:', 'The plates slide past each other in opposite directions, or in the same direction at different speeds. Crust is neither created nor destroyed, so there are no volcanoes.', 'f4_sanandreas.jpg', 'the San Andreas Fault'],
        ['Tear (transform) faulting:', 'The movement tears the crust along a long vertical fault, and the land on each side is offset. Rivers, roads and fences that cross the fault are displaced, as along the San Andreas Fault in California.'],
        ['Earthquakes:', 'The plates lock together by friction, and stress builds up for many years. When the rocks suddenly slip, a strong shallow earthquake occurs, like the San Francisco earthquake of 1906.']] },
  ],
  evaluation: [['Why do fold mountains form at destructive margins but not at conservative margins?', 'At destructive margins plates collide and compress rock layers; at conservative margins plates only slide past each other.'],
    ['Name one ocean trench and the island arc near it.', 'The Japan Trench and Japan, or the Mariana Trench and the Mariana Islands.']],
  remediation: ['An upward fold is an ______.', 'The deepest trench is the ______ Trench.', 'Conservative margins have earthquakes but no ______.'],
  remediationAnswers: '1. anticline 2. Mariana 3. volcanoes',
  homework: 'Distinguish magma from lava.',
  hwAnswer: 'Magma is molten rock below the surface; lava is molten rock that has reached the surface.',
  bilingual: [['Fold mountain', 'La chaîne de montagnes plissées'], ['Trench', 'La fosse océanique'], ['Earthquake', 'Le séisme'], ['Plate margin', 'La limite de plaque'], ['Anticline', "L'anticlinal"], ['Syncline', 'Le synclinal']],
});

L.push({ no: 6, title: 'Volcanism', topic: T2, subtopic: 'Volcanicity', pointPerSlide: true,
  notions: 'Volcanism (vulcanicity), magma, lava, active, dormant and extinct volcanoes, pyroclasts, basic and acid lava, cone, crater, caldera, lava plateau.',
  focus: 'Meaning of volcanism; the life cycle of volcanoes; products of eruptions; volcanic landforms (cones, lava plateaux, craters and calderas).',
  competence: 'Learners are able to classify volcanoes and explain the landforms built by different volcanic materials, with Cameroonian examples.',
  objectives: ['Define volcanism, magma and lava.', 'Distinguish active, dormant and extinct volcanoes.', 'Describe the products of an eruption.', 'Explain the formation of volcanic cones and other landforms.'],
  recall: ['Magma rises at weak zones of the crust.', 'Mount Cameroon is on the Cameroon Volcanic Line.', 'Shield volcanoes have gentle slopes.'],
  situation: 'The news says that Mount Cameroon shows signs of activity, with rumbling and smoke near its peak. Your uncle in Mokolo says: "Don\'t worry, the peak of Rhumsiki near here looks like a volcano, but it has been silent for millions of years." You ask: "Why is one mountain active and the other a quiet rocky peak, and why do volcanoes have different shapes?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the life cycle of volcanoes and the causes of their shapes.'],
    ['What is the process of molten rock reaching the surface called?', 'Volcanism (vulcanicity).'],
    ['Why is Mount Cameroon active and Rhumsiki not?', 'Mount Cameroon erupted recently; Rhumsiki is the remains of an extinct volcano.']],
  justification: 'This lesson helps us to understand the volcanic landforms of Cameroon and the risks of active volcanoes.',
  action: 'Recognise volcanic landforms and rocks in Cameroon.',
  activities: [
    { sec: '1. MEANING', img: 'volcano_big.png', caption: 'The parts of a volcano.', q: 'What is the difference between magma and lava?', a: 'Magma is below the surface; lava has reached the surface.', noProj: 'draw a volcano with its vent.' },
    { sec: '2. LIFE CYCLE', img: 'lsa_mtcameroon.jpg', caption: 'Mount Cameroon.', q: 'When did Mount Cameroon last erupt significantly?', a: 'In 1999–2000 (small activity in 2012).', noProj: 'list eruptions of Mount Cameroon.' },
    { sec: '2. LIFE CYCLE', img: 'lsa_mandara.jpg', caption: 'Volcanic necks near Rhumsiki.', q: 'Why is the peak of Rhumsiki called extinct?', a: 'It has not erupted for millions of years and will not erupt again.', noProj: 'describe the peaks of Rhumsiki.' },
    { sec: '3. PRODUCTS', img: 'lsa_pahoehoe.jpg', caption: 'Solidified runny lava.', q: 'Which lava flows far: basic or acid?', a: 'Basic lava (runny, low in silica).', noProj: 'compare water and thick porridge.' },
    { sec: '4. LANDFORMS', img: 'f4_crater.jpg', caption: 'A volcanic crater.', q: 'What is the difference between a crater and a caldera?', a: 'A crater is small (under 1 km); a caldera is a very large basin formed by collapse.', noProj: 'draw a crater and a caldera.' },
  ],
  summary: [
    D([['Volcanicity:', 'It is the set of processes by which molten rock, gases and other materials are forced from the interior of the Earth to the surface.'],
      ['Magma:', 'It is molten rock below the surface.'],
      ['Lava:', 'It is molten rock that has reached the surface.'],
      ['Cone:', 'It is a hill or mountain built around a vent by the materials of eruptions.']]),
    { title: '1. Meaning and Process of Volcanism', intro: 'Volcanism is explained as follows:',
      items: [['Meaning:', 'Volcanism is the movement of molten rock and gases from inside the Earth towards the surface. It includes eruptions at the surface (extrusive activity) and the cooling of magma inside the crust (intrusive activity).'],
        ['Process:', 'Magma forms where rocks of the mantle or crust melt, at plate margins or hot spots, and it rises because it is lighter than the rocks around it. It collects in a magma chamber, and when the pressure of the gases is high enough, it forces its way up through a vent and erupts.', 'geo2_volc_life.png', 'the life cycle of a volcano']] },
    { title: '2. Stages in the Life Cycle of a Volcano', intro: 'A volcano passes through the following stages:',
      items: [['Active volcano:', 'An active volcano is erupting or has erupted in recorded history and shows signs of activity. Mount Cameroon, which erupted in 1999 and 2000, is the most active volcano of West Africa.', 'lsa_mtcameroon.jpg', 'Mount Cameroon'],
        ['Dormant volcano:', 'A dormant volcano has not erupted for a long time but may erupt again, because magma is still present below it. Kilimanjaro and Mount Fuji are examples.', 'f2t_kilimanjaro.jpg', 'Kilimanjaro'],
        ['Extinct volcano:', 'An extinct volcano has not erupted for thousands or millions of years and has no more magma supply. Erosion wears it down, leaving hard plugs such as the volcanic necks of Rhumsiki in the Mandara Mountains.', 'lsa_mandara.jpg', 'volcanic necks at Rhumsiki']] },
    { title: '3. Products of Volcanic Eruptions', intro: 'An eruption releases the following products:',
      items: [['Lava:', 'Basic lava is low in silica, very hot and runny, so it flows far before cooling into basalt. Acid lava is rich in silica, thick and sticky, so it cools quickly near the vent and blocks it, causing explosions.'],
        ['Pyroclasts:', 'Explosions throw out solid fragments of all sizes: fine ash, small stones called cinders or lapilli, and large blocks and bombs. The ash can be carried by winds over thousands of kilometres.', 'geo2_products.png', 'the products of an eruption'],
        ['Gases:', 'Volcanic gases are mostly water vapour, with carbon dioxide, sulphur dioxide and hydrogen sulphide. Their pressure drives the eruption, and some are poisonous.']] },
    { title: '4. Volcanic Landforms', sub: 'A) Volcanic Cones', intro: 'Different materials and eruptions build the following types of cones:',
      items: [['Basic lava cones (shield volcanoes):', 'Runny basic lava flows far before it solidifies, so it builds very wide volcanoes with gentle slopes. Mauna Loa in Hawaii is the largest example.', 'lsa_shield.jpg', 'a shield volcano'],
        ['Acid lava cones (cumulo-domes):', 'Sticky acid lava cannot flow far and piles up around the vent. It forms small, steep-sided domes, like the domes of the Puy region in France.'],
        ['Ash and cinder cones:', 'Explosive eruptions throw out ash and cinders, which fall around the vent. They build small, steep cones with a crater at the top, like Paricutin in Mexico.'],
        ['Composite cones (strato-volcanoes):', 'Alternating eruptions of lava and pyroclasts build layers, and the lava binds the ash together. They form tall, steep, symmetrical cones, like Mount Cameroon (4,095 m) and Mount Fuji.', 'lsa_mayon.jpg', 'a composite cone']] },
    { title: '4. Volcanic Landforms', sub: 'B) Lava Plateaux and Volcanic Depressions', intro: 'Volcanism also forms the following landforms:',
      items: [['Lava plateaux:', 'Very runny basic lava erupts from long fissures, spreads in thin sheets and covers huge areas, layer upon layer. The Deccan Plateau of India and the Adamawa basalts in Cameroon were formed in this way.', 'lsa_basalt.jpg', 'basalt columns'],
        ['Craters and crater lakes:', 'A crater is a bowl-shaped depression at the top of a vent, usually less than 1 km wide. Rainwater can fill it to form a crater lake, like Lake Nyos and Lake Barombi Mbo in Cameroon.', 'f4_crater.jpg', 'a crater'],
        ['Calderas:', 'A caldera is a very large basin, several kilometres wide, formed when the top of a volcano collapses into its emptied magma chamber after a huge eruption. Crater Lake in the United States fills a caldera.']] },
  ],
  evaluation: [['Distinguish an active volcano from an extinct volcano with one example each.', 'An active volcano has erupted in recorded history (Mount Cameroon); an extinct one will not erupt again (Rhumsiki necks).'],
    ['Why are shield volcanoes wide and composite cones steep?', 'Shield volcanoes are built by runny lava that flows far; composite cones are built by layers of lava and ash that pile up.']],
  remediation: ['Molten rock below the surface is ______.', 'Kilimanjaro is a ______ volcano.', 'A very large collapsed crater is a ______.'],
  remediationAnswers: '1. magma 2. dormant 3. caldera',
  homework: 'Give one benefit of volcanoes to man.',
  hwAnswer: 'Fertile soils, tourism, geothermal energy, building stone or minerals (any one).',
  bilingual: [['Volcano', 'Le volcan'], ['Lava', 'La lave'], ['Ash', 'La cendre'], ['Eruption', "L'éruption"], ['Crater', 'Le cratère'], ['Extinct volcano', 'Le volcan éteint']],
});

L.push({ no: 7, title: 'Volcanoes and Man', topic: T2, subtopic: 'Volcanicity', pointPerSlide: true,
  notions: 'Volcanic resource, volcanic hazard, andosol, geothermal energy, pyroclastic flow, lahar, limnic eruption, monitoring, mitigation, adaptation.',
  focus: 'Volcanoes as resources (soils, tourism, energy, materials, minerals); volcanoes as hazards (lava, ash, pyroclastic flows, lahars, gases, Lake Nyos); adaptation and mitigation.',
  competence: 'Learners are able to explain why people live near volcanoes and propose measures to reduce volcanic risks in Cameroon.',
  objectives: ['Explain the resources provided by volcanoes.', 'Explain the hazards of volcanoes.', 'Describe the Lake Nyos disaster.', 'Describe adaptation and mitigation strategies.'],
  recall: ['Mount Cameroon is an active composite cone.', 'Lake Nyos is a crater lake.', 'Eruptions release lava, pyroclasts and gases.'],
  situation: 'Your friend\'s elder sister works for the Cameroon Development Corporation (CDC) on a banana plantation near Tiko, on the slopes of Mount Cameroon. In her photos the soil is very dark and the plants grow extremely well. Yet you know that Mount Cameroon is an active volcano. You ask: "Why do people choose to farm and live so close to a mountain that can erupt, and how can they protect themselves?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand why volcanoes are both a resource and a hazard.'],
    ['Why are CDC plantations on Mount Cameroon?', 'Volcanic ash weathers into very fertile soils.'],
    ['What must people living there do?', 'Use monitoring, hazard maps, education and evacuation plans.']],
  justification: 'This lesson helps us to weigh the advantages and dangers of volcanoes and to reduce disasters such as Lake Nyos.',
  action: 'Follow the advice of the authorities in volcanic areas and support monitoring and evacuation plans.',
  activities: [
    { sec: '1. RESOURCES', img: 'usa_banana.jpg', caption: 'A banana plantation.', q: 'Why are volcanic soils so fertile?', a: 'Ash and lava weather into soils rich in minerals (andosols).', noProj: 'name crops of the South-West.' },
    { sec: '1. RESOURCES', img: 'f4_geothermal.jpg', caption: 'A geothermal power station.', q: 'How can the heat of magma produce electricity?', a: 'It heats underground water into steam that turns turbines.', noProj: 'describe a kettle producing steam.' },
    { sec: '2. HAZARDS', img: 'f4_lavahouse.jpg', caption: 'A house destroyed by lava.', q: 'Which volcanic hazard is the most deadly?', a: 'The pyroclastic flow.', noProj: 'list volcanic hazards.' },
    { sec: '2. HAZARDS', img: 'f4_nyos.jpg', caption: 'Lake Nyos.', q: 'What killed about 1,700 people at Lake Nyos in 1986?', a: 'A sudden release of carbon dioxide gas from the lake.', noProj: 'locate Nyos in the North-West.' },
    { sec: '3. MITIGATION', img: 'lsa_volcmonitor.jpg', caption: 'Monitoring a volcano.', q: 'Name one instrument used to monitor a volcano.', a: 'A seismometer, a gas sensor or GPS.', noProj: 'describe an evacuation plan.' },
  ],
  summary: [
    D([['Volcanic resource:', 'It is a benefit that people obtain from volcanoes, such as fertile soils or energy.'],
      ['Volcanic hazard:', 'It is a volcanic event that can harm people and property.'],
      ['Adaptation:', 'It is the adjustment of people\'s way of life to live with a hazard.'],
      ['Mitigation:', 'It is the set of actions that reduce the damage of a hazard.']]),
    { title: '1. Volcanoes as a Resource', intro: 'Volcanoes are important to man in the following ways:',
      items: [['Fertile soils:', 'Volcanic ash and lava weather into deep, rich soils called andosols. On the slopes of Mount Cameroon, they support the CDC plantations of bananas, rubber, tea and oil palm, and in the Western Highlands dense farming of coffee and food crops.', 'usa_banana.jpg', 'a banana plantation'],
        ['Tourism:', 'Volcanoes and crater lakes attract visitors, which creates jobs and income. The Mount Cameroon Race of Hope and the crater lakes of the Western Highlands are examples.'],
        ['Geothermal energy:', 'Underground heat turns water into steam, which drives turbines to produce electricity and heats houses. Iceland and Kenya produce a large part of their electricity in this way.', 'f4_geothermal.jpg', 'a geothermal power station'],
        ['Building materials and minerals:', 'Basalt and pozzolana are quarried for roads, houses and cement. Volcanic areas also contain valuable minerals such as sulphur, copper and diamonds.']] },
    { title: '2. Volcanoes as a Hazard', intro: 'Volcanoes cause the following hazards:',
      items: [['Lava flows:', 'Rivers of molten rock destroy houses, roads and farms in their path, as during the 1999 eruption of Mount Cameroon, which cut the road near Bakingili. They usually move slowly, so people can escape.', 'f4_lavahouse.jpg', 'a house destroyed by lava'],
        ['Ash falls and pyroclastic flows:', 'Heavy ash collapses roofs, ruins crops and damages engines and aircraft. Pyroclastic flows, clouds of hot ash, rock and gas moving at over 100 km/h, destroy everything and are the deadliest hazard.'],
        ['Lahars:', 'Ash mixed with heavy rain or melted snow forms fast mudflows that rush down valleys. In 1985, a lahar from Nevado del Ruiz in Colombia buried the town of Armero and killed about 23,000 people.', 'lsa_lahar.jpg', 'a lahar'],
        ['Poisonous gases:', 'Volcanic gases can suffocate people and animals. In 1986, Lake Nyos suddenly released a cloud of carbon dioxide that killed about 1,700 people and thousands of cattle.', 'f4_nyos.jpg', 'Lake Nyos']] },
    { title: '3. Adaptation and Mitigation Strategies', intro: 'People reduce volcanic risks with the following strategies:',
      items: [['Monitoring and warning:', 'Seismometers detect the small earthquakes caused by rising magma, sensors measure gases and satellites detect the swelling of the volcano. When an eruption is likely, warnings allow people to leave in time.', 'lsa_volcmonitor.jpg', 'monitoring a volcano'],
        ['Hazard mapping and land-use planning:', 'Maps show the zones threatened by lava, ash, lahars and gases. Houses, schools and hospitals are then built outside the most dangerous zones.'],
        ['Education and evacuation plans:', 'People learn the warning signs and what to do during an eruption. Evacuation routes and shelters are prepared in advance.'],
        ['Engineering measures:', 'Strong, steep roofs resist the weight of ash, and barriers or channels divert lava and lahars. At Lake Nyos, pipes have been installed since 2001 to release the gas slowly and prevent another disaster.', 'geo2_volc_man.png', 'volcanoes and man']] },
  ],
  evaluation: [['Explain why a volcano is both a resource and a hazard.', 'It gives fertile soils, energy and tourism, but its eruptions and gases destroy property and kill people.'],
    ['Give two measures to reduce volcanic risks.', 'Monitoring, hazard maps and zoning, education and evacuation plans, engineering works (any two).']],
  remediation: ['Volcanic soils are called ______.', 'The deadliest volcanic hazard is the ______ flow.', 'Lake Nyos released ______ in 1986.'],
  remediationAnswers: '1. andosols 2. pyroclastic 3. carbon dioxide',
  homework: 'Define the epicentre of an earthquake.',
  hwAnswer: 'The epicentre is the point on the surface of the Earth directly above the focus of an earthquake.',
  bilingual: [['Hazard', 'Le risque / l\'aléa'], ['Resource', 'La ressource'], ['Fertile soil', 'Le sol fertile'], ['Mitigation', "L'atténuation"], ['Evacuation', "L'évacuation"], ['Geothermal energy', "L'énergie géothermique"]],
});

L.push({ no: 8, title: 'Earthquakes and Man', topic: T2, subtopic: 'Seismic Activity (Earthquakes)', pointPerSlide: true,
  notions: 'Earthquake, focus (hypocentre), epicentre, seismic waves, seismograph, Ring of Fire, liquefaction, tsunami, mitigation.',
  focus: 'Meaning and nature of earthquakes; causes and distribution (world and Cameroon); earthquakes as hazards; mitigation measures.',
  competence: 'Learners are able to explain the causes, distribution and effects of earthquakes and propose ways of reducing their damage.',
  objectives: ['Define an earthquake, the focus and the epicentre.', 'Explain the causes of earthquakes.', 'Describe their distribution in the world and in Cameroon.', 'Explain their effects.', 'Describe mitigation measures.'],
  recall: ['Plates slide, collide or move apart at margins.', 'The Cameroon Volcanic Line is a zone of weakness.', 'Mount Cameroon is monitored.'],
  situation: 'One evening in Garoua, the CRTV news reports a small earth tremor felt in Bamenda. There was no major damage, but people were frightened by the sudden shaking. You have never felt such a thing in Garoua. You ask your father: "Why does the ground shake in some parts of our country but not here? What causes it, and is it dangerous?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the causes, distribution and dangers of earthquakes.'],
    ['What is the sudden shaking of the ground called?', 'An earthquake.'],
    ['Why is Bamenda more exposed than Garoua?', 'It lies on the Cameroon Volcanic Line, a weak and active zone.']],
  justification: 'This lesson helps us to understand earthquakes and to reduce their effects through good building and preparedness.',
  action: 'Learn and practise "Drop, Cover and Hold On" and build with reinforced materials in exposed areas.',
  activities: [
    { sec: '1. MEANING', img: 'geo2_quake.png', caption: 'Focus and epicentre.', q: 'Where is the shaking usually strongest?', a: 'At the epicentre, directly above the focus.', noProj: 'drop a stone in water to show waves.' },
    { sec: '1. MEANING', img: 'f4_seismograph.jpg', caption: 'A seismograph.', q: 'What does a seismograph record?', a: 'Seismic waves (ground vibrations).', noProj: 'describe a seismograph.' },
    { sec: '2. DISTRIBUTION', img: 'plates_big.png', caption: 'Plates and their margins.', q: 'Where is the most active earthquake zone?', a: 'The Pacific Ring of Fire.', noProj: 'trace the Ring of Fire on a map.' },
    { sec: '3. HAZARDS', img: 'f4_quakedamage.jpg', caption: 'Buildings destroyed by an earthquake.', q: 'Give two effects of an earthquake on people.', a: 'Collapse of buildings, fires, injuries, deaths, homelessness (any two).', noProj: 'list effects on the board.' },
    { sec: '4. MITIGATION', img: 'geo2_quake_resp.png', caption: 'Reducing earthquake damage.', q: 'What should you do during an earthquake?', a: 'Drop, cover (under a table) and hold on.', noProj: 'practise the drill.' },
  ],
  summary: [
    D([['Earthquake:', 'It is a sudden, violent shaking of the ground caused by the release of energy stored in the crust.'],
      ['Focus (hypocentre):', 'It is the point inside the Earth where the rocks break and the earthquake starts.'],
      ['Epicentre:', 'It is the point on the surface directly above the focus.'],
      ['Isostatic recovery:', 'It is the slow rise of the crust after a heavy load, such as an ice sheet, has been removed.'],
      ['Tsunami:', 'It is a series of giant sea waves caused by an undersea earthquake, volcanic eruption or landslide.']]),
    { title: '1. Meaning and Nature of Earthquakes', intro: 'An earthquake is explained as follows:',
      items: [['Meaning:', 'Rocks of the crust are slowly deformed by stress until they suddenly break or slip along a fault. The energy released spreads out as waves that make the ground shake.', 'geo2_quake.png', 'focus and epicentre'],
        ['Focus and epicentre:', 'The focus is the point underground where the rupture starts; it may be shallow (less than 70 km) or deep (up to 700 km). The epicentre is the point on the surface directly above it, where the shaking is usually strongest.'],
        ['Seismic waves:', 'Primary (P) waves are the fastest and push and pull the rocks, while secondary (S) waves shake them from side to side. Surface waves, which travel along the ground, are the slowest but cause most of the damage.'],
        ['Measurement:', 'Seismographs record the waves, and the magnitude, the energy released, is measured on the Richter or moment magnitude scale. Each step of 1 on the scale means about 32 times more energy.', 'f4_seismograph.jpg', 'a seismograph']] },
    { title: '2. Distribution of Earthquakes', intro: 'Earthquakes are distributed as follows:',
      items: [['The Pacific Ring of Fire:', 'About 80 % of the energy of the earthquakes of the world is released around the Pacific Ocean. Japan, Chile, Indonesia and California are among the most affected places.', 'plates_big.png', 'the plates and their margins'],
        ['The Alpine–Himalayan belt:', 'It runs from the Mediterranean through Turkey and Iran to the Himalayas and China. Turkey, Iran and Nepal suffer frequent destructive earthquakes.'],
        ['Ridges and rift valleys:', 'Many small, shallow earthquakes occur along the mid-ocean ridges and the East African Rift. They are frequent but usually not very destructive.'],
        ['Local scale: Cameroon:', 'In Cameroon, tremors are linked to the Cameroon Volcanic Line, around Mount Cameroon, Kumba, Bamenda and Foumban. Northern Cameroon, around Garoua, lies on stable rocks and has very few earthquakes.', 'cameroon_volcanic_line.png', 'the Cameroon Volcanic Line']] },
    { title: '3. Causes of Earthquakes', intro: 'Earthquakes are caused by the following processes:',
      items: [['Movements at plate margins:', 'Most earthquakes happen where plates collide, slide past each other or move apart. The plates lock by friction, stress builds up, and the sudden slip releases the energy.'],
        ['Volcanism:', 'Magma rising under a volcano breaks the rocks and causes small to moderate earthquakes. For example, the eruptions of Mount Cameroon in 1999 were preceded by earthquakes felt in Buea and Limbe.'],
        ['Isostatic recovery:', 'Where the crust rises after the melting of ice sheets, or sinks under a new load, the rocks adjust by breaking. This causes minor earthquakes, as in Scandinavia and Canada.']] },
    { title: '4. Earthquakes as a Hazard', sub: 'A) Effects on the Land', intro: 'Earthquakes have the following effects on the land:',
      items: [['Ground shaking and fissures:', 'Strong shaking opens cracks in the ground and can raise or lower blocks of land along faults. It is the main cause of damage.'],
        ['Landslides and rockfalls:', 'In hilly and mountainous areas, shaking loosens soil and rocks, which slide down the slopes. They can block roads and rivers and bury villages.'],
        ['Liquefaction:', 'Wet, loose soils lose their strength and behave like a liquid during shaking. Buildings standing on them tilt or sink.'],
        ['Tsunamis:', 'An undersea earthquake lifts the sea floor and sets off giant waves that can cross whole oceans. They flood the coasts, as in the Indian Ocean in 2004.', 'lsa_tsunami.jpg', 'a tsunami']] },
    { title: '4. Earthquakes as a Hazard', sub: 'B) Effects on People', intro: 'Earthquakes have the following effects on people:',
      items: [['Deaths and injuries:', 'Most people are killed by the collapse of buildings, especially at night. The 2004 Indian Ocean earthquake and tsunami killed about 230,000 people in 14 countries.'],
        ['Destruction of buildings and infrastructure:', 'Houses, bridges, roads, pipes and power lines are destroyed. Many people become homeless, and rescue is difficult.', 'f4_quakedamage.jpg', 'earthquake damage'],
        ['Fires and diseases:', 'Broken gas and electric lines start fires, as in San Francisco in 1906. Damaged water and sewage pipes spread diseases such as cholera.'],
        ['Economic losses:', 'Factories, shops and farms stop working, and reconstruction costs billions. Poor countries may need years to recover.']] },
    { title: '5. Measures to Mitigate the Effects', intro: 'The effects of earthquakes are reduced by the following measures:',
      items: [['Monitoring and warning:', 'Seismographs and GPS monitor ground movements, although the exact time of an earthquake cannot yet be predicted. Tsunami warning systems now alert coastal populations within minutes.'],
        ['Earthquake-resistant buildings:', 'Reinforced concrete, steel frames, flexible foundations and light roofs help buildings resist shaking. Building codes make these techniques compulsory in exposed zones, as in Japan.', 'geo2_quake_resp.png', 'responses to earthquakes'],
        ['Education and preparedness:', 'People learn to "Drop, Cover and Hold On", prepare emergency kits and practise evacuation drills. This greatly reduces the number of victims.'],
        ['Land-use planning:', 'Building is avoided on active faults, loose soils and steep slopes. Hospitals, schools and fire stations are made especially strong so that they can work after a disaster.']] },
  ],
  evaluation: [['Distinguish the focus from the epicentre.', 'The focus is where the earthquake starts inside the Earth; the epicentre is the point on the surface above it.'],
    ['Why is Garoua rarely affected by earthquakes?', 'It is far from plate margins and from the Cameroon Volcanic Line.']],
  remediation: ['The point where an earthquake starts is the ______.', 'The most active earthquake zone is the Pacific ______ of Fire.', 'Undersea earthquakes can cause ______.'],
  remediationAnswers: '1. focus (hypocentre) 2. Ring 3. tsunamis',
  homework: 'Define weathering.',
  hwAnswer: 'Weathering is the breakdown of rocks in place, at or near the surface of the Earth.',
  bilingual: [['Earthquake', 'Le séisme'], ['Epicentre', "L'épicentre"], ['Focus', "Le foyer (l'hypocentre)"], ['Seismic waves', 'Les ondes sismiques'], ['Hazard', 'Le risque'], ['Tsunami', 'Le tsunami']],
});

module.exports = { B, L };
