// LOWER SIXTH ARTS — Meteorology, part 3: Lessons 13–18 and Further Study 2 (atmospheric circulation, air masses, weather observation)
// Rewritten from the teacher's course supports (LSA_LESSONS_METEOROLOGY_2026, USA_LESSONS_METEO) in our own words; facts checked.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const { B } = require('./lsamet_1');
const L = [];
const T4 = 'Global and Local Atmospheric Circulation', T5 = 'Atmospheric Motions', T6 = 'Climates';

L.push({ no: 13, title: 'Pressure Systems', topic: T4, subtopic: 'Pressure Belts', pointPerSlide: true,
  notions: 'Atmospheric pressure, barometer, hectopascal, anticyclone, cyclone (depression), pressure belts, ITCZ, tricellular model, Hadley, Ferrel and polar cells, Coriolis effect.',
  focus: 'Meaning of pressure systems (anticyclones and cyclones); global distribution of pressure belts; the tricellular model with emphasis on the Hadley cell.',
  competence: 'Learners are able to explain the pressure belts and the tricellular circulation and relate them to the seasons of Garoua.',
  objectives: ['Define atmospheric pressure and pressure systems.', 'Distinguish anticyclones and cyclones and their weather.', 'Describe the global pressure belts.', 'Explain the tricellular model and the Hadley cell.'],
  recall: ['Warm air rises and cool air sinks.', 'Rising air cools and forms clouds.', 'The Sahara lies near 20–30° N.'],
  situation: 'Watching the weather news, you see heavy thunderstorms over the Congo Basin near the Equator while the Sahara, near 25° N, has clear skies and dry heat. The presenter speaks of "low pressure" over one region and "high pressure" over the other. In Garoua, the dry north-east wind blows for months, then the moist south-west wind comes. You ask: "What are these pressure systems, and how do they organise the winds and weather of the world?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the pressure systems and the global circulation of the atmosphere.'],
    ['Why is there heavy rain near the Equator?', 'Air rises in a low-pressure zone (the ITCZ), cools and forms rain clouds.'],
    ['Why is the Sahara dry?', 'Air sinks in the subtropical high-pressure belt, so clouds do not form.']],
  justification: 'This lesson explains the great belts of pressure and winds that control the climates of the world and of Cameroon.',
  action: 'Read pressure on weather maps to understand the coming weather.',
  activities: [
    { sec: '1. PRESSURE SYSTEMS', img: 'f4_barometer.jpg', caption: 'A barometer.', q: 'Which instrument measures atmospheric pressure?', a: 'The barometer.', noProj: 'press on a table to show weight.' },
    { sec: '1. PRESSURE SYSTEMS', img: 'met2_pressure.png', caption: 'Low and high pressure.', q: 'What weather is associated with an anticyclone?', a: 'Clear skies, dry and calm weather.', noProj: 'draw rising and sinking air.' },
    { sec: '2. PRESSURE BELTS', img: 'pressure_belts_big.png', caption: 'The pressure belts of the world.', q: 'Which pressure belt lies around 30° N and S?', a: 'The subtropical high-pressure belt.', noProj: 'draw the belts on a globe sketch.' },
    { sec: '3. TRICELLULAR MODEL', img: 'tricellular_big.png', caption: 'The three cells.', q: 'Name the three cells of each hemisphere.', a: 'The Hadley, Ferrel and polar cells.', noProj: 'draw the three cells.' },
    { sec: '3. HADLEY CELL', img: 'hadley.gif', caption: 'Animation: the Hadley cell.', q: 'Which surface winds complete the Hadley cell in the northern hemisphere?', a: 'The north-east trade winds (the Harmattan over West Africa).', noProj: 'draw the four steps of the cell.' },
  ],
  summary: [
    D([['Atmospheric pressure:', 'It is the force exerted by the weight of the air on a unit area of the surface, measured in hectopascals (hPa).'],
      ['Pressure system:', 'It is an area where the pressure is higher or lower than in the surrounding areas.'],
      ['Anticyclone:', 'It is a high-pressure system of sinking air.'],
      ['Depression (cyclone):', 'It is a low-pressure system of rising air.'],
      ['Tricellular model:', 'It is a model of three circulation cells in each hemisphere that carry heat from the Equator to the poles.']]),
    { title: '1. Meaning of Pressure Systems', intro: 'Pressure systems are explained as follows:',
      items: [['Atmospheric pressure:', 'The weight of the air presses on the surface with an average force of about 1,013 hPa at sea level, measured with a barometer. Pressure falls with altitude because there is less air above, and it changes from place to place with temperature.', 'f4_barometer.jpg', 'a barometer'],
        ['High pressure (anticyclone):', 'In a high-pressure system, air sinks, is compressed and spreads out at the surface. Sinking air warms and cannot form clouds, so anticyclones give clear, dry and calm weather.', 'met2_pressure.png', 'high and low pressure'],
        ['Low pressure (depression):', 'In a low-pressure system, air flows in at the surface and rises. Rising air cools and its vapour condenses, so depressions give clouds, rain and often storms.']] },
    { title: '2. The Tricellular Model', sub: 'A) The Three Cells', intro: 'The tricellular model divides the circulation of each hemisphere into the following three cells:',
      items: [['The Hadley cell (0° to 30°):', 'It is a thermal cell driven by the strong heating of the Equator. It creates the equatorial low pressure where air rises and the subtropical high pressure where it sinks.', 'tricellular_big.png', 'the tricellular model'],
        ['The Ferrel cell (30° to 60°):', 'It is a cell driven by the movement of the two cells on either side of it. Its surface air flows poleward from the subtropical highs as the westerlies and rises at the subpolar lows.'],
        ['The polar cell (60° to 90°):', 'Very cold, dense air sinks over the poles and forms the polar highs. It flows towards 60° as the polar easterlies, where it meets warmer air, rises and returns poleward at high altitude.']] },
    { title: '2. The Tricellular Model', sub: 'B) The Hadley Cell', intro: 'The Hadley cell works in the following four steps:',
      items: [['Step 1, rising air at the Equator:', 'Strong heating near the Equator makes the air expand, become light and rise. This creates the equatorial low pressure, or ITCZ, with cumulonimbus clouds and heavy rain.', 'hadley_first.png', 'the Hadley cell'],
        ['Step 2, flow towards the poles aloft:', 'At about 15 km, the tropopause stops the air from rising further, so it spreads out towards the poles. As it moves, it loses heat by radiation and becomes cooler and denser.'],
        ['Step 3, sinking air at about 30°:', 'Near 30° N and S, the cooled air sinks and is warmed by compression, so no clouds can form. This creates the subtropical high pressure and explains the great hot deserts, such as the Sahara.'],
        ['Step 4, return flow at the surface:', 'At the surface, the air flows back to the Equator to replace the rising air. Deflected by the Coriolis effect, it becomes the north-east trade winds, which in West Africa blow as the Harmattan.']] },
  ],
  evaluation: [['Distinguish an anticyclone from a depression.', 'An anticyclone is high pressure with sinking air and clear weather; a depression is low pressure with rising air, clouds and rain.'],
    ['Explain how the Hadley cell creates the Sahara Desert.', 'Air rising at the Equator moves poleward, cools and sinks near 30° N, forming high pressure where clouds cannot form.']],
  remediation: ['Pressure is measured with a ______.', 'Sinking air forms ______ pressure.', 'The cell between the Equator and 30° is the ______ cell.'],
  remediationAnswers: '1. barometer 2. high 3. Hadley',
  homework: 'State why warm air rises.',
  hwAnswer: 'Warm air rises because it is lighter (less dense) than the cooler air around it.',
  bilingual: [['Air pressure', 'La pression atmosphérique'], ['Wind', 'Le vent'], ['Circulation', 'La circulation'], ['Hadley cell', 'La cellule de Hadley'], ['Anticyclone', "L'anticyclone"], ['Depression', 'La dépression']],
});

L.push({ no: 14, title: 'Vertical Motions: Stability and Instability', topic: T4, subtopic: 'Atmospheric Motions', pointPerSlide: true,
  notions: 'Vertical motion, air parcel, instability (absolute, conditional), stability (absolute, neutral), adiabatic, dry adiabatic lapse rate (DALR), saturated adiabatic lapse rate (SALR), environmental lapse rate (ELR).',
  focus: 'Meaning of vertical motions; atmospheric instability and its weather; atmospheric stability and its weather; the role of adiabatic lapse rates in determining stability.',
  competence: 'Learners are able to explain why some days bring storms and others clear skies by comparing lapse rates.',
  objectives: ['Define vertical motions and an air parcel.', 'Explain atmospheric instability and its weather.', 'Explain atmospheric stability and its weather.', 'Use the DALR, SALR and ELR to determine stability.'],
  recall: ['Temperature falls about 6.5 °C per km (ELR).', 'Rising air expands and cools.', 'Latent heat is released when vapour condenses.'],
  situation: 'Your teacher fills one balloon with warm air from a hair dryer and another near a bowl of ice. The warm balloon rises easily while the cold one stays down. You remember that some afternoons in Garoua small clouds grow into huge storm clouds, while on other days, especially in the Harmattan, the sky stays clear and hazy all day. You ask: "Why does air rise freely on some days and not on others?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand atmospheric stability and instability.'],
    ['Why does the warm balloon rise?', 'Warm air is lighter than the cooler air around it.'],
    ['What kind of atmosphere produces storm clouds?', 'An unstable atmosphere, where rising air keeps rising.']],
  justification: 'This lesson helps us to understand and forecast storms, clear days, fog and pollution episodes.',
  action: 'Watch for towering clouds on unstable afternoons and shelter from storms and lightning.',
  activities: [
    { sec: '1. VERTICAL MOTIONS', img: 'parcel.gif', caption: 'Animation: a rising air parcel.', q: 'What is an air parcel?', a: 'A small imaginary volume of air that rises or sinks without mixing with the air around it.', noProj: 'use the two balloons.' },
    { sec: '2. INSTABILITY', img: 'f4_cumulonimbus.jpg', caption: 'A towering cumulonimbus.', q: 'What weather does instability bring?', a: 'Cumulonimbus clouds, thunderstorms, heavy rain and hail.', noProj: 'describe an afternoon storm.' },
    { sec: '3. STABILITY', img: 'lsa_smog.jpg', caption: 'Haze trapped in stable air.', q: 'Why does pollution build up in stable air?', a: 'Air does not rise, so there is no vertical mixing.', noProj: 'describe Harmattan haze.' },
    { sec: '4. LAPSE RATES', img: 'stability_big.png', caption: 'Lapse rates and stability.', q: 'Why does saturated air cool more slowly than dry air?', a: 'Condensation releases latent heat.', noProj: 'draw the DALR and SALR lines.' },
    { sec: '4. LAPSE RATES', img: 'met2_stab_rules.png', caption: 'Rules of stability.', q: 'If the ELR is greater than the DALR, is the air stable or unstable?', a: 'Absolutely unstable.', noProj: 'write the three rules.' },
  ],
  summary: [
    D([['Vertical motions:', 'They are the upward and downward movements of air in the atmosphere.'],
      ['Adiabatic lapse rate:', 'It is the rate at which rising air cools by expansion, or sinking air warms by compression, without exchange of heat with the surrounding air.'],
      ['Atmospheric instability:', 'It is the state in which a lifted air parcel keeps rising because it is warmer than the air around it.'],
      ['Atmospheric stability:', 'It is the state in which a lifted air parcel sinks back because it is cooler than the air around it.']]),
    { title: '1. The Adiabatic Lapse Rates', intro: 'Stability and instability are found by comparing the following lapse rates:',
      items: [['Dry adiabatic lapse rate (DALR):', 'Unsaturated air that rises expands and cools at a fixed rate of about 10 °C per 1,000 m. Sinking air warms at the same rate.', 'stability_big.png', 'the lapse rates'],
        ['Saturated adiabatic lapse rate (SALR):', 'Once rising air is saturated, it cools more slowly, at about 5 to 7 °C per 1,000 m. This is because the condensation of vapour releases latent heat that partly warms the air.'],
        ['Environmental lapse rate (ELR):', 'It is the real fall of temperature of the still air around the parcel, on average 6.5 °C per 1,000 m. It changes from day to day, so comparing it with the DALR and SALR shows whether the air is stable or unstable.']] },
    { title: '2. Atmospheric Instability', sub: 'A) Meaning and Types', intro: 'Atmospheric instability and its types are explained as follows:',
      items: [['Meaning:', 'Air is unstable when a parcel that is lifted stays warmer and lighter than the air around it. It therefore keeps rising on its own, like a hot-air balloon.', 'parcel_last.png', 'a rising parcel of air'],
        ['Absolute instability:', 'It occurs when the ELR is greater than the DALR, for example on very hot afternoons when the ground is strongly heated. The parcel is always warmer than its surroundings, whether it is dry or saturated.'],
        ['Conditional instability:', 'It occurs when the ELR lies between the SALR and the DALR. The air is stable while it is dry, but becomes unstable once it is lifted enough to become saturated.'],
        ['Potential instability:', 'It occurs when a stable layer of air, dry above and moist below, is lifted as a whole, for example over mountains or at a front. The lower moist part becomes saturated first and the whole layer becomes unstable.']] },
    { title: '2. Atmospheric Instability', sub: 'B) Associated Weather Conditions', intro: 'Unstable air brings the following weather conditions:',
      items: [['Towering clouds:', 'Rising air forms cumulus clouds that grow into huge cumulonimbus reaching the tropopause. They are common on rainy-season afternoons in Garoua.', 'f4_cumulonimbus.jpg', 'a cumulonimbus cloud'],
        ['Heavy showers and thunderstorms:', 'Cumulonimbus clouds give heavy but short showers, with thunder, lightning and sometimes hail. Strong gusts of wind blow ahead of the storm.'],
        ['Turbulence and good dispersion:', 'Strong up-currents make aircraft shake and can be dangerous for flights. On the other hand, they carry smoke and dust upwards, so the air near the ground stays clean.']] },
    { title: '3. Atmospheric Stability', sub: 'A) Meaning and Types', intro: 'Atmospheric stability and its types are explained as follows:',
      items: [['Meaning:', 'Air is stable when a parcel that is lifted becomes cooler and heavier than the air around it. It therefore sinks back to its starting level and resists vertical movement.'],
        ['Absolute stability:', 'It occurs when the ELR is smaller than the SALR, for example during a temperature inversion. The parcel is always cooler than its surroundings, whether it is dry or saturated.'],
        ['Neutral stability:', 'It occurs when the ELR is equal to the lapse rate of the parcel. The lifted parcel has the same temperature as its surroundings, so it neither rises nor sinks on its own.']] },
    { title: '3. Atmospheric Stability', sub: 'B) Associated Weather Conditions', intro: 'Stable air brings the following weather conditions:',
      items: [['Clear skies and calm weather:', 'Air does not rise, so clouds cannot grow and there is little or no rain. This is the weather of anticyclones and of the dry season in the North.'],
        ['Fog and layer clouds:', 'When stable air is moist, it forms fog near the ground or flat layers of stratus. These clouds give only drizzle or light rain.'],
        ['Trapped pollution:', 'Smoke, dust and fumes cannot rise and remain near the ground. This produces haze and smog, as during the Harmattan season in towns.', 'lsa_smog.jpg', 'smog']] },
  ],
  evaluation: [['Distinguish a stable from an unstable atmosphere.', 'In a stable atmosphere, lifted air sinks back and skies stay clear; in an unstable atmosphere, lifted air keeps rising and forms storm clouds.'],
    ['Why does saturated air cool more slowly than dry air?', 'Condensation releases latent heat, which partly compensates for the cooling.']],
  remediation: ['Dry air cools at about ______ °C per km.', 'An ELR greater than the DALR gives ______ instability.', 'Stable air often traps ______.'],
  remediationAnswers: '1. 10 2. absolute 3. pollution (haze, fog)',
  homework: 'Define wind.',
  hwAnswer: 'Wind is the movement of air from an area of high pressure to an area of low pressure.',
  bilingual: [['Stability', 'La stabilité'], ['Instability', "L'instabilité"], ['Air parcel', "La particule d'air"], ['Lapse rate', 'Le gradient thermique'], ['Thunderstorm', "L'orage"], ['Latent heat', 'La chaleur latente']],
});

L.push({ no: 15, title: 'Planetary Winds', topic: T4, subtopic: 'Macroscale or Global Scale Winds', pointPerSlide: true,
  notions: 'Wind, pressure gradient, Coriolis effect, Ferrel\'s law, planetary winds, trade winds, westerlies, polar easterlies, doldrums, horse latitudes.',
  focus: 'Meaning of wind and planetary winds; the Coriolis effect; the three planetary winds (trade winds, westerlies, polar easterlies) and their characteristics.',
  competence: 'Learners are able to explain the pattern of planetary winds and the winds that affect Cameroon.',
  objectives: ['Define wind and planetary winds.', 'Explain the causes of wind and the Coriolis effect.', 'Describe the trade winds.', 'Describe the westerlies and the polar easterlies.'],
  recall: ['Air moves from high to low pressure.', 'Pressure belts lie at 0°, 30°, 60° and 90°.', 'The Hadley cell produces the north-east trade winds.'],
  situation: 'In an old book, you read that sailing ships crossing the Atlantic followed winds that "always blow from the same direction", which sailors called the trade winds. Near the Equator, the ships were sometimes stuck for days without wind. You then notice that the Harmattan blows over Garoua from the north-east for months. You ask: "Which great winds blow over the Earth, and why do they not blow straight from north to south?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the planetary winds and their directions.'],
    ['What are the trade winds?', 'Steady winds blowing from the subtropical highs towards the Equator.'],
    ['Why do winds curve instead of blowing straight?', 'Because of the rotation of the Earth (the Coriolis effect).']],
  justification: 'This lesson explains the permanent winds that move heat and moisture around the world and influence the climate of Cameroon.',
  action: 'Use wind directions to explain the dry and rainy seasons of your region.',
  activities: [
    { sec: '1. WIND', img: 'f4_windsock.jpg', caption: 'A windsock.', q: 'Why does wind blow?', a: 'Air moves from high pressure to low pressure.', noProj: 'observe the direction of smoke.' },
    { sec: '1. CORIOLIS EFFECT', img: 'coriolis.gif', caption: 'Animation: the Coriolis effect.', q: 'To which side are winds deflected in the northern hemisphere?', a: 'To the right.', noProj: 'draw a line on a spinning paper disc.' },
    { sec: '2. PLANETARY WINDS', img: 'planetary_winds_big.png', caption: 'The planetary winds.', q: 'Which winds blow between the subtropical highs and the Equator?', a: 'The trade winds.', noProj: 'draw the winds on a globe sketch.' },
    { sec: '2. PLANETARY WINDS', img: 'lsa_ship.jpg', caption: 'A sailing ship.', q: 'Why were the trade winds useful to sailors?', a: 'They blow steadily in the same direction.', noProj: 'trace a sailing route.' },
    { sec: '2. PLANETARY WINDS', img: 'f4_bigwaves.jpg', caption: 'Stormy seas.', q: 'Why are the westerlies stronger in the southern hemisphere?', a: 'There is little land to slow them down.', noProj: 'compare the two hemispheres.' },
  ],
  summary: [
    D([['Wind:', 'It is the horizontal movement of air from high pressure to low pressure.'],
      ['Planetary winds:', 'They are permanent winds that blow all year between the pressure belts.'],
      ['Coriolis effect:', 'It is the deflection of winds by the rotation of the Earth: to the right in the northern hemisphere and to the left in the southern hemisphere.']]),
    { title: '1. Meaning and Illustration of Planetary Winds', intro: 'Planetary winds are explained as follows:',
      items: [['Pressure gradient:', 'Air always moves from high pressure towards low pressure, and the difference of pressure between two places is the pressure gradient. The bigger the difference, the stronger the wind.', 'f4_windsock.jpg', 'a windsock'],
        ['The Coriolis effect (Ferrel\'s law):', 'Because the Earth rotates, winds do not blow straight from high to low pressure. They are deflected to the right in the northern hemisphere and to the left in the southern hemisphere.', 'coriolis_last.png', 'the Coriolis effect'],
        ['Naming of winds:', 'A wind is named after the direction from which it blows. For example, a north-east wind blows from the north-east towards the south-west.']] },
    { title: '2. Types and Characteristics of Planetary Winds', intro: 'The three planetary winds have the following characteristics:',
      items: [['Trade winds:', 'They blow from the subtropical highs (30°) towards the equatorial low, from the north-east in the northern hemisphere and from the south-east in the southern hemisphere. They are steady and regular, dry over land like the Harmattan but moist over the oceans, and meet in the calm doldrums at the ITCZ.', 'planetary_winds_big.png', 'the planetary winds'],
        ['Westerlies:', 'They blow from the subtropical highs towards the subpolar lows (30° to 60°), from the south-west in the northern hemisphere and from the north-west in the southern hemisphere. They are variable, bring depressions and rain to western Europe, and are strongest over the southern oceans, where they are called the Roaring Forties.', 'f4_bigwaves.jpg', 'rough seas'],
        ['Polar easterlies:', 'They blow from the polar highs towards the subpolar lows (above 60°), from the east. They are very cold, dry and irregular, and where they meet the westerlies the polar front forms.', 'met2_winds3.png', 'the three planetary winds']] },
  ],
  evaluation: [['Describe the trade winds.', 'Steady winds blowing from the subtropical highs to the Equator, from the north-east (N. hemisphere) and south-east (S. hemisphere).'],
    ['Explain the Coriolis effect.', 'The rotation of the Earth deflects winds to the right in the northern hemisphere and to the left in the southern hemisphere.']],
  remediation: ['Winds blow from high to ______ pressure.', 'The winds between 30° and 60° are the ______.', 'The calm belt at the Equator is the ______.'],
  remediationAnswers: '1. low 2. westerlies 3. doldrums',
  homework: 'Name the dry wind that blows over Garoua in the dry season.',
  hwAnswer: 'The Harmattan (north-east trade wind from the Sahara).',
  bilingual: [['Wind', 'Le vent'], ['Trade winds', 'Les alizés'], ['Westerlies', "Les vents d'ouest"], ['Coriolis effect', "L'effet de Coriolis"], ['Doldrums', 'Le pot au noir'], ['Pressure gradient', 'Le gradient de pression']],
});

L.push({ no: 16, title: 'Tropical Seasonal Winds: Monsoon and Harmattan', topic: T4, subtopic: 'Mesoscale Winds', pointPerSlide: true,
  notions: 'Monsoon, summer (wet) monsoon, winter (dry) monsoon, differential heating, Harmattan, West African monsoon, ITCZ.',
  focus: 'Monsoon winds: meaning, causes, areas and effects (Asia, West Africa); the Harmattan: meaning, causes and effects in Cameroon.',
  competence: 'Learners are able to explain the seasonal reversal of winds and adapt to the effects of the monsoon and the Harmattan in Garoua.',
  objectives: ['Define the monsoon and the Harmattan.', 'Explain the causes of the summer and winter monsoons.', 'Describe the areas and effects of monsoons.', 'Explain the positive and negative effects of the Harmattan.'],
  recall: ['Land heats and cools faster than the sea.', 'The Harmattan is part of the north-east trade winds.', 'The ITCZ moves with the overhead sun.'],
  situation: 'In mid-January in Garoua, a cool, dusty wind blows from the north, the sky is hazy, dust covers everything, lips crack and many people cough. Five months earlier, in August, the wind came from the south, the air was heavy with moisture and heavy rain fell almost every day. You ask: "Why does the wind completely change its direction and character during the year?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand the seasonal reversal of winds.'],
    ['What is the dry, dusty wind of January called?', 'The Harmattan.'],
    ['Why is the August wind wet?', 'It comes from the Atlantic Ocean: it is the south-west monsoon.']],
  justification: 'This lesson explains the rainy and dry seasons that control farming, health and daily life in Garoua.',
  action: 'Protect your health during the Harmattan (drink water, cover your nose, avoid bush fires) and prepare fields before the monsoon rains.',
  activities: [
    { sec: '1. MONSOON', img: 'met2_monsoon.png', caption: 'Summer and winter monsoons.', q: 'Why does the summer monsoon bring rain?', a: 'It blows from the sea to the hot land and carries moisture.', noProj: 'draw arrows sea→land and land→sea.' },
    { sec: '1. MONSOON', img: 'lsa_monsoon.jpg', caption: 'Monsoon rain in Asia.', q: 'Give one negative effect of the Asian monsoon.', a: 'Floods, landslides and loss of life.', noProj: 'locate India and Bangladesh.' },
    { sec: '1. WEST AFRICAN MONSOON', img: 'itcz.gif', caption: 'Animation: the rain belt moves during the year.', q: 'When does the south-west monsoon reach Garoua?', a: 'From about May to September–October.', noProj: 'draw the ITCZ in January and July.' },
    { sec: '2. HARMATTAN', img: 'f2t_harmattan.jpg', caption: 'Harmattan haze.', q: 'Where does the Harmattan come from?', a: 'From the Sahara Desert.', noProj: 'draw the arrow from the Sahara.' },
    { sec: '2. HARMATTAN', img: 'met2_harmattan.png', caption: 'Effects of the Harmattan.', q: 'Give one positive effect of the Harmattan.', a: 'Cool nights, drying of crops, or fewer mosquitoes.', noProj: 'list effects in two columns.' },
  ],
  summary: [
    D([['Monsoon:', 'It is a seasonal wind that reverses its direction between summer and winter; the word comes from the Arabic mausim, meaning season.'],
      ['Harmattan:', 'It is the dry, dusty north-east wind that blows from the Sahara over West Africa in the dry season.'],
      ['Intertropical Convergence Zone (ITCZ):', 'It is the low-pressure zone where the winds of the two hemispheres meet; over land in West Africa it is called the Intertropical Front.']]),
    { title: '1. Monsoon Winds', sub: 'A) Meaning and Causes', intro: 'Monsoon winds are explained as follows:',
      items: [['Meaning:', 'A monsoon is a wind that blows from the sea to the land in summer and from the land to the sea in winter. It brings a wet season and a dry season each year.', 'met2_monsoon.png', 'the monsoon'],
        ['Differential heating of land and sea:', 'In summer, the land heats faster than the sea and low pressure forms over it, so moist air is drawn in from the sea. In winter, the land cools faster and high pressure forms over it, so dry air blows out to sea.'],
        ['Shift of the ITCZ:', 'The ITCZ follows the overhead sun north in the northern summer and south in the northern winter. As it moves, the trade winds cross the Equator, change direction with the Coriolis effect and become the monsoon winds.', 'itcz_july.png', 'the ITCZ in July']] },
    { title: '1. Monsoon Winds', sub: 'B) Areas of Occurrence', intro: 'Monsoon winds blow in the following areas:',
      items: [['South and South-East Asia:', 'The Asian monsoon is the strongest in the world because of the huge size of the Asian continent. It affects India, Bangladesh, Myanmar, Thailand, Vietnam and southern China.', 'lsa_monsoon.jpg', 'monsoon rain in Asia'],
        ['West Africa and Cameroon:', 'The south-west monsoon blows from the Gulf of Guinea over the coast and inland as far as the Sahel. It reaches southern Cameroon in March and northern Cameroon around May.'],
        ['Other areas:', 'Monsoon winds also blow over East Africa and northern Australia. In each case, they are caused by the seasonal heating of a large land mass.']] },
    { title: '1. Monsoon Winds', sub: 'C) Effects', intro: 'Monsoon winds have the following effects:',
      items: [['Rain for agriculture in Asia:', 'The summer monsoon brings about 80 % of the annual rain of India between June and September. It waters the rice fields and fills rivers and reservoirs used for irrigation and hydroelectricity.'],
        ['Floods and disasters in Asia:', 'When the monsoon is very strong, heavy rains cause floods and landslides, as in Bangladesh, where millions of people are affected. When it is late or weak, drought and famine can follow.'],
        ['The rainy season in Cameroon:', 'The south-west monsoon brings the rainy season to Garoua from about May to October. Farmers sow millet, sorghum, maize and cotton at its start, and the Benue and Lake Lagdo are filled.', 'f4_rainyseason.jpg', 'the rainy season']] },
    { title: '2. The Harmattan', sub: 'A) Meaning and Causes', intro: 'The Harmattan is explained as follows:',
      items: [['Meaning:', 'The Harmattan is the dry, dusty north-east wind that blows from the Sahara over West Africa from about November to March. In northern Cameroon, it is the wind of the dry season.', 'f2t_harmattan.jpg', 'Harmattan haze'],
        ['Causes:', 'In the northern winter, the overhead sun is south of the Equator and a high pressure forms over the cool Sahara. The ITCZ moves south towards the coast, and the north-east trade winds blow from the desert towards it, carrying its dry air and dust.']] },
    { title: '2. The Harmattan', sub: 'B) Effects', intro: 'The Harmattan has the following effects:',
      items: [['Health problems:', 'The dry, dusty air causes coughs, catarrh, asthma, dry skin and cracked lips. Meningitis epidemics also spread most in the Harmattan season in the Sahel.'],
        ['Poor visibility and bush fires:', 'The dust haze reduces visibility and can delay flights at Garoua airport. The dry vegetation catches fire easily, so bush fires are frequent.'],
        ['Relief from heat and fewer mosquitoes:', 'Nights and mornings are cool, which brings relief after the heat of the rainy season. The dry air also reduces the number of mosquitoes, so there is less malaria.'],
        ['Drying of harvests:', 'The dry air helps farmers to dry and store millet, beans, groundnuts and cotton. It also dries fish and meat for preservation.', 'met2_harmattan.png', 'the effects of the Harmattan']] },
  ],
  evaluation: [['Why is the summer monsoon wet and the winter monsoon dry?', 'The summer monsoon blows from the sea and carries moisture; the winter monsoon blows from the land and is dry.'],
    ['Give two negative effects of the Harmattan in Garoua.', 'Poor visibility, respiratory diseases, cracked lips and dry skin, bush fires (any two).']],
  remediation: ['A wind that reverses with the seasons is a ______.', 'The Harmattan comes from the ______.', 'The rainy season wind of Garoua is the south-west ______.'],
  remediationAnswers: '1. monsoon 2. Sahara 3. monsoon',
  homework: 'Define a sea breeze.',
  hwAnswer: 'A sea breeze is a cool wind that blows from the sea to the land during the day.',
  bilingual: [['Monsoon', 'La mousson'], ['Harmattan', "L'harmattan"], ['Season', 'La saison'], ['Dust', 'La poussière'], ['Humidity', "L'humidité"], ['Bush fire', 'Le feu de brousse']],
});

L.push({ no: 17, title: 'Local Winds', topic: T5, subtopic: 'Microscale (Local) Winds', pointPerSlide: true,
  notions: 'Local wind, sea breeze, land breeze, anabatic (valley) wind, katabatic (mountain) wind, foehn, Chinook.',
  focus: 'Meaning of local winds; land and sea breezes; valley and mountain winds; foehn winds; effects of local winds on weather and man.',
  competence: 'Learners are able to explain the daily local winds of coasts and mountains and their effects.',
  objectives: ['Define local winds.', 'Explain sea and land breezes.', 'Explain anabatic and katabatic winds.', 'Explain foehn winds.', 'Describe the effects of local winds.'],
  recall: ['Air moves from high to low pressure.', 'Land heats and cools faster than water.', 'Cold air is heavy and sinks.'],
  situation: 'Your friend lives in a village at the foot of the Mandara Mountains. He tells you that every evening after sunset, a cool breeze flows down from the slopes through the village and makes the nights pleasant, while during the day a gentle warm breeze blows up towards the mountains. Your cousin in Limbe says the same thing happens with the sea: a cool wind from the sea in the afternoon, and from the land at night. You ask: "Why do these winds change direction every day?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand local winds.'],
    ['What is the cool wind flowing down the slopes at night?', 'A mountain (katabatic) wind.'],
    ['Why does the wind in Limbe blow from the sea in the afternoon?', 'The land is hotter than the sea, so low pressure forms over the land: it is a sea breeze.']],
  justification: 'This lesson explains daily winds that affect the comfort, farming and fishing of people near coasts and mountains.',
  action: 'Use sea and land breezes for fishing and ventilation, and protect crops in valleys from cold night air.',
  activities: [
    { sec: '1. LAND AND SEA BREEZES', img: 'seabreeze.gif', caption: 'Animation: the sea breeze.', q: 'In which direction does the sea breeze blow?', a: 'From the sea to the land, during the day.', noProj: 'draw the coastline, LAND and SEA.' },
    { sec: '1. LAND AND SEA BREEZES', img: 'f2t_fishing.jpg', caption: 'Fishermen at sea.', q: 'How can fishermen use the land breeze?', a: 'It helps to push their boats out to sea at night or dawn.', noProj: 'describe fishing at Limbe.' },
    { sec: '2. VALLEY AND MOUNTAIN WINDS', img: 'anabatic_big.png', caption: 'Anabatic and katabatic winds.', q: 'Why does air flow down the slopes at night?', a: 'The slopes cool quickly, the air becomes cold and heavy, and gravity pulls it down.', noProj: 'draw day and night arrows.' },
    { sec: '3. FOEHN', img: 'foehn_big.png', caption: 'The foehn effect.', q: 'Why is the foehn warm and dry?', a: 'It lost its moisture on the windward side and warms as it descends.', noProj: 'draw the mountain and the two sides.' },
    { sec: '4. EFFECTS', img: 'met2_local.png', caption: 'The local winds.', q: 'Give one danger of warm, dry foehn winds.', a: 'Forest fires (and rapid snowmelt).', noProj: 'list effects on the board.' },
  ],
  summary: [
    D([['Local winds:', 'They are winds produced over a small area by local differences of temperature and pressure.'],
      ['Sea breeze:', 'It is a cool wind blowing from the sea to the land during the day.'],
      ['Land breeze:', 'It is a wind blowing from the land to the sea at night.'],
      ['Anabatic wind:', 'It is a warm wind blowing up the slopes during the day.'],
      ['Katabatic wind:', 'It is a cold wind blowing down the slopes at night.']]),
    { title: '1. Meaning and Categories of Local Winds', intro: 'Local winds are explained as follows:',
      items: [['Meaning:', 'Local winds blow over a small area, such as a coast or a valley, and usually last only a few hours. They are caused by local differences of heating between land and sea or between slopes and valleys, or by relief.'],
        ['Categories:', 'Thermal local winds are caused by unequal heating, such as land and sea breezes and anabatic and katabatic winds. Relief (dynamic) local winds are caused by air crossing mountains, such as the Foehn.', 'met2_local.png', 'local winds']] },
    { title: '2. Land and Sea Breezes', intro: 'Land and sea breezes form as follows:',
      items: [['Sea breeze (by day):', 'By day, the land heats faster than the sea, so the air above it rises and a low pressure forms. Cool, moist air then blows from the sea towards the land, usually from late morning to evening.', 'seabreeze_day.png', 'the sea breeze'],
        ['Land breeze (at night):', 'At night, the land cools faster than the sea, so a high pressure forms over it. Air then blows gently from the land towards the sea, which is warmer.'],
        ['Examples and effects:', 'Coastal towns such as Limbe, Kribi and Douala feel the sea breeze on hot afternoons, which makes them more comfortable. Fishermen use the land breeze to sail out to sea at dawn and the sea breeze to return in the afternoon.', 'f2t_fishing.jpg', 'fishing canoes']] },
    { title: '3. Anabatic and Katabatic Winds', intro: 'Winds on mountain slopes form as follows:',
      items: [['Anabatic (valley) wind:', 'By day, the sun heats the slopes more than the air at the same height over the valley. The warm, light air rises up the slopes, often forming clouds on the summits in the afternoon.', 'anabatic_big.png', 'anabatic and katabatic winds'],
        ['Katabatic (mountain) wind:', 'At night, the slopes lose heat quickly and cool the air in contact with them. This cold, heavy air flows down into the valley, where it collects.'],
        ['Examples and effects:', 'Villages at the foot of the Mandara Mountains and the Adamawa Plateau receive cool katabatic breezes after sunset. In cold regions, katabatic winds bring frost and fog to valley floors, and on the ice caps of Greenland and Antarctica they can be very strong.']] },
    { title: '4. Foehn Winds', intro: 'Foehn winds form as follows:',
      items: [['On the windward side:', 'Moist air is forced to rise over a mountain range, cools and forms clouds. It loses most of its moisture as rain or snow on the windward slope.', 'foehn_big.png', 'the Foehn wind'],
        ['On the leeward side:', 'The dry air then descends the other side and is compressed, so it warms quickly at the dry adiabatic rate. It reaches the foot of the mountain much warmer and drier than it was at the start.'],
        ['Examples and effects:', 'Examples are the Foehn of the Alps and the Chinook of the Rocky Mountains, which can raise the temperature by 20 °C in a few hours. They melt snow quickly, which is good for early grazing but can cause floods, and they dry the vegetation and increase the risk of forest fires.']] },
    { title: '5. Effects of Winds on Weather and Man', intro: 'Local winds have the following effects on weather and man:',
      items: [['On temperature and comfort:', 'Sea breezes cool coastal towns on hot afternoons, and katabatic winds bring cool nights to valleys. These winds make life more pleasant in hot regions.'],
        ['On clouds and rain:', 'Sea breezes and anabatic winds make moist air rise, which forms clouds and afternoon showers on coasts and mountains. Foehn winds, on the other hand, bring dry, clear weather to the leeward side.'],
        ['On agriculture:', 'Foehn winds melt snow early and help grapes and fruit to ripen. Katabatic winds can bring frost to valleys, so farmers plant sensitive crops on the slopes.'],
        ['On fishing and energy:', 'Fishermen use land and sea breezes to sail out and return. Steady local winds can also drive wind turbines to produce electricity.']] },
  ],
  evaluation: [['Explain why a sea breeze differs from a land breeze.', 'By day the land is hotter than the sea and wind blows from the sea; at night the land is cooler and wind blows from the land.'],
    ['Why is a katabatic wind cold?', 'It is air cooled on the slopes at night, which becomes heavy and flows down.']],
  remediation: ['A wind from the sea by day is a sea ______.', 'A wind blowing down slopes at night is ______.', 'The Chinook is a ______ wind.'],
  remediationAnswers: '1. breeze 2. katabatic 3. foehn',
  homework: 'Define an air mass.',
  hwAnswer: 'An air mass is a very large body of air with nearly the same temperature and humidity throughout.',
  bilingual: [['Local wind', 'Le vent local'], ['Sea breeze', 'La brise de mer'], ['Land breeze', 'La brise de terre'], ['Katabatic wind', 'Le vent catabatique'], ['Anabatic wind', 'Le vent anabatique'], ['Leeward', 'Sous le vent']],
});

L.push({ no: 18, title: 'Air Masses', topic: T6, subtopic: 'Air Masses and Effects on Climate', pointPerSlide: true,
  notions: 'Air mass, source region, continental, maritime, tropical, polar, arctic, equatorial, cT, mT, ITCZ, Harmattan, monsoon.',
  focus: 'Meaning and characteristics of air masses; source regions; classification (c/m, T/P/A/E); the air masses affecting Cameroon and West Africa (cT and mT).',
  competence: 'Learners are able to classify air masses and explain how the cT and mT air masses produce the seasons of Garoua.',
  objectives: ['Define an air mass and a source region.', 'Explain how air masses acquire their characteristics.', 'Classify air masses with the two-letter system.', 'Describe the cT and mT air masses affecting Cameroon.'],
  recall: ['The Harmattan comes from the Sahara.', 'The south-west monsoon comes from the Atlantic.', 'The ITCZ moves with the seasons.'],
  situation: 'In January in Garoua, the air is very dry, hazy and full of fine dust; lips are chapped, the ground is cracked and everything is covered with reddish powder. In August, the air was heavy and humid and everything was green after daily rains. You ask: "How can the air feel so different at different times of the year? Is it not the same air?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know what air masses are and how they change the weather.'],
    ['Why is the air of January so different from the air of August?', 'They are two different air masses.'],
    ['Where do they come from?', 'The dry air from the Sahara, the humid air from the Atlantic Ocean.']],
  justification: 'This lesson explains the origin of the dry and rainy seasons of Cameroon.',
  action: 'Recognise the air mass over Garoua from humidity, dust and clouds, and plan activities accordingly.',
  activities: [
    { sec: '1. MEANING', img: 'airmass_source_big.png', caption: 'Source regions of air masses.', q: 'What is a source region?', a: 'The large, uniform area where an air mass forms and takes its characteristics.', noProj: 'use the sponge example.' },
    { sec: '2. CLASSIFICATION', img: 'airmass_classes_big.png', caption: 'Classification of air masses.', q: 'What does the letter "m" mean in "mT"?', a: 'Maritime: formed over the sea, so moist.', noProj: 'write the codes on the board.' },
    { sec: '3. CAMEROON', img: 'wa_airmasses_big.png', caption: 'Air masses over West Africa.', q: 'Which air mass brings the rainy season to Garoua?', a: 'The tropical maritime (mT) air mass.', noProj: 'draw the two air masses and the ITF.' },
    { sec: '3. CAMEROON', img: 'f2t_harmattan.jpg', caption: 'Harmattan haze.', q: 'Is the Harmattan air stable or unstable?', a: 'Stable: it prevents clouds and rain.', noProj: 'describe a Harmattan day.' },
    { sec: '3. CAMEROON', img: 'f4_heavyrain.jpg', caption: 'Heavy rain.', q: 'Why does mT air give heavy rain?', a: 'It is moist and unstable, so it rises and forms cumulonimbus clouds.', noProj: 'describe an August storm.' },
  ],
  summary: [
    D([['Air mass:', 'It is a very large body of air with nearly the same temperature and humidity throughout at a given height.'],
      ['Source region:', 'It is the large, uniform area where an air mass forms and acquires its characteristics.'],
      ['Front:', 'It is the boundary between two air masses of different temperature and humidity.'],
      ['Intertropical Convergence Zone (ITCZ):', 'It is the zone where the air masses of the two hemispheres meet; over West Africa it is called the Intertropical Front (ITF).']]),
    { title: '1. Meaning and Characteristics of Air Masses', intro: 'Air masses have the following characteristics:',
      items: [['Size:', 'An air mass is very large and can cover thousands of square kilometres, such as the whole of the Sahara. It can reach several kilometres in height.', 'airmass_source_big.png', 'source regions of air masses'],
        ['Uniform temperature and humidity:', 'At the same height, the temperature and moisture of an air mass are almost the same everywhere. This is what distinguishes it from the air masses around it.'],
        ['Weather of its source:', 'An air mass brings the weather of its source region to the places it crosses. For example, air from the Sahara is always dry, while air from the ocean is moist.']] },
    { title: '2. Development of Air Masses', intro: 'Air masses acquire their characteristics in the following way:',
      items: [['A uniform source region:', 'An air mass forms over a large, flat and uniform surface, such as a desert, an ocean or an ice-covered plain. Mountains and mixed surfaces do not make good source regions.'],
        ['A long stay over the source:', 'The air must stay over the source for several days or weeks, usually in a calm anticyclone. Like a sponge, it slowly takes the temperature and moisture of the surface below.'],
        ['Modification when moving:', 'When the air mass moves, it is slowly changed by the surfaces it crosses. For example, dry Saharan air picks up moisture over the Gulf of Guinea, and cold air becomes unstable when it passes over a warm sea.']] },
    { title: '3. Classification and Examples', intro: 'Air masses are classified with two letters as follows:',
      items: [['First letter (humidity):', 'The letter c (continental) is used for an air mass formed over land, which is dry. The letter m (maritime) is used for an air mass formed over the sea, which is moist.'],
        ['Second letter (temperature):', 'E means equatorial (very warm), T tropical (warm), P polar (cold) and A arctic or antarctic (very cold). The letters show the latitude of the source region.', 'airmass_classes_big.png', 'the classification of air masses'],
        ['Examples:', 'cT is hot and dry, like the Saharan air; mT is warm and moist, like the air over the tropical oceans. cP is cold and dry, like the Siberian air in winter, and mP is cool and moist, like the air of the North Atlantic.']] },
    { title: '4. Types and Movements of Air Masses', intro: 'Air masses are of the following types and move as follows:',
      items: [['Warm air masses:', 'A warm air mass is warmer than the surface it moves over, so it is cooled from below. It becomes stable and brings layer clouds, drizzle and fog.'],
        ['Cold air masses:', 'A cold air mass is colder than the surface it moves over, so it is heated from below. It becomes unstable and brings cumulus clouds and showers.'],
        ['Seasonal movement:', 'Air masses move with the pressure belts, which follow the overhead sun north and south during the year. As a result, each region is dominated by different air masses in different seasons.']] },
    { title: '5. Air Masses Affecting Cameroon and West Africa', intro: 'Two air masses control the seasons of Cameroon as follows:',
      items: [['Tropical continental air (cT):', 'It forms over the Sahara and is hot by day, very dry, dusty and stable, blowing as the north-east Harmattan. It dominates the dry season in Garoua from about November to March, with sunshine, haze and low humidity.', 'f2t_harmattan.jpg', 'the Harmattan'],
        ['Tropical maritime air (mT):', 'It forms over the South Atlantic Ocean around Saint Helena and is warm, very moist and unstable, blowing as the south-west monsoon. It brings the rainy season to Garoua from about May to October, with cumulonimbus clouds and storms.', 'f4_heavyrain.jpg', 'heavy rain'],
        ['The Intertropical Front (ITF):', 'The two air masses meet along the ITF, which moves north in the northern summer and south in winter. Places south of the ITF receive rain, which explains why the rainy season is longer in the south of Cameroon than in the north.', 'wa_airmasses_big.png', 'the air masses of West Africa']] },
  ],
  evaluation: [['Distinguish a continental air mass from a maritime air mass.', 'A continental air mass forms over land and is dry; a maritime air mass forms over the sea and is moist.'],
    ['Which air mass brings the rainy season to Garoua, and why?', 'The tropical maritime (mT) air mass, because it is moist and unstable.']],
  remediation: ['An air mass takes its characteristics from its ______ region.', 'The Harmattan is a ______ air mass.', 'The two air masses meet at the ______.'],
  remediationAnswers: '1. source 2. tropical continental (cT) 3. Intertropical Front (ITF)',
  homework: 'Define climate.',
  hwAnswer: 'Climate is the average state of the weather of a place over a long period, usually 30 years.',
  bilingual: [['Air mass', "La masse d'air"], ['Continental', 'Continental'], ['Maritime', 'Maritime'], ['Harmattan', "L'harmattan"], ['Monsoon', 'La mousson'], ['Source region', 'La région source']],
});

L.push({ kind: 'Further Study', no: 2, title: 'Weather Observation, Prediction, Modification and Mapping', topic: T6, subtopic: 'Weather Observation', pointPerSlide: true,
  notions: 'Weather element, weather station, Stevenson screen, rain gauge, barometer, anemometer, radiosonde, Doppler radar, weather satellite, numerical weather prediction, cloud seeding, synoptic chart, isobar, front.',
  focus: 'Weather observation (elements and instruments); weather prediction; weather modification techniques; weather mapping with synoptic charts.',
  competence: 'Learners are able to explain how weather is observed, forecast, modified and mapped, and read a simple synoptic chart.',
  objectives: ['Name the weather elements and the instruments used to measure them.', 'Explain how weather is predicted.', 'Describe techniques of weather modification.', 'Read the main symbols of a synoptic chart.'],
  recall: ['Pressure is measured with a barometer.', 'Anticyclones bring clear weather.', 'Fronts separate air masses.'],
  situation: 'Before planting cotton, a farmer near Garoua listens to the weather forecast on the radio, which announces the first rains for next week. At the airport, a pilot checks satellite images before taking off, and in the newspaper you see a map full of lines and symbols. You ask: "How do meteorologists observe the weather, how do they forecast it, and how do they draw it on maps?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how weather is observed, predicted and mapped.'],
    ['Which instrument measures rainfall?', 'The rain gauge.'],
    ['What is a weather map called?', 'A synoptic chart.']],
  justification: 'This lesson shows how weather information is produced and used by farmers, pilots, fishermen and the public.',
  action: 'Follow weather forecasts before farming, travelling or fishing.',
  activities: [
    { sec: '1. OBSERVATION', img: 'instruments_big.png', caption: 'Instruments of a weather station.', q: 'Where are thermometers kept in a weather station?', a: 'In a Stevenson screen.', noProj: 'visit or describe a weather station.' },
    { sec: '1. OBSERVATION', img: 'lsa_radiosonde.jpg', caption: 'Launching a radiosonde.', q: 'What does a radiosonde measure?', a: 'Temperature, humidity and pressure at different heights.', noProj: 'describe a weather balloon.' },
    { sec: '2. PREDICTION', img: 'lsa_radar.jpg', caption: 'A weather radar.', q: 'What does a Doppler radar detect?', a: 'The intensity and movement of rain and storms.', noProj: 'listen to a radio forecast.' },
    { sec: '3. MODIFICATION', img: 'met2_modif.png', caption: 'Weather modification.', q: 'What is cloud seeding?', a: 'Adding silver iodide or dry ice to clouds to make them rain.', noProj: 'list the techniques.' },
    { sec: '4. MAPPING', img: 'met2_fronts.png', caption: 'Symbols of a synoptic chart.', q: 'What do closely spaced isobars indicate?', a: 'Strong winds.', noProj: 'draw isobars around an L and an H.' },
  ],
  summary: [
    D([['Weather observation:', 'It is the measurement and recording of the elements of the weather.'],
      ['Weather forecasting:', 'It is the prediction of future weather from observations and models.'],
      ['Weather modification:', 'It is the deliberate action of people to change the weather.'],
      ['Synoptic chart:', 'It is a weather map summarising the weather over a large area at a given time.'],
      ['Isobar:', 'It is a line joining places of equal atmospheric pressure.']]),
    { title: '1. Weather Observation', sub: 'A) Elements Observed at a Weather Station', intro: 'The main elements of weather are observed as follows:',
      items: [['Temperature:', 'Temperature is measured in °C with thermometers kept in a white, ventilated Stevenson screen, 1.25 m above the ground and out of direct sunlight. Maximum and minimum thermometers give the highest and lowest temperatures of each day.', 'instruments_big.png', 'weather instruments'],
        ['Rainfall (precipitation):', 'Rainfall is measured in millimetres with a rain gauge placed in an open area away from trees and buildings. The water collected is measured every morning at the same time.', 'f4_raingauge.jpg', 'a rain gauge'],
        ['Cloud cover:', 'Cloud cover is estimated by looking at the sky and dividing it into eighths, called oktas. A sky with no clouds is 0 okta and a completely covered sky is 8 oktas.']] },
    { title: '1. Weather Observation', sub: 'B) Upper-Air and Remote Observation', intro: 'The upper air and large areas are observed with the following instruments:',
      items: [['Radiosonde:', 'A radiosonde is a small box of instruments carried up to about 30 km by a balloon filled with hydrogen or helium. It sends the temperature, humidity and pressure of the upper air by radio, and tracking it gives the wind.', 'lsa_radiosonde.jpg', 'a radiosonde'],
        ['Doppler radar:', 'A Doppler radar sends out radio waves that are reflected by raindrops and hailstones. It shows where it is raining, how heavily, and in which direction and how fast the storm is moving.', 'lsa_radar.jpg', 'a weather radar'],
        ['Weather satellites:', 'Geostationary satellites, such as Meteosat over Africa, stay above the same place and send images every 15 minutes. Polar-orbiting satellites pass over the whole Earth and measure temperature and moisture at different heights.']] },
    { title: '2. Weather Prediction', intro: 'Weather is predicted in the following steps:',
      items: [['Collection of data:', 'Thousands of stations, ships, balloons, radars and satellites send their observations to world weather centres several times a day. The data are exchanged between countries through the World Meteorological Organization.', 'met2_obs.png', 'weather observations'],
        ['Numerical models:', 'Powerful computers solve the equations of the atmosphere to calculate the future weather. Forecasts are fairly reliable for about five to seven days.'],
        ['Forecasts for users:', 'Meteorologists interpret the models and inform the public, farmers, pilots and fishermen. In Cameroon, this is done by the National Meteorological Service, whose forecasts help farmers to plan sowing.']] },
    { title: '3. Weather Modification', intro: 'People try to modify the weather by the following techniques:',
      items: [['Cloud seeding:', 'Aircraft or rockets spread silver iodide or dry ice into clouds, which act as nuclei on which ice crystals and drops grow. This can increase rain or snow by about 10 %, and it is used in dry countries such as the United Arab Emirates.', 'met2_modif.png', 'weather modification'],
        ['Hail suppression:', 'Seeding a storm cloud with many nuclei makes many small hailstones instead of a few large ones. The small stones melt before reaching the ground, which protects crops and vineyards.'],
        ['Fog dispersal:', 'At airports, fog is cleared by seeding supercooled fog with dry ice or by heating the air with burners. This allows aircraft to land and take off safely.'],
        ['Hurricane modification:', 'Scientists tried to weaken hurricanes by seeding the clouds around their eye in the Stormfury project (1962 to 1983). The results were not clear, and this technique remains experimental because of the risks.']] },
    { title: '4. Weather Mapping: the Synoptic Chart', intro: 'A synoptic chart shows the weather with the following elements:',
      items: [['Isobars:', 'Isobars join places with the same pressure, usually drawn every 4 hPa. Close isobars show a steep pressure gradient and strong winds, while widely spaced isobars show light winds.', 'synoptic_big.png', 'a synoptic chart'],
        ['Pressure systems:', 'The letter H marks the centre of an anticyclone, with clear and stable weather. The letter L marks a depression, with clouds, rain and strong winds.'],
        ['Fronts:', 'A cold front is a blue line with triangles and brings cooler air and heavy showers. A warm front is a red line with semicircles and brings steady rain, and an occluded front is a purple line with both symbols.', 'met2_fronts.png', 'the symbols of fronts'],
        ['Station models and uses:', 'Small symbols at each station show its temperature, wind, cloud cover and weather. By comparing charts drawn every few hours, forecasters follow the movement of weather systems for aviation, shipping and agriculture.']] },
  ],
  evaluation: [['Explain how a radiosonde works.', 'A balloon carries instruments into the upper air; they measure temperature, humidity and pressure and send the data by radio.'],
    ['What is a synoptic chart and how is it used?', 'A weather map summarising conditions over a large area at one time; it is used to analyse and forecast the weather.']],
  remediation: ['Rainfall is measured with a rain ______.', 'Lines of equal pressure are ______.', 'Silver iodide is used for cloud ______.'],
  remediationAnswers: '1. gauge 2. isobars 3. seeding',
  homework: 'Name the two air masses that affect the climate of Cameroon.',
  hwAnswer: 'The dry tropical continental air (Harmattan) from the Sahara and the moist tropical maritime air (south-west monsoon) from the Atlantic.',
  bilingual: [['Weather forecast', 'La prévision météorologique'], ['Rain gauge', 'Le pluviomètre'], ['Barometer', 'Le baromètre'], ['Weather map', 'La carte météorologique'], ['Isobar', "L'isobare"], ['Cloud seeding', "L'ensemencement des nuages"]],
});

module.exports = { B, L };
