// LOWER SIXTH ARTS — Meteorology, part 3: Lessons 13–18 and Further Study 2 (atmospheric circulation, air masses, weather observation)
// Rewritten from the teacher's course supports (LSA_LESSONS_METEOROLOGY_2026, USA_LESSONS_METEO) in our own words; facts checked.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const { B } = require('./lsamet_1');
const L = [];
const T4 = 'Global and Local Atmospheric Circulation', T5 = 'Atmospheric Motions', T6 = 'Climates';

L.push({ no: 13, title: 'Pressure Systems', topic: T4, subtopic: 'Pressure Belts',
  notions: 'Atmospheric pressure, barometer, hectopascal, anticyclone, cyclone (depression), pressure belts, ITCZ, tricellular model, Hadley, Ferrel and polar cells, Coriolis effect.',
  focus: 'Meaning of pressure systems (anticyclones and cyclones); global distribution of pressure belts; the tricellular model with emphasis on the Hadley cell.',
  competence: 'Learners are able to explain the pressure belts and the tricellular circulation and relate them to the seasons of Garoua.',
  objectives: ['Define atmospheric pressure and pressure systems.', 'Distinguish anticyclones and cyclones and their weather.', 'Describe the global pressure belts.', 'Explain the tricellular model and the Hadley cell.'],
  recall: ['Warm air rises and cool air sinks.', 'Rising air cools and forms clouds.', 'The Sahara lies near 20–30° N.'],
  situation: 'Watching the weather news, you see heavy thunderstorms over the Congo Basin near the Equator while the Sahara, near 25° N, has clear skies and dry heat. The presenter speaks of "low pressure" over one region and "high pressure" over the other. In Garoua, the dry north-east wind blows for months, then the moist south-west wind comes. You ask: "What are these pressure systems, and how do they organise the winds and weather of the world?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the pressure systems and the global circulation of the atmosphere.'],
    ['Why is there heavy rain near the Equator?', 'Air rises in a low-pressure zone (the ITCZ), cools and forms rain clouds.'],
    ['Why is the Sahara dry?', 'Air sinks in the subtropical high-pressure belt, so clouds do not form.']],
  justification: 'This lesson explains the great belts of pressure and winds that control the climates of the world and of Cameroon.',
  action: 'Read pressure on weather maps to understand the coming weather.',
  activities: [
    { sec: '1. PRESSURE SYSTEMS', img: 'f4_barometer.jpg', caption: 'A barometer.', q: 'Which instrument measures atmospheric pressure?', a: 'The barometer.', noProj: 'press on a table to show weight.' },
    { sec: '1. PRESSURE SYSTEMS', img: 'met2_pressure.png', caption: 'Low and high pressure.', q: 'What weather is associated with an anticyclone?', a: 'Clear skies, dry and calm weather.', noProj: 'draw rising and sinking air.' },
    { sec: '2. PRESSURE BELTS', img: 'pressure_belts_big.png', caption: 'The pressure belts of the world.', q: 'Which pressure belt lies around 30° N and S?', a: 'The subtropical high-pressure belt.', noProj: 'draw the belts on a globe sketch.' },
    { sec: '3. TRICELLULAR MODEL', img: 'tricellular_big.png', caption: 'The three cells.', q: 'Name the three cells of each hemisphere.', a: 'The Hadley, Ferrel and polar cells.', noProj: 'draw the three cells.' },
    { sec: '3. HADLEY CELL', img: 'hadley.gif', caption: 'Animation: the Hadley cell.', q: 'Which surface winds complete the Hadley cell in the northern hemisphere?', a: 'The north-east trade winds (the Harmattan over West Africa).', noProj: 'draw the four steps of the cell.' },
  ],
  summary: [
    D([['Atmospheric pressure:', 'It is the force exerted by the weight of the air on a unit area of the surface, measured in hectopascals (hPa).'],
      ['Anticyclone:', 'It is a high-pressure system of sinking air that brings clear, dry weather.'],
      ['Cyclone (depression):', 'It is a low-pressure system of rising air that brings clouds and rain.'],
      ['Tricellular model:', 'It is a model of three circulation cells in each hemisphere that carry heat from the Equator to the poles.']]),
    { title: '1. Meaning of Pressure Systems', intro: 'Pressure systems are presented as follows:',
      items: [['Atmospheric pressure:', 'The average pressure at sea level is about 1,013 hPa; it falls with altitude.', 'f4_barometer.jpg', 'a barometer'],
        ['High pressure (anticyclone):', 'Air sinks and spreads out at the surface, giving clear, dry and calm weather.', 'met2_pressure.png', 'low and high pressure'],
        ['Low pressure (cyclone, depression):', 'Air converges and rises, giving clouds, rain and often storms.'],
        ['Wind:', 'Air moves from high pressure towards low pressure.']] },
    { title: '2. Global Distribution of Pressure Belts', intro: 'The pressure belts of the world are the following:',
      items: [['Equatorial low (ITCZ):', 'Strong heating makes air rise near the Equator, giving heavy rain and rainforests, as in southern Cameroon.', 'pressure_belts_big.png', 'the pressure belts'],
        ['Subtropical highs (about 30° N and S):', 'Air sinks and gives arid conditions and deserts like the Sahara.'],
        ['Subpolar lows (about 60° N and S):', 'Cold polar air meets warmer air, which rises and forms depressions.'],
        ['Polar highs:', 'Very cold, dense air sinks over the poles.'],
        ['Seasonal shift:', 'The belts move north and south with the overhead sun, which explains the seasons of Garoua.']] },
    { title: '3. The Tricellular Model', intro: 'The tricellular model is presented as follows:',
      items: [['Three cells:', ['Hadley cell: from the Equator to about 30°.', 'Ferrel cell: from about 30° to 60°.', 'Polar cell: from about 60° to the poles.']],
        ['Illustration:', 'The cells carry heat from the zone of surplus to the zones of deficit.', 'tricellular_big.png', 'the three cells'],
        ['Hadley cell, step 1:', 'Air heated at the Equator rises and forms the ITCZ, with heavy rain.', 'hadley_first.png', 'the Hadley cell'],
        ['Steps 2 and 3:', 'At high altitude the air moves poleward, cools and sinks near 30°, forming the subtropical high and deserts.'],
        ['Step 4:', 'Surface air returns to the Equator; deflected by the Coriolis effect, it becomes the north-east trade winds, the Harmattan of Garoua.']] },
  ],
  evaluation: [['Distinguish an anticyclone from a depression.', 'An anticyclone is high pressure with sinking air and clear weather; a depression is low pressure with rising air, clouds and rain.'],
    ['Explain how the Hadley cell creates the Sahara Desert.', 'Air rising at the Equator moves poleward, cools and sinks near 30° N, forming high pressure where clouds cannot form.']],
  remediation: ['Pressure is measured with a ______.', 'Sinking air forms ______ pressure.', 'The cell between the Equator and 30° is the ______ cell.'],
  remediationAnswers: '1. barometer 2. high 3. Hadley',
  homework: 'State why warm air rises.',
  hwAnswer: 'Warm air rises because it is lighter (less dense) than the cooler air around it.',
  bilingual: [['Air pressure', 'La pression atmosphérique'], ['Wind', 'Le vent'], ['Circulation', 'La circulation'], ['Hadley cell', 'La cellule de Hadley'], ['Anticyclone', "L'anticyclone"], ['Depression', 'La dépression']],
});

L.push({ no: 14, title: 'Vertical Motions: Stability and Instability', topic: T4, subtopic: 'Atmospheric Motions',
  notions: 'Vertical motion, air parcel, instability (absolute, conditional), stability (absolute, neutral), adiabatic, dry adiabatic lapse rate (DALR), saturated adiabatic lapse rate (SALR), environmental lapse rate (ELR).',
  focus: 'Meaning of vertical motions; atmospheric instability and its weather; atmospheric stability and its weather; the role of adiabatic lapse rates in determining stability.',
  competence: 'Learners are able to explain why some days bring storms and others clear skies by comparing lapse rates.',
  objectives: ['Define vertical motions and an air parcel.', 'Explain atmospheric instability and its weather.', 'Explain atmospheric stability and its weather.', 'Use the DALR, SALR and ELR to determine stability.'],
  recall: ['Temperature falls about 6.5 °C per km (ELR).', 'Rising air expands and cools.', 'Latent heat is released when vapour condenses.'],
  situation: 'Your teacher fills one balloon with warm air from a hair dryer and another near a bowl of ice. The warm balloon rises easily while the cold one stays down. You remember that some afternoons in Garoua small clouds grow into huge storm clouds, while on other days, especially in the Harmattan, the sky stays clear and hazy all day. You ask: "Why does air rise freely on some days and not on others?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand atmospheric stability and instability.'],
    ['Why does the warm balloon rise?', 'Warm air is lighter than the cooler air around it.'],
    ['What kind of atmosphere produces storm clouds?', 'An unstable atmosphere, where rising air keeps rising.']],
  justification: 'This lesson helps us to understand and forecast storms, clear days, fog and pollution episodes.',
  action: 'Watch for towering clouds on unstable afternoons and shelter from storms and lightning.',
  activities: [
    { sec: '1. VERTICAL MOTIONS', img: 'parcel.gif', caption: 'Animation: a rising air parcel.', q: 'What is an air parcel?', a: 'A small imaginary volume of air that rises or sinks without mixing with the air around it.', noProj: 'use the two balloons.' },
    { sec: '2. INSTABILITY', img: 'f4_cumulonimbus.jpg', caption: 'A towering cumulonimbus.', q: 'What weather does instability bring?', a: 'Cumulonimbus clouds, thunderstorms, heavy rain and hail.', noProj: 'describe an afternoon storm.' },
    { sec: '3. STABILITY', img: 'lsa_smog.jpg', caption: 'Haze trapped in stable air.', q: 'Why does pollution build up in stable air?', a: 'Air does not rise, so there is no vertical mixing.', noProj: 'describe Harmattan haze.' },
    { sec: '4. LAPSE RATES', img: 'stability_big.png', caption: 'Lapse rates and stability.', q: 'Why does saturated air cool more slowly than dry air?', a: 'Condensation releases latent heat.', noProj: 'draw the DALR and SALR lines.' },
    { sec: '4. LAPSE RATES', img: 'met2_stab_rules.png', caption: 'Rules of stability.', q: 'If the ELR is greater than the DALR, is the air stable or unstable?', a: 'Absolutely unstable.', noProj: 'write the three rules.' },
  ],
  summary: [
    D([['Vertical motions:', 'They are the upward and downward movements of air in the atmosphere.'],
      ['Instability:', 'It is the state in which a lifted air parcel keeps rising because it is warmer than the air around it.'],
      ['Stability:', 'It is the state in which a lifted air parcel sinks back because it is cooler than the air around it.'],
      ['Adiabatic cooling:', 'It is the cooling of rising air by expansion, without exchange of heat with the surrounding air.']]),
    { title: '1. Meaning of Vertical Motions', intro: 'Vertical motions are presented as follows:',
      items: [['Rising and sinking air:', 'Whether air rises or sinks depends on its temperature compared with the air around it.', 'parcel_last.png', 'a rising air parcel'],
        ['Importance:', 'Rising air forms clouds and rain, while sinking air brings clear skies.']] },
    { title: '2. Atmospheric Instability', intro: 'Atmospheric instability is presented as follows:',
      items: [['Meaning:', 'A lifted parcel stays warmer and lighter than its surroundings, so it keeps rising.'],
        ['Types:', ['Absolute instability: the parcel is always warmer than its environment.', 'Conditional instability: the air is stable when dry but unstable once saturated.', 'Potential instability: the air becomes unstable after surface heating or added moisture.']],
        ['Weather:', 'Cumulus and cumulonimbus clouds, thunderstorms, heavy rain, hail and strong turbulence, as on rainy-season afternoons in Garoua.', 'f4_cumulonimbus.jpg', 'a cumulonimbus']] },
    { title: '3. Atmospheric Stability', intro: 'Atmospheric stability is presented as follows:',
      items: [['Meaning:', 'A lifted parcel becomes cooler and heavier than its surroundings and sinks back.'],
        ['Types:', ['Absolute stability: the parcel is always cooler than its environment.', 'Neutral stability: the parcel has the same temperature as its environment.']],
        ['Weather:', 'Clear skies and calm weather, fog and low stratus in moist air, and trapped pollution, as in the Harmattan haze.', 'lsa_smog.jpg', 'haze in stable air']] },
    { title: '4. Role of the Adiabatic Lapse Rates', intro: 'Stability is determined by comparing the following lapse rates:',
      items: [['Dry adiabatic lapse rate (DALR):', 'Unsaturated rising air cools by about 10 °C per km.', 'stability_big.png', 'lapse rates and stability'],
        ['Saturated adiabatic lapse rate (SALR):', 'Saturated air cools more slowly, about 5–7 °C per km, because condensation releases latent heat.'],
        ['Environmental lapse rate (ELR):', 'It is the real fall of temperature of the surrounding air with height, on average 6.5 °C per km.'],
        ['Rules:', ['ELR greater than DALR: absolute instability.', 'ELR between SALR and DALR: conditional instability.', 'ELR smaller than SALR: absolute stability.']],
        ['Summary table:', 'Each case brings its own type of weather.', 'met2_stab_rules.png', 'rules of stability']] },
  ],
  evaluation: [['Distinguish a stable from an unstable atmosphere.', 'In a stable atmosphere, lifted air sinks back and skies stay clear; in an unstable atmosphere, lifted air keeps rising and forms storm clouds.'],
    ['Why does saturated air cool more slowly than dry air?', 'Condensation releases latent heat, which partly compensates for the cooling.']],
  remediation: ['Dry air cools at about ______ °C per km.', 'An ELR greater than the DALR gives ______ instability.', 'Stable air often traps ______.'],
  remediationAnswers: '1. 10 2. absolute 3. pollution (haze, fog)',
  homework: 'Define wind.',
  hwAnswer: 'Wind is the movement of air from an area of high pressure to an area of low pressure.',
  bilingual: [['Stability', 'La stabilité'], ['Instability', "L'instabilité"], ['Air parcel', "La particule d'air"], ['Lapse rate', 'Le gradient thermique'], ['Thunderstorm', "L'orage"], ['Latent heat', 'La chaleur latente']],
});

L.push({ no: 15, title: 'Planetary Winds', topic: T4, subtopic: 'Macroscale or Global Scale Winds',
  notions: 'Wind, pressure gradient, Coriolis effect, Ferrel\'s law, planetary winds, trade winds, westerlies, polar easterlies, doldrums, horse latitudes.',
  focus: 'Meaning of wind and planetary winds; the Coriolis effect; the three planetary winds (trade winds, westerlies, polar easterlies) and their characteristics.',
  competence: 'Learners are able to explain the pattern of planetary winds and the winds that affect Cameroon.',
  objectives: ['Define wind and planetary winds.', 'Explain the causes of wind and the Coriolis effect.', 'Describe the trade winds.', 'Describe the westerlies and the polar easterlies.'],
  recall: ['Air moves from high to low pressure.', 'Pressure belts lie at 0°, 30°, 60° and 90°.', 'The Hadley cell produces the north-east trade winds.'],
  situation: 'In an old book, you read that sailing ships crossing the Atlantic followed winds that "always blow from the same direction", which sailors called the trade winds. Near the Equator, the ships were sometimes stuck for days without wind. You then notice that the Harmattan blows over Garoua from the north-east for months. You ask: "Which great winds blow over the Earth, and why do they not blow straight from north to south?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the planetary winds and their directions.'],
    ['What are the trade winds?', 'Steady winds blowing from the subtropical highs towards the Equator.'],
    ['Why do winds curve instead of blowing straight?', 'Because of the rotation of the Earth (the Coriolis effect).']],
  justification: 'This lesson explains the permanent winds that move heat and moisture around the world and influence the climate of Cameroon.',
  action: 'Use wind directions to explain the dry and rainy seasons of your region.',
  activities: [
    { sec: '1. WIND', img: 'f4_windsock.jpg', caption: 'A windsock.', q: 'Why does wind blow?', a: 'Air moves from high pressure to low pressure.', noProj: 'observe the direction of smoke.' },
    { sec: '1. CORIOLIS EFFECT', img: 'coriolis.gif', caption: 'Animation: the Coriolis effect.', q: 'To which side are winds deflected in the northern hemisphere?', a: 'To the right.', noProj: 'draw a line on a spinning paper disc.' },
    { sec: '2. PLANETARY WINDS', img: 'planetary_winds_big.png', caption: 'The planetary winds.', q: 'Which winds blow between the subtropical highs and the Equator?', a: 'The trade winds.', noProj: 'draw the winds on a globe sketch.' },
    { sec: '2. PLANETARY WINDS', img: 'lsa_ship.jpg', caption: 'A sailing ship.', q: 'Why were the trade winds useful to sailors?', a: 'They blow steadily in the same direction.', noProj: 'trace a sailing route.' },
    { sec: '2. PLANETARY WINDS', img: 'f4_bigwaves.jpg', caption: 'Stormy seas.', q: 'Why are the westerlies stronger in the southern hemisphere?', a: 'There is little land to slow them down.', noProj: 'compare the two hemispheres.' },
  ],
  summary: [
    D([['Wind:', 'It is the horizontal movement of air from high pressure to low pressure.'],
      ['Planetary winds:', 'They are permanent winds that blow all year between the pressure belts.'],
      ['Coriolis effect:', 'It is the deflection of winds by the rotation of the Earth: to the right in the northern hemisphere and to the left in the southern hemisphere.']]),
    { title: '1. Meaning and Causes of Wind', intro: 'Winds are caused and deflected as follows:',
      items: [['Pressure gradient:', 'The bigger the difference in pressure, the stronger the wind.', 'f4_windsock.jpg', 'a windsock'],
        ['Coriolis effect (Ferrel\'s law):', 'The rotation of the Earth deflects winds to the right in the northern hemisphere and to the left in the southern hemisphere.', 'coriolis_last.png', 'the Coriolis effect'],
        ['Naming winds:', 'A wind is named after the direction it comes from: a north-east wind blows from the north-east.']] },
    { title: '2. Types of Planetary Winds', intro: 'The three planetary winds are the following:',
      items: [['Trade winds:', 'They blow from the subtropical highs (30°) to the Equator: from the north-east in the northern hemisphere and from the south-east in the southern hemisphere.', 'planetary_winds_big.png', 'the planetary winds'],
        ['Characteristics of the trade winds:', 'They are steady and regular, dry over land like the Harmattan and moist over oceans, and meet at the ITCZ.', 'lsa_ship.jpg', 'a sailing ship'],
        ['Westerlies:', 'They blow from the subtropical highs to the subpolar lows (30°–60°), from the west; they are variable, bring depressions and rain to Europe, and are strongest in the southern hemisphere ("Roaring Forties").', 'f4_bigwaves.jpg', 'stormy seas'],
        ['Polar easterlies:', 'They blow from the polar highs to the subpolar lows; they are cold, dry and irregular.'],
        ['Calm belts:', 'The doldrums at the Equator and the horse latitudes near 30° have light, variable winds.'],
        ['Summary:', 'The three winds form a regular pattern in each hemisphere.', 'met2_winds3.png', 'the three planetary winds']] },
  ],
  evaluation: [['Describe the trade winds.', 'Steady winds blowing from the subtropical highs to the Equator, from the north-east (N. hemisphere) and south-east (S. hemisphere).'],
    ['Explain the Coriolis effect.', 'The rotation of the Earth deflects winds to the right in the northern hemisphere and to the left in the southern hemisphere.']],
  remediation: ['Winds blow from high to ______ pressure.', 'The winds between 30° and 60° are the ______.', 'The calm belt at the Equator is the ______.'],
  remediationAnswers: '1. low 2. westerlies 3. doldrums',
  homework: 'Name the dry wind that blows over Garoua in the dry season.',
  hwAnswer: 'The Harmattan (north-east trade wind from the Sahara).',
  bilingual: [['Wind', 'Le vent'], ['Trade winds', 'Les alizés'], ['Westerlies', "Les vents d'ouest"], ['Coriolis effect', "L'effet de Coriolis"], ['Doldrums', 'Le pot au noir'], ['Pressure gradient', 'Le gradient de pression']],
});

L.push({ no: 16, title: 'Tropical Seasonal Winds: Monsoon and Harmattan', topic: T4, subtopic: 'Mesoscale Winds',
  notions: 'Monsoon, summer (wet) monsoon, winter (dry) monsoon, differential heating, Harmattan, West African monsoon, ITCZ.',
  focus: 'Monsoon winds: meaning, causes, areas and effects (Asia, West Africa); the Harmattan: meaning, causes and effects in Cameroon.',
  competence: 'Learners are able to explain the seasonal reversal of winds and adapt to the effects of the monsoon and the Harmattan in Garoua.',
  objectives: ['Define the monsoon and the Harmattan.', 'Explain the causes of the summer and winter monsoons.', 'Describe the areas and effects of monsoons.', 'Explain the positive and negative effects of the Harmattan.'],
  recall: ['Land heats and cools faster than the sea.', 'The Harmattan is part of the north-east trade winds.', 'The ITCZ moves with the overhead sun.'],
  situation: 'In mid-January in Garoua, a cool, dusty wind blows from the north, the sky is hazy, dust covers everything, lips crack and many people cough. Five months earlier, in August, the wind came from the south, the air was heavy with moisture and heavy rain fell almost every day. You ask: "Why does the wind completely change its direction and character during the year?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand the seasonal reversal of winds.'],
    ['What is the dry, dusty wind of January called?', 'The Harmattan.'],
    ['Why is the August wind wet?', 'It comes from the Atlantic Ocean: it is the south-west monsoon.']],
  justification: 'This lesson explains the rainy and dry seasons that control farming, health and daily life in Garoua.',
  action: 'Protect your health during the Harmattan (drink water, cover your nose, avoid bush fires) and prepare fields before the monsoon rains.',
  activities: [
    { sec: '1. MONSOON', img: 'met2_monsoon.png', caption: 'Summer and winter monsoons.', q: 'Why does the summer monsoon bring rain?', a: 'It blows from the sea to the hot land and carries moisture.', noProj: 'draw arrows sea→land and land→sea.' },
    { sec: '1. MONSOON', img: 'lsa_monsoon.jpg', caption: 'Monsoon rain in Asia.', q: 'Give one negative effect of the Asian monsoon.', a: 'Floods, landslides and loss of life.', noProj: 'locate India and Bangladesh.' },
    { sec: '1. WEST AFRICAN MONSOON', img: 'itcz.gif', caption: 'Animation: the rain belt moves during the year.', q: 'When does the south-west monsoon reach Garoua?', a: 'From about May to September–October.', noProj: 'draw the ITCZ in January and July.' },
    { sec: '2. HARMATTAN', img: 'f2t_harmattan.jpg', caption: 'Harmattan haze.', q: 'Where does the Harmattan come from?', a: 'From the Sahara Desert.', noProj: 'draw the arrow from the Sahara.' },
    { sec: '2. HARMATTAN', img: 'met2_harmattan.png', caption: 'Effects of the Harmattan.', q: 'Give one positive effect of the Harmattan.', a: 'Cool nights, drying of crops, or fewer mosquitoes.', noProj: 'list effects in two columns.' },
  ],
  summary: [
    D([['Monsoon:', 'It is a seasonal wind that reverses its direction between summer and winter.'],
      ['Harmattan:', 'It is the dry, dusty north-east wind that blows from the Sahara over West Africa in the dry season.']]),
    { title: '1. Monsoon Winds', sub: 'A) Meaning and Causes', intro: 'Monsoon winds are caused as follows:',
      items: [['Differential heating:', 'Land heats and cools faster than the sea, so pressure over land changes with the seasons.', 'met2_monsoon.png', 'summer and winter monsoons'],
        ['Summer (wet) monsoon:', 'The hot land forms low pressure; moist air blows from the sea to the land and brings heavy rain.'],
        ['Winter (dry) monsoon:', 'The cold land forms high pressure; dry air blows from the land to the sea.'],
        ['Role of the ITCZ:', 'The shift of the ITCZ with the overhead sun drives the reversal of winds.', 'itcz_july.png', 'the ITCZ in July']] },
    { title: '1. Monsoon Winds', sub: 'B) Areas and Effects', intro: 'Monsoons occur in the following areas with the following effects:',
      items: [['South Asia (India, Bangladesh):', 'The summer monsoon brings the rain needed for rice and fills rivers and reservoirs.', 'lsa_monsoon.jpg', 'monsoon rain'],
        ['Negative effects in Asia:', 'Very heavy rains cause floods, landslides and loss of life.'],
        ['Winter monsoon in Asia:', 'It brings a long, dry and cool season, good for harvesting.'],
        ['West Africa and Cameroon:', 'The moist south-west monsoon from the Atlantic brings the rainy season to Garoua (about May to October), for millet, sorghum, maize and cotton.']] },
    { title: '2. The Harmattan', intro: 'The Harmattan is presented as follows:',
      items: [['Origin:', 'It blows from the Sahara, where high pressure forms in the northern winter; it is the north-east trade wind and the winter monsoon of West Africa.', 'f2t_harmattan.jpg', 'Harmattan haze'],
        ['Character:', 'It is very dry and dusty, cool at night and in the morning, and hot in the afternoon.'],
        ['Negative effects:', ['Dust haze and poor visibility that can disturb flights at Garoua airport.', 'Coughs, catarrh, asthma, dry skin and cracked lips.', 'Dry vegetation and a high risk of bush fires.', 'Dust on houses, goods and food.']],
        ['Positive effects:', ['Relief from heat with cool nights.', 'Dry air for harvesting and drying millet, beans and cotton.', 'Fewer mosquitoes and less malaria.']],
        ['Summary:', 'The Harmattan is both a problem and a help.', 'met2_harmattan.png', 'effects of the Harmattan']] },
  ],
  evaluation: [['Why is the summer monsoon wet and the winter monsoon dry?', 'The summer monsoon blows from the sea and carries moisture; the winter monsoon blows from the land and is dry.'],
    ['Give two negative effects of the Harmattan in Garoua.', 'Poor visibility, respiratory diseases, cracked lips and dry skin, bush fires (any two).']],
  remediation: ['A wind that reverses with the seasons is a ______.', 'The Harmattan comes from the ______.', 'The rainy season wind of Garoua is the south-west ______.'],
  remediationAnswers: '1. monsoon 2. Sahara 3. monsoon',
  homework: 'Define a sea breeze.',
  hwAnswer: 'A sea breeze is a cool wind that blows from the sea to the land during the day.',
  bilingual: [['Monsoon', 'La mousson'], ['Harmattan', "L'harmattan"], ['Season', 'La saison'], ['Dust', 'La poussière'], ['Humidity', "L'humidité"], ['Bush fire', 'Le feu de brousse']],
});

L.push({ no: 17, title: 'Local Winds', topic: T5, subtopic: 'Microscale (Local) Winds',
  notions: 'Local wind, sea breeze, land breeze, anabatic (valley) wind, katabatic (mountain) wind, foehn, Chinook.',
  focus: 'Meaning of local winds; land and sea breezes; valley and mountain winds; foehn winds; effects of local winds on weather and man.',
  competence: 'Learners are able to explain the daily local winds of coasts and mountains and their effects.',
  objectives: ['Define local winds.', 'Explain sea and land breezes.', 'Explain anabatic and katabatic winds.', 'Explain foehn winds.', 'Describe the effects of local winds.'],
  recall: ['Air moves from high to low pressure.', 'Land heats and cools faster than water.', 'Cold air is heavy and sinks.'],
  situation: 'Your friend lives in a village at the foot of the Mandara Mountains. He tells you that every evening after sunset, a cool breeze flows down from the slopes through the village and makes the nights pleasant, while during the day a gentle warm breeze blows up towards the mountains. Your cousin in Limbe says the same thing happens with the sea: a cool wind from the sea in the afternoon, and from the land at night. You ask: "Why do these winds change direction every day?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand local winds.'],
    ['What is the cool wind flowing down the slopes at night?', 'A mountain (katabatic) wind.'],
    ['Why does the wind in Limbe blow from the sea in the afternoon?', 'The land is hotter than the sea, so low pressure forms over the land: it is a sea breeze.']],
  justification: 'This lesson explains daily winds that affect the comfort, farming and fishing of people near coasts and mountains.',
  action: 'Use sea and land breezes for fishing and ventilation, and protect crops in valleys from cold night air.',
  activities: [
    { sec: '1. LAND AND SEA BREEZES', img: 'seabreeze.gif', caption: 'Animation: the sea breeze.', q: 'In which direction does the sea breeze blow?', a: 'From the sea to the land, during the day.', noProj: 'draw the coastline, LAND and SEA.' },
    { sec: '1. LAND AND SEA BREEZES', img: 'f2t_fishing.jpg', caption: 'Fishermen at sea.', q: 'How can fishermen use the land breeze?', a: 'It helps to push their boats out to sea at night or dawn.', noProj: 'describe fishing at Limbe.' },
    { sec: '2. VALLEY AND MOUNTAIN WINDS', img: 'anabatic_big.png', caption: 'Anabatic and katabatic winds.', q: 'Why does air flow down the slopes at night?', a: 'The slopes cool quickly, the air becomes cold and heavy, and gravity pulls it down.', noProj: 'draw day and night arrows.' },
    { sec: '3. FOEHN', img: 'foehn_big.png', caption: 'The foehn effect.', q: 'Why is the foehn warm and dry?', a: 'It lost its moisture on the windward side and warms as it descends.', noProj: 'draw the mountain and the two sides.' },
    { sec: '4. EFFECTS', img: 'met2_local.png', caption: 'The local winds.', q: 'Give one danger of warm, dry foehn winds.', a: 'Forest fires (and rapid snowmelt).', noProj: 'list effects on the board.' },
  ],
  summary: [
    D([['Local winds:', 'They are winds produced over a small area by local differences of temperature and pressure.'],
      ['Sea breeze:', 'It is a cool wind blowing from the sea to the land during the day.'],
      ['Land breeze:', 'It is a wind blowing from the land to the sea at night.'],
      ['Anabatic wind:', 'It is a warm wind blowing up the slopes during the day.'],
      ['Katabatic wind:', 'It is a cold wind blowing down the slopes at night.']]),
    { title: '1. Land and Sea Breezes', intro: 'Land and sea breezes form as follows:',
      items: [['Sea breeze (day):', 'The land heats faster than the sea, so low pressure forms over the land and cool, moist air blows in from the sea.', 'seabreeze_day.png', 'the sea breeze'],
        ['Land breeze (night):', 'The land cools faster than the sea, so high pressure forms over the land and air blows out to sea.'],
        ['Example:', 'Coastal towns such as Limbe, Kribi and Douala feel sea breezes in the afternoon.', 'f2t_fishing.jpg', 'fishermen at sea']] },
    { title: '2. Valley and Mountain Winds', intro: 'Valley and mountain winds form as follows:',
      items: [['Anabatic (valley) wind:', 'By day, the sun heats the slopes, and the warm, light air rises up the slopes from the valley.', 'anabatic_big.png', 'anabatic and katabatic winds'],
        ['Katabatic (mountain) wind:', 'At night, the slopes cool quickly, and cold, heavy air flows down into the valley.'],
        ['Example:', 'Villages at the foot of the Mandara Mountains receive cool katabatic breezes after sunset.']] },
    { title: '3. Foehn Winds', intro: 'Foehn winds form as follows:',
      items: [['Windward side:', 'Moist air rises over a mountain, cools and loses its moisture as rain.', 'foehn_big.png', 'the foehn effect'],
        ['Leeward side:', 'The dry air descends, is compressed and warms quickly.'],
        ['Examples:', 'The Foehn of the Alps and the Chinook of the Rocky Mountains.'],
        ['Effects:', 'They melt snow rapidly and increase the risk of forest fires.']] },
    { title: '4. Effects of Local Winds on Weather and Man', intro: 'Local winds have the following effects:',
      items: [['Temperature:', 'Sea breezes cool coastal towns on hot afternoons.', 'met2_local.png', 'the local winds'],
        ['Agriculture:', 'Katabatic winds bring cold air into valleys and can damage crops, while foehn winds ripen fruit but dry the soil.'],
        ['Pollution:', 'Land breezes can carry pollution out to sea.'],
        ['Comfort and energy:', 'Gentle breezes are pleasant, dusty winds cause diseases, and steady winds can drive wind turbines.']] },
  ],
  evaluation: [['Explain why a sea breeze differs from a land breeze.', 'By day the land is hotter than the sea and wind blows from the sea; at night the land is cooler and wind blows from the land.'],
    ['Why is a katabatic wind cold?', 'It is air cooled on the slopes at night, which becomes heavy and flows down.']],
  remediation: ['A wind from the sea by day is a sea ______.', 'A wind blowing down slopes at night is ______.', 'The Chinook is a ______ wind.'],
  remediationAnswers: '1. breeze 2. katabatic 3. foehn',
  homework: 'Define an air mass.',
  hwAnswer: 'An air mass is a very large body of air with nearly the same temperature and humidity throughout.',
  bilingual: [['Local wind', 'Le vent local'], ['Sea breeze', 'La brise de mer'], ['Land breeze', 'La brise de terre'], ['Katabatic wind', 'Le vent catabatique'], ['Anabatic wind', 'Le vent anabatique'], ['Leeward', 'Sous le vent']],
});

L.push({ no: 18, title: 'Air Masses', topic: T6, subtopic: 'Air Masses and Effects on Climate',
  notions: 'Air mass, source region, continental, maritime, tropical, polar, arctic, equatorial, cT, mT, ITCZ, Harmattan, monsoon.',
  focus: 'Meaning and characteristics of air masses; source regions; classification (c/m, T/P/A/E); the air masses affecting Cameroon and West Africa (cT and mT).',
  competence: 'Learners are able to classify air masses and explain how the cT and mT air masses produce the seasons of Garoua.',
  objectives: ['Define an air mass and a source region.', 'Explain how air masses acquire their characteristics.', 'Classify air masses with the two-letter system.', 'Describe the cT and mT air masses affecting Cameroon.'],
  recall: ['The Harmattan comes from the Sahara.', 'The south-west monsoon comes from the Atlantic.', 'The ITCZ moves with the seasons.'],
  situation: 'In January in Garoua, the air is very dry, hazy and full of fine dust; lips are chapped, the ground is cracked and everything is covered with reddish powder. In August, the air was heavy and humid and everything was green after daily rains. You ask: "How can the air feel so different at different times of the year? Is it not the same air?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know what air masses are and how they change the weather.'],
    ['Why is the air of January so different from the air of August?', 'They are two different air masses.'],
    ['Where do they come from?', 'The dry air from the Sahara, the humid air from the Atlantic Ocean.']],
  justification: 'This lesson explains the origin of the dry and rainy seasons of Cameroon.',
  action: 'Recognise the air mass over Garoua from humidity, dust and clouds, and plan activities accordingly.',
  activities: [
    { sec: '1. MEANING', img: 'airmass_source_big.png', caption: 'Source regions of air masses.', q: 'What is a source region?', a: 'The large, uniform area where an air mass forms and takes its characteristics.', noProj: 'use the sponge example.' },
    { sec: '2. CLASSIFICATION', img: 'airmass_classes_big.png', caption: 'Classification of air masses.', q: 'What does the letter "m" mean in "mT"?', a: 'Maritime: formed over the sea, so moist.', noProj: 'write the codes on the board.' },
    { sec: '3. CAMEROON', img: 'wa_airmasses_big.png', caption: 'Air masses over West Africa.', q: 'Which air mass brings the rainy season to Garoua?', a: 'The tropical maritime (mT) air mass.', noProj: 'draw the two air masses and the ITF.' },
    { sec: '3. CAMEROON', img: 'f2t_harmattan.jpg', caption: 'Harmattan haze.', q: 'Is the Harmattan air stable or unstable?', a: 'Stable: it prevents clouds and rain.', noProj: 'describe a Harmattan day.' },
    { sec: '3. CAMEROON', img: 'f4_heavyrain.jpg', caption: 'Heavy rain.', q: 'Why does mT air give heavy rain?', a: 'It is moist and unstable, so it rises and forms cumulonimbus clouds.', noProj: 'describe an August storm.' },
  ],
  summary: [
    D([['Air mass:', 'It is a very large body of air with nearly the same temperature and humidity throughout at a given height.'],
      ['Source region:', 'It is the large, uniform area where an air mass forms and acquires its characteristics.']]),
    { title: '1. Meaning and Characteristics of Air Masses', intro: 'Air masses are presented as follows:',
      items: [['Size:', 'An air mass covers thousands of square kilometres.', 'airmass_source_big.png', 'source regions'],
        ['Acquired characteristics:', 'Air staying long over a surface takes its temperature and moisture, like a sponge.'],
        ['Good source regions:', 'Large, flat and uniform areas such as deserts, oceans and ice-covered lands.'],
        ['Movement:', 'When an air mass moves, it brings the weather of its source region.']] },
    { title: '2. Classification of Air Masses', intro: 'Air masses are classified with two letters as follows:',
      items: [['First letter (moisture):', ['c = continental: formed over land, dry.', 'm = maritime: formed over the sea, moist.']],
        ['Second letter (temperature):', ['E = equatorial: very warm.', 'T = tropical: warm.', 'P = polar: cold.', 'A = arctic or antarctic: very cold.']],
        ['Examples:', 'cT is hot and dry (Sahara), mT is warm and moist (tropical oceans), cP is cold and dry (Siberia).', 'airmass_classes_big.png', 'classification of air masses']] },
    { title: '3. Air Masses Affecting Cameroon and West Africa', intro: 'Two air masses control the seasons of Cameroon as follows:',
      items: [['Tropical continental (cT):', 'It comes from the Sahara; it is hot, very dry, dusty and stable, and blows as the Harmattan.', 'f2t_harmattan.jpg', 'Harmattan haze'],
        ['Influence of cT:', 'It dominates the dry season (about November to March in Garoua), with sunshine, haze, low humidity and a risk of fires.'],
        ['Tropical maritime (mT):', 'It comes from the South Atlantic; it is warm, very moist and unstable, and blows as the south-west monsoon.', 'f4_heavyrain.jpg', 'heavy rain'],
        ['Influence of mT:', 'It brings the rainy season (about May to September–October in Garoua), with cumulonimbus clouds and storms; the coast of Cameroon receives the most rain.'],
        ['The meeting zone:', 'The two air masses meet at the Intertropical Front (ITF), which moves north and south with the seasons.', 'wa_airmasses_big.png', 'air masses over West Africa'],
        ['Comparison:', 'The two air masses are opposite in almost everything.', 'met2_am_cmr.png', 'cT and mT compared']] },
  ],
  evaluation: [['Distinguish a continental air mass from a maritime air mass.', 'A continental air mass forms over land and is dry; a maritime air mass forms over the sea and is moist.'],
    ['Which air mass brings the rainy season to Garoua, and why?', 'The tropical maritime (mT) air mass, because it is moist and unstable.']],
  remediation: ['An air mass takes its characteristics from its ______ region.', 'The Harmattan is a ______ air mass.', 'The two air masses meet at the ______.'],
  remediationAnswers: '1. source 2. tropical continental (cT) 3. Intertropical Front (ITF)',
  homework: 'Define climate.',
  hwAnswer: 'Climate is the average state of the weather of a place over a long period, usually 30 years.',
  bilingual: [['Air mass', "La masse d'air"], ['Continental', 'Continental'], ['Maritime', 'Maritime'], ['Harmattan', "L'harmattan"], ['Monsoon', 'La mousson'], ['Source region', 'La région source']],
});

L.push({ kind: 'Further Study', no: 2, title: 'Weather Observation, Prediction, Modification and Mapping', topic: T6, subtopic: 'Weather Observation',
  notions: 'Weather element, weather station, Stevenson screen, rain gauge, barometer, anemometer, radiosonde, Doppler radar, weather satellite, numerical weather prediction, cloud seeding, synoptic chart, isobar, front.',
  focus: 'Weather observation (elements and instruments); weather prediction; weather modification techniques; weather mapping with synoptic charts.',
  competence: 'Learners are able to explain how weather is observed, forecast, modified and mapped, and read a simple synoptic chart.',
  objectives: ['Name the weather elements and the instruments used to measure them.', 'Explain how weather is predicted.', 'Describe techniques of weather modification.', 'Read the main symbols of a synoptic chart.'],
  recall: ['Pressure is measured with a barometer.', 'Anticyclones bring clear weather.', 'Fronts separate air masses.'],
  situation: 'Before planting cotton, a farmer near Garoua listens to the weather forecast on the radio, which announces the first rains for next week. At the airport, a pilot checks satellite images before taking off, and in the newspaper you see a map full of lines and symbols. You ask: "How do meteorologists observe the weather, how do they forecast it, and how do they draw it on maps?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how weather is observed, predicted and mapped.'],
    ['Which instrument measures rainfall?', 'The rain gauge.'],
    ['What is a weather map called?', 'A synoptic chart.']],
  justification: 'This lesson shows how weather information is produced and used by farmers, pilots, fishermen and the public.',
  action: 'Follow weather forecasts before farming, travelling or fishing.',
  activities: [
    { sec: '1. OBSERVATION', img: 'instruments_big.png', caption: 'Instruments of a weather station.', q: 'Where are thermometers kept in a weather station?', a: 'In a Stevenson screen.', noProj: 'visit or describe a weather station.' },
    { sec: '1. OBSERVATION', img: 'lsa_radiosonde.jpg', caption: 'Launching a radiosonde.', q: 'What does a radiosonde measure?', a: 'Temperature, humidity and pressure at different heights.', noProj: 'describe a weather balloon.' },
    { sec: '2. PREDICTION', img: 'lsa_radar.jpg', caption: 'A weather radar.', q: 'What does a Doppler radar detect?', a: 'The intensity and movement of rain and storms.', noProj: 'listen to a radio forecast.' },
    { sec: '3. MODIFICATION', img: 'met2_modif.png', caption: 'Weather modification.', q: 'What is cloud seeding?', a: 'Adding silver iodide or dry ice to clouds to make them rain.', noProj: 'list the techniques.' },
    { sec: '4. MAPPING', img: 'met2_fronts.png', caption: 'Symbols of a synoptic chart.', q: 'What do closely spaced isobars indicate?', a: 'Strong winds.', noProj: 'draw isobars around an L and an H.' },
  ],
  summary: [
    D([['Weather observation:', 'It is the measurement and recording of the elements of the weather.'],
      ['Weather forecasting:', 'It is the prediction of future weather from observations and models.'],
      ['Weather modification:', 'It is the deliberate action of people to change the weather.'],
      ['Synoptic chart:', 'It is a weather map summarising the weather over a large area at a given time.'],
      ['Isobar:', 'It is a line joining places of equal atmospheric pressure.']]),
    { title: '1. Weather Observation', intro: 'Weather is observed with the following elements and instruments:',
      items: [['Weather station:', 'Thermometers are kept in a white, ventilated Stevenson screen, with a rain gauge, a wind vane and an anemometer nearby.', 'instruments_big.png', 'instruments of a weather station'],
        ['Elements and instruments:', ['Temperature: thermometers (°C).', 'Rainfall: rain gauge (mm).', 'Pressure: barometer (hPa).', 'Wind: wind vane and anemometer.', 'Humidity: hygrometer (%).', 'Cloud cover: estimated in eighths (oktas).']],
        ['Radiosonde:', 'A balloon carries instruments that send temperature, humidity and pressure data from the upper air by radio.', 'lsa_radiosonde.jpg', 'a radiosonde'],
        ['Doppler radar:', 'It detects the intensity and movement of rain, winds and storms.', 'lsa_radar.jpg', 'a weather radar'],
        ['Weather satellites:', 'Geostationary satellites watch the same area, and polar-orbiting satellites pass over the whole Earth.']] },
    { title: '2. Weather Prediction', intro: 'Weather is predicted as follows:',
      items: [['Data collection:', 'Thousands of stations, balloons, radars and satellites send observations to weather centres.', 'met2_obs.png', 'elements and instruments'],
        ['Numerical models:', 'Computers solve equations of the atmosphere to forecast the weather days ahead.'],
        ['Meteorologists:', 'They interpret the models and inform the public, farmers, pilots and fishermen, as the National Meteorological Service of Cameroon does.']] },
    { title: '3. Weather Modification', intro: 'The main techniques of weather modification are the following:',
      items: [['Cloud seeding:', 'Silver iodide or dry ice is added to clouds to increase rain in dry areas.', 'met2_modif.png', 'weather modification'],
        ['Hail suppression:', 'Seeding keeps hailstones small to protect crops.'],
        ['Fog dispersal:', 'Heating or dry ice clears fog at airports.'],
        ['Hurricane modification:', 'It remains experimental because of the risks.']] },
    { title: '4. Weather Mapping: the Synoptic Chart', intro: 'A synoptic chart has the following components:',
      items: [['Isobars:', 'Lines of equal pressure; close isobars mean strong winds, widely spaced isobars mean calm weather.', 'met2_fronts.png', 'symbols of a synoptic chart'],
        ['Pressure systems:', 'H marks an anticyclone (clear, stable weather), L marks a depression (clouds and rain).', 'synoptic_big.png', 'a synoptic chart'],
        ['Fronts:', ['Cold front: blue line with triangles, bringing cooler air and storms.', 'Warm front: red line with semicircles, bringing steady rain.', 'Occluded front: purple line with both symbols.']],
        ['Uses:', 'Synoptic charts help to forecast weather for aviation, shipping and agriculture.']] },
  ],
  evaluation: [['Explain how a radiosonde works.', 'A balloon carries instruments into the upper air; they measure temperature, humidity and pressure and send the data by radio.'],
    ['What is a synoptic chart and how is it used?', 'A weather map summarising conditions over a large area at one time; it is used to analyse and forecast the weather.']],
  remediation: ['Rainfall is measured with a rain ______.', 'Lines of equal pressure are ______.', 'Silver iodide is used for cloud ______.'],
  remediationAnswers: '1. gauge 2. isobars 3. seeding',
  homework: 'Name the two air masses that affect the climate of Cameroon.',
  hwAnswer: 'The dry tropical continental air (Harmattan) from the Sahara and the moist tropical maritime air (south-west monsoon) from the Atlantic.',
  bilingual: [['Weather forecast', 'La prévision météorologique'], ['Rain gauge', 'Le pluviomètre'], ['Barometer', 'Le baromètre'], ['Weather map', 'La carte météorologique'], ['Isobar', "L'isobare"], ['Cloud seeding', "L'ensemencement des nuages"]],
});

module.exports = { B, L };
