// LOWER SIXTH ARTS — Meteorology, part 2: Lessons 7–12 (distribution of temperature; moisture in the atmosphere)
// Rewritten from the teacher's course support (LSA_LESSONS_METEOROLOGY_2026) in our own words; facts checked and updated.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const { B } = require('./lsamet_1');
const L = [];
const T2 = 'Energy in the Atmosphere', T3 = 'Moisture in the Atmosphere';

L.push({ no: 7, title: 'Geographical Factors Affecting Temperature', topic: T2, subtopic: 'Global Distribution of Heat (Temperature)',
  notions: 'Continentality, maritime influence, specific heat, relief, altitude, aspect, ocean currents, prevailing winds, cloud cover, urban heat island.',
  focus: 'Geographical factors that modify temperatures at the same latitude: land and sea, relief (altitude, aspect), ocean currents, winds, cloud cover, urbanisation.',
  competence: 'Learners are able to explain why places at the same latitude have different temperatures, with examples around Garoua.',
  objectives: ['Explain the different heating of land and water (continentality).', 'Explain the effects of altitude and aspect.', 'Explain the effects of ocean currents and winds.', 'Explain the double role of clouds.', 'Explain the urban heat island.'],
  recall: ['Temperature decreases with latitude.', 'The Harmattan brings hot, dry air.', 'Clouds reflect sunlight.'],
  situation: 'You spend Saturday afternoon in your grandmother\'s village, 30 km from Garoua. Coming back in the evening, as your bus enters the city around the Central Market, the air suddenly feels much hotter and stuffier than in the village. You ask: "We are at the same latitude, so why does the town feel like an oven compared to the village?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the geographical factors that change temperature at the same latitude.'],
    ['Why is the town hotter than the village?', 'Tar and concrete store heat, and there are fewer trees: an urban heat island.'],
    ['Name another factor that changes temperature locally.', 'Altitude, nearness to water (Lagdo), winds or cloud cover.']],
  justification: 'This lesson explains local differences of temperature and the importance of green spaces in towns.',
  action: 'Plant and protect trees in town to reduce the urban heat island.',
  activities: [
    { sec: '1. LAND AND SEA', img: 'continentality_big.png', caption: 'Coastal and inland temperatures.', q: 'Why do places far inland have more extreme temperatures?', a: 'Land heats and cools quickly, while the sea moderates coastal temperatures.', noProj: 'compare Douala and Garoua.' },
    { sec: '2. RELIEF', img: 'f2t_kilimanjaro.jpg', caption: 'Snow on Kilimanjaro near the Equator.', q: 'Why is there snow on Kilimanjaro near the Equator?', a: 'Temperature falls with altitude (about 6.5 °C per 1,000 m).', noProj: 'calculate the fall of temperature for 2,000 m.' },
    { sec: '2. RELIEF', img: 'aspect_big.png', caption: 'The aspect of slopes.', q: 'What is aspect?', a: 'The direction a slope faces.', noProj: 'find a slope facing the sun.' },
    { sec: '3. CURRENTS AND WINDS', img: 'ocean_currents_big.png', caption: 'Warm and cold currents.', q: 'How does the cold Benguela Current affect Namibia?', a: 'It cools the coast and makes it dry.', noProj: 'locate Namibia.' },
    { sec: '4. TOWNS', img: 'heat_island_big.png', caption: 'The urban heat island.', q: 'Give two causes of the urban heat island.', a: 'Tar and concrete, heat from vehicles and machines, few trees, tall buildings (any two).', noProj: 'feel a tar road and grass at noon.' },
  ],
  summary: [
    D([['Continentality:', 'It is the effect of distance from the sea, which makes inland temperatures more extreme.'],
      ['Aspect:', 'It is the direction a slope faces.'],
      ['Normal lapse rate:', 'It is the average fall of temperature with height, about 6.5 °C per 1,000 m.'],
      ['Urban heat island:', 'It is a town that is warmer than the surrounding countryside.']]),
    { title: '1. Nature of the Surface: Land and Water', intro: 'Land and water influence temperature as follows:',
      items: [['Land:', 'It heats and cools quickly because of its low specific heat.', 'continentality_big.png', 'coastal and inland temperatures'],
        ['Water:', 'It heats and cools slowly, so it moderates the temperature of nearby land.'],
        ['Maritime influence:', 'Coastal places like Douala and Kribi have small temperature ranges.'],
        ['Continentality:', 'Inland places like Garoua and Maroua have larger ranges: very hot days in March–April and cool nights in December–January.']] },
    { title: '2. Relief', intro: 'Relief influences temperature as follows:',
      items: [['Altitude:', 'Temperature falls by about 6.5 °C per 1,000 m, so the Mandara Mountains and Ngaoundéré are cooler than Garoua.', 'f2t_kilimanjaro.jpg', 'snow on Kilimanjaro'],
        ['Aspect:', 'In the northern hemisphere, south-facing slopes receive more sun and are warmer and drier than north-facing slopes.', 'aspect_big.png', 'the aspect of slopes'],
        ['Valleys:', 'Cold air can drain into valleys at night, making them cooler than the slopes.']] },
    { title: '3. Ocean Currents, Winds and Clouds', intro: 'Ocean currents, winds and clouds influence temperature as follows:',
      items: [['Warm currents:', 'They warm the coasts they touch, like the Guinea Current along the coast of Cameroon.', 'ocean_currents_big.png', 'ocean currents'],
        ['Cold currents:', 'They cool and dry the coasts they touch, like the Benguela Current off Namibia.'],
        ['Prevailing winds:', 'Winds from hot regions raise temperatures, like the Harmattan; winds from the sea or cold regions lower them.'],
        ['Cloud cover by day:', 'Clouds reflect sunlight, so cloudy days are cooler.'],
        ['Cloud cover by night:', 'Clouds trap terrestrial radiation like a blanket, so cloudy nights are warmer than clear nights.']] },
    { title: '4. Urbanisation: the Urban Heat Island', intro: 'Towns are warmer than the countryside for the following reasons:',
      items: [['Surfaces:', 'Concrete, tar and roofs absorb and store more heat than soil and plants.', 'heat_island_big.png', 'the urban heat island'],
        ['Human heat:', 'Vehicles, motorbikes, air conditioners and factories give off heat.'],
        ['Lack of vegetation:', 'Few trees mean less shade and less cooling by transpiration.'],
        ['Building shape:', 'Tall buildings trap heat in the narrow streets between them.']] },
  ],
  evaluation: [['Distinguish a maritime climate from a continental climate.', 'A maritime climate near the sea has small temperature ranges; a continental climate far inland has large ranges.'],
    ['Explain the double role of clouds on temperature.', 'By day they reflect sunlight and cool the ground; at night they trap heat and keep it warm.']],
  remediation: ['Temperature falls by about ______ °C per 1,000 m.', 'The direction a slope faces is its ______.', 'A town warmer than the countryside is an urban heat ______.'],
  remediationAnswers: '1. 6.5 2. aspect 3. island',
  homework: 'Define the environmental lapse rate.',
  hwAnswer: 'The environmental lapse rate is the rate at which air temperature falls with height, on average 6.5 °C per 1,000 m.',
  bilingual: [['Relief', 'Le relief'], ['Altitude', "L'altitude"], ['Wind', 'Le vent'], ['Cloud', 'Le nuage'], ['Urban heat island', "L'îlot de chaleur urbain"], ['Continentality', 'La continentalité']],
});

L.push({ no: 8, title: 'Vertical Distribution of Temperature', topic: T2, subtopic: 'Vertical Distribution of Heat in the Atmosphere',
  notions: 'Environmental lapse rate, terrestrial radiation, air density, pressure, expansion, adiabatic cooling.',
  focus: 'The decrease of temperature with height in the troposphere; the environmental lapse rate; reasons for the lapsing of temperature.',
  competence: 'Learners are able to explain why temperature falls with altitude and calculate temperatures at different heights.',
  objectives: ['Describe the vertical variation of temperature in the troposphere.', 'Define and use the environmental lapse rate.', 'Explain why the atmosphere is heated from below.', 'Explain the roles of air density and pressure.'],
  recall: ['The troposphere is the lowest layer.', 'The ground heats the air above it.', 'Mountains are cooler than plains.'],
  situation: 'During the holidays, your family drives from Garoua to Rhumsiki in the Mandara Mountains. As the car climbs past Guider, the air through the window becomes cooler and cooler, and at Rhumsiki you feel a little cold. Yet you are higher, so "closer to the Sun". You ask: "Why does it get colder as we go up, and by how much?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand why temperature decreases with height.'],
    ['Is the air heated directly by the Sun?', 'No, mainly from below, by the ground.'],
    ['What is the rate of cooling with height called?', 'The environmental lapse rate.']],
  justification: 'This lesson explains why highlands are cool and helps us to calculate temperatures at different altitudes.',
  action: 'Use the lapse rate to estimate temperatures before travelling to highlands.',
  activities: [
    { sec: '1. LAPSE RATE', img: 'lapse_rate_big.png', caption: 'Temperature and height.', q: 'If Garoua (about 200 m) is at 35 °C, what is the temperature at 1,200 m?', a: '35 − 6.5 = 28.5 °C.', noProj: 'do the calculation on the board.' },
    { sec: '1. LAPSE RATE', img: 'lsa_mtcameroon.jpg', caption: 'Mount Cameroon.', q: 'Why is the summit of Mount Cameroon cold while Buea is warm?', a: 'The summit (4,095 m) is about 25 °C cooler because of altitude.', noProj: 'compare Buea and the summit.' },
    { sec: '2. REASONS', img: 'heated_below_big.png', caption: 'The atmosphere is heated from below.', q: 'Where is the air warmest in the troposphere?', a: 'Near the ground, the source of heat.', noProj: 'feel the air above hot ground.' },
    { sec: '2. REASONS', img: 'met2_elr.png', caption: 'Why temperature falls with height.', q: 'Why does thin air at altitude hold little heat?', a: 'It has fewer gas molecules, dust and water vapour to absorb heat.', noProj: 'list the three reasons.' },
    { sec: '2. REASONS', img: 'parcel.gif', caption: 'Animation: rising air expands and cools.', q: 'What happens to rising air as pressure falls?', a: 'It expands and cools.', noProj: 'feel the cold gas from a spray.' },
  ],
  summary: [
    D([['Environmental lapse rate (ELR):', 'It is the rate at which air temperature falls with height, on average 6.5 °C per 1,000 m.'],
      ['Terrestrial radiation:', 'It is the long-wave heat given off by the surface of the Earth.'],
      ['Air density:', 'It is the amount of air (mass) in a given volume.']]),
    { title: '1. The Vertical Variation of Temperature', intro: 'Temperature varies with height as follows:',
      items: [['General rule:', 'In the troposphere, temperature falls as altitude increases.', 'lapse_rate_big.png', 'temperature and height'],
        ['Average rate:', 'The fall is about 6.5 °C for every 1,000 m.'],
        ['Worked example:', 'At 35 °C in Garoua (about 200 m), a place at 1,200 m would be at about 35 − 6.5 = 28.5 °C.'],
        ['Mountains in the tropics:', 'The summit of Mount Cameroon (4,095 m) is about 25 °C cooler than the coast and can have frost.', 'lsa_mtcameroon.jpg', 'Mount Cameroon']] },
    { title: '2. Reasons for the Fall of Temperature with Height', intro: 'Temperature falls with height for the following reasons:',
      items: [['Heating from below:', 'Sunlight passes through the air and heats the ground, which warms the air above it, so the air is warmest near the ground.', 'heated_below_big.png', 'heating from below'],
        ['Denser air below:', 'Gravity keeps most gases, dust and water vapour near the ground, and they absorb and keep heat.', 'met2_elr.png', 'why temperature falls with height'],
        ['Thin air above:', 'At high altitudes, there are fewer particles to absorb heat.'],
        ['Pressure and expansion:', 'Rising air meets lower pressure, expands and cools.', 'parcel_last.png', 'rising air cools']] },
  ],
  evaluation: [['Why is it colder at the top of a mountain than on the plain although it is "closer to the Sun"?', 'The air is heated from the ground; higher air is thinner, holds less heat and cools by expansion.'],
    ['If it is 30 °C at sea level, what is the temperature at 2,000 m?', '30 − (2 × 6.5) = 17 °C.']],
  remediation: ['Temperature falls with height in the ______.', 'The average lapse rate is ______ °C per 1,000 m.', 'Rising air expands and ______.'],
  remediationAnswers: '1. troposphere 2. 6.5 3. cools',
  homework: 'Define a temperature inversion.',
  hwAnswer: 'A temperature inversion is a situation in which temperature increases with height instead of decreasing.',
  bilingual: [['Altitude', "L'altitude"], ['Lapse rate', 'Le gradient thermique'], ['Atmosphere', "L'atmosphère"], ['Air density', "La densité de l'air"], ['Terrestrial radiation', 'Le rayonnement terrestre'], ['Pressure', 'La pression']],
});

L.push({ no: 9, title: 'Temperature Inversion', topic: T2, subtopic: 'Vertical Distribution of Heat in the Atmosphere',
  notions: 'Temperature inversion, surface (radiation) inversion, upper-air inversion, fog, smog, frost, stability.',
  focus: 'Meaning and types of temperature inversion; causes of surface inversion; effects on weather and human activities (fog, pollution, frost).',
  competence: 'Learners are able to explain the formation of temperature inversions and their effects, such as morning haze in the Benue valley.',
  objectives: ['Define a temperature inversion.', 'Distinguish surface and upper-air inversions.', 'Explain the conditions for a surface inversion.', 'Explain the effects of inversions.'],
  recall: ['Temperature normally falls with height.', 'The ground loses heat at night.', 'The Harmattan air is very dry.'],
  situation: 'On an early January morning in Garoua, you walk to school. The air near the ground is surprisingly cold on your legs, and a low haze of dust and smoke from cooking fires hangs in the air without rising. You have learnt that air gets colder with height. You ask: "Why is the air colder at the ground this morning, and why does the smoke not rise?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not understand the temperature inversion.'],
    ['What is this condition called?', 'A temperature inversion: cold air below warmer air.'],
    ['Why does the smoke not rise?', 'The warm layer above acts like a lid that stops rising air.']],
  justification: 'This lesson explains morning fog and haze, air pollution and frost, which affect health, transport and farming.',
  action: 'Avoid burning waste on calm, cold mornings, and drive carefully in fog and haze.',
  activities: [
    { sec: '1. MEANING', img: 'inversion_graph_big.png', caption: 'Temperature in an inversion.', q: 'How does temperature change with height in an inversion?', a: 'It increases instead of decreasing.', noProj: 'draw the normal and the inverted line.' },
    { sec: '1. MEANING', img: 'inversion.gif', caption: 'Animation: a night inversion forms.', q: 'Where is the coldest air in a surface inversion?', a: 'Just above the ground.', noProj: 'describe a cold early morning.' },
    { sec: '2. CAUSES', img: 'met2_inv_causes.png', caption: 'Conditions for an inversion.', q: 'Why do clear skies help an inversion to form?', a: 'Heat escapes from the ground to space, so the ground and the air above it cool quickly.', noProj: 'compare cloudy and clear nights.' },
    { sec: '3. EFFECTS', img: 'lsa_cloudsea.jpg', caption: 'Fog in a valley.', q: 'Why does fog form in valleys during an inversion?', a: 'The cold air near the ground is cooled to its dew point.', noProj: 'describe fog over the Benue.' },
    { sec: '3. EFFECTS', img: 'lsa_smog.jpg', caption: 'Smog over a city.', q: 'Give one health effect of pollution trapped by an inversion.', a: 'Coughing and breathing problems.', noProj: 'discuss smoke from cooking fires.' },
  ],
  summary: [
    D([['Temperature inversion:', 'It is a situation in which temperature increases with height, so warm air lies above cold air.'],
      ['Fog:', 'It is a cloud at ground level that reduces visibility to less than 1 km.'],
      ['Smog:', 'It is a mixture of smoke (or pollutants) and fog.']]),
    { title: '1. Meaning and Types of Temperature Inversion', intro: 'Temperature inversions are presented as follows:',
      items: [['Meaning:', 'The normal fall of temperature with height is reversed, and the warm layer acts like a lid.', 'inversion_graph_big.png', 'temperature in an inversion'],
        ['Surface (radiation) inversion:', 'It forms near the ground at night and in the early morning; it is the most common type.', 'inversion_last.png', 'a night inversion'],
        ['Upper-air inversion:', 'It forms higher up, when air sinks slowly and warms in high-pressure areas.']] },
    { title: '2. Causes of a Surface Inversion', intro: 'A surface inversion forms best under the following conditions:',
      items: [['Long nights:', 'The ground has more time to lose heat by terrestrial radiation.', 'met2_inv_causes.png', 'conditions for an inversion'],
        ['Clear skies:', 'Without clouds, heat escapes quickly to space.'],
        ['Calm air:', 'Without wind, the cold, heavy air stays near the ground.'],
        ['Dry air:', 'Dry air, such as Harmattan air, cools quickly.'],
        ['Valleys:', 'Cold air drains down the slopes and collects in valleys and basins, like the Benue valley.']] },
    { title: '3. Effects on Weather and Human Activities', intro: 'Temperature inversions have the following effects:',
      items: [['Fog:', 'Air near the cold ground is cooled to its dew point and forms fog, common in valleys and near rivers.', 'lsa_cloudsea.jpg', 'fog in a valley'],
        ['Trapped pollution:', 'Smoke, exhaust fumes and dust are trapped near the ground, causing smog and breathing problems.', 'lsa_smog.jpg', 'smog'],
        ['Reduced visibility:', 'Fog and smog make roads and flights dangerous.'],
        ['Frost:', 'In cold regions or high mountains, trapped cold air can fall below 0 °C and damage crops.', 'lsa_frost.jpg', 'frost']] },
  ],
  evaluation: [['How do a clear sky and calm winds help an inversion to form at night?', 'Clear skies let the ground lose heat quickly; calm air lets the cold air stay near the ground without mixing.'],
    ['Give two effects of temperature inversion on human activities.', 'Fog and reduced visibility, trapped pollution and health problems, frost damaging crops (any two).']],
  remediation: ['In an inversion, temperature ______ with height.', 'A mixture of smoke and fog is ______.', 'Inversions are strongest on ______ and calm nights.'],
  remediationAnswers: '1. increases 2. smog 3. clear',
  homework: 'Define relative humidity.',
  hwAnswer: 'Relative humidity is the amount of water vapour in the air compared with the maximum it can hold at that temperature, in %.',
  bilingual: [['Inversion', "L'inversion"], ['Fog', 'Le brouillard'], ['Pollutant', 'Le polluant'], ['Visibility', 'La visibilité'], ['Frost', 'Le gel'], ['Smog', 'Le smog']],
});

L.push({ no: 10, title: 'Nature of Moisture', topic: T3, subtopic: 'Atmospheric Humidity',
  notions: 'Atmospheric moisture, humidity, evaporation, transpiration, states of water, absolute humidity, relative humidity, saturation, dew point.',
  focus: 'Meaning and sources of atmospheric moisture; the three states of water; absolute and relative humidity; factors of humidity; importance of moisture.',
  competence: 'Learners are able to explain the humidity of the air in the rainy and dry seasons of Garoua and calculate relative humidity.',
  objectives: ['Define atmospheric moisture and humidity.', 'Identify the sources of moisture.', 'Describe the three states of water in the atmosphere.', 'Distinguish absolute and relative humidity.', 'Explain the factors and importance of humidity.'],
  recall: ['Water vapour is a variable gas.', 'Latent heat is stored in water vapour.', 'The Harmattan is very dry.'],
  situation: 'In August, during the rainy season in Garoua, you play football with friends. Although the sun is not very hot, you sweat a lot and your clothes feel damp and sticky. In January, during the Harmattan, the air was so dry that your lips cracked and the same game did not make you feel so uncomfortable. You ask: "What invisible thing in the air makes it so sticky in August and so dry in January?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the nature of atmospheric moisture.'],
    ['What is the invisible thing in the air?', 'Water vapour (moisture).'],
    ['Where does the moisture around Garoua come from?', 'Evaporation from the Benue and Lake Lagdo, the soil, and transpiration from plants.']],
  justification: 'This lesson explains humidity, which controls clouds, rain and our comfort.',
  action: 'Drink enough water in dry, hot weather and protect water bodies and vegetation that feed moisture to the air.',
  activities: [
    { sec: '1. SOURCES', img: 'water_cycle.gif', caption: 'Animation: the water cycle.', q: 'Name two sources of moisture in the air.', a: 'Evaporation from seas, lakes and rivers, and transpiration from plants.', noProj: 'draw the water cycle.' },
    { sec: '1. STATES', img: 'lsa_ice.jpg', caption: 'Ice.', q: 'In which three states can water exist in the atmosphere?', a: 'Gas (vapour), liquid (droplets) and solid (ice crystals).', noProj: 'show ice, water and steam.' },
    { sec: '2. HUMIDITY', img: 'humidity_big.png', caption: 'Absolute and relative humidity.', q: 'What does a relative humidity of 100 % mean?', a: 'The air is saturated.', noProj: 'fill a cup to the brim.' },
    { sec: '2. HUMIDITY', img: 'met2_humidity.png', caption: 'Relative humidity changes with temperature.', q: 'Why does relative humidity rise at night?', a: 'The air cools and can hold less vapour.', noProj: 'calculate RH on the board.' },
    { sec: '3. MEASUREMENT', img: 'lsa_hygro.jpg', caption: 'A hygrometer.', q: 'Which instrument measures humidity?', a: 'The hygrometer (or wet- and dry-bulb thermometers).', noProj: 'wet a cloth and wave it.' },
  ],
  summary: [
    D([['Atmospheric moisture:', 'It is the water present in the atmosphere as vapour, droplets or ice.'],
      ['Humidity:', 'It is the amount of water vapour in the air.'],
      ['Absolute humidity:', 'It is the mass of water vapour in a volume of air, in grams per cubic metre (g/m³).'],
      ['Relative humidity:', 'It is the actual vapour in the air compared with the maximum it can hold at that temperature, in %.'],
      ['Dew point:', 'It is the temperature at which air becomes saturated and condensation begins.']]),
    { title: '1. Atmospheric Moisture', intro: 'Atmospheric moisture is presented as follows:',
      items: [['Sources:', ['Evaporation from oceans, lakes (Lagdo) and rivers (Benue).', 'Evaporation from moist soils.', 'Transpiration from plants.']],
        ['Illustration:', 'These sources feed the water cycle.', 'water_cycle_last.png', 'the water cycle'],
        ['Gaseous state:', 'Invisible water vapour is the most common form.'],
        ['Liquid state:', 'Droplets form clouds, fog, dew and rain.'],
        ['Solid state:', 'Ice crystals form high clouds, snow, frost and hail.', 'lsa_ice.jpg', 'ice']] },
    { title: '2. Types and Measurement of Humidity', intro: 'Humidity is measured in the following ways:',
      items: [['Absolute humidity:', 'For example, 15 g/m³ means 15 grams of vapour in each cubic metre of air.', 'humidity_big.png', 'absolute and relative humidity'],
        ['Relative humidity:', 'RH = actual vapour ÷ maximum vapour at that temperature × 100; at 100 % the air is saturated.'],
        ['Worked example:', 'Air at 30 °C can hold about 30 g/m³; if it holds 15 g/m³, RH = 15 ÷ 30 × 100 = 50 %.', 'met2_humidity.png', 'RH and temperature'],
        ['Instrument:', 'Humidity is measured with a hygrometer or with wet- and dry-bulb thermometers.', 'lsa_hygro.jpg', 'a hygrometer']] },
    { title: '3. Factors and Importance of Humidity', intro: 'Humidity depends on the following factors and has the following importance:',
      items: [['Temperature:', 'Warm air can hold more vapour; when air cools, RH rises, which is why dew forms at dawn.'],
        ['Nearness to water:', 'Coastal Douala is more humid than inland Maroua.'],
        ['Seasons:', 'In Garoua, RH is very low with the Harmattan (under 20 %) and high in the rainy season (over 70 %).'],
        ['Importance:', ['It is the source of clouds, fog, dew and rain.', 'High humidity in hot weather makes us feel hotter because sweat evaporates slowly.', 'It influences plants and animals.']]] },
  ],
  evaluation: [['Distinguish absolute humidity from relative humidity.', 'Absolute humidity is the mass of vapour in a volume of air; relative humidity compares this amount with the maximum possible at that temperature, in %.'],
    ['Why do we feel hotter in humid weather?', 'Sweat evaporates slowly, so the body cools less.']],
  remediation: ['Humidity is measured with a ______.', 'Air at 100 % relative humidity is ______.', 'The temperature at which condensation begins is the ______ point.'],
  remediationAnswers: '1. hygrometer 2. saturated 3. dew',
  homework: 'Name three types of clouds.',
  hwAnswer: 'Cumulus, cumulonimbus, stratus and cirrus (any three).',
  bilingual: [['Moisture', "L'humidité"], ['Water vapour', "La vapeur d'eau"], ['Evaporation', "L'évaporation"], ['Relative humidity', "L'humidité relative"], ['Condensation', 'La condensation'], ['Dew point', 'Le point de rosée']],
});

L.push({ no: 11, title: 'Forms of Condensation and Precipitation', topic: T3, subtopic: 'Precipitation',
  notions: 'Condensation, dew point, condensation nuclei, cumulus, cumulonimbus, stratus, cirrus, fog, mist, dew, drizzle, rain, hail, snow, frost, convectional, orographic and frontal rainfall.',
  focus: 'Forms of condensation (clouds and their classification, fog and mist); forms of precipitation (liquid and solid); types of rainfall.',
  competence: 'Learners are able to identify clouds and forms of precipitation and explain the types of rainfall, especially the thunderstorms of Garoua.',
  objectives: ['Define condensation and precipitation.', 'Classify the main types of clouds and their weather.', 'Distinguish fog and mist.', 'Describe liquid and solid precipitation.', 'Explain convectional, orographic and frontal rainfall.'],
  recall: ['Relative humidity rises when air cools.', 'Aerosols act as condensation nuclei.', 'Rising air expands and cools.'],
  situation: 'On a hot July afternoon in Garoua, the sky is blue with a few white, puffy clouds. During the afternoon, you watch them grow upwards like mountains, and their bases become dark grey. Thunder rumbles, and within an hour a heavy rain floods the streets before stopping as suddenly as it began. You ask: "How does invisible vapour become clouds, and how can a sunny day turn into such a storm?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know how clouds and rain form.'],
    ['What turns vapour into cloud droplets?', 'Condensation.'],
    ['What type of rain is this storm?', 'Convectional rainfall from a cumulonimbus cloud.']],
  justification: 'This lesson helps us to read the sky and to understand the rains on which farming in the North depends.',
  action: 'Observe the clouds to anticipate storms and shelter from lightning.',
  activities: [
    { sec: '1. CLOUDS', img: 'cloud_types_big.png', caption: 'The main types of clouds.', q: 'Which cloud brings thunderstorms?', a: 'The cumulonimbus.', noProj: 'draw the four cloud types.' },
    { sec: '1. CLOUDS', img: 'lsa_cumulus.jpg', caption: 'Cumulus clouds.', q: 'What weather do small cumulus clouds usually indicate?', a: 'Fair weather.', noProj: 'look at today\'s sky.' },
    { sec: '2. PRECIPITATION', img: 'lsa_dew.jpg', caption: 'Dew on grass.', q: 'Is dew a form of precipitation?', a: 'No, it is condensation on cool surfaces.', noProj: 'look at grass at dawn.' },
    { sec: '2. PRECIPITATION', img: 'lsa_hail.jpg', caption: 'Hailstones.', q: 'In which cloud do hailstones form?', a: 'In cumulonimbus clouds during violent storms.', noProj: 'describe a hailstorm.' },
    { sec: '3. TYPES OF RAINFALL', img: 'rainfall_types_big.png', caption: 'Three types of rainfall.', q: 'What is the dry side of a mountain called?', a: 'The rain shadow (leeward side).', noProj: 'draw orographic rainfall.' },
  ],
  summary: [
    D([['Condensation:', 'It is the change of water vapour into liquid water when air cools to its dew point.'],
      ['Condensation nuclei:', 'They are tiny particles of dust, salt or smoke on which droplets form.'],
      ['Precipitation:', 'It is any form of water, liquid or solid, that falls from clouds to the ground.'],
      ['Rain shadow:', 'It is the dry leeward side of a mountain.']]),
    { title: '1. Forms of Condensation', intro: 'Condensation takes the following forms:',
      items: [['Clouds:', 'Rising moist air expands and cools, and vapour condenses on nuclei into tiny droplets or ice crystals.', 'cloud_types_big.png', 'the main types of clouds'],
        ['Cumulus:', 'Puffy clouds with flat bases, usually with fair weather.', 'lsa_cumulus.jpg', 'cumulus clouds'],
        ['Cumulonimbus:', 'Huge, tall, dark clouds with heavy rain, thunder, lightning and sometimes hail, very common in Garoua in the rainy season.', 'f4_cumulonimbus.jpg', 'a cumulonimbus'],
        ['Stratus:', 'Grey layers covering the sky, with drizzle or light, steady rain.'],
        ['Cirrus:', 'Thin, feathery clouds of ice crystals very high in the sky, a sign of fair weather.'],
        ['Fog and mist:', 'Clouds at ground level; fog reduces visibility below 1 km, mist less.']] },
    { title: '2. Forms of Precipitation', intro: 'Precipitation takes the following forms:',
      items: [['Dew:', 'Droplets on cool surfaces at night; it is condensation, not precipitation.', 'lsa_dew.jpg', 'dew'],
        ['Drizzle:', 'Very small drops, less than 0.5 mm.'],
        ['Rain:', 'Drops larger than 0.5 mm, formed when cloud droplets grow heavy enough to fall.'],
        ['Hail:', 'Balls of ice formed in cumulonimbus clouds during violent storms.', 'lsa_hail.jpg', 'hailstones'],
        ['Snow and frost:', 'Snow is ice crystals falling in cold climates; frost is ice crystals formed on cold surfaces.'],
        ['Summary:', 'The forms of condensation and precipitation can be compared in a table.', 'met2_precip.png', 'forms of precipitation']] },
    { title: '3. Types of Rainfall', intro: 'The main types of rainfall are the following:',
      items: [['Convectional rainfall:', 'Intense heating makes moist air rise quickly and form cumulonimbus clouds, giving short, heavy afternoon storms, as in Garoua and equatorial regions.', 'rainfall_types_big.png', 'three types of rainfall'],
        ['Orographic (relief) rainfall:', 'Moist winds rise over mountains and give rain on the windward side, while the leeward side is a rain shadow, as around Mount Cameroon.'],
        ['Frontal (cyclonic) rainfall:', 'Warm air rises slowly over cold air where two air masses meet, giving long, steady rain.']] },
  ],
  evaluation: [['Explain how a hot sunny day in Garoua can lead to a heavy afternoon storm.', 'The ground heats the air, which rises quickly, cools and condenses into a cumulonimbus that gives convectional rain.'],
    ['Distinguish dew from drizzle.', 'Dew is condensation on cool surfaces; drizzle is fine rain falling from clouds.']],
  remediation: ['Thunderstorm clouds are ______.', 'The dry side of a mountain is the rain ______.', 'Rain from warm air rising over cold air is ______ rain.'],
  remediationAnswers: '1. cumulonimbus 2. shadow 3. frontal (cyclonic)',
  homework: 'Name the world\'s wettest belt of latitude.',
  hwAnswer: 'The equatorial belt, around the Equator.',
  bilingual: [['Cloud', 'Le nuage'], ['Rain', 'La pluie'], ['Condensation', 'La condensation'], ['Precipitation', 'Les précipitations'], ['Thunderstorm', "L'orage"], ['Hail', 'La grêle']],
});

L.push({ no: 12, title: 'Global Distribution of Precipitation', topic: T3, subtopic: 'Precipitation',
  notions: 'Pressure belts, ITCZ, subtropical high, temperate low, polar high, maritime and continental air masses, relief rainfall, rain shadow, continentality.',
  focus: 'The global pattern of precipitation and its primary factors (pressure belts, air masses); secondary factors (relief, distance from the sea, vegetation, currents, lakes, towns).',
  competence: 'Learners are able to explain the world pattern of rainfall and the contrast between Douala and Garoua.',
  objectives: ['Describe the global pattern of precipitation.', 'Explain the role of pressure belts.', 'Explain the role of air masses.', 'Explain the secondary factors of rainfall.'],
  recall: ['Rising air cools and forms clouds.', 'Relief forces air to rise.', 'The Harmattan is continental air.'],
  situation: 'In late March, the heat in Garoua is intense and there is no rain yet. Your uncle in Douala calls and complains that heavy rains have already started there and flooded his quarter. He says: "You people in Garoua are lucky with your long dry season!" You ask: "Why does Douala receive so much rain so early, while Garoua has less rain and a shorter rainy season?"',
  sitQA: [['What is the problem in the situation?', 'The learner does not know the factors of the distribution of rainfall.'],
    ['Why is Douala so wet?', 'It is near the equatorial low-pressure belt, on the coast, and at the foot of Mount Cameroon.'],
    ['Why is Garoua drier?', 'It is far inland and under the dry Harmattan for a long part of the year.']],
  justification: 'This lesson explains the world pattern of rainfall and the differences in water availability within Cameroon.',
  action: 'Save water during the long dry season and plan farming with the rainfall calendar.',
  activities: [
    { sec: '1. GLOBAL PATTERN', img: 'rain_latitude_big.png', caption: 'Rainfall by latitude.', q: 'Where is rainfall heaviest on the globe?', a: 'Around the Equator.', noProj: 'draw rainfall bars by latitude.' },
    { sec: '1. PRESSURE BELTS', img: 'pressure_belts_big.png', caption: 'The pressure belts.', q: 'Why are the great deserts near 30° N and S?', a: 'Air sinks in the subtropical high-pressure belts, so clouds do not form.', noProj: 'draw the pressure belts.' },
    { sec: '1. PRESSURE BELTS', img: 'f2t_erg.jpg', caption: 'The Sahara.', q: 'Which pressure belt lies over the Sahara?', a: 'The subtropical high-pressure belt.', noProj: 'locate the Sahara.' },
    { sec: '2. SECONDARY FACTORS', img: 'rain_compare_big.png', caption: 'Rainfall of Douala and Garoua.', q: 'Give one reason why Douala is wetter than Garoua.', a: 'It is on the coast, close to the moist monsoon air, and at the foot of Mount Cameroon.', noProj: 'compare the two towns.' },
    { sec: '2. SECONDARY FACTORS', img: 'met2_rain_factors.png', caption: 'Factors of rainfall.', q: 'How do forests increase rainfall?', a: 'They release water vapour by transpiration.', noProj: 'list the factors.' },
  ],
  summary: [
    D([['Pressure belt:', 'It is a zone of high or low pressure that circles the globe along a latitude.'],
      ['Intertropical Convergence Zone (ITCZ):', 'It is the equatorial low-pressure zone where the trade winds meet and air rises.'],
      ['Air mass:', 'It is a large body of air with similar temperature and humidity.']]),
    { title: '1. The Global Pattern and Primary Factors', sub: 'A) Pressure Belts', intro: 'The pressure belts control rainfall as follows:',
      items: [['General pattern:', 'Rainfall is heaviest near the Equator and decreases, unevenly, towards the poles.', 'rain_latitude_big.png', 'rainfall by latitude'],
        ['Equatorial low (ITCZ):', 'Intense heating makes air rise, giving heavy convectional rain all year and rainforests.', 'pressure_belts_big.png', 'the pressure belts'],
        ['Subtropical highs (about 30° N and S):', 'Sinking air warms and forms no clouds, so the great deserts like the Sahara are found there.', 'f2t_erg.jpg', 'the Sahara'],
        ['Temperate lows (about 60° N and S):', 'Warm and cold air masses meet and give moderate frontal rain.'],
        ['Polar highs:', 'Cold sinking air gives very little precipitation, making "ice deserts".']] },
    { title: '1. The Global Pattern and Primary Factors', sub: 'B) Air Masses', intro: 'Air masses influence rainfall as follows:',
      items: [['Maritime air masses:', 'They form over oceans, are moist and bring rain, like the south-west monsoon over Cameroon.'],
        ['Continental air masses:', 'They form over land, are dry and bring dry weather, like the Harmattan from the Sahara.', 'f2t_harmattan.jpg', 'the Harmattan']] },
    { title: '2. Secondary (Local) Factors', intro: 'The local factors of rainfall are the following:',
      items: [['Relief:', 'Moist air rising over mountains gives heavy rain on the windward side and a rain shadow on the leeward side: Debundscha, at the foot of Mount Cameroon, receives about 10,000 mm a year.', 'met2_rain_factors.png', 'factors of rainfall'],
        ['Distance from the sea:', 'Coastal Douala (about 4,000 mm) and Kribi are wet, while inland Garoua (about 1,000 mm) is drier: continentality.', 'rain_compare_big.png', 'Douala and Garoua'],
        ['Vegetation:', 'Forests release vapour by transpiration and encourage convectional rain.'],
        ['Other factors:', ['Warm currents increase rain, cold currents reduce it.', 'Large lakes such as Lake Chad add moisture.', 'Big cities can increase local storms.']]] },
  ],
  evaluation: [['Why does the Equator receive heavy rain all year while 30° N is very dry?', 'At the Equator, low pressure makes air rise and form rain clouds; at 30° N, high pressure makes air sink and warm, so no clouds form.'],
    ['Give two reasons why Douala is wetter than Garoua.', 'It is on the coast near moist monsoon air; Mount Cameroon forces the air to rise (relief rain).']],
  remediation: ['The equatorial low-pressure zone is the ______.', 'Deserts lie under the subtropical ______ pressure belts.', 'The dry side of a mountain is the rain ______.'],
  remediationAnswers: '1. ITCZ 2. high 3. shadow',
  homework: 'Define atmospheric pressure.',
  hwAnswer: 'Atmospheric pressure is the weight of the air pressing on a unit area of the surface of the Earth.',
  bilingual: [['Precipitation', 'Les précipitations'], ['Pressure belt', 'La ceinture de pression'], ['Relief', 'Le relief'], ['Windward side', 'Le versant au vent'], ['Rain shadow', "L'ombre pluviométrique"], ['Air mass', "La masse d'air"]],
});

module.exports = { B, L };
