// UPPER SIXTH ARTS — Practical Geography: statistical techniques (Quantitative Techniques 2, 3 in three parts, and 4)
// Rewritten from the teacher's course support (STATISTICAL TECHNIQUES IN GEOGRAPHICAL ANALYSIS, 2026) in our own words; calculations checked.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const OLD = require('../v2_usa_prac2').B;
const B = Object.assign({}, OLD, {
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Module 8 (Practical Geography).', 'Teacher\'s course notes: Mr KAMDEM E., Statistical Techniques in Geographical Analysis (USA), GBHS Garoua, 2026.'] });
const L = [];
const T = 'Quantitative Techniques in Geography', K = 'Quantitative Techniques';

L.push({ kind: K, no: 2, title: 'Data Collection: Sources and Techniques', topic: T, subtopic: 'Statistical Techniques',
  notions: 'Geographical data, primary data, secondary data, population, sample, random, systematic and stratified sampling, observation, measurement, questionnaire, interview, focus group.',
  focus: 'Sources of geographical data (primary and secondary); basic sampling procedures (random, systematic, stratified); primary data collection techniques.',
  competence: 'Learners are able to choose sources, sampling methods and techniques to collect data for a geographical investigation in Garoua.',
  objectives: ['Distinguish primary and secondary data with examples.', 'Explain why sampling is used.', 'Describe random, systematic and stratified sampling.', 'Describe the main primary data collection techniques.'],
  recall: ['A census counts the whole population.', 'A sample is a part of the population.', 'A rain gauge measures rainfall.'],
  situation: 'Aïcha\'s mother sells fabrics at the Grand Marché of Garoua and has had fewer customers recently. Aïcha wants to use her geography to find out why. She cannot question the thousands of people who visit the market, and she does not know which information to collect or how. She asks: "Where can I find reliable information, how can I choose the people to question, and which methods should I use?"',
  sitQA: [['What is the problem in the situation?', 'Aïcha does not know how to collect geographical data for her investigation.'],
    ['What does Aïcha need first?', 'Data: facts about customers and the market, not guesses.'],
    ['How can she study the market without questioning everyone?', 'By sampling: choosing a small, representative group.']],
  justification: 'This lesson gives the methods used in fieldwork, projects and examinations to collect reliable data.',
  action: 'Plan every investigation by stating the data needed, the sample and the collection techniques.',
  activities: [
    { sec: '1. SOURCES', img: 'data_sources_big.png', caption: 'Primary and secondary data.', q: 'Is a BUCREP census report primary or secondary data for a student?', a: 'Secondary data.', noProj: 'list sources in two columns.' },
    { sec: '2. SAMPLING', img: 'sampling_big.png', caption: 'Three sampling methods.', q: 'In which method does every member have an equal chance of being chosen?', a: 'Random sampling.', noProj: 'pick names from a box.' },
    { sec: '2. SAMPLING', img: 'stat2_systematic.png', caption: 'Systematic sampling.', q: 'What is the sampling interval for 20 students chosen from 200?', a: 'k = 200 ÷ 20 = 10.', noProj: 'select every 10th name on the class list.' },
    { sec: '3. TECHNIQUES', img: 'stat2_techniques.png', caption: 'Primary data collection techniques.', q: 'How can you study traffic on the Pont Neuf of Garoua?', a: 'By counting vehicles for a fixed time (observation and counting).', noProj: 'prepare a tally sheet.' },
    { sec: '3. TECHNIQUES', img: 'questionnaire_big.png', caption: 'Good and bad questions.', q: 'Why is "Isn\'t the market dirty?" a bad question?', a: 'It is a leading question that suggests the answer.', noProj: 'write two closed questions.' },
  ],
  summary: [
    D([['Geographical data:', 'They are facts and figures collected to study places, people and environments.'],
      ['Primary data:', 'They are first-hand data collected by the researcher for a specific purpose.'],
      ['Secondary data:', 'They are data already collected by someone else for another purpose.'],
      ['Population (in statistics):', 'It is the whole group to be studied.'],
      ['Sample:', 'It is a smaller, representative part of the population.']]),
    { title: '1. Sources of Geographical Data', intro: 'Geographical data come from the following sources:',
      items: [['Primary data:', 'They are original, up to date and specific, collected by fieldwork, observation, measurement, interviews and questionnaires.', 'data_sources_big.png', 'primary and secondary data'],
        ['Example of primary data:', 'Measuring the temperature of the Benue with a thermometer.'],
        ['Secondary data:', 'They already exist and are cheap and quick to obtain, but may be outdated or not fit the study.'],
        ['Sources of secondary data:', 'Books, BUCREP census reports, INS statistics, Cameroon Tribune, maps, websites and reports of the Ministry of Agriculture on cotton production.']] },
    { title: '2. Basic Sampling Procedures', intro: 'The basic sampling procedures are the following:',
      items: [['Why sample:', 'It is often impossible, too slow or too costly to study the whole population.', 'sampling_big.png', 'three sampling methods'],
        ['Random sampling:', 'Every member has an equal chance of being chosen, by drawing names from a box or using random numbers; it is unbiased.'],
        ['Systematic sampling:', 'Members are chosen at a regular interval k = population ÷ sample size, from a random start: for 20 out of 200, k = 10, so the 7th, 17th, 27th and so on.', 'stat2_systematic.png', 'systematic sampling'],
        ['Stratified sampling:', 'The population is divided into groups (strata), such as forms in a school, and each group is sampled in proportion to its size; it is very representative.']] },
    { title: '3. Primary Data Collection Techniques', intro: 'The main techniques of primary data collection are the following:',
      items: [['Observation, counting and recording:', 'Counting cars, motos and lorries on the Pont Neuf in one hour, or photographing house types in Yelwa.', 'stat2_techniques.png', 'collection techniques'],
        ['Measurement:', 'Instruments give precise figures: thermometer, rain gauge, measuring tape (river width), clinometer (slope angle).'],
        ['Questionnaires:', 'Written questions answered by respondents, with closed (yes/no, choices) or open questions.', 'questionnaire_big.png', 'good and bad questions'],
        ['Interviews:', 'Face-to-face or telephone conversations, structured (fixed questions) or unstructured.'],
        ['Focus group discussions:', 'A guided discussion with 6–10 people sharing a characteristic, such as cotton farmers near Garoua discussing climate change.']] },
  ],
  evaluation: [['Distinguish primary data from secondary data, with one example from Garoua for each.', 'Primary: collected by the researcher (counting motos at a crossroads); secondary: already published (BUCREP census figures).'],
    ['Explain how to select 30 people from a list of 600 by systematic sampling.', 'k = 600 ÷ 30 = 20; choose a random start between 1 and 20, then every 20th person.']],
  remediation: ['Data collected by the researcher are ______ data.', 'Choosing every 10th house is ______ sampling.', 'Dividing the population into groups first is ______ sampling.'],
  remediationAnswers: '1. primary 2. systematic 3. stratified',
  homework: 'Define the arithmetic mean.',
  hwAnswer: 'The arithmetic mean is the sum of all the values divided by the number of values.',
  bilingual: [['Data', 'Les données'], ['Sample', "L'échantillon"], ['Observation', "L'observation"], ['Questionnaire', 'Le questionnaire'], ['Interview', "L'entretien"], ['Sampling', "L'échantillonnage"]],
});

L.push({ kind: K, no: '3 (Part 1)', replaces: 'Quantitative Techniques 3', fileOverride: 'USA_PRA_QT03a_Measures_of_Central_Tendency_Range_and_Quartiles', title: 'Measures of Central Tendency, Range and Quartiles', topic: T, subtopic: 'Statistical Techniques',
  notions: 'Central tendency, mean, median, mode, unimodal, bimodal, outlier, range, quartiles, interquartile range.',
  focus: 'Measures of central tendency (mean, median, mode) with calculations, advantages and disadvantages; range; quartiles and interquartile range.',
  competence: 'Learners are able to calculate and interpret the mean, median, mode, range and interquartile range of geographical data.',
  objectives: ['Calculate the mean and state its advantages and disadvantages.', 'Find the median of odd and even sets of data.', 'Find the mode and recognise bimodal data.', 'Calculate the range.', 'Calculate the quartiles and the interquartile range.'],
  recall: ['A sample represents a population.', 'Data can be collected by measurement.', 'Garoua is very hot in March–April.'],
  situation: 'Oumarou has visited 9 small farms on the road to Pitoa and recorded their maize production in bags: 15, 20, 18, 20, 22, 17, 45, 16 and 19. One farm produced 45 bags, much more than the others. Looking at his list, he cannot say what the "typical" production is or how different the farms are. He asks: "Which single value best represents these farms, and how can I describe how spread out they are?"',
  sitQA: [['What is the problem in the situation?', 'Oumarou does not know how to summarise his data.'],
    ['Which value is usually used as the "average"?', 'The mean.'],
    ['Why may the median be better here?', 'The outlier (45 bags) pulls the mean up, but does not affect the median.']],
  justification: 'This lesson gives the basic tools to summarise geographical data in fieldwork, projects and examinations.',
  action: 'Always choose the average that suits the data and show all the working.',
  activities: [
    { sec: '1. MEAN', img: 'stat2_mean.png', caption: 'Worked examples of the mean.', q: 'Calculate the mean of Oumarou\'s 9 farms (total = 192 bags).', a: '192 ÷ 9 ≈ 21.3 bags.', noProj: 'add the values on the board.' },
    { sec: '1. MEDIAN', img: 'stat2_median.png', caption: 'Finding the median.', q: 'What is the median of Oumarou\'s farms (15, 16, 17, 18, 19, 20, 20, 22, 45)?', a: '19 bags (the 5th value).', noProj: 'order the values.' },
    { sec: '1. MODE', img: 'stat2_mode.png', caption: 'A frequency table.', q: 'What is the mode of Oumarou\'s farms?', a: '20 bags (it appears twice).', noProj: 'make a tally table.' },
    { sec: '2. RANGE', img: 'f4_maxmin.jpg', caption: 'A maximum and minimum thermometer.', q: 'Garoua\'s maxima for a week: 38, 40, 42, 37, 44, 41, 39 °C. What is the range?', a: '44 − 37 = 7 °C.', noProj: 'find the highest and lowest.' },
    { sec: '3. QUARTILES', img: 'stat2_iqr.png', caption: 'Quartiles and IQR.', q: 'Why is the IQR better than the range when there is an outlier?', a: 'It ignores the lowest and highest 25 % of the values.', noProj: 'split the ordered data in halves.' },
  ],
  summary: [
    D([['Measures of central tendency:', 'They are values that describe the centre or typical value of a set of data: the mean, the median and the mode.'],
      ['Outlier:', 'It is a value much higher or lower than the others.'],
      ['Range:', 'It is the difference between the highest and the lowest values.'],
      ['Interquartile range (IQR):', 'It is the difference between the upper and lower quartiles; it covers the middle 50 % of the data.']]),
    { title: '1. Measures of Central Tendency', sub: 'A) The Mean', intro: 'The mean is calculated and assessed as follows:',
      items: [['Formula:', 'Mean (x̄) = Σx ÷ n, where Σx is the sum of the values and n the number of values.', 'stat2_mean.png', 'examples of the mean'],
        ['Example 1:', 'Services in 10 villages (3, 10, 6, 8, 4, 5, 7, 18, 2, 1): 64 ÷ 10 = 6.4 services.'],
        ['Example 2:', 'Monthly temperatures of station A: Σx = 322 for 12 months, so the mean is about 26.8 °C.'],
        ['Advantages:', ['It is familiar and easy to understand.', 'It uses every value.', 'There is only one mean.', 'It is needed for the standard deviation.']],
        ['Disadvantages:', ['It is distorted by outliers, as the 45-bag farm.', 'It may not be an actual value.', 'It cannot be used for categories.']]] },
    { title: '1. Measures of Central Tendency', sub: 'B) The Median', intro: 'The median is found and assessed as follows:',
      items: [['Method:', 'Order the values, then take the value in position (n + 1) ÷ 2.', 'stat2_median.png', 'finding the median'],
        ['Odd number of values:', '3, 4, 5, 6, 8, 8, 10: position (7 + 1) ÷ 2 = 4th, so the median is 6.'],
        ['Even number of values:', '2, 3, 4, 5, 6, 7, 9, 12: the median is the mean of the 4th and 5th values, (5 + 6) ÷ 2 = 5.5.'],
        ['Example of Ndu (1963–1972):', 'The 5th and 6th of the ordered annual rainfalls are 1,942 and 1,904 mm, so the median is 1,923 mm.'],
        ['Advantages and disadvantages:', ['Advantage: it is easy and not affected by outliers.', 'Disadvantage: it ignores most values and is slow to find for large sets.']]] },
    { title: '1. Measures of Central Tendency', sub: 'C) The Mode', intro: 'The mode is found and assessed as follows:',
      items: [['Method:', 'The mode is the most frequent value, found by counting with a frequency table.', 'stat2_mode.png', 'a frequency table'],
        ['Example:', 'At station A, 28 °C occurs in 6 months, so the mode is 28 °C.'],
        ['Special cases:', ['2, 5, 8, 3, 7, 4, 11: no mode.', '1, 8, 7, 8, 5, 9, 11, 5: two modes, 5 and 8 (bimodal).']],
        ['Advantages:', 'It works for categories (soil types, means of transport), is easy to find and is not affected by outliers.'],
        ['Disadvantages:', 'There may be no mode or several modes, and it ignores the other values.', 'stat2_central_compare.png', 'mean, median and mode compared']] },
    { title: '2. The Range', intro: 'The range is calculated and assessed as follows:',
      items: [['Formula:', 'Range = highest value − lowest value.'],
        ['Example:', 'Garoua maxima for a week (38, 40, 42, 37, 44, 41, 39 °C): 44 − 37 = 7 °C.', 'f4_maxmin.jpg', 'a maximum and minimum thermometer'],
        ['Interpretation:', 'A large range shows widely spread data; a small range shows clustered data, as 28 − 23 = 5 °C at station A.'],
        ['Advantages and disadvantages:', ['Advantage: simple and quick.', 'Disadvantage: it uses only the two extreme values and is misled by outliers.']]] },
    { title: '3. Quartiles and the Interquartile Range', intro: 'The quartiles and the IQR are calculated as follows:',
      items: [['Steps:', ['Order the data.', 'Find the median (Q2).', 'Q1 is the median of the lower half.', 'Q3 is the median of the upper half.', 'IQR = Q3 − Q1.']],
        ['Example 1 (n = 11):', '102 … 118: median = 109, Q1 = 105, Q3 = 115, so IQR = 10.', 'stat2_iqr.png', 'quartiles and IQR'],
        ['Example 2 (n = 13):', '10, 25, 30, 30, 40, 41, 42, 50, 55, 70, 101, 110, 111: median = 42, Q1 = 30, Q3 = 85.5, so IQR = 55.5.'],
        ['Advantage:', 'The IQR is not affected by outliers because it ignores the lowest and highest quarters.', 'box_whisker_big.png', 'a box-and-whisker plot']] },
  ],
  evaluation: [['Find the mean, median and mode of 4, 7, 7, 9, 13.', 'Mean = 40 ÷ 5 = 8; median = 7; mode = 7.'],
    ['Why is the median better than the mean for Oumarou\'s farms?', 'The outlier (45 bags) raises the mean to about 21.3, while the median (19) represents most farms.']],
  remediation: ['Mean = Σx ÷ ______.', 'The most frequent value is the ______.', 'IQR = Q3 − ______.'],
  remediationAnswers: '1. n 2. mode 3. Q1',
  homework: 'Calculate the mean of 3, 5, 7 and 9.',
  hwAnswer: '(3 + 5 + 7 + 9) ÷ 4 = 24 ÷ 4 = 6.',
  bilingual: [['Mean', 'La moyenne'], ['Median', 'La médiane'], ['Mode', 'Le mode'], ['Range', "L'étendue"], ['Quartile', 'Le quartile'], ['Outlier', 'La valeur aberrante']],
});

L.push({ kind: K, no: '3 (Part 2)', replaces: 'Quantitative Techniques 3', fileOverride: 'USA_PRA_QT03b_Measures_of_Dispersion', title: 'Measures of Dispersion: Variance, Standard Deviation and Coefficient of Variation', topic: T, subtopic: 'Statistical Techniques',
  notions: 'Dispersion, deviation, variance, standard deviation, coefficient of variation, population (σ), sample (s).',
  focus: 'Variance: meaning, formula and calculation; standard deviation: steps and worked examples; coefficient of variation.',
  competence: 'Learners are able to calculate and interpret the variance, standard deviation and coefficient of variation of geographical data.',
  objectives: ['Define dispersion and variance.', 'Calculate the variance.', 'Calculate the standard deviation step by step.', 'Calculate and interpret the coefficient of variation.'],
  recall: ['Mean = Σx ÷ n.', 'The range uses only two values.', 'The IQR ignores outliers.'],
  situation: 'Two farmers near Garoua both harvest an average of 20 bags of maize a year. Over five years, the first harvested 19, 20, 21, 20 and 20 bags, while the second harvested 5, 35, 12, 30 and 18 bags. The bank must lend money to the more reliable farmer. The bank officer asks: "The averages are the same, so how can we measure which harvest varies more?"',
  sitQA: [['What is the problem in the situation?', 'The officer does not know how to measure the spread of data around the mean.'],
    ['Whose harvests are more regular?', 'The first farmer\'s.'],
    ['Which measure uses every value to show spread?', 'The standard deviation.']],
  justification: 'This lesson gives the most important measures of spread used in geography, for rainfall, yields, temperatures and populations.',
  action: 'Use the standard deviation and coefficient of variation to compare the reliability of rainfall or harvests.',
  activities: [
    { sec: '1. VARIANCE', img: 'stat2_variance.png', caption: 'Variance worked examples.', q: 'What is the first step in calculating the variance?', a: 'Calculate the mean.', noProj: 'write the steps on the board.' },
    { sec: '2. STANDARD DEVIATION', img: 'stat2_sd.png', caption: 'Standard deviation of household ages.', q: 'If the variance is 7, what is the standard deviation?', a: '√7 ≈ 2.65.', noProj: 'use a calculator for the square root.' },
    { sec: '2. STANDARD DEVIATION', img: 'sd_big.png', caption: 'A standard deviation table.', q: 'Why are the deviations squared?', a: 'To remove the negative signs.', noProj: 'add the deviations without squaring.' },
    { sec: '3. COEFFICIENT OF VARIATION', img: 'stat2_cv.png', caption: 'The coefficient of variation.', q: 'Calculate the CV if SD = 10.05 and mean = 13.', a: '10.05 ÷ 13 × 100 ≈ 77.3 %.', noProj: 'calculate on the board.' },
    { sec: '3. COEFFICIENT OF VARIATION', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'Would monthly rainfall in Garoua have a high or low CV?', a: 'High: some months have almost no rain and others over 200 mm.', noProj: 'read the rainfall bars.' },
  ],
  summary: [
    D([['Dispersion:', 'It is the spread of the values of a set of data around the mean.'],
      ['Variance (σ² or s²):', 'It is the mean of the squared deviations from the mean.'],
      ['Standard deviation (σ or s):', 'It is the square root of the variance; it shows how closely values cluster around the mean.'],
      ['Coefficient of variation (CV):', 'It is the standard deviation expressed as a percentage of the mean.']]),
    { title: '1. The Variance', intro: 'The variance is calculated as follows:',
      items: [['Formula:', 'Variance = Σ(x − x̄)² ÷ n.', 'stat2_variance.png', 'worked examples'],
        ['Steps:', ['Calculate the mean.', 'Subtract the mean from each value.', 'Square each deviation.', 'Add the squares and divide by n.']],
        ['Example:', 'Heights 610, 450, 160, 420, 310 mm: mean = 390, Σ(x − x̄)² = 112,200, variance = 112,200 ÷ 5 = 22,440 mm².'],
        ['Sample or population:', 'For a sample, statisticians divide by n − 1; for most GCE data treated as a whole set, we divide by n.']] },
    { title: '2. The Standard Deviation', intro: 'The standard deviation is calculated and interpreted as follows:',
      items: [['Formula:', 'SD = √[Σ(x − x̄)² ÷ n]; it is the most used measure of dispersion in GCE geography.', 'sd_big.png', 'a standard deviation table'],
        ['Example 1:', 'Minimum ages in 10 households (5, 8, 3, 2, 7, 9, 8, 2, 2, 4): mean = 5, Σ(x − x̄)² = 70, variance = 7, SD = √7 ≈ 2.65 years.', 'stat2_sd.png', 'household ages'],
        ['Example 2:', '12, 6, 7, 3, 15, 10, 18, 5: mean = 9.5, Σ(x − x̄)² = 190, variance = 23.75, SD ≈ 4.87.'],
        ['Interpretation:', 'A small SD means values cluster close to the mean; a large SD means they are widely spread.'],
        ['Advantage:', 'Unlike the range and the IQR, it uses every value in the set.']] },
    { title: '3. The Coefficient of Variation', intro: 'The coefficient of variation is calculated and interpreted as follows:',
      items: [['Formula:', 'CV = SD ÷ mean × 100 (%).', 'stat2_cv.png', 'the coefficient of variation'],
        ['Example:', 'A station with SD = 10.05 and mean = 13 has CV = 10.05 ÷ 13 × 100 ≈ 77.3 %.'],
        ['Interpretation:', 'A high CV shows very variable data, like the monthly rainfall of Garoua; a low CV shows regular data.', 'garoua_climate_big.png', 'the climate of Garoua'],
        ['Use:', 'It compares the variability of data with different means or units, such as rainfall of Garoua and Douala.']] },
  ],
  evaluation: [['Calculate the SD of 2, 4, 4, 4, 5, 5, 7, 9.', 'Mean = 40 ÷ 8 = 5; Σ(x − x̄)² = 32; variance = 4; SD = 2.'],
    ['Why is the CV useful when comparing two stations?', 'It expresses the spread relative to the mean, so stations with different means can be compared.']],
  remediation: ['The SD is the square ______ of the variance.', 'Deviations are ______ to remove negative signs.', 'CV = SD ÷ ______ × 100.'],
  remediationAnswers: '1. root 2. squared 3. mean',
  homework: 'Rank these values from highest to lowest: 12, 30, 25, 18.',
  hwAnswer: '30 (rank 1), 25 (rank 2), 18 (rank 3), 12 (rank 4).',
  bilingual: [['Dispersion', 'La dispersion'], ['Variance', 'La variance'], ['Standard deviation', "L'écart type"], ['Coefficient of variation', 'Le coefficient de variation'], ['Deviation', "L'écart"], ['Square root', 'La racine carrée']],
});

L.push({ kind: K, no: '3 (Part 3)', replaces: 'Quantitative Techniques 3', fileOverride: 'USA_PRA_QT03c_Measures_of_Association_Spearman', title: "Measures of Association: Spearman's Rank Correlation", topic: T, subtopic: 'Statistical Techniques',
  notions: 'Association, correlation, positive and negative correlation, rank, tied ranks, Spearman\'s rank correlation coefficient (Rs), null hypothesis, significance.',
  focus: 'Meaning and uses of Spearman\'s rank correlation; the formula and steps of calculation; interpretation and significance; worked example (slope angle and soil depth).',
  competence: 'Learners are able to calculate, interpret and test the significance of Spearman\'s rank correlation for geographical data.',
  objectives: ['Explain what Spearman\'s rank correlation measures.', 'Rank data, including tied values.', 'Calculate Rs step by step.', 'Interpret the strength and direction of Rs.', 'Test the significance of Rs.'],
  recall: ['Data can be ranked from highest to lowest.', 'A scatter graph shows a relationship between two variables.', 'Soil is thin on steep slopes.'],
  situation: 'During fieldwork on a hill near Garoua, students measured the slope angle and the soil depth at 10 points. They expected thin soils on steep slopes, but the figures seem to show the opposite. Their teacher tells them: "Do not guess. Measure the relationship." A student asks: "How can we calculate whether slope angle and soil depth are really related, and how strongly?"',
  sitQA: [['What is the problem in the situation?', 'The students do not know how to measure the relationship between two variables.'],
    ['Which statistic measures the relationship with ranks?', 'Spearman\'s rank correlation coefficient (Rs).'],
    ['What will the null hypothesis say?', 'There is no relationship between slope angle and soil depth.']],
  justification: 'This lesson gives a key tool to test geographical relationships in fieldwork and examinations.',
  action: 'Always state a null hypothesis, calculate Rs and test its significance before concluding.',
  activities: [
    { sec: '1. MEANING', img: 'scatter_big.png', caption: 'A negative correlation.', q: 'What kind of correlation does this graph show?', a: 'A negative correlation: one variable increases as the other decreases.', noProj: 'draw positive and negative patterns.' },
    { sec: '2. RANKING', img: 'spearman_big.png', caption: 'A simple Spearman table.', q: 'Two equal values would occupy ranks 2 and 3. Which rank do they receive?', a: '(2 + 3) ÷ 2 = 2.5 each.', noProj: 'rank the heights of five students.' },
    { sec: '3. CALCULATION', img: 'stat2_spearman.png', caption: 'Slope angle and soil depth.', q: 'Calculate Rs if Σd² = 48 and n = 10.', a: 'Rs = 1 − 288 ÷ 990 ≈ +0.71.', noProj: 'complete the table on the board.' },
    { sec: '4. INTERPRETATION', img: 'stat2_rs_scale.png', caption: 'Interpreting Rs.', q: 'What does Rs = +0.71 mean?', a: 'A fairly strong positive correlation.', noProj: 'draw the scale from −1 to +1.' },
    { sec: '4. SIGNIFICANCE', img: 'lsa_soilpit.jpg', caption: 'Measuring soil depth.', q: 'Is Rs = 0.71 significant at 95 % for n = 10 (critical value 0.648)?', a: 'Yes: 0.71 is greater than 0.648, so the null hypothesis is rejected.', noProj: 'compare with the critical value.' },
  ],
  summary: [
    D([['Correlation:', 'It is the relationship between two variables.'],
      ['Spearman\'s rank correlation coefficient (Rs):', 'It is a measure of the strength and direction of the relationship between two variables using their ranks.'],
      ['Null hypothesis (H0):', 'It is the statement that there is no relationship between the two variables.'],
      ['Significance:', 'It is the level of confidence that a correlation is real and not due to chance.']]),
    { title: '1. Meaning and Uses of Spearman\'s Rank Correlation', intro: 'Spearman\'s rank correlation tells us the following:',
      items: [['Existence:', 'Whether a relationship exists; Rs = 0 means no relationship.', 'scatter_big.png', 'a negative correlation'],
        ['Strength:', 'The closer Rs is to +1 or −1, the stronger the relationship.'],
        ['Direction:', ['Positive: both variables rise or fall together, like altitude and rainfall on a windward slope.', 'Negative: one rises while the other falls, like altitude and temperature.']],
        ['Use of ranks:', 'It uses ranks instead of values, so it works with ordinal data and uneven values.']] },
    { title: '2. Formula and Steps of Calculation', intro: 'Rs is calculated with the following steps:',
      items: [['Formula:', 'Rs = 1 − (6Σd²) ÷ (n³ − n), where d is the difference between ranks and n the number of pairs.', 'spearman_big.png', 'a simple Spearman table'],
        ['Steps:', ['State the null hypothesis (H0).', 'Count the pairs (n).', 'Rank each variable, the highest value getting rank 1.', 'Give tied values the average of their ranks.', 'Calculate d, then d², then Σd².', 'Substitute into the formula and interpret.']],
        ['Tied ranks:', 'Two soil depths of 60 cm would occupy ranks 1 and 2, so each gets 1.5.']] },
    { title: '3. Worked Example: Slope Angle and Soil Depth', intro: 'The worked example is solved as follows:',
      items: [['Null hypothesis:', 'H0: there is no significant relationship between slope angle and soil depth.'],
        ['Table:', 'The two variables of the 10 points are ranked and d² is calculated.', 'stat2_spearman.png', 'slope angle and soil depth'],
        ['Result:', 'Σd² = 48, so Rs = 1 − (6 × 48) ÷ (1,000 − 10) = 1 − 288 ÷ 990 ≈ +0.71.'],
        ['Interpretation:', 'Rs = +0.71 shows a fairly strong positive correlation: on this hill, soils tend to be deeper where slopes are steeper, perhaps because of vegetation or rock type.']] },
    { title: '4. Interpretation and Significance', intro: 'Rs is interpreted and tested as follows:',
      items: [['Scale:', ['+1: perfect positive correlation.', '+0.5 to +0.9: strong positive.', '+0.1 to +0.4: weak positive.', '0: no correlation.', '−0.1 to −0.4: weak negative; −0.5 to −0.9: strong negative; −1: perfect negative.']],
        ['Significance test:', 'Rs is compared with critical values from tables for the same n.', 'stat2_rs_scale.png', 'interpreting Rs'],
        ['Application:', 'For n = 10, the critical values are 0.648 (95 %) and 0.794 (99 %), so Rs = 0.71 is significant at 95 % but not at 99 %.'],
        ['Conclusion:', 'We reject H0 at the 95 % level: the relationship is real, not due to chance.']] },
  ],
  evaluation: [['State a null hypothesis for rainfall and crop yield.', 'H0: there is no significant relationship between annual rainfall and crop yield.'],
    ['Six pairs give Σd² = 4. Calculate Rs and interpret it.', 'Rs = 1 − 24 ÷ 210 ≈ +0.89: a strong positive correlation.']],
  remediation: ['Rs always lies between −1 and ______.', 'The null hypothesis says there is ______ relationship.', 'Rs = 1 − (6Σd²) ÷ (n³ − ______).'],
  remediationAnswers: '1. +1 2. no 3. n',
  homework: 'Name three types of graphs.',
  hwAnswer: 'Bar graphs, line graphs, pie charts, climographs, triangular graphs, scatter graphs or ogives (any three).',
  bilingual: [['Correlation', 'La corrélation'], ['Rank', 'Le rang'], ['Null hypothesis', "L'hypothèse nulle"], ['Significance', 'La significativité'], ['Positive', 'Positif'], ['Negative', 'Négatif']],
});

L.push({ kind: K, no: 4, title: 'Plotting and Interpreting Graphical Tools', topic: T, subtopic: 'Graphical Techniques',
  notions: 'Bar graph, line graph (simple, compound), ogive, cumulative frequency, climograph, pie chart, triangular graph, scatter graph, line of best fit.',
  focus: 'Construction, interpretation, advantages and disadvantages of bar graphs, line graphs, ogives, climographs, pie charts, triangular graphs and scatter graphs.',
  competence: 'Learners are able to choose, draw and interpret the main graphs used in geography.',
  objectives: ['Draw and interpret vertical and horizontal bar graphs.', 'Draw and interpret simple and compound line graphs.', 'Draw an ogive and read the median.', 'Draw a climograph and a pie chart.', 'Plot triangular and scatter graphs and interpret them.'],
  recall: ['Rs measures the relationship between two variables.', 'The median divides data into two halves.', 'Climate data include temperature and rainfall.'],
  situation: 'For his project on Garoua, a student has tables of rainfall and temperature, maize production by region, the shares of products at an agricultural show, soil samples and altitudes of weather stations. His teacher tells him that each set of data needs the right graph. He asks: "Which graph should I use for each set of data, how do I draw it correctly, and how do I interpret it?"',
  sitQA: [['What is the problem in the situation?', 'The student does not know how to choose, draw and interpret graphs.'],
    ['Which graph shows rainfall and temperature together?', 'The climograph.'],
    ['Which graph shows parts of a whole?', 'The pie chart.']],
  justification: 'This lesson gives the graphical skills needed in projects, fieldwork reports and practical examinations.',
  action: 'Always give a graph a title, labelled axes with units, a suitable scale and a key.',
  activities: [
    { sec: '1. BAR AND LINE GRAPHS', img: 'stat2_bar.png', caption: 'A vertical bar graph.', q: 'Which region produces the most maize?', a: 'The South (200 tons).', noProj: 'draw the bars on squared paper.' },
    { sec: '1. BAR AND LINE GRAPHS', img: 'stat2_line.png', caption: 'A simple line graph.', q: 'By how much does temperature fall for every 500 m?', a: '5 °C.', noProj: 'plot the four points.' },
    { sec: '2. OGIVE AND CLIMOGRAPH', img: 'stat2_ogive.png', caption: 'An ogive.', q: 'Which value is used on the x-axis of an ogive?', a: 'The upper limit of each class.', noProj: 'calculate the cumulative frequencies.' },
    { sec: '3. PIE CHART', img: 'stat2_pie.png', caption: 'A pie chart.', q: 'How many degrees represent 25 %?', a: '25 × 3.6 = 90°.', noProj: 'draw the pie with a protractor.' },
    { sec: '4. SCATTER GRAPH', img: 'stat2_scatter_alt.png', caption: 'Altitude and temperature.', q: 'What type of correlation does this scatter graph show?', a: 'A strong negative correlation.', noProj: 'draw the line of best fit by eye.' },
  ],
  summary: [
    D([['Bar graph:', 'It is a graph using bars whose length shows the value of each category.'],
      ['Line graph:', 'It is a graph joining points to show change over time or the relationship between two variables.'],
      ['Ogive:', 'It is a cumulative frequency curve.'],
      ['Climograph:', 'It is a graph combining rainfall (bars) and temperature (line) of a station.'],
      ['Scatter graph:', 'It is a graph of points showing the relationship between two numerical variables.']]),
    { title: '1. Bar Graphs', intro: 'Bar graphs are drawn and used as follows:',
      items: [['Types:', 'Vertical bars suit short category names; horizontal bars suit long names.', 'stat2_bar.png', 'a vertical bar graph'],
        ['Steps:', ['Choose the data and the type.', 'Draw the axes: categories and values.', 'Choose an even scale.', 'Draw bars of equal width and spacing with a ruler.', 'Add a title, axis labels with units and a key.']],
        ['Interpretation:', 'Maize: the South leads (200 t) and the Centre is lowest (100 t); rainfall: City B is wettest (700 mm) and City A driest (450 mm).', 'stat2_hbar.png', 'a horizontal bar graph'],
        ['Assessment:', ['Advantages: easy to draw and read; good for comparing categories.', 'Disadvantages: unsuitable for continuous data; cluttered with too many bars.']]] },
    { title: '2. Line Graphs', intro: 'Line graphs are drawn and used as follows:',
      items: [['Types:', 'A simple line graph shows one set of data; a compound line graph shows several sets with a key.'],
        ['Steps:', 'Put the independent variable (time, altitude) on the x-axis and the dependent variable on the y-axis, plot the points and join them with a ruler.', 'stat2_line.png', 'a simple line graph'],
        ['Example:', 'Temperature falls from 30 °C at sea level to 15 °C at 1,500 m: 5 °C every 500 m.'],
        ['Assessment:', ['Advantages: shows trends and allows prediction.', 'Disadvantages: several lines confuse; it shows trends but not causes.']]] },
    { title: '3. Ogives and Climographs', intro: 'Ogives and climographs are drawn and used as follows:',
      items: [['Ogive steps:', 'Make a frequency table, add frequencies progressively and plot cumulative frequency against the upper class limits.', 'stat2_ogive.png', 'an ogive'],
        ['Ogive example:', 'Scores of 25 students give points (10, 2), (20, 7), (30, 15), (40, 21) and (50, 25); the median (12.5th student) is about 27 marks.'],
        ['Climograph steps:', 'Months on the x-axis, rainfall as bars on one y-axis and temperature as a line on the other.', 'garoua_climate_big.png', 'the climograph of Garoua'],
        ['Climograph of Garoua:', 'It shows a rainy season from May to September–October with a peak in August, and a hot dry season with a maximum in March–April.'],
        ['Assessment:', ['Advantages: ogives give medians and quartiles; climographs compare rainfall and temperature month by month.', 'Disadvantages: ogives hide class frequencies; two axes may confuse readers.']]] },
    { title: '4. Pie Charts and Triangular Graphs', intro: 'Pie charts and triangular graphs are drawn and used as follows:',
      items: [['Pie chart steps:', 'Convert values to percentages, then to degrees (% × 3.6), and draw the sectors with a protractor.', 'stat2_pie.png', 'a pie chart'],
        ['Pie chart example:', 'At the Ebolowa agricultural show, cereals 30 % (108°), processed food 25 % (90°), livestock 20 % (72°), tubers 15 % (54°) and others 10 % (36°).'],
        ['Triangular graph:', 'It shows three components that total 100 %, such as a rock of 50 % quartz, 30 % feldspar and 20 % mica, or soil texture.', 'stat2_triangle.png', 'a triangular graph'],
        ['Assessment:', ['Advantages: pie charts show shares of a whole; triangular graphs compare many samples of three parts.', 'Disadvantages: pies are poor for many categories; triangular graphs are hard for beginners.']]] },
    { title: '5. Scatter Graphs', intro: 'Scatter graphs are drawn and used as follows:',
      items: [['Steps:', 'Put the independent variable on the x-axis, plot each pair as a dot, and draw a line of best fit by eye with equal points on both sides.', 'stat2_scatter.png', 'a positive correlation'],
        ['Example 1:', 'Moisture and organic content of soils rise together: a positive correlation, with one anomaly.'],
        ['Example 2:', 'Altitude and temperature: Nairobi (1,770 m) and Lubango have 17 °C, while Lagos and Cape Coast at sea level have 27 °C: a strong negative correlation.', 'stat2_scatter_alt.png', 'altitude and temperature'],
        ['Assessment:', ['Advantages: shows direction and strength of relationships and outliers.', 'Disadvantages: only two variables; a trend does not prove a cause.']]] },
  ],
  evaluation: [['Which graph would you choose for the percentages of workers in three sectors, and why?', 'A pie chart (or a triangular graph for several countries), because the parts make a whole of 100 %.'],
    ['Give one advantage and one disadvantage of a climograph.', 'Advantage: shows rainfall and temperature together; disadvantage: two vertical axes may confuse readers.']],
  remediation: ['In a pie chart, 1 % = ______°.', 'An ogive uses the ______ class limits.', 'On a climograph, rainfall is shown by ______.'],
  remediationAnswers: '1. 3.6 2. upper 3. bars',
  homework: 'Name the instrument that gives geographical coordinates by satellite.',
  hwAnswer: 'The GPS (Global Positioning System) receiver.',
  bilingual: [['Bar graph', "Le diagramme en barres"], ['Line graph', 'La courbe'], ['Pie chart', 'Le diagramme circulaire'], ['Scatter graph', 'Le nuage de points'], ['Cumulative frequency', 'La fréquence cumulée'], ['Line of best fit', "La droite d'ajustement"]],
});

module.exports = { B, L };
