// UPPER SIXTH ARTS — Practical Geography: statistical techniques (Quantitative Techniques 2, 3 in three parts, and 4)
// Rewritten from the teacher's course support (STATISTICAL TECHNIQUES IN GEOGRAPHICAL ANALYSIS, 2026) in our own words; calculations checked.
const D = (items, intro = 'The key terms of this lesson are defined as follows:') => ({ title: 'DEFINITIONS', intro, items });
const OLD = require('../v2_usa_prac2').B;
const B = Object.assign({}, OLD, {
  refs: ['Geography Syllabus for Sixth Forms (Lower and Upper Sixth), MINESEC, 2019 — Module 8 (Practical Geography).', 'Teacher\'s course notes: Mr KAMDEM E., Statistical Techniques in Geographical Analysis (USA), GBHS Garoua, 2026.'] });
const L = [];
const T = 'Quantitative Techniques in Geography', K = 'Quantitative Techniques';

L.push({ kind: K, no: 2, title: 'Data Collection: Sources and Techniques', topic: T, subtopic: 'Statistical Techniques', pointPerSlide: true,
  notions: 'Geographical data, primary data, secondary data, population, sample, random, systematic and stratified sampling, observation, measurement, questionnaire, interview, focus group.',
  focus: 'Sources of geographical data (primary and secondary); basic sampling procedures (random, systematic, stratified); primary data collection techniques.',
  competence: 'Learners are able to choose sources, sampling methods and techniques to collect data for a geographical investigation in Garoua.',
  objectives: ['Distinguish primary and secondary data with examples.', 'Explain why sampling is used.', 'Describe random, systematic and stratified sampling.', 'Describe the main primary data collection techniques.'],
  recall: ['A census counts the whole population.', 'A sample is a part of the population.', 'A rain gauge measures rainfall.'],
  situation: 'Aïcha\'s mother sells fabrics at the Grand Marché of Garoua and has had fewer customers recently. Aïcha wants to use her geography to find out why. She cannot question the thousands of people who visit the market, and she does not know which information to collect or how. She asks: "Where can I find reliable information, how can I choose the people to question, and which methods should I use?"',
  sitQA: [['What is the problem in the situation?', 'Aïcha does not know how to collect geographical data for her investigation.'],
    ['What does Aïcha need first?', 'Data: facts about customers and the market, not guesses.'],
    ['How can she study the market without questioning everyone?', 'By sampling: choosing a small, representative group.']],
  justification: 'This lesson gives the methods used in fieldwork, projects and examinations to collect reliable data.',
  action: 'Plan every investigation by stating the data needed, the sample and the collection techniques.',
  activities: [
    { sec: '1. SOURCES', img: 'data_sources_big.png', caption: 'Primary and secondary data.', q: 'Is a BUCREP census report primary or secondary data for a student?', a: 'Secondary data.', noProj: 'list sources in two columns.' },
    { sec: '2. SAMPLING', img: 'sampling_big.png', caption: 'Three sampling methods.', q: 'In which method does every member have an equal chance of being chosen?', a: 'Random sampling.', noProj: 'pick names from a box.' },
    { sec: '2. SAMPLING', img: 'stat2_systematic.png', caption: 'Systematic sampling.', q: 'What is the sampling interval for 20 students chosen from 200?', a: 'k = 200 ÷ 20 = 10.', noProj: 'select every 10th name on the class list.' },
    { sec: '3. TECHNIQUES', img: 'stat2_techniques.png', caption: 'Primary data collection techniques.', q: 'How can you study traffic on the Pont Neuf of Garoua?', a: 'By counting vehicles for a fixed time (observation and counting).', noProj: 'prepare a tally sheet.' },
    { sec: '3. TECHNIQUES', img: 'questionnaire_big.png', caption: 'Good and bad questions.', q: 'Why is "Isn\'t the market dirty?" a bad question?', a: 'It is a leading question that suggests the answer.', noProj: 'write two closed questions.' },
  ],
  summary: [
    D([['Geographical data:', 'They are facts and figures collected to study places, people and environments.'],
      ['Primary data:', 'They are first-hand data collected by the researcher for a specific purpose.'],
      ['Secondary data:', 'They are data already collected by someone else for another purpose.'],
      ['Population (in statistics):', 'It is the whole group to be studied.'],
      ['Sample:', 'It is a smaller, representative part of the population.']]),
    { title: "1. Sources of Geographical Data", sub: "A) Primary Data", intro: "Primary data are presented as follows:",
      items: [["Meaning:", "Primary data are collected by the researcher in person through fieldwork, observation, measurement, interviews and questionnaires. For example, a student measures the temperature of the Benue with a thermometer.", "data_sources_big.png", "sources of data"],
        ["Original and suited to the study:", "Primary data are new and up to date. They answer exactly the question that the researcher is studying."],
        ["Slow and costly to collect:", "Fieldwork takes a lot of time, transport and materials. A researcher can therefore only cover a small area."]] },
    { title: "1. Sources of Geographical Data", sub: "B) Secondary Data", intro: "Secondary data are presented as follows:",
      items: [["Meaning:", "Secondary data already exist in books, BUCREP census reports, INS statistics, newspapers such as Cameroon Tribune, maps and websites. Reports of the Ministry of Agriculture on cotton production are an example."],
        ["Cheap and quick to obtain:", "Secondary data are already published, so the researcher only has to consult them. They often cover large areas and long periods."],
        ["Possibly outdated or unsuited:", "Secondary data may be old, for example a census taken many years ago. They were also collected for another purpose, so they may not answer the question exactly."]] },
    { title: '2. Basic Sampling Procedures', intro: 'Samples are chosen by the following procedures:',
      items: [['Why sample:', 'It is often impossible, too slow or too costly to study every member of a population. A well-chosen sample gives reliable results for the whole group.', 'sampling_big.png', 'sampling methods'],
        ['Random sampling:', 'Every member has an equal chance of being chosen, for example by drawing names from a box or using random numbers. This method avoids bias.'],
        ['Systematic sampling:', 'Members are chosen at a regular interval k = population ÷ sample size, starting from a random point. To choose 20 out of 200, k = 10, so the 7th, 17th, 27th and so on are chosen.', 'stat2_systematic.png', 'systematic sampling'],
        ['Stratified sampling:', 'The population is divided into groups (strata), such as the forms of a school, and each group is sampled in proportion to its size. This makes the sample very representative.']] },
    { title: '3. Primary Data Collection Techniques', sub: 'A) Observation, Recording and Measurement', intro: 'Data are collected in the field with the following techniques:',
      items: [['Observation, counting and recording of frequencies:', 'The researcher watches and counts events and records them on a tally sheet. For example, he counts the cars, motorbikes and lorries crossing the Pont Neuf in Garoua in one hour.', 'stat2_techniques.png', 'data collection techniques'],
        ['Pictures, filming and video recording:', 'Photographs and videos record landscapes, house types or activities as evidence. For example, a student photographs the types of houses in the Yelwa quarter.'],
        ['Measurement:', 'Instruments give precise figures, such as a thermometer for temperature, a rain gauge for rainfall and a measuring tape for the width of a river. A clinometer measures the angle of slopes.']] },
    { title: '3. Primary Data Collection Techniques', sub: 'B) Questionnaires, Interviews and Focus Groups', intro: 'Data are collected from people with the following techniques:',
      items: [['Questionnaires:', 'They are written questions answered by respondents, with closed questions (yes or no, or choices) or open questions. Closed questions are easy to count, while open questions give more detail.', 'questionnaire_big.png', 'a questionnaire'],
        ['Interviews:', 'They are face-to-face or telephone conversations with respondents. They can be structured, with fixed questions, or unstructured, like a free conversation.'],
        ['Focus group discussions:', 'A small group of 6 to 10 people who share a characteristic discusses a topic guided by the researcher. For example, cotton farmers near Garoua discuss the effects of climate change on their harvests.']] },
  ],
  evaluation: [['Distinguish primary data from secondary data, with one example from Garoua for each.', 'Primary: collected by the researcher (counting motos at a crossroads); secondary: already published (BUCREP census figures).'],
    ['Explain how to select 30 people from a list of 600 by systematic sampling.', 'k = 600 ÷ 30 = 20; choose a random start between 1 and 20, then every 20th person.']],
  remediation: ['Data collected by the researcher are ______ data.', 'Choosing every 10th house is ______ sampling.', 'Dividing the population into groups first is ______ sampling.'],
  remediationAnswers: '1. primary 2. systematic 3. stratified',
  homework: 'Define the arithmetic mean.',
  hwAnswer: 'The arithmetic mean is the sum of all the values divided by the number of values.',
  bilingual: [['Data', 'Les données'], ['Sample', "L'échantillon"], ['Observation', "L'observation"], ['Questionnaire', 'Le questionnaire'], ['Interview', "L'entretien"], ['Sampling', "L'échantillonnage"]],
});

L.push({ kind: K, no: '3 (Part 1)', replaces: 'Quantitative Techniques 3', fileOverride: 'USA_PRA_QT03a_Measures_of_Central_Tendency_Range_and_Quartiles', title: 'Measures of Central Tendency, Range and Quartiles', topic: T, subtopic: 'Statistical Techniques', pointPerSlide: true,
  notions: 'Central tendency, mean, median, mode, unimodal, bimodal, outlier, range, quartiles, interquartile range.',
  focus: 'Measures of central tendency (mean, median, mode) with calculations, advantages and disadvantages; range; quartiles and interquartile range.',
  competence: 'Learners are able to calculate and interpret the mean, median, mode, range and interquartile range of geographical data.',
  objectives: ['Calculate the mean and state its advantages and disadvantages.', 'Find the median of odd and even sets of data.', 'Find the mode and recognise bimodal data.', 'Calculate the range.', 'Calculate the quartiles and the interquartile range.'],
  recall: ['A sample represents a population.', 'Data can be collected by measurement.', 'Garoua is very hot in March–April.'],
  situation: 'Oumarou has visited 9 small farms on the road to Pitoa and recorded their maize production in bags: 15, 20, 18, 20, 22, 17, 45, 16 and 19. One farm produced 45 bags, much more than the others. Looking at his list, he cannot say what the "typical" production is or how different the farms are. He asks: "Which single value best represents these farms, and how can I describe how spread out they are?"',
  sitQA: [['What is the problem in the situation?', 'Oumarou does not know how to summarise his data.'],
    ['Which value is usually used as the "average"?', 'The mean.'],
    ['Why may the median be better here?', 'The outlier (45 bags) pulls the mean up, but does not affect the median.']],
  justification: 'This lesson gives the basic tools to summarise geographical data in fieldwork, projects and examinations.',
  action: 'Always choose the average that suits the data and show all the working.',
  activities: [
    { sec: '1. MEAN', img: 'stat2_mean.png', caption: 'Worked examples of the mean.', q: 'Calculate the mean of Oumarou\'s 9 farms (total = 192 bags).', a: '192 ÷ 9 ≈ 21.3 bags.', noProj: 'add the values on the board.' },
    { sec: '1. MEDIAN', img: 'stat2_median.png', caption: 'Finding the median.', q: 'What is the median of Oumarou\'s farms (15, 16, 17, 18, 19, 20, 20, 22, 45)?', a: '19 bags (the 5th value).', noProj: 'order the values.' },
    { sec: '1. MODE', img: 'stat2_mode.png', caption: 'A frequency table.', q: 'What is the mode of Oumarou\'s farms?', a: '20 bags (it appears twice).', noProj: 'make a tally table.' },
    { sec: '2. RANGE', img: 'f4_maxmin.jpg', caption: 'A maximum and minimum thermometer.', q: 'Garoua\'s maxima for a week: 38, 40, 42, 37, 44, 41, 39 °C. What is the range?', a: '44 − 37 = 7 °C.', noProj: 'find the highest and lowest.' },
    { sec: '3. QUARTILES', img: 'stat2_iqr.png', caption: 'Quartiles and IQR.', q: 'Why is the IQR better than the range when there is an outlier?', a: 'It ignores the lowest and highest 25 % of the values.', noProj: 'split the ordered data in halves.' },
  ],
  summary: [
    D([['Measures of central tendency:', 'They are values that describe the centre or typical value of a set of data: the mean, the median and the mode.'],
      ['Outlier:', 'It is a value much higher or lower than the others.'],
      ['Range:', 'It is the difference between the highest and the lowest values.'],
      ['Interquartile range (IQR):', 'It is the difference between the upper and lower quartiles; it covers the middle 50 % of the data.']]),
    { title: "1. Measures of Central Tendency", sub: "A) The Mean: Calculation", intro: "The mean is calculated as follows:",
      items: [["Formula:", "Mean (x̄) = Σx ÷ n, where Σx is the sum of the values and n the number of values. The mean is the average of all the values.", "stat2_mean.png", "the mean"],
        ["Example of the villages:", "The services of 10 villages are 3, 10, 6, 8, 4, 5, 7, 18, 2 and 1, which add up to 64. The mean is therefore 64 ÷ 10 = 6.4 services."],
        ["Example of station A:", "The twelve monthly temperatures of station A add up to Σx = 322. The mean temperature is therefore 322 ÷ 12 ≈ 26.8 °C."]] },
    { title: "1. Measures of Central Tendency", sub: "B) The Mean: Advantages and Disadvantages", intro: "The mean has the following advantages and disadvantages:",
      items: [["It uses every value:", "The mean is familiar and easy to understand, and every value of the set is included in it. It is therefore a complete summary of the data."],
        ["It is needed for other measures:", "The mean is used to calculate the variance and the standard deviation. Without it, dispersion cannot be measured precisely."],
        ["It is distorted by outliers:", "One extreme value can pull the mean far from most values. For 3, 4, 5, 6 and 45 bags, the mean of 12.6 bags does not represent most farms."],
        ["It may not be a real value:", "The mean is often a value that does not exist in the set, such as 6.4 services. It also cannot be used for categories such as soil types."]] },
    { title: "1. Measures of Central Tendency", sub: "C) The Median: Calculation", intro: "The median is found as follows:",
      items: [["Method:", "Put the values in order, then take the value in position (n + 1) ÷ 2. The median is the middle value of the set.", "stat2_median.png", "the median"],
        ["An odd number of values:", "For 3, 4, 5, 6, 8, 8 and 10, the position is (7 + 1) ÷ 2 = 4th. The median is therefore 6."],
        ["An even number of values:", "For 2, 3, 4, 5, 6, 7, 9 and 12, the middle falls between the 4th and 5th values. The median is their mean, (5 + 6) ÷ 2 = 5.5."],
        ["Example of Ndu (1963 to 1972):", "The annual rainfalls of the ten years are put in order. The 5th and 6th values are 1,942 and 1,904 mm, so the median is 1,923 mm."]] },
    { title: "1. Measures of Central Tendency", sub: "D) The Median: Advantages and Disadvantages", intro: "The median has the following advantages and disadvantages:",
      items: [["It is not affected by outliers:", "An extreme value at either end does not change the middle value. The median therefore represents skewed data better than the mean."],
        ["It is easy to find:", "For a small set, the values only need to be put in order. No long calculation is needed."],
        ["It ignores most values:", "Only the middle value or the two middle values are used. For large sets, putting all the values in order is also slow."]] },
    { title: "1. Measures of Central Tendency", sub: "E) The Mode: Calculation", intro: "The mode is found as follows:",
      items: [["Method:", "The mode is the most frequent value, found by counting with a frequency table. At station A, 28 °C occurs in 6 months, so the mode is 28 °C.", "stat2_mode.png", "the mode"],
        ["A set with no mode:", "In the set 2, 5, 8, 3, 7, 4 and 11, no value is repeated. This set therefore has no mode."],
        ["A bimodal set:", "In the set 1, 8, 7, 8, 5, 9, 11 and 5, the values 5 and 8 both occur twice. The set has two modes and is called bimodal."]] },
    { title: "1. Measures of Central Tendency", sub: "F) The Mode: Advantages and Disadvantages", intro: "The mode has the following advantages and disadvantages:",
      items: [["It can be used for categories:", "The mode is the only measure that works for categories, such as soil types or means of transport. It shows the most common category.", "stat2_central_compare.png", "comparing the three measures"],
        ["It is not affected by outliers:", "Extreme values are rare, so they do not change the most frequent value. The mode remains a typical value."],
        ["There may be no mode or several:", "Some sets have no repeated value, and others have two or more modes. The mode also ignores all the other values."]] },
    { title: "2. The Range", sub: "A) Calculation and Interpretation", intro: "The range is calculated and interpreted as follows:",
      items: [["Formula:", "Range = highest value − lowest value. It measures the spread between the two extreme values.", "f4_maxmin.jpg", "a maximum and minimum thermometer"],
        ["Example of Garoua:", "The maximum temperatures of Garoua in a week are 38, 40, 42, 37, 44, 41 and 39 °C. The range is 44 − 37 = 7 °C."],
        ["Interpretation:", "A large range shows widely spread data. A small range, such as 28 − 23 = 5 °C at station A, shows clustered data."]] },
    { title: "2. The Range", sub: "B) Advantages and Disadvantages", intro: "The range has the following advantages and disadvantages:",
      items: [["It is simple and quick:", "Only the highest and the lowest values are needed. It gives a first idea of the spread of the data."],
        ["It is misled by outliers:", "It uses only the two extreme values and ignores all the others. One unusual value can therefore give a very large range."]] },
    { title: '3. Quartiles and the Interquartile Range', intro: 'The quartiles and the interquartile range are calculated as follows:',
      items: [['Steps:', 'Put the data in order and find the median (Q2). The lower quartile (Q1) is the median of the lower half, the upper quartile (Q3) is the median of the upper half, and IQR = Q3 − Q1.', 'stat2_iqr.png', 'quartiles'],
        ['Example 1 (n = 11):', 'For eleven values from 102 to 118, the median is 109, Q1 is 105 and Q3 is 115. The interquartile range is 115 − 105 = 10.'],
        ['Example 2 (n = 13):', 'For 10, 25, 30, 30, 40, 41, 42, 50, 55, 70, 101, 110, 111, the median is 42 and Q1 = (30 + 30) ÷ 2 = 30. Q3 = (70 + 101) ÷ 2 = 85.5, so the IQR is 85.5 − 30 = 55.5.'],
        ['Advantage:', 'The IQR covers the middle 50 % of the data and ignores the lowest and highest quarters. It is therefore not affected by outliers, unlike the range.', 'box_whisker_big.png', 'a box and whisker plot']] },
  ],
  evaluation: [['Find the mean, median and mode of 4, 7, 7, 9, 13.', 'Mean = 40 ÷ 5 = 8; median = 7; mode = 7.'],
    ['Why is the median better than the mean for Oumarou\'s farms?', 'The outlier (45 bags) raises the mean to about 21.3, while the median (19) represents most farms.']],
  remediation: ['Mean = Σx ÷ ______.', 'The most frequent value is the ______.', 'IQR = Q3 − ______.'],
  remediationAnswers: '1. n 2. mode 3. Q1',
  homework: 'Calculate the mean of 3, 5, 7 and 9.',
  hwAnswer: '(3 + 5 + 7 + 9) ÷ 4 = 24 ÷ 4 = 6.',
  bilingual: [['Mean', 'La moyenne'], ['Median', 'La médiane'], ['Mode', 'Le mode'], ['Range', "L'étendue"], ['Quartile', 'Le quartile'], ['Outlier', 'La valeur aberrante']],
});

L.push({ kind: K, no: '3 (Part 2)', replaces: 'Quantitative Techniques 3', fileOverride: 'USA_PRA_QT03b_Measures_of_Dispersion', title: 'Measures of Dispersion: Variance, Standard Deviation and Coefficient of Variation', topic: T, subtopic: 'Statistical Techniques', pointPerSlide: true,
  notions: 'Dispersion, deviation, variance, standard deviation, coefficient of variation, population (σ), sample (s).',
  focus: 'Variance: meaning, formula and calculation; standard deviation: steps and worked examples; coefficient of variation.',
  competence: 'Learners are able to calculate and interpret the variance, standard deviation and coefficient of variation of geographical data.',
  objectives: ['Define dispersion and variance.', 'Calculate the variance.', 'Calculate the standard deviation step by step.', 'Calculate and interpret the coefficient of variation.'],
  recall: ['Mean = Σx ÷ n.', 'The range uses only two values.', 'The IQR ignores outliers.'],
  situation: 'Two farmers near Garoua both harvest an average of 20 bags of maize a year. Over five years, the first harvested 19, 20, 21, 20 and 20 bags, while the second harvested 5, 35, 12, 30 and 18 bags. The bank must lend money to the more reliable farmer. The bank officer asks: "The averages are the same, so how can we measure which harvest varies more?"',
  sitQA: [['What is the problem in the situation?', 'The officer does not know how to measure the spread of data around the mean.'],
    ['Whose harvests are more regular?', 'The first farmer\'s.'],
    ['Which measure uses every value to show spread?', 'The standard deviation.']],
  justification: 'This lesson gives the most important measures of spread used in geography, for rainfall, yields, temperatures and populations.',
  action: 'Use the standard deviation and coefficient of variation to compare the reliability of rainfall or harvests.',
  activities: [
    { sec: '1. VARIANCE', img: 'stat2_variance.png', caption: 'Variance worked examples.', q: 'What is the first step in calculating the variance?', a: 'Calculate the mean.', noProj: 'write the steps on the board.' },
    { sec: '2. STANDARD DEVIATION', img: 'stat2_sd.png', caption: 'Standard deviation of household ages.', q: 'If the variance is 7, what is the standard deviation?', a: '√7 ≈ 2.65.', noProj: 'use a calculator for the square root.' },
    { sec: '2. STANDARD DEVIATION', img: 'sd_big.png', caption: 'A standard deviation table.', q: 'Why are the deviations squared?', a: 'To remove the negative signs.', noProj: 'add the deviations without squaring.' },
    { sec: '3. COEFFICIENT OF VARIATION', img: 'stat2_cv.png', caption: 'The coefficient of variation.', q: 'Calculate the CV if SD = 10.05 and mean = 13.', a: '10.05 ÷ 13 × 100 ≈ 77.3 %.', noProj: 'calculate on the board.' },
    { sec: '3. COEFFICIENT OF VARIATION', img: 'garoua_climate_big.png', caption: 'The climate of Garoua.', q: 'Would monthly rainfall in Garoua have a high or low CV?', a: 'High: some months have almost no rain and others over 200 mm.', noProj: 'read the rainfall bars.' },
  ],
  summary: [
    D([['Dispersion:', 'It is the spread of the values of a set of data around the mean.'],
      ['Variance (σ² or s²):', 'It is the mean of the squared deviations from the mean.'],
      ['Standard deviation (σ or s):', 'It is the square root of the variance; it shows how closely values cluster around the mean.'],
      ['Coefficient of variation (CV):', 'It is the standard deviation expressed as a percentage of the mean.']]),
    { title: '1. The Variance', intro: 'The variance is calculated as follows:',
      items: [['Formula:', 'Variance = Σ(x − x̄)² ÷ n. It measures the average squared distance of the values from the mean.', 'stat2_variance.png', 'the variance'],
        ['Steps:', 'Calculate the mean, then subtract it from each value to find the deviations. Square each deviation, add the squares and divide by n.'],
        ['Example:', 'For heights of 610, 450, 160, 420 and 310 mm, the mean is 390 and Σ(x − x̄)² = 112,200. The variance is 112,200 ÷ 5 = 22,440 mm².'],
        ['Sample or population:', 'For a sample, statisticians divide by n − 1 instead of n. For most GCE data, treated as a whole set, we divide by n.']] },
    { title: '2. The Standard Deviation', intro: 'The standard deviation is calculated and interpreted as follows:',
      items: [['Formula:', 'SD = √[Σ(x − x̄)² ÷ n], the square root of the variance. It is the most used measure of dispersion in GCE geography.', 'sd_big.png', 'the standard deviation'],
        ['Example 1:', 'The minimum ages in 10 households are 5, 8, 3, 2, 7, 9, 8, 2, 2 and 4, so the mean is 5 and Σ(x − x̄)² = 70. The variance is 70 ÷ 10 = 7 and the SD is √7 ≈ 2.65 years.', 'stat2_sd.png', 'a worked example'],
        ['Example 2:', 'For 12, 6, 7, 3, 15, 10, 18 and 5, the mean is 9.5 and Σ(x − x̄)² = 190. The variance is 190 ÷ 8 = 23.75 and the SD is about 4.87.'],
        ['Interpretation:', 'A small SD means the values cluster close to the mean, while a large SD means they are widely spread. Unlike the range and the IQR, it uses every value in the set.']] },
    { title: "3. The Coefficient of Variation", intro: "The coefficient of variation is calculated and interpreted as follows:",
      items: [["Formula:", "CV = SD ÷ mean × 100, in %. It expresses the standard deviation as a percentage of the mean.", "stat2_cv.png", "the coefficient of variation"],
        ["Example:", "A station has a standard deviation of 10.05 and a mean of 13. Its CV is 10.05 ÷ 13 × 100 ≈ 77.3 %."],
        ["Interpretation:", "A high CV shows very variable data, like the monthly rainfall of Garoua, which is very high in August and nil in January. A low CV shows regular data.", "garoua_climate_big.png", "the climate of Garoua"],
        ["Use:", "The CV compares the variability of data sets with different means or units. For example, it shows whether the rainfall of Garoua is more variable than that of Douala."]] },
  ],
  evaluation: [['Calculate the SD of 2, 4, 4, 4, 5, 5, 7, 9.', 'Mean = 40 ÷ 8 = 5; Σ(x − x̄)² = 32; variance = 4; SD = 2.'],
    ['Why is the CV useful when comparing two stations?', 'It expresses the spread relative to the mean, so stations with different means can be compared.']],
  remediation: ['The SD is the square ______ of the variance.', 'Deviations are ______ to remove negative signs.', 'CV = SD ÷ ______ × 100.'],
  remediationAnswers: '1. root 2. squared 3. mean',
  homework: 'Rank these values from highest to lowest: 12, 30, 25, 18.',
  hwAnswer: '30 (rank 1), 25 (rank 2), 18 (rank 3), 12 (rank 4).',
  bilingual: [['Dispersion', 'La dispersion'], ['Variance', 'La variance'], ['Standard deviation', "L'écart type"], ['Coefficient of variation', 'Le coefficient de variation'], ['Deviation', "L'écart"], ['Square root', 'La racine carrée']],
});

L.push({ kind: K, no: '3 (Part 3)', replaces: 'Quantitative Techniques 3', fileOverride: 'USA_PRA_QT03c_Measures_of_Association_Spearman', title: "Measures of Association: Spearman's Rank Correlation", topic: T, subtopic: 'Statistical Techniques', pointPerSlide: true,
  notions: 'Association, correlation, positive and negative correlation, rank, tied ranks, Spearman\'s rank correlation coefficient (Rs), null hypothesis, significance.',
  focus: 'Meaning and uses of Spearman\'s rank correlation; the formula and steps of calculation; interpretation and significance; worked example (slope angle and soil depth).',
  competence: 'Learners are able to calculate, interpret and test the significance of Spearman\'s rank correlation for geographical data.',
  objectives: ['Explain what Spearman\'s rank correlation measures.', 'Rank data, including tied values.', 'Calculate Rs step by step.', 'Interpret the strength and direction of Rs.', 'Test the significance of Rs.'],
  recall: ['Data can be ranked from highest to lowest.', 'A scatter graph shows a relationship between two variables.', 'Soil is thin on steep slopes.'],
  situation: 'During fieldwork on a hill near Garoua, students measured the slope angle and the soil depth at 10 points. They expected thin soils on steep slopes, but the figures seem to show the opposite. Their teacher tells them: "Do not guess. Measure the relationship." A student asks: "How can we calculate whether slope angle and soil depth are really related, and how strongly?"',
  sitQA: [['What is the problem in the situation?', 'The students do not know how to measure the relationship between two variables.'],
    ['Which statistic measures the relationship with ranks?', 'Spearman\'s rank correlation coefficient (Rs).'],
    ['What will the null hypothesis say?', 'There is no relationship between slope angle and soil depth.']],
  justification: 'This lesson gives a key tool to test geographical relationships in fieldwork and examinations.',
  action: 'Always state a null hypothesis, calculate Rs and test its significance before concluding.',
  activities: [
    { sec: '1. MEANING', img: 'scatter_big.png', caption: 'A negative correlation.', q: 'What kind of correlation does this graph show?', a: 'A negative correlation: one variable increases as the other decreases.', noProj: 'draw positive and negative patterns.' },
    { sec: '2. RANKING', img: 'spearman_big.png', caption: 'A simple Spearman table.', q: 'Two equal values would occupy ranks 2 and 3. Which rank do they receive?', a: '(2 + 3) ÷ 2 = 2.5 each.', noProj: 'rank the heights of five students.' },
    { sec: '3. CALCULATION', img: 'stat2_spearman.png', caption: 'Slope angle and soil depth.', q: 'Calculate Rs if Σd² = 48 and n = 10.', a: 'Rs = 1 − 288 ÷ 990 ≈ +0.71.', noProj: 'complete the table on the board.' },
    { sec: '4. INTERPRETATION', img: 'stat2_rs_scale.png', caption: 'Interpreting Rs.', q: 'What does Rs = +0.71 mean?', a: 'A fairly strong positive correlation.', noProj: 'draw the scale from −1 to +1.' },
    { sec: '4. SIGNIFICANCE', img: 'lsa_soilpit.jpg', caption: 'Measuring soil depth.', q: 'Is Rs = 0.71 significant at 95 % for n = 10 (critical value 0.648)?', a: 'Yes: 0.71 is greater than 0.648, so the null hypothesis is rejected.', noProj: 'compare with the critical value.' },
  ],
  summary: [
    D([['Correlation:', 'It is the relationship between two variables.'],
      ["Spearman's rank correlation coefficient (Rs):", 'It is a measure of the strength and direction of the relationship between two variables using their ranks.'],
      ['Null hypothesis (H0):', 'It is the statement that there is no relationship between the two variables.'],
      ['Significance:', 'It is the level of confidence that a correlation is real and not due to chance.']]),
    { title: "1. Meaning and Uses of Spearman's Rank Correlation", intro: "Spearman's rank correlation shows the following:",
      items: [['Existence and strength:', 'Rs shows whether a relationship exists between two variables; Rs = 0 means there is none. The closer Rs is to +1 or −1, the stronger the relationship.', 'scatter_big.png', 'types of correlation'],
        ['Direction:', 'A positive correlation means that both variables rise or fall together, like altitude and rainfall on a windward slope. A negative correlation means that one rises while the other falls, like altitude and temperature.'],
        ['Use of ranks:', 'The method uses the ranks of the values instead of the values themselves. It therefore works with ordinal data and with very uneven values.']] },
    { title: "2. Formula and Steps of Calculation", sub: "A) The Formula", intro: "The formula of Spearman is used as follows:",
      items: [["Formula:", "Rs = 1 − (6Σd²) ÷ (n³ − n), where d is the difference between the two ranks of each pair and n is the number of pairs. The result always lies between −1 and +1.", "spearman_big.png", "Spearman's formula"],
        ["Tied ranks:", "When two values are equal, they share the average of the ranks they occupy. For example, two soil depths of 60 cm occupying ranks 1 and 2 each get rank 1.5."]] },
    { title: "2. Formula and Steps of Calculation", sub: "B) The Steps", intro: "Rs is calculated in the following steps:",
      items: [["Step 1, the hypothesis:", "State the null hypothesis (H0), which says that there is no relationship between the two variables. Then count the number of pairs (n)."],
        ["Step 2, the ranks:", "Rank each variable separately, giving rank 1 to the highest value. Write the two ranks of each pair side by side in a table."],
        ["Step 3, the differences:", "For each pair, calculate the difference d between the two ranks and square it. Add all the squares to find Σd²."],
        ["Step 4, the result:", "Substitute Σd² and n into the formula to find Rs. Then interpret its sign and its value."]] },
    { title: '3. Worked Example: Slope Angle and Soil Depth', intro: 'The worked example is solved as follows:',
      items: [['Hypothesis and data:', 'H0: there is no significant relationship between slope angle and soil depth. Slope angle and soil depth are measured at 10 points on a hill, and each variable is ranked.', 'stat2_spearman.png', 'the calculation table'],
        ['Calculation:', 'The table gives Σd² = 48 and n = 10. Rs = 1 − (6 × 48) ÷ (1,000 − 10) = 1 − 288 ÷ 990 ≈ +0.71.'],
        ['Interpretation:', 'Rs = +0.71 shows a fairly strong positive correlation: on this hill, soils tend to be deeper where slopes are steeper. This may be explained by vegetation or rock type.']] },
    { title: '4. Interpretation and Significance', intro: 'Rs is interpreted and tested as follows:',
      items: [['Positive values:', 'Rs = +1 is a perfect positive correlation, +0.5 to +0.9 a strong one and +0.1 to +0.4 a weak one. Rs = 0 means there is no correlation.', 'stat2_rs_scale.png', 'the scale of Rs'],
        ['Negative values:', 'Rs = −1 is a perfect negative correlation, −0.5 to −0.9 a strong one and −0.1 to −0.4 a weak one. The sign shows the direction and the value shows the strength.'],
        ['Significance test:', 'Rs is compared with the critical values given in tables for the same number of pairs. If Rs is greater than the critical value, the correlation is significant.'],
        ['Application and conclusion:', 'For n = 10, the critical values are 0.648 at 95 % and 0.794 at 99 %, so Rs = 0.71 is significant at 95 % but not at 99 %. We therefore reject H0 at the 95 % level: the relationship is real and not due to chance.']] },
  ],
  evaluation: [['State a null hypothesis for rainfall and crop yield.', 'H0: there is no significant relationship between annual rainfall and crop yield.'],
    ['Six pairs give Σd² = 4. Calculate Rs and interpret it.', 'Rs = 1 − 24 ÷ 210 ≈ +0.89: a strong positive correlation.']],
  remediation: ['Rs always lies between −1 and ______.', 'The null hypothesis says there is ______ relationship.', 'Rs = 1 − (6Σd²) ÷ (n³ − ______).'],
  remediationAnswers: '1. +1 2. no 3. n',
  homework: 'Name three types of graphs.',
  hwAnswer: 'Bar graphs, line graphs, pie charts, climographs, triangular graphs, scatter graphs or ogives (any three).',
  bilingual: [['Correlation', 'La corrélation'], ['Rank', 'Le rang'], ['Null hypothesis', "L'hypothèse nulle"], ['Significance', 'La significativité'], ['Positive', 'Positif'], ['Negative', 'Négatif']],
});

L.push({ kind: K, no: 4, title: 'Plotting and Interpreting Graphical Tools', topic: T, subtopic: 'Graphical Techniques', pointPerSlide: true,
  notions: 'Bar graph, line graph (simple, compound), ogive, cumulative frequency, climograph, pie chart, triangular graph, scatter graph, line of best fit.',
  focus: 'Construction, interpretation, advantages and disadvantages of bar graphs, line graphs, ogives, climographs, pie charts, triangular graphs and scatter graphs.',
  competence: 'Learners are able to choose, draw and interpret the main graphs used in geography.',
  objectives: ['Draw and interpret vertical and horizontal bar graphs.', 'Draw and interpret simple and compound line graphs.', 'Draw an ogive and read the median.', 'Draw a climograph and a pie chart.', 'Plot triangular and scatter graphs and interpret them.'],
  recall: ['Rs measures the relationship between two variables.', 'The median divides data into two halves.', 'Climate data include temperature and rainfall.'],
  situation: 'For his project on Garoua, a student has tables of rainfall and temperature, maize production by region, the shares of products at an agricultural show, soil samples and altitudes of weather stations. His teacher tells him that each set of data needs the right graph. He asks: "Which graph should I use for each set of data, how do I draw it correctly, and how do I interpret it?"',
  sitQA: [['What is the problem in the situation?', 'The student does not know how to choose, draw and interpret graphs.'],
    ['Which graph shows rainfall and temperature together?', 'The climograph.'],
    ['Which graph shows parts of a whole?', 'The pie chart.']],
  justification: 'This lesson gives the graphical skills needed in projects, fieldwork reports and practical examinations.',
  action: 'Always give a graph a title, labelled axes with units, a suitable scale and a key.',
  activities: [
    { sec: '1. BAR AND LINE GRAPHS', img: 'stat2_bar.png', caption: 'A vertical bar graph.', q: 'Which region produces the most maize?', a: 'The South (200 tons).', noProj: 'draw the bars on squared paper.' },
    { sec: '1. BAR AND LINE GRAPHS', img: 'stat2_line.png', caption: 'A simple line graph.', q: 'By how much does temperature fall for every 500 m?', a: '5 °C.', noProj: 'plot the four points.' },
    { sec: '2. OGIVE AND CLIMOGRAPH', img: 'stat2_ogive.png', caption: 'An ogive.', q: 'Which value is used on the x-axis of an ogive?', a: 'The upper limit of each class.', noProj: 'calculate the cumulative frequencies.' },
    { sec: '3. PIE CHART', img: 'stat2_pie.png', caption: 'A pie chart.', q: 'How many degrees represent 25 %?', a: '25 × 3.6 = 90°.', noProj: 'draw the pie with a protractor.' },
    { sec: '4. SCATTER GRAPH', img: 'stat2_scatter_alt.png', caption: 'Altitude and temperature.', q: 'What type of correlation does this scatter graph show?', a: 'A strong negative correlation.', noProj: 'draw the line of best fit by eye.' },
  ],
  summary: [
    D([['Bar graph:', 'It is a graph using bars whose length shows the value of each category.'],
      ['Line graph:', 'It is a graph joining points to show change over time or the relationship between two variables.'],
      ['Ogive:', 'It is a cumulative frequency curve.'],
      ['Climograph:', 'It is a graph combining rainfall (bars) and temperature (line) of a station.'],
      ['Scatter graph:', 'It is a graph of points showing the relationship between two numerical variables.']]),
    { title: "1. Bar Graphs", sub: "A) Construction and Interpretation", intro: "Bar graphs are constructed and interpreted as follows:",
      items: [["Types:", "Vertical bar graphs suit short category names, while horizontal bar graphs suit long names. Both compare separate categories.", "stat2_bar.png", "a vertical bar graph"],
        ["Construction:", "Draw the axes, one for the categories and one for the values, and choose an even scale. Draw bars of equal width and spacing with a ruler, then add a title, axis labels with units and a key."],
        ["Interpretation:", "For maize production, the South leads with 200 t and the Centre is lowest with 100 t. For rainfall, City B is the wettest with 700 mm and City A the driest with 450 mm.", "stat2_hbar.png", "a horizontal bar graph"]] },
    { title: "1. Bar Graphs", sub: "B) Advantages and Disadvantages", intro: "Bar graphs have the following advantages and disadvantages:",
      items: [["Easy comparison:", "Bar graphs are easy to draw and read. The length of the bars shows at once which category is the largest."],
        ["Limited use:", "They are unsuitable for continuous data such as temperature over time. They also become cluttered when there are too many bars."]] },
    { title: "2. Linear Graphs", sub: "A) Construction and Interpretation", intro: "Line graphs are constructed and interpreted as follows:",
      items: [["Types:", "A simple line graph shows one set of data, such as the population of a town over time. A compound line graph shows several sets on the same axes, with a key."],
        ["Construction:", "Put the independent variable, such as time or altitude, on the x-axis and the dependent variable on the y-axis. Plot the points and join them with a ruler.", "stat2_line.png", "a line graph"],
        ["Example:", "Temperature falls from 30 °C at sea level to 15 °C at 1,500 m. The graph shows a regular fall of 5 °C every 500 m."]] },
    { title: "2. Linear Graphs", sub: "B) Advantages and Disadvantages", intro: "Line graphs have the following advantages and disadvantages:",
      items: [["Clear trends:", "Line graphs show clearly whether values rise or fall over time. They also allow future values to be predicted."],
        ["Risk of confusion:", "Several lines on the same graph can confuse the reader. A trend also does not show its causes."]] },
    { title: "3. Cumulative Frequency Curves (Ogives)", sub: "A) Construction and Interpretation", intro: "Ogives are constructed and interpreted as follows:",
      items: [["Cumulative frequencies:", "Make a frequency table and add the frequencies progressively to obtain the cumulative frequencies. The last cumulative frequency equals the total number of values.", "stat2_ogive.png", "an ogive"],
        ["Plotting:", "Plot each cumulative frequency against the upper limit of its class. Join the points with a smooth curve."],
        ["Example:", "The scores of 25 students give the points (10, 2), (20, 7), (30, 15), (40, 21) and (50, 25). The median, read at the 12.5th student, is about 27 marks."]] },
    { title: "3. Cumulative Frequency Curves (Ogives)", sub: "B) Advantages and Disadvantages", intro: "Ogives have the following advantages and disadvantages:",
      items: [["Quick reading of the median and quartiles:", "The median and the quartiles are read directly from the curve. No long calculation is needed."],
        ["Hidden class frequencies:", "The curve shows only running totals. The frequency of each class cannot be seen directly."]] },
    { title: "4. Climographs", sub: "A) Construction and Interpretation", intro: "Climographs are constructed and interpreted as follows:",
      items: [["Construction:", "Put the months on the x-axis, rainfall as bars on the left y-axis and temperature as a line on the right y-axis. Each axis must have its own scale and units.", "garoua_climate_big.png", "the climograph of Garoua"],
        ["Rainfall at Garoua:", "The climograph of Garoua shows a rainy season from May to October with a peak in August. From November to April, almost no rain falls."],
        ["Temperature at Garoua:", "The line shows a hot dry season with the highest temperatures in March and April. Temperatures fall slightly during the rainy season."]] },
    { title: "4. Climographs", sub: "B) Advantages and Disadvantages", intro: "Climographs have the following advantages and disadvantages:",
      items: [["Complete picture of the climate:", "Climographs compare rainfall and temperature month by month on one graph. The seasons can be seen at a glance."],
        ["Difficult for beginners:", "The two vertical axes have different scales and units. Beginners may read the bars on the wrong axis."]] },
    { title: "5. Pie Charts", sub: "A) Construction and Interpretation", intro: "Pie charts are constructed and interpreted as follows:",
      items: [["Construction:", "Convert the values to percentages, then to degrees by multiplying by 3.6. Draw the sectors with a protractor, starting from the top, and add a key.", "stat2_pie.png", "a pie chart"],
        ["Example:", "At the Ebolowa agricultural show, cereals were 30 % (108°), processed food 25 % (90°) and livestock 20 % (72°). Tubers were 15 % (54°) and others 10 % (36°)."]] },
    { title: "5. Pie Charts", sub: "B) Advantages and Disadvantages", intro: "Pie charts have the following advantages and disadvantages:",
      items: [["Clear shares:", "Pie charts show clearly the share of each part in a whole. The largest sector is seen at once."],
        ["Poor for many categories:", "With many categories, the sectors become too small to read. Small differences between sectors are also hard to see."]] },
    { title: "6. Triangular Graphs", sub: "A) Construction and Interpretation", intro: "Triangular graphs are constructed and interpreted as follows:",
      items: [["Construction:", "Each side of an equilateral triangle is a scale from 0 to 100 % for one of three components that add up to 100 %. Each sample is plotted as one point where the three values meet.", "stat2_triangle.png", "a triangular graph"],
        ["Example:", "A rock made of 50 % quartz, 30 % feldspar and 20 % mica is shown by one point. Soil texture, with its shares of sand, silt and clay, is also shown in this way."]] },
    { title: "6. Triangular Graphs", sub: "B) Advantages and Disadvantages", intro: "Triangular graphs have the following advantages and disadvantages:",
      items: [["Many samples on one graph:", "Many samples of three parts can be compared on one graph. Groups of similar samples appear as clusters of points."],
        ["Hard to read:", "Beginners find it difficult to follow the three scales. They often read a value on the wrong side of the triangle."]] },
    { title: "7. Scatter Graphs", sub: "A) Construction and Interpretation", intro: "Scatter graphs are constructed and interpreted as follows:",
      items: [["Construction:", "Put the independent variable on the x-axis and the dependent variable on the y-axis, and plot each pair of values as a dot. Draw a line of best fit by eye, with about the same number of points on each side.", "stat2_scatter.png", "a scatter graph"],
        ["Example 1:", "The moisture and organic content of soils rise together, which shows a positive correlation. One point lies far from the line and is an anomaly."],
        ["Example 2:", "Nairobi (1,770 m) and Lubango have about 17 °C, while Lagos and Cape Coast at sea level have about 27 °C. The graph shows a strong negative correlation between altitude and temperature.", "stat2_scatter_alt.png", "altitude and temperature"]] },
    { title: "7. Scatter Graphs", sub: "B) Advantages and Disadvantages", intro: "Scatter graphs have the following advantages and disadvantages:",
      items: [["Direction and strength of a relationship:", "Scatter graphs show whether two variables are related, and how strongly. They also reveal outliers that do not follow the trend."],
        ["Only two variables:", "A scatter graph shows only two variables at a time. A trend also does not prove that one variable causes the other."]] },
  ],
  evaluation: [['Which graph would you choose for the percentages of workers in three sectors, and why?', 'A pie chart (or a triangular graph for several countries), because the parts make a whole of 100 %.'],
    ['Give one advantage and one disadvantage of a climograph.', 'Advantage: shows rainfall and temperature together; disadvantage: two vertical axes may confuse readers.']],
  remediation: ['In a pie chart, 1 % = ______°.', 'An ogive uses the ______ class limits.', 'On a climograph, rainfall is shown by ______.'],
  remediationAnswers: '1. 3.6 2. upper 3. bars',
  homework: 'Name the instrument that gives geographical coordinates by satellite.',
  hwAnswer: 'The GPS (Global Positioning System) receiver.',
  bilingual: [['Bar graph', "Le diagramme en barres"], ['Line graph', 'La courbe'], ['Pie chart', 'Le diagramme circulaire'], ['Scatter graph', 'Le nuage de points'], ['Cumulative frequency', 'La fréquence cumulée'], ['Line of best fit', "La droite d'ajustement"]],
});

module.exports = { B, L };
