// LOWER SIXTH ARTS — BIOGEOGRAPHY part 2: VEGETATION AND ECOSYSTEMS (Module 3, lessons 12–28, FS2, FS3, PW2). 2 periods, 5 activities, summary 2–3 sentences per point.
const { run } = require('./sixth');
const { B } = require('./v2_lsa_bio1');
const V1 = 'Natural Vegetation', E1 = 'Ecological Systems (Ecosystems)', S3 = 'Physical Geography of Cameroon';
const L = [];

L.push({ no: 12, title: 'Meaning of Natural Vegetation', topic: V1, subtopic: 'Basic Concepts',
  notions: 'Natural vegetation, flora, plant formation, plant community, vegetation system.', focus: 'Definition; plant groupings and classification; the vegetation system; importance of vegetation.',
  competence: 'Learners are able to define natural vegetation, classify plant groupings and explain the importance of vegetation.',
  objectives: ['Define natural vegetation and related terms.', 'Classify plant groupings (forest, grassland, desert).', 'Explain the vegetation system and its importance.'],
  recall: ['Plants need sunlight, water, air and nutrients.', 'Climate changes from the south to the north of Cameroon.'],
  situation: 'Travelling from Kribi to Kousseri, a learner sees thick forest, then tall grass with trees, then short grass and thorny bushes. Near towns, he also sees oil palm and teak plantations.',
  sitQA: [['What is the problem in the situation?', 'The learner wants to understand the different plant covers.'], ['Is a plantation natural vegetation?', 'No, it was planted by man.'], ['How are plant covers grouped?', 'Into forests, grasslands and desert vegetation.']],
  justification: 'This lesson introduces the study of vegetation, which protects soils and supports life.',
  activities: [
    { sec: 'I. MEANING', img: 'f2t_rainforest.jpg', caption: 'A natural equatorial forest.', q: 'What is natural vegetation?', a: 'Plants that grow in an area without being planted by man.', noProj: 'describe a forest near your area.' },
    { sec: 'I. MEANING', img: 'lsa_oilpalm.jpg', caption: 'An oil palm plantation seen from the air.', q: 'Why is this not natural vegetation?', a: 'It was planted and is managed by man.', noProj: 'compare a farm and a forest.' },
    { sec: 'II. PLANT GROUPINGS', img: 'f2t_savanna.jpg', caption: 'A savanna grassland.', q: 'Name the three main plant formations.', a: 'Forests, grasslands and desert (scrub) vegetation.', noProj: 'list formations of Cameroon.' },
    { sec: 'III. THE VEGETATION SYSTEM', img: 'veg_system_big.png', caption: 'A plant as a system.', q: 'Name two inputs and two outputs of the vegetation system.', a: 'Inputs: sunlight, water, CO₂, nutrients. Outputs: oxygen, water vapour, dead leaves.', noProj: 'draw a tree with arrows.' },
    { sec: 'IV. IMPORTANCE', img: 'f2t_charcoal.jpg', caption: 'Charcoal made from wood.', q: 'Give three uses of vegetation to man.', a: 'Wood and fuel, food and medicines, protection of soils and water.', noProj: 'list uses of trees at home.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Natural vegetation:', 'It is the plant cover that grows without human planting.'], ['Flora:', 'It is all the plant species of an area.'], ['Plant formation:', 'It is a large group of plants with a similar appearance, such as forest or grassland.']] },
    { title: 'II. Plant Groupings and the System', items: [['A. Classification:', 'Vegetation is grouped into forests, grasslands and desert scrub. Each is divided by climate, such as tropical or temperate forest.'], ['B. Plant community:', 'It is a group of plants living together in one place. They compete for light, water and nutrients.'], ['C. The vegetation system:', 'Inputs are sunlight, water, carbon dioxide and nutrients. Outputs are oxygen, water vapour and litter.']] },
    { title: 'III. Importance of Vegetation', items: [['A. To the environment:', 'Vegetation protects soils from erosion and adds humus. It regulates climate and the water cycle.'], ['B. To man:', 'It gives wood, fuel, food, medicines and pasture. It also supports tourism.'], ['C. To animals:', 'It gives food and shelter to wildlife. It is the base of all food chains.']], draw: { img: 'veg_system_big.png', caption: 'Copy the vegetation system.' } },
  ],
  evaluation: [['Define natural vegetation.', 'The plant cover that grows without human planting.'], ['Give three importances of vegetation.', 'It protects soils, gives wood and food, regulates climate.']],
  remediation: ['All the plant species of an area is its ______.', 'Forest and grassland are plant ______.', 'Plants release ______ during photosynthesis.'], remediationAnswers: '1. flora 2. formations 3. oxygen',
  homework: 'List five plants of your area and say whether each is natural or planted.', homeworkTag: 'This prepares Lesson 13: Evolution of Vegetation over Time.',
  bilingual: [['Vegetation', 'La végétation'], ['Plant formation', 'La formation végétale'], ['Flora', 'La flore'], ['Plantation', 'La plantation'], ['Photosynthesis', 'La photosynthèse'], ['Litter', 'La litière']],
});

L.push({ no: 13, title: 'Evolution of Vegetation over Time: Plant Succession', topic: V1, subtopic: 'Development of Vegetation',
  notions: 'Plant succession, sere, prisere, pioneer, colonisation, climax, arresting factor.', focus: 'Notion of succession; types; sites of priseres; process of colonisation; arresting factors.',
  competence: 'Learners are able to explain how vegetation develops over time and what can stop it.',
  objectives: ['Define plant succession and its stages.', 'Name the types and sites of priseres.', 'Explain colonisation and arresting factors.'],
  recall: ['Soil forms from bare rock over time.', 'Lichens and mosses grow on rocks.'],
  situation: 'An old farm near Ebolowa was abandoned ten years ago. First grass covered it, then bushes, and now young trees are growing. Farmers say that "the forest is coming back".',
  sitQA: [['What is the problem in the situation?', 'The vegetation changes over time on the same land.'], ['What is this change called?', 'Plant succession.'], ['What is the final stage?', 'The climax vegetation (here, forest).']],
  justification: 'This lesson helps us to understand how vegetation grows back and why it is sometimes stopped.',
  activities: [
    { sec: 'I. SUCCESSION', img: 'succession.gif', caption: 'Animation: from bare rock to forest.', q: 'Name the stages of a plant succession.', a: 'Bare ground, pioneers (lichens, mosses), grasses, shrubs, climax forest.', noProj: 'draw the stages on the board.' },
    { sec: 'II. TYPES AND SITES', img: 'priseres_big.png', caption: 'The four priseres.', q: 'What is a hydrosere? Where does it begin?', a: 'A succession that begins in fresh water (a pond or lake).', noProj: 'list the four priseres.' },
    { sec: 'III. COLONISATION', img: 'lsa_lichen.jpg', caption: 'Lichens on bare rock.', q: 'Why are lichens called pioneer plants?', a: 'They are the first to grow on bare rock and start soil formation.', noProj: 'look for lichens on walls.' },
    { sec: 'III. COLONISATION', img: 'hydrosere_big.png', caption: 'A hydrosere from open water to woodland.', q: 'How does a pond slowly become dry land?', a: 'Dead plants and mud fill it, and land plants replace water plants.', noProj: 'describe a swampy pond.' },
    { sec: 'IV. ARRESTING FACTORS', img: 'f2t_bushfire.jpg', caption: 'Burnt land after a bush fire.', q: 'Give two factors that can stop a succession.', a: 'Fire and grazing (also farming, cutting).', noProj: 'discuss yearly bush fires.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Plant succession:', 'It is the gradual change of plant communities in an area over time.'], ['Sere:', 'It is the whole series of stages in a succession.'], ['Pioneer species:', 'They are the first plants to grow on bare ground.'], ['Climax:', 'It is the final, stable stage of a succession.']] },
    { title: 'II. Types and Sites', items: [['A. Primary succession:', 'It starts on new bare surfaces with no soil, like lava or sand. It is called a prisere.'], ['B. Secondary succession:', 'It starts where vegetation was removed but soil remains. It is faster than primary succession.'], ['C. Sites of priseres:', 'A lithosere starts on rock and a hydrosere in fresh water. A psammosere starts on sand and a halosere in salt water.']] },
    { title: 'III. Process and Arresting Factors', items: [['A. Colonisation:', 'Pioneers arrive, grow and change the site by adding humus. New plants then replace them.'], ['B. Competition:', 'Taller plants shade smaller ones. The community becomes richer until the climax.'], ['C. Arresting factors:', 'Fire, grazing, cutting and farming stop succession. The result is a plagioclimax, like many savannas.']] },
  ],
  evaluation: [['What is plant succession?', 'The gradual change of plant communities in an area over time.'], ['Distinguish primary and secondary succession.', 'Primary starts on bare ground without soil; secondary starts where soil remains.']],
  remediation: ['The first plants on bare rock are ______.', 'A succession in fresh water is a ______.', 'Fire and grazing are ______ factors.'], remediationAnswers: '1. pioneers 2. hydrosere 3. arresting',
  homework: 'Observe an abandoned field and describe the plants growing on it.', homeworkTag: 'This prepares Lesson 14: The Concept of Climax Vegetation.',
  bilingual: [['Succession', 'La succession végétale'], ['Pioneer', 'Pionnier'], ['Climax', 'Le climax'], ['Lichen', 'Le lichen'], ['Colonisation', 'La colonisation'], ['Pond', "L'étang"]],
});

L.push({ no: 14, title: 'The Concept of Climax Vegetation', topic: V1, subtopic: 'Development of Vegetation',
  notions: 'Climax, monoclimax, polyclimax, climatic climax, edaphic climax, plagioclimax.', focus: 'Meaning of climax vegetation; mono and poly climax views; types of climax; debate on the climax status of grasslands.',
  competence: 'Learners are able to explain the climax concept and discuss whether savannas are climax vegetation.',
  objectives: ['Define climax vegetation.', 'Compare the monoclimax and polyclimax views.', 'Discuss the climax status of grasslands.'],
  recall: ['Succession ends with a climax.', 'Fire and grazing can stop succession.'],
  situation: 'A forester says that much of the savanna of central Cameroon would become forest if bush fires stopped. A herder disagrees and says savanna is the natural vegetation there.',
  sitQA: [['What is the problem in the situation?', 'They disagree on whether savanna is a natural climax.'], ['What would happen without fire?', 'Trees might grow and forest could spread.'], ['What do we call vegetation kept by fire?', 'A plagioclimax.']],
  justification: 'This lesson helps us to understand the final stage of vegetation and how man changes it.',
  activities: [
    { sec: 'I. MEANING', img: 'climax_big.png', caption: 'Climatic climax and plagioclimax.', q: 'What is climax vegetation?', a: 'The final, stable plant community in balance with the environment.', noProj: 'draw the diagram.' },
    { sec: 'II. CLIMATIC CLIMAX', img: 'f2t_rainforest.jpg', caption: 'The equatorial rainforest.', q: 'Why is the rainforest called a climatic climax?', a: 'It is the stable vegetation that the hot, wet climate allows.', noProj: 'name climax forests of the world.' },
    { sec: 'III. PLAGIOCLIMAX', img: 'f2t_savanna.jpg', caption: 'A savanna with scattered trees.', q: 'Why do some scientists say that many savannas are not true climaxes?', a: 'They are kept by fire and grazing; without them trees would grow.', noProj: 'discuss the debate.' },
    { sec: 'III. PLAGIOCLIMAX', img: 'f2t_cattle.jpg', caption: 'Cattle grazing.', q: 'How does grazing keep grassland?', a: 'Animals eat young trees and trample seedlings.', noProj: 'describe grazing on the Adamawa.' },
    { sec: 'IV. THE DEBATE', img: 'f2t_prairie.jpg', caption: 'A temperate grassland (prairie).', q: 'Give one argument that some grasslands are climatic climaxes.', a: 'Where rain is too low for trees, grass is the natural final vegetation.', noProj: 'compare prairie and savanna.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Climax vegetation:', 'It is the final, stable plant community of a succession.'], ['Plagioclimax:', 'It is vegetation kept below its climax by human action.'], ['Edaphic climax:', 'It is a climax controlled by soil conditions.']] },
    { title: 'II. Views and Types', items: [['A. Monoclimax view (Clements):', 'In one climate zone there is only one climax, set by climate. All successions end in it.'], ['B. Polyclimax view (Tansley):', 'There can be several climaxes in one zone. Soil, relief and fire also control the climax.'], ['C. Types:', 'There are climatic, edaphic, topographic and fire climaxes. A plagioclimax is caused by man.']] },
    { title: 'III. The Grassland Debate', items: [['A. Climatic view:', 'Some grasslands grow where rain is too low for trees. Here grass is a true climax.'], ['B. Plagioclimax view:', 'Many savannas are kept by fire, grazing and farming. Without them, woodland or forest would grow.'], ['C. Conclusion:', 'Most tropical savannas are influenced by both climate and man. Protecting them from fire can bring back trees.']], draw: { img: 'climax_big.png', caption: 'Copy the diagram.' } },
  ],
  evaluation: [['Distinguish monoclimax and polyclimax views.', 'Monoclimax: one climax set by climate; polyclimax: several climaxes set by climate, soil, relief and fire.'], ['What is a plagioclimax? Give an example.', 'Vegetation kept below its climax by man; savanna kept by fire.']],
  remediation: ['The final stable stage is the ______.', 'The view of one climax per climate is ______.', 'Vegetation kept by man is a ______.'], remediationAnswers: '1. climax 2. monoclimax 3. plagioclimax',
  homework: 'Write a short paragraph: "Is the savanna of Cameroon a climax?"', homeworkTag: 'This prepares Lesson 15: Examples of Plant Succession.',
  bilingual: [['Climax', 'Le climax'], ['Grassland', 'La prairie, la savane'], ['Debate', 'Le débat'], ['Grazing', 'Le pâturage'], ['Fire', 'Le feu'], ['Stable', 'Stable']],
});

L.push({ no: 15, title: 'Examples of Plant Succession', topic: V1, subtopic: 'Development of Vegetation',
  notions: 'Primary succession, lithosere, hydrosere, secondary succession, fallow, secondary forest.', focus: 'Primary succession (lithosere, hydrosere) and secondary succession (fallow, cleared forest).',
  competence: 'Learners are able to describe examples of primary and secondary succession.',
  objectives: ['Describe a lithosere on lava.', 'Describe a hydrosere in a pond.', 'Describe secondary succession on abandoned farmland.'],
  recall: ['Succession has stages from pioneers to climax.', 'Primary succession starts without soil.'],
  situation: 'On Mount Cameroon, ferns now grow on lava from 1999, while an abandoned cassava farm nearby is already covered with bushes and young trees.',
  sitQA: [['What is the problem in the situation?', 'Plants return at different speeds.'], ['Which is primary succession?', 'The lava flow, because it had no soil.'], ['Why is the farm faster?', 'Soil and seeds were still there: secondary succession.']],
  justification: 'This lesson helps us to recognise real successions around us and use them in farming and conservation.',
  activities: [
    { sec: 'I. LITHOSERE', img: 'lsa_fernlava.jpg', caption: 'A fern growing on lava.', q: 'Why can ferns grow here before trees?', a: 'They need little soil and grow in cracks where water and dust collect.', noProj: 'describe the 1999 and 2000 lava flows.' },
    { sec: 'I. LITHOSERE', img: 'lsa_moss.jpg', caption: 'Moss growing in a rock crack.', q: 'What do mosses do for later plants?', a: 'They trap dust and water and add humus: they start the soil.', noProj: 'look for moss on old walls.' },
    { sec: 'II. HYDROSERE', img: 'lsa_pond.jpg', caption: 'A pond with water lilies.', q: 'What will this pond become after a long time?', a: 'A swamp, then dry land with woodland.', noProj: 'describe ponds that dried up.' },
    { sec: 'III. SECONDARY SUCCESSION', img: 'lsa_regrowth.jpg', caption: 'Young shrubs and trees growing back on cleared land.', q: 'Why is secondary succession faster than primary?', a: 'Soil, roots and seeds are already there.', noProj: 'describe a fallow farm.' },
    { sec: 'III. SECONDARY SUCCESSION', img: 'f2t_logging_truck.jpg', caption: 'Logs from a cleared forest.', q: 'Is the forest that grows back the same as the original?', a: 'No. It is a secondary forest with different, faster-growing species.', noProj: 'discuss logging in the East.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Lithosere:', 'It is a primary succession that starts on bare rock or lava.'], ['Hydrosere:', 'It is a succession that starts in fresh water.'], ['Secondary forest:', 'It is forest that grows back after the first forest was cleared.']] },
    { title: 'II. Primary Succession', items: [['A. Lithosere:', 'Lichens and mosses colonise bare rock and make thin soil. Ferns and grasses, then shrubs and trees follow.'], ['B. Example:', 'On Mount Cameroon lava flows, ferns and mosses appear first. Forest takes hundreds of years to return.'], ['C. Hydrosere:', 'Water plants grow and mud collects in a pond. Reeds, then swamp trees and dry woodland replace them.']] },
    { title: 'III. Secondary Succession', items: [['A. On fallow land:', 'Grasses and weeds come first, then bushes and fast-growing trees. After many years, forest may return.'], ['B. After logging:', 'Light-loving trees like umbrella trees grow first. The secondary forest is poorer than the original.'], ['C. Use in farming:', 'Bush fallow uses secondary succession to restore soil fertility. Short fallows do not give enough time.']] },
  ],
  evaluation: [['Describe the stages of a lithosere.', 'Lichens and mosses, then ferns and grasses, then shrubs, then trees (climax).'], ['Why is secondary succession faster?', 'Soil, roots and seeds are already present.']],
  remediation: ['A succession on lava is a ______.', 'A succession in a pond is a ______.', 'Forest that grows back after clearing is ______ forest.'], remediationAnswers: '1. lithosere 2. hydrosere 3. secondary',
  homework: 'Describe the plants on a fallow field near you and say which stage it has reached.', homeworkTag: 'This prepares Lesson 16: Spatial Distribution of Vegetation.',
  bilingual: [['Lava', 'La lave'], ['Moss', 'La mousse'], ['Fern', 'La fougère'], ['Swamp', 'Le marécage'], ['Fallow', 'La jachère'], ['Regrowth', 'La repousse']],
});

L.push({ no: 16, title: 'Spatial Distribution of Vegetation', topic: V1, subtopic: 'Development of Vegetation',
  notions: 'Horizontal distribution, vegetation formation, zonation, vertical distribution, altitudinal zone.', focus: 'Horizontal distribution (world formations); factors of distribution; vertical distribution on mountains.',
  competence: 'Learners are able to describe and explain the distribution of vegetation across the world and on mountains.',
  objectives: ['Describe the horizontal distribution of vegetation formations.', 'Explain the factors of vegetation distribution.', 'Describe the vertical distribution of vegetation.'],
  recall: ['Temperature falls with altitude.', 'Rainfall decreases from the Equator to the tropics.'],
  situation: 'Climbing Mount Cameroon from Buea, hikers pass through farms and forest, then mossy forest, then grassland, and finally bare lava near the summit.',
  sitQA: [['What is the problem in the situation?', 'Vegetation changes with height on the mountain.'], ['What causes these changes?', 'Temperature and rainfall change with altitude.'], ['What is this pattern called?', 'Vertical (altitudinal) zonation.']],
  justification: 'This lesson helps us to understand where vegetation types are found and why.',
  activities: [
    { sec: 'I. HORIZONTAL DISTRIBUTION', img: 'africa_vegetation_big.png', caption: 'The vegetation of Africa.', q: 'Describe the order of vegetation from the Equator to the Sahara.', a: 'Rainforest, then savanna, then semi-desert and desert.', noProj: 'draw bands on a map of Africa.' },
    { sec: 'I. HORIZONTAL DISTRIBUTION', img: 'biomes_map_big.png', caption: 'The main vegetation zones of the world (simplified).', q: 'Which formation is found just south of the Arctic tundra?', a: 'The taiga (coniferous forest).', noProj: 'list zones from Equator to pole.' },
    { sec: 'II. FACTORS', img: 'lsa_oilpalm.jpg', caption: 'Forest replaced by an oil palm plantation.', q: 'Give three factors of vegetation distribution.', a: 'Climate, soil and relief (also man and animals).', noProj: 'list natural and human factors.' },
    { sec: 'III. VERTICAL DISTRIBUTION', img: 'veg_altitude_big.png', caption: 'Vegetation zones on Mount Cameroon.', q: 'Why does forest give way to grassland near 2,400 m?', a: 'It becomes too cold and windy for trees.', noProj: 'draw the zones.' },
    { sec: 'III. VERTICAL DISTRIBUTION', img: 'lsa_mtcameroon.jpg', caption: 'Mount Cameroon.', q: 'Why is vertical zonation like a journey from the Equator to the poles?', a: 'Temperature falls with height as it falls with latitude.', noProj: 'compare the mountain with the globe.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Horizontal distribution:', 'It is the pattern of vegetation zones across latitudes.'], ['Vertical distribution:', 'It is the change of vegetation with altitude.'], ['Treeline:', 'It is the highest altitude or latitude where trees can grow.']] },
    { title: 'II. Horizontal Distribution and Factors', items: [['A. Pattern:', 'Rainforest lies near the Equator, then savanna and desert towards the tropics. Temperate forests and grasslands, taiga and tundra follow towards the poles.'], ['B. Climatic factors:', 'Temperature and rainfall are the main factors. Light and wind also matter.'], ['C. Other factors:', 'Soil, relief and drainage change vegetation locally. Man changes it by farming, fire and plantations.']] },
    { title: 'III. Vertical Distribution', items: [['A. Cause:', 'Temperature falls with height, and rain and wind change. Vegetation changes in belts up the mountain.'], ['B. Mount Cameroon:', 'Lowland forest grows below 800 m, then submontane and montane forest. Montane grassland lies above 2,400 m and bare lava near the top.'], ['C. Comparison:', 'Climbing a mountain is like travelling towards the poles. Each belt matches a latitude zone.']], draw: { img: 'veg_altitude_big.png', caption: 'Copy the vegetation zones.' } },
  ],
  evaluation: [['Describe the horizontal distribution of vegetation in Africa.', 'Rainforest at the Equator, then savanna, then semi-desert and desert towards the tropics.'], ['Why does vegetation change with altitude?', 'Temperature falls with height and rain and wind change.']],
  remediation: ['Vegetation zones across latitudes form a ______ distribution.', 'The highest place where trees grow is the ______.', 'Above 2,400 m on Mount Cameroon there is montane ______.'], remediationAnswers: '1. horizontal 2. treeline 3. grassland',
  homework: 'Draw the vegetation belts of Mount Cameroon with their heights.', homeworkTag: 'This prepares Further Study 2: Vegetation of Cameroon.',
  bilingual: [['Distribution', 'La répartition'], ['Zone', 'La zone'], ['Altitude', "L'altitude"], ['Treeline', 'La limite des arbres'], ['Taiga', 'La taïga'], ['Tundra', 'La toundra']],
});

L.push({ kind: 'Further Study', no: 2, title: 'Vegetation of Cameroon', topic: S3, subtopic: 'Vegetation Types and their Characteristics',
  notions: 'Mangrove, rainforest, montane forest, Guinea savanna, Sudan savanna, Sahel, forest reserve, plantation.', focus: 'Forest types (mangrove, rainforest, montane, submontane); grassland types (Guinea, Sudan, Sahel); planted vegetation; forest reserves; distribution, species, exploitation, threats and measures.',
  competence: 'Learners are able to locate and describe the vegetation types of Cameroon and propose ways to protect them.',
  objectives: ['Locate the vegetation types of Cameroon on a map.', 'Describe the forest and grassland types.', 'Explain their exploitation, threats and protection measures.'],
  recall: ['Vegetation changes from forest to desert away from the Equator.', 'Cameroon has equatorial and tropical climates.'],
  situation: 'Cameroon is called "Africa in miniature" because a traveller can see mangroves, rainforest, mountain grassland, savanna and Sahel landscapes in one country.',
  sitQA: [['What is the problem in the situation?', 'Learners want to know the vegetation types of Cameroon.'], ['Why is there so much variety?', 'Cameroon stretches from 2°N to 13°N and has high mountains.'], ['What threatens this vegetation?', 'Logging, farming, bush fires and overgrazing.']],
  justification: 'This further study helps us to know and protect the vegetation of our country.',
  activities: [
    { sec: 'I. DISTRIBUTION', img: 'cameroon_veg_big.png', caption: 'Vegetation of Cameroon (simplified).', q: 'Which vegetation covers the south and east?', a: 'Dense rainforest.', noProj: 'draw the vegetation map.' },
    { sec: 'II. FORESTS', img: 'lsa_mangrove.jpg', caption: 'A mangrove forest.', q: 'Where are mangroves found in Cameroon? Why are they important?', a: 'On the coast (Douala, Rio del Rey); they protect coasts and are fish nurseries.', noProj: 'find the Wouri estuary.' },
    { sec: 'II. FORESTS', img: 'f2t_rainforest.jpg', caption: 'Dense tropical rainforest.', q: 'Give two uses and one threat of the rainforest.', a: 'Timber and non-timber products; threat: logging and farming.', noProj: 'name reserves: Dja, Korup, Lobéké.' },
    { sec: 'III. GRASSLANDS', img: 'f2t_savanna.jpg', caption: 'Savanna with scattered trees.', q: 'Name the three savanna types from south to north.', a: 'Guinea savanna, Sudan savanna and Sahel savanna.', noProj: 'describe the Adamawa grasslands.' },
    { sec: 'IV. PLANTED VEGETATION', img: 'lsa_oilpalm.jpg', caption: 'An oil palm plantation.', q: 'Give two examples of man-planted vegetation in Cameroon.', a: 'Oil palm, cocoa, tea, rubber and eucalyptus plantations.', noProj: 'mention CDC and SOCAPALM.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Mangrove:', 'It is a forest of salt-tolerant trees on muddy tropical coasts.'], ['Forest reserve:', 'It is a protected forest where cutting and hunting are controlled.'], ['Savanna:', 'It is a tropical grassland with scattered trees.']] },
    { title: 'II. Forest Types', items: [['A. Mangrove:', 'It grows on the coast around Douala and Rio del Rey. It is threatened by fuelwood cutting and urban growth.'], ['B. Dense rainforest:', 'It covers the south and east, with trees like sapele, iroko and ayous. It gives timber but is threatened by logging and farming.'], ['C. Montane and submontane forest:', 'They grow on Mount Cameroon and the Western Highlands. They are rich in rare species but cleared for farms.']] },
    { title: 'III. Grasslands, Planted Vegetation and Protection', items: [['A. Savannas:', 'Guinea savanna covers the Adamawa, Sudan savanna the North and Sahel savanna the Far North. They are used for grazing and threatened by fire and overgrazing.'], ['B. Planted vegetation:', 'Plantations of oil palm, rubber, tea and banana replace natural forest. Eucalyptus is planted for wood in the highlands.'], ['C. Measures:', 'Cameroon has reserves and parks like Dja, Korup and Waza. Reforestation, controlled logging and fire control protect vegetation.']], draw: { img: 'cameroon_veg_big.png', caption: 'Copy the map.' } },
  ],
  evaluation: [['Name the forest types and grassland types of Cameroon.', 'Forests: mangrove, rainforest, montane. Grasslands: Guinea, Sudan and Sahel savannas.'], ['Give three measures to protect vegetation.', 'Forest reserves, reforestation, controlled logging (also fire control).']],
  remediation: ['Salt-tolerant forests on the coast are ______.', 'The savanna of the Adamawa is ______ savanna.', 'Dja and Korup are forest ______.'], remediationAnswers: '1. mangroves 2. Guinea 3. reserves',
  homework: 'Draw the vegetation map of Cameroon and write one threat for each type.', homeworkTag: 'This prepares Lesson 17: Meaning of Ecology and Ecosystems.',
  bilingual: [['Mangrove', 'La mangrove'], ['Rainforest', 'La forêt dense humide'], ['Savanna', 'La savane'], ['Reserve', 'La réserve'], ['Logging', "L'exploitation forestière"], ['Reforestation', 'Le reboisement']],
});

L.push({ no: 17, title: 'Meaning of Ecology and Ecosystems', topic: E1, subtopic: 'Basic Concepts',
  notions: 'Ecology, ecosystem, biotic, abiotic, producer, consumer, decomposer, habitat.', focus: 'Definition of ecology and ecosystems; components; characteristics.',
  competence: 'Learners are able to define an ecosystem and identify its components and characteristics.',
  objectives: ['Define ecology and ecosystem.', 'Identify the abiotic and biotic components.', 'Describe the characteristics of ecosystems.'],
  recall: ['Plants need sunlight, water and nutrients.', 'Decomposers break down dead matter.'],
  situation: 'In Waza National Park, a guide explains that if lions disappear, antelopes increase, eat all the grass and then die of hunger. Everything is linked.',
  sitQA: [['What is the problem in the situation?', 'Living things depend on each other and on their environment.'], ['What is such a linked community called?', 'An ecosystem.'], ['Name the non-living parts.', 'Sunlight, water, air, soil and nutrients.']],
  justification: 'This lesson introduces ecosystems, the units in which living things and their environment work together.',
  activities: [
    { sec: 'I. COMPONENTS', img: 'ecosystem_components_big.png', caption: 'Abiotic and biotic components.', q: 'Name two abiotic and two biotic components of an ecosystem.', a: 'Abiotic: sunlight, water. Biotic: plants, animals.', noProj: 'list things in the school garden.' },
    { sec: 'II. TERRESTRIAL ECOSYSTEM', img: 'f2t_savanna.jpg', caption: 'The savanna: a land ecosystem.', q: 'What are the producers in the savanna?', a: 'Grasses and trees.', noProj: 'describe the savanna.' },
    { sec: 'II. AQUATIC ECOSYSTEM', img: 'lsa_pond.jpg', caption: 'A pond: a water ecosystem.', q: 'Name one producer and one consumer in a pond.', a: 'Producer: water lilies or algae. Consumer: fish or frogs.', noProj: 'describe a local pond.' },
    { sec: 'III. BIOTIC ROLES', img: 'lsa_zebra.jpg', caption: 'Zebras grazing.', q: 'What is the role of the zebra in the ecosystem?', a: 'It is a consumer (herbivore) that eats plants.', noProj: 'name herbivores of Cameroon.' },
    { sec: 'III. BIOTIC ROLES', img: 'lsa_fungi.jpg', caption: 'A fungus on dead wood.', q: 'What would happen without decomposers?', a: 'Dead matter would pile up and nutrients would not return to the soil.', noProj: 'describe rotting leaves.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Ecology:', 'It is the study of living things and their relationships with the environment.'], ['Ecosystem:', 'It is a community of living things interacting with their non-living environment.'], ['Habitat:', 'It is the place where an organism lives.']] },
    { title: 'II. Components', items: [['A. Abiotic components:', 'They are the non-living parts: sunlight, heat, water, air, soil and nutrients. They control which organisms can live there.'], ['B. Producers:', 'Green plants make food by photosynthesis. They are the base of the ecosystem.'], ['C. Consumers and decomposers:', 'Consumers are animals that eat plants or other animals. Decomposers break down dead matter and recycle nutrients.']] },
    { title: 'III. Characteristics', items: [['A. Size:', 'Ecosystems can be small, like a pond, or huge, like a rainforest. The largest are called biomes.'], ['B. Interdependence:', 'All parts depend on each other. A change in one part affects the others.'], ['C. Open systems:', 'Energy and matter enter and leave. Ecosystems tend towards a balance (equilibrium).']], draw: { img: 'ecosystem_components_big.png', caption: 'Copy the components.' } },
  ],
  evaluation: [['Define an ecosystem.', 'A community of living things interacting with their non-living environment.'], ['Distinguish producers, consumers and decomposers.', 'Producers make food; consumers eat others; decomposers break down dead matter.']],
  remediation: ['The study of organisms and their environment is ______.', 'Green plants are ______.', 'Fungi and bacteria are ______.'], remediationAnswers: '1. ecology 2. producers 3. decomposers',
  homework: 'List the producers, consumers and decomposers in your compound.', homeworkTag: 'This prepares Lesson 18: The Ecosystem as a System.',
  bilingual: [['Ecology', "L'écologie"], ['Ecosystem', "L'écosystème"], ['Producer', 'Le producteur'], ['Consumer', 'Le consommateur'], ['Decomposer', 'Le décomposeur'], ['Habitat', "L'habitat"]],
});

L.push({ no: 18, title: 'The Ecosystem as a System', topic: E1, subtopic: 'The Structure of an Ecosystem',
  notions: 'Input, output, store, process, photosynthesis, respiration, decomposition, feedback.', focus: 'Inputs, outputs and processes of an ecosystem and the interactions between them.',
  competence: 'Learners are able to describe an ecosystem as an open system with inputs, stores, processes and outputs.',
  objectives: ['Identify the inputs and outputs of an ecosystem.', 'Explain the main processes (photosynthesis, feeding, decomposition).', 'Explain the interactions between inputs, processes and outputs.'],
  recall: ['An ecosystem has abiotic and biotic parts.', 'A drainage basin is an open system.'],
  situation: 'After a forest near Bertoua is cleared, the river becomes muddy and the soil loses its fertility within a few years. The learners ask why removing trees changes the whole system.',
  sitQA: [['What is the problem in the situation?', 'Clearing the forest changed soil and water.'], ['Why did the river become muddy?', 'Without trees, rain erodes the soil (a new output).'], ['Why did fertility fall?', 'Litter input stopped and nutrients were leached.']],
  justification: 'This lesson helps us to see ecosystems as systems where a change in one part affects the whole.',
  activities: [
    { sec: 'I. THE SYSTEM', img: 'ecosystem_system_big.png', caption: 'The ecosystem as an open system.', q: 'Name two inputs and two outputs of an ecosystem.', a: 'Inputs: sun energy, rain (also CO₂, nutrients). Outputs: heat, leaching (also O₂, erosion).', noProj: 'draw three boxes.' },
    { sec: 'II. PROCESSES', img: 'f2t_rainforest.jpg', caption: 'A forest: a large store of biomass.', q: 'Which process makes food and stores energy in plants?', a: 'Photosynthesis.', noProj: 'write the photosynthesis equation in words.' },
    { sec: 'II. PROCESSES', img: 'lsa_litter.jpg', caption: 'Litter being broken down on the soil.', q: 'Which process returns nutrients to the soil?', a: 'Decomposition.', noProj: 'describe rotting leaves.' },
    { sec: 'III. INTERACTIONS', img: 'lsa_lion.jpg', caption: 'A lioness stalking zebras.', q: 'How is feeding a process that moves energy?', a: 'Energy passes from the eaten to the eater.', noProj: 'describe a food chain.' },
    { sec: 'III. INTERACTIONS', img: 'f4_gully.jpg', caption: 'A gully on bare land.', q: 'How does removing vegetation change the outputs of the ecosystem?', a: 'Runoff, erosion and leaching increase.', noProj: 'describe bare land after clearing.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Input:', 'It is energy or matter that enters an ecosystem.'], ['Output:', 'It is energy or matter that leaves an ecosystem.'], ['Store:', 'It is where matter is kept, like biomass, litter or soil.']] },
    { title: 'II. Inputs, Stores and Outputs', items: [['A. Inputs:', 'Sun energy, rain, carbon dioxide and nutrients from rock enter the system. Animals and seeds can also arrive.'], ['B. Stores:', 'Nutrients and energy are stored in biomass, litter and soil. The size of each store differs between ecosystems.'], ['C. Outputs:', 'Heat, oxygen and water vapour leave the system. Nutrients are lost by leaching, erosion and harvesting.']] },
    { title: 'III. Processes and Interactions', items: [['A. Processes:', 'Photosynthesis makes food, feeding passes it on and respiration uses it. Decomposition returns nutrients to the soil.'], ['B. Interactions:', 'A change in one input changes processes and outputs. For example, less rain means less growth and less litter.'], ['C. Human effect:', 'Clearing, burning and farming change inputs and outputs. They can upset the balance of the ecosystem.']], draw: { img: 'ecosystem_system_big.png', caption: 'Copy the system.' } },
  ],
  evaluation: [['Name two processes of an ecosystem.', 'Photosynthesis and decomposition (also feeding, respiration).'], ['How does deforestation change ecosystem outputs?', 'Runoff, erosion and leaching increase.']],
  remediation: ['Sun energy is an ______ to the ecosystem.', 'Dead matter is broken down by ______.', 'Loss of nutrients in water is ______.'], remediationAnswers: '1. input 2. decomposition 3. leaching',
  homework: 'Draw the ecosystem of a farm as a system with inputs, stores and outputs.', homeworkTag: 'This prepares Lesson 19: Examples of Ecosystems.',
  bilingual: [['Input', "L'entrée (intrant)"], ['Output', 'La sortie'], ['Store', 'Le stock'], ['Respiration', 'La respiration'], ['Decomposition', 'La décomposition'], ['Balance', "L'équilibre"]],
});

L.push({ no: 19, title: 'Examples of Ecosystems: The Pond', topic: E1, subtopic: 'The Structure of an Ecosystem',
  notions: 'Aquatic ecosystem, pond, algae, plankton, producer, consumer, decomposer, food chain.', focus: 'Example of an aquatic ecosystem (pond): components, characteristics and functioning as a system.',
  competence: 'Learners are able to describe a pond as an ecosystem with its components and processes.',
  objectives: ['Identify the abiotic and biotic components of a pond.', 'Describe a pond food chain.', 'Show the pond as a system.'],
  recall: ['An ecosystem has producers, consumers and decomposers.', 'Ecosystems are open systems.'],
  situation: 'A fish farmer near Foumban notices that when he adds too much animal waste to his pond, the water turns green and the fish die.',
  sitQA: [['What is the problem in the situation?', 'The pond ecosystem was upset and fish died.'], ['What made the water green?', 'Too many nutrients made algae grow fast.'], ['Why did the fish die?', 'Rotting algae used up the oxygen.']],
  justification: 'This lesson helps us to study a small ecosystem that we can observe near us.',
  activities: [
    { sec: 'I. COMPONENTS', img: 'pond_big.png', caption: 'The pond ecosystem.', q: 'Name the producers, consumers and decomposers of the pond.', a: 'Producers: algae, water lilies. Consumers: fish, frogs. Decomposers: bacteria.', noProj: 'draw the pond.' },
    { sec: 'I. COMPONENTS', img: 'lsa_waterlily.jpg', caption: 'Water lilies on a pond.', q: 'Why are water lilies producers?', a: 'They make food by photosynthesis.', noProj: 'look at water plants.' },
    { sec: 'II. FOOD CHAIN', img: 'f2t_fishing.jpg', caption: 'Fishermen on the water.', q: 'Give a pond food chain ending with man.', a: 'Algae → small animals (zooplankton) → fish → man.', noProj: 'write the chain on the board.' },
    { sec: 'III. AS A SYSTEM', img: 'lsa_pond.jpg', caption: 'A garden pond.', q: 'Name two inputs of the pond system.', a: 'Sunlight and nutrients (also rain water, leaves).', noProj: 'list inputs and outputs.' },
    { sec: 'III. COMPARISON', img: 'f2t_savanna.jpg', caption: 'The savanna, a land ecosystem.', q: 'Give one difference between a pond and a savanna ecosystem.', a: 'The pond is in water; its producers are mainly algae, not grass.', noProj: 'compare the two.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Aquatic ecosystem:', 'It is an ecosystem in water, such as a pond, river or lake.'], ['Algae:', 'They are simple water plants that make food by photosynthesis.'], ['Eutrophication:', 'It is the too-rapid growth of algae caused by excess nutrients.']] },
    { title: 'II. Components of a Pond', items: [['A. Abiotic:', 'Water, sunlight, dissolved oxygen, mud and nutrients. Temperature and light change with depth.'], ['B. Producers and consumers:', 'Algae, water lilies and reeds are producers. Insects, fish and frogs are consumers.'], ['C. Decomposers:', 'Bacteria and fungi live in the mud. They break down dead matter and release nutrients.']] },
    { title: 'III. The Pond as a System', items: [['A. Inputs and outputs:', 'Sunlight, rain, leaves and nutrients enter the pond. Water evaporates, and fish are removed by man.'], ['B. Food chain:', 'Algae are eaten by small animals, which are eaten by fish. Fish are eaten by birds or man.'], ['C. Disturbance:', 'Too many nutrients cause eutrophication. Oxygen falls and fish die.']], draw: { img: 'pond_big.png', caption: 'Copy the pond ecosystem.' } },
  ],
  evaluation: [['Name one producer, one consumer and one decomposer of a pond.', 'Algae; fish; bacteria.'], ['What is eutrophication?', 'Rapid algae growth from excess nutrients, which reduces oxygen.']],
  remediation: ['Simple water plants are ______.', 'Bacteria in the mud are ______.', 'Excess nutrients cause ______.'], remediationAnswers: '1. algae 2. decomposers 3. eutrophication',
  homework: 'Observe a pond or stream and list what lives in it.', homeworkTag: 'This prepares Lesson 20: Interactions within Ecosystems.',
  bilingual: [['Pond', "L'étang"], ['Algae', 'Les algues'], ['Fish', 'Le poisson'], ['Food chain', 'La chaîne alimentaire'], ['Oxygen', "L'oxygène"], ['Mud', 'La vase']],
});

L.push({ no: 20, title: 'Interactions within Ecosystems', topic: E1, subtopic: 'The Structure of an Ecosystem',
  notions: 'Compartment, four-compartment model, equilibrium, dynamic equilibrium, disequilibrium, feedback.', focus: 'Structure with four compartments; interrelations; equilibrium and its nature; factors of disequilibrium, notably man.',
  competence: 'Learners are able to explain the equilibrium of ecosystems and how man can upset it.',
  objectives: ['Describe the four compartments of an ecosystem.', 'Explain the interrelations and the equilibrium between them.', 'Explain the factors of disequilibrium, especially man.'],
  recall: ['An ecosystem is an open system.', 'Nutrients move between biomass, litter and soil.'],
  situation: 'For many years, farmers around Garoua cleared land, burned bush and kept large herds. Now the soils are poor, the grass is thin and the rains wash the soil away.',
  sitQA: [['What is the problem in the situation?', 'The ecosystem has lost its balance.'], ['What caused this?', 'Human activities: clearing, burning and overgrazing.'], ['What do we call the balance of an ecosystem?', 'Equilibrium.']],
  justification: 'This lesson helps us to understand the balance of nature and our role in keeping it.',
  activities: [
    { sec: 'I. COMPARTMENTS', img: 'equilibrium_big.png', caption: 'The four compartments of an ecosystem.', q: 'Name the four compartments.', a: 'Atmosphere, biomass, litter and soil.', noProj: 'draw four boxes with arrows.' },
    { sec: 'II. INTERRELATIONS', img: 'gersmehl_big.png', caption: 'Nutrients moving between biomass, litter and soil.', q: 'How do nutrients move from biomass to litter to soil?', a: 'Leaves fall (fallout), then decompose into the soil.', noProj: 'describe the cycle.' },
    { sec: 'III. EQUILIBRIUM', img: 'lsa_litter.jpg', caption: 'Litter on the forest floor.', q: 'Why is the equilibrium called dynamic?', a: 'Matter keeps moving, but inputs and outputs stay balanced.', noProj: 'compare with a full bucket with a tap and a hole.' },
    { sec: 'IV. DISEQUILIBRIUM', img: 'f2t_logging_truck.jpg', caption: 'Logs from a cleared forest.', q: 'How does logging upset the equilibrium?', a: 'It removes biomass and nutrients and exposes the soil to erosion.', noProj: 'discuss logging.' },
    { sec: 'IV. DISEQUILIBRIUM', img: 'overgrazing_big.png', caption: 'Overgrazing leaves bare soil.', q: 'Give two human factors of disequilibrium.', a: 'Overgrazing and bush fires (also logging, pollution).', noProj: 'describe bare grazing land.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Compartment:', 'It is a store in an ecosystem, such as biomass or soil.'], ['Equilibrium:', 'It is the balance between the parts of an ecosystem.'], ['Disequilibrium:', 'It is the loss of balance in an ecosystem.']] },
    { title: 'II. Structure and Interrelations', items: [['A. Four compartments:', 'The atmosphere, biomass, litter and soil store energy and matter. They are linked by flows.'], ['B. Flows:', 'Plants take carbon dioxide from the air and nutrients from the soil. Litter falls, decomposes and returns nutrients.'], ['C. Feedback:', 'A change in one compartment affects the others. Negative feedback helps to restore balance.']] },
    { title: 'III. Equilibrium and Disequilibrium', items: [['A. Dynamic equilibrium:', 'Matter and energy keep moving, but the stores stay about the same. The ecosystem can recover from small changes.'], ['B. Natural factors:', 'Droughts, floods and volcanic eruptions can upset the balance. Most ecosystems recover with time.'], ['C. Man:', 'Logging, fire, overgrazing and pollution cause serious disequilibrium. Soils lose fertility, and species disappear.']], draw: { img: 'equilibrium_big.png', caption: 'Copy the four compartments.' } },
  ],
  evaluation: [['Name the four compartments of an ecosystem.', 'Atmosphere, biomass, litter and soil.'], ['Explain how man causes disequilibrium.', 'Logging, fire, overgrazing and pollution remove stores and increase losses.']],
  remediation: ['Balance in an ecosystem is ______.', 'A store in an ecosystem is a ______.', 'Overgrazing causes ______.'], remediationAnswers: '1. equilibrium 2. compartment 3. disequilibrium',
  homework: 'Give an example of an ecosystem in your area that has lost its balance and explain why.', homeworkTag: 'This prepares Lesson 21: Energy Flows.',
  bilingual: [['Compartment', 'Le compartiment'], ['Equilibrium', "L'équilibre"], ['Feedback', 'La rétroaction'], ['Overgrazing', 'Le surpâturage'], ['Pollution', 'La pollution'], ['Recovery', 'Le rétablissement']],
});

L.push({ no: 21, title: 'Energy Flows in Ecosystems', topic: E1, subtopic: 'The Functioning of Ecosystems',
  notions: 'Energy flow, photosynthesis, respiration, first law of thermodynamics, second law of thermodynamics, 10 % rule.', focus: 'Sources of energy in the ecosystem; the two energy laws analysed.',
  competence: 'Learners are able to explain how energy enters and flows through ecosystems using the two energy laws.',
  objectives: ['Identify the source of energy in ecosystems.', 'Explain the first and second laws of energy.', 'Explain why energy decreases along a food chain.'],
  recall: ['Plants make food by photosynthesis.', 'Animals eat plants or other animals.'],
  situation: 'A herder feeds his cattle on grass. A learner calculates that the cattle use most of the energy in the grass to walk and keep warm, and very little becomes meat.',
  sitQA: [['What is the problem in the situation?', 'Much energy is lost between grass and meat.'], ['Where does the energy go?', 'It is lost as heat through respiration and movement.'], ['Where does the energy of grass come from?', 'From the Sun.']],
  justification: 'This lesson helps us to understand why energy flows in one direction and why food chains are short.',
  activities: [
    { sec: 'I. SOURCE OF ENERGY', img: 'lsa_sun.jpg', caption: 'The Sun, source of all energy in ecosystems.', q: 'How does solar energy enter the ecosystem?', a: 'Through photosynthesis by green plants.', noProj: 'explain why plants need light.' },
    { sec: 'I. SOURCE OF ENERGY', img: 'veg_system_big.png', caption: 'Photosynthesis.', q: 'Into what form is solar energy changed by plants?', a: 'Chemical energy stored in food (sugars).', noProj: 'write the equation in words.' },
    { sec: 'II. ENERGY FLOW', img: 'energy_flow_big.png', caption: 'Energy flow along a food chain.', q: 'If grass has 10,000 units, how much reaches the lion?', a: 'About 100 units (10 % at each step).', noProj: 'do the calculation.' },
    { sec: 'III. THE ENERGY LAWS', img: 'lsa_zebra.jpg', caption: 'Zebras grazing.', q: 'Why does the zebra keep only a small part of the grass energy?', a: 'It loses most as heat when it moves and breathes (second law).', noProj: 'feel body heat after running.' },
    { sec: 'III. THE ENERGY LAWS', img: 'lsa_lion.jpg', caption: 'A lioness stalking zebras.', q: 'Why are there few lions and many zebras?', a: 'Little energy is left at the top of the chain.', noProj: 'compare numbers in a park.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Energy flow:', 'It is the movement of energy through an ecosystem.'], ['First law of thermodynamics:', 'It says that energy cannot be created or destroyed, only changed.'], ['Second law of thermodynamics:', 'It says that each change of energy loses some as heat.']] },
    { title: 'II. Sources of Energy', items: [['A. The Sun:', 'Nearly all energy in ecosystems comes from sunlight. Plants use only about 1 % of it.'], ['B. Photosynthesis:', 'Plants change light energy into chemical energy in food. This is the entry point of energy.'], ['C. Other sources:', 'Some bacteria use chemical energy from rocks or hot springs. This is rare.']] },
    { title: 'III. The Two Energy Laws', items: [['A. First law:', 'Energy is changed from light to chemical energy and then to heat. The total amount stays the same.'], ['B. Second law:', 'At each step energy is lost as heat by respiration and movement. Only about 10 % passes to the next level.'], ['C. Consequences:', 'Energy flows in one direction and is not recycled. Food chains are short, and top carnivores are few.']], draw: { img: 'energy_flow_big.png', caption: 'Copy the energy flow.' } },
  ],
  evaluation: [['State the two energy laws.', 'First: energy is not created or destroyed, only changed. Second: each change loses some energy as heat.'], ['Why are food chains short?', 'About 90 % of energy is lost at each level.']],
  remediation: ['All energy in ecosystems comes from the ______.', 'Plants take in energy by ______.', 'At each level about ______ % of energy passes on.'], remediationAnswers: '1. Sun 2. photosynthesis 3. 10',
  homework: 'Calculate how much energy reaches a hawk if grass has 50,000 units in the chain grass → grasshopper → bird → hawk.', homeworkTag: 'This prepares Lesson 22: Trophic Levels.',
  bilingual: [['Energy', "L'énergie"], ['Heat', 'La chaleur'], ['Law', 'La loi'], ['Flow', 'Le flux'], ['Sunlight', 'La lumière solaire'], ['Respiration', 'La respiration']],
});

L.push({ no: 22, title: 'Trophic Levels, Food Chains and Food Webs', topic: E1, subtopic: 'The Functioning of Ecosystems',
  notions: 'Trophic level, herbivore, carnivore, omnivore, food chain, food web, ecological pyramid.', focus: 'Meaning and illustration of trophic levels; stepwise nature and limits; food chains and food webs.',
  competence: 'Learners are able to build food chains and food webs and explain trophic levels.',
  objectives: ['Define trophic level and name the levels.', 'Build a food chain and a food web.', 'Explain why the number of trophic levels is limited.'],
  recall: ['Energy decreases by about 90 % at each level.', 'Producers, consumers and decomposers make an ecosystem.'],
  situation: 'In the Bénoué National Park, poachers killed many lions. Rangers then saw antelopes and warthogs increase and the grass disappear in some places.',
  sitQA: [['What is the problem in the situation?', 'Removing one animal changed the whole food web.'], ['Which level did the lions occupy?', 'The top carnivore level.'], ['Why did the grass disappear?', 'More herbivores ate more grass.']],
  justification: 'This lesson helps us to understand feeding links and why protecting all species keeps ecosystems stable.',
  activities: [
    { sec: 'I. TROPHIC LEVELS', img: 'trophic_pyramid_big.png', caption: 'Trophic levels as a pyramid.', q: 'Name the trophic levels from the bottom to the top.', a: 'Producers, primary consumers, secondary consumers, tertiary consumers.', noProj: 'draw the pyramid.' },
    { sec: 'II. FOOD CHAIN', img: 'lsa_lion.jpg', caption: 'A lioness stalking zebras.', q: 'Write a food chain with the lion.', a: 'Grass → zebra → lion.', noProj: 'write chains from the savanna.' },
    { sec: 'II. FOOD WEB', img: 'food_web_big.png', caption: 'A savanna food web.', q: 'Why is a food web more stable than a single chain?', a: 'Animals have several food sources, so losing one is less serious.', noProj: 'draw arrows between animals.' },
    { sec: 'III. DECOMPOSERS', img: 'lsa_fungi.jpg', caption: 'A fungus feeding on dead wood.', q: 'Where do decomposers fit in a food web?', a: 'They feed on dead matter from all levels.', noProj: 'add decomposers to the web.' },
    { sec: 'III. LIMITS', img: 'f2t_elephants.jpg', caption: 'Elephants, large herbivores.', q: 'Why are there rarely more than four or five trophic levels?', a: 'Too little energy is left for another level.', noProj: 'recall the 10 % rule.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Trophic level:', 'It is a feeding level in an ecosystem.'], ['Food chain:', 'It is a single line showing who eats whom.'], ['Food web:', 'It is a network of linked food chains.']] },
    { title: 'II. Trophic Levels', items: [['A. Producers:', 'Green plants form the first level. They make food from sunlight.'], ['B. Consumers:', 'Herbivores are primary consumers, and carnivores are secondary or tertiary consumers. Omnivores eat at several levels.'], ['C. Stepwise nature:', 'Energy passes up one level at a time. Numbers and biomass usually decrease upwards, forming a pyramid.']] },
    { title: 'III. Food Chains and Food Webs', items: [['A. Food chains:', 'They show one path of energy, like grass → zebra → lion. They are simple but rare in nature.'], ['B. Food webs:', 'Most animals eat several foods, so chains link into webs. Webs make ecosystems more stable.'], ['C. Limits:', 'Energy loss limits chains to four or five levels. Removing a species can upset the whole web.']], draw: { img: 'food_web_big.png', caption: 'Copy the food web.' } },
  ],
  evaluation: [['Distinguish a food chain and a food web.', 'A food chain is one line of feeding; a food web is a network of linked chains.'], ['Why are trophic levels limited?', 'Energy is lost at each level, so little is left for higher levels.']],
  remediation: ['Plants are on the first ______ level.', 'Herbivores are ______ consumers.', 'A network of food chains is a food ______.'], remediationAnswers: '1. trophic 2. primary 3. web',
  homework: 'Build a food web of five animals and three plants from your area.', homeworkTag: 'This prepares Lesson 23: Nutrient Cycling.',
  bilingual: [['Trophic level', 'Le niveau trophique'], ['Herbivore', "L'herbivore"], ['Carnivore', 'Le carnivore'], ['Food web', 'Le réseau alimentaire'], ['Pyramid', 'La pyramide'], ['Prey', 'La proie']],
});

L.push({ no: 23, title: 'Nutrient Cycling and the Gersmehl Model', topic: E1, subtopic: 'The Functioning of Ecosystems',
  notions: 'Nutrient cycling, biomass, litter, soil, fallout, decomposition, uptake, Gersmehl model.', focus: 'Meaning of nutrient cycling; definition of biomass, litter and soil; the Gersmehl model.',
  competence: 'Learners are able to explain nutrient cycling with the Gersmehl model.',
  objectives: ['Define nutrient cycling, biomass and litter.', 'Describe the three stores and the flows of the Gersmehl model.', 'Explain the inputs and outputs of nutrients.'],
  recall: ['Energy flows but matter is recycled.', 'Decomposers return nutrients to the soil.'],
  situation: 'In a forest, no one adds fertiliser, yet the trees grow for centuries. On a farm, the farmer must add manure every year. The class asks why.',
  sitQA: [['What is the problem in the situation?', 'The forest keeps its nutrients while the farm loses them.'], ['How does the forest keep its nutrients?', 'They are recycled between trees, litter and soil.'], ['Why does the farm lose them?', 'Harvests remove nutrients.']],
  justification: 'This lesson helps us to understand how ecosystems recycle nutrients and why farms need care.',
  activities: [
    { sec: 'I. THE GERSMEHL MODEL', img: 'gersmehl_big.png', caption: 'The Gersmehl nutrient cycle.', q: 'Name the three stores of the Gersmehl model.', a: 'Biomass, litter and soil.', noProj: 'draw three circles.' },
    { sec: 'II. STORES', img: 'lsa_litter.jpg', caption: 'Litter on the soil.', q: 'What is litter? Which flow brings nutrients into it?', a: 'Dead organic matter on the surface; fallout (leaf fall).', noProj: 'collect dead leaves.' },
    { sec: 'III. FLOWS', img: 'lsa_fungi.jpg', caption: 'Decomposition of dead wood.', q: 'Which flow moves nutrients from litter to soil?', a: 'Decomposition.', noProj: 'describe rotting leaves.' },
    { sec: 'III. FLOWS', img: 'f4_roots.jpg', caption: 'Roots in the soil.', q: 'How do nutrients return from soil to biomass?', a: 'By uptake through plant roots.', noProj: 'pull up a plant and look at its roots.' },
    { sec: 'IV. INPUTS AND OUTPUTS', img: 'f4_gully.jpg', caption: 'Erosion on bare land.', q: 'Name two ways nutrients leave the cycle.', a: 'Leaching and runoff (erosion).', noProj: 'describe soil washed away.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Nutrient cycling:', 'It is the continuous movement of nutrients between living things and their environment.'], ['Biomass:', 'It is the total mass of living matter in an area.'], ['Litter:', 'It is the dead organic matter lying on the soil surface.']] },
    { title: 'II. The Gersmehl Model', items: [['A. Stores:', 'Nutrients are stored in biomass, litter and soil. Circles show the size of each store.'], ['B. Flows:', 'Fallout moves nutrients from biomass to litter, and decomposition from litter to soil. Uptake returns them from soil to biomass.'], ['C. Arrows:', 'The thickness of arrows shows the size of the flows. It varies between ecosystems.']] },
    { title: 'III. Inputs and Outputs', items: [['A. Inputs:', 'Nutrients come from rain (dissolved in it) and from weathering of rock. Man adds fertiliser and manure.'], ['B. Outputs:', 'Nutrients are lost by leaching and surface runoff. Harvests and burning remove them too.'], ['C. Importance:', 'The model shows where nutrients are stored in each biome. It helps to manage forests and farms.']], draw: { img: 'gersmehl_big.png', caption: 'Copy the Gersmehl model.' } },
  ],
  evaluation: [['Name the three stores and three flows of the Gersmehl model.', 'Stores: biomass, litter, soil. Flows: fallout, decomposition, uptake.'], ['Give two inputs of nutrients.', 'Rain and weathering of rock (also fertiliser).']],
  remediation: ['Dead matter on the surface is ______.', 'Leaf fall moves nutrients from biomass to ______.', 'Roots take nutrients by ______.'], remediationAnswers: '1. litter 2. litter 3. uptake',
  homework: 'Draw the Gersmehl model and explain each arrow in one sentence.', homeworkTag: 'This prepares Lesson 24: Nutrient Cycling in Contrasting Ecosystems.',
  bilingual: [['Nutrient', "L'élément nutritif"], ['Cycle', 'Le cycle'], ['Biomass', 'La biomasse'], ['Litter', 'La litière'], ['Uptake', "L'absorption"], ['Fallout', 'La chute de litière']],
});

L.push({ no: 24, title: 'Nutrient Cycling in Contrasting Ecosystems', topic: E1, subtopic: 'The Functioning of Ecosystems',
  notions: 'Selva, steppe, taiga, nutrient store, plantation, cereal farming.', focus: 'Nutrient cycles of the selva and the man-made ecosystem replacing it; the steppe and its replacement; the taiga.',
  competence: 'Learners are able to compare nutrient cycles of the selva, steppe and taiga and explain the effects of replacing them.',
  objectives: ['Describe the nutrient cycle of the selva and its plantation replacement.', 'Describe the nutrient cycle of the steppe and its cereal replacement.', 'Describe the nutrient cycle of the taiga.'],
  recall: ['The Gersmehl model has three stores.', 'Heavy rain causes leaching.'],
  situation: 'When forest is cleared for farms in southern Cameroon, crops grow well for two or three years and then fail. On the steppes of Ukraine, wheat has grown on the same black soils for a century.',
  sitQA: [['What is the problem in the situation?', 'Cleared rainforest soils lose fertility fast, but steppe soils stay fertile.'], ['Where are the nutrients in the rainforest?', 'Mostly in the biomass (trees).'], ['Where are they in the steppe?', 'Mostly in the soil.']],
  justification: 'This lesson helps us to understand why some ecosystems can be farmed for long and others cannot.',
  activities: [
    { sec: 'I. COMPARISON', img: 'gersmehl_compare_big.png', caption: 'Nutrient stores in three biomes.', q: 'In which biome is the biomass store largest? In which is the soil store largest?', a: 'Biomass: selva. Soil: steppe.', noProj: 'draw the three models.' },
    { sec: 'II. THE SELVA', img: 'f2t_rainforest.jpg', caption: 'The selva (tropical rainforest).', q: 'Why is the litter store small in the selva?', a: 'Heat and humidity make decomposition very fast.', noProj: 'describe the thin litter of the forest.' },
    { sec: 'II. SELVA REPLACED', img: 'lsa_oilpalm.jpg', caption: 'An oil palm plantation replacing forest.', q: 'What happens to nutrients when the selva is cleared?', a: 'The biomass store is removed and rain leaches the soil.', noProj: 'discuss shifting cultivation.' },
    { sec: 'III. THE STEPPE REPLACED', img: 'lsa_wheat.jpg', caption: 'Harvesting wheat on former grassland.', q: 'Why could steppes be farmed for so long?', a: 'Their soils (chernozems) store many nutrients.', noProj: 'find Ukraine and the Prairies.' },
    { sec: 'IV. THE TAIGA', img: 'f2t_conifer.jpg', caption: 'The taiga (coniferous forest).', q: 'Why is the litter store large in the taiga?', a: 'It is cold, so decomposition is slow.', noProj: 'find the taiga on a map.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Selva:', 'It is the tropical rainforest.'], ['Steppe:', 'It is the temperate grassland of Eurasia.'], ['Taiga:', 'It is the coniferous forest of cold northern regions.']] },
    { title: 'II. Selva and Steppe', items: [['A. Selva:', 'Most nutrients are in the biomass, and the litter and soil stores are small. Recycling is fast because of heat and rain.'], ['B. Selva replaced:', 'Plantations and farms remove the biomass store. Leaching and erosion quickly make soils poor.'], ['C. Steppe:', 'Most nutrients are in the deep, dark soil, and the biomass is small. Cereal farming can last long but needs fertiliser and erosion control.']] },
    { title: 'III. The Taiga', items: [['A. Stores:', 'The litter store is large because decomposition is slow in the cold. The soil is acid and poor.'], ['B. Flows:', 'Uptake and fallout are slow. Needles make acid humus that leads to podsols.'], ['C. Management:', 'Logging removes nutrients that return very slowly. Replanting and careful cutting are needed.']], draw: { img: 'gersmehl_compare_big.png', caption: 'Copy the three models.' } },
  ],
  evaluation: [['Where are most nutrients in the selva, the steppe and the taiga?', 'Selva: biomass. Steppe: soil. Taiga: litter.'], ['Why do cleared rainforest soils lose fertility quickly?', 'The biomass store is removed and heavy rain leaches the soil.']],
  remediation: ['In the selva most nutrients are in the ______.', 'In the steppe most nutrients are in the ______.', 'In the taiga the ______ store is large.'], remediationAnswers: '1. biomass 2. soil 3. litter',
  homework: 'Draw the Gersmehl models of the selva and the steppe and explain the differences.', homeworkTag: 'This prepares Lesson 25: Nutrient Cycling and Ecosystem Management.',
  bilingual: [['Rainforest', 'La forêt dense'], ['Steppe', 'La steppe'], ['Taiga', 'La taïga'], ['Plantation', 'La plantation'], ['Wheat', 'Le blé'], ['Decomposition', 'La décomposition']],
});

L.push({ no: 25, title: 'Nutrient Cycling and Ecosystem Management', topic: E1, subtopic: 'The Functioning of Ecosystems',
  notions: 'Ecosystem management, sustainable use, fallow, manure, agroforestry, crop rotation.', focus: 'Meaning of ecosystem management; how knowledge of nutrient cycling helps to manage ecosystems.',
  competence: 'Learners are able to use nutrient cycling to propose ways of managing farms and forests sustainably.',
  objectives: ['Define ecosystem management.', 'Explain how nutrient cycling guides management.', 'Propose practices that keep nutrients in the system.'],
  recall: ['Nutrients cycle between biomass, litter and soil.', 'Harvests and leaching remove nutrients.'],
  situation: 'A cooperative in the West Region wants to grow food on the same land every year without the soil becoming poor. An agronomist tells them to "copy the forest".',
  sitQA: [['What is the problem in the situation?', 'The farmers want to farm without exhausting the soil.'], ['What does "copy the forest" mean?', 'Keep the soil covered and return organic matter, as a forest does.'], ['Name one such practice.', 'Agroforestry or composting.']],
  justification: 'This lesson helps us to use ecological knowledge to farm and manage forests sustainably.',
  activities: [
    { sec: 'I. MEANING', img: 'gersmehl_big.png', caption: 'The nutrient cycle.', q: 'Which flows must farmers protect to keep soils fertile?', a: 'Litter return (fallout) and decomposition, and low losses by leaching and runoff.', noProj: 'point to the arrows.' },
    { sec: 'II. RETURNING NUTRIENTS', img: 'f4_zai.jpg', caption: 'Zai pits with manure.', q: 'How does manure copy the natural cycle?', a: 'It returns organic matter and nutrients to the soil, like litter.', noProj: 'describe manure use.' },
    { sec: 'II. RETURNING NUTRIENTS', img: 'lsa_fertiliser.jpg', caption: 'A farmer applying fertiliser.', q: 'Why must fertiliser be used carefully?', a: 'Excess is leached into rivers and pollutes them.', noProj: 'discuss fertiliser use.' },
    { sec: 'III. REDUCING LOSSES', img: 'f4_terraces.jpg', caption: 'Terraces on a hillside.', q: 'How do terraces keep nutrients in the system?', a: 'They reduce runoff and erosion of topsoil.', noProj: 'mention the Mandara terraces.' },
    { sec: 'III. COPYING NATURE', img: 'f2t_tree_planting.jpg', caption: 'Planting trees.', q: 'How does agroforestry help nutrient cycling?', a: 'Trees add litter, their roots bring up nutrients and they protect the soil.', noProj: 'describe trees in farms.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Ecosystem management:', 'It is the careful use of an ecosystem so that it stays productive.'], ['Agroforestry:', 'It is growing trees and crops together on the same land.'], ['Crop rotation:', 'It is changing crops on a field from season to season.']] },
    { title: 'II. Nutrient Cycling as a Guide', items: [['A. Knowing the stores:', 'Where nutrients are stored shows how fragile an ecosystem is. The selva is fragile because nutrients are in the trees.'], ['B. Protecting flows:', 'Keeping litter and humus maintains decomposition and uptake. Burning and bare soil break the cycle.'], ['C. Reducing losses:', 'Leaching and erosion must be reduced. Cover crops and terraces keep nutrients in the system.']] },
    { title: 'III. Management Practices', items: [['A. On farms:', 'Farmers use manure, compost, fallow, legumes and crop rotation. Fertiliser should replace only what harvests remove.'], ['B. In forests:', 'Selective logging and replanting keep the biomass store. Reserves protect whole ecosystems.'], ['C. Agroforestry:', 'Trees and crops together copy the natural forest cycle. It is used with cocoa, coffee and fruit trees in Cameroon.']] },
  ],
  evaluation: [['What is ecosystem management?', 'The careful use of an ecosystem so that it stays productive.'], ['Give three practices that keep nutrients in a farm.', 'Manure, crop rotation, agroforestry (also terraces, fallow).']],
  remediation: ['Growing trees with crops is ______.', 'Changing crops each season is crop ______.', 'Burning breaks the nutrient ______.'], remediationAnswers: '1. agroforestry 2. rotation 3. cycle',
  homework: 'Suggest a plan to keep the soil of your family farm fertile for ten years.', homeworkTag: 'This prepares Lesson 26: Productivity of Ecosystems.',
  bilingual: [['Management', 'La gestion'], ['Sustainable', 'Durable'], ['Manure', 'Le fumier'], ['Agroforestry', "L'agroforesterie"], ['Compost', 'Le compost'], ['Cover crop', 'La plante de couverture']],
});

L.push({ no: 26, title: 'Productivity of Ecosystems', topic: E1, subtopic: 'Ecosystem Productivity',
  notions: 'Productivity, primary productivity, secondary productivity, gross primary productivity, net primary productivity, respiration.', focus: 'Meaning; types (primary and secondary); measurement (gross and net); productivity of ecosystems and reasons; factors.',
  competence: 'Learners are able to explain and compare the productivity of ecosystems.',
  objectives: ['Define productivity and its types.', 'Distinguish gross and net primary productivity.', 'Compare the productivity of ecosystems and explain the factors.'],
  recall: ['Plants make food by photosynthesis.', 'Energy is lost by respiration.'],
  situation: 'A forester says that one hectare of rainforest makes about 25 times more new plant matter each year than one hectare of desert. Learners want to know why.',
  sitQA: [['What is the problem in the situation?', 'Ecosystems produce very different amounts of plant matter.'], ['What do we call this production?', 'Productivity.'], ['Why is the rainforest so productive?', 'It has heat, light, water and a long growing season.']],
  justification: 'This lesson helps us to understand which ecosystems produce the most food and wood, and why.',
  activities: [
    { sec: 'I. MEANING AND TYPES', img: 'veg_system_big.png', caption: 'Plants make new matter by photosynthesis.', q: 'What is primary productivity?', a: 'The rate at which plants make new organic matter.', noProj: 'explain with a growing plant.' },
    { sec: 'II. MEASUREMENT', img: 'productivity_big.png', caption: 'Net primary productivity of biomes.', q: 'Which biome is the most productive? Which is the least?', a: 'Most: rainforest. Least: desert.', noProj: 'read the bar graph.' },
    { sec: 'III. HIGH PRODUCTIVITY', img: 'f2t_rainforest.jpg', caption: 'Tropical rainforest.', q: 'Give two reasons why rainforests are very productive.', a: 'High temperature and much rain all year (long growing season).', noProj: 'compare with savanna.' },
    { sec: 'III. LOW PRODUCTIVITY', img: 'lsa_tundra.jpg', caption: 'The tundra.', q: 'Why is productivity low in the tundra?', a: 'It is cold and the growing season is very short.', noProj: 'find the tundra on a map.' },
    { sec: 'IV. MEASURING', img: 'lsa_quadrat.jpg', caption: 'Scientists measuring vegetation with a quadrat.', q: 'How can scientists measure plant productivity in the field?', a: 'They cut and weigh the plants in a quadrat at intervals.', noProj: 'make a 1 m square with sticks.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Productivity:', 'It is the rate at which new organic matter is made in an ecosystem.'], ['Gross primary productivity (GPP):', 'It is all the organic matter made by plants in photosynthesis.'], ['Net primary productivity (NPP):', 'It is GPP minus the matter used by plants in respiration.']] },
    { title: 'II. Types and Measurement', items: [['A. Primary productivity:', 'It is made by plants from sunlight. It is the base of all food.'], ['B. Secondary productivity:', 'It is new matter made by animals from the food they eat. It is much smaller than primary productivity.'], ['C. Measurement:', 'NPP = GPP − respiration, in g/m²/year. Scientists harvest plants in quadrats or use satellites.']] },
    { title: 'III. Productivity of Ecosystems and Factors', items: [['A. High:', 'Rainforests and swamps produce about 2,000 g/m²/year. They have heat, water and light all year.'], ['B. Low:', 'Deserts and tundra produce under 200 g/m²/year. They lack water or warmth.'], ['C. Factors:', 'Light, temperature, water and nutrients control productivity. Man can raise it with irrigation and fertiliser.']], draw: { img: 'productivity_big.png', caption: 'Copy the bar graph.' } },
  ],
  evaluation: [['Distinguish GPP and NPP.', 'GPP is all matter made by photosynthesis; NPP is GPP minus respiration.'], ['Give three factors of productivity.', 'Temperature, water and light (also nutrients).']],
  remediation: ['NPP = GPP − ______.', 'The most productive land biome is the ______.', 'Matter made by animals is ______ productivity.'], remediationAnswers: '1. respiration 2. rainforest 3. secondary',
  homework: 'Rank five biomes by productivity and give one reason for each.', homeworkTag: 'This prepares Practical Work 2: Measuring Ecosystem Productivity.',
  bilingual: [['Productivity', 'La productivité'], ['Gross', 'Brut'], ['Net', 'Net'], ['Respiration', 'La respiration'], ['Quadrat', 'Le quadrat'], ['Growing season', 'La saison de croissance']],
});

L.push({ kind: 'Practical Work', no: 2, title: 'Measurement of Ecosystem Productivity', topic: E1, subtopic: 'Ecosystem Productivity',
  notions: 'GPP, respiration, NPP, net productivity per unit area, bar graph, ranking.', focus: 'Calculate net productivity from tables; draw bar graphs; classify ecosystems by net productivity per unit area; explain differences.',
  competence: 'Learners are able to calculate and compare the net productivity of ecosystems.',
  objectives: ['Calculate NPP from GPP and respiration.', 'Draw a bar graph of productivity.', 'Rank ecosystems and explain the differences.'],
  recall: ['NPP = GPP − respiration.', 'Rainforests are the most productive land biomes.'],
  situation: 'The Ministry of Forests gives the class a table of gross productivity and respiration for four biomes. The class must calculate net productivity and rank the biomes.',
  sitQA: [['What is the problem in the situation?', 'The class must calculate and compare productivity.'], ['What formula will they use?', 'NPP = GPP − respiration.'], ['How will they show the results?', 'With a bar graph.']],
  justification: 'This practical work helps us to use data to compare ecosystems.',
  activities: [
    { sec: 'I. THE DATA', img: 'pw_productivity_big.png', caption: 'GPP and respiration of four biomes.', q: 'Calculate the NPP of the rainforest and the desert.', a: 'Rainforest: 4,400 − 2,200 = 2,200. Desert: 200 − 110 = 90 g/m²/year.', noProj: 'copy the table.' },
    { sec: 'II. BAR GRAPH', img: 'productivity_big.png', caption: 'A bar graph of NPP.', q: 'Rank the four biomes from highest to lowest NPP.', a: 'Rainforest (2,200), savanna (900), temperate grassland (600), desert (90).', noProj: 'draw bars on graph paper.' },
    { sec: 'III. FIELD METHOD', img: 'lsa_quadrat.jpg', caption: 'A quadrat used to sample vegetation.', q: 'A 1 m² quadrat of grass gives 900 g of dry matter in a year. What is the NPP?', a: '900 g/m²/year.', noProj: 'describe cutting, drying and weighing.' },
    { sec: 'IV. INTERPRETATION', img: 'f2t_savanna.jpg', caption: 'Savanna in the dry season.', q: 'Why is savanna NPP lower than rainforest NPP?', a: 'It has a long dry season, so plants grow only part of the year.', noProj: 'link to climate graphs.' },
    { sec: 'IV. INTERPRETATION', img: 'biomes_map_big.png', caption: 'The main biomes of the world.', q: 'What is the main reason for the low NPP of deserts?', a: 'Lack of water.', noProj: 'find the deserts on the map.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Net productivity per unit area:', 'It is the NPP for one square metre, in g/m²/year.'], ['Respiration:', 'It is the use of food by plants to release energy.'], ['Bar graph:', 'It is a graph that compares values with bars of different heights.']] },
    { title: 'II. Method', items: [['A. Calculation:', 'Subtract respiration from GPP to get NPP. Write the unit g/m²/year.'], ['B. Graph:', 'Draw one bar for each biome, from the highest to the lowest. Give the graph a title and label the axes.'], ['C. Field sampling:', 'Cut the plants in a quadrat, dry them and weigh them. Repeat in several places and take the average.']] },
    { title: 'III. Interpretation', items: [['A. Ranking:', 'Rainforests and swamps have the highest NPP. Deserts and tundra have the lowest.'], ['B. Reasons:', 'High NPP comes from warmth, water and light all year. Low NPP comes from drought or cold.'], ['C. Use:', 'The results show where food and wood production is greatest. They also show which ecosystems recover slowly.']] },
  ],
  evaluation: [['A grassland has GPP 1,500 and respiration 700. Find the NPP.', '800 g/m²/year.'], ['Why does the tundra have a low NPP?', 'It is very cold with a short growing season.']],
  remediation: ['NPP is measured in g per m² per ______.', 'The biome with the lowest NPP is the ______.', 'Plants in a quadrat are cut, dried and ______.'], remediationAnswers: '1. year 2. desert 3. weighed',
  homework: 'Draw the bar graph of the four biomes and write three sentences explaining it.', homeworkTag: 'This prepares Lesson 27: Biomes.',
  bilingual: [['Table', 'Le tableau'], ['Calculate', 'Calculer'], ['Bar graph', "L'histogramme"], ['Rank', 'Classer'], ['Average', 'La moyenne'], ['Sample', "L'échantillon"]],
});

L.push({ no: 27, title: 'Biomes', topic: E1, subtopic: 'Global Terrestrial Ecosystems (Biomes)',
  notions: 'Biome, tropical, temperate, polar, forest, grassland, scrubland, desert.', focus: 'Meaning of biome; classification by climate (tropical, temperate, polar) and by vegetation (forest, grassland, scrubland).',
  competence: 'Learners are able to define and classify the world\'s biomes.',
  objectives: ['Define a biome.', 'Classify biomes by climate.', 'Classify biomes by vegetation.'],
  recall: ['Vegetation zones follow latitude and climate.', 'Ecosystems can be small or very large.'],
  situation: 'A documentary shows lions in the African savanna, bison on the North American prairie and reindeer on the Arctic tundra. Learners ask how scientists group such huge regions.',
  sitQA: [['What is the problem in the situation?', 'Learners want to group very large ecosystems.'], ['What is a very large ecosystem called?', 'A biome.'], ['On what basis are biomes grouped?', 'Climate and main vegetation.']],
  justification: 'This lesson helps us to understand the great natural regions of the world.',
  activities: [
    { sec: 'I. MEANING', img: 'biomes_map_big.png', caption: 'The main biomes of the world (simplified).', q: 'What is a biome?', a: 'A very large ecosystem with a similar climate, vegetation and animals.', noProj: 'find biomes on the map.' },
    { sec: 'II. CLASSIFICATION', img: 'biome_classes_big.png', caption: 'Biomes by climate and vegetation.', q: 'Give one forest biome for each climate group.', a: 'Tropical: rainforest. Temperate: deciduous forest. Cold: taiga.', noProj: 'copy the table.' },
    { sec: 'III. TEMPERATE BIOMES', img: 'f2t_autumn_forest.jpg', caption: 'A temperate deciduous forest in autumn.', q: 'Why do these trees lose their leaves?', a: 'To survive the cold winter.', noProj: 'compare with evergreen forests.' },
    { sec: 'III. GRASSLAND BIOMES', img: 'f2t_prairie.jpg', caption: 'A temperate grassland.', q: 'Name one tropical and one temperate grassland.', a: 'Savanna (tropical); steppe or prairie (temperate).', noProj: 'find them on the map.' },
    { sec: 'IV. POLAR BIOMES', img: 'lsa_tundra.jpg', caption: 'The Arctic tundra.', q: 'Why are there no trees on the tundra?', a: 'It is too cold, windy and the ground is frozen.', noProj: 'describe the tundra.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Biome:', 'It is a very large ecosystem with similar climate, vegetation and animals.'], ['Scrubland:', 'It is vegetation of shrubs and small trees in dry areas.'], ['Evergreen:', 'It is a plant that keeps its leaves all year.']] },
    { title: 'II. Classification by Climate', items: [['A. Tropical biomes:', 'They are hot all year, like rainforest, savanna and hot desert. Rain decides which one is found.'], ['B. Temperate biomes:', 'They have warm summers and cool winters. Examples are deciduous forest, steppe and Mediterranean scrub.'], ['C. Cold and polar biomes:', 'They have long, cold winters. Examples are taiga and tundra.']] },
    { title: 'III. Classification by Vegetation', items: [['A. Forest biomes:', 'Trees dominate in rainforest, deciduous forest and taiga. They need enough rain.'], ['B. Grassland biomes:', 'Grasses dominate in savanna, steppe and prairie. Drought, fire and grazing limit trees.'], ['C. Scrub and desert biomes:', 'Shrubs and scattered plants grow in dry areas. Plants are adapted to save water.']], draw: { img: 'biome_classes_big.png', caption: 'Copy the table.' } },
  ],
  evaluation: [['Define a biome.', 'A very large ecosystem with similar climate, vegetation and animals.'], ['Name one tropical, one temperate and one polar biome.', 'Rainforest; deciduous forest (or steppe); tundra.']],
  remediation: ['A very large ecosystem is a ______.', 'The cold coniferous forest is the ______.', 'The temperate grassland of Eurasia is the ______.'], remediationAnswers: '1. biome 2. taiga 3. steppe',
  homework: 'Draw a table of six biomes with their climate and vegetation.', homeworkTag: 'This prepares Lesson 28: Tropical Biomes.',
  bilingual: [['Biome', 'Le biome'], ['Tropical', 'Tropical'], ['Temperate', 'Tempéré'], ['Polar', 'Polaire'], ['Scrubland', 'La brousse'], ['Evergreen', 'Sempervirent']],
});

L.push({ no: 28, title: 'Characteristics of Tropical Biomes', topic: E1, subtopic: 'Global Terrestrial Ecosystems (Biomes)',
  notions: 'Selva, savanna, hot desert, adaptation, xerophyte, deciduous, emergent.', focus: 'Tropical rainforest, savanna and hot desert: location, climate, vegetation, soils, fauna, productivity, resources, human activities, challenges and solutions; links between climate, vegetation and soil.',
  competence: 'Learners are able to describe the tropical biomes and explain the links between their climate, vegetation and soils.',
  objectives: ['Describe the rainforest biome.', 'Describe the savanna biome.', 'Describe the hot desert biome and compare the three.'],
  recall: ['Biomes are grouped by climate and vegetation.', 'Ferrallitic soils form under hot, wet climates.'],
  situation: 'Cameroon has rainforest in the south, savanna in the centre and north, and borders the Sahara near Lake Chad. Learners want to compare these three tropical biomes.',
  sitQA: [['What is the problem in the situation?', 'Learners want to compare three tropical biomes.'], ['What controls the differences?', 'Mainly the amount and season of rain.'], ['Which biome is the richest in species?', 'The rainforest.']],
  justification: 'This lesson helps us to understand the three tropical biomes found in and around Cameroon.',
  activities: [
    { sec: 'I. RAINFOREST', img: 'f2t_rainforest.jpg', caption: 'The tropical rainforest (selva).', q: 'Describe the vegetation of the rainforest.', a: 'Tall evergreen trees in layers, many species, lianas and emergents.', noProj: 'describe the layers of the forest.' },
    { sec: 'I. RAINFOREST', img: 'douala_climate_big.png', caption: 'An equatorial climate graph.', q: 'How does this climate explain the rainforest?', a: 'Heat and rain all year allow continuous growth.', noProj: 'read the graph.' },
    { sec: 'II. SAVANNA', img: 'f2t_savanna.jpg', caption: 'The savanna.', q: 'How are savanna trees adapted to the dry season?', a: 'They lose leaves, have thick bark and deep roots.', noProj: 'describe the baobab or acacia.' },
    { sec: 'II. SAVANNA', img: 'garoua_climate_big.png', caption: 'A tropical wet and dry climate graph.', q: 'Why is savanna vegetation green only part of the year?', a: 'Rain falls only in one season.', noProj: 'compare with Douala.' },
    { sec: 'III. HOT DESERT', img: 'f2t_desert_plants.jpg', caption: 'Desert plants.', q: 'How are desert plants adapted to drought?', a: 'Small or no leaves, long roots, water storage (xerophytes).', noProj: 'describe a cactus.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Selva:', 'It is the tropical rainforest biome.'], ['Xerophyte:', 'It is a plant adapted to very dry conditions.'], ['Emergent:', 'It is a very tall tree that rises above the forest canopy.']] },
    { title: 'II. Rainforest and Savanna', items: [['A. Rainforest location and climate:', 'It lies between 5°N and 5°S, in the Congo, Amazon and South-East Asia. It is hot (about 27 °C) and wet (over 2,000 mm) all year.'], ['B. Rainforest life and use:', 'Tall evergreen trees in layers grow on deep, leached ferrallitic soils. It gives timber and crops but suffers from deforestation.'], ['C. Savanna:', 'It lies between 5° and 15°, with one wet and one dry season. Grasses and drought-resistant trees support large herds, grazing and cereal farming.']] },
    { title: 'III. Hot Desert and Links', items: [['A. Hot desert:', 'It lies near the tropics, like the Sahara, with under 250 mm of rain. Xerophytes and animals like camels survive the heat and drought.'], ['B. Challenges and solutions:', 'Deforestation, overgrazing and desertification threaten these biomes. Reserves, reforestation and good grazing help.'], ['C. Climate, vegetation and soil:', 'Rain decreases from rainforest to desert, and vegetation becomes shorter and sparser. Soils become thinner and less leached.']] },
  ],
  evaluation: [['Give two characteristics of the rainforest climate.', 'Hot all year (about 27 °C) and wet all year (over 2,000 mm).'], ['How are savanna trees adapted to the dry season?', 'They lose leaves, have thick bark and deep roots.']],
  remediation: ['Plants adapted to drought are ______.', 'Very tall trees above the canopy are ______.', 'The savanna has one wet and one ______ season.'], remediationAnswers: '1. xerophytes 2. emergents 3. dry',
  homework: 'Make a table comparing the climate, vegetation, soils and uses of the three tropical biomes.', homeworkTag: 'This prepares Further Study 3: Ecosystem Services.',
  bilingual: [['Rainforest', 'La forêt dense'], ['Savanna', 'La savane'], ['Desert', 'Le désert'], ['Adaptation', "L'adaptation"], ['Canopy', 'La canopée'], ['Desertification', 'La désertification']],
});

L.push({ kind: 'Further Study', no: 3, title: 'Ecosystem Services', topic: E1, subtopic: 'Global Terrestrial Ecosystems (Biomes)',
  notions: 'Ecosystem services, provisioning, regulating, cultural, supporting services.', focus: 'Resources of ecosystems to man: provisioning, regulating, cultural and supporting services, with examples.',
  competence: 'Learners are able to explain the benefits of ecosystems and why they must be protected.',
  objectives: ['Define ecosystem services.', 'Explain the four types of services with examples.', 'Explain why ecosystem services must be protected.'],
  recall: ['Ecosystems produce food and wood.', 'Vegetation protects soils and water.'],
  situation: 'Villagers near Korup National Park say that the forest gives them bush mango, medicines and clean water. Tourists also pay to visit it. A logger says the forest is only useful for timber.',
  sitQA: [['What is the problem in the situation?', 'People see different benefits in the forest.'], ['Name three benefits the forest gives the villagers.', 'Food, medicines and clean water.'], ['What do we call these benefits?', 'Ecosystem services.']],
  justification: 'This further study helps us to value all the benefits that ecosystems give us.',
  activities: [
    { sec: 'I. TYPES OF SERVICES', img: 'services_big.png', caption: 'The four types of ecosystem services.', q: 'Name the four types of ecosystem services.', a: 'Provisioning, regulating, cultural and supporting.', noProj: 'draw four boxes.' },
    { sec: 'II. PROVISIONING', img: 'f2t_fish_market.jpg', caption: 'A fish market.', q: 'Give three provisioning services.', a: 'Food (fish, fruit), wood and water (also medicines).', noProj: 'list products from forests and rivers.' },
    { sec: 'II. PROVISIONING', img: 'lsa_herbs.jpg', caption: 'Dried medicinal plants for sale in a market (Seoul).', q: 'Why are ecosystems important for medicines?', a: 'Many medicines come from plants and animals.', noProj: 'name local medicinal plants.' },
    { sec: 'III. SUPPORTING', img: 'lsa_bee.jpg', caption: 'A bee pollinating a flower.', q: 'Which service does the bee give to farmers?', a: 'Pollination (a supporting service).', noProj: 'explain pollination.' },
    { sec: 'IV. CULTURAL', img: 'f2t_safari.jpg', caption: 'A leopard seen on a safari drive.', q: 'Give two cultural services of ecosystems.', a: 'Tourism and recreation (also sacred forests, education).', noProj: 'mention Waza and Limbe.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Ecosystem services:', 'They are the benefits that people get from ecosystems.'], ['Pollination:', 'It is the transfer of pollen that allows plants to make fruit and seeds.'], ['Sacred forest:', 'It is a forest protected for religious or traditional reasons.']] },
    { title: 'II. The Four Services', items: [['A. Provisioning services:', 'Ecosystems give food, wood, fibre, water and medicines. Forests, rivers and the sea feed millions of people.'], ['B. Regulating services:', 'Forests clean the air, store carbon and regulate climate. Wetlands and mangroves control floods and clean water.'], ['C. Cultural services:', 'Ecosystems give beauty, tourism, recreation and education. Sacred forests keep cultural traditions alive.'], ['D. Supporting services:', 'Soil formation, nutrient cycling and pollination support all other services. Without them there would be no food.']] },
    { title: 'III. Protecting Services', items: [['A. Threats:', 'Deforestation, pollution and overexploitation reduce services. The loss is often seen only when it is too late.'], ['B. Measures:', 'Parks, reserves and sustainable use protect ecosystems. Local people should share the benefits.']], draw: { img: 'services_big.png', caption: 'Copy the four services.' } },
  ],
  evaluation: [['Define ecosystem services.', 'The benefits that people get from ecosystems.'], ['Give one example of each type of service.', 'Provisioning: food; regulating: flood control; cultural: tourism; supporting: pollination.']],
  remediation: ['Food and wood are ______ services.', 'Flood control is a ______ service.', 'Pollination is a ______ service.'], remediationAnswers: '1. provisioning 2. regulating 3. supporting',
  homework: 'List the services given by an ecosystem near your home and classify them.', homeworkTag: 'This ends the Biogeography branch of Lower Sixth.',
  bilingual: [['Service', 'Le service'], ['Benefit', 'Le bénéfice'], ['Pollination', 'La pollinisation'], ['Tourism', 'Le tourisme'], ['Medicine', 'Le médicament'], ['Wetland', 'La zone humide']],
});

module.exports = { L, B };
if (require.main === module) run(L, B, process.argv.slice(2).length ? process.argv.slice(2) : null);
