// LOWER SIXTH ARTS — BIOGEOGRAPHY part 1: SOILS (Module 3, lessons 1–11, PW1, FS1). 2 periods, 5 activities, summary 2–3 sentences per point.
const { run } = require('./sixth');
const B = { level: 'LSA', branch: 'Biogeography', folder: 'Biogeography', code: 'BIO',
  module: 'Module 3: Understanding and managing biogeographic zones across the world in general and Cameroon in particular',
  moduleShort: 'Module 3 (Biogeography)', topicDefault: 'Soil and its Properties' };
const S1 = 'Soil and its Properties', S2 = 'Soil Development', S3 = 'Physical Geography of Cameroon';
const L = [];

L.push({ no: 1, title: 'The Soil', topic: S1, subtopic: 'The Soil System',
  notions: 'Soil, pedology, mineral matter, organic matter, soil air, soil water, soil system.', focus: 'Meaning of soil; components and their variation with depth; importance of soil; the soil system.',
  competence: 'Learners are able to describe what soil is made of and explain why it is important to man and to living things.',
  objectives: ['Define soil and pedology.', 'Describe the four components of soil and how they change with depth.', 'Explain the importance of soil and the soil as a system.'],
  recall: ['Weathering breaks rocks into small pieces.', 'Plants need water and nutrients.'],
  situation: 'A farmer in Foumbot says that his dark soil feeds his family, while a builder says that soil is only "dirt" to be removed. The class wants to know what soil really is.',
  sitQA: [['What is the problem in the situation?', 'People do not agree on what soil is and why it matters.'], ['Is soil only broken rock?', 'No. It also contains humus, water, air and living things.'], ['Why is soil important?', 'It grows our food and supports all land life.']],
  justification: 'This lesson helps us to understand the soil, the base of farming and of land ecosystems.',
  activities: [
    { sec: 'I. MEANING', img: 'lsa_soilpit.jpg', caption: 'A soil pit showing layers of soil.', q: 'What does the pit show about soil?', a: 'Soil is a thin layer over rock, with different layers from the top down.', noProj: 'dig a small hole near the school.' },
    { sec: 'II. COMPONENTS', img: 'soil_components_big.png', caption: 'The four components of a good soil.', q: 'Name the four components of soil. Which is the largest?', a: 'Mineral matter, water, air and organic matter; mineral matter is the largest (45 %).', noProj: 'draw the pie chart.' },
    { sec: 'II. COMPONENTS', img: 'lsa_earthworm.jpg', caption: 'An earthworm in the soil.', q: 'Why is the earthworm part of the soil?', a: 'Soil contains living organisms that mix it and make humus.', noProj: 'look for worms after rain.' },
    { sec: 'III. IMPORTANCE', img: 'lsa_cmrfarm.jpg', caption: 'A woman farmer in her farm in Cameroon.', q: 'Give two uses of soil for man.', a: 'It grows food and cash crops and gives building materials (clay, sand).', noProj: 'list crops grown in your area.' },
    { sec: 'IV. THE SOIL SYSTEM', img: 'soil_system_big.png', caption: 'The soil as an open system.', q: 'Name two inputs and two outputs of the soil system.', a: 'Inputs: rain, dead leaves (also weathered rock, sun). Outputs: leaching, erosion (also uptake, evaporation).', noProj: 'draw the three boxes.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil:', 'It is the thin, loose top layer of the Earth where plants grow.'], ['Pedology:', 'It is the scientific study of soils.'], ['Humus:', 'It is dark, decayed organic matter in the soil.']] },
    { title: 'II. Components of Soil', items: [['A. Mineral matter (45 %):', 'It comes from weathered rock as sand, silt and clay. It gives the soil its body.'], ['B. Water and air (25 % each):', 'They fill the pores between particles. Plants and soil animals need both.'], ['C. Organic matter (5 %):', 'It comes from dead plants and animals and becomes humus. It holds water and nutrients.'], ['D. Variation with depth:', 'Humus and life are highest near the surface. Deeper down there is more rock and less air.']] },
    { title: 'III. Importance and the Soil System', items: [['A. Importance to man:', 'Soil grows food, cash crops and forests. It also gives clay, sand and laterite for building.'], ['B. Importance to the biosphere:', 'Soil stores water and nutrients for plants. It is home to many living things.'], ['C. The soil system:', 'Inputs are rain, weathered rock, litter and energy. Outputs are uptake, leaching, evaporation and erosion.']], draw: { img: 'soil_system_big.png', caption: 'Copy the soil system.' } },
  ],
  evaluation: [['Name the four components of soil with their proportions.', 'Mineral matter 45 %, water 25 %, air 25 %, organic matter 5 %.'], ['Give two outputs of the soil system.', 'Leaching and erosion (also uptake, evaporation).']],
  remediation: ['The study of soils is ______.', 'Decayed organic matter is ______.', 'The largest component of soil is ______ matter.'], remediationAnswers: '1. pedology 2. humus 3. mineral',
  homework: 'Collect a handful of soil and list what you can see in it.', homeworkTag: 'This prepares Lesson 2: Physical Properties of the Soil.',
  bilingual: [['Soil', 'Le sol'], ['Humus', "L'humus"], ['Pore', 'Le pore'], ['Earthworm', 'Le ver de terre'], ['Leaching', 'Le lessivage'], ['Pedology', 'La pédologie']],
});

L.push({ no: 2, title: 'Physical Properties of the Soil: Texture', topic: S1, subtopic: 'Soil Properties and their Significance',
  notions: 'Soil texture, sand, silt, clay, loam, textural class, texture triangle.', focus: 'Meaning of texture; textural classes; field and laboratory determination; representation; factors; significance.',
  competence: 'Learners are able to identify soil texture and explain its importance for farming.',
  objectives: ['Define soil texture and name the particle sizes.', 'Determine texture in the field and in the laboratory.', 'Read the texture triangle and explain the significance of texture.'],
  recall: ['Mineral matter comes from weathered rock.', 'Soil holds water and air in its pores.'],
  situation: 'In the Adamawa, a farmer notices that water disappears quickly in his sandy field, while in a valley the clay soil stays wet and sticky for days after rain.',
  sitQA: [['What is the problem in the situation?', 'Soils behave differently with water.'], ['What property explains this?', 'Soil texture.'], ['Which soil holds more water?', 'The clay soil.']],
  justification: 'This lesson helps us to know soil texture, which controls water, air and fertility.',
  activities: [
    { sec: 'I. PARTICLE SIZES', img: 'particle_sizes_big.png', caption: 'The size of soil particles.', q: 'Put sand, silt and clay in order from the largest to the smallest.', a: 'Sand, silt, clay.', noProj: 'show sand, flour and clay.' },
    { sec: 'II. TEXTURAL CLASSES', img: 'texture_triangle_big.png', caption: 'The soil texture triangle.', q: 'A soil has 40 % sand, 40 % silt and 20 % clay. What is its class?', a: 'Loam.', noProj: 'draw the triangle.' },
    { sec: 'III. DETERMINATION', img: 'ribbon_test_big.png', caption: 'The ribbon test for soil texture.', q: 'In the field, how can you tell if a wet soil is sandy or clayey?', a: 'Sand feels gritty and falls apart; clay feels sticky and makes a long ribbon.', noProj: 'rub wet soil between the fingers.' },
    { sec: 'IV. FACTORS', img: 'f4_redsoil.jpg', caption: 'A red tropical soil.', q: 'Why are soils on granite often sandy, and soils on basalt often clayey?', a: 'Granite weathers into quartz sand; basalt weathers into clay.', noProj: 'compare local rocks.' },
    { sec: 'V. SIGNIFICANCE', img: 'f2t_rice_field.jpg', caption: 'A rice field.', q: 'Why is rice grown on clay soils?', a: 'Clay holds water and keeps the field flooded.', noProj: 'mention rice at Ndop and Yagoua.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil texture:', 'It is the proportion of sand, silt and clay in a soil.'], ['Loam:', 'It is a soil with a good mixture of sand, silt and clay.'], ['Texture triangle:', 'It is a triangle graph used to name the texture class of a soil.']] },
    { title: 'II. Classes and Determination', items: [['A. Particle sizes:', 'Sand is 0.05–2 mm, silt 0.002–0.05 mm and clay below 0.002 mm. Gravel is bigger than 2 mm.'], ['B. Field methods:', 'We feel, mould and roll wet soil in the hand. Sand is gritty, silt is smooth and clay is sticky.'], ['C. Laboratory methods:', 'Sieving and sedimentation separate the particles. The percentages are plotted on the texture triangle.']] },
    { title: 'III. Factors and Significance', items: [['A. Factors:', 'Parent rock, weathering and age control texture. Water and wind also move fine particles.'], ['B. Sandy soils:', 'They are light, well aerated and easy to dig. But they drain fast and lose nutrients.'], ['C. Clay and loam soils:', 'Clay holds water and nutrients but can be sticky and waterlogged. Loam is the best balance for most crops.']], draw: { img: 'texture_triangle_big.png', caption: 'Copy the texture triangle.' } },
  ],
  evaluation: [['What is soil texture?', 'The proportion of sand, silt and clay in a soil.'], ['Give one advantage and one disadvantage of a sandy soil.', 'Advantage: easy to dig and well aerated. Disadvantage: dries fast and loses nutrients.']],
  remediation: ['The smallest soil particles are ______.', 'A soil with a good mix of particles is ______.', 'Texture classes are read on the texture ______.'], remediationAnswers: '1. clay 2. loam 3. triangle',
  homework: 'Test three soils from home by feel and give the texture of each.', homeworkTag: 'This prepares Practical Work 1: Determining Soil Texture.',
  bilingual: [['Texture', 'La texture'], ['Sand', 'Le sable'], ['Silt', 'Le limon'], ['Clay', "L'argile"], ['Loam', 'Le sol limoneux équilibré'], ['Sieve', 'Le tamis']],
});

L.push({ kind: 'Practical Work', no: 1, title: 'Determining Soil Texture', topic: S1, subtopic: 'Soil Properties and their Significance',
  notions: 'Feel method, moulding, ribbon test, sieving, textural class, ternary graph.', focus: 'In the field: feeling, moulding and ribbon methods. In the laboratory: sieving, percentages and plotting on a ternary graph.',
  competence: 'Learners are able to determine soil texture in the field and in the laboratory and plot it on a texture triangle.',
  objectives: ['Collect soil samples correctly.', 'Determine texture by feeling, moulding and ribbon methods.', 'Sieve a sample, calculate percentages and plot them on a texture triangle.'],
  recall: ['Sand is gritty, silt smooth and clay sticky.', 'The texture triangle shows the class of a soil.'],
  situation: 'The school wants to start a vegetable garden. The teacher asks the class to test the soils in three places in the school compound and to choose the best one.',
  sitQA: [['What is the problem in the situation?', 'The class must find the best soil for a garden.'], ['What property will they test?', 'Soil texture.'], ['Which texture is best for vegetables?', 'A loam.']],
  justification: 'This practical work helps us to test soils ourselves and choose good land for crops.',
  activities: [
    { sec: 'I. SAMPLING', img: 'lsa_soilpit.jpg', caption: 'Taking samples from a soil pit.', q: 'Why do we take samples from several places?', a: 'Soils change from place to place, so one sample is not enough.', noProj: 'mark three sample points in the compound.' },
    { sec: 'II. FIELD METHODS', img: 'ribbon_test_big.png', caption: 'The feel and ribbon test.', q: 'A wet sample makes a long, shiny ribbon. What is its texture?', a: 'Clay.', noProj: 'do the ribbon test with the class.' },
    { sec: 'III. LABORATORY METHOD', img: 'particle_sizes_big.png', caption: 'Particles separated by sieves.', q: 'Why do we dry and crush the soil before sieving?', a: 'So the particles separate and pass through the right sieve.', noProj: 'use kitchen sieves of different sizes.' },
    { sec: 'III. LABORATORY METHOD', img: 'pw_texture_big.png', caption: 'Results for three samples.', q: 'Which sample is best for the school garden? Why?', a: 'Sample B (loam): it holds water and drains well.', noProj: 'copy the table.' },
    { sec: 'IV. PLOTTING', img: 'texture_triangle_big.png', caption: 'Plotting a sample on the triangle.', q: 'Plot sample C (20 % sand, 25 % silt, 55 % clay). In which class does it fall?', a: 'Clay.', noProj: 'plot the three samples.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Feel method:', 'It is finding texture by rubbing wet soil between the fingers.'], ['Ribbon test:', 'It is pressing wet soil into a ribbon to judge its clay content.'], ['Ternary graph:', 'It is a triangle graph with three axes that add up to 100 %.']] },
    { title: 'II. Field Methods', items: [['A. Feeling:', 'Wet a small sample and rub it. Gritty means sand, smooth means silt and sticky means clay.'], ['B. Moulding:', 'Roll the soil into a ball. Sand falls apart, and clay keeps its shape.'], ['C. Ribbon:', 'Press the soil between thumb and finger. A long ribbon shows much clay.']] },
    { title: 'III. Laboratory Method', items: [['A. Sieving:', 'Dry, crush and weigh the sample, then pass it through sieves. Weigh the sand, silt and clay parts.'], ['B. Percentages:', 'Divide each weight by the total and multiply by 100. The three values must add up to 100 %.'], ['C. Plotting:', 'Plot the percentages on the texture triangle. Read the class where the three lines meet.']], draw: { img: 'pw_texture_big.png', caption: 'Copy the results table.' } },
  ],
  evaluation: [['A sample weighs 200 g: 80 g sand, 80 g silt, 40 g clay. Give the percentages.', 'Sand 40 %, silt 40 %, clay 20 % (loam).'], ['Give two field methods to find texture.', 'Feel method and ribbon test (also moulding).']],
  remediation: ['A gritty soil is rich in ______.', 'A long ribbon shows much ______.', 'The three percentages must add up to ______ %.'], remediationAnswers: '1. sand 2. clay 3. 100',
  homework: 'Write a short report on the three school samples and the best place for the garden.', homeworkTag: 'This prepares Lesson 3: Soil Structure.',
  bilingual: [['Sample', "L'échantillon"], ['Sieve', 'Le tamis'], ['Weigh', 'Peser'], ['Percentage', 'Le pourcentage'], ['Triangle', 'Le triangle'], ['Garden', 'Le jardin']],
});

L.push({ no: 3, title: 'Soil Structure', topic: S1, subtopic: 'Soil Properties and their Significance',
  notions: 'Soil structure, ped, crumb, blocky, platy, prismatic, compaction.', focus: 'Meaning and types of soil structure; factors; significance.',
  competence: 'Learners are able to identify soil structures and explain how to keep a good structure.',
  objectives: ['Define soil structure.', 'Describe the main types of structure.', 'Explain the factors and significance of structure.'],
  recall: ['Texture is the proportion of sand, silt and clay.', 'Earthworms mix the soil.'],
  situation: 'On a school farm, the soil where tractors pass is hard and water lies on it after rain. Under the bushes, the soil is loose and crumbly and water soaks in quickly.',
  sitQA: [['What is the problem in the situation?', 'Some soils are hard and do not let water in.'], ['What property is different?', 'Soil structure.'], ['What damaged the structure?', 'Compaction by heavy machines.']],
  justification: 'This lesson helps us to understand how soil particles are arranged, which controls water, air and roots.',
  activities: [
    { sec: 'I. TYPES', img: 'soil_structure_big.png', caption: 'The main types of soil structure.', q: 'Which structure is best for crops? Why?', a: 'Crumb: it lets water, air and roots pass easily.', noProj: 'break a lump of soil in the hand.' },
    { sec: 'II. FACTORS', img: 'lsa_earthworm.jpg', caption: 'An earthworm in the soil.', q: 'How do earthworms improve soil structure?', a: 'They mix the soil and glue particles into crumbs.', noProj: 'look for worm casts.' },
    { sec: 'II. FACTORS', img: 'f2t_cracked_soil.jpg', caption: 'Cracked clay soil in the dry season.', q: 'What happens to clay soils when they dry?', a: 'They shrink and crack into large blocks or columns.', noProj: 'describe dry clay in the north.' },
    { sec: 'II. FACTORS', img: 'f2t_combine.jpg', caption: 'A heavy farm machine.', q: 'How can heavy machines damage soil structure?', a: 'They press the soil and make it compact, so water cannot enter.', noProj: 'compare a path and a field.' },
    { sec: 'III. SIGNIFICANCE', img: 'f4_roots.jpg', caption: 'Roots growing through soil and rock.', q: 'Why do roots grow better in soils with a good structure?', a: 'There are many pores for roots, air and water.', noProj: 'pull a plant from loose and hard soil.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil structure:', 'It is the way soil particles are grouped together.'], ['Ped:', 'It is a single lump or aggregate of soil particles.'], ['Compaction:', 'It is the pressing of soil so that its pores become small.']] },
    { title: 'II. Types of Structure', items: [['A. Crumb and granular:', 'They are small, round, porous peds. They are found in topsoils rich in humus.'], ['B. Blocky:', 'It has angular block-shaped peds. It is common in subsoils.'], ['C. Platy and prismatic:', 'Platy peds are flat layers that stop water. Prismatic peds are tall columns found in dry clay soils.']] },
    { title: 'III. Factors and Significance', items: [['A. Factors:', 'Humus, clay, roots and soil animals help particles to stick together. Wetting and drying, frost and machines also change structure.'], ['B. Significance:', 'A good structure lets water, air and roots move easily. It reduces runoff and erosion.'], ['C. Management:', 'Adding manure and avoiding heavy machines on wet soil keep a good structure. Mulching protects the surface.']], draw: { img: 'soil_structure_big.png', caption: 'Copy the four structures.' } },
  ],
  evaluation: [['Distinguish soil texture and soil structure.', 'Texture is the proportion of particles; structure is how particles are grouped.'], ['Give two ways to improve soil structure.', 'Add manure (humus) and avoid compaction (also mulching).']],
  remediation: ['A lump of soil particles is a ______.', 'The best structure for crops is ______.', 'Heavy machines cause ______.'], remediationAnswers: '1. ped 2. crumb 3. compaction',
  homework: 'Break soil from a path and from a garden. Describe the structure of each.', homeworkTag: 'This prepares Lesson 4: Soil Depth and Organic Matter.',
  bilingual: [['Structure', 'La structure'], ['Crumb', 'Grumeleuse'], ['Compaction', 'Le tassement'], ['Root', 'La racine'], ['Manure', 'Le fumier'], ['Mulch', 'Le paillis']],
});

L.push({ no: 4, title: 'Soil Depth, Organic Matter and Soil Organisms', topic: S1, subtopic: 'Soil Properties and their Significance',
  notions: 'Soil depth, regolith, organic matter, humus, humification, soil organisms, decomposers.', focus: 'Soil depth and its factors; inorganic matter; soil organisms; soil organic matter (humus) and its importance.',
  competence: 'Learners are able to explain soil depth and the role of organic matter and organisms in the soil.',
  objectives: ['Define soil depth and explain its factors.', 'Explain the formation and importance of humus.', 'Describe the role of soil organisms.'],
  recall: ['Soil has four components.', 'Earthworms improve soil structure.'],
  situation: 'On the steep slopes of the Mandara Mountains the soil is only a few centimetres deep, while in the southern forest the red soil can be several metres deep.',
  sitQA: [['What is the problem in the situation?', 'Soils have very different depths.'], ['Why is the soil thin on steep slopes?', 'Erosion removes it quickly.'], ['Why is the forest soil deep?', 'Heat and rain weather the rock deeply over a long time.']],
  justification: 'This lesson helps us to understand soil depth and the living part of the soil that keeps it fertile.',
  activities: [
    { sec: 'I. SOIL DEPTH', img: 'soil_profile_big.png', caption: 'A soil profile from the surface to the bedrock.', q: 'What is soil depth?', a: 'The thickness of the soil from the surface to the parent rock.', noProj: 'measure a road cutting.' },
    { sec: 'I. SOIL DEPTH', img: 'lsa_scree.jpg', caption: 'Steep mountain slopes with broken rock.', q: 'Why are soils thin on steep mountain slopes?', a: 'Erosion removes soil as fast as it forms.', noProj: 'compare slopes and valleys.' },
    { sec: 'II. ORGANIC MATTER', img: 'lsa_litter.jpg', caption: 'Dead leaves and worm casts on the soil.', q: 'What happens to dead leaves on the soil?', a: 'Organisms break them down into humus.', noProj: 'look under a tree.' },
    { sec: 'III. ORGANISMS', img: 'lsa_termite.jpg', caption: 'A termite mound.', q: 'How do termites change the soil?', a: 'They move and mix soil and break down dead plants.', noProj: 'describe termite mounds in the savanna.' },
    { sec: 'III. ORGANISMS', img: 'lsa_fungi.jpg', caption: 'A mushroom (fungus) on dead wood.', q: 'Why are fungi and bacteria called decomposers?', a: 'They break down dead matter and release nutrients.', noProj: 'describe rotting wood.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil depth:', 'It is the thickness of the soil down to the parent rock.'], ['Humification:', 'It is the change of dead organic matter into humus.'], ['Decomposers:', 'They are organisms such as fungi and bacteria that break down dead matter.']] },
    { title: 'II. Soil Depth', items: [['A. Factors:', 'Climate, rock type, slope, vegetation and time control soil depth. Hot, wet climates give deep soils.'], ['B. Examples:', 'Tropical forest soils can be many metres deep. Mountain and desert soils are often thin.'], ['C. Inorganic matter:', 'It includes rock pieces, minerals and nutrients. It comes from weathering of the parent rock.']] },
    { title: 'III. Organic Matter and Organisms', items: [['A. Humus:', 'Dead leaves and animals are broken down into humus. Humus is dark and holds water and nutrients.'], ['B. Soil organisms:', 'Worms, termites, ants, fungi and bacteria live in the soil. They mix it, make pores and decompose matter.'], ['C. Importance:', 'Humus and organisms make soils fertile and well structured. Burning and overuse destroy them.']] },
  ],
  evaluation: [['Give three factors of soil depth.', 'Climate, slope and time (also rock type, vegetation).'], ['Why is humus important?', 'It holds water and nutrients and improves structure.']],
  remediation: ['Dead matter becomes ______.', 'Fungi and bacteria are ______.', 'Soils on steep slopes are ______.'], remediationAnswers: '1. humus 2. decomposers 3. thin',
  homework: 'Make a small compost heap with leaves and observe it for two weeks.', homeworkTag: 'This prepares Lesson 5: Chemical Properties of the Soil.',
  bilingual: [['Depth', 'La profondeur'], ['Organic matter', 'La matière organique'], ['Decomposer', 'Le décomposeur'], ['Termite', 'Le termite'], ['Fungus', 'Le champignon'], ['Compost', 'Le compost']],
});

L.push({ no: 5, title: 'Chemical Properties of the Soil', topic: S1, subtopic: 'Soil Properties and their Significance',
  notions: 'Soil colour, nutrients, macronutrients, pH, acidity, alkalinity, liming.', focus: 'Soil colour, soil nutrients and soil pH: meaning, factors and significance.',
  competence: 'Learners are able to explain soil colour, nutrients and pH and their effect on crops.',
  objectives: ['Explain what soil colour shows.', 'Name the main soil nutrients.', 'Explain soil pH, its factors and significance.'],
  recall: ['Humus is dark.', 'Leaching removes minerals from the soil.'],
  situation: 'An agricultural officer in Bertoua tests a farmer\'s soil and says that it is "too acid" for maize. She advises the farmer to add lime and manure.',
  sitQA: [['What is the problem in the situation?', 'The soil is too acid for crops.'], ['What measures acidity?', 'Soil pH.'], ['How can acidity be reduced?', 'By adding lime.']],
  justification: 'This lesson helps us to understand the chemistry of soil, which controls fertility.',
  activities: [
    { sec: 'I. SOIL COLOUR', img: 'f4_redsoil.jpg', caption: 'A red tropical soil.', q: 'What gives this soil its red colour?', a: 'Iron oxides (rust) formed by weathering in a hot, wet climate.', noProj: 'compare local soil colours.' },
    { sec: 'I. SOIL COLOUR', img: 'f2t_black_soil.jpg', caption: 'A dark soil.', q: 'What does a dark colour usually show?', a: 'Much humus (or clay rich in minerals, as in black earths).', noProj: 'compare topsoil and subsoil.' },
    { sec: 'II. SOIL pH', img: 'ph_scale_big.png', caption: 'The soil pH scale.', q: 'What pH is best for most crops?', a: 'About 6 to 7 (slightly acid to neutral).', noProj: 'draw the scale.' },
    { sec: 'II. SOIL pH', img: 'lsa_phtest.jpg', caption: 'A soil pH test kit.', q: 'How can a farmer measure soil pH?', a: 'With a test kit or pH paper that changes colour.', noProj: 'describe litmus paper.' },
    { sec: 'III. NUTRIENTS', img: 'lsa_fertiliser.jpg', caption: 'A farmer applying fertiliser.', q: 'Name the three main nutrients in fertiliser.', a: 'Nitrogen (N), phosphorus (P) and potassium (K).', noProj: 'read a fertiliser bag (NPK).' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil pH:', 'It is a measure of how acid or alkaline a soil is.'], ['Nutrients:', 'They are chemical elements that plants need to grow.'], ['Liming:', 'It is adding lime to a soil to reduce acidity.']] },
    { title: 'II. Colour and Nutrients', items: [['A. Colour:', 'Red and yellow colours come from iron oxides. Dark colours show humus, and grey colours show waterlogging.'], ['B. Macronutrients:', 'Plants need much nitrogen, phosphorus and potassium. Calcium, magnesium and sulphur are also important.'], ['C. Factors:', 'Nutrients come from rock, humus and fertiliser. Leaching and harvests remove them.']] },
    { title: 'III. Soil pH', items: [['A. Scale:', 'pH goes from 1 to 14, and 7 is neutral. Below 7 is acid and above 7 is alkaline.'], ['B. Factors:', 'Heavy rain leaches bases and makes soils acid, like ferrallitic soils. Dry climates and limestone give alkaline soils.'], ['C. Significance:', 'Most crops grow best at pH 6 to 7. Lime corrects acid soils, and gypsum or drainage helps alkaline soils.']], draw: { img: 'ph_scale_big.png', caption: 'Copy the pH scale.' } },
  ],
  evaluation: [['What does a red soil colour show?', 'Iron oxides formed by weathering in a hot, wet climate.'], ['Why are soils of the rainforest often acid?', 'Heavy rain leaches the bases (calcium, magnesium) out of the soil.']],
  remediation: ['A pH of 7 is ______.', 'Acid soils are corrected by adding ______.', 'N, P and K are plant ______.'], remediationAnswers: '1. neutral 2. lime 3. nutrients',
  homework: 'Read the label of a fertiliser bag and explain what N, P and K do.', homeworkTag: 'This prepares Lesson 6: Soil Fertility.',
  bilingual: [['Colour', 'La couleur'], ['Acid', 'Acide'], ['Nutrient', "L'élément nutritif"], ['Fertiliser', "L'engrais"], ['Lime', 'La chaux'], ['Iron', 'Le fer']],
});

L.push({ no: 6, title: 'Soil Fertility', topic: S1, subtopic: 'Soil Properties and their Significance',
  notions: 'Soil fertility, productivity, fallow, manure, crop rotation, soil exhaustion.', focus: 'Meaning and factors of soil fertility.',
  competence: 'Learners are able to explain what makes a soil fertile and how farmers can keep it fertile.',
  objectives: ['Define soil fertility.', 'Explain the natural and human factors of fertility.', 'Suggest ways to maintain soil fertility.'],
  recall: ['Soils need nutrients, humus and a good structure.', 'Soil pH affects crops.'],
  situation: 'Farmers in the West Region grow good crops every year on volcanic soils, while in some parts of the North, yields fall after two or three years on the same field.',
  sitQA: [['What is the problem in the situation?', 'Some soils stay fertile and others lose fertility.'], ['Why are volcanic soils fertile?', 'They are rich in minerals from volcanic rock.'], ['Why do yields fall in the North?', 'Nutrients are used up and not replaced.']],
  justification: 'This lesson helps us to understand soil fertility and how to keep soils productive for food.',
  activities: [
    { sec: 'I. MEANING', img: 'f2t_tea_highlands.jpg', caption: 'Crops on fertile highland soils.', q: 'What is a fertile soil?', a: 'A soil that can supply enough water and nutrients for good crops.', noProj: 'name fertile farming areas in Cameroon.' },
    { sec: 'II. NATURAL FACTORS', img: 'f4_redsoil.jpg', caption: 'A leached red soil.', q: 'Why are many rainforest soils poor despite the thick forest?', a: 'Heavy rain leaches nutrients; most nutrients are in the plants, not the soil.', noProj: 'explain leaching with a coffee filter.' },
    { sec: 'III. HUMAN FACTORS', img: 'f2t_bushfire.jpg', caption: 'Burnt land after a bush fire.', q: 'How can bush fires reduce fertility in the long term?', a: 'They burn humus and leave the soil bare to erosion.', noProj: 'discuss burning before planting.' },
    { sec: 'IV. MAINTAINING FERTILITY', img: 'f4_zai.jpg', caption: 'Zai pits with manure.', q: 'How do zai pits help fertility?', a: 'They hold water and manure near the crops.', noProj: 'describe zai in the Far North.' },
    { sec: 'IV. MAINTAINING FERTILITY', img: 'f4_terraces.jpg', caption: 'Terraces on a hillside.', q: 'How do terraces protect fertility?', a: 'They stop erosion from removing the topsoil.', noProj: 'mention terraces in the Mandara Mountains.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil fertility:', 'It is the ability of a soil to supply water and nutrients to plants.'], ['Soil exhaustion:', 'It is the loss of fertility after long use without care.'], ['Fallow:', 'It is land left to rest so that it regains its fertility.']] },
    { title: 'II. Factors of Fertility', items: [['A. Natural factors:', 'Parent rock, humus, texture, structure and pH control fertility. Volcanic and alluvial soils are often very fertile.'], ['B. Climate:', 'Heavy rain leaches nutrients, and drought limits plant growth. Moderate climates keep more nutrients.'], ['C. Human factors:', 'Burning, overcropping and erosion reduce fertility. Manure, fertiliser and good practices increase it.']] },
    { title: 'III. Maintaining Fertility', items: [['A. Organic methods:', 'Farmers add manure, compost and crop residues. They also use fallow and legumes that fix nitrogen.'], ['B. Soil protection:', 'Terraces, contour ridges and cover crops stop erosion. Zai pits keep water and manure near the crops.'], ['C. Chemical methods:', 'Fertilisers and lime correct nutrient shortages and acidity. They must be used carefully to avoid pollution.']] },
  ],
  evaluation: [['Define soil fertility.', 'The ability of a soil to supply water and nutrients to plants.'], ['Give three ways of maintaining soil fertility.', 'Manure, fallow, crop rotation (also terraces, fertiliser, lime).']],
  remediation: ['Land left to rest is ______.', 'Loss of fertility by overuse is soil ______.', 'Legumes add ______ to the soil.'], remediationAnswers: '1. fallow 2. exhaustion 3. nitrogen',
  homework: 'Ask a farmer how he keeps his soil fertile and write a short report.', homeworkTag: 'This prepares Lesson 7: Soil Formation.',
  bilingual: [['Fertility', 'La fertilité'], ['Fallow', 'La jachère'], ['Crop rotation', 'La rotation des cultures'], ['Legume', 'La légumineuse'], ['Yield', 'Le rendement'], ['Overcropping', 'La surexploitation']],
});

L.push({ no: 7, title: 'Soil Formation', topic: S2, subtopic: 'Soil Formation',
  notions: 'Pedogenesis, parent material, Jenny\'s equation, active factors, passive factors.', focus: 'Stages of soil formation; factors (Cl, O, R, P, T): active and passive, and the role of each.',
  competence: 'Learners are able to explain how soils form and the role of each soil-forming factor.',
  objectives: ['Describe the stages of soil formation.', 'State Jenny\'s equation.', 'Explain the role of active and passive factors.'],
  recall: ['Weathering breaks rocks.', 'Humus comes from dead organic matter.'],
  situation: 'On the 1999 lava flow of Mount Cameroon there is almost no soil yet, but on older flows there are farms. Learners ask how long it takes to make soil.',
  sitQA: [['What is the problem in the situation?', 'Learners do not know how soil forms.'], ['Why is there no soil on the new lava?', 'There has not been enough time for weathering and plants.'], ['What are the main factors of soil formation?', 'Climate, organisms, relief, parent material and time.']],
  justification: 'This lesson helps us to understand that soil forms very slowly and must be protected.',
  activities: [
    { sec: 'I. STAGES', img: 'soil_formation.gif', caption: 'Animation: from bare rock to deep soil.', q: 'What is the first stage of soil formation?', a: 'Weathering of the parent rock.', noProj: 'draw the five stages.' },
    { sec: 'II. FACTORS', img: 'clorpt_big.png', caption: 'Jenny\'s equation: the five factors.', q: 'Which factors are called active? Why?', a: 'Climate and organisms, because they drive the processes.', noProj: 'write S = f(Cl, O, R, P, T).' },
    { sec: 'II. ACTIVE FACTORS', img: 'f4_redsoil.jpg', caption: 'A deep red soil of the humid tropics.', q: 'How does a hot, wet climate affect soil formation?', a: 'It speeds up chemical weathering and gives deep, leached soils.', noProj: 'compare the south and the north.' },
    { sec: 'III. PASSIVE FACTORS', img: 'lsa_scree.jpg', caption: 'Steep mountain slopes.', q: 'How does relief affect soils?', a: 'Steep slopes have thin soils; valleys collect deep, wet soils.', noProj: 'compare hilltop and valley soils.' },
    { sec: 'III. PASSIVE FACTORS', img: 'lsa_fernlava.jpg', caption: 'A fern growing on young lava.', q: 'Why is time an important factor?', a: 'Soil forms very slowly, about 1 cm in 100 to 1,000 years.', noProj: 'compare new and old lava flows.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Pedogenesis:', 'It is the process of soil formation.'], ['Parent material:', 'It is the rock or deposit from which a soil forms.'], ['Jenny\'s equation:', 'It is S = f (Cl, O, R, P, T), which links soil to five factors.']] },
    { title: 'II. Stages', items: [['A. Weathering:', 'The parent rock breaks up into regolith. This gives the mineral part of the soil.'], ['B. Colonisation:', 'Lichens, mosses and plants grow and add organic matter. Humus begins to form.'], ['C. Maturity:', 'Water moves materials and horizons develop. A mature soil has a clear profile.']] },
    { title: 'III. Factors', items: [['A. Climate (active):', 'Temperature and rain control weathering and leaching. Hot, wet climates give deep, red, leached soils.'], ['B. Organisms (active):', 'Plants give humus, and animals mix the soil. Man also changes soils by farming.'], ['C. Relief, parent material, time (passive):', 'Slope controls depth and drainage, and rock controls texture and minerals. Time allows horizons to develop.']], draw: { img: 'clorpt_big.png', caption: 'Copy the factors.' } },
  ],
  evaluation: [['State Jenny\'s equation.', 'S = f (Cl, O, R, P, T): soil depends on climate, organisms, relief, parent material and time.'], ['Why are climate and organisms called active factors?', 'They drive the soil-forming processes.']],
  remediation: ['Soil formation is called ______.', 'The rock from which soil forms is the ______ material.', 'Soil forms very ______.'], remediationAnswers: '1. pedogenesis 2. parent 3. slowly',
  homework: 'Explain why the soils of Mount Cameroon differ from those of the Far North.', homeworkTag: 'This prepares Lesson 8: The Soil Profile.',
  bilingual: [['Soil formation', 'La pédogenèse'], ['Parent rock', 'La roche mère'], ['Climate', 'Le climat'], ['Relief', 'Le relief'], ['Time', 'Le temps'], ['Organism', "L'organisme"]],
});

L.push({ no: 8, title: 'The Soil Profile', topic: S2, subtopic: 'Soil Profile Development and Forming Processes',
  notions: 'Soil profile, horizon, O, A, E, B, C, R horizons, eluviation, illuviation.', focus: 'Meaning of soil profile; the ideal profile and its horizons; reasons for horizons.',
  competence: 'Learners are able to describe a soil profile and explain why soils have horizons.',
  objectives: ['Define soil profile and horizon.', 'Describe the ideal soil profile.', 'Explain why horizons form.'],
  recall: ['Soil forms in stages.', 'Water moves down through the soil.'],
  situation: 'During the building of a road near Dschang, learners see a fresh cutting with a dark layer at the top, a red layer in the middle and broken rock at the bottom.',
  sitQA: [['What is the problem in the situation?', 'Learners do not know why the soil has layers.'], ['What are these layers called?', 'Horizons.'], ['What is the whole section called?', 'A soil profile.']],
  justification: 'This lesson helps us to read soil profiles, which tell us how a soil formed and how it can be used.',
  activities: [
    { sec: 'I. THE IDEAL PROFILE', img: 'ideal_profile_big.png', caption: 'The ideal soil profile.', q: 'Name the horizons from the top to the bottom.', a: 'O, A, E, B, C and R.', noProj: 'draw the profile.' },
    { sec: 'I. THE IDEAL PROFILE', img: 'lsa_soilpit.jpg', caption: 'A real soil profile in a pit.', q: 'Which horizon is darkest? Why?', a: 'The A horizon, because it is rich in humus.', noProj: 'describe a road cutting.' },
    { sec: 'II. HORIZONS', img: 'lsa_litter.jpg', caption: 'Dead leaves on the surface.', q: 'Which horizon is made of dead leaves and humus?', a: 'The O (organic) horizon.', noProj: 'scrape the surface under a tree.' },
    { sec: 'III. REASONS', img: 'minor_processes_big.png', caption: 'Materials washed out and washed in.', q: 'Why is the E horizon pale and the B horizon rich in clay?', a: 'Water washes clay and iron out of E (eluviation) and leaves them in B (illuviation).', noProj: 'pour muddy water through sand.' },
    { sec: 'III. REASONS', img: 'soil_profile_big.png', caption: 'Weathering from the bottom and humus from the top.', q: 'Give two other reasons why horizons form.', a: 'Humus is added from the top, and weathering works from the rock below.', noProj: 'draw arrows on the profile.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil profile:', 'It is a vertical section of soil from the surface to the rock.'], ['Horizon:', 'It is a layer of the soil with its own colour, texture and structure.'], ['Eluviation:', 'It is the washing out of materials from a horizon.'], ['Illuviation:', 'It is the deposit of washed-in materials in a lower horizon.']] },
    { title: 'II. The Ideal Profile', items: [['A. O and A horizons:', 'O is fresh and rotting litter at the surface. A is dark topsoil with humus, roots and life.'], ['B. E and B horizons:', 'E is a pale layer that has lost clay and iron. B is the subsoil where clay, iron and humus collect.'], ['C. C and R horizons:', 'C is weathered parent rock. R is the solid bedrock.']] },
    { title: 'III. Why Horizons Form', items: [['A. Water movement:', 'Rain water carries materials down by eluviation and leaves them in B. In dry areas water can move salts upward.'], ['B. Additions and weathering:', 'Organic matter is added from the top. Weathering acts on the rock from below.'], ['C. Living things:', 'Roots and animals mix the upper layers. The profile depends on climate, time and relief.']], draw: { img: 'ideal_profile_big.png', caption: 'Copy the ideal profile.' } },
  ],
  evaluation: [['What is a soil profile?', 'A vertical section of soil from the surface to the rock.'], ['Distinguish eluviation and illuviation.', 'Eluviation washes materials out of a horizon; illuviation deposits them in a lower horizon.']],
  remediation: ['The dark topsoil is the ______ horizon.', 'Clay and iron collect in the ______ horizon.', 'The bedrock is the ______ horizon.'], remediationAnswers: '1. A 2. B 3. R',
  homework: 'Draw a soil profile seen in a road cutting near your home and label the horizons.', homeworkTag: 'This prepares Lesson 9: Major Pedogenic Regimes.',
  bilingual: [['Profile', 'Le profil'], ['Horizon', "L'horizon"], ['Topsoil', 'La couche arable'], ['Subsoil', 'Le sous-sol'], ['Bedrock', 'La roche en place'], ['Eluviation', "L'éluviation"]],
});

L.push({ no: 9, title: 'Major Pedogenic Regimes', topic: S2, subtopic: 'Soil Profile Development and Forming Processes',
  notions: 'Pedogenic regime, podsolisation, laterisation, calcification, salinisation, gleying.', focus: 'Meaning and classification; podsolisation, laterisation, calcification, salinisation and gleying: location, movement of materials, processes.',
  competence: 'Learners are able to explain the main soil-forming regimes and link them to climate zones.',
  objectives: ['Define a pedogenic regime.', 'Explain podsolisation and laterisation (downward movement).', 'Explain calcification, salinisation and gleying.'],
  recall: ['Water moves materials in the soil.', 'Climate is an active factor of soil formation.'],
  situation: 'A teacher shows photos of a red soil from Yaoundé, a grey soil from Canada and a salty white crust from an irrigated field in the Sahel. Learners ask why soils differ so much.',
  sitQA: [['What is the problem in the situation?', 'Soils in different climates look very different.'], ['What controls these differences?', 'The main soil-forming process (pedogenic regime), linked to climate.'], ['Name the regime of hot, wet tropics.', 'Laterisation.']],
  justification: 'This lesson helps us to understand the great soil types of the world and their problems.',
  activities: [
    { sec: 'I. CLASSIFICATION', img: 'pedogenic_big.png', caption: 'Five pedogenic regimes.', q: 'In which regimes does water move mainly down? In which does it move up?', a: 'Down: podsolisation and laterisation. Up: calcification and salinisation.', noProj: 'draw the five columns.' },
    { sec: 'II. PODSOLISATION', img: 'f2t_conifer.jpg', caption: 'A coniferous forest (taiga).', q: 'Why are soils under coniferous forests acid and leached?', a: 'Needles make acid humus, and rain washes iron and clay down.', noProj: 'find the taiga on a map.' },
    { sec: 'III. LATERISATION', img: 'f2t_laterite.jpg', caption: 'Laterite, a hard red layer.', q: 'Which elements stay in the soil during laterisation?', a: 'Iron and aluminium oxides; silica and bases are washed out.', noProj: 'describe laterite roads.' },
    { sec: 'IV. CALCIFICATION', img: 'lsa_steppe.jpg', caption: 'The dry steppe of Kazakhstan.', q: 'Why does calcium collect near the surface in steppe soils?', a: 'Rain is low, so calcium is not washed away and evaporation brings it up.', noProj: 'find the steppes on a map.' },
    { sec: 'V. SALINISATION', img: 'f2t_salt_crust.jpg', caption: 'A salt crust on dry land.', q: 'How can irrigation cause salinisation?', a: 'Water evaporates and leaves salts at the surface.', noProj: 'describe salty wells in the north.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Pedogenic regime:', 'It is the main process that gives a soil its character.'], ['Leaching:', 'It is the washing down of dissolved minerals by water.'], ['Capillary rise:', 'It is the upward movement of water in small pores.']] },
    { title: 'II. Downward Movement', items: [['A. Podsolisation:', 'It happens in cold, wet climates under coniferous forests. Acid water leaches iron and humus from the E horizon into B.'], ['B. Laterisation:', 'It happens in hot, wet tropics. Silica and bases are leached, and iron and aluminium oxides stay and form red soils or laterite.']] },
    { title: 'III. Upward Movement and Waterlogging', items: [['A. Calcification:', 'It happens in semi-arid grasslands like the steppe. Calcium collects in the upper soil and gives fertile black soils.'], ['B. Salinisation:', 'It happens in hot, dry areas and irrigated land. Evaporation draws water up and leaves salts at the surface.'], ['C. Gleying:', 'It happens where soils are waterlogged. Lack of air turns iron grey-blue.']], draw: { img: 'pedogenic_big.png', caption: 'Copy the diagram.' } },
  ],
  evaluation: [['Where does laterisation occur? Which elements stay?', 'In hot, wet tropics; iron and aluminium oxides stay.'], ['Explain salinisation.', 'In dry areas, evaporation draws water up and leaves salts at the surface.']],
  remediation: ['The regime of the taiga is ______.', 'The regime of the humid tropics is ______.', 'Grey waterlogged soils form by ______.'], remediationAnswers: '1. podsolisation 2. laterisation 3. gleying',
  homework: 'Copy the pedogenic diagram and give one climate for each regime.', homeworkTag: 'This prepares Lesson 10: Minor Soil Forming Processes.',
  bilingual: [['Podsolisation', 'La podzolisation'], ['Laterisation', 'La latéritisation'], ['Calcification', 'La calcification'], ['Salinisation', 'La salinisation'], ['Gleying', "L'hydromorphie (gley)"], ['Crust', 'La croûte']],
});

L.push({ no: 10, title: 'Minor Soil Forming Processes', topic: S2, subtopic: 'Soil Profile Development and Forming Processes',
  notions: 'Weathering, eluviation, lessivage, leaching, illuviation, organic sorting, capillary action, translocation.', focus: 'Weathering; eluviation (lessivage and leaching); illuviation; organic sorting; capillary action; translocation.',
  competence: 'Learners are able to explain the small processes that move and change materials in soils.',
  objectives: ['Explain weathering and translocation.', 'Distinguish eluviation, leaching, lessivage and illuviation.', 'Explain organic sorting and capillary action.'],
  recall: ['Horizons form because materials move.', 'Pedogenic regimes depend on climate.'],
  situation: 'A learner fills a bottle with soil, pours water on it and sees brown water coming out at the bottom. He asks what the water took from the soil.',
  sitQA: [['What is the problem in the situation?', 'Water removes materials from the soil.'], ['What is this washing out called?', 'Eluviation (leaching for dissolved matter).'], ['Where do these materials go?', 'Lower down, where they can be deposited (illuviation).']],
  justification: 'This lesson helps us to understand the processes that build soil horizons and change fertility.',
  activities: [
    { sec: 'I. PROCESSES', img: 'minor_processes_big.png', caption: 'The minor soil forming processes.', q: 'Distinguish leaching and lessivage.', a: 'Leaching removes dissolved minerals; lessivage carries fine clay particles in suspension.', noProj: 'filter muddy and salty water.' },
    { sec: 'II. WEATHERING', img: 'f4_rust.jpg', caption: 'Rust: iron oxidised by air and water.', q: 'Which weathering process gives red soils?', a: 'Oxidation of iron.', noProj: 'show rusty metal.' },
    { sec: 'III. LEACHING', img: 'f2t_rainforest.jpg', caption: 'The humid rainforest.', q: 'Why is leaching strong under rainforest?', a: 'Heavy rain moves down through the soil all year.', noProj: 'compare with the Sahel.' },
    { sec: 'IV. ORGANIC SORTING', img: 'lsa_earthworm.jpg', caption: 'An earthworm in the soil.', q: 'How do worms sort and mix the soil?', a: 'They carry fine soil and humus up and down through their tunnels.', noProj: 'look for worm casts.' },
    { sec: 'V. CAPILLARY ACTION', img: 'f2t_salt_crust.jpg', caption: 'A white salt crust.', q: 'How does capillary action form this crust?', a: 'Water rises in small pores, evaporates and leaves salts.', noProj: 'dip a sugar cube in coloured water.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Translocation:', 'It is the movement of materials from one part of the soil to another.'], ['Lessivage:', 'It is the washing down of fine clay particles in suspension.'], ['Organic sorting:', 'It is the mixing and sorting of soil by living organisms.']] },
    { title: 'II. Downward Processes', items: [['A. Weathering:', 'Rock breaks down by physical, chemical and biological weathering. It supplies minerals and clay.'], ['B. Eluviation and leaching:', 'Eluviation washes materials out of a horizon. Leaching removes minerals in solution and makes soils acid.'], ['C. Illuviation:', 'Washed-down materials are deposited in a lower horizon. The B horizon becomes rich in clay, iron or humus.']] },
    { title: 'III. Other Processes', items: [['A. Organic sorting:', 'Worms, termites and roots mix the soil and move particles. They form crumbs and pores.'], ['B. Capillary action:', 'In dry periods water rises through small pores. It brings salts or calcium to the surface.'], ['C. Translocation:', 'All these processes move materials inside the soil. Together they create horizons.']] },
  ],
  evaluation: [['Distinguish eluviation and illuviation.', 'Eluviation washes materials out of a horizon; illuviation deposits them in a lower horizon.'], ['What is capillary action?', 'The rise of water through small pores, leaving salts when it evaporates.']],
  remediation: ['Removal of dissolved minerals is ______.', 'Movement of clay in suspension is ______.', 'Mixing by worms is organic ______.'], remediationAnswers: '1. leaching 2. lessivage 3. sorting',
  homework: 'Pour water through soil in a bottle and describe the water that comes out.', homeworkTag: 'This prepares Lesson 11: Classes of Soil.',
  bilingual: [['Leaching', 'Le lessivage (dissolution)'], ['Suspension', 'La suspension'], ['Capillary', 'Capillaire'], ['Salt', 'Le sel'], ['Oxidation', "L'oxydation"], ['Translocation', 'La migration']],
});

L.push({ no: 11, title: 'Classes of Soil', topic: S2, subtopic: 'Classification of Soils',
  notions: 'Soil classification, zonal, intrazonal, azonal soils.', focus: 'Basis of classification; zonal, intrazonal and azonal soils: meaning and characteristics.',
  competence: 'Learners are able to classify soils into zonal, intrazonal and azonal groups with examples.',
  objectives: ['Explain the basis of soil classification.', 'Describe zonal soils.', 'Describe intrazonal and azonal soils.'],
  recall: ['Climate controls the main pedogenic regimes.', 'Young soils have few horizons.'],
  situation: 'Along the Logone, farmers grow rice on grey, wet soils, while a few kilometres away the soils are dry and sandy. On the slopes of Mount Cameroon, young ash soils have no clear layers.',
  sitQA: [['What is the problem in the situation?', 'Soils in the same region are very different.'], ['Why are the Logone soils grey and wet?', 'They are waterlogged (a local factor).'], ['How are soils grouped?', 'Into zonal, intrazonal and azonal soils.']],
  justification: 'This lesson helps us to classify soils and understand why they differ even in the same climate.',
  activities: [
    { sec: 'I. BASIS', img: 'soil_classes_big.png', caption: 'The three classes of soil.', q: 'On what basis are soils divided into zonal, intrazonal and azonal?', a: 'On the main factor that formed them and on their maturity.', noProj: 'draw the three boxes.' },
    { sec: 'II. ZONAL SOILS', img: 'f4_redsoil.jpg', caption: 'A ferrallitic soil of the humid tropics.', q: 'Why is this a zonal soil?', a: 'It was formed mainly by the climate and vegetation of its zone.', noProj: 'match soils to climate zones.' },
    { sec: 'III. INTRAZONAL SOILS', img: 'f2t_rice_field.jpg', caption: 'Rice on a waterlogged soil.', q: 'Why are waterlogged soils called intrazonal?', a: 'A local factor (water) is stronger than the climate.', noProj: 'describe swampy valleys.' },
    { sec: 'IV. AZONAL SOILS', img: 'f4_floodplain.jpg', caption: 'A river floodplain.', q: 'Why are alluvial soils azonal?', a: 'They are young, new layers of mud with no clear horizons.', noProj: 'describe fields beside a river.' },
    { sec: 'IV. AZONAL SOILS', img: 'lsa_pahoehoe.jpg', caption: 'Young lava.', q: 'Why are soils on young lava or ash azonal?', a: 'There has not been enough time for horizons to form.', noProj: 'mention Mount Cameroon lava flows.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Zonal soils:', 'They are mature soils formed mainly by the climate and vegetation of a zone.'], ['Intrazonal soils:', 'They are soils formed mainly by a local factor such as water, salt or rock.'], ['Azonal soils:', 'They are young soils without clear horizons.']] },
    { title: 'II. Basis of Classification', items: [['A. Genetic basis:', 'Soils are grouped by the factor and process that formed them. The profile and maturity are also used.'], ['B. Other bases:', 'Soils can also be grouped by texture, colour or use. International systems like the FAO use detailed classes.']] },
    { title: 'III. Characteristics', items: [['A. Zonal:', 'They have well-developed horizons and follow climate zones. Examples are ferrallitic soils, podsols and chernozems.'], ['B. Intrazonal:', 'A local factor is stronger than the climate. Examples are hydromorphic, saline and limestone soils.'], ['C. Azonal:', 'They are young and have little profile development. Examples are alluvial, volcanic ash and mountain soils.']], draw: { img: 'soil_classes_big.png', caption: 'Copy the three classes.' } },
  ],
  evaluation: [['Distinguish zonal and azonal soils.', 'Zonal soils are mature and follow climate; azonal soils are young without clear horizons.'], ['Give one example of each class.', 'Zonal: ferrallitic; intrazonal: hydromorphic; azonal: alluvial.']],
  remediation: ['Soils formed by climate are ______.', 'Waterlogged soils are ______.', 'Alluvial soils are ______.'], remediationAnswers: '1. zonal 2. intrazonal 3. azonal',
  homework: 'Give one zonal, one intrazonal and one azonal soil found in Cameroon.', homeworkTag: 'This prepares Further Study 1: Soils of Cameroon.',
  bilingual: [['Classification', 'La classification'], ['Zonal', 'Zonal'], ['Alluvial', 'Alluvial'], ['Waterlogged', 'Engorgé d\'eau'], ['Mature', 'Évolué'], ['Young', 'Jeune']],
});

L.push({ kind: 'Further Study', no: 1, title: 'Soils of Cameroon', topic: S3, subtopic: 'Soil Types and their Characteristics',
  notions: 'Ferrallitic, ferruginous, tropical black earths, alluvial, volcanic, mountain, hydromorphic soils.', focus: 'Zonal soils (ferrallitic, ferruginous, black earths); azonal soils (alluvial, volcanic, mountain); intrazonal hydromorphic soils; characteristics and location.',
  competence: 'Learners are able to locate the soils of Cameroon and describe their characteristics and uses.',
  objectives: ['Locate the main soils of Cameroon on a map.', 'Describe zonal soils and their characteristics.', 'Describe azonal and intrazonal soils and their uses.'],
  recall: ['Soils are zonal, intrazonal or azonal.', 'Laterisation happens in hot, wet climates.'],
  situation: 'A cocoa buyer notices that cocoa grows well around Mbalmayo, Arabica coffee in the West, cotton in the North and rice along the Logone. He asks if the soils explain this.',
  sitQA: [['What is the problem in the situation?', 'Different crops grow in different regions.'], ['What soil is found around Mbalmayo?', 'Red ferrallitic soil.'], ['Why is the West good for coffee?', 'It has fertile volcanic soils.']],
  justification: 'This further study helps us to know our country\'s soils and to use them wisely.',
  activities: [
    { sec: 'I. DISTRIBUTION', img: 'cameroon_soils_big.png', caption: 'The main soils of Cameroon (simplified).', q: 'Which soil covers most of southern Cameroon?', a: 'Ferrallitic (red) soils.', noProj: 'draw Cameroon and shade the soils.' },
    { sec: 'II. ZONAL SOILS', img: 'f4_redsoil.jpg', caption: 'A red ferrallitic soil.', q: 'Give two characteristics of ferrallitic soils.', a: 'Deep, red, acid and leached (poor in bases).', noProj: 'describe soils around Yaoundé.' },
    { sec: 'II. ZONAL SOILS', img: 'f2t_black_soil.jpg', caption: 'A dark soil.', q: 'Where are tropical black earths found? What are they used for?', a: 'In the Far North plains (karal); they are used for dry-season sorghum (muskwari).', noProj: 'mention karal soils near Maroua.' },
    { sec: 'III. AZONAL SOILS', img: 'f2t_tea_highlands.jpg', caption: 'Farms on fertile highland soils.', q: 'Why are volcanic soils of the West so fertile?', a: 'They are rich in minerals from basalt and ash.', noProj: 'list crops of the West.' },
    { sec: 'IV. INTRAZONAL SOILS', img: 'f4_ricefield.jpg', caption: 'A flooded rice field.', q: 'Which soils are used for rice along the Logone? Why?', a: 'Hydromorphic soils: they are waterlogged and hold water.', noProj: 'mention SEMRY at Yagoua.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Ferrallitic soil:', 'It is a deep, red, leached soil of the humid tropics.'], ['Ferruginous soil:', 'It is a red-brown soil of the tropical wet and dry zone.'], ['Hydromorphic soil:', 'It is a soil formed under waterlogging.']] },
    { title: 'II. Zonal Soils', items: [['A. Ferrallitic soils:', 'They cover the south and east, under forest and heavy rain. They are deep and red but acid and poor, so they need care.'], ['B. Ferruginous soils:', 'They are found in the Adamawa and the North, with one rainy season. They are less leached but form hard crusts.'], ['C. Tropical black earths:', 'They occur on the plains of the Far North. They are clayey, crack in the dry season and are used for muskwari.']] },
    { title: 'III. Azonal and Intrazonal Soils', items: [['A. Volcanic soils:', 'They are found in the West, North-West and around Mount Cameroon. They are very fertile and grow coffee, tea, bananas and food crops.'], ['B. Alluvial and mountain soils:', 'Alluvial soils lie along rivers like the Benue and are fertile. Mountain soils are thin and stony on steep slopes.'], ['C. Hydromorphic soils:', 'They are found in the Logone floodplain and swampy valleys. They are used for rice.']], draw: { img: 'cameroon_soils_big.png', caption: 'Copy the map.' } },
  ],
  evaluation: [['Name the three zonal soils of Cameroon.', 'Ferrallitic, ferruginous and tropical black earths.'], ['Why are volcanic soils important in the West?', 'They are very fertile and support coffee, tea and food crops.']],
  remediation: ['Southern Cameroon has ______ soils.', 'Muskwari grows on tropical black ______.', 'Rice along the Logone grows on ______ soils.'], remediationAnswers: '1. ferrallitic 2. earths 3. hydromorphic',
  homework: 'Draw the soil map of Cameroon and write one crop for each soil.', homeworkTag: 'This prepares Lesson 12: Meaning of Natural Vegetation.',
  bilingual: [['Ferrallitic soil', 'Le sol ferrallitique'], ['Ferruginous soil', 'Le sol ferrugineux'], ['Volcanic soil', 'Le sol volcanique'], ['Alluvial soil', 'Le sol alluvial'], ['Black earth', 'Le vertisol (karal)'], ['Floodplain', "La plaine d'inondation"]],
});

module.exports = { L, B };
if (require.main === module) run(L, B, process.argv.slice(2).length ? process.argv.slice(2) : null);
