// UPPER SIXTH ARTS — ECONOMIC GEOGRAPHY part 3: TRANSPORT AND TOURISM (Module 6: lessons 27–31, PW4, PW5, FS6, FS7).
const { run } = require('./sixth');
const { B } = require('./v2_usa_eco1');
const T1 = 'Transport Activities and Characteristics', T2 = 'Transport Network Development', TR = 'Tourism Activities', T6 = 'Geography of Cameroon';
const L = [];

L.push({ no: 27, title: 'Transport', topic: T1, subtopic: 'Modes of Transport',
  notions: 'Transport, mode, head portage, road, rail, inland waterway, ocean transport, containerisation, air transport, pipeline, cable way.', focus: 'Meaning of transport; land, water, air and other modes (characteristics, factors of development, advantages and disadvantages); general importance of transport.',
  competence: 'Learners are able to describe the modes of transport, compare them and explain the importance of transport.',
  objectives: ['Define transport and classify its modes.', 'Compare the advantages and disadvantages of each mode.', 'Explain the importance of transport.'],
  recall: ['Goods and people move from one place to another.', 'Cameroon has roads, a railway, ports and airports.'],
  situation: 'A trader in Garoua must send 20 tonnes of cotton to Douala. She can use a truck, the train from Ngaoundéré or a boat on the Benue in the rainy season. Each choice has a different cost and speed.',
  sitQA: [['What is the problem in the situation?', 'The trader must choose the best mode of transport.'], ['Name the three modes in the situation.', 'Road, rail and river transport.'], ['What should guide her choice?', 'Cost, speed, safety and the nature of the goods.']],
  justification: 'This lesson helps us to choose the best transport for people and goods.',
  activities: [
    { sec: 'I. MEANING', img: 'usa_truck.jpg', caption: 'A loaded pick-up on a rural road.', q: 'What is transport?', a: 'The movement of people and goods from one place to another.', noProj: 'list ways people travel in your village.' },
    { sec: 'II. LAND TRANSPORT', img: 'f2t_moto_taxi.jpg', caption: 'Motorbike taxis.', q: 'Give one advantage and one disadvantage of motorbike taxis.', a: 'Advantage: they reach places cars cannot. Disadvantage: many accidents.', noProj: 'discuss motorbike taxis in your town.' },
    { sec: 'III. WATER TRANSPORT', img: 'usa_container.jpg', caption: 'A container port.', q: 'What is containerisation?', a: 'Carrying goods in standard metal boxes that move easily between ships, trains and trucks.', noProj: 'describe a container.' },
    { sec: 'IV. AIR AND OTHERS', img: 'usa_airport.jpg', caption: 'An aircraft at an airport.', q: 'Which goods travel by air, and why?', a: 'Light, valuable or perishable goods like flowers and medicines, because air is fast.', noProj: 'list air goods.' },
    { sec: 'V. COMPARISON', img: 'modes_big.png', caption: 'Advantages and disadvantages of modes.', q: 'Why is rail better than road for heavy goods over long distances?', a: 'It carries large loads cheaply over long distances.', noProj: 'read the table.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Transport:', 'It is the movement of people and goods from one place to another.'], ['Mode of transport:', 'It is a means of transport, like road, rail, water, air or pipeline.'], ['Containerisation:', 'It is the carrying of goods in standard metal boxes moved between ships, trains and trucks.']] },
    { title: 'II. Modes of Transport', items: [['A. Land:', 'Head portage is cheap but slow. Road is flexible and door to door, while rail carries heavy loads far and cheaply.'], ['B. Water:', 'Inland waterways use rivers and canals, and ocean ships carry most world trade. It is cheap for bulky goods but slow.'], ['C. Air:', 'Air transport is the fastest mode for people and valuable goods. It is very costly and needs airports.'], ['D. Others:', 'Pipelines carry oil, gas and water continuously. Cable ways cross mountains and valleys.']], draw: { img: 'modes_big.png', caption: 'Copy the table.' } },
    { title: 'III. Factors and Importance', items: [['A. Factors:', 'Relief, climate, capital, technology and the demand for transport affect each mode. Government policy also matters.'], ['B. Importance:', 'Transport links producers and markets and creates jobs. It also helps national unity and tourism.']] },
  ],
  evaluation: [['Give one advantage and one disadvantage of road and rail transport.', 'Road: door to door, but costly over long distances. Rail: heavy loads, but fixed routes.'], ['Give three importance of transport.', 'Links markets, creates jobs and helps national unity.']],
  remediation: ['Carrying loads on the head is head ______.', 'The fastest mode is ______ transport.', 'Oil is often carried by ______.'], remediationAnswers: '1. portage 2. air 3. pipeline',
  homework: 'Choose the best mode to carry cattle from Ngaoundéré to Yaoundé and justify your choice.', homeworkTag: 'This prepares Practical Work 4: Transport Costs.',
  bilingual: [['Transport', 'Le transport'], ['Road', 'La route'], ['Railway', 'Le chemin de fer'], ['Port', 'Le port'], ['Airport', "L'aéroport"], ['Pipeline', "L'oléoduc"]],
});

L.push({ kind: 'Practical Work', no: 4, title: 'Calculating and Illustrating Transport Costs', topic: T1, subtopic: 'Transport Costs Structures',
  notions: 'Terminal cost, line-haul cost, total cost, tapering, freight rate, break-of-bulk.', focus: 'Types of transport costs; relative cost structure of modes; distance and cost relationships; transport cost and the nature of the commodity.',
  competence: 'Learners are able to calculate transport costs and draw cost-distance graphs.',
  objectives: ['Distinguish terminal and line-haul costs.', 'Calculate total transport cost for different modes.', 'Draw and interpret cost-distance graphs.'],
  recall: ['Road, rail and water are modes of transport.', 'A line graph shows how one value changes with another.'],
  situation: 'A company in Garoua must send cement 300 km. The truck company, the railway and a river boat each give a price list. The class must find the cheapest mode.',
  sitQA: [['What is the problem in the situation?', 'The class must compare transport costs.'], ['Which two costs make up the total?', 'Terminal cost and line-haul (distance) cost.'], ['Which mode is best for very long distances?', 'Usually water transport.']],
  justification: 'This practical work helps us to calculate and compare transport costs.',
  activities: [
    { sec: 'I. TYPES OF COSTS', img: 'transport_costs_big.png', caption: 'Cost-distance lines of three modes.', q: 'What is a terminal cost?', a: 'The fixed cost of loading, unloading and handling, paid whatever the distance.', noProj: 'list terminal costs.' },
    { sec: 'II. CALCULATION', img: 'pw_transport_big.png', caption: 'Worked example (hypothetical values).', q: 'Calculate the road cost for 300 km.', a: '2,000 + (60 × 300) = 20,000 F per tonne.', noProj: 'calculate each mode.' },
    { sec: 'II. RELATIVE COSTS', img: 'transport_costs_big.png', caption: 'Where each line is lowest.', q: 'Why is road cheapest for short distances?', a: 'It has the lowest terminal cost.', noProj: 'find the crossing points.' },
    { sec: 'III. DISTANCE AND COST', img: 'tapering_big.png', caption: 'Tapering freight rates.', q: 'What does "tapering" mean?', a: 'The cost per kilometre falls as the distance increases.', noProj: 'explain tapering.' },
    { sec: 'IV. NATURE OF GOODS', img: 'f2t_logging_truck.jpg', caption: 'A logging truck.', q: 'Why do bulky or perishable goods cost more to carry?', a: 'Bulky goods need more space and perishable goods need speed or cooling.', noProj: 'compare logs and flowers.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Terminal cost:', 'It is the fixed cost of loading, unloading and handling goods.'], ['Line-haul cost:', 'It is the cost of moving goods along the route, which rises with distance.'], ['Tapering:', 'It is the fall in the cost per kilometre as distance increases.']] },
    { title: 'II. Method', items: [['A. Formula:', 'Total cost = terminal cost + (line cost × distance). Calculate it for each mode.'], ['B. Graph:', 'Plot distance on the x-axis and cost on the y-axis. Draw one line per mode.'], ['C. Reading:', 'Road is cheapest for short trips, rail for medium and water for long trips. The crossing points show where the best mode changes.']], draw: { img: 'transport_costs_big.png', caption: 'Copy the graph.' } },
    { title: 'III. Cost and Commodity', items: [['A. Nature of goods:', 'Bulky, fragile, perishable or dangerous goods cost more to carry. Valuable light goods can pay for air transport.'], ['B. Break-of-bulk:', 'Changing mode adds terminal costs. Industries often locate at these break-of-bulk points.']] },
  ],
  evaluation: [['Rail: terminal 6,000 F, line 30 F/km. Find the cost for 500 km.', '6,000 + (30 × 500) = 21,000 F.'], ['Why is water transport cheapest over long distances?', 'Its line cost is very low, so its high terminal cost is shared over many kilometres.']],
  remediation: ['Loading and unloading make the ______ cost.', 'The fall in cost per km with distance is ______.', 'The cheapest mode for short distances is ______.'], remediationAnswers: '1. terminal 2. tapering 3. road',
  homework: 'Draw the cost-distance graph for road, rail and river using the table, up to 600 km.', homeworkTag: 'This prepares Lesson 28: Transport Networks.',
  bilingual: [['Cost', 'Le coût'], ['Distance', 'La distance'], ['Freight', 'Le fret'], ['Loading', 'Le chargement'], ['Graph', 'Le graphique'], ['Perishable', 'Périssable']],
});

L.push({ no: 28, title: 'Transport Networks', topic: T2, subtopic: 'Transport Network Development',
  notions: 'Network, node, link, route, connectivity, network evolution.', focus: 'Meaning of transport networks (definition, nodes, links and types); general factors of network development; network prediction and evolution (increasing connectivity).',
  competence: 'Learners are able to describe transport networks and explain the factors of their development.',
  objectives: ['Define a network, a node and a link.', 'Identify types of networks.', 'Explain the factors of network development and evolution.'],
  recall: ['Roads join towns.', 'Some regions have many roads and others few.'],
  situation: 'On a road map of Cameroon, the class sees many roads joining the towns of the West and Littoral, but few roads in the East and the Far North. They ask why the network is so uneven.',
  sitQA: [['What is the problem in the situation?', 'The road network is uneven.'], ['What are the towns called in a network?', 'Nodes.'], ['What are the roads called?', 'Links (edges).']],
  justification: 'This lesson helps us to understand how transport networks form and grow.',
  activities: [
    { sec: 'I. MEANING', img: 'network_terms_big.png', caption: 'Nodes and links of a network.', q: 'Count the nodes and links in the network.', a: '6 nodes and 7 links.', noProj: 'draw a simple network.' },
    { sec: 'I. TYPES', img: 'beta_scale_big.png', caption: 'Branching and circuit networks.', q: 'Distinguish a branching network from a circuit network.', a: 'Branching: no closed loops. Circuit: loops give more than one route between nodes.', noProj: 'draw both types.' },
    { sec: 'II. FACTORS', img: 'f2t_muddy_road.jpg', caption: 'A muddy road in the rainy season.', q: 'How does relief or climate affect network development?', a: 'Mountains, swamps and heavy rain make roads costly to build and keep.', noProj: 'discuss roads in your area.' },
    { sec: 'II. FACTORS', img: 'usa_traffic.jpg', caption: 'Busy town traffic.', q: 'Why do dense and rich regions have dense networks?', a: 'There is more demand and more money to build roads.', noProj: 'compare two regions.' },
    { sec: 'III. EVOLUTION', img: 'taaffe_big.png', caption: 'Stages of network growth.', q: 'How does a network evolve over time?', a: 'New links are added, so connectivity increases and loops form.', noProj: 'describe the four boxes.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Transport network:', 'It is a system of routes joining places.'], ['Node:', 'It is a point in a network, like a town or junction.'], ['Link:', 'It is a route joining two nodes, like a road or railway.']] },
    { title: 'II. Types and Factors', items: [['A. Types:', 'Networks can be branching (tree) or circuit (with loops). They can also be road, rail, air or water networks.'], ['B. Physical factors:', 'Relief, rivers, swamps and climate affect where routes are built. Flat land is cheaper to build on.'], ['C. Human factors:', 'Population, economic activity, capital, technology and politics affect density. History, like colonial railways, also matters.']], draw: { img: 'network_terms_big.png', caption: 'Copy the network.' } },
    { title: 'III. Network Evolution', items: [['A. Meaning:', 'Network evolution is the growth of a network over time. New links increase connectivity.'], ['B. Prediction:', 'Links usually grow towards big nodes and rich areas. Models like Taaffe, Morrill and Gould describe the stages.']] },
  ],
  evaluation: [['Define node and link.', 'A node is a point such as a town; a link is a route joining two nodes.'], ['Give two physical and two human factors of network development.', 'Physical: relief, climate. Human: population, capital.']],
  remediation: ['A town in a network is a ______.', 'A road joining two towns is a ______.', 'A network with loops is a ______ network.'], remediationAnswers: '1. node 2. link 3. circuit',
  homework: 'Draw the main road network of your region and count its nodes and links.', homeworkTag: 'This prepares Lesson 29: Transport Network Efficiency.',
  bilingual: [['Network', 'Le réseau'], ['Node', 'Le nœud'], ['Link', 'Le lien'], ['Junction', 'Le carrefour'], ['Route', "L'itinéraire"], ['Connectivity', 'La connectivité']],
});

L.push({ no: 29, title: 'Transport Network Efficiency', topic: T2, subtopic: 'Transport Network Efficiency',
  notions: 'Efficiency, connectivity, density, accessibility, network deviation, detour index.', focus: 'Meaning; indices of efficiency (connectivity, density, extent, rate of flow, fineness, flexibility, technology); connectivity (meaning, user and builder costs, network deviations); factors.',
  competence: 'Learners are able to explain the efficiency of networks and the factors of connectivity.',
  objectives: ['Define network efficiency and connectivity.', 'Describe the indices of efficiency.', 'Explain user and builder costs and the factors of connectivity.'],
  recall: ['A network has nodes and links.', 'A circuit network has loops.'],
  situation: 'To travel from Garoua to Bertoua, a driver must go round through Ngaoundéré because there is no direct road. The trip is long and costly.',
  sitQA: [['What is the problem in the situation?', 'The network is not well connected.'], ['What is the extra distance called?', 'A network deviation (detour).'], ['How can it be reduced?', 'By building a more direct link.']],
  justification: 'This lesson helps us to judge how well a transport network works.',
  activities: [
    { sec: 'I. MEANING', img: 'network_terms_big.png', caption: 'A simple network.', q: 'What is network efficiency?', a: 'How well a network moves people and goods quickly and cheaply between places.', noProj: 'define efficiency.' },
    { sec: 'II. INDICES', img: 'beta_scale_big.png', caption: 'Beta index and connectivity.', q: 'Name three indices of network efficiency.', a: 'Connectivity, density and rate of flow (also extent, fineness, flexibility).', noProj: 'list indices.' },
    { sec: 'III. USER AND BUILDER COSTS', img: 'usa_truck.jpg', caption: 'Road transport.', q: 'Distinguish user cost and builder cost.', a: 'User cost: paid by travellers (time, fuel). Builder cost: paid to build and maintain routes.', noProj: 'discuss who pays.' },
    { sec: 'III. NETWORK DEVIATIONS', img: 'f2t_muddy_road.jpg', caption: 'A difficult road.', q: 'Why do routes deviate from straight lines?', a: 'To avoid mountains, swamps or to pass through towns (positive deviation).', noProj: 'find a detour on a map.' },
    { sec: 'IV. FACTORS', img: 'cmr_transport_big.png', caption: 'Main transport routes of Cameroon.', q: 'Give two factors of connectivity in Cameroon.', a: 'Relief and level of development (also capital and history).', noProj: 'read the map.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Network efficiency:', 'It is how well a network moves people and goods quickly and cheaply.'], ['Connectivity:', 'It is the degree to which the nodes of a network are joined together.'], ['Network deviation:', 'It is the extra length of a route compared with a straight line.']] },
    { title: 'II. Indices of Efficiency', items: [['A. Structure:', 'Connectivity, density (length per area) and extent measure the shape of a network. Fineness shows how closely links are spaced.'], ['B. Use:', 'Rate of flow and flexibility measure traffic and choice of routes. Technology such as tarred roads also raises efficiency.']], draw: { img: 'beta_scale_big.png', caption: 'Copy the three networks.' } },
    { title: 'III. Connectivity', items: [['A. User and builder costs:', 'Users want direct links that save time and fuel. Builders want few short links that cost less to build.'], ['B. Deviations:', 'Negative deviations avoid obstacles like hills and swamps. Positive deviations go through towns to collect traffic.'], ['C. Factors:', 'Relief, size and shape of region, population, development, capital and technology affect connectivity. Politics and history also play a role.']] },
  ],
  evaluation: [['Define connectivity and give two indices of efficiency.', 'The degree to which nodes are joined; density and rate of flow.'], ['Distinguish positive and negative deviation.', 'Positive: to pass through towns. Negative: to avoid obstacles.']],
  remediation: ['The degree to which nodes are joined is ______.', 'Costs paid by travellers are ______ costs.', 'A detour around a hill is a ______ deviation.'], remediationAnswers: '1. connectivity 2. user 3. negative',
  homework: 'Measure the straight-line and road distances between two towns and find the detour index.', homeworkTag: 'This prepares Practical Work 5: Measuring Network Efficiency.',
  bilingual: [['Efficiency', "L'efficacité"], ['Density', 'La densité'], ['Detour', 'Le détour'], ['Flow', 'Le flux'], ['Builder', 'Le constructeur'], ['User', "L'usager"]],
});

L.push({ kind: 'Practical Work', no: 5, title: 'Measuring Transport Network Efficiency', topic: T2, subtopic: 'Transport Network Efficiency',
  notions: 'Beta index, accessibility matrix, Shimbel index, König number, topological map.', focus: 'Connectivity (beta index); centrality with the accessibility matrix (König number, Shimbel index); techniques of mapping transport networks.',
  competence: 'Learners are able to calculate connectivity and accessibility indices and map a network.',
  objectives: ['Calculate the beta index.', 'Build an accessibility matrix and find Shimbel and König values.', 'Draw a topological map of a network.'],
  recall: ['A network has nodes and links.', 'Connectivity shows how well nodes are joined.'],
  situation: 'The Regional Delegation of Public Works wants to know which town in a small road network is the most accessible, to build a market there. The class receives a simple map of four towns and five roads.',
  sitQA: [['What is the problem in the situation?', 'The class must find the most accessible town.'], ['Which index shows connectivity?', 'The beta index.'], ['Which index shows accessibility?', 'The Shimbel index (and König number).']],
  justification: 'This practical work helps us to measure network efficiency with simple indices.',
  activities: [
    { sec: 'I. BETA INDEX', img: 'network_terms_big.png', caption: 'A network of 6 nodes and 7 links.', q: 'Calculate the beta index.', a: 'β = links ÷ nodes = 7 ÷ 6 = 1.17.', noProj: 'count and divide.' },
    { sec: 'I. INTERPRETATION', img: 'beta_scale_big.png', caption: 'Beta scale.', q: 'What does β = 1.17 mean?', a: 'More than 1: the network has circuits and is fairly well connected.', noProj: 'compare with the scale.' },
    { sec: 'II. ACCESSIBILITY MATRIX', img: 'shimbel_big.png', caption: 'Accessibility matrix of four towns.', q: 'How is each cell of the matrix filled?', a: 'With the number of links on the shortest path between the two towns.', noProj: 'fill the matrix.' },
    { sec: 'II. SHIMBEL AND KÖNIG', img: 'shimbel_big.png', caption: 'Shimbel and König values.', q: 'Which towns are the most accessible, and why?', a: 'B and D: they have the lowest Shimbel total (3) and König number (1).', noProj: 'add the rows.' },
    { sec: 'III. MAPPING', img: 'cmr_transport_big.png', caption: 'Transport routes of Cameroon.', q: 'What is a topological map?', a: 'A simplified map that shows only nodes and links, not true distances or shapes.', noProj: 'simplify a road map.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Beta index:', 'It is the number of links divided by the number of nodes.'], ['Shimbel index:', 'It is the total number of links on the shortest paths from one node to all others.'], ['König number:', 'It is the largest number of links from one node to the farthest node.']] },
    { title: 'II. Method', items: [['A. Beta index:', 'β = e ÷ v, with e links and v nodes. Below 1 is branching, 1 is one circuit and above 1 is well connected.'], ['B. Matrix:', 'Write the nodes in rows and columns and enter the shortest path in links. Add each row to get the Shimbel index.'], ['C. König number:', 'Take the largest value in each row. The lowest König and Shimbel values show the most central node.']], draw: { img: 'shimbel_big.png', caption: 'Copy the matrix.' } },
    { title: 'III. Mapping and Limits', items: [['A. Mapping:', 'Draw a topological map with dots for nodes and straight lines for links. Flow lines can show traffic volume.'], ['B. Limits:', 'The indices ignore distance, road quality and traffic. They measure structure, not real travel time.']] },
  ],
  evaluation: [['A network has 8 nodes and 6 links. Find β and interpret it.', 'β = 6 ÷ 8 = 0.75: a branching, poorly connected network.'], ['In the matrix, why is A less accessible than B?', 'A has a higher Shimbel total (4) than B (3).']],
  remediation: ['β = links ÷ ______.', 'The sum of a row of the matrix is the ______ index.', 'A map with only nodes and links is ______.'], remediationAnswers: '1. nodes 2. Shimbel 3. topological',
  homework: 'Draw a topological map of five towns in your region and calculate its beta index and accessibility matrix.', homeworkTag: 'This prepares Lesson 30: The Taaffe, Morrill and Gould Model.',
  bilingual: [['Index', "L'indice"], ['Matrix', 'La matrice'], ['Accessibility', "L'accessibilité"], ['Shortest path', 'Le plus court chemin'], ['Row', 'La ligne'], ['Column', 'La colonne']],
});

L.push({ no: 30, title: 'The Taaffe, Morrill and Gould Model', topic: T2, subtopic: 'Transport Network Development Theories',
  notions: 'Model, penetration line, feeder route, interconnection, high-priority link.', focus: 'The Taaffe, Morrill and Gould (1963) model of network development; the four stages and the factors at each stage; evaluation.',
  competence: 'Learners are able to describe the stages of the Taaffe, Morrill and Gould model and apply it to Cameroon.',
  objectives: ['State the assumptions of the model.', 'Describe its four stages.', 'Apply and criticise the model using Cameroon.'],
  recall: ['Networks grow over time.', 'The colonial railway joined Douala to the interior.'],
  situation: 'The first modern routes in Cameroon were railways from Douala into the interior built by the Germans. Later, roads joined other towns to these lines. Today, towns are linked by many roads.',
  sitQA: [['What is the problem in the situation?', 'We must explain how the network grew.'], ['Where did the first routes start?', 'At the coast (ports).'], ['What came after the first lines?', 'Feeder roads and interconnections.']],
  justification: 'This lesson helps us to explain the growth of transport networks in developing countries.',
  activities: [
    { sec: 'I. THE MODEL', img: 'taaffe_big.png', caption: 'The four stages of the model.', q: 'Where was the model first developed?', a: 'From studies of Ghana and Nigeria in West Africa (1963).', noProj: 'read the title.' },
    { sec: 'II. STAGES 1 AND 2', img: 'f4_port.jpg', caption: 'A port.', q: 'Describe stages 1 and 2.', a: 'Stage 1: scattered small ports. Stage 2: lines of penetration join some ports to the interior.', noProj: 'describe the first boxes.' },
    { sec: 'III. STAGES 3 AND 4', img: 'taaffe_big.png', caption: 'Feeder routes and interconnection.', q: 'Describe stages 3 and 4.', a: 'Stage 3: feeder roads join the lines. Stage 4: routes interconnect and main links form.', noProj: 'describe the last boxes.' },
    { sec: 'IV. APPLICATION', img: 'cmr_transport_big.png', caption: 'Main routes of Cameroon.', q: 'Which stage fits the Douala–Ngaoundéré railway?', a: 'Stage 2: a line of penetration from the port to the interior.', noProj: 'find it on the map.' },
    { sec: 'IV. CRITICISMS', img: 'f2t_train.jpg', caption: 'A train.', q: 'Give two criticisms of the model.', a: 'It ignores air and political factors, and not all ports grow the same way.', noProj: 'discuss the limits.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Model:', 'It is a simplified picture of reality used to explain it.'], ['Line of penetration:', 'It is a main route from a port into the interior.'], ['Feeder route:', 'It is a small route that joins a main line.']] },
    { title: 'II. The Four Stages', items: [['A. Stage 1:', 'Small scattered ports trade with nearby areas only. There are few links inland.'], ['B. Stage 2:', 'Lines of penetration join some ports to mines, farms or towns inland. These ports grow fast.'], ['C. Stage 3:', 'Feeder routes develop along the main lines. Nodes grow at junctions.'], ['D. Stage 4:', 'Links interconnect and high-priority main routes form. The network becomes well connected.']], draw: { img: 'taaffe_big.png', caption: 'Copy the four stages.' } },
    { title: 'III. Evaluation', items: [['A. Strengths:', 'The model is simple and fits many former colonies. It shows the role of ports and resources.'], ['B. Weaknesses:', 'It ignores air transport and political choices. Real networks do not always follow the stages.']] },
  ],
  evaluation: [['Describe the four stages of the model.', 'Scattered ports, penetration lines, feeder routes, interconnection.'], ['Apply the model to Cameroon.', 'Douala as port, railway as penetration line, roads as feeders, national roads as interconnection.']],
  remediation: ['The model was built in ______.', 'A route from a port inland is a line of ______.', 'Small roads joining main lines are ______ routes.'], remediationAnswers: '1. 1963 2. penetration 3. feeder',
  homework: 'Draw a sketch showing how the road network of your region developed.', homeworkTag: 'This prepares Further Study 6: Transport Development in Cameroon.',
  bilingual: [['Model', 'Le modèle'], ['Stage', "L'étape"], ['Port', 'Le port'], ['Interior', "L'intérieur"], ['Feeder road', 'La route secondaire'], ['Main road', 'La route principale']],
});

L.push({ kind: 'Further Study', no: 6, title: 'Transport Development in Cameroon', topic: T6, subtopic: 'Transport in Cameroon',
  notions: 'Road network, Camrail, port of Douala, Kribi deep-sea port, airport, road maintenance.', focus: 'Different route networks and their spatial pattern; problems of transport development; efforts to improve transport.',
  competence: 'Learners are able to describe the transport networks of Cameroon, their problems and solutions.',
  objectives: ['Describe the road, rail, water and air networks of Cameroon.', 'Explain the problems of transport.', 'Propose solutions and describe state efforts.'],
  recall: ['Douala is the main port.', 'The railway goes from Douala to Ngaoundéré.'],
  situation: 'Trucks carrying goods for Chad and CAR leave Douala port and travel north. In the rainy season, some roads become muddy, trucks get stuck and prices rise in the north.',
  sitQA: [['What is the problem in the situation?', 'Poor roads slow transport and raise prices.'], ['Which countries use Douala port?', 'Chad and the Central African Republic.'], ['What can improve the situation?', 'Tarring and maintaining roads and improving the railway.']],
  justification: 'This further study helps us to understand transport problems and solutions in Cameroon.',
  activities: [
    { sec: 'I. NETWORKS', img: 'cmr_transport_big.png', caption: 'Main transport routes of Cameroon.', q: 'Describe the pattern of the road network.', a: 'Dense in the South-West and West, thin in the East and North, with main roads from Douala.', noProj: 'read the map.' },
    { sec: 'I. RAIL AND WATER', img: 'f2t_train.jpg', caption: 'Rail transport.', q: 'Name the two main ports of Cameroon.', a: 'Douala and Kribi (also Limbe and Garoua on the Benue).', noProj: 'locate the ports.' },
    { sec: 'I. AIR', img: 'usa_airport.jpg', caption: 'An airport.', q: 'Name the international airports of Cameroon.', a: 'Douala, Yaoundé-Nsimalen and Garoua.', noProj: 'locate the airports.' },
    { sec: 'II. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A muddy road.', q: 'Give three problems of transport in Cameroon.', a: 'Poor roads, heavy rains and lack of maintenance (also accidents and insecurity).', noProj: 'list problems.' },
    { sec: 'III. EFFORTS', img: 'usa_container.jpg', caption: 'A modern container port.', q: 'Give two efforts to improve transport.', a: 'Building the Kribi deep-sea port and tarring main roads.', noProj: 'list projects.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Transport network:', 'It is a system of routes joining places.'], ['Deep-sea port:', 'It is a port deep enough for very large ships, like Kribi.']] },
    { title: 'II. Networks and Pattern', items: [['A. Road:', 'Roads carry most goods and people. The network is dense in the south and west and thin in the east and north.'], ['B. Rail:', 'Camrail links Douala, Yaoundé and Ngaoundéré. It carries timber, fuel and goods for Chad and CAR.'], ['C. Water and air:', 'Douala and Kribi are the main ports, and Garoua has a seasonal river port. Douala, Nsimalen and Garoua are international airports.']], draw: { img: 'cmr_transport_big.png', caption: 'Sketch the main routes.' } },
    { title: 'III. Problems and Efforts', items: [['A. Problems:', 'Many roads are untarred and damaged by rain. Accidents, lack of money and insecurity also slow transport.'], ['B. Efforts:', 'The state builds and tars roads, bridges and the Kribi port. Road maintenance funds and private partners also help.'], ['C. Suggestions:', 'Regular maintenance and extending the railway would improve links. Road safety education reduces accidents.']] },
  ],
  evaluation: [['Describe the rail network of Cameroon.', 'Camrail links Douala, Yaoundé and Ngaoundéré.'], ['Give two problems and two solutions of road transport.', 'Problems: bad roads, accidents. Solutions: tarring and maintenance, road safety.']],
  remediation: ['The main port of Cameroon is ______.', 'The deep-sea port is at ______.', 'The railway ends at ______.'], remediationAnswers: '1. Douala 2. Kribi 3. Ngaoundéré',
  homework: 'Describe the state of the main road near your school and suggest improvements.', homeworkTag: 'This prepares Lesson 31: Tourism.',
  bilingual: [['Road network', 'Le réseau routier'], ['Railway station', 'La gare'], ['Deep-sea port', 'Le port en eau profonde'], ['Maintenance', "L'entretien"], ['Accident', "L'accident"], ['Bridge', 'Le pont']],
});

L.push({ no: 31, title: 'Tourism', topic: TR, subtopic: 'World (Global) Tourism',
  notions: 'Tourism, tourist, destination, mass tourism, ecotourism, Butler model.', focus: 'Meaning; types and categories of tourists; major origins and destinations; resources, facilities and activities; impacts; growth and factors; measures to promote tourism; Butler\'s model.',
  competence: 'Learners are able to explain world tourism, its impacts and its evolution.',
  objectives: ['Define tourism and classify its types.', 'Describe origins, destinations and factors of growth.', 'Explain the impacts of tourism and the Butler model.'],
  recall: ['People travel for holidays.', 'Cameroon has beaches, mountains and parks.'],
  situation: 'European tourists visit the beaches of Kribi and the park of Waza. They spend money in hotels and markets, but some beaches become dirty and local customs change.',
  sitQA: [['What is the problem in the situation?', 'Tourism brings money but also problems.'], ['Name two tourist attractions in the situation.', 'Kribi beaches and Waza park.'], ['Give one problem of tourism.', 'Pollution of beaches (or change in local customs).']],
  justification: 'This lesson helps us to understand tourism and how to manage it.',
  activities: [
    { sec: 'I. MEANING AND TYPES', img: 'usa_beach.jpg', caption: 'A crowded beach resort.', q: 'Distinguish mass tourism and ecotourism.', a: 'Mass tourism: many tourists in resorts. Ecotourism: small groups visiting nature with care for the environment.', noProj: 'give examples.' },
    { sec: 'II. ORIGINS AND DESTINATIONS', img: 'tourism_flows_big.png', caption: 'Main tourist flows.', q: 'Which region sends and receives most tourists?', a: 'Europe.', noProj: 'read the flows.' },
    { sec: 'III. RESOURCES AND ACTIVITIES', img: 'usa_safari.jpg', caption: 'Wildlife in an African park.', q: 'Give two natural and two human tourist resources.', a: 'Natural: wildlife, beaches. Human: monuments, festivals.', noProj: 'list attractions.' },
    { sec: 'IV. IMPACTS', img: 'tourism_impacts_big.png', caption: 'Positive and negative impacts.', q: 'Give two positive and two negative impacts of tourism.', a: 'Positive: jobs, foreign currency. Negative: pollution, loss of culture.', noProj: 'sort the impacts.' },
    { sec: 'V. BUTLER MODEL', img: 'butler_big.png', caption: 'Butler\'s tourist area life cycle.', q: 'What can happen after stagnation?', a: 'Decline, or rejuvenation if the resort is improved.', noProj: 'describe the curve.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Tourism:', 'It is travel for leisure, business or culture outside one\'s usual home for at least one night.'], ['Tourist:', 'It is a person who travels for this purpose.'], ['Ecotourism:', 'It is responsible travel to natural areas that protects nature and helps local people.']] },
    { title: 'II. Nature and Growth of Tourism', items: [['A. Types:', 'Mass, eco, cultural, business and religious tourism exist. Tourists can be domestic or international.'], ['B. Origins and destinations:', 'Europe, North America and East Asia send most tourists. France, Spain, the USA and Italy receive the most.'], ['C. Factors of growth:', 'Higher incomes, paid holidays and cheap flights increased tourism. The internet and peace also help.']], draw: { img: 'tourism_flows_big.png', caption: 'Sketch the main flows.' } },
    { title: 'III. Impacts and Butler Model', items: [['A. Positive impacts:', 'Tourism creates jobs, foreign currency and infrastructure. It can protect nature and culture.'], ['B. Negative impacts:', 'It can cause pollution, high prices and loss of culture. Profits often leave the country.'], ['C. Butler model:', 'A resort passes through exploration, involvement, development, consolidation and stagnation. It then declines or is rejuvenated.'], ['D. Promotion:', 'Advertising, security and good infrastructure attract tourists. Training staff also improves service.']] },
  ],
  evaluation: [['Give two factors for the growth of world tourism.', 'Higher incomes and cheaper air travel.'], ['Name the stages of Butler\'s model.', 'Exploration, involvement, development, consolidation, stagnation, then decline or rejuvenation.']],
  remediation: ['Travel to nature that protects it is ______.', 'The largest tourist region is ______.', 'Butler\'s stage after development is ______.'], remediationAnswers: '1. ecotourism 2. Europe 3. consolidation',
  homework: 'Choose a tourist site in Cameroon and place it on a stage of Butler\'s model.', homeworkTag: 'This prepares Further Study 7: Tourism Development in Cameroon.',
  bilingual: [['Tourism', 'Le tourisme'], ['Tourist', 'Le touriste'], ['Destination', 'La destination'], ['Hotel', "L'hôtel"], ['Beach', 'La plage'], ['Wildlife', 'La faune']],
});

L.push({ kind: 'Further Study', no: 7, title: 'Tourism Development in Cameroon', topic: T6, subtopic: 'Tourism in Cameroon',
  notions: 'Tourist resource, national park, hotel, tourist circuit, Ministry of Tourism.', focus: 'Natural and human resources and their distribution; tourist infrastructure; sources and destinations; problems; measures by individuals, communities and government; impacts.',
  competence: 'Learners are able to describe tourism in Cameroon, its problems and ways to promote it.',
  objectives: ['Describe the tourist resources and infrastructure of Cameroon.', 'Explain the problems of tourism.', 'Propose measures to promote tourism and assess its impacts.'],
  recall: ['Cameroon is called "Africa in miniature".', 'Tourism brings jobs and money.'],
  situation: 'Cameroon has beaches, mountains, parks and many cultures, yet it receives fewer tourists than Kenya or Morocco. The Ministry of Tourism wants to attract more visitors.',
  sitQA: [['What is the problem in the situation?', 'Cameroon has great potential but few tourists.'], ['Why is Cameroon called "Africa in miniature"?', 'It has nearly all the landscapes and cultures of Africa.'], ['Give one way to attract tourists.', 'Advertise and improve security and roads.']],
  justification: 'This further study helps us to understand and promote tourism in Cameroon.',
  activities: [
    { sec: 'I. RESOURCES', img: 'cmr_tourism_big.png', caption: 'Main tourist sites of Cameroon.', q: 'Give two natural tourist sites and their regions.', a: 'Waza park (Far North) and Kribi beaches (South).', noProj: 'read the map.' },
    { sec: 'I. RESOURCES', img: 'usa_limbe.jpg', caption: 'Sunset at Limbe.', q: 'Give two human (cultural) tourist resources.', a: 'Chiefdoms like Bafut and Foumban, and festivals like Ngondo.', noProj: 'list cultural sites.' },
    { sec: 'II. INFRASTRUCTURE', img: 'usa_hotel.jpg', caption: 'A hotel with a swimming pool.', q: 'Name three types of tourist infrastructure.', a: 'Hotels, roads and airports (also travel agencies).', noProj: 'list hotels in your town.' },
    { sec: 'III. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A bad road.', q: 'Give three problems of tourism in Cameroon.', a: 'Bad roads, insecurity and poor advertising (also high costs).', noProj: 'list problems.' },
    { sec: 'IV. MEASURES AND IMPACTS', img: 'f2t_elephants.jpg', caption: 'Wildlife in a national park.', q: 'How can local communities benefit from tourism?', a: 'By selling crafts, guiding tourists and sharing park income.', noProj: 'discuss community tourism.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Tourist resource:', 'It is a natural or human feature that attracts tourists.'], ['National park:', 'It is a protected area for wildlife and nature, like Waza or Benue.']] },
    { title: 'II. Resources and Infrastructure', items: [['A. Natural resources:', 'Beaches at Kribi and Limbe, Mount Cameroon and parks like Waza and Benue attract visitors. Waterfalls like Lobé are also attractions.'], ['B. Human resources:', 'Chiefdoms, palaces and festivals show rich cultures. Foumban, Bafut and Rhumsiki are famous.'], ['C. Infrastructure:', 'Hotels, airports and roads are concentrated in big towns. The Ministry of Tourism manages the sector.'], ['D. Tourists:', 'Most tourists come from France, other European countries and Africa. Business tourism is common in Douala and Yaoundé.']], draw: { img: 'cmr_tourism_big.png', caption: 'Sketch the tourist sites.' } },
    { title: 'III. Problems, Measures and Impacts', items: [['A. Problems:', 'Bad roads, insecurity and poor advertising limit tourism. Hotels are costly and few in rural areas.'], ['B. Measures:', 'The government can improve roads, security and advertising. Communities and individuals can welcome and guide visitors.'], ['C. Impacts:', 'Tourism brings jobs, income and pride in culture. It can also pollute sites and disturb wildlife.']] },
  ],
  evaluation: [['Give two natural and two cultural tourist resources of Cameroon.', 'Natural: Waza, Kribi. Cultural: Foumban palace, Ngondo festival.'], ['Give two measures to promote tourism in Cameroon.', 'Improve roads and security; advertise abroad.']],
  remediation: ['Waza park is in the ______ Region.', 'The beaches of ______ are in the South Region.', 'Tourism is managed by the Ministry of ______.'], remediationAnswers: '1. Far North 2. Kribi 3. Tourism',
  homework: 'Prepare a short advertisement for a tourist site in your region.', homeworkTag: 'This ends Module 6 and prepares Module 7: Environment and Development.',
  bilingual: [['National park', 'Le parc national'], ['Chiefdom', 'La chefferie'], ['Festival', 'Le festival'], ['Craft', "L'artisanat"], ['Guide', 'Le guide'], ['Advertising', 'La publicité']],
});

module.exports = { L, B };
if (require.main === module) run(L, B, process.argv.slice(2).length ? process.argv.slice(2) : null);
