// UPPER SIXTH ARTS — PRACTICAL GEOGRAPHY part 2: QUANTITATIVE TECHNIQUES AND FIELDWORK (Module 8). Fieldwork 2 (Meteorology) is a project (PBL) and is not prepared as a deck.
const { run } = require('./sixth');
const { B } = require('./v2_usa_prac1');
const Q = 'Quantitative Techniques in Geography', F = 'Fieldwork in Geography', KQ = 'Quantitative Techniques', KF = 'Field Work';
const L = [];

L.push({ kind: KQ, no: 1, title: 'Analysis of Cartographic Tools', topic: Q, subtopic: 'Cartographical techniques',
  notions: 'Choropleth, isopleth, dot map, proportional circles, star diagram, flow-line map, population pyramid, Lorenz curve.', focus: 'Interpretation of choropleth, isopleth and dot maps, hachures, proportional circles, pyramids, star diagrams, flow-line maps and the Lorenz curve.',
  competence: 'Learners are able to choose, read and interpret cartographic tools.',
  objectives: ['Distinguish the main types of statistical maps.', 'Interpret proportional circles, star diagrams and flow-line maps.', 'Interpret the Lorenz curve.'],
  recall: ['Maps can show data.', 'Population density differs between regions.'],
  situation: 'The Regional Delegation of Planning gives the class data on population, rainfall and migration. It asks which type of map is best for each set of data.',
  sitQA: [['What is the problem in the situation?', 'The class must choose the right map for each data set.'], ['Which map suits rainfall?', 'An isopleth map (isohyets).'], ['Which map suits migration?', 'A flow-line map.']],
  justification: 'This lesson helps us to present and read geographical data on maps.',
  activities: [
    { sec: 'I. CHOROPLETH AND DOT MAPS', img: 'choropleth_big.png', caption: 'A choropleth map.', q: 'Give one advantage and one disadvantage of a choropleth map.', a: 'Advantage: easy to compare regions. Disadvantage: sudden changes at boundaries.', noProj: 'read the map.' },
    { sec: 'I. ISOPLETHS', img: 'isopleth_big.png', caption: 'An isopleth map.', q: 'What is an isopleth? Give two examples.', a: 'A line joining equal values: isohyets (rain), isotherms (temperature).', noProj: 'name isolines.' },
    { sec: 'II. PROPORTIONAL CIRCLES', img: 'prop_circles_big.png', caption: 'Proportional circles.', q: 'Why is the radius proportional to the square root of the value?', a: 'So that the circle\'s area matches the value.', noProj: 'calculate radii.' },
    { sec: 'II. STAR AND FLOW MAPS', img: 'flow_map_big.png', caption: 'A flow-line map (hypothetical).', q: 'What does the width of a flow line show?', a: 'The volume of movement (e.g. number of migrants).', noProj: 'read the flows.' },
    { sec: 'III. LORENZ CURVE', img: 'lorenz_big.png', caption: 'A Lorenz curve.', q: 'What does a curve far from the diagonal show?', a: 'A very unequal distribution.', noProj: 'interpret the curve.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Choropleth map:', 'It is a map that shades areas according to their values.'], ['Isopleth:', 'It is a line joining places of equal value.'], ['Lorenz curve:', 'It is a graph that shows how evenly something is distributed.']] },
    { title: 'II. Statistical Maps', items: [['A. Area maps:', 'Choropleth maps shade regions; dot maps show distribution with dots of fixed value. Hachures show slopes with short lines.'], ['B. Line maps:', 'Isopleths join equal values like rainfall or height. Flow-line maps show movement with lines proportional to volume.'], ['C. Symbol maps:', 'Proportional circles use radius ∝ √value. Star diagrams show wind directions or seasons.']], draw: { img: 'isopleth_big.png', caption: 'Sketch the isohyets.' } },
    { title: 'III. Pyramids and Lorenz Curve', items: [['A. Pyramids:', 'Population pyramids show age and sex structure. A wide base shows high birth rates.'], ['B. Lorenz curve:', 'Plot cumulative percentages of two variables. The further from the diagonal, the more unequal the distribution.']] },
  ],
  evaluation: [['Which map would you use for rainfall, population by region and migration?', 'Isopleth, choropleth, flow-line.'], ['Values 16 and 4: compare the radii of proportional circles.', '√16 = 4 and √4 = 2: the first radius is twice the second.']],
  remediation: ['Lines of equal rainfall are ______.', 'Circle radius ∝ the square ______ of the value.', 'Movement is shown on a ______ map.'], remediationAnswers: '1. isohyets 2. root 3. flow-line',
  homework: 'Draw a choropleth map of population density by region of Cameroon.', homeworkTag: 'This prepares Data Collection: Sources and Techniques.',
  bilingual: [['Choropleth map', 'La carte choroplèthe'], ['Isopleth', "L'isoligne"], ['Dot map', 'La carte par points'], ['Flow line', 'Le flux'], ['Pyramid', 'La pyramide'], ['Distribution', 'La répartition']],
});

L.push({ kind: KQ, no: 2, title: 'Data Collection: Sources and Techniques', topic: Q, subtopic: 'Statistical Techniques',
  notions: 'Primary data, secondary data, sampling, random, systematic, stratified, questionnaire, interview, focus group.', focus: 'Sources of geographical data; basic sampling procedures; observation, counting, photographs and video; measurements; questionnaires, interviews and focus groups.',
  competence: 'Learners are able to choose data sources, select samples and design simple questionnaires.',
  objectives: ['Distinguish primary and secondary data.', 'Describe random, systematic and stratified sampling.', 'Design a simple questionnaire and plan an interview.'],
  recall: ['Geographers collect information in the field.', 'A census counts people.'],
  situation: 'The class wants to know why people in the town buy food at the market rather than in shops. They cannot ask everybody, so they must choose some people and prepare questions.',
  sitQA: [['What is the problem in the situation?', 'The class must collect data from part of the population.'], ['What is choosing some people called?', 'Sampling.'], ['Which tool contains the questions?', 'A questionnaire.']],
  justification: 'This lesson helps us to collect reliable data for geographical studies.',
  activities: [
    { sec: 'I. SOURCES', img: 'data_sources_big.png', caption: 'Primary and secondary data.', q: 'Distinguish primary and secondary data with one example each.', a: 'Primary: collected yourself (a traffic count). Secondary: already exists (census).', noProj: 'list sources.' },
    { sec: 'II. SAMPLING', img: 'sampling_big.png', caption: 'Sampling methods.', q: 'Why do geographers use samples?', a: 'It saves time and money when the whole population cannot be studied.', noProj: 'explain sampling.' },
    { sec: 'II. METHODS', img: 'sampling_big.png', caption: 'Random, systematic and stratified.', q: 'How would you take a systematic sample of 20 houses on a street of 200?', a: 'Choose every 10th house.', noProj: 'plan a sample.' },
    { sec: 'III. OBSERVATION AND MEASUREMENT', img: 'usa_tape.jpg', caption: 'Measuring in the field.', q: 'Give two tools for field measurement.', a: 'Measuring tape and rain gauge (also compass, clinometer, GPS).', noProj: 'list tools.' },
    { sec: 'IV. QUESTIONNAIRES', img: 'questionnaire_big.png', caption: 'Good and bad questions.', q: 'Give two rules for a good questionnaire.', a: 'Short, clear questions that are not leading or too personal.', noProj: 'write three questions.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Primary data:', 'It is data collected by the researcher in the field.'], ['Secondary data:', 'It is data already collected by others, like census data.'], ['Sampling:', 'It is the selection of a small part to represent the whole.']] },
    { title: 'II. Sources and Sampling', items: [['A. Sources:', 'Primary sources include observation, counts, measurements and questionnaires. Secondary sources include census, maps, reports and weather records.'], ['B. Random sampling:', 'Every item has an equal chance of being chosen, using random numbers. It avoids bias.'], ['C. Systematic and stratified:', 'Systematic sampling chooses at regular intervals. Stratified sampling takes each group in proportion to its size.']], draw: { img: 'sampling_big.png', caption: 'Copy the three methods.' } },
    { title: 'III. Techniques', items: [['A. Observation and recording:', 'Counting, photos and videos record what is seen. Tally sheets record frequencies.'], ['B. Questionnaires and interviews:', 'Questionnaires use short, clear questions. Interviews and focus groups give deeper opinions.']] },
  ],
  evaluation: [['Give one advantage of each sampling method.', 'Random: no bias. Systematic: easy. Stratified: represents all groups.'], ['Give two primary and two secondary sources.', 'Primary: counts, questionnaires. Secondary: census, maps.']],
  remediation: ['Data you collect yourself are ______ data.', 'Every 10th house is ______ sampling.', 'A group discussion is a ______ group.'], remediationAnswers: '1. primary 2. systematic 3. focus',
  homework: 'Prepare a questionnaire of five questions about how students travel to school.', homeworkTag: 'This prepares Basic Tools of Data Analysis.',
  bilingual: [['Data', 'Les données'], ['Sample', "L'échantillon"], ['Questionnaire', 'Le questionnaire'], ['Interview', "L'entretien"], ['Survey', "L'enquête"], ['Census', 'Le recensement']],
});

L.push({ kind: KQ, no: 3, title: 'Basic Tools of Data Analysis', topic: Q, subtopic: 'Statistical Techniques',
  notions: 'Mean, median, mode, range, quartile, interquartile range, variance, standard deviation, coefficient of variation, Spearman\'s rank correlation.', focus: 'Measures of central tendency (mean, median, mode, range, quartiles, IQR); dispersion (variance, standard deviation, coefficient of variation); association (Spearman\'s rank correlation).',
  competence: 'Learners are able to calculate and interpret basic statistics for geographical data.',
  objectives: ['Calculate the mean, median, mode, range and interquartile range.', 'Calculate the standard deviation and coefficient of variation.', 'Calculate and interpret Spearman\'s rank correlation.'],
  recall: ['An average summarises many values.', 'Data can be ranked from highest to lowest.'],
  situation: 'The class has the monthly rainfall of a station and the population and number of services of six towns. They must summarise the rainfall and test whether bigger towns have more services.',
  sitQA: [['What is the problem in the situation?', 'The class must summarise and compare data.'], ['Which measure gives the average?', 'The mean (or median).'], ['Which test compares two rankings?', 'Spearman\'s rank correlation.']],
  justification: 'This lesson gives us the statistical tools to analyse geographical data.',
  activities: [
    { sec: 'I. CENTRAL TENDENCY', img: 'stats_central_big.png', caption: 'Mean, median, mode and range.', q: 'Why is the median sometimes better than the mean?', a: 'It is not affected by extreme values.', noProj: 'calculate each measure.' },
    { sec: 'I. QUARTILES', img: 'box_whisker_big.png', caption: 'Box-and-whisker plot.', q: 'What does the interquartile range show?', a: 'The spread of the middle half of the data.', noProj: 'find LQ and UQ.' },
    { sec: 'II. DISPERSION', img: 'sd_big.png', caption: 'Standard deviation worked example.', q: 'What does a small standard deviation mean?', a: 'The values are close to the mean (little variation).', noProj: 'complete the table.' },
    { sec: 'III. SPEARMAN', img: 'spearman_big.png', caption: 'Spearman\'s rank correlation.', q: 'Interpret Rs = +0.89.', a: 'A strong positive correlation: bigger towns have more services.', noProj: 'rank the data.' },
    { sec: 'III. SIGNIFICANCE', img: 'scatter_big.png', caption: 'A negative correlation.', q: 'What would Rs close to −1 mean?', a: 'A strong negative correlation: as one value rises, the other falls.', noProj: 'describe the graph.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Mean:', 'It is the sum of values divided by their number.'], ['Standard deviation:', 'It is a measure of how spread out values are around the mean.'], ['Correlation:', 'It is the relationship between two variables.']] },
    { title: 'II. Central Tendency and Dispersion', items: [['A. Averages:', 'The mean is Σx ÷ n, the median is the middle value and the mode is the most frequent. The range is highest minus lowest.'], ['B. Quartiles:', 'The lower and upper quartiles cut off a quarter of the data. IQR = UQ − LQ shows the spread of the middle half.'], ['C. Standard deviation:', 'SD = √(Σ(x − mean)² ÷ n). The coefficient of variation is SD ÷ mean × 100.']], draw: { img: 'sd_big.png', caption: 'Copy the worked example.' } },
    { title: 'III. Spearman\'s Rank Correlation', items: [['A. Method:', 'Rank both variables, find d and d², then Rs = 1 − (6Σd²) ÷ (n³ − n). Rs lies between −1 and +1.'], ['B. Interpretation:', 'Near +1 is strong positive and near −1 strong negative correlation. Check significance tables before concluding.']] },
  ],
  evaluation: [['Find the mean and median of 4, 8, 10, 12, 26.', 'Mean = 60 ÷ 5 = 12; median = 10.'], ['n = 6, Σd² = 10. Find Rs.', '1 − 60 ÷ 210 = 0.71: fairly strong positive.']],
  remediation: ['The middle value is the ______.', 'UQ − LQ is the ______ range.', 'Rs lies between −1 and ______.'], remediationAnswers: '1. median 2. interquartile 3. +1',
  homework: 'Collect the daily maximum temperature for 7 days and calculate the mean and standard deviation.', homeworkTag: 'This prepares Plotting and Interpreting Graphical Tools.',
  bilingual: [['Mean', 'La moyenne'], ['Median', 'La médiane'], ['Mode', 'Le mode'], ['Range', "L'étendue"], ['Standard deviation', "L'écart type"], ['Correlation', 'La corrélation']],
});

L.push({ kind: KQ, no: 4, title: 'Plotting and Interpreting Graphical Tools', topic: Q, subtopic: 'Graphical Techniques',
  notions: 'Bar graph, compound bar, line graph, ogive, climograph, pie chart, triangular graph, scatter graph.', focus: 'Construction and interpretation of bar graphs, line graphs, cumulative frequency curves (ogive), climographs, pie charts, triangular graphs and scatter graphs.',
  competence: 'Learners are able to draw and interpret the main geographical graphs.',
  objectives: ['Choose the right graph for a data set.', 'Construct bar, line, pie and compound graphs.', 'Interpret ogives, triangular and scatter graphs.'],
  recall: ['Graphs show data visually.', 'A climate graph shows rain and temperature.'],
  situation: 'For a school exhibition, the class must present data on urban population, jobs by sector, travel times to school and the climate of Garoua with the best graphs.',
  sitQA: [['What is the problem in the situation?', 'The class must choose and draw suitable graphs.'], ['Which graph suits jobs by sector (%)?', 'A pie chart (or triangular graph).'], ['Which graph shows the climate of Garoua?', 'A climograph.']],
  justification: 'This lesson helps us to present data clearly with graphs.',
  activities: [
    { sec: 'I. CHOICE OF GRAPH', img: 'graph_choice_big.png', caption: 'Which graph for which data.', q: 'Which graph would you use for change over time?', a: 'A line graph.', noProj: 'match data and graphs.' },
    { sec: 'II. BAR GRAPHS', img: 'compound_bar_big.png', caption: 'A compound bar graph (approximate).', q: 'Describe the trend of urban population.', a: 'It increased from 38 % in 1987 to 57 % in 2020.', noProj: 'read the bars.' },
    { sec: 'II. PIE CHARTS', img: 'pie_big.png', caption: 'A pie chart (approximate).', q: 'Calculate the angle for 15 %.', a: '15 × 3.6 = 54°.', noProj: 'calculate angles.' },
    { sec: 'III. OGIVE', img: 'ogive_big.png', caption: 'A cumulative frequency curve.', q: 'How is the median read from an ogive?', a: 'Read across from n ÷ 2 to the curve, then down to the x-axis.', noProj: 'find the median.' },
    { sec: 'IV. TRIANGULAR GRAPH', img: 'triangular_big.png', caption: 'A triangular graph.', q: 'When is a triangular graph used?', a: 'For three parts that add up to 100 %, like employment sectors or soil texture.', noProj: 'plot a point.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Graph:', 'It is a diagram that shows data and their relationships.'], ['Ogive:', 'It is a cumulative frequency curve used to find the median and quartiles.'], ['Climograph:', 'It is a graph combining rainfall bars and a temperature line.']] },
    { title: 'II. Construction', items: [['A. Bar and line graphs:', 'Bars compare amounts; compound bars show parts of a total. Line graphs show change over time.'], ['B. Pie charts:', 'Multiply each percentage by 3.6 to get the angle. Start at 12 o\'clock and go clockwise.'], ['C. Rules:', 'Every graph needs a title, labelled axes, units, a key and a suitable scale. Use a sharp pencil and ruler.']], draw: { img: 'pie_big.png', caption: 'Copy the pie chart.' } },
    { title: 'III. Special Graphs', items: [['A. Ogive and climograph:', 'Ogives plot cumulative frequency against upper class limits. Climographs combine rainfall bars and temperature lines.'], ['B. Triangular and scatter graphs:', 'Triangular graphs show three percentages adding to 100. Scatter graphs show correlation, with a best-fit line.']] },
  ],
  evaluation: [['Give four elements every graph must have.', 'Title, labelled axes, units and key.'], ['Farming 60 %, industry 10 %, services 30 %: give the pie angles.', '216°, 36°, 108°.']],
  remediation: ['A cumulative frequency curve is an ______.', 'Pie angle = % × ______.', 'Correlation is shown by a ______ graph.'], remediationAnswers: '1. ogive 2. 3.6 3. scatter',
  homework: 'Draw a climograph of your town using data from the nearest weather station.', homeworkTag: 'This prepares Fieldwork 1: Getting Geographical Coordinates.',
  bilingual: [['Graph', 'Le graphique'], ['Bar graph', "L'histogramme"], ['Pie chart', 'Le diagramme circulaire'], ['Axis', "L'axe"], ['Scale', "L'échelle"], ['Trend', 'La tendance']],
});

L.push({ kind: KF, no: 1, title: 'Getting Geographical Coordinates', topic: F, subtopic: 'Location in Geography',
  notions: 'Direction, bearing, compass, GPS, latitude, longitude.', focus: 'Directions and bearings; the compass (meaning and uses, outdoor demonstration); the GPS (meaning and uses, outdoor demonstration with a phone).',
  competence: 'Learners are able to find directions and bearings and obtain coordinates with a compass and a GPS.',
  objectives: ['Give directions and measure bearings.', 'Use a compass in the field.', 'Obtain coordinates with a GPS or smartphone.'],
  recall: ['The four cardinal points are N, E, S and W.', 'Latitude and longitude locate places.'],
  situation: 'The class goes to the school field. The teacher asks each group to find the bearing of the market from the school gate and the latitude and longitude of the gate with a phone.',
  sitQA: [['What is the problem in the situation?', 'The class must locate places in the field.'], ['Which tool measures bearings?', 'A compass.'], ['Which tool gives latitude and longitude?', 'A GPS (or smartphone).']],
  justification: 'This fieldwork teaches us to locate places precisely.',
  activities: [
    { sec: 'I. DIRECTIONS AND BEARINGS', img: 'bearings_big.png', caption: 'Bearings.', q: 'What is a bearing, and what is the bearing of south-west?', a: 'An angle measured clockwise from north; south-west is 225°.', noProj: 'give bearings.' },
    { sec: 'II. MAP AND COMPASS', img: 'usa_topomap.jpg', caption: 'A topographic map used in the field.', q: 'Why do you orient the map with a compass in the field?', a: 'So that directions on the map match directions on the ground.', noProj: 'orient a map outside.' },
    { sec: 'II. BACK BEARING', img: 'bearings_big.png', caption: 'Bearing school → market = 120°.', q: 'Find the bearing from the market back to the school.', a: '120° + 180° = 300°.', noProj: 'calculate back bearings.' },
    { sec: 'III. THE GPS', img: 'usa_gps.jpg', caption: 'A GPS receiver.', q: 'What information does a GPS give?', a: 'Latitude, longitude and altitude (also time and speed).', noProj: 'use a phone app.' },
    { sec: 'III. FIELD DEMONSTRATION', img: 'fieldwork_steps_big.png', caption: 'Steps of fieldwork.', q: 'Give two safety rules for fieldwork.', a: 'Stay in groups and follow the teacher\'s instructions (also avoid roads and rivers).', noProj: 'plan the outing.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Bearing:', 'It is the angle of a direction measured clockwise from north, in three figures.'], ['Compass:', 'It is an instrument with a magnetic needle that points to magnetic north.'], ['GPS:', 'It is a satellite system that gives the exact position of a receiver.']] },
    { title: 'II. Directions and the Compass', items: [['A. Directions:', 'There are 4 cardinal and 12 other points (16 in all). North is 000°, east 090°, south 180° and west 270°.'], ['B. Using a compass:', 'Hold it flat and away from metal, point at the object and read the bearing. A back bearing adds or subtracts 180°.']], draw: { img: 'bearings_big.png', caption: 'Copy the compass rose.' } },
    { title: 'III. The GPS', items: [['A. Principle:', 'Satellites send signals to the receiver, which calculates its position. Smartphones have GPS inside.'], ['B. Uses:', 'GPS records coordinates of sample sites and helps navigation and mapping. The data can be used in a GIS.']] },
  ],
  evaluation: [['Give the bearings of east and north-west.', '090° and 315°.'], ['Give two uses of a GPS in fieldwork.', 'Recording sample sites and mapping routes.']],
  remediation: ['Bearings are measured ______ from north.', 'The bearing of south is ______.', 'Back bearing = bearing ± ______.'], remediationAnswers: '1. clockwise 2. 180° 3. 180°',
  homework: 'Record the coordinates of five places in your neighbourhood with a phone and plot them on a sketch.', homeworkTag: 'This prepares Fieldwork 3: Hydrology.',
  bilingual: [['Compass', 'La boussole'], ['Bearing', "L'azimut"], ['North', 'Le nord'], ['Latitude', 'La latitude'], ['Longitude', 'La longitude'], ['GPS', 'Le GPS']],
});

L.push({ kind: KF, no: 3, title: 'Fieldwork in Hydrology: Running Water', topic: F, subtopic: 'Field investigations in physical geography',
  notions: 'Channel width, depth, velocity, discharge, load, roundness, gully, sheet erosion.', focus: 'Stream channel processes and characteristics; load characteristics; channel form with distance; stream, gully or sheet erosion.',
  competence: 'Learners are able to measure channel characteristics and load and relate them to distance downstream.',
  objectives: ['Measure width, depth and velocity of a stream.', 'Calculate discharge and analyse load size and shape.', 'Observe and record erosion features.'],
  recall: ['Rivers erode, transport and deposit.', 'Discharge = area × velocity.'],
  situation: 'The class plans to study a small stream near the school at four sites from upstream to downstream. Their hypothesis is: "Channel width, depth and discharge increase downstream."',
  sitQA: [['What is the problem in the situation?', 'The class must test a hypothesis on a stream.'], ['What will they measure?', 'Width, depth, velocity and load.'], ['How is discharge calculated?', 'Cross-section area × velocity.']],
  justification: 'This fieldwork helps us to observe river processes directly.',
  activities: [
    { sec: 'I. PLANNING', img: 'fieldwork_steps_big.png', caption: 'Steps of a field investigation.', q: 'Write a hypothesis for a stream study.', a: '"Discharge increases downstream" (or "pebbles get smaller downstream").', noProj: 'write hypotheses.' },
    { sec: 'II. CHANNEL MEASUREMENT', img: 'channel_measure_big.png', caption: 'Measuring a channel.', q: 'Width 6 m, mean depth 0.5 m, velocity 0.5 m/s. Find discharge.', a: '6 × 0.5 × 0.5 = 1.5 m³/s.', noProj: 'calculate discharge.' },
    { sec: 'II. LOAD SAMPLING', img: 'usa_pebbles.jpg', caption: 'Pebbles of different sizes and shapes.', q: 'How do you sample pebbles at each site?', a: 'Pick 10 pebbles at random, measure their long axis and score their roundness.', noProj: 'describe the method.' },
    { sec: 'III. LOAD', img: 'load_size_big.png', caption: 'Load size and roundness downstream.', q: 'Why do pebbles become smaller and rounder downstream?', a: 'Attrition and abrasion wear them down as they are transported.', noProj: 'explain the graph.' },
    { sec: 'IV. EROSION', img: 'f4_gully.jpg', caption: 'Gully erosion.', q: 'How can you record gully erosion in the field?', a: 'Measure its width and depth, take photos and note the slope and vegetation.', noProj: 'record a gully.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Discharge:', 'It is the volume of water passing a point per second (m³/s).'], ['Load:', 'It is the material carried by a river.'], ['Hypothesis:', 'It is a statement that the fieldwork will test.']] },
    { title: 'II. Methods', items: [['A. Channel form:', 'Measure width with a tape and depth at regular intervals with a metre rule. Area = width × mean depth.'], ['B. Velocity and discharge:', 'Time a float over 10 m and repeat three times. Q = area × velocity.'], ['C. Load:', 'Measure the long axis of 10 pebbles at each site. Score roundness with a chart.']], draw: { img: 'channel_measure_big.png', caption: 'Copy the method.' } },
    { title: 'III. Results and Safety', items: [['A. Expected results:', 'Width, depth and discharge usually increase downstream. Pebbles become smaller and rounder.'], ['B. Safety:', 'Work in groups, avoid deep or fast water and wear boots. Check the weather before going.']] },
  ],
  evaluation: [['Float travels 10 m in 25 s. Find velocity.', '10 ÷ 25 = 0.4 m/s.'], ['Give two expected changes downstream.', 'Discharge increases; pebbles get smaller.']],
  remediation: ['Q = area × ______.', 'Wearing down of pebbles is ______.', 'Velocity is measured with a ______.'], remediationAnswers: '1. velocity 2. attrition 3. float',
  homework: 'Prepare a recording sheet for width, depth, velocity and pebble size at four sites.', homeworkTag: 'This prepares Fieldwork 4: Geomorphology.',
  bilingual: [['Stream', 'Le ruisseau'], ['Width', 'La largeur'], ['Depth', 'La profondeur'], ['Velocity', 'La vitesse'], ['Discharge', 'Le débit'], ['Pebble', 'Le galet']],
});

L.push({ kind: KF, no: 4, title: 'Fieldwork in Geomorphology: Rivers and Coasts', topic: F, subtopic: 'Field investigations in physical geography',
  notions: 'Long profile, clinometer, ranging pole, beach profile, swash, backwash, longshore drift.', focus: 'Long profile of a river and its landforms; coastal processes (waves, longshore drift, erosion, transport); beach materials and coastal landforms.',
  competence: 'Learners are able to survey river and beach profiles and observe landforms and processes.',
  objectives: ['Survey a long or beach profile with simple tools.', 'Identify erosional and depositional landforms in the field.', 'Measure wave action and longshore drift.'],
  recall: ['A river has upper, middle and lower courses.', 'Waves erode and deposit on coasts.'],
  situation: 'A class from Limbe visits the coast to study the beach, while a class from Garoua follows the Benue from its tributary to the floodplain. Both must describe landforms and processes.',
  sitQA: [['What is the problem in the situation?', 'The classes must study landforms and processes in the field.'], ['What tool measures slope angles?', 'A clinometer.'], ['What moves sand along a beach?', 'Longshore drift.']],
  justification: 'This fieldwork helps us to see how landforms are shaped.',
  activities: [
    { sec: 'I. LONG PROFILE', img: 'long_profile_big.png', caption: 'The long profile of a river.', q: 'How does the gradient change downstream?', a: 'It is steep upstream and becomes gentle downstream.', noProj: 'describe the profile.' },
    { sec: 'I. SURVEY METHOD', img: 'slope_survey_big.png', caption: 'Surveying a profile.', q: 'Which tools are needed to survey a profile?', a: 'Ranging poles, a clinometer and a measuring tape.', noProj: 'list the tools.' },
    { sec: 'II. RIVER LANDFORMS', img: 'f4_meander.jpg', caption: 'A meander.', q: 'Name one erosional and one depositional river landform.', a: 'Erosional: waterfall (or river cliff). Depositional: point bar (or floodplain).', noProj: 'identify landforms.' },
    { sec: 'III. COASTAL PROCESSES', img: 'longshore_big.png', caption: 'Longshore drift.', q: 'How can longshore drift be measured in the field?', a: 'Put a float or painted pebble in the sea and measure how far it moves in a given time.', noProj: 'plan the test.' },
    { sec: 'III. BEACH MATERIALS', img: 'f4_waves.jpg', caption: 'Waves on a beach.', q: 'How does beach material change up the beach?', a: 'Larger pebbles are often at the back of the beach (thrown by storm waves); finer sand is near the water.', noProj: 'sample the beach.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Long profile:', 'It is the change in height of a river from its source to its mouth.'], ['Longshore drift:', 'It is the movement of material along a beach by waves arriving at an angle.']] },
    { title: 'II. River Fieldwork', items: [['A. Method:', 'Measure gradient with poles and a clinometer at several sites. Record landforms with sketches and photos.'], ['B. Landforms:', 'Waterfalls, rapids and V-shaped valleys are found upstream. Meanders, floodplains and point bars are found downstream.']], draw: { img: 'slope_survey_big.png', caption: 'Copy the method.' } },
    { title: 'III. Coastal Fieldwork', items: [['A. Processes:', 'Count waves per minute and observe swash and backwash. Measure longshore drift with floats.'], ['B. Features:', 'Record cliffs, stacks, beaches and spits. Sample sand and pebble sizes along a beach profile.'], ['C. Safety:', 'Never work alone near the sea and check the tide times. Keep away from cliff edges.']] },
  ],
  evaluation: [['Give three tools for a beach profile survey.', 'Ranging poles, clinometer, tape.'], ['Describe how to measure longshore drift.', 'Time a float over a measured distance along the beach.']],
  remediation: ['Slope angles are measured with a ______.', 'Water going up the beach is ______.', 'Movement of sand along the coast is longshore ______.'], remediationAnswers: '1. clinometer 2. swash 3. drift',
  homework: 'Draw the long profile of a local stream using heights from a map.', homeworkTag: 'This prepares Fieldwork 5: Biogeography.',
  bilingual: [['Profile', 'Le profil'], ['Slope', 'La pente'], ['Beach', 'La plage'], ['Wave', 'La vague'], ['Drift', 'La dérive'], ['Tide', 'La marée']],
});

L.push({ kind: KF, no: 5, title: 'Fieldwork in Biogeography: Soils and Vegetation', topic: F, subtopic: 'Field investigations in physical geography',
  notions: 'Soil profile, horizon, soil pit, auger, transect, quadrat, kite diagram, percentage cover.', focus: 'Soil profile and variation with depth or along a slope; soil erosion; vegetation density, structure and species along a transect with quadrats.',
  competence: 'Learners are able to describe soil profiles and sample vegetation along a transect.',
  objectives: ['Describe a soil profile and test soil properties.', 'Sample vegetation with quadrats along a transect.', 'Present results with a kite diagram.'],
  recall: ['Soil has horizons.', 'Vegetation changes with height and water.'],
  situation: 'On a slope near the school, the grass is tall at the bottom near a stream and short at the top. The class wants to know how soil and vegetation change along the slope.',
  sitQA: [['What is the problem in the situation?', 'The class must explain changes along the slope.'], ['Which tool samples vegetation?', 'A quadrat.'], ['What line is followed for sampling?', 'A transect.']],
  justification: 'This fieldwork helps us to study the links between soils and vegetation.',
  activities: [
    { sec: 'I. SOIL PROFILE', img: 'soil_profile_big.png', caption: 'A soil profile.', q: 'Name the main soil horizons.', a: 'Topsoil (A), subsoil (B), weathered rock (C) and bedrock.', noProj: 'describe a soil pit.' },
    { sec: 'I. SOIL SAMPLING', img: 'usa_auger.jpg', caption: 'Taking a soil sample.', q: 'Give three soil properties you can test in the field.', a: 'Colour, texture and pH (also depth and moisture).', noProj: 'test a sample.' },
    { sec: 'II. QUADRATS', img: 'lsa_quadrat.jpg', caption: 'A quadrat.', q: 'What is a quadrat used for?', a: 'To measure plant species and percentage cover in a small square area.', noProj: 'make a quadrat.' },
    { sec: 'II. TRANSECT', img: 'kite_big.png', caption: 'Kite diagram of a transect.', q: 'Describe the change in trees along the transect.', a: 'Trees increase from 0 % to about 55 % cover towards 90 m.', noProj: 'read the diagram.' },
    { sec: 'III. EXPLANATION', img: 'f2t_savanna.jpg', caption: 'Savanna vegetation.', q: 'Give two factors that explain vegetation change along a slope.', a: 'Soil moisture and soil depth (also grazing and fire).', noProj: 'explain the pattern.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil profile:', 'It is a vertical section of soil showing its horizons.'], ['Transect:', 'It is a line along which samples are taken at regular intervals.'], ['Quadrat:', 'It is a square frame used to sample vegetation.']] },
    { title: 'II. Soil Investigation', items: [['A. Profile:', 'Dig a pit or use an auger and describe each horizon. Measure depth, colour and texture.'], ['B. Variation:', 'Compare soils at the top, middle and bottom of a slope. Soils are often deeper and wetter at the bottom.'], ['C. Erosion:', 'Record gullies and bank erosion with measurements and photos. Note the causes.']], draw: { img: 'soil_profile_big.png', caption: 'Copy the profile.' } },
    { title: 'III. Vegetation Investigation', items: [['A. Method:', 'Lay a transect and place a quadrat every 10 m. Record species, height and percentage cover.'], ['B. Presentation:', 'Kite diagrams show cover along the transect. Relate changes to soil, water and people.']] },
  ],
  evaluation: [['Give the steps of a transect survey.', 'Lay a tape, place quadrats at intervals, record species and cover.'], ['Name two soil tests done in the field.', 'Texture and pH.']],
  remediation: ['Topsoil is the ______ horizon.', 'A square sampling frame is a ______.', 'Cover along a transect is shown by a ______ diagram.'], remediationAnswers: '1. A 2. quadrat 3. kite',
  homework: 'Make a 1 m quadrat and record the plants in three places around the school.', homeworkTag: 'This prepares Fieldwork 6: Economic Activities.',
  bilingual: [['Soil', 'Le sol'], ['Horizon', "L'horizon"], ['Quadrat', 'Le quadrat'], ['Transect', 'Le transect'], ['Cover', 'Le recouvrement'], ['Species', "L'espèce"]],
});

L.push({ kind: KF, no: 6, title: 'Fieldwork on Economic Activities', topic: F, subtopic: 'Field investigations in human geography',
  notions: 'Farm survey, capital, cottage industry, factory, inputs, traffic count, peak hour.', focus: 'Agricultural systems (variation with distance or relief, influence of capital); industrial systems (inputs of a cottage industry and a modern factory); traffic flows (movement of goods and people, variation over time).',
  competence: 'Learners are able to survey farms, industries and traffic and explain their characteristics.',
  objectives: ['Survey how farming changes with distance from a village.', 'Compare the inputs of a cottage industry and a modern factory.', 'Count and analyse traffic flows over time.'],
  recall: ['Farms near villages are used more intensively.', 'Factories need raw materials, labour and capital.'],
  situation: 'The class plans three studies: farms at different distances from a village, a pottery workshop and a brewery, and a traffic count on the main road into town.',
  sitQA: [['What is the problem in the situation?', 'The class must study economic activities in the field.'], ['What tool will they use for farmers?', 'A questionnaire or interview.'], ['How will they study traffic?', 'By counting vehicles at fixed times.']],
  justification: 'This fieldwork helps us to understand economic activities around us.',
  activities: [
    { sec: 'I. FARM SURVEY', img: 'farm_distance_big.png', caption: 'Farm intensity and distance (hypothetical).', q: 'What does the graph show?', a: 'Land use and visits decrease as distance from the village increases.', noProj: 'read the bars.' },
    { sec: 'I. CAPITAL', img: 'f2t_combine.jpg', caption: 'A combine harvester: capital-intensive farming.', q: 'How does invested capital change farm characteristics?', a: 'More capital brings machines, fertiliser and higher yields.', noProj: 'interview a farmer.' },
    { sec: 'II. COTTAGE INDUSTRY', img: 'usa_pottery.jpg', caption: 'Pottery, a cottage industry.', q: 'Give two characteristics of a cottage industry.', a: 'Local raw materials and family labour (also hand tools, local market).', noProj: 'visit a workshop.' },
    { sec: 'II. MODERN FACTORY', img: 'industry_inputs_big.png', caption: 'Inputs compared.', q: 'Compare the labour of a cottage industry and a modern factory.', a: 'Cottage: few family workers. Factory: many paid, skilled workers.', noProj: 'complete the table.' },
    { sec: 'III. TRAFFIC FLOWS', img: 'traffic_count_big.png', caption: 'A traffic count (hypothetical).', q: 'When are the peak hours, and why?', a: '6–8 h and 16–18 h, when people go to and return from work and school.', noProj: 'read the graph.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Cottage industry:', 'It is a small industry run at home with simple tools and family labour.'], ['Traffic count:', 'It is the counting of vehicles or people passing a point in a given time.']] },
    { title: 'II. Agriculture and Industry', items: [['A. Farm survey:', 'Interview farmers at different distances and record crops, inputs and yields. Intensity usually falls with distance.'], ['B. Cottage industry:', 'It uses local raw materials, family labour and hand tools. It sells in local markets.'], ['C. Modern factory:', 'It uses machines, electricity, capital and many workers. Its location depends on raw materials, market and transport.']], draw: { img: 'industry_inputs_big.png', caption: 'Copy the table.' } },
    { title: 'III. Traffic Flows', items: [['A. Method:', 'Count vehicles by type every 15 minutes at a fixed point. Repeat at different times and days.'], ['B. Results:', 'Traffic peaks in the morning and evening and on market days. Present results with bar graphs and flow maps.']] },
  ],
  evaluation: [['Give two differences between a cottage industry and a factory.', 'Labour: family vs many workers. Capital: little vs much.'], ['Why does traffic peak at 7 h?', 'People travel to work and school.']],
  remediation: ['A home-based industry is a ______ industry.', 'Busiest times are ______ hours.', 'Farm intensity ______ with distance.'], remediationAnswers: '1. cottage 2. peak 3. falls',
  homework: 'Count vehicles passing your house for 15 minutes in the morning and evening and compare.', homeworkTag: 'This prepares Fieldwork 7: Settlement.',
  bilingual: [['Farm', "L'exploitation agricole"], ['Capital', 'Le capital'], ['Workshop', "L'atelier"], ['Traffic', 'La circulation'], ['Count', 'Le comptage'], ['Peak hour', "L'heure de pointe"]],
});

L.push({ kind: KF, no: 7, title: 'Fieldwork on Settlement', topic: F, subtopic: 'Field investigations in human geography',
  notions: 'Land-use survey, transect, market threshold, range, segregation, sphere of influence, desire line.', focus: 'Rural land use and settlement variation with distance; market thresholds and range; urban land use and functions (segregation over distance); shopping patterns; urban sphere of influence.',
  competence: 'Learners are able to survey land use and delimit the sphere of influence of a market or town.',
  objectives: ['Carry out a land-use transect in a town.', 'Study the range and threshold of a local market.', 'Delimit a sphere of influence with desire lines.'],
  recall: ['Towns have functional zones.', 'People travel to markets to buy goods.'],
  situation: 'The class wants to know how far people travel to the weekly market and how land use changes from the town centre to the edge. They plan a questionnaire at the market and a walk along a main road.',
  sitQA: [['What is the problem in the situation?', 'The class must study land use and the market\'s influence.'], ['What will they draw from the questionnaire?', 'Desire lines to show the sphere of influence.'], ['How will they study land use?', 'With a land-use transect.']],
  justification: 'This fieldwork helps us to study the organisation of our settlements.',
  activities: [
    { sec: 'I. LAND-USE TRANSECT', img: 'landuse_transect_big.png', caption: 'Land-use transect.', q: 'How does land use change from the centre outwards?', a: 'From shops and banks to mixed use, then housing and finally farms.', noProj: 'walk a transect.' },
    { sec: 'I. SEGREGATION', img: 'lsa_douala.jpg', caption: 'A town seen from above.', q: 'Why do building heights fall away from the centre?', a: 'Land is more expensive in the accessible centre, so people build upwards.', noProj: 'compare buildings.' },
    { sec: 'II. MARKET THRESHOLD AND RANGE', img: 'range_threshold_big.png', caption: 'Range and threshold.', q: 'Distinguish range and threshold.', a: 'Range: maximum distance people travel. Threshold: minimum customers needed.', noProj: 'ask sellers.' },
    { sec: 'III. SPHERE OF INFLUENCE', img: 'sphere_big.png', caption: 'Desire lines to a market.', q: 'How are desire lines drawn?', a: 'Lines from each buyer\'s home village to the market, based on questionnaires.', noProj: 'draw desire lines.' },
    { sec: 'III. SHOPPING PATTERNS', img: 'f2t_market.jpg', caption: 'A market.', q: 'Why do people travel further for high-order goods?', a: 'They are bought rarely and found only in bigger centres.', noProj: 'discuss shopping.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Land-use survey:', 'It is the recording of how each plot or building is used.'], ['Sphere of influence:', 'It is the area served by a settlement or market.'], ['Desire line:', 'It is a straight line joining a person\'s origin to a destination.']] },
    { title: 'II. Land Use and Functions', items: [['A. Transect method:', 'Record land use every 100 m along a road from the centre. Use a colour key and a map.'], ['B. Results:', 'Commercial uses dominate the centre and housing and farms dominate the edge. Building heights and land values fall outwards.']], draw: { img: 'landuse_transect_big.png', caption: 'Copy the transect.' } },
    { title: 'III. Markets and Spheres of Influence', items: [['A. Threshold and range:', 'Ask sellers how many customers they need and buyers how far they travel. Low-order goods have small ranges.'], ['B. Sphere of influence:', 'Plot buyers\' home villages and draw desire lines. The outer limit is the sphere of influence.']] },
  ],
  evaluation: [['Give the steps to delimit a market\'s sphere of influence.', 'Questionnaire buyers, map their origins, draw desire lines, draw the boundary.'], ['What is a threshold?', 'The minimum number of customers needed for a service.']],
  remediation: ['Lines from home to market are ______ lines.', 'The area served by a market is its ______ of influence.', 'The maximum travel distance is the ______.'], remediationAnswers: '1. desire 2. sphere 3. range',
  homework: 'Ask ten buyers at a market where they come from and draw desire lines on a sketch map.', homeworkTag: 'This ends Module 8 and the Upper Sixth programme.',
  bilingual: [['Land use', "L'occupation du sol"], ['Market', 'Le marché'], ['Customer', 'Le client'], ['Range', 'La portée'], ['Threshold', 'Le seuil'], ['Sphere of influence', "L'aire d'influence"]],
});

module.exports = { L, B };
if (require.main === module) run(L, B, process.argv.slice(2).length ? process.argv.slice(2) : null);
