// UPPER SIXTH ARTS — ENVIRONMENT AND DEVELOPMENT part 1: ENVIRONMENTAL ISSUES AND DEVELOPMENT (Module 7: lessons 1–7). 2 periods, 5 activities, summary 2–3 sentences per point.
const { run } = require('./sixth');
const B = { level: 'USA', branch: 'Environment and Development', folder: 'Environment and Development', code: 'ENV',
  module: 'Module 7: Understanding and managing contemporary environmental and development issues',
  moduleShort: 'Module 7 (Environment and Development)', topicDefault: 'Contemporary Environmental Issues' };
const E = 'Contemporary Environmental Issues', D = 'Current Development Issues';
const L = [];

L.push({ no: 1, title: 'Pollution', topic: E, subtopic: 'Environmental Degradation',
  notions: 'Pollution, pollutant, acid rain, eutrophication, recycling.', focus: 'Main types (water, air, land); meaning, pollutants and sources; nature and magnitude; causes; effects on people and the environment; solutions (legislation, technology, recycling, disposal, international cooperation).',
  competence: 'Learners are able to identify types of pollution, explain their causes and effects and propose solutions.',
  objectives: ['Define pollution and name its main types.', 'Explain the causes and effects of pollution.', 'Propose solutions to pollution.'],
  recall: ['Factories and cars produce smoke.', 'Rubbish is thrown in drains and rivers.'],
  situation: 'In Douala, plastic bags block the gutters, smoke from factories and old cars fills the air and some people drink water from polluted wells. Many children have coughs and diarrhoea.',
  sitQA: [['What is the problem in the situation?', 'Air, water and land are polluted.'], ['Give two sources of pollution in the situation.', 'Plastic waste and smoke from factories and cars.'], ['Give one effect on people.', 'Coughs and diarrhoea.']],
  justification: 'This lesson helps us to understand pollution and to protect our health and environment.',
  activities: [
    { sec: 'I. TYPES', img: 'env_pollution_big.png', caption: 'The main types of pollution.', q: 'Name the three main types of pollution.', a: 'Air, water and land pollution (also noise).', noProj: 'list polluted places in your town.' },
    { sec: 'II. AIR POLLUTION', img: 'usa_smoke.jpg', caption: 'Smoke from factory chimneys.', q: 'Give two sources of air pollution.', a: 'Factories and car exhaust (also burning waste and bush fires).', noProj: 'describe smoke you see.' },
    { sec: 'II. ACID RAIN', img: 'acid_rain_big.png', caption: 'How acid rain forms.', q: 'Explain how acid rain forms.', a: 'Sulphur and nitrogen gases mix with water in clouds and fall as acid rain.', noProj: 'describe the steps.' },
    { sec: 'III. WATER AND LAND', img: 'usa_dump.jpg', caption: 'A rubbish dump in West Africa.', q: 'Give two effects of rubbish dumps.', a: 'They pollute water and soil and spread diseases like cholera.', noProj: 'discuss rubbish in your area.' },
    { sec: 'IV. SOLUTIONS', img: 'pollution_table_big.png', caption: 'Causes, effects and solutions.', q: 'Give three solutions to pollution.', a: 'Recycling, laws against dumping and treatment plants (also clean technology).', noProj: 'suggest solutions for your school.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Pollution:', 'It is the addition of harmful substances to air, water or land.'], ['Pollutant:', 'It is a substance that causes pollution, like smoke or plastic.'], ['Eutrophication:', 'It is the excess growth of algae in water caused by fertilisers and sewage.']] },
    { title: 'II. Types and Causes', items: [['A. Air pollution:', 'Smoke from factories, cars and burning waste pollutes the air. It causes acid rain and lung diseases.'], ['B. Water pollution:', 'Sewage, chemicals, oil spills and plastics pollute rivers and seas. Fish die and people catch cholera.'], ['C. Land pollution:', 'Rubbish dumps, pesticides and mining waste damage soils. Population growth and industry increase the problem.']], draw: { img: 'acid_rain_big.png', caption: 'Copy the acid rain diagram.' } },
    { title: 'III. Effects and Solutions', items: [['A. Effects:', 'Pollution causes diseases, kills wildlife and damages buildings and soils. It also lowers crop yields.'], ['B. Solutions:', 'Laws, clean technology, recycling and safe waste disposal reduce pollution. International agreements help for global problems.']] },
  ],
  evaluation: [['Give two causes and two effects of water pollution.', 'Causes: sewage, chemicals. Effects: cholera, fish die.'], ['Give three measures to reduce pollution.', 'Recycling, laws and treatment plants.']],
  remediation: ['Rain made acid by factory gases is ______ rain.', 'Algae growth caused by fertilisers is ______.', 'Using waste again is ______.'], remediationAnswers: '1. acid 2. eutrophication 3. recycling',
  homework: 'List the sources of pollution around your home and suggest one solution for each.', homeworkTag: 'This prepares Lesson 2: Deforestation and Desertification.',
  bilingual: [['Pollution', 'La pollution'], ['Waste', 'Les déchets'], ['Smoke', 'La fumée'], ['Sewage', 'Les eaux usées'], ['Recycling', 'Le recyclage'], ['Acid rain', 'Les pluies acides']],
});

L.push({ no: 2, title: 'Deforestation and Desertification', topic: E, subtopic: 'Environmental Degradation',
  notions: 'Deforestation, desertification, overgrazing, afforestation, reforestation, Green Wall.', focus: 'Meaning and examples; causes; consequences; preventive and corrective measures.',
  competence: 'Learners are able to explain the causes and consequences of deforestation and desertification and propose measures.',
  objectives: ['Define deforestation and desertification with examples.', 'Explain their causes and consequences.', 'Propose preventive and corrective measures.'],
  recall: ['Trees protect the soil.', 'The Far North of Cameroon is close to the Sahara.'],
  situation: 'In the East Region, large areas of forest are cut for timber and farms. In the Far North, trees are cut for firewood, cattle eat all the grass and sand begins to cover fields.',
  sitQA: [['What is the problem in the situation?', 'Forests are destroyed and land is becoming desert.'], ['What is the loss of forest called?', 'Deforestation.'], ['What is the spread of desert conditions called?', 'Desertification.']],
  justification: 'This lesson helps us to protect forests and fight desertification.',
  activities: [
    { sec: 'I. MEANING', img: 'usa_clearcut.jpg', caption: 'A forest cleared by logging.', q: 'What is deforestation?', a: 'The removal of forests for timber, farming or building.', noProj: 'describe cut forests you know.' },
    { sec: 'II. CAUSES OF DEFORESTATION', img: 'deforest_causes_big.png', caption: 'Causes of deforestation.', q: 'Give three causes of deforestation.', a: 'Farming, logging and fuelwood (also mining and roads).', noProj: 'list causes in your region.' },
    { sec: 'III. DESERTIFICATION', img: 'sahel_map_big.png', caption: 'The Sahel, at risk of desertification.', q: 'Where is desertification most serious in Africa?', a: 'In the Sahel, south of the Sahara, including the Far North of Cameroon.', noProj: 'locate the Sahel.' },
    { sec: 'III. CAUSES OF DESERTIFICATION', img: 'desert_cycle_big.png', caption: 'The desertification cycle.', q: 'How does overgrazing lead to desertification?', a: 'Animals remove plants, the soil is bare and is eroded by wind and water.', noProj: 'follow the cycle.' },
    { sec: 'IV. MEASURES', img: 'f2t_tree_planting_sahel.jpg', caption: 'Planting trees in the Sahel.', q: 'Give two measures against desertification.', a: 'Tree planting (Green Wall, Sahel Vert) and controlled grazing (also improved stoves).', noProj: 'discuss tree planting.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Deforestation:', 'It is the removal of forest cover by people.'], ['Desertification:', 'It is the spread of desert conditions into dry lands, mainly because of human activities and drought.'], ['Afforestation:', 'It is the planting of trees where there were none.']] },
    { title: 'II. Causes and Consequences', items: [['A. Causes of deforestation:', 'Farming, logging, fuelwood, mining and roads remove forests. Population growth increases the pressure.'], ['B. Causes of desertification:', 'Overgrazing, over-cultivation and cutting trees leave soils bare. Long droughts make the problem worse.'], ['C. Consequences:', 'Soils are eroded, wildlife is lost and rainfall may fall. Farmers become poorer and migrate.']], draw: { img: 'desert_cycle_big.png', caption: 'Copy the cycle.' } },
    { title: 'III. Measures', items: [['A. Preventive:', 'Controlled logging, protected areas and improved stoves reduce tree cutting. Controlled grazing protects grass.'], ['B. Corrective:', 'Reforestation, the Great Green Wall and Operation Sahel Vert restore land. Stone lines and zaï pits help crops grow again.']] },
  ],
  evaluation: [['Define desertification and give two causes.', 'The spread of desert conditions; overgrazing and cutting trees.'], ['Give two preventive and two corrective measures.', 'Preventive: controlled grazing, improved stoves. Corrective: reforestation, stone lines.']],
  remediation: ['Removing forests is ______.', 'Too many animals on land is ______.', 'Planting trees again is ______.'], remediationAnswers: '1. deforestation 2. overgrazing 3. reforestation',
  homework: 'Interview an elder about changes in trees and grass in your area over the years.', homeworkTag: 'This prepares Lesson 3: Soil Erosion.',
  bilingual: [['Deforestation', 'La déforestation'], ['Desertification', 'La désertification'], ['Overgrazing', 'Le surpâturage'], ['Firewood', 'Le bois de chauffe'], ['Tree planting', 'Le reboisement'], ['Drought', 'La sécheresse']],
});

L.push({ no: 3, title: 'Soil Erosion', topic: E, subtopic: 'Environmental Degradation',
  notions: 'Soil erosion, splash, sheet, rill and gully erosion, soil conservation, terracing, contour ploughing.', focus: 'Meaning and types; causes; effects; soil conservation methods.',
  competence: 'Learners are able to identify types of soil erosion, explain causes and effects and apply conservation methods.',
  objectives: ['Define soil erosion and name its types.', 'Explain its causes and effects.', 'Describe soil conservation methods.'],
  recall: ['Rain and wind move soil.', 'Plants protect the soil.'],
  situation: 'On the slopes of the Mandara Mountains, heavy rains wash soil from bare fields. Deep channels appear and harvests fall. Some farmers build stone terraces to stop the damage.',
  sitQA: [['What is the problem in the situation?', 'Soil is washed away from the fields.'], ['What are the deep channels called?', 'Gullies.'], ['What solution do some farmers use?', 'Stone terraces.']],
  justification: 'This lesson helps us to protect our soils, which feed us.',
  activities: [
    { sec: 'I. MEANING', img: 'erosion_rain.gif', caption: 'Rain on bare and grassy soil.', q: 'Why is bare soil eroded faster than grassy soil?', a: 'Nothing protects it from raindrops or holds it with roots.', noProj: 'compare two plots.' },
    { sec: 'I. TYPES', img: 'erosion_types_big.png', caption: 'Types of soil erosion by water.', q: 'Distinguish rill and gully erosion.', a: 'Rills are small shallow channels; gullies are deep, wide channels.', noProj: 'describe each type.' },
    { sec: 'II. CAUSES AND EFFECTS', img: 'f4_gully.jpg', caption: 'A gully.', q: 'Give two human causes of soil erosion.', a: 'Deforestation and overgrazing (also bush fires and ploughing down slopes).', noProj: 'find gullies near school.' },
    { sec: 'III. CONSERVATION', img: 'f4_terraces.jpg', caption: 'Terraces on a hillside.', q: 'How do terraces reduce soil erosion?', a: 'They turn slopes into flat steps that slow down running water.', noProj: 'draw a terrace.' },
    { sec: 'III. CONSERVATION', img: 'soil_conservation_big.png', caption: 'Soil conservation methods.', q: 'Give three other conservation methods.', a: 'Contour ploughing, cover crops and tree planting.', noProj: 'list methods used locally.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Soil erosion:', 'It is the removal of the top soil by water, wind or people faster than it forms.'], ['Soil conservation:', 'It is the protection of soil from erosion and loss of fertility.']] },
    { title: 'II. Types, Causes and Effects', items: [['A. Types:', 'Water causes splash, sheet, rill and gully erosion. Wind erosion is common in dry areas.'], ['B. Causes:', 'Heavy rain, steep slopes and strong winds are natural causes. Deforestation, overgrazing, bush fires and poor ploughing are human causes.'], ['C. Effects:', 'Fertile soil is lost and yields fall. Rivers and dams fill with silt.']], draw: { img: 'erosion_types_big.png', caption: 'Copy the types.' } },
    { title: 'III. Conservation Methods', items: [['A. Mechanical:', 'Terraces, stone lines and contour ploughing slow water on slopes. Gullies can be blocked with stones.'], ['B. Biological:', 'Cover crops, mulch, agroforestry and tree planting protect the soil. Controlled grazing and no bush fires keep grass.']] },
  ],
  evaluation: [['Name four types of water erosion.', 'Splash, sheet, rill and gully.'], ['Give two mechanical and two biological conservation methods.', 'Mechanical: terraces, contour ploughing. Biological: cover crops, trees.']],
  remediation: ['Deep channels cut by water are ______.', 'Steps built on slopes are ______.', 'Ploughing across the slope is ______ ploughing.'], remediationAnswers: '1. gullies 2. terraces 3. contour',
  homework: 'Observe a slope near your home and suggest two ways to protect its soil.', homeworkTag: 'This prepares Lesson 4: Climatic Change.',
  bilingual: [['Soil erosion', "L'érosion des sols"], ['Gully', 'Le ravin'], ['Terrace', 'La terrasse'], ['Slope', 'La pente'], ['Mulch', 'Le paillage'], ['Topsoil', 'La couche arable']],
});

L.push({ no: 4, title: 'Climatic Change', topic: E, subtopic: 'Climate Change',
  notions: 'Climate change, greenhouse gases, ice core, El Niño, Milankovitch cycles.', focus: 'Meaning; evidence; natural and human causes.',
  competence: 'Learners are able to explain the evidence and causes of climate change.',
  objectives: ['Define climatic change.', 'Describe the evidence of climate change.', 'Explain its natural and human causes.'],
  recall: ['Climate is the average weather over a long time.', 'Burning fuels releases carbon dioxide.'],
  situation: 'Old farmers in the North say the rains now start later and stop earlier than when they were young. Scientists also show that glaciers are melting on mountains around the world.',
  sitQA: [['What is the problem in the situation?', 'The climate is changing.'], ['Give one piece of evidence in the situation.', 'Melting glaciers (or changing rains).'], ['Is climate change natural or human?', 'Both, but today it is mainly caused by people.']],
  justification: 'This lesson helps us to understand the changes in our climate.',
  activities: [
    { sec: 'I. MEANING', img: 'co2_temp_big.png', caption: 'CO₂ and world temperature (approximate).', q: 'What happened to CO₂ and temperature since 1960?', a: 'Both rose steadily: CO₂ from about 317 to 414 ppm and temperature by about 1 °C.', noProj: 'read the graph.' },
    { sec: 'II. EVIDENCE', img: 'climate_evidence_big.png', caption: 'Evidence of climate change.', q: 'Give three pieces of evidence of climate change.', a: 'Weather records, melting glaciers and rising sea level.', noProj: 'list evidence.' },
    { sec: 'II. EVIDENCE', img: 'usa_glacier.jpg', caption: 'Melting ice.', q: 'How does melting ice show climate change?', a: 'Ice melts because the air and sea are warmer.', noProj: 'discuss melting ice.' },
    { sec: 'III. NATURAL CAUSES', img: 'climate_causes_big.png', caption: 'Natural and human causes.', q: 'Give two natural causes of climate change.', a: 'Changes in the Earth\'s orbit and volcanic eruptions (also the sun and El Niño).', noProj: 'read the left column.' },
    { sec: 'III. HUMAN CAUSES', img: 'usa_powerplant.jpg', caption: 'A coal power station.', q: 'How do power stations change the climate?', a: 'Burning coal releases CO₂, a greenhouse gas that traps heat.', noProj: 'discuss fuels we burn.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Climatic change:', 'It is a long-term change in the average climate of a place or of the world.'], ['Greenhouse gases:', 'They are gases like CO₂ and methane that trap heat in the atmosphere.']] },
    { title: 'II. Evidence', items: [['A. Records:', 'Thermometer records show about 1.1 °C of warming since 1850. Rainfall patterns are changing.'], ['B. Ice and sea:', 'Glaciers and ice sheets are melting and sea level is rising. Ice cores show past climates.'], ['C. Nature:', 'Tree rings, pollen and fossils show past changes. Plants and animals now move to cooler places.']], draw: { img: 'climate_evidence_big.png', caption: 'Copy the evidence.' } },
    { title: 'III. Causes', items: [['A. Natural causes:', 'Changes in the Earth\'s orbit and the sun\'s energy change climate over long periods. Volcanic dust and El Niño cause short changes.'], ['B. Human causes:', 'Burning coal, oil and gas and deforestation add greenhouse gases. Cattle, rice fields and fertilisers add methane and nitrous oxide.']] },
  ],
  evaluation: [['Give two pieces of evidence of climate change.', 'Rising temperatures and melting glaciers.'], ['Give two natural and two human causes.', 'Natural: volcanoes, orbit changes. Human: burning fuels, deforestation.']],
  remediation: ['CO₂ and methane are ______ gases.', 'Ice ______ show past climates.', 'Warming since 1850 is about ______ °C.'], remediationAnswers: '1. greenhouse 2. cores 3. 1.1',
  homework: 'Ask two elders how the seasons have changed and write their answers.', homeworkTag: 'This prepares Lesson 5: Global Warming.',
  bilingual: [['Climate change', 'Le changement climatique'], ['Evidence', 'La preuve'], ['Glacier', 'Le glacier'], ['Greenhouse gas', 'Le gaz à effet de serre'], ['Volcano', 'Le volcan'], ['Sea level', 'Le niveau de la mer']],
});

L.push({ no: 5, title: 'Global Warming', topic: E, subtopic: 'Climate Change',
  notions: 'Global warming, greenhouse effect, mitigation, adaptation, Paris Agreement.', focus: 'Meaning and trends; causes and consequences; adaptation and mitigation measures.',
  competence: 'Learners are able to explain global warming and propose adaptation and mitigation measures.',
  objectives: ['Define global warming and describe its trend.', 'Explain its causes and consequences.', 'Distinguish and propose mitigation and adaptation measures.'],
  recall: ['Greenhouse gases trap heat.', 'The world is getting warmer.'],
  situation: 'In the Sahel, droughts are more frequent; on the coast, the sea eats into the beaches of Limbe and Kribi. The government of Cameroon has signed the Paris Agreement to reduce emissions.',
  sitQA: [['What is the problem in the situation?', 'Global warming affects Cameroon.'], ['Give two effects in the situation.', 'Droughts and coastal erosion.'], ['What did the government sign?', 'The Paris Agreement.']],
  justification: 'This lesson helps us to understand global warming and how to respond to it.',
  activities: [
    { sec: 'I. MEANING', img: 'greenhouse_big.png', caption: 'The greenhouse effect.', q: 'Explain the greenhouse effect.', a: 'Sunlight warms the Earth and greenhouse gases trap part of the heat.', noProj: 'describe the steps.' },
    { sec: 'I. TRENDS', img: 'co2_temp_big.png', caption: 'CO₂ and temperature (approximate).', q: 'Why is warming called "enhanced" today?', a: 'People add extra greenhouse gases, so more heat is trapped.', noProj: 'read the graph.' },
    { sec: 'II. CONSEQUENCES', img: 'warming_impacts_big.png', caption: 'Impacts of global warming.', q: 'Give three consequences of global warming.', a: 'Sea-level rise, droughts and more malaria.', noProj: 'list local effects.' },
    { sec: 'III. MITIGATION', img: 'f4_solar.jpg', caption: 'Solar panels.', q: 'How does solar energy mitigate global warming?', a: 'It produces electricity without greenhouse gases.', noProj: 'discuss clean energy.' },
    { sec: 'III. ADAPTATION', img: 'mit_adapt_big.png', caption: 'Mitigation and adaptation.', q: 'Distinguish mitigation and adaptation.', a: 'Mitigation reduces the causes; adaptation helps people live with the effects.', noProj: 'sort the measures.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Global warming:', 'It is the rise in the average temperature of the Earth.'], ['Mitigation:', 'It is reducing the causes of global warming.'], ['Adaptation:', 'It is adjusting our lives to the effects of global warming.']] },
    { title: 'II. Causes and Consequences', items: [['A. Causes:', 'Extra greenhouse gases from fuels, deforestation and farming enhance the greenhouse effect. More heat is trapped.'], ['B. Consequences:', 'Sea level rises, ice melts and storms, floods and droughts become stronger. Crops fail and diseases spread.']], draw: { img: 'greenhouse_big.png', caption: 'Copy the greenhouse effect.' } },
    { title: 'III. Measures', items: [['A. Mitigation:', 'Renewable energy, energy saving and tree planting reduce emissions. The Paris Agreement (2015) aims to keep warming well below 2 °C.'], ['B. Adaptation:', 'Drought-resistant crops, water harvesting and sea walls reduce damage. Early warnings protect people.']] },
  ],
  evaluation: [['Give two causes and two consequences of global warming.', 'Causes: burning fuels, deforestation. Consequences: sea-level rise, droughts.'], ['Give one mitigation and one adaptation measure.', 'Mitigation: solar power. Adaptation: drought-resistant crops.']],
  remediation: ['Reducing the causes is ______.', 'Living with the effects is ______.', 'The 2015 climate treaty is the ______ Agreement.'], remediationAnswers: '1. mitigation 2. adaptation 3. Paris',
  homework: 'Propose three actions your school can take to reduce greenhouse gases.', homeworkTag: 'This prepares Lesson 6: Flooding.',
  bilingual: [['Global warming', 'Le réchauffement climatique'], ['Heat', 'La chaleur'], ['Mitigation', "L'atténuation"], ['Adaptation', "L'adaptation"], ['Renewable energy', "L'énergie renouvelable"], ['Emissions', 'Les émissions']],
});

L.push({ no: 6, title: 'Flooding', topic: E, subtopic: 'Climate Change',
  notions: 'Flood, floodplain, storm hydrograph, lag time, hard engineering, soft engineering.', focus: 'Meaning and magnitude; physical and human causes; effects; adaptation and mitigation measures.',
  competence: 'Learners are able to explain the causes and effects of floods and propose measures.',
  objectives: ['Define flooding and describe its magnitude.', 'Explain the causes and effects of floods.', 'Propose measures to reduce flood damage.'],
  recall: ['Rivers overflow in the rainy season.', 'Concrete does not absorb water.'],
  situation: 'Every rainy season, parts of Douala and Maroua are flooded. Houses built near rivers are destroyed, drains are blocked with rubbish and cholera spreads.',
  sitQA: [['What is the problem in the situation?', 'Floods destroy houses and spread disease.'], ['Give one human cause in the situation.', 'Blocked drains (or building near rivers).'], ['Give one effect.', 'Cholera (or destroyed houses).']],
  justification: 'This lesson helps us to prevent and reduce flood damage.',
  activities: [
    { sec: 'I. MEANING', img: 'f4_floodvillage.jpg', caption: 'A flooded village.', q: 'What is a flood?', a: 'When water covers land that is normally dry.', noProj: 'describe a flood you saw.' },
    { sec: 'II. CAUSES', img: 'flood_causes_big.png', caption: 'Physical and human causes.', q: 'Give two physical and two human causes of floods.', a: 'Physical: heavy rain, saturated soil. Human: urbanisation, blocked drains.', noProj: 'sort causes.' },
    { sec: 'II. HYDROGRAPH', img: 'storm_hydrograph_big.png', caption: 'A storm hydrograph.', q: 'Why do towns have shorter lag times?', a: 'Concrete and drains send water quickly to rivers.', noProj: 'read the lag time.' },
    { sec: 'III. EFFECTS', img: 'lsa_streetflood.jpg', caption: 'A flooded street.', q: 'Give three effects of floods.', a: 'Loss of lives and houses, diseases and destroyed crops.', noProj: 'list effects.' },
    { sec: 'IV. MEASURES', img: 'usa_thames.jpg', caption: 'The Thames Barrier, London.', q: 'Give one hard and one soft engineering measure.', a: 'Hard: barriers, levees or dams. Soft: land-use zoning or tree planting.', noProj: 'suggest measures for your town.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Flood:', 'It is the covering of normally dry land by water.'], ['Floodplain:', 'It is the flat land beside a river that is flooded when the river overflows.'], ['Lag time:', 'It is the time between peak rainfall and peak river discharge.']] },
    { title: 'II. Causes and Effects', items: [['A. Physical causes:', 'Heavy or long rain, saturated soils and storm surges cause floods. Flat low land floods easily.'], ['B. Human causes:', 'Urbanisation, deforestation and blocked drains send water quickly to rivers. Building on floodplains puts people at risk.'], ['C. Effects:', 'Floods kill people, destroy houses, roads and crops and spread diseases. They can also bring fertile silt.']], draw: { img: 'storm_hydrograph_big.png', caption: 'Copy the hydrograph.' } },
    { title: 'III. Measures', items: [['A. Hard engineering:', 'Dams, levees, barriers and wider channels hold back water. They are costly but protect towns.'], ['B. Soft engineering:', 'Land-use zoning, tree planting and warnings reduce risk. Clean drains are cheap and effective.']] },
  ],
  evaluation: [['Give two causes of urban floods.', 'Concrete surfaces and blocked drains.'], ['Compare hard and soft engineering.', 'Hard: costly structures. Soft: cheaper natural methods and planning.']],
  remediation: ['Flat land beside a river is a ______.', 'Walls built along rivers are ______.', 'Planning where to build is land-use ______.'], remediationAnswers: '1. floodplain 2. levees 3. zoning',
  homework: 'Map the flood-prone areas of your town and suggest two solutions.', homeworkTag: 'This prepares Lesson 7: Notion of Development.',
  bilingual: [['Flood', "L'inondation"], ['Drain', 'Le caniveau'], ['Dam', 'Le barrage'], ['Levee', 'La digue'], ['Warning', "L'alerte"], ['Floodplain', "La plaine d'inondation"]],
});

L.push({ no: 7, title: 'Notion of Development', topic: D, subtopic: 'Concept of Development',
  notions: 'Development, economic growth, GNI, HDI, development gap, sustainable development.', focus: 'Meaning of development, economic development and growth; reasons for the gap between rich and poor; economic and social criteria (HDI); classification of countries; sustainable development and ways to achieve it.',
  competence: 'Learners are able to measure development, explain the development gap and suggest ways to achieve sustainable development.',
  objectives: ['Distinguish development and economic growth.', 'Measure development with economic and social criteria.', 'Explain the development gap and sustainable development.'],
  recall: ['Some countries are rich and others poor.', 'Health and education improve people\'s lives.'],
  situation: 'A student compares Cameroon and Norway. Norway has high incomes, long life expectancy and almost everyone can read. Cameroon has rich resources but many people are still poor.',
  sitQA: [['What is the problem in the situation?', 'There is a big gap in development.'], ['Name two measures of development in the situation.', 'Income and life expectancy (also literacy).'], ['What index combines them?', 'The Human Development Index (HDI).']],
  justification: 'This lesson helps us to understand and measure development.',
  activities: [
    { sec: 'I. MEANING', img: 'usa_skyline.jpg', caption: 'A city in a rich country.', q: 'Distinguish economic growth and development.', a: 'Growth is a rise in output; development is a better life for all people.', noProj: 'give examples.' },
    { sec: 'II. CRITERIA', img: 'dev_indicators_big.png', caption: 'Development indicators (approximate).', q: 'Name two economic and two social criteria of development.', a: 'Economic: GNI per person, jobs. Social: life expectancy, literacy.', noProj: 'read the table.' },
    { sec: 'II. HDI', img: 'hdi_map_big.png', caption: 'Human Development Index (approximate).', q: 'Which region has most low-HDI countries?', a: 'Sub-Saharan Africa.', noProj: 'read the map.' },
    { sec: 'III. THE GAP', img: 'usa_slum.jpg', caption: 'A poor neighbourhood.', q: 'Give three reasons for the gap between rich and poor countries.', a: 'Colonial history, unfair trade and debt (also poor governance, conflicts, climate).', noProj: 'discuss reasons.' },
    { sec: 'IV. SUSTAINABLE DEVELOPMENT', img: 'sustain_big.png', caption: 'The three pillars.', q: 'What is sustainable development?', a: 'Development that meets today\'s needs without harming future generations.', noProj: 'explain the circles.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Development:', 'It is the improvement of people\'s living standards and wellbeing.'], ['Economic growth:', 'It is the increase in the output of goods and services of a country.'], ['HDI:', 'It is an index from 0 to 1 that combines income, life expectancy and education.']] },
    { title: 'II. Measuring and Classifying', items: [['A. Economic criteria:', 'GNI per person, jobs in industry and energy use measure wealth. They hide inequality.'], ['B. Social criteria:', 'Life expectancy, literacy, doctors and clean water show welfare. The HDI combines several criteria.'], ['C. Classification:', 'Countries are classed as developed (MEDCs), developing (LEDCs) or least developed. Cameroon has a medium HDI.']], draw: { img: 'dev_indicators_big.png', caption: 'Copy the table.' } },
    { title: 'III. The Gap and Sustainable Development', items: [['A. Reasons for the gap:', 'Colonialism, unfair trade, debt, poor governance and conflicts keep countries poor. Harsh climates and diseases also slow development.'], ['B. Sustainable development:', 'It balances economy, society and environment. Clean energy, education and good governance help to achieve it.']] },
  ],
  evaluation: [['Distinguish development and growth.', 'Growth is more output; development is a better life for people.'], ['Give three components of the HDI.', 'Income, life expectancy and education.']],
  remediation: ['An index of income, health and education is the ______.', 'Cameroon has a ______ HDI.', 'Development that protects future generations is ______.'], remediationAnswers: '1. HDI 2. medium 3. sustainable',
  homework: 'Compare Cameroon with one African country using three development indicators.', homeworkTag: 'This prepares Lesson 8: Strategies of Development.',
  bilingual: [['Development', 'Le développement'], ['Growth', 'La croissance'], ['Income', 'Le revenu'], ['Life expectancy', "L'espérance de vie"], ['Literacy', "L'alphabétisation"], ['Gap', "L'écart"]],
});

module.exports = { L, B };
if (require.main === module) run(L, B, process.argv.slice(2).length ? process.argv.slice(2) : null);
