// UPPER SIXTH ARTS — ECONOMIC GEOGRAPHY part 2: ENERGY, MINERALS, WATER, INDUSTRY (Module 6: lessons 11, 13–26, PW2, PW3, FS3, FS4, FS5). The syllabus has no lesson 12.
const { run } = require('./sixth');
const { B } = require('./v2_usa_eco1');
const E1 = 'Power Resources', E2 = 'Mineral Resources', I1 = 'Nature of Manufacturing Industries', I2 = 'Distribution of Industries', I3 = 'Industrial Structure and Changes', I4 = 'Theories of Industrial Location', T6 = 'Geography of Cameroon';
const L = [];

L.push({ no: 11, title: 'Energy Resources', topic: E1, subtopic: 'Power Resources',
  notions: 'Energy, fossil fuel, renewable energy, hydro-electricity, energy conservation.', focus: 'Definition and classification; sources and world distribution (producers and consumers); importance; problems (exhaustion, pollution); future energy sources; conservation.',
  competence: 'Learners are able to classify energy resources, describe their distribution and propose sustainable solutions.',
  objectives: ['Classify energy resources.', 'Describe world producers and consumers.', 'Explain problems of energy and future sources.'],
  recall: ['Oil and coal are non-renewable.', 'Rivers can produce electricity.'],
  situation: 'Cameroon produces oil and hydro-electricity, yet many villages have no electricity and towns suffer power cuts. Meanwhile, the burning of oil and coal in the world changes the climate.',
  sitQA: [['What is the problem in the situation?', 'Energy is unevenly available and some sources pollute.'], ['Which energy sources does Cameroon use?', 'Hydro-electricity, oil, gas and wood.'], ['Which sources are clean?', 'Renewable sources like hydro, solar and wind.']],
  justification: 'This lesson helps us to understand energy, a key resource for development.',
  activities: [
    { sec: 'I. CLASSIFICATION', img: 'energy_class_big.png', caption: 'Renewable and non-renewable energy.', q: 'Give two renewable and two non-renewable energy sources.', a: 'Renewable: solar, hydro. Non-renewable: oil, coal.', noProj: 'sort energy sources.' },
    { sec: 'II. DISTRIBUTION', img: 'energy_mix_big.png', caption: 'World energy use by source (approximate).', q: 'What share of world energy comes from fossil fuels?', a: 'About 80 %.', noProj: 'read the bars.' },
    { sec: 'II. DISTRIBUTION', img: 'oil_producers_big.png', caption: 'Main oil producers (approximate).', q: 'Name the three largest oil producers.', a: 'USA, Saudi Arabia and Russia.', noProj: 'find them on a map.' },
    { sec: 'III. PROBLEMS', img: 'usa_offshore.jpg', caption: 'An offshore oil platform.', q: 'Give two problems of fossil fuels.', a: 'They will run out and they pollute (greenhouse gases, oil spills).', noProj: 'discuss pollution.' },
    { sec: 'IV. FUTURE ENERGY', img: 'f4_solar.jpg', caption: 'Solar panels.', q: 'Why are solar and wind called clean energy?', a: 'They do not produce greenhouse gases and never run out.', noProj: 'discuss solar in villages.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Energy resource:', 'It is a source of power used for work, heat and light.'], ['Fossil fuel:', 'It is a fuel formed from ancient plants and animals, like coal, oil and gas.'], ['Energy conservation:', 'It is using less energy or using it more efficiently.']] },
    { title: 'II. Sources, Distribution and Importance', items: [['A. Classification:', 'Non-renewable sources are oil, coal, gas and uranium. Renewable sources are hydro, solar, wind, geothermal, tidal and biomass.'], ['B. Distribution:', 'Oil is concentrated in the Middle East, Russia and the Americas. The USA, China and Europe are the largest consumers.'], ['C. Importance:', 'Energy powers industry, transport, homes and farms. Energy use is linked to development.']] },
    { title: 'III. Problems and Solutions', items: [['A. Problems:', 'Fossil fuels will run out and cause air pollution and climate change. Oil spills damage seas and coasts.'], ['B. Future sources:', 'HEP, solar, wind, geothermal and biomass are clean and renewable. Cameroon has huge hydro potential.'], ['C. Conservation:', 'Efficient lamps, insulation and public transport save energy. Recycling also reduces energy use.']], draw: { img: 'energy_class_big.png', caption: 'Copy the classification.' } },
  ],
  evaluation: [['Classify energy resources with two examples each.', 'Non-renewable: oil, coal. Renewable: hydro, solar.'], ['Give two problems of fossil fuels and two solutions.', 'Problems: exhaustion, pollution. Solutions: renewable energy, conservation.']],
  remediation: ['Coal, oil and gas are ______ fuels.', 'Energy from rivers is ______.', 'Using less energy is energy ______.'], remediationAnswers: '1. fossil 2. hydro-electricity 3. conservation',
  homework: 'List the energy sources used in your home and suggest how to save energy.', homeworkTag: 'This prepares Lesson 13: Minerals and Mining.',
  bilingual: [['Energy', "L'énergie"], ['Fossil fuel', 'Le combustible fossile'], ['Solar energy', "L'énergie solaire"], ['Wind', 'Le vent'], ['Power cut', 'La coupure de courant'], ['Conservation', 'Les économies d\'énergie']],
});

L.push({ no: 13, title: 'Minerals and Mining', topic: E2, subtopic: 'Mineral Resources',
  notions: 'Mineral, ore, ferrous, non-ferrous, open-cast mining, shaft mining, placer mining, conservation.', focus: 'Definition and classification; world distribution, producers and consumers; methods of extraction; problems; conservation.',
  competence: 'Learners are able to classify minerals, describe mining methods and propose conservation measures.',
  objectives: ['Classify minerals.', 'Describe the methods of mineral extraction.', 'Explain the problems of mining and ways of conserving minerals.'],
  recall: ['Minerals are non-renewable.', 'Cameroon has bauxite, iron ore and gold.'],
  situation: 'In the East Region, men dig pits by hand to find gold, while a large company plans an open-pit iron mine at Mbalam. Villagers worry about their rivers and farms.',
  sitQA: [['What is the problem in the situation?', 'Mining brings money but can damage the environment.'], ['Name two mining methods in the situation.', 'Artisanal digging and open-pit mining.'], ['Why do villagers worry?', 'Mining can pollute rivers and destroy farmland.']],
  justification: 'This lesson helps us to understand mining and its effects on people and nature.',
  activities: [
    { sec: 'I. CLASSIFICATION', img: 'mineral_class_big.png', caption: 'Types of minerals.', q: 'Distinguish ferrous and non-ferrous minerals.', a: 'Ferrous minerals contain iron; non-ferrous minerals do not (bauxite, copper, gold).', noProj: 'list minerals.' },
    { sec: 'II. METHODS', img: 'mining_methods_big.png', caption: 'Methods of mining.', q: 'When is open-cast mining used?', a: 'When the mineral is near the surface.', noProj: 'draw the methods.' },
    { sec: 'II. METHODS', img: 'usa_openpit.jpg', caption: 'An open-pit mine.', q: 'Give one advantage and one disadvantage of open-pit mining.', a: 'Advantage: cheap and safe. Disadvantage: huge scars on the landscape.', noProj: 'discuss mine scars.' },
    { sec: 'III. PROBLEMS', img: 'usa_goldminers.jpg', caption: 'Small-scale gold miners.', q: 'Give two problems of artisanal mining.', a: 'Dangerous pits and polluted rivers (mercury).', noProj: 'discuss gold mining in the East.' },
    { sec: 'IV. CONSERVATION', img: 'mineral_problems_big.png', caption: 'Problems and conservation.', q: 'Give two ways of conserving minerals.', a: 'Recycling and using substitutes (also reducing waste).', noProj: 'discuss recycling metal.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Mineral:', 'It is a natural substance in the Earth\'s crust with a definite composition.'], ['Ore:', 'It is rock that contains enough of a mineral to be mined profitably.'], ['Mining:', 'It is the extraction of minerals from the ground.']] },
    { title: 'II. Classification and Distribution', items: [['A. Types:', 'Metallic minerals are ferrous (iron) or non-ferrous (bauxite, copper, gold). Non-metallic minerals include limestone, salt and diamonds.'], ['B. Distribution:', 'Australia, China, Brazil, Russia, South Africa and the DR Congo are major producers. China, the USA and Europe are major consumers.'], ['C. Methods:', 'Open-cast mining takes near-surface ores, and shaft mining reaches deep ores. Placer mining washes river sands, and drilling extracts oil and gas.']] },
    { title: 'III. Problems and Conservation', items: [['A. Problems:', 'Minerals run out and leave ghost towns. Mining causes land scars, pollution and deforestation.'], ['B. Economic problems:', 'World prices rise and fall, and poor countries export ore cheaply. Accidents and child labour occur in artisanal mines.'], ['C. Conservation:', 'Recycling, substitutes and efficient use save minerals. Laws must force companies to restore land.']], draw: { img: 'mining_methods_big.png', caption: 'Copy the mining methods.' } },
  ],
  evaluation: [['Describe two methods of mining.', 'Open-cast: near-surface ore removed from a pit. Shaft: deep tunnels to reach ore.'], ['Give two ways of conserving minerals.', 'Recycling and substitutes.']],
  remediation: ['Rock rich in a mineral is an ______.', 'Bauxite is a ______ mineral.', 'Washing river sands for gold is ______ mining.'], remediationAnswers: '1. ore 2. non-ferrous 3. placer',
  homework: 'List objects at home made from minerals and name the mineral.', homeworkTag: 'This prepares Further Study 3: Mineral and Energy Resources of Cameroon.',
  bilingual: [['Mineral', 'Le minerai, le minéral'], ['Mine', 'La mine'], ['Ore', 'Le minerai'], ['Open-cast', 'À ciel ouvert'], ['Recycling', 'Le recyclage'], ['Gold', "L'or"]],
});

L.push({ kind: 'Further Study', no: 3, title: 'Management of Mineral and Energy Resources in Cameroon', topic: T6, subtopic: 'Mineral and Energy Resources of Cameroon',
  notions: 'Oil, natural gas, bauxite, iron ore, gold, cobalt, SONARA, SNH, sustainable exploitation.', focus: 'Low level of exploitation; minerals, their distribution, quality and quantity; exploitation methods and stakeholders; uses; problems and state efforts; benefits; sustainable measures.',
  competence: 'Learners are able to describe Cameroon\'s mineral and energy resources and explain how to exploit them sustainably.',
  objectives: ['Locate the main minerals and energy resources of Cameroon.', 'Explain their exploitation, uses and problems.', 'Explain the benefits and sustainable measures.'],
  recall: ['Minerals are non-renewable.', 'Cameroon produces oil and hydro-electricity.'],
  situation: 'Cameroon has oil, gas, bauxite, iron ore, cobalt and gold, but most of these minerals are still in the ground. Bauxite is found in the Adamawa, yet the aluminium plant at Edéa imports its alumina.',
  sitQA: [['What is the problem in the situation?', 'Cameroon\'s minerals are little exploited.'], ['Why is bauxite not used at Edéa?', 'Lack of railway, capital and processing plants.'], ['Which mineral is most exploited?', 'Oil.']],
  justification: 'This further study helps us to know the mineral wealth of Cameroon and how to use it well.',
  activities: [
    { sec: 'I. DISTRIBUTION', img: 'cmr_minerals_big.png', caption: 'Main minerals of Cameroon (simplified).', q: 'Where are oil, bauxite and iron ore found in Cameroon?', a: 'Oil offshore (Rio del Rey, Kribi); bauxite in the Adamawa and West; iron ore at Mbalam and Kribi.', noProj: 'draw the map.' },
    { sec: 'II. EXPLOITATION', img: 'usa_offshore.jpg', caption: 'An offshore oil platform.', q: 'Who exploits oil in Cameroon?', a: 'Foreign companies with the state (SNH); it is refined at SONARA in Limbe.', noProj: 'list stakeholders.' },
    { sec: 'II. EXPLOITATION', img: 'usa_goldminers.jpg', caption: 'Artisanal gold miners.', q: 'How is gold mined in the East?', a: 'Mostly by artisanal miners and some small companies.', noProj: 'discuss artisanal mining.' },
    { sec: 'III. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A muddy road in the interior.', q: 'Give two problems hindering mineral exploitation.', a: 'Poor transport and lack of capital (also technology, world prices).', noProj: 'list problems.' },
    { sec: 'IV. BENEFITS', img: 'usa_smelter.jpg', caption: 'An aluminium smelter.', q: 'Give two benefits of mineral exploitation.', a: 'Export income and jobs (also industry and infrastructure).', noProj: 'discuss ALUCAM at Edéa.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Proven reserve:', 'It is a mineral deposit known to exist in a quantity worth mining.'], ['Sustainable exploitation:', 'It is using a resource without destroying the environment or future chances.']] },
    { title: 'II. Resources and Exploitation', items: [['A. Energy minerals:', 'Oil comes from offshore fields near Rio del Rey and Kribi, and gas from Logbaba and Kribi. Oil is refined at SONARA in Limbe.'], ['B. Other minerals:', 'Bauxite is found at Minim-Martap and Fongo-Tongo, iron ore at Mbalam and Kribi, cobalt at Lomié. Gold is mined in the East, and limestone at Figuil.'], ['C. Stakeholders and uses:', 'The state (SNH, SONAMINES), foreign companies and artisanal miners are involved. Minerals give fuel, cement, jewellery and export income.']] },
    { title: 'III. Problems, Benefits and Measures', items: [['A. Problems:', 'Exploitation is low because of poor transport, lack of capital, technology and energy. Artisanal mining pollutes and is poorly controlled.'], ['B. Benefits:', 'Mining brings export income, jobs, roads and taxes. It can supply industries.'], ['C. Measures:', 'The mining code, SONAMINES and new railways (Mbalam–Kribi) aim at better exploitation. Environmental rules must protect land and rivers.']] },
  ],
  evaluation: [['Name four minerals of Cameroon and their location.', 'Oil (offshore), bauxite (Adamawa), iron ore (Mbalam), gold (East).'], ['Give two problems hindering mineral exploitation in Cameroon.', 'Poor transport and lack of capital (also technology).']],
  remediation: ['Oil is refined at ______ in Limbe.', 'Bauxite is found at Minim-______.', 'Gold is mined mainly in the ______ Region.'], remediationAnswers: '1. SONARA 2. Martap 3. East',
  homework: 'Draw the mineral map of Cameroon.', homeworkTag: 'This prepares Further Study 4: Management of Water Resources.',
  bilingual: [['Oil field', 'Le gisement pétrolier'], ['Refinery', 'La raffinerie'], ['Bauxite', 'La bauxite'], ['Iron ore', 'Le minerai de fer'], ['Mining code', 'Le code minier'], ['Deposit', 'Le gisement']],
});

L.push({ kind: 'Further Study', no: 4, title: 'Management of Water Resources in Cameroon', topic: T6, subtopic: 'Water Resources of Cameroon',
  notions: 'Water resources, fishing, aquaculture, irrigation, flood-retreat farming, hydro-electricity, SEMRY, UNVDA.', focus: 'Distribution of water bodies and their resources and uses; fishing (modern and traditional), problems and impacts; irrigation schemes, benefits and problems.',
  competence: 'Learners are able to describe how Cameroon uses its water resources and propose improvements.',
  objectives: ['Describe the water bodies of Cameroon and their uses.', 'Explain fishing and its problems.', 'Explain irrigation schemes, their benefits and problems.'],
  recall: ['Cameroon has four drainage basins.', 'Dams produce hydro-electricity.'],
  situation: 'Around Yagoua, SEMRY grows irrigated rice with water from the Logone. On Lake Lagdo and the coast, fishermen catch fish for the markets. The Lom Pangar dam regulates the Sanaga for electricity.',
  sitQA: [['What is the problem in the situation?', 'Water is used in many ways.'], ['Name three uses of water in the situation.', 'Irrigation, fishing and electricity.'], ['What is SEMRY?', 'A state rice irrigation company in the Far North.']],
  justification: 'This further study helps us to use the water resources of Cameroon wisely.',
  activities: [
    { sec: 'I. DISTRIBUTION AND USES', img: 'cmr_water_big.png', caption: 'Main water uses in Cameroon (simplified).', q: 'Name two dams and their uses.', a: 'Song Loulou (electricity) and Lagdo (electricity, irrigation, fishing).', noProj: 'draw the map.' },
    { sec: 'II. FISHING', img: 'usa_fishing.jpg', caption: 'Fishing boats.', q: 'Distinguish traditional and modern fishing.', a: 'Traditional: canoes, nets, small catches. Modern: trawlers, cold storage, large catches.', noProj: 'describe fishing on the coast.' },
    { sec: 'II. FISHING PROBLEMS', img: 'f2t_lake_chad.jpg', caption: 'Lake Chad.', q: 'Give two problems of fishing in Cameroon.', a: 'Shrinking lakes and overfishing (also poor storage, insecurity).', noProj: 'discuss Lake Chad.' },
    { sec: 'III. IRRIGATION', img: 'f4_ricefield.jpg', caption: 'Irrigated rice.', q: 'Name two irrigation schemes and their crop.', a: 'SEMRY (Yagoua, Maga) and UNVDA (Ndop): rice.', noProj: 'find them on the map.' },
    { sec: 'III. BENEFITS AND PROBLEMS', img: 'f2t_lagdo.jpg', caption: 'The Lagdo dam on the Benue.', q: 'Give one benefit and one problem of irrigation schemes.', a: 'Benefit: food and income all year. Problem: high costs, waterborne diseases, salinisation.', noProj: 'list benefits and problems.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Water resources:', 'They are all waters that people can use: seas, rivers, lakes and groundwater.'], ['Irrigation:', 'It is the artificial supply of water to crops.'], ['Flood-retreat farming:', 'It is farming on land left wet after floods go down.']] },
    { title: 'II. Water Bodies and Fishing', items: [['A. Water bodies and uses:', 'The Atlantic coast, rivers like the Sanaga and Benue, and lakes like Chad and Lagdo supply water. They are used for fishing, transport, energy, domestic use and irrigation.'], ['B. Fishing:', 'Traditional fishermen use canoes and nets on the coast and lakes. Modern trawlers and fish farms are few.'], ['C. Problems and impacts:', 'Overfishing, poor storage and shrinking Lake Chad reduce catches. Fishing gives food, jobs and income.']] },
    { title: 'III. Irrigation and Hydro-electricity', items: [['A. Schemes:', 'SEMRY grows rice at Yagoua and Maga with Logone water, and UNVDA at Ndop. Lagdo irrigates land on the Benue.'], ['B. Benefits:', 'They give food, jobs and income all year. Dams like Song Loulou, Edéa, Lagdo and Memve\'ele produce electricity.'], ['C. Problems:', 'Schemes are costly and often poorly maintained. Waterborne diseases, silting and floods downstream are problems.']], draw: { img: 'cmr_water_big.png', caption: 'Copy the map.' } },
  ],
  evaluation: [['Give three uses of water resources in Cameroon.', 'Fishing, irrigation, electricity (also domestic use, transport).'], ['Give two problems of irrigation schemes.', 'High costs and waterborne diseases (also salinisation, poor maintenance).']],
  remediation: ['SEMRY grows ______ at Yagoua.', 'UNVDA is at ______.', 'Song Loulou produces ______.'], remediationAnswers: '1. rice 2. Ndop 3. electricity',
  homework: 'Describe how water is used in your area.', homeworkTag: 'This prepares Lesson 14: What is Manufacturing?',
  bilingual: [['Water resources', 'Les ressources en eau'], ['Fishing', 'La pêche'], ['Irrigation', "L'irrigation"], ['Dam', 'Le barrage'], ['Fish farming', 'La pisciculture'], ['Lake', 'Le lac']],
});

L.push({ no: 14, title: 'What is Manufacturing?', topic: I1, subtopic: 'Nature of Manufacturing Industries',
  notions: 'Industry, manufacturing, primary, secondary, tertiary, quaternary, heavy industry, light industry, industrial system.', focus: 'Meaning and classification of industries; the industrial system.',
  competence: 'Learners are able to classify industries and describe the industrial system.',
  objectives: ['Define manufacturing industry.', 'Classify industries.', 'Describe the industrial system.'],
  recall: ['Raw materials come from farms, mines and forests.', 'A system has inputs, processes and outputs.'],
  situation: 'In Douala, a brewery turns maize, water and malt into beer; in Garoua, CICAM turns cotton into cloth. A learner asks what makes these activities "manufacturing".',
  sitQA: [['What is the problem in the situation?', 'Learners want to define manufacturing.'], ['What do the factories do?', 'They change raw materials into finished products.'], ['To which sector do they belong?', 'The secondary sector.']],
  justification: 'This lesson introduces industry, a key driver of development.',
  activities: [
    { sec: 'I. MEANING', img: 'usa_brewery.jpg', caption: 'A bottling line in a brewery.', q: 'What is manufacturing?', a: 'Changing raw materials into finished goods in factories.', noProj: 'list factories in Cameroon.' },
    { sec: 'II. CLASSIFICATION', img: 'industry_class_big.png', caption: 'The four economic sectors.', q: 'To which sector do farming, factories and banks belong?', a: 'Primary, secondary and tertiary.', noProj: 'sort jobs by sector.' },
    { sec: 'II. CLASSIFICATION', img: 'usa_steel.jpg', caption: 'A steel works.', q: 'Distinguish heavy and light industry.', a: 'Heavy: bulky raw materials and products (steel). Light: small goods (clothes, electronics).', noProj: 'give examples.' },
    { sec: 'III. THE INDUSTRIAL SYSTEM', img: 'industrial_system_big.png', caption: 'The factory as a system.', q: 'Name two inputs and two outputs of a factory.', a: 'Inputs: raw materials, labour. Outputs: products, waste.', noProj: 'draw the system.' },
    { sec: 'III. THE INDUSTRIAL SYSTEM', img: 'f2t_textile_factory.jpg', caption: 'A textile factory.', q: 'What is the feedback in an industrial system?', a: 'Profits are reinvested in new machines and technology.', noProj: 'discuss CICAM.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Manufacturing:', 'It is the processing of raw materials into finished goods.'], ['Heavy industry:', 'It is industry using bulky raw materials to make large products.'], ['Light industry:', 'It is industry making small, light goods.']] },
    { title: 'II. Classification', items: [['A. By sector:', 'Primary activities extract resources, and secondary activities manufacture. Tertiary activities give services, and quaternary activities deal with research and information.'], ['B. By size and weight:', 'Heavy industries include steel and shipbuilding. Light industries include clothing and electronics.'], ['C. Other classifications:', 'Industries can be processing or assembly industries. They can also be raw-material, market or footloose industries.']] },
    { title: 'III. The Industrial System', items: [['A. Inputs:', 'Raw materials, labour, capital, power and land enter the factory. Technology and management are also inputs.'], ['B. Processes and outputs:', 'Processing, assembly and packing make products. Outputs are goods, profits, wages and waste.'], ['C. Feedback:', 'Profits are reinvested in the factory. Losses can lead to closure.']], draw: { img: 'industrial_system_big.png', caption: 'Copy the industrial system.' } },
  ],
  evaluation: [['Distinguish heavy and light industry with examples.', 'Heavy: steel, shipbuilding. Light: clothing, electronics.'], ['Name the four economic sectors.', 'Primary, secondary, tertiary and quaternary.']],
  remediation: ['Manufacturing belongs to the ______ sector.', 'Steel making is ______ industry.', 'Research belongs to the ______ sector.'], remediationAnswers: '1. secondary 2. heavy 3. quaternary',
  homework: 'Draw a factory in your area as a system.', homeworkTag: 'This prepares Lesson 15: Industrial Location.',
  bilingual: [['Industry', "L'industrie"], ['Factory', "L'usine"], ['Raw material', 'La matière première'], ['Finished good', 'Le produit fini'], ['Sector', 'Le secteur'], ['Assembly', "L'assemblage"]],
});

L.push({ no: 15, title: 'Industrial Location', topic: I2, subtopic: 'Distribution of Industries',
  notions: 'Industrial location, optimum location, least-cost location, raw-material oriented, market oriented, footloose.', focus: 'The economic (optimum) location of industries; case studies.',
  competence: 'Learners are able to explain the idea of optimum location with examples.',
  objectives: ['Define optimum location.', 'Distinguish raw-material, market and footloose locations.', 'Study examples of industrial location.'],
  recall: ['Factories need raw materials and markets.', 'Transport costs affect location.'],
  situation: 'The aluminium smelter is at Edéa near a hydro-electric dam; breweries are in big towns; sawmills are near the forests of the East. Each factory owner chose a different kind of place.',
  sitQA: [['What is the problem in the situation?', 'Industries are located in different places.'], ['Why is the smelter near a dam?', 'It needs very large amounts of electricity.'], ['Why are breweries in towns?', 'Near their market; beer is heavy to transport.']],
  justification: 'This lesson helps us to explain where factories are built.',
  activities: [
    { sec: 'I. OPTIMUM LOCATION', img: 'location_factors_big.png', caption: 'Factors that pull a factory.', q: 'What is the optimum location of a factory?', a: 'The place where profit is highest (costs lowest or sales highest).', noProj: 'draw the factors.' },
    { sec: 'II. RAW-MATERIAL LOCATION', img: 'usa_sawmill.jpg', caption: 'Logs at a sawmill.', q: 'Why are sawmills near forests?', a: 'Logs are heavy and lose weight when cut.', noProj: 'mention sawmills in the East.' },
    { sec: 'II. POWER LOCATION', img: 'usa_smelter.jpg', caption: 'An aluminium smelter.', q: 'Why is ALUCAM at Edéa?', a: 'It needs cheap hydro-electricity from the Sanaga dams and is near the port.', noProj: 'find Edéa.' },
    { sec: 'III. MARKET LOCATION', img: 'usa_brewery.jpg', caption: 'A brewery.', q: 'Why are breweries market-oriented?', a: 'Water is added, so the product is heavier than the raw materials.', noProj: 'list market industries.' },
    { sec: 'III. FOOTLOOSE', img: 'usa_techpark.jpg', caption: 'Skilled workers in a high-tech firm.', q: 'What is a footloose industry?', a: 'One that is not tied to raw materials or markets, like electronics or software.', noProj: 'discuss call centres.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Optimum location:', 'It is the place where a factory makes the highest profit.'], ['Footloose industry:', 'It is an industry free to locate in many places.']] },
    { title: 'II. Types of Location', items: [['A. Raw-material location:', 'Industries whose raw materials lose weight or perish locate near them. Sawmills and sugar mills are examples.'], ['B. Power location:', 'Industries needing much energy locate near cheap power. Aluminium smelting at Edéa uses hydro-electricity.'], ['C. Market location:', 'Industries whose products gain weight or break easily locate near markets. Breweries and bakeries are examples.'], ['D. Footloose location:', 'High-tech and service industries can locate anywhere. They look for skilled labour and a pleasant environment.']] },
    { title: 'III. Case Studies', items: [['A. In Cameroon:', 'ALUCAM at Edéa (power and port), CICAM at Garoua (cotton) and breweries in Douala and Yaoundé (market). Most industries are in Douala.'], ['B. In the world:', 'Steel moved from coalfields to coasts, and car factories to markets and cheap labour. Electronics cluster in science parks.']] },
  ],
  evaluation: [['Distinguish raw-material and market location with examples.', 'Raw material: sawmill near forest. Market: brewery in town.'], ['Why is ALUCAM located at Edéa?', 'Cheap hydro-electricity and nearness to the port of Douala.']],
  remediation: ['The most profitable location is the ______ location.', 'Industries free to locate anywhere are ______.', 'Breweries are ______-oriented.'], remediationAnswers: '1. optimum 2. footloose 3. market',
  homework: 'Choose a factory in Cameroon and explain its location.', homeworkTag: 'This prepares Lesson 16: Factors of Industrial Location.',
  bilingual: [['Location', 'La localisation'], ['Optimum', 'Optimal'], ['Footloose', 'Non localisée (libre)'], ['Smelter', "L'usine d'électrolyse"], ['Sawmill', 'La scierie'], ['Brewery', 'La brasserie']],
});

L.push({ no: 16, title: 'Factors of Industrial Location', topic: I2, subtopic: 'Distribution of Industries',
  notions: 'Raw materials, market, power, transport, labour, capital, land, environment, human choice.', focus: 'Dynamic and complex nature of factors; economic factors; land and environment; other factors (patriotism, human choice).',
  competence: 'Learners are able to explain the factors that influence industrial location.',
  objectives: ['Explain the economic factors of industrial location.', 'Explain land and environmental factors.', 'Explain why factors change over time.'],
  recall: ['Factories choose optimum locations.', 'Transport costs rise with distance.'],
  situation: 'A businessman wants to build a biscuit factory. He must choose between Douala (port, market, many workers but congested) and a smaller town (cheap land but few workers and poor roads).',
  sitQA: [['What is the problem in the situation?', 'The businessman must weigh many factors.'], ['Give two advantages of Douala.', 'A large market and the port.'], ['Give one advantage of the small town.', 'Cheap land and less congestion.']],
  justification: 'This lesson helps us to understand how factory locations are chosen.',
  activities: [
    { sec: 'I. ECONOMIC FACTORS', img: 'location_factors_big.png', caption: 'Location factors.', q: 'Name four economic factors of industrial location.', a: 'Raw materials, market, power, transport (also labour, capital).', noProj: 'list factors.' },
    { sec: 'I. ECONOMIC FACTORS', img: 'usa_container.jpg', caption: 'A container ship.', q: 'Why do many industries locate near ports?', a: 'To import raw materials and export products cheaply.', noProj: 'discuss Douala.' },
    { sec: 'I. ECONOMIC FACTORS', img: 'usa_textile.jpg', caption: 'Textile workers.', q: 'Why do clothing factories move to countries with cheap labour?', a: 'Labour is their largest cost.', noProj: 'discuss Asia.' },
    { sec: 'II. LAND AND ENVIRONMENT', img: 'usa_techpark.jpg', caption: 'Skilled workers in a high-tech firm.', q: 'Why do modern industries prefer pleasant environments?', a: 'To attract skilled workers and have space to expand.', noProj: 'compare old and new industrial areas.' },
    { sec: 'III. OTHER FACTORS', img: 'f2t_factory_workers.jpg', caption: 'Factory workers.', q: 'How can personal choice influence location?', a: 'An owner may build in his home town (patriotism) or where he likes to live.', noProj: 'give local examples.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Location factor:', 'It is anything that affects where a factory is built.'], ['Agglomeration:', 'It is the grouping of firms in one place to share services.']] },
    { title: 'II. Economic Factors', items: [['A. Raw materials and power:', 'Heavy, perishable materials pull factories to their source. Cheap power attracts energy-hungry industries.'], ['B. Market and transport:', 'Large markets attract consumer industries. Ports, railways and roads reduce costs.'], ['C. Labour and capital:', 'Cheap or skilled labour attracts different industries. Banks and investors are found in big cities.']] },
    { title: 'III. Other Factors and Change', items: [['A. Land and environment:', 'Industries need cheap, flat land with space to expand. Pleasant, uncongested towns attract modern firms.'], ['B. Human choice:', 'Patriotism, tradition and personal preference also matter. Governments influence location too.'], ['C. Changing factors:', 'Improved transport and technology reduce the pull of raw materials. Today markets and labour matter more.']] },
  ],
  evaluation: [['Give four factors of industrial location.', 'Raw materials, market, transport, labour (also power, capital, land).'], ['Why do factors change over time?', 'New transport and technology change costs; markets and labour become more important.']],
  remediation: ['Heavy, perishable materials pull factories to their ______.', 'Clothing firms seek cheap ______.', 'Grouping of firms is ______.'], remediationAnswers: '1. source 2. labour 3. agglomeration',
  homework: 'Choose the best site for a biscuit factory in Cameroon and justify it.', homeworkTag: 'This prepares Lesson 17: Government Policy and Industrial Location.',
  bilingual: [['Factor', 'Le facteur'], ['Labour', 'La main-d\'œuvre'], ['Capital', 'Le capital'], ['Transport', 'Le transport'], ['Port', 'Le port'], ['Land', 'Le terrain']],
});

L.push({ no: 17, title: 'Government Policy and Industrial Location', topic: I2, subtopic: 'Distribution of Industries',
  notions: 'Government intervention, incentive, free zone, tax holiday, regional policy, planning.', focus: 'How and why governments intervene in industrial location (planning and incentives).',
  competence: 'Learners are able to explain how and why governments influence where industries locate.',
  objectives: ['Explain why governments intervene.', 'Describe the forms of intervention.', 'Give examples from the world and Cameroon.'],
  recall: ['Most industries in Cameroon are in Douala.', 'Regions develop unequally.'],
  situation: 'The government created an industrial zone at Kribi near the new deep-sea port and offers tax breaks to firms that invest there. It wants to reduce the concentration of industry in Douala.',
  sitQA: [['What is the problem in the situation?', 'Industries are concentrated in one city.'], ['What does the government offer?', 'Tax breaks and an industrial zone.'], ['Why?', 'To spread development and jobs.']],
  justification: 'This lesson helps us to understand the role of the state in industrial development.',
  activities: [
    { sec: 'I. WHY INTERVENE', img: 'lsa_douala.jpg', caption: 'Douala, the main industrial city.', q: 'Why do governments intervene in industrial location?', a: 'To reduce regional inequality, create jobs and protect the environment.', noProj: 'discuss regional inequality.' },
    { sec: 'II. HOW: INCENTIVES', img: 'usa_container.jpg', caption: 'A modern port.', q: 'Give two incentives offered to industries.', a: 'Tax holidays and cheap land (also grants, loans, free zones).', noProj: 'list incentives.' },
    { sec: 'II. HOW: PLANNING', img: 'usa_newtown.jpg', caption: 'A planned new town.', q: 'How can planning control industrial location?', a: 'By zoning land and refusing permits in crowded areas.', noProj: 'discuss industrial zones.' },
    { sec: 'III. EXAMPLES', img: 'usa_smelter.jpg', caption: 'An aluminium smelter.', q: 'Give one example of state-led industry in Cameroon.', a: 'ALUCAM at Edéa, CICAM at Garoua or SONARA at Limbe.', noProj: 'list state industries.' },
    { sec: 'III. EXAMPLES', img: 'usa_techpark.jpg', caption: 'Skilled workers in a high-tech firm.', q: 'What is a special economic (free) zone?', a: 'An area where firms pay low taxes and duties to attract investment.', noProj: 'mention Kribi.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Incentive:', 'It is an advantage given to encourage a firm to invest in a place.'], ['Free zone:', 'It is an area where firms pay few taxes and customs duties.'], ['Regional policy:', 'It is government action to reduce differences between regions.']] },
    { title: 'II. Why Governments Intervene', items: [['A. Regional balance:', 'Industry tends to concentrate in a few cities. States want jobs in poorer regions.'], ['B. Strategic and social reasons:', 'Governments protect key industries like energy and defence. They also reduce unemployment.'], ['C. Environment:', 'Planning keeps polluting industries away from homes. It protects fragile areas.']] },
    { title: 'III. How Governments Intervene', items: [['A. Incentives:', 'Grants, loans, tax holidays, cheap land and free zones attract firms. Infrastructure like ports and roads helps.'], ['B. Controls:', 'Permits, zoning and environmental laws restrict location. Some countries nationalise industries.'], ['C. Cameroon:', 'The state created ALUCAM, CICAM and SONARA and industrial zones at Bonabéri, Bassa and Kribi. The investment charter offers incentives.']] },
  ],
  evaluation: [['Give three reasons why governments intervene in industrial location.', 'Regional balance, jobs, environment (also strategic reasons).'], ['Give three incentives.', 'Tax holidays, grants, cheap land (also free zones).']],
  remediation: ['An advantage given to a firm is an ______.', 'An area with low taxes is a ______ zone.', 'Reducing regional differences is regional ______.'], remediationAnswers: '1. incentive 2. free 3. policy',
  homework: 'Suggest how the government could attract industries to your region.', homeworkTag: 'This prepares Lesson 18: The Changing Nature of Industrial Location.',
  bilingual: [['Government', "L'État"], ['Incentive', "L'incitation"], ['Tax holiday', "L'exonération fiscale"], ['Free zone', 'La zone franche'], ['Planning', "L'aménagement"], ['Investment', "L'investissement"]],
});

L.push({ no: 18, title: 'The Changing Nature of Industrial Location', topic: I2, subtopic: 'Distribution of Industries',
  notions: 'Industrial shift, relocation, iron and steel industry, coastal location, global shift.', focus: 'Meaning; the case of iron and steel; factors and implications of changes.',
  competence: 'Learners are able to explain why industrial locations change over time.',
  objectives: ['Explain what a change in industrial location means.', 'Explain the changing location of iron and steel.', 'Explain the factors and implications.'],
  recall: ['Location factors change over time.', 'Heavy industry used much coal.'],
  situation: 'In the 1800s, steel works in Britain were built on coalfields. Today, the biggest steel works are on the coasts, and most steel is made in China.',
  sitQA: [['What is the problem in the situation?', 'Industries have moved to new places.'], ['Why were steel works on coalfields?', 'They used huge amounts of coal.'], ['Why are they now on coasts?', 'They import ore and coal by sea.']],
  justification: 'This lesson helps us to understand that industrial geography keeps changing.',
  activities: [
    { sec: 'I. MEANING', img: 'iron_steel_big.png', caption: 'The changing location of iron and steel.', q: 'Describe the three stages of steel location.', a: 'Coalfields, then ore fields, then coasts.', noProj: 'draw the three boxes.' },
    { sec: 'II. IRON AND STEEL', img: 'usa_steel.jpg', caption: 'A steel works.', q: 'Why did steel works move from coalfields?', a: 'Less coal was needed and local coal and ore ran out.', noProj: 'discuss technology.' },
    { sec: 'II. IRON AND STEEL', img: 'usa_container.jpg', caption: 'A large ship.', q: 'Why are modern steel works on the coast?', a: 'They import ore and coal by cheap bulk ships and export steel.', noProj: 'find coastal steel works.' },
    { sec: 'III. GLOBAL SHIFT', img: 'deindust_big.png', caption: 'Manufacturing in the UK and China (approximate).', q: 'What is the global shift in manufacturing?', a: 'The move of factories from old industrial countries to Asia.', noProj: 'read the graph.' },
    { sec: 'IV. IMPLICATIONS', img: 'usa_carfactory.jpg', caption: 'A modern factory with robots.', q: 'Give one implication for old industrial regions.', a: 'Unemployment and derelict land (need for new industries).', noProj: 'discuss consequences.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Industrial relocation:', 'It is the movement of an industry to a new place.'], ['Global shift:', 'It is the movement of manufacturing from rich countries to Asia and other LEDCs.']] },
    { title: 'II. The Case of Iron and Steel', items: [['A. Coalfield stage:', 'In the 1800s steel works were on coalfields because coal was the heaviest input. Examples were South Wales and the Ruhr.'], ['B. Ore field stage:', 'New methods used less coal, so some works moved to iron ore fields. Lorraine in France is an example.'], ['C. Coastal stage:', 'Local resources ran out, and imported ore and coal came by sea. Modern works are at coastal sites like Dunkirk and Taranto.']] },
    { title: 'III. Factors and Implications', items: [['A. Factors:', 'Exhaustion of resources, new technology, cheaper transport and cheap labour abroad cause change. Government policy also matters.'], ['B. Implications for old regions:', 'Factories close, causing unemployment and derelict land. Regions must find new industries.'], ['C. Implications for new regions:', 'NICs gain jobs and growth. They also face pollution and poor working conditions.']], draw: { img: 'iron_steel_big.png', caption: 'Copy the stages.' } },
  ],
  evaluation: [['Explain the changing location of iron and steel.', 'From coalfields to ore fields to coasts, because of less coal use, exhaustion and cheap sea transport.'], ['Give two implications of industrial relocation.', 'Unemployment in old regions; growth in new regions.']],
  remediation: ['Early steel works were on ______.', 'Modern steel works are on the ______.', 'The move of factories to Asia is the global ______.'], remediationAnswers: '1. coalfields 2. coast 3. shift',
  homework: 'Explain why many clothes sold in Cameroon are made in Asia.', homeworkTag: 'This prepares Lesson 19: Industrial Agglomerations.',
  bilingual: [['Relocation', 'La délocalisation'], ['Steel', "L'acier"], ['Coalfield', 'Le bassin houiller'], ['Coast', 'La côte'], ['Shift', 'Le déplacement'], ['Derelict land', 'La friche industrielle']],
});

L.push({ no: 19, title: 'Industrial Agglomerations', topic: I2, subtopic: 'Distribution of Industries',
  notions: 'Agglomeration, industrial region, AICs, NICs, Asian tigers, economies of scale, external economies.', focus: 'Meaning; main world industrial zones and groups (AICs, NICs, tigers, dragons, workshop economies); factors; advantages and disadvantages; why few industries in the developing world.',
  competence: 'Learners are able to describe the main industrial regions of the world and explain agglomeration.',
  objectives: ['Define industrial agglomeration.', 'Describe the main industrial zones and groups of countries.', 'Explain the causes, advantages and disadvantages of agglomeration and the weak industry of LEDCs.'],
  recall: ['Industries group in cities.', 'Manufacturing has shifted to Asia.'],
  situation: 'In Douala, factories, banks, suppliers and the port are close together. Around the world, industry is concentrated in North America, Europe and East Asia, while Africa has few factories.',
  sitQA: [['What is the problem in the situation?', 'Industry is concentrated in few places.'], ['What is this grouping called?', 'Industrial agglomeration.'], ['Why does Africa have few factories?', 'Lack of capital, technology, skills and markets.']],
  justification: 'This lesson helps us to understand why industry concentrates and why Africa is little industrialised.',
  activities: [
    { sec: 'I. MEANING', img: 'lsa_douala.jpg', caption: 'Douala.', q: 'What is an industrial agglomeration?', a: 'A grouping of many industries in one area.', noProj: 'list industries in Douala.' },
    { sec: 'II. WORLD ZONES', img: 'industry_world_big.png', caption: 'Main industrial regions of the world (simplified).', q: 'Name two old industrial regions and two newly industrialising countries.', a: 'NE USA and Western Europe; China and South Korea.', noProj: 'find them on a map.' },
    { sec: 'III. ADVANTAGES', img: 'usa_carfactory.jpg', caption: 'A car factory.', q: 'Give two advantages of agglomeration.', a: 'Shared services and suppliers (external economies), and a pool of skilled labour.', noProj: 'list advantages.' },
    { sec: 'III. DISADVANTAGES', img: 'usa_traffic.jpg', caption: 'Traffic congestion.', q: 'Give two disadvantages of agglomeration.', a: 'Congestion and pollution (also high land prices).', noProj: 'list disadvantages.' },
    { sec: 'IV. DEVELOPING WORLD', img: 'usa_textile.jpg', caption: 'Workers in a textile factory.', q: 'Why are there few manufacturing industries in most LEDCs?', a: 'Lack of capital, skills, power, markets and good transport.', noProj: 'discuss Cameroon.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Industrial agglomeration:', 'It is the grouping of many industries in one area.'], ['External economies:', 'They are cost savings from sharing services and suppliers with nearby firms.'], ['NIC:', 'It is a newly industrialising country, like China, South Korea or Brazil.']] },
    { title: 'II. World Industrial Zones', items: [['A. Advanced industrial countries (AICs):', 'The USA, Western Europe and Japan industrialised first. They now focus on high technology and services.'], ['B. NICs and tigers:', 'South Korea, Taiwan, Singapore and Hong Kong (tigers) grew fast after 1960. China became the "factory of the world".'], ['C. Factors:', 'Raw materials, markets, capital, labour and transport created these zones. Government support and exports drove the NICs.']] },
    { title: 'III. Advantages, Disadvantages and LEDCs', items: [['A. Advantages:', 'Firms share suppliers, services, skilled labour and infrastructure. Costs fall and ideas spread.'], ['B. Disadvantages:', 'Congestion, pollution and high land prices appear. Other regions are left behind.'], ['C. Few industries in LEDCs:', 'Lack of capital, skills, power, transport and markets limits industry. Colonial history made them exporters of raw materials.']], draw: { img: 'industry_world_big.png', caption: 'Sketch the main industrial regions.' } },
  ],
  evaluation: [['Give two advantages and two disadvantages of industrial agglomeration.', 'Advantages: shared services, skilled labour. Disadvantages: congestion, pollution.'], ['Why do LEDCs have few manufacturing industries?', 'Lack of capital, skills, power and markets (also colonial history).']],
  remediation: ['The grouping of industries is ______.', 'China is called the ______ of the world.', 'South Korea is an Asian ______.'], remediationAnswers: '1. agglomeration 2. factory 3. tiger',
  homework: 'Explain why most industries of Cameroon are in Douala.', homeworkTag: 'This prepares Practical Work 2: The Location Quotient.',
  bilingual: [['Agglomeration', "La concentration industrielle"], ['Industrial region', 'La région industrielle'], ['Newly industrialising country', 'Le pays nouvellement industrialisé'], ['Congestion', 'La congestion'], ['Supplier', 'Le fournisseur'], ['Skilled', 'Qualifié']],
});

L.push({ kind: 'Practical Work', no: 2, title: 'Measuring Industrial Agglomeration: The Location Quotient', topic: I2, subtopic: 'Distribution of Industries',
  notions: 'Location quotient, concentration, employment data.', focus: 'Meaning, formula, application, interpretation, advantages and disadvantages of the location quotient.',
  competence: 'Learners are able to calculate and interpret the location quotient.',
  objectives: ['State the formula of the location quotient.', 'Calculate LQ from data.', 'Interpret LQ and give its limits.'],
  recall: ['Industries concentrate in some regions.', 'Percentages compare parts of a whole.'],
  situation: 'The Ministry of Industry wants to know whether the textile industry is really concentrated in the North. It gives the class the number of textile workers and all workers in each region.',
  sitQA: [['What is the problem in the situation?', 'The class must measure concentration.'], ['What index will they use?', 'The location quotient.'], ['What does LQ > 1 mean?', 'The industry is concentrated in that region.']],
  justification: 'This practical work helps us to measure the concentration of industries.',
  activities: [
    { sec: 'I. THE FORMULA', img: 'lq_big.png', caption: 'Location quotients by region.', q: 'Write the formula of the location quotient.', a: 'LQ = (workers in the industry in the region ÷ all workers in the region) ÷ (workers in the industry in the country ÷ all workers in the country).', noProj: 'write the formula.' },
    { sec: 'II. CALCULATION', img: 'lq_big.png', caption: 'Worked example.', q: 'Calculate the LQ of the Centre (2,000 textile workers out of 200,000).', a: '(2,000 ÷ 200,000) ÷ (10,000 ÷ 500,000) = 0.01 ÷ 0.02 = 0.5.', noProj: 'calculate each region.' },
    { sec: 'III. INTERPRETATION', img: 'usa_textile.jpg', caption: 'Textile workers.', q: 'Interpret LQ = 3.0 for the North.', a: 'The North has three times its fair share: the industry is strongly concentrated there.', noProj: 'interpret each value.' },
    { sec: 'III. MAPPING', img: 'cmr_industry_big.png', caption: 'Industrial regions of Cameroon.', q: 'How can LQ results be shown on a map?', a: 'By a choropleth map shading regions by LQ.', noProj: 'shade a map.' },
    { sec: 'IV. LIMITS', img: 'f2t_factory_workers.jpg', caption: 'Factory workers.', q: 'Give one advantage and one limit of LQ.', a: 'Advantage: simple and comparable. Limit: depends on data quality and region size.', noProj: 'discuss limits.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Location quotient (LQ):', 'It is an index that compares the share of an industry in a region with its share in the country.']] },
    { title: 'II. Method', items: [['A. Formula:', 'LQ = (Ei ÷ E) in the region ÷ (Ni ÷ N) in the country. E and N are employment figures.'], ['B. Steps:', 'Calculate the share in the region, then the share in the country, and divide. Round to one decimal place.'], ['C. Interpretation:', 'LQ > 1 means concentration, LQ = 1 an average share and LQ < 1 under-representation. Results can be mapped.']] },
    { title: 'III. Advantages and Disadvantages', items: [['A. Advantages:', 'It is simple and allows comparison between regions and industries. It uses available employment data.'], ['B. Disadvantages:', 'It depends on accurate data and on how regions are drawn. It says nothing about output or firm size.']], draw: { img: 'lq_big.png', caption: 'Copy the table.' } },
  ],
  evaluation: [['A region has 600 of 30,000 workers in brewing; the country has 2,000 of 400,000. Find LQ.', '(600 ÷ 30,000) ÷ (2,000 ÷ 400,000) = 0.02 ÷ 0.005 = 4.0.'], ['What does LQ = 0.5 mean?', 'The industry is under-represented in the region.']],
  remediation: ['LQ > 1 means ______.', 'LQ = 1 means an ______ share.', 'LQ uses ______ data.'], remediationAnswers: '1. concentration 2. average 3. employment',
  homework: 'Calculate the LQ for each region using the table and draw a choropleth map.', homeworkTag: 'This prepares Lesson 20: Functional Linkages.',
  bilingual: [['Quotient', 'Le quotient'], ['Employment', "L'emploi"], ['Share', 'La part'], ['Concentration', 'La concentration'], ['Region', 'La région'], ['Data', 'Les données']],
});

L.push({ no: 20, title: 'Functional Linkages', topic: I3, subtopic: 'Industrial Structure and Changes',
  notions: 'Linkage, backward linkage, forward linkage, horizontal linkage, diagonal linkage, multiplier effect.', focus: 'Meaning and types of linkages; reasons; significance.',
  competence: 'Learners are able to explain industrial linkages and their importance.',
  objectives: ['Define functional linkage.', 'Distinguish types of linkages.', 'Explain the significance of linkages.'],
  recall: ['Industries group together.', 'Factories need suppliers.'],
  situation: 'A car factory needs steel, glass and tyres from other factories, and sells cars through dealers and garages. When the factory closed in a town, suppliers and garages also lost jobs.',
  sitQA: [['What is the problem in the situation?', 'Industries depend on each other.'], ['What are these connections called?', 'Functional linkages.'], ['Why did suppliers lose jobs?', 'Their customer factory closed.']],
  justification: 'This lesson helps us to understand the links between industries.',
  activities: [
    { sec: 'I. MEANING', img: 'linkages_big.png', caption: 'Backward and forward linkages.', q: 'Distinguish backward and forward linkages.', a: 'Backward: links with suppliers. Forward: links with customers.', noProj: 'draw the diagram.' },
    { sec: 'II. TYPES', img: 'usa_carfactory.jpg', caption: 'A car assembly line.', q: 'Name three suppliers of a car factory.', a: 'Steel, glass and tyre makers.', noProj: 'list suppliers.' },
    { sec: 'II. TYPES', img: 'usa_brewery.jpg', caption: 'A brewery bottling line.', q: 'Give one forward linkage of a brewery.', a: 'Distributors, bars and shops that sell the drinks.', noProj: 'list customers.' },
    { sec: 'III. REASONS', img: 'lsa_douala.jpg', caption: 'Douala.', q: 'Why do linked industries locate close together?', a: 'To reduce transport costs and deliver quickly.', noProj: 'discuss Douala.' },
    { sec: 'IV. SIGNIFICANCE', img: 'f2t_factory_workers.jpg', caption: 'Factory workers.', q: 'What is the multiplier effect?', a: 'One new industry creates more jobs in linked industries and services.', noProj: 'explain with an example.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Functional linkage:', 'It is a connection between firms through supplies, sales or services.'], ['Multiplier effect:', 'It is when one new activity creates more jobs and income in other activities.']] },
    { title: 'II. Types', items: [['A. Backward linkages:', 'They link a firm with its suppliers of materials and parts. A car factory buys steel and tyres.'], ['B. Forward linkages:', 'They link a firm with firms that use or sell its products. Cars go to dealers and garages.'], ['C. Horizontal and diagonal linkages:', 'Horizontal linkages join firms making parts for the same product. Diagonal linkages supply services like transport and cleaning to many firms.']] },
    { title: 'III. Reasons and Significance', items: [['A. Reasons:', 'Linked firms locate close together to cut transport costs and time. They share information and workers.'], ['B. Significance:', 'Linkages create the multiplier effect and growth. They explain why agglomerations form.'], ['C. Risks:', 'If one firm closes, linked firms suffer. Diverse linkages reduce this risk.']], draw: { img: 'linkages_big.png', caption: 'Copy the linkages.' } },
  ],
  evaluation: [['Distinguish backward and forward linkages with examples.', 'Backward: supplier of tyres to a car factory. Forward: car dealer.'], ['Explain the multiplier effect.', 'One new industry creates more jobs and income in linked activities.']],
  remediation: ['Links with suppliers are ______ linkages.', 'Links with customers are ______ linkages.', 'One activity creating others is the ______ effect.'], remediationAnswers: '1. backward 2. forward 3. multiplier',
  homework: 'Draw the linkages of a factory in your town.', homeworkTag: 'This prepares Lesson 21: Industrial Inertia.',
  bilingual: [['Linkage', 'Le lien'], ['Supplier', 'Le fournisseur'], ['Customer', 'Le client'], ['Multiplier effect', "L'effet multiplicateur"], ['Parts', 'Les pièces'], ['Service', 'Le service']],
});

L.push({ no: 21, title: 'Industrial Inertia', topic: I3, subtopic: 'Industrial Structure and Changes',
  notions: 'Industrial inertia, geographical momentum, sunk costs, skilled labour.', focus: 'Meaning, examples, reasons and implications of industrial inertia.',
  competence: 'Learners are able to explain why some industries stay where they are after their original advantages disappear.',
  objectives: ['Define industrial inertia.', 'Give examples.', 'Explain its reasons and implications.'],
  recall: ['Steel works were built on coalfields.', 'Coal in some areas has run out.'],
  situation: 'Sheffield in England still makes special steel although its coal and iron ore ran out long ago. The factory owners say moving would cost too much and they would lose their skilled workers.',
  sitQA: [['What is the problem in the situation?', 'An industry stays although its original advantages are gone.'], ['What is this called?', 'Industrial inertia.'], ['Why does it stay?', 'Moving is costly and skilled workers are there.']],
  justification: 'This lesson helps us to understand why industrial patterns change slowly.',
  activities: [
    { sec: 'I. MEANING', img: 'usa_steel.jpg', caption: 'A steel works.', q: 'What is industrial inertia?', a: 'The survival of an industry in a place after its original advantages have gone.', noProj: 'define inertia.' },
    { sec: 'II. EXAMPLES', img: 'iron_steel_big.png', caption: 'Changing location of steel.', q: 'Give one example of industrial inertia.', a: 'Special steel in Sheffield (England).', noProj: 'give other examples.' },
    { sec: 'III. REASONS', img: 'f2t_factory_workers.jpg', caption: 'Skilled workers.', q: 'Give two reasons for industrial inertia.', a: 'Skilled labour and the high cost of moving buildings and machines.', noProj: 'list reasons.' },
    { sec: 'III. REASONS', img: 'linkages_big.png', caption: 'Linkages.', q: 'How do linkages keep an industry in place?', a: 'Suppliers, customers and services are all nearby.', noProj: 'discuss linkages.' },
    { sec: 'IV. IMPLICATIONS', img: 'usa_carfactory.jpg', caption: 'A modern factory.', q: 'Give one advantage and one disadvantage of inertia.', a: 'Advantage: keeps jobs. Disadvantage: the firm may become uncompetitive.', noProj: 'discuss implications.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Industrial inertia:', 'It is the tendency of an industry to stay in a place after the original reasons for its location have gone.'], ['Sunk costs:', 'They are money already invested in buildings and machines that cannot be recovered.']] },
    { title: 'II. Examples and Reasons', items: [['A. Examples:', 'Special steel in Sheffield and cutlery industries remain after coal and ore ran out. Old textile towns keep some mills.'], ['B. Reasons:', 'Moving buildings and machines is very costly. Skilled workers, linkages and reputation keep firms in place.'], ['C. Government help:', 'Subsidies may keep industries to save jobs. Tradition and local pride also matter.']] },
    { title: 'III. Implications', items: [['A. Advantages:', 'Jobs and skills are kept, and the region avoids sudden decline. Infrastructure keeps being used.'], ['B. Disadvantages:', 'Firms may pay higher costs and lose competitiveness. In the end many close anyway.']] },
  ],
  evaluation: [['Define industrial inertia and give an example.', 'An industry staying after its location advantages have gone; Sheffield steel.'], ['Give two reasons for industrial inertia.', 'High cost of moving and skilled labour (also linkages, reputation).']],
  remediation: ['An industry staying after its advantages go shows ______.', 'Money already invested is ______ costs.', 'Sheffield is known for ______.'], remediationAnswers: '1. inertia 2. sunk 3. steel',
  homework: 'Find an old industry in Cameroon that stayed in its place and explain why.', homeworkTag: 'This prepares Lesson 22: New Trends in Manufacturing.',
  bilingual: [['Inertia', "L'inertie"], ['Skilled labour', 'La main-d\'œuvre qualifiée'], ['Cost', 'Le coût'], ['Tradition', 'La tradition'], ['Competitive', 'Compétitif'], ['Closure', 'La fermeture']],
});

L.push({ no: 22, title: 'New Trends in Manufacturing', topic: I3, subtopic: 'Industrial Structure and Changes',
  notions: 'High-technology industry, multinational corporation, deindustrialisation, reindustrialisation, science park.', focus: 'High-tech industries, multinationals, deindustrialisation and reindustrialisation: meaning, causes and consequences (briefly).',
  competence: 'Learners are able to explain recent changes in manufacturing.',
  objectives: ['Explain high-technology industries.', 'Explain multinational corporations.', 'Explain deindustrialisation and reindustrialisation.'],
  recall: ['Manufacturing moved to Asia.', 'Old industrial regions lost jobs.'],
  situation: 'The phone in a learner\'s pocket was designed in the USA, assembled in China by a company with factories in many countries, and sold in Cameroon. Meanwhile, old factories in Europe have closed.',
  sitQA: [['What is the problem in the situation?', 'Manufacturing has become global and high-tech.'], ['What is a company with factories in many countries?', 'A multinational corporation.'], ['What is the closing of old factories called?', 'Deindustrialisation.']],
  justification: 'This lesson helps us to understand the modern world of industry.',
  activities: [
    { sec: 'I. HIGH-TECH INDUSTRY', img: 'usa_techpark.jpg', caption: 'Skilled workers in a high-tech firm.', q: 'Give two characteristics of high-tech industries.', a: 'Research and skilled workers; footloose, often in science parks.', noProj: 'list high-tech products.' },
    { sec: 'II. MULTINATIONALS', img: 'usa_container.jpg', caption: 'Containers carrying goods worldwide.', q: 'Give one advantage and one disadvantage of multinationals for LEDCs.', a: 'Advantage: jobs and investment. Disadvantage: profits leave the country.', noProj: 'name multinationals in Cameroon.' },
    { sec: 'III. DEINDUSTRIALISATION', img: 'deindust_big.png', caption: 'Manufacturing jobs in the UK (approximate).', q: 'What is deindustrialisation?', a: 'The decline of manufacturing in a country or region.', noProj: 'read the graph.' },
    { sec: 'III. DEINDUSTRIALISATION', img: 'usa_textile.jpg', caption: 'Textile workers in Asia.', q: 'Give two causes of deindustrialisation in MEDCs.', a: 'Competition from cheap-labour countries and automation.', noProj: 'list causes.' },
    { sec: 'IV. REINDUSTRIALISATION', img: 'usa_carfactory.jpg', caption: 'A robotic car factory.', q: 'What is reindustrialisation?', a: 'The growth of new industries in old industrial regions.', noProj: 'give examples.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['High-technology industry:', 'It is industry based on advanced research, like electronics and biotechnology.'], ['Multinational corporation (MNC):', 'It is a company with factories or offices in several countries.'], ['Deindustrialisation:', 'It is the decline of manufacturing industry.']] },
    { title: 'II. High-Tech Industries and MNCs', items: [['A. High-tech industries:', 'They need research, skilled workers and universities. They cluster in science parks like Silicon Valley.'], ['B. MNCs:', 'They locate factories where costs are lowest and markets are large. Examples are Samsung, Nestlé and Total.'], ['C. Effects of MNCs:', 'They bring jobs, investment and technology. But profits often leave, and they may exploit workers and the environment.']] },
    { title: 'III. Deindustrialisation and Reindustrialisation', items: [['A. Deindustrialisation:', 'Old industries closed in MEDCs because of competition, automation and exhaustion of resources. It caused unemployment and derelict land.'], ['B. Reindustrialisation:', 'New industries, often high-tech and services, replace old ones. Governments help with grants and enterprise zones.']] },
  ],
  evaluation: [['Define a multinational corporation and give one advantage and one disadvantage.', 'A company in several countries; brings jobs but profits leave.'], ['Give two causes of deindustrialisation.', 'Competition from cheap-labour countries and automation.']],
  remediation: ['A company in many countries is a ______.', 'The decline of manufacturing is ______.', 'High-tech firms cluster in science ______.'], remediationAnswers: '1. multinational 2. deindustrialisation 3. parks',
  homework: 'Name three multinationals present in Cameroon and their products.', homeworkTag: 'This prepares Lesson 23: Weber\'s Least-Cost Model.',
  bilingual: [['Multinational', 'La multinationale'], ['High technology', 'La haute technologie'], ['Deindustrialisation', 'La désindustrialisation'], ['Science park', 'Le technopôle'], ['Automation', "L'automatisation"], ['Investment', "L'investissement"]],
});

L.push({ no: 23, title: 'Weber\'s Least-Cost Model', topic: I4, subtopic: 'Theories of Industrial Location',
  notions: 'Weber, least-cost location, material index, locational triangle, isodapane, labour, agglomeration.', focus: 'Aim and assumptions; the material index; location factors (transport, labour, agglomeration); applicability and criticisms.',
  competence: 'Learners are able to explain Weber\'s model and assess it.',
  objectives: ['State the aim and assumptions of Weber\'s model.', 'Explain the material index and the location triangle.', 'Explain labour and agglomeration and assess the model.'],
  recall: ['Transport costs affect location.', 'Some materials lose weight when processed.'],
  situation: 'A sugar mill is built next to the cane fields at Mbandjock, while a soft drink factory is built in Douala. A learner asks if there is a rule for choosing the cheapest location.',
  sitQA: [['What is the problem in the situation?', 'Industries choose different least-cost locations.'], ['Why is the sugar mill near the cane?', 'Cane is heavy and loses weight when processed.'], ['Which model explains this?', 'Weber\'s least-cost model.']],
  justification: 'This lesson helps us to understand a classic theory of industrial location.',
  activities: [
    { sec: 'I. ASSUMPTIONS', img: 'f2t_savanna.jpg', caption: 'A flat plain.', q: 'Give two assumptions of Weber\'s model.', a: 'Uniform plain; transport cost depends on weight and distance (also fixed markets and materials).', noProj: 'list assumptions.' },
    { sec: 'II. LOCATION TRIANGLE', img: 'weber_big.png', caption: 'Weber\'s location triangle.', q: 'Where is the least-cost location?', a: 'Where total transport cost of materials and product is lowest.', noProj: 'draw the triangle.' },
    { sec: 'II. MATERIAL INDEX', img: 'mi_table_big.png', caption: 'Material index examples.', q: 'A sugar mill uses 8 t of cane to make 1 t of sugar. Where should it be?', a: 'MI = 8 > 1, so near the cane fields.', noProj: 'calculate MI.' },
    { sec: 'III. LABOUR', img: 'isodapanes_big.png', caption: 'Isodapanes and cheap labour.', q: 'When will a firm move to a cheap-labour town?', a: 'When labour savings are greater than extra transport costs.', noProj: 'explain the critical isodapane.' },
    { sec: 'IV. CRITICISMS', img: 'usa_techpark.jpg', caption: 'Skilled workers in a modern firm.', q: 'Give two criticisms of Weber\'s model.', a: 'Transport costs are less important today; it ignores demand and government.', noProj: 'list criticisms.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Least-cost location:', 'It is the place where total production and transport costs are lowest.'], ['Material index (MI):', 'It is the weight of localised materials divided by the weight of the product.'], ['Isodapane:', 'It is a line joining places with equal extra transport cost.']] },
    { title: 'II. The Model (1909)', items: [['A. Aim and assumptions:', 'Weber sought the least-cost location for a factory. He assumed a uniform plain, fixed markets and materials, and transport cost rising with weight and distance.'], ['B. Material index:', 'If MI > 1, the factory locates near raw materials. If MI < 1, it locates near the market.'], ['C. Labour and agglomeration:', 'A firm moves to cheap labour if savings exceed extra transport cost (critical isodapane). Agglomeration savings can also pull firms together.']] },
    { title: 'III. Applicability and Criticisms', items: [['A. Applicability:', 'It explains heavy industries like sugar, cement and steel. The material index is still useful.'], ['B. Criticisms:', 'Transport costs are lower today and not proportional to distance. It ignores demand, government and human choice.']], draw: { img: 'weber_big.png', caption: 'Copy the triangle and MI rule.' } },
  ],
  evaluation: [['What does MI > 1 mean?', 'The materials lose weight, so the factory locates near raw materials.'], ['Give two criticisms of Weber\'s model.', 'It overstates transport cost; it ignores demand and government.']],
  remediation: ['MI < 1 means locate near the ______.', 'A line of equal extra transport cost is an ______.', 'Weber sought the ______-cost location.'], remediationAnswers: '1. market 2. isodapane 3. least',
  homework: 'Calculate the MI of two industries and state their best location.', homeworkTag: 'This prepares Practical Work 3: Material Index and Isodapanes.',
  bilingual: [['Least cost', 'Le moindre coût'], ['Material index', "L'indice matière"], ['Triangle', 'Le triangle'], ['Weight', 'Le poids'], ['Isodapane', "L'isodapane"], ['Labour cost', 'Le coût de la main-d\'œuvre']],
});

L.push({ kind: 'Practical Work', no: 3, title: 'Material Index, Location Triangles and Isodapanes', topic: I4, subtopic: 'Theories of Industrial Location',
  notions: 'Material index, location triangle, ton-kilometres, isodapane, critical isodapane.', focus: 'Calculation of material index and location types; location triangles; plotting and interpreting isodapanes and least labour cost location.',
  competence: 'Learners are able to calculate the material index and use isodapanes.',
  objectives: ['Calculate the material index.', 'Find the least transport cost point in a triangle.', 'Interpret isodapanes for a labour location.'],
  recall: ['MI = materials ÷ product.', 'Isodapanes join equal extra transport costs.'],
  situation: 'An investor wants to build a cement factory. It needs 1.6 t of limestone and 0.2 t of gypsum for each tonne of cement. The class must advise where to build.',
  sitQA: [['What is the problem in the situation?', 'The class must find the best factory location.'], ['What must they calculate first?', 'The material index.'], ['What is MI here?', '(1.6 + 0.2) ÷ 1 = 1.8, so near the limestone.']],
  justification: 'This practical work helps us to apply Weber\'s model with numbers.',
  activities: [
    { sec: 'I. MATERIAL INDEX', img: 'mi_table_big.png', caption: 'Material index of several industries.', q: 'Why is brewing market-oriented?', a: 'MI = 0.2: water is added at the market, so the product gains weight.', noProj: 'calculate MI for each.' },
    { sec: 'II. TON-KILOMETRES', img: 'weber_big.png', caption: 'A location triangle.', q: 'A site is 20 km from 2 t of ore and 10 km from a market for 1 t of product. Find the ton-km.', a: '2 × 20 + 1 × 10 = 50 ton-km.', noProj: 'compare several sites.' },
    { sec: 'III. ISODAPANES', img: 'isodapanes_big.png', caption: 'Isodapanes.', q: 'The labour town saves 25 per tonne and lies between the +20 and +30 isodapanes. Should the firm move?', a: 'Only if the extra cost there is below 25; between +20 and +30 it depends on the exact position.', noProj: 'discuss the critical isodapane.' },
    { sec: 'IV. APPLICATION', img: 'lsa_bauxite.jpg', caption: 'A bauxite mine.', q: 'Aluminium: 4 t of bauxite give 1 t of metal. Where should the refinery be?', a: 'MI = 4, so near the bauxite (if power is available).', noProj: 'discuss Minim-Martap.' },
    { sec: 'V. INTERPRETATION', img: 'location_factors_big.png', caption: 'Location factors.', q: 'Why may real factories not follow the calculation?', a: 'Power, labour, government and markets also matter.', noProj: 'discuss limits.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Ton-kilometre:', 'It is the cost unit of moving one tonne over one kilometre.'], ['Critical isodapane:', 'It is the isodapane where extra transport cost equals labour savings.']] },
    { title: 'II. Method', items: [['A. Material index:', 'MI = total weight of localised materials ÷ weight of product. MI > 1 gives a material location, and MI < 1 a market location.'], ['B. Location triangle:', 'Calculate ton-kilometres from each site to materials and market. The site with the lowest total is the least-cost point.'], ['C. Isodapanes:', 'Draw lines of equal extra cost around the least-cost point. Compare with the labour saving to find the critical isodapane.']] },
    { title: 'III. Interpretation', items: [['A. Results:', 'Weight-losing industries locate near materials, and weight-gaining ones near markets. Cheap labour inside the critical isodapane attracts the firm.'], ['B. Limits:', 'Real costs are not linear and other factors intervene. The method gives only a guide.']] },
  ],
  evaluation: [['Cement uses 1.6 t limestone and 0.2 t gypsum per tonne. Find MI and the location.', 'MI = 1.8, near the limestone.'], ['When does a firm move to a cheap-labour site?', 'When the site is inside the critical isodapane (savings > extra costs).']],
  remediation: ['MI = materials ÷ ______.', 'Moving 1 t over 1 km is one ______.', 'Savings equal to extra cost define the ______ isodapane.'], remediationAnswers: '1. product 2. ton-kilometre 3. critical',
  homework: 'Calculate ton-kilometres for three sites and choose the least-cost site.', homeworkTag: 'This prepares Lesson 24: Other Theories of Industrial Location.',
  bilingual: [['Calculation', 'Le calcul'], ['Site', 'Le site'], ['Limestone', 'Le calcaire'], ['Cement', 'Le ciment'], ['Saving', "L'économie"], ['Isodapane', "L'isodapane"]],
});

L.push({ no: 24, title: 'Other Theories of Industrial Location: Lösch and Smith', topic: I4, subtopic: 'Theories of Industrial Location',
  notions: 'Lösch, market area, maximum revenue, D. M. Smith, space-cost curve, spatial margins of profitability.', focus: 'Lösch\'s market area theory; D. M. Smith\'s space-cost theory.',
  competence: 'Learners are able to explain and compare Lösch\'s and Smith\'s theories.',
  objectives: ['Explain Lösch\'s market area theory.', 'Explain Smith\'s spatial margins of profitability.', 'Compare them with Weber.'],
  recall: ['Weber sought the least-cost location.', 'Christaller used hexagons.'],
  situation: 'Two bakeries sell bread in a town. One is in the centre where many customers pass; the other on the edge where rent is cheap. Both make a profit. A learner asks if there is only one best location.',
  sitQA: [['What is the problem in the situation?', 'Firms can make profit in several places.'], ['Which theory says profit is possible in a zone?', 'Smith\'s spatial margins of profitability.'], ['Which theory focuses on sales?', 'Lösch\'s market area theory.']],
  justification: 'This lesson helps us to see industrial location from the side of demand and profit.',
  activities: [
    { sec: 'I. LÖSCH', img: 'losch_big.png', caption: 'Lösch\'s market areas.', q: 'What did Lösch seek?', a: 'The location of maximum revenue (largest market).', noProj: 'draw the hexagons.' },
    { sec: 'I. LÖSCH', img: 'christaller_big.png', caption: 'Hexagonal market areas.', q: 'Why are Lösch\'s market areas hexagons?', a: 'Demand falls with distance and hexagons cover space with no gaps.', noProj: 'compare with Christaller.' },
    { sec: 'II. SMITH', img: 'smith_big.png', caption: 'Spatial margins of profitability.', q: 'What are the spatial margins of profitability?', a: 'The limits of the area where revenue is greater than cost.', noProj: 'draw the curves.' },
    { sec: 'II. SMITH', img: 'usa_techpark.jpg', caption: 'A modern firm.', q: 'Why does Smith\'s theory explain sub-optimal locations?', a: 'A firm can make profit anywhere inside the margins, not only at the best point.', noProj: 'discuss choices.' },
    { sec: 'III. COMPARISON', img: 'weber_big.png', caption: 'Weber\'s triangle.', q: 'Compare Weber, Lösch and Smith.', a: 'Weber: least cost. Lösch: maximum revenue. Smith: profit zone between margins.', noProj: 'make a table.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Market area:', 'It is the area from which a firm draws its customers.'], ['Spatial margin of profitability:', 'It is the limit beyond which a firm cannot make a profit.']] },
    { title: 'II. The Theories', items: [['A. Lösch (1940):', 'He argued that firms seek maximum revenue, not only least cost. Demand falls with distance, so market areas become hexagons.'], ['B. D. M. Smith (1966):', 'He drew space-cost and space-revenue curves. Profit is possible anywhere between the spatial margins.'], ['C. Consequences:', 'Firms can choose among many profitable sites. Personal choice and government can guide the choice.']] },
    { title: 'III. Comparison and Criticisms', items: [['A. Comparison:', 'Weber focused on costs, Lösch on revenue and Smith on both. Smith\'s model is the most realistic.'], ['B. Criticisms:', 'Lösch\'s model is abstract and hard to test. Smith\'s curves are difficult to measure in practice.']], draw: { img: 'smith_big.png', caption: 'Copy the spatial margins.' } },
  ],
  evaluation: [['Compare the approaches of Weber and Lösch.', 'Weber: least cost. Lösch: maximum revenue.'], ['Explain Smith\'s spatial margins of profitability.', 'The limits of the zone where revenue exceeds cost; profit is possible anywhere inside.']],
  remediation: ['Lösch sought maximum ______.', 'Smith\'s profit zone lies between the spatial ______.', 'Weber sought least ______.'], remediationAnswers: '1. revenue 2. margins 3. cost',
  homework: 'Make a table comparing Weber, Lösch and Smith.', homeworkTag: 'This prepares Lesson 25: Sub-optimal Industrial Location.',
  bilingual: [['Revenue', 'Le revenu (recette)'], ['Profit', 'Le profit'], ['Margin', 'La marge'], ['Demand', 'La demande'], ['Market area', 'La zone de marché'], ['Theory', 'La théorie']],
});

L.push({ no: 25, title: 'Sub-optimal Industrial Location', topic: I4, subtopic: 'Theories of Industrial Location',
  notions: 'Sub-optimal location, satisficer, behavioural approach, imperfect information.', focus: 'Meaning and reasons of sub-optimal location.',
  competence: 'Learners are able to explain why many factories are not in the best possible location.',
  objectives: ['Define sub-optimal location.', 'Explain the reasons for sub-optimal locations.', 'Give examples.'],
  recall: ['Smith\'s model allows profit in a zone.', 'Human choice affects location.'],
  situation: 'A businessman from Bafoussam built his factory in his home town although Douala would have been cheaper for transport and markets. His factory still makes a small profit.',
  sitQA: [['What is the problem in the situation?', 'The factory is not in the best location.'], ['What is such a location called?', 'Sub-optimal.'], ['Why did he choose it?', 'Personal preference (home town) and the profit is enough.']],
  justification: 'This lesson helps us to understand real decisions behind factory locations.',
  activities: [
    { sec: 'I. MEANING', img: 'smith_big.png', caption: 'The zone of profit.', q: 'What is a sub-optimal location?', a: 'A location that gives some profit but not the maximum.', noProj: 'point inside the margins.' },
    { sec: 'II. REASONS', img: 'f2t_factory_workers.jpg', caption: 'Workers in a local factory.', q: 'Give two reasons for sub-optimal location.', a: 'Personal preference and lack of information (also inertia, government).', noProj: 'list reasons.' },
    { sec: 'II. REASONS', img: 'f2t_phone_farmer.jpg', caption: 'Information on a phone.', q: 'How does imperfect information lead to sub-optimal choices?', a: 'Owners do not know all costs and sites, so they choose what they know.', noProj: 'discuss information.' },
    { sec: 'III. GOVERNMENT', img: 'usa_newtown.jpg', caption: 'A planned area.', q: 'How can government cause sub-optimal locations?', a: 'It may force or pay firms to locate in poorer regions.', noProj: 'discuss incentives.' },
    { sec: 'IV. EXAMPLES', img: 'usa_steel.jpg', caption: 'An old steel works.', q: 'How is industrial inertia a cause of sub-optimal location?', a: 'Firms stay in old places that are no longer the best.', noProj: 'link to inertia.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Sub-optimal location:', 'It is a location that makes a profit but not the highest possible profit.'], ['Satisficer:', 'It is a decision-maker who is happy with a good enough result.']] },
    { title: 'II. Reasons', items: [['A. Human behaviour:', 'Owners are satisficers, not perfect optimisers. They prefer their home town or a pleasant place.'], ['B. Imperfect information:', 'Managers do not know all costs and markets. Decisions are made quickly with limited data.'], ['C. Other reasons:', 'Industrial inertia, government policy and changing conditions make old choices sub-optimal. Smith\'s margins allow this.']] },
    { title: 'III. Implications', items: [['A. Results:', 'Many factories are not at the least-cost point but still survive. Regions gain jobs they might not get otherwise.'], ['B. Risks:', 'Sub-optimal firms may close when competition increases. Government help may be needed.']] },
  ],
  evaluation: [['Define sub-optimal location.', 'A location that makes a profit but not the maximum.'], ['Give three reasons for sub-optimal location.', 'Personal choice, imperfect information, government policy (also inertia).']],
  remediation: ['A location with less than maximum profit is ______.', 'A person happy with good enough results is a ______.', 'Staying in an old place is industrial ______.'], remediationAnswers: '1. sub-optimal 2. satisficer 3. inertia',
  homework: 'Find a business in your town that is not in the best location and explain why.', homeworkTag: 'This prepares Lesson 26: Impacts of Manufacturing on the Environment.',
  bilingual: [['Sub-optimal', 'Sous-optimal'], ['Decision', 'La décision'], ['Information', "L'information"], ['Preference', 'La préférence'], ['Behaviour', 'Le comportement'], ['Survival', 'La survie']],
});

L.push({ no: 26, title: 'Impacts of Manufacturing on the Environment', topic: 'Manufacturing Industries and the Environment', subtopic: 'Manufacturing Industries and the Environment',
  notions: 'Air pollution, water pollution, acid rain, industrial waste, environmental impact assessment, clean technology.', focus: 'Negative impacts of manufacturing on the environment and solutions.',
  competence: 'Learners are able to explain the environmental impacts of industry and propose solutions.',
  objectives: ['Explain the impacts of industry on air, water and land.', 'Give examples.', 'Propose solutions.'],
  recall: ['Factories produce waste.', 'Fossil fuels cause pollution.'],
  situation: 'People near an industrial zone in Douala complain of smoke, bad smells and dirty water in the drains. Fishermen say the fish have become rare in the estuary.',
  sitQA: [['What is the problem in the situation?', 'Industry pollutes the environment.'], ['Which parts of the environment are affected?', 'Air, water and aquatic life.'], ['Name one solution.', 'Treating waste before release.']],
  justification: 'This lesson helps us to balance industrial growth with a healthy environment.',
  activities: [
    { sec: 'I. AIR', img: 'ind_pollution_big.png', caption: 'Impacts of industry.', q: 'Give two effects of industry on the air.', a: 'Smoke and greenhouse gases (also acid rain).', noProj: 'copy the four boxes.' },
    { sec: 'I. AIR', img: 'usa_steel.jpg', caption: 'A steel works near a town.', q: 'What is acid rain?', a: 'Rain made acid by sulphur and nitrogen gases from factories.', noProj: 'explain acid rain.' },
    { sec: 'II. WATER', img: 'lsa_wouri.jpg', caption: 'The Wouri estuary.', q: 'How does industry pollute rivers and seas?', a: 'By releasing chemicals, oil and hot water.', noProj: 'discuss the Wouri.' },
    { sec: 'III. LAND', img: 'usa_openpit.jpg', caption: 'A mine scar.', q: 'Give two impacts of industry on land.', a: 'Waste dumps and mine scars (also loss of farmland).', noProj: 'list land impacts.' },
    { sec: 'IV. SOLUTIONS', img: 'f4_solar.jpg', caption: 'Clean energy.', q: 'Give three solutions to industrial pollution.', a: 'Filters and treatment plants, laws and fines, clean energy and recycling.', noProj: 'list solutions.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Industrial pollution:', 'It is harmful waste from factories that damages air, water or land.'], ['Acid rain:', 'It is rain made acid by sulphur and nitrogen gases.'], ['Environmental impact assessment:', 'It is a study of the effects of a project before it is built.']] },
    { title: 'II. Negative Impacts', items: [['A. Air:', 'Smoke, dust and gases cause breathing diseases and acid rain. Greenhouse gases cause climate change.'], ['B. Water:', 'Chemicals, oil and hot water kill fish and make water unsafe. Estuaries near industrial towns are affected.'], ['C. Land:', 'Waste dumps, mine scars and factories destroy farmland and forests. Noise and smells disturb residents.']] },
    { title: 'III. Solutions', items: [['A. Technology:', 'Filters, treatment plants and clean energy reduce pollution. Recycling reduces waste.'], ['B. Laws:', 'Environmental laws, fines and impact assessments control firms. The polluter must pay.'], ['C. Planning:', 'Industrial zones are placed away from homes. Green belts and tree planting absorb pollution.']] },
  ],
  evaluation: [['Give three negative impacts of industry on the environment.', 'Air pollution, water pollution, land degradation.'], ['Give three solutions to industrial pollution.', 'Filters, laws, recycling (also clean energy, zoning).']],
  remediation: ['Rain made acid by factory gases is ______ rain.', 'A study before a project is an environmental impact ______.', 'The principle "the polluter ______".'], remediationAnswers: '1. acid 2. assessment 3. pays',
  homework: 'Identify a source of pollution in your town and suggest a solution.', homeworkTag: 'This prepares Further Study 5: Industry in Cameroon.',
  bilingual: [['Pollution', 'La pollution'], ['Acid rain', 'Les pluies acides'], ['Waste', 'Les déchets'], ['Filter', 'Le filtre'], ['Law', 'La loi'], ['Impact', "L'impact"]],
});

L.push({ kind: 'Further Study', no: 5, title: 'Industrial Development and Change in Cameroon', topic: T6, subtopic: 'Manufacturing Industries of Cameroon',
  notions: 'Import substitution, light industry, industrial region, industrial zone, emergence.', focus: 'Characteristics of manufacturing; the four industrial regions and their industries; location and growth factors; reasons for low industrialisation; state efforts; socio-economic impacts.',
  competence: 'Learners are able to describe the industries of Cameroon and explain their distribution and problems.',
  objectives: ['Describe the characteristics of manufacturing in Cameroon.', 'Describe the four industrial regions and their factors.', 'Explain the low level of industrialisation, state efforts and impacts.'],
  recall: ['Most industries of Cameroon are in Douala.', 'ALUCAM, CICAM and SONARA are major industries.'],
  situation: 'Cameroon exports cocoa beans, logs and crude oil but imports chocolate, furniture and petrol. Most factories are in Douala; the East and the South have very few.',
  sitQA: [['What is the problem in the situation?', 'Cameroon exports raw materials and imports manufactured goods.'], ['Where are most factories?', 'In Douala (the coastal region).'], ['Why is industry weak?', 'Lack of capital, technology, energy and markets.']],
  justification: 'This further study helps us to understand the industries of Cameroon and how to develop them.',
  activities: [
    { sec: 'I. CHARACTERISTICS', img: 'usa_brewery.jpg', caption: 'A brewery.', q: 'Give two characteristics of industry in Cameroon.', a: 'Mostly light industries and import substitution (also based on local raw materials).', noProj: 'list factories.' },
    { sec: 'II. INDUSTRIAL REGIONS', img: 'cmr_industry_big.png', caption: 'The four industrial regions (simplified).', q: 'Name the four industrial regions and one industry in each.', a: 'Coastal (ALUCAM), Centre-South (breweries, wood), West (coffee, food), North (textiles, cement).', noProj: 'draw the map.' },
    { sec: 'II. FACTORS', img: 'usa_container.jpg', caption: 'A port.', q: 'Why is the coastal region the most industrialised?', a: 'The port, the largest market, power and banks are there.', noProj: 'discuss Douala.' },
    { sec: 'III. PROBLEMS', img: 'f2t_muddy_road.jpg', caption: 'A poor road.', q: 'Give three reasons for the low level of industrialisation.', a: 'Lack of capital, technology and energy (also small market, poor transport).', noProj: 'list problems.' },
    { sec: 'IV. STATE EFFORTS AND IMPACTS', img: 'usa_smelter.jpg', caption: 'An aluminium smelter.', q: 'Give two state efforts and two impacts of industry.', a: 'Efforts: industrial zones, investment charter. Impacts: jobs and pollution.', noProj: 'discuss Vision 2035.' },
  ],
  summary: [
    { title: 'I. Definitions', items: [['Import substitution:', 'It is making at home goods that were once imported.'], ['Industrial zone:', 'It is land set aside and equipped for factories.']] },
    { title: 'II. Characteristics and Regions', items: [['A. Characteristics:', 'Industry is small, mostly light and based on agricultural raw materials. Many firms replace imports, like drinks, soap and cement.'], ['B. Coastal and Centre-South regions:', 'Douala has most factories (food, drinks, chemicals), Edéa has ALUCAM and Limbe SONARA. Yaoundé and Mbalmayo have drinks, printing and wood industries.'], ['C. West and North:', 'Bafoussam and Bamenda process coffee and food. Garoua has CICAM textiles and Figuil cement.']] },
    { title: 'III. Problems, Efforts and Impacts', items: [['A. Low industrialisation:', 'Capital, technology, skilled labour and cheap energy are lacking. The market is small and transport is poor.'], ['B. State efforts:', 'The state creates industrial zones, dams (Lom Pangar, Memve\'ele) and the Kribi port. The investment charter gives incentives to investors.'], ['C. Impacts:', 'Industry creates jobs, taxes and urban growth. It also causes pollution and regional inequality.']], draw: { img: 'cmr_industry_big.png', caption: 'Copy the map.' } },
  ],
  evaluation: [['Name the four industrial regions of Cameroon with one industry each.', 'Coastal (ALUCAM), Centre-South (breweries), West (coffee), North (CICAM).'], ['Give three reasons for the low level of industrialisation.', 'Lack of capital, technology and energy.']],
  remediation: ['Making goods once imported is import ______.', 'CICAM is at ______.', 'Most factories are in ______.'], remediationAnswers: '1. substitution 2. Garoua 3. Douala',
  homework: 'Choose a raw material exported by Cameroon and suggest a factory to process it.', homeworkTag: 'This prepares Lesson 27: Transport.',
  bilingual: [['Industry', "L'industrie"], ['Import substitution', 'La substitution aux importations'], ['Industrial zone', 'La zone industrielle'], ['Textile', 'Le textile'], ['Refinery', 'La raffinerie'], ['Emergence', "L'émergence"]],
});

module.exports = { L, B };
if (require.main === module) run(L, B, process.argv.slice(2).length ? process.argv.slice(2) : null);
